function CombatCloud.RegisterMedia(LMP)
    LMP:Register(LMP.MediaType.FONT, 'Adventure',           [[CombatCloud/Media/Fonts/adventure.ttf]])
    LMP:Register(LMP.MediaType.FONT, 'Bazooka',             [[CombatCloud/Media/Fonts/bazooka.ttf]])
    LMP:Register(LMP.MediaType.FONT, 'Cooline',             [[CombatCloud/Media/Fonts/cooline.ttf]])
    LMP:Register(LMP.MediaType.FONT, 'Diogenes',            [[CombatCloud/Media/Fonts/diogenes.ttf]])
    LMP:Register(LMP.MediaType.FONT, 'Ginko',               [[CombatCloud/Media/Fonts/ginko.ttf]])
    LMP:Register(LMP.MediaType.FONT, 'Heroic',              [[CombatCloud/Media/Fonts/heroic.ttf]])
    LMP:Register(LMP.MediaType.FONT, 'Metamorphous',        [[CombatCloud/Media/Fonts/metamorphous.otf]])
    LMP:Register(LMP.MediaType.FONT, 'Porky',               [[CombatCloud/Media/Fonts/porky.ttf]])
    LMP:Register(LMP.MediaType.FONT, 'Roboto Bold',         [[CombatCloud/Media/Fonts/Roboto-Bold.ttf]])
    LMP:Register(LMP.MediaType.FONT, 'Roboto Bold Italic',  [[CombatCloud/Media/Fonts/Roboto-BoldItalic.ttf]])
    LMP:Register(LMP.MediaType.FONT, 'Talisman',            [[CombatCloud/Media/Fonts/talisman.ttf]])
    LMP:Register(LMP.MediaType.FONT, 'Transformers',        [[CombatCloud/Media/Fonts/transformers.ttf]])
    LMP:Register(LMP.MediaType.FONT, 'Yellowjacket',        [[CombatCloud/Media/Fonts/yellowjacket.ttf]])
end