SafeAddString(SI_BINDING_NAME_CAMERA_HORIZONTAL_INC, "Горизонтальное положение вправо", 1)
SafeAddString(SI_BINDING_NAME_CAMERA_HORIZONTAL_DEC, "Горизонтальное положение слева", 1)
SafeAddString(SI_BINDING_NAME_CAMERA_HORIZONTALOFFSET_INC, "Горизонтальное смещение вправо", 1)
SafeAddString(SI_BINDING_NAME_CAMERA_HORIZONTALOFFSET_DEC, "Горизонтальное смещение влево", 1)
SafeAddString(SI_BINDING_NAME_CAMERA_VERTICAL_INC, "Вертикальное смещение вверх", 1)
SafeAddString(SI_BINDING_NAME_CAMERA_VERTICAL_DEC, "Вертикальное смещение вниз", 1)
SafeAddString(SI_BINDING_NAME_CAMERA_RECENTER, "Центрировать камеру", 1)

SafeAddString(SI_BINDING_NAME_SAVE_QUICKSLOT_1, "Сохранить QuickSlot 1", 1)
SafeAddString(SI_BINDING_NAME_LOAD_QUICKSLOT_1, "Загрузить QuickSlot 1", 1)
SafeAddString(SI_BINDING_NAME_SAVE_QUICKSLOT_2, "Сохранить QuickSlot 2", 1)
SafeAddString(SI_BINDING_NAME_LOAD_QUICKSLOT_2, "Загрузить QuickSlot 2", 1)
SafeAddString(SI_BINDING_NAME_SAVE_QUICKSLOT_3, "Сохранить QuickSlot 3", 1)
SafeAddString(SI_BINDING_NAME_LOAD_QUICKSLOT_3, "Загрузить QuickSlot 3", 1)
