
TiradilL10n = {}

local STRINGS = {
    en = {
        ROSTER_TITLE = "Guild Roster",
        TAB_APPROVED = "Approved",
        TAB_INVITED = "Invited",
        TAB_JOINED = "Joined",
        TAB_REJECTED = "Rejected",
        TAB_KICKED = "Kicked",
        TAB_LEFT = "Left",
        TAB_PROMOTED = "Promoted",
        TAB_DEMOTED = "Demoted",
        FILTER_ALL = "All",
        FILTER_THIS_WEEK = "This Week",
        FILTER_7_DAYS = "7 Days",
        FILTER_30_DAYS = "30 Days",
        OFFICER_STATS = "Officer Stats",
        SEARCH_LABEL = "Search:",
        COL_TIME = "Time",
        COL_GUILD = "Guild",
        COL_OFFICER = "Officer",
        COL_MEMBER = "Member",

        LEDGER_TITLE = "GUILD LEDGER & ACCOUNTING SYSTEM",
        ROW_BANK_GOLD = "Bank Gold",
        BANK_GOLD_LAST_SEEN = "last seen",
        BANK_GOLD_UNAVAILABLE = "N/A (open your guild bank once this session to enable)",
        ROW_SALES_VOLUME = "Store Sales Volume",
        ROW_TAX_REVENUE = "Guild Tax Revenue",
        ROW_DEPOSITS = "Member Deposits",
        ROW_WITHDRAWALS = "Withdrawn From Bank",
        ROW_TRADER_EXPENSE = "Trader Rent & Bid Expense",
        ROW_CURRENT_TRADER = "Current Trader",
        ROW_CURRENT_BIDS = "Current Trader Bids",
        ROW_AVAILABLE_FUNDS = "Available Guild Funds",
        NET_PROFIT_LABEL = "PROFIT",
        NET_LOSS_LABEL = "LOSS",
        ROW_NET_PROFIT = "NET PROFIT / LOSS",
        PANEL_DONORS_SELLERS = "TOP DONORS & SELLERS (this period)",
        PANEL_DONORS_SELLERS_BASE = "TOP DONORS & SELLERS",
        PANEL_DONORS = "DONORS",
        PANEL_SELLERS = "TOP SELLERS",
        PANEL_BIDS = "THIS PERIOD'S BIDS (up to 10)",
        PANEL_BIDS_BASE = "BIDS (up to 10)",
        PANEL_KIOSKS = "TRADER HISTORY (ALL GUILDS)",
        PANEL_RANKS = "MEMBER RANKS (this guild, this period)",
        PANEL_RANKS_BASE = "MEMBER RANKS",
        BTN_REFRESH = "Refresh",
        BTN_KIOSKS = "Kiosks",
        BTN_RANKS = "Ranks",
        BTN_CLEAR_FILTER = "Clear Filter",
        BTN_MEMBER_SEARCH = "Search",
        SEARCH_PANEL_TITLE = "MEMBER LOOKUP",
        SEARCH_PANEL_HINT = "Type a member name to search their donations, sales and purchases in the selected guild/period.",
        LEDGER_NOTE_PREFIX = "Note:",
        EDIT_NOTE_TITLE = "PERSONAL NOTE (TGA)",
        EDIT_NOTE_SUBTITLE = "For <<1>> - only visible to you, never sent to the server.",
        EDIT_NOTE_XML_OUTDATED = "GuildLedger.xml appears to be an outdated version - the \"Edit Note\" window was not found. Please update all addon files (especially the .xml files).",
        SEARCH_PANEL_NONE = "No matching activity for this guild/period.",
        LEDGER_LABEL_DONATIONS = "Donations",
        LEDGER_LABEL_SALES = "Sales",
        LEDGER_LABEL_PURCHASES = "Purchases",
        SEARCH_FILTER_ACTIVE = "Filtered",
        STATUS_PROCESSING = "Processing data...",
        STATUS_NO_VALID_GUILD = "No valid guild selected.",
        RANKS_SUBTITLE = "Members meeting requirements in the selected period (they may already hold these ranks)",
        RANKS_NONE_QUALIFY = "No members meet any rank threshold this period. Adjust thresholds in Rank Settings if needed.",
        KIOSKS_NONE_YET = "No trader activity recorded yet (or LibHistoire is still syncing).",
        KIOSK_CURRENT_TAG = "CURRENT",
        DONORS_NONE = "No donations in this period.",
        SELLERS_NONE = "No sales in this period.",
        BIDS_NONE = "No bids placed in this period.",
        CONFIRMED_EXPENSES_TITLE = "CONFIRMED TRADER EXPENSES (this period)",
        CONFIRMED_EXPENSES_NONE = "None confirmed yet.",
        CHAT_LIBHISTOIRE_MISSING = "LibHistoire not found. Please install LibHistoire first.",
        CHAT_TRACKING_STARTED = "Financial data tracking started (<<1>> guild(s)).",
        DONATION_ANNOUNCE_FORMAT = "<<1>> donated <<2>> to <<3>>",
        ROSTER_STATS_NO_DATA = "No data for the current filters yet.",
        ROSTER_STATS_TITLE = "Officer Activity Summary (respects Guild/Date/Search filters above)",
        PERIOD_THIS_WEEK = "This Week",
        PERIOD_LAST_WEEK = "Last Week",
        PERIOD_2_WEEKS_AGO = "2 Weeks Ago",
        PERIOD_3_WEEKS_AGO = "3 Weeks Ago",
        PERIOD_4_WEEKS_AGO = "4 Weeks Ago",
        PERIOD_LAST_MONTH = "Last Month",
        PERIOD_THIS_MONTH = "This Month",
        PERIOD_LAST_30_DAYS = "Last 30 Days",
        PERIOD_ALL_TIME = "All Time (Total)",

        SUITE_TITLE = "Tiradil's Guild Assistant",
        BTN_GUILD_ROSTER = "Guild Roster",
        BTN_GUILD_LEDGER = "Guild Ledger",

        LANG_EN = "EN",
        LANG_TR = "TR",
        LANG_DE = "DE",
        LANG_ES = "ES",
        LANG_PL = "PL",
        LANG_RU = "RU",
        LANG_IT = "IT",
        LANG_PT = "PT",

        LAM_RANK_DESCRIPTION = "A member qualifies for a tier if they meet EITHER the sales OR the donation threshold in the selected period (This Week / Last Month / etc. - set in the Guild Ledger window). Thresholds are set SEPARATELY per guild - pick a guild below first.",
        LAM_HEADER_DISPLAY = "Display",
        LAM_LANGUAGE_NAME = "Language",
        LAM_LANGUAGE_TOOLTIP = "Changes the language of Tiradil's Guild Assistant (main titles, tabs, columns, buttons, status messages, and settings panel).",
        LAM_HEADER_ROSTER_INTEGRATION = "Guild Roster Integration",
        LAM_SHOW_CONTRIB_COLUMN_NAME = "Show Contribution Column in Guild Roster",
        LAM_SHOW_CONTRIB_COLUMN_TOOLTIP = "Toggles the donation/sale/purchase column that Tiradil adds to the in-game Guild Roster screen. Turning this off does not delete any data - it only hides the column.",
        LAM_SHOW_RANK_COLUMN_NAME = "Show Rank Column in Guild Roster",
        LAM_SHOW_RANK_COLUMN_TOOLTIP = "Toggles the Legend/Diamond/Gold/Silver/Bronze rank tag that Tiradil adds next to member names on the in-game Guild Roster screen. Has its own period selector (below the column header), independent from the Ledger window's period and from the Contribution column's period.",
        LAM_HEADER_RANK_THRESHOLDS = "Rank Thresholds",
        LAM_GUILD_NAME = "Guild",
        LAM_GUILD_TOOLTIP = "Which guild's rank thresholds you are editing below.",
        LAM_KICK_THRESHOLD_NAME = "Kick Eligibility Threshold (days)",
        LAM_KICK_THRESHOLD_TOOLTIP = "How many days of guild membership AND inactivity (no login) are required before a member can appear on the Kick List, in addition to having zero contributions ever. Set separately per guild.",
        LAM_TIER_NAME_NAME = "Rank Name",
        LAM_TIER_NAME_TOOLTIP = "Rename this rank tier to match your guild's own naming (e.g. \"VIP\", \"Elite\", \"Trusted\") instead of the default.",
        LAM_SALES_THRESHOLD_NAME = "Sales Threshold",
        LAM_SALES_THRESHOLD_TOOLTIP = "Total store sales (gold) needed in the period to qualify for ",
        LAM_DONATION_THRESHOLD_NAME = "Donation Threshold",
        LAM_DONATION_THRESHOLD_TOOLTIP = "Total donations (gold) needed in the period to qualify for ",
        LAM_LEGEND_MODE_NAME = "Legend Assignment Mode",
        LAM_LEGEND_MODE_TOOLTIP = "How members earn the Legend rank: a fixed threshold, or automatically as the top contributors of the currently selected period.",
        LAM_LEGEND_MODE_THRESHOLD = "Threshold (Sales/Donation)",
        LAM_LEGEND_MODE_TOP3 = "Top N Sellers & Donors",
        LAM_LEGEND_TOP3_DESC = "In Top N mode, Legend is always the top sellers and top donors of whichever period is currently selected (This Week, Last Month, etc.) - even if their totals are below the Gold threshold. How many of each (default 3/3) can be set below. The Sales/Donation Threshold fields further below are ignored while this mode is active.",
        LAM_LEGEND_TOP_SELLERS_COUNT_NAME = "Top Sellers Count",
        LAM_LEGEND_TOP_SELLERS_COUNT_TOOLTIP = "How many top sellers of the selected period become Legend (Top N mode only).",
        LAM_LEGEND_TOP_DONORS_COUNT_NAME = "Top Donors Count",
        LAM_LEGEND_TOP_DONORS_COUNT_TOOLTIP = "How many top donors of the selected period become Legend (Top N mode only).",
        LAM_HEADER_NOTIFICATIONS = "Notifications",
        LAM_SCREEN_NOTIF_NAME = "Show Center-Screen Announcement on New Donations",
        LAM_SCREEN_NOTIF_TOOLTIP = "When a member makes a new donation, shows a brief announcement in the center of your screen (same style as quest/item discovery messages). Only fires for donations made after you log in - does not replay history.",
        LAM_HEADER_MAIL_TEMPLATE = "Mail Template",
        LAM_MAIL_TEMPLATE_DESC = "Set up a mail template for the guild selected above. Use '@' to insert the recipient's name, or '@@' for their full @UserID. Send it from the Guild Roster right-click menu (Send Mail) - the mail form opens pre-filled, you press Send yourself.",
        LAM_MAIL_SUBJECT_NAME = "Subject",
        LAM_MAIL_SUBJECT_TOOLTIP = "Mail subject line. '@' becomes the recipient's name.",
        LAM_MAIL_BODY_NAME = "Body",
        LAM_MAIL_BODY_TOOLTIP = "Mail body text. '@' becomes the recipient's name.",
    },

    tr = {
        ROSTER_TITLE = "Lonca Listesi",
        TAB_APPROVED = "Onaylanan",
        TAB_INVITED = "Davet Edilen",
        TAB_JOINED = "Katilan",
        TAB_REJECTED = "Reddedilen",
        TAB_KICKED = "Kovulan",
        TAB_LEFT = "Ayrilan",
        TAB_PROMOTED = "Terfi Eden",
        TAB_DEMOTED = "Dusurulen",
        FILTER_ALL = "Tumu",
        FILTER_THIS_WEEK = "Bu Hafta",
        FILTER_7_DAYS = "7 Gun",
        FILTER_30_DAYS = "30 Gun",
        OFFICER_STATS = "Yetkili Istatistikleri",
        SEARCH_LABEL = "Ara:",
        COL_TIME = "Zaman",
        COL_GUILD = "Lonca",
        COL_OFFICER = "Yetkili",
        COL_MEMBER = "Uye",

        LEDGER_TITLE = "LONCA MUHASEBE SISTEMI",
        ROW_BANK_GOLD = "Kasa Altini",
        BANK_GOLD_LAST_SEEN = "en son",
        BANK_GOLD_UNAVAILABLE = "N/A (bu oturumda bir kez lonca bankasini acmaniz gerekiyor)",
        ROW_SALES_VOLUME = "Magaza Satis Hacmi",
        ROW_TAX_REVENUE = "Lonca Vergi Geliri",
        ROW_DEPOSITS = "Uye Bagislari",
        ROW_WITHDRAWALS = "Kasadan Cekilen",
        ROW_TRADER_EXPENSE = "Tuccar Kira & Ihale Harcamasi",
        ROW_CURRENT_TRADER = "Guncel Tuccar",
        ROW_CURRENT_BIDS = "Guncel Trader Bid'leri",
        ROW_AVAILABLE_FUNDS = "Kullanilabilir Lonca Varligi",
        NET_PROFIT_LABEL = "KAR",
        NET_LOSS_LABEL = "ZARAR",
        ROW_NET_PROFIT = "NET KAR / ZARAR",
        PANEL_DONORS_SELLERS = "EN IYI BAGISCILAR & SATICILAR (bu donem)",
        PANEL_DONORS_SELLERS_BASE = "EN IYI BAGISCILAR & SATICILAR",
        PANEL_DONORS = "BAGISCILAR",
        PANEL_SELLERS = "EN IYI SATICILAR",
        PANEL_BIDS = "BU DONEMIN IHALELERI (en fazla 10)",
        PANEL_BIDS_BASE = "IHALELER (en fazla 10)",
        PANEL_KIOSKS = "TUCCAR GECMISI (TUM LONCALAR)",
        PANEL_RANKS = "UYE RUTBELERI (bu lonca, bu donem)",
        PANEL_RANKS_BASE = "UYE RUTBELERI",
        BTN_REFRESH = "Yenile",
        BTN_KIOSKS = "Tezgahlar",
        BTN_RANKS = "Rutbeler",
        BTN_CLEAR_FILTER = "Filtreyi Temizle",
        BTN_MEMBER_SEARCH = "Ara",
        SEARCH_PANEL_TITLE = "UYE SORGULAMA",
        SEARCH_PANEL_HINT = "Secili guild/donem icinde bagis, satis ve satin alimlarini aramak icin bir uye adi yazin.",
        LEDGER_NOTE_PREFIX = "Not:",
        EDIT_NOTE_TITLE = "KISISEL NOT (TGA)",
        EDIT_NOTE_SUBTITLE = "<<1>> icin - sadece sen gorursun, sunucuya asla gonderilmez.",
        EDIT_NOTE_XML_OUTDATED = "GuildLedger.xml eski bir surumde gorunuyor - \"Notu Duzenle\" penceresi bulunamadi. Lutfen tum addon dosyalarini (ozellikle .xml dosyalarini) guncelleyin.",
        SEARCH_PANEL_NONE = "Bu guild/donem icin eslesen hareket yok.",
        LEDGER_LABEL_DONATIONS = "Bagis",
        LEDGER_LABEL_SALES = "Satis",
        LEDGER_LABEL_PURCHASES = "Satin Alim",
        SEARCH_FILTER_ACTIVE = "Filtrelendi",
        STATUS_PROCESSING = "Veri isleniyor...",
        STATUS_NO_VALID_GUILD = "Gecerli bir lonca secilmedi.",
        RANKS_SUBTITLE = "Secili donemde gereksinimleri karsilayan uyeler (bu rutbelere zaten sahip olabilirler)",
        RANKS_NONE_QUALIFY = "Bu donemde hicbir uye rutbe esigini karsilamiyor. Gerekirse Rutbe Ayarlari'ndan esikleri duzenleyin.",
        KIOSKS_NONE_YET = "Henuz tuccar hareketi kaydedilmedi (veya LibHistoire hala senkronize oluyor).",
        KIOSK_CURRENT_TAG = "SU AN",
        DONORS_NONE = "Bu donemde bagis yok.",
        SELLERS_NONE = "Bu donemde satis yok.",
        BIDS_NONE = "Bu donemde ihale yapilmadi.",
        CONFIRMED_EXPENSES_TITLE = "ONAYLANMIS TUCCAR HARCAMALARI (bu donem)",
        CONFIRMED_EXPENSES_NONE = "Henuz onaylanan yok.",
        CHAT_LIBHISTOIRE_MISSING = "LibHistoire bulunamadi. Lutfen once LibHistoire'i kurun.",
        CHAT_TRACKING_STARTED = "Finansal veri takibi baslatildi (<<1>> lonca).",
        DONATION_ANNOUNCE_FORMAT = "<<1>>, <<3>> loncasina <<2>> bagisladi",
        ROSTER_STATS_NO_DATA = "Mevcut filtreler icin henuz veri yok.",
        ROSTER_STATS_TITLE = "Yetkili Aktivite Ozeti (yukaridaki Lonca/Tarih/Arama filtrelerine gore)",
        PERIOD_THIS_WEEK = "Bu Hafta",
        PERIOD_LAST_WEEK = "Gecen Hafta",
        PERIOD_2_WEEKS_AGO = "2 Hafta Once",
        PERIOD_3_WEEKS_AGO = "3 Hafta Once",
        PERIOD_4_WEEKS_AGO = "4 Hafta Once",
        PERIOD_LAST_MONTH = "Gecen Ay",
        PERIOD_THIS_MONTH = "Bu Ay",
        PERIOD_LAST_30_DAYS = "Son 30 Gun",
        PERIOD_ALL_TIME = "Tum Zamanlar (Toplam)",

        SUITE_TITLE = "Tiradil's Guild Assistant",
        BTN_GUILD_ROSTER = "Lonca Listesi",
        BTN_GUILD_LEDGER = "Lonca Muhasebesi",

        LANG_EN = "EN",
        LANG_TR = "TR",
        LANG_DE = "DE",
        LANG_ES = "ES",
        LANG_PL = "PL",
        LANG_RU = "RU",
        LANG_IT = "IT",
        LANG_PT = "PT",

        LAM_RANK_DESCRIPTION = "Bir uye, secili donemde (Bu Hafta / Gecen Ay / vb. - Guild Ledger penceresinden ayarlanir) satis VEYA bagis esiklerinden BIRINI karsilarsa bir rutbeye hak kazanir. Esikler her guild icin AYRI AYRI ayarlanir - once asagidan bir guild secin.",
        LAM_HEADER_DISPLAY = "Gorunum",
        LAM_LANGUAGE_NAME = "Dil",
        LAM_LANGUAGE_TOOLTIP = "Tiradil's Guild Assistant'in dilini degistirir (ana basliklar, sekmeler, sutunlar, butonlar, durum mesajlari ve ayarlar paneli).",
        LAM_HEADER_ROSTER_INTEGRATION = "Guild Roster Entegrasyonu",
        LAM_SHOW_CONTRIB_COLUMN_NAME = "Guild Roster'da Katki Kolonunu Goster",
        LAM_SHOW_CONTRIB_COLUMN_TOOLTIP = "Tiradil'in oyun ici Guild Roster ekranina ekledigi bagis/satis/satin-alim kolonunu ac/kapat. Bunu kapatmak hicbir veriyi silmez - sadece kolonu gizler.",
        LAM_SHOW_RANK_COLUMN_NAME = "Guild Roster'da Rutbe Kolonunu Goster",
        LAM_SHOW_RANK_COLUMN_TOOLTIP = "Tiradil'in oyun ici Guild Roster ekraninda uye isimlerinin yanina ekledigi Legend/Diamond/Gold/Silver/Bronze rutbe etiketini ac/kapat. Kendi AYRI donem secicisine sahiptir (kolon basliginin altinda), hem Ledger penceresinden hem Katki kolonunun seciminden BAGIMSIZDIR.",
        LAM_HEADER_RANK_THRESHOLDS = "Rutbe Esikleri",
        LAM_GUILD_NAME = "Lonca",
        LAM_GUILD_TOOLTIP = "Asagida hangi guild'in rutbe esiklerini duzenledigin.",
        LAM_KICK_THRESHOLD_NAME = "Kick Uygunluk Esigi (gun)",
        LAM_KICK_THRESHOLD_TOOLTIP = "Bir uyenin Kick List'te gorunebilmesi icin gereken uyelik suresi VE inaktiflik (giris yapmama) gun sayisi - buna ek olarak hic katkisinin olmamasi gerekir. Her guild icin ayri ayarlanir.",
        LAM_TIER_NAME_NAME = "Rutbe Adi",
        LAM_TIER_NAME_TOOLTIP = "Bu rutbe seviyesini varsayilan yerine loncanizin kendi adlandirmasina gore yeniden adlandirin (orn. \"VIP\", \"Elit\", \"Guvenilir\").",
        LAM_SALES_THRESHOLD_NAME = "Satis Esigi",
        LAM_SALES_THRESHOLD_TOOLTIP = "Su rutbeye hak kazanmak icin donem icinde gereken toplam magaza satisi (altin): ",
        LAM_DONATION_THRESHOLD_NAME = "Bagis Esigi",
        LAM_DONATION_THRESHOLD_TOOLTIP = "Su rutbeye hak kazanmak icin donem icinde gereken toplam bagis (altin): ",
        LAM_LEGEND_MODE_NAME = "Legend Atama Modu",
        LAM_LEGEND_MODE_TOOLTIP = "Uyeler Legend rutbesini nasil kazanir: sabit bir esik degeriyle, ya da o an secili olan donemin en cok katki yapanlari olarak otomatik.",
        LAM_LEGEND_MODE_THRESHOLD = "Esik Degeri (Satis/Bagis)",
        LAM_LEGEND_MODE_TOP3 = "Top N Satici ve Bagisci",
        LAM_LEGEND_TOP3_DESC = "Top N modunda Legend, HER ZAMAN o an SECILI olan donemin (Bu Hafta, Gecen Ay, vs.) en cok satis yapan ve en cok bagis yapan kisilerdir - degerleri Gold esiginin altinda kalsa bile. Kacar kisi sayilacagi (varsayilan 3/3) asagidan ayarlanabilir. Daha altta kalan Satis/Bagis Esigi alanlari bu mod aktifken DIKKATE ALINMAZ.",
        LAM_LEGEND_TOP_SELLERS_COUNT_NAME = "Top Satici Sayisi",
        LAM_LEGEND_TOP_SELLERS_COUNT_TOOLTIP = "Secili donemin en cok satan kac kisisinin Legend olacagi (sadece Top N modunda).",
        LAM_LEGEND_TOP_DONORS_COUNT_NAME = "Top Bagisci Sayisi",
        LAM_LEGEND_TOP_DONORS_COUNT_TOOLTIP = "Secili donemin en cok bagis yapan kac kisisinin Legend olacagi (sadece Top N modunda).",
        LAM_HEADER_NOTIFICATIONS = "Bildirimler",
        LAM_SCREEN_NOTIF_NAME = "Yeni Bagislarda Ekran Ortasi Bildirimi Goster",
        LAM_SCREEN_NOTIF_TOOLTIP = "Bir uye yeni bagis yaptiginda, ekraninizin ortasinda kisa bir bildirim gosterir (gorev/esya kesfi mesajlariyla ayni stil). Sadece siz giris yaptiktan SONRAKI bagislarda tetiklenir - gecmisi tekrar oynatmaz.",
        LAM_HEADER_MAIL_TEMPLATE = "Mail Sablonu",
        LAM_MAIL_TEMPLATE_DESC = "Yukarida secili guild icin mail sablonu ayarla. Alicinin adini eklemek icin '@', tam @UserID icin '@@' kullan. Guild Roster'daki sag tik menusunden (Mail Gonder) gonder - mail formu onceden doldurulmus acilir, Gonder tusuna sen basarsin.",
        LAM_MAIL_SUBJECT_NAME = "Konu",
        LAM_MAIL_SUBJECT_TOOLTIP = "Mail konu satiri. '@' alicinin adina donusur.",
        LAM_MAIL_BODY_NAME = "Metin",
        LAM_MAIL_BODY_TOOLTIP = "Mail govde metni. '@' alicinin adina donusur.",
    },

    de = {
        ROSTER_TITLE = "Gildenliste",
        TAB_APPROVED = "Genehmigt",
        TAB_INVITED = "Eingeladen",
        TAB_JOINED = "Beigetreten",
        TAB_REJECTED = "Abgelehnt",
        TAB_KICKED = "Rausgeworfen",
        TAB_LEFT = "Verlassen",
        TAB_PROMOTED = "Befoerdert",
        TAB_DEMOTED = "Degradiert",
        FILTER_ALL = "Alle",
        FILTER_THIS_WEEK = "Diese Woche",
        FILTER_7_DAYS = "7 Tage",
        FILTER_30_DAYS = "30 Tage",
        OFFICER_STATS = "Offiziersstatistik",
        SEARCH_LABEL = "Suche:",
        COL_TIME = "Zeit",
        COL_GUILD = "Gilde",
        COL_OFFICER = "Offizier",
        COL_MEMBER = "Mitglied",

        LEDGER_TITLE = "GILDEN-BUCHHALTUNGSSYSTEM",
        ROW_BANK_GOLD = "Bankgold",
        BANK_GOLD_LAST_SEEN = "zuletzt gesehen",
        BANK_GOLD_UNAVAILABLE = "N/A (oeffne einmal in dieser Sitzung die Gildenbank, um dies zu aktivieren)",
        ROW_SALES_VOLUME = "Ladenverkaufsvolumen",
        ROW_TAX_REVENUE = "Gildensteuereinnahmen",
        ROW_DEPOSITS = "Mitgliederspenden",
        ROW_WITHDRAWALS = "Von der Bank abgehoben",
        ROW_TRADER_EXPENSE = "Haendlermiete & Gebotskosten",
        ROW_CURRENT_TRADER = "Aktueller Haendler",
        ROW_CURRENT_BIDS = "Aktuelle Haendlergebote",
        ROW_AVAILABLE_FUNDS = "Verfuegbares Gildenvermoegen",
        NET_PROFIT_LABEL = "GEWINN",
        NET_LOSS_LABEL = "VERLUST",
        ROW_NET_PROFIT = "NETTOGEWINN / -VERLUST",
        PANEL_DONORS_SELLERS = "TOP-SPENDER & VERKAEUFER (dieser Zeitraum)",
        PANEL_DONORS_SELLERS_BASE = "TOP-SPENDER & VERKAEUFER",
        PANEL_DONORS = "SPENDER",
        PANEL_SELLERS = "TOP-VERKAEUFER",
        PANEL_BIDS = "GEBOTE DIESES ZEITRAUMS (bis zu 10)",
        PANEL_BIDS_BASE = "GEBOTE (bis zu 10)",
        PANEL_KIOSKS = "HAENDLERVERLAUF (ALLE GILDEN)",
        PANEL_RANKS = "MITGLIEDERRAENGE (diese Gilde, dieser Zeitraum)",
        PANEL_RANKS_BASE = "MITGLIEDERRAENGE",
        BTN_REFRESH = "Aktualisieren",
        BTN_KIOSKS = "Kioske",
        BTN_RANKS = "Raenge",
        BTN_CLEAR_FILTER = "Filter loeschen",
        BTN_MEMBER_SEARCH = "Suche",
        SEARCH_PANEL_TITLE = "MITGLIEDERSUCHE",
        SEARCH_PANEL_HINT = "Gib einen Mitgliedsnamen ein, um Spenden, Verkaeufe und Einkaeufe in der gewaehlten Gilde/Zeitraum zu durchsuchen.",
        LEDGER_NOTE_PREFIX = "Notiz:",
        EDIT_NOTE_TITLE = "PERSOENLICHE NOTIZ (TGA)",
        EDIT_NOTE_SUBTITLE = "Fuer <<1>> - nur fuer dich sichtbar, nie an den Server gesendet.",
        EDIT_NOTE_XML_OUTDATED = "GuildLedger.xml scheint eine veraltete Version zu sein - das \"Notiz bearbeiten\"-Fenster wurde nicht gefunden. Bitte aktualisiere alle Addon-Dateien (besonders die .xml-Dateien).",
        SEARCH_PANEL_NONE = "Keine passende Aktivitaet fuer diese Gilde/Zeitraum.",
        LEDGER_LABEL_DONATIONS = "Spenden",
        LEDGER_LABEL_SALES = "Verkaeufe",
        LEDGER_LABEL_PURCHASES = "Einkaeufe",
        SEARCH_FILTER_ACTIVE = "Gefiltert",
        STATUS_PROCESSING = "Daten werden verarbeitet...",
        STATUS_NO_VALID_GUILD = "Keine gueltige Gilde ausgewaehlt.",
        RANKS_SUBTITLE = "Mitglieder, die im gewaehlten Zeitraum die Anforderungen erfuellen (koennten diese Raenge bereits haben)",
        RANKS_NONE_QUALIFY = "Kein Mitglied erfuellt in diesem Zeitraum einen Rangschwellenwert. Passen Sie bei Bedarf die Schwellenwerte in den Rangeinstellungen an.",
        KIOSKS_NONE_YET = "Noch keine Haendleraktivitaet erfasst (oder LibHistoire synchronisiert noch).",
        KIOSK_CURRENT_TAG = "AKTUELL",
        DONORS_NONE = "Keine Spenden in diesem Zeitraum.",
        SELLERS_NONE = "Keine Verkaeufe in diesem Zeitraum.",
        BIDS_NONE = "Keine Gebote in diesem Zeitraum abgegeben.",
        CONFIRMED_EXPENSES_TITLE = "BESTAETIGTE HAENDLERAUSGABEN (dieser Zeitraum)",
        CONFIRMED_EXPENSES_NONE = "Noch nichts bestaetigt.",
        CHAT_LIBHISTOIRE_MISSING = "LibHistoire nicht gefunden. Bitte zuerst LibHistoire installieren.",
        CHAT_TRACKING_STARTED = "Finanzdaten-Tracking gestartet (<<1>> Gilde(n)).",
        DONATION_ANNOUNCE_FORMAT = "<<1>> hat <<2>> an <<3>> gespendet",
        ROSTER_STATS_NO_DATA = "Noch keine Daten fuer die aktuellen Filter.",
        ROSTER_STATS_TITLE = "Offiziersaktivitaet-Uebersicht (beruecksichtigt die obigen Gilde/Datum/Suche-Filter)",
        PERIOD_THIS_WEEK = "Diese Woche",
        PERIOD_LAST_WEEK = "Letzte Woche",
        PERIOD_2_WEEKS_AGO = "Vor 2 Wochen",
        PERIOD_3_WEEKS_AGO = "Vor 3 Wochen",
        PERIOD_4_WEEKS_AGO = "Vor 4 Wochen",
        PERIOD_LAST_MONTH = "Letzter Monat",
        PERIOD_THIS_MONTH = "Dieser Monat",
        PERIOD_LAST_30_DAYS = "Letzte 30 Tage",
        PERIOD_ALL_TIME = "Gesamte Zeit",

        SUITE_TITLE = "Tiradil's Guild Assistant",
        BTN_GUILD_ROSTER = "Gildenliste",
        BTN_GUILD_LEDGER = "Gildenbuchhaltung",

        LANG_EN = "EN",
        LANG_TR = "TR",
        LANG_DE = "DE",
        LANG_ES = "ES",
        LANG_PL = "PL",
        LANG_RU = "RU",
        LANG_IT = "IT",
        LANG_PT = "PT",

        LAM_RANK_DESCRIPTION = "Ein Mitglied qualifiziert sich fuer einen Rang, wenn es ENTWEDER den Verkaufs- ODER den Spendenschwellenwert im gewaehlten Zeitraum erreicht (Diese Woche / Letzter Monat / usw. - im Guild Ledger Fenster festgelegt). Schwellenwerte werden SEPARAT pro Gilde festgelegt - waehlen Sie zuerst unten eine Gilde.",
        LAM_HEADER_DISPLAY = "Anzeige",
        LAM_LANGUAGE_NAME = "Sprache",
        LAM_LANGUAGE_TOOLTIP = "Aendert die Sprache von Tiradil's Guild Assistant (Haupttitel, Registerkarten, Spalten, Schaltflaechen, Statusmeldungen und Einstellungsfenster).",
        LAM_HEADER_ROSTER_INTEGRATION = "Gilden-Roster-Integration",
        LAM_SHOW_CONTRIB_COLUMN_NAME = "Beitragsspalte im Guild Roster anzeigen",
        LAM_SHOW_CONTRIB_COLUMN_TOOLTIP = "Schaltet die Spenden-/Verkaufs-/Einkaufsspalte um, die Tiradil zum spieleigenen Guild Roster Bildschirm hinzufuegt. Das Deaktivieren loescht keine Daten - es blendet nur die Spalte aus.",
        LAM_SHOW_RANK_COLUMN_NAME = "Rangspalte im Guild Roster anzeigen",
        LAM_SHOW_RANK_COLUMN_TOOLTIP = "Schaltet das Legend/Diamond/Gold/Silver/Bronze Rang-Tag um, das Tiradil neben Mitgliedernamen im spieleigenen Guild Roster Bildschirm anzeigt. Hat einen EIGENEN Zeitraumwaehler (unter der Spaltenueberschrift), unabhaengig vom Ledger-Fenster und von der Beitragsspalte.",
        LAM_HEADER_RANK_THRESHOLDS = "Rangschwellenwerte",
        LAM_GUILD_NAME = "Gilde",
        LAM_GUILD_TOOLTIP = "Fuer welche Gilde du unten die Rangschwellenwerte bearbeitest.",
        LAM_KICK_THRESHOLD_NAME = "Kick-Berechtigungsschwelle (Tage)",
        LAM_KICK_THRESHOLD_TOOLTIP = "Wie viele Tage Gildenmitgliedschaft UND Inaktivitaet (kein Login) noetig sind, damit ein Mitglied auf der Kick-Liste erscheint - zusaetzlich zu null Beitraegen jemals. Wird pro Gilde separat eingestellt.",
        LAM_TIER_NAME_NAME = "Rangname",
        LAM_TIER_NAME_TOOLTIP = "Diesen Rang statt des Standardnamens nach der eigenen Benennung deiner Gilde umbenennen (z.B. \"VIP\", \"Elite\", \"Vertraut\").",
        LAM_SALES_THRESHOLD_NAME = "Verkaufsschwellenwert",
        LAM_SALES_THRESHOLD_TOOLTIP = "Gesamtverkaeufe (Gold) im Zeitraum, die fuer folgenden Rang erforderlich sind: ",
        LAM_DONATION_THRESHOLD_NAME = "Spendenschwellenwert",
        LAM_DONATION_THRESHOLD_TOOLTIP = "Gesamtspenden (Gold) im Zeitraum, die fuer folgenden Rang erforderlich sind: ",
        LAM_LEGEND_MODE_NAME = "Legend-Zuweisungsmodus",
        LAM_LEGEND_MODE_TOOLTIP = "Wie Mitglieder den Legend-Rang erhalten: ein fester Schwellenwert, oder automatisch als Top-Beitragende des aktuell ausgewaehlten Zeitraums.",
        LAM_LEGEND_MODE_THRESHOLD = "Schwellenwert (Verkauf/Spende)",
        LAM_LEGEND_MODE_TOP3 = "Top N Verkaeufer & Spender",
        LAM_LEGEND_TOP3_DESC = "Im Top-N-Modus sind Legend IMMER die besten Verkaeufer und besten Spender des AKTUELL AUSGEWAEHLTEN Zeitraums (diese Woche, letzter Monat, usw.) - selbst wenn ihre Summen unter dem Gold-Schwellenwert liegen. Wie viele jeweils (Standard 3/3) kann unten eingestellt werden. Die weiter unten stehenden Verkaufs-/Spendenschwellenwert-Felder werden in diesem Modus ignoriert.",
        LAM_LEGEND_TOP_SELLERS_COUNT_NAME = "Anzahl Top-Verkaeufer",
        LAM_LEGEND_TOP_SELLERS_COUNT_TOOLTIP = "Wie viele Top-Verkaeufer des gewaehlten Zeitraums Legend werden (nur im Top-N-Modus).",
        LAM_LEGEND_TOP_DONORS_COUNT_NAME = "Anzahl Top-Spender",
        LAM_LEGEND_TOP_DONORS_COUNT_TOOLTIP = "Wie viele Top-Spender des gewaehlten Zeitraums Legend werden (nur im Top-N-Modus).",
        LAM_HEADER_NOTIFICATIONS = "Benachrichtigungen",
        LAM_SCREEN_NOTIF_NAME = "Bildschirmmitte-Ankuendigung bei neuen Spenden anzeigen",
        LAM_SCREEN_NOTIF_TOOLTIP = "Wenn ein Mitglied eine neue Spende macht, wird eine kurze Ankuendigung in der Bildschirmmitte angezeigt (gleicher Stil wie Quest-/Gegenstandsentdeckungsmeldungen). Wird nur fuer Spenden nach deinem Login ausgeloest - spielt keine Historie ab.",
        LAM_HEADER_MAIL_TEMPLATE = "Mail-Vorlage",
        LAM_MAIL_TEMPLATE_DESC = "Richte eine Mail-Vorlage fuer die oben ausgewaehlte Gilde ein. Verwende '@' fuer den Namen des Empfaengers, oder '@@' fuer die vollstaendige @UserID. Sende sie ueber das Guild Roster Rechtsklickmenue (Mail senden) - das Mailformular oeffnet sich vorausgefuellt, du druckst selbst auf Senden.",
        LAM_MAIL_SUBJECT_NAME = "Betreff",
        LAM_MAIL_SUBJECT_TOOLTIP = "Mail-Betreffzeile. '@' wird zum Namen des Empfaengers.",
        LAM_MAIL_BODY_NAME = "Text",
        LAM_MAIL_BODY_TOOLTIP = "Mail-Textinhalt. '@' wird zum Namen des Empfaengers.",
    },
    es = {
        ROSTER_TITLE = "Lista de Miembros",
        TAB_APPROVED = "Aprobados",
        TAB_INVITED = "Invitados",
        TAB_JOINED = "Union",
        TAB_REJECTED = "Rechazados",
        TAB_KICKED = "Expulsados",
        TAB_LEFT = "Abandonos",
        TAB_PROMOTED = "Ascensos",
        TAB_DEMOTED = "Descensos",
        FILTER_ALL = "Todos",
        FILTER_THIS_WEEK = "Esta Semana",
        FILTER_7_DAYS = "7 Dias",
        FILTER_30_DAYS = "30 Dias",
        OFFICER_STATS = "Estadisticas de Oficiales",
        SEARCH_LABEL = "Buscar:",
        COL_TIME = "Fecha",
        COL_GUILD = "Hermandad",
        COL_OFFICER = "Oficial",
        COL_MEMBER = "Miembro",

        LEDGER_TITLE = "SISTEMA DE CONTABILIDAD DE LA HERMANDAD",
        ROW_BANK_GOLD = "Oro del Banco",
        BANK_GOLD_LAST_SEEN = "visto por ultima vez",
        BANK_GOLD_UNAVAILABLE = "N/D (abre el banco de tu hermandad una vez en esta sesion para activarlo)",
        ROW_SALES_VOLUME = "Volumen de Ventas",
        ROW_TAX_REVENUE = "Ingresos por Impuestos",
        ROW_DEPOSITS = "Depositos de Miembros",
        ROW_WITHDRAWALS = "Retiros del Banco",
        ROW_TRADER_EXPENSE = "Alquiler de Puesto y Pujas",
        ROW_CURRENT_TRADER = "Comerciante Actual",
        ROW_CURRENT_BIDS = "Pujas de Comerciante Actuales",
        ROW_AVAILABLE_FUNDS = "Fondos de Hermandad Disponibles",
        NET_PROFIT_LABEL = "GANANCIA",
        NET_LOSS_LABEL = "PERDIDA",
        ROW_NET_PROFIT = "GANANCIA / PERDIDA NETA",
        PANEL_DONORS_SELLERS = "MEJORES DONANTES Y VENDEDORES (este periodo)",
        PANEL_DONORS_SELLERS_BASE = "MEJORES DONANTES Y VENDEDORES",
        PANEL_DONORS = "DONANTES",
        PANEL_SELLERS = "MEJORES VENDEDORES",
        PANEL_BIDS = "PUJAS DE ESTE PERIODO (hasta 10)",
        PANEL_BIDS_BASE = "PUJAS (hasta 10)",
        PANEL_KIOSKS = "HISTORIAL DE COMERCIANTES (TODAS LAS HERMANDADES)",
        PANEL_RANKS = "RANGOS DE MIEMBROS (esta hermandad, este periodo)",
        PANEL_RANKS_BASE = "RANGOS DE MIEMBROS",
        BTN_REFRESH = "Actualizar",
        BTN_KIOSKS = "Puestos",
        BTN_RANKS = "Rangos",
        BTN_CLEAR_FILTER = "Quitar Filtro",
        BTN_MEMBER_SEARCH = "Buscar",
        SEARCH_PANEL_TITLE = "BUSQUEDA DE MIEMBROS",
        SEARCH_PANEL_HINT = "Escribe el nombre de un miembro para buscar sus donaciones, ventas y compras en la hermandad/periodo seleccionados.",
        LEDGER_NOTE_PREFIX = "Nota:",
        EDIT_NOTE_TITLE = "NOTA PERSONAL (TGA)",
        EDIT_NOTE_SUBTITLE = "Para <<1>> - solo visible para ti, nunca se envia al servidor.",
        EDIT_NOTE_XML_OUTDATED = "GuildLedger.xml parece ser una version desactualizada - no se encontro la ventana \"Editar Nota\". Por favor actualiza todos los archivos del addon (especialmente los archivos .xml).",
        SEARCH_PANEL_NONE = "Sin actividad coincidente para esta hermandad/periodo.",
        LEDGER_LABEL_DONATIONS = "Donaciones",
        LEDGER_LABEL_SALES = "Ventas",
        LEDGER_LABEL_PURCHASES = "Compras",
        SEARCH_FILTER_ACTIVE = "Filtrado",
        STATUS_PROCESSING = "Procesando datos...",
        STATUS_NO_VALID_GUILD = "No se selecciono ninguna hermandad valida.",
        RANKS_SUBTITLE = "Miembros que cumplen los requisitos en el periodo seleccionado (puede que ya tengan estos rangos)",
        RANKS_NONE_QUALIFY = "Ningun miembro alcanza un umbral de rango este periodo. Ajusta los umbrales en Configuracion de Rangos si es necesario.",
        KIOSKS_NONE_YET = "Aun no se registro actividad de comerciantes (o LibHistoire sigue sincronizando).",
        KIOSK_CURRENT_TAG = "ACTUAL",
        DONORS_NONE = "Sin donaciones en este periodo.",
        SELLERS_NONE = "Sin ventas en este periodo.",
        BIDS_NONE = "Sin pujas realizadas en este periodo.",
        CONFIRMED_EXPENSES_TITLE = "GASTOS DE COMERCIANTE CONFIRMADOS (este periodo)",
        CONFIRMED_EXPENSES_NONE = "Ninguno confirmado todavia.",
        CHAT_LIBHISTOIRE_MISSING = "LibHistoire no encontrado. Por favor instala LibHistoire primero.",
        CHAT_TRACKING_STARTED = "Seguimiento de datos financieros iniciado (<<1>> hermandad(es)).",
        DONATION_ANNOUNCE_FORMAT = "<<1>> dono <<2>> a <<3>>",
        ROSTER_STATS_NO_DATA = "Aun no hay datos para los filtros actuales.",
        ROSTER_STATS_TITLE = "Resumen de Actividad de Oficiales (respeta los filtros de Hermandad/Fecha/Busqueda de arriba)",
        PERIOD_THIS_WEEK = "Esta Semana",
        PERIOD_LAST_WEEK = "Semana Pasada",
        PERIOD_2_WEEKS_AGO = "Hace 2 Semanas",
        PERIOD_3_WEEKS_AGO = "Hace 3 Semanas",
        PERIOD_4_WEEKS_AGO = "Hace 4 Semanas",
        PERIOD_LAST_MONTH = "Mes Pasado",
        PERIOD_THIS_MONTH = "Este Mes",
        PERIOD_LAST_30_DAYS = "Ultimos 30 Dias",
        PERIOD_ALL_TIME = "Todo el Tiempo (Total)",

        SUITE_TITLE = "Tiradil's Guild Assistant",
        BTN_GUILD_ROSTER = "Lista de Miembros",
        BTN_GUILD_LEDGER = "Contabilidad",

        LANG_EN = "EN",
        LANG_TR = "TR",
        LANG_DE = "DE",
        LANG_ES = "ES",
        LANG_PL = "PL",
        LANG_RU = "RU",
        LANG_IT = "IT",
        LANG_PT = "PT",

        LAM_RANK_DESCRIPTION = "Un miembro califica para un rango si cumple CUALQUIERA de los umbrales de ventas O de donaciones en el periodo seleccionado (Esta Semana / Mes Pasado / etc. - se define en la ventana de Contabilidad). Los umbrales se establecen POR SEPARADO para cada hermandad - elige una hermandad abajo primero.",
        LAM_HEADER_DISPLAY = "Pantalla",
        LAM_LANGUAGE_NAME = "Idioma",
        LAM_LANGUAGE_TOOLTIP = "Cambia el idioma de Tiradil's Guild Assistant (titulos principales, pestanas, columnas, botones, mensajes de estado y panel de configuracion).",
        LAM_HEADER_ROSTER_INTEGRATION = "Integracion con la Lista de Miembros",
        LAM_SHOW_CONTRIB_COLUMN_NAME = "Mostrar Columna de Contribucion en la Lista de Miembros",
        LAM_SHOW_CONTRIB_COLUMN_TOOLTIP = "Activa o desactiva la columna de donaciones/ventas/compras que Tiradil anade a la pantalla de Lista de Miembros del juego. Desactivarla no borra ningun dato - solo oculta la columna.",
        LAM_SHOW_RANK_COLUMN_NAME = "Mostrar Columna de Rango en la Lista de Miembros",
        LAM_SHOW_RANK_COLUMN_TOOLTIP = "Activa o desactiva la etiqueta de rango Legend/Diamond/Gold/Silver/Bronze que Tiradil anade junto a los nombres de miembros en la pantalla de Lista de Miembros del juego. Tiene su propio selector de periodo (bajo el encabezado de la columna), independiente del periodo de la ventana de Contabilidad y del periodo de la columna de Contribucion.",
        LAM_HEADER_RANK_THRESHOLDS = "Umbrales de Rango",
        LAM_GUILD_NAME = "Hermandad",
        LAM_GUILD_TOOLTIP = "De que hermandad estas editando los umbrales de rango abajo.",
        LAM_KICK_THRESHOLD_NAME = "Umbral de Elegibilidad para Expulsion (dias)",
        LAM_KICK_THRESHOLD_TOOLTIP = "Cuantos dias de membresia E inactividad (sin iniciar sesion) se requieren para que un miembro aparezca en la Lista de Expulsion, ademas de no tener nunca contribuciones. Se establece por separado para cada hermandad.",
        LAM_TIER_NAME_NAME = "Nombre del Rango",
        LAM_TIER_NAME_TOOLTIP = "Renombra este nivel de rango segun la nomenclatura propia de tu hermandad (por ejemplo, \"VIP\", \"Elite\", \"De Confianza\") en lugar del nombre predeterminado.",
        LAM_SALES_THRESHOLD_NAME = "Umbral de Ventas",
        LAM_SALES_THRESHOLD_TOOLTIP = "Ventas totales de tienda (oro) necesarias en el periodo para calificar para ",
        LAM_DONATION_THRESHOLD_NAME = "Umbral de Donaciones",
        LAM_DONATION_THRESHOLD_TOOLTIP = "Donaciones totales (oro) necesarias en el periodo para calificar para ",
        LAM_LEGEND_MODE_NAME = "Modo de Asignacion de Legend",
        LAM_LEGEND_MODE_TOOLTIP = "Como los miembros obtienen el rango Legend: un umbral fijo, o automaticamente como los mejores contribuyentes del periodo seleccionado actualmente.",
        LAM_LEGEND_MODE_THRESHOLD = "Umbral (Ventas/Donaciones)",
        LAM_LEGEND_MODE_TOP3 = "Los N Mejores Vendedores y Donantes",
        LAM_LEGEND_TOP3_DESC = "En el modo Top N, Legend siempre son los mejores vendedores y donantes del periodo que este seleccionado actualmente (Esta Semana, Mes Pasado, etc.) - incluso si sus totales estan por debajo del umbral de Gold. Cuantos de cada uno (por defecto 3/3) se puede definir abajo. Los campos de Umbral de Ventas/Donaciones mas abajo se ignoran mientras este modo este activo.",
        LAM_LEGEND_TOP_SELLERS_COUNT_NAME = "Numero de Mejores Vendedores",
        LAM_LEGEND_TOP_SELLERS_COUNT_TOOLTIP = "Cuantos de los mejores vendedores del periodo seleccionado se convierten en Legend (solo en modo Top N).",
        LAM_LEGEND_TOP_DONORS_COUNT_NAME = "Numero de Mejores Donantes",
        LAM_LEGEND_TOP_DONORS_COUNT_TOOLTIP = "Cuantos de los mejores donantes del periodo seleccionado se convierten en Legend (solo en modo Top N).",
        LAM_HEADER_NOTIFICATIONS = "Notificaciones",
        LAM_SCREEN_NOTIF_NAME = "Mostrar Anuncio en el Centro de la Pantalla en Nuevas Donaciones",
        LAM_SCREEN_NOTIF_TOOLTIP = "Cuando un miembro hace una nueva donacion, muestra un breve anuncio en el centro de tu pantalla (mismo estilo que los mensajes de descubrimiento de mision/objeto). Solo se activa para donaciones hechas despues de iniciar sesion - no repite el historial.",
        LAM_HEADER_MAIL_TEMPLATE = "Plantilla de Correo",
        LAM_MAIL_TEMPLATE_DESC = "Configura una plantilla de correo para la hermandad seleccionada arriba. Usa '@' para insertar el nombre del destinatario, o '@@' para su @UserID completo. Envialo desde el menu contextual de la Lista de Miembros (Enviar Correo) - el formulario de correo se abre precompletado, tu mismo pulsas Enviar.",
        LAM_MAIL_SUBJECT_NAME = "Asunto",
        LAM_MAIL_SUBJECT_TOOLTIP = "Linea de asunto del correo. '@' se convierte en el nombre del destinatario.",
        LAM_MAIL_BODY_NAME = "Cuerpo",
        LAM_MAIL_BODY_TOOLTIP = "Texto del cuerpo del correo. '@' se convierte en el nombre del destinatario.",
    },
    pl = {
        ROSTER_TITLE = "Lista Gildii",
        TAB_APPROVED = "Zaakceptowani",
        TAB_INVITED = "Zaproszeni",
        TAB_JOINED = "Dolaczyli",
        TAB_REJECTED = "Odrzuceni",
        TAB_KICKED = "Wyrzuceni",
        TAB_LEFT = "Opuscili",
        TAB_PROMOTED = "Awansowani",
        TAB_DEMOTED = "Zdegradowani",
        FILTER_ALL = "Wszyscy",
        FILTER_THIS_WEEK = "Ten Tydzien",
        FILTER_7_DAYS = "7 Dni",
        FILTER_30_DAYS = "30 Dni",
        OFFICER_STATS = "Statystyki Oficerow",
        SEARCH_LABEL = "Szukaj:",
        COL_TIME = "Czas",
        COL_GUILD = "Gildia",
        COL_OFFICER = "Oficer",
        COL_MEMBER = "Czlonek",

        LEDGER_TITLE = "SYSTEM KSIEGOWY GILDII",
        ROW_BANK_GOLD = "Zloto w Banku",
        BANK_GOLD_LAST_SEEN = "ostatnio widziano",
        BANK_GOLD_UNAVAILABLE = "N/D (otworz bank gildii raz w tej sesji, aby to wlaczyc)",
        ROW_SALES_VOLUME = "Wolumen Sprzedazy",
        ROW_TAX_REVENUE = "Przychod z Podatkow Gildii",
        ROW_DEPOSITS = "Wplaty Czlonkow",
        ROW_WITHDRAWALS = "Wyplaty z Banku",
        ROW_TRADER_EXPENSE = "Czynsz Kupca i Licytacje",
        ROW_CURRENT_TRADER = "Obecny Kupiec",
        ROW_CURRENT_BIDS = "Aktualne Oferty Kupca",
        ROW_AVAILABLE_FUNDS = "Dostepne Fundusze Gildii",
        NET_PROFIT_LABEL = "ZYSK",
        NET_LOSS_LABEL = "STRATA",
        ROW_NET_PROFIT = "ZYSK / STRATA NETTO",
        PANEL_DONORS_SELLERS = "NAJLEPSI DARCZYNCY I SPRZEDAWCY (ten okres)",
        PANEL_DONORS_SELLERS_BASE = "NAJLEPSI DARCZYNCY I SPRZEDAWCY",
        PANEL_DONORS = "DARCZYNCY",
        PANEL_SELLERS = "NAJLEPSI SPRZEDAWCY",
        PANEL_BIDS = "LICYTACJE W TYM OKRESIE (do 10)",
        PANEL_BIDS_BASE = "LICYTACJE (do 10)",
        PANEL_KIOSKS = "HISTORIA KUPCOW (WSZYSTKIE GILDIE)",
        PANEL_RANKS = "RANGI CZLONKOW (ta gildia, ten okres)",
        PANEL_RANKS_BASE = "RANGI CZLONKOW",
        BTN_REFRESH = "Odswiez",
        BTN_KIOSKS = "Kioski",
        BTN_RANKS = "Rangi",
        BTN_CLEAR_FILTER = "Wyczysc Filtr",
        BTN_MEMBER_SEARCH = "Szukaj",
        SEARCH_PANEL_TITLE = "WYSZUKIWANIE CZLONKOW",
        SEARCH_PANEL_HINT = "Wpisz nazwe czlonka, aby wyszukac jego darowizny, sprzedaze i zakupy w wybranej gildii/okresie.",
        LEDGER_NOTE_PREFIX = "Notatka:",
        EDIT_NOTE_TITLE = "NOTATKA OSOBISTA (TGA)",
        EDIT_NOTE_SUBTITLE = "Dla <<1>> - widoczne tylko dla ciebie, nigdy nie wysylane na serwer.",
        EDIT_NOTE_XML_OUTDATED = "GuildLedger.xml wyglada na nieaktualna wersje - nie znaleziono okna \"Edytuj Notatke\". Prosze zaktualizowac wszystkie pliki dodatku (zwlaszcza pliki .xml).",
        SEARCH_PANEL_NONE = "Brak pasujacej aktywnosci dla tej gildii/okresu.",
        LEDGER_LABEL_DONATIONS = "Darowizny",
        LEDGER_LABEL_SALES = "Sprzedaz",
        LEDGER_LABEL_PURCHASES = "Zakupy",
        SEARCH_FILTER_ACTIVE = "Filtrowane",
        STATUS_PROCESSING = "Przetwarzanie danych...",
        STATUS_NO_VALID_GUILD = "Nie wybrano prawidlowej gildii.",
        RANKS_SUBTITLE = "Czlonkowie spelniajacy wymagania w wybranym okresie (moga juz posiadac te rangi)",
        RANKS_NONE_QUALIFY = "Zaden czlonek nie spelnia progu rangi w tym okresie. W razie potrzeby dostosuj progi w Ustawieniach Rang.",
        KIOSKS_NONE_YET = "Nie zarejestrowano jeszcze zadnej aktywnosci kupcow (lub LibHistoire wciaz synchronizuje).",
        KIOSK_CURRENT_TAG = "OBECNY",
        DONORS_NONE = "Brak darowizn w tym okresie.",
        SELLERS_NONE = "Brak sprzedazy w tym okresie.",
        BIDS_NONE = "Brak zlozonych licytacji w tym okresie.",
        CONFIRMED_EXPENSES_TITLE = "POTWIERDZONE WYDATKI NA KUPCOW (ten okres)",
        CONFIRMED_EXPENSES_NONE = "Jeszcze nic nie potwierdzono.",
        CHAT_LIBHISTOIRE_MISSING = "Nie znaleziono LibHistoire. Najpierw zainstaluj LibHistoire.",
        CHAT_TRACKING_STARTED = "Rozpoczeto sledzenie danych finansowych (<<1>> gildia/gildie).",
        DONATION_ANNOUNCE_FORMAT = "<<1>> przekazal(a) <<2>> dla <<3>>",
        ROSTER_STATS_NO_DATA = "Brak danych dla obecnych filtrow.",
        ROSTER_STATS_TITLE = "Podsumowanie Aktywnosci Oficerow (uwzglednia filtry Gildii/Daty/Wyszukiwania powyzej)",
        PERIOD_THIS_WEEK = "Ten Tydzien",
        PERIOD_LAST_WEEK = "Zeszly Tydzien",
        PERIOD_2_WEEKS_AGO = "2 Tygodnie Temu",
        PERIOD_3_WEEKS_AGO = "3 Tygodnie Temu",
        PERIOD_4_WEEKS_AGO = "4 Tygodnie Temu",
        PERIOD_LAST_MONTH = "Zeszly Miesiac",
        PERIOD_THIS_MONTH = "Ten Miesiac",
        PERIOD_LAST_30_DAYS = "Ostatnie 30 Dni",
        PERIOD_ALL_TIME = "Caly Czas (Razem)",

        SUITE_TITLE = "Tiradil's Guild Assistant",
        BTN_GUILD_ROSTER = "Lista Gildii",
        BTN_GUILD_LEDGER = "Ksiegowosc Gildii",

        LANG_EN = "EN",
        LANG_TR = "TR",
        LANG_DE = "DE",
        LANG_ES = "ES",
        LANG_PL = "PL",
        LANG_RU = "RU",
        LANG_IT = "IT",
        LANG_PT = "PT",

        LAM_RANK_DESCRIPTION = "Czlonek kwalifikuje sie do rangi, jesli spelnia próg sprzedazy LUB próg darowizn w wybranym okresie (Ten Tydzien / Zeszly Miesiac / itp. - ustawiane w oknie Ksiegowosci Gildii). Progi ustawia sie OSOBNO dla kazdej gildii - najpierw wybierz gildie ponizej.",
        LAM_HEADER_DISPLAY = "Wyswietlanie",
        LAM_LANGUAGE_NAME = "Jezyk",
        LAM_LANGUAGE_TOOLTIP = "Zmienia jezyk Tiradil's Guild Assistant (glowne tytuly, zakladki, kolumny, przyciski, komunikaty statusu i panel ustawien).",
        LAM_HEADER_ROSTER_INTEGRATION = "Integracja z Lista Gildii",
        LAM_SHOW_CONTRIB_COLUMN_NAME = "Pokaz Kolumne Wkladu w Liscie Gildii",
        LAM_SHOW_CONTRIB_COLUMN_TOOLTIP = "Wlacza lub wylacza kolumne darowizn/sprzedazy/zakupow, ktora Tiradil dodaje do ekranu Listy Gildii w grze. Wylaczenie tego nie usuwa zadnych danych - jedynie ukrywa kolumne.",
        LAM_SHOW_RANK_COLUMN_NAME = "Pokaz Kolumne Rangi w Liscie Gildii",
        LAM_SHOW_RANK_COLUMN_TOOLTIP = "Wlacza lub wylacza etykiete rangi Legend/Diamond/Gold/Silver/Bronze, ktora Tiradil dodaje obok nazw czlonkow na ekranie Listy Gildii w grze. Posiada wlasny selektor okresu (pod naglowkiem kolumny), niezalezny od okresu okna Ksiegowosci i okresu kolumny Wkladu.",
        LAM_HEADER_RANK_THRESHOLDS = "Progi Rang",
        LAM_GUILD_NAME = "Gildia",
        LAM_GUILD_TOOLTIP = "Ktorej gildii progi rang edytujesz ponizej.",
        LAM_KICK_THRESHOLD_NAME = "Prog Kwalifikowalnosci do Wyrzucenia (dni)",
        LAM_KICK_THRESHOLD_TOOLTIP = "Ile dni czlonkostwa w gildii ORAZ nieaktywnosci (brak logowania) jest wymaganych, aby czlonek pojawil sie na Liscie do Wyrzucenia, oprocz braku jakichkolwiek wkladow. Ustawiane osobno dla kazdej gildii.",
        LAM_TIER_NAME_NAME = "Nazwa Rangi",
        LAM_TIER_NAME_TOOLTIP = "Zmien nazwe tego poziomu rangi na wlasne nazewnictwo twojej gildii (np. \"VIP\", \"Elita\", \"Zaufany\") zamiast domyslnej.",
        LAM_SALES_THRESHOLD_NAME = "Prog Sprzedazy",
        LAM_SALES_THRESHOLD_TOOLTIP = "Laczna sprzedaz w sklepie (zloto) potrzebna w tym okresie, aby zakwalifikowac sie do ",
        LAM_DONATION_THRESHOLD_NAME = "Prog Darowizn",
        LAM_DONATION_THRESHOLD_TOOLTIP = "Laczne darowizny (zloto) potrzebne w tym okresie, aby zakwalifikowac sie do ",
        LAM_LEGEND_MODE_NAME = "Tryb Przyznawania Legend",
        LAM_LEGEND_MODE_TOOLTIP = "Jak czlonkowie zdobywaja range Legend: staly prog, lub automatycznie jako najlepsi uczestnicy aktualnie wybranego okresu.",
        LAM_LEGEND_MODE_THRESHOLD = "Prog (Sprzedaz/Darowizny)",
        LAM_LEGEND_MODE_TOP3 = "N Najlepszych Sprzedawcow i Darczyncow",
        LAM_LEGEND_TOP3_DESC = "W trybie Top N, Legend to zawsze najlepsi sprzedawcy i darczyncy aktualnie wybranego okresu (Ten Tydzien, Zeszly Miesiac, itp.) - nawet jesli ich sumy sa ponizej progu Gold. Ile osob z kazdej kategorii (domyslnie 3/3) mozna ustawic ponizej. Pola Progu Sprzedazy/Darowizn ponizej sa ignorowane, gdy ten tryb jest aktywny.",
        LAM_LEGEND_TOP_SELLERS_COUNT_NAME = "Liczba Najlepszych Sprzedawcow",
        LAM_LEGEND_TOP_SELLERS_COUNT_TOOLTIP = "Ilu najlepszych sprzedawcow wybranego okresu zostaje Legend (tylko w trybie Top N).",
        LAM_LEGEND_TOP_DONORS_COUNT_NAME = "Liczba Najlepszych Darczyncow",
        LAM_LEGEND_TOP_DONORS_COUNT_TOOLTIP = "Ilu najlepszych darczyncow wybranego okresu zostaje Legend (tylko w trybie Top N).",
        LAM_HEADER_NOTIFICATIONS = "Powiadomienia",
        LAM_SCREEN_NOTIF_NAME = "Pokaz Ogloszenie na Srodku Ekranu przy Nowych Darowiznach",
        LAM_SCREEN_NOTIF_TOOLTIP = "Gdy czlonek dokona nowej darowizny, pokazuje krotkie ogloszenie na srodku ekranu (w tym samym stylu co wiadomosci o odkryciu misji/przedmiotu). Uruchamia sie tylko dla darowizn dokonanych po zalogowaniu - nie odtwarza historii.",
        LAM_HEADER_MAIL_TEMPLATE = "Szablon Wiadomosci",
        LAM_MAIL_TEMPLATE_DESC = "Skonfiguruj szablon wiadomosci dla gildii wybranej powyzej. Uzyj '@', aby wstawic imie odbiorcy, lub '@@' dla pelnego @UserID. Wyslij go z menu kontekstowego Listy Gildii (Wyslij Wiadomosc) - formularz wiadomosci otwiera sie wstepnie wypelniony, ty sam klikasz Wyslij.",
        LAM_MAIL_SUBJECT_NAME = "Temat",
        LAM_MAIL_SUBJECT_TOOLTIP = "Temat wiadomosci. '@' zamienia sie w imie odbiorcy.",
        LAM_MAIL_BODY_NAME = "Tresc",
        LAM_MAIL_BODY_TOOLTIP = "Tresc wiadomosci. '@' zamienia sie w imie odbiorcy.",
    },
    ru = {
        ROSTER_TITLE = "Список гильдии",
        TAB_APPROVED = "Одобрены",
        TAB_INVITED = "Приглашены",
        TAB_JOINED = "Вступили",
        TAB_REJECTED = "Отклонены",
        TAB_KICKED = "Исключены",
        TAB_LEFT = "Покинули",
        TAB_PROMOTED = "Повышены",
        TAB_DEMOTED = "Понижены",
        FILTER_ALL = "Все",
        FILTER_THIS_WEEK = "На этой неделе",
        FILTER_7_DAYS = "7 дней",
        FILTER_30_DAYS = "30 дней",
        OFFICER_STATS = "Статистика офицеров",
        SEARCH_LABEL = "Поиск:",
        COL_TIME = "Время",
        COL_GUILD = "Гильдия",
        COL_OFFICER = "Офицер",
        COL_MEMBER = "Участник",

        LEDGER_TITLE = "БУХГАЛТЕРИЯ ГИЛЬДИИ",
        ROW_BANK_GOLD = "Золото в банке",
        BANK_GOLD_LAST_SEEN = "последний раз показано",
        BANK_GOLD_UNAVAILABLE = "Н/Д (откройте банк гильдии один раз за сессию, чтобы включить)",
        ROW_SALES_VOLUME = "Объём продаж в магазине",
        ROW_TAX_REVENUE = "Налоговый доход гильдии",
        ROW_DEPOSITS = "Пожертвования участников",
        ROW_WITHDRAWALS = "Снято с банка",
        ROW_TRADER_EXPENSE = "Аренда торговца и ставки",
        ROW_CURRENT_TRADER = "Текущий торговец",
        ROW_CURRENT_BIDS = "Текущие ставки на торговца",
        ROW_AVAILABLE_FUNDS = "Доступные средства гильдии",
        NET_PROFIT_LABEL = "ПРИБЫЛЬ",
        NET_LOSS_LABEL = "УБЫТОК",
        ROW_NET_PROFIT = "ЧИСТАЯ ПРИБЫЛЬ / УБЫТОК",
        PANEL_DONORS_SELLERS = "ЛУЧШИЕ ДОНОРЫ И ПРОДАВЦЫ (за этот период)",
        PANEL_DONORS_SELLERS_BASE = "ЛУЧШИЕ ДОНОРЫ И ПРОДАВЦЫ",
        PANEL_DONORS = "ДОНОРЫ",
        PANEL_SELLERS = "ЛУЧШИЕ ПРОДАВЦЫ",
        PANEL_BIDS = "СТАВКИ ЭТОГО ПЕРИОДА (до 10)",
        PANEL_BIDS_BASE = "СТАВКИ (до 10)",
        PANEL_KIOSKS = "ИСТОРИЯ ТОРГОВЦЕВ (ВСЕ ГИЛЬДИИ)",
        PANEL_RANKS = "РАНГИ УЧАСТНИКОВ (эта гильдия, этот период)",
        PANEL_RANKS_BASE = "РАНГИ УЧАСТНИКОВ",
        BTN_REFRESH = "Обновить",
        BTN_KIOSKS = "Киоски",
        BTN_RANKS = "Ранги",
        BTN_CLEAR_FILTER = "Сбросить фильтр",
        BTN_MEMBER_SEARCH = "Поиск",
        SEARCH_PANEL_TITLE = "ПОИСК УЧАСТНИКА",
        SEARCH_PANEL_HINT = "Введите имя участника, чтобы найти его пожертвования, продажи и покупки в выбранной гильдии/периоде.",
        LEDGER_NOTE_PREFIX = "Заметка:",
        EDIT_NOTE_TITLE = "ЛИЧНАЯ ЗАМЕТКА (TGA)",
        EDIT_NOTE_SUBTITLE = "Для <<1>> - видно только вам, никогда не отправляется на сервер.",
        EDIT_NOTE_XML_OUTDATED = "Похоже, файл GuildLedger.xml устарел - окно \"Редактировать заметку\" не найдено. Пожалуйста, обновите все файлы аддона (особенно .xml файлы).",
        SEARCH_PANEL_NONE = "Нет подходящей активности для этой гильдии/периода.",
        LEDGER_LABEL_DONATIONS = "Пожертвования",
        LEDGER_LABEL_SALES = "Продажи",
        LEDGER_LABEL_PURCHASES = "Покупки",
        SEARCH_FILTER_ACTIVE = "Отфильтровано",
        STATUS_PROCESSING = "Обработка данных...",
        STATUS_NO_VALID_GUILD = "Не выбрана действительная гильдия.",
        RANKS_SUBTITLE = "Участники, соответствующие требованиям за выбранный период (они уже могут иметь эти ранги)",
        RANKS_NONE_QUALIFY = "Ни один участник не достиг порога ранга за этот период. При необходимости настройте пороги в настройках рангов.",
        KIOSKS_NONE_YET = "Активность торговцев ещё не зафиксирована (или LibHistoire всё ещё синхронизируется).",
        KIOSK_CURRENT_TAG = "ТЕКУЩИЙ",
        DONORS_NONE = "Нет пожертвований за этот период.",
        SELLERS_NONE = "Нет продаж за этот период.",
        BIDS_NONE = "Ставки за этот период не размещались.",
        CONFIRMED_EXPENSES_TITLE = "ПОДТВЕРЖДЁННЫЕ РАСХОДЫ НА ТОРГОВЦА (этот период)",
        CONFIRMED_EXPENSES_NONE = "Пока ничего не подтверждено.",
        CHAT_LIBHISTOIRE_MISSING = "LibHistoire не найден. Пожалуйста, сначала установите LibHistoire.",
        CHAT_TRACKING_STARTED = "Отслеживание финансовых данных запущено (<<1>> гильдия(й)).",
        DONATION_ANNOUNCE_FORMAT = "<<1>> пожертвовал(а) <<2>> гильдии <<3>>",
        ROSTER_STATS_NO_DATA = "Пока нет данных для текущих фильтров.",
        ROSTER_STATS_TITLE = "Сводка активности офицеров (учитывает фильтры гильдии/даты/поиска выше)",
        PERIOD_THIS_WEEK = "На этой неделе",
        PERIOD_LAST_WEEK = "На прошлой неделе",
        PERIOD_2_WEEKS_AGO = "2 недели назад",
        PERIOD_3_WEEKS_AGO = "3 недели назад",
        PERIOD_4_WEEKS_AGO = "4 недели назад",
        PERIOD_LAST_MONTH = "В прошлом месяце",
        PERIOD_THIS_MONTH = "В этом месяце",
        PERIOD_LAST_30_DAYS = "Последние 30 дней",
        PERIOD_ALL_TIME = "За всё время (Итого)",

        SUITE_TITLE = "Tiradil's Guild Assistant",
        BTN_GUILD_ROSTER = "Список гильдии",
        BTN_GUILD_LEDGER = "Бухгалтерия гильдии",

        LANG_EN = "EN",
        LANG_TR = "TR",
        LANG_DE = "DE",
        LANG_ES = "ES",
        LANG_PL = "PL",
        LANG_RU = "RU",
        LANG_IT = "IT",
        LANG_PT = "PT",

        LAM_RANK_DESCRIPTION = "Участник получает ранг, если он достигает ЛИБО порога продаж, ЛИБО порога пожертвований за выбранный период (На этой неделе / В прошлом месяце / и т.д. - задаётся в окне Бухгалтерии гильдии). Пороги задаются ОТДЕЛЬНО для каждой гильдии - сначала выберите гильдию ниже.",
        LAM_HEADER_DISPLAY = "Отображение",
        LAM_LANGUAGE_NAME = "Язык",
        LAM_LANGUAGE_TOOLTIP = "Изменяет язык Tiradil's Guild Assistant (основные заголовки, вкладки, столбцы, кнопки, сообщения о состоянии и панель настроек).",
        LAM_HEADER_ROSTER_INTEGRATION = "Интеграция со Списком гильдии",
        LAM_SHOW_CONTRIB_COLUMN_NAME = "Показывать столбец вклада в Списке гильдии",
        LAM_SHOW_CONTRIB_COLUMN_TOOLTIP = "Включает/выключает столбец пожертвований/продаж/покупок, который Tiradil добавляет на игровой экран Списка гильдии. Отключение не удаляет данные - только скрывает столбец.",
        LAM_SHOW_RANK_COLUMN_NAME = "Показывать столбец ранга в Списке гильдии",
        LAM_SHOW_RANK_COLUMN_TOOLTIP = "Включает/выключает метку ранга Legend/Diamond/Gold/Silver/Bronze, которую Tiradil добавляет рядом с именами участников на игровом экране Списка гильдии. Имеет собственный выбор периода (под заголовком столбца), независимый от периода окна Бухгалтерии и периода столбца Вклада.",
        LAM_HEADER_RANK_THRESHOLDS = "Пороги рангов",
        LAM_GUILD_NAME = "Гильдия",
        LAM_GUILD_TOOLTIP = "Пороги рангов какой гильдии вы редактируете ниже.",
        LAM_KICK_THRESHOLD_NAME = "Порог для исключения (дней)",
        LAM_KICK_THRESHOLD_TOOLTIP = "Сколько дней членства в гильдии И неактивности (без входа в игру) требуется, прежде чем участник может появиться в Списке на исключение, в дополнение к отсутствию вклада вообще. Задаётся отдельно для каждой гильдии.",
        LAM_TIER_NAME_NAME = "Название ранга",
        LAM_TIER_NAME_TOOLTIP = "Переименуйте этот уровень ранга в соответствии с собственной системой вашей гильдии (например, \"VIP\", \"Элита\", \"Доверенный\") вместо стандартного названия.",
        LAM_SALES_THRESHOLD_NAME = "Порог продаж",
        LAM_SALES_THRESHOLD_TOOLTIP = "Общая сумма продаж в магазине (золото), необходимая за период для получения ранга ",
        LAM_DONATION_THRESHOLD_NAME = "Порог пожертвований",
        LAM_DONATION_THRESHOLD_TOOLTIP = "Общая сумма пожертвований (золото), необходимая за период для получения ранга ",
        LAM_LEGEND_MODE_NAME = "Режим присвоения ранга Legend",
        LAM_LEGEND_MODE_TOOLTIP = "Как участники получают ранг Legend: фиксированный порог, или автоматически как лучшие участники за текущий выбранный период.",
        LAM_LEGEND_MODE_THRESHOLD = "Порог (продажи/пожертвования)",
        LAM_LEGEND_MODE_TOP3 = "N лучших продавцов и доноров",
        LAM_LEGEND_TOP3_DESC = "В режиме Top N ранг Legend всегда получают лучшие продавцы и лучшие доноры за текущий выбранный период (На этой неделе, В прошлом месяце и т.д.) - даже если их суммы ниже порога ранга Gold. Количество для каждой категории (по умолчанию 3/3) можно задать ниже. Поля порогов продаж/пожертвований ниже игнорируются, пока активен этот режим.",
        LAM_LEGEND_TOP_SELLERS_COUNT_NAME = "Количество лучших продавцов",
        LAM_LEGEND_TOP_SELLERS_COUNT_TOOLTIP = "Сколько лучших продавцов выбранного периода получают ранг Legend (только в режиме Top N).",
        LAM_LEGEND_TOP_DONORS_COUNT_NAME = "Количество лучших доноров",
        LAM_LEGEND_TOP_DONORS_COUNT_TOOLTIP = "Сколько лучших доноров выбранного периода получают ранг Legend (только в режиме Top N).",
        LAM_HEADER_NOTIFICATIONS = "Уведомления",
        LAM_SCREEN_NOTIF_NAME = "Показывать объявление по центру экрана при новых пожертвованиях",
        LAM_SCREEN_NOTIF_TOOLTIP = "Когда участник делает новое пожертвование, показывает краткое объявление в центре экрана (в том же стиле, что и сообщения об обнаружении заданий/предметов). Срабатывает только для пожертвований, сделанных после входа в игру - не воспроизводит историю.",
        LAM_HEADER_MAIL_TEMPLATE = "Шаблон письма",
        LAM_MAIL_TEMPLATE_DESC = "Настройте шаблон письма для выбранной выше гильдии. Используйте '@' для вставки имени получателя, или '@@' для его полного @UserID. Отправьте его из контекстного меню Списка гильдии (Отправить письмо) - форма письма откроется уже заполненной, отправить нужно будет самому.",
        LAM_MAIL_SUBJECT_NAME = "Тема",
        LAM_MAIL_SUBJECT_TOOLTIP = "Тема письма. '@' заменяется на имя получателя.",
        LAM_MAIL_BODY_NAME = "Текст",
        LAM_MAIL_BODY_TOOLTIP = "Текст письма. '@' заменяется на имя получателя.",
    },
    it = {
        ROSTER_TITLE = "Elenco Gilda",
        TAB_APPROVED = "Approvati",
        TAB_INVITED = "Invitati",
        TAB_JOINED = "Iscritti",
        TAB_REJECTED = "Rifiutati",
        TAB_KICKED = "Espulsi",
        TAB_LEFT = "Usciti",
        TAB_PROMOTED = "Promossi",
        TAB_DEMOTED = "Retrocessi",
        FILTER_ALL = "Tutti",
        FILTER_THIS_WEEK = "Questa Settimana",
        FILTER_7_DAYS = "7 Giorni",
        FILTER_30_DAYS = "30 Giorni",
        OFFICER_STATS = "Statistiche Ufficiali",
        SEARCH_LABEL = "Cerca:",
        COL_TIME = "Ora",
        COL_GUILD = "Gilda",
        COL_OFFICER = "Ufficiale",
        COL_MEMBER = "Membro",

        LEDGER_TITLE = "SISTEMA CONTABILE DELLA GILDA",
        ROW_BANK_GOLD = "Oro della Banca",
        BANK_GOLD_LAST_SEEN = "ultimo aggiornamento",
        BANK_GOLD_UNAVAILABLE = "N/D (apri la banca della gilda una volta in questa sessione per abilitarlo)",
        ROW_SALES_VOLUME = "Volume Vendite Negozio",
        ROW_TAX_REVENUE = "Entrate Fiscali della Gilda",
        ROW_DEPOSITS = "Depositi dei Membri",
        ROW_WITHDRAWALS = "Prelievi dalla Banca",
        ROW_TRADER_EXPENSE = "Affitto Mercante e Offerte",
        ROW_CURRENT_TRADER = "Mercante Attuale",
        ROW_CURRENT_BIDS = "Offerte Mercante Attuali",
        ROW_AVAILABLE_FUNDS = "Fondi Gilda Disponibili",
        NET_PROFIT_LABEL = "PROFITTO",
        NET_LOSS_LABEL = "PERDITA",
        ROW_NET_PROFIT = "PROFITTO / PERDITA NETTA",
        PANEL_DONORS_SELLERS = "MIGLIORI DONATORI E VENDITORI (questo periodo)",
        PANEL_DONORS_SELLERS_BASE = "MIGLIORI DONATORI E VENDITORI",
        PANEL_DONORS = "DONATORI",
        PANEL_SELLERS = "MIGLIORI VENDITORI",
        PANEL_BIDS = "OFFERTE DI QUESTO PERIODO (fino a 10)",
        PANEL_BIDS_BASE = "OFFERTE (fino a 10)",
        PANEL_KIOSKS = "STORIA MERCANTI (TUTTE LE GILDE)",
        PANEL_RANKS = "RANGHI DEI MEMBRI (questa gilda, questo periodo)",
        PANEL_RANKS_BASE = "RANGHI DEI MEMBRI",
        BTN_REFRESH = "Aggiorna",
        BTN_KIOSKS = "Chioschi",
        BTN_RANKS = "Ranghi",
        BTN_CLEAR_FILTER = "Rimuovi Filtro",
        BTN_MEMBER_SEARCH = "Cerca",
        SEARCH_PANEL_TITLE = "RICERCA MEMBRO",
        SEARCH_PANEL_HINT = "Digita il nome di un membro per cercare le sue donazioni, vendite e acquisti nella gilda/periodo selezionati.",
        LEDGER_NOTE_PREFIX = "Nota:",
        EDIT_NOTE_TITLE = "NOTA PERSONALE (TGA)",
        EDIT_NOTE_SUBTITLE = "Per <<1>> - visibile solo a te, mai inviata al server.",
        EDIT_NOTE_XML_OUTDATED = "GuildLedger.xml sembra essere una versione obsoleta - la finestra \"Modifica Nota\" non e stata trovata. Aggiorna tutti i file dell'addon (specialmente i file .xml).",
        SEARCH_PANEL_NONE = "Nessuna attivita corrispondente per questa gilda/periodo.",
        LEDGER_LABEL_DONATIONS = "Donazioni",
        LEDGER_LABEL_SALES = "Vendite",
        LEDGER_LABEL_PURCHASES = "Acquisti",
        SEARCH_FILTER_ACTIVE = "Filtrato",
        STATUS_PROCESSING = "Elaborazione dati...",
        STATUS_NO_VALID_GUILD = "Nessuna gilda valida selezionata.",
        RANKS_SUBTITLE = "Membri che soddisfano i requisiti nel periodo selezionato (potrebbero gia avere questi ranghi)",
        RANKS_NONE_QUALIFY = "Nessun membro raggiunge una soglia di rango in questo periodo. Regola le soglie nelle Impostazioni Ranghi se necessario.",
        KIOSKS_NONE_YET = "Nessuna attivita mercante ancora registrata (o LibHistoire e ancora in sincronizzazione).",
        KIOSK_CURRENT_TAG = "ATTUALE",
        DONORS_NONE = "Nessuna donazione in questo periodo.",
        SELLERS_NONE = "Nessuna vendita in questo periodo.",
        BIDS_NONE = "Nessuna offerta effettuata in questo periodo.",
        CONFIRMED_EXPENSES_TITLE = "SPESE MERCANTE CONFERMATE (questo periodo)",
        CONFIRMED_EXPENSES_NONE = "Nessuna confermata ancora.",
        CHAT_LIBHISTOIRE_MISSING = "LibHistoire non trovato. Installa prima LibHistoire.",
        CHAT_TRACKING_STARTED = "Tracciamento dati finanziari avviato (<<1>> gilda/e).",
        DONATION_ANNOUNCE_FORMAT = "<<1>> ha donato <<2>> a <<3>>",
        ROSTER_STATS_NO_DATA = "Ancora nessun dato per i filtri attuali.",
        ROSTER_STATS_TITLE = "Riepilogo Attivita Ufficiali (rispetta i filtri Gilda/Data/Ricerca sopra)",
        PERIOD_THIS_WEEK = "Questa Settimana",
        PERIOD_LAST_WEEK = "Settimana Scorsa",
        PERIOD_2_WEEKS_AGO = "2 Settimane Fa",
        PERIOD_3_WEEKS_AGO = "3 Settimane Fa",
        PERIOD_4_WEEKS_AGO = "4 Settimane Fa",
        PERIOD_LAST_MONTH = "Mese Scorso",
        PERIOD_THIS_MONTH = "Questo Mese",
        PERIOD_LAST_30_DAYS = "Ultimi 30 Giorni",
        PERIOD_ALL_TIME = "Sempre (Totale)",

        SUITE_TITLE = "Tiradil's Guild Assistant",
        BTN_GUILD_ROSTER = "Elenco Gilda",
        BTN_GUILD_LEDGER = "Contabilita Gilda",

        LANG_EN = "EN",
        LANG_TR = "TR",
        LANG_DE = "DE",
        LANG_ES = "ES",
        LANG_PL = "PL",
        LANG_RU = "RU",
        LANG_IT = "IT",
        LANG_PT = "PT",

        LAM_RANK_DESCRIPTION = "Un membro si qualifica per un rango se soddisfa la soglia di vendite O quella di donazioni nel periodo selezionato (Questa Settimana / Mese Scorso / ecc. - impostato nella finestra della Contabilita Gilda). Le soglie sono impostate SEPARATAMENTE per ogni gilda - scegli prima una gilda qui sotto.",
        LAM_HEADER_DISPLAY = "Visualizzazione",
        LAM_LANGUAGE_NAME = "Lingua",
        LAM_LANGUAGE_TOOLTIP = "Cambia la lingua di Tiradil's Guild Assistant (titoli principali, schede, colonne, pulsanti, messaggi di stato e pannello impostazioni).",
        LAM_HEADER_ROSTER_INTEGRATION = "Integrazione con l'Elenco Gilda",
        LAM_SHOW_CONTRIB_COLUMN_NAME = "Mostra Colonna Contributi nell'Elenco Gilda",
        LAM_SHOW_CONTRIB_COLUMN_TOOLTIP = "Attiva/disattiva la colonna donazioni/vendite/acquisti che Tiradil aggiunge alla schermata di gioco dell'Elenco Gilda. Disattivarla non elimina i dati - nasconde solo la colonna.",
        LAM_SHOW_RANK_COLUMN_NAME = "Mostra Colonna Rango nell'Elenco Gilda",
        LAM_SHOW_RANK_COLUMN_TOOLTIP = "Attiva/disattiva l'etichetta di rango Legend/Diamond/Gold/Silver/Bronze che Tiradil aggiunge accanto ai nomi dei membri nella schermata di gioco dell'Elenco Gilda. Ha un proprio selettore di periodo (sotto l'intestazione della colonna), indipendente dal periodo della finestra Contabilita e da quello della colonna Contributi.",
        LAM_HEADER_RANK_THRESHOLDS = "Soglie di Rango",
        LAM_GUILD_NAME = "Gilda",
        LAM_GUILD_TOOLTIP = "Di quale gilda stai modificando le soglie di rango qui sotto.",
        LAM_KICK_THRESHOLD_NAME = "Soglia Idoneita Espulsione (giorni)",
        LAM_KICK_THRESHOLD_TOOLTIP = "Quanti giorni di appartenenza alla gilda E inattivita (nessun accesso) sono richiesti prima che un membro possa apparire nella Lista Espulsioni, oltre ad avere zero contributi mai. Impostato separatamente per ogni gilda.",
        LAM_TIER_NAME_NAME = "Nome Rango",
        LAM_TIER_NAME_TOOLTIP = "Rinomina questo livello di rango secondo la denominazione della tua gilda (es. \"VIP\", \"Elite\", \"Fidato\") invece del nome predefinito.",
        LAM_SALES_THRESHOLD_NAME = "Soglia Vendite",
        LAM_SALES_THRESHOLD_TOOLTIP = "Vendite totali del negozio (oro) necessarie nel periodo per qualificarsi per ",
        LAM_DONATION_THRESHOLD_NAME = "Soglia Donazioni",
        LAM_DONATION_THRESHOLD_TOOLTIP = "Donazioni totali (oro) necessarie nel periodo per qualificarsi per ",
        LAM_LEGEND_MODE_NAME = "Modalita Assegnazione Legend",
        LAM_LEGEND_MODE_TOOLTIP = "Come i membri ottengono il rango Legend: una soglia fissa, o automaticamente come i migliori contributori del periodo attualmente selezionato.",
        LAM_LEGEND_MODE_THRESHOLD = "Soglia (Vendite/Donazioni)",
        LAM_LEGEND_MODE_TOP3 = "I Migliori N Venditori e Donatori",
        LAM_LEGEND_TOP3_DESC = "In modalita Top N, Legend sono sempre i migliori venditori e i migliori donatori del periodo attualmente selezionato (Questa Settimana, Mese Scorso, ecc.) - anche se i loro totali sono sotto la soglia Gold. Quanti per ciascuno (predefinito 3/3) puoi impostarlo qui sotto. I campi Soglia Vendite/Donazioni piu sotto vengono ignorati mentre questa modalita e attiva.",
        LAM_LEGEND_TOP_SELLERS_COUNT_NAME = "Numero Migliori Venditori",
        LAM_LEGEND_TOP_SELLERS_COUNT_TOOLTIP = "Quanti migliori venditori del periodo selezionato diventano Legend (solo modalita Top N).",
        LAM_LEGEND_TOP_DONORS_COUNT_NAME = "Numero Migliori Donatori",
        LAM_LEGEND_TOP_DONORS_COUNT_TOOLTIP = "Quanti migliori donatori del periodo selezionato diventano Legend (solo modalita Top N).",
        LAM_HEADER_NOTIFICATIONS = "Notifiche",
        LAM_SCREEN_NOTIF_NAME = "Mostra Annuncio al Centro Schermo per Nuove Donazioni",
        LAM_SCREEN_NOTIF_TOOLTIP = "Quando un membro effettua una nuova donazione, mostra un breve annuncio al centro dello schermo (stesso stile dei messaggi di scoperta missione/oggetto). Si attiva solo per le donazioni effettuate dopo il login - non riproduce la cronologia.",
        LAM_HEADER_MAIL_TEMPLATE = "Modello di Posta",
        LAM_MAIL_TEMPLATE_DESC = "Configura un modello di posta per la gilda selezionata sopra. Usa '@' per inserire il nome del destinatario, o '@@' per il suo @UserID completo. Invialo dal menu contestuale dell'Elenco Gilda (Invia Posta) - il modulo di posta si apre precompilato, premi Invia tu stesso.",
        LAM_MAIL_SUBJECT_NAME = "Oggetto",
        LAM_MAIL_SUBJECT_TOOLTIP = "Riga oggetto della posta. '@' diventa il nome del destinatario.",
        LAM_MAIL_BODY_NAME = "Corpo",
        LAM_MAIL_BODY_TOOLTIP = "Testo del corpo della posta. '@' diventa il nome del destinatario.",
    },
    pt = {
        ROSTER_TITLE = "Lista da Guilda",
        TAB_APPROVED = "Aprovados",
        TAB_INVITED = "Convidados",
        TAB_JOINED = "Aderiram",
        TAB_REJECTED = "Rejeitados",
        TAB_KICKED = "Expulsos",
        TAB_LEFT = "Sairam",
        TAB_PROMOTED = "Promovidos",
        TAB_DEMOTED = "Despromovidos",
        FILTER_ALL = "Todos",
        FILTER_THIS_WEEK = "Esta Semana",
        FILTER_7_DAYS = "7 Dias",
        FILTER_30_DAYS = "30 Dias",
        OFFICER_STATS = "Estatisticas de Oficiais",
        SEARCH_LABEL = "Pesquisar:",
        COL_TIME = "Hora",
        COL_GUILD = "Guilda",
        COL_OFFICER = "Oficial",
        COL_MEMBER = "Membro",

        LEDGER_TITLE = "SISTEMA DE CONTABILIDADE DA GUILDA",
        ROW_BANK_GOLD = "Ouro do Banco",
        BANK_GOLD_LAST_SEEN = "visto pela ultima vez",
        BANK_GOLD_UNAVAILABLE = "N/D (abra o banco da guilda uma vez nesta sessao para ativar)",
        ROW_SALES_VOLUME = "Volume de Vendas da Loja",
        ROW_TAX_REVENUE = "Receita de Impostos da Guilda",
        ROW_DEPOSITS = "Depositos de Membros",
        ROW_WITHDRAWALS = "Levantado do Banco",
        ROW_TRADER_EXPENSE = "Renda do Mercador e Licitacoes",
        ROW_CURRENT_TRADER = "Mercador Atual",
        ROW_CURRENT_BIDS = "Licitacoes de Mercador Atuais",
        ROW_AVAILABLE_FUNDS = "Fundos da Guilda Disponiveis",
        NET_PROFIT_LABEL = "LUCRO",
        NET_LOSS_LABEL = "PREJUIZO",
        ROW_NET_PROFIT = "LUCRO / PREJUIZO LIQUIDO",
        PANEL_DONORS_SELLERS = "MELHORES DOADORES E VENDEDORES (este periodo)",
        PANEL_DONORS_SELLERS_BASE = "MELHORES DOADORES E VENDEDORES",
        PANEL_DONORS = "DOADORES",
        PANEL_SELLERS = "MELHORES VENDEDORES",
        PANEL_BIDS = "LICITACOES DESTE PERIODO (ate 10)",
        PANEL_BIDS_BASE = "LICITACOES (ate 10)",
        PANEL_KIOSKS = "HISTORICO DE MERCADORES (TODAS AS GUILDAS)",
        PANEL_RANKS = "CATEGORIAS DE MEMBROS (esta guilda, este periodo)",
        PANEL_RANKS_BASE = "CATEGORIAS DE MEMBROS",
        BTN_REFRESH = "Atualizar",
        BTN_KIOSKS = "Quiosques",
        BTN_RANKS = "Categorias",
        BTN_CLEAR_FILTER = "Limpar Filtro",
        BTN_MEMBER_SEARCH = "Pesquisar",
        SEARCH_PANEL_TITLE = "PESQUISA DE MEMBRO",
        SEARCH_PANEL_HINT = "Escreva o nome de um membro para pesquisar as suas doacoes, vendas e compras na guilda/periodo selecionados.",
        LEDGER_NOTE_PREFIX = "Nota:",
        EDIT_NOTE_TITLE = "NOTA PESSOAL (TGA)",
        EDIT_NOTE_SUBTITLE = "Para <<1>> - visivel apenas para si, nunca enviada ao servidor.",
        EDIT_NOTE_XML_OUTDATED = "O ficheiro GuildLedger.xml parece estar desatualizado - a janela \"Editar Nota\" nao foi encontrada. Por favor atualize todos os ficheiros do addon (especialmente os ficheiros .xml).",
        SEARCH_PANEL_NONE = "Nenhuma atividade correspondente para esta guilda/periodo.",
        LEDGER_LABEL_DONATIONS = "Doacoes",
        LEDGER_LABEL_SALES = "Vendas",
        LEDGER_LABEL_PURCHASES = "Compras",
        SEARCH_FILTER_ACTIVE = "Filtrado",
        STATUS_PROCESSING = "A processar dados...",
        STATUS_NO_VALID_GUILD = "Nenhuma guilda valida selecionada.",
        RANKS_SUBTITLE = "Membros que cumprem os requisitos no periodo selecionado (podem ja ter estas categorias)",
        RANKS_NONE_QUALIFY = "Nenhum membro atinge um limiar de categoria neste periodo. Ajuste os limiares nas Definicoes de Categorias se necessario.",
        KIOSKS_NONE_YET = "Ainda nao foi registada atividade de mercadores (ou o LibHistoire ainda esta a sincronizar).",
        KIOSK_CURRENT_TAG = "ATUAL",
        DONORS_NONE = "Sem doacoes neste periodo.",
        SELLERS_NONE = "Sem vendas neste periodo.",
        BIDS_NONE = "Nenhuma licitacao feita neste periodo.",
        CONFIRMED_EXPENSES_TITLE = "DESPESAS DE MERCADOR CONFIRMADAS (este periodo)",
        CONFIRMED_EXPENSES_NONE = "Nenhuma confirmada ainda.",
        CHAT_LIBHISTOIRE_MISSING = "LibHistoire nao encontrado. Por favor instale primeiro o LibHistoire.",
        CHAT_TRACKING_STARTED = "Rastreio de dados financeiros iniciado (<<1>> guilda(s)).",
        DONATION_ANNOUNCE_FORMAT = "<<1>> doou <<2>> a <<3>>",
        ROSTER_STATS_NO_DATA = "Ainda sem dados para os filtros atuais.",
        ROSTER_STATS_TITLE = "Resumo de Atividade dos Oficiais (respeita os filtros de Guilda/Data/Pesquisa acima)",
        PERIOD_THIS_WEEK = "Esta Semana",
        PERIOD_LAST_WEEK = "Semana Passada",
        PERIOD_2_WEEKS_AGO = "Ha 2 Semanas",
        PERIOD_3_WEEKS_AGO = "Ha 3 Semanas",
        PERIOD_4_WEEKS_AGO = "Ha 4 Semanas",
        PERIOD_LAST_MONTH = "Mes Passado",
        PERIOD_THIS_MONTH = "Este Mes",
        PERIOD_LAST_30_DAYS = "Ultimos 30 Dias",
        PERIOD_ALL_TIME = "Desde Sempre (Total)",

        SUITE_TITLE = "Tiradil's Guild Assistant",
        BTN_GUILD_ROSTER = "Lista da Guilda",
        BTN_GUILD_LEDGER = "Contabilidade da Guilda",

        LANG_EN = "EN",
        LANG_TR = "TR",
        LANG_DE = "DE",
        LANG_ES = "ES",
        LANG_PL = "PL",
        LANG_RU = "RU",
        LANG_IT = "IT",
        LANG_PT = "PT",

        LAM_RANK_DESCRIPTION = "Um membro qualifica-se para uma categoria se cumprir o limiar de vendas OU o limiar de doacoes no periodo selecionado (Esta Semana / Mes Passado / etc. - definido na janela de Contabilidade da Guilda). Os limiares sao definidos SEPARADAMENTE por guilda - escolha primeiro uma guilda abaixo.",
        LAM_HEADER_DISPLAY = "Visualizacao",
        LAM_LANGUAGE_NAME = "Idioma",
        LAM_LANGUAGE_TOOLTIP = "Altera o idioma do Tiradil's Guild Assistant (titulos principais, separadores, colunas, botoes, mensagens de estado e painel de definicoes).",
        LAM_HEADER_ROSTER_INTEGRATION = "Integracao com a Lista da Guilda",
        LAM_SHOW_CONTRIB_COLUMN_NAME = "Mostrar Coluna de Contribuicao na Lista da Guilda",
        LAM_SHOW_CONTRIB_COLUMN_TOOLTIP = "Ativa/desativa a coluna de doacoes/vendas/compras que o Tiradil adiciona ao ecra de Lista da Guilda do jogo. Desativar isto nao apaga dados - apenas oculta a coluna.",
        LAM_SHOW_RANK_COLUMN_NAME = "Mostrar Coluna de Categoria na Lista da Guilda",
        LAM_SHOW_RANK_COLUMN_TOOLTIP = "Ativa/desativa a etiqueta de categoria Legend/Diamond/Gold/Silver/Bronze que o Tiradil adiciona junto aos nomes dos membros no ecra de Lista da Guilda do jogo. Tem o seu proprio seletor de periodo (abaixo do cabecalho da coluna), independente do periodo da janela de Contabilidade e do periodo da coluna de Contribuicao.",
        LAM_HEADER_RANK_THRESHOLDS = "Limiares de Categoria",
        LAM_GUILD_NAME = "Guilda",
        LAM_GUILD_TOOLTIP = "De que guilda esta a editar os limiares de categoria abaixo.",
        LAM_KICK_THRESHOLD_NAME = "Limiar de Elegibilidade para Expulsao (dias)",
        LAM_KICK_THRESHOLD_TOOLTIP = "Quantos dias de pertenca a guilda E inatividade (sem login) sao necessarios antes que um membro possa aparecer na Lista de Expulsao, alem de nunca ter tido contribuicoes. Definido separadamente por guilda.",
        LAM_TIER_NAME_NAME = "Nome da Categoria",
        LAM_TIER_NAME_TOOLTIP = "Renomeie esta categoria de acordo com a nomenclatura da sua guilda (ex. \"VIP\", \"Elite\", \"Confiavel\") em vez do nome predefinido.",
        LAM_SALES_THRESHOLD_NAME = "Limiar de Vendas",
        LAM_SALES_THRESHOLD_TOOLTIP = "Total de vendas na loja (ouro) necessario no periodo para se qualificar para ",
        LAM_DONATION_THRESHOLD_NAME = "Limiar de Doacoes",
        LAM_DONATION_THRESHOLD_TOOLTIP = "Total de doacoes (ouro) necessario no periodo para se qualificar para ",
        LAM_LEGEND_MODE_NAME = "Modo de Atribuicao Legend",
        LAM_LEGEND_MODE_TOOLTIP = "Como os membros obtem a categoria Legend: um limiar fixo, ou automaticamente como os melhores contribuintes do periodo atualmente selecionado.",
        LAM_LEGEND_MODE_THRESHOLD = "Limiar (Vendas/Doacoes)",
        LAM_LEGEND_MODE_TOP3 = "Os N Melhores Vendedores e Doadores",
        LAM_LEGEND_TOP3_DESC = "No modo Top N, Legend sao sempre os melhores vendedores e melhores doadores do periodo atualmente selecionado (Esta Semana, Mes Passado, etc.) - mesmo que os seus totais estejam abaixo do limiar Gold. Quantos de cada (predefinido 3/3) pode ser definido abaixo. Os campos de Limiar de Vendas/Doacoes mais abaixo sao ignorados enquanto este modo estiver ativo.",
        LAM_LEGEND_TOP_SELLERS_COUNT_NAME = "Numero de Melhores Vendedores",
        LAM_LEGEND_TOP_SELLERS_COUNT_TOOLTIP = "Quantos dos melhores vendedores do periodo selecionado se tornam Legend (apenas no modo Top N).",
        LAM_LEGEND_TOP_DONORS_COUNT_NAME = "Numero de Melhores Doadores",
        LAM_LEGEND_TOP_DONORS_COUNT_TOOLTIP = "Quantos dos melhores doadores do periodo selecionado se tornam Legend (apenas no modo Top N).",
        LAM_HEADER_NOTIFICATIONS = "Notificacoes",
        LAM_SCREEN_NOTIF_NAME = "Mostrar Anuncio no Centro do Ecra em Novas Doacoes",
        LAM_SCREEN_NOTIF_TOOLTIP = "Quando um membro faz uma nova doacao, mostra um breve anuncio no centro do seu ecra (mesmo estilo das mensagens de descoberta de missao/item). So e ativado para doacoes feitas apos o login - nao reproduz o historico.",
        LAM_HEADER_MAIL_TEMPLATE = "Modelo de Correio",
        LAM_MAIL_TEMPLATE_DESC = "Configure um modelo de correio para a guilda selecionada acima. Use '@' para inserir o nome do destinatario, ou '@@' para o seu @UserID completo. Envie-o a partir do menu de contexto da Lista da Guilda (Enviar Correio) - o formulario de correio abre pre-preenchido, e voce mesmo que clica em Enviar.",
        LAM_MAIL_SUBJECT_NAME = "Assunto",
        LAM_MAIL_SUBJECT_TOOLTIP = "Linha de assunto do correio. '@' torna-se no nome do destinatario.",
        LAM_MAIL_BODY_NAME = "Corpo",
        LAM_MAIL_BODY_TOOLTIP = "Texto do corpo do correio. '@' torna-se no nome do destinatario.",
    },
}

function TiradilL10n.Get(key)
    local lang = (GuildLedger_SavedVars and GuildLedger_SavedVars.language) or "en"
    local dict = STRINGS[lang] or STRINGS.en
    return dict[key] or STRINGS.en[key] or key
end

function TiradilL10n.RefreshAll()
    local L = TiradilL10n.Get

    if TiradilRosterWindowTitle then TiradilRosterWindowTitle:SetText(L("ROSTER_TITLE") .. " - Tiradil") end
    if TiradilRosterWindowTab1 then TiradilRosterWindowTab1:SetText(L("TAB_APPROVED")) end
    if TiradilRosterWindowTab2 then TiradilRosterWindowTab2:SetText(L("TAB_INVITED")) end
    if TiradilRosterWindowTab3 then TiradilRosterWindowTab3:SetText(L("TAB_JOINED")) end
    if TiradilRosterWindowTab4 then TiradilRosterWindowTab4:SetText(L("TAB_REJECTED")) end
    if TiradilRosterWindowTab5 then TiradilRosterWindowTab5:SetText(L("TAB_KICKED")) end
    if TiradilRosterWindowTab6 then TiradilRosterWindowTab6:SetText(L("TAB_LEFT")) end
    if TiradilRosterWindowTab7 then TiradilRosterWindowTab7:SetText("|c66FF66^|r " .. L("TAB_PROMOTED")) end
    if TiradilRosterWindowTab8 then TiradilRosterWindowTab8:SetText("|cFF6666v|r " .. L("TAB_DEMOTED")) end
    if TiradilRosterWindowGF0 then TiradilRosterWindowGF0:SetText(L("FILTER_ALL")) end
    if TiradilRosterWindowDFWeek then TiradilRosterWindowDFWeek:SetText(L("FILTER_THIS_WEEK")) end
    if TiradilRosterWindowDFD7 then TiradilRosterWindowDFD7:SetText(L("FILTER_7_DAYS")) end
    if TiradilRosterWindowDFD30 then TiradilRosterWindowDFD30:SetText(L("FILTER_30_DAYS")) end
    if TiradilRosterWindowDFAll then TiradilRosterWindowDFAll:SetText(L("FILTER_ALL")) end
    if TiradilRosterWindowStatsBtn then TiradilRosterWindowStatsBtn:SetText(L("OFFICER_STATS")) end
    if TiradilRosterWindowSearchLabel then TiradilRosterWindowSearchLabel:SetText(L("SEARCH_LABEL")) end
    if TiradilRosterWindowColTime then TiradilRosterWindowColTime:SetText(L("COL_TIME")) end
    if TiradilRosterWindowColGuild then TiradilRosterWindowColGuild:SetText(L("COL_GUILD")) end
    if TiradilRosterWindowColFrom then TiradilRosterWindowColFrom:SetText(L("COL_OFFICER")) end
    if TiradilRosterWindowColTo then TiradilRosterWindowColTo:SetText(L("COL_MEMBER")) end

    if GuildLedgerFrameHeaderTitle then GuildLedgerFrameHeaderTitle:SetText(L("LEDGER_TITLE")) end
    if GuildLedgerFrameBodyStatsColumnRow1Label then GuildLedgerFrameBodyStatsColumnRow1Label:SetText(L("ROW_BANK_GOLD")) end
    if GuildLedgerFrameBodyStatsColumnRow2Label then GuildLedgerFrameBodyStatsColumnRow2Label:SetText(L("ROW_SALES_VOLUME")) end
    if GuildLedgerFrameBodyStatsColumnRow3Label then GuildLedgerFrameBodyStatsColumnRow3Label:SetText(L("ROW_TAX_REVENUE")) end
    if GuildLedgerFrameBodyStatsColumnRow4Label then GuildLedgerFrameBodyStatsColumnRow4Label:SetText(L("ROW_DEPOSITS")) end
    if GuildLedgerFrameBodyStatsColumnRow5Label then GuildLedgerFrameBodyStatsColumnRow5Label:SetText(L("ROW_WITHDRAWALS")) end
    if GuildLedgerFrameBodyStatsColumnRow6Label then GuildLedgerFrameBodyStatsColumnRow6Label:SetText(L("ROW_TRADER_EXPENSE")) end
    if GuildLedgerFrameBodyStatsColumnRow7Label then GuildLedgerFrameBodyStatsColumnRow7Label:SetText(L("ROW_CURRENT_BIDS")) end
    if GuildLedgerFrameBodyStatsColumnRow8Label then GuildLedgerFrameBodyStatsColumnRow8Label:SetText(L("ROW_AVAILABLE_FUNDS")) end
    if GuildLedgerFrameBodyStatsColumnNetLabel then GuildLedgerFrameBodyStatsColumnNetLabel:SetText(L("ROW_NET_PROFIT")) end
    if GuildLedgerFrameBodyDonationsPanelDonorsSubtitle then GuildLedgerFrameBodyDonationsPanelDonorsSubtitle:SetText(L("PANEL_DONORS")) end
    if GuildLedgerFrameBodyDonationsPanelSellersSubtitle then GuildLedgerFrameBodyDonationsPanelSellersSubtitle:SetText(L("PANEL_SELLERS")) end
    if GuildLedgerFrameKiosksPanelTitle then GuildLedgerFrameKiosksPanelTitle:SetText(L("PANEL_KIOSKS")) end
    if GuildLedgerFrameRanksPanelSubtitle then GuildLedgerFrameRanksPanelSubtitle:SetText(L("RANKS_SUBTITLE")) end
    if GuildLedgerFrameSearchPanelTitle then GuildLedgerFrameSearchPanelTitle:SetText(L("SEARCH_PANEL_TITLE")) end
    if GuildLedgerFrameSearchPanelHint and (GuildLedger and GuildLedger.searchPanelQuery or "") == "" then
        GuildLedgerFrameSearchPanelHint:SetText(L("SEARCH_PANEL_HINT"))
    end
    if GuildLedger and GuildLedger.UpdatePanelTitles then
        GuildLedger.UpdatePanelTitles()
    end
    if GuildLedgerFrameFooterRefreshBtn then GuildLedgerFrameFooterRefreshBtn:SetText(L("BTN_REFRESH")) end
    if GuildLedgerFrameFooterKiosksBtn then GuildLedgerFrameFooterKiosksBtn:SetText(L("BTN_KIOSKS")) end
    if GuildLedgerFrameFooterRanksBtn then GuildLedgerFrameFooterRanksBtn:SetText(L("BTN_RANKS")) end
    if GuildLedgerFrameFooterSearchBtn then GuildLedgerFrameFooterSearchBtn:SetText(L("BTN_MEMBER_SEARCH")) end
    if GuildLedgerFrameFooterClearFilterBtn then GuildLedgerFrameFooterClearFilterBtn:SetText(L("BTN_CLEAR_FILTER")) end
    if GuildLedgerFrameFooterStatus and GuildLedgerFrameFooterStatus:GetText() == "Processing data..." then
        GuildLedgerFrameFooterStatus:SetText(L("STATUS_PROCESSING"))
    end
    if GuildLedger and GuildLedger.RebuildCombos then
        GuildLedger.RebuildCombos()
    end

    if TiradilGuildAssistantWindowTitle then TiradilGuildAssistantWindowTitle:SetText(L("SUITE_TITLE")) end
    if TiradilGuildAssistantWindowRosterBtn then TiradilGuildAssistantWindowRosterBtn:SetText(L("BTN_GUILD_ROSTER")) end
    if TiradilGuildAssistantWindowLedgerBtn then TiradilGuildAssistantWindowLedgerBtn:SetText(L("BTN_GUILD_LEDGER")) end
    if TiradilGuildAssistantWindowInactiveWatchBtn and TiradilIWL10n then TiradilGuildAssistantWindowInactiveWatchBtn:SetText(TiradilIWL10n.Get("BTN_LAUNCHER")) end

    if TGA_LAM_LanguageDropdown then TGA_LAM_LanguageDropdown.label:SetText(L("LAM_LANGUAGE_NAME")) end
    if TGA_LAM_ShowContribColumn then TGA_LAM_ShowContribColumn.label:SetText(L("LAM_SHOW_CONTRIB_COLUMN_NAME")) end
    if TGA_LAM_ShowRankColumn then TGA_LAM_ShowRankColumn.label:SetText(L("LAM_SHOW_RANK_COLUMN_NAME")) end
    if TGA_LAM_ScreenNotif then TGA_LAM_ScreenNotif.label:SetText(L("LAM_SCREEN_NOTIF_NAME")) end
    if TGA_LAM_MailSubject then TGA_LAM_MailSubject.label:SetText(L("LAM_MAIL_SUBJECT_NAME")) end
    if TGA_LAM_MailBody then TGA_LAM_MailBody.label:SetText(L("LAM_MAIL_BODY_NAME")) end
    if TGA_LAM_GuildDropdown then TGA_LAM_GuildDropdown.label:SetText(L("LAM_GUILD_NAME")) end
    if TGA_LAM_KickThresholdSlider then TGA_LAM_KickThresholdSlider.label:SetText(L("LAM_KICK_THRESHOLD_NAME")) end
    if TGA_LAM_LegendModeDropdown then TGA_LAM_LegendModeDropdown.label:SetText(L("LAM_LEGEND_MODE_NAME")) end
    if TGA_LAM_TopSellersSlider then TGA_LAM_TopSellersSlider.label:SetText(L("LAM_LEGEND_TOP_SELLERS_COUNT_NAME")) end
    if TGA_LAM_TopDonorsSlider then TGA_LAM_TopDonorsSlider.label:SetText(L("LAM_LEGEND_TOP_DONORS_COUNT_NAME")) end
    for i = 1, 5 do
        local salesRef = _G["TGA_LAM_SalesThreshold_" .. i]
        if salesRef then salesRef.label:SetText(L("LAM_SALES_THRESHOLD_NAME")) end
        local donationRef = _G["TGA_LAM_DonationThreshold_" .. i]
        if donationRef then donationRef.label:SetText(L("LAM_DONATION_THRESHOLD_NAME")) end
        local tierNameRef = _G["TGA_LAM_TierName_" .. i]
        if tierNameRef then tierNameRef.label:SetText(L("LAM_TIER_NAME_NAME")) end
    end
end
