ZO_CreateStringId(Banker.SI.BANKER_NAME,										"Bankier")
ZO_CreateStringId(Banker.SI.HEADER_SETTINGS,									"Beschreibung")
ZO_CreateStringId(Banker.SI.HEADER_ITEM_TYPES,									"ItemTypen")
ZO_CreateStringId(Banker.SI.WARNING_ITEM_TYPES,									"Stelle auf Ein um Items von diesem Typ automatisch in die Bank zu transferieren,falls das Item schon in der Bank liegt.")
ZO_CreateStringId(Banker.SI.DESC_MAIN_TITLE,									"Beschreibung")
ZO_CreateStringId(Banker.SI.DESC_MAIN,											"Banker ist eine Mod, die dir hilft dein Inventar aufzur\195\164umen.Daf\195\188 r werden Items in deine Bank verschoben, die bereits vorhanden sind.")
ZO_CreateStringId(Banker.SI.HEADER_DEVELOPER,									"Entwickler Einstellung")
ZO_CreateStringId(Banker.SI.ITEMTYPE_TITLE,										"Itemtype")
ZO_CreateStringId(Banker.SI.ITEMTYPE_DESC,										"Itemtype Description")
ZO_CreateStringId(Banker.SI.TITLE_DEBUG,										"Zeige Debug-Informationen")
ZO_CreateStringId(Banker.SI.COMMON_TITLE,										"Allgemeine Einstellungen")
ZO_CreateStringId(Banker.SI.COMMON_DESC,										"")
ZO_CreateStringId(Banker.SI.WARNING_DEVELOPER,									"Wenn du nicht wei�t was diese Option macht, dann lass die Finger davon.")
ZO_CreateStringId(Banker.SI.MIN_TITLE,											"Gold Minimum")
ZO_CreateStringId(Banker.SI.STEP_TITLE,											"Schritt")
ZO_CreateStringId(Banker.SI.EITEMS_TITLE,										"Item-Transfer")
ZO_CreateStringId(Banker.SI.EMONEY_TITLE,										"Money-Transfer")
ZO_CreateStringId(Banker.SI.MSG_TITLE,											"Zeige Chat-Nachrichten")
ZO_CreateStringId(Banker.SI.DEBUG_TITLE,										"Zeige Debug-Nachrichten")
ZO_CreateStringId(Banker.SI.KB_TITLE,											"Zeige Shortcut")
ZO_CreateStringId(Banker.SI.KB_SYNC_ITEMS,										"Synchronisiere Bank und Tasche")
ZO_CreateStringId(Banker.SI.KB_SAFE_MONEY,										"Geldeinzahlen")
ZO_CreateStringId(Banker.SI.BINDING_NAME_SYNC_INVENTORY,     					"Synchronisiere Bank und Tasche")
ZO_CreateStringId(Banker.SI.BINDING_NAME_AUTO_DEPOSIT_MONEY, 					"Geldeinzahlen")