-- ---------------------------------------------------------------------------
-- Thresholds - shipped trial boss data
-- GENERATED by tools/generate_boss_data.py - DO NOT EDIT BY HAND
--
-- Keyed by in-game zoneId; boss names are English client unit names.
-- Value per boss: `true` = known boss (no shipped thresholds), or a
-- descending list of default threshold percentages.
-- ---------------------------------------------------------------------------

Thresholds.BossData = {
    [636] = { -- Hel Ra Citadel (HRC)
        name = "Hel Ra Citadel",
        bosses = {
            ["Ra Kotu"] = true, -- derived from encounter name, unverified
            ["Yokeda Kai"] = true, -- confirmed via UESP/guides
            ["Yokeda Rok'dun"] = true, -- confirmed via UESP/guides
            ["The Warrior"] = true,
        },
    },
    [638] = { -- Aetherian Archive (AA)
        name = "Aetherian Archive",
        bosses = {
            ["Lightning Storm Atronach"] = true, -- derived from encounter name, unverified
            ["Foundation Stone Atronach"] = true, -- derived from encounter name, unverified
            ["Varlariel"] = true, -- derived from encounter name, unverified
            ["The Mage"] = true,
        },
    },
    [639] = { -- Sanctum Ophidia (SO)
        name = "Sanctum Ophidia",
        bosses = {
            ["Possessed Mantikora"] = true, -- derived from encounter name, unverified
            ["Stonebreaker"] = true, -- derived from encounter name, unverified
            ["Ozara"] = true, -- derived from encounter name, unverified
            ["The Serpent"] = true,
        },
    },
    [725] = { -- Maw of Lorkhaj (MoL)
        name = "Maw of Lorkhaj",
        bosses = {
            ["Zhaj'hassa The Forgotten"] = true, -- derived from encounter name, unverified
            ["Vashai"] = true, -- confirmed via UESP/guides
            ["S'kinrai"] = true, -- confirmed via UESP/guides
            ["Rakkhat"] = true,
        },
    },
    [975] = { -- Halls of Fabrication (HoF)
        name = "Halls of Fabrication",
        bosses = {
            ["Hunter-Killer Positrox"] = true, -- confirmed via UESP/guides
            ["Hunter-Killer Negatrix"] = true, -- confirmed via UESP/guides
            ["Pinnacle Factotum"] = true, -- derived from encounter name, unverified
            ["Archcustodian"] = true, -- derived from encounter name, unverified
            ["Reducer"] = true, -- confirmed via UESP/guides
            ["Reclaimer"] = true, -- confirmed via UESP/guides
            ["Reactor"] = true, -- confirmed via UESP/guides
            ["Assembly General"] = true,
        },
    },
    [1000] = { -- Asylum Sanctorium (AS)
        name = "Asylum Sanctorium",
        bosses = {
            ["Saint Llothis the Pious"] = true,
            ["Saint Felms the Bold"] = true,
            ["Saint Olms the Just"] = true,
        },
    },
    [1051] = { -- Cloudrest (CR)
        name = "Cloudrest",
        bosses = {
            ["Shade of Galenwe"] = true, -- derived from encounter name, unverified
            ["Shade of Relequen"] = true, -- derived from encounter name, unverified
            ["Shade of Siroria"] = true, -- derived from encounter name, unverified
            ["Z'Maja"] = true,
        },
    },
    [1121] = { -- Sunspire (SS)
        name = "Sunspire",
        bosses = {
            ["Lokkestiiz"] = true,
            ["Yolnahkriin"] = true,
            ["Nahviintaas"] = true,
        },
    },
    [1196] = { -- Kyne's Aegis (KA)
        name = "Kyne's Aegis",
        bosses = {
            ["Yandir the Butcher"] = true,
            ["Captain Vrol"] = true,
            ["Lord Falgravn"] = true,
        },
    },
    [1263] = { -- Rockgrove (RG)
        name = "Rockgrove",
        bosses = {
            ["Oaxiltso"] = true,
            ["Flame-Herald Bahsei"] = true,
            ["Xalvakka"] = true,
        },
    },
    [1344] = { -- Dreadsail Reef (DSR)
        name = "Dreadsail Reef",
        bosses = {
            ["Lylanar"] = true,
            ["Turlassil"] = true,
            ["Reef Guardian"] = true,
            ["Tideborn Taleria"] = true,
        },
    },
    [1427] = { -- Sanity's Edge (SE)
        name = "Sanity's Edge",
        bosses = {
            ["Exarchanic Yaseyla"] = true,
            ["Archwizard Twelvane"] = true,
            ["Chimera"] = true,
            ["Ansuul the Tormentor"] = true,
        },
    },
    [1478] = { -- Lucent Citadel (LC)
        name = "Lucent Citadel",
        bosses = {
            ["Count Ryelaz"] = true,
            ["Zilyesset"] = true,
            ["Orphic Shattered Shard"] = true,
            ["Xoryn"] = true,
        },
    },
    [1548] = { -- Ossein Cage (OC)
        name = "Ossein Cage",
        bosses = {
            ["Shaper of Flesh"] = true,
            ["Jynorah"] = true,
            ["Skorkhif"] = true,
            ["Overfiend Kazpian"] = true,
        },
    },
}
