-- Monster difficulty data provided by https://en.uesp.net/wiki/Online:Creatures. Thank you!

CZT_EXCLUDED_MONSTER_NAMES = {
  
"argonischer behemoth",
"avrusa duleri",
"beobachter",
"daedrischer titan",
"daedroth",
"der beobachter",
"die schwärmende woge",
"draugr-leichnam",
"draugr-sturmfürstin",
"dremora-kynvogt",
"drovos nelvayn",
"drublog-mammut",
"dwemersphäre",
"dwemersphärenmeister",
"dwemerzenturio",
"eisenatronach",
"eisenkopf",
"ernterin",
"flusstroll",
"frostatronach",
"frostbissspinne",
"frosttroll",
"gargyl",
"gefäß der würmer",
"geisterriese",
"haj-mota",
"hauptmann jena apinia",
"heimgesuchter zenturio",
"himmlischen-fledermaus",
"himmlischen-skorpion",
"hunger",
"irrlichtmutter",
"justiziarin avanaire",
"kaiser tarish-zi",
"klippenhammerriese",
"knochenkoloss",
"krähenschrecken",
"leutnant lepida",
"mammut",
"mantikor",
"minotauren",
"minotaurenschamane",
"morastmergler",
"nereïde",
"nereïdenkaiserin",
"netchbulle",
"riese",
"riesenskorpion",
"rosathild",
"schatten-blutunholdin",
"schleiererbe-koloss",
"spinnendaedra",
"sturmatronach",
"titan",
"troll",
"tundramammut",
"waldmammut",
"wamasu",
"weißsturzriese",
"zalar-do",
"zunderfliegenstock-golem",
"zwielichtschrecken",
"zylara",

}