-- Monster difficulty data provided by https://en.uesp.net/wiki/Online:Creatures. Thank you!

CZT_EXCLUDED_MONSTER_NAMES = {

"argonian behemoth",
"avrusa duleri",
"bone colossus",
"bull netch",
"captain jena apinia",
"celestial bat",
"celestial scorpion",
"craghammer giant",
"daedric titan",
"daedroth",
"draugr corpse",
"draugr stormlord",
"dremora kynreeve",
"drovos nelvayn",
"drublog mammoth",
"dwarven centurion",
"dwarven sphere",
"dwarven sphere master",
"emperor tarish-zi",
"fetcherfly hive golem",
"frost atronach",
"frost troll",
"frostbite spider",
"gargoyle",
"giant scorpion",
"giant",
"grievous twilight",
"haj mota",
"harvester",
"haunted centurion",
"hive golem",
"hunger",
"iron atronach",
"iron head",
"justiciar avanaire",
"mammoth",
"mantikora",
"minotaur shaman",
"minotaur",
"miregaunt",
"lieutenant lepida",
"rosathild",
"nereid empress",
"nereid",
"river troll",
"shadow bloodfiend",
"spider daedra",
"spirit giant",
"storm atronach",
"the swarming tide",
"timber mammoth",
"titan",
"troll",
"tundra mammoth",
"veiled colossus",
"vessel of worms",
"wamasu",
"watcher",
"white fall giant",
"wispmother",
"wraith-of-crows",
"zalar-do",
"zylara",

}