-- Monster difficulty data provided by https://en.uesp.net/wiki/Online:Creatures. Thank you!

CZT_EXCLUDED_MONSTER_NAMES = {

"arachnide daedrique",
"atronach de fer",
"atronach de foudre",
"atronach de glace",
"avrusa duleri",
"béhémoth argonien",
"cadavre de draugr",
"centurion dwemer",
"centurion hanté",
"chaman minotaure",
"chauve-souris céleste",
"colosse squelette",
"colosse voilé",
"crépuscule périlleux",
"daedroth",
"dame des tempêtes draugr",
"dévoreur",
"drovos nelvayn",
"fangeux émacié",
"gardien",
"gargouille",
"géant de la chute blanche",
"géant de pierremartel",
"géant spirituel",
"géant",
"givrépeire",
"golem de mouches chercheuses",
"golem de ruche",
"haj mota",
"impératrice néréide",
"kynreeve drémora",
"l’empereur tarish-zi",
"la justiciar avanairë",
"la marée implacable",
"le capitaine jena apinia",
"le dévoreur",
"le gardien",
"le lieutenant lépida",
"lucereine",
"maître de sphère dwemer",
"mammouth de la toundra",
"mammouth drublog",
"mammouth sylvestre",
"mammouth",
"mantikora",
"minotaur",
"minotaure",
"moissonneur",
"moissonneuse",
"néréide",
"netch mâle",
"rosathilde",
"sangrebête d'ombres",
"scorpion céleste",
"scorpion géant",
"spectre-des-corbeaux",
"sphère dwemer",
"titan daedrique",
"titan",
"tête de fer",
"troll de givre",
"troll de rivière",
"troll",
"vaisseau des vers",
"wamasu",
"zalar-do",
"zylara",

}