SafeAddString(SI_KEYBINDINGS_CATEGORY_VOTANS_MINIMAP, "Minimapa")
SafeAddString(SI_BINDING_NAME_VOTANS_TOGGLE_MAP_SHOW, "Mostrat/Ocultar mapa")
SafeAddString(SI_BINDING_NAME_VOTANS_TOGGLE_MAP_SHOW_HUD, "Mostrat/Ocultar HUD")
SafeAddString(SI_BINDING_NAME_VOTANS_TOGGLE_MAP_SHOW_SIEGE_HUD, "Mostrat/Ocultar mapa durante asedio")
SafeAddString(SI_BINDING_NAME_VOTANS_TOGGLE_MAP_SHOW_COMBAT, "Mostrat/Ocultar mapa en combate")
SafeAddString(SI_BINDING_NAME_VOTANS_TOGGLE_MAP_ZOOM_OUT, "Zoom mínimo")
SafeAddString(SI_BINDING_NAME_VOTANS_TOGGLE_MAP_ZOOM_IN, "Zoom máximo")
SafeAddString(SI_BINDING_NAME_VOTANS_TOGGLE_MAP_ZOOM_PLUS, "Acercar zoom")
SafeAddString(SI_BINDING_NAME_VOTANS_TOGGLE_MAP_ZOOM_MINUS, "Alejar zoom")

SafeAddString(SI_VOTANSMINIMAP_WORLD_MAP_TWEAKS, "Ajustes del mapa")
SafeAddString(SI_VOTANSMINIMAP_WORLD_MAP_TWEAKS_TOOLTIP, "Habilite ajustes para extender la carga de la CPU a lo largo del tiempo.")
SafeAddString(SI_VOTANSMINIMAP_MINI_MAP, "Mini-mapa")
SafeAddString(SI_VOTANSMINIMAP_MINI_MAP_TOOLTIP, "Habilitar la característica Mini-mapa del mapa en construcción.")
SafeAddString(SI_VOTANSMINIMAP_APPLY_BUTTON, "Aplicar")
SafeAddString(SI_VOTANSMINIMAP_LOCK_POSITION, "Boqueo de posición y tamaño")
SafeAddString(SI_VOTANSMINIMAP_LOCK_POSITION_TOOLTIP, "No permite mover y cambiar el tamaño de la ventana.")
SafeAddString(SI_VOTANSMINIMAP_ZOOM, "Zoom")
SafeAddString(SI_VOTANSMINIMAP_ZOOM_TOOLTIP, "Zoom relativo a la resolución del mapa nativo.")
SafeAddString(SI_VOTANSMINIMAP_MOUNTED_ZOOM, "Zoom montado")
SafeAddString(SI_VOTANSMINIMAP_MOUNTED_ZOOM_TOOLTIP, "Factor de zoom relativo, si está montado. El valor 1 mantiene el zoom actual.")
SafeAddString(SI_VOTANSMINIMAP_SUB_ZONE_ZOOM, "Zoom de Subzona")
SafeAddString(SI_VOTANSMINIMAP_SUB_ZONE_ZOOM_TOOLTIP, "Zoom relativo a la resolución del mapa nativo, si está en una subzona.")
SafeAddString(SI_VOTANSMINIMAP_DUNGEON_ZOOM, "Zoom de Mazmorra ")
SafeAddString(SI_VOTANSMINIMAP_DUNGEON_ZOOM_TOOLTIP, "Zoom relativo a la resolución del mapa nativo, si está en una mazmorra.")
SafeAddString(SI_VOTANSMINIMAP_BG_ZOOM, "Battleground Zoom")
SafeAddString(SI_VOTANSMINIMAP_BG_ZOOM_TOOLTIP, "Zoom relative to native map resolution, if on a battleground.")
SafeAddString(SI_VOTANSMINIMAP_UNIT_PINS_MINIMUM_SIZE, "Tamaño mínimo de pines")
SafeAddString(SI_VOTANSMINIMAP_UNIT_PINS_MINIMUM_SIZE_TOOLTIP, "Los pines no tienen escala debajo de este factor.")
SafeAddString(SI_VOTANSMINIMAP_SHOW_MAP, "Mostrar mapa")
SafeAddString(SI_VOTANSMINIMAP_SHOW_MAP_TOOLTIP, "Mostrar mini mapa en absoluto.")
SafeAddString(SI_VOTANSMINIMAP_SHOW_HUD, "Mostrar en HUD")
SafeAddString(SI_VOTANSMINIMAP_SHOW_HUD_TOOLTIP, "Mostrar mientras camina en el mundo.")
SafeAddString(SI_VOTANSMINIMAP_SHOW_LOOTING, "Mostrar mientras saquea.")
SafeAddString(SI_VOTANSMINIMAP_SHOW_LOOTING_TOOLTIP, "Ocultar y mostrar menos.")
SafeAddString(SI_VOTANSMINIMAP_ZOOM_TO_PLAYER, "Zoom del mapa del Jugador")
SafeAddString(SI_VOTANSMINIMAP_ZOOM_TO_PLAYER_TOOLTIP, "Mostrar mapa mundial, al acercar o al alejar.")
SafeAddString(SI_VOTANSMINIMAP_SHOW_MOUNTED, "Mostrar mientras está montado")
SafeAddString(SI_VOTANSMINIMAP_SHOW_MOUNTED_TOOLTIP, "Muestra mientras estás sentado en tu montura. Tiene prioridad sobre el 'Mostrar en Combate'.")
SafeAddString(SI_VOTANSMINIMAP_SHOW_COMBAT, "Mostrar en Combate")
SafeAddString(SI_VOTANSMINIMAP_SHOW_COMBAT_TOOLTIP, "Mostrar mientras estás en combate.")
SafeAddString(SI_VOTANSMINIMAP_SHOW_SIEGE, "Mostrar en Asedio")
SafeAddString(SI_VOTANSMINIMAP_SHOW_SIEGE_TOOLTIP, "Muestre mientras está asediando.")
SafeAddString(SI_VOTANSMINIMAP_KEYBINDINGS_ZOOM, "Atajos de teclado")
SafeAddString(SI_VOTANSMINIMAP_ZOOM_OUT, "Disminuir el zoom")
SafeAddString(SI_VOTANSMINIMAP_ZOOM_OUT_TOOLTIP, "Combinación de teclas para alejar el zoom.\n(Mantenga presionada la tecla.)")
SafeAddString(SI_VOTANSMINIMAP_ZOOM_IN, "Aumentar el zoom")
SafeAddString(SI_VOTANSMINIMAP_ZOOM_IN_TOOLTIP, "Combinación de teclas para acercar el zoom.\n(Mantener presionada la tecla).")
SafeAddString(SI_VOTANSMINIMAP_APPEARANCE, "Apariencia")
SafeAddString(SI_VOTANSMINIMAP_BORDER_STYLE, "Estilo de borde")
SafeAddString(SI_VOTANSMINIMAP_BORDER_OPACITY, "Opacidad del borde")
SafeAddString(SI_VOTANSMINIMAP_TITLE_FONT, "Fuente del titulo")
SafeAddString(SI_VOTANSMINIMAP_TITLE_FONT_SIZE, "Tamaño del título")
SafeAddString(SI_VOTANSMINIMAP_TITLE_COLOR, "Color del título")
SafeAddString(SI_VOTANSMINIMAP_TITLE_POSITION, "Posición del título")
SafeAddString(SI_VOTANSMINIMAP_SHOW_FULL_TITLE, "Mostrar título completo ")
SafeAddString(SI_VOTANSMINIMAP_SHOW_FULL_TITLE_TOOLTIP, "Muestra el título completo. Incluyendo el nombre y la dificultad de la campaña, incluso si es demasiado largo para la ventana deñ Mini-mapa.")
SafeAddString(SI_VOTANSMINIMAP_SHOW_CLOCK, "Mostrar reloj")
SafeAddString(SI_VOTANSMINIMAP_SHOW_CLOCK_TOOLTIP, "Mostrar reloj en el Mini-mapa.")
SafeAddString(SI_VOTANSMINIMAP_TIME_FORMAT, "Formato de tiempo")
SafeAddString(SI_VOTANSMINIMAP_SHOW_CLOCK0, "Apagado")
SafeAddString(SI_VOTANSMINIMAP_SHOW_CLOCK1, "Tiempo real")
SafeAddString(SI_VOTANSMINIMAP_SHOW_CLOCK2, "Tiempo en el juego")
SafeAddString(SI_VOTANSMINIMAP_SHOW_CLOCK3, "Tiempo real y en el juego")
SafeAddString(SI_VOTANSMINIMAP_ALLOW_FLOOR_NAVIGATION, "Permitir navegación por el suelo ")
SafeAddString(SI_VOTANSMINIMAP_ALLOW_FLOOR_NAVIGATION_TOOLTIP, "Mostrar el botón de navegación del piso en el mini mapa, si el mapa tiene pisos.")
SafeAddString(SI_VOTANSMINIMAP_ZONE_CHANGE_ALERT, "Alerta de cambio de zona")
SafeAddString(SI_VOTANSMINIMAP_SHOW_COMPASS, "Mostrar/Ocultar brújula")
SafeAddString(SI_VOTANSMINIMAP_SHOW_COMPASS_TOOLTIP, "Muestre u oculte la brújula, si se muestra el Mini-mapa o manténgala intacta y deje que otros complementos cambien la visibilidad de la brújula.")
SafeAddString(SI_VOTANSMINIMAP_FRAMEDROP_DEBUG, "Depuración Frame-drop")
SafeAddString(SI_VOTANSMINIMAP_SHOW_FREEZE_WARNING, "Mostrar advertencia de congelación")
SafeAddString(SI_VOTANSMINIMAP_SHOW_FREEZE_WARNING_TOOLTIP, "Muestra una advertencia si la acción excede la velocidad de fotogramas para 60 fps.")
SafeAddString(SI_VOTANSMINIMAP_SHOW_CAMERA_HEADING, "Mostrar el rumbo de la cámara")
SafeAddString(SI_VOTANSMINIMAP_SHOW_CAMERA_HEADING_TOOLTIP, "Muestra el rumbo de la cámara en el mundo y el minimapa.")
SafeAddString(SI_VOTANSMINIMAP_CAMERA_HEADING_ANGLE, "Ángulo de marcador")
SafeAddString(SI_VOTANSMINIMAP_CAMERA_HEADING_ANGLE_TOOLTIP, "El ángulo de la línea del marcador.")

SafeAddString(SI_VOTANSMINIMAP_ZONEALERTMODE_ALWAYS, "Siempre")
SafeAddString(SI_VOTANSMINIMAP_ZONEALERTMODE_MAP_HIDDEN, "Mini mapa escondido")
SafeAddString(SI_VOTANSMINIMAP_ZONEALERTMODE_NEVER, "Nunca")
SafeAddString(SI_VOTANSMINIMAP_COMPASSMODE_UNTOUCHED, "Sin tocar")
SafeAddString(SI_VOTANSMINIMAP_COMPASSMODE_HIDDEN, "Oculto")
SafeAddString(SI_VOTANSMINIMAP_COMPASSMODE_SHOWN, "Mostrado")

SafeAddString(SI_VOTANSMINIMAP_KEEP_SQUARE, "Mantener Cuadrado")
SafeAddString(SI_VOTANSMINIMAP_KEEP_SQUARE_TOOLTIP, "Mantenga el área del mapa cuadrada. Comportamiento por defecto.")

SafeAddString(SI_BINDING_NAME_VOTANS_TOGGLE_MAP_OFFSET_FIX, "Alternar posición del Mini-mapa")

SafeAddString(SI_VOTANSMINIMAP_ASYNC_UPDATE, "Actualización asíncrona")
SafeAddString(SI_VOTANSMINIMAP_ASYNC_UPDATE_TOOLTIP, "Encendido: Velocidad de fotogramas sobre actualización.\nApagado: actualización sobre la velocidad de fotogramas.")

SafeAddString(SI_VOTANSMINIMAP_PINSIZE_KEEP_FAST_TRAVEL, "Santuario de Transitus")
SafeAddString(SI_VOTANSMINIMAP_PINSIZE_KEEPS, "Mantiene")
SafeAddString(SI_VOTANSMINIMAP_PINSIZE_DISTRICTS, "Distritos")