ICT.locations = {
	[GetString(SI_ICTHENEXTBOSS_AMONCRUL)] = GetString(SI_ICTHENEXTBOSS_NOBLESDISTRICT),
	[GetString(SI_ICTHENEXTBOSS_THIRSK)] = GetString(SI_ICTHENEXTBOSS_NOBLESDISTRICT),
	[GetString(SI_ICTHENEXTBOSS_GLORGOLOCH)] = GetString(SI_ICTHENEXTBOSS_ARENADISTRICT),
	[GetString(SI_ICTHENEXTBOSS_CHARR)] = GetString(SI_ICTHENEXTBOSS_TEMPLEDISTRICT),
	[GetString(SI_ICTHENEXTBOSS_KHROGO)] = GetString(SI_ICTHENEXTBOSS_ARENADISTRICT),
	[GetString(SI_ICTHENEXTBOSS_MALYGDA)] = GetString(SI_ICTHENEXTBOSS_ARBORETUMDISTRICT),
	[GetString(SI_ICTHENEXTBOSS_MAZALUHAD)] = GetString(SI_ICTHENEXTBOSS_TEMPLEDISTRICT),
	[GetString(SI_ICTHENEXTBOSS_NUNATAK)] = GetString(SI_ICTHENEXTBOSS_MEMORIALDISTRICT),
	[GetString(SI_ICTHENEXTBOSS_MATRON)] = GetString(SI_ICTHENEXTBOSS_ELVENGARDENSDISTRICT),
	[GetString(SI_ICTHENEXTBOSS_VOLGHASS)] = GetString(SI_ICTHENEXTBOSS_MEMORIALDISTRICT),
	[GetString(SI_ICTHENEXTBOSS_YSENDA)] = GetString(SI_ICTHENEXTBOSS_ARBORETUMDISTRICT),
	[GetString(SI_ICTHENEXTBOSS_ZOAL)] = GetString(SI_ICTHENEXTBOSS_ELVENGARDENSDISTRICT),
}

ICT.timetable = {
	[GetString(SI_ICTHENEXTBOSS_NOBLESDISTRICT)] = 0,
	[GetString(SI_ICTHENEXTBOSS_ARENADISTRICT)] = 0,
	[GetString(SI_ICTHENEXTBOSS_TEMPLEDISTRICT)] = 0,
	[GetString(SI_ICTHENEXTBOSS_ARBORETUMDISTRICT)] = 0,
	[GetString(SI_ICTHENEXTBOSS_MEMORIALDISTRICT)] = 0,
	[GetString(SI_ICTHENEXTBOSS_ELVENGARDENSDISTRICT)] = 0,
}

ICT.fallbackTimes = {
	[GetString(SI_ICTHENEXTBOSS_AMONCRUL)] = 0,
	[GetString(SI_ICTHENEXTBOSS_THIRSK)] = 0,
	[GetString(SI_ICTHENEXTBOSS_GLORGOLOCH)] = 0,
	[GetString(SI_ICTHENEXTBOSS_CHARR)] = 0,
	[GetString(SI_ICTHENEXTBOSS_KHROGO)] = 0,
	[GetString(SI_ICTHENEXTBOSS_MALYGDA)] = 0,
	[GetString(SI_ICTHENEXTBOSS_MAZALUHAD)] = 0,
	[GetString(SI_ICTHENEXTBOSS_NUNATAK)] = 0,
	[GetString(SI_ICTHENEXTBOSS_MATRON)] = 0,
	[GetString(SI_ICTHENEXTBOSS_VOLGHASS)] = 0,
	[GetString(SI_ICTHENEXTBOSS_YSENDA)] = 0,
	[GetString(SI_ICTHENEXTBOSS_ZOAL)] = 0,
}