---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by YeOldeDragon.
--- DateTime: 2021-03-26 10:38
---
---
local ADDON_VERSION = "1.0.0"
local ADDON_SETTINGS_VERSION = 1.0

local CONTAINER_SHOW_TIME_MS = 3600
local PERSISTENT_CONTAINER_SHOW_TIME_MS = 4800
local DEFAULT_MAX_ITEMS = 6

local SETTING_PATTERN = "<<1>>Control<<2>>"
local SETTING_DESC_TITLE_PATTERN = "|cDA8A00<<1>> :|r"
local SETTING_DESC_CONTENT_PATTERN = "|c777777<<1>>|r"

YeOldeLootHistory.DefaultValues = {
    DebugEnabled = false,
    ContainerShowTime = CONTAINER_SHOW_TIME_MS,
    PersistantContainerShowTime = PERSISTENT_CONTAINER_SHOW_TIME_MS,
    MaxItems = DEFAULT_MAX_ITEMS,
    ShowInMenus = false,
    ShowType = {
        [YEOLDE_WORLD_LEGERDEMAIN] = true,
        [YEOLDE_WORLD_EXCAVATION] = true,
        [YEOLDE_WORLD_VAMPIRE] = true,
        [YEOLDE_WORLD_SOUL] = true,
        [YEOLDE_WORLD_SCRYING] = true,
        [YEOLDE_WORLD_WEREWOLF] = true,
    }
}

local function SetTitle(stringId)
    return zo_strformat(SETTING_DESC_TITLE_PATTERN, YeOldeLootHistory.lang[stringId])
end

local function CreateRef(id)
    return zo_strformat(SETTING_PATTERN, YeOldeLootHistory.AddonName, id)
end


function YeOldeLootHistory.CreateSettingsMenu()
    local panelData = {
        type = "panel",
        name = YeOldeLootHistory.AddonName,
        displayName = "YeOldeLootHistory Settings",
        author = "|c9D2900YeOldeDragon|r",
        version = ADDON_VERSION,
        website = "https://www.esoui.com/downloads/info3122-YeOldeLootHistory.html",
        feedback = "https://www.esoui.com/downloads/info3122-YeOldeLootHistory.html#comments",
        registerForRefresh = true,
        registerForDefaults = true,
    }

    local optionsTable = {}

    optionsTable[#optionsTable + 1] = {
        type = "slider",
        name = YeOldeLootHistory.lang[SI_YEOLDEHISTORYLOOT_CONTAINER_SHOW_TIME_MS],
        tooltip = YeOldeLootHistory.lang[SI_YEOLDEHISTORYLOOT_CONTAINER_TOOLTIP],
        getFunc = function() return YeOldeLootHistory.SV.ContainerShowTime end,
        setFunc = function(value)
            YeOldeLootHistory.SV.ContainerShowTime = value
            YeOldeLootHistory.UpdateContainerShowTime()
        end,
        min = 1000,
        max = 10000,
        step = 500,
        decimals = 0,
    }
    optionsTable[#optionsTable + 1] = {
        type = "slider",
        name = YeOldeLootHistory.lang[SI_YEOLDEHISTORYLOOT_PERSISTENT_CONTAINER_SHOW_TIME_MS],
        tooltip = YeOldeLootHistory.lang[SI_YEOLDEHISTORYLOOT_PERSISTENT_CONTAINER_TOOLTIP],
        getFunc = function() return YeOldeLootHistory.SV.PersistantContainerShowTime end,
        setFunc = function(value)
            YeOldeLootHistory.SV.PersistantContainerShowTime = value
            YeOldeLootHistory.UpdatePersistentContainerShowTime()
        end,
        min = 1000,
        max = 10000,
        step = 500,
        decimals = 0,
    }
    optionsTable[#optionsTable + 1] = {
        type = "slider",
        name = YeOldeLootHistory.lang[SI_YEOLDEHISTORYLOOT_MAX_ITEMS],
        getFunc = function() return YeOldeLootHistory.SV.MaxItems end,
        setFunc = function(value)
            YeOldeLootHistory.SV.MaxItems = value
            YeOldeLootHistory.UpdateMaxEntries()
        end,
        min = 2,
        max = 20,
        step = 1,
        decimals = 0,
    }
    optionsTable[#optionsTable + 1] = {
        type = "checkbox",
        name = YeOldeLootHistory.lang[SI_YEOLDEHISTORYLOOT_SHOW_IN_MENU],
        getFunc = function() return YeOldeLootHistory.SV.ShowInMenus end,
        setFunc = function(value)
            YeOldeLootHistory.SV.ShowInMenus = value
            YeOldeLootHistory.UpdateLootHistoryDisplayInMenus()
        end,
    }

    optionsTable[#optionsTable + 1] = {
        type = "divider",
        reference = CreateRef(#optionsTable),
    }
    optionsTable[#optionsTable + 1] = {
        type = "description",
        title = SetTitle(SI_YEOLDEHISTORYLOOT_EXT_DISPLAY_DESC),
        reference = CreateRef(#optionsTable),
    }

    for skillIndex, _ in pairs(YeOldeLootHistory.SV.ShowType) do
        local skillLineData = SKILLS_DATA_MANAGER:GetSkillLineDataByIndices(SKILL_TYPE_WORLD, skillIndex)

        optionsTable[#optionsTable + 1] = {
            type = "checkbox",
            name = skillLineData:GetFormattedName(),
            getFunc = function() return YeOldeLootHistory.SV.ShowType[skillIndex] end,
            setFunc = function(value) YeOldeLootHistory.SV.ShowType[skillIndex] = value end,
        }
    end

    optionsTable[#optionsTable + 1] = {
        type = "divider",
        reference = CreateRef(#optionsTable),
    }
    optionsTable[#optionsTable + 1] = {
        type = "description",
        title = SetTitle(SI_YEOLDEHISTORYLOOT_DEBUG_OPTIONS),
        reference = CreateRef(#optionsTable),
    }
    optionsTable[#optionsTable + 1] = {
        type = "checkbox",
        name = YeOldeLootHistory.lang[SI_YEOLDEHISTORYLOOT_DEBUG_ENABLED],
        getFunc = function() return YeOldeLootHistory.SV.DebugEnabled end,
        setFunc = function(value) YeOldeLootHistory.SV.DebugEnabled = value end,
    }

    --optionsTable[#optionsTable + 1] = {
    --    type = "dropdown",
    --    name = YeOldeLootHistory.lang[SI_YeOldeLootHistory_FONT_TYPE],
    --    choices = {"CHAT_FONT", "MEDIUM_FONT", "BOLD_FONT", "ANTIQUE_FONT", "HANDWRITTEN_FONT", "STONE_TABLET_FONT" },
    --    getFunc = function() return YeOldeLootHistory.SV.FontType end,
    --    setFunc = function(value)
    --        SetFontType(value)
    --    end,
    --    requiresReload = true,
    --}



    local LAM = LibAddonMenu2
    LAM:RegisterAddonPanel("YeOldeLootHistoryMenu", panelData)
    LAM:RegisterOptionControls("YeOldeLootHistoryMenu", optionsTable)
end

function YeOldeLootHistory.Initialize(eventCode, addOnName)
    if (addOnName ~= "YeOldeLootHistory") then return end
    YeOldeLootHistory.SV = ZO_SavedVars:NewAccountWide("YeOldeLootHistoryVars", 1.0, nil, YeOldeLootHistory.DefaultValues, nil)

    LootHistoryExt_Load()

    YeOldeLootHistory.CreateSettingsMenu()
end

EVENT_MANAGER:RegisterForEvent(YeOldeLootHistory.AddonName, EVENT_ADD_ON_LOADED, YeOldeLootHistory.Initialize)


--- skillLineData:
-- .isDiscovered -- true/false
-- .skillLineIndex -- 1
-- .currentRank -- 1
-- .name -- Guilde des Mages
-- .isWerewolf -- true/false
-- .isActive -- true/false
-- .isDiscovered -- true/false
-- .currentRank -- number
-- .id -- number
-- .lastRankXP = 100
-- .currentXP = 118
-- .nextRankXP = 180

--- skillType
-- SKILL_TYPE_ARMOR
-- SKILL_TYPE_AVA
-- SKILL_TYPE_CHAMPION
-- SKILL_TYPE_CLASS
-- SKILL_TYPE_GUILD
-- SKILL_TYPE_NONE
-- SKILL_TYPE_RACIAL
-- SKILL_TYPE_TRADESKILL
-- SKILL_TYPE_WEAPON
-- SKILL_TYPE_WORLD

--- reason
-- PROGRESS_REASON_ACHIEVEMENT = 25
-- PROGRESS_REASON_ACTION = 13
-- PROGRESS_REASON_ALLIANCE_POINTS = 33
-- PROGRESS_REASON_ANTIQUITY_COMPLETED_DIGGING = 42 -- new
-- PROGRESS_REASON_ANTIQUITY_COMPLETED_SCRYING = 41 -- new
-- PROGRESS_REASON_AVA = 15
-- PROGRESS_REASON_BATTLEGROUND = 6
-- PROGRESS_REASON_BOOK_COLLECTION_COMPLETE = 12
-- PROGRESS_REASON_BOSS_KILL = 26
-- PROGRESS_REASON_COLLECT_BOOK = 11
-- PROGRESS_REASON_COMMAND = 4
-- PROGRESS_REASON_COMPLETE_POI = 2
-- PROGRESS_REASON_DARK_ANCHOR_CLOSED = 28
-- PROGRESS_REASON_DARK_FISSURE_CLOSED = 29
-- PROGRESS_REASON_DISCOVER_POI = 3
-- PROGRESS_REASON_DRAGON_KILL = 39
-- PROGRESS_REASON_DUNGEON_CHALLENGE = 35
-- PROGRESS_REASON_EVENT = 27
-- PROGRESS_REASON_FINESSE = 9
-- PROGRESS_REASON_GRANT_REPUTATION = 32
-- PROGRESS_REASON_GUILD_REP = 14
-- PROGRESS_REASON_HARROWSTORM_COMPLETED = 40 -- new
-- PROGRESS_REASON_JUSTICE_SKILL_EVENT = 36
-- PROGRESS_REASON_KEEP_REWARD = 5
-- PROGRESS_REASON_KILL = 0
-- PROGRESS_REASON_LFG_REWARD = 37
-- PROGRESS_REASON_LOCK_PICK = 10
-- PROGRESS_REASON_MEDAL = 8
-- PROGRESS_REASON_NONE = -1
-- PROGRESS_REASON_OTHER = 31
-- PROGRESS_REASON_OVERLAND_BOSS_KILL = 24
-- PROGRESS_REASON_PVP_EMPEROR = 34
-- PROGRESS_REASON_QUEST = 1
-- PROGRESS_REASON_REWARD = 17
-- PROGRESS_REASON_SCRIPTED_EVENT = 7
-- PROGRESS_REASON_SKILL_BOOK = 30
-- PROGRESS_REASON_TRADESKILL = 16
-- PROGRESS_REASON_TRADESKILL_ACHIEVEMENT = 18
-- PROGRESS_REASON_TRADESKILL_CONSUME = 20
-- PROGRESS_REASON_TRADESKILL_HARVEST = 21
-- PROGRESS_REASON_TRADESKILL_QUEST = 19
-- PROGRESS_REASON_TRADESKILL_RECIPE = 22
-- PROGRESS_REASON_TRADESKILL_TRAIT = 23
-- PROGRESS_REASON_WORLD_EVENT_COMPLETED = 38