local strings = {
    -- style materials submenu
    DUSTMAN_STYLE_MATERIALS = "Materiales de estilo",
    -- item traits submenu
    DUSTMAN_ITEM_TRAITS = "Características del artículo",
    -- weapons & armors & jewelry submenu
    DUSTMAN_WEAP_ARM_JEWL = "Armas, armaduras y joyas",
    -- weapons & armors submenu and jewelry submenu
    DUSTMAN_WEAP_ARM = "Armas y armaduras",
    DUSTMAN_EQUIP_NOTRAIT = "Marcar elementos sin rasgo",
    DUSTMAN_EQUIP_NOTRAIT_DESC_WA = "Activar/desactivar el marcado de armas y armaduras equipables sin rasgo como basura",
    DUSTMAN_EQUIP_NOTRAIT_DESC_J = "Activar/desactivar marcar joyas sin rasgo como basura",
    DUSTMAN_EQUIPMENT = "Marcar artículos equipables",
    DUSTMAN_EQUIPMENT_DESC_WA = "Activar/desactivar el marcado de armas y armaduras equipables como basura",
    DUSTMAN_EQUIPMENT_DESC_J = "Activar/desactivar marcar joyas como basura",
    DUSTMAN_ORNATE = "Marcar elementos ornamentados",
    DUSTMAN_ORNATE_DESC_WA = "Activar/desactivar marcar armas y armaduras ornamentadas como basura",
    DUSTMAN_ORNATE_DESC_J = "Activar/desactivar marcar joyas ornamentadas como basura",
    DUSTMAN_WHITE_ZERO = "Marcar elementos de valor cero",
    DUSTMAN_WHITE_ZERO_DESC_WA = "Activar/desactivar la marcación de armas y armaduras equipables de calidad normal de valor cero como basura",
    DUSTMAN_WHITE_ZERO_DESC_J = "Activar/desactivar marcar joyas equipables de calidad normal de valor cero como basura",
    DUSTMAN_INTRICATE = "Excluir elementos con rasgos intrincados",
    DUSTMAN_INTRICATE_DESC_WA = "Si está habilitado, el complemento nunca marcará las armas y armaduras con rasgos intrincados como basura",
    DUSTMAN_INTRICATE_DESC_J = "Si está habilitado, el complemento nunca marcará las joyas con rasgos intrincados como basura",
    DUSTMAN_INTRIC_MAX = "Solo si es necesario para subir de nivel la habilidad de elaboración",
    DUSTMAN_INTRIC_MAX_DESC_WA = "Si está habilitado, el complemento excluirá armas y armaduras complejas solo si las necesita para subir de nivel su habilidad de elaboración",
    DUSTMAN_INTRIC_MAX_DESC_J = "Si está habilitado, el complemento excluirá las joyas intrincadas solo si las necesita para subir de nivel su habilidad de elaboración",
    DUSTMAN_RESEARCH = "Excluir elementos con rasgo investigable",
    DUSTMAN_RESEARCH_DESC_WA = "Si está habilitado, el complemento nunca marcará las armas y armaduras con un rasgo investigable como basura",
    DUSTMAN_RESEARCH_DESC_J = "Si está habilitado, el complemento nunca marcará las joyas con un rasgo investigable como basura",
    DUSTMAN_NIRNHONED = "Excluir elementos con rasgo Nirnhoned",
    DUSTMAN_NIRNHONED_DESC = "Si está habilitado, el complemento nunca marcará las armas y armaduras con el rasgo \"Nirnhoned\"como basura",
    DUSTMAN_SET = "Excluir todos los elementos configurados",
    DUSTMAN_SET_DESC_WA = "Si está habilitado, el complemento nunca marcará las armas y armaduras con bonificación de conjunto como basura",
    DUSTMAN_SET_DESC_J = "Si está habilitado, el complemento nunca marcará las joyas con bonificación de conjunto como basura",
    DUSTMAN_LEVEL = "Excluir elementos del nivel> =",
    DUSTMAN_LEVEL_DESC_WA = "Si está habilitado, el complemento nunca marcará armas y armaduras con un valor superior a cero y un nivel (o rango de campeón) igual o superior a este valor",
    DUSTMAN_LEVEL_DESC_J = "Si está habilitado, el complemento nunca marcará las joyas con un valor superior a cero y un nivel (o rango de campeón) igual o superior a este valor",
    DUSTMAN_LEVEL_ORNATE = "Marque los elementos ornamentados de nivel máximo de todos modos",
    DUSTMAN_LEVEL_ORNATE_DESC_WA = "Si está habilitado, el complemento marcará de todos modos las armas y armaduras con un rasgo adornado con un nivel (o rango de campeón) igual o superior al valor seleccionado",
    DUSTMAN_LEVEL_ORNATE_DESC_J = "Si está habilitado, el complemento marcará de todos modos las joyas con un rasgo adornado con un nivel (o rango de campeón) igual o superior al valor seleccionado",
    DUSTMAN_TRAITSSETS = "Marque los elementos del conjunto con esos rasgos específicos de todos modos",
    DUSTMAN_TRAITSSETS_DESC = "Si está habilitado, el complemento marcará de todos modos los elementos del conjunto con los rasgos específicos seleccionados",
    DUSTMAN_SET_ARENA = "Excluir armas de arena",
    DUSTMAN_SET_ARENA_DESC = "Si está habilitado, el complemento nunca marcará las armas de la arena (Dragonstar Arena, Maelstrom Arena, Blackrose Prison) como basura",
    DUSTMAN_SET_BG = "Excluir conjuntos de campos de batalla",
    DUSTMAN_SET_BG_DESC_WA = "Si está habilitado, el complemento nunca marcará las armas y armaduras de los campos de batalla como basura",
    DUSTMAN_SET_BG_DESC_J = "Si está habilitado, el complemento nunca marcará las joyas de los campos de batalla como basura",
    DUSTMAN_SET_CRAFTED = "Excluir conjuntos hechos a mano",
    DUSTMAN_SET_CRAFTED_DESC_WA = "Si está habilitado, el complemento nunca marcará las armas y armaduras creadas (por ejemplo, el obsequio de Magnus, Ashen Grip, etc.) como basura",
    DUSTMAN_SET_CRAFTED_DESC_J = "Si está habilitado, el complemento nunca marcará las joyas hechas a mano (por ejemplo, el obsequio de Magnus, Ashen Grip, etc.) como basura",
    DUSTMAN_SET_CYRO = "Excluir conjuntos de Cyrodill",
    DUSTMAN_SET_CYRO_DESC_WA = "Si está habilitado, el complemento nunca marcará las armas y armaduras de Cyrodill (por ejemplo, Golpe mortal, Furia del guerrero, etc.) como basura",
    DUSTMAN_SET_CYRO_DESC_J = "Si está habilitado, el complemento nunca marcará las joyas de Cyrodill (por ejemplo, Golpe mortal, Furia del guerrero, etc.) como basura",
    DUSTMAN_SET_RANDIC = "Excluir series diarias rd o IC",
    DUSTMAN_SET_RANDIC_DESC = "Si está habilitado, el complemento nunca marcará la mazmorra aleatoria diaria o las joyas de la Ciudad Imperial (Resistencia, Fuerza de Voluntad, Agilidad) como basura",
    DUSTMAN_SET_DUNG = "Excluir conjuntos de mazmorras",
    DUSTMAN_SET_DUNG_DESC_WA = "Si está habilitado, el complemento nunca marcará las armas y armaduras de las mazmorras (por ejemplo, Guía de Jorvuld, Luna de sangre, etc.) como basura",
    DUSTMAN_SET_DUNG_DESC_J = "Si está habilitado, el complemento nunca marcará las joyas de la mazmorra (por ejemplo, Guía de Jorvuld, Luna de sangre, etc.) como basura",
    DUSTMAN_SET_IC = "Excluir conjuntos de Ciudad Imperial",
    DUSTMAN_SET_IC_DESC_WA = "Si está habilitado, el complemento nunca marcará las armas y armaduras de la Ciudad Imperial (por ejemplo, Phoenix, Imperial Physique, etc.) como basura",
    DUSTMAN_SET_IC_DESC_J = "Si está habilitado, el complemento nunca marcará las joyas de la Ciudad Imperial (por ejemplo, Phoenix, Imperial Physique, etc.) como basura",
    DUSTMAN_SET_MS = "Excluir conjuntos de monstruos",
    DUSTMAN_SET_MS_DESC = "Si está habilitado, el complemento nunca marcará conjuntos de monstruos (por ejemplo, Ilambris, Iceheart, etc.) como basura",
    DUSTMAN_SET_OVERLAND = "Excluir conjuntos terrestres",
    DUSTMAN_SET_OVERLAND_DESC_WA = "Si está habilitado, el complemento nunca marcará las armas y armaduras terrestres (por ejemplo, Necropotence, Briarheart, etc.) como basura",
    DUSTMAN_SET_OVERLAND_DESC_J = "Si está habilitado, el complemento nunca marcará las joyas terrestres (por ejemplo, Necropotence, Briarheart, etc.) como basura",
    DUSTMAN_SET_SPEC = "Excluir conjuntos especiales",
    DUSTMAN_SET_SPEC_DESC_WA = "Si está habilitado, el complemento nunca marcará armas y armaduras especiales (Prophet, Broken Soul de recompensas de nivel superior) como basura",
    DUSTMAN_SET_SPEC_DESC_J = "Si está habilitado, el complemento nunca marcará las joyas especiales (Alma rota de las recompensas de nivel superior) como basura",
    DUSTMAN_SET_TRIAL = "Excluir conjuntos de prueba",
    DUSTMAN_SET_TRIAL_DESC_WA = "Si está habilitado, el complemento nunca marcará las armas y armaduras de prueba (por ejemplo, Moondancer, Berserking Warrior, etc.) como basura",
    DUSTMAN_SET_TRIAL_DESC_J = "Si está habilitado, el complemento nunca marcará las joyas de prueba (por ejemplo, Moondancer, Berserking Warrior, etc.) como basura",
    DUSTMAN_DISGUISES = "Marcar disfraces",
    DUSTMAN_DISGUISES_DESC = "Activar/desactivar el marcado de disfraces como basura",
    DUSTMAN_DISGUISES_DESTROY = "... ¡y destrúyelos!",
    DUSTMAN_DISGUISES_DESTROY_DESC = "Destruye disfraces automáticamente",
    -- provisioning submenu
    DUSTMAN_INGR_ALL = "Marque todos los ingredientes de aprovisionamiento",
    DUSTMAN_INGR_ALL_DESC = "Activar/desactivar el marcado de todos los ingredientes de aprovisionamiento como basura.",
    DUSTMAN_INGR_UNUS = "Marque los ingredientes de aprovisionamiento no utilizables",
    DUSTMAN_INGR_UNUS_DESC = "Activar/desactivar el marcado de ingredientes de aprovisionamiento inutilizables como basura.",
    DUSTMAN_INGR_DISH = "Habilitado para ingredientes de platos",
    DUSTMAN_INGR_DISH_DESC = "Habilitar el filtrado de ingredientes del plato (bonificación estadística)",
    DUSTMAN_INGR_DRINK = "Habilitado para ingredientes de bebidas",
    DUSTMAN_INGR_DRINK_DESC = "Habilitar el filtrado de ingredientes de bebidas (regeneración de estadísticas)",
    DUSTMAN_INGR_RARE = "Excluir aditivos raros",
    DUSTMAN_INGR_RARE_DESC = "Excluir |H1:item:26802:28:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h, |H1:item:27059:28:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|hy|h1:elemento:64222:29:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h. ",
    DUSTMAN_RECIPE = "Marcar recetas conocidas",
    DUSTMAN_RECIPE_DESC = "Activar/desactivar el marcado de recetas de aprovisionamiento conocidas como basura.",
    -- crafting materials submenu
    DUSTMAN_CRAFTING_MATERIALS = "Materiales de artesanía",
    DUSTMAN_CRAFTING_BLACKSMITHING_DESC = "Activar/desactivar el marcado de materiales de herrería de bajo nivel (solo|h0:item:64489:30:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h no se marcará) ",
    DUSTMAN_CRAFTING_RAW_BLACKSMITHING_DESC = "Activar/desactivar el marcado de materiales de herrería en bruto de bajo nivel (solo|h0:item:71198:30:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h no se marcará) ",
    DUSTMAN_CRAFTING_CLOTHING_DESC = "Activar/desactivar el marcado de materiales de ropa de bajo nivel (solo|h0:item:64504:30:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|hy|h0:elemento:64506:30:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h no se marcará) ",
    DUSTMAN_CRAFTING_RAW_CLOTHING_DESC = "Activar/desactivar el marcado de materiales de coagulación en bruto de bajo nivel (solo|h0:item:71200:30:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|hy|h0:elemento:71239:30:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h no se marcará) ",
    DUSTMAN_CRAFTING_WOODWORKING_DESC = "Activar/desactivar el marcado de materiales de carpintería de bajo nivel (solo|h0:item:64502:30:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h no se marcará) ",
    DUSTMAN_CRAFTING_RAW_WOODWORKING_DESC = "Activar/desactivar el marcado de materiales de carpintería en bruto de bajo nivel (solo|h0:item:71199:30:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h no se marcará) ",
    DUSTMAN_CRAFTING_JEWELRY_DESC = "Activar/desactivar el marcado de materiales de joyería de bajo nivel (solo|h0:item:135146:30:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h no se marcará) ",
    DUSTMAN_CRAFTING_RAW_JEWELRY_DESC = "Activar/desactivar el marcado de materiales de joyería en bruto de bajo nivel (solo|h0:item:135145:30:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h no se marcará) ",
    -- furnishing submenu
    DUSTMAN_FURNISHING_MATERIALS = "Materiales de decoración",
    DUSTMAN_ALCHRESIN = "Resina alquímica",
    DUSTMAN_BAST = "Líber",
    DUSTMAN_CLEANPELT = "Piel limpia",
    DUSTMAN_DECWAX = "Cera decorativa",
    DUSTMAN_HEARTWOOD = "Duramen",
    DUSTMAN_MUNDRUNE = "Runa mundana",
    DUSTMAN_OCHRE = "Ocre",
    DUSTMAN_REGULUS = "Regulus",
    -- enchanting submenu
    DUSTMAN_GLYPHS = "Marcar glifos no elaborados",
    DUSTMAN_GLYPHS_DESC = "Activar/desactivar el marcado de glifos",
    DUSTMAN_LEVELGLYPH = "Excluir glifos de nivel> =",
    DUSTMAN_LEVELGLYPH_DESC = "Si está habilitado, el complemento nunca marcará los glifos saqueados con un nivel (o rango de campeón) igual o superior a este valor",
    DUSTMAN_ASPECT_RUNES = "Marcar runas de aspecto",
    DUSTMAN_ASPECT_RUNES_DESC = "Activar/desactivar el marcado de runas de aspecto como basura.",
    DUSTMAN_ESSENCE_RUNES = "Marcar runas de esencia",
    DUSTMAN_ESSENCE_RUNES_DESC = "Activar/desactivar el marcado de runas de esencia como basura.",
    DUSTMAN_POTENCY_RUNES = "Marcar runas de potencia",
    DUSTMAN_POTENCY_RUNES_DESC = "Activar/desactivar el marcado de runas de potencia como basura.",
    -- consumables submenu
    DUSTMAN_FOOD_ALL = "Marque todas las comidas y bebidas",
    DUSTMAN_FOOD_ALL_DESC = "Activar/desactivar el marcado de todos los alimentos y bebidas como basura.",
    DUSTMAN_POTIONS = "Marcar pociones no elaboradas",
    DUSTMAN_POTIONS_DESC = "Activar/desactivar el marcado de pociones no elaboradas como basura.",
    DUSTMAN_LEVELPOTIONS = "Excluir pociones de nivel> =",
    DUSTMAN_LEVELPOTIONS_DESC = "Si está habilitado, el complemento nunca marcará las pociones saqueadas con un rango de campeón igual o superior a este valor",
    DUSTMAN_POISONS = "Marcar venenos no elaborados",
    DUSTMAN_POISONS_DESC = "Activar/desactivar el marcado de venenos no elaborados como basura.",
    DUSTMAN_POISONS_SOLVANTS = "Marque los solventes venenosos",
    DUSTMAN_POISONS_SOLVANTS_DESC = "Activar/desactivar el marcado de solventes venenosos como basura.",
    DUSTMAN_LEVELPOISONS = "Excluir venenos de nivel> =",
    DUSTMAN_LEVELPOISONS_DESC = "Si está habilitado, el complemento nunca marcará los venenos saqueados con un rango de campeón igual o superior a este valor",
    DUSTMAN_EMPTYGEMS = "Marcar gemas del alma vacías",
    DUSTMAN_EMPTYGEMS_DESC = "Activar/desactivar el marcado de Soul Gems vacías como basura.",
    DUSTMAN_TREASURE_MAPS = "Marcar mapas del tesoro",
    DUSTMAN_TREASURE_MAPS_DESC = "Activar/desactivar el marcado de mapas del tesoro como basura.",
    DUSTMAN_TREASURE_MAPS_DESTROY = "... ¡y destrúyelos!",
    DUSTMAN_TREASURE_MAPS_DESTROY_DESC = "Destruye automáticamente mapas del tesoro",
    DUSTMAN_JEWELRY_MASTER_WRITS = "Destruye los escritos del maestro de joyas",
    DUSTMAN_JEWELRY_MASTER_WRITS_DESC = "Destruye automáticamente los escritos del maestro de joyas",
    -- treasures and trophies submenu
    DUSTMAN_TREASURES = "Tesoros y trofeos",
    DUSTMAN_TREASURE = "Marcar tesoros",
    DUSTMAN_TREASURE_DESC = "Activar/desactivar el marcado de tesoros como basura.",
    DUSTMAN_TROPHIES = "Mark recogió trofeos",
    DUSTMAN_TROPHIES_DESC = "Habilitar/deshabilitar el marcado de trofeos como basura para los que ya se han recolectado",
    DUSTMAN_MUSEUM_PIECES = "Mark Museum Pieces",
    DUSTMAN_MUSEUM_PIECES_DESC = "Activar/desactivar el marcado de piezas de museo como basura.",
    DUSTMAN_MUSEUM_PIECES_DESTROY = "... ¡y destrúyelos!",
    DUSTMAN_MUSEUM_PIECES_DESTROY_DESC = "Destruir automáticamente las piezas del museo",
    -- daily logins stuff
    DUSTMAN_CROWN = "CORONA",
    DUSTMAN_DAILY_LOGINS = "Cosas de los inicios de sesión diarios",
    DUSTMAN_DL_FOOD = "Comida",
    DUSTMAN_DL_FOOD_DESC = "Destruye los alimentos obtenidos al reclamar los inicios de sesión diarios",
    DUSTMAN_DL_DRINKS = "Bebidas",
    DUSTMAN_DL_DRINKS_DESC = "Destruye las bebidas obtenidas al reclamar inicios de sesión diarios",
    DUSTMAN_DL_POTIONS = "Pociones",
    DUSTMAN_DL_POTIONS_DESC = "Destruye las pociones obtenidas al reclamar inicios de sesión diarios",
    DUSTMAN_DL_POISONS = "Venenos",
    DUSTMAN_DL_POISONS_DESC = "Destruye los venenos obtenidos al reclamar inicios de sesión diarios",
    DUSTMAN_DL_REP_KITS = "Kits de reparación",
    DUSTMAN_DL_REP_KITS_DESC = "Destruye los kits de reparación obtenidos al reclamar inicios de sesión diarios",
    DUSTMAN_DL_SOUL_GEMS = "Gemas del alma",
    DUSTMAN_DL_SOUL_GEMS_DESC = "Destruye las gemas del alma obtenidas al reclamar los inicios de sesión diarios",
    -- shared
    DUSTMAN_QUALITY = "Solo si la calidad es menor o igual a:",
    DUSTMAN_QUALITY_DESC = "Aplicar opción solo si la calidad del artículo es menor o igual al valor seleccionado.",
    DUSTMAN_QUALITY_SUPP = "Solo si la calidad es superior o igual a:",
    DUSTMAN_QUALITY_SUPP_DESC = "Aplicar la opción solo si la calidad del elemento es superior o igual al valor seleccionado.",
    DUSTMAN_FULLSTACK = "Solo con pila completa en el banco",
    DUSTMAN_FULLSTACK_DESC = "Aplique opciones solo si ya tiene una pila completa de artículos en el banco.",
    DUSTMAN_FULLSTACK_BAG = "Solo con pila completa en la bolsa",
    DUSTMAN_FULLSTACK_BAG_DESC = "Aplique opciones solo si ya tiene una pila completa de artículos en la mochila.",
    -- fishing
    DUSTMAN_FISHES = "Pesca",
    DUSTMAN_LURE = "Marcar señuelos de pesca",
    DUSTMAN_LURE_DESC = "Activar/desactivar el marcado de señuelos de pesca como basura.",
    DUSTMAN_TROPHY = "Mark recogió peces trofeo",
    DUSTMAN_TROPHY_DESC = "Habilite/deshabilite el marcado de peces trofeo como basura para aquellos que ya han sido recolectados. Se excluyen los peces recolectables y los ingredientes se manejan de la misma manera que el resto del material de aprovisionamiento.",
    -- housing
    DUSTMAN_HOUSING_RECIPES = "Marcar patrones de vivienda conocidos",
    DUSTMAN_HOUSING_RECIPES_DESC = "Activar/desactivar el marcado de patrones de vivienda conocidos como basura.",
    -- remember junk
    DUSTMAN_REMEMBER = "Recuerda los elementos marcados como basura",
    DUSTMAN_REMEMBER_DESC = "Habilita/deshabilita el seguimiento de lo que marcas como basura. Una vez que lo hagas, el complemento marcará automáticamente esos elementos como basura hasta que los desmarques como basura.",
    DUSTMAN_MEMORYFIRST = "Utilice primero los elementos recordados",
    DUSTMAN_MEMORYFIRST_DESC = "Si está habilitado, los elementos recordados se utilizarán como un filtro de mayor prioridad. Significa que puede anular otros filtros basura.",
    -- destroy junk submenu
    DUSTMAN_DESTROY = "Destruye basura",
    DUSTMAN_DESTROY_DESC = "Activar/desactivar la destrucción de artículos de bajo costo no deseados.",
    DUSTMAN_DESTROY_VAL = "Vender el umbral de precio",
    DUSTMAN_DESTROY_VAL_DESC = "Todos los artículos no deseados con un valor menor o igual a la cantidad seleccionada serán destruidos.",
    DUSTMAN_DESTROY_STOLEN = "Umbral para artículos robados",
    DUSTMAN_DESTROY_STOLEN_DESC = "Todos los artículos robados marcados como basura, con un valor menor o igual a la cantidad seleccionada, serán destruidos.",
    DUSTMAN_DESTROY_STACK = "Excluir elementos apilables",
    DUSTMAN_DESTROY_STACK_DESC = "No destruya los artículos apilables con un valor de venta superior a cero y menos del valor seleccionado",
    -- notifications submenu
    DUSTMAN_VERBOSE = "Notificar cuando manipule basura",
    DUSTMAN_VERBOSE_DESC = "Activar/desactivar la notificación de que un elemento se ha marcado como basura o se ha destruido.",
    DUSTMAN_FOUND = "Informar sobre elementos interesantes",
    DUSTMAN_FOUND_DESC = "Habilitar/deshabilitar la notificación de que el complemento encontró un elemento con rasgo investigable, con rasgo nirnhorned o elemento con bonificación de conjunto.",
    DUSTMAN_ALLITEMS = "Mostrar lista detallada a la venta",
    DUSTMAN_ALLITEMS_DESC = "Activar/desactivar la visualización de una lista detallada de lo que se vendió.",
    DUSTMAN_TOTAL = "Mostrar resumen en venta",
    DUSTMAN_TOTAL_DESC = "Activar/desactivar la visualización de un resumen de lo que se vendió.",
    DUSTMAN_CONFIRM = "Mostrar cuadro de diálogo de confirmación de venta",
    DUSTMAN_CONFIRM_DESC = "Activar/desactivar el cuadro de diálogo de confirmación de venta de basura.",
    DUSTMAN_DONTSELL = "Vender artículos automáticamente",
    DUSTMAN_DONTSELL_DESC = "Habilitar/deshabilitar la venta automática cuando hable con un comerciante. Si está deshabilitado, deberá usar la combinación de teclas \"Vender toda la basura\" o vender artículos manualmente",
    DUSTMAN_AUTOMATIC_SCAN = "Escanear inventario automáticamente",
    DUSTMAN_AUTOMATIC_SCAN_DESC = "Si esta opción está habilitada, sus reglas de Dustman se aplicarán automáticamente cuando se encuentre un nuevo artículo en su inventario. Tenga en cuenta que si deshabilita esta opción, deberá forzar manualmente un escaneo de inventario usando la opción a continuación o la combinación de teclas para volver a escanear",
    -- stolen items
    DUSTMAN_STOLEN = "Marcar tesoros como basura",
    DUSTMAN_STOLEN_DESC = "Activar/desactivar marcar tesoros como basura",
    DUSTMAN_STOLEN_LAUNDER = "Lavar artículos robados",
    DUSTMAN_STOLEN_LAUNDER_DESC = "Lavar artículos robados que no coincidan con los filtros basura",
    DUSTMAN_STOLEN_CLOTHES = "Excluya la ropa robada",
    DUSTMAN_STOLEN_CLOTHES_DESC = "No marcar y no blanquear ropa robada",
    DUSTMAN_NOLAUNDER = "No blanquear <<1>>",
    DUSTMAN_NOLAUNDER_DESC = "No blanquear <<1>>",
    DUSTMAN_NON_LAUNDERED = "Destruye los elementos seleccionados anteriormente",
    DUSTMAN_NON_LAUNDERED_DESC = "Destruye los elementos seleccionados anteriormente. Si no se activa, los elementos se dejarán como están en tu bolsa",
    DUSTMAN_ACT_LOWTREASURES = "Acción por tesoros de baja calidad",
    DUSTMAN_ACT_LOWTREASURES_DESC = "Seleccione la acción a realizar para los tesoros de baja calidad",
    DUSTMAN_ACT_LOWTREASURE1 = "Nada",
    DUSTMAN_ACT_LOWTREASURE2 = "Destruir elemento",
    DUSTMAN_ACT_LOWTREASURE3 = "Lavar artículo",
    -- keybinds
    DUSTMAN_JUNKKEYBIND = "Activar \"(Des) marcar como basura\" combinación de teclas",
    DUSTMAN_JUNKKEYBIND_DESC = "Agregue un botón de combinación de teclas para (des) desechar rápidamente sus artículos en el inventario",
    DUSTMAN_DESTROYKEYBIND = "Habilitar \"Destruir\" combinación de teclas",
    DUSTMAN_DESTROYKEYBIND_DESC = "Agregue un botón de combinación de teclas para destruir rápidamente sus artículos en el inventario",
    -- rescan button
    DUSTMAN_SWEEP = "Volver a escanear",
    DUSTMAN_SWEEP_DESC = "Vuelve a escanear todos los elementos de la mochila usando los filtros de arriba",
    -- clear marked as Junk
    DUSTMAN_CLEAR_MARKED = "Borrar entradas manuales",
    DUSTMAN_CLEAR_MARKED_DESC = "Borrar todos los elementos configurados manualmente como basura",
    -- global settings
    DUSTMAN_GLOBAL = "¿Usar configuración global?",
    DUSTMAN_GLOBAL_DESC = "¿Usar la misma configuración para todos los personajes?",
    -- import
    DUSTMAN_IMPORT = "Importar la configuración de Dustman desde",
    DUSTMAN_IMPORT_DESC = "Selecciona desde qué personaje Dustman debe importar su configuración.",
    DUSTMAN_IMPORTED = "La configuración de Dustman se ha importado del carácter <<1>>",
    -- chat notification
    DUSTMAN_SET_ENABLED = "Dustman ahora marcará el equipo configurado como basura",
    DUSTMAN_SET_DISABLED = "Dustman ahora guardará el equipo establecido",
    DUSTMAN_RESCAN_MSG = "¡Dustman ha vuelto a escanear con éxito su inventario!",
    DUSTMAN_NOTE_JUNK = "Dustman ha marcado <<t:1>> como basura (<<2>>).",
    DUSTMAN_NOTE_DESTROY = "Dustman ha destruido <<t:1>> (<<2>>).",
    DUSTMAN_NOTE_RESEARCH = "Elemento con rasgo investigable: <<t:1>> (<<2>>).",
    DUSTMAN_NOTE_NIRNHONED = "Elemento con |cFFFFFF<<1>>|r rasgo: <<t:2>>.",
    DUSTMAN_NOTE_SETITEM = "Objeto con bonificación de conjunto: <<t:1>> (<<2>>).",
    DUSTMAN_NOTE_INTERSTING = "Elemento interesante: <<t:1>>.",
    -- report formats
    DUSTMAN_FORMAT_ZERO = "Dustman vendió <<2>> x <<t:1>>.",
    DUSTMAN_FORMAT_GOLD = "Dustman vendió <<2>> x <<t:1>> por <<3>>|t16:16:EsoUI/Art/currency/currency_gold.dds|t.",
    DUSTMAN_FORMAT_NOTSOLD = "Dustman no pudo vender <<t:1>>.",
    DUSTMAN_FORMAT_TOTAL = "Dustman vendió <<1>> <<1[artículo/artículos]>> (<<3>> <<3[pila/pilas]>>) por <<2>>|t16:16:EsoUI/Art/currency/currency_gold.dds|t.",
    DUSTMAN_FORMATL_ZERO = "Dustman blanqueó <<2>> x <<t:1>>.",
    DUSTMAN_FORMATL_GOLD = "Dustman blanqueó <<2>> x <<t:1>> para <<3>>|t16:16:EsoUI/Art/currency/currency_gold.dds|t.",
    DUSTMAN_FORMATL_NOTSOLD = "Dustman no podía lavar <<t:1>>.",
    DUSTMAN_FORMATL_TOTAL = "Dustman blanqueó <<1>> <<1[artículo/artículos]>> para <<2>>|t16:16:EsoUI/Art/currency/currency_gold.dds|t.",
    DUSTMAN_ZOS_RESTRICTIONS = "Debido a las restricciones de ZOS, Dustman procesó solo 50 transacciones. Espere 10 segundos e interactúe nuevamente con el NPC.",
    -- bursar of tributes
    DUSTMAN_BOT_QUEST_NAME_1 = "Una cuestión de tributos",
    DUSTMAN_BOT_QUEST_NAME_2 = "Una cuestión de respeto",
    DUSTMAN_BOT_QUEST_NAME_3 = "Una cuestión de ocio",
    DUSTMAN_BOT_QUEST_NAME_4 = "Brillo y resplandor",
    DUSTMAN_BOT_QUEST_NAME_5 = "Bocados y picotazos",
    DUSTMAN_BOT_QUEST_NAME_6 = "Nibbles and Bits",
    DUSTMAN_BOT_COSMETIC = "Cosmético",
    DUSTMAN_BOT_GROOMING_ITEMS = "Artículos de aseo",
    DUSTMAN_BOT_UTENSILS = "Utensilios",
    DUSTMAN_BOT_DAC = "Platos y utensilios de cocina",
    DUSTMAN_BOT_DRINKWARE = "Vasos",
    DUSTMAN_BOT_CT = "Juguetes infantiles",
    DUSTMAN_BOT_DOLLS = "Muñecas",
    DUSTMAN_BOT_GAMES = "Juegos",
    DUSTMAN_BOT = "Guardar objetos de misión del tesorero de tributos",
    DUSTMAN_BOT_DESC = "Guarde los elementos para las misiones del Tesorero de Tributos. Dado que hay seis misiones posibles dadas por el cuervo npc, puede elegir guardar todos los elementos necesarios para todas las misiones posibles o guardar solo los elementos necesarios para la misión activa.",
    DUSTMAN_BOT_DD_ALL = "Todos los elementos necesarios para todas las misiones",
    DUSTMAN_BOT_DD_ACTIVE = "Artículos necesarios solo para misiones activas"
}

for stringId, stringValue in pairs(strings) do
    ZO_CreateStringId(stringId, stringValue)
    SafeAddVersion(stringId, 1)
end
