
K2EUpdate.normalItemSuffixTable = {
    [0] = "",
    [5365] = "of Frost",
    [26580] = "of Health",
    [26582] = "of Magicka",
    [26588] = "of Stamina",
    [26844] = "of Shock",
    [26845] = "of Crushing",
    [26848] = "of Flame",
    [43573] = "of Absorb Health",
    [45867] = "of Absorb Stamina",
    [45868] = "of Absorb Magicka",
    [45869] = "of Decrease Health",
    [45870] = "of Reduce Spell Cost",
    [45871] = "of Reduce Feat Cost",
    [45883] = "of Increase Physical Harm",
    [45885] = "of Decrease Physical Harm",
    [54484] = "of Weapon Damage",
}

K2EUpdate.normalItemPrefixs = {
    "^(calcinium)%s",
    "^(dwarven)%s",
    "^(ebon)%s",
    "^(galatite)%s",
    "^(iron)%s",
    "^(orichalc)%s",
    "^(quicksilver)%s",
    "^(rubedite)%s",
    "^(steel)%s",
    "^(voidsteel)%s",

    "^(ancestor silk)%s",
    "^(cotton)%s",
    "^(ebonthread)%s",
    "^(homespun)%s",
    "^(ironthread)%s",
    "^(kresh)%s",
    "^(linen)%s",
    "^(shadowspun)%s",
    "^(silverweave)%s",
    "^(spidersilk)%s",

    "^(brigandine)%s",
    "^(fell)%s",
    "^(full.leather)%s",
    "^(hide)%s",
    "^(ironhide)%s",
    "^(leather)%s",
    "^(rawhide)%s",
    "^(rubedo leather)%s",
    "^(shadowhide)%s",
    "^(superb)%s",

    "^(ash)%s",
    "^(beech)%s",
    "^(birch)%s",
    "^(hickory)%s",
    "^(mahogany)%s",
    "^(maple)%s",
    "^(nightwood)%s",
    "^(oak)%s",
    "^(ruby ash)%s",
    "^(yew)%s",

    "^(copper)%s",
    "^(electrum)%s",
    "^(pewter)%s",
    "^(platinum)%s",
    "^(silver)%s",
}

K2EUpdate.normalItemNames = {
    "arm cops$",
    "axe$",
    "battle axe$",
    "belt$",
    "boots$",
    "bow$",
    "bracers$",
    "breeches$",
    "cuirass$",
    "dagger$",
    "epaulets$",
    "gauntlets$",
    "girdle$",
    "gloves$",
    "greaves$",
    "guards$",
    "hat$",
    "helm$",
    "helmet$",
    "ice staff$",
    "inferno staff$",
    "jack$",
    "jerkin$",
    "lightning staff$",
    "mace$",
    "maul$",
    "necklace$",
    "pauldron$",
    "restoration staff$",
    "ring$",
    "robe$",
    "sabatons$",
    "sash$",
    "shield$",
    "shoes$",
    "sword$",

    "(arm cops)%sof%s.+",
    "(axe)%sof%s.+",
    "(battle axe)%sof%s.+",
    "(belt)%sof%s.+",
    "(boots)%sof%s.+",
    "(bow)%sof%s.+",
    "(bracers)%sof%s.+",
    "(breeches)%sof%s.+",
    "(cuirass)%sof%s.+",
    "(dagger)%sof%s.+",
    "(epaulets)%sof%s.+",
    "(gauntlets)%sof%s.+",
    "(girdle)%sof%s.+",
    "(gloves)%sof%s.+",
    "(greaves)%sof%s.+",
    "(guards)%sof%s.+",
    "(hat)%sof%s.+",
    "(helm)%sof%s.+",
    "(helmet)%sof%s.+",
    "(ice staff)%sof%s.+",
    "(inferno staff)%sof%s.+",
    "(jack)%sof%s.+",
    "(jerkin)%sof%s.+",
    "(lightning staff)%sof%s.+",
    "(mace)%sof%s.+",
    "(maul)%sof%s.+",
    "(necklace)%sof%s.+",
    "(pauldron)%sof%s.+",
    "(restoration staff)%sof%s.+",
    "(ring)%sof%s.+",
    "(robe)%sof%s.+",
    "(sabatons)%sof%s.+",
    "(sash)%sof%s.+",
    "(shield)%sof%s.+",
    "(shoes)%sof%s.+",
    "(sword)%sof%s.+",
}


