-- PB's Translate dictionary: The Elder Scrolls Online
--
-- Loaded last, so the game's meaning of a word beats the everyday one: "tank" is a role,
-- "keep" in a noun position is a fortress, "hm" is hard mode.
--
-- Within this file the order is nouns, verbs, expressions: for a word in more than one block
-- the last one is its reading when nothing around it says otherwise, and chat shorthand is
-- most often typed on its own ("wipe", "stack", "afk").
--
-- Place and character names follow the Japanese client where they are known. Acronyms whose
-- Japanese name is long or uncertain (dungeon and trial abbreviations) are kept as written:
-- listing them still matters, because a known word counts towards "this line is English"
-- (see Main.lua), and a raid call like "lf healer vma" should not be skipped as gibberish.
--
-- A possessive in a name is written as a separate word: "hew 's bane" (the tokenizer splits
-- the 's off before the dictionary is consulted).

local D = PBsTranslate.Define

D("n", [[
-- roles and group play
tank=タンク
healer=ヒーラー
heals=回復
heal=回復
dps=DPS
dd=DD
stam dps=スタミナDPS
mag dps=マジカDPS
stamdps=スタミナDPS
magdps=マジカDPS
support=サポート
role=ロール
group=グループ
grp=グループ
party=パーティー
raid=レイド
leader=リーダー
group leader=グループリーダー
raid lead=レイドリーダー
rl=レイドリーダー
group finder=グループファインダー
random=ランダム
pug=野良
premade=固定
carry=キャリー
run=周回
spot=枠
slot=枠
roster=メンバー表
-- content
dungeon=ダンジョン
dungeons=ダンジョン
dungeon finder=ダンジョンファインダー
trial=試練
trials=試練
arena=アリーナ
vet=ベテラン
veteran=ベテラン
normal=ノーマル
hard mode=ハードモード
hardmode=ハードモード
trifecta=トリフェクタ
no death=ノーデス
speed run=スピードラン
speedrun=スピードラン
achievement=実績
achievements=実績
cheevo=実績
title=称号
skin=スキン
pledge=誓約
pledges=誓約
daily=デイリー
dailies=デイリー
quest=クエスト
main quest=メインクエスト
side quest=サイドクエスト
delve=洞窟
public dungeon=パブリックダンジョン
world boss=ワールドボス
wb=ワールドボス
dolmen=ドルメン
dark anchor=ダークアンカー
geyser=ゲイザー
harrowstorm=ハロウストーム
oblivion portal=オブリビオンポータル
skyshard=スカイシャード
skyshards=スカイシャード
lorebook=伝承本
boss=ボス
final boss=最終ボス
last boss=最終ボス
trash=雑魚
trash pack=雑魚集団
add=雑魚
adds=雑魚
mob=敵
mobs=敵
mechanic=ギミック
mechanics=ギミック
mech=ギミック
aoe=範囲攻撃
one shot=即死攻撃
portal=ポータル
wipe=全滅
pvp=PvP
pve=PvE
cyrodiil=シロディール
cyro=シロディール
imperial city=インペリアルシティ
ic=インペリアルシティ
battleground=バトルグラウンド
battlegrounds=バトルグラウンド
bg=バトルグラウンド
bgs=バトルグラウンド
campaign=キャンペーン
keep=砦
outpost=前哨基地
resource=資源
scroll=エルダースクロール
elder scroll=エルダースクロール
emperor=皇帝
siege=攻城兵器
ram=破城槌
ballista=バリスタ
trebuchet=トレビュシェット
zerg=大集団
ganker=ガンカー
ap=アライアンスポイント
alliance points=アライアンスポイント
tel var=テルヴァー
telvar=テルヴァー
tel var stones=テルヴァーストーン
alliance=同盟
aldmeri dominion=アルドメリ・ドミニオン
ebonheart pact=エボンハート・パクト
ep=エボンハート・パクト
daggerfall covenant=ダガーフォール・カバナント
-- character
character=キャラクター
char=キャラ
toon=キャラ
alt=サブキャラ
class=クラス
race=種族
build=ビルド
setup=構成
gear=装備
set=セット
sets=セット
monster set=モンスターセット
mythic=神話アイテム
trait=特性
traits=特性
motif=スタイル
motifs=スタイル
style=スタイル
skill=スキル
skills=スキル
skill line=スキルライン
skill point=スキルポイント
skill points=スキルポイント
ultimate=アルティメット
ult=アルティメット
ults=アルティメット
morph=派生
passive=パッシブ
passives=パッシブ
bar=バー
front bar=表バー
back bar=裏バー
buff=バフ
buffs=バフ
debuff=デバフ
debuffs=デバフ
stamina=スタミナ
stam=スタミナ
magicka=マジカ
mag=マジカ
health=体力
hp=HP
damage=ダメージ
dmg=ダメージ
crit=クリティカル
penetration=貫通
pen=貫通
resistance=耐性
cp=CP
champion points=チャンピオンポイント
level=レベル
lvl=レベル
xp=経験値
exp=経験値
mount=マウント
horse=馬
pet=ペット
costume=衣装
outfit=外見
emote=エモート
companion=コンパニオン
werewolf=ウェアウルフ
vampire=ヴァンパイア
vamp=ヴァンパイア
dragonknight=ドラゴンナイト
dk=ドラゴンナイト
sorcerer=ソーサラー
sorc=ソーサラー
nightblade=ナイトブレード
nb=ナイトブレード
templar=テンプラー
plar=テンプラー
warden=ワーデン
necromancer=ネクロマンサー
necro=ネクロマンサー
arcanist=アルカニスト
arc=アルカニスト
nord=ノルド
breton=ブレトン
redguard=レッドガード
khajiit=カジート
argonian=アルゴニアン
dunmer=ダンマー
dark elf=ダークエルフ
altmer=アルトマー
high elf=ハイエルフ
bosmer=ボズマー
wood elf=ウッドエルフ
orc=オーク
imperial=インペリアル
-- items and economy
gold=ゴールド
g=ゴールド
crowns=クラウン
crown=クラウン
crown store=クラウンストア
crown crate=クラウン箱
crates=クラウン箱
eso plus=ESO Plus
seals of endeavor=努力の証
event ticket=イベントチケット
event tickets=イベントチケット
transmute=変性
transmute stone=変性クリスタル
transmute crystal=変性クリスタル
loot=戦利品
drop=ドロップ
drops=ドロップ
item set=アイテムセット
jewelry=宝飾品
necklace=首飾り
ring=指輪
weapon=武器
two hander=両手武器
2h=両手武器
1h=片手武器
sword and board=片手剣と盾
dual wield=二刀流
dw=二刀流
destro staff=破壊の杖
destruction staff=破壊の杖
resto staff=回復の杖
restoration staff=回復の杖
bow=弓
light armor=軽装
medium armor=中装
heavy armor=重装
gold jewelry=金の宝飾品
gold gear=金装備
purple gear=紫装備
legendary=レジェンダリー
epic=エピック
furniture=家具
furnishing=家具
house=家
housing=ハウジング
guild hall=ギルドホール
writ=依頼
writs=依頼
master writ=上級依頼
master writs=上級依頼
survey=調査報告
surveys=調査報告
treasure map=宝の地図
lead=手がかり
leads=手がかり
antiquity=古物
antiquities=古物
mat=素材
mats=素材
material=素材
materials=素材
style mat=スタイル素材
style mats=スタイル素材
temper=強化素材
tempers=強化素材
glyph=グリフ
glyphs=グリフ
potion=ポーション
pots=ポーション
pot=ポーション
poison=毒
food=料理
drink=飲み物
soul gem=魂石
soul gems=魂石
lockpick=ロックピック
lockpicks=ロックピック
repair kit=修理キット
siege repair kit=攻城修理キット
guild=ギルド
guild trader=ギルドトレーダー
trader=トレーダー
guild store=ギルドストア
guild bank=ギルド銀行
guild master=ギルドマスター
officer=オフィサー
recruit=新人
trading guild=トレードギルド
social guild=交流ギルド
pvp guild=PvPギルド
raid guild=レイドギルド
blacksmithing=鍛冶
blacksmith=鍛冶
clothing=裁縫
clothier=裁縫
woodworking=木工
woodworker=木工
jewelry crafting=宝飾
enchanting=付呪
enchanter=付呪師
alchemy=錬金術
provisioning=調理
crafting=クラフト
crafter=クラフター
research=研究
crafting station=クラフト台
wayshrine=ウェイシュライン
dungeon wayshrine=ダンジョンのウェイシュライン
mundus stone=ムンダスストーン
mundus=ムンダス
dye=染料
dye station=染色台
outfit station=外見変更台
transmute station=変性台
banker=銀行員
merchant=商人
vendor=商人
fence=盗品商
bounty=懸賞金
jail=牢屋
guard=衛兵
npc=NPC
dlc=DLC
chapter=チャプター
expansion=拡張
patch=パッチ
pts=PTS
maintenance=メンテナンス
maint=メンテナンス
megaserver=メガサーバー
na=北米サーバー
eu=欧州サーバー
-- lore and places
tamriel=タムリエル
nirn=ニルン
coldharbour=コールドハーバー
oblivion=オブリビオン
molag bal=モラグ・バル
daedric prince=デイドラ公
mages guild=魔術師ギルド
fighters guild=戦士ギルド
thieves guild=盗賊ギルド
dark brotherhood=闇の一党
undaunted=アンドーンテッド
psijic order=サイジック会
psijic=サイジック
skyrim=スカイリム
western skyrim=西スカイリム
morrowind=モロウィンド
vvardenfell=ヴァーデンフェル
summerset=サマーセット
elsweyr=エルスウェア
northern elsweyr=北エルスウェア
southern elsweyr=南エルスウェア
craglorn=クラグローン
wrothgar=ロスガー
hew 's bane=ヒューズベイン
gold coast=ゴールドコースト
clockwork city=クロックワーク・シティ
murkmire=マークマイア
greymoor=グレイムーア
blackreach=ブラックリーチ
the reach=リーチ
markarth=マルカルス
blackwood=ブラックウッド
deadlands=デッドランズ
high isle=ハイアイル
galen=ガレン
telvanni peninsula=テルヴァンニ半島
apocrypha=アポクリファ
necrom=ネクロム
west weald=ウェストウィールド
solstice=ソルスティス
glenumbra=グレナンブラ
stormhaven=ストームヘヴン
rivenspire=リベンスパイア
alikr=アリクル砂漠
alikr desert=アリクル砂漠
bangkorai=バンコライ
stonefalls=ストンフォール
deshaan=デシャーン
shadowfen=シャドウフェン
eastmarch=イーストマーチ
the rift=リフト
rift=リフト
auridon=オーリドン
grahtwood=グラスウッド
greenshade=グリーンシェード
malabal tor=マラバル・トール
reaper 's march=リーパーズ・マーチ
reapers march=リーパーズ・マーチ
artaeum=アルテウム
wayrest=ウェイレスト
daggerfall=ダガーフォール
sentinel=センチネル
evermor=エバーモア
mournhold=モーンホールド
davon 's watch=ダボンズ・ウォッチ
windhelm=ウィンドヘルム
riften=リフテン
elden root=エルデンルート
vulkhel guard=ヴルケル・ガード
vivec city=ヴィベク・シティ
vivec=ヴィベク
balmora=バルモラ
sadrith mora=サドリス・モラ
alinor=アリノール
senchal=センシャル
rimmen=リメン
solitude=ソリチュード
leyawiin=レヤウィン
gonfalon bay=ゴンファロン湾
anvil=アンヴィル
kvatch=クヴァッチ
orsinium=オルシニウム
belkarth=ベルカース
abah 's landing=アバーズ・ランディング
brass fortress=真鍮の砦
lilmoth=リルモス
fargrave=ファーグレイヴ
coldharbor=コールドハーバー
mudcrab=マッドクラブ
guar=グアル
netch=ネッチ
skeever=スキーヴァー
-- trial and dungeon abbreviations, kept as written
vma=vMA
maelstrom=メイルストローム
maelstrom arena=メイルストローム・アリーナ
vvh=vVH
vh=VH
vateshran=ヴァテシュラン
vss=vSS
ss=SS
sunspire=サンスパイア
vcr=vCR
cr=CR
cloudrest=クラウドレスト
vas=vAS
asylum=アサイラム
vhrc=vHRC
hrc=HRC
vaa=vAA
aa=AA
vso=vSO
vmol=vMoL
mol=MoL
vhof=vHoF
hof=HoF
vka=vKA
vrg=vRG
vdsr=vDSR
dsr=DSR
vse=vSE
vlc=vLC
lc=LC
voc=vOC
vdsa=vDSA
dsa=DSA
brp=BRP
vbrp=vBRP
icp=ICP
wgt=WGT
fg1=FG1
fg2=FG2
fg3=FG3
bc1=BC1
bc2=BC2
dc1=DC1
dc2=DC2
eh1=EH1
eh2=EH2
sc1=SC1
sc2=SC2
coa1=CoA1
coa2=CoA2
coh1=CoH1
coh2=CoH2
vom=VoM
dfk=DFK
spc=SCP
scp=SCP
mos=MoS
mhk=MHK
fv=FV
dom=DoM
mgf=MGF
lom=LoM
bdv=BDV
rpb=RPB
dcl=DC
ere=ERE
bv=BV
]])

D("v", [[
lf=探している/1
looking for=探している/1
wts=売りたい/i/を
wtb=買いたい/i/を
wtt=交換したい/i/を
selling=売っている/1
buying=買っている/1
trading=交換している/1
port=テレポートする/s
tp=テレポートする/s
loot=ルートする/s
heal=回復する/s
carry=キャリーする/s
farm=周回する/s
run=周回する/s
queue=キューに入る/5
pug=野良で行く/5
gank=奇襲する/s
zerg=数で押す/5
kite=引き回す/5
cleanse=浄化する/s
purge=浄化する/s
rez=蘇生する/s
res=蘇生する/s
craft=クラフトする/s
research=研究する/s
deconstruct=分解する/s
decon=分解する/s
refine=精製する/s
enchant=付呪する/s
transmute=変性する/s
reconstruct=再構築する/s
bind=登録する/s
unlock=解除する/s
respec=スキルを振り直す/5
slot=セットする/s
proc=発動する/s
]])

D("x", [[
lfg=グループ募集中
lfm=メンバー募集中
lf1m=あと1人募集
lf2m=あと2人募集
lf3m=あと3人募集
lf4m=あと4人募集
lf5m=あと5人募集
lf6m=あと6人募集
lf8m=あと8人募集
lf10m=あと10人募集
lfr=残りメンバー募集
lfp=パーティー募集中
wts=売ります
wtb=買います
wtt=交換します
pst=ささやいてください
pm me=ささやいてください
whisper me=ささやいてください
x up=参加する人は+を
+1=参加します
inc=来るぞ
incoming=来るぞ
rezz=蘇生して
rez me=蘇生してください
res me=蘇生してください
ty for rez=蘇生ありがとう
ty for res=蘇生ありがとう
ty for the rez=蘇生ありがとう
thanks for the rez=蘇生ありがとう
ty for group=グループありがとう
ty for the group=グループありがとう
thanks for the group=グループありがとう
ty for run=周回ありがとう
ty for the run=周回ありがとう
thanks for the run=周回ありがとう
ty for carry=キャリーありがとう
ty for the carry=キャリーありがとう
gg all=皆さんお疲れさまでした
gg everyone=皆さんお疲れさまでした
ggwp=お疲れさまでした
gf=よろしくお願いします
hm=ハードモード
nd=ノーデス
wipe=全滅
we wiped=全滅しました
add me=フレンド追加してください
add me pls=フレンド追加してください
full=満員です
group full=グループは満員です
last spot=残り1枠
invite sent=招待を送りました
inv sent=招待を送りました
inv pls=招待してください
inv please=招待してください
inv me=招待してください
invite me=招待してください
invite pls=招待してください
invite please=招待してください
x for inv=招待希望は x を
x for invite=招待希望は x を
+ for invite=招待希望は + を
tp=テレポート
port to me=私の所にテレポートしてください
port to leader=リーダーの所にテレポートしてください
travel to leader=リーダーの所に移動してください
queue=キュー
queue up=キューに入ってください
q up=キューに入ってください
requeue=再キュー
ready check=準備確認
stack=集まって
stack up=集まって
spread=散開
spread out=散開して
kite=引き回して
taunt=挑発して
block=ブロックして
dodge=回避して
interrupt=妨害して
bash=妨害して
purge=浄化して
cleanse=浄化して
heal me=回復してください
need heals=回復が必要です
oom=マジカ切れ
low hp=体力が少ない
boss down=ボス撃破
dead=死にました
i died=死にました
i am dead=死にました
afk=離席中
brb bio=トイレ休憩
bio=トイレ休憩
bio break=トイレ休憩
dc=切断されました
lag=ラグい
laggy=ラグい
so laggy=すごくラグい
server lag=サーバーがラグい
i crashed=落ちました
omw=向かっています
be there soon=すぐ行きます
on my way=向かっています
]])

-- A ground-effect warning, not a reference to an alliance.
D("adv", [[
in the red=赤い範囲内に
]])

-- Community chat expansion (2026-09-16). Sources and scope: SLANG_SOURCES.md [eso].
D("n", [[
pvx=PvEとPvPの両方
lowbie=低レベルキャラクター
lowbies=低レベルキャラクター
mule=倉庫キャラクター
bank alt=倉庫キャラクター
rngeesus=乱数の神様
rngeezus=乱数の神様
randoms=野良メンバー
pre made=固定グループ
pug run=野良での攻略
pug raid=野良レイド
pug tank=野良タンク
pug healer=野良ヒーラー
fake tank=タンク役を偽ったプレイヤー
fake healer=ヒーラー役を偽ったプレイヤー
fake heal=ヒーラー役を偽ったプレイヤー
random normal=ランダムノーマルダンジョン
random vet=ランダムベテランダンジョン
random veteran=ランダムベテランダンジョン
rnd=ランダムノーマルダンジョン
rnds=ランダムノーマルダンジョン
random daily=デイリーのランダムダンジョン
vet pledges=ベテランの誓い
normal pledges=ノーマルの誓い
non dlc=非DLC
base game dungeon=ベースゲームのダンジョン
dlcs=DLC
normals=ノーマル難易度
achiev=実績
achieves=実績
achis=実績
cheevos=実績
achievement run=実績狙いの攻略
trifecta run=トリフェクタ狙いの攻略
no death run=ノーデス狙いの攻略
nodeath=ノーデス
speed clear=高速クリア
speedclear=高速クリア
mt=メインタンク
ot=サブタンク
maintank=メインタンク
offtank=サブタンク
pocket healer=専属ヒーラー
pocket heal=専属ヒール
pocket heals=専属ヒール
heal check=回復力チェック
healer check=回復力チェック
mit check=ダメージ軽減チェック
mitigation check=ダメージ軽減チェック
hard enrage=時間切れの強制全滅
soft enrage=時間経過での難化
enrage timer=時間切れまでの制限時間
burn phase=集中攻撃フェーズ
execute phase=低体力時のとどめフェーズ
cleave damage=対象の周囲も巻き込むダメージ
st damage=単体ダメージ
aoe damage=範囲ダメージ
pad damage=意味の薄い火力の水増し
trash mobs=雑魚敵
trash pull=雑魚のまとめ戦闘
add wave=追加の敵の出現
boss cleave=ボスの巻き込み攻撃
gcd=グローバルクールダウン
icd=内部クールダウン
internal cooldown=内部クールダウン
animation cancel=モーションキャンセル
animation cancelling=モーションキャンセル
animation canceling=モーションキャンセル
ani canceling=モーションキャンセル
ani cancelling=モーションキャンセル
light attack weaving=軽攻撃を挟む操作
heavy attack build=重攻撃中心のビルド
ha build=重攻撃中心のビルド
one bar build=ワンバービルド
onebar=ワンバー
one bar=ワンバー
pet sorc=ペットソーサラー
petsorc=ペットソーサラー
magsorc=マジカソーサラー
stamsorc=スタミナソーサラー
magplar=マジカテンプラー
stamplar=スタミナテンプラー
magblade=マジカナイトブレイド
stamblade=スタミナナイトブレイド
magdk=マジカドラゴンナイト
stamdk=スタミナドラゴンナイト
magden=マジカウォーデン
stamden=スタミナウォーデン
magcro=マジカネクロマンサー
stamcro=スタミナネクロマンサー
magarc=マジカアルカニスト
stamarc=スタミナアルカニスト
healden=ヒーラーウォーデン
bow build=弓ビルド
bow bow=両バー弓のビルド
bowbow=両バー弓のビルド
snb=片手武器と盾
sword and shield=片手武器と盾
destro=破壊杖
resto=回復杖
desto=破壊杖
spammable=連発する主力スキル
spammables=連発する主力スキル
stat stick=能力値を得るための装備
proc set=条件で効果が発動するセット
proc sets=条件で効果が発動するセット
body set=防具枠で揃えるセット
frontbar=表バー
backbar=裏バー
fb=表バー
]])

-- Community chat expansion (2026-09-16). Sources and scope: SLANG_SOURCES.md [raid].
D("n", [[
prog=攻略練習
progression group=攻略練習グループ
prog group=攻略練習グループ
prog run=攻略練習の回
fresh prog=最初からの攻略練習
blind prog=予習なしの攻略練習
reclear=クリア済みコンテンツの再攻略
reclear run=クリア済みコンテンツの再攻略
farm run=周回
farm group=周回グループ
learning run=練習の回
learning group=練習グループ
practice run=練習の回
training run=練習の回
clear run=クリアを目指す回
first clear=初クリア
first timer=初挑戦の人
first timers=初挑戦の人
parse=ダミー相手の火力測定
parsing=ダミー相手の火力測定
parse dummy=火力測定用ダミー
trial dummy=試練用の火力測定ダミー
target dummy=練習用ダミー
raid comp=レイド編成
group comp=グループ編成
team comp=チーム編成
comp=編成
strat=攻略方法
strats=攻略方法
raidwide=全体攻撃
tankbuster=タンク向けの大ダメージ攻撃
tank buster=タンク向けの大ダメージ攻撃
tank swap=タンク交代
tank swap mechanic=タンク交代ギミック
aggro reset=敵の狙いのリセット
threat drop=敵の狙いが外れること
body pull=接近による敵の釣り
chain pull=休みなく敵を釣ること
face pull=不用意な接近で敵を釣ること
proxy aggro=接近による敵の反応
heal aggro=回復で敵に狙われること
heal over time=継続回復
healing over time=継続回復
damage over time=継続ダメージ
single target=単体対象
single target damage=単体ダメージ
splash damage=周囲への巻き込みダメージ
splash heal=周囲への回復
hot uptime=継続回復の維持率
dot uptime=継続ダメージの維持率
buff uptime=強化効果の維持率
uptime=効果や攻撃を維持できる時間
boss uptime=ボスを攻撃できる時間
downtime=攻撃できない時間
]])

-- Community chat expansion (2026-09-16). Sources and scope: SLANG_SOURCES.md [raid].
D("x", [[
first time here=ここは初めてです
]])

-- Community chat expansion (2026-09-16). Sources and scope: SLANG_SOURCES.md [trade].
D("n", [[
boe=装備時に譲渡不可
bop=取得時に譲渡制限
bind on equip=装備時に譲渡不可
bind on pickup=取得時に譲渡制限
cod=代金引換
cash on delivery=代金引換
price check=相場確認
pricecheck=相場確認
vendor trash=店売り用の不要品
vendor junk=店売り用の不要品
gold sink=ゲーム内通貨の回収要素
listing fee=出品手数料
trading fee=取引手数料
full stack=最大数までまとまったアイテム
stack price=1スタックあたりの価格
unit price=1個あたりの価格
price per unit=1個あたりの価格
price per stack=1スタックあたりの価格
my mats=素材は自分が用意
your mats=素材はそちらで用意
]])

-- Community chat expansion (2026-09-16). Sources and scope: SLANG_SOURCES.md [trade].
D("x", [[
mats included=素材込み
mats provided=素材持参
have mats=素材は持っています
lf crafter=クラフターを探しています
looking for crafter=クラフターを探しています
lfw=クラフトの依頼募集中
ltb=購入希望
obo=価格相談可
or best offer=価格相談可
pst offer=希望価格をささやいてください
pst offers=希望価格をささやいてください
wts carry=キャリー代行を売ります
]])

-- Conjugatable readings for negation and modal verbs; fixed calls below remain the defaults.
D("v", [[
hard stack=同じ位置に密集する/s
soft stack=間隔を空けて集合する/s
stack tightly=同じ位置に密集する/s
stack loosely=間隔を空けて集合する/s
burn boss=ボスに火力を集中する/s
burn the boss=ボスに火力を集中する/s
nuke boss=ボスに火力を集中する/s
nuke the boss=ボスに火力を集中する/s
focus adds=追加の敵を優先する/s
ignore adds=追加の敵を無視する/s
ignore the adds=追加の敵を無視する/s
stop dps=攻撃を止める/1
hold dps=攻撃を止めて待つ/5
save ults=アルティメットを温存する/s
save ult=アルティメットを温存する/s
]])

-- Community chat expansion (2026-09-16). Sources and scope: SLANG_SOURCES.md [calls].
D("x", [[
lf7m=あと7人募集
lf9m=あと9人募集
lf11m=あと11人募集
lf1 tank=タンクをあと1人募集
lf1 healer=ヒーラーをあと1人募集
lf1 dd=火力役をあと1人募集
lf1 dps=火力役をあと1人募集
lf2 dd=火力役をあと2人募集
lf2 dps=火力役をあと2人募集
exp only=経験者のみ
experienced only=経験者のみ
link achievement=実績をリンクしてください
link achiev=実績をリンクしてください
link ach=実績をリンクしてください
link parse=火力測定結果を見せてください
need quest=クエストをやりたいです
need the quest=クエストをやりたいです
doing quest=クエスト中です
questing here=ここでクエスト中です
first time=初めてです
first run=初挑戦です
new here=ここは初めてです
new to this=これは初めてです
new to tanking=タンクは不慣れです
new to healing=ヒーラーは不慣れです
still learning=まだ練習中です
learning mechs=ギミックを練習中です
explain mechs=ギミックを説明してください
anyone need=欲しい人はいますか
free to take=自由に持っていってください
all yours=どうぞ持っていってください
wait for quest=クエストが終わるまで待ってください
wait for healer=ヒーラーを待ってください
wait for group=グループを待ってください
wait for everyone=全員を待ってください
do not rush=急がないでください
hard stack=同じ位置にぴったり重なって集合
soft stack=少し間隔を空けて集合
stack tightly=同じ位置にぴったり重なって集合
stack loosely=少し間隔を空けて集合
spread loosely=少し間隔を空けて散開
burn boss=ボスに火力を集中
burn the boss=ボスに火力を集中
nuke boss=ボスに火力を集中
nuke the boss=ボスに火力を集中
focus adds=追加の敵を優先
kill adds first=追加の敵を先に倒して
ignore adds=追加の敵は無視
ignore the adds=追加の敵は無視
stop dps=攻撃を止めて
hold dps=攻撃を止めて待って
save ults=アルティメットを温存
save ult=アルティメットを温存
ults ready=アルティメット準備OK
ult ready=アルティメット準備OK
ult up=アルティメット使用可能
ults up=アルティメット使用可能
ult down=アルティメット使用不可
ults down=アルティメット使用不可
rezzing=蘇生中
resing=蘇生中
rezz please=蘇生してください
res please=蘇生してください
need rez=蘇生してください
need res=蘇生してください
rez inc=今から蘇生します
res inc=今から蘇生します
wipe it=一度全滅してやり直そう
reset fight=戦闘をやり直そう
reset the fight=戦闘をやり直そう
nice pull=いい挑戦でした
good pull=いい挑戦でした
one more pull=もう一度挑戦
last pull=最後の挑戦
food check=食事バフを確認して
repair break=修理休憩
gear broken=装備が壊れています
brb repair=修理して戻ります
brb repairs=修理して戻ります
relogging=ログインし直しています
reloggin=ログインし直しています
dced=切断されました
dc would=切断されました
disconnected=切断されました
got dc=切断されました
i dced=切断されました
brb relog=ログインし直して戻ります
stuck in combat=戦闘状態が解除されません
can not bar swap=武器バーを切り替えられません
lagging hard=ラグがひどいです
rubber banding=ラグで位置が引き戻されます
packet loss=通信パケットの欠落
high ping=通信遅延が大きい状態
ping spike=通信遅延の急増
skill delay=スキル発動の遅延
skills not firing=スキルが発動しません
]])

-- Explicit short negative calls (no + action).
D("x", [[
no hard stack=密集しないでください
no soft stack=間隔を空けた集合はしないでください
]])

-- Ground-effect escape call; verb reading preserves negation and modal forms.
D("v", [[
get out of red=赤い範囲から出る/1
]])
