-- PB's Translate dictionary: verbs
--
-- english=辞書形/class/particle
--
--   class  1 ichidan, 5 godan, s suru, k kuru,
--          i / na for English verbs that are adjectives in Japanese (want -> 欲しい, like -> 好き)
--   particle  what marks the object, when it is not を: meet に会う, like が好き
--
-- A state verb ending in ている ("have" -> 持っている, "know" -> 知っている) comes out as
-- 持っています, which is how Japanese says those, and is never read as a command.

local D = PBsTranslate.Define

D("v", [[
be=いる/1
go=行く/5/に
come=来る/k/に
return=戻る/5/に
leave=出る/1/を
arrive=着く/5/に
enter=入る/5/に
exit=出る/1/を
get=もらう/5
take=取る/5
give=あげる/1
bring=持ってくる/k
send=送る/5
receive=受け取る/5
make=作る/5
do=する/s
have=持っている/1
own=持っている/1
hold=持つ/5
keep=取っておく/5
put=置く/5
use=使う/5
need=必要/na/が
want=欲しい/i/が
like=好き/na/が
love=大好き/na/が
hate=嫌い/na/が
prefer=好む/5
know=知っている/1
think=思う/5
believe=信じる/1
understand=分かる/5/が
remember=覚えている/1
forget=忘れる/1
learn=学ぶ/5
teach=教える/1
study=勉強する/s
see=見る/1
look=見る/1
watch=見る/1
look at=見る/1
look for=探す/5
search=探す/5
find=見つける/1
hear=聞く/5
listen=聞く/5
listen to=聞く/5
say=言う/5
tell=言う/5
talk=話す/5
speak=話す/5
talk to=話す/5/と
ask=聞く/5
answer=答える/1
reply=返事する/s
call=呼ぶ/5
write=書く/5
read=読む/5
type=入力する/s
mean=意味する/s
explain=説明する/s
agree=賛成する/s/に
disagree=反対する/s/に
feel=感じる/1
seem=見える/1
look like=似ている/1/に
eat=食べる/1
drink=飲む/5
cook=料理する/s
sleep=寝る/1
wake up=起きる/1
rest=休む/5
sit=座る/5/に
stand=立つ/5/に
walk=歩く/5
run=走る/5
jump=ジャンプする/s
swim=泳ぐ/5
fly=飛ぶ/5
ride=乗る/5/に
climb=登る/5
fall=落ちる/1
move=動く/5
follow=ついていく/5/に
lead=導く/5
wait=待つ/5
wait for=待つ/5
stay=いる/1/に
live=住んでいる/1/に
work=働く/5
play=遊ぶ/5
start=始める/1
begin=始める/1
stop=止める/1
finish=終わらせる/1
end=終わる/5
continue=続ける/1
try=試す/5
open=開ける/1
close=閉める/1
change=変える/1
turn=回す/5
turn on=つける/1
turn off=消す/5
break=壊す/5
fix=直す/5
repair=修理する/s
build=建てる/1
create=作る/5
destroy=破壊する/s
kill=倒す/5
die=死ぬ/5
live on=生き残る/5
survive=生き残る/5
fight=戦う/5/と
attack=攻撃する/s
defend=守る/5
protect=守る/5
guard=守る/5
hit=叩く/5
shoot=撃つ/5
cast=唱える/1
heal=回復する/s
revive=蘇生する/s
resurrect=蘇生する/s
res=蘇生する/s
rez=蘇生する/s
save=助ける/1
help=手伝う/5
support=サポートする/s
carry=運ぶ/5
win=勝つ/5/に
lose=失くす/5
beat=倒す/5
fail=失敗する/s/に
succeed=成功する/s/に
pass=通る/5
miss=逃す/5
catch=捕まえる/1
chase=追いかける/1
escape=逃げる/1/から
hide=隠れる/1
steal=盗む/5
pick=選ぶ/5
pick up=拾う/5
choose=選ぶ/5
decide=決める/1
buy=買う/5
sell=売る/5
pay=払う/5
trade=交換する/s
spend=使う/5
cost=かかる/5
earn=稼ぐ/5
farm=周回する/s
grind=周回する/s
collect=集める/1
gather=集める/1
craft=作る/5
cook up=作る/5
upgrade=強化する/s
improve=改善する/s
equip=装備する/s
wear=着る/1
share=共有する/s
lend=貸す/5
borrow=借りる/1
return to=戻る/5/に
invite=招待する/s
inv=招待する/s
join=参加する/s/に
kick=キックする/s
accept=受け入れる/1
refuse=断る/5
reject=拒否する/s
allow=許可する/s
let=させる/1
report=報告する/s
block=ブロックする/s
ignore=無視する/s
mute=ミュートする/s
add=追加する/s
remove=削除する/s
delete=削除する/s
check=確認する/s
test=テストする/s
show=見せる/1
hope=願う/5
wish=願う/5
plan=計画する/s
prepare=準備する/s
practice=練習する/s
train=訓練する/s
level=レベル上げする/s
level up=レベルアップする/s
queue=キューに入る/5
queue up=キューに入る/5
log in=ログインする/s
log on=ログインする/s
log out=ログアウトする/s
log off=ログアウトする/s
logout=ログアウトする/s
login=ログインする/s
relog=再ログインする/s
reload=リロードする/s
restart=再起動する/s
crash=落ちる/1
lag=ラグる/5
disconnect=切断する/s
dc=切断する/s
afk=離席している/1
port=ポートする/s
teleport=テレポートする/s
travel=移動する/s/に
explore=探索する/s
quest=クエストをする/s
complete=完了する/s
clear=クリアする/s
solo=ソロでやる/5
duo=二人でやる/5
group up=グループを組む/5
party up=パーティーを組む/5
tank=タンクをする/s
dps=DPSをする/s
roll=ロールする/s
reset=リセットする/s
respec=リスペックする/s
spawn=湧く/5
respawn=リスポーンする/s
pull=引く/5
aggro=タゲを取る/5
taunt=挑発する/s
interrupt=妨害する/s
dodge=回避する/s
dodge roll=回避する/s
block=ブロックする/s
stack=固まる/5
stack up=固まる/5
spread out=散る/5
wipe=全滅する/s
enjoy=楽しむ/5
laugh=笑う/5
cry=泣く/5
smile=笑う/5
worry=心配する/s
care=気にする/s
mind=気にする/s
thank=感謝する/s/に
apologize=謝る/5
forgive=許す/5
promise=約束する/s
lie=嘘をつく/5
cheat=ずるをする/s
joke=冗談を言う/5
kid=冗談を言う/5
dance=踊る/5
sing=歌う/5
meet=会う/5/に
visit=訪れる/1
marry=結婚する/s/と
date=付き合う/5/と
greet=挨拶する/s/に
welcome=歓迎する/s
celebrate=祝う/5
count=数える/1
measure=測る/5
compare=比べる/1
match=合う/5/に
fit=合う/5/に
include=含む/5
contain=含む/5
belong=属する/s/に
depend=次第/na
matter=重要/na
happen=起こる/5
exist=存在する/s
appear=現れる/1
disappear=消える/1
grow=育つ/5
become=なる/5/に
get to=着く/5/に
go back=戻る/5/に
come back=戻ってくる/k/に
come on=来る/k
hurry=急ぐ/5
hurry up=急ぐ/5
calm down=落ち着く/5
give up=諦める/1
set up=準備する/s
sign up=登録する/s
show up=来る/k
find out=分かる/5
figure out=理解する/s
work out=うまくいく/5
hang out=遊ぶ/5
look forward to=楽しみにしている/1
take care=気をつける/1
pay attention=注意する/s
make sure=確認する/s
fill=満たす/5
empty=空にする/s
throw=投げる/1
drop=落とす/5
push=押す/5
press=押す/5
touch=触る/5/に
hug=ハグする/s
kiss=キスする/s
wake=起こす/5
dream=夢を見る/1
imagine=想像する/s
guess=推測する/s
expect=期待する/s
suggest=提案する/s
recommend=おすすめする/s
offer=提供する/s
provide=提供する/s
require=必要とする/s
deserve=値する/s/に
suck=下手/na
rock=最高/na
recruit=募集する/s
be back=戻る/5
be right back=すぐ戻る/5
lose to=負ける/1/に
have a question=質問がある/5
have questions=質問がある/5
have time=時間がある/5
have a problem=問題がある/5
have an idea=考えがある/5
have no idea=分からない/i
have plans=予定がある/5
have space=空きがある/5
have room=空きがある/5
have a spot=空きがある/5
lf=探す/5
]])

-- Participles and states that English says with "be": "I am tired", "it is broken".
D("v", [[
tired=疲れている/1
exhausted=疲れ切っている/1
done=終わっている/1
finished=終わっている/1
ready=準備ができている/1
busy=忙しい/i
stuck=詰まっている/1
broken=壊れている/1
bugged=バグっている/1
dead=死んでいる/1
alive=生きている/1
online=オンライン/na
offline=オフライン/na
full=満員/na
bored=退屈している/1
confused=混乱している/1
excited=ワクワクしている/1
interested=興味がある/5
worried=心配している/1
scared=怖がっている/1
afraid=怖がっている/1
surprised=驚いている/1
married=結婚している/1
located=ある/5
missing=足りない/i
closed=閉まっている/1
opened=開いている/1
sold out=売り切れている/1
angry=怒っている/1
mad=怒っている/1
upset=怒っている/1
wrong=間違っている/1
similar=似ている/1
nervous=緊張している/1
hungry=お腹がすいている/1
thirsty=喉が渇いている/1
worth=価値がある/5
]])

-- More verbs
D("v", [[
accompany=同行する/s
achieve=達成する/s
act=行動する/s
admit=認める/1
advise=助言する/s
afford=買う余裕がある/5
aim=狙う/5
announce=発表する/s
annoy=イライラさせる/1
apply=申し込む/5
appreciate=感謝する/s
approach=近づく/5/に
argue=言い争う/5
arrange=手配する/s
attend=出席する/s/に
avoid=避ける/1
bake=焼く/5
bark=吠える/1
bathe=入浴する/s
beg=頼み込む/5
behave=振る舞う/5
bend=曲げる/1
bet=賭ける/1
bite=噛む/5
blame=責める/1
bleed=出血する/s
blow=吹く/5
boil=沸かす/5
bother=邪魔する/s
bounce=跳ねる/1
breathe=呼吸する/s
brush=磨く/5
burn=燃やす/5
bury=埋める/1
calculate=計算する/s
camp=キャンプする/s
cancel=キャンセルする/s
capture=捕まえる/1
chat=チャットする/s
cheer=応援する/s
chew=噛む/5
clap=拍手する/s
click=クリックする/s
collapse=倒れる/1
comment=コメントする/s
communicate=連絡する/s
complain=文句を言う/5
concentrate=集中する/s
confirm=確認する/s
connect=接続する/s
consider=検討する/s
contact=連絡する/s/に
control=操作する/s
convince=説得する/s
copy=コピーする/s
correct=訂正する/s
cough=咳をする/s
cover=覆う/5
crawl=這う/5
cross=渡る/5
crush=潰す/5
cure=治す/5
cycle=自転車に乗る/5
damage=傷つける/1
deliver=届ける/1
deny=否定する/s
describe=説明する/s
design=設計する/s
develop=開発する/s
dig=掘る/5
discover=発見する/s
discuss=話し合う/5
dislike=嫌う/5
divide=分ける/1
donate=寄付する/s
download=ダウンロードする/s
drag=引きずる/5
draw=描く/5
dress=服を着る/1
drive=運転する/s
drown=溺れる/1
earn=稼ぐ/5
edit=編集する/s
educate=教育する/s
employ=雇う/5
encourage=励ます/5
examine=調べる/1
exchange=交換する/s
excuse=許す/5
exercise=運動する/s
expand=広げる/1
experience=経験する/s
explode=爆発する/s
face=向き合う/5/と
fade=消えていく/5
fear=恐れる/1
feed=食べさせる/1
fetch=取ってくる/k
file=提出する/s
film=撮影する/s
fish=釣りをする/s
flash=光る/5
float=浮かぶ/5
flow=流れる/1
fold=畳む/5
force=強制する/s
form=作る/5
freeze=凍る/5
frighten=怖がらせる/1
gain=得る/1
glow=光る/5
grab=掴む/5
greet=挨拶する/s/に
guard=守る/5
guide=案内する/s
hang=掛ける/1
harm=傷つける/1
hatch=孵化する/s
heat=温める/1
hunt=狩る/5
hurt=痛む/5
identify=特定する/s
improve=上達する/s
increase=増やす/5
inform=知らせる/1
injure=怪我をする/s
insist=言い張る/5
install=インストールする/s
introduce=紹介する/s
investigate=調査する/s
iron=アイロンをかける/1
jog=ジョギングする/s
judge=判断する/s
kneel=ひざまずく/5
knit=編む/5
knock=ノックする/s
land=着陸する/s
last=続く/5
lay=置く/5
lean=寄りかかる/5
lick=舐める/1
lift=持ち上げる/1
light=火をつける/1
limit=制限する/s
list=並べる/1
load=読み込む/5
lock=鍵をかける/1
manage=管理する/s
mark=印をつける/1
melt=溶ける/1
mention=言及する/s
mix=混ぜる/1
moan=うめく/5
murder=殺す/5
nod=うなずく/5
note=メモする/s
notice=気づく/5/に
obey=従う/5/に
observe=観察する/s
obtain=入手する/s
occur=起こる/5
order=注文する/s
organize=整理する/s
overcome=乗り越える/1
paint=塗る/5
park=駐車する/s
participate=参加する/s/に
pause=一時停止する/s
perform=演じる/1
permit=許可する/s
persuade=説得する/s
phone=電話する/s/に
pinch=つねる/5
plant=植える/1
play with=遊ぶ/5/と
point=指さす/5
polish=磨く/5
pour=注ぐ/5
pray=祈る/5
predict=予測する/s
pretend=ふりをする/s
print=印刷する/s
produce=生産する/s
program=プログラムする/s
protest=抗議する/s
prove=証明する/s
publish=公開する/s
punch=殴る/5
punish=罰する/s
purchase=購入する/s
quit=やめる/1
race=競争する/s
rain=雨が降る/5
raise=上げる/1
reach=届く/5/に
realize=気づく/5/に
recognize=認識する/s
record=記録する/s
recover=回復する/s
reduce=減らす/5
reflect=反省する/s
regret=後悔する/s
relax=くつろぐ/5
release=解放する/s
rely=頼る/5/に
remain=残る/5
remind=思い出させる/1
rent=借りる/1
replace=交換する/s
request=依頼する/s
rescue=救う/5
respect=尊敬する/s
respond=返事する/s
review=見直す/5
rob=奪う/5
roll=転がす/5
rub=こする/5
rule=支配する/s
rush=急ぐ/5
satisfy=満足させる/1
scream=叫ぶ/5
seek=探す/5
select=選択する/s
serve=仕える/1
settle=落ち着く/5
shake=振る/5
shine=輝く/5
shout=叫ぶ/5
shut=閉める/1
sigh=ため息をつく/5
sign=署名する/s
sink=沈む/5
skip=飛ばす/5
slap=叩く/5
slide=滑る/5
slip=滑る/5
smell=匂いを嗅ぐ/5
snow=雪が降る/5
solve=解決する/s
sort=並べ替える/1
spell=綴る/5
spill=こぼす/5
split=分ける/1
spray=吹き付ける/1
squeeze=絞る/5
stare=見つめる/1
steer=操縦する/s
stick=くっつく/5
sting=刺す/5
store=保管する/s
stretch=伸ばす/5
strike=打つ/5
struggle=苦戦する/s
suffer=苦しむ/5
supply=供給する/s
suppose=思う/5
surround=囲む/5
suspect=疑う/5
swear=誓う/5
sweat=汗をかく/5
swing=振る/5
switch=切り替える/1
tap=タップする/s
taste=味わう/5
tear=破る/5
thank you=感謝する/s/に
tidy=片付ける/1
tie=結ぶ/5
touch=触る/5/に
tour=見て回る/5
trace=たどる/5
translate=翻訳する/s
trap=罠にかける/1
treat=扱う/5
tremble=震える/1
trick=騙す/5
trust=信頼する/s
twist=ねじる/5
unite=団結する/s
unpack=荷ほどきする/s
update=更新する/s
upload=アップロードする/s
vanish=消える/1
vote=投票する/s
warn=警告する/s
wash=洗う/5
waste=無駄にする/s
water=水をやる/5
wave=手を振る/5
weigh=量る/5
whisper=ささやく/5
whistle=口笛を吹く/5
wonder=不思議に思う/5
worship=崇拝する/s
wrap=包む/5
yawn=あくびをする/s
yell=叫ぶ/5
zoom=ズームする/s
-- chat and online
dm=DMする/s
message=メッセージを送る/5
pm=個別メッセージを送る/5
text=メッセージを送る/5
stream=配信する/s
screenshot=スクショを撮る/5
like it=気に入っている/1
nerf=弱体化する/s
buff=強化する/s
ban=BANする/s
report=通報する/s
spam=スパムする/s
troll=荒らす/5
unfriend=フレンドを解除する/s
save=保存する/s
load=ロードする/s
subscribe=登録する/s
google=検索する/s
]])

-- High-school vocabulary, part 1 (2026-09-15)
D("v", [[
account for=説明する/s
accuse=非難する/s
acquire=習得する/s
adapt=適応する/s/に
adjust=調整する/s
admire=感心する/s/に
adopt=採用する/s
advance=進む/5
advertise=宣伝する/s
affect=影響する/s/に
aid=援助する/s
alter=変える/1
amaze=驚かせる/1
amuse=楽しませる/1
analyze=分析する/s
analyse=分析する/s
anticipate=予想する/s
apologise=謝る/5
appeal=訴える/1
applaud=拍手する/s
appoint=任命する/s
approve=承認する/s
argue about=議論する/s
arise=生じる/1
arrest=逮捕する/s
assemble=組み立てる/1
assess=評価する/s
assign=割り当てる/1
assist=手伝う/5
associate=関連付ける/1
assume=思い込む/5
assure=保証する/s
attach=取り付ける/1
attempt=試みる/1
attract=引きつける/1
awake=目覚める/1
belong to=属する/s/に
bless=祝福する/s
boast=自慢する/s
breed=育てる/1
broadcast=放送する/s
cause=引き起こす/5
cease=やめる/1
challenge=挑戦する/s/に
charge=請求する/s
cheer up=元気づける/1
claim=主張する/s
classify=分類する/s
clear up=片付ける/1
combine=組み合わせる/1
comfort=慰める/1
command=命令する/s
commit=犯す/5
communicate with=連絡する/s/と
compete=競争する/s
complain about=文句を言う/5
compose=作曲する/s
concentrate on=集中する/s/に
concern=関係する/s/に
conclude=結論づける/1
conduct=行う/5
confess=告白する/s
confuse=混乱させる/1
congratulate=祝う/5
connect with=つながる/5/と
conquer=征服する/s
consist of=成り立つ/5
construct=建設する/s
consult=相談する/s/に
consume=消費する/s
contribute=貢献する/s/に
convert=変換する/s
cooperate=協力する/s/と
cope with=対処する/s/に
correspond=一致する/s/と
cover up=隠す/5
crack=割る/5
criticize=批判する/s
criticise=批判する/s
cultivate=栽培する/s
cut down=減らす/5
dare=思い切ってする/s
deal with=対処する/s/に
declare=宣言する/s
decline=断る/5
decorate=飾る/5
decrease=減る/5
defeat=打ち負かす/5
delay=遅らせる/1
delight=喜ばせる/1
demand=要求する/s
demonstrate=実演する/s
depart=出発する/s
depend on=頼る/5/に
deposit=預ける/1
derive=由来する/s
descend=下りる/1
desire=強く望む/5
detect=見つける/1
determine=決定する/s
devote=捧げる/1
differ=異なる/5
digest=消化する/s
direct=指示する/s
disappoint=がっかりさせる/1
discourage=落胆させる/1
dismiss=解散させる/1
display=展示する/s
distinguish=区別する/s
distribute=配る/5
disturb=邪魔する/s
dive=飛び込む/5
divorce=離婚する/s/と
elect=選ぶ/5
eliminate=取り除く/5
embarrass=恥ずかしい思いをさせる/1
emerge=現れる/1
emphasize=強調する/s
enable=可能にする/s
encounter=出会う/5/に
endure=耐える/1
engage=従事する/s/に
enhance=高める/1
ensure=確実にする/s
entertain=楽しませる/1
establish=設立する/s
estimate=見積もる/5
evaluate=評価する/s
evolve=進化する/s
exaggerate=誇張する/s
exceed=超える/1
exclude=除外する/s
exhibit=展示する/s
export=輸出する/s
expose=さらす/5
express=表現する/s
extend=延長する/s
fasten=締める/1
favor=好む/5
feed on=食べる/1
fight for=戦う/5
fill in=記入する/s
fill out=記入する/s
focus=集中する/s/に
forbid=禁止する/s
fry=揚げる/1
fulfill=果たす/5
get along=仲良くする/s/と
get off=降りる/1/から
get on=乗る/5/に
get up=起きる/1
glance=ちらっと見る/1
govern=統治する/s
graduate=卒業する/s/を
grant=与える/1
grin=にやりと笑う/5
grip=握る/5
guarantee=保証する/s
handle=扱う/5
hang up=電話を切る/5
heat up=温める/1
hesitate=ためらう/5
hire=雇う/5
illustrate=説明する/s
impress=感動させる/1
import=輸入する/s
indicate=示す/5
infect=感染させる/1
influence=影響を与える/1/に
inherit=受け継ぐ/5
insert=差し込む/5
inspire=刺激する/s
instruct=指導する/s
insult=侮辱する/s
interpret=解釈する/s
invent=発明する/s
invest=投資する/s
involve=巻き込む/5
isolate=孤立させる/1
leap=跳ぶ/5
lecture=講義する/s
lie down=横になる/5
locate=見つける/1
look after=世話をする/s
look up=調べる/1
maintain=維持する/s
manufacture=製造する/s
modify=修正する/s
monitor=監視する/s
motivate=やる気にさせる/1
multiply=掛ける/1
negotiate=交渉する/s
occupy=占める/1
offend=怒らせる/1
operate=操作する/s
oppose=反対する/s/に
overlook=見落とす/5
owe=借りている/1
pack=詰める/1
participate in=参加する/s/に
perceive=気づく/5/に
pick out=選ぶ/5
praise=褒める/1
preserve=保存する/s
prevent=防ぐ/5
proceed=進む/5
prohibit=禁止する/s
promote=促進する/s
pronounce=発音する/s
propose=提案する/s
pursue=追求する/s
put off=延期する/s
put on=着る/1
qualify=資格を得る/1
quote=引用する/s
react=反応する/s/に
recall=思い出す/5
refer to=言及する/s/に
regard=みなす/5
register=登録する/s
relate=関係づける/1
rely on=頼る/5/に
represent=代表する/s
resemble=似ている/1/に
reserve=予約する/s
resign=辞める/1
resist=抵抗する/s/に
resolve=解決する/s
restore=修復する/s
retire=引退する/s
reveal=明らかにする/s
revise=改訂する/s
scare=怖がらせる/1
scatter=まき散らす/5
scratch=引っかく/5
seal=封をする/s
seize=つかむ/5
shift=移す/5
shock=衝撃を与える/1
sneeze=くしゃみをする/s
sort out=整理する/s
spare=割く/5
specialize=専門にする/s
spin=回る/5
spoil=台無しにする/s
sponsor=後援する/s
stand for=表す/5
stare at=見つめる/1
starve=飢える/1
stimulate=刺激する/s
stir=かき混ぜる/1
strengthen=強化する/s
submit=提出する/s
substitute=代わりに使う/5
suit=似合う/5/に
swallow=飲み込む/5
sweep=掃く/5
take off=脱ぐ/5
take part in=参加する/s/に
tend=傾向がある/5
terrify=怖がらせる/1
thrill=わくわくさせる/1
tolerate=我慢する/s
toss=投げる/1
transfer=移す/5
transform=変える/1
transport=輸送する/s
try on=試着する/s
turn down=断る/5
turn into=変わる/5/に
urge=促す/5
vary=変わる/5
wander=さまよう/5
weaken=弱める/1
wound=傷つける/1
yield=生む/5
]])

-- Adjective + preposition set phrases, read as one predicate: "interested in history" ->
-- 歴史に興味があります. The particle is what the English preposition becomes.
D("v", [[
interested in=興味がある/5/に
good at=得意/na/が
bad at=苦手/na/が
poor at=苦手/na/が
afraid of=怖い/i/が
scared of=怖い/i/が
proud of=誇りに思っている/1/を
tired of=飽きている/1/に
sick of=うんざりしている/1/に
famous for=有名/na/で
known for=知られている/1/で
full of=いっぱい/na/で
different from=異なっている/1/と
similar to=似ている/1/に
responsible for=責任がある/5/に
familiar with=詳しい/i/に
fond of=好き/na/が
aware of=気づいている/1/に
satisfied with=満足している/1/に
pleased with=喜んでいる/1/に
worried about=心配している/1/を
excited about=わくわくしている/1/に
surprised at=驚いている/1/に
surprised by=驚いている/1/に
angry with=怒っている/1/に
angry at=怒っている/1/に
angry about=怒っている/1/に
kind to=親切/na/に
close to=近い/i/に
far from=遠い/i/から
late for=遅れる/1/に
busy with=忙しい/i/で
good for=良い/i/に
bad for=悪い/i/に
necessary for=必要/na/に
important for=重要/na/に
graduate from=卒業する/s/を
suffer from=苦しんでいる/1/に
recover from=回復する/s/から
apologize for=謝る/5/のことで
apologise for=謝る/5/のことで
thank for=感謝する/s/に
wait for=待つ/5
look for=探す/5
care about=気にかける/1/を
care for=世話をする/s/の
listen to=聞く/5
talk about=話す/5/について
think about=考える/1/について
dream of=夢見る/1/を
dream about=夢見る/1/を
agree with=同意する/s/に
arrive at=着く/5/に
arrive in=着く/5/に
succeed in=成功する/s/に
fail in=失敗する/s/に
believe in=信じる/1/を
consist of=成り立つ/5/から
depend on=頼る/5/に
focus on=集中する/s/に
insist on=言い張る/5/を
laugh at=笑う/5/を
look at=見る/1
look like=似ている/1/に
prepare for=準備する/s/の
search for=探す/5
take care of=世話をする/s/の
get rid of=取り除く/5
make fun of=からかう/5
run out of=使い果たす/5
put up with=我慢する/s/を
come up with=思いつく/5/を
keep up with=ついていく/5/に
catch up with=追いつく/5/に
look up to=尊敬する/s/を
look down on=見下す/5
]])

-- Directions
D("v", [[
turn left=左に曲がる/5
turn right=右に曲がる/5
go straight=まっすぐ行く/5
go back=戻る/5/に
]])

-- High-school vocabulary, part 2 (2026-09-15)
D("v", [[
abandon=見捨てる/1
abolish=廃止する/s
absorb=吸収する/s
abuse=乱用する/s
accelerate=加速する/s
accumulate=蓄積する/s
acknowledge=認める/1
activate=作動させる/1
advocate=主張する/s
alert=警告する/s
allocate=割り当てる/1
amend=修正する/s
apply for=申し込む/5/に
arouse=呼び起こす/5
ascend=登る/5
attain=達成する/s
authorize=許可する/s
await=待つ/5
bargain=交渉する/s
betray=裏切る/5
bid=入札する/s
blend=混ぜる/1
blink=まばたきする/s
boost=高める/1
browse=見て回る/5
bump=ぶつかる/5/に
burst=破裂する/s
cherish=大切にする/s
chop=刻む/5
circulate=循環する/s
cite=引用する/s
clarify=明確にする/s
cling=しがみつく/5/に
coincide=同時に起こる/5
collaborate=協力する/s/と
commute=通勤する/s
compensate=補償する/s
compile=まとめる/1
complement=補う/5
comply=従う/5/に
comprehend=理解する/s
comprise=成る/5
compromise=妥協する/s
conceal=隠す/5
concede=認める/1
condemn=非難する/s
confine=限定する/s
confront=立ち向かう/5/に
conserve=保存する/s
constitute=構成する/s
contemplate=熟考する/s
contradict=矛盾する/s/と
convey=伝える/1
convict=有罪とする/s
coordinate=調整する/s
correspond with=文通する/s/と
counsel=助言する/s
cruise=巡航する/s
dedicate=捧げる/1
deduce=推論する/s
define=定義する/s
deprive=奪う/5
designate=指定する/s
despise=軽蔑する/s
deteriorate=悪化する/s
devise=考案する/s
diagnose=診断する/s
dictate=指図する/s
diminish=減少する/s
discard=捨てる/1
discharge=放出する/s
disclose=公開する/s
disguise=変装する/s
dispose of=処分する/s
dispute=論争する/s
dissolve=溶ける/1
distort=ゆがめる/1
distract=気をそらす/5
dominate=支配する/s
doubt about=疑う/5
drift=漂う/5
dump=捨てる/1
duplicate=複製する/s
dwell=住む/5/に
embrace=抱きしめる/1
emit=放出する/s
enclose=同封する/s
endanger=危険にさらす/5
enforce=施行する/s
enrich=豊かにする/s
enroll=登録する/s
entitle=権利を与える/1
erase=消す/5
erupt=噴火する/s
escalate=拡大する/s
evacuate=避難する/s
evaporate=蒸発する/s
exhaust=使い果たす/5
expel=追放する/s
exploit=利用する/s
extinguish=消す/5
extract=抽出する/s
facilitate=促進する/s
fascinate=魅了する/s
flee=逃げる/1
flourish=栄える/1
fluctuate=変動する/s
foresee=予見する/s
formulate=策定する/s
foster=育成する/s
frown=眉をひそめる/1
frustrate=いらだたせる/1
generate=生み出す/5
glide=滑るように進む/5
grasp=理解する/s
guard against=用心する/s/に
halt=止める/1
hinder=妨げる/1
illuminate=照らす/5
imitate=まねる/1
immigrate=移住する/s
implement=実行する/s
imply=ほのめかす/5
impose=課す/5
imprison=投獄する/s
incline=傾ける/1
incorporate=組み込む/5
indulge=ふける/5/に
inhabit=住む/5/に
inhibit=抑える/1
initiate=始める/1
inject=注入する/s
innovate=革新する/s
inquire=問い合わせる/1
inspect=検査する/s
integrate=統合する/s
intensify=強める/1
interact=交流する/s/と
interfere=干渉する/s/に
intervene=介入する/s/に
invade=侵略する/s
irritate=いらいらさせる/1
justify=正当化する/s
kidnap=誘拐する/s
label=ラベルを貼る/5
launch=開始する/s
leak=漏れる/1
legislate=法律を制定する/s
liberate=解放する/s
linger=ぐずぐずする/s
litter=散らかす/5
magnify=拡大する/s
maximize=最大化する/s
meditate=瞑想する/s
merge=合併する/s
migrate=移動する/s
minimize=最小化する/s
mislead=誤解させる/1
misunderstand=誤解する/s
mock=あざける/5
mourn=嘆く/5
navigate=操縦する/s
neglect=怠る/5
nominate=指名する/s
nourish=養う/5
nurture=育む/5
object to=反対する/s/に
oblige=義務づける/1
obscure=曖昧にする/s
occupy oneself=従事する/s/に
omit=省略する/s
originate=始まる/5
overflow=あふれる/1
overhear=ふと耳にする/s
overtake=追い越す/5
overthrow=打倒する/s
overwhelm=圧倒する/s
owe to=おかげである/5
penetrate=貫く/5
persist=固執する/s/に
pile=積み重ねる/1
plead=嘆願する/s
plunge=突っ込む/5
point out=指摘する/s
portray=描写する/s
pose=提起する/s
possess=所有する/s
postpone=延期する/s
precede=先行する/s
prescribe=処方する/s
presume=推定する/s
prevail=広まる/5
proclaim=宣言する/s
prolong=延長する/s
prompt=促す/5
prosecute=起訴する/s
prosper=繁栄する/s
provoke=引き起こす/5
purify=浄化する/s
quit smoking=禁煙する/s
radiate=放射する/s
rearrange=並べ替える/1
reassure=安心させる/1
rebel=反抗する/s/に
recite=暗唱する/s
reckon=思う/5
reconcile=和解させる/1
regain=取り戻す/5
regulate=規制する/s
rehearse=練習する/s
reinforce=強化する/s
rejoice=喜ぶ/5
relieve=和らげる/1
remark=述べる/1
remedy=改善する/s
renew=更新する/s
renovate=改装する/s
repay=返済する/s
repent=後悔する/s
reproduce=再現する/s
rescue from=救い出す/5/から
resent=憤慨する/s
reside=住む/5/に
restrain=抑える/1
restrict=制限する/s
resume=再開する/s
retain=保持する/s
retreat=退却する/s
retrieve=取り戻す/5
reunite=再会する/s/と
revolve=回転する/s
rid=取り除く/5
ridicule=あざける/5
roam=歩き回る/5
rot=腐る/5
sacrifice=犠牲にする/s
salute=敬礼する/s
scan=ざっと見る/1
scold=叱る/5
scrub=こすり洗いする/s
shatter=粉々にする/s
shiver=震える/1
shrink=縮む/5
shrug=肩をすくめる/1
simplify=単純化する/s
simulate=模擬する/s
situate=位置させる/1
skate=スケートをする/s
ski=スキーをする/s
slaughter=虐殺する/s
slam=バタンと閉める/1
sob=すすり泣く/5
soak=浸す/5
soar=急上昇する/s
sow=種をまく/5
sparkle=きらめく/5
speculate=推測する/s
spit=吐く/5
sprinkle=振りかける/1
stabilize=安定させる/1
stagger=よろめく/5
stain=汚す/5
startle=びっくりさせる/1
stumble=つまずく/5
subscribe to=購読する/s
succeed to=継ぐ/5
summarize=要約する/s
supervise=監督する/s
suppress=抑圧する/s
surpass=上回る/5
surrender=降伏する/s
suspend=一時停止する/s
sustain=維持する/s
swell=腫れる/1
symbolize=象徴する/s
sympathize=同情する/s/に
tackle=取り組む/5/に
tempt=誘惑する/s
terminate=終わらせる/1
testify=証言する/s
thrive=繁栄する/s
torture=拷問する/s
trade with=貿易する/s/と
transmit=伝える/1
trigger=引き起こす/5
tumble=転ぶ/5
undergo=経験する/s
underline=強調する/s
undermine=弱体化させる/1
undertake=引き受ける/1
undo=元に戻す/5
unfold=広げる/1
uphold=支持する/s
utilize=利用する/s
verify=確かめる/1
violate=違反する/s/に
weave=織る/5
widen=広げる/1
withdraw=引き出す/5
withstand=耐える/1
wrestle=格闘する/s
]])

-- High-school vocabulary, part 3 (2026-09-15)
D("v", [[
refer=参照する/s
repeat=繰り返す/5
rise=上がる/5
sail=航海する/s
shave=そる/5
organise=組織する/s
excite=興奮させる/1
intend=つもりである/5
consist=成り立つ/5/から
born=生まれる/1
brush one 's teeth=歯を磨く/5
brush my teeth=歯を磨く/5
take a bath=お風呂に入る/5
take a shower=シャワーを浴びる/1
take a walk=散歩する/s
take a picture=写真を撮る/5
take a photo=写真を撮る/5
take a rest=休憩する/s
take a break=休憩する/s
have breakfast=朝ごはんを食べる/1
have lunch=昼ごはんを食べる/1
have dinner=夕ごはんを食べる/1
do homework=宿題をする/s
do my homework=宿題をする/s
do the dishes=皿洗いをする/s
do the laundry=洗濯をする/s
go shopping=買い物に行く/5
go fishing=釣りに行く/5
go camping=キャンプに行く/5
go skiing=スキーに行く/5
go swimming=泳ぎに行く/5
go to bed=寝る/1
go to school=学校に行く/5
go home=家に帰る/5
come home=帰宅する/s
get home=家に着く/5
make a mistake=間違える/1
make mistakes=間違える/1
make friends=友達を作る/5
make a decision=決める/1
make progress=進歩する/s
make money=お金を稼ぐ/5
make noise=騒ぐ/5
pay attention to=注意を払う/5/に
catch a cold=風邪をひく/5
have a cold=風邪をひいている/1
have a fever=熱がある/5
have a headache=頭が痛い/i
have a good time=楽しく過ごす/5
feel like=気がする/s
feel sick=気分が悪い/i
get married=結婚する/s/と
get lost=道に迷う/5
get better=良くなる/5
get worse=悪くなる/5
get angry=怒る/5
get tired=疲れる/1
get well=元気になる/5
get ready=準備する/s
get used to=慣れる/1/に
be used to=慣れている/1/に
give a speech=スピーチをする/s
keep in touch=連絡を取り合う/5/と
stay up late=夜更かしする/s
wake up early=早起きする/s
change trains=電車を乗り換える/1
miss the train=電車に乗り遅れる/1
miss the bus=バスに乗り遅れる/1
]])

-- Online game slang (2026-09-15)
D("v", [[
int=わざと死ぬ/5
inting=わざと死んでいる/1
botting=ボットを使っている/1
flaming=暴言を吐いている/1
tilt=イライラする/s
ragequit=キレて抜ける/1
rage quit=キレて抜ける/1
smurfing=サブ垢で遊んでいる/1
clutch=土壇場で決める/1
carry me=キャリーする/s
boost me=ブーストする/s
power level=パワーレベリングする/s
min max=極める/1
ninja loot=横取りする/s
body block=体で止める/1
spawn camp=湧き待ちする/s
dodge queue=キューを抜ける/1
get carried=キャリーされる/1
]])

-- Participle phrases, as predicates of their own: "made of iron" -> 鉄でできている. They also
-- modify a noun from behind ("a sword made of iron", see Grammar.lua PostModifierStart).
D("v", [[
made of=できている/1/で
made from=作られている/1/から
made in=作られている/1/で
known as=知られている/1/として
written by=書かれている/1/に
filled with=満たされている/1/で
covered with=覆われている/1/で
located in=ある/5/に
based on=基づいている/1/に
used for=使われている/1/に
]])
