TetsuDailyWritPrecrafter = TetsuDailyWritPrecrafter or {}
local L = TetsuDailyWritPrecrafter.L
if not L then return end

L.TITLE                   = "|cFFD700Tetsu's|r Daily Writ Precrafter "

L.OPTIONS_SECTION_LABEL   = "自動化"
L.OPTIONS_SECTION_TT      = "ゲームパッド向けの安全な自動化オプション。"
L.INFO_LABEL              = "情報"
L.INFO_TT                 = "アドオンが役立ったら、ゲーム内メールで @Tetsurion へ少しゴールドを送っていただけると嬉しいです。不具合やアイデアも同じ宛先へ。\n\nLazy Writ併用（初期設定）：今日の依頼・受注・納品・箱は Lazy Writ。製作台で R3 を押すと、スライダーの日数分を明日から事前製作します。\n\n単独（Lazy Writオプションと Lazy Writ 本体をオフ）：初期は進行中の依頼のみ。事前製作をオンにして R3 で今日＋先の日数。自動受注・納品・箱は「自動化」にあります。"
L.COMPAT_LWC_LABEL        = "Lazy Writ Creator と併用"
L.COMPAT_LWC_TT           = "初期ON。今日の依頼・受注・納品・箱は Lazy Writ。このアドオンは明日からの R3 事前製作。\n単独モードに切り替える前に Dolgubon's Lazy Writ Creator をオフにしてください。\nこの設定を変えるとUIが再読み込みされます。"
L.AUTO_QUEST_LABEL        = "クラフト依頼の自動受注・納品"
L.AUTO_QUEST_TT           = "掲示板から依頼を受け、箱で自動的に納品します。"
L.AUTO_BOX_LABEL          = "報酬箱を自動で開く"
L.AUTO_BOX_TT             = "デイリークエストの報酬コンテナがバッグに入ったらすぐに開きます。"

L.PRECRAFT_SECTION_LABEL  = "プレクラフト（このキャラクター）"
L.PRECRAFT_SECTION_TT     = "設定はこのキャラクターごとに保存されます。"
L.PRECRAFT_ENABLED_LABEL  = "将来分をプレクラフトする"
L.PRECRAFT_ENABLED_TT     = "有効時：R3で日替わりローテーションに従い数日分を作成。無効時：R3は進行中の依頼に必要なものだけ作成。"
L.PRECRAFT_DAYS_LABEL     = "何日分先まで"
L.PRECRAFT_DAYS_TT        = "何日分プレクラフトするか（今日を含む）。スライダー 1～10。"
L.PRECRAFT_DAYS_TT_COMPAT = "今日より先の日数。今日の依頼は Lazy Writ Creator。1＝明日のみ。3＝明日＋さらに2日。"

L.KEYBIND_PRECRAFT        = "|c00FF00[R3]|r プレクラフト <<1>>日 (<<2>>個)"
L.KEYBIND_QUEST_CRAFT     = "|c00FF00[R3]|r 進行中の依頼を作成 (<<1>>個)"
L.KEYBIND_NOTHING         = "|c888888[R3]|r 作成するものなし"

L.CONFIRM_TITLE_PRECRAFT  = "デイリークエストのプレクラフト"
L.CONFIRM_PROMPT_PRECRAFT = "<<1>>日分のアイテムを作成しますか？（<<2>>個）"
L.CONFIRM_TITLE_QUEST     = "進行中の依頼を作成"
L.CONFIRM_PROMPT_QUEST    = "進行中の依頼に必要なアイテムを作成しますか？（<<1>>個）"

L.PROGRESS_CRAFTING       = "作成中..."
L.PROGRESS_STATUS         = "処理：<<1>> / <<2>>"

L.ERR_BAG_FULL            = "バッグの空きが足りません（約<<1>>スロット必要）。"
L.ERR_NO_STYLE            = "バッグまたはクラフトバッグに既知のスタイル素材がありません。"
L.ERR_MISSING_RUNES       = "付呪ルーンが不足しています（効力 / 本質 / Ta）。"
L.ERR_CANNOT_CRAFT        = "<<1>>を作成できません（素材・スタイル・スキル不足）。"
L.ERR_CRAFT_FAILED        = "作成失敗 (<<1>>/<<2>>)。スキップ。"
L.ERR_NOT_AT_STATION      = "クラフトステーションにいません。"
L.ERR_PROV_SKIP_UNKNOWN   = "スキップ（レシピ未習得）：<<1>>"
L.ERR_NOTHING_TO_CRAFT    = "作成するものがありません。"
L.ERR_NO_ACTIVE_WRIT      = "このステーションに対応する進行中のクラフト依頼がありません。"

L.PRECHECK_HEADER         = "|cFF6666[Tetsu's Daily Writ Precrafter]|r 素材不足。作成を中止しました："
L.PRECHECK_JOBS           = "キュー内のジョブ：|cFFFFFF<<1>>|r"
L.PRECHECK_LINE           = "  - |cFFD700<<1>>|r：必要 |cFFFFFF<<2>>|r、所持 |cFFFFFF<<3>>|r (|cFF6666-<<4>>|r)"
L.PRECHECK_ABORT          = "不足している素材を追加して、もう一度 R3 を押してください。"
L.PRECHECK_OK             = "素材チェック OK。|c00FF00<<1>>|r個を作成します..."

L.USING_QUEST_DATA        = "進行中の依頼データを使用。"
L.USING_PREDICTED         = "プレクラフトモード：<<1>>日分の日替わりローテーション。"
L.CRAFT_DONE              = "完了。作成：|c00FF00<<1>>|r、スキップ：|cFFFF00<<2>>|r。"
L.PATTERN_TODAY           = "今日のパターン：|cFFD700<<1>>|r"
L.ERR_PHASE_UNKNOWN     = "ローテーションの位相が不明です。このステーションで今日の依頼を一度受注してください。サイクルを学習するとプレクラフトが使えます。"
L.PHASE_LEARNED         = "このクラフトのローテーション位相：|cFFD700<<1>>|r"
L.CONFLICT_TITLE          = "アドオンの競合"
L.CONFLICT_BODY           = "<<1>> をオフにしてください。同じ依頼を作成し、Tetsu's Daily Writ Precrafter と衝突します。"
L.CONFLICT_CHAT           = "|cFF6666[Tetsu's Daily Writ Precrafter]|r |cFFD700<<1>>|r をオフにしてください。オンの間は自動製作を停止します。"
L.MISSING_LWC_TITLE       = "Lazy Writ Creator が見つかりません"
L.MISSING_LWC_BODY        = "Dolgubon's Lazy Writ Creator を入れるか、「Lazy Writ と併用」をオフにして単独モードにしてください。"
L.MISSING_LWC_CHAT        = "|cFF6666[Tetsu's Daily Writ Precrafter]|r Lazy Writ Creator が有効ではありません。導入するか併用をオフにしてください。"
L.QUIET_INFO_LABEL        = "通常のチャット通知を隠す"
L.QUIET_INFO_TT           = "開始・ローテ・材料OK・完了を隠します。不足やエラーは常に表示します。"
L.ERR_WAIT_LWC            = "待機：Lazy Writ Creator が今日の依頼を製作中です。ステーションを閉じた後に R3 を押してください。"
L.ERR_STATION_CLOSED      = "キャンセル：ステーションを離れました。開き直して R3。"
