

-- EmotePack_Global

-- Get addon
EmoteKEKW = EmoteKEKW or {}
local EmoteKEKW = EmoteKEKW
-- Build table
EmoteKEKW.media = EmoteKEKW.media or {}
EmoteKEKW.media["Multi"] = EmoteKEKW.media["Multi"] or {}
EmoteKEKW.media["Multi"]["EmotePack_Global"] = EmoteKEKW.media["Multi"]["EmotePack_Global"] or {}

-- Emote pack
local EmotePack = EmoteKEKW.media["Multi"]["EmotePack_Global"]

-- Add emotes
EmotePack["HSWP"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/HSWP.dds"},}
EmotePack["PokGengar"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PokGengar.dds"},}
EmotePack["NiceTry"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/NiceTry.dds"},}
EmotePack["PokShadowmew"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PokShadowmew.dds"},}
EmotePack["HolidayPresent"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/HolidayPresent.dds"},}
EmotePack["PokMachamp"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PokMachamp.dds"},}
EmotePack["ScaredyCat"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/ScaredyCat.dds"},}
EmotePack["PokCharizard"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PokCharizard.dds"},}
EmotePack["PJSugar"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PJSugar.dds"},}
EmotePack["CarlSmile"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/CarlSmile.dds"},}
EmotePack["StinkyCheese"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/StinkyCheese.dds"},}
EmotePack["PMSTwin"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PMSTwin.dds"},}
EmotePack["HotPokket"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/HotPokket.dds"},}
EmotePack["ThankEgg"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/ThankEgg.dds"},}
EmotePack["ModLove"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/ModLove.dds"},}
EmotePack["BabyRage"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/BabyRage.dds"},}
EmotePack["EarthDay"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/EarthDay.dds"},}
EmotePack["GayPride"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/GayPride.dds"},}
EmotePack["TwitchLit"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TwitchLit.dds"},}
EmotePack["FlipThis"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FlipThis.dds"},}
EmotePack["VoHiYo"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/VoHiYo.dds"},}
EmotePack["PoroSad"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PoroSad.dds"},}
EmotePack["BrainSlug"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/BrainSlug.dds"},}
EmotePack["PJSalt"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PJSalt.dds"},}
EmotePack["PokEmpoleon"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PokEmpoleon.dds"},}
EmotePack["ExtraLife"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/ExtraLife.dds"},}
EmotePack["prTestTest"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/prTestTest.dds"},}
EmotePack["DansGame"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/DansGame.dds"},}
EmotePack["RedCoat"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/RedCoat.dds"},}
EmotePack["PokMaskedpika"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PokMaskedpika.dds"},}
EmotePack["HeyGuys"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/HeyGuys.dds"},}
EmotePack["TheRinger"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TheRinger.dds"},}
EmotePack["TheIlluminati"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TheIlluminati.dds"},}
EmotePack["RlyTho"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/RlyTho.dds"},}
EmotePack["EleGiggle"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/EleGiggle.dds"},}
EmotePack["FBPenalty"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FBPenalty.dds"},}
EmotePack["ArsonNoSexy"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/ArsonNoSexy.dds"},}
EmotePack["DarkMode"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/DarkMode.dds"},}
EmotePack["FootBall"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FootBall.dds"},}
EmotePack["HungryPaimon"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/HungryPaimon.dds"},}
EmotePack["PokSceptile"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PokSceptile.dds"},}
EmotePack["TwitchLit"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TwitchLit.dds"},}
EmotePack["FootGoal"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FootGoal.dds"},}
EmotePack["PokAegislash"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PokAegislash.dds"},}
EmotePack["OptimizePrime"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/OptimizePrime.dds"},}
EmotePack["KevinTurtle"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KevinTurtle.dds"},}
EmotePack["ChefFrank"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/ChefFrank.dds"},}
EmotePack["FootYellow"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FootYellow.dds"},}
EmotePack["BagOfMemes"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/BagOfMemes.dds"},}
EmotePack["VoteYea"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/VoteYea.dds"},}
EmotePack["PRChase"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PRChase.dds"},}
EmotePack["OhMyDog"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/OhMyDog.dds"},}
EmotePack["TPcrunchyroll"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TPcrunchyroll.dds"},}
EmotePack["KAPOW"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KAPOW.dds"},}
EmotePack["GlitchNRG"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/GlitchNRG.dds"},}
EmotePack["StrawBeary"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/StrawBeary.dds"},}
EmotePack["Jebasted"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Jebasted.dds"},}
EmotePack["riPepperonis"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/riPepperonis.dds"},}
EmotePack["HolidayTree"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/HolidayTree.dds"},}
EmotePack["Keepo"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Keepo.dds"},}
EmotePack["PizzaTime"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PizzaTime.dds"},}
EmotePack["PanicVis"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PanicVis.dds"},}
EmotePack["NotATK"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/NotATK.dds"},}
EmotePack["VoteNay"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/VoteNay.dds"},}
EmotePack["PokBraixen"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PokBraixen.dds"},}
EmotePack["duDudu"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/duDudu.dds"},}
EmotePack["FamilyMan"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FamilyMan.dds"},}
EmotePack["BlargNaut"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/BlargNaut.dds"},}
EmotePack["pastaThat"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/pastaThat.dds"},}
EmotePack["RalpherZ"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/RalpherZ.dds"},}
EmotePack["VirtualHug"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/VirtualHug.dds"},}
EmotePack["TF2John"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TF2John.dds"},}
EmotePack["OneHand"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/OneHand.dds"},}
EmotePack["FreakinStinkin"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FreakinStinkin.dds"},}
EmotePack["O_o"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/O_o.dds"},}
EmotePack["FallCry"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FallCry.dds"},}
EmotePack["CaitlynS"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/CaitlynS.dds"},}
EmotePack["ImTyping"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/ImTyping.dds"},}
EmotePack["TinyFace"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TinyFace.dds"},}
EmotePack["ANELE"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/ANELE.dds"},}
EmotePack["FortLlama"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FortLlama.dds"},}
EmotePack["twitchRaid"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/twitchRaid.dds"},}
EmotePack["Squid4"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Squid4.dds"},}
EmotePack["CoolStoryBob"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/CoolStoryBob.dds"},}
EmotePack["MercyWing1"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/MercyWing1.dds"},}
EmotePack["FortBush"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FortBush.dds"},}
EmotePack["DarkKnight"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/DarkKnight.dds"},}
EmotePack["PeoplesChamp"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PeoplesChamp.dds"},}
EmotePack["Poooound"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Poooound.dds"},}
EmotePack["AsexualPride"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/AsexualPride.dds"},}
EmotePack["FBBlock"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FBBlock.dds"},}
EmotePack["FBChallenge"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FBChallenge.dds"},}
EmotePack["O_o"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/O_o.dds"},}
EmotePack["PinkMercy"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PinkMercy.dds"},}
EmotePack["FlipThis"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FlipThis.dds"},}
EmotePack["BuddhaBar"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/BuddhaBar.dds"},}
EmotePack["HolidayLog"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/HolidayLog.dds"},}
EmotePack["MyAvatar"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/MyAvatar.dds"},}
EmotePack["KappaHD"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KappaHD.dds"},}
EmotePack["SUBprise"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/SUBprise.dds"},}
EmotePack["Squid3"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Squid3.dds"},}
EmotePack["ShazBotstix"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/ShazBotstix.dds"},}
EmotePack["PokGardevoir"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PokGardevoir.dds"},}
EmotePack["PixelBob"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PixelBob.dds"},}
EmotePack["MindManners"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/MindManners.dds"},}
EmotePack["DoritosChip"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/DoritosChip.dds"},}
EmotePack["PokGarchomp"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PokGarchomp.dds"},}
EmotePack["MrDestructoid"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/MrDestructoid.dds"},}
EmotePack["PermaSmug"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PermaSmug.dds"},}
EmotePack["TwitchRPG"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TwitchRPG.dds"},}
EmotePack["copyThis"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/copyThis.dds"},}
EmotePack["PokScizor"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PokScizor.dds"},}
EmotePack["PokChandelure"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PokChandelure.dds"},}
EmotePack["PrimeRlyTho"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PrimeRlyTho.dds"},}
EmotePack["PokSuicune"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PokSuicune.dds"},}
EmotePack["KappaWealth"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KappaWealth.dds"},}
EmotePack["Squid1"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Squid1.dds"},}
EmotePack["MingLee"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/MingLee.dds"},}
EmotePack["KappaPride"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KappaPride.dds"},}
EmotePack["PokMewtwo"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PokMewtwo.dds"},}
EmotePack["TheThing"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TheThing.dds"},}
EmotePack["PowerUpR"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PowerUpR.dds"},}
EmotePack["TwitchVotes"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TwitchVotes.dds"},}
EmotePack["IntersexPride"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/IntersexPride.dds"},}
EmotePack["Kappu"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Kappu.dds"},}
EmotePack["ShadyLulu"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/ShadyLulu.dds"},}
EmotePack["PokCroagunk"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PokCroagunk.dds"},}
EmotePack["LionOfYara"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/LionOfYara.dds"},}
EmotePack["SeriousSloth"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/SeriousSloth.dds"},}
EmotePack["DxCat"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/DxCat.dds"},}
EmotePack["MorphinTime"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/MorphinTime.dds"},}
EmotePack["KappaRoss"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KappaRoss.dds"},}
EmotePack["KappaHD"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KappaHD.dds"},}
EmotePack["PartyTime"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PartyTime.dds"},}
EmotePack["BCWarrior"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/BCWarrior.dds"},}
EmotePack["DAESuppy"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/DAESuppy.dds"},}
EmotePack["SMOrc"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/SMOrc.dds"},}
EmotePack["FBtouchdown"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FBtouchdown.dds"},}
EmotePack["GivePLZ"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/GivePLZ.dds"},}
EmotePack["TehePelo"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TehePelo.dds"},}
EmotePack["TheTarFu"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TheTarFu.dds"},}
EmotePack["SingsMic"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/SingsMic.dds"},}
EmotePack["TwitchUnity"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TwitchUnity.dds"},}
EmotePack["DatSheffy"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/DatSheffy.dds"},}
EmotePack["FallHalp"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FallHalp.dds"},}
EmotePack["HassaanChop"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/HassaanChop.dds"},}
EmotePack["TransgenderPride"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TransgenderPride.dds"},}
EmotePack["FailFish"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FailFish.dds"},}
EmotePack["cmonBruh"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/cmonBruh.dds"},}
EmotePack["mcaT"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/mcaT.dds"},}
EmotePack["TakeNRG"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TakeNRG.dds"},}
EmotePack["FBSpiral"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FBSpiral.dds"},}
EmotePack["CorgiDerp"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/CorgiDerp.dds"},}
EmotePack["RaccAttack"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/RaccAttack.dds"},}
EmotePack["GlitchLit"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/GlitchLit.dds"},}
EmotePack["GenderFluidPride"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/GenderFluidPride.dds"},}
EmotePack["PokDarkrai"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PokDarkrai.dds"},}
EmotePack["Kappa"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Kappa.dds"},}
EmotePack["PansexualPride"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PansexualPride.dds"},}
EmotePack["FBPass"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FBPass.dds"},}
EmotePack["PartyPopper"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PartyPopper.dds"},}
EmotePack["PunOko"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PunOko.dds"},}
EmotePack["MiniK"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/MiniK.dds"},}
EmotePack["RuleFive"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/RuleFive.dds"},}
EmotePack["ItsBoshyTime"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/ItsBoshyTime.dds"},}
EmotePack["TableHere"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TableHere.dds"},}
EmotePack["OpieOP"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/OpieOP.dds"},}
EmotePack["PokBlaziken"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PokBlaziken.dds"},}
EmotePack["KappaHD"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KappaHD.dds"},}
EmotePack["YouWHY"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/YouWHY.dds"},}
EmotePack["PokWeavile"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PokWeavile.dds"},}
EmotePack["BigPhish"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/BigPhish.dds"},}
EmotePack["SingsNote"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/SingsNote.dds"},}
EmotePack["FallWinning"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FallWinning.dds"},}
EmotePack["MercyWing2"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/MercyWing2.dds"},}
EmotePack["FUNgineer"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FUNgineer.dds"},}
EmotePack["OSFrog"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/OSFrog.dds"},}
EmotePack["PokDecidueye"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PokDecidueye.dds"},}
EmotePack["GrammarKing"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/GrammarKing.dds"},}
EmotePack["SabaPing"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/SabaPing.dds"},}
EmotePack["UnSane"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/UnSane.dds"},}
EmotePack["PokLucario"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PokLucario.dds"},}
EmotePack["StinkyGlitch"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/StinkyGlitch.dds"},}
EmotePack["BOP"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/BOP.dds"},}
EmotePack["Getcamped"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Getcamped.dds"},}
EmotePack["FutureMan"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FutureMan.dds"},}
EmotePack["GingerPower"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/GingerPower.dds"},}
EmotePack["Kreygasm"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Kreygasm.dds"},}
EmotePack["MaxLOL"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/MaxLOL.dds"},}
EmotePack["SoBayed"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/SoBayed.dds"},}
EmotePack["FBCatch"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FBCatch.dds"},}
EmotePack["LaundryBasket"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/LaundryBasket.dds"},}
EmotePack["BagOfMemes"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/BagOfMemes.dds"},}
EmotePack["BigBrother"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/BigBrother.dds"},}
EmotePack["bleedPurple"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/bleedPurple.dds"},}
EmotePack["WutFace"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/WutFace.dds"},}
EmotePack["TwitchSings"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TwitchSings.dds"},}
EmotePack["PartyPopper"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PartyPopper.dds"},}
EmotePack["NomNom"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/NomNom.dds"},}
EmotePack["FrankerZ"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FrankerZ.dds"},}
EmotePack["SwiftRage"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/SwiftRage.dds"},}
EmotePack["FortOne"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FortOne.dds"},}
EmotePack["FortHype"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FortHype.dds"},}
EmotePack["FlipThis"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FlipThis.dds"},}
EmotePack["WTRuck"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/WTRuck.dds"},}
EmotePack["SuperVinlin"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/SuperVinlin.dds"},}
EmotePack["YouDontSay"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/YouDontSay.dds"},}
EmotePack["DendiFace"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/DendiFace.dds"},}
EmotePack["Shush"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Shush.dds"},}
EmotePack["RitzMitz"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/RitzMitz.dds"},}
EmotePack["PokPikachu"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PokPikachu.dds"},}
EmotePack["MVGame"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/MVGame.dds"},}
EmotePack["CurseLit"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/CurseLit.dds"},}
EmotePack["DogFace"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/DogFace.dds"},}
EmotePack["KomodoHype"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KomodoHype.dds"},}
EmotePack["Kippa"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Kippa.dds"},}
EmotePack["EntropyWins"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/EntropyWins.dds"},}
EmotePack["SSSsss"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/SSSsss.dds"},}
EmotePack["BrokeBack"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/BrokeBack.dds"},}
EmotePack["PotFriend"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PotFriend.dds"},}
EmotePack["PogChamp"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PogChamp.dds"},}
EmotePack["SeemsGood"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/SeemsGood.dds"},}
EmotePack["TBAngel"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TBAngel.dds"},}
EmotePack["KappaClaus"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KappaClaus.dds"},}
EmotePack["JonCarnage"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/JonCarnage.dds"},}
EmotePack["UncleNox"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/UncleNox.dds"},}
EmotePack["TableHere"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TableHere.dds"},}
EmotePack["ResidentSleeper"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/ResidentSleeper.dds"},}
EmotePack["CoolCat"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/CoolCat.dds"},}
EmotePack["PowerUpL"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PowerUpL.dds"},}
EmotePack["PopCorn"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PopCorn.dds"},}
EmotePack["PrimeMe"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PrimeMe.dds"},}
EmotePack["MiniK"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/MiniK.dds"},}
EmotePack["TriHard"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TriHard.dds"},}
EmotePack["SmoocherZ"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/SmoocherZ.dds"},}
EmotePack["MikeHogu"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/MikeHogu.dds"},}
EmotePack["InuyoFace"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/InuyoFace.dds"},}
EmotePack["Squid2"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Squid2.dds"},}
EmotePack["NonbinaryPride"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/NonbinaryPride.dds"},}
EmotePack["BegWan"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/BegWan.dds"},}
EmotePack["MiniK"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/MiniK.dds"},}
EmotePack["BatChest"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/BatChest.dds"},}
EmotePack["HarleyWink"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/HarleyWink.dds"},}
EmotePack["NinjaGrumpy"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/NinjaGrumpy.dds"},}
EmotePack["CrreamAwk"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/CrreamAwk.dds"},}
EmotePack["TooSpicy"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TooSpicy.dds"},}
EmotePack["panicBasket"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/panicBasket.dds"},}
EmotePack["O_o"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/O_o.dds"},}
EmotePack["HolidayCookie"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/HolidayCookie.dds"},}
EmotePack["FBRun"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FBRun.dds"},}
EmotePack["Lechonk"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Lechonk.dds"},}
EmotePack["BloodTrail"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/BloodTrail.dds"},}
EmotePack["WhySoSerious"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/WhySoSerious.dds"},}
EmotePack["GunRun"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/GunRun.dds"},}
EmotePack["TTours"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TTours.dds"},}
EmotePack["BlackLivesMatter"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/BlackLivesMatter.dds"},}
EmotePack["MechaRobot"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/MechaRobot.dds"},}
EmotePack["TearGlove"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TearGlove.dds"},}
EmotePack["AsianGlow"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/AsianGlow.dds"},}
EmotePack["Jebaited"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Jebaited.dds"},}
EmotePack["PartyHat"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PartyHat.dds"},}
EmotePack["BibleThump"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/BibleThump.dds"},}
EmotePack["PrimeUWot"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PrimeUWot.dds"},}
EmotePack["Kappa"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Kappa.dds"},}
EmotePack["SoonerLater"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/SoonerLater.dds"},}
EmotePack["HSCheers"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/HSCheers.dds"},}
EmotePack["Mau5"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Mau5.dds"},}
EmotePack["ScaredyCat"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/ScaredyCat.dds"},}
EmotePack["PokBlastoise"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PokBlastoise.dds"},}
EmotePack["StoneLightning"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/StoneLightning.dds"},}
EmotePack["NewRecord"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/NewRecord.dds"},}
EmotePack["TombRaid"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TombRaid.dds"},}
EmotePack["PunchTrees"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PunchTrees.dds"},}
EmotePack["HolidaySanta"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/HolidaySanta.dds"},}
EmotePack["PrimeYouDontSay"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PrimeYouDontSay.dds"},}
EmotePack["ThunBeast"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/ThunBeast.dds"},}
EmotePack["ScaredyCat"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/ScaredyCat.dds"},}
EmotePack["JKanStyle"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/JKanStyle.dds"},}
EmotePack["ArgieB8"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/ArgieB8.dds"},}
EmotePack["BisexualPride"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/BisexualPride.dds"},}
EmotePack["PogBones"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PogBones.dds"},}
EmotePack["KonCha"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KonCha.dds"},}
EmotePack["NotLikeThis"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/NotLikeThis.dds"},}
EmotePack["4Head"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/4Head.dds"},}
EmotePack["TPFufun"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TPFufun.dds"},}
EmotePack["LesbianPride"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/LesbianPride.dds"},}
EmotePack["GlitchCat"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/GlitchCat.dds"},}
EmotePack["PraiseIt"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PraiseIt.dds"},}
EmotePack["imGlitch"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/imGlitch.dds"},}
EmotePack["TableHere"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TableHere.dds"},}
EmotePack["DBstyle"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/DBstyle.dds"},}
EmotePack["PicoMause"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PicoMause.dds"},}
EmotePack["WholeWheat"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/WholeWheat.dds"},}
EmotePack["UWot"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/UWot.dds"},}
EmotePack["MindManners"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/MindManners.dds"},}
EmotePack["PipeHype"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PipeHype.dds"},}
EmotePack["LUL"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/LUL.dds"},}
EmotePack["KEKHeim"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KEKHeim.dds"},}
EmotePack["RyuChamp"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/RyuChamp.dds"},}
EmotePack["OMEGALUL"] = {type = "emote", scale = 0.96875, paths = {"EmoteKEKW/EmotePack_Global/OMEGALUL.dds"},}
EmotePack["Pog"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Pog.dds"},}
EmotePack["PepeHands"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PepeHands.dds"},}
EmotePack["widepeepoHappy"] = {type = "emote", scale = 4.2105263157894735, paths = {"EmoteKEKW/EmotePack_Global/widepeepoHappy.dds"},}
EmotePack["LULW"] = {type = "emote", scale = 0.875, paths = {"EmoteKEKW/EmotePack_Global/LULW.dds"},}
EmotePack["Pepega"] = {type = "emote", scale = 1.28, paths = {"EmoteKEKW/EmotePack_Global/Pepega.dds"},}
EmotePack["monkaW"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/monkaW.dds"},}
EmotePack["5Head"] = {type = "emote", scale = 0.8125, paths = {"EmoteKEKW/EmotePack_Global/5Head.dds"},}
EmotePack["POGGERS"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/POGGERS.dds"},}
EmotePack["monkaS"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/monkaS.dds"},}
EmotePack["AYAYA"] = {type = "emote", scale = 1.032258064516129, paths = {"EmoteKEKW/EmotePack_Global/AYAYA.dds"},}
EmotePack["PepeLaugh"] = {type = "emote", scale = 1.0344827586206897, paths = {"EmoteKEKW/EmotePack_Global/PepeLaugh.dds"},}
EmotePack["widepeepoSad"] = {type = "emote", scale = 4.0, paths = {"EmoteKEKW/EmotePack_Global/widepeepoSad.dds"},}
EmotePack["Sadge"] = {type = "emote", scale = 1.2727272727272727, paths = {"EmoteKEKW/EmotePack_Global/Sadge.dds"},}
EmotePack["FeelsBadMan"] = {type = "emote", scale = 1.0344827586206897, paths = {"EmoteKEKW/EmotePack_Global/FeelsBadMan.dds"},}
EmotePack["HYPERS"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/HYPERS.dds"},}
EmotePack["YEP"] = {type = "emote", scale = 1.032258064516129, paths = {"EmoteKEKW/EmotePack_Global/YEP.dds"},}
EmotePack["FeelsOkayMan"] = {type = "emote", scale = 1.037037037037037, paths = {"EmoteKEKW/EmotePack_Global/FeelsOkayMan.dds"},}
EmotePack["Kapp"] = {type = "emote", scale = 0.38095238095238093, paths = {"EmoteKEKW/EmotePack_Global/Kapp.dds"},}
EmotePack["EZY"] = {type = "emote", scale = 1.0769230769230769, paths = {"EmoteKEKW/EmotePack_Global/EZY.dds"},}
EmotePack["HandsUp"] = {type = "emote", scale = 1.9, paths = {"EmoteKEKW/EmotePack_Global/HandsUp.dds"},}
EmotePack["PepoThink"] = {type = "emote", scale = 1.032258064516129, paths = {"EmoteKEKW/EmotePack_Global/PepoThink.dds"},}
EmotePack["3Head"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/3Head.dds"},}
EmotePack["gachiGASM"] = {type = "emote", scale = 0.8571428571428571, paths = {"EmoteKEKW/EmotePack_Global/gachiGASM.dds"},}
EmotePack["FeelsWeirdMan"] = {type = "emote", scale = 1.037037037037037, paths = {"EmoteKEKW/EmotePack_Global/FeelsWeirdMan.dds"},}
EmotePack["monkaHmm"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/monkaHmm.dds"},}
EmotePack["forsenCD"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/forsenCD.dds"},}
EmotePack["KKomrade"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KKomrade.dds"},}
EmotePack["PepoG"] = {type = "emote", scale = 1.2307692307692308, paths = {"EmoteKEKW/EmotePack_Global/PepoG.dds"},}
EmotePack["monkaOMEGA"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/monkaOMEGA.dds"},}
EmotePack["monkaGun"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/monkaGun.dds"},}
EmotePack["peepoBlanket"] = {type = "emote", scale = 0.96875, paths = {"EmoteKEKW/EmotePack_Global/peepoBlanket.dds"},}
EmotePack["FeelsStrongMan"] = {type = "emote", scale = 1.032258064516129, paths = {"EmoteKEKW/EmotePack_Global/FeelsStrongMan.dds"},}
EmotePack["monkaEyes"] = {type = "emote", scale = 3.75, paths = {"EmoteKEKW/EmotePack_Global/monkaEyes.dds"},}
EmotePack["HYPERBRUH"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/HYPERBRUH.dds"},}
EmotePack["peepoHappy"] = {type = "emote", scale = 1.4, paths = {"EmoteKEKW/EmotePack_Global/peepoHappy.dds"},}
EmotePack["monkaTOS"] = {type = "emote", scale = 0.9642857142857143, paths = {"EmoteKEKW/EmotePack_Global/monkaTOS.dds"},}
EmotePack["peepoLove"] = {type = "emote", scale = 1.2727272727272727, paths = {"EmoteKEKW/EmotePack_Global/peepoLove.dds"},}
EmotePack["weSmart"] = {type = "emote", scale = 0.9642857142857143, paths = {"EmoteKEKW/EmotePack_Global/weSmart.dds"},}
EmotePack["FeelsGoodMan"] = {type = "emote", scale = 1.3333333333333333, paths = {"EmoteKEKW/EmotePack_Global/FeelsGoodMan.dds"},}
EmotePack["KKonaW"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KKonaW.dds"},}
EmotePack["FeelsDankMan"] = {type = "emote", scale = 0.875, paths = {"EmoteKEKW/EmotePack_Global/FeelsDankMan.dds"},}
EmotePack["REEeee"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/REEeee.dds"},}
EmotePack["monkaH"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/monkaH.dds"},}
EmotePack["4HEad"] = {type = "emote", scale = 1.4545454545454546, paths = {"EmoteKEKW/EmotePack_Global/4HEad.dds"},}
EmotePack["FeelsSpecialMan"] = {type = "emote", scale = 1.12, paths = {"EmoteKEKW/EmotePack_Global/FeelsSpecialMan.dds"},}
EmotePack["KEKWait"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KEKWait.dds"},}
EmotePack["PepeLaugh"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PepeLaugh.dds"},}
EmotePack["WideHardo"] = {type = "emote", scale = 3.95, paths = {"EmoteKEKW/EmotePack_Global/WideHardo.dds"},}
EmotePack["monkaMEGA"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/monkaMEGA.dds"},}
EmotePack["peepoSad"] = {type = "emote", scale = 1.4736842105263157, paths = {"EmoteKEKW/EmotePack_Global/peepoSad.dds"},}
EmotePack["Prayge"] = {type = "emote", scale = 1.4, paths = {"EmoteKEKW/EmotePack_Global/Prayge.dds"},}
EmotePack["YouDied"] = {type = "emote", scale = 4.444444444444445, paths = {"EmoteKEKW/EmotePack_Global/YouDied.dds"},}
EmotePack["pikachuS"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/pikachuS.dds"},}
EmotePack["peepoClown"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/peepoClown.dds"},}
EmotePack["COPIUM"] = {type = "emote", scale = 1.032258064516129, paths = {"EmoteKEKW/EmotePack_Global/COPIUM.dds"},}
EmotePack["WICKED"] = {type = "emote", scale = 1.4545454545454546, paths = {"EmoteKEKW/EmotePack_Global/WICKED.dds"},}
EmotePack["WideHard"] = {type = "emote", scale = 2.5, paths = {"EmoteKEKW/EmotePack_Global/WideHard.dds"},}
EmotePack["Madge"] = {type = "emote", scale = 1.2727272727272727, paths = {"EmoteKEKW/EmotePack_Global/Madge.dds"},}
EmotePack["PepegaPhone"] = {type = "emote", scale = 3.9, paths = {"EmoteKEKW/EmotePack_Global/PepegaPhone.dds"},}
EmotePack["peepoWTF"] = {type = "emote", scale = 1.4736842105263157, paths = {"EmoteKEKW/EmotePack_Global/peepoWTF.dds"},}
EmotePack["WeirdChamp"] = {type = "emote", scale = 0.96875, paths = {"EmoteKEKW/EmotePack_Global/WeirdChamp.dds"},}
EmotePack["POGGIES"] = {type = "emote", scale = 1.037037037037037, paths = {"EmoteKEKW/EmotePack_Global/POGGIES.dds"},}
EmotePack["DICKS"] = {type = "emote", scale = 5.0, paths = {"EmoteKEKW/EmotePack_Global/DICKS.dds"},}
EmotePack["peepoFat"] = {type = "emote", scale = 1.0666666666666667, paths = {"EmoteKEKW/EmotePack_Global/peepoFat.dds"},}
EmotePack["MEGALUL"] = {type = "emote", scale = 1.0666666666666667, paths = {"EmoteKEKW/EmotePack_Global/MEGALUL.dds"},}
EmotePack["PressF"] = {type = "emote", scale = 1.0666666666666667, paths = {"EmoteKEKW/EmotePack_Global/PressF.dds"},}
EmotePack["Pepepains"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Pepepains.dds"},}
EmotePack["PauseChamp"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PauseChamp.dds"},}
EmotePack["Okayge"] = {type = "emote", scale = 1.2727272727272727, paths = {"EmoteKEKW/EmotePack_Global/Okayge.dds"},}
EmotePack["widepeepoHappy"] = {type = "emote", scale = 4.2105263157894735, paths = {"EmoteKEKW/EmotePack_Global/widepeepoHappy.dds"},}
EmotePack["4Weird"] = {type = "emote", scale = 0.6875, paths = {"EmoteKEKW/EmotePack_Global/4Weird.dds"},}
EmotePack["HeavyBreathing"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/HeavyBreathing.dds"},}
EmotePack["Thonk"] = {type = "emote", scale = 1.1851851851851851, paths = {"EmoteKEKW/EmotePack_Global/Thonk.dds"},}
EmotePack["TRIGGERED"] = {type = "emote", scale = 4.2105263157894735, paths = {"EmoteKEKW/EmotePack_Global/TRIGGERED.dds"},}
EmotePack["widepeepoBlanket"] = {type = "emote", scale = 4.0, paths = {"EmoteKEKW/EmotePack_Global/widepeepoBlanket.dds"},}
EmotePack["Klappa"] = {type = "emote", scale = 1.103448275862069, paths = {"EmoteKEKW/EmotePack_Global/Klappa.dds"},}
EmotePack["WaitWhat"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/WaitWhat.dds"},}
EmotePack["PeepoGlad"] = {type = "emote", scale = 1.4545454545454546, paths = {"EmoteKEKW/EmotePack_Global/PeepoGlad.dds"},}
EmotePack["Pogey"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Pogey.dds"},}
EmotePack["monkaHmm"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/monkaHmm.dds"},}
EmotePack["4House"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/4House.dds"},}
EmotePack["SmileW"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/SmileW.dds"},}
EmotePack["monkaChrist"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/monkaChrist.dds"},}
EmotePack["pepeJAM"] = {type = "emote", scale = 1.037037037037037, paths = {"EmoteKEKW/EmotePack_Global/pepeJAM.dds"},}
EmotePack["GG!"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/GG!.dds"},}
EmotePack["peepoPoo"] = {type = "emote", scale = 0.96875, paths = {"EmoteKEKW/EmotePack_Global/peepoPoo.dds"},}
EmotePack["POGGERS"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/POGGERS.dds"},}
EmotePack["Stonks"] = {type = "emote", scale = 0.96875, paths = {"EmoteKEKW/EmotePack_Global/Stonks.dds"},}
EmotePack["PagMan"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PagMan.dds"},}
EmotePack["Hmm"] = {type = "emote", scale = 1.0666666666666667, paths = {"EmoteKEKW/EmotePack_Global/Hmm.dds"},}
EmotePack["Hahaa"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Hahaa.dds"},}
EmotePack["gachiHYPER"] = {type = "emote", scale = 0.8571428571428571, paths = {"EmoteKEKW/EmotePack_Global/gachiHYPER.dds"},}
EmotePack["SadCatW"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/SadCatW.dds"},}
EmotePack["HYPERDANSGAME"] = {type = "emote", scale = 0.8125, paths = {"EmoteKEKW/EmotePack_Global/HYPERDANSGAME.dds"},}
EmotePack["sadKEK"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/sadKEK.dds"},}
EmotePack["ThisIsFine"] = {type = "emote", scale = 0.9032258064516129, paths = {"EmoteKEKW/EmotePack_Global/ThisIsFine.dds"},}
EmotePack["2Head"] = {type = "emote", scale = 1.1923076923076923, paths = {"EmoteKEKW/EmotePack_Global/2Head.dds"},}
EmotePack["monkaGIGA"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/monkaGIGA.dds"},}
EmotePack["SuchMeme"] = {type = "emote", scale = 0.875, paths = {"EmoteKEKW/EmotePack_Global/SuchMeme.dds"},}
EmotePack["4Shrug"] = {type = "emote", scale = 0.9642857142857143, paths = {"EmoteKEKW/EmotePack_Global/4Shrug.dds"},}
EmotePack["pepePoint"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/pepePoint.dds"},}
EmotePack["MaN"] = {type = "emote", scale = 0.8125, paths = {"EmoteKEKW/EmotePack_Global/MaN.dds"},}
EmotePack["EHEHE"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/EHEHE.dds"},}
EmotePack["peepoHug"] = {type = "emote", scale = 1.3333333333333333, paths = {"EmoteKEKW/EmotePack_Global/peepoHug.dds"},}
EmotePack["Clap"] = {type = "emote", scale = 0.7619047619047619, paths = {"EmoteKEKW/EmotePack_Global/Clap.dds"},}
EmotePack["PepeLmao"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PepeLmao.dds"},}
EmotePack["stopS"] = {type = "emote", scale = 4.0, paths = {"EmoteKEKW/EmotePack_Global/stopS.dds"},}
EmotePack["POOGERS"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/POOGERS.dds"},}
EmotePack["Bedge"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Bedge.dds"},}
EmotePack["KKona"] = {type = "emote", scale = 0.6875, paths = {"EmoteKEKW/EmotePack_Global/KKona.dds"},}
EmotePack["StrimPlz"] = {type = "emote", scale = 1.1481481481481481, paths = {"EmoteKEKW/EmotePack_Global/StrimPlz.dds"},}
EmotePack["monkaSpeed"] = {type = "emote", scale = 1.0666666666666667, paths = {"EmoteKEKW/EmotePack_Global/monkaSpeed.dds"},}
EmotePack["FacePalm"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FacePalm.dds"},}
EmotePack["CatWhat"] = {type = "emote", scale = 1.28, paths = {"EmoteKEKW/EmotePack_Global/CatWhat.dds"},}
EmotePack["okiRIP"] = {type = "emote", scale = 2.3, paths = {"EmoteKEKW/EmotePack_Global/okiRIP.dds"},}
EmotePack["Sadge"] = {type = "emote", scale = 1.3333333333333333, paths = {"EmoteKEKW/EmotePack_Global/Sadge.dds"},}
EmotePack["KEKL"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KEKL.dds"},}
EmotePack["pepeGun"] = {type = "emote", scale = 1.12, paths = {"EmoteKEKW/EmotePack_Global/pepeGun.dds"},}
EmotePack["Susge"] = {type = "emote", scale = 1.2727272727272727, paths = {"EmoteKEKW/EmotePack_Global/Susge.dds"},}
EmotePack["widepeepoHug"] = {type = "emote", scale = 4.0, paths = {"EmoteKEKW/EmotePack_Global/widepeepoHug.dds"},}
EmotePack["JUSTDOIT"] = {type = "emote", scale = 0.96875, paths = {"EmoteKEKW/EmotePack_Global/JUSTDOIT.dds"},}
EmotePack["gachiBASS"] = {type = "emote", scale = 0.875, paths = {"EmoteKEKW/EmotePack_Global/gachiBASS.dds"},}
EmotePack["SadCat"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/SadCat.dds"},}
EmotePack["eShrug"] = {type = "emote", scale = 2.75, paths = {"EmoteKEKW/EmotePack_Global/eShrug.dds"},}
EmotePack["Bruh"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Bruh.dds"},}
EmotePack["OkayChamp"] = {type = "emote", scale = 0.9375, paths = {"EmoteKEKW/EmotePack_Global/OkayChamp.dds"},}
EmotePack["pepeLaugh"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/pepeLaugh.dds"},}
EmotePack["FeelsBirthdayMan"] = {type = "emote", scale = 0.6875, paths = {"EmoteKEKW/EmotePack_Global/FeelsBirthdayMan.dds"},}
EmotePack["KannaNom"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KannaNom.dds"},}
EmotePack["RAGEY"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/RAGEY.dds"},}
EmotePack["peepoShy"] = {type = "emote", scale = 1.4736842105263157, paths = {"EmoteKEKW/EmotePack_Global/peepoShy.dds"},}
EmotePack["4WeirdW"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/4WeirdW.dds"},}
EmotePack["PLEASENO"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PLEASENO.dds"},}
EmotePack["WTFF"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/WTFF.dds"},}
EmotePack["PepeClown"] = {type = "emote", scale = 1.0666666666666667, paths = {"EmoteKEKW/EmotePack_Global/PepeClown.dds"},}
EmotePack["FeelsWeirdManW"] = {type = "emote", scale = 1.1428571428571428, paths = {"EmoteKEKW/EmotePack_Global/FeelsWeirdManW.dds"},}
EmotePack["PillowNo"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PillowNo.dds"},}
EmotePack["PillowYes"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PillowYes.dds"},}
EmotePack["peepoFinger"] = {type = "emote", scale = 2.0, paths = {"EmoteKEKW/EmotePack_Global/peepoFinger.dds"},}
EmotePack["Tuturu"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Tuturu.dds"},}
EmotePack["MikuStare"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/MikuStare.dds"},}
EmotePack["VWasted"] = {type = "emote", scale = 3.888888888888889, paths = {"EmoteKEKW/EmotePack_Global/VWasted.dds"},}
EmotePack["FeelsWowMan"] = {type = "emote", scale = 1.0384615384615385, paths = {"EmoteKEKW/EmotePack_Global/FeelsWowMan.dds"},}
EmotePack["OhISee"] = {type = "emote", scale = 1.032258064516129, paths = {"EmoteKEKW/EmotePack_Global/OhISee.dds"},}
EmotePack["HYPERS"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/HYPERS.dds"},}
EmotePack["FeelsAmazingMan"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FeelsAmazingMan.dds"},}
EmotePack["Kapp"] = {type = "emote", scale = 0.40625, paths = {"EmoteKEKW/EmotePack_Global/Kapp.dds"},}
EmotePack["TooLewd"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TooLewd.dds"},}
EmotePack["dankHug"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/dankHug.dds"},}
EmotePack["peepoBlush"] = {type = "emote", scale = 1.4736842105263157, paths = {"EmoteKEKW/EmotePack_Global/peepoBlush.dds"},}
EmotePack["Pog"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Pog.dds"},}
EmotePack["peepoPat"] = {type = "emote", scale = 1.037037037037037, paths = {"EmoteKEKW/EmotePack_Global/peepoPat.dds"},}
EmotePack["Pepega"] = {type = "emote", scale = 1.28, paths = {"EmoteKEKW/EmotePack_Global/Pepega.dds"},}
EmotePack["PepeHands"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PepeHands.dds"},}
EmotePack["FeelsStrongMan"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FeelsStrongMan.dds"},}
EmotePack["monkaT"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/monkaT.dds"},}
EmotePack["coronaS"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/coronaS.dds"},}
EmotePack["HUH"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/HUH.dds"},}
EmotePack["NOP"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/NOP.dds"},}
EmotePack["Dolan"] = {type = "emote", scale = 1.09375, paths = {"EmoteKEKW/EmotePack_Global/Dolan.dds"},}
EmotePack["PogO"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PogO.dds"},}
EmotePack["ConcernFroge"] = {type = "emote", scale = 1.1428571428571428, paths = {"EmoteKEKW/EmotePack_Global/ConcernFroge.dds"},}
EmotePack["OMEGALUL"] = {type = "emote", scale = 0.96875, paths = {"EmoteKEKW/EmotePack_Global/OMEGALUL.dds"},}
EmotePack["Pepege"] = {type = "emote", scale = 1.2727272727272727, paths = {"EmoteKEKW/EmotePack_Global/Pepege.dds"},}
EmotePack["BootyTime"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/BootyTime.dds"},}
EmotePack["PeepoWeird"] = {type = "emote", scale = 1.4, paths = {"EmoteKEKW/EmotePack_Global/PeepoWeird.dds"},}
EmotePack["4HEader"] = {type = "emote", scale = 2.8, paths = {"EmoteKEKW/EmotePack_Global/4HEader.dds"},}
EmotePack["monkaStop"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/monkaStop.dds"},}
EmotePack["nepSmug"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/nepSmug.dds"},}
EmotePack["PepeREE"] = {type = "emote", scale = 1.032258064516129, paths = {"EmoteKEKW/EmotePack_Global/PepeREE.dds"},}
EmotePack["WutFaceW"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/WutFaceW.dds"},}
EmotePack["Wokege"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Wokege.dds"},}
EmotePack["RIP"] = {type = "emote", scale = 0.96875, paths = {"EmoteKEKW/EmotePack_Global/RIP.dds"},}
EmotePack["peepoShrug"] = {type = "emote", scale = 1.4, paths = {"EmoteKEKW/EmotePack_Global/peepoShrug.dds"},}
EmotePack["ToroSalt"] = {type = "emote", scale = 3.75, paths = {"EmoteKEKW/EmotePack_Global/ToroSalt.dds"},}
EmotePack["PantsGrab"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PantsGrab.dds"},}
EmotePack["widepeepoHigh"] = {type = "emote", scale = 4.0, paths = {"EmoteKEKW/EmotePack_Global/widepeepoHigh.dds"},}
EmotePack["WideHarder"] = {type = "emote", scale = 4.0, paths = {"EmoteKEKW/EmotePack_Global/WideHarder.dds"},}
EmotePack["RNGplz"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/RNGplz.dds"},}
EmotePack["PauseChamp"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PauseChamp.dds"},}
EmotePack["4Heed"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/4Heed.dds"},}
EmotePack["GoodMemes"] = {type = "emote", scale = 3.3, paths = {"EmoteKEKW/EmotePack_Global/GoodMemes.dds"},}
EmotePack["ricardoFlick"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/ricardoFlick.dds"},}
EmotePack["SHEESH"] = {type = "emote", scale = 4.0, paths = {"EmoteKEKW/EmotePack_Global/SHEESH.dds"},}
EmotePack["VaN"] = {type = "emote", scale = 0.9, paths = {"EmoteKEKW/EmotePack_Global/VaN.dds"},}
EmotePack["KannaPolice"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KannaPolice.dds"},}
EmotePack["CosmicBrain"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/CosmicBrain.dds"},}
EmotePack["PepeSuspicious"] = {type = "emote", scale = 1.1428571428571428, paths = {"EmoteKEKW/EmotePack_Global/PepeSuspicious.dds"},}
EmotePack["YuuBooty"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/YuuBooty.dds"},}
EmotePack["Catgasm"] = {type = "emote", scale = 1.1071428571428572, paths = {"EmoteKEKW/EmotePack_Global/Catgasm.dds"},}
EmotePack["Okayeg"] = {type = "emote", scale = 1.0769230769230769, paths = {"EmoteKEKW/EmotePack_Global/Okayeg.dds"},}
EmotePack["AYAYAHyper"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/AYAYAHyper.dds"},}
EmotePack["pepoHmm"] = {type = "emote", scale = 1.2727272727272727, paths = {"EmoteKEKW/EmotePack_Global/pepoHmm.dds"},}
EmotePack["BOOMER"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/BOOMER.dds"},}
EmotePack["peepoKnife"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/peepoKnife.dds"},}
EmotePack["peepoPooPoo"] = {type = "emote", scale = 0.9642857142857143, paths = {"EmoteKEKW/EmotePack_Global/peepoPooPoo.dds"},}
EmotePack["monkaGun"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/monkaGun.dds"},}
EmotePack["monkaH"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/monkaH.dds"},}
EmotePack["dogeKek"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/dogeKek.dds"},}
EmotePack["5Head"] = {type = "emote", scale = 0.8125, paths = {"EmoteKEKW/EmotePack_Global/5Head.dds"},}
EmotePack["AYAYAWeird"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/AYAYAWeird.dds"},}
EmotePack["monkaW"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/monkaW.dds"},}
EmotePack["catOK"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/catOK.dds"},}
EmotePack["Clueless"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Clueless.dds"},}
EmotePack["SmugPepe"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/SmugPepe.dds"},}
EmotePack["NiceHost"] = {type = "emote", scale = 3.6, paths = {"EmoteKEKW/EmotePack_Global/NiceHost.dds"},}
EmotePack["TrollDespair"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TrollDespair.dds"},}
EmotePack["FeelsSexMan"] = {type = "emote", scale = 3.9, paths = {"EmoteKEKW/EmotePack_Global/FeelsSexMan.dds"},}
EmotePack["PepeLa"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PepeLa.dds"},}
EmotePack["FeelsDonkMan"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FeelsDonkMan.dds"},}
EmotePack["AmaRekt"] = {type = "emote", scale = 5.0, paths = {"EmoteKEKW/EmotePack_Global/AmaRekt.dds"},}
EmotePack["KermitENOUGH"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KermitENOUGH.dds"},}
EmotePack["AYAYA"] = {type = "emote", scale = 4.0, paths = {"EmoteKEKW/EmotePack_Global/AYAYA.dds"},}
EmotePack["forsenScoots"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/forsenScoots.dds"},}
EmotePack["BASED"] = {type = "emote", scale = 1.032258064516129, paths = {"EmoteKEKW/EmotePack_Global/BASED.dds"},}
EmotePack["FeelsOkayMan"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FeelsOkayMan.dds"},}
EmotePack["peepoRiot"] = {type = "emote", scale = 1.4090909090909092, paths = {"EmoteKEKW/EmotePack_Global/peepoRiot.dds"},}
EmotePack["monkaLaugh"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/monkaLaugh.dds"},}
EmotePack["widepeepoFat"] = {type = "emote", scale = 4.2105263157894735, paths = {"EmoteKEKW/EmotePack_Global/widepeepoFat.dds"},}
EmotePack["ppL"] = {type = "emote", scale = 1.2857142857142858, paths = {"EmoteKEKW/EmotePack_Global/ppL.dds"},}
EmotePack["pepeL"] = {type = "emote", scale = 1.25, paths = {"EmoteKEKW/EmotePack_Global/pepeL.dds"},}
EmotePack["peepoG"] = {type = "emote", scale = 1.2307692307692308, paths = {"EmoteKEKW/EmotePack_Global/peepoG.dds"},}
EmotePack["Daijoubu"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Daijoubu.dds"},}
EmotePack["peepoSIMP"] = {type = "emote", scale = 0.875, paths = {"EmoteKEKW/EmotePack_Global/peepoSIMP.dds"},}
EmotePack["PeepoFinger"] = {type = "emote", scale = 1.75, paths = {"EmoteKEKW/EmotePack_Global/PeepoFinger.dds"},}
EmotePack["monakS"] = {type = "emote", scale = 1.2307692307692308, paths = {"EmoteKEKW/EmotePack_Global/monakS.dds"},}
EmotePack["OOF"] = {type = "emote", scale = 1.0869565217391304, paths = {"EmoteKEKW/EmotePack_Global/OOF.dds"},}
EmotePack["Weirdge"] = {type = "emote", scale = 1.2727272727272727, paths = {"EmoteKEKW/EmotePack_Global/Weirdge.dds"},}
EmotePack["Hmmm"] = {type = "emote", scale = 1.0666666666666667, paths = {"EmoteKEKW/EmotePack_Global/Hmmm.dds"},}
EmotePack["BOGGED"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/BOGGED.dds"},}
EmotePack["peepoExit"] = {type = "emote", scale = 0.90625, paths = {"EmoteKEKW/EmotePack_Global/peepoExit.dds"},}
EmotePack["AYAYA"] = {type = "emote", scale = 1.032258064516129, paths = {"EmoteKEKW/EmotePack_Global/AYAYA.dds"},}
EmotePack["FeelsRageMan"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FeelsRageMan.dds"},}
EmotePack["REEEEE"] = {type = "emote", scale = 1.1428571428571428, paths = {"EmoteKEKW/EmotePack_Global/REEEEE.dds"},}
EmotePack["YeahBoi"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/YeahBoi.dds"},}
EmotePack["Kermitpls"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Kermitpls.dds"},}
EmotePack["WideHard"] = {type = "emote", scale = 4.0, paths = {"EmoteKEKW/EmotePack_Global/WideHard.dds"},}
EmotePack["GAMEOVER"] = {type = "emote", scale = 4.4375, paths = {"EmoteKEKW/EmotePack_Global/GAMEOVER.dds"},}
EmotePack["HEYYEYAAEYAAAEYAEYAA"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/HEYYEYAAEYAAAEYAEYAA.dds"},}
EmotePack["ILuvU"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/ILuvU.dds"},}
EmotePack["GoodNight"] = {type = "emote", scale = 0.96875, paths = {"EmoteKEKW/EmotePack_Global/GoodNight.dds"},}
EmotePack["pOg"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/pOg.dds"},}
EmotePack["haHAA"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/haHAA.dds"},}
EmotePack["PepeHands"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PepeHands.dds"},}
EmotePack["pepoRope"] = {type = "emote", scale = 1.032258064516129, paths = {"EmoteKEKW/EmotePack_Global/pepoRope.dds"},}
EmotePack["COGGERS"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/COGGERS.dds"},}
EmotePack["LULW"] = {type = "emote", scale = 0.875, paths = {"EmoteKEKW/EmotePack_Global/LULW.dds"},}
EmotePack["CirnoBaka"] = {type = "emote", scale = 2.4, paths = {"EmoteKEKW/EmotePack_Global/CirnoBaka.dds"},}
EmotePack["peepoCheer"] = {type = "emote", scale = 2.2, paths = {"EmoteKEKW/EmotePack_Global/peepoCheer.dds"},}
EmotePack["Madge"] = {type = "emote", scale = 1.2727272727272727, paths = {"EmoteKEKW/EmotePack_Global/Madge.dds"},}
EmotePack["MegaLUL"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/MegaLUL.dds"},}
EmotePack["PogU"] = {type = "emote", scale = 0.875, paths = {"EmoteKEKW/EmotePack_Global/PogU.dds"},}
EmotePack["LETSGO"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/LETSGO.dds"},}
EmotePack["rageW"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/rageW.dds"},}
EmotePack["pepeW"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/pepeW.dds"},}
EmotePack["peepoDetective"] = {type = "emote", scale = 1.4, paths = {"EmoteKEKW/EmotePack_Global/peepoDetective.dds"},}
EmotePack["KEKLEO"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KEKLEO.dds"},}
EmotePack["peepoKiss"] = {type = "emote", scale = 1.1666666666666667, paths = {"EmoteKEKW/EmotePack_Global/peepoKiss.dds"},}
EmotePack["WTFgurl"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/WTFgurl.dds"},}
EmotePack["forsenCD"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/forsenCD.dds"},}
EmotePack["pepeGun"] = {type = "emote", scale = 1.0666666666666667, paths = {"EmoteKEKW/EmotePack_Global/pepeGun.dds"},}
EmotePack["monkaO"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/monkaO.dds"},}
EmotePack["TooGood"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TooGood.dds"},}
EmotePack["5Head"] = {type = "emote", scale = 0.8125, paths = {"EmoteKEKW/EmotePack_Global/5Head.dds"},}
EmotePack["KeK"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KeK.dds"},}
EmotePack["Gladge"] = {type = "emote", scale = 1.2727272727272727, paths = {"EmoteKEKW/EmotePack_Global/Gladge.dds"},}
EmotePack["PepoRage"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PepoRage.dds"},}
EmotePack["PepeLaugh"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PepeLaugh.dds"},}
EmotePack["Bedge"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Bedge.dds"},}
EmotePack["peepoChrist"] = {type = "emote", scale = 1.1666666666666667, paths = {"EmoteKEKW/EmotePack_Global/peepoChrist.dds"},}
EmotePack["4Town"] = {type = "emote", scale = 4.0, paths = {"EmoteKEKW/EmotePack_Global/4Town.dds"},}
EmotePack["monkaThink"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/monkaThink.dds"},}
EmotePack["OMEGALULEatingAnEggplant"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/OMEGALULEatingAnEggplant.dds"},}
EmotePack["Hmm"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Hmm.dds"},}
EmotePack["PepeLove"] = {type = "emote", scale = 1.28, paths = {"EmoteKEKW/EmotePack_Global/PepeLove.dds"},}
EmotePack["KermitTea"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KermitTea.dds"},}
EmotePack["monkaEyes"] = {type = "emote", scale = 3.75, paths = {"EmoteKEKW/EmotePack_Global/monkaEyes.dds"},}
EmotePack["NickyQ"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/NickyQ.dds"},}
EmotePack["KKoooona"] = {type = "emote", scale = 4.0, paths = {"EmoteKEKW/EmotePack_Global/KKoooona.dds"},}
EmotePack["peepoHey"] = {type = "emote", scale = 1.1666666666666667, paths = {"EmoteKEKW/EmotePack_Global/peepoHey.dds"},}
EmotePack["DIDSOMEONESAYCOCK"] = {type = "emote", scale = 0.7096774193548387, paths = {"EmoteKEKW/EmotePack_Global/DIDSOMEONESAYCOCK.dds"},}
EmotePack["FeelsWeirdMan"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FeelsWeirdMan.dds"},}
EmotePack["BibleBag"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/BibleBag.dds"},}
EmotePack["xbn"] = {type = "emote", scale = 5.0, paths = {"EmoteKEKW/EmotePack_Global/xbn.dds"},}
EmotePack["Gigachad"] = {type = "emote", scale = 0.90625, paths = {"EmoteKEKW/EmotePack_Global/Gigachad.dds"},}
EmotePack["Pepega"] = {type = "emote", scale = 1.28, paths = {"EmoteKEKW/EmotePack_Global/Pepega.dds"},}
EmotePack["UHM"] = {type = "emote", scale = 1.032258064516129, paths = {"EmoteKEKW/EmotePack_Global/UHM.dds"},}
EmotePack["peepoHurt"] = {type = "emote", scale = 1.2727272727272727, paths = {"EmoteKEKW/EmotePack_Global/peepoHurt.dds"},}
EmotePack["WoweeW"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/WoweeW.dds"},}
EmotePack["PepeThink"] = {type = "emote", scale = 1.032258064516129, paths = {"EmoteKEKW/EmotePack_Global/PepeThink.dds"},}
EmotePack["NepYay"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/NepYay.dds"},}
EmotePack["YEP"] = {type = "emote", scale = 1.032258064516129, paths = {"EmoteKEKW/EmotePack_Global/YEP.dds"},}
EmotePack["PepoG"] = {type = "emote", scale = 1.2307692307692308, paths = {"EmoteKEKW/EmotePack_Global/PepoG.dds"},}
EmotePack["monkaGun"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/monkaGun.dds"},}
EmotePack["Ohno"] = {type = "emote", scale = 1.0666666666666667, paths = {"EmoteKEKW/EmotePack_Global/Ohno.dds"},}
EmotePack["Nerdge"] = {type = "emote", scale = 1.2173913043478262, paths = {"EmoteKEKW/EmotePack_Global/Nerdge.dds"},}
EmotePack["PepeLaugh"] = {type = "emote", scale = 1.0344827586206897, paths = {"EmoteKEKW/EmotePack_Global/PepeLaugh.dds"},}
EmotePack["WeirdDude"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/WeirdDude.dds"},}
EmotePack["arnoldHalt"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/arnoldHalt.dds"},}
EmotePack["YouDied"] = {type = "emote", scale = 5.333333333333333, paths = {"EmoteKEKW/EmotePack_Global/YouDied.dds"},}
EmotePack["peepoAwesome"] = {type = "emote", scale = 1.391304347826087, paths = {"EmoteKEKW/EmotePack_Global/peepoAwesome.dds"},}
EmotePack["POI"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/POI.dds"},}
EmotePack["TeeHee"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TeeHee.dds"},}
EmotePack["HeyPal"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/HeyPal.dds"},}
EmotePack["FeelsOldMan"] = {type = "emote", scale = 1.032258064516129, paths = {"EmoteKEKW/EmotePack_Global/FeelsOldMan.dds"},}
EmotePack["LOLW"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/LOLW.dds"},}
EmotePack["JustRight"] = {type = "emote", scale = 1.0666666666666667, paths = {"EmoteKEKW/EmotePack_Global/JustRight.dds"},}
EmotePack["WeirdChamp"] = {type = "emote", scale = 0.96875, paths = {"EmoteKEKW/EmotePack_Global/WeirdChamp.dds"},}
EmotePack["PepeScoots"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PepeScoots.dds"},}
EmotePack["shrugFace"] = {type = "emote", scale = 2.75, paths = {"EmoteKEKW/EmotePack_Global/shrugFace.dds"},}
EmotePack["GG!"] = {type = "emote", scale = 1.55, paths = {"EmoteKEKW/EmotePack_Global/GG!.dds"},}
EmotePack["Kissahomie"] = {type = "emote", scale = 1.3333333333333333, paths = {"EmoteKEKW/EmotePack_Global/Kissahomie.dds"},}
EmotePack["Sadeg"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Sadeg.dds"},}
EmotePack["Pepeg"] = {type = "emote", scale = 1.2727272727272727, paths = {"EmoteKEKW/EmotePack_Global/Pepeg.dds"},}
EmotePack["Floshed"] = {type = "emote", scale = 1.032258064516129, paths = {"EmoteKEKW/EmotePack_Global/Floshed.dds"},}
EmotePack["NOOOO"] = {type = "emote", scale = 1.2173913043478262, paths = {"EmoteKEKW/EmotePack_Global/NOOOO.dds"},}
EmotePack["BadSpeedrun"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/BadSpeedrun.dds"},}
EmotePack["noxSorry"] = {type = "emote", scale = 0.875, paths = {"EmoteKEKW/EmotePack_Global/noxSorry.dds"},}
EmotePack["UhOh"] = {type = "emote", scale = 1.032258064516129, paths = {"EmoteKEKW/EmotePack_Global/UhOh.dds"},}
EmotePack["PepeMods"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PepeMods.dds"},}
EmotePack["GoodMorning"] = {type = "emote", scale = 0.96875, paths = {"EmoteKEKW/EmotePack_Global/GoodMorning.dds"},}
EmotePack["WeebsOut"] = {type = "emote", scale = 0.90625, paths = {"EmoteKEKW/EmotePack_Global/WeebsOut.dds"},}
EmotePack["Pogplant"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Pogplant.dds"},}
EmotePack["FeelsSadMan"] = {type = "emote", scale = 1.037037037037037, paths = {"EmoteKEKW/EmotePack_Global/FeelsSadMan.dds"},}
EmotePack["PepeChill"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PepeChill.dds"},}
EmotePack["Krappa"] = {type = "emote", scale = 0.84375, paths = {"EmoteKEKW/EmotePack_Global/Krappa.dds"},}
EmotePack["RoWOW"] = {type = "emote", scale = 1.7, paths = {"EmoteKEKW/EmotePack_Global/RoWOW.dds"},}
EmotePack["NOPE"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/NOPE.dds"},}
EmotePack["PepeHands"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PepeHands.dds"},}
EmotePack["Pog"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Pog.dds"},}
EmotePack["KermitComfy"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KermitComfy.dds"},}
EmotePack["Kappa_420"] = {type = "emote", scale = 0.78125, paths = {"EmoteKEKW/EmotePack_Global/Kappa_420.dds"},}
EmotePack["PagMan"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PagMan.dds"},}
EmotePack["FeelsGladMan"] = {type = "emote", scale = 1.032258064516129, paths = {"EmoteKEKW/EmotePack_Global/FeelsGladMan.dds"},}
EmotePack["pepeD"] = {type = "emote", scale = 1.8571428571428572, paths = {"EmoteKEKW/EmotePack_Global/pepeD.dds"},}
EmotePack["OMEGALUL"] = {type = "emote", scale = 0.96875, paths = {"EmoteKEKW/EmotePack_Global/OMEGALUL.dds"},}
EmotePack["monkaTOS"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/monkaTOS.dds"},}
EmotePack["monkaHmm"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/monkaHmm.dds"},}
EmotePack["LULW"] = {type = "emote", scale = 0.875, paths = {"EmoteKEKW/EmotePack_Global/LULW.dds"},}
EmotePack["pepeW"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/pepeW.dds"},}
EmotePack["MeguminHappy"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/MeguminHappy.dds"},}
EmotePack["LennyFace"] = {type = "emote", scale = 2.8, paths = {"EmoteKEKW/EmotePack_Global/LennyFace.dds"},}
EmotePack["peepoNotes"] = {type = "emote", scale = 1.2307692307692308, paths = {"EmoteKEKW/EmotePack_Global/peepoNotes.dds"},}
EmotePack["NaM"] = {type = "emote", scale = 0.96875, paths = {"EmoteKEKW/EmotePack_Global/NaM.dds"},}
EmotePack["THICC"] = {type = "emote", scale = 1.037037037037037, paths = {"EmoteKEKW/EmotePack_Global/THICC.dds"},}
EmotePack["NyanPasu"] = {type = "emote", scale = 1.1428571428571428, paths = {"EmoteKEKW/EmotePack_Global/NyanPasu.dds"},}
EmotePack["4WeirdBuff"] = {type = "emote", scale = 0.8928571428571429, paths = {"EmoteKEKW/EmotePack_Global/4WeirdBuff.dds"},}
EmotePack["Pepega"] = {type = "emote", scale = 1.103448275862069, paths = {"EmoteKEKW/EmotePack_Global/Pepega.dds"},}
EmotePack["peepoS"] = {type = "emote", scale = 1.4, paths = {"EmoteKEKW/EmotePack_Global/peepoS.dds"},}
EmotePack["ThinkingFaceEmoji"] = {type = "emote", scale = 0.9655172413793104, paths = {"EmoteKEKW/EmotePack_Global/ThinkingFaceEmoji.dds"},}
EmotePack["OMEGASP"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/OMEGASP.dds"},}
EmotePack["DontBully"] = {type = "emote", scale = 0.96875, paths = {"EmoteKEKW/EmotePack_Global/DontBully.dds"},}
EmotePack["peepoCute"] = {type = "emote", scale = 1.1428571428571428, paths = {"EmoteKEKW/EmotePack_Global/peepoCute.dds"},}
EmotePack["ButtBooty"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/ButtBooty.dds"},}
EmotePack["DesuOP"] = {type = "emote", scale = 1.0666666666666667, paths = {"EmoteKEKW/EmotePack_Global/DesuOP.dds"},}
EmotePack["monkaSSS"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/monkaSSS.dds"},}
EmotePack["Starege"] = {type = "emote", scale = 1.0769230769230769, paths = {"EmoteKEKW/EmotePack_Global/Starege.dds"},}
EmotePack["LickMe"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/LickMe.dds"},}
EmotePack["peepoNo"] = {type = "emote", scale = 1.1428571428571428, paths = {"EmoteKEKW/EmotePack_Global/peepoNo.dds"},}
EmotePack["peepoCry"] = {type = "emote", scale = 1.0769230769230769, paths = {"EmoteKEKW/EmotePack_Global/peepoCry.dds"},}
EmotePack["WanWan"] = {type = "emote", scale = 1.032258064516129, paths = {"EmoteKEKW/EmotePack_Global/WanWan.dds"},}
EmotePack["MOIST"] = {type = "emote", scale = 4.111111111111111, paths = {"EmoteKEKW/EmotePack_Global/MOIST.dds"},}
EmotePack["AndKnuckles"] = {type = "emote", scale = 7.2727272727272725, paths = {"EmoteKEKW/EmotePack_Global/AndKnuckles.dds"},}
EmotePack["peepoFriendship"] = {type = "emote", scale = 1.8823529411764706, paths = {"EmoteKEKW/EmotePack_Global/peepoFriendship.dds"},}
EmotePack["widepeepoClown"] = {type = "emote", scale = 4.2105263157894735, paths = {"EmoteKEKW/EmotePack_Global/widepeepoClown.dds"},}
EmotePack["noxWhat"] = {type = "emote", scale = 0.78125, paths = {"EmoteKEKW/EmotePack_Global/noxWhat.dds"},}
EmotePack["PassTheBleach"] = {type = "emote", scale = 1.1071428571428572, paths = {"EmoteKEKW/EmotePack_Global/PassTheBleach.dds"},}
EmotePack["peepoYes"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/peepoYes.dds"},}
EmotePack["ABABABABA"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/ABABABABA.dds"},}
EmotePack["KKrikey"] = {type = "emote", scale = 0.8928571428571429, paths = {"EmoteKEKW/EmotePack_Global/KKrikey.dds"},}
EmotePack["TriEasy"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TriEasy.dds"},}
EmotePack["mericCat"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/mericCat.dds"},}
EmotePack["PepoThink"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PepoThink.dds"},}
EmotePack["KannaWave"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KannaWave.dds"},}
EmotePack["KEKYou"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KEKYou.dds"},}
EmotePack["gachiPRIDE"] = {type = "emote", scale = 0.8571428571428571, paths = {"EmoteKEKW/EmotePack_Global/gachiPRIDE.dds"},}
EmotePack["HYPEtime"] = {type = "emote", scale = 2.888888888888889, paths = {"EmoteKEKW/EmotePack_Global/HYPEtime.dds"},}
EmotePack["KEKLEO"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KEKLEO.dds"},}
EmotePack["monkaChrist"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/monkaChrist.dds"},}
EmotePack["peepoFinger"] = {type = "emote", scale = 1.4, paths = {"EmoteKEKW/EmotePack_Global/peepoFinger.dds"},}
EmotePack["peepoRun"] = {type = "emote", scale = 0.9629629629629629, paths = {"EmoteKEKW/EmotePack_Global/peepoRun.dds"},}
EmotePack["CatHiss"] = {type = "emote", scale = 0.90625, paths = {"EmoteKEKW/EmotePack_Global/CatHiss.dds"},}
EmotePack["PepegaBlind"] = {type = "emote", scale = 1.2727272727272727, paths = {"EmoteKEKW/EmotePack_Global/PepegaBlind.dds"},}
EmotePack["HYPERDANSGAMEW"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/HYPERDANSGAMEW.dds"},}
EmotePack["PepePoint"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PepePoint.dds"},}
EmotePack["monkaStare"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/monkaStare.dds"},}
EmotePack["WaitWhat"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/WaitWhat.dds"},}
EmotePack["ICANT"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/ICANT.dds"},}
EmotePack["2Header"] = {type = "emote", scale = 4.0, paths = {"EmoteKEKW/EmotePack_Global/2Header.dds"},}
EmotePack["OpieOShaq"] = {type = "emote", scale = 0.84375, paths = {"EmoteKEKW/EmotePack_Global/OpieOShaq.dds"},}
EmotePack["4HEad"] = {type = "emote", scale = 1.391304347826087, paths = {"EmoteKEKW/EmotePack_Global/4HEad.dds"},}
EmotePack["peepoHug"] = {type = "emote", scale = 1.4, paths = {"EmoteKEKW/EmotePack_Global/peepoHug.dds"},}
EmotePack["Magoo"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Magoo.dds"},}
EmotePack["PogO"] = {type = "emote", scale = 0.96875, paths = {"EmoteKEKW/EmotePack_Global/PogO.dds"},}
EmotePack["peepoRage"] = {type = "emote", scale = 1.3333333333333333, paths = {"EmoteKEKW/EmotePack_Global/peepoRage.dds"},}
EmotePack["Booba"] = {type = "emote", scale = 1.0666666666666667, paths = {"EmoteKEKW/EmotePack_Global/Booba.dds"},}
EmotePack["PeepoStop"] = {type = "emote", scale = 1.103448275862069, paths = {"EmoteKEKW/EmotePack_Global/PeepoStop.dds"},}
EmotePack["PoiPoi"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PoiPoi.dds"},}
EmotePack["smileW"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/smileW.dds"},}
EmotePack["peepoEZ"] = {type = "emote", scale = 1.3333333333333333, paths = {"EmoteKEKW/EmotePack_Global/peepoEZ.dds"},}
EmotePack["Pog"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Pog.dds"},}
EmotePack["peepoFlower"] = {type = "emote", scale = 1.5555555555555556, paths = {"EmoteKEKW/EmotePack_Global/peepoFlower.dds"},}
EmotePack["GotEm"] = {type = "emote", scale = 0.96875, paths = {"EmoteKEKW/EmotePack_Global/GotEm.dds"},}
EmotePack["peepoMad"] = {type = "emote", scale = 1.2727272727272727, paths = {"EmoteKEKW/EmotePack_Global/peepoMad.dds"},}
EmotePack["KKomrade"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KKomrade.dds"},}
EmotePack["FeelsBadMan"] = {type = "emote", scale = 1.032258064516129, paths = {"EmoteKEKW/EmotePack_Global/FeelsBadMan.dds"},}
EmotePack["Widega"] = {type = "emote", scale = 4.0, paths = {"EmoteKEKW/EmotePack_Global/Widega.dds"},}
EmotePack["HeheHehe"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/HeheHehe.dds"},}
EmotePack["NeverGiveUp"] = {type = "emote", scale = 4.8, paths = {"EmoteKEKW/EmotePack_Global/NeverGiveUp.dds"},}
EmotePack["LULW"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/LULW.dds"},}
EmotePack["KEKW"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KEKW.dds"},}
EmotePack["peepoComeBack"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/peepoComeBack.dds"},}
EmotePack["peepoScared"] = {type = "emote", scale = 1.391304347826087, paths = {"EmoteKEKW/EmotePack_Global/peepoScared.dds"},}
EmotePack["FeelsTastyMan"] = {type = "emote", scale = 1.2173913043478262, paths = {"EmoteKEKW/EmotePack_Global/FeelsTastyMan.dds"},}
EmotePack["1Head"] = {type = "emote", scale = 1.1923076923076923, paths = {"EmoteKEKW/EmotePack_Global/1Head.dds"},}
EmotePack["peepoThink"] = {type = "emote", scale = 1.3333333333333333, paths = {"EmoteKEKW/EmotePack_Global/peepoThink.dds"},}
EmotePack["PepeHands"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PepeHands.dds"},}
EmotePack["AYAYA"] = {type = "emote", scale = 1.032258064516129, paths = {"EmoteKEKW/EmotePack_Global/AYAYA.dds"},}
EmotePack["NANI!"] = {type = "emote", scale = 3.0555555555555554, paths = {"EmoteKEKW/EmotePack_Global/NANI!.dds"},}
EmotePack["SadgeBusiness"] = {type = "emote", scale = 1.1923076923076923, paths = {"EmoteKEKW/EmotePack_Global/SadgeBusiness.dds"},}
EmotePack["OOF"] = {type = "emote", scale = 0.9375, paths = {"EmoteKEKW/EmotePack_Global/OOF.dds"},}
EmotePack["widepepOMEGAKEKHappyChampHands"] = {type = "emote", scale = 2.0, paths = {"EmoteKEKW/EmotePack_Global/widepepOMEGAKEKHappyChampHands.dds"},}
EmotePack["HiKibbi"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/HiKibbi.dds"},}
EmotePack["MutedMic"] = {type = "emote", scale = 0.875, paths = {"EmoteKEKW/EmotePack_Global/MutedMic.dds"},}
EmotePack["CapitalD"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/CapitalD.dds"},}
EmotePack["PepeCool"] = {type = "emote", scale = 1.032258064516129, paths = {"EmoteKEKW/EmotePack_Global/PepeCool.dds"},}
EmotePack["ConfusedCat"] = {type = "emote", scale = 1.28, paths = {"EmoteKEKW/EmotePack_Global/ConfusedCat.dds"},}
EmotePack["BRUH"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/BRUH.dds"},}
EmotePack["stareChamp"] = {type = "emote", scale = 1.4, paths = {"EmoteKEKW/EmotePack_Global/stareChamp.dds"},}
EmotePack["Okayga"] = {type = "emote", scale = 1.28, paths = {"EmoteKEKW/EmotePack_Global/Okayga.dds"},}
EmotePack["KannaBlob"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KannaBlob.dds"},}
EmotePack["5Head"] = {type = "emote", scale = 0.8125, paths = {"EmoteKEKW/EmotePack_Global/5Head.dds"},}
EmotePack["PepoFinger"] = {type = "emote", scale = 1.103448275862069, paths = {"EmoteKEKW/EmotePack_Global/PepoFinger.dds"},}
EmotePack["HungryTag"] = {type = "emote", scale = 1.6, paths = {"EmoteKEKW/EmotePack_Global/HungryTag.dds"},}
EmotePack["monkaCozy"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/monkaCozy.dds"},}
EmotePack["peepoWow"] = {type = "emote", scale = 1.4736842105263157, paths = {"EmoteKEKW/EmotePack_Global/peepoWow.dds"},}
EmotePack["peepoLove"] = {type = "emote", scale = 1.2727272727272727, paths = {"EmoteKEKW/EmotePack_Global/peepoLove.dds"},}
EmotePack["StopStreaming"] = {type = "emote", scale = 4.0, paths = {"EmoteKEKW/EmotePack_Global/StopStreaming.dds"},}
EmotePack["peepoComfyBlanket"] = {type = "emote", scale = 1.032258064516129, paths = {"EmoteKEKW/EmotePack_Global/peepoComfyBlanket.dds"},}
EmotePack["WeirdEyes"] = {type = "emote", scale = 4.0, paths = {"EmoteKEKW/EmotePack_Global/WeirdEyes.dds"},}
EmotePack["MEGALUL"] = {type = "emote", scale = 1.0666666666666667, paths = {"EmoteKEKW/EmotePack_Global/MEGALUL.dds"},}
EmotePack["CiGrip"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/CiGrip.dds"},}
EmotePack["DatSauce"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/DatSauce.dds"},}
EmotePack["ForeverAlone"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/ForeverAlone.dds"},}
EmotePack["GabeN"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/GabeN.dds"},}
EmotePack["HailHelix"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/HailHelix.dds"},}
EmotePack["ShoopDaWhoop"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/ShoopDaWhoop.dds"},}
EmotePack["TwaT"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/TwaT.dds"},}
EmotePack["WatChuSay"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/WatChuSay.dds"},}
EmotePack["bttvNice"] = {type = "emote", scale = 1.5, paths = {"EmoteKEKW/EmotePack_Global/bttvNice.dds"},}
EmotePack["TaxiBro"] = {type = "emote", scale = 2.9, paths = {"EmoteKEKW/EmotePack_Global/TaxiBro.dds"},}
EmotePack["BroBalt"] = {type = "emote", scale = 1.5333333333333334, paths = {"EmoteKEKW/EmotePack_Global/BroBalt.dds"},}
EmotePack["CandianRage"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/CandianRage.dds"},}
EmotePack["VisLaud"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/VisLaud.dds"},}
EmotePack["KaRappa"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/KaRappa.dds"},}
EmotePack["sosGame"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/sosGame.dds"},}
EmotePack["CruW"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/CruW.dds"},}
EmotePack["RarePepe"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/RarePepe.dds"},}
EmotePack["haHAA"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/haHAA.dds"},}
EmotePack["FeelsBirthdayMan"] = {type = "emote", scale = 0.6785714285714286, paths = {"EmoteKEKW/EmotePack_Global/FeelsBirthdayMan.dds"},}
EmotePack["RonSmug"] = {type = "emote", scale = 0.75, paths = {"EmoteKEKW/EmotePack_Global/RonSmug.dds"},}
EmotePack["KappaCool"] = {type = "emote", scale = 0.7857142857142857, paths = {"EmoteKEKW/EmotePack_Global/KappaCool.dds"},}
EmotePack["bUrself"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/bUrself.dds"},}
EmotePack["ConcernDoge"] = {type = "emote", scale = 0.8928571428571429, paths = {"EmoteKEKW/EmotePack_Global/ConcernDoge.dds"},}
EmotePack["FeelsBadMan"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FeelsBadMan.dds"},}
EmotePack["FeelsGoodMan"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FeelsGoodMan.dds"},}
EmotePack["FireSpeed"] = {type = "emote", scale = 1.8928571428571428, paths = {"EmoteKEKW/EmotePack_Global/FireSpeed.dds"},}
EmotePack["FishMoley"] = {type = "emote", scale = 1.6470588235294117, paths = {"EmoteKEKW/EmotePack_Global/FishMoley.dds"},}
EmotePack["Hhhehehe"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Hhhehehe.dds"},}
EmotePack["KKona"] = {type = "emote", scale = 0.7352941176470589, paths = {"EmoteKEKW/EmotePack_Global/KKona.dds"},}
EmotePack["NaM"] = {type = "emote", scale = 0.95, paths = {"EmoteKEKW/EmotePack_Global/NaM.dds"},}
EmotePack["PoleDoge"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PoleDoge.dds"},}
EmotePack["tehPoleCat"] = {type = "emote", scale = 0.75, paths = {"EmoteKEKW/EmotePack_Global/tehPoleCat.dds"},}
EmotePack["AngelThump"] = {type = "emote", scale = 3.0, paths = {"EmoteKEKW/EmotePack_Global/AngelThump.dds"},}
EmotePack["SourPls"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/SourPls.dds"},}
EmotePack["FeelsSnowMan"] = {type = "emote", scale = 1.0333333333333334, paths = {"EmoteKEKW/EmotePack_Global/FeelsSnowMan.dds"},}
EmotePack["FeelsSnowyMan"] = {type = "emote", scale = 1.0333333333333334, paths = {"EmoteKEKW/EmotePack_Global/FeelsSnowyMan.dds"},}
EmotePack["LuL"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/LuL.dds"},}
EmotePack["SaltyCorn"] = {type = "emote", scale = 0.9333333333333333, paths = {"EmoteKEKW/EmotePack_Global/SaltyCorn.dds"},}
EmotePack["monkaS"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/monkaS.dds"},}
EmotePack["VapeNation"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/VapeNation.dds"},}
EmotePack["ariW"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/ariW.dds"},}
EmotePack["notsquishY"] = {type = "emote", scale = 0.8571428571428571, paths = {"EmoteKEKW/EmotePack_Global/notsquishY.dds"},}
EmotePack["FeelsAmazingMan"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/FeelsAmazingMan.dds"},}
EmotePack["DuckerZ"] = {type = "emote", scale = 1.3214285714285714, paths = {"EmoteKEKW/EmotePack_Global/DuckerZ.dds"},}
EmotePack["Wowee"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Wowee.dds"},}
EmotePack["SqShy"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/SqShy.dds"},}
EmotePack["WubTF"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/WubTF.dds"},}
EmotePack["cvR"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/cvR.dds"},}
EmotePack["cvL"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/cvL.dds"},}
EmotePack["cvHazmat"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/cvHazmat.dds"},}
EmotePack["cvMask"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/cvMask.dds"},}
EmotePack["DogChamp"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/DogChamp.dds"},}
EmotePack["PATHETIC"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/PATHETIC.dds"},}
EmotePack["LETSFUCKINGGOOO"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/LETSFUCKINGGOOO.dds"},}
EmotePack["dronkBepis"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/dronkBepis.dds"},}
EmotePack["DESPAIR"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/DESPAIR.dds"},}
EmotePack["MohammedL"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/MohammedL.dds"},}
EmotePack["slavDoge"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/slavDoge.dds"},}
EmotePack["Inshallah"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Inshallah.dds"},}
EmotePack["Moyai"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Moyai.dds"},}
EmotePack["Aware"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/Aware.dds"},}
EmotePack["LETHIMCOOK"] = {type = "emote", scale = 1.1428571428571428, paths = {"EmoteKEKW/EmotePack_Global/LETHIMCOOK.dds"},}
EmotePack["WHOLETHIMCOOK"] = {type = "emote", scale = 1.0, paths = {"EmoteKEKW/EmotePack_Global/WHOLETHIMCOOK.dds"},}

