-- English strings for Transmute Set Crafter

ZO_CreateStringId("SI_TSC_TITLE",                  "Transmute Set Crafter")
ZO_CreateStringId("SI_TSC_INVENTORY_HEADER",        "Item Sets")
ZO_CreateStringId("SI_TSC_BACK_PREFIX",             "← ")
ZO_CreateStringId("SI_TSC_SET_PIECE_COUNT",         "<<1>> pieces")
ZO_CreateStringId("SI_TSC_QUEUE_HEADER",            "Queue")
ZO_CreateStringId("SI_TSC_TARGET_TRAIT_LABEL",      "Target Trait:")
ZO_CreateStringId("SI_TSC_SELECT_TRAIT_PROMPT",     "-- select trait --")
ZO_CreateStringId("SI_TSC_ENCHANTMENT_LABEL",       "Enchantment:")
ZO_CreateStringId("SI_TSC_ENCHANTMENT_PLACEHOLDER", "e.g. Weapon Damage")
ZO_CreateStringId("SI_TSC_QUALITY_LABEL",           "Quality:")
ZO_CreateStringId("SI_TSC_SELECT_QUALITY_PROMPT",   "-- select quality --")
ZO_CreateStringId("SI_TSC_ADD_TO_QUEUE",            "Add to Queue")
ZO_CreateStringId("SI_TSC_ADD_COUNT_TO_QUEUE",      "Add to Queue (<<1>>)")
ZO_CreateStringId("SI_TSC_TRANSMUTE_ALL",           "Reconstruct All (<<1>>)")
ZO_CreateStringId("SI_TSC_CLEAR_QUEUE",             "Clear Queue")
ZO_CreateStringId("SI_TSC_CRYSTALS_COST",           "Crystals needed: <<1>>  /  Available: <<2>>")
ZO_CreateStringId("SI_TSC_QUEUE_ROW_DETAIL",        "<<1>>  ·  <<2>>")
ZO_CreateStringId("SI_TSC_EMPTY_QUEUE",             "Queue is empty")
ZO_CreateStringId("SI_TSC_NOT_AT_STATION",          "Must be at a Transmutation Station (Reconstruct tab)")
ZO_CreateStringId("SI_TSC_INSUFFICIENT_CRYSTALS",   "Not enough Transmute Crystals (need <<1>>, have <<2>>)")
ZO_CreateStringId("SI_TSC_ITEM_NOT_FOUND",          "Item Set piece no longer available: <<1>>")
ZO_CreateStringId("SI_TSC_TRANSMUTE_FAILED",        "Reconstruction failed: <<1>>")
ZO_CreateStringId("SI_TSC_FILTER_WEAPONS",          "Weapons")
ZO_CreateStringId("SI_TSC_FILTER_ARMOR",            "Armor")
ZO_CreateStringId("SI_TSC_FILTER_JEWELRY",          "Jewelry")
ZO_CreateStringId("SI_TSC_TRAIT_NOT_RESEARCHED",    " (not researched)")
ZO_CreateStringId("SI_TSC_PIECE_NOT_COLLECTED",     " (not collected)")
ZO_CreateStringId("SI_TSC_SEARCH_PLACEHOLDER",      "Search by set name...")
ZO_CreateStringId("SI_BINDING_NAME_TSC_TOGGLE",     "Toggle Transmute Set Crafter")
ZO_CreateStringId("SI_TSC_GAMEPAD_UNSUPPORTED",     "Transmute Set Crafter does not support gamepad mode.")

-- Settings
ZO_CreateStringId("SI_TSC_SETTINGS_PANEL_NAME",     "Transmute Set Crafter")
ZO_CreateStringId("SI_TSC_SETTINGS_CLOSE_ON_EXIT",  "Close on transmute station exit")
ZO_CreateStringId("SI_TSC_SETTINGS_CLOSE_ON_EXIT_TOOLTIP", "Automatically close the window when you leave a Transmutation Station.")
ZO_CreateStringId("SI_TSC_SETTINGS_AUTO_OPEN",      "Open at transmute station")
ZO_CreateStringId("SI_TSC_SETTINGS_AUTO_OPEN_TOOLTIP", "Automatically open the window when you interact with a Transmutation Station.")
ZO_CreateStringId("SI_TSC_SETTINGS_AUTO_RECONSTRUCT", "Open on Reconstruct tab")
ZO_CreateStringId("SI_TSC_SETTINGS_AUTO_RECONSTRUCT_TOOLTIP", "Automatically switch the Transmutation Station to the Reconstruct tab when you interact with it. A manual switch back to Retrait in the same session is preserved.")
ZO_CreateStringId("SI_TSC_SETTINGS_AUTO_OPEN_ENCHANT", "Open at enchanting station")
ZO_CreateStringId("SI_TSC_SETTINGS_AUTO_OPEN_ENCHANT_TOOLTIP", "Automatically open the window when you interact with an Enchanting Station and at least one queued item is still waiting on its glyph. Stations interacted with while the queue has no pending glyph work are left alone.")
ZO_CreateStringId("SI_TSC_SETTINGS_CLOSE_ON_ENCHANT_EXIT", "Close on enchanting station exit")
ZO_CreateStringId("SI_TSC_SETTINGS_CLOSE_ON_ENCHANT_EXIT_TOOLTIP", "Automatically close the window when you leave an Enchanting Station.")

-- UI labels (column headers, buttons, placeholder text)
ZO_CreateStringId("SI_TSC_COL_SET",                 "Set")
ZO_CreateStringId("SI_TSC_COL_TYPE",                "Type")
ZO_CreateStringId("SI_TSC_COL_TRAIT",               "Trait")
ZO_CreateStringId("SI_TSC_COL_ENCHANT",             "Enchant")
ZO_CreateStringId("SI_TSC_COL_ITEM",                "Item")
ZO_CreateStringId("SI_TSC_COL_NEED",                "Need")
ZO_CreateStringId("SI_TSC_COL_HAVE",                "Have")
ZO_CreateStringId("SI_TSC_LABEL_MATERIALS",         "Materials")
ZO_CreateStringId("SI_TSC_LABEL_QUICKSAVES",        "Quicksaves")
ZO_CreateStringId("SI_TSC_LABEL_CANCEL_EDIT",       "Cancel Edit")
ZO_CreateStringId("SI_TSC_LABEL_UPDATE_ENTRY",      "Update Entry")
ZO_CreateStringId("SI_TSC_LABEL_EDIT",              "Edit")
ZO_CreateStringId("SI_TSC_LABEL_SAVE",              "Save")
ZO_CreateStringId("SI_TSC_LABEL_NONE",              "(none)")
ZO_CreateStringId("SI_TSC_MISSING_SUFFIX",          " (missing)")
ZO_CreateStringId("SI_TSC_TWO_HANDED_SUFFIX",       " (2H)")
ZO_CreateStringId("SI_TSC_NAME_TRANSMUTE_CRYSTALS", "Transmute Crystals")

-- Queue-row warning reasons (shown when hovering the red ! icon)
ZO_CreateStringId("SI_TSC_WARN_PIECE_GONE",         "Set piece no longer available.")
ZO_CreateStringId("SI_TSC_WARN_NOT_COLLECTED",      "You haven't collected this set piece yet.")
ZO_CreateStringId("SI_TSC_WARN_TRAIT_NOT_RESEARCHED", "You haven't researched this trait for this piece.")

-- Chat / alert notifications
ZO_CreateStringId("SI_TSC_MSG_ALL_DONE",            "All reconstructions complete.")
ZO_CreateStringId("SI_TSC_MSG_NO_TRAIT",            "No target trait selected.")
ZO_CreateStringId("SI_TSC_MSG_NO_QUALITY",          "No quality selected.")
ZO_CreateStringId("SI_TSC_MSG_NO_PIECES",           "No pieces selected.")
ZO_CreateStringId("SI_TSC_MSG_PIECE_GONE_EDIT",     "Item set piece no longer available — cannot edit.")
ZO_CreateStringId("SI_TSC_MSG_QUICKSAVE_NEEDS_NAME","Quicksave needs a name.")
ZO_CreateStringId("SI_TSC_MSG_QUICKSAVE_EMPTY",     "Queue is empty — nothing to save.")
ZO_CreateStringId("SI_TSC_MSG_QUICKSAVE_SAVED",     "Saved quicksave '<<1>>' with <<2>> item(s).")
ZO_CreateStringId("SI_TSC_MSG_QUICKSAVE_LOADED",    "Loaded quicksave '<<1>>' (<<2>> item(s)).")
ZO_CreateStringId("SI_TSC_MSG_QUICKSAVE_DELETED",   "Deleted quicksave '<<1>>'.")
ZO_CreateStringId("SI_TSC_MSG_TYPE_NAME_FIRST",     "Type a name first.")
ZO_CreateStringId("SI_TSC_MSG_NO_LLC",              "LibLazyCrafting not available — install it to auto-craft glyphs.")
ZO_CreateStringId("SI_TSC_MSG_NO_LLC_MAPPING",      "No LibLazyCrafting mapping for '<<1>>' — skipping.")
ZO_CreateStringId("SI_TSC_MSG_APPLIED_EXISTING",    "Applied existing glyph to <<1>>.")
ZO_CreateStringId("SI_TSC_MSG_GLYPH_HAVE_NO_ITEM",  "Have glyph for '<<1>>' but reconstructed item not found.")
ZO_CreateStringId("SI_TSC_MSG_GLYPH_SUMMARY",       "Glyphs — requested: <<1>>, applied existing: <<2>>.")
ZO_CreateStringId("SI_TSC_MSG_GLYPH_INSUFFICIENT",  "Can't craft glyph for '<<1>>' — not enough runes. See the Materials window for what's needed.")
ZO_CreateStringId("SI_TSC_MSG_GLYPH_FAILED",        "Glyph craft failed for '<<1>>'.")
ZO_CreateStringId("SI_TSC_MSG_GLYPH_NO_ITEM",       "Glyph crafted but reconstructed item not found in backpack for '<<1>>'.")
ZO_CreateStringId("SI_TSC_MSG_APPLIED_GLYPH",       "Applied glyph to <<1>>.")

-- Quicksave import / export
ZO_CreateStringId("SI_TSC_LABEL_IMPORT",            "Import")
ZO_CreateStringId("SI_TSC_LABEL_EXPORT",            "Export")
ZO_CreateStringId("SI_TSC_LABEL_E",                 "E")  -- per-row Export button text (icon-like)
ZO_CreateStringId("SI_TSC_EXPORT_DIALOG_TITLE",     "Export Quicksave: <<1>>")
ZO_CreateStringId("SI_TSC_IMPORT_DIALOG_TITLE",     "Import Quicksave")
ZO_CreateStringId("SI_TSC_EXPORT_HINT",             "Copy this string and share it. Recipients can Import it back.")
ZO_CreateStringId("SI_TSC_IMPORT_HINT",             "Paste a TSC export string and click Import.")
ZO_CreateStringId("SI_TSC_MSG_EXPORT_BAD_CHAR",     "Quicksave name contains a reserved character (| or ;). Rename it first.")
ZO_CreateStringId("SI_TSC_MSG_EXPORT_BAD_ENCHANT",  "An enchantment contains a reserved character (;); cannot export.")
ZO_CreateStringId("SI_TSC_MSG_IMPORT_EMPTY",        "Paste a TSC export string first.")
ZO_CreateStringId("SI_TSC_MSG_IMPORT_NOT_TSC",      "That doesn't look like a TSC export string (missing 'TSC1' prefix).")
ZO_CreateStringId("SI_TSC_MSG_IMPORT_MALFORMED",    "Import failed: malformed string at entry <<1>>.")
ZO_CreateStringId("SI_TSC_MSG_IMPORT_NO_NAME",      "Import failed: missing quicksave name.")
ZO_CreateStringId("SI_TSC_MSG_IMPORT_OK",           "Imported quicksave '<<1>>' (<<2>> item(s)).")

-- Rename
ZO_CreateStringId("SI_TSC_LABEL_RENAME",            "Rename")
ZO_CreateStringId("SI_TSC_LABEL_R",                 "R")  -- per-row Rename button text (icon-like)
ZO_CreateStringId("SI_TSC_RENAME_DIALOG_TITLE",     "Rename Quicksave: <<1>>")
ZO_CreateStringId("SI_TSC_RENAME_HINT",             "Edit the name and click Rename.")
ZO_CreateStringId("SI_TSC_MSG_QUICKSAVE_RENAMED",   "Renamed quicksave to '<<1>>'.")

-- Queue from equipped gear
ZO_CreateStringId("SI_TSC_LABEL_QUEUE_EQUIPPED",    "Queue Equipped")
ZO_CreateStringId("SI_TSC_MSG_EQUIPPED_QUEUED",     "Queued <<1>> equipped piece(s); skipped <<2>> (crafted sets and non-reconstructable items can't be queued).")

-- Set-list sort
ZO_CreateStringId("SI_TSC_SORT_BY_NAME",            "Name")
ZO_CreateStringId("SI_TSC_SORT_BY_COST",            "Cost")
ZO_CreateStringId("SI_TSC_SORT_BY_WEIGHT",          "Weight")
