ItemShareSavedVars =
{
    ["Default"] = 
    {
        ["@TankyOrc"] = 
        {
            ["$AccountWide"] = 
            {
                ["sharedItems"] = 
                {
                    ["|H0:item:116411:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||inventory:grom grok"] = 
                    {
                        ["itemLink"] = "|H0:item:116411:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                        ["locationKey"] = "inventory:grom grok",
                        ["lastDumpedAt"] = 1776422695,
                        ["count"] = 1,
                        ["sharedFrom"] = "Inventory (Grom Grok)",
                        ["bagId"] = 1,
                        ["itemTypeName"] = "Furnishing",
                        ["quality"] = 3,
                        ["traitType"] = 0,
                        ["accountName"] = "@TankyOrc",
                        ["furnitureDataId"] = 1082,
                        ["firstDumpedAt"] = 1776422695,
                        ["itemKey"] = "|H0:item:116411:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||inventory:grom grok",
                        ["trait"] = "",
                        ["slotIndex"] = 3,
                        ["itemType"] = 61,
                        ["itemName"] = "Orcish Lantern, Hanging",
                        ["qualityName"] = "Superior",
                    },
                    ["|H0:item:117820:5:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||inventory:grom grok"] = 
                    {
                        ["itemLink"] = "|H0:item:117820:5:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                        ["locationKey"] = "inventory:grom grok",
                        ["lastDumpedAt"] = 1776422714,
                        ["count"] = 1,
                        ["sharedFrom"] = "Inventory (Grom Grok)",
                        ["bagId"] = 1,
                        ["itemTypeName"] = "Furnishing",
                        ["quality"] = 4,
                        ["traitType"] = 0,
                        ["accountName"] = "@TankyOrc",
                        ["furnitureDataId"] = 1339,
                        ["firstDumpedAt"] = 1776422714,
                        ["itemKey"] = "|H0:item:117820:5:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||inventory:grom grok",
                        ["trait"] = "",
                        ["slotIndex"] = 6,
                        ["itemType"] = 61,
                        ["itemName"] = "Redguard Candelabra, Polished",
                        ["qualityName"] = "Epic",
                    },
                    ["|H0:item:223161:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||inventory:grom grok"] = 
                    {
                        ["itemLink"] = "|H0:item:223161:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                        ["locationKey"] = "inventory:grom grok",
                        ["lastDumpedAt"] = 1776422751,
                        ["count"] = 1,
                        ["sharedFrom"] = "Inventory (Grom Grok)",
                        ["bagId"] = 1,
                        ["itemTypeName"] = "Furnishing",
                        ["quality"] = 3,
                        ["traitType"] = 0,
                        ["accountName"] = "@TankyOrc",
                        ["furnitureDataId"] = 11184,
                        ["firstDumpedAt"] = 1776422751,
                        ["itemKey"] = "|H0:item:223161:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||inventory:grom grok",
                        ["trait"] = "",
                        ["slotIndex"] = 9,
                        ["itemType"] = 61,
                        ["itemName"] = "Worm Cult Tongs, Metal",
                        ["qualityName"] = "Superior",
                    },
                    ["|H0:item:203234:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||bank"] = 
                    {
                        ["itemLink"] = "|H0:item:203234:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                        ["locationKey"] = "bank",
                        ["lastDumpedAt"] = 1776422833,
                        ["count"] = 1,
                        ["sharedFrom"] = "Bank",
                        ["bagId"] = 2,
                        ["itemTypeName"] = "Collectible",
                        ["quality"] = 5,
                        ["traitType"] = 0,
                        ["accountName"] = "@TankyOrc",
                        ["furnitureDataId"] = 0,
                        ["firstDumpedAt"] = 1776422833,
                        ["itemKey"] = "|H0:item:203234:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||bank",
                        ["trait"] = "",
                        ["slotIndex"] = 103,
                        ["itemType"] = 34,
                        ["itemName"] = "Style Page: Earthbone Ayleid Epaulets",
                        ["qualityName"] = "Legendary",
                    },
                    ["|H0:item:190323:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||bank"] = 
                    {
                        ["itemLink"] = "|H0:item:190323:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                        ["locationKey"] = "bank",
                        ["lastDumpedAt"] = 1776422873,
                        ["count"] = 1,
                        ["sharedFrom"] = "Bank",
                        ["bagId"] = 2,
                        ["itemTypeName"] = "Collectible",
                        ["quality"] = 5,
                        ["traitType"] = 0,
                        ["accountName"] = "@TankyOrc",
                        ["furnitureDataId"] = 0,
                        ["firstDumpedAt"] = 1776422873,
                        ["itemKey"] = "|H0:item:190323:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||bank",
                        ["trait"] = "",
                        ["slotIndex"] = 104,
                        ["itemType"] = 34,
                        ["itemName"] = "Style Page: Bonemold Pauldrons",
                        ["qualityName"] = "Legendary",
                    },
                    ["|H0:item:90193:363:50:0:0:0:0:0:0:0:0:0:0:0:0:25:0:0:0:400:0|h|h||inventory:grom grok"] = 
                    {
                        ["itemLink"] = "|H0:item:90193:363:50:0:0:0:0:0:0:0:0:0:0:0:0:25:0:0:0:400:0|h|h",
                        ["locationKey"] = "inventory:grom grok",
                        ["lastDumpedAt"] = 1776422753,
                        ["count"] = 1,
                        ["sharedFrom"] = "Inventory (Grom Grok)",
                        ["bagId"] = 1,
                        ["itemTypeName"] = "Weapon",
                        ["quality"] = 4,
                        ["traitType"] = 8,
                        ["accountName"] = "@TankyOrc",
                        ["furnitureDataId"] = 0,
                        ["firstDumpedAt"] = 1776422753,
                        ["itemKey"] = "|H0:item:90193:363:50:0:0:0:0:0:0:0:0:0:0:0:0:25:0:0:0:400:0|h|h||inventory:grom grok",
                        ["trait"] = "Decisive",
                        ["slotIndex"] = 18,
                        ["itemType"] = 1,
                        ["itemName"] = "Bow of Ancient Grace",
                        ["qualityName"] = "Epic",
                    },
                    ["|H0:item:190326:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||bank"] = 
                    {
                        ["itemLink"] = "|H0:item:190326:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                        ["locationKey"] = "bank",
                        ["lastDumpedAt"] = 1776422919,
                        ["count"] = 5,
                        ["sharedFrom"] = "Bank",
                        ["bagId"] = 2,
                        ["itemTypeName"] = "Collectible",
                        ["quality"] = 5,
                        ["traitType"] = 0,
                        ["accountName"] = "@TankyOrc",
                        ["furnitureDataId"] = 0,
                        ["firstDumpedAt"] = 1776422919,
                        ["itemKey"] = "|H0:item:190326:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||bank",
                        ["trait"] = "",
                        ["slotIndex"] = 106,
                        ["itemType"] = 34,
                        ["itemName"] = "Style Page: Bonemold Girdle",
                        ["qualityName"] = "Legendary",
                    },
                    ["|H0:item:190320:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||bank"] = 
                    {
                        ["itemLink"] = "|H0:item:190320:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                        ["locationKey"] = "bank",
                        ["lastDumpedAt"] = 1776422942,
                        ["count"] = 1,
                        ["sharedFrom"] = "Bank",
                        ["bagId"] = 2,
                        ["itemTypeName"] = "Collectible",
                        ["quality"] = 5,
                        ["traitType"] = 0,
                        ["accountName"] = "@TankyOrc",
                        ["furnitureDataId"] = 0,
                        ["firstDumpedAt"] = 1776422942,
                        ["itemKey"] = "|H0:item:190320:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||bank",
                        ["trait"] = "",
                        ["slotIndex"] = 107,
                        ["itemType"] = 34,
                        ["itemName"] = "Style Page: Bonemold Cuirass",
                        ["qualityName"] = "Legendary",
                    },
                }
            }
        }
    }
}
