FurnishThemAllData_FPacks_ForgeLordsGreatWorks = {
    name = "Forge-Lord's Great Works",
    source = "Furnishing Packs",
    collection = {
        [1] = {
            { name = "Dwarven Bench, Forged" },
            { name = "Dwarven Brazier, Open" },
            { name = "Dwarven Bust, Forge-Lord" },
            { name = "Dwarven Chandelier, Braced" },
            { name = "Dwarven Conduit, Rounded" },
            { name = "Dwarven Dais, Conduit" },
            { name = "Dwarven Frieze, Colossal Power" },
            { name = "Dwarven Frieze, Power in Twain" },
            { name = "Dwarven Frieze, Wrathstone" },
            { name = "Dwarven Gear, Large Open" },
            { name = "Dwarven Gear, Large Spokes" },
            { name = "Dwarven Gearwork, Perpetual" },
            { name = "Dwarven Hub, Sentry Wheel" },
            { name = "Dwarven Lamppost, Powered" },
            { name = "Dwarven Lamps, Heavy" },
            { name = "Dwarven Lantern, Oil" },
            { name = "Dwarven Part, Sentry Head" },
            { name = "Dwarven Platform, Fan" },
            { name = "Dwarven Rack, Spider Legs" },
            { name = "Dwarven Table, Heavy Workbench" },
            { name = "Dwarven Throne, Conduit" },
            { name = "Dwarven Valve, Sealed" },
        },
    },
}
