FurnishThemAllData_FPacks_NewLifeFestival = {
    name = "New Life Festival",
    source = "Furnishing Packs",
    collection = {
        [1] = {
            { name = "From Old Life To New" },
            { name = "Guar Ice Sculpture" },
            { name = "Lantern, Stationary" },
            { name = "Mudcrab Ice Sculpture" },
            { name = "New Life Cookies and Ale" },
            { name = "New Life Festive Fir" },
            { name = "New Life Garland" },
            { name = "New Life Garland Wreath" },
            { name = "New Life Ladle" },
            { name = "New Life Snowmortal, Argonian" },
            { name = "New Life Snowmortal, Human" },
            { name = "New Life Snowmortal, Khajiit" },
            { name = "New Life Triptych Banner" },
            { name = "Nord Candleholder, Cup" },
            { name = "Nord Chair, Lattice" },
            { name = "Nord Rug, Bearskin" },
            { name = "Nord Table, Great" },
            { name = "Snow Pile" },
            { name = "Vvardvark Ice Sculpture" },
            { name = "Winter Festival Hearth" },
            { name = "Winter Festival Hearthfire" },
            { name = "Winter Ouroboros Wreath" },
        },
    },
}
