FurnishThemAllData_FPacks_DibellasGarden = {
    name = "Dibella's Garden",
    source = "Furnishing Packs",
    collection = {
        [1] = {
            { name = "Blue Butterfly Flock" },
            { name = "Dibella's Mysteries and Revelations" },
            { name = "Dibella, Lady of Love" },
            { name = "Flower Spray, Crimson Daisies" },
            { name = "Flower Spray, Starlight Daisies" },
            { name = "Flower, Grandmother Hibiscus" },
            { name = "Flower, Lover's Lily" },
            { name = "Flowers, Midnight Glory" },
            { name = "Flowers, Midnight Sage" },
            { name = "Flowers, Red Poppy" },
            { name = "Flowers, Violet Bellflower" },
            { name = "Imperial Bench, Scrollwork" },
            { name = "Monarch Butterfly Flock" },
            { name = "Pergola, Festive Flowers" },
            { name = "Redguard Fountain, Mosaic" },
            { name = "Ritual Brazier, Gilded" },
            { name = "Ritual Stone, Dibella" },
            { name = "Seal of Dibella" },
            { name = "Tree, Argent Blue" },
            { name = "Tree, Pale Gold" },
            { name = "Vine Curtain, Festive Flowers" },
            { name = "Wildflowers, Yellow and Orange" },
        },
    },
}
