FurnishThemAllData_FPacks_KhajiitiLife = {
    name = "Khajiiti Life",
    source = "Furnishing Packs",
    collection = {
        [1] = {
            { name = "Alchemy Station" },
            { name = "Elsweyr Armchair, Low-Backed Elegant" },
            { name = "Elsweyr Bowl, Moon-Sugar" },
            { name = "Elsweyr Bucket, Wooden" },
            { name = "Elsweyr Candle, Saucer" },
            { name = "Elsweyr Cart, Moons-Blessed" },
            { name = "Elsweyr Lantern, Metal Ring" },
            { name = "Elsweyr Sugar Bowl, Gilded" },
            { name = "Elsweyr Sugar Pipe, Gilded" },
            { name = "Elsweyr Well, Simple Arched" },
            { name = "Khajiit Tent, Mercantile" },
            { name = "Moon-Sugar, Cluster" },
            { name = "Moon-Sugar, Harvested Large" },
            { name = "Moon-Sugar, Harvested Small" },
            { name = "Moon-Sugar, Row" },
            { name = "Sapphire Candlefly Gathering" },
            { name = "Straw Pile" },
            { name = "Tool, Hoe" },
            { name = "Tool, Pitchfork" },
            { name = "Tool, Plow" },
            { name = "Tool, Sickle" },
            { name = "Tool, Two-Person Crosscut Saw" },
        },
    },
}
