FurnishThemAllData_FPacks_HubalajadsFinalTreasure = {
    name = "Hubalajad's Final Treasure",
    source = "Furnishing Packs",
    collection = {
        [1] = {
            { name = "Gold Drakes, Pristine" },
            { name = "Hubalajad's Reflection" },
            { name = "In Defense of Prince Hubalajad" },
            { name = "Jar, Gilded Canopic" },
            { name = "Ra Gada Funerary Statue, Gilded Cat" },
            { name = "Ra Gada Funerary Statue, Gilded Ibis" },
            { name = "Ra Gada Funerary Statue, Gilded Servant" },
            { name = "Ra Gada Funerary Statue, Stone Cat" },
            { name = "Ra Gada Guardian Statue, Lion Ibis" },
            { name = "Ra Gada Guardian Statue, Riding Camel" },
            { name = "Ra Gada Guardian Statue, Winged Bull" },
            { name = "Ra Gada Reliquary, Miniature Palace" },
            { name = "Redguard Amphora, Gilded" },
            { name = "Redguard Bowl, Hanging Star" },
            { name = "Redguard Censer, Hanging Bell" },
            { name = "Redguard Divider, Gilded" },
            { name = "Redguard Lantern, Caged Stand" },
            { name = "Redguard Lantern, Cannister" },
            { name = "Redguard Pillow Roll, Desert Flame" },
            { name = "Redguard Pillow, Florid Flames" },
            { name = "Redguard Pillow, Lattice Flames" },
            { name = "Redguard Throw Pillow, Desert Flame" },
            { name = "Redguard Trunk, Garish" },
            { name = "Target Mournful Aegis" },
        },
    },
}
