FurnishThemAllData_FPacks_MolagBal = {
    name = "Molag Bal",
    source = "Furnishing Packs",
    collection = {
        [1] = {
            { name = "Coldharbour Compact" },
            { name = "Daedric Altar, Molag Bal" },
            { name = "Daedric Banner, Molag Bal" },
            { name = "Daedric Block, Seat" },
            { name = "Daedric Brazier, Coldharbour" },
            { name = "Daedric Brazier, Molag Bal" },
            { name = "Daedric Cage, Hanging" },
            { name = "Daedric Chain, Segment" },
            { name = "Daedric Chains, Hanging" },
            { name = "Daedric Doorway, Spiked" },
            { name = "Daedric Fence, Section" },
            { name = "Daedric Fragment, Coldharbour" },
            { name = "Daedric Pennant, Molag Bal" },
            { name = "Daedric Sconce, Molag Bal" },
            { name = "Daedric Shards, Coldharbour" },
            { name = "Daedric Spout, Arched" },
            { name = "Daedric Spout, Block" },
            { name = "Daedric Tapestry, Molag Bal" },
            { name = "Daedric Torch, Coldharbour" },
            { name = "Daedric Torture Device, Chained" },
            { name = "Seal of Molag Bal, Grand" },
            { name = "Soul Gem, Single" },
            { name = "Soul Gems, Pile" },
            { name = "Soul Gems, Scattered" },
            { name = "Soul-Shriven, Armored" },
            { name = "Soul-Shriven, Robed" },
            { name = "Statue of Molag Bal, God of Schemes" },
        },
    },
}
