FurnishThemAllData_FPacks_WitchesCoven = {
    name = "Witches' Coven",
    source = "Furnishing Packs",
    collection = {
        [1] = {
            { name = "Carcass, Hanging Deer" },
            { name = "Fogs of the Hag Fen" },
            { name = "Hagraven Altar, Alchemical" },
            { name = "Hagraven Cauldron, Ritual" },
            { name = "Hagraven Totem, Skull" },
            { name = "Log, Fallen Pine" },
            { name = "Log, Rotten Bog" },
            { name = "Mists of the Hag Fen" },
            { name = "Reachmen Cage, Sturdy" },
            { name = "Reachmen Rug, Mottled Skin" },
            { name = "Reachmen Rug, Smooth Skin" },
            { name = "Skulls, Heap" },
            { name = "Stump, Mossy Cypress" },
            { name = "Stump, Wretched Cypress" },
            { name = "The Witches of Hag Fen" },
            { name = "Tree, Fetid Cypress" },
            { name = "Tree, Wretched Cypress" },
            { name = "Witches Totem, Antler Charms" },
            { name = "Witches' Basin, Scrying" },
            { name = "Witches' Brazier, Beast Skull" },
            { name = "Witches' Cauldron, Provisioning" },
            { name = "Witches' Tent, Lean-To" },
        },
    },
}
