-- SPDX-FileCopyrightText: 2025 m00nyONE
-- SPDX-License-Identifier: Artistic-2.0

local lib_name = "LibCustomIcons"
local lib = _G[lib_name]
local s = lib.GetStaticTable()
local a = lib.GetAnimatedTable()

s["@Kustana"] = "LibCustomIcons/icons/misc4/kustana.dds"
s["@Muranache"] = "LibCustomIcons/icons/misc4/muranache3.dds"
s["@Teias"] = "LibCustomIcons/icons/misc4/teias.dds"
s["@GrafCadoroc"] = "LibCustomIcons/icons/misc4/grafcadoroc.dds"
s["@Lord_Termy"] = "LibCustomIcons/icons/misc4/lordtermy.dds"
s["@Milanymeria"] = "LibCustomIcons/icons/misc4/milanymeria.dds"
s["@Twister12304"] = "LibCustomIcons/icons/misc4/twister12304.dds"
s["@supersonic_kitten"] = "LibCustomIcons/icons/misc4/supersonickitten.dds"
s["@Ms.Razan"] = "LibCustomIcons/icons/misc4/msrazan.dds"
s["@MissDate"] = "LibCustomIcons/icons/misc4/missdate.dds"
s["@SorinThePenguin"] = "LibCustomIcons/icons/misc4/sorinthepenguin.dds"
s["@Hardog"] = "LibCustomIcons/icons/misc4/hardog.dds"
s["@BeckieMA"] = "LibCustomIcons/icons/misc4/beckiema.dds"
s["@Northknightwest"] = "LibCustomIcons/icons/misc4/Northknightwest_2.dds"
s["@Bananananananana"] = "LibCustomIcons/icons/misc4/bananananananana.dds"
s["@Maeana"] = "LibCustomIcons/icons/misc4/maeana.dds"
s["@Andy_Fr"] = "LibCustomIcons/icons/misc4/andyfr.dds"
s["@Pax_03"] = "LibCustomIcons/icons/misc4/pax03.dds"
s["@Inbeingincap"] = "LibCustomIcons/icons/misc4/Inbeingincap_4.dds"
s["@Kuroi61"] = "LibCustomIcons/icons/misc4/kuroi61.dds"
s["@Dova-Craft"] = "LibCustomIcons/icons/misc4/dovacraft.dds"
s["@Trohaniel"] = "LibCustomIcons/icons/misc4/trohaniel.dds"
s["@JorgirdMossyflame"] = "LibCustomIcons/icons/misc4/JorgirdMossyflame.dds"
s["@mychaelo"] = "LibCustomIcons/icons/misc4/mychaelo.dds"
s["@Dovavivavi"] = "LibCustomIcons/icons/misc4/dovavivavi.dds"
s["@Ironman1908"] = "LibCustomIcons/icons/misc4/ironman1908.dds"
s["@olegmongol"] = "LibCustomIcons/icons/misc4/olegmongol.dds"
s["@I_Buurrr"] = "LibCustomIcons/icons/misc4/ibuurrr.dds"
s["@CelesteLion"] = "LibCustomIcons/icons/misc4/sekhlou1se.dds"
s["@Indra_oo"] = "LibCustomIcons/icons/misc4/yourdoll2.dds"
s["@Monweel"] = "LibCustomIcons/icons/misc4/monweel_2.dds"
s["@FluidEmbers"] = "LibCustomIcons/icons/misc4/fluidembers.dds"
s["@Rhicarde"] = "LibCustomIcons/icons/misc4/rhicarde.dds"
s["@Stig_Bloom"] = "LibCustomIcons/icons/misc4/stigbloom.dds"
s["@Chance-16"] = "LibCustomIcons/icons/misc4/chance16.dds"
s["@MarkoPoelo"] = "LibCustomIcons/icons/misc4/markopoelo.dds"
s["@mothfell"] = "LibCustomIcons/icons/misc4/mothfell.dds"
s["@Shiro-yasha"] = "LibCustomIcons/icons/misc4/shiroyasha.dds"
s["@MasterHerzog"] = "LibCustomIcons/icons/misc4/masterherzog3.dds"
s["@HumanNature"] = "LibCustomIcons/icons/misc4/humannature.dds"
s["@Leevii"] = "LibCustomIcons/icons/misc4/leevii.dds"
s["@Coleypie"] = "LibCustomIcons/icons/misc4/coleypie.dds"
s["@PrinceAngy"] = "LibCustomIcons/icons/misc4/princeangy.dds"
s["@joemcallister"] = "LibCustomIcons/icons/misc4/joemcallister.dds"
s["@ardick"] = "LibCustomIcons/icons/misc4/ardick.dds"
s["@Emblem13235"] = "LibCustomIcons/icons/misc4/emblem132352.dds"
s["@Greviodas"] = "LibCustomIcons/icons/misc4/greviodas.dds"
s["@Knorrmeister"] = "LibCustomIcons/icons/misc4/knorrmeister.dds"
s["@RatherBeEIsweyr"] = "LibCustomIcons/icons/misc4/ratherbeeisweyr.dds"
s["@kiirdan"] = "LibCustomIcons/icons/misc4/kiirdan.dds"
s["@TurkALicious"] = "LibCustomIcons/icons/misc4/turkalicious.dds"
s["@SoIitude"] = "LibCustomIcons/icons/misc4/soiitude.dds"
s["@IzzyLegendESO"] = "LibCustomIcons/icons/misc4/izzylegendeso.dds"
s["@ElRojoBlanco"] = "LibCustomIcons/icons/misc4/elrojoblanco.dds"
s["@fcliverpoolfc8"] = "LibCustomIcons/icons/misc4/fcliverpoolfc8.dds"
s["@BigESO"] = "LibCustomIcons/icons/misc4/rachalia.dds"
s["@MediumESO"] = "LibCustomIcons/icons/misc4/kinglemonpop.dds"
s["@Voxei"] = "LibCustomIcons/icons/misc4/voxei.dds"
s["@BlueDremora"] = "LibCustomIcons/icons/misc4/bluedremora.dds"
s["@sepleen"] = "LibCustomIcons/icons/misc4/sepleen.dds"
s["@SpexxarN"] = "LibCustomIcons/icons/misc4/spexxarn.dds"
s["@Etherealys"] = "LibCustomIcons/icons/misc4/ethereal.dds"
s["@Arvendir"] = "LibCustomIcons/icons/misc4/arvendir.dds"
s["@Sand_Bat"] = "LibCustomIcons/icons/misc4/sandbat2.dds"
s["@Veskim"] = "LibCustomIcons/icons/misc4/veskim.dds"
s["@Bora-S"] = "LibCustomIcons/icons/misc4/boras.dds"
s["@Kùßù"] = "LibCustomIcons/icons/misc4/kubu5.dds"
s["@KingKufo"] = "LibCustomIcons/icons/misc4/kingkufo.dds"
s["@PizzaHeart"] = "LibCustomIcons/icons/misc4/pizzaheart.dds"
s["@Hircules"] = "LibCustomIcons/icons/misc4/hircules.dds"
s["@Dörtydört"] = "LibCustomIcons/icons/misc4/dortydort.dds"
s["@MFerro"] = "LibCustomIcons/icons/misc4/mferro.dds"
s["@Dovahkir"] = "LibCustomIcons/icons/misc4/dovahkir.dds"
s["@Avieee"] = "LibCustomIcons/icons/misc4/avieee.dds"
s["@Vuur_Draakje"] = "LibCustomIcons/icons/misc2/joetotale.dds"
s["@KingFakeFox"] = "LibCustomIcons/icons/misc4/kingfakefox.dds"
s["@B1ghorse"] = "LibCustomIcons/icons/misc4/B1ghorse.dds"
s["@Fretzbreak95"] = "LibCustomIcons/icons/misc4/fretzbreak95.dds"
s["@Roberto000"] = "LibCustomIcons/icons/misc4/roberto000.dds"
s["@HadWat595"] = "LibCustomIcons/icons/misc4/hadwat595.dds"
s["@karo57"] = "LibCustomIcons/icons/misc4/karo57.dds"
s["@MonteVex"] = "LibCustomIcons/icons/misc4/montevex2.dds"
s["@Tipareth"] = "LibCustomIcons/icons/misc4/tipareth.dds"
s["@Brookleym"] = "LibCustomIcons/icons/misc4/brookleym.dds"
s["@v33n4"] = "LibCustomIcons/icons/misc4/v33n4.dds"
s["@Sunomer"] = "LibCustomIcons/icons/misc4/sunomer.dds"
s["@The_Flagbearer"] = "LibCustomIcons/icons/misc4/theflagbearer.dds"
s["@Jennasaurus"] = "LibCustomIcons/icons/misc4/jennasaurus.dds"
s["@Carsios"] = "LibCustomIcons/icons/misc4/carsios.dds"
s["@Aluure"] = "LibCustomIcons/icons/misc4/Aluure.dds"
s["@Xerodom"] = "LibCustomIcons/icons/misc4/xerodom.dds"
s["@LaurenKittie"] = "LibCustomIcons/icons/misc4/laurenkittie.dds"
s["@valenandia"] = "LibCustomIcons/icons/misc4/valenandia.dds"
s["@Lunaria19"] = "LibCustomIcons/icons/misc4/lunaria19.dds"
s["@Vizuhnari"] = "LibCustomIcons/icons/misc4/vizuhnari.dds"
s["@SmokeScrollS"] = "LibCustomIcons/icons/misc4/smokescrolls.dds"
s["@ilazim"] = "LibCustomIcons/icons/misc4/ilazim.dds"
s["@b.green"] = "LibCustomIcons/icons/misc4/bgreen.dds"
s["@HorAig9000"] = "LibCustomIcons/icons/misc4/horaig9000.dds"
s["@Klixse"] = "LibCustomIcons/icons/misc4/klixse.dds"
s["@Prionyx"] = "LibCustomIcons/icons/misc4/prionyx.dds"
s["@Rubynoof"] = "LibCustomIcons/icons/misc4/rubynoof.dds"
s["@Missvyxen"] = "LibCustomIcons/icons/misc4/missvyxen.dds"
s["@BigPoppaRedux"] = "LibCustomIcons/icons/misc4/bigpopparedux.dds"
s["@Navagod"] = "LibCustomIcons/icons/misc4/Navagod.dds"
s["@Gorni_orelchik"] = "LibCustomIcons/icons/misc4/gorniorelchik.dds"
s["@Khulstai"] = "LibCustomIcons/icons/misc4/khulstai.dds"
s["@Warcked"] = "LibCustomIcons/icons/misc4/warcked.dds"
s["@Raly.K"] = "LibCustomIcons/icons/misc4/ralyktop2.dds"
s["@Lucas_954"] = "LibCustomIcons/icons/misc4/lucas954.dds"
s["@pochiexd"] = "LibCustomIcons/icons/misc4/pochiexd.dds"
s["@PostLemon"] = "LibCustomIcons/icons/misc4/postlemon.dds"
s["@mrnoodle1"] = "LibCustomIcons/icons/misc4/mrnoodle1.dds"
s["@TheHarty"] = "LibCustomIcons/icons/misc4/TheHarty.dds"
s["@SgtGranite"] = "LibCustomIcons/icons/misc4/sgtgranite.dds"
s["@madmax36185"] = "LibCustomIcons/icons/misc4/madmax36185.dds"
s["@Ghost_77"] = "LibCustomIcons/icons/misc4/ghost77.dds"
s["@Alafin"] = "LibCustomIcons/icons/misc4/alafin.dds"
s["@paskaparta"] = "LibCustomIcons/icons/misc4/paskaparta.dds"
s["@HeiKyoma"] = "LibCustomIcons/icons/misc4/HeiKyoma_2.dds"
s["@BaneofBones"] = "LibCustomIcons/icons/misc4/baneofbones.dds"
s["@gamebreaker90"] = "LibCustomIcons/icons/misc4/gamebreaker90.dds"
s["@Corrupt-Paragon"] = "LibCustomIcons/icons/misc4/corruptparagon.dds"
s["@peachesandtoes"] = "LibCustomIcons/icons/misc4/peachesandtoes.dds"
s["@Nirain"] = "LibCustomIcons/icons/misc4/Nirain2.dds"
s["@Jiiimmmyy"] = "LibCustomIcons/icons/misc4/jiiimmmyy.dds"
s["@Rated's_Online"] = "LibCustomIcons/icons/misc4/ratedsonline.dds"
s["@Avientia"] = "LibCustomIcons/icons/misc4/avientia.dds"
s["@CaptnCloud"] = "LibCustomIcons/icons/misc4/captncloud.dds"
s["@DarthODanO"] = "LibCustomIcons/icons/misc4/darthodano.dds"
s["@Orouborous"] = "LibCustomIcons/icons/misc4/orouborous.dds"
s["@bumbleVee"] = "LibCustomIcons/icons/misc4/hollowvoluminous.dds"
s["@thirtyfreak"] = "LibCustomIcons/icons/misc4/thirtyfreak.dds"
s["@Seelenloser898"] = "LibCustomIcons/icons/misc4/seelenloser898.dds"
s["@Jowobaby"] = "LibCustomIcons/icons/misc4/jowobaby.dds"
s["@Vannessee"] = "LibCustomIcons/icons/misc4/vannessee.dds"
s["@pæp"] = "LibCustomIcons/icons/misc4/paep.dds"
s["@satanzeref"] = "LibCustomIcons/icons/misc4/satanzeref.dds"
s["@Staslytvyn"] = "LibCustomIcons/icons/misc4/staslytvyn.dds"
s["@NVNNN2"] = "LibCustomIcons/icons/misc4/NVNNN2.dds"
s["@ShadyTheLady"] = "LibCustomIcons/icons/misc4/shadythelady.dds"
s["@Selegnar"] = "LibCustomIcons/icons/misc4/selegnar.dds"
s["@ShadowIgni"] = "LibCustomIcons/icons/misc4/shadowigni.dds"
s["@Umbro100"] = "LibCustomIcons/icons/misc4/umbro100.dds"
s["@Ar4ybald"] = "LibCustomIcons/icons/misc4/ar4ybald.dds"
s["@Kitsune_Tsuki"] = "LibCustomIcons/icons/misc4/Kitsune_Tsuki.dds"
s["@adogatemyleg"] = "LibCustomIcons/icons/misc4/adogatemyleg.dds"
s["@WhoDatDere"] = "LibCustomIcons/icons/misc4/whodatdere4.dds"
s["@xbrightknee"] = "LibCustomIcons/icons/misc4/xbrightknee.dds"
s["@foulars"] = "LibCustomIcons/icons/misc4/foulars.dds"
s["@Alemini"] = "LibCustomIcons/icons/misc4/alemini.dds"
s["@Alue61"] = "LibCustomIcons/icons/misc4/alue61.dds"
s["@AlcoSorcerer"] = "LibCustomIcons/icons/misc4/alcosorcerer.dds"
s["@September_sky"] = "LibCustomIcons/icons/misc4/septembersky.dds"
s["@Smilemoous"] = "LibCustomIcons/icons/misc4/smilemoous.dds"
s["@KillerBunny1"] = "LibCustomIcons/icons/misc4/dragonslayerxvi.dds"
s["@Se.na"] = "LibCustomIcons/icons/misc4/sena.dds"
s["@Warsore_RH"] = "LibCustomIcons/icons/misc4/warsorerh.dds"
s["@Chicoplüsch"] = "LibCustomIcons/icons/misc4/chicoplusch.dds"
s["@Akari_UA"] = "LibCustomIcons/icons/misc4/Akari_UA.dds"
s["@BigHerek"] = "LibCustomIcons/icons/misc4/bigherek.dds"
s["@Pickle2689"] = "LibCustomIcons/icons/misc4/pickle2689.dds"
s["@Zebio22"] = "LibCustomIcons/icons/misc4/zebio22.dds"
s["@KittyPK"] = "LibCustomIcons/icons/misc4/KittyPK_2.dds"
s["@DaakuFuremuMasutaa"] = "LibCustomIcons/icons/misc4/daakufuremumasutaa.dds"
s["@Cyandris"] = "LibCustomIcons/icons/misc4/cyandris.dds"
s["@Lellandra"] = "LibCustomIcons/icons/misc4/Lellandra3.dds"
s["@Dena_snk"] = "LibCustomIcons/icons/misc4/denasnk2.dds"
s["@nmgupta"] = "LibCustomIcons/icons/misc4/nmgupta.dds"
s["@Eithrial"] = "LibCustomIcons/icons/misc4/eithrial.dds"
s["@Buddha_Slapz"] = "LibCustomIcons/icons/misc4/buddhaslapz.dds"
s["@jormax"] = "LibCustomIcons/icons/misc4/jormax.dds"
s["@jammyjess"] = "LibCustomIcons/icons/misc4/jammyjess.dds"
s["@Umbralescent"] = "LibCustomIcons/icons/misc4/umbralescent.dds"
s["@Boulvai77"] = "LibCustomIcons/icons/misc4/boulvai77.dds"
s["@Rinchin"] = "LibCustomIcons/icons/misc4/rinchin.dds"
s["@Tefish"] = "LibCustomIcons/icons/misc4/tefish.dds"
s["@nfkwayne"] = "LibCustomIcons/icons/misc4/nfkwayne2.dds"
s["@ArchAngelCass"] = "LibCustomIcons/icons/misc4/ArchAngelCass_2.dds"
s["@ArvelanESO"] = "LibCustomIcons/icons/misc4/arvelaneso.dds"
s["@DL23"] = "LibCustomIcons/icons/misc4/dl23.dds"
s["@Sirrom1323"] = "LibCustomIcons/icons/misc4/sirrom1323.dds"
s["@RedHuskyVII"] = "LibCustomIcons/icons/misc4/redhuskyvii.dds"
s["@Vanderfeld"] = "LibCustomIcons/icons/misc4/vanderfeld.dds"
s["@Sinclere"] = "LibCustomIcons/icons/misc4/sinclere.dds"
s["@DarthLycaeon"] = "LibCustomIcons/icons/misc4/darthlycaeon.dds"
s["@AlkarionLP"] = "LibCustomIcons/icons/misc4/alkarionlp.dds"
s["@Wlar0xz"] = "LibCustomIcons/icons/misc4/wlar0xz.dds"
s["@Master_Cris"] = "LibCustomIcons/icons/misc4/mastercris.dds"
s["@Smoke999"] = "LibCustomIcons/icons/misc4/smoke999.dds"
s["@maitre-fu"] = "LibCustomIcons/icons/misc4/maitrefu.dds"
s["@BlackRoseBlooms"] = "LibCustomIcons/icons/misc4/blackroseblooms.dds"
s["@Drake-1"] = "LibCustomIcons/icons/misc4/drake1.dds"
s["@prollynate"] = "LibCustomIcons/icons/misc4/prollynate.dds"
s["@DejaVuDetroit"] = "LibCustomIcons/icons/misc4/dejavudetroit.dds"
s["@ArkansasFive"] = "LibCustomIcons/icons/misc4/arkansasfive.dds"
s["@Minartus"] = "LibCustomIcons/icons/misc4/minartus.dds"
s["@Lirri"] = "LibCustomIcons/icons/misc4/lirri3.dds"
s["@HelgaWindshield"] = "LibCustomIcons/icons/misc4/helgawindshield.dds"
s["@Santaniko"] = "LibCustomIcons/icons/misc4/santaniko.dds"
s["@Aquos"] = "LibCustomIcons/icons/misc4/aquos2.dds"
s["@ARRIUSL"] = "LibCustomIcons/icons/misc4/arriusl.dds"
s["@PulseFour"] = "LibCustomIcons/icons/misc4/pulsefour.dds"
s["@kilgrxves"] = "LibCustomIcons/icons/misc4/kilgrxves.dds"
s["@The_Sucsubot"] = "LibCustomIcons/icons/misc4/thesucsubot.dds"
s["@anotherTimeWizard"] = "LibCustomIcons/icons/misc4/joyfullyordinary.dds"
s["@JoyfullyOrdinary"] = s["@anotherTimeWizard"]
s["@FlawedResolve"] = "LibCustomIcons/icons/misc4/flawedresolve.dds"
s["@manubilo"] = "LibCustomIcons/icons/misc4/manubilo.dds"
s["@kithit"] = "LibCustomIcons/icons/misc4/kithit.dds"
s["@Comparer1991"] = "LibCustomIcons/icons/misc4/comparer1991.dds"
s["@nirntrotter"] = "LibCustomIcons/icons/misc4/nirntrotter.dds"
s["@SIushy"] = "LibCustomIcons/icons/misc4/siushy.dds"
s["@Fockee"] = "LibCustomIcons/icons/misc4/fockee.dds"
s["@Ryu9"] = "LibCustomIcons/icons/misc4/Nantick_3.dds"
s["@SatanLord"] = "LibCustomIcons/icons/misc4/satanlord.dds"
s["@Valaky"] = "LibCustomIcons/icons/misc4/valaky.dds"
s["@Wood_boy"] = "LibCustomIcons/icons/misc4/woodboy.dds"
s["@DOABatman"] = "LibCustomIcons/icons/misc4/doabatman.dds"
s["@LordProtocolypse"] = "LibCustomIcons/icons/misc4/lordprotocolypse.dds"
s["@Livien"] = "LibCustomIcons/icons/misc4/livien.dds"
s["@Isenbrand"] = "LibCustomIcons/icons/misc4/isenbrand.dds"
s["@TheSeaOrphan"] = "LibCustomIcons/icons/misc4/theseaorphan.dds"
s["@PhoenixSwashbuckler"] = "LibCustomIcons/icons/misc4/PhoenixSwashbuckler.dds"
s["@lGroovyl"] = "LibCustomIcons/icons/misc4/lgroovyl.dds"
s["@donanoca"] = "LibCustomIcons/icons/misc4/donanoca.dds"
s["@AvantoMusic"] = "LibCustomIcons/icons/misc4/avantomusic.dds"
s["@Dromgrin"] = "LibCustomIcons/icons/misc4/dromgrin.dds"
s["@IvySparrow"] = "LibCustomIcons/icons/misc4/ivysparrow.dds"
s["@Aashiana"] = "LibCustomIcons/icons/misc4/aashiana.dds"
s["@RedMacil"] = "LibCustomIcons/icons/misc4/redmacil.dds"
s["@ALYSLAYED"] = "LibCustomIcons/icons/misc4/alyslayed.dds"
s["@mayun"] = "LibCustomIcons/icons/misc4/mayun.dds"
s["@Zerodead_1"] = "LibCustomIcons/icons/misc4/zerodead1.dds"
s["@Meekology"] = "LibCustomIcons/icons/misc4/meekology.dds"
s["@Polska_1999"] = "LibCustomIcons/icons/misc4/polska1999.dds"
s["@Devatz"] = "LibCustomIcons/icons/misc4/devatz.dds"
s["@Is'ya"] = "LibCustomIcons/icons/misc4/Isya_2.dds"
s["@Tumsalin"] = "LibCustomIcons/icons/misc4/tumsalin.dds"
s["@Bilberi"] = "LibCustomIcons/icons/misc4/bilberi.dds"
s["@mctuja"] = "LibCustomIcons/icons/misc4/mctuja.dds"
s["@Malevolence666"] = "LibCustomIcons/icons/misc4/malevolence666.dds"
s["@Jeezyx"] = "LibCustomIcons/icons/misc4/jeezyx.dds"
s["@Taufrin"] = "LibCustomIcons/icons/misc4/taufrin2.dds"
s["@R1VA"] = "LibCustomIcons/icons/misc4/r1va2.dds"
s["@R1mm"] = "LibCustomIcons/icons/misc4/r1mm.dds"
s["@MandragoraBela"] = "LibCustomIcons/icons/misc4/mandragorabela.dds"
s["@Tasks"] = "LibCustomIcons/icons/misc4/tasks.dds"
s["@Patchedelix"] = "LibCustomIcons/icons/misc4/patchedelix.dds"
s["@EngRayan"] = "LibCustomIcons/icons/misc4/engrayan.dds"
s["@ToxicKitty135"] = "LibCustomIcons/icons/misc4/toxickitty135.dds"
s["@Viraz"] = "LibCustomIcons/icons/misc4/viraz.dds"
s["@Evgen_ok"] = "LibCustomIcons/icons/misc4/evgenok.dds"
s["@mgsnakes"] = "LibCustomIcons/icons/misc4/mgsnakes2.dds"
s["@mcload64"] = "LibCustomIcons/icons/misc4/mcload64.dds"
s["@CrocoAce"] = "LibCustomIcons/icons/misc4/crocoace.dds"
s["@xDesertKillerx"] = "LibCustomIcons/icons/misc4/xdesertkillerx.dds"
s["@Telaris"] = "LibCustomIcons/icons/misc4/telaris.dds"
s["@denzocca"] = "LibCustomIcons/icons/misc4/denzocca.dds"
s["@Endrex"] = "LibCustomIcons/icons/misc4/endrex.dds"
s["@DExRxEK"] = "LibCustomIcons/icons/misc4/dexrxek.dds"
s["@RyPie"] = "LibCustomIcons/icons/misc4/rypie.dds"
s["@Chalmes"] = "LibCustomIcons/icons/misc4/chalmes.dds"
s["@Kermudgen"] = "LibCustomIcons/icons/misc4/kermudgen.dds"
s["@emerald648"] = "LibCustomIcons/icons/misc4/emerald648.dds"
s["@TheDragonReborn96"] = "LibCustomIcons/icons/misc4/thedragonreborn96.dds"
s["@Branddi"] = "LibCustomIcons/icons/misc4/branddi.dds"
s["@Jaylin"] = "LibCustomIcons/icons/misc4/jaylin.dds"
s["@T.agg"] = "LibCustomIcons/icons/misc4/tagg.dds"
s["@LyamX"] = "LibCustomIcons/icons/misc4/lyamx.dds"
s["@Asklepious"] = "LibCustomIcons/icons/misc4/asklepious.dds"
s["@Amazake"] = "LibCustomIcons/icons/misc4/amazake.dds"
s["@Moonay"] = "LibCustomIcons/icons/misc4/Moonay.dds"
s["@MireyCylus"] = "LibCustomIcons/icons/misc4/mireycylus.dds"
s["@jeddy87"] = "LibCustomIcons/icons/misc4/jeddy87.dds"
s["@ArjunaBela"] = "LibCustomIcons/icons/misc4/arjunabela.dds"
s["@Mythical_void"] = "LibCustomIcons/icons/misc4/mythicalvoid.dds"
s["@wittor"] = "LibCustomIcons/icons/misc4/wittor.dds"
s["@NeverKillMePleb"] = "LibCustomIcons/icons/misc4/neverkillmepleb.dds"
s["@Alykace"] = "LibCustomIcons/icons/misc4/alykace.dds"
s["@MrEllander"] = "LibCustomIcons/icons/misc4/mrellander.dds"
s["@KeyRea1"] = "LibCustomIcons/icons/misc4/keyrea1.dds"
s["@Slyjock"] = "LibCustomIcons/icons/misc4/slyjock.dds"
s["@Cortanaa"] = "LibCustomIcons/icons/misc4/cortanaa.dds"
s["@vrayni"] = "LibCustomIcons/icons/misc4/vrayni.dds"
s["@Sinbann"] = "LibCustomIcons/icons/misc4/sinbann.dds"
s["@Infinite_Light"] = "LibCustomIcons/icons/misc4/infinitelight.dds"
s["@Gorkamunda"] = "LibCustomIcons/icons/misc4/gorkamunda.dds"
s["@Vaiyas"] = "LibCustomIcons/icons/misc4/vaiyas.dds"
s["@Morgo'th"] = "LibCustomIcons/icons/misc4/morgoth.dds"
s["@BartLampard"] = "LibCustomIcons/icons/misc4/bartlampard.dds"
s["@Sanqualiz"] = "LibCustomIcons/icons/misc4/sanqualiz.dds"
s["@mr.hellfirefox"] = "LibCustomIcons/icons/misc4/mrhellfirefox.dds"
s["@adipose_world"] = "LibCustomIcons/icons/misc4/adiposeworld.dds"
s["@Mylittleloser"] = "LibCustomIcons/icons/misc4/mylittleloser.dds"
s["@kristyy"] = "LibCustomIcons/icons/misc4/kristyy.dds"
s["@NievesWolters"] = "LibCustomIcons/icons/misc4/nieveswolters.dds"
s["@Hiroshi_FR"] = "LibCustomIcons/icons/misc4/hiroshifr.dds"
s["@serana'sdragonborn"] = "LibCustomIcons/icons/misc4/seranasdragonborn.dds"
s["@Nef-TilTmachine"] = "LibCustomIcons/icons/misc4/neftiltmachine.dds"
s["@pakozh"] = "LibCustomIcons/icons/misc4/pakozh.dds"
s["@Ezhh"] = "LibCustomIcons/icons/misc4/ezhh.dds"
s["@d3v1ld0g0321"] = "LibCustomIcons/icons/misc4/d3v1ld0g0321.dds"
s["@Otrocious"] = "LibCustomIcons/icons/misc4/Otrocious1.dds"
s["@BuddhaForMe"] = "LibCustomIcons/icons/misc4/buddhaforme.dds"
s["@purrsutsu"] = "LibCustomIcons/icons/misc4/purrsutsu.dds"
s["@RedKialandi"] = "LibCustomIcons/icons/misc4/redkialandi.dds"
s["@Ianous1"] = "LibCustomIcons/icons/misc4/ianous1.dds"
s["@TimShutDown"] = "LibCustomIcons/icons/misc4/timshutdown.dds"
s["@oTomeii"] = "LibCustomIcons/icons/misc4/otomeii.dds"
s["@Dreqin"] = "LibCustomIcons/icons/misc4/dreqin.dds"
s["@Symbolseka"] = "LibCustomIcons/icons/misc4/symbolseka.dds"
s["@boom456987"] = "LibCustomIcons/icons/misc4/boom456987.dds"
s["@N8xMYSTk"] = "LibCustomIcons/icons/misc4/n8xmystk.dds"
s["@DaedricDoge"] = "LibCustomIcons/icons/misc4/daedricdoge.dds"
s["@the-postminimalist"] = "LibCustomIcons/icons/misc4/thepostminimalist.dds"
s["@XxMadChaosxX"] = "LibCustomIcons/icons/misc4/xxmadchaosxx.dds"
s["@Ailyuiaire"] = "LibCustomIcons/icons/misc4/ailyuiaire.dds"
s["@Cellyz"] = "LibCustomIcons/icons/misc4/cellyz.dds"
s["@Nolvenn_Oreyn"] = "LibCustomIcons/icons/misc4/nolvennoreyn.dds"
s["@Miho0119"] = "LibCustomIcons/icons/misc4/miho0119.dds"
s["@Mokona_Smiles"] = "LibCustomIcons/icons/misc4/mokonasmiles.dds"
s["@LionLN"] = "LibCustomIcons/icons/misc4/lionln.dds"
s["@Welshea"] = "LibCustomIcons/icons/misc4/welshea.dds"
s["@Shad'rell"] = "LibCustomIcons/icons/misc4/shadrell.dds"
a["@Shiro-yasha"] = {"LibCustomIcons/icons/misc4/Shiro-yasha_anim4.dds", 6, 6, 10}
a["@Veli'Dreth"] = {"LibCustomIcons/icons/misc4/ZadrithMora_anim.dds", 13, 1, 15}
a["@Arcykaplan_Beliara"] = {"LibCustomIcons/icons/misc4/Arcykaplan_Beliara_anim.dds", 6, 4, 30}
a["@Navagod"] = {"LibCustomIcons/icons/misc4/Navagod_anim.dds", 7, 4, 21}
a["@JungleDiff"] = {"LibCustomIcons/icons/misc4/JungleDiff_anim.dds", 7, 7, 33}
a["@schwarzes.fleisch"] = {"LibCustomIcons/icons/misc4/schwarzesfleisch_anim.dds", 35, 1, 25}
a["@xMasuto"] = {"LibCustomIcons/icons/misc4/xMasuto_anim2.dds", 10, 1, 20}
a["@varitasurby"] = {"LibCustomIcons/icons/misc4/varitasurby_anim.dds", 9, 1, 25}
a["@NeonFoxy"] = {"LibCustomIcons/icons/misc4/NeonFoxy_anim_3.dds", 10, 1, 17}
a["@OakparkIsRight"] = {"LibCustomIcons/icons/misc4/oakparkisright_anim.dds", 10, 5, 10}
a["@bradydjf"] = {"LibCustomIcons/icons/misc4/bradydjf_anim3.dds", 7, 5, 3.5}
a["@AccounttNotFound"] = {"LibCustomIcons/icons/misc4/AccounttNotFound_anim.dds", 15, 1, 23}
a["@IChandlerI"] = {"LibCustomIcons/icons/misc4/IChandlerI_anim.dds", 15, 1, 23}
a["@theLEERest"] = {"LibCustomIcons/icons/misc4/theLEERest_anim.dds", 10, 2, 9}
a["@Maba1905"] = {"LibCustomIcons/icons/misc4/Maba1905_anim.dds", 6, 2, 15}
a["@wallychamp94"] = {"LibCustomIcons/icons/misc4/wallychamp94_anim.dds", 33, 1, 14}
a["@Naira.Nyx"] = {"LibCustomIcons/icons/misc4/nairanyx_anim2.dds", 41, 1, 25}
a["@Sir_andres"] = {"LibCustomIcons/icons/misc4/sirandres_anim.dds", 40, 1, 8}
a["@Altaryxa"] = {"LibCustomIcons/icons/misc4/altaryxa_anim.dds", 40, 1, 33}
a["@Lunaria19"] = {"LibCustomIcons/icons/misc4/lunaria19_anim.dds", 7, 1, 10}
a["@Hades-_Vengeance"] = {"LibCustomIcons/icons/misc4/hadesvengeance_anim.dds", 13, 1, 9}
a["@NotiFizzE"] = {"LibCustomIcons/icons/misc4/notifizze_anim.dds", 5, 1, 10}
a["@ReliaBlackFang"] = {"LibCustomIcons/icons/misc4/reliablackfang_anim.dds", 12, 1, 10}
a["@RomainFanDeLaim"] = {"LibCustomIcons/icons/misc4/romainfandelaim_anim3.dds", 7, 1, 11}
a["@phandfield"] = {"LibCustomIcons/icons/misc4/phandfield_anim.dds", 8, 1, 4}
a["@Varkeniz"] = {"LibCustomIcons/icons/misc4/varkeniz_anim.dds", 46, 1, 14}
a["@Shalltear9"] = {"LibCustomIcons/icons/misc4/shalltear9_anim.dds", 49, 1, 14}
a["@VeRelBilndog"] = {"LibCustomIcons/icons/misc4/verelbilndog_anim.dds", 10, 5, 10}
a["@Previsible"] = {"LibCustomIcons/icons/misc4/previsible_anim.dds", 47, 1, 14}
a["@deathixi"] = {"LibCustomIcons/icons/misc4/deathixi_anim.dds", 47, 1, 25}
a["@Frost769"] = {"LibCustomIcons/icons/misc4/frost769_anim.dds", 38, 1, 33}
a["@SyrupSamich"] = {"LibCustomIcons/icons/misc4/SyrupSamich_anim.dds", 8, 1, 20}
a["@ZillaBird"] = {"LibCustomIcons/icons/misc4/zillabird_anim2.dds", 16, 1, 10}
a["@LyamX"] = {"LibCustomIcons/icons/misc4/lyamx_anim.dds", 9, 1, 14}
a["@dukeofdarkness11"] = {"LibCustomIcons/icons/misc4/dukeofdarkness11_anim2.dds", 30, 1, 10}
a["@KaggIes"] = {"LibCustomIcons/icons/misc4/kaggies_anim.dds", 5, 1, 11}
a["@ItsXin"] = {"LibCustomIcons/icons/misc4/itsxin_anim.dds", 16, 1, 33}
a["@Blueberry_joke"] = {"LibCustomIcons/icons/misc4/blueberryjoke_anim.dds", 33, 1, 14}
a["@Slitsensilla"] = {"LibCustomIcons/icons/misc4/slitsensilla_anim.dds", 6, 1, 33}
a["@INK_addict"] = {"LibCustomIcons/icons/misc4/inkaddict_anim3.dds", 11, 1, 25}
a["@SendeVerbot"] = {"LibCustomIcons/icons/misc4/sendeverbot_anim.dds", 47, 1, 8}
a["@terAAA"] = {"LibCustomIcons/icons/misc4/teraaa_anim.dds", 19, 1, 17}
a["@engelchen87"] = {"LibCustomIcons/icons/misc4/engelchen87_anim.dds", 12, 5, 25}
a["@wulfy1987"] = {"LibCustomIcons/icons/hodor/warfire_anim2.dds", 22, 1, 50}
a["@Freedomino"] = {"LibCustomIcons/icons/misc4/freedomino_anim3.dds", 10, 1, 2}
a["@Shambroka"] = {"LibCustomIcons/icons/misc4/shambroka_anim.dds", 37, 1, 20}
a["@iMoH"] = {"LibCustomIcons/icons/misc4/imoh_anim.dds", 21, 1, 14}
a["@Zahu"] = {"LibCustomIcons/icons/misc4/zahu_anim.dds", 6, 1, 6}
a["@Duckyirl"] = {"LibCustomIcons/icons/misc4/duckyirl_anim.dds", 16, 1, 9}
a["@Forzentina"] = {"LibCustomIcons/icons/misc4/forzentina_anim.dds", 8, 1, 7}
a["@flamingmams"] = {"LibCustomIcons/icons/misc4/flamingmams_anim.dds", 24, 1, 10}
a["@Jackknif4ek"] = {"LibCustomIcons/icons/misc4/jackknif4ek_anim.dds", 13, 1, 13}
a["@BananaDrama"] = {"LibCustomIcons/icons/misc4/bananadrama_anim.dds", 9, 1, 10}
a["@IIMelissaII"] = {"LibCustomIcons/icons/misc4/iimelissaii_anim.dds", 40, 1, 33}
a["@gregory.nik"] = {"LibCustomIcons/icons/misc4/gregorynik_anim.dds", 16, 1, 10}
a["@Lanfer"] = {"LibCustomIcons/icons/misc4/lanfer_anim.dds", 10, 5, 10}
a["@RyanRose"] = {"LibCustomIcons/icons/misc4/ryanrose_anim.dds", 34, 1, 10}
a["@MonroeGrimm"] = {"LibCustomIcons/icons/misc4/monroegrimm_anim.dds", 10, 5, 20}
a["@DOAM1"] = {"LibCustomIcons/icons/misc4/doam1_anim.dds", 6, 6, 25}
a["@D4BIDDEN1"] = {"LibCustomIcons/icons/misc4/d4bidden1_anim.dds", 31, 1, 9}
a["@Von_Riddick"] = {"LibCustomIcons/icons/misc4/vonriddick_anim.dds", 18, 1, 6}
a["@Kowly01"] = {"LibCustomIcons/icons/misc4/kowly01_anim.dds", 20, 1, 10}
a["@BIeed"] = {"LibCustomIcons/icons/misc4/bieed_anim.dds", 10, 5, 20}
a["@Yohas"] = {"LibCustomIcons/icons/misc4/Yohas_anim.dds", 11, 1, 11}
a["@cjmsupermans"] = {"LibCustomIcons/icons/misc4/cjmsupermans_anim.dds", 13, 1, 20}
a["@Hyo'jin"] = {"LibCustomIcons/icons/misc4/hyojin_anim.dds", 4, 1, 12}
a["@Dinkie"] = {"LibCustomIcons/icons/misc4/dinkie_anim.dds", 47, 1, 33}
a["@Kattatonia"] = {"LibCustomIcons/icons/misc4/kattatonia_anim.dds", 8, 1, 6}
a["@ImaginaryStory"] = {"LibCustomIcons/icons/misc4/imaginarystory_anim2.dds", 3, 1, 8}
a["@LordRenan"] = {"LibCustomIcons/icons/misc4/lordrenan_anim.dds", 16, 1, 15}
a["@Somatariel"] = {"LibCustomIcons/icons/misc4/somatariel_anim.dds", 4, 1, 5}
a["@Rustieee"] = {"LibCustomIcons/icons/misc4/Rustieee_anim_2.dds", 6, 3, 7}
a["@Rusty-Reformed"] = a["@Rustieee"]
a["@Woesz"] = {"LibCustomIcons/icons/misc4/woesz_anim.dds", 10, 5, 20}
a["@Katrusha"] = {"LibCustomIcons/icons/misc4/katrusha_anim.dds", 26, 1, 16}
a["@Dr.Knu_stiCH"] = {"LibCustomIcons/icons/misc4/drknustich_anim.dds", 15, 1, 14}
a["@BlueKaramelz"] = {"LibCustomIcons/icons/misc4/bluekaramelz_anim.dds", 9, 1, 20}
a["@OGRomky"] = {"LibCustomIcons/icons/misc4/OGRomky_anim_2.dds", 10, 5, 10}
a["@Po4talbonPechkin"] = {"LibCustomIcons/icons/misc4/po4talbonpechkin_anim.dds", 15, 1, 11}
a["@SMAUGY13"] = {"LibCustomIcons/icons/misc4/smaugy13_anim2.dds", 37, 1, 25}
a["@Hyperboreios7"] = {"LibCustomIcons/icons/misc4/hyperboreios7_anim.dds", 4, 1, 6}
a["@Santillius"] = {"LibCustomIcons/icons/misc4/santillius_anim.dds", 14, 1, 6}
a["@Large_Muffin"] = {"LibCustomIcons/icons/misc4/largemuffin_anim.dds", 3, 1, 10}
a["@LordGerry"] = {"LibCustomIcons/icons/misc4/lordgerry_anim.dds", 7, 1, 13}
a["@jormax"] = {"LibCustomIcons/icons/misc4/jormax_anim.dds", 16, 1, 10}
a["@mekops"] = {"LibCustomIcons/icons/misc4/mekops_anim.dds", 13, 1, 10}
a["@Hræsvelgr"] = {"LibCustomIcons/icons/misc4/hraesvelgr_anim.dds", 3, 1, 7}
a["@Awnia"] = {"LibCustomIcons/icons/misc4/awnia_anim.dds", 11, 1, 20}
a["@Neurotic_B1Purple"] = {"LibCustomIcons/icons/misc4/Neurotic_B1Purple_anim.dds", 9, 5, 14}
a["@Pawcio010"] = {"LibCustomIcons/icons/misc4/pawcio010_anim.dds", 11, 1, 10}
a["@mrnoodle1"] = {"LibCustomIcons/icons/misc4/mrnoodle1_anim.dds", 13, 1, 30}
a["@Stria"] = {"LibCustomIcons/icons/misc4/stria_anim.dds", 13, 1, 20}
a["@gigisalvo"] = {"LibCustomIcons/icons/misc4/gigisalvo_anim.dds", 42, 1, 12}
a["@Corrupt-Paragon"] = {"LibCustomIcons/icons/misc4/corruptparagon_anim.dds", 17, 1, 20}
a["@seryzawa"] = {"LibCustomIcons/icons/misc4/seryzawa_anim.dds", 16, 1, 10}
a["@St.Rain"] = {"LibCustomIcons/icons/misc4/strain_anim.dds", 16, 1, 10}
a["@Asgül_91"] = {"LibCustomIcons/icons/misc4/asgul91_anim.dds", 59, 1, 25}
a["@Tezlakipuka"] = {"LibCustomIcons/icons/misc4/tezlakipuka_anim.dds", 27, 1, 10}
a["@B1ghorse"] = {"LibCustomIcons/icons/misc4/b1ghorse_anim.dds", 15, 1, 25}
a["@rolst"] = {"LibCustomIcons/icons/misc4/rolst_anim.dds", 24, 1, 25}
a["@Epire"] = {"LibCustomIcons/icons/misc4/epire_anim.dds", 37, 1, 20}
a["@iamphilippbe"] = {"LibCustomIcons/icons/misc4/iamphilippbe_anim.dds", 20, 1, 20}
a["@XSummerRainX"] = {"LibCustomIcons/icons/misc4/xsummerrainx_anim.dds", 18, 1, 10}
a["@PhenixSong"] = {"LibCustomIcons/icons/misc4/phenixsong_anim.dds", 15, 1, 15}
a["@SaltyNoLife"] = {"LibCustomIcons/icons/misc4/saltynolife_anim.dds", 10, 1, 11}
a["@VerTiq"] = {"LibCustomIcons/icons/misc4/vertiq_anim.dds", 32, 1, 14}
a["@Meji-Wolf"] = {"LibCustomIcons/icons/misc4/mejiwolf_anim.dds", 15, 1, 10}
a["@albinoninjaxx17923"] = {"LibCustomIcons/icons/misc4/albinoninjaxx17923_anim.dds", 30, 1, 25}
a["@Qreatur"] = {"LibCustomIcons/icons/misc4/qreatur_anim.dds", 30, 1, 20}
a["@KanGaHru"] = {"LibCustomIcons/icons/misc4/kangahru_anim.dds", 35, 1, 10}
a["@Pyyveli"] = {"LibCustomIcons/icons/misc4/pyyveli_anim.dds", 12, 1, 25}
a["@NeruKodoka"] = {"LibCustomIcons/icons/misc4/nerukodoka_anim.dds", 49, 1, 20}
a["@PridePelt1"] = {"LibCustomIcons/icons/misc4/freezernips_anim.dds", 38, 1, 10}
a["@carl00"] = {"LibCustomIcons/icons/misc4/carl00_anim.dds", 49, 1, 20}
a["@Aemon_Lorraine"] = {"LibCustomIcons/icons/misc4/aemonlorraine_anim.dds", 9, 1, 25}
a["@Playtm"] = {"LibCustomIcons/icons/misc4/playtm_anim.dds", 11, 1, 13}
a["@Sighlentorion"] = {"LibCustomIcons/icons/misc4/sighlentorion_anim.dds", 9, 1, 11}
a["@PandaPareidolia"] = {"LibCustomIcons/icons/misc4/pandapareidolia_anim.dds", 10, 6, 25}
a["@SlipperySoap"] = {"LibCustomIcons/icons/misc4/slipperysoap_anim.dds", 13, 1, 25}
a["@Audds"] = {"LibCustomIcons/icons/misc4/audds_anim.dds", 46, 1, 20}
a["@tauriel02"] = {"LibCustomIcons/icons/misc4/tauriel02_anim.dds", 10, 1, 33}
a["@ck37090"] = {"LibCustomIcons/icons/misc4/ck37090_anim.dds", 20, 1, 10}
a["@FruitSloot"] = {"LibCustomIcons/icons/misc4/fruitsloot_anim.dds", 10, 1, 6}
a["@Sorgen-Kind"] = {"LibCustomIcons/icons/misc4/sorgenkind_anim3.dds", 31, 1, 11}
a["@mRakobore"] = {"LibCustomIcons/icons/misc4/mrakobore_anim.dds", 7, 1, 20}
a["@ViaViy"] = {"LibCustomIcons/icons/misc4/viaviy_anim.dds", 43, 1, 10}
a["@LagDoseIntolerance"] = {"LibCustomIcons/icons/misc4/lagdoseintolerance_anim.dds", 20, 1, 33}
a["@DorianGrayy"] = {"LibCustomIcons/icons/misc4/doriangrayy_anim.dds", 10, 5, 17}
a["@iaspis"] = {"LibCustomIcons/icons/misc4/iaspis_anim2.dds", 54, 1, 10}
a["@DejaVuDetroit"] = {"LibCustomIcons/icons/misc4/DejaVuDetroit_anim.dds", 9, 3, 18}
a["@Comparer1991"] = {"LibCustomIcons/icons/misc4/Comparer1991_anim.dds", 8, 1, 4}
a["@EcruteakCity"] = a["@randomuserID1"]
a["@Orblitzer"] = a["catjam"]
