-- SPDX-FileCopyrightText: 2026 m00nyONE
-- SPDX-License-Identifier: Artistic-2.0
local lib_name = "LibCustomIcons"
local lib = _G[lib_name]
local s = lib.GetStaticTable()
local a = lib.GetAnimatedTable()

s["@RedBoul"] = "LibCustomIcons/icons/misc8/RedBoul.dds"
s["@Beejy"] = "LibCustomIcons/icons/misc8/Beejy.dds"
s["@Soul_Hagans"] = "LibCustomIcons/icons/misc8/Soul_Hagans.dds"
s["@Ukmadorian"] = "LibCustomIcons/icons/misc8/Ukmadorian.dds"
a["@Kuroko29012"] = {"LibCustomIcons/icons/misc8/Kuroko29012_anim.dds", 17, 1, 10}
s["@Chio-Cill"] = "LibCustomIcons/icons/misc8/Chio_Cill.dds"
s["@NecroCat_Crimson"] = "LibCustomIcons/icons/misc8/NecroCat_Crimson.dds"
s["@zDarkus"] = "LibCustomIcons/icons/misc8/zDarkus.dds"
a["@Juanut0"] = {"LibCustomIcons/icons/misc8/Juanut0_anim.dds", 7, 5, 12}
a["@krdntro"] = {"LibCustomIcons/icons/misc8/krdntro_anim.dds", 9, 1, 13}
a["@AsieRubio"] = {"LibCustomIcons/icons/misc8/AsieRubio_anim.dds", 7, 5, 12}
a["@itsTraka"] = {"LibCustomIcons/icons/misc8/itsTraka_anim.dds", 7, 5, 12}
a["@IBelmonteI"] = {"LibCustomIcons/icons/misc8/ibelmontei_anim.dds", 16, 1, 16}
s["@Beaver720"] = "LibCustomIcons/icons/misc8/Beaver720.dds"
a["@Beaver720"] = {"LibCustomIcons/icons/misc8/Beaver720_anim.dds", 10, 5, 25}
s["@Freddingerz"] = "LibCustomIcons/icons/misc8/Freddingerz.dds"
s["@Senfkorn"] = "LibCustomIcons/icons/misc8/Senfkorn.dds"
a["@ClothFollow1"] = {"LibCustomIcons/icons/misc8/ClothFollow1_anim.dds", 6, 6, 25}
a["@Paaatchy"] = {"LibCustomIcons/icons/misc8/Paaatchy_anim.dds", 6, 6, 12}
s["@Gofure24816"] = "LibCustomIcons/icons/misc8/Gofure.dds"
s["@NJtheMinion"] = "LibCustomIcons/icons/misc8/minion.dds"
a["@oppy13"] = {"LibCustomIcons/icons/misc8/Oppy_anim.dds", 5, 4, 10}
a["@DeadHistory"] = {"LibCustomIcons/icons/misc8/DeadHistory_anim.dds", 43, 1, 20}
s["@NierielSootica"] = "LibCustomIcons/icons/misc8/NierielSootica.dds"
a["@EviceratorN"] = {"LibCustomIcons/icons/misc8/EviceratorN_anim.dds", 12, 4, 20}
a["@MatejSitar"] = {"LibCustomIcons/icons/misc8/MatejSitar_anim.dds", 12, 1, 25}
s["@Admral_Snakbar"] = "LibCustomIcons/icons/misc8/Admral_Snakbar.dds"
s["@Akira_tm"] = "LibCustomIcons/icons/misc8/Akira_tm.dds"
a["@Nicotine92"] = {"LibCustomIcons/icons/misc8/Nicotine92_anim.dds", 10, 5, 10}
s["@MrSalv"] = "LibCustomIcons/icons/misc8/MrSalv.dds"
s["@Arhwan"] = "LibCustomIcons/icons/misc8/Arhwan.dds"
s["@Wusband"] = "LibCustomIcons/icons/misc8/Wusband.dds"
a["@Wusband"] = {"LibCustomIcons/icons/misc8/Wusband_anim.dds", 6, 1, 10}
s["@LilianHeart"] = "LibCustomIcons/icons/misc8/LilianHeart.dds"
s["@Velarion"] = "LibCustomIcons/icons/misc8/Velarion.dds"
s["@vladossk"] = "LibCustomIcons/icons/misc8/vladossk.dds"
s["@Valerachich"] = "LibCustomIcons/icons/misc8/Valerachich.dds"
s["@Witcher988"] = "LibCustomIcons/icons/misc8/Witcher988.dds"
s["@gnomeimnot"] = "LibCustomIcons/icons/misc8/gnomeimnot.dds"
a["@TrustInDust"] = {"LibCustomIcons/icons/misc8/TrustInDust_anim.dds", 23, 2, 23}
s["@Fanatir"] = "LibCustomIcons/icons/misc8/Fanatir.dds"
a["@kantal1st"] = {"LibCustomIcons/icons/misc8/kantal1st_anim.dds", 40, 1, 20}
a["@Barrrny"] = {"LibCustomIcons/icons/misc8/barrrny_anim.dds", 69, 1, 20}
s["@Barrrny"] = "LibCustomIcons/icons/misc8/barrrny.dds"
a["@Nickx9"] = {"LibCustomIcons/icons/misc8/Nickx9_anim.dds", 11, 1, 4}
a["@LeeWangcai"] = {"LibCustomIcons/icons/misc8/LeeWangcai_anim.dds", 15, 2, 8}
a["@Saarz"] = {"LibCustomIcons/icons/misc8/Saarz_anim.dds", 16, 1, 9}
a["@ShuguBota"] = {"LibCustomIcons/icons/misc8/ShuguBota_anim.dds", 20, 1, 25}
a["@FIatIining"] = {"LibCustomIcons/icons/misc8/FIatIining_anim.dds", 45, 1, 30}
s["@PyroFD3S"] = "LibCustomIcons/icons/misc8/PyroFD3S.dds"
s["@rowenlacour"] = "LibCustomIcons/icons/misc8/rowenlacour.dds"
s["@CJACKS25"] = "LibCustomIcons/icons/misc8/CJACKS25.dds"
s["@TABANTHAA"] = "LibCustomIcons/icons/misc8/TABANTHAA.dds"
s["@mdjessup"] = "LibCustomIcons/icons/misc8/mdjessup.dds"
s["@NicoleScarlet"] = "LibCustomIcons/icons/misc8/NicoleScarlet.dds"
s["@DunklesLink"] = "LibCustomIcons/icons/misc8/DunklesLink.dds"
a["@Sher-E"] = {"LibCustomIcons/icons/misc8/Sher-E_anim.dds", 17, 2, 12.5}
a["@BEAR_406ttv"] = {"LibCustomIcons/icons/misc8/BEAR_406ttv_anim.dds", 10, 1, 10}
s["@LuttyTheKiller"] = "LibCustomIcons/icons/misc8/LuttyTheKiller.dds"
s["@Hanadila"] = "LibCustomIcons/icons/misc8/Hanadila.dds"
a["@Hanadila"] = {"LibCustomIcons/icons/misc8/Hanadila_anim.dds", 10, 5, 20}
a["@SomebodyNobody"] = {"LibCustomIcons/icons/misc8/SomebodyNobody_anim.dds", 19, 1, 12.5}
a["@Jirachi_Ex"] = {"LibCustomIcons/icons/misc8/Jirachi_Ex_anim_2.dds", 5, 2, 5}
s["@DestroyerESO"] = "LibCustomIcons/icons/misc8/DestroyerESO.dds"
s["@LordG.36"] = "LibCustomIcons/icons/misc8/LordG36.dds"
-- a["@LordG.36"] = {"LibCustomIcons/icons/misc8/LordG36_anim.dds", 0, 0, 0}
s["@Clutter_Monk"] = "LibCustomIcons/icons/misc8/Clutter_Monk.dds"
s["@RodMajors"] = "LibCustomIcons/icons/misc8/RodMajors.dds"
s["@dye_qwerty"] = "LibCustomIcons/icons/misc8/dye_qwerty.dds"
s["@Xphalt"] = "LibCustomIcons/icons/misc8/Xphalt.dds"
s["@SkinnyBE"] = "LibCustomIcons/icons/misc8/SkinnyBE.dds"
s["@paradiys"] = "LibCustomIcons/icons/misc8/paradiys.dds"
a["@Kaioshin14"] = {"LibCustomIcons/icons/misc8/Kaioshin14_anim.dds", 9, 1, 10}
s["@CheshireNeko"] = "LibCustomIcons/icons/misc8/CheshireNeko.dds"
a["@SLIMLAC2000"] = {"LibCustomIcons/icons/misc8/SLIMLAC2000_anim.dds", 11, 4, 33}
s["@Cheesecattac"] = "LibCustomIcons/icons/misc8/Cheesecattac.dds"
s["@Taku3mi"] = "LibCustomIcons/icons/misc8/Taku3mi.dds"
s["@SnowPrime"] = "LibCustomIcons/icons/misc8/SnowPrime.dds"
s["@xkuroibara"] = "LibCustomIcons/icons/misc8/xkuroibara.dds"
s["@ZookieFyre"] = "LibCustomIcons/icons/misc8/ZookieFyre.dds"
s["@Sagrel"] = "LibCustomIcons/icons/misc8/sagrel.dds"
s["@kelumila"] = "LibCustomIcons/icons/misc8/kelumila.dds"
s["@Fieler"] = "LibCustomIcons/icons/misc8/Fieler.dds"
s["@Raelyn-mie"] = "LibCustomIcons/icons/misc8/Raelyn-mie.dds"
s["@DonjaZero"] = "LibCustomIcons/icons/misc8/DonjaZero.dds"
s["@Invs"] = "LibCustomIcons/icons/misc8/Invs.dds"
s["@Anonymous_Ember"] = "LibCustomIcons/icons/misc8/anonymous_ember.dds"
s["@Fream4ik"] = "LibCustomIcons/icons/misc8/fream4ik.dds"
s["@Affinitis"] = "LibCustomIcons/icons/misc8/Affinitis.dds"
s["@arima_alone"] = "LibCustomIcons/icons/misc8/arima_alone.dds"
s["@Umpalunpa"] = "LibCustomIcons/icons/misc8/Umpalunpa.dds"
s["@cxldnvs"] = "LibCustomIcons/icons/misc8/cxldnvs.dds"
s["@FinLaatDovahkiin"] = "LibCustomIcons/icons/misc8/FinLaatDovahkiin.dds"
a["@LillyxHaze"] = {"LibCustomIcons/icons/misc8/LillyxHaze_anim.dds", 13, 2, 5}
a["@lnfinty"] = {"LibCustomIcons/icons/misc8/lnfinty_anim.dds", 15, 3, 20}
a["@Sora_renewed"] = {"LibCustomIcons/icons/misc8/Sora_renewed_anim.dds", 12, 1, 10}
a["@GoldenCrowned"] = {"LibCustomIcons/icons/misc8/GoldenCrowned_anim.dds", 6, 1, 20}
s["@R3nTeXx"] = "LibCustomIcons/icons/misc8/R3nTeXx.dds"
a["@alaric1804"] = {"LibCustomIcons/icons/misc8/alaric1804_anim.dds", 12, 4, 50}
a["@Lilarna"] = {"LibCustomIcons/icons/misc8/Lilarna_anim.dds", 10, 5, 50}
s["@InWater1021"] = "LibCustomIcons/icons/misc8/InWater1021.dds"
a["@yztrash"] = {"LibCustomIcons/icons/misc8/yz_anim.dds", 11, 16, 33}
s["@Freyney"] = "LibCustomIcons/icons/misc8/little_pills.dds"
a["@Freyney"] = {"LibCustomIcons/icons/misc8/little_pills_anim.dds", 4, 1, 6}
s["@Cxdie"] = "LibCustomIcons/icons/misc8/Cxdie.dds"
s["@pururumka"] = "LibCustomIcons/icons/misc8/pururum.dds"
s["@Magic-Zack"] = "LibCustomIcons/icons/misc8/MagicZack.dds"
a["@jwill2theizzay"] = {"LibCustomIcons/icons/misc8/jwill2theizzay_anim.dds", 23, 1, 26}
a["@Trouble13691"] = {"LibCustomIcons/icons/misc8/Trouble13691_anim.dds", 7, 7, 16}
s["@Mushki"] = "LibCustomIcons/icons/misc8/Mushki.dds"
s["@K.YChen"] = "LibCustomIcons/icons/misc8/KYChen.dds"
a["@TetsuNoKirai"] = {"LibCustomIcons/icons/misc8/TetsuNoKirai.dds", 32, 1, 10}
s["@Mittrik"] = "LibCustomIcons/icons/misc8/mittrik.dds"
s["@El_Prezz"] = "LibCustomIcons/icons/misc8/ElPrez.dds"
s["@NeSatoshi"] = "LibCustomIcons/icons/misc8/nesatoshi.dds"
s["@Silmaxa"] = "LibCustomIcons/icons/misc8/Silmaxa.dds"
a["@drawsheichou"] = {"LibCustomIcons/icons/misc8/stellarringer_anim.dds", 11, 5, 9}
s["@mak1racle"] = "LibCustomIcons/icons/misc8/mak1racle.dds"
s["@duvvel"] = "LibCustomIcons/icons/misc8/duvvel.dds"
s["@lil-stinkyy"] = "LibCustomIcons/icons/misc8/lil-stinkyy.dds"
a["@IMPXRIVM"] = {"LibCustomIcons/icons/misc8/IMPXRIVM_anim.dds", 15, 3, 10}
s["@Adoring"] = "LibCustomIcons/icons/misc8/Adoring.dds"
a["@ArhonFiresoul"] = {"LibCustomIcons/icons/misc8/ArhonFiresoul_anim.dds", 7, 7, 10}
a["@GoridoTF2"] = {"LibCustomIcons/icons/misc8/GoridoTF2_anim.dds", 10, 5, 24}
s["@GoridoTF2"] = "LibCustomIcons/icons/misc8/GoridoTF2.dds"
a["@MichaelOfPie"] = {"LibCustomIcons/icons/misc8/MichaelOfPie_anim.dds", 5, 1, 11}
s["@MichaelOfPie"] = "LibCustomIcons/icons/misc8/MichaelOfPie.dds"
s["@MicahMXL"] = "LibCustomIcons/icons/misc8/MicahMXL.dds"
a["@MicahMXL"] = {"LibCustomIcons/icons/misc8/MicahMXL_anim.dds", 7, 5, 12}
s["@Valara-1"] = "LibCustomIcons/icons/misc8/Valara-1.dds"
s["@Alatariel301183"] = "LibCustomIcons/icons/misc8/Alatariel301183.dds"
s["@annakwonda"] = "LibCustomIcons/icons/misc8/annakwonda.dds"
a["@charlemagne9"] = {"LibCustomIcons/icons/misc8/charlemagne9_anim.dds", 10, 5, 10}
a["@ShadowDios"] = {"LibCustomIcons/icons/misc8/ShadowDios_anim.dds", 11, 1, 10}
s["@Eric-Gremond"] = "LibCustomIcons/icons/misc8/Eric-Gremond.dds"
s["@shiweiYan"] = "LibCustomIcons/icons/misc8/shiweiYan.dds"
s["@Yansq"] = "LibCustomIcons/icons/misc8/Yansq.dds"
s["@Fannfan"] = "LibCustomIcons/icons/misc8/Fannfan.dds"
s["@luan_ma"] = "LibCustomIcons/icons/misc8/luan_ma.dds"
a["@LeyaCQ"] = {"LibCustomIcons/icons/misc8/LeyaCQ_anim.dds", 5, 4, 14}
s["@creazyAllen"] = "LibCustomIcons/icons/misc8/creazyAllen.dds"
s["@heianqinshihuang"] = "LibCustomIcons/icons/misc8/heianqinshihuang.dds"
a["@Mother.Bear"] = {"LibCustomIcons/icons/misc8/Mother.Bear_anim.dds", 5, 1, 25}
s["@xDivie"] = "LibCustomIcons/icons/misc8/xDivie.dds"
a["@xDivie"] = {"LibCustomIcons/icons/misc8/xDivie_anim.dds", 4, 1, 2}
s["@perfectbao"] = "LibCustomIcons/icons/misc8/perfectbao.dds"
s["@wangpm001"] = "LibCustomIcons/icons/misc8/wangpm001.dds"
s["@TheMrPancake"] = "LibCustomIcons/icons/misc8/themrpancake.dds"
s["@Shironix"] = "LibCustomIcons/icons/misc8/Shironix.dds"
--a["@Shironix"] = a["catjam"]
s["@jelhalla"] = "LibCustomIcons/icons/misc8/jelhalla.dds"
s["@Feles"] = "LibCustomIcons/icons/misc8/feles.dds"
s["@Elder_Turtle707"] = "LibCustomIcons/icons/misc8/Elder_Turtle707.dds"
a["@Elder_Turtle707"] = {"LibCustomIcons/icons/misc8/Elder_Turtle707_anim.dds", 8, 1, 10}
a["@HollywoodSandy"] = {"LibCustomIcons/icons/misc8/HollywoodSandy_anim.dds", 43, 1, 15}
a["@bradiggan"] = {"LibCustomIcons/icons/misc8/bradiggan_anim.dds", 12, 1, 7}
a["@shedow2090"] = {"LibCustomIcons/icons/misc8/shedow2090_anim.dds", 24, 1, 10}
s["@Mizael1644"] = "LibCustomIcons/icons/misc8/Mizael1644.dds"
s["@Darkfire99"] = "LibCustomIcons/icons/misc8/Darkfire99.dds"
a["@St1cHHoG"] = {"LibCustomIcons/icons/misc8/St1cHHoG_anim.dds", 18, 1, 10}
s["@Aethluna"] = "LibCustomIcons/icons/misc8/Aethluna.dds"
s["@gangialf3"] = "LibCustomIcons/icons/misc8/gangialf3.dds"
s["@BlackArrow971"] = "LibCustomIcons/icons/misc8/BlackArrow971.dds"
a["@loriensinsight"] = {"LibCustomIcons/icons/misc8/loriensinsight_anim.dds", 6, 1, 10}
a["@TENMANGOES"] = {"LibCustomIcons/icons/misc8/TENMANGOES_anim.dds", 5, 1, 10}
a["@Efreezo"] = {"LibCustomIcons/icons/misc8/Efreezo_anim.dds", 6, 4, 10}
a["@LittleSeastar"] = {"LibCustomIcons/icons/misc8/LittleSeastar_anim.dds", 6, 4, 25}
s["@Premm"] = "LibCustomIcons/icons/misc8/Premm.dds"
s["@iKillElves4Septims"] = "LibCustomIcons/icons/misc8/iKillElves4Septims.dds"
s["@iGinz"] = "LibCustomIcons/icons/misc8/iGinz.dds"
a["@ObiJovi"] = {"LibCustomIcons/icons/misc8/ObiJovi_anim.dds", 5, 1, 5.5}
a["@Kansxi"] = {"LibCustomIcons/icons/misc8/Kansxi_anim.dds", 47, 1, 14}
s["@Notpure2"] = "LibCustomIcons/icons/misc8/Notpure2.dds"
a["@Notpure2"] = {"LibCustomIcons/icons/misc8/Notpure2_anim.dds", 4, 7, 28}
s["@bleeblue"] = "LibCustomIcons/icons/misc8/bleeblue.dds"
s["@Fer_Torres"] = "LibCustomIcons/icons/misc8/Fer_Torres.dds"
s["@Ozthos"] = "LibCustomIcons/icons/misc8/Ozthos.dds"
s["@Obrivious"] = "LibCustomIcons/icons/misc8/Obrivious.dds"
s["@raggsz"] = "LibCustomIcons/icons/misc8/raggsz.dds"
a["@raggsz"] = {"LibCustomIcons/icons/misc8/raggsz_anim.dds", 7, 7, 20}
s["@SolarcoolHan"] = "LibCustomIcons/icons/misc8/SolarcoolHan.dds"
a["@UnslaadVusWunduniik"] = {"LibCustomIcons/icons/misc8/UnslaadVusWunduniik_anim.dds", 6, 4, 50}
a["@Fried-childhood"] = {"LibCustomIcons/icons/misc8/Fried-childhood_anim.dds", 6, 4, 8}
s["@spyro76"] = "LibCustomIcons/icons/misc8/spyro76.dds"
a["@BIGTU"] = {"LibCustomIcons/icons/misc8/BIGTU_anim.dds", 11, 1, 33}
a["@Cookie_Axis"] = {"LibCustomIcons/icons/misc8/Cookie_Axis_anim.dds", 4, 2, 20}
s["@FerryTAIR"] = "LibCustomIcons/icons/misc8/FerryTAIR.dds"
s["@peachysaurusx"] = "LibCustomIcons/icons/misc8/peachysaurusx.dds"
a["@peachysaurusx"] = {"LibCustomIcons/icons/misc8/peachysaurusx_anim.dds", 8, 1, 9}
a["@Marquis_Shax"] = {"LibCustomIcons/icons/misc8/Marquis_Shax_anim.dds", 12, 4, 23}
a["@LeinadZ"] = {"LibCustomIcons/icons/misc8/LeinadZ_anim.dds", 4, 3, 10}
s["@Giubp"] = "LibCustomIcons/icons/misc8/Giubp.dds"
s["@Halvkyrie"] = "LibCustomIcons/icons/misc8/Halvkyrie.dds"
s["@PrincessValerie"] = s["@Halvkyrie"]
s["@WastelandValkyrie"] = s["@Halvkyrie"]
s["@Cappucci777"] = "LibCustomIcons/icons/misc8/Cappucci777_1.dds"
a["@AwfulGameDesign"] = {"LibCustomIcons/icons/misc8/AwfulGameDesign_anim.dds", 19, 1, 9.5}
s["@ArturoGarcia"] = "LibCustomIcons/icons/misc8/ArturoGarcia.dds"
a["@laolaowang"] = {"LibCustomIcons/icons/misc8/laolaowang_anim.dds", 4, 1, 6.6}
a["@verthick"] = {"LibCustomIcons/icons/misc8/verthick_anim.dds", 31, 1, 14}
s["@McFilthy"] = "LibCustomIcons/icons/misc8/McFilthy.dds"
