-- SPDX-FileCopyrightText: 2025 m00nyONE
-- SPDX-License-Identifier: Artistic-2.0

local lib_name = "LibCustomIcons"
local lib = _G[lib_name]
local s = lib.GetStaticTable()
local a = lib.GetAnimatedTable()

s["@GodSoma"] = "LibCustomIcons/icons/misc6/GodSoma.dds"
s["@FindingChemo"] = "LibCustomIcons/icons/misc6/FindingChemo.dds"
s["@zeegoddess"] = "LibCustomIcons/icons/misc6/zeegoddess.dds"
s["@Kingcyo"] = "LibCustomIcons/icons/misc6/Kingcyo.dds"
s["@stoleyoursweetroll42"] = "LibCustomIcons/icons/misc6/stoleyoursweetroll42.dds"
s["@Pamplemousse's"] = "LibCustomIcons/icons/misc6/Pamplemousses.dds"
s["@Nova-Chrono"] = "LibCustomIcons/icons/misc6/Nova-Chrono.dds"
s["@Chiefie"] = "LibCustomIcons/icons/misc6/Chiefie.dds"
s["@Harleenka"] = "LibCustomIcons/icons/misc6/Harleenka.dds"
s["@testfive"] = "LibCustomIcons/icons/misc6/testfive.dds"
s["@Woolter"] = "LibCustomIcons/icons/misc6/Woolter.dds"
s["@BetterCallBungie"] = "LibCustomIcons/icons/misc6/BetterCallBungie.dds"
s["@SteveRiver"] = "LibCustomIcons/icons/misc6/SteveRiver.dds"
s["@ZhuQueFlame"] = "LibCustomIcons/icons/misc6/ZhuQueFlame2.dds"
s["@L'oreasael"] = "LibCustomIcons/icons/misc6/Loreasael.dds"
s["@Dashiel20"] = "LibCustomIcons/icons/misc6/Dashiel20.dds"
s["@Spudlehhh"] = "LibCustomIcons/icons/misc6/Spudlehhh_2.dds"
s["@GattsLord"] = "LibCustomIcons/icons/misc6/GattsLord.dds"
s["@keevelish"] = "LibCustomIcons/icons/misc6/keevelish.dds"
s["@Mendrak"] = "LibCustomIcons/icons/misc6/Mendrak.dds"
s["@SGzuidiao"] = "LibCustomIcons/icons/misc6/SGzuidiao.dds"
s["@yaasshaa"] = "LibCustomIcons/icons/misc6/yaasshaa_2.dds"
s["@UNSLaaDKONahRIK2000"] = "LibCustomIcons/icons/misc6/UNSLaaDKONahRIK2000.dds"
s["@purplepyxis"] = "LibCustomIcons/icons/misc6/purplepyxis.dds"
s["@GogiDich"] = "LibCustomIcons/icons/misc6/GogiDich.dds"
s["@Supiidohantaa"] = "LibCustomIcons/icons/misc6/Supiidohantaa.dds"
s["@Niko_NSK"] = "LibCustomIcons/icons/misc6/Niko_NSK.dds"
s["@qva-qva"] = "LibCustomIcons/icons/misc6/qva-qva.dds"
s["@sam.sable"] = "LibCustomIcons/icons/misc6/sam.sable2.dds"
s["@Vidvar"] = "LibCustomIcons/icons/misc6/Vidvar2.dds"
s["@IFairyKingI"] = "LibCustomIcons/icons/misc6/IFairyKingI.dds"
s["@SimpleEasy"] = "LibCustomIcons/icons/misc6/SimpleEasy.dds"
s["@Mickitymal"] = "LibCustomIcons/icons/misc6/mickitymal.dds"
s["@IndorilGames"] = "LibCustomIcons/icons/misc6/IndorilGames.dds"
s["@P4inK1IL"] = "LibCustomIcons/icons/misc6/P4inK1IL.dds"
s["@ScaryCloud"] = "LibCustomIcons/icons/misc6/ScaryCloud.dds"
s["@Shebeka"] = "LibCustomIcons/icons/misc6/Shebeka.dds"
s["@Ellawissa"] = "LibCustomIcons/icons/misc6/Ellawissa.dds"
s["@HeIIss"] = "LibCustomIcons/icons/misc6/HeIIss.dds"
s["@DarkSawer"] = "LibCustomIcons/icons/misc6/DarkSawer.dds"
s["@Majima323"] = "LibCustomIcons/icons/misc6/Majima323_2.dds"
s["@PaybackFFS"] = "LibCustomIcons/icons/misc6/PaybackFFS.dds"
s["@silentseashore"] = "LibCustomIcons/icons/misc6/silentseashore.dds"
s["@Banana.Fish"] = "LibCustomIcons/icons/misc6/Banana.Fish.dds"
s["@Banana.Jelly"] = s["@Banana.Fish"]
s["@Banana.Jellyfish"] = s["@Banana.Fish"]
s["@Chomper876"] = "LibCustomIcons/icons/misc6/Chomper876_2.dds"
s["@OrjanOls"] = "LibCustomIcons/icons/misc6/OrjanOls.dds"
s["@RGinty"] = "LibCustomIcons/icons/misc6/RGinty.dds"
s["@Slicerr"] = "LibCustomIcons/icons/misc6/Slicerr.dds"
s["@Bjr54"] = "LibCustomIcons/icons/misc6/Bjr54.dds"
s["@DevoutLion"] = "LibCustomIcons/icons/misc6/DevoutLion.dds"
s["@Sk00ma4Life"] = "LibCustomIcons/icons/misc6/Sk00ma4Life.dds"
s["@Pandamonium77"] = "LibCustomIcons/icons/misc6/Pandamonium77.dds"
s["@Nrgy604"] = "LibCustomIcons/icons/misc6/Nrgy604.dds"
s["@BIGG'0730"] = "LibCustomIcons/icons/misc6/BIGG0730.dds"
s["@MrDAJ"] = "LibCustomIcons/icons/misc6/MrDAJ.dds"
s["@H4ckl"] = "LibCustomIcons/icons/misc6/H4ckl1.dds"
s["@zFinrod"] = "LibCustomIcons/icons/misc6/Firiendil.dds"
s["@Valkyrya"] = "LibCustomIcons/icons/misc6/Valkyrya.dds"
s["@Eris221"] = "LibCustomIcons/icons/misc6/Eris221_3.dds"
s["@Beekonchik"] = "LibCustomIcons/icons/misc6/Beekonchik.dds"
s["@Rountyy"] = "LibCustomIcons/icons/misc6/Rountyy.dds"
s["@qian1"] = "LibCustomIcons/icons/misc6/qian1.dds"
s["@xiaowu1"] = "LibCustomIcons/icons/misc6/xiaowu1.dds"
s["@Underworld_King"] = "LibCustomIcons/icons/misc6/Underworld_King.dds"
s["@Patll"] = "LibCustomIcons/icons/misc6/Patll.dds"
s["@Idream07"] = "LibCustomIcons/icons/misc6/Idream07.dds"
s["@KayDe'Vine"] = "LibCustomIcons/icons/misc6/KayDeVine.dds"
s["@Cruor'Vult"] = "LibCustomIcons/icons/misc6/CruorVult.dds"
s["@Urfin_jus318"] = "LibCustomIcons/icons/misc6/Urfin_jus318.dds"
s["@Sarior"] = "LibCustomIcons/icons/misc6/Sarior.dds"
s["@FunkM"] = "LibCustomIcons/icons/misc6/FunkM.dds"
s["@Menilig"] = "LibCustomIcons/icons/misc6/Menilig.dds"
s["@laviniascott"] = "LibCustomIcons/icons/misc6/laviniascott.dds"
s["@Merican_Hunter"] = "LibCustomIcons/icons/misc6/Merican_Hunter.dds"
s["@BlueSirop"] = "LibCustomIcons/icons/misc6/BlueSirop.dds"
s["@Sulfurg1"] = "LibCustomIcons/icons/misc6/Sulfurg1.dds"
s["@rjYassi"] = "LibCustomIcons/icons/misc6/rjYassi.dds"
s["@riddledend"] = "LibCustomIcons/icons/misc6/riddledend.dds"
s["@kast1x"] = "LibCustomIcons/icons/misc6/kast1x.dds"
s["@TakiitoPotato"] = "LibCustomIcons/icons/misc6/TakiitoPotato.dds"
s["@PyratoX"] = "LibCustomIcons/icons/misc6/PyratoX.dds"
s["@pimsous"] = "LibCustomIcons/icons/misc6/pimsous.dds"
s["@tanksapeuu"] = "LibCustomIcons/icons/misc6/tanksapeuu.dds"
s["@Skyu1618"] = "LibCustomIcons/icons/misc6/Skyu1618.dds"
s["@Apel'sinka"] = "LibCustomIcons/icons/misc6/Apelsinka2.dds"
s["@NotExist"] = "LibCustomIcons/icons/misc6/NotExist.dds"
s["@Veranka"] = "LibCustomIcons/icons/misc6/Veranka.dds"
s["@mr.r0b0t"] = "LibCustomIcons/icons/misc6/mr.r0b0t.dds"
s["@CodeKatana"] = "LibCustomIcons/icons/misc6/CodeKatana.dds"
s["@JIM.ESO"] = "LibCustomIcons/icons/misc6/JIM.ESO.dds"
s["@Hulimulli"] = "LibCustomIcons/icons/misc6/Hulimulli.dds"
s["@IlmareSOSITE"] = "LibCustomIcons/icons/misc6/IlmareSOSITE.dds"
s["@IshIshsauvages"] = "LibCustomIcons/icons/misc6/IshIshsauvages.dds"
s["@SuAzeria"] = "LibCustomIcons/icons/misc6/SuAzeria.dds"
s["@wongers"] = "LibCustomIcons/icons/misc6/wongers.dds"
s["@Bilvy"] = "LibCustomIcons/icons/misc6/Bilvy.dds"
a["@Bilvy"] = {"LibCustomIcons/icons/misc6/Bilvy_anim.dds", 7, 7, 30}
s["@uzw"] = "LibCustomIcons/icons/misc6/uzw.dds"
s["@Akang91"] = "LibCustomIcons/icons/misc6/Akang91.dds"
s["@SirTrimar"] = "LibCustomIcons/icons/misc6/SirTrimar.dds"
s["@Eigh1_Puppies"] = "LibCustomIcons/icons/misc6/Eigh1_Puppies.dds"
s["@haleysarahw"] = "LibCustomIcons/icons/misc6/haleysarahw_2.dds"
s["@Bron2007"] = "LibCustomIcons/icons/misc6/Bron2007_2.dds"
s["@Ezyh_B"] = "LibCustomIcons/icons/misc6/Ezyh_B.dds"
s["@silverspin"] = "LibCustomIcons/icons/misc6/silverspin.dds"
s["@Antisley"] = "LibCustomIcons/icons/misc6/Antisley.dds"
s["@Hasenengel"] = "LibCustomIcons/icons/misc6/Hasenengel.dds"
s["@cy970461584"] = "LibCustomIcons/icons/misc6/cy970461584.dds"
s["@Qingcaodangao"] = "LibCustomIcons/icons/misc6/Qingcaodangao.dds"
s["@Malcolm_Merlyn"] = "LibCustomIcons/icons/misc6/Malcolm_Merlyn_2.dds"
s["@hozumi995"] = "LibCustomIcons/icons/misc6/hozumi995.dds"
s["@lihanwen"] = "LibCustomIcons/icons/misc6/lihanwen.dds"
s["@haven_savage"] = "LibCustomIcons/icons/misc6/haven_savage_2.dds"
s["@kartoonxv"] = "LibCustomIcons/icons/misc6/kartoonxv.dds"
s["@SLXXBYY"] = "LibCustomIcons/icons/misc6/SLXXBYY.dds"
s["@TheUzi"] = "LibCustomIcons/icons/misc6/TheUzi.dds"
s["@Presho"] = "LibCustomIcons/icons/misc6/Presho.dds"
s["@OlajuwonPS"] = "LibCustomIcons/icons/misc6/OlajuwonPS.dds"
s["@leo1991991"] = "LibCustomIcons/icons/misc6/Leo1991991.dds"
s["@BirdTheChatterer"] = "LibCustomIcons/icons/misc6/BirdTheChatterer.dds"
s["@Olive_Q"] = "LibCustomIcons/icons/misc6/Olive_Q.dds"
s["@Dolbic"] = "LibCustomIcons/icons/misc6/Dolbic.dds"
s["@o_Temp"] = "LibCustomIcons/icons/misc6/o_Temp.dds"
s["@Justacourier"] = "LibCustomIcons/icons/misc6/Justacourier.dds"
s["@Caste-R"] = "LibCustomIcons/icons/misc6/Caste-R.dds"
s["@Quickslant"] = "LibCustomIcons/icons/misc6/Quickslant.dds"
s["@xuyiwsx"] = "LibCustomIcons/icons/misc6/xuyiwsx.dds"
s["@Franzisa"] = "LibCustomIcons/icons/misc6/Franzisa.dds"
s["@ToastiVT"] = "LibCustomIcons/icons/misc6/ToastiVT.dds"
s["@Toasti-chan"] = s["@ToastiVT"]
s["@Kinkaya"] = "LibCustomIcons/icons/misc6/Kinkaya.dds"
s["@Eldawald"] = "LibCustomIcons/icons/misc6/Eldawald_3.dds"
s["@Jayela7w7"] = "LibCustomIcons/icons/misc6/Jayela7w7.dds"
s["@S.lunatic"] = "LibCustomIcons/icons/misc6/S.lunatic.dds"
s["@LoreleaAriani"] = "LibCustomIcons/icons/misc6/LoreleaAriani.dds"
s["@Tonjeel"] = "LibCustomIcons/icons/misc6/Tonjeel.dds"
s["@CordingOnyx"] = "LibCustomIcons/icons/misc6/CordingOnyx.dds"
s["@FergusMcLeod"] = "LibCustomIcons/icons/misc6/FergusMcLeod.dds"
s["@taiko.txt"] = "LibCustomIcons/icons/misc6/taiko.txt.dds"
s["@Numzy"] = "LibCustomIcons/icons/misc6/Numzy_3.dds"
s["@Rektdown"] = "LibCustomIcons/icons/misc6/Rektdown.dds"
s["@aestrivex"] = "LibCustomIcons/icons/misc6/aestrivex.dds"
s["@CosminG10"] = "LibCustomIcons/icons/misc6/CosminG10.dds"
s["@ZwERkY420"] = "LibCustomIcons/icons/misc6/ZwERkY420.dds"
s["@fadlo"] = "LibCustomIcons/icons/misc6/fadlo.dds"
s["@WuffyCerulei"] = "LibCustomIcons/icons/misc6/WuffyCerulei.dds"
s["@KiltMaster"] = "LibCustomIcons/icons/misc6/KiltMaster.dds"
s["@Chaos.Riron"] = "LibCustomIcons/icons/misc6/ChaosRiron.dds"
s["@JacquelineS"] = "LibCustomIcons/icons/misc6/JacquelineS.dds"
s["@Tochno"] = "LibCustomIcons/icons/misc6/Tochno.dds"
s["@PzeuSs"] = "/esoui/art/icons/ability_templar_stendarr_aura.dds"
s["@V'oid"] = "LibCustomIcons/icons/misc6/Void_2.dds"
s["@AyumiChiyo"] = "LibCustomIcons/icons/misc6/AyumiChiyo.dds"
s["@Elda_Reaper"] = "LibCustomIcons/icons/misc6/Elda_Reaper.dds"
s["@iceteaqueen"] = "LibCustomIcons/icons/misc6/iceteaqueen.dds"
s["@Shake98"] = "LibCustomIcons/icons/misc6/Shake98.dds"
s["@Verathius"] = "LibCustomIcons/icons/misc6/Verathius.dds"
s["@staledom"] = "LibCustomIcons/icons/misc6/staledom_2.dds"
s["@luciferwow"] = "LibCustomIcons/icons/misc6/luciferwow.dds"
s["@XTheAvariciousX"] = "LibCustomIcons/icons/misc6/XTheAvariciousX.dds"
s["@TinY-tiNy"] = "LibCustomIcons/icons/misc6/TinY-tiNy.dds"
s["@Sei2000"] = "LibCustomIcons/icons/misc6/Seija12.dds"
s["@NanfengoubA"] = "LibCustomIcons/icons/misc6/NanfengoubA.dds"
s["@TheFifthMizukage"] = "LibCustomIcons/icons/misc6/TheFifthMizukage.dds"
s["@iiiDeMiGoD"] = "LibCustomIcons/icons/misc6/iiiDeMiGoD.dds"
s["@SlayerSyrena"] = "LibCustomIcons/icons/misc6/SlayerSyrena.dds"
s["@Rainsolo"] = "LibCustomIcons/icons/misc6/Rainsolo.dds"
s["@Kecaj"] = "LibCustomIcons/icons/misc6/Kecaj.dds"
s["@Gandalf_Sturmbringer"] = "LibCustomIcons/icons/misc6/Gandalf_Sturmbringer.dds"
s["@Atærius"] = "LibCustomIcons/icons/misc6/Ataerius.dds"
s["@Murkmire_Prepper"] = "LibCustomIcons/icons/misc6/Murkmire_Prepper.dds"
s["@SomeSnacks"] = "LibCustomIcons/icons/misc6/SomeSnacks.dds"
s["@MoonFourteen"] = "LibCustomIcons/icons/misc6/MoonFourteen.dds"
s["@Fee_Morgane"] = "LibCustomIcons/icons/misc6/Fee_Morgane.dds"
s["@MisterAlf"] = "LibCustomIcons/icons/misc6/MisterAlf.dds"
s["@FabinusMagnus"] = "LibCustomIcons/icons/misc6/FabinusMagnus.dds"
s["@sledgex"] = "LibCustomIcons/icons/misc6/sledgex.dds"
s["@Nyphadora"] = "LibCustomIcons/icons/misc6/Nyphadora.dds"
s["@Ievus"] = "LibCustomIcons/icons/misc6/Ievus.dds"
s["@csndvl10"] = "/esoui/art/icons/class/class_nightblade.dds"
s["@Cowardly_Slime"] = "LibCustomIcons/icons/misc6/Cowardly_Slime.dds"
s["@Sparrow20202"] = "LibCustomIcons/icons/misc6/Sparrow20202.dds"
s["@woody4853"] = "LibCustomIcons/icons/misc6/woody4853.dds"
s["@Sbirro91"] = "LibCustomIcons/icons/misc6/Sbirro91.dds"
s["@Valnic76"] = "LibCustomIcons/icons/misc6/Valnic76.dds"
s["@DRAG0Z"] = "LibCustomIcons/icons/misc6/DRAG0Z.dds"
s["@Ar0s"] = "LibCustomIcons/icons/misc6/Ar0s.dds"
s["@MeggySlayer69"] = "LibCustomIcons/icons/misc6/MeggySlayer69_2.dds"
s["@shaggySpy69"] = "LibCustomIcons/icons/misc6/shaggySpy69.dds"
s["@Canaryi0"] = "LibCustomIcons/icons/misc6/Canaryi0.dds"
s["@PixelMachine"] = "LibCustomIcons/icons/misc6/PixelMachine.dds"
s["@imsixtwosix"] = "LibCustomIcons/icons/misc6/imsixtwosix.dds"
s["@Mr.Quamfy"] = "LibCustomIcons/icons/misc6/Mr.Quamfy_2.dds"
s["@Sadzonka"] = "LibCustomIcons/icons/misc6/Sadzonka.dds"
s["@Mr.Yeeager"] = "LibCustomIcons/icons/misc6/Mr.Yeeager.dds"
s["@Yuzuru0083"] = "LibCustomIcons/icons/misc6/Yuzuru0083.dds"
s["@einfach.sasa"] = "LibCustomIcons/icons/misc6/einfach.sasa.dds"
s["@Am63R"] = "LibCustomIcons/icons/misc6/Am63R.dds"
s["@LaNiu4"] = "LibCustomIcons/icons/misc6/LaNiu4.dds"
s["@TREEONLY"] = "LibCustomIcons/icons/misc6/TREEONLY_2.dds"
s["@Brundeen"] = "LibCustomIcons/icons/misc6/Brundeen.dds"
s["@Invader_Him"] = "LibCustomIcons/icons/misc6/Invader_Him.dds"
s["@O'mighty"] = "LibCustomIcons/icons/misc6/Omighty.dds"
s["@n0us_2xh"] = "LibCustomIcons/icons/misc6/n0us_2xh.dds"
s["@RestCap"] = "LibCustomIcons/icons/misc6/RestCap.dds"
s["@Roboen"] = "LibCustomIcons/icons/misc6/Roboen.dds"
s["@Thy_NecroNymph"] = "LibCustomIcons/icons/misc6/Thy_NecroNymph.dds"
s["@cdyesno"] = "LibCustomIcons/icons/misc6/cdyesno.dds"
s["@DonKingDingaLing"] = "LibCustomIcons/icons/misc6/DonKingDingaLing_2.dds"
s["@Toronir_bosmer"] = "LibCustomIcons/icons/misc6/Toronir_bosmer.dds"
s["@mel1582"] = "LibCustomIcons/icons/misc6/mel1582.dds"
s["@Aglon_X"] = "LibCustomIcons/icons/misc6/Aglon_X.dds"
s["@Shiyozushi"] = "LibCustomIcons/icons/misc6/Shiyozushi.dds"
s["@Helia1221"] = "LibCustomIcons/icons/misc6/Helia1221.dds"
s["@ar2r_papian"] = "LibCustomIcons/icons/misc6/ar2r_papian_3.dds"
s["@FMSeries"] = "LibCustomIcons/icons/misc6/FMSeries.dds"
s["@Xahxi"] = "LibCustomIcons/icons/misc6/Xahxi.dds"
s["@Tony_Skarface"] = "LibCustomIcons/icons/misc6/Tony_Skarface.dds"
s["@KiraMariko"] = "LibCustomIcons/icons/misc6/KiraMariko.dds"
s["@CydrosDE"] = "LibCustomIcons/icons/misc6/CydrosDE_4.dds"
s["@Spirit2726"] = "LibCustomIcons/icons/misc6/Spirit2726.dds"
s["@norncat"] = "LibCustomIcons/icons/misc6/norncat.dds"
s["@Ideenloser"] = "LibCustomIcons/icons/misc6/Ideenloser.dds"
s["@Taabahtee"] = "LibCustomIcons/icons/misc6/Taabahtee.dds"
s["@Xajiro"] = "LibCustomIcons/icons/misc6/Xajiro.dds"
s["@matarius"] = "LibCustomIcons/icons/misc6/matarius.dds"
s["@DarthxMordecai"] = "LibCustomIcons/icons/misc6/DarthxMordecai.dds"
s["@DarthxLohwie"] = "LibCustomIcons/icons/misc6/DarthxLohwie.dds"
s["@teheUwU"] = "LibCustomIcons/icons/misc6/teheUwU.dds"
s["@l3schi"] = "LibCustomIcons/icons/misc6/l3schi_2.dds"
s["@Stei-Net"] = "LibCustomIcons/icons/misc6/Stei-Net.dds"
s["@MarcNB"] = "LibCustomIcons/icons/misc6/MarcNB.dds"
s["@fortyouncez"] = "LibCustomIcons/icons/misc6/fortyouncez.dds"
s["@jumpy'boi"] = "LibCustomIcons/icons/misc6/jumpyboi.dds"
s["@Sigillum_Diaboli"] = "LibCustomIcons/icons/misc6/Sigillum_Diaboli.dds"
s["@just_1n"] = "LibCustomIcons/icons/misc6/just_1n.dds"
s["@Sniko_hs"] = "LibCustomIcons/icons/misc6/Sniko_hs.dds"
s["@MeatBoy543"] = "LibCustomIcons/icons/misc6/MeatBoy543.dds"
s["@withoout"] = "LibCustomIcons/icons/misc6/withoout_2.dds"
s["@Tamonten-RU"] = "LibCustomIcons/icons/misc6/Tamonten-RU.dds"
s["@Shiftypaaste"] = "LibCustomIcons/icons/misc6/Shiftypaaste.dds"
s["@Eivissa82"] = "LibCustomIcons/icons/misc6/Eivissa82.dds"
s["@Magicmaster_Lord"] = "LibCustomIcons/icons/misc6/Magicmaster_Lord_2.dds"
s["@DeLuIu"] = "LibCustomIcons/icons/misc6/DeLuIu.dds"
s["@KinoToad"] = "LibCustomIcons/icons/misc6/KinoToad.dds"
s["@Trierhier"] = "LibCustomIcons/icons/misc6/Trierhier.dds"
s["@Plada"] = "LibCustomIcons/icons/misc6/Plada.dds"
s["@BortSmithson"] = "LibCustomIcons/icons/misc6/BortSmithson.dds"
s["@shenqaq"] = "LibCustomIcons/icons/misc6/shenqaq_2.dds"
s["@dovahkiinrichard"] = "LibCustomIcons/icons/misc6/dovahkiinrichard.dds"
s["@AgentJ_28"] = "LibCustomIcons/icons/misc6/AgentJ_28.dds"
s["@Grau.sherra"] = "LibCustomIcons/icons/misc6/Grausherra.dds"
s["@BangBangESO"] = "LibCustomIcons/icons/misc6/BangBangESO.dds"
s["@DazedGoldfish"] = "LibCustomIcons/icons/misc6/DazedGoldfish.dds"
s["@Flex-Lord"] = "LibCustomIcons/icons/misc6/Flex-Lord.dds"
s["@HydraGus"] = "LibCustomIcons/icons/misc6/HydraGus.dds"
s["@Auri-El7"] = "LibCustomIcons/icons/misc6/AuriEl.dds"
s["@Mashiroz233"] = "LibCustomIcons/icons/misc6/Mashiroz233.dds"
s["@xiyi"] = "LibCustomIcons/icons/misc6/xiyi.dds"
s["@DaniDas78"] = "LibCustomIcons/icons/misc6/DaniDas78.dds"
s["@SanyaDieZockt"] = "LibCustomIcons/icons/misc6/SanyaDieZockt.dds"
s["@Polly22"] = "LibCustomIcons/icons/misc6/Polly22.dds"
s["@zot900"] = "LibCustomIcons/icons/misc6/zot900.dds"
s["@VEL.A"] = "LibCustomIcons/icons/misc6/VEL.A.dds"
s["@Bilma"] = "LibCustomIcons/icons/misc6/Bilma.dds"
s["@Red7Velvet"] = "LibCustomIcons/icons/misc6/Red7Velvet.dds"
s["@Alphalyr43"] = "LibCustomIcons/icons/misc6/Alphalyr43.dds"
s["@MajoGaming21"] = "LibCustomIcons/icons/misc6/MajoGaming21.dds"
s["@TheRoyalPlayer"] = "LibCustomIcons/icons/misc6/TheRoyalPlayer.dds"
s["@Terapanthera"] = "LibCustomIcons/icons/misc6/Terapanthera.dds"
s["@Alpheu5"] = "LibCustomIcons/icons/misc6/Alpheu5.dds"
s["@JadeDoll"] = "LibCustomIcons/icons/misc6/JadeDoll.dds"
s["@Brassmoose"] = "LibCustomIcons/icons/misc6/Brassmoose.dds"
s["@beezii"] = "LibCustomIcons/icons/misc6/beezii_3.dds"
s["@RAGE_Xiomar"] = "LibCustomIcons/icons/misc6/RAGE_Xiomar.dds"
s["@Squeamishh"] = "LibCustomIcons/icons/misc6/Squeamishh.dds"
s["@xablauzin"] = "LibCustomIcons/icons/misc6/xablauzin.dds"
s["@Darkend_Skye"] = "LibCustomIcons/icons/misc6/Darkend_Skye.dds"
s["@Kadamey"] = "LibCustomIcons/icons/misc6/Kadamey.dds"
s["@Dn8sH"] = "LibCustomIcons/icons/misc6/Dn8sH.dds"
s["@SARAH_KSA"] = "LibCustomIcons/icons/misc6/SARAH_KSA.dds"
s["@xS1n15t3r_F0rc3x"] = "LibCustomIcons/icons/misc6/xS1n15t3r_F0rc3x.dds"
s["@EinSchaefchen"] = "LibCustomIcons/icons/misc6/EinSchaefchen.dds"
s["@Envertebrate"] = "LibCustomIcons/icons/misc6/Envertebrate.dds"
s["@Jerdiss"] = "LibCustomIcons/icons/misc6/Jerdiss.dds"
s["@InTenssiv"] = "LibCustomIcons/icons/misc6/InTenssiv.dds"
s["@PinotGringo"] = "LibCustomIcons/icons/misc6/PinotGringo.dds"
s["@NobbyBobby"] = "LibCustomIcons/icons/misc6/NobbyBobby.dds"
s["@happy_p1neapple"] = "LibCustomIcons/icons/misc6/happy_p1neapple.dds"
s["@x-r"] = "LibCustomIcons/icons/misc6/x-r.dds"
s["@Robthecoolio"] = "LibCustomIcons/icons/misc6/Robthecoolio.dds"
s["@ZzLazyCat"] = "LibCustomIcons/icons/misc6/ZzLazyCat.dds"
s["@ExcelUK"] = "LibCustomIcons/icons/misc6/ExcelUK.dds"
s["@Eljin_Eryr"] = "LibCustomIcons/icons/misc6/Eljin_Eryr.dds"
s["@vanillasalt"] = "LibCustomIcons/icons/misc6/vanillasalt.dds"
s["@JabbaSnowHaze"] = "LibCustomIcons/icons/misc6/JabbaSnowHaze.dds"
s["@meanmegan"] = "LibCustomIcons/icons/misc6/meanmegan.dds"
s["@Valoryen"] = "LibCustomIcons/icons/misc6/Valoryen.dds"
s["@NATE_PK"] = "LibCustomIcons/icons/misc6/NATE_PK.dds"
s["@Kempo1597"] = "LibCustomIcons/icons/misc6/Kempo1597.dds"
s["@beijixiong987"] = "LibCustomIcons/icons/misc6/beijixiong987.dds"
s["@Gendizer"] = "LibCustomIcons/icons/misc6/Gendizer.dds"
s["@Istala"] = "LibCustomIcons/icons/misc6/Istala.dds"
s["@BrainFartLoL"] = "LibCustomIcons/icons/misc6/BrainFartLoL_4.dds"
s["@OwLu"] = "LibCustomIcons/icons/misc6/OwLu.dds"
s["@Naomi_helluva"] = "LibCustomIcons/icons/misc6/Naomi_helluva.dds"
s["@Gushenpai"] = "LibCustomIcons/icons/misc6/Gushenpai.dds"
s["@Magnolyon"] = "LibCustomIcons/icons/misc6/Magnolyon.dds"
s["@Aytix"] = "LibCustomIcons/icons/misc6/Aytix.dds"
s["@ShaqShoes"] = "LibCustomIcons/icons/misc6/ShaqShoes.dds"
s["@Unprincesslike"] = "LibCustomIcons/icons/misc6/Unprincesslike.dds"
a["@Pasongsong"] = {"LibCustomIcons/icons/misc6/Pasongsong_anim.dds", 11, 2, 32}
s["@c_lout"] = "LibCustomIcons/icons/misc6/c_lout.dds"
s["@MurderingTacos"] = "LibCustomIcons/icons/misc6/MurderingTacos.dds"
s["@BLTNJ"] = "LibCustomIcons/icons/misc6/BLTNJ.dds"
s["@Glacial.Skadi"] = "LibCustomIcons/icons/misc6/Glacial.Skadi.dds"
s["@Paradoxdruid"] = "LibCustomIcons/icons/misc6/Paradoxdruid.dds"
s["@lTomie"] = "LibCustomIcons/icons/misc6/lTomie.dds"
s["@ErebosMortuus"] = "LibCustomIcons/icons/misc6/ErebosMortuus.dds"
s["@nick59349"] = "LibCustomIcons/icons/misc6/nick59349.dds"
s["@Varspaun"] = "LibCustomIcons/icons/misc6/Varspaun.dds"
s["@Mikey-Sano"] = "LibCustomIcons/icons/misc6/Mikey-Sano.dds"
s["@Misono'Mika"] = "LibCustomIcons/icons/misc6/MisonoMika_2.dds"
s["@Kamii-i"] = "LibCustomIcons/icons/misc6/Kamii-i_3.dds"
s["@PrincessMinnie.93"] = "LibCustomIcons/icons/misc6/PrincessMinnie.93.dds"
s["@OrIando"] = "LibCustomIcons/icons/misc6/OrIando.dds"
s["@MajesticUnicorn173"] = "LibCustomIcons/icons/misc6/MajesticUnicorn173.dds"
s["@Yujie"] = "LibCustomIcons/icons/misc6/Yujie_3.dds"
s["@Azsharah"] = "LibCustomIcons/icons/misc6/Azsharah.dds"
s["@BlackSkyMooN"] = "LibCustomIcons/icons/misc6/BlackSkyMooN.dds"
s["@bakabrick"] = "LibCustomIcons/icons/misc6/bakabrick.dds"
s["@TheCyberSniper"] = "LibCustomIcons/icons/misc6/TheCyberSniper.dds"
s["@SkylerBluee"] = "LibCustomIcons/icons/misc6/SkylerBluee.dds"
s["@NyxNyxNyxNyxNyx"] = "LibCustomIcons/icons/misc6/NyxNyxNyxNyxNyx.dds"
s["@SparkRip"] = "LibCustomIcons/icons/misc6/SparkRip.dds"
s["@FINEJADE"] = "LibCustomIcons/icons/misc6/FINEJADE.dds"
s["@nomoretoast"] = "LibCustomIcons/icons/misc6/nomoretoast.dds"
s["@tom6143346"] = "LibCustomIcons/icons/misc6/tom6143346.dds"
s["@RedKz4"] = "LibCustomIcons/icons/misc6/RedKz4.dds"
s["@zanyxx"] = "LibCustomIcons/icons/misc6/zanyxx.dds"
s["@LexxEzz"] = "LibCustomIcons/icons/misc6/LexxEzz.dds"
s["@FireyHellHound"] = "LibCustomIcons/icons/misc6/FireyHellHound.dds"
s["@ext_fish"] = "LibCustomIcons/icons/misc6/ext_fish.dds"
s["@KIANSOP"] = "LibCustomIcons/icons/misc6/KIANSOP.dds"
s["@Missina"] = "LibCustomIcons/icons/misc6/Missina.dds"
s["@ChiLLOutZ808"] = "LibCustomIcons/icons/misc6/ChiLLOutZ808.dds"
s["@ThrashersShogun"] = "LibCustomIcons/icons/misc6/ThrashersShogun.dds"
s["@Arbuz"] = "LibCustomIcons/icons/misc6/Arbuz.dds"
s["@ShreK20"] = "LibCustomIcons/icons/misc6/ShreK20.dds"
s["@DarkFreireich"] = "LibCustomIcons/icons/misc6/DarkFreireich.dds"
s["@LunaAdLumina"] = "LibCustomIcons/icons/misc6/LunaAdLumina.dds"
s["@WillzoBoB"] = "LibCustomIcons/icons/misc6/WillzoBoB_2.dds"
s["@Dezmonteri"] = "LibCustomIcons/icons/misc6/Dezmonteri.dds"
s["@TheBearOfTamriel"] = "LibCustomIcons/icons/misc6/TheBearOfTamriel.dds"
s["@notsojuicy"] = "LibCustomIcons/icons/misc6/notsojuicy.dds"
s["@TheBardAtTheInn"] = "LibCustomIcons/icons/misc6/TheBardAtTheInn.dds"
s["@ThePandaOfTamriel"] = "LibCustomIcons/icons/misc6/ThePandaOfTamriel.dds"
s["@KiFFeinTheBeast"] = "LibCustomIcons/icons/misc6/KiFFeinTheBeast.dds"
s["@Exxod7"] = "LibCustomIcons/icons/misc6/Exxod7.dds"
s["@AlmostHappy"] = "LibCustomIcons/icons/misc6/AlmostHappy.dds"
s["@cptnn3m0"] = "LibCustomIcons/icons/misc6/cptnn3m0.dds"
s["@StefHanma"] = "LibCustomIcons/icons/misc6/StefHanma.dds"
s["@AcidiiS"] = "LibCustomIcons/icons/misc6/AcidiiS_4.dds"
s["@BadBehavior_ESO"] = "LibCustomIcons/icons/misc6/BadBehavior_ESO.dds"
s["@Janika23"] = "LibCustomIcons/icons/misc6/Janika23.dds"
s["@PARASIT3"] = "LibCustomIcons/icons/misc6/PARASIT3.dds"
s["@Silvamus"] = "LibCustomIcons/icons/misc6/Silvamus.dds"
s["@Nahlot_Sunvaar"] = "LibCustomIcons/icons/misc6/Nahlot_Sunvaar.dds"
s["@Arabeiia"] = "/esoui/art/icons/class/class_nightblade.dds"
s["@Treuce"] = "LibCustomIcons/icons/misc6/Treuce_2.dds"
s["@Treuce2"] = s["@Treuce"]
s["@Admiral_Schneider"] = "LibCustomIcons/icons/misc6/Admiral_Schneider.dds"
s["@Analiesa"] = "LibCustomIcons/icons/misc6/Analiesa.dds"
s["@SenseiKazuro"] = "LibCustomIcons/icons/misc6/SenseiKazuro.dds"
s["@T.exe"] = "LibCustomIcons/icons/misc6/T.exe.dds"
s["@Z.emy"] = "LibCustomIcons/icons/misc6/Z.emy.dds"
s["@ESONEWS"] = "LibCustomIcons/icons/misc6/ESONEWS.dds"
s["@Doomzdey"] = "LibCustomIcons/icons/misc6/Doomzdey_2.dds"
s["@Sootica"] = "LibCustomIcons/icons/misc6/Sootica.dds"
s["@Boulder_Dash"] = "LibCustomIcons/icons/misc6/Boulder_Dash.dds"
s["@Tattles"] = "LibCustomIcons/icons/misc6/Tattles.dds"
s["@dongdaye8848"] = "LibCustomIcons/icons/misc6/dongdaye8848.dds"
s["@OhMyGodcat"] = "LibCustomIcons/icons/misc6/OhMyGodcat.dds"
s["@SeanDUrban"] = "LibCustomIcons/icons/misc6/SeanDUrban.dds"
s["@mettaleggroll"] = "LibCustomIcons/icons/misc6/mettaleggroll.dds"
s["@Flauschefluff"] = "LibCustomIcons/icons/misc6/Flauschefluff.dds"
s["@OfeliaNox"] = "LibCustomIcons/icons/misc6/OfeliaNox.dds"
s["@Nabbz"] = "LibCustomIcons/icons/misc6/Nabbz.dds"
s["@JustFitzy"] = "LibCustomIcons/icons/misc6/JustFitzy.dds"
s["@Zorgslayer"] = "LibCustomIcons/icons/misc6/Zorgslayer.dds"
s["@Gojo_Senpai"] = "LibCustomIcons/icons/misc6/Gojo_Senpai.dds"
s["@SnowPhoeniix"] = "LibCustomIcons/icons/misc6/SnowPhoeniix.dds"
s["@CyberSpektre"] = "LibCustomIcons/icons/misc6/CyberSpektre.dds"
s["@Phoenix_Firex"] = "LibCustomIcons/icons/misc6/Phoenix_Firex.dds"
s["@Vinterskald"] = "LibCustomIcons/icons/misc6/Vinterskald.dds"
s["@Ryanater2302"] = "LibCustomIcons/icons/misc6/Ryanater2302.dds"
s["@abc_legend"] = "LibCustomIcons/icons/misc6/abc_legend.dds"
s["@Unbekannt666"] = "LibCustomIcons/icons/misc6/Unbekannt666.dds"
s["@Light_Escapes"] = "LibCustomIcons/icons/misc6/Light_Escapes.dds"
s["@Viralissa"] = "LibCustomIcons/icons/misc6/Viralissa.dds"
s["@EmberleyMarie"] = "LibCustomIcons/icons/misc6/EmberleyMarie.dds"
s["@ReLaxz33"] = "LibCustomIcons/icons/misc6/ReLaxz33_2.dds"
s["@Krümellöwe"] = "LibCustomIcons/icons/misc6/Krumellowe.dds"
s["@DerAlpha"] = "LibCustomIcons/icons/misc6/DerAlpha.dds"
s["@BansheeVT"] = "LibCustomIcons/icons/misc6/BansheeVT.dds"
s["@W0ff3l"] = "LibCustomIcons/icons/misc6/W0ff3l.dds"
s["@Anima5683"] = "LibCustomIcons/icons/misc6/Anima5683.dds"
s["@Grimlock4914"] = "LibCustomIcons/icons/misc6/Grimlock4914.dds"
s["@Kaus-sirrah"] = "LibCustomIcons/icons/misc6/Kaus-sirrah.dds"
s["@Fyeur"] = "LibCustomIcons/icons/misc6/Fyeur.dds"
s["@Necromist"] = "LibCustomIcons/icons/misc6/Necromist.dds"
s["@Kowalski2684"] = "LibCustomIcons/icons/misc6/Kowalski2684.dds"
s["@Deodei"] = "LibCustomIcons/icons/misc6/Deodei.dds"
s["@Tutorion"] = "LibCustomIcons/icons/misc6/Tutorion.dds"
s["@xZephyria"] = "LibCustomIcons/icons/misc6/xZephyria.dds"
s["@BillyBoah"] = "LibCustomIcons/icons/misc6/BillyBoah.dds"
s["@JJSugar"] = "LibCustomIcons/icons/misc6/JJSugar.dds"
s["@Lightshroom"] = "LibCustomIcons/icons/misc6/Lightshroom.dds"
s["@Nedchik"] = "LibCustomIcons/icons/misc6/Nedchik_2.dds"
s["@BradyNATO7"] = "LibCustomIcons/icons/misc6/BradyNATO7.dds"
s["@clqq"] = "LibCustomIcons/icons/misc6/clqq.dds"
s["@dragonflames67"] = "LibCustomIcons/icons/misc6/dragonflames67.dds"
s["@Gaijinmarket"] = "LibCustomIcons/icons/misc6/Gaijinmarket.dds"
s["@TuonyS"] = "LibCustomIcons/icons/misc6/TuonyS.dds"
s["@aWanderingMuse"] = "LibCustomIcons/icons/misc6/aWanderingMuse.dds"
s["@choco'holic"] = "LibCustomIcons/icons/misc6/chocoholic.dds"
s["@anather.wolfy"] = "LibCustomIcons/icons/misc6/anather.wolfy.dds"
s["@Shaxigaming"] = "LibCustomIcons/icons/misc6/Shaxigaming.dds"
s["@Vapurity"] = "LibCustomIcons/icons/misc6/Vapurity.dds"
s["@Kermit417"] = "LibCustomIcons/icons/misc6/Kermit417.dds"
s["@TheLegend272"] = "LibCustomIcons/icons/misc6/TheLegend272.dds"
s["@NemeCruz"] = "LibCustomIcons/icons/misc6/NemeCruz.dds"
s["@peinhunter"] = "LibCustomIcons/icons/misc6/peinhunter.dds"
s["@lPvtgumpl"] = "LibCustomIcons/icons/misc6/lPvtgumpl.dds"
s["@ugaduga"] = "LibCustomIcons/icons/misc6/ugaduga.dds"
s["@DarkfireDreams"] = "LibCustomIcons/icons/misc6/DarkfireDreams.dds"
s["@VenomSheru"] = "LibCustomIcons/icons/misc6/VenomSheru.dds"
s["@cure.inc"] = "LibCustomIcons/icons/misc6/cure.inc.dds"
s["@Goetzsson"] = "LibCustomIcons/icons/misc6/Goetzsson.dds"
s["@Ciallo_0721"] = "LibCustomIcons/icons/misc6/Ciallo_0721.dds"
s["@tristanwho"] = "LibCustomIcons/icons/misc6/tristanwho.dds"
s["@Gopher07"] = "LibCustomIcons/icons/misc6/Gopher07.dds"
s["@Iseias"] = "LibCustomIcons/icons/misc6/Iseias.dds"
s["@YellowDream"] = "LibCustomIcons/icons/misc6/YellowDream.dds"
s["@Shtille"] = "LibCustomIcons/icons/misc6/shtille.dds"
s["@Chibiman007"] = "LibCustomIcons/icons/misc6/Chibiman007.dds"
s["@Constant-REM"] = "LibCustomIcons/icons/misc6/Constant-REM.dds"
s["@Dj-Lynx"] = "LibCustomIcons/icons/misc6/Dj-Lynx.dds"
s["@mTwsnake"] = "LibCustomIcons/icons/misc6/mTwsnake.dds"
s["@Matthiiass"] = "LibCustomIcons/icons/misc6/Matthiiass.dds"
s["@Duesentrieb"] = "LibCustomIcons/icons/misc6/Duesentrieb.dds"
s["@Naruto_kun"] = "LibCustomIcons/icons/misc6/Naruto_kun.dds"
s["@Saske_Kun"] = "LibCustomIcons/icons/misc6/Saske_kun.dds"
s["@cujokills"] = "LibCustomIcons/icons/misc6/cujokills_2.dds"
s["@Kraaii"] = "LibCustomIcons/icons/misc6/Kraaii.dds"
s["@ss1978473006"] = "LibCustomIcons/icons/misc6/ss1978473006.dds"
s["@tl2655993"] = "LibCustomIcons/icons/misc6/tl2655993.dds"
s["@PureGG"] = "LibCustomIcons/icons/misc6/PureGG.dds"
s["@Yoda_33"] = "LibCustomIcons/icons/misc6/Yoda_33.dds"
s["@obiz"] = "LibCustomIcons/icons/misc6/obiz_anim.dds"
s["@quethrosar"] = "LibCustomIcons/icons/misc6/quethrosar.dds"
s["@Aljea"] = "LibCustomIcons/icons/misc6/Aljea.dds"
a["@M1stic"] = {"LibCustomIcons/icons/misc6/M1stic_anim.dds", 5, 1, 14}
s["@Kyip"] = "LibCustomIcons/icons/misc6/Kyip.dds"
s["@MrBevells"] = "LibCustomIcons/icons/misc6/MrBevells.dds"
s["@murder.hobo"] = "LibCustomIcons/icons/misc6/murderhobo.dds"
s["@MaeanaEso"] = "LibCustomIcons/icons/misc6/MaeanaEso.dds"
s["@Caspase3-TNF"] = "LibCustomIcons/icons/misc6/Caspase3-TNF.dds"
s["@Acid-Glow"] = "LibCustomIcons/icons/misc6/Acid-Glow_2.dds"
s["@Dino1994"] = "LibCustomIcons/icons/misc6/Dino1994.dds"
s["@V33NUS"] = "LibCustomIcons/icons/misc6/V33NUS.dds"
s["@JustEndeavour"] = "LibCustomIcons/icons/misc6/JustEndeavour_2.dds"
s["@Gynormus"] = "LibCustomIcons/icons/misc6/Gynormus.dds"
s["@Flamebuckler"] = "LibCustomIcons/icons/misc6/Flamebuckler.dds"
s["@moysiades"] = "LibCustomIcons/icons/misc6/moysiades.dds"
s["@Flavosaurus"] = "LibCustomIcons/icons/misc6/Flavosaurus.dds"
s["@SekoTallo"] = "LibCustomIcons/icons/misc6/SekoTallo.dds"
s["@NexiiZ_I"] = "LibCustomIcons/icons/misc6/NexiiZ_I.dds"
s["@Frankluckone"] = "LibCustomIcons/icons/misc6/Frankluckone.dds"
s["@Schwarzes_Nirn"] = "LibCustomIcons/icons/misc6/Schwarzes_Nirn.dds"
s["@Raspberry41"] = "LibCustomIcons/icons/misc6/Raspberry41.dds"
s["@ChrisaSweetfoxy"] = "LibCustomIcons/icons/misc6/ChrisaSweetfoxy.dds"
s["@I'm-A_Femboy"] = "LibCustomIcons/icons/misc6/Im-A_Femboy.dds"
s["@haze068"] = "LibCustomIcons/icons/misc6/haze068.dds"
a["@haze068"] = {"LibCustomIcons/icons/misc6/haze068_anim.dds", 24, 1, 15}
s["@Dark.Anima"] = "LibCustomIcons/icons/misc6/Dark.Anima.dds"
s["@twopups"] = "LibCustomIcons/icons/misc6/twopups.dds"
s["@ToxicTenshii"] = "LibCustomIcons/icons/misc6/ToxicTenshii.dds"
s["@A66adon"] = "LibCustomIcons/icons/misc6/A66adon.dds"
s["@BYC2OR"] = "LibCustomIcons/icons/misc6/BYC2OR.dds"
s["@Arkti_kA"] = "LibCustomIcons/icons/misc6/Arkti_kA.dds"
s["@roasted.garlic"] = "LibCustomIcons/icons/flags/usa.dds"
s["@nastusenysh"] = "LibCustomIcons/icons/misc6/nastusenysh.dds"
s["@frogthroat"] = "LibCustomIcons/icons/misc6/frogthroat.dds"
s["@TheArtofBreaking92"] = "LibCustomIcons/icons/misc6/TheArtofBreaking92.dds"
s["@Briezy"] = "LibCustomIcons/icons/misc6/Briezy.dds"
s["@Helenar"] = "LibCustomIcons/icons/misc6/Helenar.dds"
a["@GodSoma"] = {"LibCustomIcons/icons/misc6/GodSoma_anim.dds", 12, 1, 10}
a["@scorch061"] = {"LibCustomIcons/icons/misc6/scorch061_anim.dds", 23, 2, 20}
a["@chaoticbubbles"] = {"LibCustomIcons/icons/misc6/chaoticbubbles_anim.dds", 13, 3, 25}
a["@Dessmer"] = {"LibCustomIcons/icons/misc6/Dessmer_anim.dds", 10, 5, 33}
a["@DeprivedChalkline"] = {"LibCustomIcons/icons/misc6/DeprivedChalkline_anim_4.dds", 39, 1, 20}
a["@Holytwinkie"] = {"LibCustomIcons/icons/misc6/Holytwinkie_anim2.dds", 5, 3, 10}
a["@Maybecup"] = {"LibCustomIcons/icons/misc6/Maybecup_anim2.dds", 12, 1, 12.5}
a["@zingerbox69"] = {"LibCustomIcons/icons/misc6/zingerbox69_anim_2.dds", 5, 3, 10}
a["@KiaraCastello"] = {"LibCustomIcons/icons/misc6/KiaraCastello_anim.dds", 12, 1, 9}
a["@Innodo"] = {"LibCustomIcons/icons/misc6/Innodo_anim.dds", 14, 1, 20}
a["@xReLoadUix4"] = {"LibCustomIcons/icons/misc6/xReLoadUix4_anim_2.dds", 9, 1, 4}
a["@blatherers"] = {"LibCustomIcons/icons/misc6/blatherers_anim1.dds", 12, 1, 5}
a["@worries"] = {"LibCustomIcons/icons/misc6/worries_anim.dds", 10, 5, 10}
a["@SoulEater111"] = {"LibCustomIcons/icons/misc6/SoulEater111_anim2.dds", 7, 1, 7}
a["@De4D3Ye1"] = {"LibCustomIcons/icons/misc6/De4D3Ye1_anim.dds", 12, 1, 1.5}
a["@Kage997"] = {"LibCustomIcons/icons/misc6/Kage997_anim.dds", 10, 1, 9}
a["@powfu"] = {"LibCustomIcons/icons/misc6/powfu_anim.dds", 9, 2, 10}
a["@Damzses"] = {"LibCustomIcons/icons/misc6/Damzses_anim2.dds", 8, 6, 25}
a["@Unholy_Magic"] = {"LibCustomIcons/icons/misc6/Unholy_Magic_anim.dds", 13, 2, 17}
a["@pnewmont"] = {"LibCustomIcons/icons/misc6/pnewmont_anim.dds", 12, 1, 12.5}
a["@FlameFox_TTV"] = {"LibCustomIcons/icons/misc6/FlameFox_TTV_anim_2.dds", 16, 1, 10}
a["@Solu_s"] = {"LibCustomIcons/icons/misc6/Solu_s_anim.dds", 16, 1, 50}
a["@gqx1079604284"] = {"LibCustomIcons/icons/misc6/gqx1079604284_anim.dds", 10, 1, 10}
a["@kewcioprala"] = {"LibCustomIcons/icons/misc6/kewcioprala_anim.dds", 12, 1, 10}
a["@cowskybaby"] = {"LibCustomIcons/icons/misc6/cowskybaby_anim.dds", 17, 2, 12.5}
a["@the_joke"] = {"LibCustomIcons/icons/misc6/the_joke_anim.dds", 6, 4, 10}
a["@Es'cliff"] = {"LibCustomIcons/icons/misc6/Escliff_anim.dds", 9, 3, 7}
a["@Loddiko"] = {"LibCustomIcons/icons/misc6/Loddiko_anim.dds", 23, 2, 20}
a["@llEarendill"] = {"LibCustomIcons/icons/misc6/llEarendill_anim.dds", 10, 1, 25}
a["@Aang7"] = {"LibCustomIcons/icons/misc6/Aang7_anim.dds", 9, 5, 10}
a["@p'eps"] = {"LibCustomIcons/icons/misc6/peps_anim2.dds", 12, 1, 6}
a["@TheArcticElysium"] = {"LibCustomIcons/icons/misc6/TheArcticElysium_anim.dds", 7, 5, 25}
a["@jettythemeatloaf"] = {"LibCustomIcons/icons/misc6/jettythemeatloaf_anim.dds", 19, 1, 5}
a["@stellarria"] = {"LibCustomIcons/icons/misc6/stellarria_anim.dds", 10, 5, 25}
a["@ZweiFass4"] = {"LibCustomIcons/icons/misc6/ZweiFass4_anim.dds", 10, 5, 10}
a["@OliSP"] = {"LibCustomIcons/icons/misc6/OliSP_anim.dds", 10, 3, 10}
a["@hfblade"] = {"LibCustomIcons/icons/misc6/hfblade_anim.dds", 7, 4, 14}
a["@Khan0s"] = {"LibCustomIcons/icons/misc6/Khan0s_anim.dds", 8, 6, 25}
a["@KevinLovegood"] = {"LibCustomIcons/icons/misc6/KevinLovegood_anim.dds", 10, 1, 10}
a["@StoneyTheCat"] = {"LibCustomIcons/icons/misc6/StoneyTheCat_anim_2.dds", 10, 5, 17}
a["@oHarlock"] = {"LibCustomIcons/icons/misc6/oHarlock_anim.dds", 7, 2, 17}
a["@Su-Shi"] = {"LibCustomIcons/icons/misc6/Su-Shi_anim.dds", 14, 3, 50}
a["@KlyRobin"] = {"LibCustomIcons/icons/misc6/KlyRobin_anim.dds", 16, 1, 2}
a["@Panache1120"] = {"LibCustomIcons/icons/misc6/Panache1120_anim.dds", 6, 6, 12.5}
a["@Bjr54"] = {"LibCustomIcons/icons/misc6/Bjr54_anim.dds", 6, 5, 19}
a["@BIGG'0730"] = {"LibCustomIcons/icons/misc6/BIGG0730_anim_4.dds", 10, 5, 25}
a["@zmph"] = {"LibCustomIcons/icons/misc6/zmph_anim.dds", 23, 2, 25}
a["@master_Extended"] = {"LibCustomIcons/icons/misc6/master_Extended_anim.dds", 9, 3, 11}
a["@Paidakia"] = {"LibCustomIcons/icons/misc6/Paidakia_anim.dds", 10, 1, 11}
a["@Circé0.0"] = {"LibCustomIcons/icons/misc6/Circe0.0_anim.dds", 9, 3, 20}
a["@Ophryoglena"] = {"LibCustomIcons/icons/misc6/Ophryoglena_anim1.dds", 8, 5, 10}
a["@jjev"] = {"LibCustomIcons/icons/misc6/jjev_anim.dds", 7, 2, 10}
a["@AmaoCN"] = {"LibCustomIcons/icons/misc6/AmaoCN_anim.dds", 19, 1, 10}
a["@mup7h"] = {"LibCustomIcons/icons/misc6/mup7h_anim.dds", 16, 1, 12}
a["@GanjaRuss"] = {"LibCustomIcons/icons/misc6/GanjaRuss_anim.dds", 15, 1, 5}
a["@S.ïvv"] = {"LibCustomIcons/icons/misc6/S.ivv_anim_4.dds", 10, 5, 25}
a["@izgoose"] = {"LibCustomIcons/icons/misc6/izgoose_anim.dds", 5, 3, 16}
a["@NewZiBit"] = {"LibCustomIcons/icons/misc6/NewZiBit_anim.dds", 16, 1, 16}
a["@shinby"] = {"LibCustomIcons/icons/misc6/shinby_anim.dds", 6, 6, 21}
a["@Ervani"] = {"LibCustomIcons/icons/misc6/Ervani_anim.dds", 8, 1, 10}
a["@green-fyah"] = {"LibCustomIcons/icons/misc6/green-fyah_anim.dds", 10, 5, 25}
a["@NoahJay"] = {"LibCustomIcons/icons/misc6/NoahJay_anim2.dds", 6, 1, 5}
a["@Rastananana"] = {"LibCustomIcons/icons/misc6/Rastananana_anim.dds", 6, 3, 7}
a["@Nater"] = {"LibCustomIcons/icons/misc6/Nater_anim.dds", 7, 3, 11}
a["@Texou13"] = {"LibCustomIcons/icons/misc6/Texou13_anim2.dds", 6, 1, 10}
a["@Moranker"] = {"LibCustomIcons/icons/misc6/Moranker_anim2.dds", 13, 1, 20}
s["@Slaytania"] = "LibCustomIcons/icons/misc6/Slaytania.dds"
a["@Slaytania"] = {"LibCustomIcons/icons/misc6/Slaytania_anim_2.dds", 6, 3, 10}
a["@rjYassi"] = {"LibCustomIcons/icons/misc6/rjYassi_anim.dds", 10, 5, 9}
s["@KuraidamaSetsuro"] = "LibCustomIcons/icons/misc6/KuraidamaSetsuro.dds"
a["@KuraidamaSetsuro"] = {"LibCustomIcons/icons/misc6/KuraidamaSetsuro_anim.dds", 14, 1, 17}
a["@Minervyr"] = {"LibCustomIcons/icons/misc6/Minervyr_anim.dds", 12, 1, 5}
a["@S1NGL3"] = {"LibCustomIcons/icons/misc6/S1NGL3_anim.dds", 5, 5, 14}
a["@Sotiriou"] = {"LibCustomIcons/icons/misc6/Sotiriou_anim.dds", 7, 4, 8}
a["@Q.wazz"] = {"LibCustomIcons/icons/misc6/Q.wazz_anim.dds", 16, 1, 8}
a["@Highmaje"] = {"LibCustomIcons/icons/misc6/Highmaje_anim.dds", 13, 1, 8}
a["@Tenzeii"] = {"LibCustomIcons/icons/misc6/Tenzeii_anim.dds", 16, 1, 10}
a["@damionchow"] = {"LibCustomIcons/icons/misc6/damionchow_anim.dds", 6, 5, 17}
a["@CodeKatana"] = {"LibCustomIcons/icons/misc6/CodeKatana_anim1.dds", 31, 1, 22}
a["@Sugar-free_cake"] = {"LibCustomIcons/icons/misc6/Sugar-free_cake_anim_3.dds", 12, 1, 15}
a["@nord.wallace"] = {"LibCustomIcons/icons/misc6/nordwallace_anim.dds", 12, 1, 10}
a["@SmasharooIsOld"] = {"LibCustomIcons/icons/misc6/SmasharooIsOld_anim.dds", 9, 1, 20}
a["@RENG3406"] = {"LibCustomIcons/icons/misc6/RENG3406_anim.dds", 10, 1, 6}
a["@LKW0602"] = {"LibCustomIcons/icons/misc6/LKW0602_anim.dds", 10, 5, 33}
a["@Astoria0"] = {"LibCustomIcons/icons/misc6/Astoria0_anim.dds", 7, 6, 20}
a["@gao3721"] = {"LibCustomIcons/icons/misc6/gao3721_anim.dds", 9, 1, 12}
a["@Sweetink"] = {"LibCustomIcons/icons/misc6/Sweetink_anim.dds", 11, 4, 10}
a["@Seminolegirl1992"] = {"LibCustomIcons/icons/misc6/Seminolegirl1992_anim.dds", 10, 1, 10}
a["@CookieMan69"] = {"LibCustomIcons/icons/misc6/CookieMan69_anim.dds", 4, 2, 12.5}
a["@Damsik9673"] = {"LibCustomIcons/icons/misc6/damsik9673_anim.dds", 10, 5, 9}
a["@Crazy-47"] = {"LibCustomIcons/icons/misc6/Crazy-47_anim.dds", 8, 1, 10}
a["@Yumio"] = {"LibCustomIcons/icons/misc6/Yumio_anim_2.dds", 6, 1, 14}
a["@rara5"] = {"LibCustomIcons/icons/misc6/rara5_anim.dds", 9, 1, 10}
a["@rayremind"] = {"LibCustomIcons/icons/misc6/rayremind_anim.dds", 29, 1, 8}
a["@Bastekk"] = {"LibCustomIcons/icons/misc6/Bastekk_anim.dds", 8, 6, 30}
a["@Kaellora"] = {"LibCustomIcons/icons/misc6/Kaellora_anim.dds", 6, 5, 33}
a["@YiHe"] = {"LibCustomIcons/icons/misc6/YiHe_anim.dds", 6, 5, 20}
a["@kellesabelle"] = {"LibCustomIcons/icons/misc6/kellesabelle_anim.dds", 10, 1, 12.5}
a["@scarecrowemm"] = {"LibCustomIcons/icons/misc6/scarecrowemm_anim.dds", 10, 1, 12}
a["@AsheraTepes"] = {"LibCustomIcons/icons/misc6/AsheraTepes_anim.dds", 7, 7, 24}
a["@o153456342"] = {"LibCustomIcons/icons/misc6/o153456342_anim.dds", 10, 5, 20}
a["@Meemac"] = {"LibCustomIcons/icons/misc6/Meemac_anim.dds", 10, 5, 17}
a["@The_Hema"] = {"LibCustomIcons/icons/misc6/The_Hema_anim2.dds", 11, 3, 25}
a["@Brio115"] = {"LibCustomIcons/icons/misc6/Brio115_anim__1.dds", 19, 1, 10}
a["@arie.sian"] = {"LibCustomIcons/icons/misc6/arie.sian_anim.dds", 17, 1, 17}
a["@DelphoxPrime"] = {"LibCustomIcons/icons/misc6/DelphoxPrime_anim_2.dds", 7, 2, 7}
a["@Jayela7w7"] = {"LibCustomIcons/icons/misc6/Jayela7w7_anim.dds", 10, 5, 12}
a["@Kai'lynn"] = {"LibCustomIcons/icons/misc6/Kailynn_anim.dds", 9, 1, 10}
a["@Wolf_z13"] = {"LibCustomIcons/icons/misc6/Wolf_z13_anim.dds", 23, 1, 10}
a["@IKeepYourSoul"] = {"LibCustomIcons/icons/misc6/IKeepYourSoul_anim.dds", 17, 2, 20}
a["@Bahdezdiil"] = {"LibCustomIcons/icons/misc6/Bahdezdiil_anim.dds", 8, 1, 25}
a["@scherni"] = {"LibCustomIcons/icons/misc6/scherni_anim.dds", 10, 3, 25}
a["@PartialGrub66"] = {"LibCustomIcons/icons/misc6/PartialGrub66_anim.dds", 6, 6, 9}
a["@Numzy"] = {"LibCustomIcons/icons/misc6/Numzy_anim_3.dds", 6, 2, 10}
a["@Honk-Honk"] = {"LibCustomIcons/icons/misc6/Honk-Honk_anim.dds", 10, 5, 8}
a["@Amiish"] = {"LibCustomIcons/icons/misc6/Amiish_anim.dds", 31, 1, 33}
a["@ROTUS-WONG"] = {"LibCustomIcons/icons/misc6/ROTUS-WONG_anim.dds", 8, 6, 8}
a["@Floki-i"] = {"LibCustomIcons/icons/misc6/Floki-i_anim_2.dds", 8, 6, 33}
a["@Chris.Nr.7"] = {"LibCustomIcons/icons/misc6/Chris.Nr.7_anim.dds", 14, 1, 12.5}
a["@kurumiii"] = {"LibCustomIcons/icons/misc6/kurumiii_anim.dds", 7, 4, 11}
a["@Bam.21"] = {"LibCustomIcons/icons/misc6/Bam.21_anim.dds", 11, 3, 10}
a["@MW2"] = {"LibCustomIcons/icons/misc6/MW2_anim_2.dds", 16, 2, 10}
a["@oBeanify"] = {"LibCustomIcons/icons/misc6/oBeanify_anim_2.dds", 7, 7, 29}
a["@Aorys"] = {"LibCustomIcons/icons/misc6/Aorys_anim.dds", 10, 5, 14}
a["@Dieu_Gradoque"] = {"LibCustomIcons/icons/misc6/Dieu_Gradoque_anim.dds", 16, 1, 17}
a["@BabyDragonStar"] = {"LibCustomIcons/icons/misc6/BabyDragonStar_anim.dds", 12, 1, 9}
a["@Shelldunk"] = {"LibCustomIcons/icons/misc6/Shelldunk_anim.dds", 8, 5, 33}
a["@pureiam"] = {"LibCustomIcons/icons/misc6/pureiam_anim.dds", 7, 3, 33}
a["@dream.s"] = {"LibCustomIcons/icons/misc6/dream.s_anim.dds", 7, 4, 20}
a["@Darkittani"] = {"LibCustomIcons/icons/misc6/Darkittani_anim.dds", 14, 1, 10}
a["@Dwarfchig"] = {"LibCustomIcons/icons/misc6/Dwarfchig_anim.dds", 5, 5, 12.5}
a["@Slaay"] = {"LibCustomIcons/icons/misc6/Slaay_anim.dds", 7, 1, 5}
a["@Shadow_Play"] = {"LibCustomIcons/icons/misc6/Shadow_Play_anim.dds", 10, 2, 23}
a["@XTheAvariciousX"] = {"LibCustomIcons/icons/misc6/XTheAvariciousX_anim.dds", 12, 1, 10}
a["@IIILaaLaaIII"] = {"LibCustomIcons/icons/misc6/IIILaaLaaIII_anim.dds", 5, 3, 7}
a["@phoueyyouey"] = {"LibCustomIcons/icons/misc6/phoueyyouey_anim.dds", 9, 3, 10}
a["@HaroBird"] = {"LibCustomIcons/icons/misc6/harobird_anim.dds", 10, 5, 50}
a["@AdiTriZ"] = {"LibCustomIcons/icons/misc6/AdiTriZ_anim.dds", 10, 1, 7}
a["@MissSoleOscuro"] = {"LibCustomIcons/icons/misc6/MissSoleOscuro_anim.dds", 9, 5, 20}
a["@p00tx"] = {"LibCustomIcons/icons/misc6/p00tx_anim.dds", 10, 5, 25}
a["@NanfengoubA"] = {"LibCustomIcons/icons/misc6/NanfengoubA_anim.dds", 8, 1, 7}
a["@Reynaile"] = {"LibCustomIcons/icons/misc6/Reynaile_anim.dds", 10, 2, 10}
a["@HotLikeWasab1"] = {"LibCustomIcons/icons/misc6/HotLikeWasab1_anim_2.dds", 7, 7, 33}
a["@SKUBIDUNSHA"] = {"LibCustomIcons/icons/misc6/SKUBIDUNSHA_anim.dds", 6, 1, 6}
a["@xXScOrPiON96Xx"] = {"LibCustomIcons/icons/misc6/xXScOrPiON96Xx_anim.dds", 5, 4, 20}
a["@DarkSp00n"] = {"LibCustomIcons/icons/misc6/DarkSp00n_anim.dds", 8, 6, 10}
a["@funkystatue2"] = {"LibCustomIcons/icons/misc6/funkystatue2_anim.dds", 6, 4, 14}
a["@hardmodes"] = {"LibCustomIcons/icons/misc6/hardmodes_anim_4.dds", 21, 1, 33}
a["@pipipipi"] = {"LibCustomIcons/icons/misc6/pipipipi_anim.dds", 23, 1, 12.5}
a["@XxxEscanoRxxX"] = {"LibCustomIcons/icons/misc6/XxxEscanoRxxX_anim.dds", 7, 1, 15}
a["@Iit"] = {"LibCustomIcons/icons/misc6/Iit_anim.dds", 7, 7, 10}
a["@RaDiAnTPeAcH"] = {"LibCustomIcons/icons/misc6/RaDiAnTPeAcH_anim_1.dds", 16, 1, 6}
a["@Mkhkovo"] = {"LibCustomIcons/icons/misc6/Mkhkovo_anim.dds", 8, 1, 17}
a["@zabyrocks"] = {"LibCustomIcons/icons/misc6/zabyrocks_anim.dds", 8, 1, 25}
a["@SIap"] = {"LibCustomIcons/icons/misc6/SIap_anim_2.dds", 31, 1, 20}
a["@CoolEyes"] = {"LibCustomIcons/icons/misc6/CoolEyes_anim.dds", 9, 2, 7.5}
a["@Blackified"] = {"LibCustomIcons/icons/misc6/Blackified_anim.dds", 7, 7, 33}
a["@Smirkies"] = {"LibCustomIcons/icons/misc6/Smirkies_anim.dds", 6, 1, 8}
a["@CORDEL1A"] = {"LibCustomIcons/icons/misc6/CORDEL1A_anim.dds", 9, 1, 10}
a["@eziaa"] = {"LibCustomIcons/icons/misc6/eziaa_anim_1.dds", 16, 2, 6}
a["@Rare_Form"] = {"LibCustomIcons/icons/misc6/Rare_Form_anim.dds", 21, 1, 20}
a["@DongLord-69"] = {"LibCustomIcons/icons/misc6/DongLord-69_anim.dds", 5, 2, 25}
a["@wnkbll"] = {"LibCustomIcons/icons/misc6/wnkbll_anim_2.dds", 9, 1, 10}
a["@RRReoll"] = {"LibCustomIcons/icons/misc6/RRReoll_anim.dds", 6, 4, 10}
a["@Xyn0psis"] = {"LibCustomIcons/icons/misc6/Xyn0psis_anim.dds", 10, 1, 10}
a["@noctislulou"] = {"LibCustomIcons/icons/misc6/noctislulou_anim.dds", 8, 1, 3}
a["@Bj-orn"] = {"LibCustomIcons/icons/misc6/Bj-orn_anim_2.dds", 10, 5, 13}
a["@Gearedtofire"] = {"LibCustomIcons/icons/misc6/Gearedtofire_anim.dds", 21, 1, 14.5}
a["@TheChaosApple"] = {"LibCustomIcons/icons/misc6/TheChaosApple_anim.dds", 6, 4, 10}
a["@Stereum"] = {"LibCustomIcons/icons/misc6/Stereum_anim.dds", 10, 1, 10}
a["@FujianMoon"] = {"LibCustomIcons/icons/misc6/FujianMoon_anim.dds", 10, 1, 8}
a["@RkRider"] = {"LibCustomIcons/icons/misc6/RkRider_anim.dds", 8, 1, 5}
a["@Unsterblich99"] = {"LibCustomIcons/icons/misc6/unsterblich99_anim.dds", 6, 1, 10}
a["@CadenzaWaffleFries"] = {"LibCustomIcons/icons/misc6/CadenzaWaffleFries_anim.dds", 7, 1, 10}
a["@df12386181"] = {"LibCustomIcons/icons/misc6/df12386181_anim.dds", 8, 1, 10}
a["@Kionney"] = {"LibCustomIcons/icons/misc6/Kionney_anim.dds", 7, 2, 8.5}
a["@Andrewklein13"] = {"LibCustomIcons/icons/misc6/Andrewklein13_anim.dds", 8, 1, 10}
a["@DelLvalLe"] = {"LibCustomIcons/icons/misc6/DelLvalLe_anim.dds", 8, 5, 20}
a["@Oldy_sk"] = {"LibCustomIcons/icons/misc6/Oldy_sk_anim.dds", 5, 5, 20}
a["@Pausten"] = {"LibCustomIcons/icons/misc6/Pausten_anim.dds", 9, 1, 20}
a["@n0us_2xh"] = {"LibCustomIcons/icons/misc6/n0us_2xh_anim.dds", 10, 1, 25}
a["@Shine9"] = {"LibCustomIcons/icons/misc6/Shine9_anim.dds", 12, 1, 20}
a["@VlleyCat"] = {"LibCustomIcons/icons/misc6/VlleyCat_anim.dds", 10, 5, 20}
a["@Armin_End"] = {"LibCustomIcons/icons/misc6/Armin_End_anim.dds", 7, 4, 3}
a["@komorebiZ"] = {"LibCustomIcons/icons/misc6/komorebiZ_anim.dds", 7, 6, 21}
a["@Perfect-Storm"] = {"LibCustomIcons/icons/misc6/Perfect-Storm_anim.dds", 9, 2, 8}
a["@DarkPhoeniix"] = {"LibCustomIcons/icons/misc6/DarkPhoeniix_anim_2.dds", 10, 1, 10}
a["@Beoumunt"] = {"LibCustomIcons/icons/misc6/Beoumunt_anim.dds", 5, 2, 25}
s["@BrorChop"] = "LibCustomIcons/icons/misc6/BrorChop.dds"
--a["@BrorChop"] = {"LibCustomIcons/icons/misc6/BrorChop_anim.dds", 7, 6, 5}
a["@FzFrost"] = {"LibCustomIcons/icons/misc6/FzFrost_anim.dds", 7, 6, 27.5}
a["@GomezZnl"] = {"LibCustomIcons/icons/misc6/GomezZnl_anim.dds", 10, 5, 20}
a["@Spoon.The_Sinner77"] = {"LibCustomIcons/icons/misc6/Spoon.The_Sinner77_anim.dds", 8, 1, 2}
a["@iPlugg"] = {"LibCustomIcons/icons/misc6/iPlugg_anim.dds", 7, 3, 12.5}
a["@Bootyy"] = {"LibCustomIcons/icons/misc6/Bootyy_anim.dds", 10, 1, 20}
a["@Boon45"] = {"LibCustomIcons/icons/misc6/Boon45_anim.dds", 8, 5, 12.5}
a["@Aberlour1"] = {"LibCustomIcons/icons/misc6/Aberlour1_anim.dds", 6, 3, 35}
a["@MoonSuga-Dogg0w0"] = {"LibCustomIcons/icons/misc6/MoonSuga-Dogg0w0_anim.dds", 7, 1, 4.5}
a["@Varkari"] = {"LibCustomIcons/icons/misc6/Varkari_anim_3.dds", 11, 1, 10}
a["@Kyzak"] = {"LibCustomIcons/icons/misc6/Kyzak_anim_3.dds", 47, 1, 25}
a["@briseusedombre"] = {"LibCustomIcons/icons/misc6/briseusedombre_anim.dds", 8, 5, 13.5}
a["@Nyx2011"] = {"LibCustomIcons/icons/misc6/Nyx2011_anim.dds", 10, 5, 8.3}
a["@Sasigei"] = {"LibCustomIcons/icons/misc6/Sasigei_anim.dds", 11, 2, 11.5}
a["@zepppeli"] = {"LibCustomIcons/icons/misc6/zepppeli_anim.dds", 10, 5, 10}
a["@AnbuMicah"] = {"LibCustomIcons/icons/misc6/AnbuMicah_anim.dds", 31, 1, 10}
a["@juneskaa"] = {"LibCustomIcons/icons/misc6/juneskaa_anim_2.dds", 5, 3, 10}
a["@Eraandill"] = {"LibCustomIcons/icons/misc6/Eraandill_anim.dds", 8, 1, 14}
a["@Ryziaa"] = {"LibCustomIcons/icons/misc6/Ryziaa_anim.dds", 10, 1, 16}
a["@ZENON1996"] = {"LibCustomIcons/icons/misc6/ZENON1996_anim.dds", 9, 2, 8}
a["@Br4ss_M0use"] = {"LibCustomIcons/icons/misc6/Br4ss_M0use_anim.dds", 16, 1, 10}
a["@zaqwerfvcx"] = {"LibCustomIcons/icons/misc6/zaqwerfvcx_anim.dds", 10, 2, 12.5}
a["@Finnnchyanf"] = {"LibCustomIcons/icons/misc6/Finnnchyanf_anim.dds", 15, 1, 6}
a["@laowuchang"] = {"LibCustomIcons/icons/misc6/laowuchang_anim.dds", 5, 1, 12.5}
a["@RealDeas"] = {"LibCustomIcons/icons/misc6/RealDeas_anim.dds", 10, 5, 29}
a["@SanyaDieZockt"] = {"LibCustomIcons/icons/misc6/SanyaDieZockt_anim.dds", 8, 1, 8}
a["@Bisenberger"] = {"LibCustomIcons/icons/misc6/Bisenberger_anim.dds", 7, 6, 10}
a["@Cat'You"] = {"LibCustomIcons/icons/misc6/CatYou_anim_2.dds", 7, 1, 10}
a["@ShadowGrabber"] = {"LibCustomIcons/icons/misc6/ShadowGrabber_anim.dds", 13, 1, 13}
a["@SimplyDUl"] = {"LibCustomIcons/icons/misc6/SimplyDUl_anim.dds", 8, 1, 6}
a["@ChaosKade"] = {"LibCustomIcons/icons/misc6/ChaosKade_anim.dds", 10, 5, 33}
a["@kkcilk"] = {"LibCustomIcons/icons/misc6/kkcilk_anim.dds", 3, 3, 10}
a["@Bryan_ESO"] = {"LibCustomIcons/icons/misc6/BryanESO_anim.dds", 3, 1, 10}
a["@beezii"] = {"LibCustomIcons/icons/misc6/beezii_anim_3.dds", 10, 5, 33}
a["@Greedydesire"] = {"LibCustomIcons/icons/misc6/Greedydesire_anim.dds", 3, 1, 10}
a["@LeonSkywalker"] = {"LibCustomIcons/icons/misc6/LeonSkywalker_anim.dds", 6, 5, 20}
a["@ArJhay"] = {"LibCustomIcons/icons/misc6/ArJhay_anim.dds", 5, 4, 10}
a["@Lextom"] = {"LibCustomIcons/icons/misc6/Lextom_anim.dds", 7, 4, 10}
a["@Rammbock"] = {"LibCustomIcons/icons/misc6/Rammbock_anim.dds", 8, 1, 20}
a["@Astral-Chain"] = {"LibCustomIcons/icons/misc6/AstralChain_anim.dds", 5, 2, 8}
a["@jillion"] = {"LibCustomIcons/icons/misc6/jillion_anim.dds", 13, 1, 10}
a["@stabnrun"] = {"LibCustomIcons/icons/misc6/stabnrun_anim.dds", 4, 3, 8}
a["@hikichan"] = {"LibCustomIcons/icons/misc6/hikichan_anim.dds", 5, 2, 10}
a["@shrimpofthenorth"] = {"LibCustomIcons/icons/misc6/shrimpofthenorth_anim.dds", 3, 2, 8}
a["@In-Water"] = {"LibCustomIcons/icons/misc6/In-Water_anim_2.dds", 6, 5, 25}
a["@lnquisitors"] = {"LibCustomIcons/icons/misc6/lnquisitors_anim.dds", 13, 3, 7}
a["@Envertebrate"] = {"LibCustomIcons/icons/misc6/Envertebrate_anim.dds", 8, 1, 8}
a["@AK269"] = {"LibCustomIcons/icons/misc6/AK269_anim.dds", 7, 3, 47}
a["@DODGlNG"] = {"LibCustomIcons/icons/misc6/Bscaredhomi_anim.dds", 19, 2, 11}
a["@Miller_HighLife14"] = {"LibCustomIcons/icons/misc6/Miller_HighLife14_anim.dds", 23, 1, 12}
a["@Kaeki"] = {"LibCustomIcons/icons/misc6/Kaeki_anim.dds", 6, 4, 10}
a["@MondayKiller"] = {"LibCustomIcons/icons/misc6/MondayKiller_anim.dds", 7, 7, 27}
a["@Nisiotika"] = {"LibCustomIcons/icons/misc6/Nisiotika_anim.dds", 10, 1, 10}
a["@beijixiong987"] = {"LibCustomIcons/icons/misc6/beijixiong987_anim.dds", 10, 5, 33}
a["@Senisin"] = {"LibCustomIcons/icons/misc6/Senisin_anim_2.dds", 10, 5, 20}
a["@SlavicMaxxing"] = {"LibCustomIcons/icons/misc6/SlavicMaxxing_anim.dds", 7, 1, 12.5}
a["@Ikashimi96"] = {"LibCustomIcons/icons/misc6/Ikashimi96_anim.dds", 20, 1, 10}
a["@emcardle660"] = {"LibCustomIcons/icons/misc6/emcardle660_anim.dds", 7, 7, 33}
a["@Gambino777"] = {"LibCustomIcons/icons/misc6/Gambino777_anim.dds", 7, 4, 17}
a["@LordG.1985"] = {"LibCustomIcons/icons/misc6/LordG.1985_anim.dds", 5, 1, 7}
a["@oZurgo"] = {"LibCustomIcons/icons/misc6/oZurgo_anim_2.dds", 16, 2, 32}
a["@OwLu"] = {"LibCustomIcons/icons/misc6/OwLu_anim.dds", 7, 3, 10}
a["@TeemoMan"] = {"LibCustomIcons/icons/misc6/TeemoMan_anim.dds", 8, 1, 20}
a["@angst.exe"] = {"LibCustomIcons/icons/misc6/angst.exe_anim.dds", 8, 1, 10}
a["@Aytix"] = {"LibCustomIcons/icons/misc6/Aytix_anim.dds", 13, 1, 8}
a["@PepperMintt"] = {"LibCustomIcons/icons/misc6/PepperMintt_anim.dds", 8, 1, 3}
a["@YUKIFUDO404"] = {"LibCustomIcons/icons/misc6/YUKIFUDO404_anim_2.dds", 5, 4, 20}
a["@iSGNiDempsey"] = {"LibCustomIcons/icons/misc6/iSGNiDempsey_anim.dds", 7, 7, 14}
a["@MF_1z1Fr4g"] = {"LibCustomIcons/icons/misc6/MF_1z1Fr4g_anim.dds", 10, 5, 10}
a["@DanyTwyt"] = {"LibCustomIcons/icons/misc6/DanyTwyt_anim.dds", 10, 1, 50}
a["@GETBUCKBRUH"] = {"LibCustomIcons/icons/misc6/GETBUCKBRUH_anim_2.dds", 7, 7, 25}
a["@AgyKoala"] = {"LibCustomIcons/icons/misc6/AgyKoala_anim.dds", 10, 5, 20}
a["@OG_Unicorn77"] = {"LibCustomIcons/icons/misc6/OG_Unicorn77_anim.dds", 39, 1, 8}
a["@XaerX"] = {"LibCustomIcons/icons/misc6/XaerX_anim.dds", 10, 4, 10}
a["@Ragga-Max"] = {"LibCustomIcons/icons/misc6/Ragga-Max_anim.dds", 7, 2, 10}
a["@x_Indica"] = {"LibCustomIcons/icons/misc6/x_Indica_anim.dds", 5, 3, 17}
a["@ArielSilva"] = {"LibCustomIcons/icons/misc6/ArielSilva_anim.dds", 7, 2, 7}
a["@Derrickbrown604"] = {"LibCustomIcons/icons/misc6/Derrickbrown604_anim.dds", 6, 6, 10}
a["@R.7"] = {"LibCustomIcons/icons/misc6/R.7_anim.dds", 50, 1, 15}
a["@Anya_Illyana"] = {"LibCustomIcons/icons/misc6/Anya_Illyana_anim.dds", 17, 1, 10}
a["@InvAli"] = {"LibCustomIcons/icons/misc6/InvAli_anim.dds", 9, 2, 17}
a["@Specialtactic"] = {"LibCustomIcons/icons/misc6/Specialtactic_anim.dds", 10, 1, 6}
a["@Samirrha"] = {"LibCustomIcons/icons/misc6/Samirrha_anim.dds", 10, 1, 6}
a["@www_eso"] = {"LibCustomIcons/icons/misc6/www_eso_anim.dds", 9, 1, 6}
a["@Levia4an"] = {"LibCustomIcons/icons/misc6/Levia4an_anim.dds", 7, 7, 25}
a["@Tbudko"] = {"LibCustomIcons/icons/misc6/Tbudko_anim.dds", 10, 1, 20}
a["@Yujie"] = {"LibCustomIcons/icons/misc6/Yujie_anim_3.dds", 10, 5, 25}
a["@Yuniicorn"] = {"LibCustomIcons/icons/misc6/Yuniicorn_anim.dds", 6, 2, 17}
a["@QuackedGamer"] = {"LibCustomIcons/icons/misc6/QuackedGamer_anim2.dds", 16, 1, 12.5}
a["@figures"] = {"LibCustomIcons/icons/misc6/figures_anim.dds", 6, 5, 33}
a["@Ariako"] = {"LibCustomIcons/icons/misc6/Ariako_anim.dds", 7, 5, 12.5}
a["@tutsuraki"] = {"LibCustomIcons/icons/misc6/tutsuraki_anim.dds", 6, 4, 25}
a["@Eeira"] = {"LibCustomIcons/icons/misc6/Eeira_anim.dds", 7, 3, 12.5}
a["@caleislove"] = {"LibCustomIcons/icons/misc6/caleislove_anim.dds", 8, 6, 7}
a["@Veinch"] = {"LibCustomIcons/icons/misc6/Veinch_anim.dds", 10, 1, 10}
a["@Torracaine"] = {"LibCustomIcons/icons/misc6/Torracaine_anim.dds", 8, 1, 25}
a["@Xi000"] = {"LibCustomIcons/icons/misc6/Xi000_anim.dds", 8, 1, 7}
a["@NormenHuang"] = {"LibCustomIcons/icons/misc6/NormenHuang_anim.dds", 9, 3, 24}
a["@RedKz4"] = {"LibCustomIcons/icons/misc6/RedKz4_anim.dds", 19, 2, 25}
a["@HolYBaaL"] = {"LibCustomIcons/icons/misc6/HolYBaaL_anim.dds", 8, 5, 10}
a["@DarioAmGrinden"] = {"LibCustomIcons/icons/misc6/DarioAmGrinden_anim.dds", 16, 2, 15}
a["@Lily-Lilas"] = {"LibCustomIcons/icons/misc6/Lily-Lilas_anim.dds", 6, 3, 17}
a["@ControlzU"] = {"LibCustomIcons/icons/misc6/ControlzU_anim.dds", 7, 7, 25}
a["@pine2D"] = {"LibCustomIcons/icons/misc6/pine2D_anim.dds", 7, 7, 30}
a["@e.lli"] = {"LibCustomIcons/icons/misc6/e.lli_anim.dds", 7, 3, 12.5}
a["@GoatDevil"] = {"LibCustomIcons/icons/misc6/GoatDevil_anim.dds", 12, 1, 10}
a["@Valkynne"] = {"LibCustomIcons/icons/misc6/Valkynne_anim.dds", 7, 7, 15}
a["@FearShadows"] = {"LibCustomIcons/icons/misc6/FearShadows_anim_6.dds", 21, 2, 11}
s["@FearShadows"] = "LibCustomIcons/icons/misc6/FearShadows.dds"
a["@no1care"] = {"LibCustomIcons/icons/misc6/no1care_anim.dds", 5, 3, 15}
a["@tktoostoned97"] = {"LibCustomIcons/icons/misc6/tktoostoned97_anim.dds", 7, 1, 10}
a["@Sever0808"] = {"LibCustomIcons/icons/misc6/Sever0808_anim.dds", 10, 5, 25}
a["@Kiva_UkkO"] = {"LibCustomIcons/icons/misc6/Kiva_UkkO_anim.dds", 31, 1, 10}
a["@SilverOwI"] = {"LibCustomIcons/icons/misc6/SilverOwI_anim.dds", 10, 5, 25}
a["@YandereSoukatsui"] = {"LibCustomIcons/icons/misc6/YandereSoukatsui_anim.dds", 8, 2, 3.5}
a["@Milkey03"] = {"LibCustomIcons/icons/misc6/Milkey03_anim.dds", 5, 3, 15}
a["@HMG_Spaun"] = {"LibCustomIcons/icons/misc6/HMG_Spaun_anim.dds", 14, 1, 10}
a["@notsojuicy"] = {"LibCustomIcons/icons/misc6/notsojuicy_anim.dds", 10, 1, 20}
a["@symboloogy"] = {"LibCustomIcons/icons/misc6/symboloogy_anim.dds", 6, 5, 25}
a["@Exotiki"] = {"LibCustomIcons/icons/misc6/Exotiki_anim.dds", 7, 5, 13.5}
a["@Vahoozlafa"] = {"LibCustomIcons/icons/misc6/Vahoozlafa_anim.dds", 10, 1, 10}
a["@Dr-S1NS"] = {"LibCustomIcons/icons/misc6/Dr-S1NS_anim.dds", 21, 2, 12}
a["@annatheminnie"] = {"LibCustomIcons/icons/misc6/annatheminnie_anim.dds", 5, 4, 17}
a["@Pxlegend"] = {"LibCustomIcons/icons/misc6/Pxlegend_anim.dds", 5, 4, 25}
a["@dok41"] = {"LibCustomIcons/icons/misc6/dok41_anim.dds", 11, 4, 12.5}
a["@ItsElevate"] = {"LibCustomIcons/icons/misc6/ItsElevate_anim.dds", 16, 1, 7.5}
a["@AcidiiS"] = {"LibCustomIcons/icons/misc6/AcidiiS_anim_4.dds", 7, 1, 10}
a["@DarkhunterXD58"] = {"LibCustomIcons/icons/misc6/DarkhunterXD58_anim.dds", 12, 3, 12}
a["@Seraphtalia"] = {"LibCustomIcons/icons/misc6/Seraphtalia_anim.dds", 14, 1, 10}
a["@Janika23"] = {"LibCustomIcons/icons/misc6/Janika23_anim.dds", 9, 5, 17}
a["@Yaboiruination"] = {"LibCustomIcons/icons/misc6/Yaboiruination_anim.dds", 6, 1, 15}
a["@LunaBamBam"] = {"LibCustomIcons/icons/misc6/LunaBamBam_anim.dds", 17, 1, 14.3}
a["@Astve"] = {"LibCustomIcons/icons/misc6/Astve_anim.dds", 4, 1, 10}
a["@Hanging"] = {"LibCustomIcons/icons/misc6/Hanging_anim.dds", 8, 1, 12.5}
a["@FreeorLovk"] = {"LibCustomIcons/icons/misc6/FreeorLovk_anim.dds", 11, 2, 8}
a["@AsikaOne"] = {"LibCustomIcons/icons/misc6/AsikaOne_anim.dds", 9, 5, 19.5}
a["@qlly"] = {"LibCustomIcons/icons/misc6/qlly_anim.dds", 9, 2, 5}
a["@borraskka"] = {"LibCustomIcons/icons/misc6/borraskka_anim.dds", 9, 5, 19.5}
a["@SenseiKazuro"] = {"LibCustomIcons/icons/misc6/SenseiKazuro_anim.dds", 12, 2, 10}
a["@T.exe"] = {"LibCustomIcons/icons/misc6/T.exe_anim.dds", 6, 1, 10}
a["@A_yue"] = {"LibCustomIcons/icons/misc6/A_yue_anim.dds", 7, 7, 50}
a["@Rytic's-WIFEY"] = {"LibCustomIcons/icons/misc6/Rytics-WIFEY_anim.dds", 6, 5, 10}
a["@xiaohambao"] = {"LibCustomIcons/icons/misc6/xiaohambao_anim.dds", 6, 5, 10}
a["@ZQ_JioJI"] = {"LibCustomIcons/icons/misc6/ZQ_JioJI_anim.dds", 5, 3, 25}
a["@oDora"] = {"LibCustomIcons/icons/misc6/oDora_anim.dds", 10, 5, 10}
a["@Pareidolian"] = {"LibCustomIcons/icons/misc6/Pareidolian_anim.dds", 6, 1, 14}
a["@BlackMindNA"] = {"LibCustomIcons/icons/misc6/BlackMindNA_anim.dds", 5, 4, 10}
a["@Mauritz7340"] = {"LibCustomIcons/icons/misc6/Mauritz7340_anim.dds", 10, 5, 30}
a["@dongdaye8848"] = {"LibCustomIcons/icons/misc6/dongdaye8848_anim.dds", 7, 2, 25}
a["@Rytic"] = {"LibCustomIcons/icons/misc6/Rytic_anim.dds", 10, 2, 11}
a["@ElderKhan"] = {"LibCustomIcons/icons/misc6/ElderKhan_anim.dds", 14, 1, 10}
a["@Neren_Di"] = {"LibCustomIcons/icons/misc6/Neren_Di_anim.dds", 8, 2, 33}
a["@PinkFoxette"] = {"LibCustomIcons/icons/misc6/PinkFoxette_anim.dds", 11, 4, 20}
a["@Nabbz"] = {"LibCustomIcons/icons/misc6/Nabbz_anim.dds", 6, 1, 10}
a["@keshon"] = {"LibCustomIcons/icons/misc6/keshon_anim.dds", 8, 1, 10}
a["@Ikun2.5years"] = {"LibCustomIcons/icons/misc6/Ikun2.5years_anim.dds", 8, 1, 14}
a["@ildanas"] = {"LibCustomIcons/icons/misc6/ildanas_anim.dds", 7, 1, 5}
a["@Pure_Love"] = {"LibCustomIcons/icons/misc6/Pure_Love_anim.dds", 10, 5, 33}
a["@lazymansmile"] = {"LibCustomIcons/icons/misc6/lazymansmile_anim.dds", 6, 3, 8}
a["@Clown_mimi"] = {"LibCustomIcons/icons/misc6/Clown_mimi_anim.dds", 6, 3, 7}
a["@a34208860"] = {"LibCustomIcons/icons/misc6/a34208860_anim.dds", 7, 2, 10}
a["@SawaGri"] = {"LibCustomIcons/icons/misc6/SawaGri_anim.dds", 6, 2, 14}
s["@MeIina"] = "LibCustomIcons/icons/misc6/Arasakas.dds"
a["@MeIina"] = {"LibCustomIcons/icons/misc6/Arasakas_anim.dds", 7, 7, 14}
a["@Vqbv"] = {"LibCustomIcons/icons/misc6/Vqbv_anim.dds", 10, 5, 17}
a["@Sasuke_Uchiha3"] = {"LibCustomIcons/icons/misc6/Sasuke_Uchiha3_anim.dds", 7, 6, 10}
a["@BACONator1313"] = {"LibCustomIcons/icons/misc6/BACONator1313_anim.dds", 5, 3, 8}
a["@Mr.FroDoeDabbins"] = {"LibCustomIcons/icons/misc6/Mr.FroDoeDabbins_anim.dds", 10, 5, 18}
a["@SkereMocro"] = {"LibCustomIcons/icons/misc6/SkereMocro_anim.dds", 7, 7, 20}
a["@ZingMerway"] = {"LibCustomIcons/icons/misc6/ZingMerway_anim.dds", 23, 1, 10}
a["@FLASH.STEP"] = {"LibCustomIcons/icons/misc6/FLASHSTEP_anim.dds", 13, 2, 15}
a["@LAOSIJI_UUU"] = {"LibCustomIcons/icons/misc6/LAOSIJI_UUU_anim.dds", 7, 7, 10}
a["@BreezyApex"] = {"LibCustomIcons/icons/misc6/BreezyApex_anim.dds", 15, 2, 20}
a["@Tutorion"] = {"LibCustomIcons/icons/misc6/Tutorion_anim.dds", 6, 8, 48}
a["@Shiriiio"] = {"LibCustomIcons/icons/misc6/Shiriiio_anim.dds", 8, 1, 6}
a["@NachoProblem"] = {"LibCustomIcons/icons/misc6/NachoProblem_anim.dds", 13, 1, 33}
a["@painelement"] = {"LibCustomIcons/icons/misc6/painelement_anim.dds", 16, 1, 10}
a["@Chrisprouss"] = {"LibCustomIcons/icons/misc6/Chrisprouss_anim.dds", 17, 1, 20}
a["@FreeCasanova"] = {"LibCustomIcons/icons/misc6/FreeCasanova_anim.dds", 5, 5, 20}
a["@Ad'elar"] = {"LibCustomIcons/icons/misc6/Adelar_anim.dds", 19, 2, 9}
a["@PikachuDD"] = {"LibCustomIcons/icons/misc6/PikachuDD_anim.dds", 10, 1, 5}
a["@JadedJackson"] = {"LibCustomIcons/icons/misc6/JadedJackson_anim.dds", 10, 2, 17}
a["@Realcherno"] = {"LibCustomIcons/icons/misc6/Realcherno_anim.dds", 6, 5, 10}
a["@Plankman"] = {"LibCustomIcons/icons/misc6/Plankman_anim.dds", 9, 2, 14}
a["@EzraLorwood"] = {"LibCustomIcons/icons/misc6/EzraLorwood_anim.dds", 6, 2, 10}
a["@Bellyknock"] = {"LibCustomIcons/icons/misc6/Bellyknock_anim.dds", 6, 4, 25}
a["@ScrollsGameplay"] = {"LibCustomIcons/icons/misc6/ScrollsGameplay_anim.dds", 5, 5, 12.5}
a["@HarvSpecial"] = {"LibCustomIcons/icons/misc6/HarvSpecial_anim.dds", 6, 6, 12.5}
a["@t.ragic"] = {"LibCustomIcons/icons/misc6/t.ragic_anim.dds", 10, 5, 25}
a["@Xeno_Nox"] = {"LibCustomIcons/icons/misc6/Xeno_Nox_anim.dds", 8, 1, 12.5}
a["@Beanh0le"] = {"LibCustomIcons/icons/misc6/Beanh0le_anim.dds", 6, 1, 33}
a["@Aruu"] = {"LibCustomIcons/icons/misc6/Aruu_anim.dds", 7, 7, 13}
a["@Sayvera"] = {"LibCustomIcons/icons/misc6/Sayvera_anim.dds", 10, 2, 12}
a["@DarkZoneGuru"] = {"LibCustomIcons/icons/misc6/DarkZoneGuru_anim.dds", 10, 1, 14}
a["@Buffroguesjk"] = {"LibCustomIcons/icons/misc6/Buffroguesjk_anim.dds", 10, 5, 8}
a["@deadbeforedeath"] = {"LibCustomIcons/icons/misc6/deadbeforedeath_anim.dds", 10, 5, 8}
a["@Veluzed"] = {"LibCustomIcons/icons/misc6/Veluzed_anim.dds", 10, 3, 10}
s["@Veluzed"] = "LibCustomIcons/icons/misc6/Veluzed.dds"
a["@xristosk952"] = {"LibCustomIcons/icons/misc6/xristosk952_anim.dds", 19, 2, 25}
a["@Mio'h"] = {"LibCustomIcons/icons/misc6/Mioh_anim.dds", 6, 2, 17}
a["@Jroh"] = {"LibCustomIcons/icons/misc6/Jroh_anim.dds", 10, 5, 33}
a["@xMinervAx"] = {"LibCustomIcons/icons/misc6/xMinervAx_anim.dds", 8, 1, 12.5}
a["@ZIHMU_BROBRO"] = {"LibCustomIcons/icons/misc6/ZIHMU_BROBRO_anim.dds", 10, 5, 17}
a["@Ms_Sin"] = {"LibCustomIcons/icons/misc6/Ms_Sin_anim.dds", 16, 2, 17}
a["@Shtille"] = {"LibCustomIcons/icons/misc6/shtille_anim.dds", 9, 3, 31}
a["@YamanD"] = {"LibCustomIcons/icons/misc6/YamanD_anim.dds", 7, 7, 10}
a["@RelentléssESO"] = {"LibCustomIcons/icons/misc6/RelentlessESO_anim_3.dds", 12, 4, 12}
s["@Ædric"] = "LibCustomIcons/icons/misc6/aedric.dds"
a["@RL'Y"] = {"LibCustomIcons/icons/misc6/RLY_anim.dds", 10, 5, 17}
a["@Duesentrieb"] = {"LibCustomIcons/icons/misc6/Duesentrieb_anim.dds", 25, 1, 10}
a["@HeyKiii"] = {"LibCustomIcons/icons/misc6/HeyKiii_anim.dds", 8, 1, 10}
a["@ss1978473006"] = {"LibCustomIcons/icons/misc6/ss1978473006_anim.dds", 13, 1, 29}
a["@tl2655993"] = {"LibCustomIcons/icons/misc6/tl2655993_anim.dds", 5, 3, 10}
a["@Fuketsu"] = {"LibCustomIcons/icons/misc6/Fuketsu_anim.dds", 5, 3, 12}
a["@A234Ri12"] = {"LibCustomIcons/icons/misc6/A234Ri12_anim.dds", 5, 5, 10}
a["@JotZet"] = {"LibCustomIcons/icons/misc6/JotZet_anim.dds", 8, 2, 10}
a["@XFYZLJ"] = {"LibCustomIcons/icons/misc6/XFYZLJ_anim.dds", 9, 1, 8}
a["@DeathF13nd"] = {"LibCustomIcons/icons/misc6/DeathF13nd_anim.dds", 8, 1, 20}
a["@Blueface_Baby"] = {"LibCustomIcons/icons/misc6/Blueface_Baby_anim.dds", 21, 1, 15}
a["@QuantumFate"] = {"LibCustomIcons/icons/misc6/QuantumFate_anim.dds", 5, 3, 10}
a["@Verolo"] = {"LibCustomIcons/icons/misc6/Verolo_anim.dds", 8, 6, 25}
a["@GUD_BYE"] = {"LibCustomIcons/icons/misc6/GUD_BYE_anim.dds", 5, 1, 14}
a["@Vantet"] = {"LibCustomIcons/icons/misc6/Vantet_anim.dds", 10, 5, 8}
a["@Flamebuckler"] = {"LibCustomIcons/icons/misc6/Flamebuckler_anim.dds", 6, 3, 11}
a["@GGreninja"] = {"LibCustomIcons/icons/misc6/GGreninja_anim.dds", 6, 2, 10}
a["@zelibobas"] = {"LibCustomIcons/icons/misc6/zelibobas_anim.dds", 6, 2, 10}
a["@utkillr"] = {"LibCustomIcons/icons/misc6/utkillr_anim.dds", 5, 3, 25}
a["@RaeL_N1"] = {"LibCustomIcons/icons/misc6/RaeL_N1_anim.dds", 17, 1, 20}
a["@TheBarkMan"] = {"LibCustomIcons/icons/misc6/TheBarkMan_anim.dds", 10, 5, 25}
a["@Bracelie"] = {"LibCustomIcons/icons/misc6/Bracelie_anim.dds", 6, 2, 14}
a["@vup4jp6"] = {"LibCustomIcons/icons/misc6/vup4jp6_anim.dds", 7, 7, 14}
a["@MiriamBelial"] = {"LibCustomIcons/icons/misc6/MiriamBelial_anim.dds", 8, 5, 14}
a["@Ancalagon1871"] = {"LibCustomIcons/icons/misc6/Ancalagon1871_anim.dds", 7, 6, 15}
a["@Namiridite"] = {"LibCustomIcons/icons/misc6/Namiridite_anim.dds", 8, 1, 10}
a["@duwutapete"] = {"LibCustomIcons/icons/misc6/Duwutape_anim.dds", 7, 1, 12.5}
a["@Duk3mNuk3m"] = {"LibCustomIcons/icons/misc6/Duk3mNuk3m_anim.dds", 5, 4, 10}
a["@ASAPXelah"] = {"LibCustomIcons/icons/misc6/ASAPXelah_anim_4.dds", 5, 3, 10}
a["@EternaIGhost"] = {"LibCustomIcons/icons/misc6/EternaIGhost_anim.dds", 8, 3, 15}
a["@KingM0n3y"] = {"LibCustomIcons/icons/misc6/KingM0n3y_anim.dds", 11, 3, 25}
s["@ChristineCamaro"] = "LibCustomIcons/icons/misc6/ChristineCamaro.dds"
a["@ChristineCamaro"] = {"LibCustomIcons/icons/misc6/ChristineCamaro_anim.dds", 7, 4, 10}
a["@EversongX"] = {"LibCustomIcons/icons/misc6/EversongX_anim.dds", 6, 4, 20}
a["@JayStay2EZ"] = {"LibCustomIcons/icons/misc6/JayStay2EZ_anim.dds", 5, 3, 8}
a["@MiaMaria456"] = {"LibCustomIcons/icons/misc6/MiaMaria456_anim.dds", 2, 2, 10}
a["@RaydoOne"] = {"LibCustomIcons/icons/misc6/RaydoOne_anim.dds", 6, 4, 25}
a["@Crispy-Sweetroll"] = {"LibCustomIcons/icons/misc6/Crispy-Sweetroll_anim.dds", 6, 2, 10}
a["@honkydonky"] = {"LibCustomIcons/icons/misc6/honkydonky_anim.dds", 7, 7, 26}
a["@AbusedBarbie"] = {"LibCustomIcons/icons/misc6/AbusedBarbie_anim.dds", 5, 2, 33}
a["@N0us_2xh"] = a["@n0us_2xh"]
s["@N0us_2xh"] = s["@n0us_2xh"]
a["@jennpancake"] = a["catjam"]
a["@AMYEU3"] = a["catjam"]
a["@Fayron_Blade"] = a["catjam"]
a["@byARCTIC"] = a["catjam"]
a["@thebomb3535"] = a["dancingcat"]
