-- SPDX-FileCopyrightText: 2025 m00nyONE
-- SPDX-License-Identifier: Artistic-2.0

local lib_name = "LibCustomIcons"
local lib = _G[lib_name]
local s = lib.GetStaticTable()
local a = lib.GetAnimatedTable()

s["@Jaise-N"] = "LibCustomIcons/icons/misc2/jaisen.dds"
s["@thecreed00"] = "LibCustomIcons/icons/misc2/thecreed00.dds"
s["@patachoux"] = "LibCustomIcons/icons/misc2/patachoux.dds"
s["@StUnT_Gee"] = "LibCustomIcons/icons/misc2/stuntgee.dds"
s["@KEAZone"] = "LibCustomIcons/icons/misc2/keazone.dds"
s["@privat52"] = "LibCustomIcons/icons/misc2/privat52.dds"
s["@Skaringard"] = "LibCustomIcons/icons/misc2/skaringard.dds"
s["@SKRVBB10RD"] = "LibCustomIcons/icons/misc2/skrvbb10rd.dds"
s["@ACEINTHEHOLE"] = "LibCustomIcons/icons/misc2/ACEINTHEHOLE_2.dds"
s["@Hellhound5"] = "LibCustomIcons/icons/misc2/hellhound5.dds"
s["@Bill_TH"] = "LibCustomIcons/icons/misc2/billth.dds"
s["@Iwamura"] = "LibCustomIcons/icons/misc2/iwamura.dds"
s["@S'oul"] = "LibCustomIcons/icons/misc2/soul.dds"
s["@jameswongw"] = "LibCustomIcons/icons/misc2/jameswongw.dds"
s["@daZza_GER"] = "LibCustomIcons/icons/misc2/dazzager.dds"
s["@Caetto"] = "LibCustomIcons/icons/misc2/caetto.dds"
s["@KingJJones"] = "LibCustomIcons/icons/misc2/kingjjones2.dds"
s["@juhe12321"] = "LibCustomIcons/icons/misc2/juhe12321.dds"
s["@meter90"] = "LibCustomIcons/icons/misc2/meter90.dds"
s["@NietzscheTR"] = "LibCustomIcons/icons/misc2/nietzschetr.dds"
s["@Cloud.ESO"] = "LibCustomIcons/icons/misc2/cloudstalkr.dds"
s["@benashey"] = "LibCustomIcons/icons/misc2/benashey3.dds"
s["@t.ea"] = "LibCustomIcons/icons/misc2/t.ea.dds"
s["@TheQakZz"] = "LibCustomIcons/icons/misc2/theqakzz.dds"
s["@Sqrtl"] = "LibCustomIcons/icons/misc2/sqrtl.dds"
s["@bookishpi"] = "LibCustomIcons/icons/misc2/bookishpi.dds"
s["@Panda-og"] = "LibCustomIcons/icons/misc2/pandaog.dds"
s["@Invisible22"] = "LibCustomIcons/icons/misc2/invisible22.dds"
s["@Xt_Twist"] = "LibCustomIcons/icons/misc2/xttwist.dds"
s["@CynepCamKa"] = "LibCustomIcons/icons/misc2/cynepcamka2.dds"
s["@Baldy.ESO"] = "LibCustomIcons/icons/misc2/baldyeso.dds"
s["@LewaCat"] = "LibCustomIcons/icons/misc2/lewacat.dds"
s["@WeirdFlexButOk"] = "LibCustomIcons/icons/misc2/weirdflexbutok.dds"
s["@Blxss"] = "LibCustomIcons/icons/misc2/Blxss.dds"
s["@Yoshpper"] = "LibCustomIcons/icons/misc2/yoshpper.dds"
s["@LEVY'S"] = "LibCustomIcons/icons/misc2/levys.dds"
s["@Sixnu"] = "LibCustomIcons/icons/misc2/sixnu.dds"
s["@L'eg"] = "LibCustomIcons/icons/misc2/legleg.dds"
s["@Neladriel"] = "LibCustomIcons/icons/misc2/neladriel.dds"
s["@DCorvin"] = "LibCustomIcons/icons/misc2/dcorvin.dds"
s["@teenytinycat"] = "LibCustomIcons/icons/misc2/teenytinycat.dds"
s["@Frosteeyy"] = "LibCustomIcons/icons/misc2/frosteeyy.dds"
s["@Alfredmcgregor"] = "LibCustomIcons/icons/misc2/alfredmcgregor.dds"
s["@luvs"] = "LibCustomIcons/icons/misc2/luvs.dds"
s["@Captain_Salad"] = "LibCustomIcons/icons/misc2/captainsalad.dds"
s["@FiveRenHrist"] = "LibCustomIcons/icons/misc2/fiverenhrist.dds"
s["@M0RTARI0N"] = "LibCustomIcons/icons/misc/mortarion3.dds"
s["@Jezekael78"] = "LibCustomIcons/icons/misc2/jezekael78.dds"
s["@YamiKuruku"] = "LibCustomIcons/icons/misc2/yamikuruku.dds"
s["@mdz0"] = "LibCustomIcons/icons/misc2/mdz0.dds"
s["@Elbakin"] = "LibCustomIcons/icons/misc2/elbakin.dds"
s["@hadouken8599"] = "LibCustomIcons/icons/misc2/hadouken8599.dds"
s["@daFluffiest"] = "LibCustomIcons/icons/misc2/dafluffiest2.dds"
s["@RushFaceFirst"] = "LibCustomIcons/icons/misc2/rushfacefirst.dds"
s["@TECKTE"] = "LibCustomIcons/icons/misc2/teckte.dds"
s["@Iamgettingtired"] = "LibCustomIcons/icons/misc2/iamgettingtired.dds"
s["@Asaffy"] = "LibCustomIcons/icons/misc2/asaffy.dds"
s["@UpsideDownFrown"] = "LibCustomIcons/icons/misc2/upsidedownfrown2.dds"
s["@emiiemii"] = "LibCustomIcons/icons/misc2/emiiemii.dds"
s["@goshi12"] = "LibCustomIcons/icons/misc2/goshi12.dds"
s["@Marcosuprem"] = "LibCustomIcons/icons/misc2/marcosuprem.dds"
s["@itsjustAJ"] = "LibCustomIcons/icons/misc2/itsjustaj.dds"
s["@JoeTotale"] = "LibCustomIcons/icons/misc2/joetotale.dds"
s["@NutellaPancakes"] = "LibCustomIcons/icons/misc2/nutellapancakes.dds"
s["@Burdigalina"] = "LibCustomIcons/icons/misc2/burdigalina.dds"
s["@Fleckie02"] = "LibCustomIcons/icons/misc2/fleckie022.dds"
s["@Atomkern"] = "LibCustomIcons/icons/misc2/atomkern2.dds"
s["@Jarva"] = "LibCustomIcons/icons/misc2/jarva2.dds"
s["@Cbk7"] = "LibCustomIcons/icons/misc2/cbk74.dds"
s["@toggla_fillen"] = "LibCustomIcons/icons/misc2/toggla_fillen3.dds"
s["@Strom3K"] = "LibCustomIcons/icons/misc2/strom3k.dds"
s["@MaggaCammara"] = "LibCustomIcons/icons/misc2/maggacammara.dds"
s["@Jo_Sinoda"] = "LibCustomIcons/icons/misc2/josinoda.dds"
s["@qcell"] = "LibCustomIcons/icons/misc2/qcell.dds"
s["@CertifiedSiIIyGoose"] = "LibCustomIcons/icons/misc2/CertifiedSiIIyGoose.dds"
s["@The_Bornless"] = "LibCustomIcons/icons/misc2/thebornless.dds"
s["@Baman19"] = "LibCustomIcons/icons/misc2/baman19.dds"
s["@Kwix"] = "LibCustomIcons/icons/misc2/kwix.dds"
s["@evkets"] = "LibCustomIcons/icons/misc2/evkets.dds"
s["@F0restDragon"] = "LibCustomIcons/icons/misc2/forestdragonbro2.dds"
s["@CyberSkooma"] = "LibCustomIcons/icons/misc2/cyberskooma.dds"
s["@purp0se"] = "LibCustomIcons/icons/misc2/kain2.dds"
s["@Huntux51YT"] = "LibCustomIcons/icons/misc2/huntux51yt.dds"
s["@O.o_lol"] = "LibCustomIcons/icons/misc2/oolol.dds"
s["@Murcat"] = "LibCustomIcons/icons/misc2/murcat.dds"
s["@DefinitelyNotHoid"] = "LibCustomIcons/icons/misc2/definitelynothoid.dds"
s["@Woohbeard"] = "LibCustomIcons/icons/misc2/woohbeard.dds"
s["@DEMONLORDITA"] = "LibCustomIcons/icons/misc2/demonlordita.dds"
s["@Black'Blade"] = "LibCustomIcons/icons/misc2/blackblade.dds"
s["@btk_GrAf"] = "LibCustomIcons/icons/misc2/btkgraf.dds"
s["@JonnyKreng"] = "LibCustomIcons/icons/misc2/jonnykreng.dds"
s["@Nvisible6"] = "LibCustomIcons/icons/misc2/nvisible6.dds"
s["@TheRaOct"] = "LibCustomIcons/icons/misc2/theraoct.dds"
s["@Zimahere"] = "LibCustomIcons/icons/misc2/zimahere.dds"
s["@Mark30094"] = "LibCustomIcons/icons/misc2/mark30094.dds"
s["@Earwyne"] = "LibCustomIcons/icons/misc2/earwyne.dds"
s["@Spengles"] = "LibCustomIcons/icons/misc2/spengles.dds"
s["@Lucky701"] = "LibCustomIcons/icons/misc2/lucky701.dds"
s["@PrincessCatWarrior"] = "LibCustomIcons/icons/misc2/princesscatwarrior.dds"
s["@MoldyGCS"] = "LibCustomIcons/icons/misc2/moldygcs.dds"
s["@Eterlight"] = "LibCustomIcons/icons/misc2/eterlight.dds"
s["@dovakin_auditore"] = "LibCustomIcons/icons/misc2/dovakin_auditore.dds"
s["@Maruchim"] = "LibCustomIcons/icons/misc2/maruchim.dds"
s["@jarograv"] = "LibCustomIcons/icons/misc2/jarograv.dds"
s["@Safeplace"] = "LibCustomIcons/icons/misc2/safeplace.dds"
s["@thenamestom8"] = "LibCustomIcons/icons/misc2/thenamestom83.dds"
s["@Valkyn_Val"] = "LibCustomIcons/icons/misc2/Valkyn_Val.dds"
s["@Scphott"] = "LibCustomIcons/icons/misc2/scphott.dds"
s["@Dimzombie"] = "LibCustomIcons/icons/misc2/dimzombie.dds"
s["@BuffBish"] = "LibCustomIcons/icons/misc2/buffbish.dds"
s["@xJmJx"] = "LibCustomIcons/icons/misc2/xjmjx.dds"
s["@Charybdisc"] = "LibCustomIcons/icons/misc2/charybdisc.dds"
s["@GuineaPigs"] = "LibCustomIcons/icons/misc2/guineapigs.dds"
s["@B00mslang"] = "LibCustomIcons/icons/misc2/b00mslang2.dds"
s["@Square_Dude"] = "LibCustomIcons/icons/misc2/Square_Dude.dds"
s["@Bounceplus1"] = "LibCustomIcons/icons/misc2/bounceplus1.dds"
s["@BoysNoize87"] = "LibCustomIcons/icons/misc2/boysnoize87.dds"
s["@Cadro"] = "LibCustomIcons/icons/misc2/cadro.dds"
s["@silver1651"] = "LibCustomIcons/icons/misc2/silverhaze1651.dds"
s["@Wyper0"] = "LibCustomIcons/icons/misc2/wyper0.dds"
s["@MagiiC_One"] = "LibCustomIcons/icons/misc2/magiicone.dds"
s["@Lepsa1ity"] = "LibCustomIcons/icons/misc2/lepsa1ity2.dds"
s["@BlackSilverUfa22"] = "LibCustomIcons/icons/misc2/blacksilverufa22.dds"
s["@Aleksandr9623"] = "LibCustomIcons/icons/misc2/aleksandr9623.dds"
s["@FelexX"] = "LibCustomIcons/icons/misc2/felexx.dds"
s["@NeKonn"] = "LibCustomIcons/icons/misc2/nekonn.dds"
s["@telvanni96"] = "LibCustomIcons/icons/misc2/telvanni96.dds"
s["@MelanieD15"] = "LibCustomIcons/icons/misc2/melaniebm123.dds"
s["@Jordy13"] = "LibCustomIcons/icons/misc2/jordy13.dds"
s["@Vala7"] = "LibCustomIcons/icons/misc2/vala7.dds"
a["@synthweaver"] = {"LibCustomIcons/icons/misc2/synthweaver.dds", 8, 1, 4}
s["@Bergruth"] = "LibCustomIcons/icons/misc2/bergruth.dds"
s["@Krauter"] = "LibCustomIcons/icons/misc2/krauter.dds"
s["@Irniben"] = "LibCustomIcons/icons/misc2/irniben.dds"
s["@Orejana"] = "LibCustomIcons/icons/misc2/orejana.dds"
s["@Darksky7493"] = "LibCustomIcons/icons/misc2/darksky7493.dds"
s["@Eithedae"] = "LibCustomIcons/icons/misc2/eithedae.dds"
s["@Eruceninde"] = "LibCustomIcons/icons/misc2/eruceninde.dds"
s["@Muffins714"] = "LibCustomIcons/icons/misc2/muffins714.dds"
s["@Vokyn"] = "LibCustomIcons/icons/misc2/vokyn.dds"
s["@lilgabe45"] = "LibCustomIcons/icons/misc2/lilgabe45_2.dds"
s["@Schnecki"] = "LibCustomIcons/icons/misc2/schnecki.dds"
s["@Schutzengelchen"] = "LibCustomIcons/icons/misc2/schutzengelchen.dds"
s["@Chris86m"] = "LibCustomIcons/icons/misc2/chris86m2.dds"
s["@nobility89"] = "LibCustomIcons/icons/misc2/nobility89_2.dds"
s["@Banana_Z"] = "LibCustomIcons/icons/misc2/bananaz2.dds"
s["@Haruhii"] = "LibCustomIcons/icons/misc2/haruhii.dds"
s["@YumiYuna"] = "LibCustomIcons/icons/misc2/yumiyuna.dds"
s["@RenegadeValor"] = "LibCustomIcons/icons/misc2/renegadevalor.dds"
s["@SpotlessFish"] = "LibCustomIcons/icons/misc2/powerbottombob2.dds"
s["@kanak2323"] = "LibCustomIcons/icons/misc2/kanak2323.dds"
s["@Amlir"] = "LibCustomIcons/icons/misc2/Amlir_3.dds"
s["@Sartas203"] = "LibCustomIcons/icons/misc2/sartas203.dds"
s["@ZoraxESO"] = "LibCustomIcons/icons/misc2/zoraxeso.dds"
s["@Capery"] = "LibCustomIcons/icons/misc2/capery.dds"
s["@V400"] = "LibCustomIcons/icons/misc2/v400.dds"
s["@galonizer1"] = "LibCustomIcons/icons/misc2/galonizer1.dds"
s["@Hovatham"] = "LibCustomIcons/icons/misc2/hovatham.dds"
s["@Garrus20"] = "LibCustomIcons/icons/misc2/garrus20.dds"
s["@pride126"] = "LibCustomIcons/icons/misc2/pride126.dds"
s["@HeroOfTheNight"] = "LibCustomIcons/icons/misc2/heroofthenight.dds"
s["@casazuzu"] = "LibCustomIcons/icons/misc2/casazuzu.dds"
s["@Vatrysha"] = "LibCustomIcons/icons/misc2/vikkovikki2.dds"
s["@Perysthos"] = "LibCustomIcons/icons/misc2/perysthos.dds"
s["@Nebulat"] = "LibCustomIcons/icons/misc2/nebulat.dds"
s["@Klebrig12"] = "LibCustomIcons/icons/misc2/klebrig12.dds"
s["@TeamFF"] = "LibCustomIcons/icons/misc2/TeamFF.dds"
s["@outersaiensu"] = "LibCustomIcons/icons/misc2/outersaiensu.dds"
s["@Hov90"] = "LibCustomIcons/icons/misc2/hov902.dds"
s["@JacekTorpeda"] = "LibCustomIcons/icons/misc2/jacektorpeda.dds"
s["@magpuk131"] = "LibCustomIcons/icons/misc2/magpuk131.dds"
s["@Bahsei"] = "LibCustomIcons/icons/misc2/bahsei.dds"
s["@End_LessLight"] = "LibCustomIcons/icons/misc2/endlesslight.dds"
s["@TanguydB"] = "LibCustomIcons/icons/misc2/tanguydb2.dds"
s["@KrakeCane"] = "LibCustomIcons/icons/misc2/krakecane.dds"
s["@Elaroth90"] = "LibCustomIcons/icons/misc2/elaroth90.dds"
s["@Raihert"] = "LibCustomIcons/icons/misc2/raihert.dds"
s["@Xilixia"] = "LibCustomIcons/icons/misc2/xilixia.dds"
s["@beccalino"] = "LibCustomIcons/icons/misc2/beccalino.dds"
s["@AnonymusPsyche"] = "LibCustomIcons/icons/misc2/anonymuspsyche.dds"
s["@Erzengel-Lucifer"] = "LibCustomIcons/icons/misc2/erzengellucifer.dds"
s["@JerryTan0831"] = "LibCustomIcons/icons/misc2/jerrytan0831.dds"
s["@Lysoo"] = "LibCustomIcons/icons/misc2/lysoo.dds"
s["@Three-Dog"] = "LibCustomIcons/icons/misc2/threedog.dds"
s["@Shipppeh"] = "LibCustomIcons/icons/misc2/shipppeh.dds"
s["@Terrwyn-16"] = "LibCustomIcons/icons/misc2/terrwyn16.dds"
s["@pandadosgames"] = "LibCustomIcons/icons/misc2/pandadosgames.dds"
s["@Ascantia"] = "LibCustomIcons/icons/misc2/ascantia.dds"
s["@Elshaa"] = "LibCustomIcons/icons/misc2/elshaa.dds"
s["@Sizzyy"] = "LibCustomIcons/icons/misc2/sizzyy.dds"
s["@H'ippy"] = "LibCustomIcons/icons/misc2/hippy.dds"
s["@UnholyFrijole"] = "LibCustomIcons/icons/misc2/freudianbean4.dds"
s["@shinry"] = "LibCustomIcons/icons/misc2/shinry.dds"
s["@WhyYouSoTwitchy"] = "LibCustomIcons/icons/misc2/whyyousotwitchy.dds"
s["@Trippcap"] = "LibCustomIcons/icons/misc2/trippcap.dds"
s["@UlfvaldrFrostbane"] = "LibCustomIcons/icons/misc2/UlfvaldrFrostbane.dds"
s["@OOKILLAOO"] = "LibCustomIcons/icons/misc2/OOKILLAOO.dds"
s["@Lord_Tightframe"] = "LibCustomIcons/icons/misc2/lordtightframe.dds"
s["@Aldagion"] = "LibCustomIcons/icons/misc2/aldagion.dds"
s["@Holgon"] = "LibCustomIcons/icons/misc2/holgon.dds"
s["@Bartalomeos"] = "LibCustomIcons/icons/misc2/bartalomeos.dds"
s["@SKYRYKER"] = "LibCustomIcons/icons/misc2/skyryker.dds"
s["@ReSisifo"] = "LibCustomIcons/icons/misc2/resisifo.dds"
s["@LeonGame"] = "LibCustomIcons/icons/misc2/leongame.dds"
s["@f1nka"] = "LibCustomIcons/icons/hodor/loki.dds"
s["@Naaririell"] = "LibCustomIcons/icons/misc2/naaririell2.dds"
s["@DagothDeer"] = "LibCustomIcons/icons/misc2/dagothdeer.dds"
s["@XJZ-MLRS"] = "LibCustomIcons/icons/misc2/XJZ-MLRS.dds"
s["@angelduuust"] = "LibCustomIcons/icons/misc2/angelduuust.dds"
s["@InkySpots"] = "LibCustomIcons/icons/misc2/inkyspots.dds"
s["@pinkie-fleur"] = "LibCustomIcons/icons/misc2/pinkiefleur.dds"
s["@Warevil"] = "LibCustomIcons/icons/misc2/warevil.dds"
s["@Lothric238"] = "LibCustomIcons/icons/misc2/lothric238.dds"
s["@TheFirst-Asura"] = "LibCustomIcons/icons/misc2/TheFirst-Asura_2.dds"
s["@Lillyangel82"] = "LibCustomIcons/icons/misc2/lillyangel82.dds"
s["@Caillou21"] = "LibCustomIcons/icons/misc2/caillou21.dds"
s["@Vyxie"] = "LibCustomIcons/icons/misc2/vyxie.dds"
s["@spu7n1k"] = "LibCustomIcons/icons/misc2/spu7n1k.dds"
s["@MöbiusD"] = "LibCustomIcons/icons/misc2/MoebiusD_2.dds"
s["@Siar5010"] = "LibCustomIcons/icons/misc3/ovomimi.dds"
s["@Chaos'Knight"] = "LibCustomIcons/icons/misc2/chaosknight.dds"
s["@Nijeps"] = "LibCustomIcons/icons/misc2/nijeps.dds"
s["@onidalton"] = "LibCustomIcons/icons/misc2/onidalton.dds"
s["@BlaCkSBEat"] = "LibCustomIcons/icons/misc2/blacksbeat.dds"
s["@Xenus24"] = "LibCustomIcons/icons/misc/brulmorith.dds"
s["@Nykteus_Fenrir"] = "LibCustomIcons/icons/misc2/nykteusfenrir3.dds"
s["@MmeChaTMaLoW"] = "LibCustomIcons/icons/misc2/mmechatmalow.dds"
s["@album-aurum"] = "LibCustomIcons/icons/misc2/albumaurum.dds"
s["@LeDieuPoulpe"] = "LibCustomIcons/icons/misc2/ledieupoulpe.dds"
s["@YantiParazi"] = "LibCustomIcons/icons/misc2/yantiparazi4.dds"
s["@Marimonn"] = "LibCustomIcons/icons/misc2/marimonn.dds"
s["@qarzulocne"] = "LibCustomIcons/icons/misc2/qarzulocne.dds"
s["@Routch0"] = "LibCustomIcons/icons/misc2/routch0.dds"
s["@mmoorraa"] = "LibCustomIcons/icons/misc2/mmoorraa.dds"
s["@sigh-duck"] = "LibCustomIcons/icons/misc2/sigh-duck.dds"
s["@jpeezyOSLT"] = "LibCustomIcons/icons/misc2/jpeezyoslt2.dds"
s["@M.Toast"] = "LibCustomIcons/icons/misc2/MToast.dds"
s["@StoryESO"] = "LibCustomIcons/icons/misc2/storyeso.dds"
s["@Immortalized007"] = "LibCustomIcons/icons/misc2/immortalized007.dds"
s["@vi.c"] = "LibCustomIcons/icons/misc2/vic.dds"
s["@Curvie"] = "LibCustomIcons/icons/misc2/curvie.dds"
s["@EvaeI"] = "LibCustomIcons/icons/misc2/evaei.dds"
s["@Mghost93"] = "LibCustomIcons/icons/misc2/mghost93.dds"
s["@x_Luna-x"] = "LibCustomIcons/icons/misc2/xlunax.dds"
s["@Gene.0"] = "LibCustomIcons/icons/misc2/gene0.dds"
s["@EKDS00"] = "LibCustomIcons/icons/misc2/ekds00.dds"
s["@sptlssmnd"] = "LibCustomIcons/icons/misc2/sptlssmnd2.dds"
s["@Bunnisox"] = "LibCustomIcons/icons/misc2/bunnisox2.dds"
s["@Aerifex"] = "LibCustomIcons/icons/misc2/aerifex.dds"
s["@spr4yer"] = "LibCustomIcons/icons/misc2/spr4yer.dds"
s["@DIFFx22"] = "LibCustomIcons/icons/misc2/DIFFx22.dds"
a["@ACEINTHEHOLE"] = {"LibCustomIcons/icons/misc2/ACEINTHEHOLE_anim2.dds", 27, 1, 10}
a["@skyeson"] = {"LibCustomIcons/icons/misc2/skyeson_anim.dds", 10, 1, 25}
a["@Sorrowowo"] = {"LibCustomIcons/icons/misc2/reniy123_anim.dds", 10, 1, 34}
a["@Hvstile"] = {"LibCustomIcons/icons/misc2/hvstile_anim2.dds", 5, 1, 12}
a["@Blxss"] = {"LibCustomIcons/icons/misc2/Blxss_anim_2.dds", 10, 5, 25}
a["@stirfriedferret"] = {"LibCustomIcons/icons/misc2/stirfriedferret_anim.dds", 6, 1, 16}
a["@Huntux51YT"] = {"LibCustomIcons/icons/misc2/Huntux51YT_anim.dds", 10, 5, 33}
a["@KiwiStu"] = {"LibCustomIcons/icons/misc2/KiwiStu_anim.dds", 7, 7, 30}
a["@Polich"] = {"LibCustomIcons/icons/misc2/Polich_anim_3.dds", 12, 1, 14}
a["@outersaiensu"] = {"LibCustomIcons/icons/misc2/outersaiensu_anim.dds", 8, 1, 20}
a["@ItzBear"] = {"LibCustomIcons/icons/misc2/ItzBear_anim.dds", 6, 1, 2}
a["@Alykah"] = {"LibCustomIcons/icons/misc2/Alykah_anim_6.dds", 23, 1, 14}
a["@HeroOfTheNight"] = {"LibCustomIcons/icons/misc2/heroofthenight_anim.dds", 9, 1, 11}
a["@Hovatham"] = {"LibCustomIcons/icons/misc2/hovatham_anim2.dds", 24, 1, 10}
a["@Naaririell"] = {"LibCustomIcons/icons/misc2/naaririell_anim.dds", 14, 1, 25}
a["@Cigfried"] = {"LibCustomIcons/icons/misc2/cigfried_anim.dds", 10, 5, 7}
a["@TanguydB"] = {"LibCustomIcons/icons/misc2/tanguydb_anim.dds", 20, 1, 20}
a["@LoTemon"] = {"LibCustomIcons/icons/misc2/LoTemon_anim.dds", 12, 1, 9}
a["@grimnoire"] = {"LibCustomIcons/icons/misc2/grimnoire_anim.dds", 30, 1, 20}
a["@Kabutbach"] = {"LibCustomIcons/icons/misc2/kabutbach_anim.dds", 8, 6, 20}
a["@IckySpot"] = {"LibCustomIcons/icons/misc2/ickyspot_anim.dds", 9, 1, 14}
a["@Bchewy"] = {"LibCustomIcons/icons/misc2/bchewy_anim.dds", 47, 1, 25}
a["@bunny-nun"] = {"LibCustomIcons/icons/misc2/bunnynun_anim.dds", 8, 1, 25}
a["@mythosmc"] = {"LibCustomIcons/icons/misc2/mythosmc_anim.dds", 10, 5, 33}
a["@LadySarah"] = {"LibCustomIcons/icons/misc2/ladysarah_anim.dds", 18, 1, 25}
a["@Big_King-Julian"] = {"LibCustomIcons/icons/misc2/bigkingjulian_anim.dds", 27, 1, 15}
a["@Wuselmann"] = {"LibCustomIcons/icons/misc2/wuselmann_anim.dds", 10, 5, 25}
a["@Babloopy"] = {"LibCustomIcons/icons/misc2/babloopy_anim.dds", 13, 1, 33}
a["@TheRealThorblitz"] = {"LibCustomIcons/icons/misc2/therealthorblitz_anim.dds", 49, 1, 14}
a["@Hollywood_bq"] = {"LibCustomIcons/icons/misc2/hollywoodbq_anim2.dds", 6, 1, 6}
a["@ekskam"] = {"LibCustomIcons/icons/misc2/ekskam_anim.dds", 11, 1, 10}
a["@DaNeroak"] = {"LibCustomIcons/icons/misc2/daneroak_anim.dds", 7, 1, 30}
a["@RebelDarkHeart"] = {"LibCustomIcons/icons/misc2/rbelbearheart_anim.dds", 21, 1, 15}
a["@SpiritNA"] = {"LibCustomIcons/icons/misc2/spiritna_anim.dds", 49, 1, 8}
a["@Jale.Anarcho"] = {"LibCustomIcons/icons/misc2/jaleanarcho_anim2.dds", 49, 1, 33}
a["@Spider.Heart"] = {"LibCustomIcons/icons/misc2/megaloptera84_anim.dds", 7, 1, 11}
a["@Sowano"] = {"LibCustomIcons/icons/misc2/sowano_anim.dds", 12, 1, 11}
a["@Toads_Stool"] = {"LibCustomIcons/icons/misc2/toadsstool_anim.dds", 12, 1, 25}
a["@HappyReformed"] = {"LibCustomIcons/icons/misc2/happyreformed_anim.dds", 10, 1, 10}
a["@IiIac"] = {"LibCustomIcons/icons/misc2/guarguarguarguarguar_anim.dds", 9, 1, 24}
a["@RiftenOG"] = {"LibCustomIcons/icons/misc2/riftenog_anim.dds", 13, 1, 11}
a["@RagePeak"] = {"LibCustomIcons/icons/misc2/ragepeak_anim.dds", 10, 5, 20}
a["@Lunaspear"] = {"LibCustomIcons/icons/misc2/lunaspear_anim.dds", 28, 1, 20}
a["@Nefaari"] = {"LibCustomIcons/icons/misc2/foylen_anim.dds", 5, 1, 7}
a["@BuzzLightYear11"] = {"LibCustomIcons/icons/misc2/buzzlightyear11_anim.dds", 8, 6, 10}
a["@taykfourtyseven"] = {"LibCustomIcons/icons/misc2/taykfourtyseven_anim.dds", 5, 1, 10}
a["@daFluffiest"] = {"LibCustomIcons/icons/misc2/dafluffiest_anim.dds", 23, 2, 10}
a["@Kwix"] = {"LibCustomIcons/icons/misc2/kwix_anim2.dds", 9, 1, 8}
a["@setseed42"] = {"LibCustomIcons/icons/misc2/setseed42_anim.dds", 8, 6, 25}
a["@emiiemii"] = {"LibCustomIcons/icons/misc2/emiiemii_anim2.dds", 6, 1, 9}
a["@Orielle"] = {"LibCustomIcons/icons/misc2/orielle_anim.dds", 6, 4, 17}
a["@Kal-EL_OCA"] = {"LibCustomIcons/icons/misc2/kaleloca_anim.dds", 15, 1, 14}
a["@TheW0nder"] = {"LibCustomIcons/icons/misc2/thew0nder_anim.dds", 13, 1, 12}
a["@McOwn"] = {"LibCustomIcons/icons/misc2/mcown_anim.dds", 11, 1, 20}
a["@x_Quickie"] = {"LibCustomIcons/icons/misc2/itsquickie_anim.dds", 7, 1, 14}
a["@ISkyee"] = {"LibCustomIcons/icons/misc2/iskyee_anim.dds", 6, 1, 10}
a["@Parietic"] = {"LibCustomIcons/icons/misc2/parietic_anim.dds", 5, 6, 25}
a["@RHOEncador"] = {"LibCustomIcons/icons/misc2/rhoencador_anim.dds", 5, 5, 7}
a["@BuffBish"] = {"LibCustomIcons/icons/misc2/buffbish_anim.dds", 31, 1, 14}
a["@daynali"] = {"LibCustomIcons/icons/misc2/daynali_anim.dds", 13, 1, 20}
a["@sillyedhel"] = {"LibCustomIcons/icons/misc2/sillyedhel_anim.dds", 9, 5, 20}
a["@XiaoChen99"] = {"LibCustomIcons/icons/misc2/xiaochen99_anim2.dds", 16, 1, 10}
a["@doshu"] = {"LibCustomIcons/icons/misc2/doshu_anim.dds", 18, 1, 50}
a["@Enclosing"] = {"LibCustomIcons/icons/misc2/enclosing_anim.dds", 24, 1, 9}
a["@Rykiln"] = {"LibCustomIcons/icons/misc2/rykiln_anim.dds", 9, 1, 25}
a["@FreshZombie"] = {"LibCustomIcons/icons/misc2/freshzombie_anim.dds", 6, 1, 10}
a["@Lodner"] = {"LibCustomIcons/icons/misc2/lodner_anim.dds", 13, 1, 9}
a["@DopeySmurf"] = {"LibCustomIcons/icons/misc2/xdopeysmurfx_anim.dds", 58, 1, 20}
a["@phenothazian"] = {"LibCustomIcons/icons/misc2/btslover_anim.dds", 8, 5, 10}
a["@Bauer_Horst"] = {"LibCustomIcons/icons/misc2/bauerhorst_anim.dds", 7, 1, 17}
a["@Tungris"] = {"LibCustomIcons/icons/misc2/tungris_anim2.dds", 46, 1, 17}
a["@MrSneakyGypsy"] = {"LibCustomIcons/icons/misc2/mrsneakygypsy_anim.dds", 6, 4, 10}
a["@SpinMeister"] = {"LibCustomIcons/icons/misc2/spinmeister_anim.dds", 9, 1, 10}
a["@SoftPink"] = {"LibCustomIcons/icons/misc2/softpink_anim.dds", 11, 1, 10}
a["@Ky_bele"] = {"LibCustomIcons/icons/misc2/kybele_anim.dds", 5, 1, 10}
a["@wsdamo"] = {"LibCustomIcons/icons/misc2/wsdamo_anim.dds", 6, 5, 14}
a["@ImPsyphi"] = {"LibCustomIcons/icons/misc2/impsyphi_anim.dds", 6, 1, 10}
a["@M0RTARI0N"] = {"LibCustomIcons/icons/misc2/mortarion_anim.dds", 11, 3, 12}
a["@SouI-Reaver"] = {"LibCustomIcons/icons/misc2/ussrtovarisch_anim.dds", 8, 6, 33}
a["@Krevad"] = {"LibCustomIcons/icons/misc2/krevad_anim2.dds", 17, 1, 10}
a["@mmarts"] = {"LibCustomIcons/icons/misc2/mmarts_anim2.dds", 14, 1, 16}
a["@Evilwoger"] = {"LibCustomIcons/icons/misc2/evilwoger_anim.dds", 29, 1, 14}
a["@Loganfu"] = {"LibCustomIcons/icons/misc2/loganfu_anim.dds", 18, 1, 10}
a["@frzgmg"] = {"LibCustomIcons/icons/misc2/frzgmg_anim.dds", 12, 1, 10}
a["@xEpic_ll"] = {"LibCustomIcons/icons/misc2/xepicll_anim.dds", 8, 5, 14}
a["@ArieNight"] = {"LibCustomIcons/icons/misc2/arienight_anim.dds", 9, 1, 13}
a["@L'ake"] = {"LibCustomIcons/icons/misc2/lake_anim.dds", 47, 1, 33}
a["@VastVortex"] = {"LibCustomIcons/icons/misc2/vastvortex_anim2.dds", 3, 1, 15}
a["@Turtledump"] = {"LibCustomIcons/icons/misc2/turtledump_anim.dds", 14, 1, 14}
a["@lmaglnary"] = {"LibCustomIcons/icons/misc2/lmaglnary_anim.dds", 8, 6, 28}
a["@BrownTyger"] = {"LibCustomIcons/icons/misc2/browntyger_anim.dds", 11, 1, 12}
a["@MaksonShishka"] = {"LibCustomIcons/icons/misc2/maksonshishka_anim.dds", 13, 1, 7}
a["@NukeOrIDip"] = {"LibCustomIcons/icons/misc2/daedalus2020_anim.dds", 7, 5, 10}
a["@Atnightgrind"] = {"LibCustomIcons/icons/misc2/atnightgrind_anim.dds", 11, 1, 11}
a["@My.stery"] = {"LibCustomIcons/icons/misc2/mystery_anim.dds", 5, 4, 10}
a["@icAirborne"] = {"LibCustomIcons/icons/misc2/icairborne_anim.dds", 3, 1, 35}
a["@moth3rlov3r"] = {"LibCustomIcons/icons/misc2/moth3rlov3r_anim.dds", 17, 2, 40}
a["@madmaurice72"] = {"LibCustomIcons/icons/misc/deltexeso_anim.dds", 3, 1, 10}
