-- SPDX-FileCopyrightText: 2025 m00nyONE
-- SPDX-License-Identifier: Artistic-2.0

local lib_name = "LibCustomIcons"
local lib = _G[lib_name]
local s = lib.GetStaticTable()
local a = lib.GetAnimatedTable()

s["@nacktermann"] = "LibCustomIcons/icons/misc3/tob145.dds"
s["@KampfKeks13"] = "LibCustomIcons/icons/misc3/kampfkeks13.dds"
s["@Stoned777"] = "LibCustomIcons/icons/misc3/stoned777.dds"
s["@KijuTiz"] = "LibCustomIcons/icons/misc3/justweaver.dds"
s["@Chihiro91"] = "LibCustomIcons/icons/misc3/Chihiro91.dds"
s["@Ironliljordy"] = "LibCustomIcons/icons/misc3/ironliljordy.dds"
s["@German1990"] = "LibCustomIcons/icons/misc3/german1990.dds"
s["@Elnadrion"] = "LibCustomIcons/icons/misc3/elnadrion.dds"
s["@Boris227"] = "LibCustomIcons/icons/misc3/boris227.dds"
s["@Kharjo94"] = "LibCustomIcons/icons/misc3/kharjo94.dds"
s["@Darkx8"] = "LibCustomIcons/icons/misc3/darkx82.dds"
s["@ILxd"] = "LibCustomIcons/icons/misc3/ilxdz.dds"
s["@AerisThePure"] = "LibCustomIcons/icons/misc3/aeristhepure.dds"
s["@Ellaria-MarteIl"] = "LibCustomIcons/icons/misc/arcirevenge.dds"
s["@Greenback86"] = "LibCustomIcons/icons/misc3/greenback86.dds"
s["@Schaumamoi7"] = "LibCustomIcons/icons/misc3/schaumamoi7.dds"
s["@AuT_Execute"] = "LibCustomIcons/icons/misc3/autexecute.dds"
s["@RottingAlien"] = "LibCustomIcons/icons/misc3/rottingalien.dds"
s["@Heavy_Frags"] = "LibCustomIcons/icons/misc3/heavyfrags.dds"
s["@Sabretusks"] = "LibCustomIcons/icons/misc3/sabretusks.dds"
s["@tweedle-dum"] = "LibCustomIcons/icons/misc3/mrtweedle.dds"
s["@lPredl"] = "LibCustomIcons/icons/misc3/lpredl.dds"
s["@Thrasher910"] = "LibCustomIcons/icons/misc3/thrasher910.dds"
s["@JuiceGotThaJuice"] = "LibCustomIcons/icons/misc3/juicegotthajuice.dds"
s["@loneloba"] = "LibCustomIcons/icons/misc3/loneloba.dds"
s["@StepsInTheSilence"] = "LibCustomIcons/icons/misc3/stepsinthesilence.dds"
s["@NeroEso"] = "LibCustomIcons/icons/misc3/neroeso.dds"
s["@rayneghost"] = "LibCustomIcons/icons/misc3/rayneghost.dds"
s["@BeTempted"] = "LibCustomIcons/icons/misc3/nguyenph88.dds"
s["@Baluron"] = "LibCustomIcons/icons/misc3/baluron.dds"
s["@garbage_llama"] = "LibCustomIcons/icons/misc3/garbage_llama.dds"
s["@Mofuu"] = "LibCustomIcons/icons/misc3/Mofuu_2.dds"
s["@cenocip"] = "LibCustomIcons/icons/misc3/cenocip.dds"
s["@caboosiebadass"] = "LibCustomIcons/icons/misc3/caboosiebadass.dds"
s["@xRosskag"] = "LibCustomIcons/icons/misc3/rosskagx2.dds"
s["@CrypticAX"] = "LibCustomIcons/icons/misc3/crypticax.dds"
s["@hiddle_z"] = "LibCustomIcons/icons/misc3/hiddlez.dds"
s["@ChaosFractal"] = "LibCustomIcons/icons/misc3/chaosfractal.dds"
s["@xJumpinJackFlash"] = "LibCustomIcons/icons/misc3/xjumpinjackflash.dds"
s["@BigCarl78"] = "LibCustomIcons/icons/misc3/bigcarl78.dds"
s["@imcantu"] = "LibCustomIcons/icons/misc3/imcantu2.dds"
s["@birdhippy"] = "LibCustomIcons/icons/misc3/birdhippy.dds"
s["@Kassinu"] = "LibCustomIcons/icons/misc3/kassinu.dds"
s["@Pacman_862"] = "LibCustomIcons/icons/misc3/pacman862.dds"
s["@Mytheia"] = "LibCustomIcons/icons/misc3/Mytheia.dds"
s["@Waiiveurn"] = "LibCustomIcons/icons/misc3/waiiveurn.dds"
s["@Alfadur88"] = "LibCustomIcons/icons/misc3/alfadur88.dds"
s["@PCP-Prod"] = "LibCustomIcons/icons/misc3/pcpprod.dds"
s["@PoisonArrrow"] = "LibCustomIcons/icons/misc3/poisonarrrowttv.dds"
s["@BigSplits"] = "LibCustomIcons/icons/misc3/bigsplits.dds"
s["@Zottel-Obi"] = "LibCustomIcons/icons/misc3/obi19092.dds"
s["@xt0ya"] = "LibCustomIcons/icons/misc3/xt0ya.dds"
s["@STRFK"] = "LibCustomIcons/icons/misc3/strfk.dds"
s["@AluwenSeaBright"] = "LibCustomIcons/icons/misc3/aluwenseabright.dds"
s["@genericvillager.exe"] = "LibCustomIcons/icons/misc3/genericvillagerexe.dds"
s["@MafistoCHEF"] = "LibCustomIcons/icons/misc3/mafistochef2.dds"
s["@T0mii"] = "LibCustomIcons/icons/misc3/t0mii.dds"
s["@Mistake199"] = "LibCustomIcons/icons/misc3/mistake199.dds"
s["@pepitogonzales420"] = "LibCustomIcons/icons/misc3/pepitogonzales420.dds"
s["@JoXeM33"] = "LibCustomIcons/icons/misc3/joxem33.dds"
s["@Maylachen"] = "LibCustomIcons/icons/misc3/maylachen.dds"
s["@epmak"] = "LibCustomIcons/icons/flags/russia.dds"
s["@Reaper0507"] = "LibCustomIcons/icons/misc3/Reaper0507.dds"
s["@Erelamae"] = "LibCustomIcons/icons/misc3/erelamae.dds"
s["@Bouns"] = "LibCustomIcons/icons/misc3/bouns.dds"
s["@kurai.mori"] = "LibCustomIcons/icons/misc3/moriarti.dds"
s["@TemaIT"] = "LibCustomIcons/icons/misc3/xtemanit2.dds"
s["@HavannaMane"] = "LibCustomIcons/icons/misc3/havannamane2.dds"
s["@aX.i"] = "LibCustomIcons/icons/misc3/axi.dds"
s["@Linuz_LK"] = "LibCustomIcons/icons/misc3/linuzlk.dds"
s["@spaghettisenpai"] = "LibCustomIcons/icons/misc3/spaghettisenpai.dds"
s["@DoMolition"] = "LibCustomIcons/icons/misc3/domolition.dds"
s["@Dodo144"] = "LibCustomIcons/icons/misc3/dodo144.dds"
s["@Smov"] = "LibCustomIcons/icons/misc3/Smov1.dds"
s["@Yurime"] = "LibCustomIcons/icons/misc3/yurime.dds"
s["@Sererinelle"] = "LibCustomIcons/icons/misc3/sererinelle.dds"
s["@Sererhillis"] = s["@Sererinelle"]
s["@maxrider"] = "LibCustomIcons/icons/misc3/maxrider.dds"
s["@Pimotruko"] = "LibCustomIcons/icons/misc3/pimotruko.dds"
s["@NotCorey"] = "LibCustomIcons/icons/misc3/notcorey.dds"
s["@StarvedGarden"] = "LibCustomIcons/icons/misc3/starvedgarden2.dds"
s["@ooNight"] = "LibCustomIcons/icons/misc3/oonight.dds"
s["@Blessing-quan"] = "LibCustomIcons/icons/misc3/blessingquan.dds"
s["@ItsNilin"] = "LibCustomIcons/icons/misc3/itsnilin2.dds"
s["@Nario15"] = "LibCustomIcons/icons/misc3/nario152.dds"
s["@DracielS4"] = "LibCustomIcons/icons/misc3/draciela4.dds"
s["@Vuz3"] = "LibCustomIcons/icons/misc3/vuz3.dds"
s["@driiitz"] = "LibCustomIcons/icons/misc3/driitz1.dds"
s["@turgon97"] = "LibCustomIcons/icons/misc3/turgon97.dds"
s["@ZJBLACK"] = "LibCustomIcons/icons/misc3/zjblack.dds"
s["@Squibbji"] = "LibCustomIcons/icons/misc3/Squibbji_2.dds"
s["@Hayden0X"] = "LibCustomIcons/icons/misc3/hayden0x2.dds"
s["@rainnn201"] = "LibCustomIcons/icons/misc3/rain201.dds"
s["@Sergeant_Dark"] = "LibCustomIcons/icons/misc3/sergeantdark.dds"
s["@RoxyDOOM"] = "LibCustomIcons/icons/misc3/roxydoom.dds"
s["@Paaatchy"] = "LibCustomIcons/icons/misc3/paaatchy4.dds"
s["@Vapor155"] = "LibCustomIcons/icons/misc3/vapor155.dds"
s["@Drayzon"] = "LibCustomIcons/icons/misc3/drayzon.dds"
s["@AlekWithK"] = "LibCustomIcons/icons/misc3/alekwithk.dds"
s["@miniminilli"] = "LibCustomIcons/icons/misc3/miniminilli.dds"
s["@MalleLuck"] = "LibCustomIcons/icons/misc3/malleluck.dds"
s["@Paath"] = "LibCustomIcons/icons/misc3/paath2.dds"
s["@Sparkiana"] = "LibCustomIcons/icons/misc3/Sparkiana_2.dds"
s["@cahlisi_xo"] = "LibCustomIcons/icons/misc3/cahlisixo.dds"
s["@Skylaxs"] = "LibCustomIcons/icons/misc3/skylaxs2.dds"
s["@paulynator"] = "LibCustomIcons/icons/misc3/paulynation2.dds"
s["@MarcaoP7"] = "LibCustomIcons/icons/misc3/israelense.dds"
s["@Lina_sb"] = "LibCustomIcons/icons/misc3/linasb.dds"
s["@Madicin"] = "LibCustomIcons/icons/misc3/madicin.dds"
s["@Cyber_Marz"] = "LibCustomIcons/icons/misc3/cybermarz.dds"
s["@Sinister_86"] = "LibCustomIcons/icons/misc3/sinistervermillion3.dds"
s["@Kendov64"] = "LibCustomIcons/icons/misc3/kendov64.dds"
s["@N.ana"] = "LibCustomIcons/icons/misc3/nana.dds"
s["@SlyBread"] = "LibCustomIcons/icons/misc3/slybread.dds"
s["@Limwen"] = "LibCustomIcons/icons/misc3/limwen.dds"
s["@Sak_enplastik"] = "LibCustomIcons/icons/misc3/sakenplastik.dds"
s["@RLRevenant"] = "LibCustomIcons/icons/misc3/rlrevenant.dds"
s["@Oberyn-MarteIl"] = "LibCustomIcons/icons/misc3/yutzkopf.dds"
s["@Raiden33"] = "LibCustomIcons/icons/misc3/raiden33.dds"
s["@Fred'dy"] = "LibCustomIcons/icons/misc3/freddy.dds"
s["@Amanalyre"] = "LibCustomIcons/icons/misc3/amanalyre.dds"
s["@patockin"] = "LibCustomIcons/icons/misc3/patockin.dds"
s["@relablues"] = "LibCustomIcons/icons/misc3/relablues.dds"
s["@shantina"] = "LibCustomIcons/icons/misc3/shantina.dds"
s["@Tinso"] = "LibCustomIcons/icons/misc3/tinso2.dds"
s["@WhiteHesky"] = "LibCustomIcons/icons/misc3/whitehesky2.dds"
s["@RaZor78"] = "LibCustomIcons/icons/misc3/razor782.dds"
s["@V3n0m78"] = "LibCustomIcons/icons/misc3/v3n0m78.dds"
s["@Tyxr"] = "LibCustomIcons/icons/misc3/tyxr2.dds"
s["@Braunizt"] = "LibCustomIcons/icons/misc3/braunizt.dds"
s["@RickySpanish967"] = "LibCustomIcons/icons/misc3/rickyspanish967.dds"
s["@ScarletteRed"] = "LibCustomIcons/icons/misc3/scarlettered.dds"
s["@VenmESO"] = "LibCustomIcons/icons/misc3/cafezin2.dds"
s["@DANGER_PLATYPUS"] = "LibCustomIcons/icons/misc3/dangerplatypus.dds"
s["@TankZeus"] = "LibCustomIcons/icons/misc3/tankzeus2.dds"
s["@tYarisdaprincess"] = "LibCustomIcons/icons/misc3/tyarisdaprincess.dds"
s["@Akaneee"] = "LibCustomIcons/icons/misc3/hitsuno.dds"
s["@LowkyQc"] = "LibCustomIcons/icons/misc3/lowkyqc.dds"
s["@barniz"] = "LibCustomIcons/icons/misc3/barniz.dds"
s["@RagedAvenger"] = "LibCustomIcons/icons/misc3/ragedavenger.dds"
s["@Soarxyn"] = "LibCustomIcons/icons/misc3/soarxyn.dds"
s["@PandaxeHD"] = "LibCustomIcons/icons/misc3/pandaxehd.dds"
s["@Ninjanate1337"] = "LibCustomIcons/icons/misc3/ninjanate1337.dds"
s["@xKatara"] = "LibCustomIcons/icons/misc3/xkatara.dds"
s["@salt_charcoal"] = "LibCustomIcons/icons/misc3/saltcharcoal.dds"
s["@G8GETA"] = "LibCustomIcons/icons/misc3/g8geta.dds"
s["@FreedomSorc"] = "LibCustomIcons/icons/misc3/freedomsorc.dds"
s["@Jcondy"] = "LibCustomIcons/icons/misc3/jcondy.dds"
s["@Changuita"] = "LibCustomIcons/icons/misc3/changuita.dds"
s["@Kuudo156"] = "LibCustomIcons/icons/misc3/kuudo156.dds"
s["@hemreakil"] = "LibCustomIcons/icons/misc3/hemreakil.dds"
s["@InsanityMind"] = "LibCustomIcons/icons/misc3/insanitymind.dds"
s["@Tryzm"] = "LibCustomIcons/icons/misc3/tryzm.dds"
s["@Luust"] = "LibCustomIcons/icons/misc3/luust2.dds"
s["@Alistair.exe"] = "LibCustomIcons/icons/misc3/Alistair.exe.dds"
s["@Cola1974"] = "LibCustomIcons/icons/misc3/cola1974.dds"
s["@MysticSoley"] = "LibCustomIcons/icons/misc3/mysticsoley2.dds"
s["@Ecaetera"] = "LibCustomIcons/icons/misc3/ecaetera.dds"
s["@Darkbeulus"] = "LibCustomIcons/icons/misc3/darkbeulus.dds"
s["@Unusualtouch"] = "LibCustomIcons/icons/misc3/unusualtouch.dds"
s["@Eddyst"] = "LibCustomIcons/icons/misc3/eddyst2.dds"
s["@LaK1ng"] = "LibCustomIcons/icons/misc3/lak1ng3.dds"
s["@rathat"] = "LibCustomIcons/icons/misc3/rathat.dds"
s["@MissRazan"] = "LibCustomIcons/icons/misc3/MissRazan_2.dds"
s["@SimpOnDuty"] = "LibCustomIcons/icons/misc3/SimpOnDuty.dds"
s["@xgalia"] = "LibCustomIcons/icons/misc3/xgalia.dds"
s["@Hunding_Swordmaster"] = "LibCustomIcons/icons/misc3/hundingswordmaster2.dds"
s["@zolipei"] = "LibCustomIcons/icons/misc3/zolipei.dds"
s["@E'gma"] = "LibCustomIcons/icons/misc3/egmamurderer4.dds"
s["@Torsuff"] = "LibCustomIcons/icons/misc3/torsuff.dds"
s["@fp-x"] = "LibCustomIcons/icons/misc3/fp-x.dds"
s["@JulianHunter"] = "LibCustomIcons/icons/misc3/julianhunter.dds"
s["@ShelenSheylis"] = "LibCustomIcons/icons/misc3/shelensheylis.dds"
s["@foggy_rain"] = "LibCustomIcons/icons/misc3/foggy_rain.dds"
s["@Jukiho"] = "LibCustomIcons/icons/misc3/jukiho2.dds"
s["@wDrizz"] = "LibCustomIcons/icons/misc3/drizzdourden.dds"
s["@Razzbut"] = "LibCustomIcons/icons/misc3/razzbut2.dds"
s["@ValoR1831"] = "LibCustomIcons/icons/misc3/valor1831.dds"
s["@Tomedn"] = "LibCustomIcons/icons/misc3/tomedn.dds"
s["@TheHairyCamel"] = "LibCustomIcons/icons/misc3/thehairycamel.dds"
s["@Ellimist_Entreri"] = "LibCustomIcons/icons/misc3/ellimistentreri.dds"
s["@AssassinsLight"] = "LibCustomIcons/icons/misc3/assassinslight.dds"
s["@Lucazoyde"] = "LibCustomIcons/icons/misc3/lucazoyde.dds"
s["@Flawless_Ace"] = "LibCustomIcons/icons/misc3/flawlessace.dds"
s["@Sk.eP"] = "LibCustomIcons/icons/misc3/skep.dds"
s["@Shadeous"] = "LibCustomIcons/icons/misc3/shadeous.dds"
s["@VEx43"] = "LibCustomIcons/icons/misc3/vex43.dds"
s["@p.et"] = "LibCustomIcons/icons/misc3/pet2.dds"
s["@GooblinHD"] = "LibCustomIcons/icons/misc3/gooblinhd.dds"
s["@HushDieRepeat"] = "LibCustomIcons/icons/misc3/hushdierepeat.dds"
s["@Lygbereth"] = "LibCustomIcons/icons/misc3/lygbereth.dds"
s["@xHaxor"] = "LibCustomIcons/icons/misc3/xhaxor.dds"
s["@NapalmEU"] = "LibCustomIcons/icons/misc3/napalmeu.dds"
s["@ryanstewart"] = "LibCustomIcons/icons/misc3/ryanstewart.dds"
s["@Kityn"] = "LibCustomIcons/icons/misc3/kityn.dds"
s["@RiDer_4296"] = "LibCustomIcons/icons/misc3/rider4296.dds"
s["@MrZeDark"] = "LibCustomIcons/icons/misc3/mrzedark.dds"
s["@tienchi"] = "LibCustomIcons/icons/misc3/tienchi.dds"
s["@swm'90"] = "LibCustomIcons/icons/misc3/swm90.dds"
s["@Y10K"] = "LibCustomIcons/icons/misc3/y10k2.dds"
s["@Crustyy"] = "LibCustomIcons/icons/misc3/crustyy2.dds"
s["@Radla"] = "LibCustomIcons/icons/misc3/connorx.dds"
s["@Lord'Gwyn"] = "LibCustomIcons/icons/misc3/lordgwyn.dds"
s["@excludedrainbow"] = "LibCustomIcons/icons/misc3/excludedrainbow.dds"
s["@BufordTJustice99"] = "LibCustomIcons/icons/misc3/bufordtjustice99.dds"
s["@StefanPro"] = "LibCustomIcons/icons/misc3/stefanpro.dds"
s["@Karadocx57"] = "LibCustomIcons/icons/misc3/karadocx57.dds"
s["@Nessa_Raven132"] = "LibCustomIcons/icons/misc3/nessaraven132.dds"
s["@Jiloez"] = "LibCustomIcons/icons/misc3/jiloez2.dds"
s["@darksR"] = "LibCustomIcons/icons/misc3/darksr3.dds"
s["@Jacob_Nordhoff"] = "LibCustomIcons/icons/misc3/jacobnordhoff.dds"
s["@kkdshka88"] = "LibCustomIcons/icons/misc3/kkdshka88.dds"
s["@Dromex13"] = "LibCustomIcons/icons/misc3/dromex132.dds"
s["@Allanon313"] = "LibCustomIcons/icons/misc3/allanon313.dds"
s["@Soriana"] = "LibCustomIcons/icons/misc3/soriana.dds"
s["@TheAnhor"] = "LibCustomIcons/icons/misc3/theanhor.dds"
s["@novatrons"] = "LibCustomIcons/icons/misc3/novatrons.dds"
s["@Oceanbluee"] = "LibCustomIcons/icons/misc3/oceanbluee.dds"
s["@caffeinatedkit"] = "LibCustomIcons/icons/misc3/caffeinatedkit.dds"
s["@TheAudacity"] = "LibCustomIcons/icons/misc3/theaudacity.dds"
s["@Ekonomisti"] = "LibCustomIcons/icons/misc3/ekonomisti.dds"
s["@Raineri100"] = "LibCustomIcons/icons/misc3/raineri100.dds"
s["@Stainiiish"] = "LibCustomIcons/icons/misc3/stainiiish.dds"
s["@Vel0xxity"] = "LibCustomIcons/icons/misc3/vel0xxity.dds"
s["@Pwanda1"] = "LibCustomIcons/icons/misc3/pwanda1.dds"
s["@Anglamy"] = "LibCustomIcons/icons/misc3/anglamy.dds"
s["@Snoozy17"] = "LibCustomIcons/icons/misc3/snoozy17.dds"
s["@DreddCorpse"] = "LibCustomIcons/icons/misc3/dreddcorpse2.dds"
s["@IScaryFoxI"] = "LibCustomIcons/icons/misc3/iscaryfoxi.dds"
s["@Yezzll"] = "LibCustomIcons/icons/misc3/yezzll.dds"
s["@TricksterFire"] = "LibCustomIcons/icons/misc3/tricksterfire.dds"
s["@Mabzek"] = "LibCustomIcons/icons/misc3/mabzek.dds"
s["@Aeryïl"] = "LibCustomIcons/icons/misc3/aeryil.dds"
s["@Flankov"] = "LibCustomIcons/icons/misc3/flankov2.dds"
s["@BoMenzzz"] = "LibCustomIcons/icons/misc3/bomenzzz.dds"
s["@Allvitende"] = "LibCustomIcons/icons/misc3/allvitende.dds"
s["@lepiih"] = "LibCustomIcons/icons/misc3/lepiih.dds"
s["@Zybelle"] = "LibCustomIcons/icons/misc3/zybelle.dds"
s["@BlazingMarauder"] = "LibCustomIcons/icons/misc3/blazingmarauder.dds"
s["@Ultimatetaters"] = "LibCustomIcons/icons/misc3/ultimatetaters.dds"
s["@TheeJamesDean"] = "LibCustomIcons/icons/misc3/theejamesdean2.dds"
s["@imSavvy"] = "LibCustomIcons/icons/misc3/imsavvy.dds"
s["@fargo-forever"] = "LibCustomIcons/icons/misc3/fargoforever.dds"
s["@OVOmimi"] = "LibCustomIcons/icons/misc3/ovomimi.dds"
s["@Oceanbro"] = "LibCustomIcons/icons/misc3/oceanbro.dds"
s["@ImWelliss"] = "LibCustomIcons/icons/misc3/imwelliss2.dds"
s["@FizzyBabyy"] = "LibCustomIcons/icons/misc3/fizzybabyy.dds"
s["@Elenise"] = "LibCustomIcons/icons/misc3/elenise.dds"
s["@Try.Hard"] = "LibCustomIcons/icons/misc3/tryhard.dds"
s["@s.av"] = "LibCustomIcons/icons/misc3/sav.dds"
s["@Omynehrale"] = "LibCustomIcons/icons/misc3/omynehrale.dds"
s["@HoRidz"] = "LibCustomIcons/icons/misc3/HoRidz.dds"
s["@ChasexThisxLight"] = "LibCustomIcons/icons/misc3/hummerken.dds"
s["@NocturnalSonata"] = "LibCustomIcons/icons/misc3/nocturnalsonata.dds"
s["@Zauko"] = "LibCustomIcons/icons/misc3/zauko.dds"
s["@DaWasef"] = "LibCustomIcons/icons/misc3/dawasef.dds"
s["@Dusty_82"] = "LibCustomIcons/icons/misc3/dusty82.dds"
s["@cat-xileel"] = "LibCustomIcons/icons/misc3/catxileel.dds"
s["@Beltroniko"] = "LibCustomIcons/icons/misc3/beltroniko.dds"
s["@zemoyuki"] = "LibCustomIcons/icons/misc3/zemoyuki.dds"
s["@petta77"] = "LibCustomIcons/icons/misc3/petta772.dds"
s["@Vinz340XIV"] = "LibCustomIcons/icons/misc3/vinz340xiv.dds"
s["@RaveN_92"] = "LibCustomIcons/icons/misc3/raven922.dds"
s["@Duncan88"] = "LibCustomIcons/icons/misc3/duncan88.dds"
s["@Zerbse"] = "LibCustomIcons/icons/misc3/zerbse4.dds"
s["@xKING_CRACKENx"] = "LibCustomIcons/icons/misc3/xkingcrackenx.dds"
s["@rescuingangel"] = "LibCustomIcons/icons/misc3/rescuingangel.dds"
s["@Mandulin"] = "LibCustomIcons/icons/misc3/mandulin.dds"
s["@Sarah_MacKenzie"] = "LibCustomIcons/icons/misc3/sarahmackenzie.dds"
s["@Deschain_Kidona"] = "LibCustomIcons/icons/misc3/deschainkidona.dds"
s["@Aubrey_Kidona"] = "LibCustomIcons/icons/misc3/aubreykidona.dds"
s["@cjninja10"] = "LibCustomIcons/icons/misc3/cjninja10.dds"
s["@InfernalGoose"] = "LibCustomIcons/icons/misc/infernalgoose2.dds"
s["@PrincessBubblez"] = "LibCustomIcons/icons/misc3/princessbubblez.dds"
s["@Kizifer"] = "LibCustomIcons/icons/misc3/kizifer.dds"
s["@IrishxxPotato"] = "LibCustomIcons/icons/misc3/irishxxpotato.dds"
s["@EchoTiger"] = "LibCustomIcons/icons/misc3/echotiger.dds"
s["@SentryAg"] = "LibCustomIcons/icons/misc3/sentryag.dds"
s["@Cozen22"] = "LibCustomIcons/icons/misc3/cozen22.dds"
s["@Devilseye95"] = "LibCustomIcons/icons/misc3/devilseye95.dds"
s["@CAM-27"] = "LibCustomIcons/icons/misc3/cam27.dds"
s["@DunzEso"] = "LibCustomIcons/icons/misc3/dunzeso.dds"
s["@Corsair-BlackBeard"] = "LibCustomIcons/icons/misc3/corsairblackbeard.dds"
s["@Mermomma"] = "LibCustomIcons/icons/misc3/mermomma.dds"
s["@koiyaza"] = "LibCustomIcons/icons/misc3/koiyaza.dds"
s["@NeuroniXx"] = "LibCustomIcons/icons/misc3/neuronixx.dds"
s["@Skraelingjar"] = "LibCustomIcons/icons/misc3/Skraelingjar_2.dds"
s["@KenLuyckx"] = "LibCustomIcons/icons/misc3/kenluyckx.dds"
s["@QQ_Zayka"] = "LibCustomIcons/icons/misc3/qqzayka.dds"
s["@Lenny-S"] = "LibCustomIcons/icons/misc3/Lenny-S.dds"
s["@MCBerst"] = "LibCustomIcons/icons/misc3/mcberst.dds"
s["@fierykibbles585"] = "LibCustomIcons/icons/misc3/fierykibbles585.dds"
s["@Exorzist0310"] = "LibCustomIcons/icons/misc3/exorzist0310.dds"
s["@BooBoozinho"] = "LibCustomIcons/icons/misc3/booboozinho2.dds"
s["@puertoniko"] = "LibCustomIcons/icons/misc3/puertoniko.dds"
s["@iDiva"] = "LibCustomIcons/icons/misc3/idiva.dds"
s["@So-so"] = "LibCustomIcons/icons/misc3/soso.dds"
s["@DeathOfTheSky"] = "LibCustomIcons/icons/misc3/deathofthesky.dds"
s["@josselinA52"] = "LibCustomIcons/icons/misc3/josselina52.dds"
s["@Jaegeron"] = "LibCustomIcons/icons/misc3/jaegeron.dds"
s["@Onna-Bushi"] = "LibCustomIcons/icons/misc3/onnabushi2.dds"
s["@Calie420"] = "LibCustomIcons/icons/misc3/calie421.dds"
s["@DarbersGaming"] = "LibCustomIcons/icons/misc3/darbersgaming.dds"
s["@EternalSessions6"] = "LibCustomIcons/icons/misc3/eternalsessions.dds"
s["@Diffused"] = "LibCustomIcons/icons/misc3/diffused.dds"
s["@mhat"] = "LibCustomIcons/icons/misc3/mhat.dds"
s["@hamiltonmaths"] = "LibCustomIcons/icons/misc3/hami1tonmath.dds"
s["@Bicullo"] = "LibCustomIcons/icons/misc3/Bicullo1.dds"
s["@FlufflePffdrr"] = "LibCustomIcons/icons/misc3/flufflepffdrr.dds"
s["@Alohawaii808"] = "LibCustomIcons/icons/misc3/alohawaii808.dds"
s["@Stripey.Socks"] = "LibCustomIcons/icons/misc3/stripeysocks.dds"
s["@DJBodyOil"] = "LibCustomIcons/icons/misc3/djbodyoil2.dds"
s["@Tempozz"] = "LibCustomIcons/icons/misc3/tempozz.dds"
s["@GuardianlIx"] = "LibCustomIcons/icons/misc3/guardianlix.dds"
s["@ZeHeden"] = "LibCustomIcons/icons/misc3/zeheden2.dds"
s["@Johnbello2611"] = "LibCustomIcons/icons/misc3/johnbello2611.dds"
s["@iBeardBro"] = "LibCustomIcons/icons/misc3/ibeardbros2.dds"
s["@Methad1"] = "LibCustomIcons/icons/misc3/methad1.dds"
s["@teddi84"] = "LibCustomIcons/icons/misc3/teddi84.dds"
s["@Hexperos"] = "LibCustomIcons/icons/misc3/kirillofficial2.dds"
s["@bashthebishop"] = "LibCustomIcons/icons/hodor/alcast.dds"
s["@FONSEC4"] = "LibCustomIcons/icons/misc3/fonsec4.dds"
s["@Rhaccory"] = "LibCustomIcons/icons/misc3/rhaccory.dds"
s["@aGitheone"] = "LibCustomIcons/icons/misc3/agitheone.dds"
s["@salvathia"] = "LibCustomIcons/icons/misc3/salvathia.dds"
s["@Miyumiu"] = "LibCustomIcons/icons/misc3/miyumiu.dds"
s["@Sinolai"] = "LibCustomIcons/icons/misc3/sinolai.dds"
s["@LLawlietL"] = "LibCustomIcons/icons/misc3/llawlietl.dds"
s["@xSovrin"] = "LibCustomIcons/icons/misc3/xsovrin.dds"
s["@L.aurelin"] = "LibCustomIcons/icons/misc3/laurelin.dds"
s["@Vexsigon"] = "LibCustomIcons/icons/misc3/vexsigon.dds"
s["@TrafDlaww"] = "LibCustomIcons/icons/misc3/trafdlaww.dds"
s["@Bangalolz"] = "LibCustomIcons/icons/misc3/bangalolz.dds"
s["@Chayaya"] = "LibCustomIcons/icons/misc3/chayaya.dds"
s["@Vaelkhyr"] = "LibCustomIcons/icons/misc3/vaelkhyr2.dds"
s["@OREOSA"] = "LibCustomIcons/icons/misc3/oreosa.dds"
s["@JolyPots"] = "LibCustomIcons/icons/misc3/JolyPots2.dds"
s["@Lucily"] = "LibCustomIcons/icons/misc3/lucily.dds"
s["@Lingshen"] = "LibCustomIcons/icons/misc3/lingshen.dds"
s["@Darknesscane92"] = "LibCustomIcons/icons/misc3/darknesscane92.dds"
s["@street-wraith"] = "LibCustomIcons/icons/misc3/streetwraith.dds"
s["@o_illusive"] = "LibCustomIcons/icons/misc3/oillusive.dds"
s["@ObesePenguin569"] = "LibCustomIcons/icons/misc3/obesepenguin569.dds"
s["@Snowballins"] = "LibCustomIcons/icons/misc3/snowballins.dds"
s["@TEQ1"] = "LibCustomIcons/icons/misc3/teq19.dds"
s["@carolho"] = "LibCustomIcons/icons/misc3/carolho.dds"
s["@shriane"] = "LibCustomIcons/icons/misc3/shriane.dds"
s["@NefastuzBR"] = "LibCustomIcons/icons/misc3/nefastuzbr.dds"
s["@Mario987"] = "LibCustomIcons/icons/misc3/mario987.dds"
s["@Tuggles2015"] = "LibCustomIcons/icons/misc3/tuggles2015.dds"
s["@Tos.t"] = "LibCustomIcons/icons/misc3/tost.dds"
s["@Davian152"] = "LibCustomIcons/icons/misc3/davian152.dds"
s["@yoshihide"] = "LibCustomIcons/icons/misc3/yoshihide.dds"
s["@brennz"] = "LibCustomIcons/icons/misc3/brennz.dds"
s["@Hyoga1"] = "LibCustomIcons/icons/misc3/hyoga1.dds"
s["@Drara_ra"] = "LibCustomIcons/icons/misc3/drarara.dds"
s["@Rangerthree1"] = "LibCustomIcons/icons/misc3/rangerthree1.dds"
s["@MusCle420"] = "LibCustomIcons/icons/misc3/muscle420.dds"
s["@SpassBremser"] = "LibCustomIcons/icons/misc3/spassbremser.dds"
s["@Skaijade"] = "LibCustomIcons/icons/misc3/skaijade2.dds"
s["@Cielsis"] = "LibCustomIcons/icons/misc3/cielsis.dds"
s["@Eonw3"] = "LibCustomIcons/icons/misc3/eonw3.dds"
s["@mayhem1987"] = "LibCustomIcons/icons/misc3/mayhem1987.dds"
s["@Silent-19"] = "LibCustomIcons/icons/misc3/silent19.dds"
s["@Kosomari"] = "LibCustomIcons/icons/misc3/kosomari.dds"
s["@Xanox-xx5"] = "LibCustomIcons/icons/misc3/xanoxxx5.dds"
s["@Rendall05"] = "LibCustomIcons/icons/misc3/rendall05.dds"
s["@AngrySugar"] = "LibCustomIcons/icons/misc3/angrysugar.dds"
s["@Semetcky"] = "LibCustomIcons/icons/misc3/semetcky.dds"
s["@jawluiz"] = "LibCustomIcons/icons/misc3/jawluiz.dds"
s["@File2606"] = "LibCustomIcons/icons/misc3/file2606.dds"
s["@KatLynx"] = "LibCustomIcons/icons/misc3/katlynx.dds"
s["@Sacmai"] = "LibCustomIcons/icons/misc3/sacmai.dds"
s["@eliasnollnollett"] = "LibCustomIcons/icons/misc3/eliasnollnollett2.dds"
s["@ylinalta"] = "LibCustomIcons/icons/misc3/ylinalta.dds"
s["@younguitar"] = "LibCustomIcons/icons/misc3/younguitar.dds"
s["@Constantine.Valdor"] = "LibCustomIcons/icons/misc3/dimontii2.dds"
s["@VoidMech"] = "LibCustomIcons/icons/misc3/voidmech.dds"
s["@Lilmaxwell"] = "LibCustomIcons/icons/misc3/lilmaxwell.dds"
s["@Thendus"] = "LibCustomIcons/icons/misc3/thendus.dds"
s["@Thejayh"] = "LibCustomIcons/icons/misc3/thejayh.dds"
s["@xXRed-Bau5Xx"] = "LibCustomIcons/icons/misc3/xxredbau5xx.dds"
s["@Sajahu"] = "LibCustomIcons/icons/misc3/sajahu.dds"
s["@Amertuim"] = "LibCustomIcons/icons/misc3/amertuim3.dds"
s["@Kran12"] = "LibCustomIcons/icons/misc3/kran12.dds"
s["@Bodys"] = "LibCustomIcons/icons/misc3/bodys.dds"
s["@Jonnie.Hadouken"] = "LibCustomIcons/icons/misc3/jonniehadouken.dds"
s["@w1nd1r"] = "LibCustomIcons/icons/misc3/w1nd1r.dds"
s["@wdtfshi"] = "LibCustomIcons/icons/misc3/wdtfshi.dds"
s["@HanzoHattori2"] = "LibCustomIcons/icons/misc3/hanzohattori2.dds"
s["@Shingin"] = "LibCustomIcons/icons/misc3/Shingin.dds"
a["@Shingin"] = {"LibCustomIcons/icons/misc3/Shingin_anim.dds", 25, 1, 14}
s["@JayEmTheMad"] = "LibCustomIcons/icons/misc3/jayemthemad.dds"
s["@Berfogod"] = "LibCustomIcons/icons/misc3/berfogod.dds"
s["@Anfirit"] = "LibCustomIcons/icons/misc3/anfirit.dds"
s["@Chance_25"] = "LibCustomIcons/icons/misc3/chance25.dds"
s["@Samnons88"] = "LibCustomIcons/icons/misc3/samnons88.dds"
s["@rebel430"] = "LibCustomIcons/icons/misc3/rebel430.dds"
s["@Lyxuff"] = "LibCustomIcons/icons/misc3/lyxuff.dds"
s["@Doctor-Braindead"] = "LibCustomIcons/icons/misc3/doctorbraindead.dds"
s["@Inoculated"] = "LibCustomIcons/icons/misc3/inoculated.dds"
s["@TooGoodForYou"] = "LibCustomIcons/icons/misc3/toogoodforyou.dds"
s["@WorstNightmare1991"] = "LibCustomIcons/icons/misc3/worstnightmare1991.dds"
s["@Juarezz"] = "LibCustomIcons/icons/misc3/juarezz.dds"
s["@TRUEARKADATA"] = "LibCustomIcons/icons/misc3/truearkadata.dds"
s["@HiddenMastery"] = "LibCustomIcons/icons/misc3/hiddenmastery.dds"
s["@NemiShed"] = "LibCustomIcons/icons/misc3/ksille.dds"
s["@RedHand92"] = "LibCustomIcons/icons/misc3/redhand92.dds"
s["@Timbrah"] = "LibCustomIcons/icons/misc3/timbrah.dds"
s["@yuffzor1"] = "LibCustomIcons/icons/misc3/yuffzor1.dds"
s["@l3lackeneD"] = "LibCustomIcons/icons/misc3/l3lackened.dds"
s["@RHOPropagandalf"] = "LibCustomIcons/icons/misc3/rhopropagandalf.dds"
s["@xXAnSchlagXx"] = "LibCustomIcons/icons/misc3/xxanschlagxx.dds"
s["@Minxin"] = "LibCustomIcons/icons/misc3/minxin.dds"
s["@Tijer87"] = "LibCustomIcons/icons/misc3/tijer87.dds"
s["@Superkraut"] = "LibCustomIcons/icons/misc3/superkraut.dds"
s["@Pato988"] = "LibCustomIcons/icons/misc3/pato988.dds"
s["@sam2401"] = "LibCustomIcons/icons/misc3/sam2401.dds"
s["@Daxicorra"] = "LibCustomIcons/icons/misc3/daxicorra.dds"
s["@Honnin_Bjorn"] = "LibCustomIcons/icons/misc3/honninbjorn.dds"
s["@McLadrones"] = "LibCustomIcons/icons/misc3/Matheuzynhow.dds"
s["@Devilish_Ahri"] = "LibCustomIcons/icons/misc3/Devilish_Ahri_2.dds"
s["@Kimchicken"] = "LibCustomIcons/icons/misc3/kimchicken.dds"
s["@gamercasual"] = "LibCustomIcons/icons/misc3/gamercasual.dds"
s["@HealShower"] = "LibCustomIcons/icons/misc3/healshower3.dds"
s["@drunkieowl"] = "LibCustomIcons/icons/misc3/drunkieowl2.dds"
s["@spacewolfplays"] = "LibCustomIcons/icons/misc3/spacewolfplays.dds"
s["@Comunist_Potato"] = "LibCustomIcons/icons/misc3/comunistpotato.dds"
s["@Skrebs"] = "LibCustomIcons/icons/misc3/Skrebs.dds"
s["@SirSkribz"] = s["@Skrebs"]
s["@CAS1NOVA"] = "LibCustomIcons/icons/misc3/CAS1NOVA.dds"
s["@PJMarc"] = "LibCustomIcons/icons/misc3/pjmarc.dds"
s["@Kurahfalgar"] = "LibCustomIcons/icons/misc3/kurahfalgar.dds"
s["@Iini"] = "LibCustomIcons/icons/misc3/linidseyy2.dds"
s["@Radwife"] = "LibCustomIcons/icons/misc3/radwife.dds"
s["@fenrynn"] = "LibCustomIcons/icons/misc3/fenrynn2.dds"
s["@bezeta"] = "LibCustomIcons/icons/misc3/bezeta3.dds"
s["@Morik72"] = "LibCustomIcons/icons/misc3/morik72.dds"
s["@Snaggel"] = "LibCustomIcons/icons/misc3/snaggel.dds"
s["@SanguisLupi"] = "LibCustomIcons/icons/misc3/sanguislupi.dds"
s["@Snoopman"] = "LibCustomIcons/icons/misc3/snoopman.dds"
s["@h'arry"] = "LibCustomIcons/icons/misc3/harry.dds"
s["@Karrika1992"] = "LibCustomIcons/icons/misc3/karrika1992.dds"
s["@alust"] = "LibCustomIcons/icons/misc3/alust.dds"
s["@Sweet_Mouse"] = "LibCustomIcons/icons/misc3/sweetmouse2.dds"
s["@Marbasar"] = "LibCustomIcons/icons/misc3/marbasar.dds"
s["@GeritoGamele"] = "LibCustomIcons/icons/misc3/geritogamele.dds"
s["@Imaslowlearner"] = "LibCustomIcons/icons/misc3/imaslowlearner.dds"
s["@immediacy"] = "LibCustomIcons/icons/misc3/immediacy.dds"
s["@OrpheusHarp"] = "LibCustomIcons/icons/misc3/orpheusharp.dds"
s["@Celesteela"] = "LibCustomIcons/icons/misc3/celesteela.dds"
s["@Primeevi1"] = "LibCustomIcons/icons/misc3/primeevi1.dds"
s["@obeseocean"] = "LibCustomIcons/icons/misc3/obeseocean.dds"
s["@thedurtybubble"] = "LibCustomIcons/icons/misc3/thedurtybubble.dds"
s["@Benzar00"] = "LibCustomIcons/icons/misc3/benzar00.dds"
s["@EqualEnd"] = "LibCustomIcons/icons/misc3/equalend.dds"
s["@Koikegmo"] = "LibCustomIcons/icons/misc3/koikegmo.dds"
s["@garnootnoot"] = "LibCustomIcons/icons/misc3/garnootnoot.dds"
s["@Saggyspandex"] = "LibCustomIcons/icons/misc3/saggyspandex.dds"
s["@para285"] = "LibCustomIcons/icons/misc3/para2853.dds"
s["@ladolz"] = "LibCustomIcons/icons/misc3/ladolz.dds"
s["@DreckigerDannn"] = "LibCustomIcons/icons/misc3/dreckigerdannn.dds"
s["@Sir.Gandalf"] = "LibCustomIcons/icons/misc3/sirgandalf.dds"
s["@Dead_Nito"] = "LibCustomIcons/icons/misc3/deadnito.dds"
s["@cutepotat0o"] = "LibCustomIcons/icons/misc3/cutepotat0o.dds"
s["@BitCopper"] = "LibCustomIcons/icons/misc3/BitCopper3.dds"
s["@ItsEntrail"] = "LibCustomIcons/icons/misc3/itsentrail.dds"
s["@Storm_Artificer"] = "LibCustomIcons/icons/misc3/stormartificer.dds"
s["@SamXVII"] = "LibCustomIcons/icons/misc3/samxvii.dds"
s["@Giltine777"] = "LibCustomIcons/icons/misc3/giltine777.dds"
s["@Sewtz"] = "LibCustomIcons/icons/misc3/sewtz.dds"
s["@C4_1397"] = "LibCustomIcons/icons/misc3/c41397.dds"
s["@chuckydiemörderpuppe"] = "LibCustomIcons/icons/misc3/chuckydiemorderpuppe.dds"
s["@GregorZamza"] = "LibCustomIcons/icons/misc3/GregorZamza_3.dds"
s["@Affenbaron"] = "LibCustomIcons/icons/misc3/affenbaron.dds"
s["@Saxy_Spaniard"] = "LibCustomIcons/icons/misc3/saxyspaniard2.dds"
s["@Mugiwara3514"] = "LibCustomIcons/icons/misc3/mugiwara3514.dds"
s["@Flonke"] = "LibCustomIcons/icons/misc3/flonke.dds"
s["@craxerr"] = "LibCustomIcons/icons/misc3/craxerr.dds"
s["@CraXerr"] = s["@craxerr"]
s["@SmackNCheese"] = "LibCustomIcons/icons/misc3/smackncheese.dds"
s["@Nithys"] = "LibCustomIcons/icons/misc3/Nithys_4.dds"
s["@predatorsoundsys"] = "LibCustomIcons/icons/misc3/predatorsoundsys.dds"
s["@lonelytoastmaker"] = "LibCustomIcons/icons/misc3/lonelytoastmaker.dds"
s["@Hydr3d"] = "LibCustomIcons/icons/misc3/hydr3d.dds"
s["@stevusbeefus"] = "LibCustomIcons/icons/misc3/stevusbeefus.dds"
s["@Randomochi"] = "LibCustomIcons/icons/misc3/randomochi.dds"
s["@woofwooff"] = "LibCustomIcons/icons/misc3/woofwooff.dds"
s["@RenegadeChook"] = "LibCustomIcons/icons/misc3/renegadechook.dds"
s["@SlenderHD"] = "LibCustomIcons/icons/misc3/slenderhd.dds"
s["@Hailan"] = "LibCustomIcons/icons/misc3/hailan.dds"
s["@YGREC94"] = "LibCustomIcons/icons/misc3/aoteso24.dds"
s["@alpdenizhan"] = "LibCustomIcons/icons/misc3/alpdenizhan.dds"
s["@NukeDuckZA"] = "LibCustomIcons/icons/misc3/nukeduckza3.dds"
s["@Scara713"] = "LibCustomIcons/icons/misc3/scara713.dds"
s["@GwynTheHuman"] = "LibCustomIcons/icons/misc3/thegennyhuman.dds"
s["@DSimonM"] = "LibCustomIcons/icons/misc3/dsimonm.dds"
s["@Peryite_001"] = "LibCustomIcons/icons/misc3/Peryite_001.dds"
s["@Croatt"] = "LibCustomIcons/icons/misc3/croatt.dds"
s["@Buratika"] = "LibCustomIcons/icons/misc3/buratika.dds"
s["@PHAEL"] = "LibCustomIcons/icons/misc3/phael.dds"
s["@Feeebulous"] = "LibCustomIcons/icons/misc3/feeebulous.dds"
s["@TheSarcasmFairy"] = "LibCustomIcons/icons/misc3/thesarcasmfairy.dds"
s["@touretticflower"] = "LibCustomIcons/icons/misc3/touretticflower.dds"
s["@NATHXN16"] = "LibCustomIcons/icons/misc3/nathxn16.dds"
s["@GreenWinny"] = "LibCustomIcons/icons/misc3/greenwinny.dds"
s["@FezMamba"] = "LibCustomIcons/icons/misc3/fezmamba.dds"
s["@BravoJuliet"] = "LibCustomIcons/icons/misc3/bravojuliet.dds"
s["@Devolapopola"] = "LibCustomIcons/icons/misc3/devolapopola.dds"
s["@Pupsas"] = "LibCustomIcons/icons/misc3/pupsas.dds"
s["@The_LaMi"] = "LibCustomIcons/icons/misc3/thelami.dds"
s["@Aerovertics"] = "LibCustomIcons/icons/misc3/aerovertics.dds"
s["@BoomHer"] = "LibCustomIcons/icons/misc3/boomher.dds"
s["@BowBowBaggins"] = "LibCustomIcons/icons/misc3/bowbowbaggins.dds"
s["@RealEmperor"] = "LibCustomIcons/icons/misc3/realemperor.dds"
s["@seven_pine-cones"] = "LibCustomIcons/icons/misc3/sevenpinecones.dds"
s["@Sir-Quackberry"] = "LibCustomIcons/icons/misc3/sirquackberry.dds"
s["@Chiyabi"] = "LibCustomIcons/icons/misc3/chiyabi.dds"
s["@Nilasnms"] = "LibCustomIcons/icons/misc3/nilasnms.dds"
s["@f.levi"] = "LibCustomIcons/icons/misc3/flevi.dds"
s["@Brybeaks"] = "LibCustomIcons/icons/misc3/brybeaks.dds"
s["@Santtutheman"] = "LibCustomIcons/icons/misc3/Santtutheman3.dds"
s["@Valkyrie-x"] = "LibCustomIcons/icons/misc3/valkyriex.dds"
s["@itsneiro"] = "LibCustomIcons/icons/misc3/itsneiro_3.dds"
s["@xDevilz"] = "LibCustomIcons/icons/misc3/xdevilz.dds"
s["@Heart.of-Coldharbour"] = "LibCustomIcons/icons/misc3/heartofcoldharbour.dds"
s["@Yaudira"] = "LibCustomIcons/icons/misc3/yaudira.dds"
s["@Kirjava76"] = "LibCustomIcons/icons/misc3/kirjava762.dds"
s["@Multay"] = "LibCustomIcons/icons/misc3/multay.dds"
s["@ice_baby"] = "LibCustomIcons/icons/misc3/icebaby.dds"
s["@Reznique"] = "LibCustomIcons/icons/misc3/reznique.dds"
s["@Caravague"] = "LibCustomIcons/icons/misc3/caravague2.dds"
s["@qubeshow"] = "LibCustomIcons/icons/misc3/qubeshow.dds"
s["@FatelessLava"] = "LibCustomIcons/icons/misc3/fatelesslava.dds"
s["@Marrrshhh"] = "LibCustomIcons/icons/misc3/marrrshhh.dds"
s["@r.avs"] = "LibCustomIcons/icons/misc3/r.avs.dds"
s["@WolfySaurusREX"] = "LibCustomIcons/icons/misc3/WolfySaurusREX_2.dds"
s["@Raluria"] = "LibCustomIcons/icons/misc3/raluria.dds"
s["@SilverLiss"] = "LibCustomIcons/icons/misc3/silverliss.dds"
s["@SquirtleSquadI"] = "LibCustomIcons/icons/misc3/squirtlesquadi.dds"
a["@SquirtleSquadI"] = {"LibCustomIcons/icons/misc3/SquirtleSquadI_anim.dds", 25, 2, 33}
s["@Feyrez"] = "LibCustomIcons/icons/misc3/feyrez.dds"
s["@WillyMancer69"] = "LibCustomIcons/icons/misc3/willymancer69.dds"
s["@OG_Stoop"] = "LibCustomIcons/icons/misc3/ogstoop.dds"
s["@AstreaTheMad"] = "LibCustomIcons/icons/misc3/astreathemad.dds"
s["@PocketMona"] = "LibCustomIcons/icons/misc3/pocketmona3.dds"
s["@milkomeda99"] = "LibCustomIcons/icons/misc3/milkomeda99.dds"
s["@Grila"] = "LibCustomIcons/icons/misc3/grila.dds"
s["@Danyooo"] = "LibCustomIcons/icons/misc3/danyooo.dds"
s["@michaeln399"] = "LibCustomIcons/icons/misc3/michaeln399.dds"
s["@Simorde"] = "LibCustomIcons/icons/misc3/simorde.dds"
s["@Der-Baumbart"] = "LibCustomIcons/icons/misc3/derbaumbart.dds"
s["@S.FE"] = "LibCustomIcons/icons/misc3/sfe.dds"
s["@L0SE"] = "LibCustomIcons/icons/misc3/l0se.dds"
s["@Dulatorr"] = "LibCustomIcons/icons/misc3/dulatorr.dds"
s["@UnasBehemoth"] = "LibCustomIcons/icons/misc3/unasbehemoth.dds"
s["@Ashenkin"] = "LibCustomIcons/icons/misc3/ashenkin.dds"
s["@Sheo98"] = "LibCustomIcons/icons/misc3/Sheo98.dds"
s["@elyasafko"] = "LibCustomIcons/icons/misc3/elyasafko.dds"
s["@Zubrowzka"] = "LibCustomIcons/icons/misc3/zubrowzka.dds"
s["@Moncc"] = "LibCustomIcons/icons/misc3/moncc.dds"
s["@Naskone1986"] = "LibCustomIcons/icons/misc3/naskone1986.dds"
s["@Anooo"] = "LibCustomIcons/icons/misc3/anooo.dds"
s["@Ping999"] = "LibCustomIcons/icons/misc3/ping999.dds"
s["@Xavis"] = "LibCustomIcons/icons/misc3/xavis2.dds"
s["@Caruple95"] = "LibCustomIcons/icons/misc3/caruple95.dds"
s["@Mareeve"] = "LibCustomIcons/icons/misc3/mareeve.dds"
s["@jwaye89"] = "LibCustomIcons/icons/misc3/jwaye89.dds"
s["@Lucas318"] = "LibCustomIcons/icons/misc3/lucas318.dds"
s["@Roycethed2"] = "LibCustomIcons/icons/misc3/roycethed2.dds"
s["@shadeomatic"] = "LibCustomIcons/icons/misc3/shadeomatic3.dds"
s["@sapphirefox31"] = "LibCustomIcons/icons/misc3/sapphirefox31.dds"
s["@deadpun"] = "LibCustomIcons/icons/misc3/deadpun_2.dds"
s["@Lernaeus"] = "LibCustomIcons/icons/misc3/lernaeus.dds"
s["@xRe4MasTeRx"] = "LibCustomIcons/icons/misc3/xre4masterx.dds"
s["@ZaiZah"] = "LibCustomIcons/icons/misc3/zaizah_2.dds"
s["@LouuDobbs"] = "LibCustomIcons/icons/misc3/louudobbs.dds"
s["@Olivene"] = "LibCustomIcons/icons/misc3/olivene.dds"
s["@CanineNote"] = "LibCustomIcons/icons/misc3/caninenote.dds"
s["@Celestia-Nova"] = "LibCustomIcons/icons/misc3/celestianova.dds"
s["@BeetleQueen"] = "LibCustomIcons/icons/misc3/beetlequeen.dds"
s["@Pan1n1"] = "LibCustomIcons/icons/misc3/hauteclerem.dds"
s["@Shiaken"] = "LibCustomIcons/icons/misc3/shiaken.dds"
s["@HouLiGaN"] = "LibCustomIcons/icons/misc3/houligan.dds"
s["@Vodka153"] = "LibCustomIcons/icons/misc3/vodka153.dds"
s["@Neytiiri"] = "LibCustomIcons/icons/misc3/neytiiri.dds"
s["@Glebowsky"] = "LibCustomIcons/icons/misc3/glebowsky.dds"
s["@pistoletova"] = "LibCustomIcons/icons/misc3/pistoletova.dds"
s["@VVombat"] = "LibCustomIcons/icons/misc3/vvombat.dds"
s["@Akasha1980"] = "LibCustomIcons/icons/misc3/akasha1980.dds"
s["@SirAlgear"] = "LibCustomIcons/icons/misc3/siralgear2.dds"
s["@Archerbazsi11"] = "LibCustomIcons/icons/misc3/archerbazsi11.dds"
s["@jambalaja188"] = "LibCustomIcons/icons/misc3/jambalaja188.dds"
s["@Zwergknurrer"] = "LibCustomIcons/icons/misc3/zwergknurrer.dds"
s["@No-Limit"] = "LibCustomIcons/icons/misc3/nolimit.dds"
s["@JurassicBeard"] = "LibCustomIcons/icons/misc3/jurassicbeard.dds"
s["@HIGHJACK0101"] = "LibCustomIcons/icons/misc3/highjack0101.dds"
s["@vidgap"] = "LibCustomIcons/icons/misc3/vidgap.dds"
s["@Villa-nelle"] = "LibCustomIcons/icons/misc3/villanelle.dds"
s["@Sipira"] = "LibCustomIcons/icons/misc3/Sipira.dds"
s["@WoolyMammoth"] = "LibCustomIcons/icons/misc3/woolymammoth.dds"
s["@IvaVixen"] = "LibCustomIcons/icons/misc3/ivavixen.dds"
s["@PrinceOfChaos1423"] = "LibCustomIcons/icons/misc3/princeofchaos1423.dds"
s["@Xavier4"] = "LibCustomIcons/icons/misc3/xavier4.dds"
s["@lackingforte"] = "LibCustomIcons/icons/misc3/lackingforte.dds"
s["@caspon"] = "LibCustomIcons/icons/misc3/caspon.dds"
s["@xZynk"] = "LibCustomIcons/icons/misc3/xzynk.dds"
s["@Anya_Jade"] = "LibCustomIcons/icons/misc3/anyajade.dds"
s["@ChefPanda"] = "LibCustomIcons/icons/misc3/chefpanda.dds"
s["@amx903"] = "LibCustomIcons/icons/misc3/amx903.dds"
s["@Tolerian"] = "LibCustomIcons/icons/misc3/tolerian.dds"
s["@Angryolman"] = "LibCustomIcons/icons/misc3/angryolman.dds"
s["@Arthou"] = "LibCustomIcons/icons/misc3/arthou.dds"
s["@totalangel06"] = "LibCustomIcons/icons/misc3/totalangel06.dds"
s["@Thoorak"] = "LibCustomIcons/icons/misc3/thoorak.dds"
s["@LemurDuke"] = "LibCustomIcons/icons/misc3/lemurduke.dds"
s["@Xenomium"] = "LibCustomIcons/icons/misc3/xenomium.dds"
s["@RossLock"] = "LibCustomIcons/icons/misc3/rosslock.dds"
s["@RavingEnterprise"] = "LibCustomIcons/icons/misc3/ravingenterprise.dds"
s["@Pekepok"] = "LibCustomIcons/icons/misc3/pekepok.dds"
s["@Clawnox"] = "LibCustomIcons/icons/misc3/clawnox.dds"
s["@Substance1990"] = "LibCustomIcons/icons/misc3/substance1990.dds"
s["@Rosewaken"] = "LibCustomIcons/icons/misc3/rosewaken.dds"
s["@SunPoeBow"] = "LibCustomIcons/icons/misc3/sunpoebow.dds"
s["@Galowen"] = "LibCustomIcons/icons/misc3/galowen.dds"
s["@Sir_Loki"] = "LibCustomIcons/icons/misc3/sirloki.dds"
s["@Panickaa"] = "LibCustomIcons/icons/misc3/panickaa3.dds"
s["@Xudowudo"] = "LibCustomIcons/icons/misc3/xudowudo.dds"
s["@oksapay"] = "LibCustomIcons/icons/misc3/oksapay.dds"
s["@Whiskey_JG"] = "LibCustomIcons/icons/misc3/whiskeyjg.dds"
s["@xilef2001"] = "LibCustomIcons/icons/misc3/xilef2001.dds"
s["@MegeTheBoomer"] = "LibCustomIcons/icons/misc3/megetheboomer.dds"
s["@skullemainia"] = "LibCustomIcons/icons/misc3/skullemainia.dds"
s["@MrBiTTeL"] = "LibCustomIcons/icons/misc3/mrbittel.dds"
s["@F0RS4K3Nx"] = "LibCustomIcons/icons/misc3/f0rs4k3nx.dds"
s["@Didipv"] = "LibCustomIcons/icons/misc3/didipv.dds"
s["@SirObolus"] = "LibCustomIcons/icons/misc3/sirobolus.dds"
s["@torejonas"] = "LibCustomIcons/icons/misc3/torejonas2.dds"
s["@MyDooM13"] = "LibCustomIcons/icons/misc3/mydoom13.dds"
s["@KukuruzkaKri"] = "LibCustomIcons/icons/misc3/kukuruzkakri2.dds"
s["@Aniogoko"] = "LibCustomIcons/icons/misc3/aniogoko2.dds"
s["@Nam0"] = "LibCustomIcons/icons/misc3/nam0.dds"
s["@yunowi"] = "LibCustomIcons/icons/misc3/kyupi2.dds"
s["@yngdny"] = "LibCustomIcons/icons/misc3/yngdny.dds"
s["@sh4d34m"] = "LibCustomIcons/icons/misc3/sh4d34m.dds"
s["@pelmeh"] = "LibCustomIcons/icons/misc3/pelmeh.dds"
s["@MuesliMan550"] = "LibCustomIcons/icons/misc3/MuesliMan550_2.dds"
s["@zBucksss"] = "LibCustomIcons/icons/misc3/zbucksss.dds"
s["@VeloxHus"] = "LibCustomIcons/icons/misc3/veloxhus.dds"
s["@bylll"] = "LibCustomIcons/icons/misc3/bylll.dds"
s["@barryy"] = "LibCustomIcons/icons/misc3/barryy.dds"
s["@Akamakus"] = "LibCustomIcons/icons/misc3/akamakus.dds"
s["@Eraseme123"] = "LibCustomIcons/icons/misc3/eraseme123.dds"
s["@CrunchyPBnJ"] = "LibCustomIcons/icons/misc3/crunchypbnj.dds"
s["@QueuesAsTanks"] = "LibCustomIcons/icons/misc3/queuesastanks.dds"
s["@DDraker"] = "LibCustomIcons/icons/misc3/ddraker.dds"
s["@TheCarnag3"] = "LibCustomIcons/icons/misc3/thecarnag3.dds"
s["@TheForFeeF"] = "LibCustomIcons/icons/misc3/theforfeef.dds"
s["@Adam.Cap"] = "LibCustomIcons/icons/misc3/adamcap.dds"
s["@Zenatheia"] = "LibCustomIcons/icons/misc3/zenatheia.dds"
s["@NImendis87"] = "LibCustomIcons/icons/misc3/nimendis87.dds"
s["@KatSerious"] = "LibCustomIcons/icons/misc3/katserious.dds"
s["@Sfio"] = "LibCustomIcons/icons/misc3/sfio.dds"
s["@miau24"] = "LibCustomIcons/icons/misc3/miau24.dds"
s["@IForsythEI"] = "LibCustomIcons/icons/misc3/iforsythei.dds"
s["@troll9191"] = "LibCustomIcons/icons/misc3/troll9191.dds"
s["@Centurio_Regor"] = "LibCustomIcons/icons/misc3/centurioregor.dds"
s["@iTzMattYz"] = "LibCustomIcons/icons/misc3/itzmattyz.dds"
s["@AllStars25"] = "LibCustomIcons/icons/misc3/allstars25.dds"
s["@Captain_Danny"] = "LibCustomIcons/icons/misc3/captaindanny.dds"
s["@Thor966"] = "LibCustomIcons/icons/misc3/thor966.dds"
s["@Kirolla_larossa"] = "LibCustomIcons/icons/misc3/kirollalarossa.dds"
s["@TheTrumpet"] = "LibCustomIcons/icons/misc3/thetrumpet.dds"
s["@IggyBlue"] = "LibCustomIcons/icons/misc3/iggyblue.dds"
s["@Teranity"] = "LibCustomIcons/icons/misc3/Teranity_3.dds"
s["@CitizenGame"] = "LibCustomIcons/icons/misc3/citizengame.dds"
s["@SinOfMen"] = "LibCustomIcons/icons/misc3/sinofmen2.dds"
s["@Nessaiga"] = "LibCustomIcons/icons/misc3/neseso2.dds"
s["@Nadalie"] = "LibCustomIcons/icons/misc3/nadalie.dds"
s["@MGU"] = "LibCustomIcons/icons/misc3/mgu.dds"
s["@Oma755"] = "LibCustomIcons/icons/misc3/oma755.dds"
s["@M12Kerbs"] = "LibCustomIcons/icons/misc3/m12kerbs.dds"
s["@Thundmer"] = "LibCustomIcons/icons/misc3/Thundmer.dds"
s["@SuperNova99"] = "LibCustomIcons/icons/misc3/supernova99.dds"
s["@Arg_o"] = "LibCustomIcons/icons/misc3/argo.dds"
s["@Grumblestiltskin"] = "LibCustomIcons/icons/misc3/grumblestiltskin.dds"
s["@DroganLord"] = "LibCustomIcons/icons/misc3/DroganLord.dds"
s["@fefvy"] = "LibCustomIcons/icons/misc3/fefvy.dds"
s["@R1ckSR"] = "LibCustomIcons/icons/misc3/r1cksr.dds"
a["@lazy_jygg"] = {"LibCustomIcons/icons/misc3/lazy_jygg_anim.dds", 25, 2, 13}
s["@alusra"] = "LibCustomIcons/icons/misc3/alusra2.dds"
a["@LordTuhy"] = {"LibCustomIcons/icons/misc3/LordTuhy_anim.dds", 30, 1, 10}
s["@GOAT6668"] = "LibCustomIcons/icons/misc3/goat6668.dds"
s["@Radishh"] = "LibCustomIcons/icons/misc3/radishh.dds"
s["@DarknoSyn"] = "LibCustomIcons/icons/misc3/darknosyn.dds"
s["@javajedi"] = "LibCustomIcons/icons/misc3/javajedi.dds"
s["@xlXStreetXlx"] = "LibCustomIcons/icons/misc3/xlxstreetxlx.dds"
s["@magi.mai"] = "LibCustomIcons/icons/misc3/magi.mai.dds"
s["@Aziing"] = "LibCustomIcons/icons/misc3/aziing3.dds"
s["@L's"] = "LibCustomIcons/icons/misc3/ls.dds"
s["@Quiest"] = "LibCustomIcons/icons/misc3/quiest.dds"
s["@ScowlingMantis9"] = "LibCustomIcons/icons/misc3/scowlingmantis9.dds"
s["@Yang1K"] = "LibCustomIcons/icons/misc3/y4ng.dds"
s["@OPrince1"] = "LibCustomIcons/icons/misc3/oprince1.dds"
s["@Praeditos"] = "LibCustomIcons/icons/misc3/praeditos.dds"
s["@jedimauve"] = "LibCustomIcons/icons/misc3/jedimauve.dds"
s["@Eddie's_ShinyMareep"] = "LibCustomIcons/icons/misc3/eddiesshinymareep.dds"
s["@PossumPrince"] = "LibCustomIcons/icons/misc3/possumprince.dds"
s["@theBeardd"] = "LibCustomIcons/icons/misc3/thebeardd.dds"
s["@Eymix"] = "LibCustomIcons/icons/misc3/eymix.dds"
s["@Revaxon"] = "LibCustomIcons/icons/misc3/revaxon.dds"
s["@stdard"] = "LibCustomIcons/icons/misc3/stdard.dds"
s["@Nexfo"] = "LibCustomIcons/icons/misc3/nexfo.dds"
s["@Coraline.off"] = "LibCustomIcons/icons/misc3/coralineoff.dds"
s["@BlackinkRebel"] = "LibCustomIcons/icons/misc3/blackinkrebel.dds"
s["@Leandra.c"] = "LibCustomIcons/icons/misc3/leandrac.dds"
s["@SpaceDandyBaby"] = "LibCustomIcons/icons/misc3/spacedandybaby.dds"
s["@Rampsay"] = "LibCustomIcons/icons/misc3/rampsay.dds"
s["@FriendOfJesus"] = "LibCustomIcons/icons/misc3/friendofjesus.dds"
s["@Gripen39"] = "LibCustomIcons/icons/misc3/gripen39.dds"
s["@Kha-Beleh"] = "LibCustomIcons/icons/misc3/khabeleh.dds"
s["@mf_doot"] = "LibCustomIcons/icons/misc3/r2dieter.dds"
s["@DmitryMikh"] = "LibCustomIcons/icons/misc3/dmitrymikh.dds"
s["@Cpjony2"] = "LibCustomIcons/icons/misc3/cpjony2.dds"
s["@MichaelPalin"] = "LibCustomIcons/icons/misc3/michaelpalin.dds"
s["@Nebel-Lei"] = "LibCustomIcons/icons/misc3/nebellei.dds"
s["@Its-BiBii"] = "LibCustomIcons/icons/misc3/Its-BiBii_2.dds"
s["@The'Decapitator"] = "LibCustomIcons/icons/misc3/thedecapitator.dds"
s["@Sailor_Earth"] = "LibCustomIcons/icons/misc3/sailorearth.dds"
s["@dekar5432"] = "LibCustomIcons/icons/misc3/dekar5432.dds"
s["@domsodaso"] = "LibCustomIcons/icons/misc3/domsodaso.dds"
s["@Chufu"] = "LibCustomIcons/icons/misc3/chufu.dds"
s["@MegamiYua"] = "LibCustomIcons/icons/misc3/MegamiYua_2.dds"
s["@Inluv63"] = "LibCustomIcons/icons/misc3/inluv63.dds"
s["@BlondaTjej"] = "LibCustomIcons/icons/misc3/dasmaedchen.dds"
s["@mysteryof-obscurity"] = "LibCustomIcons/icons/misc3/mysteryofobscurity.dds"
s["@vonabol88"] = "LibCustomIcons/icons/misc3/vonabol88.dds"
s["@NimmDirEinenKeks"] = "LibCustomIcons/icons/misc3/nimmdireinenkeks.dds"
s["@Aqv1"] = "LibCustomIcons/icons/misc3/aqv1.dds"
s["@Stealtti"] = "LibCustomIcons/icons/misc3/stealtti.dds"
s["@SkylerBlue"] = "LibCustomIcons/icons/misc3/skylerblue.dds"
s["@kapparin.o"] = "LibCustomIcons/icons/misc3/kapparinosmile.dds"
s["@IrishOphidia"] = "LibCustomIcons/icons/misc3/irishophidia.dds"
s["@Chthonink"] = "LibCustomIcons/icons/misc3/chthonink.dds"
s["@Stremme"] = "LibCustomIcons/icons/misc3/stremme.dds"
s["@LemonHaistaja"] = "LibCustomIcons/icons/misc3/lemonhaistaja.dds"
s["@Doth_Z"] = "LibCustomIcons/icons/misc3/dothz.dds"
s["@The_AshenLord"] = "LibCustomIcons/icons/misc3/theashenlord2.dds"
s["@SquinceyBones"] = "LibCustomIcons/icons/misc3/squinceybones.dds"
s["@thegoddessanna"] = "LibCustomIcons/icons/misc3/thegoddessanna.dds"
s["@ImASneekySnake"] = "LibCustomIcons/icons/misc3/imasneekysnake.dds"
s["@thestral09"] = "LibCustomIcons/icons/misc3/thestral09.dds"
s["@EeveeMom713"] = "LibCustomIcons/icons/misc3/eeveemom713.dds"
s["@MightyWoYoung"] = "LibCustomIcons/icons/misc3/mightywoyoung.dds"
s["@Nerevar.Rain"] = "LibCustomIcons/icons/misc3/NerevarRain.dds"
s["@noba00"] = "LibCustomIcons/icons/misc3/novachrono.dds"
s["@ImBlackwing"] = "LibCustomIcons/icons/misc3/imblackwing.dds"
s["@Frostyy.JS"] = "LibCustomIcons/icons/misc3/Frostyy.JS.dds"
s["@AdonisVernalis"] = "LibCustomIcons/icons/misc3/adonisvernalis.dds"
s["@Gaian-Spirit"] = "LibCustomIcons/icons/misc3/gaianspirit.dds"
s["@A.D42"] = "LibCustomIcons/icons/misc3/AD42_2.dds"
s["@Vissent"] = "esoui/art/icons/store_werewolfbite_01.dds"
s["@Ma'pyca"] = "LibCustomIcons/icons/misc3/mapyca.dds"
s["@Aka.allen"] = "LibCustomIcons/icons/misc3/akaallen2.dds"
s["@cngz"] = "LibCustomIcons/icons/misc3/cngz.dds"
s["@ßrighT_MasteR"] = "LibCustomIcons/icons/misc3/brightmaster.dds"
s["@CookieCrafter"] = "LibCustomIcons/icons/misc3/cookiecrafter.dds"
s["@SleepyLight"] = "LibCustomIcons/icons/misc3/sleepylight.dds"
s["@Wiriel"] = "LibCustomIcons/icons/misc3/wiriel.dds"
s["@Gevives"] = "LibCustomIcons/icons/misc3/gevives.dds"
s["@Loupika"] = "LibCustomIcons/icons/misc3/Loupika_2.dds"
s["@Oxmantes"] = "LibCustomIcons/icons/misc3/oxmantes.dds"
s["@Anika-Faystas"] = "LibCustomIcons/icons/misc3/anikafaystas.dds"
s["@K1ngar"] = "LibCustomIcons/icons/misc3/k1ngar.dds"
s["@DianeLu"] = "LibCustomIcons/icons/misc3/DianeLu_2.dds"
s["@Cheshirre"] = "LibCustomIcons/icons/misc3/cheshirre2.dds"
s["@Vi_Zet"] = "LibCustomIcons/icons/misc3/vizet.dds"
s["@Yakreb"] = "LibCustomIcons/icons/misc3/countstarbucks.dds"
s["@CountStarbucks"] = "LibCustomIcons/icons/misc3/countstarbucks.dds"
s["@recondrone"] = "LibCustomIcons/icons/misc3/countstarbucks.dds"
s["@Svafnir6"] = "LibCustomIcons/icons/misc3/countstarbucks.dds"
s["@mericolurgibi"] = "LibCustomIcons/icons/misc3/countstarbucks.dds"
s["@Zeira"] = "LibCustomIcons/icons/misc3/countstarbucks.dds"
s["@vademcum"] = "LibCustomIcons/icons/misc3/countstarbucks.dds"
s["@Tyrion_Baenre"] = "LibCustomIcons/icons/misc3/tyrionbaenre.dds"
s["@mgmanzs"] = "LibCustomIcons/icons/misc3/mgmanzs.dds"
s["@Shaad812"] = "LibCustomIcons/icons/misc3/shaad812.dds"
s["@Jonesy31944"] = "LibCustomIcons/icons/misc3/jonesy31944.dds"
s["@StuffiePlush"] = "LibCustomIcons/icons/misc3/stuffieplush.dds"
s["@jetplane_18"] = "LibCustomIcons/icons/misc3/jetplane18.dds"
s["@riotgunz"] = "LibCustomIcons/icons/misc3/riotgunz_2.dds"
s["@CervecitaFresca"] = "LibCustomIcons/icons/misc3/cervecitafresca2.dds"
s["@DissectumD"] = "LibCustomIcons/icons/misc3/dissectumd.dds"
s["@Alysce"] = "LibCustomIcons/icons/misc3/alysce.dds"
s["@Arctimius"] = "LibCustomIcons/icons/misc3/arctimius.dds"
s["@sasserclubb"] = "LibCustomIcons/icons/misc3/sasserclubb.dds"
s["@nahc-atikO"] = "LibCustomIcons/icons/misc3/nahcatiko.dds"
s["@deadwinston"] = "LibCustomIcons/icons/misc3/deadwinston2.dds"
s["@HoCo_xXSamXx"] = "LibCustomIcons/icons/misc3/hocoxxsamxx.dds"
s["@meek2003"] = "LibCustomIcons/icons/misc3/meek2003.dds"
s["@EvilAroma007"] = "LibCustomIcons/icons/misc3/evilaroma007.dds"
s["@xskyrage"] = "LibCustomIcons/icons/misc3/xskyrage.dds"
a["@xDelk"] = {"LibCustomIcons/icons/misc3/xDelk_anim.dds", 16, 1, 17}
a["@SleepyHead-Zzz"] = {"LibCustomIcons/icons/misc3/SleepyHead-Zzz_anim.dds", 6, 1, 10}
a["@Elstoo"] = {"LibCustomIcons/icons/misc3/Elstoo_anim.dds", 7, 3, 17}
a["@MoochHD"] = {"LibCustomIcons/icons/misc3/MoochHD_anim_6.dds", 9, 1, 10}
a["@Ssyzygy"] = {"LibCustomIcons/icons/misc3/Ssyzygy_anim.dds", 11, 1, 10}
a["@Anifortune"] = {"LibCustomIcons/icons/misc3/Anifortune_anim.dds", 17, 2, 24}
a["@B6.Kibbs"] = {"LibCustomIcons/icons/misc3/B6.Kibbs_anim.dds", 16, 1, 11}
a["@CptKildor"] = {"LibCustomIcons/icons/misc3/CptKildor_anim_2.dds", 10, 5, 20}
a["@RaveN_92"] = {"LibCustomIcons/icons/misc3/RaveN_92_anim_2.dds", 6, 4, 8}
a["@vexietexie"] = {"LibCustomIcons/icons/misc3/vexietexie_anim_2.dds", 11, 4, 12.5}
a["@Glazing"] = {"LibCustomIcons/icons/misc3/Glazing_anim.dds", 10, 1, 10}
a["@Kiyari"] = {"LibCustomIcons/icons/misc3/Pull_anim.dds", 14, 1, 13}
a["@McLadrones"] = {"LibCustomIcons/icons/misc3/matheuzynhow_anim.dds", 37, 1, 15}
a["@drunkieowl"] = {"LibCustomIcons/icons/misc3/drunkieowl_anim.dds", 12, 1, 6}
a["@VAI'REN"] = {"LibCustomIcons/icons/misc3/vairen_anim.dds", 10, 5, 20}
a["@LetsGerwin"] = {"LibCustomIcons/icons/misc3/LetsGerwin_anim.dds", 8, 3, 11}
a["@GregorZamza"] = {"LibCustomIcons/icons/misc3/GregorZamza_anim_3.dds", 12, 1, 17}
a["@r.avs"] = {"LibCustomIcons/icons/misc3/r.avs_anim_2.dds", 23, 1, 11}
a["@Iclap"] = {"LibCustomIcons/icons/misc3/Iclap_anim_3.dds", 10, 5, 25}
a["@Lucas318"] = {"LibCustomIcons/icons/misc3/Lucas318_anim.dds", 14, 1, 10}
a["@Itachi_Flow"] = {"LibCustomIcons/icons/misc3/Itachi_Flow_anim.dds", 11, 2, 10}
a["@Sipira"] = {"LibCustomIcons/icons/misc3/Sipira_anim.dds", 5, 2, 5}
a["@Reclaimer"] = {"LibCustomIcons/icons/misc3/Reclaimer_anim.dds", 7, 7, 12}
a["@Entropy66"] = {"LibCustomIcons/icons/misc3/entropygaming_anim.dds", 31, 1, 20}
a["@Mananabo"] = {"LibCustomIcons/icons/misc3/mananabo_anim.dds", 27, 1, 15}
a["@LeoShogun"] = {"LibCustomIcons/icons/misc3/LeoShogun_anim_3.dds", 9, 2, 8}
a["@Zerakthion"] = {"LibCustomIcons/icons/misc3/Zerakthion_anim_4.dds", 16, 2, 20}
a["@MaxFlaks"] = {"LibCustomIcons/icons/misc3/MaxFlaks_anim.dds", 5, 4, 20}
a["@SuddenArrival"] = {"LibCustomIcons/icons/misc3/SuddenArrival_anim_2.dds", 8, 1, 10}
a["@FIX.ME"] = {"LibCustomIcons/icons/misc3/ausker_anim.dds", 11, 1, 7}
a["@Alessia_Bridge"] = {"LibCustomIcons/icons/misc3/Alessia_Bridge_anim_3.dds", 5, 2, 10}
a["@ChickieNuggies"] = {"LibCustomIcons/icons/misc3/ChickieNuggies_anim.dds", 12, 1, 24}
a["@MAJESTlC"] = {"LibCustomIcons/icons/misc3/majestlc_anim.dds", 9, 5, 17}
a["@xDevilz"] = {"LibCustomIcons/icons/misc3/xdevilz_anim.dds", 50, 1, 15}
a["@genericvillager.exe"] = {"LibCustomIcons/icons/misc3/genericvillagerexe_anim2.dds", 10, 1, 2}
a["@Oxmantes"] = {"LibCustomIcons/icons/misc3/oxmantes_anim2.dds", 10, 5, 10}
a["@gooseegoose"] = {"LibCustomIcons/icons/misc3/gooseegoose_anim.dds", 16, 1, 25}
a["@BowBowBaggins"] = {"LibCustomIcons/icons/misc3/bowbowbaggins_anim.dds", 16, 1, 10}
a["@EvilxQC"] = {"LibCustomIcons/icons/misc3/evilxqc_anim.dds", 30, 1, 20}
a["@jedimauve"] = {"LibCustomIcons/icons/misc3/jedimauve_anim.dds", 7, 1, 11}
a["@L's"] = {"LibCustomIcons/icons/misc3/ls_anim.dds", 14, 1, 10}
a["@Snoozy17"] = {"LibCustomIcons/icons/misc3/snoozy17_anim.dds", 6, 1, 22}
a["@HealShower"] = {"LibCustomIcons/icons/misc3/healshower_anim.dds", 14, 1, 8}
a["@Hayden0X"] = {"LibCustomIcons/icons/misc3/hayden0x_anim2.dds", 30, 1, 16}
a["@Kharjo94"] = {"LibCustomIcons/icons/misc3/kharjo94_anim.dds", 41, 1, 20}
a["@ILxd"] = {"LibCustomIcons/icons/misc3/ilxdz_anim.dds", 38, 1, 33}
a["@Valkyrie-x"] = {"LibCustomIcons/icons/misc3/valkyriex_anim.dds", 15, 1, 11}
a["@jambalaja188"] = {"LibCustomIcons/icons/misc3/jambalaja188_anim3.dds", 25, 1, 10}
a["@DuduVult"] = {"LibCustomIcons/icons/misc3/DuduVult_anim2.dds", 16, 1, 25}
a["@meek2003"] = {"LibCustomIcons/icons/misc3/meek2003_anim.dds", 23, 1, 5}
a["@NATHXN16"] = {"LibCustomIcons/icons/misc3/nathxn16_anim.dds", 8, 5, 17}
a["@Cielsis"] = {"LibCustomIcons/icons/misc3/cielsis_anim.dds", 32, 1, 10}
a["@Doth_Z"] = {"LibCustomIcons/icons/misc3/dothz_anim.dds", 29, 1, 20}
a["@Pearslol"] = {"LibCustomIcons/icons/misc3/pearslol_anim.dds", 38, 1, 10}
a["@xConvict13"] = {"LibCustomIcons/icons/misc3/xconvict13_anim2.dds", 39, 1, 20}
a["@VeloxHus"] = {"LibCustomIcons/icons/misc3/norolex_anim.dds", 9, 5, 20}
a["@Magnus.GTR"] = {"LibCustomIcons/icons/misc3/magnusgtr_anim.dds", 40, 1, 10}
a["@Kotlyn"] = {"LibCustomIcons/icons/misc3/kjalnar_anim.dds", 11, 1, 22}
a["@Dan_BawsMan"] = {"LibCustomIcons/icons/misc3/danbawsman_anim.dds", 13, 1, 11}
a["@Durneviiir"] = {"LibCustomIcons/icons/misc3/durneviiir_anim.dds", 10, 5, 31}
a["@Emmaga"] = {"LibCustomIcons/icons/misc3/emmaga_anim.dds", 9, 5, 18}
a["@BloodyTirol"] = {"LibCustomIcons/icons/misc3/bloodytirol_anim2.dds", 25, 1, 14}
a["@Arcus_Dragon"] = {"LibCustomIcons/icons/misc3/arcusdragon_anim.dds", 46, 1, 50}
a["@Joint_online"] = {"LibCustomIcons/icons/misc3/jointonline_anim.dds", 30, 1, 20}
a["@super_donkey"] = {"LibCustomIcons/icons/misc3/bobdelivery_anim.dds", 16, 1, 10}
a["@mach1na"] = {"LibCustomIcons/icons/misc3/cogchamp_anim.dds", 21, 1, 8}
a["@Deathbed307"] = {"LibCustomIcons/icons/misc3/deathbed307_anim.dds", 13, 1, 14}
a["@Aldrahir"] = {"LibCustomIcons/icons/misc3/aldrahir_anim.dds", 28, 1, 8}
a["@DragonBlades11"] = {"LibCustomIcons/icons/misc3/dragonblades11_anim.dds", 37, 1, 15}
a["@huarb"] = {"LibCustomIcons/icons/misc3/huarb_anim.dds", 9, 1, 22}
a["@Saya35"] = {"LibCustomIcons/icons/misc3/saya35_anim.dds", 8, 5, 10}
a["@Madara1331331"] = {"LibCustomIcons/icons/misc3/madara1331331_anim2.dds", 35, 1, 10}
a["@B'ee"] = {"LibCustomIcons/icons/misc3/millenium21_anim.dds", 38, 1, 13}
a["@BAZALEON"] = {"LibCustomIcons/icons/misc3/bazaleon_anim.dds", 12, 1, 15}
a["@Na-os"] = {"LibCustomIcons/icons/misc3/naos_anim.dds", 34, 1, 20}
a["@Head5trong"] = {"LibCustomIcons/icons/misc3/head5trong_anim.dds", 11, 1, 20}
a["@greeed2025"] = {"LibCustomIcons/icons/misc3/greeed2025_anim.dds", 7, 1, 13}
a["@Mudcrab-Overlord"] = {"LibCustomIcons/icons/misc3/aronimus6886_anim.dds", 28, 1, 25}
a["@Shiro0"] = {"LibCustomIcons/icons/misc3/shiro0_anim.dds", 24, 1, 30}
a["@bobdelivery"] = {"LibCustomIcons/icons/misc3/bobdelivery_anim.dds", 16, 1, 10}
a["@WhiskeyRiot"] = {"LibCustomIcons/icons/misc3/bobdelivery_anim.dds", 16, 1, 10}
a["@angelica_pickles"] = {"LibCustomIcons/icons/misc3/angelicapickles_anim3.dds", 15, 1, 8}
a["@thestral09"] = {"LibCustomIcons/icons/misc3/thestral09_anim.dds", 15, 1, 14}
a["@Irritated"] = {"LibCustomIcons/icons/misc3/irritated_anim.dds", 47, 1, 20}
a["@shinykey"] = {"LibCustomIcons/icons/misc3/shinykey_anim2.dds", 20, 1, 20}
a["@LucentLady"] = {"LibCustomIcons/icons/misc3/lucentlady_anim3.dds", 5, 1, 25}
a["@korjeek"] = {"LibCustomIcons/icons/misc3/korjeek_anim.dds", 28, 1, 16}
a["@ilPone"] = {"LibCustomIcons/icons/misc3/ilpone_anim.dds", 11, 1, 9}
a["@ding0x"] = {"LibCustomIcons/icons/misc3/ding0x_anim.dds", 32, 1, 20}
a["@TBo9lKoTeuka"] = {"LibCustomIcons/icons/misc3/pavel0104_anim.dds", 11, 1, 11}
a["@FrejaClueless"] = {"LibCustomIcons/icons/misc3/yoham_anim4.dds", 42, 1, 20}
a["@Jessacakes"] = {"LibCustomIcons/icons/misc3/jessacakes_anim.dds", 3, 1, 15}
a["@WilliamDawson"] = {"LibCustomIcons/icons/misc3/williamdawson_anim.dds", 10, 5, 14}
a["@Entaro"] = {"LibCustomIcons/icons/misc3/entaro_anim.dds", 48, 1, 13}
a["@Mbokeh"] = {"LibCustomIcons/icons/misc3/mbokeh_anim.dds", 9, 5, 10}
a["@Mila-Midnight"] = {"LibCustomIcons/icons/misc3/milamidnight_anim.dds", 47, 1, 25}
a["@MagickaSorcerer"] = {"LibCustomIcons/icons/misc3/magickasorcerer.dds", 58, 1, 18}
a["@c117"] = {"LibCustomIcons/icons/misc3/fuIcrum_anim.dds", 29, 1, 10}
a["@L0SE"] = {"LibCustomIcons/icons/misc3/l0se_anim.dds", 18, 1, 11}
a["@Low_IQ"] = {"LibCustomIcons/icons/misc3/lowiq_anim2.dds", 30, 1, 28}
a["@Vanish"] = {"LibCustomIcons/icons/misc3/vanish_anim.dds", 14, 1, 10}
a["@ap0calypzeee"] = {"LibCustomIcons/icons/misc3/ap0calypzeee_anim.dds", 44, 1, 17}
a["@dileon"] = {"LibCustomIcons/icons/misc3/dileon_anim.dds", 7, 1, 2}
a["@TERMINATOR69"] = {"LibCustomIcons/icons/misc3/terminator69_anim.dds", 29, 1, 10}
a["@S.keet"] = {"LibCustomIcons/icons/misc3/digitalskeet_anim.dds", 7, 1, 30}
a["@HunterXZX"] = {"LibCustomIcons/icons/misc3/hunterxzx_anim.dds", 40, 1, 33}
a["@IIRuka"] = {"LibCustomIcons/icons/misc3/iiruka_anim.dds", 44, 1, 10}
a["@NRT_Scarface"] = {"LibCustomIcons/icons/misc3/nrtscarface_anim2.dds", 41, 1, 15}
a["@Terrious"] = {"LibCustomIcons/icons/misc3/terrious_anim.dds", 24, 1, 25}
a["@oksapay"] = {"LibCustomIcons/icons/misc3/oksapay_anim.dds", 5, 5, 10}
a["@NumaZero"] = {"LibCustomIcons/icons/misc3/numazero_anim.dds", 47, 1, 14}
a["@Lug95"] = {"LibCustomIcons/icons/misc3/lug95_anim.dds", 37, 1, 25}
a["@Sweetiieh"] = {"LibCustomIcons/icons/misc3/sweetiieh_anim.dds", 5, 1, 11}
a["@Yoshi.D"] = {"LibCustomIcons/icons/misc3/yoshid_anim.dds", 15, 1, 20}
a["@w's"] = {"LibCustomIcons/icons/hodor/warfire_anim2.dds", 22, 1, 50}
a["@Koeb1"] = {"LibCustomIcons/icons/misc3/koeb1_anim.dds", 23, 2, 25}
a["@StackedSpades"] = {"LibCustomIcons/icons/misc3/stackedspades_anim.dds", 5, 5, 12}
a["@lysavah"] = {"LibCustomIcons/icons/misc3/lysavah_anim.dds", 21, 1, 12}
a["@Caradeii"] = {"LibCustomIcons/icons/misc3/caradeii_anim.dds", 16, 1, 25}
a["@Jonsieyz"] = {"LibCustomIcons/icons/misc3/jonsieyz_anim2.dds", 42, 1, 10}
a["@Coscos007"] = {"LibCustomIcons/icons/misc3/coscos007_anim.dds", 10, 5, 8}
a["@potato101"] = {"LibCustomIcons/icons/misc3/potato101_anim.dds", 7, 1, 50}
a["@StopAsianHate"] = {"LibCustomIcons/icons/misc3/stopasianhate_anim.dds", 6, 1, 17}
a["@Vegimite.Dropbear"] = {"LibCustomIcons/icons/misc2/vegimitedropbear_anim.dds", 3, 1, 11}
a["@Zero.NullValue"] = {"LibCustomIcons/icons/misc3/zeronullvalue_anim5.dds", 24, 1, 25}
a["@Svv33tRoll"] = {"LibCustomIcons/icons/misc3/svv33troll_anim.dds", 12, 1, 10}
a["@Calandrel"] = {"LibCustomIcons/icons/misc3/calandrel_anim.dds", 33, 1, 50}
a["@ZezinJunior"] = {"LibCustomIcons/icons/misc3/zezinjunior_anim.dds", 8, 1, 2}
a["@Sp.cy"] = {"LibCustomIcons/icons/misc3/spcy_anim.dds", 6, 1, 11}
a["@Em.pire"] = {"LibCustomIcons/icons/misc3/empire_anim.dds", 13, 1, 7}
a["@Das_Weeb"] = {"LibCustomIcons/icons/misc3/dasweeb_anim.dds", 3, 1, 14}
a["@GoKuub"] = {"LibCustomIcons/icons/misc3/gokuub_anim2.dds", 11, 1, 25}
a["@dack_janiels"] = {"LibCustomIcons/icons/misc3/dackjaniels_anim.dds", 13, 1, 21}
a["@xOneOfAKindx"] = {"LibCustomIcons/icons/misc3/xoneofakindx_anim.dds", 6, 5, 50}
a["@Nuclearpath"] = {"LibCustomIcons/icons/misc3/nuclearpath_anim.dds", 49, 1, 13}
a["@szycaogeyi"] = {"LibCustomIcons/icons/misc3/szycaogeyi_anim.dds", 8, 6, 14}
a["@D_Ho"] = {"LibCustomIcons/icons/misc3/dho_anim.dds", 10, 1, 11}
a["@ValyrianEmpress"] = {"LibCustomIcons/icons/misc3/valyrianempress_anim.dds", 11, 1, 10}
a["@QuantumLoopX"] = {"LibCustomIcons/icons/misc3/quantumloopx_anim.dds", 15, 1, 33}
a["@Dark'Shade"] = {"LibCustomIcons/icons/misc3/darkshade_anim.dds", 8, 1, 11}
a["@xGARCIAx"] = {"LibCustomIcons/icons/misc3/xgarciax_anim.dds", 18, 1, 10}
a["@Pooya22"] = {"LibCustomIcons/icons/misc3/pooya22es_anim.dds", 11, 1, 25}
a["@Lurumi"] = {"LibCustomIcons/icons/misc3/lec0r_anim2.dds", 44, 1, 10}
a["@Teasinglewis999"] = {"LibCustomIcons/icons/misc3/teasinglewis999_anim.dds", 41, 1, 10}
a["@Bloyd1004"] = {"LibCustomIcons/icons/misc/whoitsma_anim.dds", 10, 6, 16}
a["@toneswho"] = {"LibCustomIcons/icons/misc3/toneswho_anim.dds", 41, 1, 25}
a["@aetherial_dragoness"] = {"LibCustomIcons/icons/misc3/aetherialdragoness_anim.dds", 21, 1, 13}
a["@Neith-hotep"] = {"LibCustomIcons/icons/misc3/neithhotep_anim.dds", 14, 1, 21}
a["@enmant88"] = {"LibCustomIcons/icons/misc3/enmant88_anim.dds", 14, 1, 14}
a["@Kylo_1"] = {"LibCustomIcons/icons/misc3/kylo1_anim.dds", 11, 1, 11}
a["@Osseley"] = {"LibCustomIcons/icons/misc3/osseley_anim2.dds", 19, 1, 13}
a["@JERICO-06"] = {"LibCustomIcons/icons/misc3/jerico06_anim2.dds", 48, 1, 10}
a["@impassiveblue"] = {"LibCustomIcons/icons/misc3/impassiveblue_anim4.dds", 8, 5, 20}
a["@Etmoon"] = {"LibCustomIcons/icons/hodor/warfire_anim2.dds", 22, 1, 50}
a["@Frost'y"] = {"LibCustomIcons/icons/misc3/frosty_anim.dds", 53, 1, 13}
a["@DarkGhost17"] = {"LibCustomIcons/icons/misc3/darkghost17_anim.dds", 33, 1, 7}
a["@Actorion"] = {"LibCustomIcons/icons/misc3/actorion_anim.dds", 24, 1, 25}
a["@REV666"] = {"LibCustomIcons/icons/misc3/rev666_anim.dds", 7, 1, 9}
a["@SmexeRR"] = {"LibCustomIcons/icons/misc3/smexerr_anim.dds", 10, 5, 25}
a["@bl7ckmamba24"] = {"LibCustomIcons/icons/misc3/bl7ckmamba24_anim.dds", 6, 1, 17}
a["@Problem_Solver"] = {"LibCustomIcons/icons/misc3/problemsolver_anim.dds", 20, 1, 7}
a["@TheArkhamCoco"] = {"LibCustomIcons/icons/misc3/thearkhamcoco_anim.dds", 6, 4, 8}
a["@GoingUpInFlamez"] = {"LibCustomIcons/icons/misc3/goingupinflamez_anim2.dds", 24, 1, 8}
a["@AnimusVx"] = {"LibCustomIcons/icons/misc3/animusvx_anim.dds", 11, 1, 25}
a["@LyChen99"] = {"LibCustomIcons/icons/misc3/lychen99_anim.dds", 12, 1, 10}
a["@BibiBlox"] = {"LibCustomIcons/icons/misc3/bibiblox_anim.dds", 7, 1, 10}
a["@Wörtschel"] = {"LibCustomIcons/icons/misc3/wortschel_anim.dds", 15, 1, 25}
a["@Lastdragonborn92"] = {"LibCustomIcons/icons/misc3/lastdragonborn92_anim.dds", 15, 1, 10}
a["@WizMelts"] = {"LibCustomIcons/icons/misc3/wizmelts_anim.dds", 5, 1, 5}
a["@H1ghSpeedK1ller"] = {"LibCustomIcons/icons/misc3/h1ghspeedk1ller_anim.dds", 11, 1, 33}
a["@Tuggles2015"] = {"LibCustomIcons/icons/misc3/bobdelivery_anim.dds", 16, 1, 10}
a["@AlekWithK"] = {"LibCustomIcons/icons/misc3/alekwithk_anim.dds", 10, 1, 20}
a["@SuperSquirtles"] = {"LibCustomIcons/icons/misc3/supersquirtles_anim2.dds", 6, 5, 10}
a["@bilabong007"] = {"LibCustomIcons/icons/misc3/bilabong007_anim2.dds", 9, 5, 20}
a["@Atenius007"] = {"LibCustomIcons/icons/misc3/atenius007_anim.dds", 9, 1, 10}
a["@serize"] = {"LibCustomIcons/icons/misc3/serize_anim.dds", 14, 1, 10}
a["@Targarus"] = {"LibCustomIcons/icons/misc3/targarus_anim.dds", 10, 5, 20}
a["@vNexez"] = {"LibCustomIcons/icons/misc3/vnexez_anim.dds", 7, 1, 10}
a["@ChopWarp"] = {"LibCustomIcons/icons/misc3/chopwarp_anim.dds", 15, 1, 2}
a["@Bignames"] = {"LibCustomIcons/icons/misc3/bignames_anim.dds", 4, 1, 3}
a["@Harmaja"] = {"LibCustomIcons/icons/misc3/harmaja_anim.dds", 3, 1, 2}
a["@InsaiCO"] = {"LibCustomIcons/icons/misc3/insaico_anim2.dds", 21, 1, 10}
a["@Anidas"] = {"LibCustomIcons/icons/misc3/anidas_anim2.dds", 25, 1, 10}
a["@janborj"] = {"LibCustomIcons/icons/misc3/janborj_anim.dds", 6, 5, 9}
a["@Goatcapped"] = {"LibCustomIcons/icons/misc3/dektajo_anim.dds", 28, 1, 9}
a["@piewithapple"] = {"LibCustomIcons/icons/misc3/piewithapple_anim.dds", 21, 1, 5}
a["@octopus_d"] = {"LibCustomIcons/icons/misc3/octopusd_anim.dds", 6, 6, 5}
a["@JL1980"] = {"LibCustomIcons/icons/misc3/jl1980_anim.dds", 16, 1, 25}
a["@Yumisa"] = {"LibCustomIcons/icons/misc3/yumisa_anim.dds", 3, 1, 2}
a["@Sophia-sophie"] = {"LibCustomIcons/icons/misc3/sophiasophie_anim.dds", 26, 1, 25}
a["@Swiftyscoob1104"] = {"LibCustomIcons/icons/misc3/swiftyscoob1104_anim.dds", 18, 1, 5}
a["@sa7nt"] = {"LibCustomIcons/icons/misc3/sa7nt_anim.dds", 11, 1, 20}
a["@Seven155"] = {"LibCustomIcons/icons/misc3/seven155_anim.dds", 10, 5, 10}
a["@BLAZIINGG"] = {"LibCustomIcons/icons/misc3/blaziingg_anim.dds", 10, 1, 20}
a["@Adrian_K"] = {"LibCustomIcons/icons/misc3/adriank_anim.dds", 27, 1, 10}
a["@ChanxThexMan"] = {"LibCustomIcons/icons/misc3/chanxthexman_anim.dds", 7, 1, 11}
a["@TrainerJordin"] = {"LibCustomIcons/icons/misc3/trainerjordin_anim.dds", 11, 1, 15}
a["@AwKeyPooh"] = {"LibCustomIcons/icons/misc3/awkeypooh_anim.dds", 12, 1, 25}
a["@SenpaiTheJedi"] = {"LibCustomIcons/icons/misc3/senpaithejedi_anim.dds", 12, 1, 11}
a["@Nova_Dose"] = {"LibCustomIcons/icons/misc3/novadose_anim.dds", 9, 1, 20}
a["@Brenticus12"] = {"LibCustomIcons/icons/misc3/brenticus12_anim2.dds", 8, 6, 15}
a["@Ramriel"] = {"LibCustomIcons/icons/misc3/ramriel_anim.dds", 23, 2, 15}
a["@RussESO1"] = {"LibCustomIcons/icons/misc3/russvaj_anim2.dds", 9, 5, 15}
a["@GhostAlienStar"] = {"LibCustomIcons/icons/misc3/ghostalienstar_anim.dds", 13, 1, 2}
a["@HomesickV"] = {"LibCustomIcons/icons/misc3/homesickv_anim.dds", 12, 1, 6}
a["@CocoTheCuti3"] = {"LibCustomIcons/icons/misc3/cocothecuti3_anim.dds", 16, 1, 13}
a["@DoggedJose_Luis"] = {"LibCustomIcons/icons/misc3/doggedjoseluis_anim2.dds", 8, 7, 10}
a["@Flaater"] = {"LibCustomIcons/icons/misc3/flaater_anim.dds", 7, 5, 10}
a["@Blaeste"] = {"LibCustomIcons/icons/misc3/blaeste_anim.dds", 8, 5, 20}
a["@Talline"] = {"LibCustomIcons/icons/misc3/talline_anim.dds", 23, 2, 25}
a["@Neraa"] = {"LibCustomIcons/icons/misc3/neraa_anim.dds", 14, 1, 7}
a["@ArchKitten"] = {"LibCustomIcons/icons/misc3/archkitten_anim.dds", 5, 1, 10}
a["@Doc_Landerf"] = {"LibCustomIcons/icons/misc3/doclanderf_anim.dds", 37, 1, 10}
a["@Simplex17"] = {"LibCustomIcons/icons/misc3/simplex17_anim2.dds", 8, 6, 20}
a["@Jagerbabe36"] = {"LibCustomIcons/icons/misc3/jagerbabe36_anim.dds", 5, 4, 10}
a["@Porchen"] = {"LibCustomIcons/icons/misc3/porchen_anim2.dds", 35, 1, 10}
a["@unemploy3d"] = {"LibCustomIcons/icons/misc3/unemploy3d_anim.dds", 7, 5, 16}
a["@Dektajo"] = {"LibCustomIcons/icons/misc3/dektajo_anim.dds", 28, 1, 9}
a["@Lulu_Traquenard"] = {"LibCustomIcons/icons/misc3/lulutraquenard_anim.dds", 18, 1, 8}
a["@Longffellow"] = {"LibCustomIcons/icons/misc3/longffellow_anim.dds", 22, 1, 14}
a["@Akaneee"] = {"LibCustomIcons/icons/misc3/hitsuno_anim2.dds", 10, 5, 20}
a["@bigfire00"] = {"LibCustomIcons/icons/misc3/bigfire00_anim.dds", 10, 5, 25}
a["@ChronicNutcase"] = {"LibCustomIcons/icons/misc3/chronicnutcase_anim2.dds", 30, 1, 9}
a["@xZocker_123x"] = {"LibCustomIcons/icons/animated/pikadab.dds", 7, 7, 20}
a["@MedikamentX"] = {"LibCustomIcons/icons/misc3/medikamentx_anim2.dds", 40, 1, 50}
a["@Finnifunfun"] = {"LibCustomIcons/icons/misc3/finnifunfun_anim2.dds", 47, 1, 10}
a["@ri'o"] = {"LibCustomIcons/icons/misc3/vvzrio_anim.dds", 10, 1, 5}
a["@Squonkalicious"] = {"LibCustomIcons/icons/misc3/squonkalicious_anim.dds", 13, 1, 13}
a["@bdeedee"] = {"LibCustomIcons/icons/misc3/bdeedee_anim.dds", 24, 1, 25}
a["@edamastergamer"] = {"LibCustomIcons/icons/misc3/edamastergamer_anim.dds", 9, 5, 15}
a["@RealKrappyyy"] = {"LibCustomIcons/icons/misc3/realkrappyyy_anim.dds", 8, 1, 25}
a["@OnIyFans"] = {"LibCustomIcons/icons/misc3/oniyfans_anim.dds", 19, 1, 12}
a["@BadTrauma"] = {"LibCustomIcons/icons/misc3/badtrauma_anim4.dds", 11, 1, 6}
a["@Q8Luffyx"] = {"LibCustomIcons/icons/misc3/q8luffyx_anim.dds", 8, 1, 11}
a["@JAM-JAM94"] = {"LibCustomIcons/icons/misc3/jamjam94_anim.dds", 13, 1, 50}
a["@Evendor666"] = {"LibCustomIcons/icons/misc3/evendor666_anim.dds", 12, 1, 20}
a["@Solomun18"] = {"LibCustomIcons/icons/misc3/solomun18_anim.dds", 42, 1, 3}
a["@Tanwen70"] = {"LibCustomIcons/icons/misc3/tanwen70_anim.dds", 22, 1, 10}
a["@unsoundd"] = {"LibCustomIcons/icons/misc3/unsoundd_anim.dds", 7, 4, 10}
a["@JexaJohn"] = {"LibCustomIcons/icons/misc3/jexajohn_anim.dds", 31, 1, 10}
a["@Szoszkenyh"] = {"LibCustomIcons/icons/misc/randomuserid1_anim.dds", 8, 4, 12}
a["@Lukewarm_Tater"] = {"LibCustomIcons/icons/misc3/lukewarmtater_anim.dds", 7, 1, 10}
a["@CookieNCream"] = {"LibCustomIcons/icons/misc3/cookiencream_anim.dds", 3, 1, 12}
a["@Pikachooo"] = {"LibCustomIcons/icons/misc3/pikachooo_anim.dds", 6, 1, 11}
a["@InfernalGoose"] = {"LibCustomIcons/icons/misc3/infernalgoose_anim2.dds", 16, 1, 25}
a["@techwar"] = {"LibCustomIcons/icons/misc3/techwar_anim.dds", 34, 1, 20}
a["@Thyster"] = {"LibCustomIcons/icons/misc3/thyster_anim.dds", 6, 1, 50}
a["@TwinLeafy"] = {"LibCustomIcons/icons/misc3/twinleafy_anim.dds", 42, 1, 8}
a["@Chubb8199"] = {"LibCustomIcons/icons/misc3/chubb_anim.dds", 22, 1, 15}
a["@Slaayz"] = {"LibCustomIcons/icons/misc3/slaayz_anim2.dds", 57, 1, 10}
a["@NoRolex"] = {"LibCustomIcons/icons/misc3/norolex_anim.dds", 9, 5, 20}
a["@BobbyDoee"] = {"LibCustomIcons/icons/misc3/bobbydoee_anim.dds", 6, 5, 10}
a["@Resei"] = {"LibCustomIcons/icons/misc3/resei_anim.dds", 11, 3, 13}
a["@MysticGemX"] = {"LibCustomIcons/icons/misc3/mysticgemx_anim.dds", 13, 1, 9}
a["@Scubi"] = {"LibCustomIcons/icons/misc3/scubi_anim.dds", 6, 4, 50}
a["@Godoring"] = {"LibCustomIcons/icons/misc3/godoring_anim4.dds", 26, 1, 17}
a["@dgy8261"] = {"LibCustomIcons/icons/misc3/dgy8261_anim.dds", 10, 1, 4}
a["@beautyorbeast"] = {"LibCustomIcons/icons/misc3/beautyorbeast_anim.dds", 13, 1, 13}
a["@StaggerStondly"] = {"LibCustomIcons/icons/misc3/stondly95_anim2.dds", 15, 1, 9}
a["@ilovemountains"] = {"LibCustomIcons/icons/misc3/ilovemountains_anim.dds", 3, 1, 11}
a["@Pankster"] = {"LibCustomIcons/icons/misc3/pankster_anim.dds", 49, 1, 25}
a["@Nehantia"] = {"LibCustomIcons/icons/misc3/nehantia_anim.dds", 16, 1, 11}
a["@Arccadez"] = {"LibCustomIcons/icons/misc3/arccadez_anim.dds", 8, 5, 25}
a["@TheNickm2"] = {"LibCustomIcons/icons/misc3/thenickm2_anim.dds", 15, 1, 14}
a["@wuzzywezzer"] = {"LibCustomIcons/icons/misc3/wuzzywezzer_anim.dds", 9, 1, 11}
a["@milktoad"] = {"LibCustomIcons/icons/misc3/milktoad_anim.dds", 23, 2, 10}
a["@VEx43"] = {"LibCustomIcons/icons/misc3/vex43_anim.dds", 29, 1, 10}
a["@JustAMist"] = {"LibCustomIcons/icons/misc3/justamist_anim.dds", 47, 1, 18}
a["@i_Skyy"] = {"LibCustomIcons/icons/misc3/iskyy_anim.dds", 24, 1, 50}
a["@KGNOG"] = {"LibCustomIcons/icons/misc3/kgnog_anim.dds", 13, 1, 15}
a["@Ldor"] = {"LibCustomIcons/icons/misc3/ldor_anim.dds", 37, 1, 10}
a["@The_Boomerang"] = {"LibCustomIcons/icons/misc3/theblackshack31_anim.dds", 11, 3, 20}
a["@jonnyzeraa"] = {"LibCustomIcons/icons/misc3/jonnyzeraa_anim.dds", 8, 6, 33}
a["@HAJ_24"] = {"LibCustomIcons/icons/misc3/haj24_anim.dds", 7, 1, 11}
a["@oMorg"] = {"LibCustomIcons/icons/misc3/omorgg_anim.dds", 12, 1, 11}
a["@IsCrooksy"] = {"LibCustomIcons/icons/misc3/iscrooksy_anim.dds", 30, 1, 15}
a["@Kai_S"] = {"LibCustomIcons/icons/misc3/kais_anim2.dds", 11, 1, 50}
a["@QuantumPie"] = {"LibCustomIcons/icons/misc3/quantumpie_anim.dds", 6, 6, 30}
a["@Upsetter"] = {"LibCustomIcons/icons/animated/fire.dds", 5, 1, 11}
a["@UtopianWarrior88"] = {"LibCustomIcons/icons/misc3/utopianwarrior88_anim.dds", 19, 1, 12}
a["@IsThatAWeed"] = {"LibCustomIcons/icons/misc3/isthataweed_anim.dds", 7, 6, 33}
a["@Wickerman666"] = {"LibCustomIcons/icons/misc3/wickerman666_anim.dds", 11, 1, 11}
a["@Adventure2098"] = {"LibCustomIcons/icons/misc3/adventure2098_anim.dds", 8, 1, 13}
a["@PineappleButts"] = {"LibCustomIcons/icons/misc3/pineapplebutts_anim.dds", 21, 1, 20}
a["@Tankgod"] = {"LibCustomIcons/icons/misc3/tankgod_anim.dds", 10, 1, 10}
a["@Its.EBK"] = {"LibCustomIcons/icons/misc3/itsebk_anim.dds", 18, 1, 13}
a["@FinalAe0n"] = {"LibCustomIcons/icons/misc3/finalae0n_anim.dds", 11, 1, 21}
a["@Quacc"] = {"LibCustomIcons/icons/misc3/quacc_anim.dds", 10, 5, 20}
a["@thecreed00"] = {"LibCustomIcons/icons/misc3/thecreed00_anim2.dds", 49, 1, 17}
a["@ThisEdgyGuy123"] = {"LibCustomIcons/icons/misc3/thisedgyguy123_anim.dds", 8, 5, 17}
a["@YungDoggo"] = {"LibCustomIcons/icons/misc3/yungdoggo_anim2.dds", 37, 1, 10}
a["@Nykto"] = {"LibCustomIcons/icons/misc3/nykto_anim.dds", 4, 1, 13}
a["@poptardpounder"] = {"LibCustomIcons/icons/misc3/poptardpounder_anim.dds", 3, 1, 11}
a["@Rhifted"] = {"LibCustomIcons/icons/misc3/rhifted_anim.dds", 28, 1, 15}
a["@Grey_Artorias"] = {"LibCustomIcons/icons/misc3/greyartorias_anim.dds", 45, 1, 10}
a["@Eragon49"] = {"LibCustomIcons/icons/misc3/eragon49_anim.dds", 23, 1, 12}
a["@devious66"] = {"LibCustomIcons/icons/misc3/devious66_anim.dds", 16, 1, 30}
a["@Lowiathan"] = {"LibCustomIcons/icons/misc3/lowscoman001_anim.dds", 18, 1, 14}
a["@euphorage"] = {"LibCustomIcons/icons/hodor/warfire_anim2.dds", 22, 1, 50}
a["@Ralonin"] = {"LibCustomIcons/icons/misc3/ralonin_anim.dds", 16, 1, 25}
a["@wellrcosta"] = {"LibCustomIcons/icons/misc3/wellrcosta_anim.dds", 14, 1, 25}
a["@leviatan64"] = {"LibCustomIcons/icons/misc3/leviatan64_anim.dds", 15, 1, 30}
a["@ImFour"] = {"LibCustomIcons/icons/misc3/imfour_anim2.dds", 8, 4, 20}
a["@Sweggo"] = {"LibCustomIcons/icons/misc3/sweggo_anim.dds", 20, 1, 10}
a["@OG_Flaco"] = {"LibCustomIcons/icons/misc3/ogflaco_anim.dds", 6, 1, 10}
a["@MG.coockie"] = {"LibCustomIcons/icons/misc3/mgcoockie_anim.dds", 23, 2, 17}
a["@KoruptProdigy"] = {"LibCustomIcons/icons/misc3/koruptprodigy_anim.dds", 21, 1, 20}
a["@WamiDaBami"] = {"LibCustomIcons/icons/misc3/wamidabami_anim2.dds", 3, 1, 14}
a["@MooncakeS2"] = {"LibCustomIcons/icons/misc3/thisbishheals_anim.dds", 22, 1, 20}
a["@SwankeyTiger"] = {"LibCustomIcons/icons/misc3/swankeytiger_anim.dds", 19, 1, 14}
a["@DeathswiT"] = {"LibCustomIcons/icons/misc3/deathswit_anim.dds", 13, 1, 21}
a["@Kandibobier"] = {"LibCustomIcons/icons/misc3/kandibobier_anim.dds", 16, 1, 30}
a["@Oclarion"] = {"LibCustomIcons/icons/misc3/oclarion_anim2.dds", 17, 1, 20}
a["@xSaladinnX"] = {"LibCustomIcons/icons/misc3/xsaladinnx_anim.dds", 27, 1, 15}
a["@Jetyz"] = {"LibCustomIcons/icons/misc3/jetyz_anim.dds", 6, 1, 10}
a["@Toe-Moss"] = {"LibCustomIcons/icons/misc3/toemoss_anim.dds", 35, 1, 25}
a["@beesea"] = {"LibCustomIcons/icons/misc3/beesea_anim.dds", 18, 1, 10}
a["@LingRanLi"] = {"LibCustomIcons/icons/misc3/lingranli_anim4.dds", 11, 1, 25}
a["@Cardiana"] = {"LibCustomIcons/icons/misc3/cardiana_anim.dds", 5, 1, 5}
a["@DevJake"] = {"LibCustomIcons/icons/misc3/devjake_anim2.dds", 24, 1, 13}
a["@Abosho"] = {"LibCustomIcons/icons/misc3/abosho_anim3.dds", 8, 5, 25}
a["@KaronisEQ2"] = {"LibCustomIcons/icons/misc3/KaronisEQ2_anim.dds", 7, 6, 10}
a["@OGVictory"] = a["@DeathswiT"]
a["@Foolebuilt"] = a["catjam"]
a["@ImSteve"] = a["catjam"]
a["@Kalhe"] = a["pikadab"]
a["@Guilt_Trip"] = a["catjam"]
a["@ImChasee"] = a["catjam"]
a["@LeDzul"] = a["catjam"]
a["@Cheonsa"] = {"LibCustomIcons/icons/misc3/blxss_anim.dds", 6, 6, 25}
a["@asobimashokashiro"] = {"LibCustomIcons/icons/misc3/blxss_anim.dds", 6, 6, 25}
a["@insektorr"] = {"LibCustomIcons/icons/misc3/blxss_anim.dds", 6, 6, 25}
