-- SPDX-FileCopyrightText: 2025 m00nyONE
-- SPDX-License-Identifier: Artistic-2.0

local lib_name = "LibCustomIcons"
local lib = _G[lib_name]
local s = lib.GetStaticTable()
local a = lib.GetAnimatedTable()

s["@Anorage"] = "LibCustomIcons/icons/misc7/Anorage_2.dds"
a["@Ash.land"] = {"LibCustomIcons/icons/misc7/Ashland_anim.dds", 5, 5, 30}
s["@Axe_Zuffs"] = "LibCustomIcons/icons/misc7/Axe_Zuffs.dds"
s["@nitm4r3"] = "LibCustomIcons/icons/misc7/nitm4r3.dds"
s["@Vilooo"] = "LibCustomIcons/icons/misc7/Vilooo.dds"
s["@oScorpio"] = "LibCustomIcons/icons/misc7/oScorpio.dds"
s["@IAstronomicanI"] = "LibCustomIcons/icons/misc7/IAstronomicanI.dds"
s["@Debuffed"] = "LibCustomIcons/icons/misc7/Debuffed.dds"
s["@lKalahari"] = "LibCustomIcons/icons/misc7/lKalahari_2.dds"
a["@lKalahari"] = {"LibCustomIcons/icons/misc7/lKalahari_anim_2.dds", 10, 5, 20}
s["@Maccies"] = "LibCustomIcons/icons/misc7/Maccies.dds"
s["@Jdaytona"] = "LibCustomIcons/icons/misc7/Jdaytona.dds"
s["@Mayhem86"] = "LibCustomIcons/icons/misc7/Mayhem86.dds"
s["@Razor1991"] = "LibCustomIcons/icons/misc7/Razor1991.dds"
s["@Yunaalescaa"] = "LibCustomIcons/icons/misc7/Yunaalescaa.dds"
s["@AimboBaggins"] = "LibCustomIcons/icons/misc7/AimboBaggins.dds"
s["@Megatreck8"] = "LibCustomIcons/icons/misc7/Megatreck8.dds"
s["@SladkiyDistroy"] = "LibCustomIcons/icons/misc7/SladkiyDistroy.dds"
s["@Ak4r1"] = "LibCustomIcons/icons/misc7/Ak4r1.dds"
s["@Prof_Flausch"] = "LibCustomIcons/icons/misc7/prof_flausch.dds"
s["@Ravnic93"] = "LibCustomIcons/icons/misc7/ravnic93.dds"
s["@Tomharken"] = "LibCustomIcons/icons/misc7/Tomharken.dds"
s["@BULLAVAS"] = "LibCustomIcons/icons/misc7/BULLAVAS.dds"
a["@BULLAVAS"] = {"LibCustomIcons/icons/misc7/BULLAVAS_anim.dds", 10, 5, 24}
s["@LittleESO"] = "LibCustomIcons/icons/misc7/LittleESO.dds"
s["@Boxis"] = "LibCustomIcons/icons/misc7/Boxis.dds"
s["@Circuitous"] = "LibCustomIcons/icons/misc7/Circuitous.dds"
s["@TAISELE"] = "LibCustomIcons/icons/misc7/TAISELE.dds"
s["@SedationMaster"] = "LibCustomIcons/icons/misc7/SedationMaster.dds"
s["@breadandmllk"] = "LibCustomIcons/icons/misc7/breadandmllk.dds"
s["@madmufffin"] = "LibCustomIcons/icons/misc7/madmufffin.dds"
s["@someone_unknown"] = "LibCustomIcons/icons/misc7/someone_unknown.dds"
s["@VaLeeeT"] = "LibCustomIcons/icons/misc7/VaLeeeT.dds"
s["@Toweliewahn"] = "LibCustomIcons/icons/misc7/Toweliewahn.dds"
s["@Shae.Vizla"] = "LibCustomIcons/icons/misc7/Shae.Vizla.dds"
s["@LunarKitsune"] = "LibCustomIcons/icons/misc7/LunarKitsune.dds"
s["@eileen_bck"] = "LibCustomIcons/icons/misc7/eileen_bck.dds"
s["@Antonyfly"] = "LibCustomIcons/icons/misc7/Antonyfly.dds"
s["@GL0O"] = "LibCustomIcons/icons/misc7/GL0O.dds"
s["@alansgaming"] = "LibCustomIcons/icons/misc7/alansgaming.dds"
s["@Lukion04"] = "LibCustomIcons/icons/misc7/Lukion04.dds"
s["@Minhoca420"] = "LibCustomIcons/icons/misc7/Minhoca420.dds"
s["@Oxi4an"] = "LibCustomIcons/icons/misc7/Oxi4an.dds"
a["@Oxi4an"] = {"LibCustomIcons/icons/misc7/Oxi4an_anim.dds", 20, 1, 10}
s["@Diemente"] = "LibCustomIcons/icons/misc7/Diemente.dds"
s["@JalaBenjo"] = "LibCustomIcons/icons/misc7/JalaBenjo.dds"
s["@lid_lid"] = "LibCustomIcons/icons/misc7/lid_lid_2.dds"
s["@Im_Churro"] = "LibCustomIcons/icons/misc7/Im_Churro.dds"
s["@Oonora"] = "LibCustomIcons/icons/misc7/Oonora.dds"
s["@SkyFox_01"] = "LibCustomIcons/icons/misc7/SkyFox_01.dds"
s["@didntgetpillager"] = "LibCustomIcons/icons/misc7/didntgetpillager.dds"
s["@issavo"] = "LibCustomIcons/icons/misc7/issavo.dds"
s["@AloAlo"] = "LibCustomIcons/icons/misc7/AloAlo.dds"
s["@xColorovy"] = "LibCustomIcons/icons/misc7/xColorovy.dds"
s["@efiye"] = "LibCustomIcons/icons/misc7/efiye.dds"
s["@SophieRain"] = "LibCustomIcons/icons/misc7/SophieRain.dds"
s["@Bleek707"] = "LibCustomIcons/icons/misc7/Bleek707.dds"
s["@Always_Atlas"] = "LibCustomIcons/icons/misc7/Always_Atlas.dds"
a["@Always_Atlas"] = {"LibCustomIcons/icons/misc7/Always_Atlas_anim.dds", 7, 1, 23}
s["@DownZi"] = "LibCustomIcons/icons/misc7/DownZi.dds"
s["@SassyFluffington"] = "LibCustomIcons/icons/misc7/SassyFluffington.dds"
s["@Orllyon"] = "LibCustomIcons/icons/misc7/Orllyon.dds"
s["@Mr.Maxie"] = "LibCustomIcons/icons/misc7/Mr.Maxie.dds"
s["@TheInquisitiveSpoon"] = "LibCustomIcons/icons/misc7/TheInquisitiveSpoon.dds"
s["@shigeatzu"] = "LibCustomIcons/icons/misc7/shigeatzu.dds"
s["@BayzBlackBaccara"] = "LibCustomIcons/icons/misc7/BayzBlackBaccara.dds"
s["@Sai_ESO"] = "LibCustomIcons/icons/misc7/Sai_ESO.dds"
s["@Qkzzz"] = "LibCustomIcons/icons/misc7/Qkzzz.dds"
s["@Kqzzz"] = "LibCustomIcons/icons/misc7/Kqzzz.dds"
s["@DovakiinFawad"] = "LibCustomIcons/icons/misc7/DovakiinFawad.dds"
s["@dianabz"] = "LibCustomIcons/icons/misc7/dianabz.dds"
s["@Abi_raga"] = "LibCustomIcons/icons/misc7/Abi_raga.dds"
s["@PinduriBerkenye"] = "LibCustomIcons/icons/misc7/PinduriBerkenye.dds"
s["@TheMemeLord27"] = "LibCustomIcons/icons/misc7/TheMemeLord27.dds"
s["@harueee"] = "LibCustomIcons/icons/misc7/harueee_2.dds"
s["@BosmerBathWater"] = "LibCustomIcons/icons/misc7/BosmerBathWater.dds"
a["@NumberOneZergling"] = {"LibCustomIcons/icons/misc7/NumberOneZergling_anim.dds", 16, 2, 16}
a["@Fishy399"] = {"LibCustomIcons/icons/misc7/Fishy399_anim.dds", 2, 2, 17}
a["@PiscesIII"] = {"LibCustomIcons/icons/misc7/PiscesIII_anim.dds", 3, 2, 33}
a["@DanoFett"] = {"LibCustomIcons/icons/misc7/DanoFett_anim.dds", 10, 5, 15}
a["@bi0skill3r"] = {"LibCustomIcons/icons/misc7/bi0skill3r_anim.dds", 7, 4, 10}
a["@ScaRlet9512"] = {"LibCustomIcons/icons/misc7/ScaRlet9512_anim.dds", 6, 2, 10}
a["@sekikamisama"] = {"LibCustomIcons/icons/misc7/sekikamisama_anim.dds", 10, 2, 20}
a["@Ponsie"] = {"LibCustomIcons/icons/misc7/Ponsie_anim.dds", 2, 2, 5}
a["@Blaze03"] = {"LibCustomIcons/icons/misc7/Blaze03_anim.dds", 5, 2, 25}
a["@oDutt"] = {"LibCustomIcons/icons/misc7/oDutt_anim.dds", 16, 2, 17}
a["@Volderam"] = {"LibCustomIcons/icons/misc7/Volderam_anim.dds", 17, 1, 10}
a["@DrGaricus"] = {"LibCustomIcons/icons/misc7/DrGaricus_anim.dds", 5, 1, 10}
a["@gettin_fresh"] = {"LibCustomIcons/icons/misc7/gettin_fresh_anim.dds", 10, 2, 20}
a["@Ayonnis"] = {"LibCustomIcons/icons/misc7/Ayonnis_anim.dds", 7, 3, 7}
a["@fdk123"] = {"LibCustomIcons/icons/misc7/fdk123_anim.dds", 3, 1, 2}
a["@h-Gecko"] = {"LibCustomIcons/icons/misc7/h-Gecko_anim.dds", 7, 7, 14}
a["@RealLoveBVB"] = {"LibCustomIcons/icons/misc7/RealLoveBVB_anim.dds", 7, 2, 32}
a["@Sc1lla"] = {"LibCustomIcons/icons/misc7/Sc1lla_anim.dds", 10, 5, 20}
a["@PaganPandas"] = {"LibCustomIcons/icons/misc7/PaganPandas_anim_4.dds", 11, 2, 50}
a["@CedrazGil"] = {"LibCustomIcons/icons/misc7/CedrazGil_anim.dds", 9, 2, 33}
a["@veludelu"] = {"LibCustomIcons/icons/misc7/veludelu_anim.dds", 6, 5, 10}
a["@OmnipotentYouthSocie"] = {"LibCustomIcons/icons/misc7/OmnipotentYouthSocie_anim.dds", 5, 4, 10}
a["@iimTaylor"] = {"LibCustomIcons/icons/misc7/iimTaylor_anim.dds", 3, 3, 8}
a["@p0rk"] = {"LibCustomIcons/icons/misc7/p0rk_anim.dds", 3, 1, 5}
a["@Root118"] = {"LibCustomIcons/icons/misc7/Root118_anim.dds", 13, 2, 6}
a["@Shirogami107"] = {"LibCustomIcons/icons/misc7/Shirogami107_anim.dds", 5, 3, 15}
a["@Passaringo"] = {"LibCustomIcons/icons/misc7/Passaringo_anim.dds", 10, 5, 20}
a["@Plies"] = {"LibCustomIcons/icons/misc7/Plies_anim.dds", 7, 1, 9}
a["@Anastesia69"] = {"LibCustomIcons/icons/misc7/Anastesia69_anim.dds", 10, 5, 10}
a["@EchoWFlechazo"] = {"LibCustomIcons/icons/misc7/EchoWFlechazo_anim.dds", 10, 5, 10}
a["@VerifiedToy"] = {"LibCustomIcons/icons/misc7/VerifiedToy_anim.dds", 5, 2, 9}
a["@Haikyuu_929"] = {"LibCustomIcons/icons/misc7/Haikyuu_929_anim.dds", 32, 1, 17}
s["@iiTzFlyy"] = "LibCustomIcons/icons/misc7/iiTzFlyy.dds"
a["@Exosq"] = {"LibCustomIcons/icons/misc7/Exosq_anim.dds", 9, 2, 9}
a["@Mizeov"] = {"LibCustomIcons/icons/misc7/Mizeov_anim.dds", 7, 6, 13}
a["@zuxyq"] = {"LibCustomIcons/icons/misc7/zuxyq_anim_2.dds", 9, 5, 12.5}
a["@ComandoAlpha"] = {"LibCustomIcons/icons/misc7/ComandoAlpha_anim.dds", 7, 7, 10}
a["@Balfgur"] = {"LibCustomIcons/icons/misc7/Balfgur_anim.dds", 5, 2, 25}
a["@arcadeslum"] = {"LibCustomIcons/icons/misc7/arcadeslum_anim.dds", 7, 7, 20}
a["@xSi1ver"] = {"LibCustomIcons/icons/misc7/xSi1ver_anim.dds", 23, 2, 14}
a["@oAMo"] = {"LibCustomIcons/icons/misc7/oAMo_anim.dds", 19, 1, 12.5}
a["@riminise"] = {"LibCustomIcons/icons/misc7/riminise_anim.dds", 7, 7, 16}
a["@Innsmaut"] = {"LibCustomIcons/icons/misc7/innsmaut_anim.dds", 6, 1, 8}
a["@Stakan9000"] = {"LibCustomIcons/icons/misc7/Stakan9000_anim.dds", 5, 3, 47}
a["@MiguelCura"] = {"LibCustomIcons/icons/misc7/MiguelCura_anim.dds", 5, 2, 14}
a["@PinduriBerkenye"] = {"LibCustomIcons/icons/misc7/PinduriBerkenye_anim.dds", 7, 2, 11}
a["@Loreuh"] = {"LibCustomIcons/icons/misc7/Loreuh_anim.dds", 5, 2, 33}
a["@Noobl3t"] = {"LibCustomIcons/icons/misc7/Noobl3t_anim.dds", 9, 5, 13}
s["@Sbirr0"] = "LibCustomIcons/icons/misc7/Sbirr0.dds"
s["@Eilistraae"] = "LibCustomIcons/icons/misc7/Eilistraae.dds"
a["@damage_1"] = {"LibCustomIcons/icons/misc7/damage_1_anim.dds", 11, 1, 17}
a["@Perxie"] = {"LibCustomIcons/icons/misc7/Perxie_anim.dds", 8, 1, 20}
s["@AlsClarity"] = "LibCustomIcons/icons/misc7/AlsClarity.dds"
a["@Malkovva"] = {"LibCustomIcons/icons/misc7/Malkovva_anim.dds", 11, 3, 50}
a["@MissMya"] = {"LibCustomIcons/icons/misc7/MissMya_anim.dds", 9, 1, 18}
a["@DEATH_SHAD0W226"] = {"LibCustomIcons/icons/misc7/DEATH_SHAD0W226_anim.dds", 30, 1, 10}
a["@Pegno"] = {"LibCustomIcons/icons/misc7/Pegno_anim.dds", 16, 2, 10}
a["@Tang015"] = {"LibCustomIcons/icons/misc7/Tang015_anim.dds", 13, 1, 14}
s["@babak.babak"] = "LibCustomIcons/icons/misc7/babak.babak.dds"
s["@pyrolah"] = "LibCustomIcons/icons/misc7/pyrolah.dds"
s["@Master_Merlyn"] = "LibCustomIcons/icons/misc7/Master_Merlyn_2.dds"
s["@CoCo_OwO"] = "LibCustomIcons/icons/misc7/CoCo_OwO.dds"
a["@Louis.Scrolls"] = {"LibCustomIcons/icons/misc7/Louis.Scrolls_anim.dds", 25, 2, 25}
a["@Jasper0729"] = {"LibCustomIcons/icons/misc7/Jasper0729_anim.dds", 47, 1, 14}
s["@Yuhaa"] = "LibCustomIcons/icons/misc7/Yuhaa_2.dds"
s["@Rexeyas"] = "LibCustomIcons/icons/misc7/Rexeyas.dds"
s["@adis3636"] = "LibCustomIcons/icons/misc7/adis3636.dds"
s["@doctorosen"] = "LibCustomIcons/icons/misc7/doctorosen.dds"
s["@Shadorein"] = "LibCustomIcons/icons/misc7/Shadorein.dds"
a["@Rainbow_Stay"] = {"LibCustomIcons/icons/misc7/Rainbow_Stay_anim.dds", 41, 1, 25}
a["@LordDraw"] = {"LibCustomIcons/icons/misc7/LordDraw_anim.dds", 74, 3, 20}
s["@Lil_Moham"] = "LibCustomIcons/icons/misc7/Lil_Moham.dds"
s["@rimuru552"] = "LibCustomIcons/icons/misc7/rimuru552.dds"
a["@Red-Roxie"] = {"LibCustomIcons/icons/misc7/Red-Roxie_anim.dds", 5, 2, 10}
a["@Havoc.1412"] = {"LibCustomIcons/icons/misc7/Havoc.1412_anim.dds", 7, 7, 25}
a["@JayyMi"] = {"LibCustomIcons/icons/misc7/JayyMi_anim.dds", 23, 6, 20}
s["@korgaard"] = "LibCustomIcons/icons/misc7/korgaard.dds"
a["@PvPenny"] = {"LibCustomIcons/icons/misc7/PvPenny_anim.dds", 3, 2, 10}
s["@UncleFoxx"] = "LibCustomIcons/icons/misc7/UncleFoxx.dds"
s["@JacobWasTake'n"] = "LibCustomIcons/icons/misc7/JacobWasTaken.dds"
s["@kamikiro"] = "LibCustomIcons/icons/misc7/kamikiro.dds"
s["@RashEnderSami"] = "LibCustomIcons/icons/misc7/RashEnderSami.dds"
s["@STUDLETON"] = "LibCustomIcons/icons/misc7/STUDLETON.dds"
s["@SnattyDee"] = "LibCustomIcons/icons/misc7/SnattyDee.dds"
a["@SnattyDee"] = {"LibCustomIcons/icons/misc7/SnattyDee_anim.dds", 4, 3, 15}
s["@rip8nine"] = "LibCustomIcons/icons/misc7/rip8nine.dds"
a["@rip8nine"] = {"LibCustomIcons/icons/misc7/rip8nine_anim.dds", 6, 6, 6}
s["@AmpEBK"] = "LibCustomIcons/icons/misc7/AmpEBK.dds"
a["@AmpEBK"] = {"LibCustomIcons/icons/misc7/AmpEBK_anim.dds", 6, 3, 9}
s["@Ned919x"] = "LibCustomIcons/icons/misc7/Ned919x.dds"
a["@Ned919x"] = {"LibCustomIcons/icons/misc7/Ned919x_anim.dds", 10, 5, 16}
s["@Karlitaa"] = "LibCustomIcons/icons/misc7/Karlitaa.dds"
a["@Karlitaa"] = {"LibCustomIcons/icons/misc7/Karlitaa_anim.dds", 5, 2, 10}
a["@KevTheChosenOne"] = {"LibCustomIcons/icons/misc7/KevTheChosenOne_anim.dds", 9, 5, 27}
s["@sagitta14"] = "LibCustomIcons/icons/misc7/sagitta14.dds"
s["@LianYi2044"] = "LibCustomIcons/icons/misc7/LianYi2044.dds"
a["@Zard_9527"] = {"LibCustomIcons/icons/misc7/Zard_9527_anim.dds", 3, 2, 10}
s["@prismaticsgg"] = "LibCustomIcons/icons/misc7/prismaticsgg.dds"
s["@WashedNotSloshed"] = "LibCustomIcons/icons/misc7/WashedNotSloshed.dds"
s["@braiso_24"] = "LibCustomIcons/icons/misc7/braiso_24.dds"
s["@Thorheit-Teutonia"] = "LibCustomIcons/icons/misc7/Thorheit-Teutonia.dds"
s["@Dark_Hydralisk"] = "LibCustomIcons/icons/misc7/Dark_Hydralisk.dds"
a["@ShIsanSAkura"] = {"LibCustomIcons/icons/misc7/ShIsanSAkura_anim.dds", 7, 4, 25}
s["@TeaMaster1010"] = "LibCustomIcons/icons/misc7/TeaMaster1010.dds"
s["@Calisto7"] = "LibCustomIcons/icons/misc7/Calisto7.dds"
s["@Latinwolverine"] = "LibCustomIcons/icons/misc7/Latinwolverine.dds"
s["@Prxvokedlegend"] = "LibCustomIcons/icons/misc7/Prxvokedlegend.dds"
a["@Prxvokedlegend"] = {"LibCustomIcons/icons/misc7/Prxvokedlegend_anim.dds", 5, 2, 10}
s["@megggish"] = "LibCustomIcons/icons/misc7/megggish.dds"
s["@Bakleeda"] = "LibCustomIcons/icons/misc7/Bakleeda.dds"
a["@Bakleeda"] = {"LibCustomIcons/icons/misc7/Bakleeda_anim.dds", 7, 2, 10}
s["@GENRAL-LAGGZ"] = "LibCustomIcons/icons/misc7/GENRAL-LAGGZ.dds"
a["@GENRAL-LAGGZ"] = {"LibCustomIcons/icons/misc7/GENRAL-LAGGZ_anim.dds", 3, 2, 5}
s["@ewilliam"] = "LibCustomIcons/icons/misc7/ewilliam.dds"
a["@ewilliam"] = {"LibCustomIcons/icons/misc7/ewilliam_anim.dds", 19, 1, 20}
s["@Chay'Kashet"] = "LibCustomIcons/icons/misc7/ChayKashet.dds"
s["@Pocket3591"] = "LibCustomIcons/icons/misc7/Pocket3591.dds"
a["@Pocket3591"] = {"LibCustomIcons/icons/misc7/Pocket3591_anim.dds", 5, 1, 10}
s["@InsaneShad0w92"] = "LibCustomIcons/icons/misc7/InsaneShad0w92.dds"
s["@MaceWinduwu"] = "LibCustomIcons/icons/misc7/MaceWinduwu.dds"
a["@MaceWinduwu"] = {"LibCustomIcons/icons/misc7/MaceWinduwu_anim.dds", 32, 1, 33}
s["@CRaull"] = "LibCustomIcons/icons/misc7/CRaull.dds"
s["@RadienESO"] = "LibCustomIcons/icons/misc7/RadienESO.dds"
s["@Manitaropitas"] = "LibCustomIcons/icons/misc7/Manitaropitas.dds"
s["@IgnisCore"] = "LibCustomIcons/icons/misc7/IgnisCore.dds"
s["@KendrasKenpachi"] = "LibCustomIcons/icons/misc7/KendrasKenpachi.dds"
s["@Minasgorth"] = "LibCustomIcons/icons/misc7/Minasgorth.dds"
s["@WildCatra"] = "LibCustomIcons/icons/misc7/WildCatra.dds"
s["@Forney"] = "LibCustomIcons/icons/misc7/Forney.dds"
s["@TheFaytFoundation"] = "LibCustomIcons/icons/misc7/TheFaytFoundation.dds"
s["@silencia330"] = "LibCustomIcons/icons/misc7/silencia330.dds"
a["@silencia330"] = {"LibCustomIcons/icons/misc7/silencia330_anim.dds", 8, 6, 16}
s["@RunPenguin"] = "LibCustomIcons/icons/misc7/RunPenguin.dds"
s["@UgliBiBagli"] = "LibCustomIcons/icons/misc7/UgliBiBagli.dds"
a["@UgliBiBagli"] = {"LibCustomIcons/icons/misc7/UgliBiBagli_anim.dds", 6, 1, 12}
s["@PoeticEevee"] = "LibCustomIcons/icons/misc7/PoeticEevee.dds"
s["@Hersher"] = "LibCustomIcons/icons/misc7/Hersher_2.dds"
a["@Hersher"] = {"LibCustomIcons/icons/misc7/Hersher_anim_2.dds", 10, 1, 12.5}
s["@Sir_Karli"] = "LibCustomIcons/icons/misc7/Sir_Karli.dds"
a["@Sir_Karli"] = {"LibCustomIcons/icons/misc7/Sir_Karli_anim.dds", 10, 1, 30}
s["@amberlink"] = "LibCustomIcons/icons/misc7/amberlink.dds"
s["@revanthemage"] = "LibCustomIcons/icons/misc7/revanthemage.dds"
s["@Larenatos"] = "LibCustomIcons/icons/misc7/Larenatos.dds"
s["@Rasa27"] = "LibCustomIcons/icons/misc7/Rasa27.dds"
s["@Lezwin"] = "LibCustomIcons/icons/misc7/Lezwin.dds"
a["@Lezwin"] = {"LibCustomIcons/icons/misc7/Lezwin_anim.dds", 7, 7, 20}
a["@Rasa27"] = {"LibCustomIcons/icons/misc7/Rasa27_anim.dds", 20, 1, 7}
s["@Szaves"] = "LibCustomIcons/icons/misc7/panda.dds"
s["@Quicknick980"] = "LibCustomIcons/icons/misc7/Quicknick980.dds"
a["@Quicknick980"] = {"LibCustomIcons/icons/misc7/Quicknick980_anim.dds", 10, 3, 7}
s["@zeusxwilson"] = "LibCustomIcons/icons/misc7/zeusxwilson_2.dds"
a["@zeusxwilson"] = {"LibCustomIcons/icons/misc7/zeusxwilson_anim_2.dds", 25, 1, 8}
s["@Bezlickiy"] = "LibCustomIcons/icons/misc7/Bezlickiy.dds"
a["@Bezlickiy"] = {"LibCustomIcons/icons/misc7/Bezlickiy_anim.dds", 15, 1, 19}
s["@Nay'rya"] = "LibCustomIcons/icons/misc7/Nayrya.dds"
s["@artemisbows"] = "LibCustomIcons/icons/misc7/artemisbows.dds"
s["@Hastriv"] = "LibCustomIcons/icons/misc7/hastriv.dds"
a["@maico09"] = {"LibCustomIcons/icons/misc7/maico09_anim.dds", 34, 1, 10}
a["@kalormano"] = {"LibCustomIcons/icons/misc7/kalormano_anim.dds", 11, 1, 10}
s["@Noble-Bear"] = "LibCustomIcons/icons/misc7/Noble-Bear.dds"
s["@Parrales"] = "LibCustomIcons/icons/misc7/parrales.dds"
s["@Levin788"] = "LibCustomIcons/icons/misc7/Levin788.dds"
a["@Levin788"] = {"LibCustomIcons/icons/misc7/Levin788_anim.dds", 17, 2, 10}
s["@Nathkim"] = "LibCustomIcons/icons/misc7/deadpool-logo-128.dds"
s["@nephAA"] = "LibCustomIcons/icons/misc7/nephAA.dds"
s["@Raylax"] = "LibCustomIcons/icons/misc7/Raylax.dds"
a["@saltmachine"] = {"LibCustomIcons/icons/misc7/saltmachine.dds", 3, 3, 6}
s["@C.urse"] = "LibCustomIcons/icons/misc7/Curse.dds"
a["@C.urse"] = {"LibCustomIcons/icons/misc7/Curse_anim.dds", 6, 1, 8}
s["@Zloyka"] = "LibCustomIcons/icons/misc7/Zloyka.dds"
a["@Zloyka"] = {"LibCustomIcons/icons/misc7/Zloyka_anim.dds", 5, 1, 10}
s["@Raffazz"] = "LibCustomIcons/icons/misc7/Raffazz.dds"
a["@MumenR1der"] = {"LibCustomIcons/icons/misc7/MumenR1der_anim.dds", 6, 3, 6}
a["@IgnDarius"] = {"LibCustomIcons/icons/misc7/IgnDarius_anim.dds", 13, 3, 6}
s["@Oshin3"] = "LibCustomIcons/icons/misc7/Oshin3.dds"
s["@pkstar12"] = "LibCustomIcons/icons/misc7/pkstar12.dds"
s["@DrewUout1"] = "LibCustomIcons/icons/misc7/DrewUout1.dds"
a["@DrewUout1"] = {"LibCustomIcons/icons/misc7/DrewUout1_anim.dds", 5, 6, 10}
s["@Trimphus"] = "LibCustomIcons/icons/misc7/Trimphus.dds"
a["@Trimphus"] = {"LibCustomIcons/icons/misc7/Trimphus_anim.dds", 19, 2, 14}
s["@PomQc"] = "LibCustomIcons/icons/misc7/PomQc.dds"
s["@TianRan1"] = "LibCustomIcons/icons/misc7/TianRan1.dds"
s["@Demisoul"] = "LibCustomIcons/icons/misc7/Demisoul.dds"
a["@Demisoul"] = {"LibCustomIcons/icons/misc7/Demisoul_anim.dds", 5, 2, 10}
s["@Addietlw"] = "LibCustomIcons/icons/misc7/Addietlw.dds"
s["@Steppeswolf"] = "LibCustomIcons/icons/misc7/Steppeswolf.dds"
a["@Steppeswolf"] = {"LibCustomIcons/icons/misc7/Steppeswolf_anim.dds", 13, 1, 10}
s["@Podwawelski"] = "LibCustomIcons/icons/misc7/Podwawelski.dds"
a["@Podwawelski"] = {"LibCustomIcons/icons/misc7/Podwawelski_anim.dds", 12, 1, 25}
s["@Cxvalry"] = "LibCustomIcons/icons/misc7/Cxvalry.dds"
a["@Cxvalry"] = {"LibCustomIcons/icons/misc7/Cxvalry_anim.dds", 30, 1, 20}
s["@Jamestlw"] = "LibCustomIcons/icons/misc7/Jamestlw.dds"
s["@Syoni"] = "LibCustomIcons/icons/misc7/Syoni.dds"
s["@LICH_PK"] = "LibCustomIcons/icons/misc7/lich.dds"
s["@KuebelFieber"] = "LibCustomIcons/icons/misc7/KuebelFieber.dds"
a["@KuebelFieber"] = {"LibCustomIcons/icons/misc7/KuebelFieber_anim.dds", 22, 2, 50}
s["@Lorelay123"] = "LibCustomIcons/icons/misc7/dragon_ice.dds"
s["@pärtdark"] = "LibCustomIcons/icons/misc7/dragon_fire.dds"
a["@Orollas"] = {"LibCustomIcons/icons/misc7/Orollas_anim.dds", 21, 1, 10}
a["@VollständigerName"] = {"LibCustomIcons/icons/misc7/VollstandigerName_anim.dds", 5, 1, 12}
s["@ItsBigKai"] = "LibCustomIcons/icons/misc7/ItsBigKai.dds"
s["@ReviaAndersson"] = "LibCustomIcons/icons/misc7/ReviaAndersson.dds"
s["@K1k1Mu"] = "LibCustomIcons/icons/misc7/K1k1Mu.dds"
s["@CrazyFr00g"] = "LibCustomIcons/icons/misc7/CrazyFr00g.dds"
s["@Grovkarln"] = "LibCustomIcons/icons/misc7/Grovkarln.dds"
a["@Grovkarln"] = {"LibCustomIcons/icons/misc7/Grovkarln_anim.dds", 19, 2, 13}
s["@coatsncheeze"] = "LibCustomIcons/icons/misc7/coatsncheeze_2.dds"
a["@coatsncheeze"] = {"LibCustomIcons/icons/misc7/coatsncheeze_anim_2.dds", 19, 1, 10}
s["@Kebahah"] = "LibCustomIcons/icons/misc7/Kebahah.dds"
s["@Valjaria"] = "LibCustomIcons/icons/misc7/Valjaria.dds"
s["@mikaleidoscorpion"] = "LibCustomIcons/icons/misc7/mikaleidoscorpion.dds"
s["@EstarossaOfHate"] = "LibCustomIcons/icons/misc7/EstarossaOfHate.dds"
s["@SteveIrwin_ESO"] = "LibCustomIcons/icons/misc7/SteveIrwin.dds"
a["@Rilarra"] = {"LibCustomIcons/icons/misc7/Rilarra_anim_2.dds", 15, 2, 10}
s["@Max.kvy"] = "LibCustomIcons/icons/misc7/Maxkvy.dds"
s["@DEA1HPIXEL"] = "LibCustomIcons/icons/misc7/deathpixel.dds"
s["@victory19"] = "LibCustomIcons/icons/misc7/victory19.dds"
a["@DessieLou"] = {"LibCustomIcons/icons/misc7/dessie.dds", 6, 6, 20}
s["@mr_me2018"] = "LibCustomIcons/icons/misc7/mrme.dds"
s["@DisabledBro's"] = "LibCustomIcons/icons/misc7/disabledbros.dds"
s["@Nightharrow"] = "LibCustomIcons/icons/misc7/nightharrow.dds"
s["@einjw"] = "LibCustomIcons/icons/misc7/einjw.dds"
s["@Neifary"] = "LibCustomIcons/icons/misc7/Neifary.dds"
a["@Crocoenjoyer"] = {"LibCustomIcons/icons/misc7/Crocoenjoyer_anim.dds", 23, 1, 20}
s["@Nala-78"] = "LibCustomIcons/icons/misc7/Nala-78.dds"
a["@Aries13th"] = {"LibCustomIcons/icons/misc7/aries13th.dds", 6, 5, 7}
a["@FairyMori"] = {"LibCustomIcons/icons/misc7/FairyMori_anim.dds", 11, 1, 9}
s["@xSHANNARAx"] = "LibCustomIcons/icons/misc7/shannara.dds"
s["@alarya_2"] = "LibCustomIcons/icons/misc7/alarya_2.dds"
s["@MathildaHex"] = "LibCustomIcons/icons/misc7/MathiHex.dds"
s["@triquetra"] = "LibCustomIcons/icons/misc7/triquetra.dds"
s["@Laurilen"] = "LibCustomIcons/icons/misc7/laurilen.dds"
s["@RedLeader99"] = "LibCustomIcons/icons/misc7/RedLeader99.dds"
a["@chamina"] = {"LibCustomIcons/icons/misc7/Cham_anim.dds", 25, 1, 12}
s["@jkmcnk"] = "LibCustomIcons/icons/misc7/jkmcnk.dds"
s["@DarthJarJar66"] = "LibCustomIcons/icons/misc7/DarthJarJar66.dds"
s["@TheElusiveBread"] = "LibCustomIcons/icons/misc7/TheElusiveBread.dds"
a["@TheElusiveBread"] = {"LibCustomIcons/icons/misc7/TheElusiveBread_anim.dds", 9, 2, 9}
s["@M.Berlingot"] = "LibCustomIcons/icons/misc7/MBerlingot.dds"
s["@Painkileuse"] = "LibCustomIcons/icons/misc7/Painkileuse.dds"
a["@Kethmac420"] = {"LibCustomIcons/icons/misc7/Kethmac420_anim.dds", 7, 5, 12}
a["@DeathMac420"] = {"LibCustomIcons/icons/misc7/DeathMac420_anim.dds", 4, 2, 6}
a["@Kolakses"] = {"LibCustomIcons/icons/misc7/Kolakses_anim.dds", 7, 3, 15}
s["@Eredthelion"] = "LibCustomIcons/icons/misc7/Eredthelion.dds"
a["@supershdow"] = {"LibCustomIcons/icons/misc7/shadow.dds", 7, 3, 12}
s["@LadyDesire"] = "LibCustomIcons/icons/misc7/LadyYousha.dds"
s["@LadyYousha"] = s["@LadyDesire"]
a["@PartialEthos"] = {"LibCustomIcons/icons/misc7/PartialEthos_anim.dds", 24, 1, 20}
a["@Scartha_Morin"] = {"LibCustomIcons/icons/misc7/scartha.dds", 5, 10, 10}
s["@SandyDog"] = "LibCustomIcons/icons/misc7/sandy_dog.dds"
s["@Bear-TheGodKing"] = "LibCustomIcons/icons/misc7/Bear-TheGodKing.dds"
a["@Ap_pA"] = {"LibCustomIcons/icons/misc7/Ap_pA.dds", 6, 1, 6}
s["@Lord_Asteroth"] = "LibCustomIcons/icons/misc7/Lord_Asteroth_2.dds"
s["@JustStoned420"] = "LibCustomIcons/icons/misc7/JustStoned420.dds"
a["@jobru"] = {"LibCustomIcons/icons/misc7/jobru_anim.dds", 10, 5, 20}
s["@Kethmac420"] = "LibCustomIcons/icons/misc7/Kethmac420.dds"
s["@DeathMac420"] = "LibCustomIcons/icons/misc7/DeathMac420.dds"
s["@Stellare"] = "LibCustomIcons/icons/misc7/Stellare.dds"
a["@Stellare"] = {"LibCustomIcons/icons/misc7/Stellare_anim.dds", 6, 10, 8}
a["@Liftwithyaback"] = {"LibCustomIcons/icons/misc7/Liftwithyaback_anim.dds", 6, 2, 15}
s["@Liftwithyaback"] = "LibCustomIcons/icons/misc7/Liftwithyaback.dds"
s["@RandomUser123"] = "LibCustomIcons/icons/misc7/RandomUser123.dds"
a["@RandomUser123"] = {"LibCustomIcons/icons/misc7/RandomUser123_anim.dds", 6, 8, 5}
s["@Cragborne"] = "LibCustomIcons/icons/misc7/Cragborne.dds"
s["@Dan_Prime"] = "LibCustomIcons/icons/misc7/Dan_Prime.dds"
a["@Dan_Prime"] = {"LibCustomIcons/icons/misc7/Dan_Prime_anim.dds", 10, 5, 10}
s["@spinostern"] = "LibCustomIcons/icons/misc7/spino.dds"
s["@brainsnorkel"] = "LibCustomIcons/icons/misc7/brainsnorkel.dds"
a["@stephnie"] = {"LibCustomIcons/icons/misc7/stephnie_anim.dds", 5, 10, 16}
s["@CaptainBuche"] = "LibCustomIcons/icons/misc7/CaptainBuche.dds"
s["@liminal.exe"] = "LibCustomIcons/icons/misc7/liminalexe.dds"
s["@pink.exe"] = "LibCustomIcons/icons/misc7/PinkPinkPinkPink.dds"
s["@creepp"] = "LibCustomIcons/icons/misc7/creepp.dds"
a["@ppflyet"] = {"LibCustomIcons/icons/misc7/ppflyet_anim.dds", 5, 4, 33}
s["@Adam_P"] = "LibCustomIcons/icons/misc7/Adam_P.dds"
s["@diduka"] = "LibCustomIcons/icons/misc7/diduka.dds"
a["@diduka"] = {"LibCustomIcons/icons/misc7/diduka_anim.dds", 19, 2, 24}
s["@HighstoneUA"] = "LibCustomIcons/icons/misc7/HighstoneUA.dds"
a["@JanosikHarnas"] = {"LibCustomIcons/icons/misc7/JanosikHarnas_anim.dds", 9, 1, 9}
a["@Heretic617"] = {"LibCustomIcons/icons/misc7/Heretic617_anim.dds", 31, 1, 12.5}
a["@Ophaniel741"] = {"LibCustomIcons/icons/misc7/Ophaniel741_anim.dds", 47, 1, 30}
a["@cn.rd"] = {"LibCustomIcons/icons/misc7/cnrd_anim.dds", 10, 3, 30}
s["@Mia1119"] = "LibCustomIcons/icons/misc7/Mia1119.dds"
s["@HßP"] = "LibCustomIcons/icons/misc7/hbp_2.dds"
s["@Dovhesi"] = "LibCustomIcons/icons/misc7/Dovhesi.dds"
a["@Simondu0"] = {"LibCustomIcons/icons/misc7/Simondu0_anim.dds", 6, 2, 13}
s["@DJ_M1n3r"] = "LibCustomIcons/icons/misc7/DJ_M1n3r.dds"
s["@melviniuspants"] = "LibCustomIcons/icons/misc7/melvinius.dds"
s["@superduperbeans"] = "LibCustomIcons/icons/misc7/superduperbeans.dds"
s["@Perseus001"] = "LibCustomIcons/icons/misc7/Perseus001.dds"
s["@Snow-Moon"] = "LibCustomIcons/icons/misc7/Snow-Moon.dds"
s["@GockPK"] = "LibCustomIcons/icons/misc7/GockPK.dds"
s["@PlayerFinity"] = "LibCustomIcons/icons/misc7/PlayerFinity.dds"
s["@Darkpown"] = "LibCustomIcons/icons/misc7/Darkpown.dds"
s["@Valkinaz"] = "LibCustomIcons/icons/misc7/valkinaz.dds"
s["@latteZZ"] = "LibCustomIcons/icons/misc7/latteZZ.dds"
a["@Diocliate"] = {"LibCustomIcons/icons/misc7/Diocliate_anim.dds", 5, 3, 23}
s["@gianlux96"] = "LibCustomIcons/icons/misc7/gianlux96_2.dds"
--a["@gianlux96"] = {"LibCustomIcons/icons/misc7/gianlux96_anim.dds", 22, 1, 22}
s["@Grim_Loki"] = "LibCustomIcons/icons/misc7/Grim_Loki.dds"
s["@DoNotAnnoyMe"] = "LibCustomIcons/icons/misc7/DoNotAnnoyMe.dds"
s["@Neurospider"] = "LibCustomIcons/icons/misc7/Neurospider.dds"
s["@Upari"] = "LibCustomIcons/icons/misc7/Upari.dds"
s["@Fitspatrik"] = "LibCustomIcons/icons/misc7/Fitspatrik.dds"
s["@Springey"] = "LibCustomIcons/icons/misc7/Springey.dds"
a["@kabellay"] = {"LibCustomIcons/icons/misc7/kabellay_anim.dds", 6, 1, 10}
s["@Riidgy"] = "LibCustomIcons/icons/misc7/Riidgy.dds"
s["@iamwezo"] = "LibCustomIcons/icons/misc7/iamwezo.dds"
s["@yy00"] = "LibCustomIcons/icons/misc7/yy00.dds"
s["@Splandonge"] = "LibCustomIcons/icons/misc7/siinnd.dds"
