-- SPDX-FileCopyrightText: 2025 m00nyONE
-- SPDX-License-Identifier: Artistic-2.0

local lib_name = "LibCustomIcons"
local lib = _G[lib_name]
local s = lib.GetStaticTable()
local a = lib.GetAnimatedTable()

s["@SanchoPansa"] = "LibCustomIcons/icons/moo/SanchoPansa.dds"
s["@Green165"] = "LibCustomIcons/icons/moo/green165.dds"
s["@Kuhpilot"] = "LibCustomIcons/icons/moo/Kuhpilot.dds"
s["@JN_Slevin"] = "/esoui/art/tutorial/progression_tabicon_dragonaspect_up.dds"
s["@SevenSinsGER"] = "LibCustomIcons/icons/moo/SevenSinsGER.dds"
s["@Romulus1969"] = "LibCustomIcons/icons/moo/Romulus1969.dds"
s["@Bluxx"] = "LibCustomIcons/icons/moo/Bluxx1.dds"
s["@Magiermädchen"] = "LibCustomIcons/icons/moo/Magiermaedchen3.dds"
s["@Magiermaedchen"] = s["@Magiermädchen"]
s["@PowerfulLevi"] = "LibCustomIcons/icons/moo/PowerfulLevi.dds"
s["@xpleader"] = "LibCustomIcons/icons/moo/xpleader.dds"
s["@m00nyONE"] = "LibCustomIcons/icons/moo/m00nyONE.dds"
s["@seadotarley"] = "LibCustomIcons/icons/moo/seadotarley.dds"
s["@H3NN3N4P"] = "LibCustomIcons/icons/moo/H3NN3N4P.dds"
s["@Lord-Grummel"] = "LibCustomIcons/icons/moo/Lord-Grummel.dds"
s["@Lady-Grummel"] = s["@Lord-Grummel"]
s["@High.Quality"] = "LibCustomIcons/icons/moo/HighQuality.dds"
s["@DaMoPa"] = "LibCustomIcons/icons/moo/DaMoPa.dds"
s["@lolemenator"] = "LibCustomIcons/icons/moo/lolemenator.dds"
s["@Dom3"] = "LibCustomIcons/icons/moo/Dom3.dds"
s["@Rodler03"] = "LibCustomIcons/icons/moo/Rodler03.dds"
s["@No4Sniper2k3"] = "LibCustomIcons/icons/moo/No4Sniper2k3.dds"
s["@FrecherZwerg"] = "LibCustomIcons/icons/moo/FrecherZwerg.dds"
s["@LotusBlut"] = "LibCustomIcons/icons/moo/LotusBlut.dds"
s["@KloppDichSchlau"] = "LibCustomIcons/icons/moo/KloppDichSchlau.dds"
s["@Kyra527"] = "LibCustomIcons/icons/moo/kyra527.dds"
s["@Artaphernes"] = "LibCustomIcons/icons/moo/Artaphernes.dds"
s["@sushiman573"] = "LibCustomIcons/icons/moo/sushiman573.dds"
s["@skinnycheeks"] = "LibCustomIcons/icons/moo/skinnycheeks.dds"
s["@Kirikina"] = "LibCustomIcons/icons/moo/Kirikina.dds"
s["@namos1337"] = "LibCustomIcons/icons/moo/namos1337.dds"
s["@Connor180"] = "LibCustomIcons/icons/moo/Connor180.dds"
s["@BloodStainChild666"] = "LibCustomIcons/icons/moo/BloodStainChild666.dds"
s["@ASSA-Zz"] = "LibCustomIcons/icons/moo/ASSA-Zz.dds"
s["@sir_fabs"] = "LibCustomIcons/icons/moo/sir_fabs.dds"
s["@Lord_Drad"] = "LibCustomIcons/icons/moo/Lord_Drad.dds"
s["@SandroKilltDich"] = "LibCustomIcons/icons/moo/sandrokilltdich.dds"
s["@ExoY94"] = "LibCustomIcons/icons/moo/ExoY94.dds"
s["@Bombarde"] = "LibCustomIcons/icons/moo/Bombarde_3.dds"
s["@Einhorn23"] = "LibCustomIcons/icons/moo/Einhorn23.dds"
s["@Survivor2012"] = "LibCustomIcons/icons/moo/Survivor2012.dds"
s["@Hunterial"] = "LibCustomIcons/icons/moo/Hunterial.dds"
s["@Ryvendur"] = "LibCustomIcons/icons/moo/Ryvendur.dds"
s["@Eco_212"] = "LibCustomIcons/icons/moo/Eco_212.dds"
s["@Mobitor"] = "LibCustomIcons/icons/moo/Mobitor.dds"
a["@Im5HEAD"] = {"LibCustomIcons/icons/moo/Im5HEAD_anim2.dds", 17, 2, 10}
s["@User7Gaming"] = "LibCustomIcons/icons/moo/User7Gaming.dds"
s["@Protossyder"] = "LibCustomIcons/icons/moo/Protossyder.dds"
s["@Regenbogenman"] = "esoui/art/icons/ability_templar_recovery.dds"
s["@NovaPixel"] = "LibCustomIcons/icons/moo/NovaPixel.dds"
a["@m00nyONE"] = {"LibCustomIcons/icons/moo/m00nyONE_anim.dds", 6, 4, 12}
a["@seadotarley"] = {"LibCustomIcons/icons/moo/seadotarley_anim.dds", 6, 1, 6}
a["@doIo"] = {"LibCustomIcons/icons/moo/doIo_anim.dds", 16, 1, 17}
a["@H3NN3N4P"] = {"LibCustomIcons/icons/moo/H3NN3N4P_anim.dds", 10, 3, 33}
a["@High.Quality"] = {"LibCustomIcons/icons/moo/HighQuality_anim.dds", 10, 5, 20}
a["@SanchoPansa"] = {"LibCustomIcons/icons/moo/SanchoPansa_anim.dds", 11, 1, 6}
a["@DaMoPa"] = {"LibCustomIcons/icons/moo/DaMoPa_anim.dds", 6, 3, 6}
a["@lolemenator"] = {"LibCustomIcons/icons/moo/lolemenator_anim.dds", 7, 4, 13}
a["@Dom3"] = {"LibCustomIcons/icons/moo/Dom3_anim.dds", 7, 3, 9}
a["@Rodler03"] = {"LibCustomIcons/icons/moo/Rodler03_anim.dds", 5, 4, 20}
a["@No4Sniper2k3"] = {"LibCustomIcons/icons/moo/No4Sniper2k3_anim.dds", 7, 2, 5}
a["@Reisser696"] = {"LibCustomIcons/icons/moo/Reisser696_anim.dds", 11, 1, 10}
a["@FrecherZwerg"] = {"LibCustomIcons/icons/moo/FrecherZwerg_anim.dds", 13, 2, 13}
a["@LotusBlut"] = {"LibCustomIcons/icons/moo/LotusBlut_anim.dds", 3, 2, 3}
a["@KloppDichSchlau"] = {"LibCustomIcons/icons/moo/KloppDichSchlau_anim.dds", 8, 6, 28}
a["@Kyra527"] = {"LibCustomIcons/icons/moo/Kyra527_anim.dds", 13, 2, 20}
a["@Artaphernes"] = {"LibCustomIcons/icons/moo/Artaphernes_anim.dds", 6, 5, 12.5}
a["@Natolia"] = {"LibCustomIcons/icons/moo/Natolia_anim.dds", 8, 1, 10}
a["@Kirikina"] = {"LibCustomIcons/icons/moo/Kirikina_anim.dds", 5, 5, 13}
a["@Connor180"] = {"LibCustomIcons/icons/moo/Connor180_anim2.dds", 10, 1, 10}
a["@FlaPi"] = {"LibCustomIcons/icons/moo/FlaPi_anim.dds", 8, 1, 10}
a["@ASSA-Zz"] = {"LibCustomIcons/icons/moo/ASSA-Zz_anim.dds", 10, 1, 5}
s["@TimistGOTT"] = "LibCustomIcons/icons/moo/TimistGOTT.dds"
a["@TimistGOTT"] = {"LibCustomIcons/icons/moo/TimistGOTT_anim.dds", 10, 6, 33}
a["@GrungE81"] = {"LibCustomIcons/icons/moo/grunge_anim.dds", 15, 1, 25}
a["@SandroKilltDich"] = {"LibCustomIcons/icons/moo/sandrokilltdich_anim.dds", 30, 1, 10}
a["@snowiii"] = {"LibCustomIcons/icons/moo/snowiii_anim.dds", 6, 4, 17}
s["@snowiii"] = "LibCustomIcons/icons/moo/snowiii.dds"
a["@Einhorn23"] = {"LibCustomIcons/icons/moo/Einhorn23_anim.dds", 23, 5, 25}
--a["@Eco_212"] = {"LibCustomIcons/icons/moo/Eco_212_anim.dds", 23, 2, 23}
a["@NikG1"] = {"LibCustomIcons/icons/moo/NikG1_anim.dds", 10, 5, 16}
--a["@Drachilo"] = {"LibCustomIcons/icons/moo/Drachilo_anim.dds", 12, 4, 12}
s["@Drachilo"] = "LibCustomIcons/icons/moo/Drachilo_2.dds"
s["@Dolgubon"] = "LibCustomIcons/icons/moo/Dolgubon.dds"
a["@Ermsi"] = {"LibCustomIcons/icons/moo/Ermsi_anim.dds", 14, 1, 20}
a["@RayRegiCide"] = {"LibCustomIcons/icons/moo/RayRegiCide_anim.dds", 9, 4, 11}
a["@schm00nel"] = a["@m00nyONE"]
s["@schm00nel"] = s["@m00nyONE"]
a["@C.arley"] = a["@seadotarley"]
s["@C.arley"] = s["@seadotarley"]
a["@DrakeX4 "] = a["@SandroKilltDich"]
s["@DrakeX4 "] = s["@SandroKilltDich"]
--a["@Eco.212"] = a["@Eco_212"]
s["@Eco.212"] = s["@Eco_212"]
a["@Ermsi2"] = a["@Ermsi"]
s["@YungGunz"] = "LibCustomIcons/icons/moo/YungGunz.dds"
s["@Fjior"] = "LibCustomIcons/icons/moo/Fjior.dds"
s["@Rappy_R50"] = "LibCustomIcons/icons/moo/Rappy_R50.dds"
s["@MedicateMe"] = "LibCustomIcons/icons/moo/MedicateMe.dds"
