VEQ.mylanguage = {
    -- Menu
    ["lang_quests_category_view_settings"] = "Einstellungen Kategoriezonenaufgaben",
    ["lang_class_show_zone"] = "Zone in der Klassen-Kategorie-Zonenansicht anzeigen",
    ["lang_class_show_zone_tip"] = "Wenn Sie die Kategoriezonenansicht verwenden, zeigen Sie die Zone der Klassenaufgabe an",
    ["lang_craft_show_zone"] = "Zone in der Zonenansicht der Handwerkskategorie anzeigen",
    ["lang_craft_show_zone_tip"] = "Bei Verwendung der Kategoriezonenansicht die Zone der Handwerksaufgaben anzeigen",
    ["lang_Group_show_zone"] = "Wenn Sie die Kategoriezonenansicht verwenden, zeigen Sie die Zone der Handwerksquests an",
    ["lang_Group_show_zone_tip"] = "Wenn Sie die Kategoriezonenansicht verwenden, zeigen Sie die Zone der Gruppenquests an",
    ["lang_Dungeon_show_zone"] = "Zone in Dungeon-Kategorie-Zonenansicht anzeigen",
    ["lang_Dungeon_show_zone_tip"] = "Wenn Sie die Kategorie-Zonen-Ansicht verwenden, zeigen Sie die Zone der Dungeon-Quests an",
    ["lang_Raid_show_zone"] = "Zone in der Zonenansicht der Raid-Kategorie anzeigen",
    ["lang_Raid_show_zone_tip"] = "Wenn Sie die Kategoriezonenansicht verwenden, zeigen Sie die Zone der Raid-Quests an",
    ["lang_HideOptObjective"] = "Optionale Ziele ausblenden",
    ["lang_HideOptObjective_tip"] = "Optionale Ziele ausblenden",
    ["lang_HideOptionalInfo"] = "Optionale Informationen ausblenden",
    ["lang_HideOptionalInfo_tip"] = "Optionale Informationen ausblenden",
    ["lang_HideHintsOption"] = "Hinweise ausblenden",
    ["lang_HideHintsOption_tip"] = "Hinweise der Aufgabe ausblenden",
    ["lang_HideHiddenOptions"] = "Versteckte Aufgaben-Hinweise ausblenden",
    ["lang_HideHiddenOptions_tip"] = "Versteckte Aufgaben-Hinweise ausblenden.",
    ["lang_HintColor"] = "Farbe der Aufgaben-Hinweise",
    ["lang_HintColor_tip"] = "Farbe der Aufgaben-Hinweise",
    ["lang_HintCompleteColor"] = "Farbe der erledigten Aufgaben-Hinweise",
    ["lang_HintCompleteColor_tip"] = "Farbe der erledigten Aufgaben-Hinweise.",
    ["lang_HideInCombat"] = "Verstecke Aufgaben\195\188bersicht im Kampf",
    ["lang_HideInCombat_tip"] = "Verstecke Aufgaben\195\188bersicht im Kampf",
    ["lang_QuestObjIcon"] = "Zeige Aufgabensymbole",
    ["lang_QuestObjIcon_tip"] = "Aufgabensymbole anstelle von Textsymbolen anzeigen.",
    ["lang_HideObjOption"] = "Ziele f\195\188r alle Quests ausblenden AUSSER",
    ["lang_HideObjOption_tip"] = "Option zum Ausblenden aller Ziele mit Ausnahme der drei Optionen. Deaktiviert ignoriert diese Option, Fokussierte Quest w\195\188rde alle Ziele ausser der fokussierten Quest ausblenden, Fokussierte Zone blendet alle Ziele ausser der Zone aus, in der sich die fokussierte Quest befindet.",
    ["lang_Miscellaneous"] = "Verschiedenes",
    ["lang_Toggle_AutoHide_off"] = "Zone/Kategorie automatisch ausblenden auf AUS gesetzt",
    ["lang_Toggle_AutoHide_on"] = "Zone/Kategorie automatisch ausblenden auf AN gesetzt",
    ["lang_Collaspe_All_Zones"] = "Alle Zonen/Kategorien einklappen",
    ["lang_Expand_All_Zones"] = "Alle Zonen/Kategorien ausklappen",
    ["lang_Toggle_Category_off"] = "Wechsel zur Zonenansicht",
    ["lang_Toggle_Category_on"] = "Wechsel zur Kategorieansicht",
    ["lang_Toggle_NotFocusTrans_on"] = "Nicht fokussierte Transparenz ist auf EIN eingestellt",
    ["lang_Toggle_NotFocusTrans_off"] = "Nicht fokussierte Transparenz ist auf AUS eingestellt",
    ["lang_Toggle_HintsHidden_on"] = "Nicht fokussierte Transparenz ist auf EIN eingestellt",
    ["lang_Toggle_HintsHidden_off"] = "Nicht fokussierte Transparenz ist auf AUS eingestellt",
    ["lang_Toggle_HideObjOption_Disabled"] = "Ziele f\195\188r alle Aufgaben aktiviert",
    ["lang_Toggle_HideObjOption_FocusedQuest"] = "Ziele nur f\195\188r fokussierte Aufgabe aktiviert",
    ["lang_Toggle_HideObjOption_FocusedZone"] = "Ziele nur f\195\188r fokussierte Zonenaufgabe aktiviert",
    
    ["lang_Chat_AddonMessages"] = "Aktiviere Chatnachrichten f\195\188r dieses Addon",
    ["lang_Chat_AddonMessages_tip"] = "Aktiviere Chatnachrichten, Nachrichten vom Addon z.B. \195\132nderung Tastaturbelegung, Fehler etc. auftreten",
    ["lang_Chat_QuestInfo"] = "Aktiviere Chatnachrichten f\195\188r die Aufgabeninformationen",
    ["lang_Chat_QuestInfo_tip"] = "Aktiviere Chatnachrichten f\195\188r die Aufgabeninformationen",
    ["lang_chat_settings"] = "Chat Einstellungen",
    ["lang_Chat_AddonMessage_HeaderColor"] = "Farbe der \195\156berschrift f\195\188r die Addon Nachrichten",
    ["lang_Chat_AddonMessage_HeaderColor_tip"] = "Stelle die Farbe f\195\188r die \195\156berschrift der Addonnachrichten ein.",
    ["lang_Chat_AddonMessage_MsgColor"] = "Addon Nachrichten Farbe",
    ["lang_Chat_AddonMessage_MsgColor_tip"] = "Stelle die Farbe f\195\188r die Addonnachrichten ein.",
    ["lang_Chat_QuestInfo_HeaderColor"] = "Farbe der \195\156berschrift f\195\188r die Aufgabeninformationen ",
    ["lang_Chat_QuestInfo_HeaderColor_tip"] = "Stelle die Farbe f\195\188r die \195\156berschrift der Addonnachrichten ein.",
    ["lang_Chat_QuestInfo_MsgColor"] = "Farbe f\195\188r die Aufgabeninformationen",
    ["lang_Chat_QuestInfo_MsgColor_tip"] = "Stelle die Farbe f\195\188r die Aufgabeninformationen ein.",
    
    ["lang_quests_timer_settings"] = "Einstellungen f\195\188r Aufgabencountdown",
    ["lang_quests_timer_settings_Tip"] = "Aktiviere/Deaktiviere den Aufgabencountdown und stelle Schrift und Farbe ein.",
    ["lang_veq_settings"] = "Vestige's Epic Quest",
    ["lang_global_settings"] = "Globale Einstellungen",
    
    ["lang_language_settings"] = "Sprache",
    ["lang_preset_settings"] = "Voreinstellung",
    ["lang_quests_filtered_settings"] = "Zeige Typ der Aufgabe",
    ["lang_overall_transparency"] = "Allgemeine Transparenz",
    ["lang_overall_width"] = "Gesamtbreite",
    ["lang_position_lock"] = "Hintergrundposition fixieren",
    ["lang_backgroundcolor_opt"] = "Hintergrundfarbe verwenden",
    ["lang_backgroundcolor_value"] = "Hintergrundfarbe",
    ["lang_intelligent_background"] = "Intelligenter Hintergrund",
	["lang_intelligent_background_tip"] = "Der intelligente Hintergrund wird ausgeblendet, wenn Sie sich bewegen oder kämpfen, und eingeblendet, wenn dies nicht der Fall ist",

    ["lang_mouse_settings"] = "Einstellungen f\195\188r die Maussteuerung",
    ["lang_mouse_1"] = "Linke Maustaste",
    ["lang_mouse_2"] = "Mittlere Maustaste",
    ["lang_mouse_3"] = "Rechte Maustaste",
    ["lang_mouse_4"] = "Maustaste 4",
    ["lang_mouse_5"] = "Maustaste 5",

    ["lang_timer_title_font"] = "Schrift Aufgabencountdown",
    ["lang_timer_title_font_tip"] = "Schriftart f\195\188r Aufgabencountdown, die bei fokussierter Aufgabe angezeigt wird, welche einen Countdown hat.",
    ["lang_timer_title_style"] = "Schriftstil Aufgabencountdown",
    ["lang_timer_title_style_tip"] = "Schriftstil f\195\188r Aufgabencountdown, die bei fokussierter Aufgabe angezeigt wird, welche einen Countdown hat.",
    ["lang_timer_title_size"] = "Schriftgr\195\182\195\159e Aufgabencountdown",
    ["lang_timer_title_size_tip"] = "Schriftgr\195\182\195\159e f\195\188r Aufgabencountdown, die bei fokussierter Aufgabe angezeigt wird, welche einen Countdown hat.",
    ["lang_timer_title_color"] = "Schriftfarbe Aufgabencountdown",
    ["lang_timer_title_color_tip"] = "Schriftfarbe f\195\188r Aufgabencountdown, die bei fokussierter Aufgabe angezeigt wird, welche einen Countdown hat.",
    
    ["lang_area_settings"] = "Einstellungen f\195\188r Questgebiete",
    ["lang_area_name"] = "Gebietsnamen anzeigen",
    ["lang_area_font"] = "Schriftart des Gebietsnamens",
    ["lang_area_style"] = "Schriftstil des Gebietsnamens",
    ["lang_area_size"] = "Schriftgr\195\182\195\159e des Gebietsnamens",
    ["lang_area_padding"] = "Seitenabstand des Gebietsnamens",
    ["lang_area_color"] = "Schriftfarbe des Gebietsnamens",
    ["lang_autohidequestzone_option"] = "Gebiet automatisch verbergen",
    ["lang_questzone_option"] = "Nur Aufgaben im aktuellen Gebiet",
    ["lang_quests_guild"] = "Gildenaufgaben anzeigen",
    ["lang_quests_mainstory"] = "Haupthandlungsaufgaben anzeigen",
    ["lang_quests_cyrodiil"] = "Aufgaben in Cyrodiil anzeigen",

    ["lang_quests_class"] = "Zeige Klassenaufgaben",
    ["lang_quests_class_tip"] = "Schaltet die Sichtbarkeit von Klassenaufgaben um.",
    ["lang_quests_crafting"] = "Zeige Handwerksaufgaben",
    ["lang_quests_crafting_tip"] = "Schaltet die Sichtbarkeit von Handwerksaufgaben um.",
    ["lang_quests_group"] = "Zeige Gruppenaufgaben",
    ["lang_quests_group_tip"] = "Schaltet die Sichtbarkeit von Gruppenaufgaben um.",
    ["lang_quests_dungeon"] = "Zeige Verliesaufgaben",
    ["lang_quests_dungeon_tip"] = "Schaltet die Sichtbarkeit von Verliesaufgaben um.",
    ["lang_quests_raid"] = "Zeige Pr\195\188fungsaufgaben",
    ["lang_quests_raid_tip"] = "Schaltet die Sichtbarkeit von Pr\195\188fungsaufgaben um.",
    ["lang_quests_AVA"] = "Zeige AVA Aufgaben",
    ["lang_quests_AVA_tip"] = "Schaltet die Sichtbarkeit von AVA Aufgaben um.",
    ["lang_quests_event"] = "Zeige Eventaufgaben",
    ["lang_quests_event_tip"] = "Schaltet die Sichtbarkeit von Eventaufgaben um.",
    ["lang_quests_BG"] = "Zeige Schlachtfeldaufgaben",
    ["lang_quests_BG_tip"] = "Schaltet die Sichtbarkeit von Schlachtfeldaufgaben um.",
    ["lang_area_hybrid"] = "Kategoriezonenansicht anzeigen",
    ["lang_area_hybrid_tip"] = "Zonen in der klassischen Kategorieansicht anzeigen, z. B. Gildenaufgaben, die in einer eigenen Kategorie aufgef\195\188hrt sind und nicht in der aktuellen Zone ist.",

    ["lang_no_trans_focused_zone"] = "Transparenz der fokussierten Aufgabe",
    ["lang_no_trans_focused_zone_tip"] = "Die Zone oder Kategorie, in der sich die fokussierte Aufgabe befindet, verwendet nicht die Transparenzeinstellung.",
    
    ["lang_quests_settings"] = "Einstellungen f\195\188r Aufgaben",
    ["lang_quests_sort"] = "Aufgaben sortieren nach...",
    ["lang_quests_nb"] = "Angezeigte Aufgaben für dieselbe Zone",
    ["lang_quests_show_timer"] = "Aufgabencountdown anzeigen",
    ["lang_quests_show_timer_tip"] = "Aufgabencountdown f\195\188r die fokussierte Quest anzeigen, wenn es einen Abschluss-Timer gibt",

    ["lang_quests_hide_obj"] = "Ziele/Hinweise der aktiven Aufgabe ausblenden",
    ["lang_quests_hide_obj_tip"] = "Blendet die Questziele und Hinweise von allen Quests aus, ausser von der fokussierten Quest.",
    
    ["lang_quests_hide_obj_optional"] = "Erledigte Hinweise und  Ziele ausblenden",
    ["lang_quests_hide_obj_optional_tip"] = "Blendet die optionalen Aufgaben aller Aufgaben EIN oder AUS.",
    
  	["lang_quests_hide_immersive_text"] = "Atmosphärischen Text ausblenden",
  	["lang_quests_hide_immersive_text_tip"] = "Den atmosphärischen Text des Tagebuchs ausblenden.",
    
    ["lang_quests_level"] = "Zeige Aufgabenlevel",
    ["lang_quests_optinfos"] = "Optionale, versteckte Hinweise",
    ["lang_quests_autoshare"] = "Aufgaben automatisch teilen",
    ["lang_quests_autountrack"] = "Abgew\195\164hlte Aufgaben ausblenden",
    ["lang_icon_opt"] = "Aktive Aufgabe mit Symbol markieren",
    ["lang_icon_texture"] = "Symboltextur",
    ["lang_icon_size"] = "Symbolgr\195\182\195\159e",
    ["lang_icon_color"] = "Symbolfarbe",
    ["lang_quests_transparency_opt"] = "Nicht aktive Aufgaben transparent",
    ["lang_quests_transparency"] = "Transparenz nicht aktiver Aufgaben",

    ["lang_titles_settings"] = "Einstellungen f\195\188r Aufgabennamen",
    ["lang_titles_font"] = "Schrift des Namens",
    ["lang_titles_style"] = "Schriftstil des Namens",
    ["lang_titles_size"] = "Schriftgr\195\182\195\159e des Namens",
    ["lang_titles_padding"] = "Seitenabstand des Namens",
    ["lang_titles_default"] = "Default Farbe des Namens",
    ["lang_titles_custom"] = "Benutzerdefinierte Farbe",
    ["lang_titles_veasy"] = "Farbe f\195\188r sehr einfache Aufgaben",
    ["lang_titles_easy"] = "Farbe f\195\188r einfache Aufgaben",
    ["lang_titles_normal"] = "Farbe f\195\188r durchschnittliche Aufgaben",
    ["lang_titles_hard"] = "Farbe f\195\188r fordernde Aufgaben",
    ["lang_titles_vhard"] = "Farbe f\195\188r sehr schwere Aufgaben",

    ["lang_obj_settings"] = "Einstellungen f\195\188r Aufgabenziele",
    ["lang_obj_font"] = "Schriftart der Ziele",
    ["lang_obj_style"] = "Schriftstil der Ziele",
    ["lang_obj_size"] = "Schriftgr\195\182\195\159e der Ziele",
    ["lang_obj_padding"] = "Seitenabstand der Ziele",
    ["lang_obj_color"] = "Schriftfarbe der Ziele",
    ["lang_obj_ccolor"] = "Schriftfarbe f\195\188r abgeschlossene Ziele",
    ["lang_obj_optcolor"] = "Schriftfarbe f\195\188r optionale Ziele",
    ["lang_obj_optccolor"] = "Schriftfarbe f\195\188r opt. abgeschlossene Ziele",

    ["lang_infos_settings"] = "Einstellungen f\195\188r Hinweise",
    ["lang_infos_font"] = "Schriftart der Hinweise",
    ["lang_infos_style"] = "Schriftstil der Hinweise",
    ["lang_infos_size"] = "Schriftgr\195\182\195\159e der Hinweise",
    ["lang_infos_color"] = "Schriftfarbe der Hinweise",
    
    ["lang_NumbQuest_opt"] = "Zeige Anzahl der Aufgaben",
    ["lang_NumbQuest_opt_tip"] = "Zeige Anzahl der angenommenen Aufgaben und die Gesamtanzahl der Aufgaben",
    ["lang_ShowClock_opt"] = "Zeige Uhr",
    ["lang_ShowClock_opt_tip"] = "Zeige die Uhrzeit links oben \195\188ber der Aufgabe",
    ["lang_ShowTbutton_opt"] = "Zeige Tastaturbelegung Aufgaben",
    ["lang_ShowTbutton_opt_tip"] = "Zeige das Bild, welche Taste hinterlegt ist f\195\188r das wechseln der aktiven Aufgaben",
    ["lang_ShowMQbutton_opt"] = "Zeige Tastaturbelegung Nebenaufgaben",
    ["lang_ShowMQbutton_opt_tip"] = "Zeige das Bild, welche Taste hinterlegt ist f\195\188r das wechseln der aktiven Nebenaufgaben",
    
    -- Menu tips
    ["lang_language_settings_tip"] = "Festlegung der gew\195\188nschten Sprache",
    ["lang_preset_settings_tip"] = "Auswahl einer Voreinstellung",
    ["lang_overall_transparency_tip"] = "Bestimmt die allgemeine Anzeigetransparenz",
    ["lang_overall_width_tip"] = "Bestimmt die Fensterbreite",
    ["lang_position_lock_tip"] = "Freigeben oder verschieben der Fensterposition",
    ["lang_backgroundcolor_opt_tip"] = "Bestimmt ob eine Hintergrundfarbe angezeigt wird",
    ["lang_backgroundcolor_value_tip"] = "Bestimmt die Hintergrundfarbe",
    
    ["lang_mouse_1_tip"] = "Festlegung der ausgef\195\188hrte Aktion bei einem Linksklick",
    ["lang_mouse_2_tip"] = "Festlegung der ausgef\195\188hrte Aktion bei mittlerer Maustaste",
    ["lang_mouse_3_tip"] = "Festlegung der ausgef\195\188hrte Aktion bei einem Rechtsklick",
    ["lang_mouse_4_tip"] = "Festlegung der ausgef\195\188hrte Aktion bei Maustaste 4",
    ["lang_mouse_5_tip"] = "Festlegung der ausgef\195\188hrte Aktion bei Maustaste 5",
    
    ["lang_area_name_tip"] = "Bestimmt ob Gebietsnamen angezeigt werden",
    ["lang_area_font_tip"] = "Bestimmt die Schriftart des Gebietsnamens",
    ["lang_area_style_tip"] = "Bestimmt den Schriftstil des Gebietsnamens",
    ["lang_area_size_tip"] = "Bestimmt die Schriftgr\195\182\195\159e des Gebietsnamens",
    ["lang_area_padding_tip"] = "Bestimmt den linken und rechten Seitenabstand des Gebietsnamens",
    ["lang_area_color_tip"] = "Bestimmt die Schriftfarbe des Gebietsnamens",
    ["lang_autohidequestzone_option_tip"] = "Bestimmt ob die Gebiete der nicht aktiven Aufgaben ausgeblendet werden sollen",
    ["lang_questzone_option_tip"] = "Bestimmt ob nur Aufgaben des derzeitigen Gebiets angezeigt werden",
    ["lang_quests_guild_tip"] = "Bestimmt ob Gildenaufgaben angezeigt werden",
    ["lang_quests_mainstory_tip"] = "Bestimmt ob Aufgaben der Haupthandlung angezeigt werden",
    ["lang_quests_cyrodiil_tip"] = "Bestimmt ob Aufgaben in Cyrodiil angezeigt werden",

    ["lang_quests_sort_tip"] = "Bestimmt die Reihenfolge der angezeigten Aufgaben",
    ["lang_quests_nb_tip"] = "Ändern Sie die Anzahl der Aufgaben, die für dieselbe Zone wie die fokussierte Aufgabe angezeigt werden",
    ["lang_quests_show_quest_timer_tip"] = "Zeigt den Countdown falls die Aufgabe eine Zeitvorgabe hat",
    ["lang_quests_level_tip"] = "Bestimmt ob die Stufen der jeweiligen Aufgaben angezeigt werden",
    ["lang_quests_optinfos_tip"] = "Bestimmt ob verborgene Hinweise der jeweiligen Aufgaben angezeigt werden",
    ["lang_quests_autoshare_tip"] = "Bestimmt ob Aufgaben in einer Gruppe automatisch geteilt werden",
    ["lang_quests_autountrack_tip"] = "Bestimmt ob nicht angezeigte Aufgaben auch in der Kompassanzeige verborgen werden",
    ["lang_icon_opt_tip"] = "Bestimmt ob ein Symbol an der derzeit aktiven Aufgabe angezeigt wird",
    ["lang_icon_texture_tip"] = "Bestimmt welches Symbol angezeigt wird",
    ["lang_icon_size_tip"] = "Bestimmt die Symbolgr\195\182\195\159e",
    ["lang_icon_color_tip"] = "Bestimmt die Symbolfarbe",
    ["lang_quests_transparency_opt_tip"] = "Bestimmt ob angezeigte, nicht aktive Aufgaben transparenter dargestellt werden",
    ["lang_quests_transparency_tip"] = "Bestimmt die Transparenz angezeigter, nicht aktiver Aufgaben",

    ["lang_titles_font_tip"] = "Bestimmt die Schriftart der \195\156berschriften",
    ["lang_titles_style_tip"] = "Bestimmt den Schriftstil der \195\156berschriften",
    ["lang_titles_size_tip"] = "Bestimmt die Schriftgr\195\182\195\159e der \195\156berschriften",
    ["lang_titles_padding_tip"] = "Bestimmt den linken und rechten Seitenabstand der \195\156berschriften",
    ["lang_titles_default_tip"] = "Bestimmt die Schriftfarbe der \195\156berschriften",
    ["lang_titles_custom_tip"] = "Bestimmt ob die \195\156berschriften nach ihrer Schwierigkeit, ausgehend von der Spielerstufe, eingef\195\164rbt werden",
    ["lang_titles_veasy_tip"] = "Bestimmt die Schriftfarbe f\195\188r Aufgaben\195\188berschriften, mehr als 4 Stufen darunter",
    ["lang_titles_easy_tip"] = "Bestimmt die Schriftfarbe f\195\188r Aufgaben\195\188berschriften, mindestens zwei Stufen darunter",
    ["lang_titles_normal_tip"] = "Bestimmt die Schriftfarbe f\195\188r Aufgaben\195\188berschriften, eine Stufe darunter oder dar\195\188ber",
    ["lang_titles_hard_tip"] = "Bestimmt die Schriftfarbe f\195\188r Aufgaben\195\188berschriften, mindestens zwei Stufen dar\195\188ber",
    ["lang_titles_vhard_tip"] = "Bestimmt die Schriftfarbe f\195\188r Aufgaben\195\188berschriften, mehr als vier Stufen dar\195\188ber",    
    
    ["lang_obj_font_tip"] = "Bestimmt die Schriftart der Aufgabenziele",
    ["lang_obj_style_tip"] = "Bestimmt den Schriftstil der Aufgabenziele",
    ["lang_obj_size_tip"] = "Bestimmt die Schriftgr\195\182\195\159e der Aufgabenziele",
    ["lang_obj_padding_tip"] = "Bestimmt den linken und rechten Seitenabstand der Aufgabenziele",
    ["lang_obj_color_tip"] = "Bestimmt die Schriftfarbe der Aufgabenziele",
    ["lang_obj_ccolor_tip"] = "Bestimmt die Schriftfarbe abgeschlossener Aufgabenziele",
    ["lang_obj_optcolor_tip"] = "Bestimmt die Schriftfarbe optionaler Aufgabenziele",
    ["lang_obj_optccolor_tip"] = "Bestimmt die Schriftfarbe abgeschlossener optionaler Aufgabenziele",

    ["lang_infos_opt_tip"] = "Bestimmt ob die Gesamtzahl der derzeitigen Aufgaben angezeigt wird",
    ["lang_infos_font_tip"] = "Bestimmt die Schriftart der Hinweise",
    ["lang_infos_style_tip"] = "Bestimmt den Schriftstil der Hinweise",
    ["lang_infos_size_tip"] = "Bestimmt die Schriftgr\195\182\195\159e der Hinweise",
    ["lang_infos_color_tip"] = "Bestimmt die Schriftfarbe der Hinweise",
    
    -- Menu Warn
    ["lang_menu_warn_1"] = "|c8B1E1E Diese \195\132nderung l\195\164d das UI neu",
    ["lang_menu_warn_2"] = "|c8B1E1E Diese \195\132nderung l\195\164d das UI neu und \195\188berschreibt die bisherigen Einstellungen.",

    -- Mouse Interactions
    ["lang_mouse_ctrl_assisted"] = "Ausgew\195\164hlte Aufgabe wechseln",
    ["lang_mouse_ctrl_filterzone"] = "Filtern nach aktuellem Gebiet",
    ["lang_mouse_ctrl_share"] = "Teile Aufgabe",
    ["lang_mouse_ctrl_showmap"] = "Zeige auf der Karte",
    ["lang_mouse_ctrl_remove"] = "Aufgabe abbrechen",
    
    -- Console
    ["lang_console_autoshare"] = "Ihr teilt eine Aufgabe automatisch",
    ["lang_console_share"] = "Ihr teilt eine Aufgabe",
    ["lang_console_noshare"] = "Diese Aufgabe kann nicht geteilt werden",
    ["lang_console_abandon"] = "Aufgabe abbrechen",
    ["lang_choose"] = "Ausw\195\164hlen: ",

----------------------------------- NEW STUFF

    ["lang_tmp_VEQMessage"] = "<<1>>: <<2>>",
    ["lang_tmp_VEQMessage_Error"] = "FEHLER <<1>>: <<2>>",

    -- Quests Infos
    ["quest_optional"] = "Optional",
    ["quest_hint"] = "Hinweis",    
    ["quest_hiddenhint"] = "Versteckter Hinweis",
    
    ["lang_tracker_type_guild"] = "Gilde",
    ["lang_tracker_type_mainstory"] = "Haupthandlung",
    ["lang_tracker_type_undaunted"] = "Unerschrockenen",
    ["lang_tracker_type_prologue"] = "Prolog",    
    ["lang_tracker_type_companion"] = "Begleiter",
    ["lang_tracker_type_repeatable"] = "Wiederholbar",
    ["lang_tracker_type_daily"] = "Täglich",
    ["lang_tracker_type_dungeon"] = "Verlies",
    ["lang_tracker_type_solo"] = "Solo",
    ["lang_tracker_type_class"] = "Klasse",
    ["lang_tracker_type_craft"] = "Handwerk",
    ["lang_tracker_type_group"] = "Gruppe",
    ["lang_tracker_type_ava"] = "Allianzkrieg",
    ["lang_tracker_type_arena"] = "Arena",
    ["lang_tracker_type_holiday_event"] = "Event",
    ["lang_tracker_type_raid"] = "Pr\195\188fung",
    ["lang_tracker_type_bg"] = "Schlachtfeld",
    ["lang_tracker_type_qa_test"] = "Pr\195\188fung",
    ["lang_tracker_type_dark_brotherhood"] = "Dunkle Bruderschaft",
    ["lang_tracker_type_thieves_guild"] = "Diebesgilde",
    ["lang_tracker_type_mages_guild"] = "Magiergilde",
    ["lang_tracker_type_fighters_guild"] = "Kriegergilde",
    ["lang_tracker_type_psijic_order"] = "Psijik-Orden",
    
    -- Inventory
    ["lang_slots_inventory"] = " verbleibende Pl\195\164tze im Inventar",
    ["lang_slot_inventory"] = " verbleibende Pl\195\164tze im Inventar",
    ["lang_free_space"] = "Platz schaffen",
    ["lang_inventory_full"] = "Inventar ist voll!",
    
    -- Treasure
    ["lang_survey_map"] = "Fundbericht",
    ["lang_treasure_map"] = "Schatzkarte",
    ["lang_get_materials"] = "Hol Dir das Material",
    ["lang_get_treasure"] = "Hol Dir die Truhe",
    
    -- Skyshards
    ["lang_skyshard"] = "Himmelsscherbe",
    ["lang_maway"] = "m entfernt",
    ["lang_distant_sky"] = "Unmerkliche \195\164therische Magicka-Pr\195\164senz",
    ["lang_weak_sky"] = "Schwache \195\164therische Magicka-Pr\195\164senz",
    ["lang_moderate_sky"] = "M\195\164\195\159ige \195\164therische Magicka-Pr\195\164senz",
    ["lang_strong_sky"] = "Starke \195\164therische Magicka-Pr\195\164senz",
    ["lang_huge_sky"] = "Riesige \195\164therische Magicka-Pr\195\164senz",
    
    -- Leads / antiquities
    ["lang_scry_exc"] = "Sp\195\164hen und Ausgraben in ",
    ["lang_antiquity_"] = "Antiquit\195\164t - ",
    
    -- Doable writs
    ["lang_check_inv"] = "\195\156berpr\195\188fe dein Inventar, um mit dem Herstellen zu beginnen",
    ["lang_doable"] = "Machbar ",
    ["lang_or"] = " oder ",
    
    -- Riding skills
    ["lang_stable_rel"] = "Eine stabile Beziehung",
    ["lang_upgrade_skills"] = "Verbessere eine deiner Reitf\195\164higkeiten",    
    ["lang_stablemaster"] = "Stallmeister",
    
    -- Backpack & Bank upgrade
    ["lang_backpack_upgrade"] = "Rucksack Upgrade",
    ["lang_you_have_the"] = "Du hast ",
    ["lang_up_back"] = "g! Vergr\195\182\195\159ere deinen Rucksack",
    ["lang_pack_merchant"] = "Gep\195\164ckh\195\164ndler",
    ["lang_bank_space_upgrade"] = "Bankplatz Upgrade",
    ["lang_up_bank"] = "g! Vergr\195\182\195\159ere deine Bankpl\195\164tze ",
    ["lang_bank_mon"] = "Bankier",
    
    
    -- Event Tickets & transmute crystals
    ["lang_event_tickets"] = "Ereignisscheine",
    ["lang_transmute_crystals"] ="Transmutationskristalle",
    ["lang_maxed_out_currency"] = "Du hast die max. Anzahl erreicht! Verbrauche welche.",
    ["lang_nears_max_currency"] = "Du hast fast das Maximum erreicht, Verbauche welche.",
    
    -- LFG & ready check
    ["lang_in"] = " in ",
    ["lang_champion_battleground"] = "CP Schlachtfeld",
    ["lang_low_battleground"] = "Niedriges Level Schlachtfeld",
    ["lang_non_battleground"] = "Kein CP Schlachtfeld",
	["lang_normal_dungeon_finder"] = GetString(SI_DUNGEONDIFFICULTY1).." Verliessuche",
	["lang_veteran_dungeon_finder"] = GetString(SI_DUNGEONDIFFICULTY2).." Verliessuche",
    ["lang_tribute_casual"] = "Ungewertete Ruhmesgeschichte",
    ["lang_tribute_competitive"] = "Gewertete Ruhmesgeschichte",
    ["lang_lfg"] = "Suche nach Gruppe...",
    ["lang_lfo"] = "Gegner wird gesucht...",
    ["lang_everybody_ready"] = "Ist jeder bereit?",
    ["lang_ready"] = " bereit",
    ["lang_grc"] = "Bereitschaftscheck Gruppe",
    ["lang_for"] = " f\195\188r ",
	["lang_LFR"] = "Ersatz gesucht",
    
    -- Entering campaign
    ["lang_cyrodiil"] = "Cyrodiil - ",
    ["lang_group"] = "Gruppe - ",
    ["lang_ewt"] = "\n• Verbleibende Wartezeit: ",
    ["lang_entering_campaign"] = "Betrete Kampagne...",
    ["lang_n_started"] = "\n• startet ",
    ["lang_ago"] = " vor",
    ["lang_confirming"] = "Best\195\164tigung",
    ["lang_finished"] = "Beendet", 
    ["lang_pending_accept"] = "Betreten...",
    ["lang_pending_join"] = "Beitritt ausstehend",
    ["lang_leaving_queue"] = "Warteschlange verlasen",
    ["lang_exiting_campaign"] = "Kampagne verlassen...",
    ["lang_waiting"] = "Warten",
    ["lang_n_queue_position"] = "\n• Position Warteschlange: ",
    
    -- Poison checker / equip / notifier    
    ["lang_out_of_poison"] = "Waffengift alle!",    
    ["lang_craft_some_poison"] = "Stelle neues Waffengift her",
    ["lang_alchemy_station"] = "Alchemiestation",
    
    -- Psijic Time Breaches helper
    ["lang_psijic_time_breach"] = "Psijic-Zeitriss #",    
    ["lang_6172_helper_9"] = "Auf halbem Weg zwischen dem Augury Basin und Keelsplitter's Nest (gehen Sie vom Wegschrein von Ebon Stadmont nach Westen, springen Sie in den Teich und folgen Sie dem Bach, der Riss befindet sich am Fuße des Wasserfalls)",    
    ["lang_6172_helper_8"] = "Zwischen Keelsplitter's Nest und Rellenthil Abyssal Geyser, auf der winzigen Insel mit dem Baum (südlich vom Wegschrein von Ebon Stadmont)",
    ["lang_6172_helper_7"] = "In einer verfallenen Struktur westlich von Alinor, auf halbem Weg zwischen Welenkin Cove und Welenkin Abyssal Geyser (gehen Sie den Kopfsteinpflasterweg südlich vom Wegschrein von Cey-Tarn Keep hinunter, halten Sie sich an jeder Gabelung rechts, einschließlich der kaputten Brücke, die zur Struktur führt)",
    ["lang_6172_helper_6"] = "Innerhalb der Direnni Acropolis, hinter der Brücke (gehen Sie den Kopfsteinpflasterweg südöstlich vom Wegschrein von King's Haven Pass hinunter, halten Sie sich an der Gabelung links)",
    ["lang_6172_helper_5"] = "Unter dem Wasserfall westlich von Shimmerene (galoppieren Sie vom Wegschrein von Shimmerene nach Norden und springen Sie so weit wie möglich ins Wasser)",
    ["lang_6172_helper_4"] = "In den Ruinen auf dem Hügel, nördlich des Sees bei Archon's Grove, östlich von Keep of the Eleven Forces (gehen Sie südlich vom Wegschrein von Shimmerene)",
    ["lang_6172_helper_3"] = "In einem der Gehege in Sil-Var-Woad (gehen Sie südlich vom Wegschrein von Sil-Var-Woad, betreten Sie den Zoo, halten Sie sich an der Gabelung rechts, im Wassergehege)",
    ["lang_6172_helper_2"] = "Am Ostufer der Insel südöstlich von Sil-Var-Woad, südöstlich des Sil-Var-Woad Abyssal Geyser, in der Nähe der zwei nördlichsten winzigen Inseln",
    ["lang_6172_helper_1"] = "Südlich vom Wegschrein von Sunhold, westlich des Sunhold Abyssal Geyser",
    
    ["lang_6181_helper_9"] = "Auf einer Klippe mit Blick auf Deleyn's Mill, nördlich von Daenia Dolmen (gehen Sie vom Wegschrein von Baelborne Rock nach Süden, laufen Sie im Fluss unter der Brücke und gehen Sie dann nach Südosten, der Riss ist etwas weiter als die Malerstaffelei)",
    ["lang_6181_helper_8"] = "Zwischen den Wurzeln an der Nordseite des Beldama Wyrd-Baums (Wegschrein des Wyrd-Baums)",
    ["lang_6181_helper_7"] = "Auf einer Klippe an der Westseite der Burial Mounds (gehen Sie vom Wegschrein von Crosswych nach Südwesten bis zum riesigen Unkraut und gehen Sie dann nach Süd-Südost oben auf der Klippe)",
    ["lang_6181_helper_6"] = "Im südlichsten Teil eines Schiffswracks an der Westseite der Insel des Koeglin-Leuchtturms (gehen Sie vom Wegschrein von Bonesnap Ruins nach West-Südwesten)",
    ["lang_6181_helper_5"] = "Am Rande der höchsten Stufe der Cumberland Falls (gehen Sie vom Wegschrein von Wind Keep nach Westen, folgen Sie dem Fluss stromaufwärts zum Wasserfall und klettern Sie auf dessen Spitze)",
    ["lang_6181_helper_4"] = "Gleich westlich von Moonlit Maw (gehen Sie vom Wegschrein von Pariah Abbey nach Norden)",
    ["lang_6181_helper_3"] = "Am Rande einer Klippe nördlich von Salas En, nordöstlich von The Warrior, mit Blick auf die Rain Catcher Fields (gehen Sie vom Wegschrein von Morwha's Bounty nach Westen, klettern Sie hinauf, gehen Sie wieder nach Westen zum Rand der Klippe)",
    ["lang_6181_helper_2"] = "An einer Klippenwand westlich von Easterly Aerie (gehen Sie vom Wegschrein von Kulati Mines nach Westen, umrunden Sie den Felsen rechts, nehmen Sie die Brücke, gehen Sie links, um auf die höhere Plattform zu klettern)",
    ["lang_6181_helper_1"] = "Zwischen HoonDing's Watch und Ragnthar (gehen Sie vom Wegschrein von HoonDing's Watch nach Süden, klettern Sie links auf den Sand, wenn Sie können, und gehen Sie wieder nach Süden)",
    
    ["lang_6185_helper_9"] = "Zwischen den beiden südlichsten Lavaströmen auf der Westseite von Senie (gehen Sie vom Wegschrein von Senie nach Westen)",
    ["lang_6185_helper_8"] = "Auf einer winzigen Insel an der Spitze des Wasserfalls zwischen den Brothers of Strife und Armature's Upheaval (gehen Sie vom Wegschrein von Brothers of Strife nach Südwesten)",
    ["lang_6185_helper_7"] = "Auf dem Bergrücken über Vivec's Antlers zwischen dem Wegschrein von Sulfur Pools und Vivec's Antlers (gehen Sie vom Wegschrein von Sulfur Pools nach Osten)",
    ["lang_6185_helper_6"] = "Neben einem der größeren Dampfbecken in Wittestadr (gehen Sie vom Wegschrein von Wittestadr nach Nordosten, der Riss befindet sich genau am Wittestadr-Symbol auf der Karte)",
    ["lang_6185_helper_5"] = "Zwischen den beiden Wasserfällen flussaufwärts südwestlich von Darkwater Crossing, südöstlich der Karte von Fort Amol (gehen Sie vom Wegschrein von Fort Amol nach Südosten)",
    ["lang_6185_helper_4"] = "Im Fluss westlich der Brücke östlich von Cradlecrush, nordwestlich von Thane Jeggi's Drinking Hole (gehen Sie vom Wegschrein von Fort Morvunskar nach Südwesten und folgen Sie der Kopfsteinpflasterstraße, halten Sie sich an der Gabelung links, schauen Sie rechts an der Brücke)",
    ["lang_6185_helper_3"] = "Nordöstlich von Fort Greenwall, südwestlich der Troll Cave (gehen Sie durch Fort Greenwall nördlich vom Wegschrein von Riften und dann nach Nordosten)",
    ["lang_6185_helper_2"] = "Direkt außerhalb der Snapleg Cave (überqueren Sie die Brücke nördlich vom Wegschrein von Nimalten und folgen Sie dem Fluss zur Höhle)",
    ["lang_6185_helper_1"] = "Oben an den Stufen in der Nähe des Throat of the World, nordwestlich von Ivarstead (gehen Sie vom Wegschrein von Geirmund's Hall nach West-Südwest, überqueren Sie die Brücke und folgen Sie den zahlreichen Stufen)",    

    ["lang_6197_helper_adamantine"] = "Gehen Sie vom Wegschrein von Eastern Evermore nach Südwesten, nutzen Sie den Zeitriss im Pelin-Friedhof, folgen Sie der Psijic-Sicht, graben Sie das Stabteil aus",
    ["lang_6197_helper_orichalc"] = "Gehen Sie südwestlich vom Wegschrein von Leki's Blade, nutzen Sie den Zeitriss nördlich von Leki's Blade, folgen Sie der Psijic-Sicht, graben Sie das Stabteil aus",
    ["lang_6197_helper_crystal"] = "Gehen Sie nördlich vom Wegschrein von Hatching Pools, nutzen Sie den Zeitriss in den Hatching Pools (unter dem Großen Hist-Baum), folgen Sie der Psijic-Sicht, graben Sie das Stabteil aus",
    ["lang_6197_helper_walk"] = "Gehen Sie vom Wegschrein von Selfora nach Süden, nutzen Sie den Zeitriss in der Nähe der Fang Spires, folgen Sie der Psijic-Sicht, graben Sie das Stabteil aus",
    
    ["lang_6197_helper_pelin"] = "Stabfragment nahe dem Pelin-Friedhof",
    ["lang_6197_helper_leki"] = "Stabfragment nahe Leki's Blade",    
    ["lang_6197_helper_hist"] = "Stabfragment nahe dem Hist-Baum",
    ["lang_6197_helper_fang"] = "Stabfragment nahe den Fang Spires",    
    
    ["lang_6194_helper_9"] = "In einer verfallenen Struktur auf der Westseite des Ossuary of Telacar (gehen Sie vom Wegschrein von Ossuary nach Nord-Nordwest)",
    ["lang_6194_helper_8"] = "Im Baumstumpf von Gil-Var-Delle, westlich des Dolmens (gehen Sie vom Wegschrein von Gil-Var-Delle nach Süden)",
    ["lang_6194_helper_7"] = "In der höchsten Turmruine nördlich von Reman's Bluff (gehen Sie vom Wegschrein von Redfur Trading Post nach West-Südwesten)",
    ["lang_6194_helper_6"] = "Auf einer Landzunge nördlich des Maormer-Lagers (überqueren Sie die Brücke nord-nordwestlich vom Wegschrein von Moonhenge, folgen Sie der Kopfsteinpflasterstraße, gehen Sie geradeaus zum Rand der Klippe, wenn die Straße nach rechts abbiegt)",
    ["lang_6194_helper_5"] = "Nördlich von Fisherman's Rest (umrunden Sie den Berg von Westen her vom Wegschrein von Serpent's Grotto)",
    ["lang_6194_helper_4"] = "Innerhalb des Labyrinths, knapp nördlich des Zentrums (nehmen Sie die Brücke nördlich vom Wegschrein von Greenheart, gehen Sie geradeaus weiter, ohne der Straße zu folgen, folgen Sie ihr, wenn sie wieder unter Ihren Füßen ist, nehmen Sie den 1. Labyrinth-Eingang links, gehen Sie rechts an der 1. Gabelung und links an der 2.)",
    ["lang_6194_helper_3"] = "Unter einer Brücke südlich von Treehenge, westlich von Ragnthar (folgen Sie dem Pfad nördlich vom Wegschrein von Wilding Run, bis Sie die Brücke erreichen, springen Sie)",
    ["lang_6194_helper_2"] = "In der Mitte von Horseshoe Island (gehen Sie vom Wegschrein von Vulkwasten nach Norden)",
    ["lang_6194_helper_1"] = "Auf der Insel nordöstlich des Xylo River Basin Dolmens (gehen Sie vom Wegschrein von Abamath nach Norden)",

    ["lang_6190_helper_9"] = "Auf der Klippe südlich von Bthanual (folgen Sie der Straße östlich vom Wegschrein von Muth Gnaar Hills, überqueren Sie die Brücke, halten Sie sich an der Gabelung links, gehen Sie vor dem Bthanual-Eingang nach Süden)",
    ["lang_6190_helper_8"] = "Am Wasserfall nordöstlich von Darkshade Caverns (gehen Sie vom Wegschrein von Silent Mire nach Südwesten, klettern Sie auf den Felsen zur höheren Plattform)",
    ["lang_6190_helper_7"] = "In einem Pflanzgefäß in der Mitte des Schreins von Saint Veloth (folgen Sie der Straße nordwestlich vom Wegschrein von Eidolon's Hollow, halten Sie sich an der 1. Gabelung links und an der 2. rechts)",
    ["lang_6190_helper_6"] = "Auf einer winzigen Insel an den Wasserfällen nordöstlich der Triple Circle Mine (gehen Sie vom Wegschrein von Shad Astula nach Süden, schwimmen Sie, springen Sie den Wasserfall hinunter, schwimmen Sie)",
    ["lang_6190_helper_5"] = "Hinter den riesigen Toren von Malak's Maw (gehen Sie vom Wegschrein von West Narsis nach Westen und machen Sie eine komplette Runde im Uhrzeigersinn)",
    ["lang_6190_helper_4"] = "Unter den Wurzeln eines Baumes in der Südwestecke in Bogmother (gehen Sie vom Wegschrein von Bogmother nach Westen)",
    ["lang_6190_helper_3"] = "In einem Steinmaul im Westen von Hei-Halai, nahe dem Eingang zu den Ruinen von Mazzatun (folgen Sie der Straße nördlich vom Wegschrein von Stillrise; wenn Sie eine Turmruine links neben der Straße sehen, gehen Sie nach Nordwesten, folgen Sie dann dem Pfad links zum Steinmaul)",
    ["lang_6190_helper_2"] = "In einem kleinen Xanmeer nordwestlich des Venomous Fens Dolmens (gehen Sie vom Wegschrein von Loriasel nach Südosten)",
    ["lang_6190_helper_1"] = "Am Fuße des Hist-Baums in der Mitte von Percolating Mire (gehen Sie vom Wegschrein von Percolating Mire nach Nordosten)",
    
    ["lang_6198_helper_red"] = "Gehen Sie südlich vom Wegschrein von Brothers of Strife, nutzen Sie den Zeitriss, folgen Sie der Psijic-Sicht, graben Sie das Stabteil aus",
    ["lang_6198_helper_white"] = "Gehen Sie vom Wegschrein von Weeping Giant nach Nordwesten bis zur Turmruine, folgen Sie dann dem Pfad rechts, überqueren Sie die Plankenbrücke, nutzen Sie den Zeitriss, folgen Sie der Psijic-Sicht, graben Sie das Stabteil aus",
    ["lang_6198_helper_greensap"] = "Gehen Sie nördlich vom Wegschrein von Greenheart, nutzen Sie den Zeitriss, folgen Sie der Psijic-Sicht, graben Sie das Stabteil aus",
    ["lang_6198_helper_snow"] = "Gehen Sie vom Wegschrein von Spellscar nach Osten, zwischen der Felsenklippe und der Adament-Anomalie, am Ende der Felsenklippe biegen Sie links ab, nutzen Sie den Zeitriss, folgen Sie der Psijic-Sicht, graben Sie das Stabteil aus",

    ["lang_6198_helper_bro"] = "Stabfragment nahe den Brothers of Strife",
    ["lang_6198_helper_weep"] = "Stabfragment nahe dem Weeping Giant",    
    ["lang_6198_helper_green"] = "Stabfragment nahe Greenheart",
    ["lang_6198_helper_spell"] = "Stabfragment nahe Spellscar",    
    
    ["lang_6468_helper_9"] = "An der Wand westlich von Trader's Rest (gehen Sie vom Wegschrein von Oldgate nach Nordosten)",
    ["lang_6468_helper_8"] = "Bei Sanguine Barrows, zwischen dem zentralen Grab und der Tribulation Crypt (gehen Sie vom Wegschrein von Sanguine Barrows nach Norden)",
    ["lang_6468_helper_7"] = "Vor dem Nordturm bei Lorkrata Hills (gehen Sie vom Wegschrein von Fell's Run nach Westen, nehmen Sie innerhalb der Lorkrata Hills-Mauern die Treppe rechts)",
    ["lang_6468_helper_6"] = "In einem Feld bei Edrald Estate (gehen Sie vom Wegschrein von Fell's Run nach Ost-Südost)",
    ["lang_6468_helper_5"] = "Auf einer Insel westlich von East-Rock Landing, nördlich der Orc's Finger Ruins, südwestlich der Serpent (gehen Sie vom Wegschrein von Boralis nach Osten)",
    ["lang_6468_helper_4"] = "In der Kapitänskajüte von Lagra's Pearl (gehen Sie vom Wegschrein von Northpoint nach Nordosten)",
    ["lang_6468_helper_3"] = "Vor den Chapel Crypts bei Crestshade (folgen Sie der Kopfsteinpflasterstraße südlich vom Wegschrein von Crestshade, gehen Sie an der Statue nach Südwesten und die Treppe hinauf, die andere Treppe links, gehen Sie geradeaus weiter zur Treppe der Chapel Crypts)",
    ["lang_6468_helper_2"] = "Gleich westlich von Aesar's Web (gehen Sie westlich vom Wegschrein von Tamrith Camp)",
    ["lang_6468_helper_1"] = "Innerhalb der Shadowfate Cavern (der Eingang befindet sich zwischen Aesar's Web und dem Wegschrein von Tamrith Camp)",

    ["lang_6196_helper_6"] = "Nordöstlich von Ogondar's Winery, westlich von Rkundzelft (gehen Sie vom Wegschrein von Spellscar nach Osten, zwischen der Felsenklippe und der Adament-Anomalie, am Ende der Felsenklippe gehen Sie nach Südosten)",
    ["lang_6196_helper_5"] = "Außerhalb der Nordwestecke von Elinhir (gehen Sie vom Wegschrein von Elinhir nach Süden, umrunden Sie die Felsenklippe von Elinhir rechts, bis Sie den Riss finden)",
    ["lang_6196_helper_4"] = "In einer Spalte am südlichen Ende der Scorpion Ravine (gehen Sie vom Wegschrein von Seeker's Archive nach Südwesten)",
    ["lang_6196_helper_3"] = "Nördlich von Hel Ra Citadel, östlich von Mtharnaz (gehen Sie vom Wegschrein von Sandy Path nach Westen)",
    ["lang_6196_helper_2"] = "Vor der Dragonstar-Arena (Wegschrein von Dragonstar)",
    ["lang_6196_helper_1"] = "Auf der Brücke nach Skyreach Hold (Wegschrein von Skyreach)",
    
    ["lang_6199_helper"] = "Steigen Sie vom Wegschrein von Goat's Head Oasis die Treppe hinauf und gehen Sie dann nach Südwesten zur Mine Divad's Chagrin",
    
    -- Group frames
    ["lang_of"] = " von ",
    
    -- Museum Pieces
    ["lang_museum"] = "gesuchtes",

    -- Dailies counter
    ["lang_repeatable_quests"] = "Wiederholbare Aufgabe",
    ["lang_ongoing"] = "Laufend: ",
    ["lang_completed_today"] = "Heute erledigt: ",
	
	-- zone todo list
	["lang_todolist"] = "Zonen-To-Do-Liste",
	
	
	-- remains silent
	["lang_remains_silent"] = "<Sie nicken wissend.>",
	
	-- Dragonguard Supply chest name (change to your language for the feature to work)
	["lang_dragonguard_supply_chest"] = "Drachengarde-Versorgungstruhe",
    
    -- mini tracker settings
    ["lang_mini_quest_tracker_settings"] = "Einstellungen Nebenaufgaben",
	["lang_mini_quest_tracker_invert_opt"] = "Taste umkehren",
	["lang_mini_quest_tracker_invert_tip"] = "Vorherige Mini-Aufgabe statt der nächsten abrufen, indem Sie diese Taste lange drücken, während Sie die Standardtastaturbelegung drücken",
    ["lang_inventory_slots_opt"] = "Inventar voll",
    ["lang_inventory_slots_tip"] = "Zeigt an wenn dein Inventar voll ist oder das Minimum an eingestellter Pl\195\164tze erreicht ist",
    ["lang_inventory_slots_limit"] = "Freie Inventarpl\195\164tze ausl\195\182ser",
    ["lang_inventory_slots_limit_tip"] = "Anzhal der minimum freien Pl\195\164tze im Inventar",    
    ["lang_lost_treasure_opt"] = "Schaftzkarten",
    ["lang_lost_treasure_tip"] = "Zeigt an, welche  Schatzkarten Du finden kannst, welche sich im Inventar befinden (perfekt mit dem Addon Lost Treasure)",    
    ["lang_skyshards_opt"] = "Himmelsscherben",
    ["lang_skyshards_tip"] = "Zeigt Dir an ob eine Himmelsscherbe in weniger als 100m um Dich herum ist",    
    ["lang_leads_opt"] = "Antiquit\195\164t",
    ["lang_leads_tip"] = "Zeigt Dir an ob Du eine Spur ersp\195\164hen und ausgraben kannst",
	["lang_fake_leads_opt"] = "Spähen- und Ausgrabungsfortschritt",
	["lang_fake_leads_tip"] = "Fügt täglich eine Mini-Aufgabe hinzu, um ein Antiquität zu spähen und auszugraben, um einen reibungslosen Fortschritt dieser Fertigkeitslinien zu gewährleisten",
    ["lang_writs_opt"] = "Machbar Handwerksschriebe",
    ["lang_writs_tip"] = "Zeigt Dir an, ob Du ein machbaren Handwerksschrieb im Inventar hast. (Ben\195\182tigt das Addon WritWorthy)",
    ["lang_stable_opt"] = "Reitf\195\164higkeiten",
    ["lang_stable_tip"] = "Zeigt Dir an, ob Du dein Reittier verbessern kannst",    
    ["lang_backbank_opt"] = "Rucksack & Bankplatz",
    ["lang_backbank_tip"] = "Zwigt Dir an, ob Du dein Rucksack oder Bankplatz aufr\195\188sten kannst, sobald Du das erforderliche Gold hast",        
	["lang_TamrielTomes_opt"] = "Tamriel-Bücher-Mini-Aufgabe",
	["lang_TamrielTomes_tip"] = "Fügt Tamriel-Bücher als Mini-Aufgabe hinzu.",
	["lang_goldenPursuit_opt"] = "Goldene Verfolgung Mini-Aufgabe",
	["lang_goldenPursuit_tip"] = "Fügt jede Goldene Verfolgung als Mini-Aufgabe hinzu.",
["lang_displayTrackedGoldenPursuitOnly_opt"] = "Nur die verfolgte Goldene Verfolgung anzeigen",
	["lang_displayTrackedGoldenPursuitOnly_tip"] = "Zeigt nur die verfolgte Goldene Verfolgung an.",
	["lang_communityEvents_opt"] = "Community-Event-Mini-Aufgabe",
	["lang_communityEvents_tip"] = "Fügt jedes Community-Event als Mini-Aufgabe hinzu.",
    ["lang_tickets_opt"] = "Ereignisscheine",
    ["lang_tickets_tip"] = "Zeigt an wenn Du die max. Anzahl an Ereignisscheine hast oder den eingestellten Wert erreicht hast",    
    ["lang_tickets_limit"] = "Minimum an Ereignisscheine bevor Max.",
    ["lang_tickets_limit_tip"] = "Ab wann soll eine Meldung kommen, bevor Du das Max. erreicht hast",
    ["lang_transmute_opt"] = "Transmutationskristalle",
    ["lang_transmute_tip"] = "Zeigt an wenn Du die max. Anzahl an Transmutationskristalle hast oder den eingestellten Wert erreicht hast",    
    ["lang_transmute_limit"] = "Minimum an Transmutationskristalle bevor Max",
    ["lang_transmute_limit_tip"] = "Ab wann soll eine Meldung kommen, bevor Du das Max. erreicht hast",
    ["lang_zoneguide_opt"] = "Automatisch Aufgaben fokussieren",
    ["lang_zoneguide_tip"] = "Die Aufgaben werden automatisch aktiviert und werden zu einer Nebenaufgabe in VEQ, wenn die Zone ge\195\164ndert wird und wenn Sie keine aktive Quest in dieser Zone haben", 
    ["lang_POIcompletion_opt"] = "Unentdeckte Zonen-Sehenswürdigkeiten als Mini-Aufgabe festlegen",
	["lang_POIcompletion_tip"] = "Eine unentdeckte Zonen-Sehenswürdigkeit wird bei Zonenwechsel zu einer Mini-Aufgabe in VEQ",	
    ["lang_poison_opt"] = "Waffengiftprüfer",
    ["lang_poison_tip"] = "\195\156berpr\195\188ft nach jedem Kampf eure Waffengiftslots, wenn sie leer sind oder kein Gift mehr da ist, wird angezeigt das Du was Herstellen sollst",    
    ["lang_group_frames_opt"] = "'Begleiter & Gruppenmitgl.' Name als Lebensbalken",
    ["lang_group_frames_tip"] = "Zeigt die Namen der Gruppenmitglieder als farbige Lebensbalken an",
	["lang_default_group_frames_opt"] = "Standard-Gruppenrahmen des Spiels ausblenden",
	["lang_default_group_frames_tip"] = "Schalten Sie diesen Schalter um, falls ein Konflikt mit einem anderen Addon bezüglich der Anzeige der Standard-Gruppenrahmen vorliegt",
    ["lang_museum_pieces_opt"] = "Museumsst\195\188cke",
    ["lang_museum_pieces_tip"] = "Zeigt jedes Museumsst\195\188ck an, das in deinem Inventar ist und errinnert daran, das Du es ins Museum zur\195\188ckzubringst",
    ["lang_dailies_counter_opt"] = "Wiederholbare t\195\164gliche Aufgabenz\195\164hler",
    ["lang_dailies_counter_tip"] = "F\195\188gt einen Z\195\164hler hinzu, um die 50 wiederholbaren Quests pro Tag zu verfolgen",
	["lang_NumbMiniQuest_opt"] = "Anzahl der Mini-Aufgaben anzeigen",
	["lang_NumbMiniQuest_opt_tip"] = "Zeigt die Anzahl der Mini-Aufgaben an",
}