local ADDON_NAME  = "MemeSupportIcons"
local MY_TEXTURES = {
    "MemeSupportIcons/icons/frogok.dds",
    "MemeSupportIcons/icons/fine.dds",
    "MemeSupportIcons/icons/internetman.dds",
    "MemeSupportIcons/icons/beavshook.dds",
    "MemeSupportIcons/icons/beavsus.dds",
    "MemeSupportIcons/icons/brocco.dds",
    "MemeSupportIcons/icons/cry.dds",
    "MemeSupportIcons/icons/dolan.dds",
    "MemeSupportIcons/icons/ok.dds",
    "MemeSupportIcons/icons/okay.dds",
    "MemeSupportIcons/icons/spongebruh.dds",
    "MemeSupportIcons/icons/spongecave.dds",
    "MemeSupportIcons/icons/spongedress.dds",
    "MemeSupportIcons/icons/spongemock.dds",
    "MemeSupportIcons/icons/spongenormal.dds",
    "MemeSupportIcons/icons/spongewhat.dds",
    "MemeSupportIcons/icons/spongewhew.dds",
    "MemeSupportIcons/icons/patevil.dds",
    "MemeSupportIcons/icons/patkrusty.dds",
    "MemeSupportIcons/icons/patkrustyno.dds",
    "MemeSupportIcons/icons/pikaho.dds",
    "MemeSupportIcons/icons/poohwtf.dds",
    "MemeSupportIcons/icons/sweat.dds",
    "MemeSupportIcons/icons/rip.dds",
    "MemeSupportIcons/icons/shrok.dds",
    "MemeSupportIcons/icons/mike.dds",
    "MemeSupportIcons/icons/eggplant.dds",
    "MemeSupportIcons/icons/nootlikethis.dds",
    "MemeSupportIcons/icons/nobitches.dds",
    "MemeSupportIcons/icons/mrbubz.dds",
    "MemeSupportIcons/icons/wot.dds",
    "MemeSupportIcons/icons/batdad.dds",
    "MemeSupportIcons/icons/cruise.dds",
    "MemeSupportIcons/icons/drake.dds",
    "MemeSupportIcons/icons/gavin.dds",
    "MemeSupportIcons/icons/scream.dds",
    "MemeSupportIcons/icons/wesmart.dds",
    "MemeSupportIcons/icons/wow.dds",
    "MemeSupportIcons/icons/badass.dds",
    "MemeSupportIcons/icons/jackie.dds",
    "MemeSupportIcons/icons/toby.dds",
    "MemeSupportIcons/icons/ruserious.dds",
    "MemeSupportIcons/icons/rcbitchplease.dds",
    "MemeSupportIcons/icons/rc4evalone.dds",
    "MemeSupportIcons/icons/rchmm.dds",
    "MemeSupportIcons/icons/rcok.dds",
    "MemeSupportIcons/icons/rcrage.dds",
    "MemeSupportIcons/icons/wojaphim.dds",
    "MemeSupportIcons/icons/wojchad.dds",
    "MemeSupportIcons/icons/wojchubcry.dds",
    "MemeSupportIcons/icons/wojcry.dds",
    "MemeSupportIcons/icons/wojdespair.dds",
    "MemeSupportIcons/icons/wojdoom.dds",
    "MemeSupportIcons/icons/wojeboy.dds",
    "MemeSupportIcons/icons/wojegirl.dds",
    "MemeSupportIcons/icons/wojnobrain.dds",
    "MemeSupportIcons/icons/wojnpc.dds",
    "MemeSupportIcons/icons/wojsmirk.dds",
    "MemeSupportIcons/icons/wojsoy.dds",
    "MemeSupportIcons/icons/wojsoymask.dds",
    "MemeSupportIcons/icons/wojtradwife.dds",
    "MemeSupportIcons/icons/pepebat.dds",
    "MemeSupportIcons/icons/pepeclown.dds",
    "MemeSupportIcons/icons/pepecry.dds",
    "MemeSupportIcons/icons/pepecrylaugh.dds",
    "MemeSupportIcons/icons/pepefeelsgood.dds",
    "MemeSupportIcons/icons/pepegossip.dds",
    "MemeSupportIcons/icons/pepelove.dds",
    "MemeSupportIcons/icons/pepemadgamer.dds",
    "MemeSupportIcons/icons/pepeorly.dds",
    "MemeSupportIcons/icons/peperee.dds",
    "MemeSupportIcons/icons/peperree.dds",
    "MemeSupportIcons/icons/peperofl.dds",
    "MemeSupportIcons/icons/pepethink.dds",
    "MemeSupportIcons/icons/pepephone.dds",
    "MemeSupportIcons/icons/pepenote.dds",
    "MemeSupportIcons/icons/pepelook.dds",
    "MemeSupportIcons/icons/pepeknife.dds",
    "MemeSupportIcons/icons/pepepray.dds",
    "MemeSupportIcons/icons/pepethinkin.dds",
    "MemeSupportIcons/icons/pepewake.dds",
    "MemeSupportIcons/icons/emojiconcern.dds",
    "MemeSupportIcons/icons/emojiglass.dds",
    "MemeSupportIcons/icons/emojihot.dds",
    "MemeSupportIcons/icons/emojijojo.dds",
    "MemeSupportIcons/icons/emojiohhh.dds",
    "MemeSupportIcons/icons/emojishh.dds",
    "MemeSupportIcons/icons/emojisob.dds",
    "MemeSupportIcons/icons/emojiteef.dds",
    "MemeSupportIcons/icons/emojithonk.dds",
    "MemeSupportIcons/icons/emojithonkbutt.dds",
    "MemeSupportIcons/icons/emojiyikers.dds",
    "MemeSupportIcons/icons/emojiyikes.dds",
}
EVENT_MANAGER:RegisterForEvent( ADDON_NAME, EVENT_ADD_ON_LOADED, function( _, addonName )
    if addonName ~= ADDON_NAME then return end
    EVENT_MANAGER:UnregisterForEvent( ADDON_NAME, EVENT_ADD_ON_LOADED )
    -- check if OdySupportIcons is active and supports unique icon packs
    if OSI and OSI.AddCustomIconPack then
        -- add your list of icons
        OSI.AddCustomIconPack( MY_TEXTURES )
    end
end )