FurnishThemAllData_Store_LimitedFurnishingPacks = {
    name = "Limited Furnishing Packs",
    source = "Store",
    collection = {
        FurnishThemAllData_FPacks_ApocryphalCuriosities.collection[1],
        FurnishThemAllData_FPacks_AquaticSplendor.collection[1],
        FurnishThemAllData_FPacks_Ayleid.collection[1],
        FurnishThemAllData_FPacks_Azura.collection[1],
        FurnishThemAllData_FPacks_ChapelOfZenithar.collection[1],
        FurnishThemAllData_FPacks_ColdharbourArcanaeum.collection[1],
        FurnishThemAllData_FPacks_CombatTraining.collection[1],
        FurnishThemAllData_FPacks_CommunityTheater.collection[1],
        FurnishThemAllData_FPacks_DaedricAmbitions.collection[1],
        FurnishThemAllData_FPacks_DariensDelights.collection[1],
        FurnishThemAllData_FPacks_DeepmireExpedition.collection[1],
        FurnishThemAllData_FPacks_DibellasGarden.collection[1],
        FurnishThemAllData_FPacks_DruidicGatherings.collection[1],
        FurnishThemAllData_FPacks_DwarvenPipes.collection[1],
        FurnishThemAllData_FPacks_DwarvenTrainingDummies.collection[1],
        FurnishThemAllData_FPacks_EquipmentStations.collection[1],
        FurnishThemAllData_FPacks_FargraveBazaar.collection[1],
        FurnishThemAllData_FPacks_ForgeLordsGreatWorks.collection[1],
        FurnishThemAllData_FPacks_HauntedHousewares.collection[1],
        FurnishThemAllData_FPacks_HeartOfTheLoom.collection[1],
        FurnishThemAllData_FPacks_HeartsDayRetreat.collection[1],
        FurnishThemAllData_FPacks_HubalajadsFinalTreasure.collection[1],
        FurnishThemAllData_FPacks_JestersFestivalStagecraft.collection[1],
        FurnishThemAllData_FPacks_LordVivec.collection[1],
        FurnishThemAllData_FPacks_MadAlchemist.collection[1],
        FurnishThemAllData_FPacks_MalacathsChosen.collection[1],
        FurnishThemAllData_FPacks_MaormerBoardingParty.collection[1],
        FurnishThemAllData_FPacks_MolagBal.collection[1],
        FurnishThemAllData_FPacks_MoonBishopsSanctuary.collection[1],
        FurnishThemAllData_FPacks_MoonlitPathways.collection[1],
        FurnishThemAllData_FPacks_MoonsBlessedOasis.collection[1],
        FurnishThemAllData_FPacks_NecromGarden.collection[1],
        FurnishThemAllData_FPacks_NewLifeFestival.collection[1],
        FurnishThemAllData_FPacks_SanguinesFestival.collection[1],
        FurnishThemAllData_FPacks_ShadAstulaScholars.collection[1],
        FurnishThemAllData_FPacks_ShadowAndStone.collection[1],
        FurnishThemAllData_FPacks_SinisterHollowjackItems.collection[1],
        FurnishThemAllData_FPacks_SteamBathSerenity.collection[1],
        FurnishThemAllData_FPacks_TheClockworkGodsDomain.collection[1],
        FurnishThemAllData_FPacks_ToymakersTrove.collection[1],
        FurnishThemAllData_FPacks_TrappingsOfMephalaWorship.collection[1],
        FurnishThemAllData_FPacks_TyrantsOfTheMerethicEra.collection[1],
        FurnishThemAllData_FPacks_WaterDancerNereid.collection[1],
        FurnishThemAllData_FPacks_WintersFeast.collection[1],
        FurnishThemAllData_FPacks_WitchesCoven.collection[1],
        FurnishThemAllData_FPacks_WrithingFortress.collection[1],

        FurnishThemAllData_FSets_CraglornMulticulturalKitchenPack.collection[1],

        FurnishThemAllData_FSets_IslandAssortmentHouseholdPack.collection[1],
        FurnishThemAllData_FSets_IslandCuisineKitchenPack.collection[1],
        FurnishThemAllData_FSets_IslandHideawayParlorPack.collection[1],
        FurnishThemAllData_FSets_IslandNightsBedroomPack.collection[1],
    },
}
