
if not RTP then RTP = { } end
if not RTP.CONST then RTP.CONST = { } end

RTP.ADDON_NAME = "RolePlayTownPortals"
RTP.ADDON_TITLE = "Role-Play Town Portals"

RTP.CONST.DIALOG_CONFIRM = "RTPConfirm"
RTP.CONST.DIALOG_SELECT_DESTINATION = "RTPSelectDestination"
RTP.CONST.DIALOG_DUMMY = "RTPDummy"

RTP.CONST.INITIALIZE_LOCATIONS_ID = "RTPInitializeLocations"
RTP.CONST.CHECK_PORTALS_ID = "RTPCheckPortals"

RTP.CONST.MAP_PIN_TYPE = "RTPMapPinType"
RTP.CONST.COMPASS_PIN_TYPE = "RTPCompassPinType"