if not RTP then RTP = {} end

RTP.HouseMaps = {
	[8] = {id = 8, map = "greenshade_base"}, -- Cliffshade
	[14] = {id = 14, map = "greenshade_base"}, -- Bouldertree Refuge
	[16] = {id = 16, map = "glenumbra_base"}, -- Captain Margaux's Place
	[20] = {id = 20, map = "deshaan_base"}, -- Velothi Reverie
	[22] = {id = 22, map = "khenarthisroost_base"}, -- Moonmirth House
	[23] = {id = 23, map = "reapersmarch_base"}, -- Sleek Creek House
	[24] = {id = 24, map = "reapersmarch_base"}, -- Dawnshadow
	[26] = {id = 26, map = "craglorn_base"}, -- Domus Phrasticus
	[41] = {id = 41, map = "earthtearcavern_base"}, -- Earthtear Cavern
	[43] = {id = 43, map = "vvardenfell_base"}, -- Amaya Lake Lodge
	[44] = {id = 44, map = "vvardenfell_base"}, -- Ald Velothi Harbor House
	[46] = {id = 46, map = "goldcoast_base"}, -- Linchal Grand Manor
	[47] = {id = 47, map = "coldharbour_base"}, -- Coldharbour Surreal Estate
	[49] = {id = 49, map = "glenumbra_base"}, -- Exorcised Coven Cottage
	[54] = {id = 54, map = "wrothgar_base"}, -- Pariah's Pinnacle
	[55] = {id = 55, map = "clockwork_base"}, -- The Observatory Prior
	[60] = {id = 60, map = "colossalaldmerigrotto_base"}, -- Colossal Aldmeri Grotto
	[64] = {id = 64, map = "lakemirexanmer_base"}, -- Lakemire Xanmeer Manor
	[68] = {id = 68, map = "rimmen_base"}, -- Sugar Bowl Suite
	[70] = {id = 70, map = "rimmen_base"}, -- Hall of the Lunar Champion
	[71] = {id = 71, map = "moonsugarmeadow_base"}, -- Moonsugar Meadow
	[73] = {id = 73, map = "senchal_base"}, -- Lucky Cat Landing
	[74] = {id = 74, map = "pellitinemanorint.base"}, -- Potentate's Retreat
	[76] = {id = 76, map = "thievesoasisext_base"}, -- Thieves' Oasis
	[91] = {id = 91, map = "u31_housing_sweetwater"}, -- Sweetwater Cascades
	[98] = {id = 98, map = "u37_fogbreaklighthouse_ext"}, -- Fogbreak Lighthouse
	[101] = {id = 101, map = "null"}, -- Emissary's Enclave
	[104] = {id = 104, map = "u39_eventhouse_ext"}, -- Kelesan'ruhn
}
RTP.Towns ={
	{id = 1, name = "Felms Oad", startingLocation = 1},
	{id = 2, name = "Rawl'iit", startingLocation = 14},
	{id = 3, name = "Ouada Mora", startingLocation = 31},
}
RTP.Locations = {
	[1] = {id = 1, houseId = 98, owner = "@Zekell", townId = 1, name="Alna District", public = true, description="|u25:0::The|u beating heart of Felms Oad for visitors, traders and residents. "},
	[2] = {id = 2, houseId = 71, owner = "@Zekell", townId = 1, name="Shaln Mora", public = true},
	[3] = {id = 3, houseId = 20, owner = "@Zekell", townId = 1, name="Chamber of Justice", description="|u25:0::The|u Chamber of the local Ordinators of Felms Oad."},
	[4] = {id = 4, houseId = 60, owner = "@Zekell", townId = 1, name="Lan Grotto", public = true, description="|u25:0::The|u old town of Felms Oad, known as the Low or the Lan District. "},
	[5] = {id = 5, houseId = 43, owner = "@Zekell", townId = 1, name="Ruined Indoril Estate"},
	[6] = {id = 6, houseId = 8, owner = "@Zekell", townId = 1, name="Burdened Hall", description="|u25:0::Beneath|u the unfinished Tel taken by House Tavari lies the infirmary. A place of healing, experimentation, alchemy and medicine, run by the healers of House Tavari."},
	[7] = {id = 7, houseId = 46, owner = "@Zekell", townId = 1, name="Market District", public = true, description="|u25:0::The|u market and homestead promenade of Felms Oad. "},
	[8] = {id = 8, houseId = 20, owner = "@Reese1170", townId = 1, name="The Book Repository", description="|u25:0::The|u official library of Felms Oad."},
	[9] = {id = 9, houseId = 55, owner = "@Zekell", townId = 1, name="Sanctuary of Seht", description="|u25:0::A|u hidden sanctuary deep in the Shaln Mora of unknown origin. It is where Sotha Sil's shrine lies, and from where the people of Felms Oad feel he provides blessings from."},
	[10] = {id = 10, houseId = 101, owner = "@Zekell", townId = 1, name="The Ancestor Hall", description="|u25:0::The|u Ancestor Hall is a small but beautifully built location in the giant main stone of Felms Oad. It houses an intentionally unattended to dedication chamber. One where people can commit private rituals and commune with the dead with bother. It also contains the High Gardens. A place of respite and meditation. However you can also sometimes find mer training here as well. Lastly, it holds the Chamber of Preparation, where dead are burnt and placed into urns for mourners. "},
	[11] = {id = 11, houseId = 44, owner = "@random_highjinx", townId = 1, name="The Alchemist's Garden", public = true, description="|u25:0::The|u herb and apothecarial gardens of Felms Oad. "},
	[12] = {id = 12, houseId = 91, owner = "@Daniea", townId = 1, name="Tavari Council Manor"},
	[13] = {id = 13, houseId = 14, owner = "@Zekell", townId = 1, name="Darkden Cavern"},
	[14] = {id = 14, houseId = 71, owner = "@Thelazylizard", townId = 2, name="Rawl'iit Town Center", public = true, description="|u25:0::The|u Town Center of Rawl'iit may look like a bustling settlement, but it was only a few years ago that it was a crumbling ruin of an abandoned adeptorium. The ancient stones of Rawl'iit speak of storied battles, terrible tragedies, triumphs and ignominies, if one but knows how to listen! Underneath the watchful gaze of Jone's Claw Keep a walker arrives at the Caravanserai - an exotic market full of goods from near and far! Beyond that lies the courtyard, where travelers find services such as the tavern and inn, Rainsong Temple, the Sugar Den and the Bank."},
	[15] = {id = 15, houseId = 71, owner = "@TheGhesk", townId = 2, name="The Springlight Woods", public = true, description="|u25:0::Located|u beneath the cliffs of Rawl'iit are the Springlight Woods - a small section of dense tropical rainforests typical of the Tenmar Region. Within the forest are the gates to the old Imperial hamlet of Ruby Row and the entrance to the Ironfang Mines. Travelers beware, for within the deeper, darker sections of the forest lie the abandoned ruins of Old Rawl'iit - scarred and haunted since the Knahaten Flu tore through the area."},
	[16] = {id = 16, houseId = 47, owner = "@Thelazylizard", townId = 2, name="Jone's Claw Keep", public = true, description="|u25:0::Jone's|u Claw Keep is the oldest structure within the Town Center, with the original sections having been constructed shortly after the union of the Sixteen Kingdoms into Two. Shortly after this, the Imperials took claim of it and occupied it for almost a century. Jone's Claw Keep was later returned to the Khajiit adepts of Rain's Fall, who transformed it back into a magnificent Adeptorium. The Keep features a grand dining hall and the Market Council chambers, as well as the bathhouse."},
	[17] = {id = 17, houseId = 68, owner = "@Thelazylizard", townId = 2, name="Wagon's Rest Inn: Small Suite", description="|u25:0::The|u Sleepy Senche Inn features a pair of inn rooms available. For a mere ten gold (10g) a night a weary traveler can rest in a fine suite featuring a comfortable bed with linen changed weekly! (Daily linen changes available for an additional fee!)"},
	[18] = {id = 18, houseId = 22, owner = "@Thelazylizard", townId = 2, name="Wagon's Rest Inn: Deluxe Suite", description="|u25:0::The|u Deluxe Suite of the Sleepy Senche Inn, for those accustomed to a certain level of luxury for long term stays! A living room allows for comfortable private meetings, while the bedroom features a bath and the finest bed, with daily linen changes at no extra cost! Only twenty gold a night!"},
	[19] = {id = 19, houseId = 73, owner = "@Thelazylizard", townId = 2, name="Clan Father's Manor", description="|u25:0::This|u elegant manor is the home of the Caravan Father, Ra'jirroh, and Magistrate of the Town, Mathei. The House dates back to the days of the Potentates, and is one of the finest examples of Pellitine architecture in the region. No expense was spared in its construction, though the long years have left the manor in a state of faded luxury. Despite this the echoes of a once glorious age of gilded wealth still linger, as do the memories of the tragedy that happened here long ago. Visitors are requested to announce their presence before entering."},
	[20] = {id = 20, houseId = 16, owner = "@Thelazylizard", townId = 2, name="Ra'jirroh's Luxury Wagon", description="|u25:0::This|u massive wagon is the pinnacle of Baandari craftsmanship and luxury. It is an abomination that was stitched together from the salvaged remains of rival Baandari merchant's wagons, capable only of traveling on the most well maintained roads and requiring two Senche-Raht to pull. It exists solely to pad the ego of its owner, and make their rival Baandari envious."},
	[21] = {id = 21, houseId = 24, owner = "@Thelazylizard", townId = 2, name="Guard Lodge", public = true, description="|u25:0::Centuries|u ago, the Guard Lodge was the first of the great manor houses that was built within the Riverside district. Over thirty years ago, the manor - and the family that lived there - were burned down almost to the ground to stave off the Flu in the Riverside district. Heavy renovations have left it almost unrecognizable from what it was in those bygone golden years of the area."},
	[22] = {id = 22, houseId = 70, owner = "@Thelazylizard", townId = 2, name="Rainsong Temple", public = true, description="|u25:0::This|u majestic Khajiiti temple is dedicated to the goddess of the Wind, Khenarthi, who ferries Khajiit souls to the Sands beyond the Stars to await the Next Pounce. The temple features a system of vent-like wind catchers on the top of the building that channel the breeze down into the vestibule of the old Temple. In this way even when sheltered from the tropical rainstorms, believers can still feel Khenarthi's breath upon them."},
	[23] = {id = 23, houseId = 49, owner = "@Thelazylizard", townId = 2, name="The Jade Flask", description="|u25:0::Little|u but ruined walls and a tower remain of an old Imperial fort that was later commissioned as a prison. The ruins became a hideout for desperate rogues and bandits after the keep's abandonment, until the ghosts of the prisoners within stirred! After Rawl'iit was re-founded, the ghost infestation was cleared out by Lakjo and the Claws of Baan Dar. The ruins lay unused and forsaken by the local Khajiit until a pair of Argonians moved in and made it their home. Within the old keep they have built the Jade Flask - one of the areas finest alchemy stores!"},
	[24] = {id = 24, houseId = 74, owner = "@Thelazylizard", townId = 2, name="Moonshroud Arena", public = true, description="|u25:0::Beneath|u Rawl'iit are a network of catacombs, caves, aquafers and a great cistern that date as far back as the first foundations of the original structure! This ancient cistern, long disused and forgotten, has been rediscovered and transformed into an underground fighting pit for the town's entertainment!"},
	[25] = {id = 25, houseId = 54, owner = "@Thelazylizard", townId = 2, name="The Ironfang Mines", public = true, description="|u25:0::The|u Ironfang Mines are a set of old mines that were dug into the cliffs during the Imperial occupation of Fort Springmoth, after seams of iron were discovered within. The Imperials mined out several shafts until forced to stop when structural instability was discovered in the fortress walls above. Rumor has it the mines may connect to the sealed catacombs beneath Jone’s Claw Keep!"},
	[26] = {id = 26, houseId = 16, owner = "@Nuketastic2300", townId = 2, name="Ardun-Vylak's Home", description="|u25:0::This|u house was built by a Rim-Man family that fled from Cyrodiil during brutal reign of the Warlord Attrebus. Although it went to ruin during the Knahaten Flu, it has been lovingly restored by its newest owner, Ardun-Vylak."},
	[27] = {id = 27, houseId = 23, owner = "@lavascale133", townId = 2, name="Sandy Bear Smithy", description="|u25:0::This|u blacksmith shop in the Riverside district has recently been renovated and restored by Raliis."},
	[28] = {id = 28, houseId = 26, owner = "@JeffR110", townId = 2, name="The Brass Lion", description="|u25:0::For|u over thirty years the blacksmith in Ruby Row lay cold and crumbling, until Fadorian moved in. In short order the Khajiit Artificer had renovated that old forge with his own artifice, made in the style of the ancient Dwemercraft. Baandari who travel from far north often bring salvaged Dwemer scrap to sell to Fadorian."},
	[29] = {id = 29, houseId = 23, owner = "@Celtic_Cryptid", townId = 2, name="Kaihanna & Ko'ebony's Home", description="|u25:0::Owned|u by Kaihanna and Ko'ebony, this is an example of a number of newer Khajiiti styled structures built in Riverside."},
	[30] = {id = 30, houseId = 22, owner = "@TheGhesk", townId = 2, name="Magistrates Office"},
	[31] = {id = 31, houseId = 64, owner = "@FatherFortune", townId = 3, name="[HH] Ouada Mora", public = true, description="|u25:0::Home|u to House Hladren, a vassal house of Indoril. Built in the shadow of an ancient and abandoned Argonian xanmeer, the town survives on the back of its fishing industry. It's warm, humid, and rains often, but the people are happy, and no one goes hungry."},
	[32] = {id = 32, houseId = 41, owner = "@FatherFortune", townId = 3, name="[BMT] The Undercity", public = true, description="|u25:0::Once|u upon a time, a slaving town that might have grown to rival Tear sat beneath these hills, until an earthquake and mudslides brought it low. Now, just this fragment remains, safe underground. The Baan Maar Tong lives here now, along with escaped slaves and various flavors of ne'er-do-well who seek to escape the attention of the surface-dwellers. "},
	[33] = {id = 33, houseId = 71, owner = "@FatherFortune", townId = 3, name="[HH] Ouada Mora Outskirts", public = true, description="|u25:0::A|u patchwork of humble dwellings and modest homesteads."},
	[34] = {id = 34, houseId = 20, owner = "@FatherFortune", townId = 3, name="[HH] The House of Remedies", public = true, description="|u25:0::Within|u the House of Remedies, skilled menders and alchemists ply their craft to offer healing to the sick and weary."},
	[35] = {id = 35, houseId = 91, owner = "@FatherFortune", townId = 3, name="[HH] The Abbey of Threefold Mercies", public = true, description="|u25:0::Within|u its hallowed halls, the Abbey houses a treasure trove of saintly relics stored there by House Indoril. Pilgrims from far and wide journey to pay homage to these sacred artifacts, seeking divine intervention in their hour of need. It also serves as a sanctuary and orphanage, where children are raised up and cared for by the monks."},
	[36] = {id = 36, houseId = 70, owner = "@FatherFortune", townId = 3, name="[HH] The Hall of Justice", public = true, description="|u25:0::Once|u a Dres manor, but now it serves a more sacred purpose. The Hall of Justice serves as barracks, headquarters, and training grounds for Ouada Mora's Ordinators. In the basement, one can even find housing for the Ordination's... 'guests'."},
	[37] = {id = 37, houseId = 104, owner = "@FatherFortune", townId = 3, name="[HH] The Ghostwood", public = true, description="|u25:0::The|u air here is filled with the fragrance of flowers and the earthy scent of the loam. The wind whispers through the trees and catches whispers of prayer. At the heart of the Ghostwood stands the newly built family tomb of House Hladren. Its presence is an oath sworn that the House will endure. "},
	[38] = {id = 38, houseId = 76, owner = "@FatherFortune", townId = 3, name="[BMT] Boethiah's Run", public = true, description="|u25:0::Descend|u into the depths of Boethiah's Run, and drown in an exquisite sense of dread. The air here is heavy with the scent of sweat and iron. Boethiah's Eye - a vast sinkhole in the center of the main chamber - is eager to witness bloodshed."},
	[39] = {id = 39, houseId = 43, owner = "@DeadKingMars", townId = 3, name="[BMT] Twilight Teahouse", public = true, description="|u25:0::Built|u within the ever growing outskirts of Vivec City, the Twilight Teahouse is a uniquely curated tea ceremony experience for all types of socialites. Owned by renowned Curator Selevis Seren, the Teahouse services those looking for an escape from the hustle and bustle of the city with its colorful gardens and otherworldly beauty."},
}
RTP.Portals = {
	[1] = { -- Alna District
		{id = 0, location = 1, destinations = {2}, x = 100570, y = 20319, z = 101922, cx = 0.580846, cy = 0.747927, portalDescription = "|u25:0::This|u poorly lit cavern leads into the Shaln Mora, the ancient fungal forest of Felms Oad. Go a bit further and it can take you to the civilized Dun Plaza where the market, shops and several estates dwell on the edge of the isle. Know though, that the Shaln Mora is a sacred place. Touched by the Tribunal, Anticipations, ancient tombs and more under a canopy of leaves and fungi. If you run into trouble in the mora, those in town may not be able to rush to your aid. Continue at your own risk if you feel the spiritual reward outweighs it.", icon = "/esoui/art/icons/poi/poi_grove_complete.dds"},
		{id = 1, location = 1, destinations = {3}, x = 94474, y = 10800, z = 84276, cx = 0.43173, cy = 0.316197, portalDescription = "|u25:0::This|u door leads to the Chamber of Justice, a Dark Stone hall built into the island. It houses the offices of the Ordinators of Felms Oad, a small set of cells and a war room. However, this is not the chamber to commit crimes in. Stealing, assault or heresy in the Chamber could lead to being attacked on sight if caught by the local Ordinators. ", icon = "/RoleplayTownPortals/icons/door.dds"},
		{id = 2, location = 1, destinations = {4}, x = 102210, y = 19675, z = 78269, cx = 0.621061, cy = 0.169292, portalDescription = "|u25:0::This|u path leads down to The Grotto of Felms Oad. Otherwise known as The Village. It keeps the ships of House Tavari guarded at a port, serves as a home to some citizens in shacks and cavern homes, and also houses the well known Tendal's Tradehouse and Hall of Laborers and Artisans.", icon = "/esoui/art/icons/poi/poi_cave_complete.dds"},
		{id = 3, location = 1, destinations = {6}, x = 94090, y = 11250, z = 79769, cx = 0.422333, cy = 0.205915, radius = 5, portalDescription = "|u25:0::This|u door leads down to the dark depths of the tower, home of the Order of the Burdened. A place to purchase apothecarial and alchemical goods, as well as seek out healing for sickness or injury. But do be warned, those who lurk in this hall just to lurk may be asked to leave. That is unless you are of the Burdened. You can often find it's members working below under Ayem's healing hands. ", icon = "/RoleplayTownPortals/icons/door.dds"},
		{id = 4, location = 1, destinations = {10}, x = 99451, y = 21295, z = 86867, cx = 0.553483, cy = 0.37963, portalDescription = "|u25:0::The|u Ancestor Hall. This elegant building is built into the stone of Felms Oad, and serves as place to connect and communicate with the dead, as per ancient Dunmeri tradition. It also houses a fine overlook of the tower's port for those wanting privacy and relaxation high in the cliffs of the isle. ", icon = "/esoui/art/icons/poi/poi_crypt_complete.dds"},
		{id = 5, location = 1, destinations = {7}, x = 93277, y = 19378, z = 88293, cx = 0.402432, cy = 0.414456, portalDescription = "|u25:0::This|u gate leads out of the Alna District and to the Market District. A lime-and-volcanic-stone pit of shops and services. Including a promenade and other fascinating locales. It is often bustling with life as merchants shout out to potential customers and sailors roam in to unload goods from across Morrowind. You can also find some cave Manors here, held by distinct mer of the region. ", icon = "/esoui/art/icons/mapkey/mapkey_artifactgate_open.dds"},
		{id = 6, location = 1, destinations = {12}, x = 104591, y = 20060, z = 90514, cx = 0.679243, cy = 0.468767, portalDescription = "|u25:0::The|u stronghold door before you leads to the Tavari Council Manor. A place of summits, private conferences and dinners, as well as audience with members of the House Council.", icon = "/esoui/art/icons/poi/poi_estate_complete.dds"},
	},
	[2] = { -- Shaln Mora
		{id = 0, location = 2, destinations = {1}, x = 59165, y = 29521, z = 54675, cx = 0.32576, cy = 0.313665, portalDescription = "|u25:0::This|u cavern is poorly lit but it will get you back to the Alna District, the capital district of Felms Oad.", icon = "/esoui/art/icons/mapkey/mapkey_soloinstance.dds"},
		{id = 1, location = 2, destinations = {5}, x = 67428, y = 30470, z = 58431, cx = 0.508826, cy = 0.396862, portalDescription = "|u25:0::This|u door leads to a long abandoned and ruined Indoril Estate. Rumors say Argonian slaves broke free and killed the family who once lived here. Now it lies empty as a ruin and reminder. Few care to revisit the site. ", icon = "/esoui/art/icons/poi/poi_estate_complete.dds"},
		{id = 2, location = 2, destinations = {9}, x = 69483, y = 28896, z = 52544, cx = 0.55443, cy = 0.266427, portalDescription = "|u25:0::This|u strange lift lowers you into the hidden Sanctuary of Sotha Sil, protected by the Temple and made of dark Velothi stone and metallic trimmings. A place where the locals feel and know he provides his blessings from. Down below and with mystery is how the Wizard helps the Mother and Warrior-Poet guide the area and protect the faithful. It is said, when one stands before his shrine, the comforting, quiet rhythm of gears turn in hearts and minds.", icon = "/esoui/art/icons/mapkey/mapkey_temple.dds"},
		{id = 3, location = 2, destinations = {13}, x = 66508, y = 29135, z = 62125, cx = 0.488558, cy = 0.478751, portalDescription = "|u25:0::A|u strange cavern tucked in the Shaln Mora of the isle. The air inside is stale and cold. It's clear to those with a touch of magicka, or even common sense that something is not quite right inside.", icon = "/esoui/art/icons/poi/poi_cave_complete.dds"},
	},
	[3] = { -- Chamber of Justice
		{id = 0, location = 3, destinations = {1}, x = 52856, y = 9536, z = 45852, cx = 0.172344, cy = 0.558009, portalDescription = "|u25:0::This|u door leads back into the chapel of the Abbey of Saint Felms the Bold.", icon = "/esoui/art/icons/mapkey/mapkey_avatown.dds"},
	},
	[4] = { -- Lan Grotto
		{id = 0, location = 4, destinations = {1}, x = 86004, y = 10231, z = 72996, cx = 0.691821, cy = 0.425194, portalDescription = "|u25:0::This|u passageway leads back to the Alna District. The center and heart of Felms Oad where you can find the Tel, Abbey of Saint Felms, Excise Office and more. ", icon = "/esoui/art/icons/mapkey/mapkey_avatown.dds"},
		{id = 1, location = 4, destinations = {2}, x = 92479, y = 10031, z = 82245, cx = 0.823591, cy = 0.613407, portalDescription = "|u25:0::This|u dark cavern leads up to connect with another, guiding you to the Shaln Mora, the spiritual place of Felms Oad aside from The Abbey of Saint Felms. While the Shaln Mora is not regularly patrolled, within the forest you can find shrines to anticipations and God-Kings, tombs and many other secrets. It also is where one walks the Pilgrimage of Brothers Beraul. ", icon = "/esoui/art/icons/poi/poi_grove_complete.dds"},
	},
	[5] = { -- Ruined Indoril Estate
		{id = 0, location = 5, destinations = {2}, x = 50434, y = 12466, z = 51930, cx = 0.445943, cy = 0.762682, portalDescription = "|u25:0::The|u door back into the Shaln Mora and out of the old walled estate.", icon = "/esoui/art/icons/poi/poi_grove_complete.dds"},
	},
	[6] = { -- Burdened Hall
		{id = 0, location = 6, destinations = {1}, x = 24184, y = 20008, z = 22665, cx = 0.652075, cy = 0.582595, portalDescription = "|u25:0::This|u door leads back up to the main floor of the lighthouse.", icon = "/RoleplayTownPortals/icons/door.dds"},
	},
	[7] = { -- Market District
		{id = 0, location = 7, destinations = {8}, x = 55622, y = 19630, z = 100202, cx = 0.753964, cy = 0.221184, portalDescription = "|u25:0::In|u the market district, the Book Repository of Felms Oad is run by Aryni Sadris of House Tavari. It contains a public section and a well guarded restricted section on the lower level. If you intend to take any tomes home, do know the tomekeepers are known for thorough check out processes and paperwork.", icon = "/RoleplayTownPortals/icons/door.dds"},
		{id = 1, location = 7, destinations = {1,2}, x = 56982, y = 19400, z = 101157, cx = 0.759404, cy = 0.225004, portalDescription = "|u25:0::This|u door leads back through to the Alna District of Felms Oad. This is the heart of the isle, where you can find the tower, a cornerclub, the Abbey of Saint Felms and more. However, it can also take you back into the ancient fungal forest if you decide to walk through the beaches.", icon = "/esoui/art/icons/mapkey/mapkey_artifactgate_open.dds"},
		{id = 2, location = 7, destinations = {11}, x = 55097, y = 19540, z = 94418, cx = 0.751864, cy = 0.198048, portalDescription = "|u25:0::This|u gate leads to the Alchemist's Garden venue, which is managed by the the Order of the Burdened. It is a small building and courtyard for alchemists and apothecaries looking to collect or harvest goods for their work. Those looking to use the service will be asked to pay a fee upon departure should they leave having claimed goods or services. ", icon = "/esoui/art/icons/mapkey/mapkey_artifactgate_open.dds"},
	},
	[8] = { -- The Book Repository
		{id = 0, location = 8, destinations = {7}, x = 52871, y = 9536, z = 45863, cx = 0.172381, cy = 0.558037, portalDescription = "|u25:0::The|u door out of the Book Repository and back into the Market District. ", icon = "/RoleplayTownPortals/icons/door.dds"},
	},
	[9] = { -- Sanctuary of Seht
		{id = 0, location = 9, destinations = {2}, x = 55920, y = 50302, z = 105493, cx = 0.223041, cy = 0.421939, portalDescription = "|u25:0::This|u odd lift takes you back up into the Shaln Mora district of Felms Oad.", icon = "/RoleplayTownPortals/icons/door.dds"},
	},
	[10] = { -- The Ancestor Hall
		{id = 0, location = 10, destinations = {1}, x = 79092, y = 4428, z = 54105, cx = 0.69096, cy = 0.213086, portalDescription = "|u25:0::This|u door leads back to the the Alna District of Felms Oad, just outside the Abbey of Saint Felms the Bold.", icon = "/RoleplayTownPortals/icons/door.dds"},
	},
	[11] = { -- The Alchemist's Garden
		{id = 0, location = 11, destinations = {7}, x = 39508, y = 12327, z = 82264, cx = 0.199334, cy = 0.274395, portalDescription = "|u25:0::This|u leads back into the Market District of Felms Oad.", icon = "/esoui/art/icons/mapkey/mapkey_artifactgate_open.dds"},
	},
	[12] = { -- Tavari Council Manor
		{id = 0, location = 12, destinations = {1}, x = 80231, y = 52492, z = 61963, cx = 0.564293, cy = 0.183847, portalDescription = "|u25:0::This|u door leads back to the Alna District of Felms Oad. ", icon = "/esoui/art/icons/mapkey/mapkey_avatown.dds"},
	},
	[13] = { -- Darkden Cavern
		{id = 0, location = 13, destinations = {2}, x = 44336, y = 11509, z = 52403, cx = 0.391798, cy = 0.731796, portalDescription = "|u25:0::This|u leads back out into the sacred fungal woodlands of Felms Oad. ", icon = "/esoui/art/icons/poi/poi_cave_complete.dds"},
	},
	[14] = { -- Rawl'iit Town Center
		{id = 0, location = 14, destinations = {15}, x = 67362, y = 29099, z = 62388, cx = 0.507355, cy = 0.484472, radius = 200, portalDescription = "|u25:0::Past|u these gates is a terrifying road carved into the surface of the cliffs themselves. This narrow road navigates the cliffs down into the jungle basin of the Springlight Woods. Travelers should exercise extreme caution on the roads - one wrong step can send a careless Walker down a hundred foot drop into the jungle basin below! ", icon = "/esoui/art/icons/poi/poi_grove_complete.dds"},
		{id = 1, location = 14, destinations = {30}, x = 66504, y = 29329, z = 61140, cx = 0.488395, cy = 0.456849, portalDescription = "|u25:0::Beyond|u these doors lie the Old Barracks. The lobby of the Magistrate's office is the first room that a walker will enter upon stepping through the door.", icon = "/esoui/art/icons/servicemappins/servicepin_museum.dds"},
		{id = 2, location = 14, destinations = {16}, x = 65104, y = 29226, z = 63043, cx = 0.457339, cy = 0.499019, portalDescription = "|u25:0::These|u doors lead into the atrium of Jone's Claw Keep - the oldest and tallest structure in Rawl'iit. On the left-hand door is carved with a scene of an ancient Khajiiti adept facing off against two other Khajiit - a Senche-Raht and a Cathay-Raht. He stands between those fearsome figures and cowering innocents. On the right hand door, the grand adept stands triumphantly over the bodies of the slain Senche-Raht and Cathay-Raht, while others celebrate joyously. Inscribed upon it is a sentence in Ta'agra: \"Do-Zakarr saves Rawl'iit from the Thundermaw Raiders.\"", icon = "/esoui/art/icons/mapkey/mapkey_outpost.dds"},
		{id = 3, location = 14, destinations = {17,18}, x = 63755, y = 29226, z = 66009, cx = 0.427427, cy = 0.564727, nameOverride = "Wagon's Rest Inn", portalDescription = "|u25:0::The|u Wagon's Rest Inn has rooms available for travelers looking to get a good night's sleep in a bed! A pair of suites are offered for rent - a small inn room for shorter stays, and a deluxe room for extended visits!", icon = "/esoui/art/icons/mapkey/mapkey_inn.dds"},
		{id = 4, location = 14, destinations = {19,21,27,29}, x = 66538, y = 29228, z = 71923, cx = 0.489212, cy = 0.695816, nameOverride = "Riverside District", portalDescription = "|u25:0::These|u are the gates to the Riverside District, where the majority of the town's residences are found. This district is built along one of the major arteries of the river that separates Grahtwood and Pellitine. Stately Khajiit manors and farmsteads in various states of restoration or decay line the roads, which are sometimes graced by traders bringing goods upriver. At the edge of the district lie the farms that produce the region's Springlight Silk.", icon = "/RoleplayTownPortals/icons/signpost.dds"},
		{id = 5, location = 14, destinations = {22}, x = 72679, y = 29070, z = 70117, cx = 0.625204, cy = 0.65577, portalDescription = "|u25:0::Gold|u inlaid doors lie before you, carved with a most intricate scene. Khajiit of various furstocks climb upon the stars, their eyes drawn upwards towards the pair of moons at the top of the arched doors. They follow after a sphynx-like female - a figure most Khajiit would recognize as Khenarthi. It is a scene of her leading the souls of True Cats to the Sands Beyond the Stars, indicating this building to be a temple dedicated in Her name.", icon = "/esoui/art/icons/mapkey/mapkey_temple.dds"},
		{id = 6, location = 14, destinations = {24}, x = 70761, y = 28988, z = 69243, cx = 0.582707, cy = 0.636319, portalDescription = "|u25:0::Beyond|u this door lies a set of stairs leading down underneath Jone's Claw Keep. The doors themselves once had carvings upon them like many in Rawl'iit, but these have long since become warn down with time and weathering - to the point that the figures upon them have become mostly imperceptible. The sentence 'Rajhin steals a stupid carving' has been crudely etched on the right hand door.", icon = "/esoui/art/icons/mapkey/mapkey_battle.dds"},
		{id = 7, location = 14, destinations = {16}, x = 68428, y = 29905, z = 68676, cx = 0.531056, cy = 0.623733, portalDescription = "|u25:0::Upon|u these double doors are carved elaborate scenes from Rawl'iit's history. On the left hand door the adepts are seen battling against Men in segmented armor, wielding tall shields and broad yet short swords. The Khajiit adepts stand upon a great gatehouse, shooting arrows at the invading Men. The scene shifts past that gatehouse onto the right hand door, where on the other side the Men march beneath a burning Khajiiti tower.", icon = "/RoleplayTownPortals/icons/doorbig.dds"},
	},
	[15] = { -- The Springlight Woods
		{id = 0, location = 15, destinations = {14}, x = 59263, y = 29521, z = 54738, cx = 0.328048, cy = 0.314972, portalDescription = "|u25:0::Beyond|u these gates lie the narrow cliff road leading up to the Town Center. It is a hard journey going up that can wear out all but the most fit of Khajiit. It is made all the more difficult by the frequent rain that cascades down the cliffs, rendering the stones slippery. Carts are forced to perilously draw close to the edge of the road to pass one another - and it is during this time, as a passenger glances out the window, that they see the terrifying drop into the mist shrouded Springlight Woods awaiting below should they fall.", icon = "/esoui/art/icons/mapkey/mapkey_artifactgate_closed.dds"},
		{id = 1, location = 15, destinations = {26,23,28}, x = 66728, y = 29203, z = 59699, cx = 0.493298, cy = 0.424975, nameOverride = "Ruby Row", portalDescription = "|u25:0::Beyond|u these gates is the hamlet of Ruby Row - a small cluster of Akaviri inspired Imperial houses and shops. It is bordered on the south by the swamp of Brazollus's Folly, and by the Izora-ko river to the east. Upon entering through the gates a walker finds the hamlet's outskirts, which straddle either side of the road. Caravans travel past the gates between Rain's Fall and Chasegrove, which are constructed from Corinthe's white stone.", icon = "/RoleplayTownPortals/icons/signpost.dds"},
		{id = 2, location = 15, destinations = {25}, x = 68832, y = 28999, z = 77536, cx = 0.540046, cy = 0.820039, portalDescription = "|u25:0::A|u dark and foreboding entrance yawns before you. From it cool wind occasionally wafts up from deeper tunnels, sharply contrasting the humid jungle air around you. These are the Ironfang Mines, from which the town gathers iron. Deeper within the mines, dormant Aeonstone can be found, as well as breaches into the ancient catacombs where terrible things were once imprisoned.", icon = "/esoui/art/icons/poi/poi_cave_complete.dds"},
		{id = 3, location = 15, destinations = {}, x = 66170, y = 29226, z = 71043, cx = 0.48104, cy = 0.676201, nameOverride = "The Deep Woods", portalDescription = "|u25:0::Beyond|u this gateway lie the roads leading deeper into the Springlight Woods. The territories of Rawl'iit extend for a few miles to the south before the river and karsts that mark the border between the lands around Torval and Rawl'iit. Other paths beyond will lead travelers across the border of Valenwood.", icon = "/esoui/art/icons/mapkey/mapkey_artifactgate_open.dds"},
	},
	[16] = { -- Jone's Claw Keep
		{id = 0, location = 16, destinations = {14}, x = 82501, y = 37022, z = 86968, cx = 0.56618, cy = 0.542338, radius = 20, portalDescription = "|u25:0::These|u are the side doors of the Keep which exit out to the main street of the Town Square. It is carved with a scene of great battle - of two Khajiit fighting against a dark spirit, who's visage has been vandalized and defaced with a chisel. The moons of Jone and Jode hover behind the two Khajiit women's heads like halo's. There is a sentence in Ta'agra carved over the top: \"Zabarra and Jira-ko banish the False Ra.\"", icon = "/RoleplayTownPortals/icons/door.dds"},
		{id = 1, location = 16, destinations = {}, x = 85327, y = 37913, z = 85377, cx = 0.566835, cy = 0.541972, nameOverride = "The Tower", portalDescription = "|u25:0::Beyond|u this door lie a series of stairs that lead up into the Tower. It is said that some nights one can hear the voices of Khajiit speaking within there, even though there is a heavy lock on the door and a sign reading \"No Access!\"", icon = "/RoleplayTownPortals/icons/door.dds"},
		{id = 2, location = 16, destinations = {14}, x = 84262, y = 38014, z = 89890, cx = 0.566587, cy = 0.543015, portalDescription = "|u25:0::Upon|u the large doors of this hall are carved an elaborate scene of Khajiit gathered around a great feasting table. A feminine Tojay-Raht stands up at the head of the table with a short, curved blade raised in the air as if in triumph. Behind her are two radiant moons that envelop her head like a halo, shining their light upon those gathered.", icon = "/RoleplayTownPortals/icons/doorbig.dds"},
		{id = 3, location = 16, destinations = {14}, x = 83067, y = 36923, z = 83400, cx = 0.566311, cy = 0.541512, portalDescription = "|u25:0::This|u door leads to the Market Courtyard of Rawl'iit's town center. Beyond the heavy gates is the entryway, with an elegantly carved set of double doors leading outside. Engraved on the door panels are images of that Khajiit called Do'Zakarr featured on the other side of the door, training new adepts. A tall male Cathay-Raht is among them, as well as two Khajiit women - one a Tojay-Raht, the other a Cathay.", icon = "/RoleplayTownPortals/icons/townsquare.dds"},
		{id = 4, location = 16, destinations = {}, x = 82202, y = 37024, z = 85858, cx = 0.566111, cy = 0.542081, nameOverride = "West Balcony", portalDescription = "|u25:0::These|u barred doors lead to the western balcony of the Atrium. The panels of the doors are intricately carved with scenes of Khajiit adepts battling one another. One group of almost skeletal monks on the left hand door is led by a dark khajiit spirit who's visage has been defaced. The right hand door features two Khajiit women with their heads wreathed in moon-like halos leading a smaller group of True Cats against the spirits.", icon = "/RoleplayTownPortals/icons/door.dds"},
		{id = 5, location = 16, destinations = {}, x = 83868, y = 37024, z = 85837, cx = 0.566497, cy = 0.542077, nameOverride = "East Balcony", portalDescription = "|u25:0::These|u double doors lead to a set of stairs that ascend to the Eastern Balcony. Carved on the left hand door was the Khajiit that had saved the innocents of Old Rawl'iit from the Thundermaw Raiders kneeling before an altar, with an image of Khenarthi emerging from sugar-smoke above him. Yet behind him lurks another Khajiit with a dagger. On the right hand door, the Adept lies dead - and Khenarthi turns away in shame as the murderer claims his mantle.", icon = "/RoleplayTownPortals/icons/door.dds"},
	},
	[17] = { -- Wagon's Rest Inn: Small Suite
		{id = 0, location = 17, destinations = {14,18}, x = 21458, y = 10134, z = 27589, cx = 0.270878, cy = 0.633784, nameOverride = "Inn Room Doors", portalDescription = "|u25:0::The|u hustle and bustle of the Wagon's Rest Inn can be heard beyond these doors. (To be fair, they can also be heard through the thinner walls of this cheaper room!) Beyond them a walker will find the small lobby of the Inn, with its carved doors surrounded by colored glass that lead out into the main street of the Town Center.", icon = "/RoleplayTownPortals/icons/door.dds"},
	},
	[18] = { -- Wagon's Rest Inn: Deluxe Suite
		{id = 0, location = 18, destinations = {14,17}, x = 33783, y = 20077, z = 26068, cx = 0.406325, cy = 0.617475, nameOverride = "Inn Room Doors", portalDescription = "|u25:0::The|u hustle and bustle of the Wagon's Rest Inn can be heard beyond these doors. Beyond them a walker will find a set of stairs leading down to the small lobby of the Inn, with its carved doors surrounded by colored glass that lead out into the main street of the Town Center.", icon = "/RoleplayTownPortals/icons/door.dds"},
	},
	[19] = { -- Clan Father's Manor
		{id = 0, location = 19, destinations = {20}, x = 49497, y = 15013, z = 60919, cx = 0.771343, cy = 0.61916, portalDescription = "|u25:0::This|u gate leads to the manor's private stables, where the Caravan Master's luxury wagon is stored. This massive abomination is forged from the remains of rival Baandari's wagons, is too large to travel on most roads, and requires two senche-raht to pull it (who are barely capable of this feat). It exists to spite those unfortunate enough to have to share the road with it.", icon = "/esoui/art/icons/mapkey/mapkey_caravan.dds"},
		{id = 1, location = 19, destinations = {14,21,27,29}, x = 47820, y = 15226, z = 63102, cx = 0.747085, cy = 0.650736, nameOverride = "Riverside Gates", portalDescription = "|u25:0::Beyond|u this gate lies the Riverside District. Ra'jirroh's walled manor looms tall over most of this district, which hosts most of the residences of Rawl'iit as well as some specialized shops. The northern end of the district is bordered by the wall dividing Riverside and the Town Center, while at the far southern end one can find silk and spice farms.", icon = "/RoleplayTownPortals/icons/signpost.dds"},
	},
	[20] = { -- Ra'jirroh's Luxury Wagon
		{id = 0, location = 20, destinations = {14}, x = 19635, y = 20026, z = 29025, cx = 0.312554, cy = 0.789918, portalDescription = "|u25:0::All|u roads eventually lead home...", icon = "/esoui/art/icons/mapkey/mapkey_caravan.dds"},
	},
	[21] = { -- Guard Lodge
		{id = 0, location = 21, destinations = {14,19,27,29}, x = 33938, y = 19831, z = 53393, cx = 0.773768, cy = 0.281806, nameOverride = "Gate to Riverside", portalDescription = "|u25:0::Beyond|u this gate lies the Riverside District. Ra'jirroh's walled manor looms tall over most of this district, which hosts most of the residences of Rawl'iit as well as some specialized shops. The northern end of the district is bordered by the wall dividing Riverside and the Town Center, while at the far southern end one can find silk and spice farms.", icon = "/RoleplayTownPortals/icons/signpost.dds"},
	},
	[22] = { -- Rainsong Temple
		{id = 0, location = 22, destinations = {14}, x = 105478, y = 10357, z = 91599, cx = 0.453546, cy = 0.228836, portalDescription = "|u25:0::As|u these double doors swing open a swift humid breeze pours through the opening into Khenarthi's Temple. Immediately outside lay the temple's courtyard at the very edge of the Town Center.", icon = "/RoleplayTownPortals/icons/doorbig.dds"},
	},
	[23] = { -- The Jade Flask
		{id = 0, location = 23, destinations = {15,26,28}, x = 60802, y = 10122, z = 46883, cx = 0.702887, cy = 0.436447, nameOverride = "Gate to Ruby Row", portalDescription = "|u25:0::This|u gate leads to Ruby Row, and from there to the Springlight Woods. The Jade Flask is located at the far southern edges of this old district, the tilted tower looming over the low, silty marshes that form naturally at the bottom of the Springlight Basin.", icon = "/RoleplayTownPortals/icons/door.dds"},
	},
	[24] = { -- Moonshroud Arena
		{id = 0, location = 24, destinations = {14}, x = 39672, y = 3512, z = 55942, cx = 0.267685, cy = 0.258773, portalDescription = "|u25:0::Beyond|u these doors lie a series of stairs leading up to the Temple Courtyard of the Town Center.", icon = "/RoleplayTownPortals/icons/doorbig.dds"},
	},
	[25] = { -- The Ironfang Mines
		{id = 0, location = 25, destinations = {15}, x = 55412, y = 61493, z = 82550, cx = 0.904314, cy = 0.413554, portalDescription = "|u25:0::The|u humid air of the rain-forest blows through this yawning exit from the mines. Despite this, there seems to be a chill to the caverns behind you that cannot be pushed back even by the tropical air coming in.", icon = "/esoui/art/icons/mapkey/mapkey_artifactgate_closed.dds"},
	},
	[26] = { -- Ardun-Vylak's Home
		{id = 0, location = 26, destinations = {28,23,15}, x = 19650, y = 20026, z = 29035, cx = 0.312595, cy = 0.789945, nameOverride = "Ardun's Door", portalDescription = "|u25:0::These|u gates lead out to a road that curves to the left and the right. A single stream follows the side of the road, over which Akaviri styled foot-bridges with exaggerated curves and snake motifs cross. Ardun-Vylak's home is the finest preserved example of the houses built by Rim-Men refugees of Attrebus's purges. A cherry tree planted for Ardun's ancestors stands at the stream's edge. ", icon = "/RoleplayTownPortals/icons/door.dds"},
	},
	[27] = { -- Sandy Bear Smithy
		{id = 0, location = 27, destinations = {21,19,14,29}, x = 22815, y = 14001, z = 25709, cx = 0.438822, cy = 0.499611, nameOverride = "Riverside Gate", portalDescription = "|u25:0::The|u Riverside district lies beyond this gate. Ra'jirroh's walled manor looms tall over most of this district, which hosts most of the residences of Rawl'iit as well as some specialized shops. The northern end of the district is bordered by the wall dividing Riverside and the Town Center, while at the far southern end one can find silk and spice farms.", icon = "/RoleplayTownPortals/icons/signpost.dds"},
	},
	[28] = { -- The Brass Lion
		{id = 0, location = 28, destinations = {26,23,15}, x = 44157, y = 34600, z = 56783, cx = 0.887286, cy = 0.625311, nameOverride = "Gates to Ruby Row", portalDescription = "|u25:0::These|u gates lead out to a road that curves uphill to the right. A single stream follows the side of the road, over which Akaviri styled foot-bridges with exaggerated curves and snake motifs cross. The Brass Lion is the largest building in Ruby Row, and is located at the lowest section of the narrow valley. The water of the stream is used to cool Fad's forges.", icon = "/RoleplayTownPortals/icons/signpost.dds"},
	},
	[29] = { -- Kaihanna & Ko'ebony's Home
		{id = 0, location = 29, destinations = {14,19,21,27}, x = 22776, y = 14001, z = 25804, cx = 0.438705, cy = 0.499898, nameOverride = "Gate to Riverside", portalDescription = "|u25:0::Beyond|u this gate lies the Riverside District. Ra'jirroh's walled manor looms tall over most of this district, which hosts most of the residences of Rawl'iit as well as some specialized shops. The northern end of the district is bordered by the wall dividing Riverside and the Town Center, while at the far southern end one can find silk and spice farms.", icon = "/RoleplayTownPortals/icons/signpost.dds"},
	},
	[30] = { -- Magistrates Office
		{id = 0, location = 30, destinations = {14}, x = 33811, y = 20077, z = 26185, cx = 0.406462, cy = 0.618012, portalDescription = "|u25:0::These|u doors will lead you outside of the Old Barracks and into the Market Courtyard. Even now, the smell of the markets exotic spices and foods tease the nose through the cracks of the doors.", icon = "/RoleplayTownPortals/icons/door.dds"},
		{id = 1, location = 30, destinations = {}, x = 33188, y = 20100, z = 25971, cx = 0.4036, cy = 0.617025, nameOverride = "Old Barracks", portalDescription = "|u25:0::Beyond|u these doors are the deeper parts of the Old Barracks. There is a short hallway beyond this door that leads to two destinations. A heavy set of doors on the right will take walkers to Rawl'iit's jail, while walking straight ahead will take them to the armory.", icon = "/RoleplayTownPortals/icons/door.dds"},
	},
	[31] = { -- [HH] Ouada Mora
		{id = 0, location = 31, destinations = {34}, x = 79009, y = 27234, z = 70137, cx = 0.594653, cy = 0.282417, icon = "/esoui/art/icons/emotes/emotecategoryicon_ceremonial.dds"},
		{id = 1, location = 31, destinations = {35}, x = 70675, y = 27140, z = 67895, cx = 0.341197, cy = 0.214212, icon = "/esoui/art/icons/mapkey/mapkey_temple.dds"},
		{id = 2, location = 31, destinations = {33}, x = 68865, y = 27522, z = 82321, cx = 0.28613, cy = 0.653033, icon = "/esoui/art/icons/poi/poi_town_complete.dds"},
	},
	[32] = { -- [BMT] The Undercity
		{id = 0, location = 32, destinations = {33}, x = 89936, y = 22522, z = 95716, cx = 0.468584, cy = 0.705162, icon = "/esoui/art/icons/poi/poi_town_complete.dds"},
		{id = 1, location = 32, destinations = {38}, x = 92841, y = 22522, z = 94425, cx = 0.529027, cy = 0.678264, icon = "/esoui/art/icons/mapkey/mapkey_groupboss.dds"},
	},
	[33] = { -- [HH] Ouada Mora Outskirts
		{id = 0, location = 33, destinations = {31}, x = 59181, y = 29521, z = 54660, cx = 0.32625, cy = 0.313338, icon = "/esoui/art/icons/poi/poi_estate_complete.dds"},
		{id = 1, location = 33, destinations = {32}, x = 70367, y = 29314, z = 51539, cx = 0.574044, cy = 0.244197, icon = "/esoui/art/icons/poi/poi_cave_complete.dds"},
		{id = 2, location = 33, destinations = {36}, x = 74851, y = 29073, z = 77247, cx = 0.673259, cy = 0.813665, icon = "/esoui/art/icons/mapkey/mapkey_artifactgate_closed.dds"},
		{id = 3, location = 33, destinations = {37}, x = 61456, y = 28982, z = 75515, cx = 0.376594, cy = 0.775253, icon = "/esoui/art/icons/poi/poi_crypt_complete.dds"},
	},
	[34] = { -- [HH] The House of Remedies
		{id = 0, location = 34, destinations = {31}, x = 52842, y = 9536, z = 45842, cx = 0.172309, cy = 0.557984, icon = "/esoui/art/icons/poi/poi_estate_complete.dds"},
	},
	[35] = { -- [HH] The Abbey of Threefold Mercies
		{id = 0, location = 35, destinations = {31}, x = 80265, y = 52492, z = 61961, cx = 0.565356, cy = 0.183847, icon = "/esoui/art/icons/poi/poi_estate_complete.dds"},
	},
	[36] = { -- [HH] The Hall of Justice
		{id = 0, location = 36, destinations = {33}, x = 105490, y = 10357, z = 91593, cx = 0.453546, cy = 0.228836, icon = "/esoui/art/icons/poi/poi_town_complete.dds"},
	},
	[37] = { -- [HH] The Ghostwood
		{id = 0, location = 37, destinations = {33}, x = 81963, y = 12214, z = 64785, cx = 0.640458, cy = 0.742006, icon = "/esoui/art/icons/poi/poi_town_complete.dds"},
	},
	[38] = { -- [BMT] Boethiah's Run
		{id = 0, location = 38, destinations = {32}, x = 66721, y = 5235, z = 75994, cx = 0.407307, cy = 0.16894, icon = "/esoui/art/icons/poi/poi_cave_complete.dds"},
		{id = 1, location = 38, destinations = {39}, x = 69360, y = 6969, z = 78084, cx = 0.503537, cy = 0.24515, icon = "/esoui/art/icons/mapkey/mapkey_inn.dds"},
	},
	[39] = { -- [BMT] Twilight Teahouse
		{id = 0, location = 39, destinations = {38}, x = 51349, y = 12154, z = 49752, cx = 0.447977, cy = 0.757842, icon = "/esoui/art/icons/mapkey/mapkey_groupboss.dds"},
	},
}
