LOVELYEMOTES_COLOR_SELECTED_FAVORITE = ZO_ColorDef:New(0.7, 0, 0, 1)
LOVELYEMOTES_COLOR_PERSONALITY_ACTIVE = ZO_ColorDef:New(0.75, 0.25, 0.95, 1)
LOVELYEMOTES_COLOR_MAINWINDOW_NORMAL = ZO_ColorDef:New(1, 1, 1, 1)
LOVELYEMOTES_COLOR_MAINWINDOW_HIGHLIGHTED = ZO_ColorDef:New(0, 1, 0, 1)
