LE_EmoteData = {
	[671] = { HasLoop = true ,}, -- /alinorallemande
	[23] = { HasLoop = true, }, -- /armscrossed
	[301] = { HasLoop = true, }, -- /attention
	[835] = { HasLoop = true, }, -- /bagpipes
	[604] = { HasLoop = true, }, -- /banneraldmeri
	[605] = { HasLoop = true, }, -- /bannercovenant
	[596] = { HasLoop = true, }, -- /bannerebonheart
	[654] = { HasLoop = true, }, -- /bannerkarthwatch
	[653] = { HasLoop = true, }, -- /bannermorthal
	[655] = { HasLoop = true, }, -- /bannersolitude
	[710] = { HasLoop = true, }, -- /barkeep
	[126] = { HasLoop = true, }, -- /beggar
	[239] = { HasLoop = true, }, -- /blessing
	[165] = { HasLoop = true, }, -- /bored
	[141] = { HasLoop = true, }, -- /breathless
	[563] = { HasLoop = true, }, -- /catcontemplation
	[117] = { HasLoop = true, }, -- /celebrate
	[185] = { HasLoop = true, }, -- /clap
	[334] = { HasLoop = true, }, -- /colder
	[778] = { HasLoop = true, }, -- /conchshell
	[193] = { HasLoop = true, }, -- /controlrod
	[35] = { HasLoop = true, }, -- /cower
	[729] = { HasLoop = true, }, -- /crochet
	[122] = { HasLoop = true, }, -- /crouch
	[361] = { HasLoop = true, }, -- /crownstore
	[240] = { HasLoop = true, }, -- /cry
	[79] = { HasLoop = true, }, -- /crying
	[80] = { HasLoop = true, }, -- /dance
	[278] = { HasLoop = true, }, -- /dancealtmer
	[279] = { HasLoop = true, }, -- /danceargonian
	[280] = { HasLoop = true, }, -- /dancebosmer
	[276] = { HasLoop = true, }, -- /dancebreton
	[869] = { HasLoop = true, }, -- /dancecelebration
	[304] = { HasLoop = true, }, -- /dancedarkelf
	[88] = { HasLoop = true, }, -- /dancedrunk
	[281] = { HasLoop = true, }, -- /dancedunmer
	[302] = { HasLoop = true, }, -- /dancehighelf
	[282] = { HasLoop = true, }, -- /danceimperial
	[283] = { HasLoop = true, }, -- /dancekhajiit
	[826] = { HasLoop = true, }, -- /dancejig
	[284] = { HasLoop = true, }, -- /dancenord
	[285] = { HasLoop = true, }, -- /danceorc
	[286] = { HasLoop = true, }, -- /danceredguard
	[303] = { HasLoop = true, }, -- /dancewoodelf
	[719] = { HasLoop = true, }, -- /dayoflights
	[602] = { HasLoop = true, }, -- /desertrain
	[39] = { HasLoop = true, }, -- /downcast
	[9] = { HasLoop = true, }, -- /drink
	[244] = { HasLoop = true, }, -- /drink2
	[298] = { HasLoop = true, }, -- /drink3
	[615] = { HasLoop = true, }, -- /drinkfromskull
	[7] = { HasLoop = true, }, -- /drum
	[166] = { HasLoop = true, }, -- /drunk
	[231] = { HasLoop = true, }, -- /eat
	[261] = { HasLoop = true, }, -- /eatbread
	[794] = { HasLoop = true, }, -- /eatintimidate
	[11] = { HasLoop = true, }, -- /eat2
	[263] = { HasLoop = true, }, -- /eat3
	[299] = { HasLoop = true, }, -- /eat4
	[467] = { HasLoop = true, }, -- /eat5
	[644] = { HasLoop = true, }, -- /eggscramble
	[716] = { HasLoop = true, }, -- /eliteseat
	[594] = { HasLoop = true, }, -- /esraj
	[670] = { HasLoop = true, }, -- /falkreathfrolic
	[768] = { HasLoop = true, }, -- /feedbird
	[538] = { HasLoop = true, }, -- /festivalbeggar
	[675] = { HasLoop = true, }, -- /firespinning
	[6] = { HasLoop = true, }, -- /flute
	[886] = { HasLoop = true, }, -- /glassharp
	[600] = { HasLoop = true, }, -- /goutfang
	[136] = { HasLoop = true, }, -- /hammer
	[155] = { HasLoop = true, }, -- /hammerlow
	[154] = { HasLoop = true, }, -- /hammerwall
	[838] = { HasLoop = true, }, -- /handpan
	[569] = { HasLoop = true, }, -- /handpuppet
	[46] = { HasLoop = true, }, -- /handsonhips
	[186] = { HasLoop = true, }, -- /heartbroken
	[124] = { HasLoop = true, }, -- /humble
	[267] = { HasLoop = true, }, -- /idle
	[288] = { HasLoop = true, }, -- /idle2
	[294] = { HasLoop = true, }, -- /idle3
	[295] = { HasLoop = true, }, -- /idle4
	[296] = { HasLoop = true, }, -- /idle5
	[856] = { HasLoop = true, }, -- /idlemagic
	[181] = { HasLoop = true, }, -- /impatient
	[292] = { HasLoop = true, }, -- /juggleflame
	[533] = { HasLoop = true, }, -- /jugglepumpkin
	[758] = { HasLoop = true, }, -- /juggleyarn
	[98] = { HasLoop = true, }, -- /jumpingjacks
	[789] = { HasLoop = true, }, -- /keyharp
	[123] = { HasLoop = true, }, -- /kneel
	[125] = { HasLoop = true, }, -- /kneelpray
	[169] = { HasLoop = true, }, -- /kowtow
	[807] = { HasLoop = true, }, -- /leafshade
	[159] = { HasLoop =true, }, -- /leanback
	[291] = { HasLoop = true, }, -- /leanbackcoin
	[158] = { HasLoop = true, }, -- /leanside
	[331] = { HasLoop = true, }, -- /letter
	[647] = { HasLoop = true, }, -- /lichen
	[865] = { HasLoop = true, }, -- /livingstatue
	[782] = { HasLoop = true, }, -- /lookatthis
	[300] = { HasLoop = true, }, -- /lookup
	[5] = { HasLoop = true, }, -- /lute
	[709] = { HasLoop = true, }, -- /marshmallowtreat
	[568] = { HasLoop = true, }, -- /mimetugofwar
	[573] = { HasLoop = true, }, -- /mimewall
	[715] = { HasLoop = true, }, -- /ownthrone
	[796] = { HasLoop = true, }, -- /palelord
	[831] = { HasLoop = true, }, -- /panflute
	[788] = { HasLoop = true, }, -- /plantyourself
	[141] = { HasLoop = true, }, -- /playdead
	[857] = { HasLoop = true, }, -- /playglassarmonica
	[60] = { HasLoop = true, }, -- /pray
	[130] = { HasLoop = true, }, -- /prov
	[100] = { HasLoop = true, }, -- /pushup
	[99] = { HasLoop = true, }, -- /pushups
	[846] = { HasLoop = true, }, -- /pyromancer
	[595] = { HasLoop = true, }, -- /qanun
	[638] = { HasLoop = true, }, -- /ragnarthered
	[289] = { HasLoop = true, }, -- /rake
	[175] = { HasLoop = true, }, -- /rally
	[13] = { HasLoop = true, }, -- /read
	[119] = { HasLoop = true, }, -- /ritual
	[755] = { HasLoop = true, }, -- /ritualcasting
	[293] = { HasLoop = true, }, -- /sad
	[67] = { HasLoop = true, }, -- /saluteloop
	[68] = { HasLoop = true, }, -- /saluteloop2
	[69] = { HasLoop = true, }, -- /saluteloop3
	[676] = { HasLoop = true, }, -- /scarecrow
	[196] = { HasLoop = true, }, -- /shovel
	[104] = { HasLoop = true, }, -- /sick
	[120] = { HasLoop = true, }, -- /sit
	[146] = { HasLoop = true, }, -- /sit2
	[147] = { HasLoop = true, }, -- /sit3
	[148] = { HasLoop = true, }, -- /sit4
	[149] = { HasLoop = true, }, -- /sit5
	[150] = { HasLoop = true, }, -- /sit6
	[121] = { HasLoop = true, }, -- /sitchair
	[140] = { HasLoop = true, }, -- /situps
	[540] = { HasLoop = true, }, -- /skullponder
	[143] = { HasLoop = true, }, -- /sleep
	[145] = { HasLoop = true, }, -- /sleep2
	[849] = { HasLoop = true, }, -- /sommelierswirl
	[771] = { HasLoop = true, }, -- /spyglass
	[759] = { HasLoop = true, }, -- /stargazer
	[848] = { HasLoop = true, }, -- /stompgrapes
	[616] = { HasLoop = true, }, -- /summonbat
	[187] = { HasLoop = true, }, -- /surrender
	[290] = { HasLoop = true, }, -- /sweep
	[809] = { HasLoop = true, }, -- /sweep
	[767] = { HasLoop = true, }, -- /sworddance
	[560] = { HasLoop = true, }, -- /teebadribble
	[561] = { HasLoop = true, }, -- /teebawarmup
	[1] =  { HasLoop = true, }, -- /torch
	[541] = { HasLoop = true, }, -- /tracker
	[793] = { HasLoop = true, }, -- /trumpetsolo
	[2] = { HasLoop = true, }, -- /wand2
	[571] = { HasLoop = true, }, -- /warmhands
	[601] = { HasLoop = true, }, -- /whisperingclaw
}
