-- Generated by tools/slice_theme_art.py. Each bar is three 256 squares.
-- Hole is left, top, right, bottom as fractions of the stitched strip
-- (tiles * 256 wide, 256 tall). Lua places the fill in that well.
ValknarrThemeFrames = {
    fileSize = 256,
    tiles = 3,
    magicka = {
        tiles = { "/ValknarrTheme/texture/yl.dds", "/ValknarrTheme/texture/ym.dds", "/ValknarrTheme/texture/yr.dds" },
        hole = { 0.1731, 0.2636, 0.805, 0.6696 },
    },
    health = {
        tiles = { "/ValknarrTheme/texture/xl.dds", "/ValknarrTheme/texture/xm.dds", "/ValknarrTheme/texture/xr.dds" },
        hole = { 0.1644, 0.3372, 0.862, 0.6116 },
    },
    stamina = {
        tiles = { "/ValknarrTheme/texture/zl.dds", "/ValknarrTheme/texture/zm.dds", "/ValknarrTheme/texture/zr.dds" },
        hole = { 0.1881, 0.2636, 0.8256, 0.6696 },
    },
}
