-- Generated by tools/encode_named_skins.py.
-- HUD hole is fractions of the stitched 768x256 strip.
-- Wolf plate is 8 squares (4x2, 1024x512). hole is Ult well fractions.
-- circle is cx (of width), cy (of height), outer radius (of width).
-- Per-skin circle centers Fury/portrait on that plate's inner chrome.
-- The plate punch follows the painted inner chrome, not a disc.
ValknarrThemeFrames = {
    fileSize = 256,
    tiles = 3,
    nordic = {
        tiles = { "/ValknarrTheme/texture/xl.dds", "/ValknarrTheme/texture/xm.dds", "/ValknarrTheme/texture/xr.dds" },
        hole = { 0.043, 0.3047, 0.9531, 0.707 },
    },
    steel = {
        tiles = { "/ValknarrTheme/texture/a2l.dds", "/ValknarrTheme/texture/a2m.dds", "/ValknarrTheme/texture/a2r.dds" },
        hole = { 0.1081, 0.3516, 0.8906, 0.6211 },
    },
    bronze = {
        tiles = { "/ValknarrTheme/texture/a3l.dds", "/ValknarrTheme/texture/a3m.dds", "/ValknarrTheme/texture/a3r.dds" },
        hole = { 0.1081, 0.3516, 0.8906, 0.6211 },
    },
    wolf = {
        tiles = 8,
        cols = 4,
        rows = 2,
        circle = { 0.75, 0.50, 0.24 },
        well = 0.20,
        nordic = {
            tiles = { "/ValknarrTheme/texture/n1.dds", "/ValknarrTheme/texture/n2.dds", "/ValknarrTheme/texture/n3.dds", "/ValknarrTheme/texture/n4.dds", "/ValknarrTheme/texture/n5.dds", "/ValknarrTheme/texture/n6.dds", "/ValknarrTheme/texture/n7.dds", "/ValknarrTheme/texture/n8.dds" },
            hole = { 0.0732, 0.7578, 0.5361, 0.9023 },
            circle = { 0.7661, 0.5296, 0.24 },
        },
        steel = {
            tiles = { "/ValknarrTheme/texture/s1.dds", "/ValknarrTheme/texture/s2.dds", "/ValknarrTheme/texture/s3.dds", "/ValknarrTheme/texture/s4.dds", "/ValknarrTheme/texture/s5.dds", "/ValknarrTheme/texture/s6.dds", "/ValknarrTheme/texture/s7.dds", "/ValknarrTheme/texture/s8.dds" },
            hole = { 0.0859, 0.7578, 0.5361, 0.8926 },
            circle = { 0.7500, 0.5000, 0.24 },
        },
        bronze = {
            tiles = { "/ValknarrTheme/texture/b1.dds", "/ValknarrTheme/texture/b2.dds", "/ValknarrTheme/texture/b3.dds", "/ValknarrTheme/texture/b4.dds", "/ValknarrTheme/texture/b5.dds", "/ValknarrTheme/texture/b6.dds", "/ValknarrTheme/texture/b7.dds", "/ValknarrTheme/texture/b8.dds" },
            hole = { 0.0859, 0.7578, 0.5361, 0.8926 },
            circle = { 0.7500, 0.5000, 0.24 },
        },
    },
}
