-- ESO Adventurer Suite
-- Antiquity lead-source reference data derived from the user-supplied Display Leads addon (remosito).
-- Game state is queried live from ESO; this table only provides source/location descriptions and find-zone overrides.
ESOProgressionCoach = ESOProgressionCoach or {}
ESOProgressionCoach.AntiquityLeadData = ESOProgressionCoach.AntiquityLeadData or {}
local D = ESOProgressionCoach.AntiquityLeadData
D.locations = {
    [18] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [19] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [20] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [21] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [22] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [23] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [24] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [25] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [26] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [27] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [28] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [29] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [30] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [31] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [32] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [33] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [34] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [35] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [36] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [37] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [38] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [39] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [40] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [41] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [42] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [43] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [44] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [45] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [46] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [47] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [48] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [49] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [50] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [51] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [52] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [53] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [54] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [55] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [56] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [57] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [58] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [59] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [60] = { long = "'Curious Dwemer Rubble' in a corner of Rkulftzel crafting area", sourceType = "Fix location", short = "Rubble", complete = true },
    [61] = { long = "Mount Fragment - Inner Sea Armature delve boss", sourceType = "Delve", short = "(D) Inner Sea Armature", complete = true },
    [62] = { long = "Klathzgars Centurion in Klathzgar delve", sourceType = "Delve", short = "(D) Klathzgar", complete = true },
    [63] = { long = "Dwemer spider, sphere, centurion, steam pipe inside Mzulft", sourceType = "Mob", short = "Mzulft mobs", complete = true },
    [64] = { long = "Aldunz delve boss", sourceType = "Delve", short = "(D) Aldunz", complete = true },
    [65] = { long = "Wolves outside, Dwarven spider inside Bthzark, Saintsport Drake Sentry/Cutthroat, Goblin Mines", sourceType = "All loot tables", short = "Most Mobs", complete = true },
    [66] = { long = "Delve boss in Avanchzel", sourceType = "Delve", short = "(D) Avanchzel", complete = true },
    [67] = { long = "Mtharnaz bosses, Skillful Seamstress, The Brass Hatchlin", sourceType = "Delve", short = "(D) Mtharnaz ", complete = true },
    [68] = { long = "Last boss in Volenfell", sourceType = "Group dungeon", short = "(GD) Volenfell", complete = true },
    [69] = { long = "Darkshade Caverns II (Engine Guardian boss)", sourceType = "Group dungeon", short = "(GD) Darkshade Caverns II", complete = true },
    [70] = { long = "All bosses in Razak's Wheel", sourceType = "Public dungeon", short = "(PD) Razak's Wheel", complete = true },
    [71] = { long = "Non-group-boss in Nchuthnkarst", sourceType = "Public dungeon", short = "(PD) Nchuthnkarst", complete = true },
    [72] = { long = "Earth Forge pressure room 3, curious dwemer rubble near the Orgnum's Scales clothier station", sourceType = "Fix location", short = "Rubble", complete = true },
    [73] = { long = "(WB) Zemarek-thu", sourceType = "World boss", short = "(WB) Zemarek-thu", complete = true },
    [74] = { long = "Darkshade Caverns I (Sentinel of Rkugamz)", sourceType = "Group dungeon", short = "(GD) Darkshade Caverns I", complete = true },
    [75] = { long = "The Last Sentinel boss in Rkhardahrk delve", sourceType = "Delve", short = "(D) Rkhardahrk", complete = true },
    [76] = { long = "Rkundzelft group delve, Mzeklok boss", sourceType = "Delve", short = "(D) Rkundzelft", complete = true },
    [77] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [78] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [79] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [80] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [81] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [82] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [83] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [84] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [85] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [86] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [87] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [88] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [89] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [90] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [91] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [93] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [94] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [95] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [96] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [97] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [98] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [99] = { long = "Jewelry box containers in all zones", sourceType = "Container", short = "Jewelry boxes", complete = true },
    [100] = { long = "Thieves troves in many/all zones", sourceType = "Thieves trove", short = "Thieves trove", complete = true },
    [101] = { long = "Safeboxes in all zones, treasure chest", sourceType = "Safebox", short = "Safebox", complete = true },
    [102] = { long = "Theatre of Rellenthil NPC. Watch the ghost dance and the lead will appear in your collections. ", sourceType = "Fix location", short = "Rellenthil Ghost Dance", complete = true },
    [103] = { long = "", sourceType = "Other", short = "", complete = true },
    [104] = { long = "High King's chamber, Blue Palace; Impresarios tent jewelry box outside Solitude", sourceType = "Fix location", short = "High King's chamber", complete = true },
    [105] = { long = "At the end of Morthal Barrow from the 'Danger in the Holds' main quest", sourceType = "Fix location", short = "Morthal Barrow ", complete = true },
    [106] = { long = "Underneath the Dragon Bridge", sourceType = "Fix location", short = "Under Dragon Bridge", complete = true },
    [107] = { long = "Clockwork Criterion in Nchuthnkarst public dungeon", sourceType = "Public dungeon", short = "(PD) Nchuthnkarst", complete = true },
    [108] = { long = "Dwarven spider boss in The Scraps delve. ", sourceType = "Delve", short = "(D) The Scraps", complete = true },
    [109] = { long = "Colossus Charging Station world boss in Blackreach", sourceType = "World boss", short = "(WB) Colossus", complete = true },
    [111] = { long = "All bosses in Karnwarsten public dungeon", sourceType = "Public dungeon", short = "(PD) Karnwarsten", complete = true },
    [112] = { long = "All world bosses", sourceType = "World boss", short = "(WB) all", complete = true },
    [113] = { long = "Saltwater fishing", sourceType = "Fishing", short = "Salt Water fishing", complete = true },
    [114] = { long = "Psijic portal in Artauem or Summerset   ", sourceType = "Node", short = "Psijic Portal", complete = true },
    [115] = { long = "Saltwater fishing", sourceType = "Fishing", short = "Salt Water fishing", complete = true },
    [116] = { long = "Drodda of Icereach in Direfrost Keep", sourceType = "Group dungeon", short = "(GD) Direfrost Keep", complete = true },
    [117] = { long = "All world bosses", sourceType = "World boss", short = "(WB) all", complete = true },
    [118] = { long = "Convenant NPC, Frostedge Sentry, Frostbite Spider, Mudcrab, Undead", sourceType = "Mob", short = "Mobs", complete = true },
    [119] = { long = "Cyrodiil, Underpall Cave, Toadstool Hollow, Capstone Cave, Red Ruby Cave delves", sourceType = "Delve", short = "(D) 4x", complete = false },
    [120] = { long = "All bosses in Labyrinthian public dungeon", sourceType = "Public dungeon", short = "(PD) Labyrinthian", complete = true },
    [121] = { long = "All world bosses", sourceType = "World boss", short = "(WB) all", complete = true },
    [122] = { long = "Canonreeve Oraneth Elden Hollow I", sourceType = "Group dungeon", short = "(GD) Elden Hollow I", complete = true },
    [123] = { long = "All bosses in Bad Man’s Hallow public dungeon", sourceType = "Public dungeon", short = "(PD) Bad Man's Hallows", complete = true },
    [124] = { long = "All world bosses", sourceType = "World boss", short = "(WB) all", complete = true },
    [125] = { long = "Bok-xul,  Echoing Hollow world bosses, bosses in Teeth of Sithis + Tsofeer Cavern delves ", sourceType = "World boss", short = "(WB)(D) All", complete = true },
    [126] = { long = "All world bosses", sourceType = "World boss", short = "(WB) all", complete = true },
    [127] = { long = "Captain Blackheart in Blackheart Haven dungeon", sourceType = "Group dungeon", short = "(GD) Blackheart Haven", complete = true },
    [128] = { long = "All world bosses", sourceType = "World boss", short = "(WB) all", complete = true },
    [129] = { long = "All world bosses", sourceType = "World boss", short = "(WB) all", complete = true },
    [130] = { long = "All bosse in Crows Wood public dungeon", sourceType = "Public dungeon", short = "(PD) Crows Wood", complete = true },
    [131] = { long = "Random mobs in Bethnik", sourceType = "Mob", short = "Random mob", complete = true },
    [132] = { long = "All bosses in Old Orsinium public dungeon", sourceType = "Public dungeon", short = "(PD) Old Orsinium", complete = true },
    [133] = { long = "All bosses in Bonesnap Ruins public dungeon ", sourceType = "Public dungeon", short = "(PD) Bonesnap Ruin", complete = true },
    [134] = { long = "Imperial City upper bosses", sourceType = "World boss", short = "(WB) IC Upper", complete = true },
    [135] = { long = "All world bosses", sourceType = "World boss", short = "(WB) all", complete = true },
    [136] = { long = "Illambris Twins in Crypt of Hearts I", sourceType = "Group dungeon", short = "(GD) Crypt of Hearts I", complete = true },
    [137] = { long = "All bosses in Village of the Lost public dungeon", sourceType = "Public dungeon", short = "(PD) Village of the Lost", complete = true },
    [138] = { long = "The Whisperer in Spindleclutch I", sourceType = "Group dungeon", short = "(GD) Spindleclutch I", complete = true },
    [139] = { long = "All bosses in Sanguine’s Demense public dungeon", sourceType = "Public dungeon", short = "(PD) Sanguine's Demense", complete = true },
    [140] = { long = "All bosses in Imperial City sewers", sourceType = "World boss", short = "(WB) All sewer bosses", complete = true },
    [141] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [142] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [143] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [144] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [145] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [146] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [147] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [148] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [149] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [150] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [151] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [152] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [153] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [154] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [155] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [156] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [157] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [158] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [159] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [160] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [161] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [162] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [163] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [164] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [165] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [166] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [167] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [168] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [169] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [170] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [171] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [172] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [173] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [174] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [175] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [176] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [177] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [178] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [179] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [180] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [181] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [182] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [183] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [184] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [185] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [186] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [187] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [188] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [189] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [190] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [191] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [192] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [193] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [194] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [195] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [196] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [197] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [198] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [199] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [200] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [204] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [205] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [206] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [207] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [208] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [209] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [213] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [214] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [215] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [216] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [217] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [218] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [219] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [220] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [221] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [222] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [223] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [224] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [225] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [226] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [227] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [228] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [229] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [230] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [231] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [232] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [233] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [234] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [235] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [236] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [237] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [238] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [239] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [240] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [241] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [242] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [243] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [244] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [245] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [246] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [247] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [248] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [249] = { long = "All bosses and random mobs in Old Orsinium public dungeon", sourceType = "Public dungeon", short = "(PD) Old Orsinium", complete = true },
    [250] = { long = "All harvesting nodes", sourceType = "Node", short = "All Harvesting nodes", complete = true },
    [251] = { long = "Wood, Runestone node", sourceType = "Node", short = "Wood,Runestone node", complete = true },
    [252] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [253] = { long = "Mammoth trash mob, Mammoth in Eastmarch, The Rift, Malabal Tor, Wrothgar", sourceType = "Mammoth", short = "Mammoth", complete = true },
    [254] = { long = "Final boss in Arx Corinium", sourceType = "Group dungeon", short = "(GD) Arx Corinium", complete = true },
    [255] = { long = "Gryphons, psijic portals, geysir", sourceType = "Gryphon", short = "Gryphon, psychic, geysir", complete = true },
    [256] = { long = "Ore node, Ore survey node, Jewelry survey", sourceType = "Node", short = "Ore, JC nodes", complete = true },
    [257] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [258] = { long = "Cheydinhal, Vlastrus, Cropsford, Chorrol, Bruma daily rewards", sourceType = "Daily", short = "Town dailies 5x", complete = true },
    [259] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [260] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [261] = { long = "Safeboxes, treasure map chest, thieves trove, resource nodes", sourceType = "Safebox", short = "Special", complete = true },
    [262] = { long = "Treasure chest", sourceType = "Treasure chest", short = "Treasure chest", complete = true },
    [263] = { long = "Mobs (wasp, wolves, Moriseli, Seamount Ghost, Bloodthorn Cultist)", sourceType = "Mob", short = "Mobs", complete = true },
    [264] = { long = "Vampiric Sabrecat, Bear, Bloodknight, mobs in Kyne's Aegis, Castle Thorn, Stone Garden", sourceType = "Mob", short = "Special", complete = false },
    [265] = { long = "Treasure chest", sourceType = "Treasure chest", short = "Treasure chest", complete = true },
    [266] = { long = "Foul bait fishing", sourceType = "Fishing", short = "Foul bait fishing", complete = true },
    [267] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [268] = { long = "Daily reward box in Vvardenfell", sourceType = "Daily", short = "Dailies", complete = true },
    [269] = { long = "Containers like urns and backpacks in Moonlit Cove and Forsaken Citadel, Senchal Dock Urn, random mob southern Elsweyr", sourceType = "Container", short = "Containers", complete = true },
    [270] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [271] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [272] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [273] = { long = "Random mobs", sourceType = "Mob", short = "Random mob", complete = true },
    [274] = { long = "Safebox in Sentinel", sourceType = "Safebox", short = "Safebox", complete = true },
    [275] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [276] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [277] = { long = "All Minotaurs anywhere.  Molag Bal in IC", sourceType = "Minotaurs", short = "Minotaurs", complete = true },
    [278] = { long = "All world bosses", sourceType = "World boss", short = "(WB) all", complete = true },
    [279] = { long = "Battleground rewards of the worthy", sourceType = "BG reward", short = "BG reward", complete = true },
    [280] = { long = "Safeboxes in Narsis, Mournhold (Tribunal Temple), The Kind Enchater, windmill near Muth Gnaar Hills, Dres House", sourceType = "Safebox", short = "Safebox", complete = true },
    [281] = { long = "Psijic portals, enchanting runestones, backback", sourceType = "Node", short = "Psijic, rune nodes", complete = true },
    [282] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [283] = { long = "Psijic portal, enchanting node", sourceType = "Node", short = "Psijic, rune nodes", complete = true },
    [284] = { long = "Safebox", sourceType = "Safebox", short = "Safebox", complete = true },
    [285] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [286] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [287] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [288] = { long = "Drop from dragons", sourceType = "World boss", short = "(WB) Dragons", complete = true },
    [289] = { long = "Symphony of Blades boss in Depths of Malatar", sourceType = "Group dungeon", short = "(GD) Depths of Malatar", complete = true },
    [290] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [291] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [292] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [293] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [294] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [295] = { long = "Drop from dragons", sourceType = "World boss", short = "(WB) Dragons", complete = true },
    [296] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [297] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [298] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [299] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [300] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [301] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [302] = { long = "Reward for completing heist and Thieves Guild dailies. Thieve's Guild small and large laundered shipment containers.", sourceType = "Daily", short = "Thieves Guild dailies", complete = true },
    [303] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [304] = { long = "Gladiators coffer Cyrodiil", sourceType = "Coffer", short = "Cyro gladiator coffers", complete = true },
    [305] = { long = "Gladiators coffer Cyrodiil", sourceType = "Coffer", short = "Cyro gladiator coffers", complete = true },
    [306] = { long = "Gladiators coffer Cyrodiil", sourceType = "Coffer", short = "Cyro gladiator coffers", complete = true },
    [307] = { long = "Chest, mobs in Bthzark, night stand stolen, Pirate in Saintsport, wolves, Assassin Beetle", sourceType = "Mob", short = "Special", complete = true },
    [308] = { long = "Any final boss in Craglorn trials", sourceType = "Trial", short = "Craglorn trials", complete = true },
    [310] = { long = "Curios Coin Collection on the top floor of the Antiquarian Circle (on top of a cabinet that is behind some bookshelves, need to collect all 102 free green, blue and purple treasure zone leads to activate spawn)", sourceType = "Fix location", short = "Curious Coin Collection", complete = true },
    [312] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [313] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [314] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [315] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [316] = { long = "Treasure Maps in The Reach and Western Skyrim", sourceType = "Treasure Maps", short = "Treasure Maps", complete = true },
    [317] = { long = "Treasure Maps in The Reach and Western Skyrim", sourceType = "Treasure Maps", short = "Treasure Maps", complete = true },
    [318] = { long = "Treasure Maps in The Reach and Western Skyrim", sourceType = "Treasure Maps", short = "Treasure Maps", complete = true },
    [319] = { long = "Treasure Maps in The Reach and Western Skyrim", sourceType = "Treasure Maps", short = "Treasure Maps", complete = true },
    [320] = { long = "Treasure Maps in The Reach and Western Skyrim", sourceType = "Treasure Maps", short = "Treasure Maps", complete = true },
    [321] = { long = "Treasure Maps in The Reach and Western Skyrim", sourceType = "Treasure Maps", short = "Treasure Maps", complete = true },
    [322] = { long = "Treasure Maps in The Reach and Western Skyrim", sourceType = "Treasure Maps", short = "Treasure Maps", complete = true },
    [323] = { long = "Treasure Maps in The Reach and Western Skyrim", sourceType = "Treasure Maps", short = "Treasure Maps", complete = true },
    [324] = { long = "Treasure Maps in The Reach and Western Skyrim", sourceType = "Treasure Maps", short = "Treasure Maps", complete = true },
    [325] = { long = "Treasure Maps in The Reach and Western Skyrim", sourceType = "Treasure Maps", short = "Treasure Maps", complete = true },
    [326] = { long = "Treasure Maps in The Reach and Western Skyrim", sourceType = "Treasure Maps", short = "Treasure Maps", complete = true },
    [327] = { long = "Treasure Maps in The Reach and Western Skyrim", sourceType = "Treasure Maps", short = "Treasure Maps", complete = true },
    [328] = { long = "Treasure Maps in The Reach and Western Skyrim", sourceType = "Treasure Maps", short = "Treasure Maps", complete = true },
    [329] = { long = "Treasure Maps in The Reach and Western Skyrim", sourceType = "Treasure Maps", short = "Treasure Maps", complete = true },
    [335] = { long = "Scroll on table in Nighthollow keep. Respawns every 5 minutes.", sourceType = "Fix location", short = "Nighthollow Keep", complete = true },
    [336] = { long = "(PD) Bad Man's Hallow Trash Mob", sourceType = "Public dungeon", short = "(PD) Bad Man's Hallow", complete = true },
    [337] = { long = "Treasure chest", sourceType = "Treasure chest", short = "Treasure chest", complete = true },
    [338] = { long = "Last boss Coldrock Diggings", sourceType = "Delve", short = "(D) Coldrock Diggings", complete = true },
    [339] = { long = "All world bosses", sourceType = "World boss", short = "(WB) all", complete = true },
    [340] = { long = "Safeboxes", sourceType = "Safebox", short = "Safebox", complete = true },
    [341] = { long = "Nerien'eth in Crypt of Hearts 2", sourceType = "Group dungeon", short = "(GD) Crypt of Hearts 2", complete = true },
    [342] = { long = "High Kinlord Rilis.", sourceType = "Group dungeon", short = "(GD)  Banished Cells 1", complete = true },
    [343] = { long = "(PD) Root Sunder Ruins bosses", sourceType = "Group dungeon", short = "(PD) Root Sunder Ruin", complete = true },
    [344] = { long = "All delve bosses", sourceType = "Delve", short = "(D) All", complete = true },
    [345] = { long = "Architron Dwemer Mobs (super low drop chance) (Bthar-Zel, Library of Arkthzand exterior,..)", sourceType = "Mob", short = "Bthar-Zel", complete = true },
    [346] = { long = "Architron Dwemer Mobs (super low drop chance) (Bthar-Zel, Library of Arkthzand exterior,..)", sourceType = "Mob", short = "Bthar-Zel", complete = true },
    [347] = { long = "Architron Dwemer Mobs (super low drop chance) (Bthar-Zel, Library of Arkthzand exterior,..)", sourceType = "Mob", short = "Bthar-Zel", complete = true },
    [348] = { long = "Architron Dwemer Mobs (super low drop chance) (Bthar-Zel, Library of Arkthzand exterior,..)", sourceType = "Mob", short = "Bthar-Zel", complete = true },
    [349] = { long = "Architron Dwemer Mobs (super low drop chance) (Bthar-Zel, Library of Arkthzand exterior,..)", sourceType = "Mob", short = "Bthar-Zel", complete = true },
    [350] = { long = "Architron Dwemer Mobs (super low drop chance) (Bthar-Zel, Library of Arkthzand exterior,..)", sourceType = "Mob", short = "Bthar-Zel", complete = true },
    [351] = { long = "Architron Dwemer Mobs (super low drop chance) (Bthar-Zel, Library of Arkthzand exterior,..)", sourceType = "Mob", short = "Bthar-Zel", complete = true },
    [352] = { long = "Inactive Construct in Blackreach. It is already dead. Over the bridge with a Void Anomaly Teleport. South of the Library of Arkthzand", sourceType = "Fix location", short = "Blackreach", complete = true },
    [353] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [354] = { long = "Drop from harrowstorms", sourceType = "World boss", short = "(WB) Harrowstorms", complete = true },
    [355] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [356] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [357] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [358] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [359] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [360] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [361] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [362] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [363] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [364] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [365] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [366] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [367] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [368] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [369] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [370] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [371] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [372] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [373] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [374] = { long = "On a Argonian stick. West of Rockgrove Trial, North of Skyshard 70.05,90.34", sourceType = "Fix location", short = "Argonian Stick", complete = true },
    [375] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [376] = { long = "Daily Reward Box Leyawiin", sourceType = "Daily", short = "Leyawiin Daily", complete = true },
    [377] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [378] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [379] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [380] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [381] = { long = "Oblivion portal final chest", sourceType = "Oblivion portal", short = "Oblivion portal", complete = true },
    [382] = { long = "All Upper IC Bosses", sourceType = "World boss", short = "(WB) Upper IC", complete = true },
    [383] = { long = "Rewards for the worthy", sourceType = "Rewards worthy", short = "Rewards worthy", complete = true },
    [384] = { long = "Last chest of Dragonstar Arena", sourceType = "Group dungeon", short = "(GD) Dragonstar Arena", complete = true },
    [385] = { long = "Anomalies, Anka-Ra. Final Chests.", sourceType = "World boss", short = "Anomaly, Anka-Ra", complete = true },
    [386] = { long = "(GD) Vault of Madness final Boss", sourceType = "Group dungeon", short = "(GD) Vault of Madness", complete = true },
    [387] = { long = "Drop from harrowstorms", sourceType = "World boss", short = "(WB) Harrowstorms", complete = true },
    [388] = { long = "Hircine Haunt all Bosses", sourceType = "Delve", short = "(D) Hircine's Haunt", complete = true },
    [389] = { long = "(GD) Spindleclutch 2 last boss", sourceType = "Group dungeon", short = "(GD) Spindleclutch II", complete = true },
    [390] = { long = "(PD) Silent Hall: Most likely all Bosses", sourceType = "Public dungeon", short = "(PD) Silent Hall", complete = true },
    [391] = { long = "All World Bosses", sourceType = "World boss", short = "(WB) All", complete = true },
    [392] = { long = "(GD) Mazzatun : Last Boss", sourceType = "Group dungeon", short = "(GD) Mazzatun", complete = true },
    [393] = { long = "All Alchemy Nodes", sourceType = "Node", short = "Alchemy nodes", complete = true },
    [394] = { long = "Foul water fishing", sourceType = "Fishing", short = "Foul water fishing", complete = true },
    [395] = { long = "Covenant Mobs", sourceType = "Mob", short = "Covenant Mobs", complete = true },
    [396] = { long = "(PD) Zenithar's Abbey: All Bosses", sourceType = "Public dungeon", short = "(PD) Zenithar's Abbey", complete = true },
    [397] = { long = "Dark Brotherhood Supply Drop in Outlaw refuges. Requires Skill point", sourceType = "Dark Brotherhood Supply Drop", short = "Dark Brotherhood", complete = true },
    [398] = { long = "(GD) Cradle of Shadows", sourceType = "Group dungeon", short = "(GD) Cradle of Shadows", complete = true },
    [399] = { long = "Bosses in all Delves", sourceType = "Delve", short = "(D) All", complete = true },
    [400] = { long = "(PD) Forgotten Crypt: All Bosses", sourceType = "Public dungeon", short = "(PD) Forgotten Crypt", complete = true },
    [401] = { long = "Ruined Hut SW of Stonewastes Wayshrine (59.67,78.86)", sourceType = "Fix location", short = "Ruined Hut", complete = true },
    [402] = { long = "West of Vunalk delve behind a large shrine in a long tunnel located (30.75,36.99)", sourceType = "Fix location", short = "Behind shrine", complete = true },
    [403] = { long = "In Stonewastes Village in dilapitated building upper floor. have to jump (63.90,79.83)", sourceType = "Fix location", short = "Dilapitated building", complete = true },
    [404] = { long = "In Gulley SSE of The Shattered Xanmeer WB (58.30,85.59)", sourceType = "Fix location", short = "Gulley", complete = true },
    [405] = { long = "Beside Skeleton SE of Leyawin Bridge (30.75,57.69)", sourceType = "Fix location", short = "Skeleton", complete = true },
    [406] = { long = "South of Glenbridge beside tent (66.41,67.52)", sourceType = "Fix location", short = "Beside tent", complete = true },
    [407] = { long = " S-E of Tidewater Cave by tree with Crate, Close to boat (31.74,70.04)", sourceType = "Fix location", short = "Tree", complete = true },
    [408] = { long = "North of Vunalk Delve in House on Island (81.29,63.49)", sourceType = "Fix location", short = "House on Island", complete = true },
    [409] = { long = "North of Silent Halls PD Icon in hole near wheelbarrow (57.91,62.90)", sourceType = "Fix location", short = "Wheelbarrow", complete = true },
    [410] = { long = "Dilapitated Building S-E Xeemhok Lagoon WB (81.66,79.33)", sourceType = "Fix location", short = "Dilapitated building", complete = true },
    [411] = { long = "Ruined Cart S-E of Blueblood wayshrine (37.42,67.77)", sourceType = "Fix location", short = "Ruined Cart", complete = true },
    [412] = { long = "castle ruins north of Gideon, east side, down through the trap - Duchess's Private study (56.60,45.35)", sourceType = "Fix location", short = "Hideout", complete = true },
    [413] = { long = "Boat N-W of Xi-Tsei Delve (48.92,75.55)", sourceType = "Fix location", short = "Boat", complete = true },
    [414] = { long = "In cave, NW of Undertow Cavern (17.13,47.40)", sourceType = "Fix location", short = "Cave", complete = true },
    [415] = { long = "South of White Stallion Inn (20.74,45.74)", sourceType = "Fix location", short = "S White Stallion", complete = true },
    [416] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [417] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [418] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [419] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [420] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [421] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [422] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [423] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [424] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [425] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [426] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [427] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [428] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [429] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [430] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = false },
    [431] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = false },
    [432] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = false },
    [433] = { long = "Safebox", sourceType = "Safebox", short = "Safebox", complete = false },
    [434] = { long = "Roaming bosses", sourceType = "World boss", short = "Roaming bosses", complete = false },
    [435] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [436] = { long = "Unusual Metal node beneath thin dead tree north of Wretched Spire wayshrine (81.29,42.29)", sourceType = "Fix location", short = "Unusual Metal Node", complete = false },
    [437] = { long = "(WB)  The Abomination Circle", sourceType = "World boss", short = "(WB) The Abomination Circle", complete = false },
    [438] = { long = "Daedras anywhere", sourceType = "All loot tables", short = "Daedras", complete = false },
    [439] = { long = "Safebox", sourceType = "Safebox", short = "Safebox", complete = false },
    [440] = { long = "(WB) Shivering Shrine", sourceType = "World boss", short = "(WB) Shivering Shrine", complete = false },
    [441] = { long = "Clannfear", sourceType = "Mob", short = "Clannfear", complete = false },
    [442] = { long = "(WB) Unmaker", sourceType = "World boss", short = "(WB) Unmaker", complete = false },
    [443] = { long = "(GD) Banished Cells I&II", sourceType = "Group dungeon", short = "(GD) Banished Cells I&II", complete = false },
    [444] = { long = "Deadlands Dailies", sourceType = "Daily", short = "Deadlands Dailies", complete = false },
    [445] = { long = "Daedrats", sourceType = "Mob", short = "Daedrats", complete = false },
    [446] = { long = "Treasure Chest", sourceType = "Treasure chest", short = "Treasure Chest", complete = false },
    [447] = { long = "Deadlands Dailies", sourceType = "Daily", short = "Deadlands Dailies", complete = false },
    [448] = { long = "(GD) Falkreath Hold Chests", sourceType = "Group dungeon", short = "(GD) Falkreath Hold Chests", complete = false },
    [449] = { long = "(GD) Black Drake Villa", sourceType = "Group dungeon", short = "(GD) Black Drake Villa", complete = false },
    [450] = { long = "Gold Coast Treasure Chest", sourceType = "Treasure chest", short = "Treasure Chest", complete = false },
    [451] = { long = "(WB) Tribune's Folly", sourceType = "World boss", short = "(WB) Tribune's Folly", complete = false },
    [452] = { long = "(PD) Atoll of Immolation (Portalevent)", sourceType = "Public dungeon", short = "(PD) Atoll of Immolation", complete = false },
    [453] = { long = "Runestone", sourceType = "Node", short = "Runestone", complete = false },
    [460] = { long = "Psijic portals", sourceType = "Node", short = "Psijic portals", complete = false },
    [461] = { long = "Safebox", sourceType = "Safebox", short = "Safebox", complete = false },
    [462] = { long = "(Trial) Sunspire (Dragons)", sourceType = "Trial", short = "(Trial) Sunspire", complete = true },
    [463] = { long = "(GD) Moongrave Fane Adds", sourceType = "Group dungeon", short = "(GD) Moongrave Fane Adds", complete = true },
    [464] = { long = "(GD) Lair of Maarselok, last boss", sourceType = "Group dungeon", short = "(GD) Lair of Maarselok", complete = true },
    [465] = { long = "Watchlings inside Portals (Atoll of Immolation)", sourceType = "Mob", short = "Watchlings inside Portals", complete = true },
    [466] = { long = "(GD) Imperial City Prison (Watcher Boss)", sourceType = "Group dungeon", short = "(GD) Imperial City Prison", complete = true },
    [467] = { long = "Clothing node", sourceType = "Node", short = "Clothing node", complete = true },
    [468] = { long = "Watcher Mobs", sourceType = "Mob", short = "Watcher Mobs", complete = true },
    [469] = { long = "(PD) Treasure Chests inside the Vile Manse Public Dungeon", sourceType = "Public dungeon", short = "(PD) Vile Manse", complete = true },
    [470] = { long = "Daily Crafting Writ", sourceType = "Daily", short = "Daily Crafting Writ", complete = true },
    [471] = { long = "Shell Trove from Geysers", sourceType = "World boss", short = "Geysers", complete = true },
    [472] = { long = "(WB) Mornard Falls", sourceType = "World boss", short = "(WB) Mornard Falls", complete = true },
    [473] = { long = "Reef Viper, Lesser Sea Adder", sourceType = "Mob", short = "Reef Viper/Adder", complete = true },
    [474] = { long = "Treasure Chest", sourceType = "Treasure chest", short = "Treasure Chest", complete = true },
    [475] = { long = "(WB) Serpent Bog", sourceType = "World boss", short = "(WB) Serpent Bog", complete = true },
    [476] = { long = "JC Survey", sourceType = "Survey", short = "JC Survey", complete = true },
    [477] = { long = "Giant Clam", sourceType = "Node", short = "Giant Clam", complete = true },
    [478] = { long = "Mage Guild Dailies", sourceType = "Daily", short = "Mage Guild Dailies", complete = true },
    [479] = { long = "(WB) Frozen Ruins", sourceType = "World boss", short = "(WB) Frozen Ruins", complete = true },
    [480] = { long = "Safebox", sourceType = "Safebox", short = "Safebox", complete = true },
    [481] = { long = "(WB) Mudcrab Beach / Titanclaw", sourceType = "World boss", short = "(WB) Mudcrab Beach", complete = true },
    [482] = { long = "Ore Nodes", sourceType = "Node", short = "Ore Nodes", complete = true },
    [483] = { long = "Random Mob", sourceType = "Mob", short = "Random Mob", complete = true },
    [484] = { long = "Volcanic Vents", sourceType = "World boss", short = "Volcanic Vents", complete = true },
    [485] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [486] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [487] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [488] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [489] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [490] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [491] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [492] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [493] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [494] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [495] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [496] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [497] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [498] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [499] = { long = "'Old Pot' at the intersection of waterways, northeast of Amenos Station", sourceType = "Fix location", short = "Amenos: Tiny islet", complete = true },
    [500] = { long = "'Textured Bowl' in the ruins built into the cliff, south of the east entrance to the Hidden Foundry", sourceType = "Fix location", short = "Amenos: Ruins at cliff base", complete = true },
    [501] = { long = "'Rusty Food Handling Tongs' on wrecked ship near the tall pole in the water, in the cove north of Skulltooth Coast", sourceType = "Fix location", short = "Amenos: N of Skulltooth", complete = true },
    [502] = { long = "'Time-Worn Stone' on northeast shore of All-Flags Islet, sheltered from the land by a tall crescent-shaped time-worn stone", sourceType = "Fix location", short = "All-Flags Islet", complete = true },
    [503] = { long = "'Olden Breton Teapot' on south shore of inlet south of Death's Valley Keep Delve", sourceType = "Fix location", short = "Inlet S of Death's Valley", complete = true },
    [504] = { long = "'Damaged Woven Strainer' next to a large tree just off the road, East of the Castle Navire Wayshrine", sourceType = "Fix location", short = "Near Castle Navire", complete = true },
    [505] = { long = "'Blazing Stones' behind the rocks in a fiery druidic circle, south of Dufort Shipyards Wayshrine", sourceType = "Fix location", short = "S of Dufort Shipyards", complete = true },
    [506] = { long = "Go west from Tor Draoich vent, then left to tree with flowers for 'Druidic Butcher's Knife'", sourceType = "Fix location", short = "W of Tor Draioch vent", complete = true },
    [507] = { long = "'Ancient Cleaning Tools' in the cliffs overlooking the sea, north of Garick's Rest", sourceType = "Fix location", short = "Near Garick's Rest", complete = true },
    [508] = { long = "'Stained Water Jug' next to driftwood on the beach, west of Spriggan's Crown", sourceType = "Fix location", short = "W of Spriggan's Crown", complete = true },
    [509] = { long = "'Druidic Arrows' nestled in the rocks near a tall tree, on the E side of a waterfall, N of Banished Refuge. Guarded by an imp. 5 MIN RESPAWN", sourceType = "Fix location", short = "Amenos: Waterfall", complete = true },
    [510] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [511] = { long = "(Trial) Dreadsail Reef", sourceType = "Trial", short = "(T) Dreadsail Reef", complete = true },
    [512] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [513] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [514] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [515] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [516] = { long = "Unknown", sourceType = "Unknown", short = "Unknown", complete = false },
    [517] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [518] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [519] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [520] = { long = "(WB) Faun Falls", sourceType = "World boss", short = "(WB) Faun Falls", complete = true },
    [521] = { long = "(PD) Obsidian Scar", sourceType = "Public dungeon", short = "(PD) Obsidian Scar", complete = true },
    [522] = { long = "Thieves Trove, Safebox", sourceType = "Thieves Trove", short = "Thieves Trove, Safebox", complete = true },
    [523] = { long = "Wood Nodes", sourceType = "Node", short = "Wood Nodes", complete = true },
    [524] = { long = "(D) Whalefall, Boss and Hunters", sourceType = "Delve", short = "(D) Whalefall", complete = true },
    [525] = { long = "Volcanic Vents", sourceType = "World boss", short = "Volcanic Vents", complete = true },
    [526] = { long = "Clothing, Alchemy Nodes", sourceType = "Node", short = "Clothing, Alchemy Nodes", complete = true },
    [527] = { long = "Daily Reward Coffer", sourceType = "Daily", short = "Daily Reward Coffer", complete = true },
    [528] = { long = "(PD) Group Event Boss in Toothmaul Gully", sourceType = "Public dungeon", short = "(PD) Toothmaul Gully", complete = true },
    [529] = { long = "(WB) Valley of the Watcher", sourceType = "World boss", short = "(WB) Valley of the Watcher", complete = true },
    [530] = { long = "Daily Blacksmithing Writs", sourceType = "Daily", short = "Daily Blacksmithing Writs", complete = true },
    [531] = { long = "(GD) Banished Cells II", sourceType = "Group dungeon", short = "(GD) Banished Cells II", complete = true },
    [532] = { long = "Fishing", sourceType = "Fishing", short = "Fishing", complete = true },
    [533] = { long = "(GD) Shipright's Regret", sourceType = "Group dungeon", short = "(GD) Shipright's Regret", complete = true },
    [534] = { long = "(WB) Indrik Frolik", sourceType = "World boss", short = "(WB) Indrik Frolik", complete = true },
    [535] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [536] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = true },
    [537] = { long = "(PD) Ghost Haven Bay Group Event", sourceType = "Public dungeon", short = "(PD) Ghost Haven Bay", complete = false },
    [538] = { long = "(PD) Forgotten Wastes", sourceType = "Public dungeon", short = "(PD) Forgotten Wastes", complete = true },
    [539] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [540] = { long = "(WB) Preserver of Galen", sourceType = "World boss", short = "(WB) Preserver of Galen", complete = true },
    [541] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = true },
    [542] = { long = "Volcanic Vent, (PD) Lost City of the Na-Totambu (Alik'r Desert)", sourceType = "Public dungeon", short = "multiple", complete = true },
    [543] = { long = "Daily Reward Coffer", sourceType = "Daily", short = "Daily Reward Coffer", complete = true },
    [544] = { long = "(WB) Desuuga the Siren", sourceType = "World boss", short = "(WB) Desuuga the Siren", complete = true },
    [545] = { long = "Treasure chest", sourceType = "Treasure chest", short = "Treasure chest", complete = true },
    [546] = { long = "(GD) Wayrest sewers 1", sourceType = "Group dungeon", short = "(GD) Wayrest sewers 1", complete = true },
    [547] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [548] = { long = "Thieves Trove, Daily Reward", sourceType = "Daily", short = "Thieves Trove, Daily Reward", complete = true },
    [549] = { long = "(GD) Wayrest Sewers 2", sourceType = "Group dungeon", short = "(GD) Wayrest Sewers 2", complete = true },
    [550] = { long = "Volcanic Vents", sourceType = "World boss", short = "Volcanic Vents", complete = true },
    [551] = { long = "(WB) Grove of the Chimera", sourceType = "World boss", short = "(WB) Grove of the Chimera", complete = true },
    [552] = { long = "(D) Faun's Thicket", sourceType = "Delve", short = "(D) Faun's Thicket", complete = true },
    [553] = { long = "Daily Reward Coffer", sourceType = "Daily", short = "Daily Reward Coffer", complete = true },
    [554] = { long = "(GD) City of Ash 1: Last Boss", sourceType = "Group dungeon", short = "(GD) City of Ash 1: Last Boss", complete = true },
    [555] = { long = "(D) Embervine", sourceType = "Delve", short = "(D) Embervine", complete = true },
    [556] = { long = "Phoenix Moth, Magma Frog", sourceType = "Mob", short = "Phoenix Moth, Magma Frog", complete = true },
    [557] = { long = "(GD) Bal Sunnar Final Boss", sourceType = "Group dungeon", short = "(GD) Bal Sunnar", complete = false },
    [558] = { long = "(WB) Clamorclap Bowl", sourceType = "World boss", short = "(WB) Clamorclap Bowl", complete = false },
    [559] = { long = "(D)  Disquiet Study Boss", sourceType = "Delve", short = "(D) Disquiet Study", complete = false },
    [560] = { long = "Treasure chest", sourceType = "Treasure chest", short = "Treasure chest", complete = false },
    [561] = { long = "Daily Reward Box", sourceType = "Daily", short = "Daily Reward Box", complete = false },
    [562] = { long = "(D) Nchuleft", sourceType = "Delve", short = "(D) Nchuleft", complete = false },
    [563] = { long = "(GD) Graven Deep Secret Boss 1,2&3", sourceType = "Group dungeon", short = "(GD) Graven Deep", complete = false },
    [564] = { long = "(GD) Coral Aerie lase secret Boss", sourceType = "Group dungeon", short = "(GD) Coral Aerie", complete = false },
    [565] = { long = "(PD) Forgotten Wastes, Nchuleftingth Group Boss", sourceType = "Public dungeon", short = "(PD) Both Group Boss", complete = false },
    [566] = { long = "(PD) Gorne Group Event", sourceType = "Public dungeon", short = "(PD) Gorne Group Event", complete = false },
    [567] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [568] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [569] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [570] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [571] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [573] = { long = "(D) Camonnaruhn Boss", sourceType = "Delve", short = "(D) Connamaruhn", complete = false },
    [574] = { long = "(GD) Scriverner's Hall Vault Treasure Chests", sourceType = "Group dungeon", short = "(GD) Scriverner's Hall Vault Chests", complete = false },
    [575] = { long = "(WB) Runemaster's Acropolis", sourceType = "World boss", short = "(WB) Runemaster's Acropolis", complete = false },
    [576] = { long = "(PD) Underweave Bosses", sourceType = "Public dungeon", short = "(PD) Underweave", complete = false },
    [577] = { long = "Innkeeper, general merchant. Requiers Pathfinder", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [578] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [579] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [580] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [581] = { long = "Bastion Nymic Harmeus Mora Miniboss Chest", sourceType = "Bastion Nymic", short = "Bastion Nymic chest", complete = false },
    [582] = { long = "Fishing", sourceType = "Fishing", short = "Fishing", complete = false },
    [583] = { long = "Fungal Grotto 2: Last Boss", sourceType = "Group dungeon", short = "Fungal Grotto 2", complete = false },
    [584] = { long = "(D) Matus-Akin Egg Mine", sourceType = "Delve", short = "(D) Matus-Akin Egg Mine", complete = false },
    [585] = { long = "(WB) Deepreave Quag", sourceType = "World boss", short = "(WB) Deepreave Quag", complete = false },
    [586] = { long = "Runestone", sourceType = "Node", short = "Runestone", complete = false },
    [587] = { long = "Daily Writs", sourceType = "Daily", short = "Daily Writs", complete = false },
    [588] = { long = "(WB) The Prime Cataloger", sourceType = "World boss", short = "(WB) The Prime Cataloger", complete = false },
    [589] = { long = "Bastion Nymic Boss", sourceType = "World boss", short = "Bastion Nymic Boss", complete = false },
    [591] = { long = "(D) Anchre Egg Mine Boss", sourceType = "Delve", short = "(D) Anchre Egg Mine", complete = false },
    [592] = { long = "Wood Nodes", sourceType = "Node", short = "Wood Nodes", complete = false },
    [593] = { long = "(D) Lady Llarel Shelter", sourceType = "Delve", short = "(D) Lady Llarel Shelter", complete = false },
    [594] = { long = "(GD) Fungal Grotto I Endboss", sourceType = "Group dungeon", short = "(GD) Fungal Grotto I", complete = false },
    [595] = { long = "Bastion Nymic Boss", sourceType = "World boss", short = "Bastion Nymic Boss", complete = false },
    [596] = { long = "(WB) Chthon Plaza", sourceType = "World boss", short = "(WB) Chthon Plaza", complete = false },
    [597] = { long = "Daily Delve Reward Coffer", sourceType = "Daily", short = "Daily Delve Reward Coffer", complete = false },
    [598] = { long = "(WB) Risen Court", sourceType = "World boss", short = "(WB) Risen Court", complete = false },
    [599] = { long = "(D) Fathms Drift", sourceType = "Delve", short = "(D) Fathms Drift", complete = false },
    [600] = { long = "Safebox, Thieves Trove", sourceType = "Safebox, Thieves Trove", short = "Safebox, Thieves Trove", complete = false },
    [601] = { long = "Innkeeper, general merchant. Requiers Hero of Necrom Achievement", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [602] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = false },
    [603] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = false },
    [604] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = false },
    [605] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = false },
    [606] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = false },
    [607] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = false },
    [608] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = false },
    [609] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = false },
    [610] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = false },
    [611] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = false },
    [612] = { long = "(D) Quires Wind Boss", sourceType = "Delve", short = "(D) Quires Wind", complete = false },
    [613] = { long = "(WB) Nightmare Den", sourceType = "World boss", short = "(WB) Nightmare Den", complete = false },
    [614] = { long = "(D) Halls of Regulation", sourceType = "Delve", short = "(D) Halls of Regulation", complete = false },
    [615] = { long = "South of Lavapool between Alavelis and Padomaic wayshrines", sourceType = "Fix location", short = "SW of Padomaic WS", complete = false },
    [616] = { long = "After bridge towards Kemel-Ze, right side", sourceType = "Fix location", short = "Towards Kemel-Ze", complete = false },
    [617] = { long = "NE of Ald Edra. Between town and water.", sourceType = "Fix location", short = "NE of Ald Edra", complete = false },
    [618] = { long = "Coast S of Nigthmare Den WB", sourceType = "Fix location", short = "Coast S of Nighmare Den", complete = false },
    [619] = { long = "To the right of Keml-Ze there's 3 islands (smallest one). Look for small urn", sourceType = "Fix location", short = "Island E of Kemel-Ze", complete = false },
    [620] = { long = "South of Padomaic wayshrine , along cliff side wall", sourceType = "Fix location", short = "S of Padomaic WS", complete = false },
    [621] = { long = "Between Talavelis and Sanity Edge Trial Entrance", sourceType = "Fix location", short = "SW of Talavelis", complete = false },
    [622] = { long = "Biggest Island South of Bal Isra", sourceType = "Fix location", short = "Island S of Bal Isra", complete = false },
    [623] = { long = "Coast North of Sailenmora", sourceType = "Fix location", short = "Coast N of Sailenmora", complete = false },
    [624] = { long = "North of Padomaic Crest wayshrine, follow river east. Hidden along rocks ( right side )", sourceType = "Fix location", short = "N of Padomaic Crest WS", complete = false },
    [625] = { long = "Tales of Tribute Coffer", sourceType = "Tales of Tribute", short = "Tales of Tribute Coffer", complete = false },
    [626] = { long = "(D) Apogee of the Tormenting Eye Boss", sourceType = "Delve", short = "(D) Apogee of the Tormenting Eye", complete = false },
    [627] = { long = "Bastion Nymic Reward Box", sourceType = "Daily", short = "Bastion Nymic Reward Box", complete = false },
    [628] = { long = "(D) Zthenganaz", sourceType = "Delve", short = "(D) Zthenganaz", complete = false },
    [629] = { long = "Anything and everything. Up to and including trials", sourceType = "Anything and everything. Up to and including trials", short = "Anything and everything. Up to and including trials", complete = false },
    [630] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [631] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [632] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [633] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = false },
    [634] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = false },
    [635] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = false },
    [636] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = false },
    [637] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = false },
    [638] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = false },
    [639] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = false },
    [640] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = false },
    [641] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = false },
    [642] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = false },
    [643] = { long = "Anything and everything. Up to and including trials", sourceType = "All loot tables", short = "All loot tables", complete = false },
    [644] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [645] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [646] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [647] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [648] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [649] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [650] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [651] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [652] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [653] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [654] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [655] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [656] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [657] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [658] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [659] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [660] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [661] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [662] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [663] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [664] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [665] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [666] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [667] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [668] = { long = "Endless Archive", sourceType = "Endless Archive", short = "Endless Archive", complete = false },
    [669] = { long = "(D)  Fort Colovia Boss", sourceType = "Delve", short = "(D)  Fort Colovia", complete = false },
    [670] = { long = "(PD) Rkindaleft", sourceType = "Public dungeon", short = "(PD) Rkindaleft", complete = false },
    [671] = { long = "(GD) Volenfell Dungeon last boss", sourceType = "Group dungeon", short = "(GD) Volenfell Dungeon last boss", complete = false },
    [672] = { long = "(D) Sankti", sourceType = "Delve", short = "(D) Sankti", complete = false },
    [673] = { long = "(T) Halls of Fabrication Final Boss", sourceType = "Trial", short = "(T) Halls of Fabrication", complete = false },
    [674] = { long = "(D) Haldain Lumber Camp boss", sourceType = "Delve", short = "(D) Haldain Lumber Camp", complete = false },
    [675] = { long = "(WB) Centurion's Rise", sourceType = "World boss", short = "(WB) Centurion's Rise", complete = false },
    [676] = { long = "Shell Trove from Geysers", sourceType = "World boss", short = "Geysers", complete = false },
    [677] = { long = "(GD) Moongrave Fane", sourceType = "Group dungeon", short = "(GD) Moongrave Fane", complete = false },
    [678] = { long = "(PD) Orcrest Group Boss", sourceType = "Public dungeon", short = "(PD) Orcrest", complete = false },
    [679] = { long = "(D) Sheogorath's Tongue", sourceType = "Delve", short = "(D) Sheogorath's Tongue", complete = false },
    [680] = { long = "Dolmen", sourceType = "Dolmen", short = "Dolmen", complete = false },
    [681] = { long = "(WB)  Lesser Circle", sourceType = "World boss", short = "(WB)  Lesser Circle", complete = false },
    [682] = { long = "Maelstrom Arena Chest in 1st Arena", sourceType = "Maelstrom Arena", short = "Maelstrom Arena", complete = false },
    [683] = { long = "(PD) Vile Manse: Sergeant Atilus", sourceType = "Public dungeon", short = "(PD) Vile Manse", complete = false },
    [684] = { long = "Zone starting lead", sourceType = "Starter", short = "Built-in", complete = true },
    [685] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [686] = { long = "Reward for excavating previous level treasure lead", sourceType = "Excavation reward", short = "Excavation reward", complete = true },
    [687] = { long = "Innkeeper, general merchant. Requiers Pathfinder Achievement", sourceType = "Vendor", short = "Innkeeper, general merchant", complete = true },
    [688] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = false },
    [689] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = false },
    [690] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = false },
    [691] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = false },
    [692] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = false },
    [693] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = false },
    [694] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = false },
    [695] = { long = "Anything and everything. Up to and including trials", sourceType = "Anything and everything. Up to and including trials", short = "Anything and everything. Up to and including trials", complete = false },
    [696] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = false },
    [697] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = false },
    [698] = { long = "Treasure map chest", sourceType = "Treasure map", short = "Treasure map", complete = false },
    [699] = { long = "(PD) Silorn", sourceType = "Public dungeon", short = "(PD) Silorn", complete = false },
    [700] = { long = "(WB) Lake Olo", sourceType = "World boss", short = "(WB) Lake Olo", complete = false },
    [701] = { long = "(D) Fyrelight Cave", sourceType = "Delve", short = "(D) Fyrelight Cave", complete = false },
    [702] = { long = "(D) Nonungalo: Shattered Shard Mobs", sourceType = "Delve", short = "(D) Nonungalo", complete = false },
    [703] = { long = "(WB) Falls Glade", sourceType = "World boss", short = "(WB) Falls Glade", complete = false },
    [704] = { long = "(D) Varen's Watch", sourceType = "Delve", short = "(D) Varen's Watch", complete = false },
    [705] = { long = "Daily Reward Coffer", sourceType = "Daily", short = "Daily Reward Coffer", complete = false },
    [706] = { long = "(PD) Leftwheel Trading Post: Yrrkkyyn, Xvarcon", sourceType = "Public dungeon", short = "(PD) Leftwheel Trading Post", complete = false },
    [707] = { long = "Mirrormoor Incursions", sourceType = "Mirrormoor Incursions", short = "Mirrormoor Incursions", complete = false },
    [708] = { long = "(D) Legion's Rest", sourceType = "Delve", short = "(D) Legion's Rest", complete = false },
}
D.findZoneOverrides = {
    [99] = 101010,
    [100] = 101010,
    [101] = 101010,
    [114] = 101012,
    [119] = 181,
    [134] = 584,
    [140] = 584,
    [253] = 101010,
    [258] = 181,
    [278] = 584,
    [279] = 101011,
    [287] = 101010,
    [290] = 101014,
    [297] = 101014,
    [304] = 181,
    [305] = 181,
    [306] = 181,
    [316] = 101015,
    [317] = 101015,
    [318] = 101015,
    [319] = 101015,
    [320] = 101015,
    [321] = 101015,
    [322] = 101015,
    [323] = 101015,
    [324] = 101015,
    [325] = 101015,
    [326] = 101015,
    [327] = 101015,
    [328] = 101015,
    [329] = 101015,
    [382] = 584,
    [383] = 181,
    [384] = 888,
    [385] = 888,
    [386] = 347,
    [387] = 1207,
    [388] = 888,
    [389] = 3,
    [392] = 117,
    [393] = 117,
    [394] = 726,
    [395] = 281,
    [397] = 101010,
    [398] = 117,
    [399] = 117,
    [400] = 57,
    [438] = 101010,
    [439] = 1261,
    [440] = 41,
    [441] = 101010,
    [443] = 381,
    [446] = 347,
    [448] = 888,
    [449] = 823,
    [450] = 823,
    [451] = 823,
    [460] = 1133,
    [461] = 1086,
    [462] = 1086,
    [463] = 1086,
    [464] = 383,
    [465] = 1286,
    [466] = 584,
    [467] = 1286,
    [469] = 382,
    [471] = 1011,
    [474] = 104,
    [476] = 101010,
    [479] = 103,
    [480] = 726,
    [481] = 19,
    [482] = 3,
    [483] = 58,
    [520] = 1318,
    [521] = 20,
    [522] = 101017,
    [523] = 101017,
    [524] = 1318,
    [525] = 101017,
    [528] = 381,
    [534] = 1011,
    [537] = 1318,
    [538] = 849,
    [544] = 20,
    [545] = 101017,
    [562] = 849,
    [565] = 849,
    [572] = 849,
    [584] = 849,
    [593] = 57,
    [598] = 347,
    [614] = 980,
    [628] = 684,
    [670] = 684,
    [671] = 104,
    [672] = 104,
    [673] = 849,
    [676] = 1011,
    [677] = 1086,
    [678] = 1086,
    [679] = 41,
    [680] = 101010,
    [681] = 104,
    [682] = 684,
    [683] = 382,
}
D.specialFindZones = {
    [101010] = { label = "All zones", zones = {} },
    [101011] = { label = "Battlegrounds", zones = {} },
    [101012] = { label = "Artaeum / Summerset", zones = { 1027, 1011 } },
    [101013] = { label = "Eastmarch / The Rift", zones = { 101, 103 } },
    [101014] = { label = "Cyrodiil / Imperial City", zones = { 181, 584 } },
    [101015] = { label = "The Reach / Western Skyrim", zones = { 1207, 1160, 1208, 1161 } },
    [101016] = { label = "Unknown", zones = {} },
    [101017] = { label = "Galen / High Isle", zones = { 1383, 1318 } },
    [101018] = { label = "Necrom", zones = { 1414, 1413 } },
}
D.recordCount = 668
D.findZoneOverrideCount = 106
