TetsuArcanistCrux = TetsuArcanistCrux or {}
local L = TetsuArcanistCrux.L
if not L then return end

L.TITLE = "|cFFD700Tetsu's|r Arcanist Crux Tracker"

L.INFO_LABEL = "Info"
L.INFO_TT = "Zählt Arkanisten-Crux. Symbole, Ziffer und Farbe auf Crux-Verbrauchern können gleichzeitig an sein.\nTon nur beim Wechsel 2→3.\nGold / Bugs: Post an @Tetsurion."

L.SHOW_ICONS = "Symbole zeigen"
L.SHOW_ICONS_TT = "1–3 offizielle Crux-Runen. Anordnung im Abschnitt Symbole."

L.SHOW_NUMBER = "Ziffer zeigen"
L.SHOW_NUMBER_TT = "Ziffer 0–3. Standard in der Bildmitte. Standardmäßig aus."

L.SHOW_BAR = "Crux-Verbraucher färben"
L.SHOW_BAR_TT = "Overlay auf jedem Skill, der Crux verbraucht. Bei 0–1 versteckt. Färbt das Skill-Icon nicht um."

L.COMBAT_ONLY = "Nur im Kampf"
L.COMBAT_ONLY_TT = "An = Symbole, Ziffer und Balkenfarbe außerhalb des Kampfs aus. Vorschau im Menü bleibt."

L.COLOR2 = "Farbe bei 2 Crux"
L.COLOR2_TT = "Für Symbole, Ziffer und Balken. Standard gelb."

L.COLOR3 = "Farbe bei 3 Crux"
L.COLOR3_TT = "Für Symbole, Ziffer und Balken. Standard rot."

L.SOUND_ENABLE = "Ton bei 3 Crux"
L.SOUND_ENABLE_TT = "Einmal beim Wechsel 2→3. Nicht bei jedem Tick auf 3."

L.SOUND_PICK = "Ton"
L.SOUND_PICK_TT = "Eingebauter Spielton. Läuft über die Interface-Lautstärke."

L.SOUND_VOL = "Tonlautstärke"
L.SOUND_VOL_TT = "Wie oft der Ton gestapelt wird (0 = still, 5 = am lautesten). Kein echter Mixer."

L.SOUND_KILL = "Todesstoß"
L.SOUND_DUEL = "Duellstart"
L.SOUND_ALERT = "Alarm"
L.SOUND_NOTIFY = "Hinweis"
L.SOUND_DISCOVER = "Ziel gefunden"
L.SOUND_RUNE = "Potenzrune"
L.SOUND_GLYPH = "Glyphe entfernt"
L.SOUND_QUEST = "Questfortschritt"
L.SOUND_LEVEL = "Stufenaufstieg"
L.SOUND_MAIL = "Neue Post"
L.SOUND_SKILL = "Fertigkeit erhalten"
L.SOUND_LOCK = "Schloss geknackt"
L.SOUND_READY = "Bereitschaftsprüfung"
L.SOUND_TICK = "Countdown-Tick"
L.SOUND_BGMIN = "Schlachtfeld 1 Min."
L.SOUND_BGGO = "Schlachtfeld-Start"
L.SOUND_TRIALOK = "Prüfung geschafft"
L.SOUND_TRIALNO = "Prüfung gescheitert"
L.SOUND_ACHIEVE = "Erfolg"
L.SOUND_SKY = "Himmelsfragment"
L.SOUND_QDONE = "Quest abgeschlossen"
L.SOUND_QACC = "Quest angenommen"
L.SOUND_CHAMP = "Championpunkte"
L.SOUND_ABIL = "Fähigkeit freigeschaltet"
L.SOUND_COLL = "Sammelobjekt"
L.SOUND_BOOK = "Buch erhalten"
L.SOUND_ESS = "Essenzrune"
L.SOUND_ASP = "Aspektrune"
L.SOUND_ALC = "Alchemie-Lösungsmittel"
L.SOUND_FRIEND = "Freundeseinladung"
L.SOUND_GJOIN = "Gruppe beigetreten"
L.SOUND_KOS = "Kill on Sight"
L.SOUND_LBREAK = "Dietrich zerbrochen"
L.SOUND_KICK = "Instanz-Kick"
L.SOUND_FANFARE = "Stufen-Fanfare"
L.SOUND_MEDAL = "Schlachtfeld-Medaille"
L.SOUND_SPT = "Fertigkeitspunkt"
L.SOUND_MAP = "Kartenort entdeckt"

L.TEST_ALL = "Alles testen"
L.TEST_ALL_TT = "Zählt 0→1→2→3 auf allen aktiven Anzeigen und spielt den 3er-Ton."
L.TEST_BTN = "Vorschau"

L.SEC_ICONS = "Symbole"
L.SEC_ICONS_TT = "Anordnung, Größe und Position der Runen."

L.ICON_LAYOUT = "Anordnung"
L.ICON_LAYOUT_TT = "Waagerechte Reihe, senkrechte Reihe oder Dreieck um den Punkt."
L.LAYOUT_ROW_H = "Reihe waagerecht"
L.LAYOUT_ROW_V = "Reihe senkrecht"
L.LAYOUT_TRI = "Dreieck am Fadenkreuz"

L.ICON_SIZE = "Symbolgröße"
L.ICON_SIZE_TT = "Pixelgröße jeder Rune."
L.ICON_X = "Symbole X"
L.ICON_X_TT = "0 = Bildmitte. + rechts, − links."
L.ICON_Y = "Symbole Y"
L.ICON_Y_TT = "0 = Bildmitte. + unten, − oben."
L.ICON_RADIUS = "Abstand zur Mitte"
L.ICON_RADIUS_TT = "Nur beim Dreieck. Wie weit die drei Runen vom Ursprung sitzen."
L.ICON_A12 = "Symboldeckkraft bei 1–2"
L.ICON_A12_TT = "Deckkraft der Runen bei 1 oder 2 Crux. Standard 50%."
L.ICON_A3 = "Symboldeckkraft bei 3"
L.ICON_A3_TT = "Deckkraft der Runen bei 3 Crux. Standard 100%."

L.TEST_ICONS = "Symbole testen"
L.TEST_ICONS_TT = "Nur Runen. Zählt 0→3."

L.SEC_NUMBER = "Ziffer"
L.SEC_NUMBER_TT = "Größe und Position der Ziffer 0–3."
L.NUM_SIZE = "Zifferngröße"
L.NUM_SIZE_TT = "Schriftgröße."
L.NUM_A12 = "Zifferndeckkraft bei 1–2"
L.NUM_A12_TT = "Deckkraft der Ziffer bei 1 oder 2 Crux. Standard 50%."
L.NUM_A3 = "Zifferndeckkraft bei 3"
L.NUM_A3_TT = "Deckkraft der Ziffer bei 3 Crux. Standard 100%."
L.NUM_X = "Ziffer X"
L.NUM_X_TT = "0 = Bildmitte. + rechts, − links."
L.NUM_Y = "Ziffer Y"
L.NUM_Y_TT = "0 = Bildmitte. + unten, − oben."
L.TEST_NUMBER = "Ziffer testen"
L.TEST_NUMBER_TT = "Nur Ziffer. Zählt 0→3."

L.SEC_BAR = "Aktionsleiste"
L.SEC_BAR_TT = "Farb-Overlay auf dem Fatecarver-Slot."
L.BAR_A2 = "Leisten-Deckkraft bei 2 Crux"
L.BAR_A2_TT = "Stärke der Platte bei 2 Stapeln."
L.BAR_A3 = "Leisten-Deckkraft bei 3 Crux"
L.BAR_A3_TT = "Stärke der Platte bei 3 Stapeln. Das Skill-Icon bleibt lesbar."
L.TEST_BAR = "Balkenfarbe testen"
L.TEST_BAR_TT = "Overlay auf Fatecarver, sonst auf Skill-Slot 1. Leiste muss sichtbar sein."
