TetsuArcanistCrux = TetsuArcanistCrux or {}
local L = TetsuArcanistCrux.L
if not L then return end

L.TITLE = "|cFFD700Tetsu's|r Arcanist Crux Tracker"

L.INFO_LABEL = "Info"
L.INFO_TT = "Suit les Crux d’arcaniste. Icônes, chiffre et teinte des compétences qui dépensent le Crux.\nSon uniquement au passage 2→3.\nOr / bugs : courrier @Tetsurion."

L.SHOW_ICONS = "Afficher les icônes"
L.SHOW_ICONS_TT = "1–3 runes officielles. Disposition dans la section Icônes."

L.SHOW_NUMBER = "Afficher le chiffre"
L.SHOW_NUMBER_TT = "Chiffre 0–3. Par défaut au centre. Désactivé au départ."

L.SHOW_BAR = "Colorer les compétences à Crux"
L.SHOW_BAR_TT = "Calque sur chaque compétence qui dépense du Crux. Caché à 0–1. Ne recolorie pas l’icône."

L.COMBAT_ONLY = "Uniquement en combat"
L.COMBAT_ONLY_TT = "On = icônes, chiffre et teinte hors combat. L’aperçu du menu reste."

L.COLOR1 = "Couleur à 1 Crux"
L.COLOR1_TT = "Icônes et chiffre. Vert par défaut."

L.COLOR2 = "Couleur à 2 Crux"
L.COLOR2_TT = "Icônes, chiffre et barre. Jaune par défaut."

L.COLOR3 = "Couleur à 3 Crux"
L.COLOR3_TT = "Icônes, chiffre et barre. Rouge par défaut."

L.SOUND_ENABLE = "Son à 3 Crux"
L.SOUND_ENABLE_TT = "Une fois au passage 2→3. Pas à chaque tic à 3."

L.SOUND_PICK = "Son"
L.SOUND_PICK_TT = "Son du jeu. Passe par le volume Interface."

L.SOUND_VOL = "Volume du son"
L.SOUND_VOL_TT = "Combien de fois empiler le son (0 = muet, 5 = plus fort). Pas un vrai mixeur."

L.SOUND_KILL = "Coup de grâce"
L.SOUND_DUEL = "Début de duel"
L.SOUND_ALERT = "Alerte"
L.SOUND_NOTIFY = "Notification"
L.SOUND_DISCOVER = "Objectif trouvé"
L.SOUND_RUNE = "Rune de puissance"
L.SOUND_GLYPH = "Glyphe retiré"
L.SOUND_QUEST = "Progression de quête"
L.SOUND_LEVEL = "Niveau supérieur"
L.SOUND_MAIL = "Nouveau courrier"
L.SOUND_SKILL = "Compétence gagnée"
L.SOUND_LOCK = "Serrure ouverte"
L.SOUND_READY = "Appel de préparation"
L.SOUND_TICK = "Tic du compte à rebours"
L.SOUND_BGMIN = "Champ de bataille 1 min"
L.SOUND_BGGO = "Début du champ de bataille"
L.SOUND_TRIALOK = "Épreuve réussie"
L.SOUND_TRIALNO = "Épreuve échouée"
L.SOUND_ACHIEVE = "Succès"
L.SOUND_SKY = "Éclat céleste"
L.SOUND_QDONE = "Quête terminée"
L.SOUND_QACC = "Quête acceptée"
L.SOUND_CHAMP = "Points Champion"
L.SOUND_ABIL = "Compétence débloquée"
L.SOUND_COLL = "Collectionnable"
L.SOUND_BOOK = "Livre obtenu"
L.SOUND_ESS = "Rune d'essence"
L.SOUND_ASP = "Rune d'aspect"
L.SOUND_ALC = "Solvant d'alchimie"
L.SOUND_FRIEND = "Invitation d'ami"
L.SOUND_GJOIN = "Rejoindre un groupe"
L.SOUND_KOS = "À abattre"
L.SOUND_LBREAK = "Crochet cassé"
L.SOUND_KICK = "Expulsion d'instance"
L.SOUND_FANFARE = "Fanfare de niveau"
L.SOUND_MEDAL = "Médaille de champ de bataille"
L.SOUND_SPT = "Point de compétence"
L.SOUND_MAP = "Lieu découvert"

L.TEST_ALL = "Tout tester"
L.TEST_ALL_TT = "Cycle 0→1→2→3 sur les affichages actifs et le son à 3."
L.TEST_BTN = "Aperçu"

L.SEC_ICONS = "Icônes"
L.SEC_ICONS_TT = "Disposition, taille et position des runes."

L.ICON_LAYOUT = "Disposition"
L.ICON_LAYOUT_TT = "Rangée horizontale, verticale ou triangle autour du point."
L.LAYOUT_ROW_H = "Rangée horizontale"
L.LAYOUT_ROW_V = "Rangée verticale"
L.LAYOUT_TRI = "Triangle au réticule"

L.ICON_SIZE = "Taille des icônes"
L.ICON_SIZE_TT = "Taille en pixels de chaque rune."
L.ICON_X = "Icônes X"
L.ICON_X_TT = "0 = centre. + droite, − gauche."
L.ICON_Y = "Icônes Y"
L.ICON_Y_TT = "0 = centre. + bas, − haut."
L.ICON_RADIUS = "Distance au centre"
L.ICON_RADIUS_TT = "Triangle seulement. Éloignement des trois runes."
L.ICON_A12 = "Opacité des icônes à 1–2"
L.ICON_A12_TT = "Opacité des runes à 1 ou 2 Crux. Défaut 50%."
L.ICON_A3 = "Opacité des icônes à 3"
L.ICON_A3_TT = "Opacité des runes à 3 Crux. Défaut 100%."

L.TEST_ICONS = "Tester les icônes"
L.TEST_ICONS_TT = "Runes seules. Cycle 0→3."

L.SEC_NUMBER = "Chiffre"
L.SEC_NUMBER_TT = "Taille et position du chiffre 0–3."
L.NUM_SIZE = "Taille du chiffre"
L.NUM_SIZE_TT = "Taille de police."
L.NUM_A12 = "Opacité du chiffre à 1–2"
L.NUM_A12_TT = "Opacité du chiffre à 1 ou 2 Crux. Défaut 50%."
L.NUM_A3 = "Opacité du chiffre à 3"
L.NUM_A3_TT = "Opacité du chiffre à 3 Crux. Défaut 100%."
L.NUM_X = "Chiffre X"
L.NUM_X_TT = "0 = centre. + droite, − gauche."
L.NUM_Y = "Chiffre Y"
L.NUM_Y_TT = "0 = centre. + bas, − haut."
L.TEST_NUMBER = "Tester le chiffre"
L.TEST_NUMBER_TT = "Chiffre seul. Cycle 0→3."

L.SEC_BAR = "Barre d’actions"
L.SEC_BAR_TT = "Calque de couleur sur l’emplacement Fatecarver."
L.BAR_A2 = "Opacité barre à 2 Crux"
L.BAR_A2_TT = "Densité de la plaque à 2 stacks."
L.BAR_A3 = "Opacité barre à 3 Crux"
L.BAR_A3_TT = "Densité de la plaque à 3 stacks. L’icône reste lisible."
L.TEST_BAR = "Tester la couleur de barre"
L.TEST_BAR_TT = "Calque sur Fatecarver s’il est placé, sinon sur l’emplacement 1."
