TetsuArcanistCrux = TetsuArcanistCrux or {}
local L = TetsuArcanistCrux.L
if not L then return end

L.TITLE = "|cFFD700Tetsu's|r Arcanist Crux Tracker"

L.INFO_LABEL = "説明"
L.INFO_TT = "アーカニストのクルックスを表示。アイコン・数字・消費スキル枠は同時に使えます。\n音は 2→3 のときだけ。\nゴールド / 不具合: メール @Tetsurion。"

L.SHOW_ICONS = "アイコンを表示"
L.SHOW_ICONS_TT = "公式クルックスルーン 1～3。配置は「アイコン」節。"

L.SHOW_NUMBER = "数字を表示"
L.SHOW_NUMBER_TT = "0～3 の数字。初期位置は画面中央。初期はオフ。"

L.SHOW_BAR = "クルックス消費スキルを着色"
L.SHOW_BAR_TT = "クルックスを消費するスキル枠の色。0～1 では非表示。スキル絵は塗り替えません。"

L.COMBAT_ONLY = "戦闘中のみ"
L.COMBAT_ONLY_TT = "オン＝非戦闘でアイコン・数字・バー色を隠す。メニューのプレビューは出る。"

L.COLOR2 = "2 スタックの色"
L.COLOR2_TT = "アイコン・数字・バー。初期は黄。"

L.COLOR3 = "3 スタックの色"
L.COLOR3_TT = "アイコン・数字・バー。初期は赤。"

L.SOUND_ENABLE = "3 スタックで音"
L.SOUND_ENABLE_TT = "2→3 の一度だけ。3 の間ずっと鳴らしません。"

L.SOUND_PICK = "音"
L.SOUND_PICK_TT = "ゲーム内蔵音。インターフェース音量に従います。"

L.SOUND_VOL = "音量"
L.SOUND_VOL_TT = "同じ音を重ねる回数（0＝無音、5＝最大）。独立ミキサーではありません。"

L.SOUND_KILL = "止めの一撃"
L.SOUND_DUEL = "決闘開始"
L.SOUND_ALERT = "警告"
L.SOUND_NOTIFY = "通知"
L.SOUND_DISCOVER = "目標発見"
L.SOUND_RUNE = "効力ルーン"
L.SOUND_GLYPH = "グリフ解除"
L.SOUND_QUEST = "クエスト進行"
L.SOUND_LEVEL = "レベルアップ"
L.SOUND_MAIL = "新着メール"
L.SOUND_SKILL = "スキル取得"
L.SOUND_LOCK = "開錠成功"
L.SOUND_READY = "レディチェック"
L.SOUND_TICK = "カウントダウン"
L.SOUND_BGMIN = "戦場1分前"
L.SOUND_BGGO = "戦場開始"
L.SOUND_TRIALOK = "試練クリア"
L.SOUND_TRIALNO = "試練失敗"
L.SOUND_ACHIEVE = "実績"
L.SOUND_SKY = "スカイシャード"
L.SOUND_QDONE = "クエスト完了"
L.SOUND_QACC = "クエスト受注"
L.SOUND_CHAMP = "チャンピオン確定"
L.SOUND_ABIL = "スキル解放"
L.SOUND_COLL = "収集品"
L.SOUND_BOOK = "本を入手"
L.SOUND_ESS = "本質ルーン"
L.SOUND_ASP = "属性ルーン"
L.SOUND_ALC = "錬金溶剤"
L.SOUND_FRIEND = "フレンド招待"
L.SOUND_GJOIN = "グループ参加"
L.SOUND_KOS = "指名手配"
L.SOUND_LBREAK = "ロックピック破損"
L.SOUND_KICK = "インスタンス追放"
L.SOUND_FANFARE = "レベルファンファーレ"
L.SOUND_MEDAL = "戦場メダル"
L.SOUND_SPT = "スキルポイント"
L.SOUND_MAP = "地図発見"

L.TEST_ALL = "すべてテスト"
L.TEST_ALL_TT = "有効な表示を 0→1→2→3 し、3 で音を出します。"
L.TEST_BTN = "プレビュー"

L.SEC_ICONS = "アイコン"
L.SEC_ICONS_TT = "ルーンの配置・大きさ・位置。"

L.ICON_LAYOUT = "配置"
L.ICON_LAYOUT_TT = "横一列、縦一列、照準まわりの三角。"
L.LAYOUT_ROW_H = "横一列"
L.LAYOUT_ROW_V = "縦一列"
L.LAYOUT_TRI = "照準の三角"

L.ICON_SIZE = "アイコンサイズ"
L.ICON_SIZE_TT = "各ルーンのピクセルサイズ。"
L.ICON_X = "アイコン X"
L.ICON_X_TT = "0＝画面中央。＋右、−左。"
L.ICON_Y = "アイコン Y"
L.ICON_Y_TT = "0＝画面中央。＋下、−上。"
L.ICON_RADIUS = "中心からの距離"
L.ICON_RADIUS_TT = "三角配置のみ。3 ルーンの広がり。"
L.ICON_A12 = "アイコン不透明度 1–2"
L.ICON_A12_TT = "1 または 2 スタック時。初期 50%。"
L.ICON_A3 = "アイコン不透明度 3"
L.ICON_A3_TT = "3 スタック時。初期 100%。"

L.TEST_ICONS = "アイコンをテスト"
L.TEST_ICONS_TT = "ルーンのみ。0→3。"

L.SEC_NUMBER = "数字"
L.SEC_NUMBER_TT = "0～3 の大きさと位置。"
L.NUM_SIZE = "数字サイズ"
L.NUM_SIZE_TT = "フォントサイズ。"
L.NUM_A12 = "数字不透明度 1–2"
L.NUM_A12_TT = "1 または 2 スタック時。初期 50%。"
L.NUM_A3 = "数字不透明度 3"
L.NUM_A3_TT = "3 スタック時。初期 100%。"
L.NUM_X = "数字 X"
L.NUM_X_TT = "0＝画面中央。＋右、−左。"
L.NUM_Y = "数字 Y"
L.NUM_Y_TT = "0＝画面中央。＋下、−上。"
L.TEST_NUMBER = "数字をテスト"
L.TEST_NUMBER_TT = "数字のみ。0→3。"

L.SEC_BAR = "アクションバー"
L.SEC_BAR_TT = "フェイトカーヴァー枠の色。"
L.BAR_A2 = "2クルックス時のバー不透明度"
L.BAR_A2_TT = "2スタック時の色板の濃さ。"
L.BAR_A3 = "3クルックス時のバー不透明度"
L.BAR_A3_TT = "3スタック時の色板の濃さ。スキル絵は残ります。"
L.TEST_BAR = "バー色をテスト"
L.TEST_BAR_TT = "フェイトカーヴァーがあればその枠、なければスキルスロット 1。"
