FurnishThemAllData_Game_GameRewards = {
    name = "Game Rewards", -- Achievement Rewards
    source = "Game",
    collection = {
        [1] = {
            { name = "Music Box, The Merry Meadmaker" },
            { name = "Target Stone Husk" },
            { name = "The Precursor" },
            { name = "Letter from Azandar" },
            { name = "Letter from Ember" },
            { name = "Letter from Isobel" },
            { name = "Letter from Sharp" },
            { name = "Letter from Tanlorin" },
            { name = "Letter from Zerith-var" },
            { name = "Sir Socks's Ball of Yarn" },

            { name = "Tribute Trophy, Ebony" },
            { name = "Tribute Trophy, Orichalcum" },
            { name = "Tribute Trophy, Quicksilver" },
            { name = "Tribute Trophy, Voidsteel" },
            { name = "Tribute Trophy, Rubedite" },

            { name = "The 36 Lessons: Sermon 1", achievement = "Tribunal Preacher", info = "Collection: Vivec's 36 Lessons. Once this achievement is unlocked, you can buy all 36 books as furnishing items from Drops-No-Glass in Vivec City." },
            { name = "The 36 Lessons: Sermon 2" },
            { name = "The 36 Lessons: Sermon 3" },
            { name = "The 36 Lessons: Sermon 4" },
            { name = "The 36 Lessons: Sermon 5" },
            { name = "The 36 Lessons: Sermon 6" },
            { name = "The 36 Lessons: Sermon 7" },
            { name = "The 36 Lessons: Sermon 8" },
            { name = "The 36 Lessons: Sermon 9" },
            { name = "The 36 Lessons: Sermon 10" },
            { name = "The 36 Lessons: Sermon 11" },
            { name = "The 36 Lessons: Sermon 12" },
            { name = "The 36 Lessons: Sermon 13" },
            { name = "The 36 Lessons: Sermon 14" },
            { name = "The 36 Lessons: Sermon 15" },
            { name = "The 36 Lessons: Sermon 16" },
            { name = "The 36 Lessons: Sermon 17" },
            { name = "The 36 Lessons: Sermon 18" },
            { name = "The 36 Lessons: Sermon 19" },
            { name = "The 36 Lessons: Sermon 20" },
            { name = "The 36 Lessons: Sermon 21" },
            { name = "The 36 Lessons: Sermon 22" },
            { name = "The 36 Lessons: Sermon 23" },
            { name = "The 36 Lessons: Sermon 24" },
            { name = "The 36 Lessons: Sermon 25" },
            { name = "The 36 Lessons: Sermon 26" },
            { name = "The 36 Lessons: Sermon 27" },
            { name = "The 36 Lessons: Sermon 28" },
            { name = "The 36 Lessons: Sermon 29" },
            { name = "The 36 Lessons: Sermon 30" },
            { name = "The 36 Lessons: Sermon 31" },
            { name = "The 36 Lessons: Sermon 32" },
            { name = "The 36 Lessons: Sermon 33" },
            { name = "The 36 Lessons: Sermon 34" },
            { name = "The 36 Lessons: Sermon 35" },
            { name = "The 36 Lessons: Sermon 36" },
        },
    },
}
