TetsuCombatHealerHelper = TetsuCombatHealerHelper or {}
local L = TetsuCombatHealerHelper.L
if not L then return end

L.TITLE = "|cFFD700Tetsu's|r Combat Healer Helper"
L.INFO_LABEL = "Info"
L.INFO_TT = "Illustrious Healing dessine un cercle au sol (8 m, 15 s). Relancer déplace le même cercle.\nCombat Prayer et deux emplacements extra affichent les TROUS par défaut : icône seulement si le buff manque.\nEn file aléatoire, vous seul voyez les marques. En guilde, chacun avec l'addon.\nOr / bugs / idées : courrier @Tetsurion."
L.ENABLED_LABEL = "Activer l'assistant"
L.ENABLED_TT = "Interrupteur général. Off cache la flaque et toutes les icônes."
L.GAPS_LABEL = "Afficher seulement les buffs manquants"
L.GAPS_TT = "On (recommandé) : icône sur ceux NON couverts. Off : icône sur ceux couverts."
L.ICON_SIZE_LABEL = "Taille des icônes au-dessus de la tête"
L.ICON_SIZE_TT = "Taille des marqueurs au-dessus des joueurs."
L.PUDDLE_SECTION = "Flaque Illustrious Healing"
L.PUDDLE_SECTION_TT = "Un cercle au sol pour votre dernier Illustrious / Springs."
L.PUDDLE_ENABLED_LABEL = "Afficher le cercle de flaque"
L.PUDDLE_ENABLED_TT = "Cercle translucide là où vous posez Illustrious Healing. Relancer le déplace."
L.PUDDLE_COLOR_LABEL = "Couleur de la flaque"
L.PUDDLE_COLOR_TT = "Couleur du cercle au sol."
L.PUDDLE_ALPHA_LABEL = "Opacité de la flaque %"
L.PUDDLE_ALPHA_TT = "Densité du cercle. Plus bas = moins de bruit visuel."
L.PRAYER_SECTION = "Combat Prayer"
L.PRAYER_SECTION_TT = "Cœur soigneur, toujours présent. Forme distincte."
L.PRAYER_ENABLED_LABEL = "Suivre Combat Prayer"
L.PRAYER_ENABLED_TT = "Icône de trou sur les membres sans Combat Prayer."
L.PRAYER_COLOR_LABEL = "Couleur de l'icône de prière"
L.PRAYER_COLOR_TT = "Couleur du marqueur Combat Prayer."
L.SLOTS_SECTION = "Icônes extra"
L.SLOTS_SECTION_TT = "Deux suivis optionnels. Même logique de trous. Doublon du slot 2 ignoré."
L.SLOT1_LABEL = "Icône extra 1"
L.SLOT1_TT = "Liste courte des effets soigneur / soutien."
L.SLOT1_COLOR_LABEL = "Couleur icône 1"
L.SLOT1_COLOR_TT = "Couleur de l'icône extra 1."
L.SLOT2_LABEL = "Icône extra 2"
L.SLOT2_TT = "Second suivi. Off = prière + icône 1 seulement."
L.SLOT2_COLOR_LABEL = "Couleur icône 2"
L.SLOT2_COLOR_TT = "Couleur de l'icône extra 2."
L.SLOT_OFF = "Off"
L.SLOT_PA = "Powerful Assault"
