TetsuCombatHealerHelper = TetsuCombatHealerHelper or {}
local L = TetsuCombatHealerHelper.L
if not L then return end

L.TITLE = "|cFFD700Tetsu's|r Combat Healer Helper"

L.INFO_LABEL = "Инфо"
L.INFO_TT = "Иконки над головой = хилы. Висят на тех, кого НЕ покрыли лужа Illustrious, Combat Prayer и один доп. слот. Попал хил — иконка гаснет.\nHUD = баффы. До 5 колонок. Зелёная точка = бафф УЖЕ на игроке.\nВ рандоме видите только вы. Гильдия ставит аддон себе.\nЗолото / баги: почта @Tetsurion."

L.ENABLED_LABEL = "Включить помощник"
L.ENABLED_TT = "Главный выключатель."
L.HUD_LABEL = "Показывать HUD баффов"
L.HUD_TT = "Сетка справа сверху: ники + зелёные точки выбранных баффов."
L.WORLD_PIPS_LABEL = "Иконки хилов над головами"
L.WORLD_PIPS_TT = "Круг = нет лужи Illustrious. Ромб = нет молитвы. Квадрат = нет доп. хила."
L.ICON_SIZE_LABEL = "Размер иконок над головой"
L.ICON_SIZE_TT = "Размер маркеров дыр хила."

L.HEAD_SECTION = "Иконки над головой (хилы)"
L.HEAD_SECTION_TT = "Всегда лужа + молитва. Третий слот по желанию."
L.IH_COLOR_LABEL = "Цвет лужи"
L.IH_COLOR_TT = "Цвет круга «нет Illustrious»."
L.PRAYER_COLOR_LABEL = "Цвет молитвы"
L.PRAYER_COLOR_TT = "Цвет ромба «нет Combat Prayer»."
L.HEAD_EXTRA_LABEL = "Доп. иконка над головой"
L.HEAD_EXTRA_TT = "Третья дыра над головой. Выкл — только лужа и молитва."
L.HEAD_EXTRA_COLOR_LABEL = "Цвет доп. иконки"
L.HEAD_EXTRA_COLOR_TT = "Цвет третьей иконки."

L.HUD_SECTION = "Колонки HUD (баффы)"
L.HUD_SECTION_TT = "Зелёная точка появляется, когда бафф уже висит на игроке."
L.HUD_COL_LABEL = "Колонка HUD %d"
L.HUD_COL_TT = "Зелёная точка в этой колонке, если эффект ЕСТЬ."

L.SLOT_OFF = "Выкл"
L.SLOT_PA = "Мощный натиск"
L.SLOT_VIGOR_ECHO = "Echoing Vigor"
L.SLOT_VIGOR_RES = "Resolving Vigor"
L.SLOT_RAD_REGEN = "Radiating Regeneration"
L.SLOT_RAPID_REGEN = "Rapid Regeneration"
L.SLOT_COURAGE = "Major Courage"
L.SLOT_ORB = "Energy Orb"
L.SLOT_IH = "Illustrious Healing"
L.SLOT_PRAYER = "Combat Prayer"
L.SLOT_FORCE = "Major Force"
L.SLOT_SLAYER = "Major Slayer"
L.SLOT_MSTEAL = "Minor Magickasteal"
L.SLOT_ORB_LOCK = "Лок синергии орба"

L.SHORT_PA = "PA"
L.SHORT_VE = "EVig"
L.SHORT_VR = "RVig"
L.SHORT_RAD = "RadR"
L.SHORT_RAP = "RapR"
L.SHORT_CRG = "Cour"
L.SHORT_ORB = "Orb"
L.SHORT_FRC = "Forc"
L.SHORT_SLY = "Slay"
L.SHORT_MS = "MStl"
L.SHORT_OLK = "Lock"

L.HEAD_HEIGHT_LABEL = "Высота иконок над головой"
L.HEAD_HEIGHT_TT = "Насколько высоко над ногами висят иконки. Подними, если они торчат из груди."
L.HEAD_MODE_LABEL = "Режим иконок над головой"
L.HEAD_MODE_TT = "Авто = 3D в мире (как рабочая лужа). Экран = пины на HUD, если зона ломает 3D."
L.HEAD_MODE_AUTO = "Авто (3D мир)"
L.HEAD_MODE_SCREEN = "Экранный оверлей"
L.HUD_X_LABEL = "Сдвиг HUD по X"
L.HUD_X_TT = "Влево (минус) или вправо."
L.HUD_Y_LABEL = "Сдвиг HUD по Y"
L.HUD_Y_TT = "Вверх (минус) или вниз."
L.HUD_SCALE_LABEL = "Масштаб HUD %"
L.HUD_SCALE_TT = "Размер сетки баффов."
