TetsuCombatHealerHelper = TetsuCombatHealerHelper or {}
local L = TetsuCombatHealerHelper.L
if not L then return end

L.TITLE = "|cFFD700Tetsu's|r Raid Lead Assistant"

L.INFO_LABEL = "Инфо"
L.INFO_TT = "Пока только HUD. До 5 колонок. Зелёная точка = бафф или хил сейчас висит на игроке.\nВидно то, что видит твой клиент (свои касты и эффекты на группе).\nЗолото / баги: почта @Tetsurion."

L.ENABLED_LABEL = "Включить помощник"
L.ENABLED_TT = "Главный выключатель."
L.HUD_LABEL = "Показывать хилерский HUD"
L.HUD_TT = "Сетка с никами и точками по людям."
L.PAIR_PANELS_LABEL = "Показывать панели баффов / дебаффов"
L.PAIR_PANELS_TT = "Рейд-баффы и дебаффы босса. Не зависит от хилерского HUD."
L.PAIR_X_LABEL = "Сдвиг бафф/дебафф X"
L.PAIR_X_TT = "Только если хилерский HUD выключен. Двигает обе нижние панели вместе."
L.PAIR_Y_LABEL = "Сдвиг бафф/дебафф Y"
L.PAIR_Y_TT = "Только если хилерский HUD выключен. Двигает обе нижние панели вместе."
L.WORLD_PIPS_LABEL = "Иконки хилов над головами"
L.WORLD_PIPS_TT = "Круг = нет лужи Illustrious. Ромб = нет молитвы. Квадрат = нет доп. хила."
L.ICON_SIZE_LABEL = "Размер иконок над головой"
L.ICON_SIZE_TT = "Размер маркеров дыр хила."

L.HEAD_SECTION = "Иконки над головой (хилы)"
L.HEAD_SECTION_TT = "Всегда лужа + молитва. Третий слот по желанию."
L.IH_COLOR_LABEL = "Цвет лужи"
L.IH_COLOR_TT = "Цвет круга «нет Illustrious»."
L.PRAYER_COLOR_LABEL = "Цвет молитвы"
L.PRAYER_COLOR_TT = "Цвет ромба «нет Combat Prayer»."
L.HEAD_EXTRA_LABEL = "Доп. иконка над головой"
L.HEAD_EXTRA_TT = "Третья дыра над головой. Выкл — только лужа и молитва."
L.HEAD_EXTRA_COLOR_LABEL = "Цвет доп. иконки"
L.HEAD_EXTRA_COLOR_TT = "Цвет третьей иконки."

L.SORT_ROLE_LABEL = "Сортировать HUD по ролям"
L.SORT_ROLE_TT = "Сначала танки, потом хилы, потом ДД."
L.HEALCUT_LABEL = "Помечать хилорез / осквернение"
L.HEALCUT_TT = "Сиреневый ник и знак, если на игроке осквернение или поглощение исцеления. Мало ХП остаётся красным."
L.LOWHP_TANKS_LABEL = "Мало ХП: только танки"
L.LOWHP_TANKS_TT = "Выкл — краснеет любой, у кого мало здоровья."
L.LOWHP_PCT_LABEL = "Порог низкого ХП %"
L.LOWHP_PCT_TT = "Ник краснеет при здоровье на этом проценте и ниже."

L.HUD_SECTION = "Колонки хилерского HUD"
L.HUD_SECTION_TT = "Точки по людям на хилерской сетке."
L.POS_SECTION = "Положение HUD"
L.POS_SECTION_TT = "Сдвиг и размер окон."
L.RAID_BUFFS = "Рейд-баффы"
L.RAID_BUFFS_TT = "Покрытие группы Major / Minor."
L.BOSS_DEBUFFS = "Дебаффы босса"
L.BOSS_DEBUFFS_TT = "Major / Minor на боссе. Off-Balance: On / Imm."
L.PAIR_SLAYER = "Палач"
L.PAIR_FORCE = "Сила"
L.PAIR_BERSERK = "Ярость"
L.PAIR_RESOLVE = "Решимость"
L.PAIR_VITALITY = "Жизненная сила"
L.PAIR_WDSPD = "Колд. / Жест."
L.PAIR_CRIT = "Прор. / Свир."
L.PAIR_RECOVER = "Инт. / Вын."
L.PAIR_HEROISM = "Героизм"
L.PAIR_BREACH = "Прорыв"
L.PAIR_FRACTURE = "Перелом"
L.PAIR_VULNERABILITY = "Уязвимость"
L.PAIR_BRITTLE = "Хрупкость"
L.PAIR_COWARDICE = "Трусость"
L.PAIR_MAIM = "Калечение"
L.PAIR_DEFILE = "Осквернение"
L.PAIR_OFFBALANCE = "Потеря равновесия"
L.PAIR_DESC_SLAYER = "Урон по монстрам. Великий +15%, малый +5%."
L.PAIR_DESC_FORCE = "Критический урон. Великий +20%, малый +10%."
L.PAIR_DESC_BERSERK = "Наносимый урон. Великий +10%, малый +5%."
L.PAIR_DESC_RESOLVE = "Сопротивление физ. и магии. Великий +5948, малый +2974."
L.PAIR_DESC_VITALITY = "Входящее исцеление. Великий +16%, малый +8%."
L.PAIR_DESC_WDSPD = "Сила оружия и заклинаний (жестокость / колдовство). Великий +20%, малый +10%."
L.PAIR_DESC_CRIT = "Крит оружия и заклинаний (свирепость / пророчество)."
L.PAIR_DESC_RECOVER = "Восстановление запаса сил и магии (выносливость / интеллект)."
L.PAIR_DESC_HEROISM = "Генерация абсолютной способности. Великий 3/с, малый 1.5/с."
L.PAIR_DESC_BREACH = "Снижает магическое сопротивление босса."
L.PAIR_DESC_FRACTURE = "Снижает физическое сопротивление босса."
L.PAIR_DESC_VULNERABILITY = "Босс получает больше урона. Великий +10%, малый +5%."
L.PAIR_DESC_BRITTLE = "Босс получает больше критического урона."
L.PAIR_DESC_COWARDICE = "Снижает силу оружия и заклинаний босса."
L.PAIR_DESC_MAIM = "Снижает наносимый боссом урон."
L.PAIR_DESC_DEFILE = "Снижает входящее исцеление босса."
L.PAIR_DESC_OFFBALANCE = "On = потеря равновесия (7 с). Imm = иммунитет после неё (15 с)."
L.HUD_COL_LABEL = "Колонка HUD %d"
L.HUD_COL_TT = "Зелёная точка в этой колонке, если эффект ЕСТЬ."

L.SLOT_OFF = "Выкл"
L.SLOT_VIGOR = "Бодрость"
L.SLOT_PA = "Мощный натиск"
L.SLOT_VIGOR_ECHO = "Гулкая бодрость"
L.SLOT_VIGOR_RES = "Крепнущая бодрость"
L.SLOT_RAD_REGEN = "Излучающая регенерация"
L.SLOT_RAPID_REGEN = "Быстрая регенерация"
L.SLOT_COURAGE = "Великая храбрость"
L.SLOT_ORB = "Энергетическая сфера"
L.SLOT_IH = "Блистательное исцеление"
L.SLOT_PRAYER = "Боевая молитва"
L.SLOT_FORCE = "Великая сила"
L.SLOT_SLAYER = "Великий палач"
L.SLOT_MSTEAL = "Малое похищение магии"
L.SLOT_ORB_LOCK = "Откат синергии орба"
L.SLOT_MINOR_COURAGE = "Малая храбрость"
L.SLOT_MINOR_BERSERK = "Малая ярость"
L.SLOT_MINOR_RESOLVE = "Малая решимость"

L.SHORT_VG = "Бодр"
L.SHORT_PA = "PA"
L.SHORT_VE = "EVig"
L.SHORT_VR = "RVig"
L.SHORT_RAD = "RadR"
L.SHORT_RAP = "RapR"
L.SHORT_CRG = "Cour"
L.SHORT_ORB = "Orb"
L.SHORT_FRC = "Forc"
L.SHORT_SLY = "Slay"
L.SHORT_MS = "MStl"
L.SHORT_OLK = "Lock"

L.HEAD_HEIGHT_LABEL = "Высота иконок над головой"
L.HEAD_HEIGHT_TT = "Насколько высоко над ногами висят иконки. Подними, если они торчат из груди."
L.HEAD_MODE_LABEL = "Режим иконок над головой"
L.HEAD_MODE_TT = "Авто = 3D в мире (как рабочая лужа). Экран = пины на HUD, если зона ломает 3D."
L.HEAD_MODE_AUTO = "Авто (3D мир)"
L.HEAD_MODE_SCREEN = "Экранный оверлей"
L.HUD_X_LABEL = "Сдвиг HUD по X"
L.HUD_X_TT = "Влево (минус) или вправо."
L.HUD_Y_LABEL = "Сдвиг HUD по Y"
L.HUD_Y_TT = "Вверх (минус) или вниз."
L.HUD_SCALE_LABEL = "Масштаб HUD %"
L.HUD_SCALE_TT = "Размер сетки баффов."
L.OOC_ALPHA_LABEL = "Прозрачность вне боя %"
L.OOC_ALPHA_TT = "Насколько плотные окна, пока вы не в бою. В бою всегда 100%."
L.CUSTOM_LABELS = "Имена на HUD"
L.CUSTOM_LABELS_TT = "Этот текст на HUD. Хилерские колонки — первые 5 букв, панели баффов/дебаффов — 8."
L.CUSTOM_LABEL_TT = "Пустое поле = английское имя."
