local _fr = {
	SI_LOVELYEMOTES_ALERT_COPY_FAILED = "[LovelyEmotes] Echec de la copie : aucun emote à copier",
	SI_LOVELYEMOTES_ALERT_COPY_SUCCESS = "[LovelyEmotes] Copie effectuée",
	SI_LOVELYEMOTES_ALERT_EMOTE_MODIFICATIONS_APPLIED = "[LovelyEmotes] Modifications d'émotes appliquées",
	SI_LOVELYEMOTES_ALERT_NO_EMOTE_SELECTED = "[LovelyEmotes] Aucun emote sélectionné.",

	SI_LOVELYEMOTES_BINDING_LAYER_RADIAL_MENU = "LovelyEmotes - Menu radial",
	SI_LOVELYEMOTES_BINDING_NEXT_TAB = "Onglet suivant",
	SI_LOVELYEMOTES_BINDING_PLAY_FAVORITE = "Jouer le favori",
	SI_LOVELYEMOTES_BINDING_PREVIOUS_TAB = "Onglet précédent",
	SI_LOVELYEMOTES_BINDING_RADIAL_QUICK_MENU = "Menu radial",
	SI_LOVELYEMOTES_BINDING_TAB = "Afficher l'onglet",
	SI_LOVELYEMOTES_BINDING_TOGGLE_MAIN_WINDOW = "Basculer la fenêtre principale",

	SI_LOVELYEMOTES_FAVORITECOMMANDS_COMMAND = "Commande",
	SI_LOVELYEMOTES_FAVORITECOMMANDS_DISPLAY_NAME = "Nom affiché",
	SI_LOVELYEMOTES_FAVORITECOMMANDS_FORCE_DISPLAY_NAME = "Force l'affichage du nom",
	SI_LOVELYEMOTES_FAVORITECOMMANDS_OPTIONAL = "optionel",
	SI_LOVELYEMOTES_FAVORITECOMMANDS_SELECTED_SLOT = "Emplacement sélectionné: ",
	SI_LOVELYEMOTES_FAVORITECOMMANDS_SELECTED_SLOT_EMPTY = "Choisir un onglet en premier.",

	SI_LOVELYEMOTES_SETTINGS_ACCOUNT_WIDE_TAB_NAME = "Onglet au niveau du compte",
	SI_LOVELYEMOTES_SETTINGS_ACCOUNT_WIDE_TAB_TOOLTIP = "Permet de sélectionner l'onglet enregistré au niveau du compte à copier ou à écraser.",
	SI_LOVELYEMOTES_SETTINGS_BUTTONDESIGN_EMOTELIST_NAME = "Apparence alternative du bouton (liste des emotes)",
	SI_LOVELYEMOTES_SETTINGS_BUTTONDESIGN_EMOTELIST_TOOLTIP = "Modifie le design des boutons dans la liste des emotes.",
	SI_LOVELYEMOTES_SETTINGS_BUTTONDESIGN_FAVORITES_NAME = "Apparence alternative du bouton (liste des favoris)",
	SI_LOVELYEMOTES_SETTINGS_BUTTONDESIGN_FAVORITES_TOOLTIP = "Modifie le design des boutons favoris dans la fenêtre principale.",
	SI_LOVELYEMOTES_SETTINGS_CHAT_BUTTON_OFFSET_NAME = "Décalage du bouton de chat",
	SI_LOVELYEMOTES_SETTINGS_CHAT_BUTTON_OFFSET_TOOLTIP = "Déplace la position du bouton. Utilisez-le pour assurer la compatibilité avec d'autres modules complémentaires qui ajoutent des boutons à la fenêtre de discussion.",
	SI_LOVELYEMOTES_SETTINGS_COPY_EMOTES_DESCRIPTION = "Permet de copier une liste d'emotes favoris vers ou depuis un personnage ou au niveau du compte.",
	SI_LOVELYEMOTES_SETTINGS_COPY_EMOTES_HEADER = "Copie des emotes",
	SI_LOVELYEMOTES_SETTINGS_COPY_EMPTY_TAB = "Onglet vide.",
	SI_LOVELYEMOTES_SETTINGS_CURRENTLY_ACTIVE_TAB = "Onglet actuellement actif",
	SI_LOVELYEMOTES_SETTINGS_EMOTES_COUNT_TEXT = "Emotes actuellement disponibles:",
	SI_LOVELYEMOTES_SETTINGS_EMOTES_SETTINGS_HEADER = "Paramètres des emotes",
	SI_LOVELYEMOTES_SETTINGS_ENABLE_ACCOUNT_WIDE_EMOTES_NAME = "Activer les emotes favorisés du compte",
	SI_LOVELYEMOTES_SETTINGS_ENABLE_ALTERNATIVE_SOUNDS_NAME = "Activer les sons alternatifs",
	SI_LOVELYEMOTES_SETTINGS_ENABLE_ALTERNATIVE_SOUNDS_TOOLTIP = "Remplace certains sons de \"Clic\" par des sons alternatifs.",
	SI_LOVELYEMOTES_SETTINGS_ENABLE_CHAT_BUTTON_NAME = "Activer le bouton de chat",
	SI_LOVELYEMOTES_SETTINGS_ENABLE_CHAT_BUTTON_TOOLTIP = "Ajoute un bouton à la fenêtre de chat pour faire basculer la fenêtre LovelyEmotes.",
	SI_LOVELYEMOTES_SETTINGS_ENABLE_PERSONALITIES_AS_FAVORITES_NAME = "Personnalités comme favoris",
	SI_LOVELYEMOTES_SETTINGS_ENABLE_PERSONALITIES_AS_FAVORITES_TOOLTIP = "Ajoute des personnalités déverrouillées à la liste des emotes.",
	SI_LOVELYEMOTES_SETTINGS_GENERAL_SETTINGS_HEADER = "Réglages généraux",
	SI_LOVELYEMOTES_SETTINGS_HIDE_MINIMIZED_WINDOW_NAME = "Cacher la fenêtre minimisée",
	SI_LOVELYEMOTES_SETTINGS_HIDE_MINIMIZED_WINDOW_TOOLTIP = "Cache le bouton \"LovelyEmotes\" en état minimisé.",
	SI_LOVELYEMOTES_SETTINGS_HIGHLIGHT_LOCKED_EMOTES_NAME = "Mettre en évidence les émotes verrouillées",
	SI_LOVELYEMOTES_SETTINGS_HIGHLIGHT_LOCKED_EMOTES_TOOLTIP = "Mettez en évidence les emotes verrouillées dans la liste des emotes.",
	SI_LOVELYEMOTES_SETTINGS_LOCAL_TAB_NAME = "Onglet au niveau du personnage",
	SI_LOVELYEMOTES_SETTINGS_LOCAL_TAB_TOOLTIP = "Permet de sélectionner l'onglet enregistré au niveau du personnage actuel à copier ou à écraser.",
	SI_LOVELYEMOTES_SETTINGS_MINIMIZE_AUTOMATICALLY_NAME = "Minimiser automatiquement",
	SI_LOVELYEMOTES_SETTINGS_MINIMIZE_AUTOMATICALLY_TOOLTIP = "Minimise automatiquement la fenêtre des favoris lorsque le curseur est caché.\nSi activé, il est également recommandé d'activer l'option \"Afficher le curseur\".",
	SI_LOVELYEMOTES_SETTINGS_MINIMIZE_IN_COMBAT_NAME = "Minimiser en combat",
	SI_LOVELYEMOTES_SETTINGS_MINIMIZE_IN_COMBAT_TOOLTIP = "Minimise automatiquement la fenêtre principale en combat. Elle réapparaîtra après le combat. Cela n'a pas d' effet si la fenêtre a eté minimisée manuellement.",
	SI_LOVELYEMOTES_SETTINGS_MINIMIZED_SCALE_NAME = "Échelle (Minimisée)",
	SI_LOVELYEMOTES_SETTINGS_MINIMIZED_SCALE_TOOLTIP = "Modifier la taille de la fenêtre minimisée.",
	SI_LOVELYEMOTES_SETTINGS_MINIMIZED_VISIBILITY_NAME = "Visibilité (Minimisée)",
	SI_LOVELYEMOTES_SETTINGS_MINIMIZED_VISIBILITY_TOOLTIP = "Détermine le niveau d'opacité lorsque la fenêtre est réduite.",
	SI_LOVELYEMOTES_SETTINGS_NAME = "Nom",
	SI_LOVELYEMOTES_SETTINGS_NUMBER_OF_EMOTES_NAME = "Nombre d'emotes",
	SI_LOVELYEMOTES_SETTINGS_NUMBER_OF_TABS_NAME = "Nombre d'onglets",
	SI_LOVELYEMOTES_SETTINGS_NUMBER_OF_TABS_TOOLTIP = "Détermine le nombre d'onglets disponibles dans la fenêtre des favoris.",
	SI_LOVELYEMOTES_SETTINGS_OVERWRITE_CHARACTER_SPECIFIC_BUTTON_NAME = "Personnage",
	SI_LOVELYEMOTES_SETTINGS_OVERWRITE_CHARACTER_SPECIFIC_BUTTON_TOOLTIP = "Remplace les emotes spécifiques de votre personnage actuel par les emotes du compte.",
	SI_LOVELYEMOTES_SETTINGS_OVERWRITE_DESCRIPTION = "Choisissez quel onglet sélectionné sera écrasé:",
	SI_LOVELYEMOTES_SETTINGS_OVERWRITE_ACCOUNT_WIDE_BUTTON_NAME = "Compte",
	SI_LOVELYEMOTES_SETTINGS_OVERWRITE_ACCOUNT_WIDE_BUTTON_TOOLTIP = "Remplace les emotes au niveau du compte par les emotes spécifiques au personnage actuel.",
	SI_LOVELYEMOTES_SETTINGS_RADIAL_MENU_SCALE_NAME = "Échelle de menu radial",
	SI_LOVELYEMOTES_SETTINGS_RADIAL_MENU_SCALE_TOOLTIP = "Changer l'échelle du menu radial.",
	SI_LOVELYEMOTES_SETTINGS_RADIAL_MENU_SHOWN_TAB_NAME = "Menu Radial: Onglet Affiché",
	SI_LOVELYEMOTES_SETTINGS_RADIAL_MENU_SHOWN_TAB_TOOLTIP = "Sélectionnez l'onglet qui doit être affiché lorsque le menu radial est ouvert.",
	SI_LOVELYEMOTES_SETTINGS_SHOW_ENDLESS_LOOP_ICONS_NAME = "Afficher l'icône des emotes persistants",
	SI_LOVELYEMOTES_SETTINGS_SHOW_ENDLESS_LOOP_ICONS_TOOLTIP = "Affiche une icône à coté du nom des emotes qui sont joués en boucle.",
	SI_LOVELYEMOTES_SETTINGS_SHOW_LOCKED_EMOTES_NAME = "Afficher les émotes verrouillées",
	SI_LOVELYEMOTES_SETTINGS_SHOW_LOCKED_EMOTES_TOOLTIP = "Ajoute ou exclut les émotes verrouillées.",
	SI_LOVELYEMOTES_SETTINGS_SHOW_SLASH_NAMES_NAME = "Afficher les noms de Slash",
	SI_LOVELYEMOTES_SETTINGS_SHOW_SLASH_NAMES_TOOLTIP = "Affiche les emotes dans la liste des emotes sous forme de slash au lieu de noms localisés.",
	SI_LOVELYEMOTES_SETTINGS_START_MINIMIZED_NAME = "Minimiser au lancement",
	SI_LOVELYEMOTES_SETTINGS_START_MINIMIZED_TOOLTIP = "Minimise la fenêtre principale au lancement du jeu.",
	SI_LOVELYEMOTES_SETTINGS_TAB = "Onglet",
	SI_LOVELYEMOTES_SETTINGS_TOGGLE_CURSOR_NAME = "Basculer curseur",
	SI_LOVELYEMOTES_SETTINGS_TOGGLE_CURSOR_TOOLTIP = "Bascule le curseur avec le raccourci clavier \"Basculer la fenêtre principale\".",
	SI_LOVELYEMOTES_SETTINGS_VISIBILITY_NAME = "Visibilité",
	SI_LOVELYEMOTES_SETTINGS_VISIBILITY_TOOLTIP = "Détermine le niveau de visibilité de la fenêtre principale et de la fenêtre de sélection des emotes.",

	SI_LOVELYEMOTES_SYNC_DESCRIPTION = "Permet de synchroniser vos emotes avec les autres joueurs utilisant LovelyEmotes.\nChoisir ci-dessous quels canaux de chat LovelyEmotes doit surveiller.\nCliquer ensuite avec le bouton droit sur une emote et appuyez sur la touche Entrée du clavier.",
	SI_LOVELYEMOTES_SYNC_EMOTE_SYNCHRONIZATION = "Synchronisation des emotes",
	SI_LOVELYEMOTES_SYNC_ENABLE_PARTY_CHAT = "Activer dans le canal \"Groupe\"",
	SI_LOVELYEMOTES_SYNC_ENABLE_SAY_CHAT = "Activer dans le canal \"Dire\"",
	SI_LOVELYEMOTES_SYNC_ENABLE_WHISPER_CHAT = "Activer dans le canal \"Chuchoter\"",
	SI_LOVELYEMOTES_SYNC_ENABLE_ZONE_CHAT = "Activer dans le canal \"Zone\"",
}

for k, v in pairs(_fr) do
	SafeAddString(_G[k], v, 1)
end
