ResearchPanel = ResearchPanel or {}

ResearchPanel.strings = {
	HIGHLIGHT_EMPTY_SLOTS_LABEL = {
		en = "Highlight Empty Slots",
		de = "Leere Slots hervorheben",
		fr = "Surligner les emplacements vides",
		ru = "Выделять пустые слоты",
		ja = "空きスロットを強調表示",
		zh = "高亮空槽位",
		es = "Resaltar espacios vacíos",
		it = "Evidenzia slot vuoti",
		pl = "Wyróżnij puste sloty",
	},
	HIGHLIGHT_EMPTY_SLOTS_TOOLTIP = {
		en = "If this character has empty available research slots, highlight this by making the specific indicator red.",
		de = "Wenn dieser Charakter freie Forschungsslots hat, wird dies hervorgehoben, indem der entsprechende Indikator rot angezeigt wird.",
		fr = "Si ce personnage a des emplacements de recherche disponibles, cela sera mis en évidence en rendant l'indicateur spécifique rouge.",
		ru = "Если у этого персонажа есть свободные слоты для исследований, выделите это, сделав соответствующий индикатор красным.",
		ja = "このキャラクターに利用可能な研究スロットがある場合、特定のインジケーターを赤くして強調表示します。",
		zh = "如果该角色有可用的空研究槽，则通过将特定指示器变为红色来突出显示。",
		es = "Si este personaje tiene espacios de investigación vacíos disponibles, resáltalo haciendo que el indicador específico sea rojo.",
		it = "Se questo personaggio ha slot di ricerca disponibili vuoti, evidenzialo rendendo l'indicatore specifico rosso.",
		pl = "Jeśli ta postać ma dostępne puste sloty badawcze, wyróżnij to, czyniąc odpowiedni wskaźnik czerwonym.",
	},
	PANEL_NAME = {
		en = "Research Panel",
		de = "Forschungsübersicht",
		fr = "Panneau de recherche",
		ru = "Панель исследований",
		ja = "研究パネル",
		zh = "研究面板",
		es = "Panel de investigación",
		it = "Pannello di ricerca",
		pl = "Panel badań",
	},
	ENABLE_ADDON_LABEL = {
		en = "Enable Addon",
		de = "Addon aktivieren",
		fr = "Activer l'addon",
		ru = "Включить аддон",
		ja = "アドオンを有効化",
		zh = "启用插件",
		es = "Activar addon",
		it = "Abilita addon",
		pl = "Włącz dodatek",
	},
	ENABLE_ADDON_TOOLTIP = {
		en = "Enable or disable Research Panel for this character.",
		de = "Aktiviere oder deaktiviere das Forschungs-Panel für diesen Charakter.",
		fr = "Activer ou désactiver le panneau de recherche pour ce personnage.",
		ru = "Включить или отключить панель исследований для этого персонажа.",
		ja = "このキャラクター用の研究パネルを有効化または無効化します。",
		zh = "为此角色启用或禁用研究面板。",
		es = "Activar o desactivar el panel de investigación para este personaje.",
		it = "Abilita o disabilita il pannello di ricerca per questo personaggio.",
		pl = "Włącz lub wyłącz panel badań dla tej postaci.",
	},
	HORIZONTAL_OFFSET_LABEL = {
		en = "Horizontal Offset",
		de = "Horizontaler Versatz",
		fr = "Décalage horizontal",
		ru = "Горизонтальное смещение",
		ja = "水平オフセット",
		zh = "水平偏移",
		es = "Desplazamiento horizontal",
		it = "Offset orizzontale",
		pl = "Przesunięcie poziome",
	},
	HORIZONTAL_OFFSET_TOOLTIP = {
		en = "Moves the Research Panel horizontally.",
		de = "Verschiebt das Forschungs-Panel horizontal.",
		fr = "Déplace le panneau de recherche horizontalement.",
		ru = "Перемещает панель исследований по горизонтали.",
		ja = "研究パネルを水平方向に移動します。",
		zh = "水平移动研究面板。",
		es = "Mueve el panel de investigación horizontalmente.",
		it = "Sposta il pannello di ricerca orizzontalmente.",
		pl = "Przesuwa panel badań poziomo.",
	},
	VERTICAL_OFFSET_LABEL = {
		en = "Vertical Offset",
		de = "Vertikaler Versatz",
		fr = "Décalage vertical",
		ru = "Вертикальное смещение",
		ja = "垂直オフセット",
		zh = "垂直偏移",
		es = "Desplazamiento vertical",
		it = "Offset verticale",
		pl = "Przesunięcie pionowe",
	},
	VERTICAL_OFFSET_TOOLTIP = {
		en = "Moves the Research Panel vertically.",
		de = "Verschiebt das Forschungs-Panel vertikal.",
		fr = "Déplace le panneau de recherche verticalement.",
		ru = "Перемещает панель исследований по вертикали.",
		ja = "研究パネルを垂直方向に移動します。",
		zh = "垂直移动研究面板。",
		es = "Mueve el panel de investigación verticalmente.",
		it = "Sposta il pannello di ricerca verticalmente.",
		pl = "Przesuwa panel badań pionowo.",
	},
  TRANSPARENCY_LABEL = {
    en = "Transparency",
    de = "Transparenz",
    fr = "Transparence",
    ru = "Прозрачность",
    ja = "透明度",
    zh = "透明度",
    es = "Transparencia",
    it = "Trasparenza",
    pl = "Przezroczystość",
  },
  TRANSPARENCY_TOOLTIP = {
    en = "Adjust the transparency of the Research Panel.",
    de = "Stelle die Transparenz des Forschungs-Panels ein.",
    fr = "Ajustez la transparence du panneau de recherche.",
    ru = "Настройте прозрачность панели исследований.",
    ja = "研究パネルの透明度を調整します。",
    zh = "调整研究面板的透明度。",
    es = "Ajusta la transparencia del panel de investigación.",
    it = "Regola la trasparenza del pannello di ricerca.",
    pl = "Dostosuj przezroczystość panelu badań.",
  },
  THEME_LABEL = {
    en = "Theme",
    de = "Thema",
    fr = "Thème",
    ru = "Тема",
    ja = "テーマ",
    zh = "主题",
    es = "Tema",
    it = "Tema",
    pl = "Motyw",
  },
  THEME_TOOLTIP = {
    en = "Select the visual theme for the Research Panel.",
    de = "Wähle das visuelle Thema für das Forschungs-Panel.",
    fr = "Sélectionnez le thème visuel du panneau de recherche.",
    ru = "Выберите визуальную тему панели исследований.",
    ja = "研究パネルのテーマを選択します。",
    zh = "选择研究面板的视觉主题。",
    es = "Selecciona el tema visual para el panel de investigación.",
    it = "Seleziona il tema visivo per il pannello di ricerca.",
    pl = "Wybierz motyw wizualny panelu badań.",
  },
  LIGHT_MODE = {
    en = "Light Mode",
    de = "Heller Modus",
    fr = "Mode clair",
    ru = "Светлый режим",
    ja = "ライトモード",
    zh = "浅色模式",
    es = "Modo claro",
    it = "Modalità chiara",
    pl = "Jasny motyw",
  },
  DARK_MODE = {
    en = "Dark Mode",
    de = "Dunkler Modus",
    fr = "Mode sombre",
    ru = "Темный режим",
    ja = "ダークモード",
    zh = "深色模式",
    es = "Modo oscuro",
    it = "Modalità scura",
    pl = "Ciemny motyw",
  },
  GRAY_MODE = {
    en = "Gray Mode",
    de = "Grauer Modus",
    fr = "Mode gris",
    ru = "Серый режим",
    ja = "グレーモード",
    zh = "灰色模式",
    es = "Modo gris",
    it = "Modalità grigia",
    pl = "Szary motyw",
  },
}

function ResearchPanel:L(key)
	local lang = GetCVar("Language.2")
	return ResearchPanel.strings[key] and (ResearchPanel.strings[key][lang] or ResearchPanel.strings[key]["en"]) or key
end
