AUI = {}
AUI.Settings = {}

AUI_TXT_COLOR_HEADER = ZO_ColorDef:New("98defb")
AUI_TXT_COLOR_SUBMENU = ZO_ColorDef:New("ffffb0")
AUI_TXT_COLOR_VERSION = ZO_ColorDef:New("ffffff")
AUI_TXT_COLOR_AUTHOR = ZO_ColorDef:New("87ddf2")

AUI_MAIN_NAME = "AUI"

AUI_MAIN_DISPLAY_NAME = "AUI (Main)"
AUI_MAIN_VERSION = 3.992
AUI_MAIN_AUTHOR = "Sensi"

AUI_MINIMAP_DISPLAY_NAME = "AUI (Minimap)"
AUI_MINIMAP_VERSION = 2.14
AUI_MINIMAP_AUTHOR = "Sensi"

AUI_ATTRIBUTE_VERSION = 2.26
AUI_ATTRIBUTE_AUTHOR = "Sensi - (Graphics by Johakim)"

AUI_COMBAT_VERSION = 1.10
AUI_COMBAT_AUTHOR = "Sensi"

AUI_ACTIONBAR_VERSION = 1.39
AUI_ACTIONBAR_AUTHOR = "Sensi"

AUI_BUFFS_VERSION = 1.07
AUI_BUFFS_AUTHOR = "Sensi"

AUI_QUESTTRACKER_VERSION = 1.01
AUI_QUESTTRACKER_AUTHOR = "Sensi"

AUI_FRAMEMOVER_VERSION = 1.04
AUI_FRAMEMOVER_AUTHOR = "Sensi"

AUI_TARGET_UNIT_TAG = "reticleover"
AUI_PLAYER_UNIT_TAG = "player"
AUI_GROUP_UNIT_TAG = "group"
AUI_CONTROLED_SIEGE_UNIT_TAG = "controlledsiege"
AUI_ESCORTED_RAM_UNIT_TAG = "escortedram"
AUI_COMPANION_UNIT_TAG = "companion"

AUI_SORTING_SMALL_TO_LARGE = 100
AUI_SORTING_LARGE_TO_SMALL = 101

AUI_ALIGNMENT_CENTER = 100
AUI_ALIGNMENT_LEFT = 101
AUI_ALIGNMENT_RIGHT = 103
AUI_ALIGNMENT_TOP = 105
AUI_ALIGNMENT_TOPLEFT = 106
AUI_ALIGNMENT_TOPRIGHT = 107
AUI_ALIGNMENT_BOTTOM = 105
AUI_ALIGNMENT_BOTTOMLEFT = 106
AUI_ALIGNMENT_BOTTOMRIGHT = 107

AUI_TEXT_ANCHOR_INSIDE = 100
AUI_TEXT_ANCHOR_OUTSIDE = 101

AUI_VERTICAL = 100
AUI_VERTICAL_REVERSE = 101
AUI_HORIZONTAL = 102
AUI_HORIZONTAL_REVERSE = 103

DEFAULT_PREVIEW_HP = 20000