-- Writ Voucher Price Data for AdventurersToolkit
-- Data from UESP Wiki - Complete attunable crafting stations
-- Updated: 2026-01-10
-- Total items: 360+ (Base stations + all attunables for BS/Clothing/Jewelry/WW)

ATWritVoucherData = ATWritVoucherData or {}

-- Default writ voucher to gold conversion rate (adjustable in settings)
ATWritVoucherData.defaultGoldPerVoucher = 1000 -- 1 WV = 1000g default

-- Items that cost Writ Vouchers (by itemId)
ATWritVoucherData.byId = {
    [118327] = {cost = 35, name = "Provisioning Station", type = "base"},
    [118328] = {cost = 35, name = "Alchemy Station", type = "base"},
    [118329] = {cost = 35, name = "Dye Station", type = "base"},
    [118330] = {cost = 35, name = "Enchanting Station", type = "base"},
    [119706] = {cost = 250, name = "Blacksmithing Station (Death's Wind)", type = "attunable"},
    [119707] = {cost = 35, name = "Clothing Station", type = "base"},
    [119708] = {cost = 250, name = "Clothing Station (Death's Wind)", type = "attunable"},
    [119709] = {cost = 250, name = "Clothing Station (Twilight's Embrace)", type = "attunable"},
    [119710] = {cost = 250, name = "Clothing Station (Night's Silence)", type = "attunable"},
    [119711] = {cost = 250, name = "Clothing Station (Whitestrake's Retribution)", type = "attunable"},
    [119712] = {cost = 250, name = "Clothing Station (Seducer)", type = "attunable"},
    [119713] = {cost = 250, name = "Clothing Station (Vampire's Kiss)", type = "attunable"},
    [119714] = {cost = 250, name = "Clothing Station (Magnus' Gift)", type = "attunable"},
    [119715] = {cost = 250, name = "Clothing Station (Night Mother's)", type = "attunable"},
    [119716] = {cost = 250, name = "Clothing Station (Ashen Grip)", type = "attunable"},
    [119717] = {cost = 250, name = "Clothing Station (Oblivion's Foe)", type = "attunable"},
    [119718] = {cost = 250, name = "Clothing Station (Spectre's Eye)", type = "attunable"},
    [119719] = {cost = 250, name = "Clothing Station (Torug's Pact)", type = "attunable"},
    [119720] = {cost = 250, name = "Clothing Station (Hist Bark)", type = "attunable"},
    [119721] = {cost = 250, name = "Clothing Station (Willow's Path)", type = "attunable"},
    [119722] = {cost = 250, name = "Clothing Station (Hunding's Rage)", type = "attunable"},
    [119723] = {cost = 250, name = "Clothing Station (Song of Lamae)", type = "attunable"},
    [119724] = {cost = 250, name = "Clothing Station (Alessia's Bulwark)", type = "attunable"},
    [119725] = {cost = 250, name = "Clothing Station (Orgnum's Scales)", type = "attunable"},
    [119726] = {cost = 250, name = "Clothing Station (Eyes of Mara)", type = "attunable"},
    [119727] = {cost = 250, name = "Clothing Station (Kagrenac's Hope)", type = "attunable"},
    [119728] = {cost = 250, name = "Clothing Station (Shalidor's Curse)", type = "attunable"},
    [119729] = {cost = 250, name = "Clothing Station (Way of the Arena)", type = "attunable"},
    [119730] = {cost = 250, name = "Clothing Station (Twice-Born Star)", type = "attunable"},
    [119731] = {cost = 250, name = "Clothing Station (Noble's Conquest)", type = "attunable"},
    [119732] = {cost = 250, name = "Clothing Station (Redistributor)", type = "attunable"},
    [119733] = {cost = 250, name = "Clothing Station (Armor Master)", type = "attunable"},
    [119734] = {cost = 250, name = "Clothing Station (Law of Julianos)", type = "attunable"},
    [119735] = {cost = 250, name = "Clothing Station (Trial by Fire)", type = "attunable"},
    [119736] = {cost = 250, name = "Clothing Station (Armor of the Code)", type = "attunable"},
    [119737] = {cost = 250, name = "Clothing Station (Morkuldin)", type = "attunable"},
    [119738] = {cost = 250, name = "Clothing Station (Tava's Favor)", type = "attunable"},
    [119739] = {cost = 250, name = "Clothing Station (Clever Alchemist)", type = "attunable"},
    [119740] = {cost = 250, name = "Clothing Station (Eternal Hunt)", type = "attunable"},
    [119741] = {cost = 250, name = "Clothing Station (Kvatch Gladiator)", type = "attunable"},
    [119742] = {cost = 250, name = "Clothing Station (Varen's Legacy)", type = "attunable"},
    [119743] = {cost = 250, name = "Clothing Station (Pelinal's Aptitude)", type = "attunable"},
    [119744] = {cost = 35, name = "Woodworking Station", type = "base"},
    [119745] = {cost = 250, name = "Woodworking Station (Death's Wind)", type = "attunable"},
    [119746] = {cost = 250, name = "Woodworking Station (Twilight's Embrace)", type = "attunable"},
    [119747] = {cost = 250, name = "Woodworking Station (Night's Silence)", type = "attunable"},
    [119748] = {cost = 250, name = "Woodworking Station (Whitestrake's Retribution)", type = "attunable"},
    [119749] = {cost = 250, name = "Woodworking Station (Seducer)", type = "attunable"},
    [119750] = {cost = 250, name = "Woodworking Station (Vampire's Kiss)", type = "attunable"},
    [119751] = {cost = 250, name = "Woodworking Station (Magnus' Gift)", type = "attunable"},
    [119752] = {cost = 250, name = "Woodworking Station (Night Mother's)", type = "attunable"},
    [119753] = {cost = 250, name = "Woodworking Station (Ashen Grip)", type = "attunable"},
    [119754] = {cost = 250, name = "Woodworking Station (Oblivion's Foe)", type = "attunable"},
    [119755] = {cost = 250, name = "Woodworking Station (Spectre's Eye)", type = "attunable"},
    [119756] = {cost = 250, name = "Woodworking Station (Torug's Pact)", type = "attunable"},
    [119757] = {cost = 250, name = "Woodworking Station (Hist Bark)", type = "attunable"},
    [119758] = {cost = 250, name = "Woodworking Station (Willow's Path)", type = "attunable"},
    [119759] = {cost = 250, name = "Woodworking Station (Hunding's Rage)", type = "attunable"},
    [119760] = {cost = 250, name = "Woodworking Station (Song of Lamae)", type = "attunable"},
    [119761] = {cost = 250, name = "Woodworking Station (Alessia's Bulwark)", type = "attunable"},
    [119762] = {cost = 250, name = "Woodworking Station (Orgnum's Scales)", type = "attunable"},
    [119763] = {cost = 250, name = "Woodworking Station (Eyes of Mara)", type = "attunable"},
    [119764] = {cost = 250, name = "Woodworking Station (Kagrenac's Hope)", type = "attunable"},
    [119765] = {cost = 250, name = "Woodworking Station (Shalidor's Curse)", type = "attunable"},
    [119766] = {cost = 250, name = "Woodworking Station (Way of the Arena)", type = "attunable"},
    [119767] = {cost = 250, name = "Woodworking Station (Twice-Born Star)", type = "attunable"},
    [119768] = {cost = 250, name = "Woodworking Station (Noble's Conquest)", type = "attunable"},
    [119769] = {cost = 250, name = "Woodworking Station (Redistributor)", type = "attunable"},
    [119770] = {cost = 250, name = "Woodworking Station (Armor Master)", type = "attunable"},
    [119771] = {cost = 250, name = "Woodworking Station (Law of Julianos)", type = "attunable"},
    [119772] = {cost = 250, name = "Woodworking Station (Trial by Fire)", type = "attunable"},
    [119773] = {cost = 250, name = "Woodworking Station (Armor of the Code)", type = "attunable"},
    [119774] = {cost = 250, name = "Woodworking Station (Morkuldin)", type = "attunable"},
    [119775] = {cost = 250, name = "Woodworking Station (Tava's Favor)", type = "attunable"},
    [119776] = {cost = 250, name = "Woodworking Station (Clever Alchemist)", type = "attunable"},
    [119777] = {cost = 250, name = "Woodworking Station (Eternal Hunt)", type = "attunable"},
    [119778] = {cost = 250, name = "Woodworking Station (Kvatch Gladiator)", type = "attunable"},
    [119779] = {cost = 250, name = "Woodworking Station (Varen's Legacy)", type = "attunable"},
    [119780] = {cost = 250, name = "Woodworking Station (Pelinal's Aptitude)", type = "attunable"},
    [119781] = {cost = 35, name = "Blacksmithing Station", type = "base"},
    [119782] = {cost = 250, name = "Blacksmithing Station (Death's Wind)", type = "attunable"},
    [119783] = {cost = 250, name = "Blacksmithing Station (Twilight's Embrace)", type = "attunable"},
    [119784] = {cost = 250, name = "Blacksmithing Station (Night's Silence)", type = "attunable"},
    [119785] = {cost = 250, name = "Blacksmithing Station (Whitestrake's Retribution)", type = "attunable"},
    [119786] = {cost = 250, name = "Blacksmithing Station (Seducer)", type = "attunable"},
    [119787] = {cost = 250, name = "Blacksmithing Station (Vampire's Kiss)", type = "attunable"},
    [119788] = {cost = 250, name = "Blacksmithing Station (Magnus' Gift)", type = "attunable"},
    [119789] = {cost = 250, name = "Blacksmithing Station (Night Mother's)", type = "attunable"},
    [119790] = {cost = 250, name = "Blacksmithing Station (Ashen Grip)", type = "attunable"},
    [119791] = {cost = 250, name = "Blacksmithing Station (Oblivion's Foe)", type = "attunable"},
    [119792] = {cost = 250, name = "Blacksmithing Station (Spectre's Eye)", type = "attunable"},
    [119793] = {cost = 250, name = "Blacksmithing Station (Torug's Pact)", type = "attunable"},
    [119794] = {cost = 250, name = "Blacksmithing Station (Hist Bark)", type = "attunable"},
    [119795] = {cost = 250, name = "Blacksmithing Station (Willow's Path)", type = "attunable"},
    [119796] = {cost = 250, name = "Blacksmithing Station (Hunding's Rage)", type = "attunable"},
    [119797] = {cost = 250, name = "Blacksmithing Station (Song of Lamae)", type = "attunable"},
    [119798] = {cost = 250, name = "Blacksmithing Station (Alessia's Bulwark)", type = "attunable"},
    [119799] = {cost = 250, name = "Blacksmithing Station (Orgnum's Scales)", type = "attunable"},
    [119800] = {cost = 250, name = "Blacksmithing Station (Eyes of Mara)", type = "attunable"},
    [119801] = {cost = 250, name = "Blacksmithing Station (Kagrenac's Hope)", type = "attunable"},
    [119802] = {cost = 250, name = "Blacksmithing Station (Shalidor's Curse)", type = "attunable"},
    [119803] = {cost = 250, name = "Blacksmithing Station (Way of the Arena)", type = "attunable"},
    [119804] = {cost = 250, name = "Blacksmithing Station (Twice-Born Star)", type = "attunable"},
    [119805] = {cost = 250, name = "Blacksmithing Station (Noble's Conquest)", type = "attunable"},
    [119806] = {cost = 250, name = "Blacksmithing Station (Redistributor)", type = "attunable"},
    [119807] = {cost = 250, name = "Blacksmithing Station (Armor Master)", type = "attunable"},
    [119808] = {cost = 250, name = "Blacksmithing Station (Law of Julianos)", type = "attunable"},
    [119809] = {cost = 250, name = "Blacksmithing Station (Trial by Fire)", type = "attunable"},
    [119810] = {cost = 250, name = "Blacksmithing Station (Armor of the Code)", type = "attunable"},
    [119811] = {cost = 250, name = "Blacksmithing Station (Morkuldin)", type = "attunable"},
    [119812] = {cost = 250, name = "Blacksmithing Station (Tava's Favor)", type = "attunable"},
    [119813] = {cost = 250, name = "Blacksmithing Station (Clever Alchemist)", type = "attunable"},
    [119814] = {cost = 250, name = "Blacksmithing Station (Eternal Hunt)", type = "attunable"},
    [119815] = {cost = 250, name = "Blacksmithing Station (Kvatch Gladiator)", type = "attunable"},
    [119816] = {cost = 250, name = "Blacksmithing Station (Varen's Legacy)", type = "attunable"},
    [119817] = {cost = 250, name = "Blacksmithing Station (Pelinal's Aptitude)", type = "attunable"},
    -- Base Jewelry Station
    [126583] = {cost = 35, name = "Jewelry Crafting Station", type = "base"},
    -- Jewelry Attunable Stations (from UESP)
    [137871] = {cost = 250, name = "Jewelry Crafting Station (Death's Wind)", type = "attunable"},
    [137872] = {cost = 250, name = "Jewelry Crafting Station (Twilight's Embrace)", type = "attunable"},
    [137873] = {cost = 250, name = "Jewelry Crafting Station (Night's Silence)", type = "attunable"},
    [137874] = {cost = 250, name = "Jewelry Crafting Station (Whitestrake's Retribution)", type = "attunable"},
    [137875] = {cost = 250, name = "Jewelry Crafting Station (Seducer)", type = "attunable"},
    [137876] = {cost = 250, name = "Jewelry Crafting Station (Vampire's Kiss)", type = "attunable"},
    [137877] = {cost = 250, name = "Jewelry Crafting Station (Magnus' Gift)", type = "attunable"},
    [137878] = {cost = 250, name = "Jewelry Crafting Station (Night Mother's)", type = "attunable"},
    [137879] = {cost = 250, name = "Jewelry Crafting Station (Ashen Grip)", type = "attunable"},
    [137880] = {cost = 250, name = "Jewelry Crafting Station (Oblivion's Foe)", type = "attunable"},
    [137881] = {cost = 250, name = "Jewelry Crafting Station (Spectre's Eye)", type = "attunable"},
    [137882] = {cost = 250, name = "Jewelry Crafting Station (Torug's Pact)", type = "attunable"},
    [137883] = {cost = 250, name = "Jewelry Crafting Station (Hist Bark)", type = "attunable"},
    [137884] = {cost = 250, name = "Jewelry Crafting Station (Willow's Path)", type = "attunable"},
    [137885] = {cost = 250, name = "Jewelry Crafting Station (Hunding's Rage)", type = "attunable"},
    [137886] = {cost = 250, name = "Jewelry Crafting Station (Song of Lamae)", type = "attunable"},
    [137887] = {cost = 250, name = "Jewelry Crafting Station (Alessia's Bulwark)", type = "attunable"},
    [137888] = {cost = 250, name = "Jewelry Crafting Station (Orgnum's Scales)", type = "attunable"},
    [137889] = {cost = 250, name = "Jewelry Crafting Station (Eyes of Mara)", type = "attunable"},
    [137890] = {cost = 250, name = "Jewelry Crafting Station (Kagrenac's Hope)", type = "attunable"},
    [137891] = {cost = 250, name = "Jewelry Crafting Station (Shalidor's Curse)", type = "attunable"},
    [137892] = {cost = 250, name = "Jewelry Crafting Station (Way of the Arena)", type = "attunable"},
    [137893] = {cost = 250, name = "Jewelry Crafting Station (Twice-Born Star)", type = "attunable"},
    [137894] = {cost = 250, name = "Jewelry Crafting Station (Noble's Conquest)", type = "attunable"},
    [137895] = {cost = 250, name = "Jewelry Crafting Station (Redistributor)", type = "attunable"},
    [137896] = {cost = 250, name = "Jewelry Crafting Station (Armor Master)", type = "attunable"},
    [137897] = {cost = 250, name = "Jewelry Crafting Station (Law of Julianos)", type = "attunable"},
    [137898] = {cost = 250, name = "Jewelry Crafting Station (Trial by Fire)", type = "attunable"},
    [137899] = {cost = 250, name = "Jewelry Crafting Station (Armor of the Code)", type = "attunable"},
    [137900] = {cost = 250, name = "Jewelry Crafting Station (Morkuldin)", type = "attunable"},
    [137901] = {cost = 250, name = "Jewelry Crafting Station (Tava's Favor)", type = "attunable"},
    [137902] = {cost = 250, name = "Jewelry Crafting Station (Clever Alchemist)", type = "attunable"},
    [137903] = {cost = 250, name = "Jewelry Crafting Station (Eternal Hunt)", type = "attunable"},
    [137904] = {cost = 250, name = "Jewelry Crafting Station (Kvatch Gladiator)", type = "attunable"},
    [137905] = {cost = 250, name = "Jewelry Crafting Station (Varen's Legacy)", type = "attunable"},
    [137906] = {cost = 250, name = "Jewelry Crafting Station (Pelinal's Wrath)", type = "attunable"},
    [137907] = {cost = 250, name = "Jewelry Crafting Station (Assassin's Guile)", type = "attunable"},
    [137908] = {cost = 250, name = "Jewelry Crafting Station (Daedric Trickery)", type = "attunable"},
    [137909] = {cost = 250, name = "Jewelry Crafting Station (Shacklebreaker)", type = "attunable"},
    [137910] = {cost = 250, name = "Jewelry Crafting Station (Innate Axiom)", type = "attunable"},
    [137911] = {cost = 250, name = "Jewelry Crafting Station (Fortified Brass)", type = "attunable"},
    [137912] = {cost = 250, name = "Jewelry Crafting Station (Mechanical Acuity)", type = "attunable"},
    -- Summerset+ Jewelry Stations
    [138740] = {cost = 250, name = "Jewelry Crafting Station (Adept Rider)", type = "attunable"},
    [138744] = {cost = 250, name = "Jewelry Crafting Station (Sload's Semblance)", type = "attunable"},
    [138748] = {cost = 250, name = "Jewelry Crafting Station (Nocturnal's Favor)", type = "attunable"},
    -- Murkmire Jewelry
    [145497] = {cost = 250, name = "Jewelry Crafting Station (Grave-Stake Collector)", type = "attunable"},
    [145501] = {cost = 250, name = "Jewelry Crafting Station (Naga Shaman)", type = "attunable"},
    [145505] = {cost = 250, name = "Jewelry Crafting Station (Might of the Lost Legion)", type = "attunable"},
    -- Elsweyr Jewelry
    [150363] = {cost = 250, name = "Jewelry Crafting Station (Coldharbour's Favorite)", type = "attunable"},
    [150367] = {cost = 250, name = "Jewelry Crafting Station (Senche-Raht's Grit)", type = "attunable"},
    [150371] = {cost = 250, name = "Jewelry Crafting Station (Vastarie's Tutelage)", type = "attunable"},
    -- Dragonhold Jewelry
    [155403] = {cost = 250, name = "Jewelry Crafting Station (Daring Corsair)", type = "attunable"},
    [155777] = {cost = 250, name = "Jewelry Crafting Station (Ancient Dragonguard)", type = "attunable"},
    [156151] = {cost = 250, name = "Jewelry Crafting Station (New Moon Acolyte)", type = "attunable"},
    -- Greymoor Jewelry
    [158315] = {cost = 250, name = "Jewelry Crafting Station (Critical Riposte)", type = "attunable"},
    [158689] = {cost = 250, name = "Jewelry Crafting Station (Unchained Aggressor)", type = "attunable"},
    [159063] = {cost = 250, name = "Jewelry Crafting Station (Dauntless Combatant)", type = "attunable"},
    [161220] = {cost = 250, name = "Jewelry Crafting Station (Stuhn's Favor)", type = "attunable"},
    [161594] = {cost = 250, name = "Jewelry Crafting Station (Dragon's Appetite)", type = "attunable"},
    -- Markarth Jewelry
    [167998] = {cost = 250, name = "Jewelry Crafting Station (Red Eagle's Fury)", type = "attunable"},
    [168372] = {cost = 250, name = "Jewelry Crafting Station (Legacy of Karth)", type = "attunable"},
    [168746] = {cost = 250, name = "Jewelry Crafting Station (Aetherial Ascension)", type = "attunable"},
    -- Blackwood Jewelry
    [172454] = {cost = 250, name = "Jewelry Crafting Station (Hist Whisperer)", type = "attunable"},
    [172828] = {cost = 250, name = "Jewelry Crafting Station (Heartland Conqueror)", type = "attunable"},
    [173202] = {cost = 250, name = "Jewelry Crafting Station (Diamond's Victory)", type = "attunable"},
    -- Deadlands Jewelry
    [178805] = {cost = 250, name = "Jewelry Crafting Station (Wretched Vitality)", type = "attunable"},
    [179179] = {cost = 250, name = "Jewelry Crafting Station (Deadlands Demolisher)", type = "attunable"},
    [179553] = {cost = 250, name = "Jewelry Crafting Station (Iron Flask)", type = "attunable"},
    -- High Isle Jewelry
    [184770] = {cost = 250, name = "Jewelry Crafting Station (Order's Wrath)", type = "attunable"},
    [185150] = {cost = 250, name = "Jewelry Crafting Station (Serpent's Disdain)", type = "attunable"},
    [185530] = {cost = 250, name = "Jewelry Crafting Station (Druid's Braid)", type = "attunable"},
    -- Firesong Jewelry
    [191231] = {cost = 250, name = "Jewelry Crafting Station (Chimera's Rebuke)", type = "attunable"},
    [191611] = {cost = 250, name = "Jewelry Crafting Station (Old Growth Brewer)", type = "attunable"},
    [191991] = {cost = 250, name = "Jewelry Crafting Station (Claw of the Forest Wraith)", type = "attunable"},
    -- Necrom Jewelry
    [194561] = {cost = 250, name = "Jewelry Crafting Station (Shattered Fate)", type = "attunable"},
    [194941] = {cost = 250, name = "Jewelry Crafting Station (Telvanni Efficiency)", type = "attunable"},
    [195321] = {cost = 250, name = "Jewelry Crafting Station (Seeker Synthesis)", type = "attunable"},
    -- Gold Road Jewelry
    [205392] = {cost = 250, name = "Jewelry Crafting Station (Tharriker's Strike)", type = "attunable"},
    [205772] = {cost = 250, name = "Jewelry Crafting Station (Highland Sentinel)", type = "attunable"},
    [206152] = {cost = 250, name = "Jewelry Crafting Station (Threads of War)", type = "attunable"},
    -- Newest Jewelry
    [215098] = {cost = 250, name = "Jewelry Crafting Station (Shared Burden)", type = "attunable"},
    [215478] = {cost = 250, name = "Jewelry Crafting Station (Tide-Born Wildstalker)", type = "attunable"},
    [215858] = {cost = 250, name = "Jewelry Crafting Station (Fellowship's Fortitude)", type = "attunable"},
    -- Newer Blacksmithing Stations (post-IC)
    [122607] = {cost = 250, name = "Blacksmithing Station (Assassin's Guile)", type = "attunable"},
    [122608] = {cost = 250, name = "Blacksmithing Station (Daedric Trickery)", type = "attunable"},
    [122609] = {cost = 250, name = "Blacksmithing Station (Shacklebreaker)", type = "attunable"},
    [130367] = {cost = 250, name = "Blacksmithing Station (Fortified Brass)", type = "attunable"},
    [130368] = {cost = 250, name = "Blacksmithing Station (Innate Axiom)", type = "attunable"},
    [130369] = {cost = 250, name = "Blacksmithing Station (Mechanical Acuity)", type = "attunable"},
    [138739] = {cost = 250, name = "Blacksmithing Station (Adept Rider)", type = "attunable"},
    [138743] = {cost = 250, name = "Blacksmithing Station (Sload's Semblance)", type = "attunable"},
    [138747] = {cost = 250, name = "Blacksmithing Station (Nocturnal's Favor)", type = "attunable"},
    [145496] = {cost = 250, name = "Blacksmithing Station (Grave-Stake Collector)", type = "attunable"},
    [145500] = {cost = 250, name = "Blacksmithing Station (Naga Shaman)", type = "attunable"},
    [145504] = {cost = 250, name = "Blacksmithing Station (Might of the Lost Legion)", type = "attunable"},
    [150362] = {cost = 250, name = "Blacksmithing Station (Coldharbour's Favorite)", type = "attunable"},
    [150366] = {cost = 250, name = "Blacksmithing Station (Senche-Raht's Grit)", type = "attunable"},
    [150370] = {cost = 250, name = "Blacksmithing Station (Vastarie's Tutelage)", type = "attunable"},
    [155402] = {cost = 250, name = "Blacksmithing Station (Daring Corsair)", type = "attunable"},
    [155776] = {cost = 250, name = "Blacksmithing Station (Ancient Dragonguard)", type = "attunable"},
    [156150] = {cost = 250, name = "Blacksmithing Station (New Moon Acolyte)", type = "attunable"},
    [158314] = {cost = 250, name = "Blacksmithing Station (Critical Riposte)", type = "attunable"},
    [158688] = {cost = 250, name = "Blacksmithing Station (Unchained Aggressor)", type = "attunable"},
    [159062] = {cost = 250, name = "Blacksmithing Station (Dauntless Combatant)", type = "attunable"},
    [161219] = {cost = 250, name = "Blacksmithing Station (Stuhn's Favor)", type = "attunable"},
    [161593] = {cost = 250, name = "Blacksmithing Station (Dragon's Appetite)", type = "attunable"},
    [163055] = {cost = 250, name = "Blacksmithing Station (Spell Parasite)", type = "attunable"},
    [167997] = {cost = 250, name = "Blacksmithing Station (Red Eagle's Fury)", type = "attunable"},
    [168371] = {cost = 250, name = "Blacksmithing Station (Legacy of Karth)", type = "attunable"},
    [168745] = {cost = 250, name = "Blacksmithing Station (Aetherial Ascension)", type = "attunable"},
    [172453] = {cost = 250, name = "Blacksmithing Station (Hist Whisperer)", type = "attunable"},
    [172827] = {cost = 250, name = "Blacksmithing Station (Heartland Conqueror)", type = "attunable"},
    [173201] = {cost = 250, name = "Blacksmithing Station (Diamond's Victory)", type = "attunable"},
    [178804] = {cost = 250, name = "Blacksmithing Station (Wretched Vitality)", type = "attunable"},
    [179178] = {cost = 250, name = "Blacksmithing Station (Deadlands Demolisher)", type = "attunable"},
    [179552] = {cost = 250, name = "Blacksmithing Station (Iron Flask)", type = "attunable"},
    [184769] = {cost = 250, name = "Blacksmithing Station (Order's Wrath)", type = "attunable"},
    [185149] = {cost = 250, name = "Blacksmithing Station (Serpent's Disdain)", type = "attunable"},
    [185529] = {cost = 250, name = "Blacksmithing Station (Druid's Braid)", type = "attunable"},
    [191230] = {cost = 250, name = "Blacksmithing Station (Chimera's Rebuke)", type = "attunable"},
    [191610] = {cost = 250, name = "Blacksmithing Station (Old Growth Brewer)", type = "attunable"},
    [191990] = {cost = 250, name = "Blacksmithing Station (Claw of the Forest Wraith)", type = "attunable"},
    [194560] = {cost = 250, name = "Blacksmithing Station (Shattered Fate)", type = "attunable"},
    [194940] = {cost = 250, name = "Blacksmithing Station (Telvanni Efficiency)", type = "attunable"},
    [195320] = {cost = 250, name = "Blacksmithing Station (Seeker Synthesis)", type = "attunable"},
    [205391] = {cost = 250, name = "Blacksmithing Station (Tharriker's Strike)", type = "attunable"},
    [205771] = {cost = 250, name = "Blacksmithing Station (Highland Sentinel)", type = "attunable"},
    [206151] = {cost = 250, name = "Blacksmithing Station (Threads of War)", type = "attunable"},
    [215097] = {cost = 250, name = "Blacksmithing Station (Shared Burden)", type = "attunable"},
    [215477] = {cost = 250, name = "Blacksmithing Station (Tide-Born Wildstalker)", type = "attunable"},
    [215857] = {cost = 250, name = "Blacksmithing Station (Fellowship's Fortitude)", type = "attunable"},
    -- Newer Clothing Stations (post-IC)
    [122601] = {cost = 250, name = "Clothing Station (Assassin's Guile)", type = "attunable"},
    [122602] = {cost = 250, name = "Clothing Station (Daedric Trickery)", type = "attunable"},
    [122603] = {cost = 250, name = "Clothing Station (Shacklebreaker)", type = "attunable"},
    [130364] = {cost = 250, name = "Clothing Station (Fortified Brass)", type = "attunable"},
    [130365] = {cost = 250, name = "Clothing Station (Innate Axiom)", type = "attunable"},
    [130366] = {cost = 250, name = "Clothing Station (Mechanical Acuity)", type = "attunable"},
    [138737] = {cost = 250, name = "Clothing Station (Adept Rider)", type = "attunable"},
    [138741] = {cost = 250, name = "Clothing Station (Sload's Semblance)", type = "attunable"},
    [138745] = {cost = 250, name = "Clothing Station (Nocturnal's Favor)", type = "attunable"},
    [145494] = {cost = 250, name = "Clothing Station (Grave-Stake Collector)", type = "attunable"},
    [145498] = {cost = 250, name = "Clothing Station (Naga Shaman)", type = "attunable"},
    [145502] = {cost = 250, name = "Clothing Station (Might of the Lost Legion)", type = "attunable"},
    [150360] = {cost = 250, name = "Clothing Station (Coldharbour's Favorite)", type = "attunable"},
    [150364] = {cost = 250, name = "Clothing Station (Senche-Raht's Grit)", type = "attunable"},
    [150368] = {cost = 250, name = "Clothing Station (Vastarie's Tutelage)", type = "attunable"},
    [155400] = {cost = 250, name = "Clothing Station (Daring Corsair)", type = "attunable"},
    [155774] = {cost = 250, name = "Clothing Station (Ancient Dragonguard)", type = "attunable"},
    [156148] = {cost = 250, name = "Clothing Station (New Moon Acolyte)", type = "attunable"},
    [158312] = {cost = 250, name = "Clothing Station (Critical Riposte)", type = "attunable"},
    [158686] = {cost = 250, name = "Clothing Station (Unchained Aggressor)", type = "attunable"},
    [159060] = {cost = 250, name = "Clothing Station (Dauntless Combatant)", type = "attunable"},
    [161217] = {cost = 250, name = "Clothing Station (Stuhn's Favor)", type = "attunable"},
    [161591] = {cost = 250, name = "Clothing Station (Dragon's Appetite)", type = "attunable"},
    [163053] = {cost = 250, name = "Clothing Station (Spell Parasite)", type = "attunable"},
    [167995] = {cost = 250, name = "Clothing Station (Red Eagle's Fury)", type = "attunable"},
    [168369] = {cost = 250, name = "Clothing Station (Legacy of Karth)", type = "attunable"},
    [168743] = {cost = 250, name = "Clothing Station (Aetherial Ascension)", type = "attunable"},
    [172451] = {cost = 250, name = "Clothing Station (Hist Whisperer)", type = "attunable"},
    [172825] = {cost = 250, name = "Clothing Station (Heartland Conqueror)", type = "attunable"},
    [173199] = {cost = 250, name = "Clothing Station (Diamond's Victory)", type = "attunable"},
    [178802] = {cost = 250, name = "Clothing Station (Wretched Vitality)", type = "attunable"},
    [179176] = {cost = 250, name = "Clothing Station (Deadlands Demolisher)", type = "attunable"},
    [179550] = {cost = 250, name = "Clothing Station (Iron Flask)", type = "attunable"},
    [184767] = {cost = 250, name = "Clothing Station (Order's Wrath)", type = "attunable"},
    [185147] = {cost = 250, name = "Clothing Station (Serpent's Disdain)", type = "attunable"},
    [185527] = {cost = 250, name = "Clothing Station (Druid's Braid)", type = "attunable"},
    [191228] = {cost = 250, name = "Clothing Station (Chimera's Rebuke)", type = "attunable"},
    [191608] = {cost = 250, name = "Clothing Station (Old Growth Brewer)", type = "attunable"},
    [191988] = {cost = 250, name = "Clothing Station (Claw of the Forest Wraith)", type = "attunable"},
    [194558] = {cost = 250, name = "Clothing Station (Shattered Fate)", type = "attunable"},
    [194938] = {cost = 250, name = "Clothing Station (Telvanni Efficiency)", type = "attunable"},
    [195318] = {cost = 250, name = "Clothing Station (Seeker Synthesis)", type = "attunable"},
    [205389] = {cost = 250, name = "Clothing Station (Tharriker's Strike)", type = "attunable"},
    [205769] = {cost = 250, name = "Clothing Station (Highland Sentinel)", type = "attunable"},
    [206149] = {cost = 250, name = "Clothing Station (Threads of War)", type = "attunable"},
    [215095] = {cost = 250, name = "Clothing Station (Shared Burden)", type = "attunable"},
    [215475] = {cost = 250, name = "Clothing Station (Tide-Born Wildstalker)", type = "attunable"},
    [215855] = {cost = 250, name = "Clothing Station (Fellowship's Fortitude)", type = "attunable"},
    -- Newer Woodworking Stations (post-IC)
    [122604] = {cost = 250, name = "Woodworking Station (Assassin's Guile)", type = "attunable"},
    [122605] = {cost = 250, name = "Woodworking Station (Daedric Trickery)", type = "attunable"},
    [122606] = {cost = 250, name = "Woodworking Station (Shacklebreaker)", type = "attunable"},
    [130370] = {cost = 250, name = "Woodworking Station (Fortified Brass)", type = "attunable"},
    [130371] = {cost = 250, name = "Woodworking Station (Innate Axiom)", type = "attunable"},
    [130372] = {cost = 250, name = "Woodworking Station (Mechanical Acuity)", type = "attunable"},
    [138738] = {cost = 250, name = "Woodworking Station (Adept Rider)", type = "attunable"},
    [138742] = {cost = 250, name = "Woodworking Station (Sload's Semblance)", type = "attunable"},
    [138746] = {cost = 250, name = "Woodworking Station (Nocturnal's Favor)", type = "attunable"},
    [145495] = {cost = 250, name = "Woodworking Station (Grave-Stake Collector)", type = "attunable"},
    [145499] = {cost = 250, name = "Woodworking Station (Naga Shaman)", type = "attunable"},
    [145503] = {cost = 250, name = "Woodworking Station (Might of the Lost Legion)", type = "attunable"},
    [150361] = {cost = 250, name = "Woodworking Station (Coldharbour's Favorite)", type = "attunable"},
    [150365] = {cost = 250, name = "Woodworking Station (Senche-Raht's Grit)", type = "attunable"},
    [150369] = {cost = 250, name = "Woodworking Station (Vastarie's Tutelage)", type = "attunable"},
    [155401] = {cost = 250, name = "Woodworking Station (Daring Corsair)", type = "attunable"},
    [155775] = {cost = 250, name = "Woodworking Station (Ancient Dragonguard)", type = "attunable"},
    [156149] = {cost = 250, name = "Woodworking Station (New Moon Acolyte)", type = "attunable"},
    [158313] = {cost = 250, name = "Woodworking Station (Critical Riposte)", type = "attunable"},
    [158687] = {cost = 250, name = "Woodworking Station (Unchained Aggressor)", type = "attunable"},
    [159061] = {cost = 250, name = "Woodworking Station (Dauntless Combatant)", type = "attunable"},
    [161218] = {cost = 250, name = "Woodworking Station (Stuhn's Favor)", type = "attunable"},
    [161592] = {cost = 250, name = "Woodworking Station (Dragon's Appetite)", type = "attunable"},
    [163054] = {cost = 250, name = "Woodworking Station (Spell Parasite)", type = "attunable"},
    [167996] = {cost = 250, name = "Woodworking Station (Red Eagle's Fury)", type = "attunable"},
    [168370] = {cost = 250, name = "Woodworking Station (Legacy of Karth)", type = "attunable"},
    [168744] = {cost = 250, name = "Woodworking Station (Aetherial Ascension)", type = "attunable"},
    [172452] = {cost = 250, name = "Woodworking Station (Hist Whisperer)", type = "attunable"},
    [172826] = {cost = 250, name = "Woodworking Station (Heartland Conqueror)", type = "attunable"},
    [173200] = {cost = 250, name = "Woodworking Station (Diamond's Victory)", type = "attunable"},
    [178803] = {cost = 250, name = "Woodworking Station (Wretched Vitality)", type = "attunable"},
    [179177] = {cost = 250, name = "Woodworking Station (Deadlands Demolisher)", type = "attunable"},
    [179551] = {cost = 250, name = "Woodworking Station (Iron Flask)", type = "attunable"},
    [184768] = {cost = 250, name = "Woodworking Station (Order's Wrath)", type = "attunable"},
    [185148] = {cost = 250, name = "Woodworking Station (Serpent's Disdain)", type = "attunable"},
    [185528] = {cost = 250, name = "Woodworking Station (Druid's Braid)", type = "attunable"},
    [191229] = {cost = 250, name = "Woodworking Station (Chimera's Rebuke)", type = "attunable"},
    [191609] = {cost = 250, name = "Woodworking Station (Old Growth Brewer)", type = "attunable"},
    [191989] = {cost = 250, name = "Woodworking Station (Claw of the Forest Wraith)", type = "attunable"},
    [194559] = {cost = 250, name = "Woodworking Station (Shattered Fate)", type = "attunable"},
    [194939] = {cost = 250, name = "Woodworking Station (Telvanni Efficiency)", type = "attunable"},
    [195319] = {cost = 250, name = "Woodworking Station (Seeker Synthesis)", type = "attunable"},
    [205390] = {cost = 250, name = "Woodworking Station (Tharriker's Strike)", type = "attunable"},
    [205770] = {cost = 250, name = "Woodworking Station (Highland Sentinel)", type = "attunable"},
    [206150] = {cost = 250, name = "Woodworking Station (Threads of War)", type = "attunable"},
    [215096] = {cost = 250, name = "Woodworking Station (Shared Burden)", type = "attunable"},
    [215476] = {cost = 250, name = "Woodworking Station (Tide-Born Wildstalker)", type = "attunable"},
    [215856] = {cost = 250, name = "Woodworking Station (Fellowship's Fortitude)", type = "attunable"},
    -- Grand Master Crafting Stations (1,500 WV base + ~80 attunables @ 250 each = 21,500 WV total)
    -- These stations consume all attunable stations and can craft any set
    [203553] = {cost = 21500, name = "Grand Master Clothing Station", type = "grandmaster"},
    [203554] = {cost = 21500, name = "Grand Master Woodworking Station", type = "grandmaster"},
    [203555] = {cost = 21500, name = "Grand Master Blacksmithing Station", type = "grandmaster"},
    [203556] = {cost = 21500, name = "Grand Master Jewelry Crafting Station", type = "grandmaster"},
}
