LC = LC or {}
local LC = LC
LC.Menu = {}

function LC.Menu.AddonMenu()
  local menuOptions = {
    type         = "panel",
    name         = "Lucent Citadel",
    displayName  = "Lucent Citadel",
    author       = LC.author,
    version      = LC.version,
    registerForRefresh  = true,
    registerForDefaults = true,
  }
  local requiresOSI = "Requires Ody Support Icons."
  local dataTable = {
    {
      type = "description",
      text = "Trial timers, alerts and indicators for Lucent Citadel.",
    },
    {
      type = "divider",
    },
    {
      type = "description",
      text = "For mechanics arrows on players for Target, Fire/frostbrand... install |cff0000OdySupportIcons|r (optional dependency)",
    },
    {
      type = "divider",
    },
    {
      type    = "checkbox",
      name    = "Killswitch",
      default = false,
      getFunc = function() return LC.status.killSwitch end,
      setFunc = function( newValue ) LC.status.killSwitch = newValue end,
      warning = "Prevents the addon from running update ticks without needing to completely disable it."
    },
    {
      type    = "checkbox",
      name    = "Unlock UI (you need to be in the trial)",
      default = false,
      getFunc = function() return not LC.status.locked end,
      setFunc = function( newValue ) LC.UnlockUI(newValue) end,
    },
    {
      type = "description",
      text = "You can also do /lc lock and /lc unlock to reposition the UI.",
    },
    {
      type    = "button",
      name    = "Reset to default position",
      func = function() LC.DefaultPosition()  end,
      warning = "Requires /reloadui for the position to reset",
    },
    {
      type    = "checkbox",
      name    = "Hide welcome text on chat",
      default = false,
      getFunc = function() return LC.savedVariables.hideWelcome end,
      setFunc = function( newValue ) LC.savedVariables.hideWelcome = newValue end,
    },
    {
	    type    = "checkbox",
	    name    = "Enabled on non-hm",
	    default = false,
	    getFunc = function() return LC.savedVariables.enabledOnNonHM end,
	    setFunc = function( newValue ) LC.savedVariables.enabledOnNonHM = newValue end,
	},
    {
      type    = "checkbox",
      name    = "Illuminati Core mode",
      default = false,
      getFunc = function() return LC.savedVariables.illuminatiCoreMode end,
      setFunc = function( newValue ) LC.savedVariables.illuminatiCoreMode = newValue end,
    },
    {
      type    = "checkbox",
      name    = "KMP Core mode",
      default = false,
      getFunc = function() return LC.savedVariables.kmpCoreMode end,
      setFunc = function( newValue ) LC.savedVariables.kmpCoreMode = newValue end,
    },
	{
		type    = "checkbox",
		name    = "Debug Mode",
		default = false,
		getFunc = function() return LC.savedVariables.debugMode end,
		setFunc = function( newValue ) LC.savedVariables.debugMode = newValue end,
	},
    {
      type = "divider",
    },
    {
      type = "header",
      name = "Common",
      reference = "LCCommonHeader"
    },
    {
      type    = "checkbox",
      name    = "Alert: Hindered for Healers",
      default = true,
      getFunc = function() return LC.savedVariables.showCommonHinderedAlertForHealers2 end,
      setFunc = function(newValue) LC.savedVariables.showCommonHinderedAlertForHealers2 = newValue end,
      warning = "Uses Message2 Alert UI Component."
    },
    {
      type = "divider",
    },
    {
      type = "header",
      name = "Zilyesset",
      reference = "LCZilyessetHeader"
    },
    {
      type    = "checkbox",
      name    = "Panel: Teleport Time",
      default = true,
      getFunc = function() return LC.savedVariables.showZilyessetPadTime end,
      setFunc = function(newValue) LC.savedVariables.showZilyessetPadTime = newValue end,
    },
    {
      type    = "checkbox",
      name    = "Alert: Teleport Time",
      default = true,
      getFunc = function() return LC.savedVariables.showZilyessetPadTimeAlert end,
      setFunc = function(newValue) LC.savedVariables.showZilyessetPadTimeAlert = newValue end,
    },
    {
      type = "divider",
    },
    {
      type = "header",
      name = "Orphic",
      reference = "LCOrphicHeader"
    },
    {
      type    = "checkbox",
      name    = "In-Game Marker: Auto-mark Elite Adds",
      default = true,
      getFunc = function() return LC.savedVariables.orphicEliteAddMarker2 end,
      setFunc = function(newValue) LC.savedVariables.orphicEliteAddMarker2 = newValue end,
      warning = "Must be group lead to be able to mark",
    },
    {
      type    = "checkbox",
      name    = "In-Game Marker: Auto-mark Xoryn",
      default = true,
      getFunc = function() return LC.savedVariables.orphicAutoMarkXoryn2 end,
      setFunc = function(newValue) LC.savedVariables.orphicAutoMarkXoryn2 = newValue end,
      warning = "Must be group lead to be able to mark",
    },
    {
      type    = "checkbox",
      name    = "In-Game Orphic Markers: Override",
      default = false,
      getFunc = function() return LC.savedVariables.orphicMarkersGroupLeadOverride end,
      setFunc = function(newValue) LC.savedVariables.orphicMarkersGroupLeadOverride = newValue end,
      warning = "On = Allows you to mark elite adds/Xoryn even if you're not group lead",
    },
    {
      type    = "checkbox",
      name    = "Panel: Xoryn Jumps (Thunder Thrall)",
      default = false,
      getFunc = function() return LC.savedVariables.showThunderThrallPanel end,
      setFunc = function(newValue) LC.savedVariables.showThunderThrallPanel = newValue end,
      warning = "Panel not functional yet",
    },
    {
      type    = "checkbox",
      name    = "Alert: Xoryn Jumps (Thunder Thrall)",
      default = true,
      getFunc = function() return LC.savedVariables.showThunderThrallAlerts2 end,
      setFunc = function(newValue) LC.savedVariables.showThunderThrallAlerts2 = newValue end,
    },
    {
      type    = "checkbox",
      name    = "OdyIcons: Orphic Clock (Numbers)",
      default = true,
      getFunc = function() return LC.savedVariables.showOrphicClock2 end,
      setFunc = function(newValue) LC.savedVariables.showOrphicClock2 = newValue end,
    },
    {
      type    = "checkbox",
      name    = "OdyIcons: Orphic Clock (Cardinal)",
      default = true,
      getFunc = function() return LC.savedVariables.showOrphicClockCardinal end,
      setFunc = function(newValue) LC.savedVariables.showOrphicClockCardinal = newValue end,
    },
    {
      type    = "checkbox",
      name    = "Panel: Mirror Mechanic",
      default = true,
      getFunc = function() return LC.savedVariables.showOrphicMirrorMechPanel end,
      setFunc = function(newValue) LC.savedVariables.showOrphicMirrorMechPanel = newValue end,
    },
    --{
      --type    = "checkbox",
      --name    = "Alerts: Mirror Mechanic",
      --default = true,
      --getFunc = function() return LC.savedVariables.showOrphicMirrorMechAlerts end,
      --setFunc = function(newValue) LC.savedVariables.showOrphicMirrorMechAlerts = newValue end,
      --warning = "This should be enabled to see alerts for the following settings."
    --},
    {
      type    = "slider",
      name    = "Alerts: Mirror Mechanic",
      min = 0,
      max = 3,
      step = 1,
      decimals = 0,
      tooltip = "0=off, 1=Numbers Only, 2=Cardinal Directions Only, 3=Both Numbers and Cardinal Directions",
      default = 3,
      --disabled = function() return LC.status.unlockedUI end,
      getFunc = function() return LC.savedVariables.showOrphicMirrorMechAlerts2 end,
      setFunc = function(newValue) LC.savedVariables.showOrphicMirrorMechAlerts2 = newValue end,
      warning = "0=off, 1=Numbers Only, 2=Cardinal Directions Only, 3=Both Numbers and Cardinal Directions"
    },
    {
      type    = "checkbox",
      name    = "Arrow: Mirror Mechanic",
      default = false,
      getFunc = function() return LC.savedVariables.showOrphicMirrorMechArrow end,
      setFunc = function(newValue) LC.savedVariables.showOrphicMirrorMechArrow = newValue end,
    },
    {
      type    = "checkbox",
      name    = "[Debug] Arrow: Mirror Mechanic",
      default = false,
      getFunc = function() return LC.savedVariables.debugOrphicMirrorMechArrow end,
      setFunc = function(newValue) LC.savedVariables.debugOrphicMirrorMechArrow = newValue end,
      warning = "Will use the 90% Mirror as a the target.",
    },
    {
      type    = "slider",
      name    = "90% Mirror",
      min = 0,
      max = 8,
      step = 1,
      decimals = 0,
      tooltip = "Mirror that you have to flip at 90%. 0 if none. For Cardinal Directions: 1=N, 2=NE, 3=E, 4=SE, 5=S, 6=SW, 7=W, 8=NW",
      default = 0,
      --disabled = function() return LC.status.unlockedUI end,
      getFunc = function() return LC.savedVariables.orphic90Mirror end,
      setFunc = function(newValue) LC.savedVariables.orphic90Mirror = newValue end,
      warning = "1=N, 2=NE, 3=E, 4=SE, 5=S, 6=SW, 7=W, 8=NW",
    },
    --{
        --type    = "dropdown",
        --name    = "90% Mirror - Directions",
        --tooltip = "Tooltip",
        --choices = LC.data.cardinalDirections,
        --choicesValues = LC.settings.dropdownChoiceValues9,
        --choicesTooltips = LC.settings.dropdownChoiceTooltipsDirections,
        --scrollable = true,
        --getFunc = function() return LC.savedVariables.orphic60MirrorDirections end,
        --setFunc = function(value) LC.savedVariables.orphic60MirrorDirections = value end,
        --default = "None",
        --reference = "LC_OrphicMirrorsDirections_Dropdown",
        --disabled = function() return LC.isLAMControlDisabled("LC.savedVariables.orphic60MirrorDirections") end,
    --},
    {
      type    = "slider",
      name    = "60% Mirror",
      min = 0,
      max = 8,
      step = 1,
      decimals = 0,
      tooltip = "Mirror that you have to flip at 60%. 0 if none. For Cardinal Directions: 1=N, 2=NE, 3=E, 4=SE, 5=S, 6=SW, 7=W, 8=NW",
      default = 0,
      --disabled = function() return LC.status.unlockedUI end,
      getFunc = function() return LC.savedVariables.orphic60Mirror end,
      setFunc = function(newValue) LC.savedVariables.orphic60Mirror = newValue end,
      warning = "1=N, 2=NE, 3=E, 4=SE, 5=S, 6=SW, 7=W, 8=NW",
    },
    {
      type    = "slider",
      name    = "40% Mirror",
      min = 0,
      max = 8,
      step = 1,
      decimals = 0,
      tooltip = "Mirror that you have to flip at 40%. 0 if none. For Cardinal Directions: 1=N, 2=NE, 3=E, 4=SE, 5=S, 6=SW, 7=W, 8=NW",
      default = 0,
      --disabled = function() return LC.status.unlockedUI end,
      getFunc = function() return LC.savedVariables.orphic40Mirror end,
      setFunc = function(newValue) LC.savedVariables.orphic40Mirror = newValue end,
      warning = "1=N, 2=NE, 3=E, 4=SE, 5=S, 6=SW, 7=W, 8=NW",
    },
    {
      type    = "slider",
      name    = "15% Mirror",
      min = 0,
      max = 8,
      step = 1,
      decimals = 0,
      tooltip = "Mirror that you have to flip at 15%. 0 if none. For Cardinal Directions: 1=N, 2=NE, 3=E, 4=SE, 5=S, 6=SW, 7=W, 8=NW",
      default = 0,
      --disabled = function() return LC.status.unlockedUI end,
      getFunc = function() return LC.savedVariables.orphic15Mirror end,
      setFunc = function(newValue) LC.savedVariables.orphic15Mirror = newValue end,
      warning = "1=N, 2=NE, 3=E, 4=SE, 5=S, 6=SW, 7=W, 8=NW",
    },
    {
      type = "divider",
    },
    {
      type = "header",
      name = "Baron Rize",
      reference = "LCBaronHeader"
    },
    {
      type    = "checkbox",
      name    = "OdyIcons: Show Baron Lanes 1-8",
      default = true,
      getFunc = function() return LC.savedVariables.showBaronSpots2 end,
      setFunc = function(newValue) LC.savedVariables.showBaronSpots2 = newValue end,
    },
    {
      type = "divider",
    },
    {
      type = "header",
      name = "Arcane Knot",
      reference = "LCXorynHeader"
    },
    {
      type    = "checkbox",
      name    = "Panel: Arcane Knot Order",
      default = true,
      getFunc = function() return LC.savedVariables.showXorynArcaneKnotPanel end, -- LC.savedVariables.showXorynArcaneKnotPanel
      setFunc = function(newValue) LC.savedVariables.showXorynArcaneKnotPanel = newValue end,
    },
    {
      type    = "checkbox",
      name    = "Alert: Arcane Knot Order",
      default = true,
      getFunc = function() return LC.savedVariables.showXorynArcaneKnotAlerts end,
      setFunc = function(newValue) LC.savedVariables.showXorynArcaneKnotAlerts = newValue end,
    },
    {
        type    = "dropdown",
        name    = "Knot Order Profiles",
        choices = LC.status.groupsAtNames,
        --choicesValues = LC.settings.dropdownChoiceValues,
        --choicesTooltips = LC.settings.dropdownChoiceTooltips,
        --scrollable = true,
        getFunc = function() return LC.status.arcaneKnotHolders[1] end,
        setFunc = function(value) LC.status.arcaneKnotHolders[1] = value end,
        --default = "none",
        reference = "LC_ArcaneKnotOrderProfiles_Dropdown",
        --disabled = function() return LC.isLAMControlDisabled("LC.savedVariables.arcaneKnotHolders[1]") end,
        warning = "This feature is not ready yet."
    },
    {
			type = "editbox",
			name = "New Knot Order Profile Name",
			tooltip = nil,
			getFunc = function() return LC.status.nameOfArcaneKnotOrderProfile end,
			setFunc = function(value) LC.status.nameOfArcaneKnotOrderProfile = value end,
			isMultiline = false,
			width = "full",
			warning = nil,
			default = "",
            warning = "This feature is not ready yet."
		},
        
	{
		type = "button",
		--name = GetString( WW_MENU_RESETUI ),
		name = "Save Knot Profile",
		func = LC.SaveKnotProfile,
		warning = "This feature is not ready yet.",
	},
	{
		type = "button",
		--name = GetString( WW_MENU_RESETUI ),
		name = "Get Core @names",
		func = LC.GetCoreAtNames,
		warning = "Only functions for Illuminati and KMP cores",
	},
	{
		type = "button",
		--name = GetString( WW_MENU_RESETUI ),
		name = "Save Manual",
		func = LC.SaveManualKnotProfile,
		warning = "This will save the manually entered Arcane Knot order as a profile that you can load later. For the time being, this is the single profile that can be saved.",
	},
	{
		type = "button",
		--name = GetString( WW_MENU_RESETUI ),
		name = "Load Saved",
		func = LC.LoadSavedKnotProfile,
		warning = "This will load the one and only saved Arcane Knot order.",
	},
    {
			type = "editbox",
			name = "1st Arcane Knot Holder (Manual Entry)",
			tooltip = nil,
			getFunc = function() return LC.status.arcaneKnotHolders[1] end,
			setFunc = function(value) LC.status.arcaneKnotHolders[1] = value end,
			isMultiline = false,
			width = "full",
			warning = nil,
			default = "",
		},
    {
			type = "editbox",
			name = "2nd Arcane Knot Holder (Manual Entry)",
			tooltip = nil,
			getFunc = function() return LC.status.arcaneKnotHolders[2] end,
			setFunc = function(value) LC.status.arcaneKnotHolders[2] = value end,
			isMultiline = false,
			width = "full",
			warning = nil,
			default = "",
		},
    {
			type = "editbox",
			name = "3rd Arcane Knot Holder (Manual Entry)",
			tooltip = nil,
			getFunc = function() return LC.status.arcaneKnotHolders[3] end,
			setFunc = function(value) LC.status.arcaneKnotHolders[3] = value end,
			isMultiline = false,
			width = "full",
			warning = nil,
			default = "",
		},
    {
			type = "editbox",
			name = "4th Arcane Knot Holder (Manual Entry)",
			tooltip = nil,
			getFunc = function() return LC.status.arcaneKnotHolders[4] end,
			setFunc = function(value) LC.status.arcaneKnotHolders[4] = value end,
			isMultiline = false,
			width = "full",
			warning = nil,
			default = "",
		},
    {
			type = "editbox",
			name = "5th Arcane Knot Holder (Manual Entry)",
			tooltip = nil,
			getFunc = function() return LC.status.arcaneKnotHolders[5] end,
			setFunc = function(value) LC.status.arcaneKnotHolders[5] = value end,
			isMultiline = false,
			width = "full",
			warning = nil,
			default = "",
		},
    {
			type = "editbox",
			name = "6th Arcane Knot Holder (Manual Entry)",
			tooltip = nil,
			getFunc = function() return LC.status.arcaneKnotHolders[6] end,
			setFunc = function(value) LC.status.arcaneKnotHolders[6] = value end,
			isMultiline = false,
			width = "full",
			warning = nil,
			default = "",
		},
    {
			type = "editbox",
			name = "7th Arcane Knot Holder (Manual Entry)",
			tooltip = nil,
			getFunc = function() return LC.status.arcaneKnotHolders[7] end,
			setFunc = function(value) LC.status.arcaneKnotHolders[7] = value end,
			isMultiline = false,
			width = "full",
			warning = nil,
			default = "",
		},
    {
			type = "editbox",
			name = "8th Arcane Knot Holder (Manual Entry)",
			tooltip = nil,
			getFunc = function() return LC.status.arcaneKnotHolders[8] end,
			setFunc = function(value) LC.status.arcaneKnotHolders[8] = value end,
			isMultiline = false,
			width = "full",
			warning = nil,
			default = "",
		},
    {
			type = "editbox",
			name = "9th Arcane Knot Holder (Manual Entry)",
			tooltip = nil,
			getFunc = function() return LC.status.arcaneKnotHolders[9] end,
			setFunc = function(value) LC.status.arcaneKnotHolders[9] = value end,
			isMultiline = false,
			width = "full",
			warning = nil,
			default = "",
		},
    {
			type = "editbox",
			name = "10th Arcane Knot Holder (Manual Entry)",
			tooltip = nil,
			getFunc = function() return LC.status.arcaneKnotHolders[10] end,
			setFunc = function(value) LC.status.arcaneKnotHolders[10] = value end,
			isMultiline = false,
			width = "full",
			warning = nil,
			default = "",
		},
    {
			type = "editbox",
			name = "11th Arcane Knot Holder (Manual Entry)",
			tooltip = nil,
			getFunc = function() return LC.status.arcaneKnotHolders[11] end,
			setFunc = function(value) LC.status.arcaneKnotHolders[11] = value end,
			isMultiline = false,
			width = "full",
			warning = nil,
			default = "",
		},
    {
			type = "editbox",
			name = "12th Arcane Knot Holder (Manual Entry)",
			tooltip = nil,
			getFunc = function() return LC.status.arcaneKnotHolders[12] end,
			setFunc = function(value) LC.status.arcaneKnotHolders[12] = value end,
			isMultiline = false,
			width = "full",
			warning = nil,
			default = "",
		},
    --{
      --type    = "checkbox",
      --name    = "Refresh Arcane Knot Holder Dropdowns",
      --default = false,
      --getFunc = function() return LC.savedVariables.xorynRefreshArcaneKnotDropdowns end,
      --setFunc = function(newValue) LC.savedVariables.xorynRefreshArcaneKnotDropdowns = newValue end,
      --warning = "Manually refreshes the dropdowns. Should only be used when there are 12 players in group."
    --},
    
	{
		type = "button",
		--name = GetString( WW_MENU_RESETUI ),
		name = "Refresh Dropdowns",
		func = LC.RefreshArcaneKnotDropdownMenus,
		warning = "Should only use when group is full 12. This feature is not ready yet.",
	},
    {
        type    = "dropdown",
        name    = "1st Arcane Knot Holder",
        tooltip = "Tooltip",
        choices = LC.status.groupsAtNames,
        choicesValues = LC.settings.dropdownChoiceValues,
        choicesTooltips = LC.settings.dropdownChoiceTooltips,
        scrollable = true,
        getFunc = function() return LC.status.arcaneKnotHolders[1] end,
        setFunc = function(value) LC.status.arcaneKnotHolders[1] = value end,
        default = "none",
        reference = "LC_ArcaneKnotHolder1_Dropdown",
        --disabled = function() return LC.isLAMControlDisabled("LC.status.arcaneKnotHolders[1]") end,
        warning = "This feature is not ready yet."
    },
    {
        type    = "dropdown",
        name    = "2nd Arcane Knot Holder",
        tooltip = "Tooltip",
        choices = LC.status.groupsAtNames,
        choicesValues = LC.settings.dropdownChoiceValues,
        choicesTooltips = LC.settings.dropdownChoiceTooltips,
        scrollable = true,
        getFunc = function() return LC.status.arcaneKnotHolders[2] end,
        setFunc = function(value) LC.status.arcaneKnotHolders[2] = value end,
        default = "none",
        reference = "LC_ArcaneKnotHolder2_Dropdown",
        --disabled = function() return LC.isLAMControlDisabled("LC.status.arcaneKnotHolders[2]") end,
        warning = "This feature is not ready yet."
    },
    {
        type    = "dropdown",
        name    = "3rd Arcane Knot Holder",
        tooltip = "Tooltip",
        choices = LC.status.groupsAtNames,
        choicesValues = LC.settings.dropdownChoiceValues,
        choicesTooltips = LC.settings.dropdownChoiceTooltips,
        scrollable = true,
        getFunc = function() return LC.status.arcaneKnotHolders[3] end,
        setFunc = function(value) LC.status.arcaneKnotHolders[3] = value end,
        default = "none",
        reference = "LC_ArcaneKnotHolder3_Dropdown",
        --disabled = function() return LC.isLAMControlDisabled("LC.status.arcaneKnotHolders[3]") end,
        warning = "This feature is not ready yet."
    },
    {
        type    = "dropdown",
        name    = "4th Arcane Knot Holder",
        tooltip = "Tooltip",
        choices = LC.status.groupsAtNames,
        choicesValues = LC.settings.dropdownChoiceValues,
        choicesTooltips = LC.settings.dropdownChoiceTooltips,
        scrollable = true,
        getFunc = function() return LC.status.arcaneKnotHolders[4] end,
        setFunc = function(value) LC.status.arcaneKnotHolders[4] = value end,
        default = "none",
        reference = "LC_ArcaneKnotHolder4_Dropdown",
        --disabled = function() return LC.isLAMControlDisabled("LC.status.arcaneKnotHolders[4]") end,
        warning = "This feature is not ready yet."
    },
    {
        type    = "dropdown",
        name    = "5th Arcane Knot Holder",
        tooltip = "Tooltip",
        choices = LC.status.groupsAtNames,
        choicesValues = LC.settings.dropdownChoiceValues,
        choicesTooltips = LC.settings.dropdownChoiceTooltips,
        scrollable = true,
        getFunc = function() return LC.status.arcaneKnotHolders[5] end,
        setFunc = function(value) LC.status.arcaneKnotHolders[5] = value end,
        default = "none",
        reference = "LC_ArcaneKnotHolder5_Dropdown",
        --disabled = function() return LC.isLAMControlDisabled("LC.status.arcaneKnotHolders[5]") end,
        warning = "This feature is not ready yet."
    },
    {
        type    = "dropdown",
        name    = "6th Arcane Knot Holder",
        tooltip = "Tooltip",
        choices = LC.status.groupsAtNames,
        choicesValues = LC.settings.dropdownChoiceValues,
        choicesTooltips = LC.settings.dropdownChoiceTooltips,
        scrollable = true,
        getFunc = function() return LC.status.arcaneKnotHolders[6] end,
        setFunc = function(value) LC.status.arcaneKnotHolders[6] = value end,
        default = "none",
        reference = "LC_ArcaneKnotHolder6_Dropdown",
        --disabled = function() return LC.isLAMControlDisabled("LC.status.arcaneKnotHolders[6]") end,
        warning = "This feature is not ready yet."
    },
    {
        type    = "dropdown",
        name    = "7th Arcane Knot Holder",
        tooltip = "Tooltip",
        choices = LC.status.groupsAtNames,
        choicesValues = LC.settings.dropdownChoiceValues,
        choicesTooltips = LC.settings.dropdownChoiceTooltips,
        scrollable = true,
        getFunc = function() return LC.status.arcaneKnotHolders[7] end,
        setFunc = function(value) LC.status.arcaneKnotHolders[7] = value end,
        default = "none",
        reference = "LC_ArcaneKnotHolder7_Dropdown",
        --disabled = function() return LC.isLAMControlDisabled("LC.status.arcaneKnotHolders[7]") end,
        warning = "This feature is not ready yet."
    },
    {
        type    = "dropdown",
        name    = "8th Arcane Knot Holder",
        tooltip = "Tooltip",
        choices = LC.status.groupsAtNames,
        choicesValues = LC.settings.dropdownChoiceValues,
        choicesTooltips = LC.settings.dropdownChoiceTooltips,
        scrollable = true,
        getFunc = function() return LC.status.arcaneKnotHolders[8] end,
        setFunc = function(value) LC.status.arcaneKnotHolders[8] = value end,
        default = "none",
        reference = "LC_ArcaneKnotHolder8_Dropdown",
        --disabled = function() return LC.isLAMControlDisabled("LC.status.arcaneKnotHolders[8]") end,
        warning = "This feature is not ready yet."
    },
    {
        type    = "dropdown",
        name    = "9th Arcane Knot Holder",
        tooltip = "Tooltip",
        choices = LC.status.groupsAtNames,
        choicesValues = LC.settings.dropdownChoiceValues,
        choicesTooltips = LC.settings.dropdownChoiceTooltips,
        scrollable = true,
        getFunc = function() return LC.status.arcaneKnotHolders[9] end,
        setFunc = function(value) LC.status.arcaneKnotHolders[9] = value end,
        default = "none",
        reference = "LC_ArcaneKnotHolder9_Dropdown",
        --disabled = function() return LC.isLAMControlDisabled("LC.status.arcaneKnotHolders[9]") end,
        warning = "This feature is not ready yet."
    },
    {
        type    = "dropdown",
        name    = "10th Arcane Knot Holder",
        tooltip = "Tooltip",
        choices = LC.status.groupsAtNames,
        choicesValues = LC.settings.dropdownChoiceValues,
        choicesTooltips = LC.settings.dropdownChoiceTooltips,
        scrollable = true,
        getFunc = function() return LC.status.arcaneKnotHolders[10] end,
        setFunc = function(value) LC.status.arcaneKnotHolders[10] = value end,
        default = "none",
        reference = "LC_ArcaneKnotHolder10_Dropdown",
        --disabled = function() return LC.isLAMControlDisabled("LC.status.arcaneKnotHolders[10]") end,
        warning = "This feature is not ready yet."
    },
    {
        type    = "dropdown",
        name    = "11th Arcane Knot Holder",
        tooltip = "Tooltip",
        choices = LC.status.groupsAtNames,
        choicesValues = LC.settings.dropdownChoiceValues,
        choicesTooltips = LC.settings.dropdownChoiceTooltips,
        scrollable = true,
        getFunc = function() return LC.status.arcaneKnotHolders[11] end,
        setFunc = function(value) LC.status.arcaneKnotHolders[11] = value end,
        default = "none",
        reference = "LC_ArcaneKnotHolder11_Dropdown",
        --disabled = function() return LC.isLAMControlDisabled("LC.status.arcaneKnotHolders[11]") end,
        warning = "This feature is not ready yet."
    },
    {
        type    = "dropdown",
        name    = "12th Arcane Knot Holder",
        tooltip = "Tooltip",
        choices = LC.status.groupsAtNames,
        choicesValues = LC.settings.dropdownChoiceValues,
        choicesTooltips = LC.settings.dropdownChoiceTooltips,
        scrollable = true,
        getFunc = function() return LC.status.arcaneKnotHolders[12] end,
        setFunc = function(value) LC.status.arcaneKnotHolders[12] = value end,
        default = "none",
        reference = "LC_ArcaneKnotHolder12_Dropdown",
        --disabled = function() return LC.isLAMControlDisabled("LC.status.arcaneKnotHolders[12]") end,
        warning = "This feature is not ready yet."
    },
    {
      type    = "checkbox",
      name    = "Panel: Tempest Assault Timers",
      default = false,
      getFunc = function() return LC.savedVariables.showXorynMirrorPanel end,
      setFunc = function(newValue) LC.savedVariables.showXorynMirrorPanel = newValue end,
      warning = "This is the mirror line mechanic."
    },
    {
      type    = "checkbox",
      name    = "Alert: Tempest Assault Timers",
      default = true,
      getFunc = function() return LC.savedVariables.showXorynMirrorAlert end,
      setFunc = function(newValue) LC.savedVariables.showXorynMirrorAlert = newValue end,
      warning = "This is the mirror line mechanic."
    },
    {
      type    = "checkbox",
      name    = "Panel: Fluctuating Current Order Assistant",
      default = false,
      getFunc = function() return LC.savedVariables.showXorynFluxPanel end,
      setFunc = function(newValue) LC.savedVariables.showXorynFluxPanel = newValue end,
    },
    {
      type    = "checkbox",
      name    = "Alert: Fluctuating Current Order Assistant",
      default = false,
      getFunc = function() return LC.savedVariables.showXorynFluctuatingAlert end,
      setFunc = function(newValue) LC.savedVariables.showXorynFluctuatingAlert = newValue end,
      warning = "This is the blue lightning circle mechanic that 1-shots after 15 seconds."
    },
    {
      type = "divider",
    },
    {
      type = "header",
      name = "Misc",
      reference = "LCMiscMenu"
    },
    {
      type = "description",
      text = "Unlock UI first to be able to change scale.",
    },
    {
      type    = "slider",
      name    = "Panel UI Scale",
      min = 0.1,
      max = 3.0,
      step = 0.1,
      decimals = 1,
	  default = 1,
      tooltip = "0.5 is tiny, 2 is huge",
      default = LC.savedVariables.panelUICustomScale,
      disabled = function() return LC.status.unlockedUI end,
      getFunc = function() return LC.savedVariables.panelUICustomScale end,
      setFunc = function(newValue) LC.SetPanelScale(newValue) end,
      warning = "Only for extreme resolutions. Addon optimized for scale=1. You can /reloadui after changing the setting to prevent it from getting reset if you crash."
    },
	{
      type    = "slider",
      name    = "Alert UI Scale",
      min = 0.1,
      max = 3.0,
      step = 0.1,
      decimals = 1,
	  default = 0.5,
      tooltip = "0.5 is tiny, 2 is huge",
      default = LC.savedVariables.alertUICustomScale,
      disabled = function() return LC.status.unlockedUI end,
      getFunc = function() return LC.savedVariables.alertUICustomScale end,
      setFunc = function(newValue) LC.SetAlertScale(newValue) end,
      warning = "Only for extreme resolutions. Addon optimized for scale=1. You can /reloadui after changing the setting to prevent it from getting reset if you crash."
    },
  }

  LAM = LibAddonMenu2
  LAM:RegisterAddonPanel(LC.name .. "Options", menuOptions)
  LAM:RegisterOptionControls(LC.name .. "Options", dataTable)
end