local strings = {
    LBOOKS_QUEST_BOOK = "Libro disponible a través de una misión",
    LBOOKS_MAYBE_NOT_HERE = "[El libro tal vez no esté aquí]",
    LBOOKS_QUEST_IN_ZONE = "Misión en <<1>>",
    -- Thank You for datamining
    LBOOKS_THANK_YOU1 = "Gracias",
    LBOOKS_THANK_YOU_LONG1 = "Eres el primero en encontrar este libro perdido",
    LBOOKS_THANK_YOU10 = "¡Seguid así!",
    LBOOKS_THANK_YOU_LONG10 = "Y grabaremos todos esos libros antiguos",
    LBOOKS_THANK_YOU20 = "Bibliotecario",
    LBOOKS_THANK_YOU_LONG20 = "Por cierto, ¿leíste esos libros? Deberías",
    LBOOKS_THANK_YOU30 = "Guardián de los Pergaminos Antiguos",
    LBOOKS_THANK_YOU_LONG30 = "Podría ser un buen título para ti",
    -- tooltips
    LBOOKS_KNOWN = "Recogido",
    LBOOKS_MOREINFO1 = "Ciudad",
    LBOOKS_MOREINFO2 = "Cueva",
    LBOOKS_MOREINFO3 = "Mazmorra pública",
    LBOOKS_MOREINFO4 = "Subterráneo",
    LBOOKS_MOREINFO5 = "Instancia de grupo",
    LBOOKS_SET_WAYPOINT = GetString(SI_WORLD_MAP_ACTION_SET_PLAYER_WAYPOINT) ..
        ":|cFFFFFF<<1>>|r",
    -- settings menu header
    LBOOKS_TITLE = "LoreBooks",
    -- appearance
    LBOOKS_PIN_TEXTURE = "Seleccionar íconos del pin del mapa",
    LBOOKS_PIN_TEXTURE_EIDETIC = "Seleccionar iconos del pin del mapa (<<1>>)",
    LBOOKS_PIN_TEXTURE_DESC = "Seleccione los iconos de los pines del mapa.",
    LBOOKS_PIN_GRAYSCALE = "-Usar escala de grises",
    LBOOKS_PIN_GRAYSCALE_DESC = "Usa escala de grises para los libros de historia recopilados. (Solo se aplica a 'íconos reales')",
    LBOOKS_PIN_GRAYSCALE_EIDETIC_DESC = "Use escala de grises para libros eidéticos no recolectados. (Solo se aplica a 'íconos reales')",
    LBOOKS_PIN_SIZE = "Tamaño del pin",
    LBOOKS_PIN_SIZE_DESC = "Establecer el tamaño de los pines del mapa.",
    LBOOKS_PIN_LAYER = "Capa del pin",
    LBOOKS_PIN_LAYER_DESC = "Establecer la capa de los pines del mapa",
    LBOOKS_PIN_TEXTURE1 = "Iconos reales",
    LBOOKS_PIN_TEXTURE2 = "Conjunto de iconos de libro 1",
    LBOOKS_PIN_TEXTURE3 = "Conjunto de iconos de libro 2",
    LBOOKS_PIN_TEXTURE4 = "Iconos de Esohead (Rushmik)",
    -- compass
    LBOOKS_COMPASS_UNKNOWN = "Mostrar libros de historia en la brújula.",
    LBOOKS_COMPASS_UNKNOWN_DESC = "Mostrar/Ocultar iconos de libros de historia desconocidos en la brújula.",
    LBOOKS_COMPASS_DIST = "Distancia máxima del pin",
    LBOOKS_COMPASS_DIST_DESC = "La distancia máxima para que aparezcan los pines en la brújula.",
    -- filters
    LBOOKS_UNKNOWN = "Mostrar libros de historia desconocidos",
    LBOOKS_UNKNOWN_DESC = "Mostrar/Ocultar iconos de libros de historia desconocidos en el mapa.",
    LBOOKS_COLLECTED = "Mostrar libros de historia ya recopilados",
    LBOOKS_COLLECTED_DESC = "Mostrar/Ocultar iconos de libros de historia ya recopilados en el mapa.",
    LBOOKS_SHARE_DATA = "Comparte tus descubrimientos con el autor de LoreBooks",
    LBOOKS_SHARE_DATA_DESC = "Habilitar esta opción compartirá sus descubrimientos con el autor de LoreBooks enviando automáticamente un correo dentro del juego con los datos recopilados.\nEsta opción solo está disponible para los usuarios de la UE, incluso si los datos recopilados se comparten con los de NA\nTenga en cuenta que puede encontrar un pequeño retraso con sus habilidades cuando se envía el correo. El correo se envía silenciosamente cada 30 libros leídos.",
    LBOOKS_EIDETIC = "Mostrar memoria eidética desconocida",
    LBOOKS_EIDETIC_DESC = "Mostrar/Ocultar pergaminos de memoria eidética desconocidos en el mapa. Esos pergaminos son pergaminos relacionados con el lore que no están involucrados en la progresión del gremio de magos, pero solo informativos sobre Tamriel",
    LBOOKS_EIDETIC_COLLECTED = "Mostrar memoria eidética conocida",
    LBOOKS_EIDETIC_COLLECTED_DESC = "Mostrar/Ocultar pergaminos de memoria eidética conocidos en el mapa. Esos pergaminos son pergaminos relacionados con el lore que no están involucrados en la progresión del gremio de magos, pero solo informativos sobre Tamriel",
    LBOOKS_COMPASS_EIDETIC = "Mostrar memoria eidética desconocida en la brújula",
    LBOOKS_COMPASS_EIDETIC_DESC = "Mostrar/ocultar pergaminos de memoria eidética desconocidos en la brújula. Esos pergaminos son pergaminos relacionados con el lore que no están involucrados en la progresión del gremio de magos, pero solo informativos sobre Tamriel",
    LBOOKS_UNLOCK_EIDETIC = "Desbloquear biblioteca eidética",
    LBOOKS_UNLOCK_EIDETIC_DESC = "Esto desbloqueará la Biblioteca Eidética incluso si no has completado la línea de misiones del Gremio de Magos. Esta opción solo es válida para usuarios de EN/FR/DE.",
    LBOOKS_UNLOCK_EIDETIC_WARNING = "Esta opción está deshabilitada porque LoreBooks aún no se ha actualizado para la última actualización del juego o tu idioma no es compatible",
    -- worldmap filters
    LBOOKS_FILTER_UNKNOWN = "Libros de historia desconocidos",
    LBOOKS_FILTER_COLLECTED = "Libros de historia recopilados",
    LBOOKS_FILTER_EICOLLECTED = "<<1>> (recopilado)",
    LBOOKS_SEARCH_LABEL = "Buscar en la biblioteca de lore:",
    LBOOKS_SEARCH_PLACEHOLDER = "Nombre del libro de referencia",
    LBOOKS_RANDOM_POSITION = "[Estantería]",
    -- Report
    LBOOKS_REPORT_KEYBIND_RPRT = "Reporte",
    LBOOKS_REPORT_KEYBIND_SWITCH = "Modo interruptor",
    LBOOKS_REPORT_KEYBIND_COPY = "Copia",
    LBOOKS_RS_FEW_BOOKS_MISSING = "Todavía faltan pocos libros en la Biblioteca de Shalidor...",
    LBOOKS_RS_MDONE_BOOKS_MISSING = "¡Has maximizado la línea de habilidades del Gremio de magos! Pero aún faltan pocos libros",
    LBOOKS_RS_GOT_ALL_BOOKS = "Recogiste toda la Biblioteca Shalidor. ¡Felicitaciones!",
    LBOOKS_RE_FEW_BOOKS_MISSING = "Aún faltan pocos libros en la Memoria Eidética...",
    LBOOKS_RE_GOT_ALL_BOOKS = "Recogiste toda la Memoria Eidética. ¡Felicitaciones!",
    LBOOKS_RE_THREESHOLD_ERROR = "Es necesario recopilar algunos libros más para obtener un informe sobre la memoria eidética...",
    LBOOKS_REPORT_BOOK = "Libro de informes <<1>>...",
    LBOOKS_EIDETIC_REPORT = "Gracias por informar las correcciones de LoreBooks.\nSi desea contribuir, habilite el uso compartido en la configuración de complementos.\nSi desea corregir un pin específico, es el lugar correcto.\nAsegúrese también de tener la última versión del complemento. -on (Su versión: <<1>>)\n\nMi informe: ",
    LBOOKS_QUEST_PLACEHOLDER = "Por favor, escriba el nombre de la misión",
    LBOOKS_QUEST_LABEL = "Nombre de la misión:",
    LBOOKS_RS_NOT_HERE_ANYMORE = "El libro ya no está aquí",
    LBOOKS_RS_NOT_HERE_ANYMORE_DESC = "Con el tiempo, algunos libros se mueven. Estoy absolutamente seguro de que este libro ya no está aquí (busqué unos minutos, arriba, abajo, tal vez una pequeña gruta)",
    LBOOKS_RS_NOT_HERE_ANYMORE_ERR = "Este libro se ha encontrado recientemente (Horns of the Reach). Busque un poco mejor.",
    LBOOKS_RE_ELIGIBLE = "Este libro se ha encontrado en Horns of the Reach (septiembre de 2017) Eidetic Memory en esta ubicación exacta. Puede informarlo",
    LBOOKS_RE_NOT_ELIGIBLE = "Este libro aún no se ha encontrado en Horns of the Reach (septiembre de 2017) Eidetic Memory en esta ubicación exacta. No puede informarlo. Si no encuentra el libro, asegúrese de tener la misión vinculada. El libro también puede haber sido trasladado a otro lugar .",
    LBOOKS_RS_BELONG_QUEST = "El libro pertenece a una misión",
    LBOOKS_RS_BELONG_QUEST_DESC = "Este libro solo está disponible antes/durante/después de una misión.",
    LBOOKS_RS_IN_DUNGEON = "Reserva en una mazmorra",
    LBOOKS_RS_IN_DUNGEON_DESC = "Este libro está en una pequeña mazmorra o en una cueva y este no tiene mapa.",
    LBOOKS_SEND_DATA = "Envía mi corrección",
    LBOOKS_REPORT_THANK_YOU = "Gracias",
    LBOOKS_REPORT_THANK_YOU_SEC = "Su modificación será verificada y agregada en la próxima versión",
    -- Immersive Mode
    LBOOKS_IMMERSIVE = "Habilitar el modo inmersivo basado en",
    LBOOKS_IMMERSIVE_DESC = "Los libros de historia desconocidos no se mostrarán en función de la finalización del siguiente objetivo en la zona actual que está viendo",
    LBOOKS_IMMERSIVE_CHOICE1 = "Discapacitado",
    LBOOKS_IMMERSIVE_CHOICE2 = "Misión principal de la zona",
    LBOOKS_IMMERSIVE_CHOICE3 = GetString(SI_MAPFILTER8),
    LBOOKS_IMMERSIVE_CHOICE4 = GetAchievementCategoryInfo(6),
    LBOOKS_IMMERSIVE_CHOICE5 = "Misiones de zona",
    -- Quest Books
    LBOOKS_USE_QUEST_BOOKS = "Use Quest Books (Beta)",
    LBOOKS_USE_QUEST_BOOKS_DESC = "Intentarán usar herramientas de búsqueda cuando las reciba para evitar perder libros que solo contengan inventario. También puede usar cosas como mapas porque no hay distinción entre libros y otros elementos de búsqueda utilizables."
}
for stringId, stringValue in pairs(strings) do
    ZO_CreateStringId(stringId, stringValue)
    SafeAddVersion(stringId, 1)
end
