ZO_SharedOptions_SettingsData[SETTING_PANEL_CAMERA][SETTING_TYPE_GAMEPAD][GAMEPAD_SETTING_CAMERA_SENSITIVITY_X].maxValue = 2
ZO_SharedOptions_SettingsData[SETTING_PANEL_CAMERA][SETTING_TYPE_GAMEPAD][GAMEPAD_SETTING_CAMERA_SENSITIVITY_Y].maxValue = 2


SLASH_COMMANDS['/setmaxsensitivity'] = function(a) ZO_SharedOptions_SettingsData[SETTING_PANEL_CAMERA][SETTING_TYPE_GAMEPAD][GAMEPAD_SETTING_CAMERA_SENSITIVITY_X].maxValue = tonumber(a) ZO_SharedOptions_SettingsData[SETTING_PANEL_CAMERA][SETTING_TYPE_GAMEPAD][GAMEPAD_SETTING_CAMERA_SENSITIVITY_Y].maxValue = tonumber(a) end

SLASH_COMMANDS['/setdefaultmaxsensitivity'] = function(a) ZO_SharedOptions_SettingsData[SETTING_PANEL_CAMERA][SETTING_TYPE_GAMEPAD][GAMEPAD_SETTING_CAMERA_SENSITIVITY_X].maxValue = 1.05 ZO_SharedOptions_SettingsData[SETTING_PANEL_CAMERA][SETTING_TYPE_GAMEPAD][GAMEPAD_SETTING_CAMERA_SENSITIVITY_Y].maxValue = 1.05 end