local R = Conductor.Registry
local entries = {
    {"WAR_HORN","War Horn",{"ULT_WARHORN"},{38564}},
    {"AGGRESSIVE_HORN","Aggressive Horn",{"ULT_WARHORN","MAJOR_FORCE"},{40224}},
    {"STURDY_HORN","Sturdy Horn",{"ULT_WARHORN"},{}},
    {"BARRIER","Barrier",{"ULT_BARRIER","GROUP_SHIELDING","MAJOR_PROTECTION"},{}},
    {"REVIVING_BARRIER","Reviving Barrier",{"ULT_BARRIER","GROUP_SHIELDING","MAJOR_PROTECTION"},{}},
    {"REPLENISHING_BARRIER","Replenishing Barrier",{"ULT_BARRIER","GROUP_SHIELDING","MAJOR_PROTECTION","ULTIMATE_RESTORE"},{}},
    {"FROZEN_COLOSSUS","Frozen Colossus",{"ULT_COLOSSUS","MAJOR_VULNERABILITY"},{}},
    {"GLACIAL_COLOSSUS","Glacial Colossus",{"ULT_COLOSSUS","MAJOR_VULNERABILITY"},{}},
    {"PESTILENT_COLOSSUS","Pestilent Colossus",{"ULT_COLOSSUS","MAJOR_VULNERABILITY"},{}},
    {"ELEMENTAL_RAGE","Elemental Rage",{"ULT_DAMAGE"},{}},
    {"EYE_OF_THE_STORM","Eye of the Storm",{"ULT_DAMAGE"},{}},
    {"ELEMENTAL_STORM","Elemental Storm",{"ULT_DAMAGE"},{}},
    {"METEOR","Meteor",{"ULT_DAMAGE"},{}},
    {"ICE_COMET","Ice Comet",{"ULT_DAMAGE"},{}},
    {"SHOOTING_STAR","Shooting Star",{"ULT_DAMAGE"},{}},
    {"STANDARD_OF_MIGHT","Standard of Might",{"ULT_DAMAGE"},{}},
    {"NOVA","Nova",{"MAJOR_MAIM"},{}},
    {"SOLAR_PRISON","Solar Prison",{"MAJOR_MAIM","SYNERGY_PROVIDER"},{}},
    {"SOLAR_DISTURBANCE","Solar Disturbance",{"MAJOR_MAIM"},{}},
    {"SOUL_TETHER","Soul Tether",{"CROWD_CONTROL"},{}},
    {"RITE_OF_PASSAGE","Rite of Passage",{"MAJOR_PROTECTION"},{}},
    {"REMEMBRANCE","Remembrance",{"MAJOR_PROTECTION"},{}},
    {"PRACTICED_INCANTATION","Practiced Incantation",{"MAJOR_PROTECTION"},{}},
    {"SLEET_STORM","Sleet Storm",{"MAJOR_PROTECTION"},{}},
    {"NORTHERN_STORM","Northern Storm",{"MAJOR_PROTECTION"},{}},
    {"PERMAFROST","Permafrost",{"MAJOR_PROTECTION","CROWD_CONTROL"},{}},
    {"BOLSTERING_DARKNESS","Bolstering Darkness",{"MAJOR_PROTECTION"},{}},
    {"VEIL_OF_BLADES","Veil of Blades",{"MAJOR_PROTECTION"},{}},
    {"CONSUMING_DARKNESS","Consuming Darkness",{"MAJOR_PROTECTION"},{}},
    {"MAGMA_SHELL","Magma Shell",{"GROUP_SHIELDING"},{}},
    {"STORM_ATRONACH","Storm Atronach",{"ULT_DAMAGE"},{}},
    {"GREATER_STORM_ATRONACH","Greater Storm Atronach",{"ULT_DAMAGE","MAJOR_BERSERK"},{}},
    {"CHARGED_ATRONACH","Summon Charged Atronach",{"ULT_DAMAGE","MAJOR_BERSERK"},{}},
    {"PANACEA","Panacea",{},{}},
    {"LIFE_GIVER","Life Giver",{},{}},
    {"LIGHTS_CHAMPION","Light's Champion",{"MAJOR_FORCE"},{}},
    {"CRYPTCANNON","Cryptcannon",{"ULTIMATE_RESTORE"},{}},
}
for _, entry in ipairs(entries) do
    R:Register("ULTIMATES",entry[1],{name=entry[2],provides=entry[3],abilityIds=entry[4],needsIdValidation=#entry[4]==0,sourceType="ULTIMATE"})
end
R:RegisterAlias("ULTIMATES","COLOSSUS","GLACIAL_COLOSSUS")
