-- This file is automatically generated. DO NOT EDIT IT DIRECTLY!
-- Visit https://weblate.sir.insidi.at/or/projects/easytravel/messages/fr/ to update translations.
local settext = LibGetText("EasyTravel").settext
settext("Jump has been interrupted, unhandled result: %d, %s", "La téléportation a été interrompu, erreur inconnue : %d, %s")
settext("/tp,/travel,/goto", "/tp,/travel,/goto")
settext("Travel to the specified target", "Voyage vers la personne spécifiée")
settext("Target cannot be reached via jump", "La destination ne peut être atteinte par une téléportation")
settext("<<1>><<2>> -|caaaaaa <<3>>", "<<1>><<2>> -|caaaaaa <<3>>")
settext("<<1>> -|caaaaaa <<2[no players/$d player/$d players]>>", "<<1>> -|caaaaaa <<2[Aucun joueur/$d joueur/$d joueurs]>>")
settext("<<1>> -|caaaaaa <<2>>", "<<1>> -|caaaaaa <<2>>")
settext("home", "home")
settext("Traveling to <<1>>", "Voyage vers <<1>>")
settext("Preparing to jump", "Préparation au saut")
settext("Jump requested", "Téléportation initialisée")
settext("Jump in progress (<<1>> seconds left)", "Téléportation en cours (<<1>> secondes restantes)")
settext("Jump failed", "Téléportation échouée")
settext("No suitable players found\nWaiting for new targets", "Aucun joueur n'a été trouvé pour voyager\nEn attente de nouveaux joueurs")
settext("<<1>> -|caaaaaa <<2>>, <<3>>", "<<1>> -|caaaaaa <<2>>, <<3>>")