-- This file is automatically generated. DO NOT EDIT IT DIRECTLY!
-- Visit https://weblate.sir.insidi.at/or/projects/easytravel/messages/ru/ to update translations.
local settext = LibGetText("EasyTravel").settext
settext("<<1>> -|caaaaaa <<2>>, <<3>>", "<<1>> -|caaaaaa <<2>>, <<3>>")
settext("Jump failed", "Перемещение провалено")
settext("Travel to the specified target", "Перемещение к выбранной цели")
settext("Target cannot be reached via jump", "Цель не может быть достигнута через перемещение")
settext("<<1>><<2>> -|caaaaaa <<3>>", "<<1>><<2>> -|caaaaaa <<3>>")
settext("<<1>> -|caaaaaa <<2[no players/$d player/$d players]>>", "<<1>> -|caaaaaa <<2[нет игроков/$d игрок/$d игроков]>>")
settext("<<1>> -|caaaaaa <<2>>", "<<1>> -|caaaaaa <<2>>")
settext("home", "home")
settext("No suitable players found\nWaiting for new targets", "Подходящих игроков не найдено\nОжидание новых целей")
settext("Jump has been interrupted, unhandled result: %d, %s", "Перемещение прервано, неизвестная ошибка: %d, %s")
settext("/tp,/travel,/goto", "/tp,/travel,/goto")
settext("Traveling to <<1>>", "Перемещение - <<1>>")
settext("Preparing to jump", "Подготовка к перемещению")
settext("Jump requested", "Перемещение запрошено")
settext("Jump in progress (<<1>> seconds left)", "Перемещение в процессе (осталось <<1>> сек.)")