---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by YeOldeDragon.
--- DateTime: 2022-01-02
---
YeOldeLootHistory = YeOldeLootHistory or {}

--#region Addon usings

--local YEOLDE_LOOTITEM_TYPE_CROWN_CRATE = "EsoUI/Art/HUD/Keyboard/lootHistory_icon_crownCrates.dds"
--local YEOLDE_LOOTITEM_TYPE_ANTIQUITIES = "EsoUI/Art/HUD/Keyboard/lootHistory_icon_antiquities.dds"
--local YEOLDE_LOOTITEM_TYPE_COLLECTIONS = "EsoUI/Art/HUD/Keyboard/lootHistory_icon_collections.dds"
--local YEOLDE_LOOTITEM_TYPE_CRAFTBAG = "EsoUI/Art/HUD/Gamepad/gp_lootHistory_icon_craftBag.dds"
local YEOLDE_LOOTITEM_TYPE_STOLEN = "YeOldeLootHistory/resources/inventory_stolenitem_icon.dds"
local YEOLDE_LOOTITEM_BACKGROUND_TEXTURE = "YeOldeLootHistory/resources/listitem_backdrop.dds"
local YEOLDE_LOOT_HISTORY_HIGHLIGHT_BG = "YeOldeLootHistory/resources/loothistory_highlight.dds"

local YEOLDE_BACKGROUND_COLOR_STOLEN = ZO_ColorDef:New("220000")
local YEOLDE_BACKGROUND_COLOR_DEFAULT = ZO_BLACK

local YEOLDE_WORLD_ICONS =
{
    [YEOLDE_WORLD_LEGERDEMAIN] = "YeOldeLootHistory/resources/skill_legerdemain.dds", -- "/esoui/art/icons/servicemappins/servicepin_fence.dds",
    [YEOLDE_WORLD_SOUL] = "/esoui/art/icons/crownstore_skillline_soulmagic.dds", -- ou encore achievement_crownstore_skillline_soulmagic_check
    [YEOLDE_WORLD_VAMPIRE] = "/esoui/art/icons/store_vampirebite_01.dds", -- ou crownstore_skillline_vampire
    [YEOLDE_WORLD_WEREWOLF] = "/esoui/art/icons/store_werewolfbite_01.dds", -- ou crownstore_skillline_werewolf, ability_werewolf_010, ability_werewolf_005
    [YEOLDE_WORLD_SCRYING] = "YeOldeLootHistory/resources/skill_scrying.dds", -- ou achievement_u26_skyrim_scry10, skilllinexp_scrying, u26_ability_scrying_05b
    [YEOLDE_WORLD_EXCAVATION] = "/esoui/art/icons/u26_ability_digging_02.dds", -- ou skilllinexp_digging, u26_ability_digging_01, achievement_u26_skyrim_dig100, achievement_u26_skyrim_dig10, achievement_u26_skyrim_digallsquaresonboard
}
--#endregion Addon usings

--#region Log function
local function EmitMessage(text)
    if text == "" then
        text = "[Empty String]"
    end

    if CHAT_ROUTER then
        CHAT_ROUTER:AddDebugMessage(text)
    elseif RequestDebugPrintText then
        RequestDebugPrintText(text)
    end
end

--- Log text or table (1st level only)
function Log(...)
    if YeOldeLootHistory.SV.DebugEnabled then


        for i = 1, select("#", ...) do
            local value = select(i, ...)
            if(type(value) == "table") then
                for k, v in pairs(value)
                do
                    local vType = type(v)
                    EmitMessage("->("..vType.."): "..tostring(k).." = "..tostring(v))
                end
            else
                EmitMessage(tostring (value))
            end
        end
    end
end

function Logf(...)
    if YeOldeLootHistory.SV.DebugEnabled then
        d(string.format(...))
    end
end

--#endregion Log function


local function HasKey(tbl, key)
    for k,_ in pairs(tbl) do
        if k == key then
            return true
        end
    end
    return false
end


--- Check if the default Loot History is disabled
local function LootHistoryDisabled()
    return tonumber(GetSetting(SETTING_TYPE_LOOT,LOOT_SETTING_LOOT_HISTORY)) ~= 1
end


--- Original function from ingame\zo_loot\loothistory_shared.lua:51
local function SetupEntryText(control, data)
    local text = data.text
    if type(text) == "function" then
        text = text(data)
    end
    control.label:SetText(text)
    control.label:SetColor(data.color:UnpackRGBA())
end


--- Original function from ingame\zo_loot\loothistory_shared.lua:59
local function SetupIconOverlayText(control, data)
    local overlayText = ZO_LootHistory_Shared.GetIconOverlayTextFromData(data)
    control.iconOverlayText:SetText(overlayText)

    local showOverlayText = ZO_LootHistory_Shared.GetShowIconOverlayTextFromData(data)
    control.iconOverlayText:SetHidden(not showOverlayText)
end


local function SetupHighlightBackground(control, data)
    local hidden = false
    if data.isStolen then
        control.backgroundHighlight:SetTexture(YEOLDE_LOOT_HISTORY_HIGHLIGHT_BG)
        control.backgroundHighlight:SetColor(YEOLDE_BACKGROUND_COLOR_STOLEN:UnpackRGB())

    -- elseif data.entryType == LOOT_ENTRY_TYPE_CROWN_CRATE  or
    --        data.entryType == LOOT_ENTRY_TYPE_ANTIQUITY_LEAD or
    --        data.entryType == LOOT_ENTRY_TYPE_COLLECTIBLE then
    --     control.backgroundHighlight:SetTexture(YEOLDE_LOOT_HISTORY_HIGHLIGHT_BG)
    --     control.backgroundHighlight:SetColor(YEOLDE_BACKGROUND_COLOR_DEFAULT:UnpackRGB())

    elseif data.highlight then -- I missed something?
        control.backgroundHighlight:SetTexture(YEOLDE_LOOT_HISTORY_HIGHLIGHT_BG)
        control.backgroundHighlight:SetColor(YEOLDE_BACKGROUND_COLOR_DEFAULT:UnpackRGB())
    else
        hidden = true
    end
    control.backgroundHighlight:SetHidden(hidden)
end


local function SetupBackground(control, data)
    control.background:SetTexture(YEOLDE_LOOTITEM_BACKGROUND_TEXTURE)
    if data.isStolen then
        control.background:SetColor(YEOLDE_BACKGROUND_COLOR_STOLEN:UnpackRGB())
    elseif data.backgroundColor then
        control.background:SetColor(data.backgroundColor:UnpackRGB())
    else
        -- default color
        control.background:SetColor(YEOLDE_BACKGROUND_COLOR_DEFAULT:UnpackRGB())
    end
end


local function SetupStatusIcon(control, data)
    local hidden = false
    if data.isStolen then
        control.statusIcon:SetTexture(YEOLDE_LOOTITEM_TYPE_STOLEN)
    elseif data.statusIcon then
        control.statusIcon:SetTexture(data.statusIcon)
    else
        hidden = true
    end
    control.statusIcon:SetHidden(hidden)
end


local function SetupIcon(control, data)
    local icon = data.icon
    if data.entryType == LOOT_ENTRY_TYPE_SKILL_EXPERIENCE then
        Logf("YeOlde:SetupIcon(): name: %s, skillType: %d, skillLineIndex: %d",data.skillLineData:GetFormattedName(), data.skillLineData.skillTypeData:GetSkillType(), data.skillLineData.skillLineIndex)
        if data.skillLineData.skillTypeData:GetSkillType() == SKILL_TYPE_WORLD then
            icon = YEOLDE_WORLD_ICONS[data.skillLineData.skillLineIndex]
        end
    end
    control.icon:SetTexture(icon)

end


--- Original function from ingame\zo_loot\loothistory_shared.lua:67
local function LootSetupFunction(control, data)
    SetupEntryText(control, data)
    SetupIcon(control, data)
    SetupIconOverlayText(control, data)
    SetupBackground(control, data)
    SetupHighlightBackground(control, data)
    SetupStatusIcon(control, data)
end


local function AllowExtendedSkillHistory(skillType, skillLineIndex, skillLineData)
    if skillType == SKILL_TYPE_WORLD then
        Logf("YeOlde:AllowExtendedSkillHistory() -> skillType: World, name: %s, skillLineIndex: %d", skillLineData:GetFormattedName(), skillLineIndex)
        --Log(skillLineData)
    end
    return skillType == SKILL_TYPE_WORLD and skillLineData.isActive and YeOldeLootHistory.SV.ShowType[skillLineIndex]
end


-- Cloned function from ZO_LootHistory_Shared class.
local function OnSkillExperienceUpdated(skillType, skillLineIndex, reason, rank, previousXP, currentXP)
    local xpGain = currentXP - previousXP
    if  LootHistoryDisabled() or xpGain <= 0 then return end

    local skillLineData = SKILLS_DATA_MANAGER:GetSkillLineDataByIndices(skillType, skillLineIndex)
    Logf("YeOlde: OnSkillExperienceUpdated(type: %d, index: %d, name: %s, amount: %d)", skillType, skillLineIndex, skillLineData.name, xpGain)

    if AllowExtendedSkillHistory(skillType, skillLineIndex, skillLineData) then
        YeOldeLootHistory.ZoLootHistory:AddSkillEntry(skillLineData, xpGain)
    end
end


function YeOldeLootHistory.UpdatePersistentContainerShowTime()
    YeOldeLootHistory.ZoLootHistory.lootStreamPersistent:SetContainerShowTime(YeOldeLootHistory.SV.PersistantContainerShowTime)
end

function YeOldeLootHistory.UpdateContainerShowTime()
    YeOldeLootHistory.ZoLootHistory.lootStream:SetContainerShowTime(YeOldeLootHistory.SV.ContainerShowTime)
end

function YeOldeLootHistory.UpdateMaxEntries()
    YeOldeLootHistory.ZoLootHistory.lootStreamPersistent.maxDisplayedEntries = YeOldeLootHistory.SV.MaxItems
    YeOldeLootHistory.ZoLootHistory.lootStream.maxDisplayedEntries = YeOldeLootHistory.SV.MaxItems
end

function YeOldeLootHistory.UpdateLootHistoryDisplayInMenus()
    for _, scene in pairs(YeOldeLootHistory.MenuScenes) do
        if YeOldeLootHistory.SV.ShowInMenus then
            scene:AddFragment(KEYBOARD_LOOT_HISTORY_FRAGMENT)
        else
            scene:RemoveFragment(KEYBOARD_LOOT_HISTORY_FRAGMENT)
        end
    end
end

function YeOldeLootHistory.OverrideLootSetupFunctions()
    local mode = "ZO_LootHistory_KeyboardEntry"
    if IsInGamepadPreferredMode() then
        mode = "ZO_LootHistory_GamepadEntry"
    end
    YeOldeLootHistory.ZoLootHistory.lootStreamPersistent.templates[mode].setup = LootSetupFunction
    YeOldeLootHistory.ZoLootHistory.lootStream.templates[mode].setup = LootSetupFunction
end


function LootHistoryExt_Load()
    YeOldeLootHistory.ZoLootHistory = SYSTEMS:GetObject(ZO_LOOT_HISTORY_NAME)
    YeOldeLootHistory.UpdatePersistentContainerShowTime()
    YeOldeLootHistory.UpdateContainerShowTime()
    YeOldeLootHistory.UpdateMaxEntries()
    YeOldeLootHistory.UpdateLootHistoryDisplayInMenus()

    YeOldeLootHistory.OverrideLootSetupFunctions()

    EVENT_MANAGER:RegisterForEvent(YeOldeLootHistory.AddonName, EVENT_SKILL_XP_UPDATE, function(eventId, ...) OnSkillExperienceUpdated(...) end)
end


