ElmsMarkers = {
    name = "ElmsMarkers",
    version = "3.1.0",
    variableVersion = 7,
    defaults = {
        enabled = true,
        locked = true,
        positions = {},
        configStringExport = "",
        configStringImport = "",
        selectedIconTexture = 13,
        selectedIconSize = 64,
        subscribeToLead = false,
        optIntoCommands = true,
        frameOffsetX = 600,
        frameOffsetY = 700,
        announcementOffsetX = 540,
        announcementOffsetY = 400,
        announcementScale = 0.5,

    },
    placedIcons = {},
    dataQueue = {},
    dataShareTuple = { },
    PING_RATE = 2000,
  }

  ElmsMarkers.iconData = {
    [1] = "elmsmarkers/icons/1.dds",
    [2] = "elmsmarkers/icons/2.dds",
    [3] = "elmsmarkers/icons/3.dds",
    [4] = "elmsmarkers/icons/4.dds",
    [5] = "elmsmarkers/icons/5.dds",
    [6] = "elmsmarkers/icons/6.dds",
    [7] = "elmsmarkers/icons/7.dds",
    [8] = "elmsmarkers/icons/8.dds",
    [9] = "elmsmarkers/icons/9.dds",
    [10] = "elmsmarkers/icons/10.dds",
    [11] = "elmsmarkers/icons/11.dds",
    [12] = "elmsmarkers/icons/12.dds",
    [13] = "OdySupportIcons/icons/arrow.dds",
    [14] = "OdySupportIcons/icons/squares/marker_lightblue.dds",
    [15] = "OdySupportIcons/icons/squares/square_blue.dds",
    [16] = "OdySupportIcons/icons/squares/square_green.dds",
    [17] = "OdySupportIcons/icons/squares/square_orange.dds",
    [18] = "OdySupportIcons/icons/squares/square_orange_OT.dds",
    [19] = "OdySupportIcons/icons/squares/square_pink.dds",
    [20] = "OdySupportIcons/icons/squares/square_red.dds",
    [21] = "OdySupportIcons/icons/squares/square_red_MT.dds",
    [22] = "OdySupportIcons/icons/squares/square_yellow.dds",
    [23] = "OdySupportIcons/icons/squares/squaretwo_blue.dds",
    [24] = "OdySupportIcons/icons/squares/squaretwo_blue_one.dds",
    [25] = "OdySupportIcons/icons/squares/squaretwo_blue_two.dds",
    [26] = "OdySupportIcons/icons/squares/squaretwo_blue_three.dds",
    [27] = "OdySupportIcons/icons/squares/squaretwo_blue_four.dds",
    [28] = "OdySupportIcons/icons/squares/squaretwo_green.dds",
    [29] = "OdySupportIcons/icons/squares/squaretwo_green_one.dds",
    [30] = "OdySupportIcons/icons/squares/squaretwo_green_two.dds",
    [31] = "OdySupportIcons/icons/squares/squaretwo_green_three.dds",
    [32] = "OdySupportIcons/icons/squares/squaretwo_green_four.dds",
    [33] = "OdySupportIcons/icons/squares/squaretwo_orange.dds",
    [34] = "OdySupportIcons/icons/squares/squaretwo_orange_one.dds",
    [35] = "OdySupportIcons/icons/squares/squaretwo_orange_two.dds",
    [36] = "OdySupportIcons/icons/squares/squaretwo_orange_three.dds",
    [37] = "OdySupportIcons/icons/squares/squaretwo_orange_four.dds",
    [38] = "OdySupportIcons/icons/squares/squaretwo_pink.dds",
    [39] = "OdySupportIcons/icons/squares/squaretwo_red.dds",
    [40] = "OdySupportIcons/icons/squares/squaretwo_red_one.dds",
    [41] = "OdySupportIcons/icons/squares/squaretwo_red_two.dds",
    [42] = "OdySupportIcons/icons/squares/squaretwo_red_three.dds",
    [43] = "OdySupportIcons/icons/squares/squaretwo_red_four.dds",
    [44] = "OdySupportIcons/icons/squares/squaretwo_yellow.dds",
    [45] = "elmsmarkers/icons/a.dds",
    [46] = "elmsmarkers/icons/b.dds",
    [47] = "elmsmarkers/icons/c.dds",
    [48] = "elmsmarkers/icons/d.dds",
    [49] = "elmsmarkers/icons/e.dds",
    [50] = "elmsmarkers/icons/f.dds",
    [51] = "elmsmarkers/icons/g.dds",
    [52] = "elmsmarkers/icons/h.dds",
    [53] = "elmsmarkers/icons/i.dds",
    [54] = "elmsmarkers/icons/j.dds",
    [55] = "elmsmarkers/icons/k.dds",
    [56] = "elmsmarkers/icons/l.dds",
    [57] = "elmsmarkers/icons/m.dds",
    [58] = "elmsmarkers/icons/n.dds",
    [59] = "elmsmarkers/icons/o.dds",
    [60] = "elmsmarkers/icons/p.dds",
    [61] = "elmsmarkers/icons/q.dds",
    [62] = "elmsmarkers/icons/r.dds",
    [63] = "elmsmarkers/icons/s.dds",
    [64] = "elmsmarkers/icons/t.dds",
    [65] = "elmsmarkers/icons/u.dds",
    [66] = "elmsmarkers/icons/v.dds",
    [67] = "elmsmarkers/icons/w.dds",
    [68] = "elmsmarkers/icons/x.dds",
    [69] = "elmsmarkers/icons/y.dds",
    [70] = "elmsmarkers/icons/z.dds",
    [71] = "elmsmarkers/icons/sharkpog.dds",
  }  
  
  ElmsMarkers.optionMap = {
    ["1"] = 1,
    ["2"] = 2,
    ["3"] = 3,
    ["4"] = 4,
    ["5"] = 5,
    ["6"] = 6,
    ["7"] = 7,
    ["8"] = 8,
    ["9"] = 9,
    ["10"] = 10,
    ["11"] = 11,
    ["12"] = 12,
    ["Arrow"] = 13,
    ["Marker_Lightblue"] = 14,
    ["Square_Blue"] = 15,
    ["Square_Green"] = 16,
    ["Square_Orange"] = 17,
    ["Square_OT"] = 18,
    ["Square_Pink"] = 19,
    ["Square_Red"] = 20,
    ["Square_MT"] = 21,
    ["Square_Yellow"] = 22,
    ["Diamond_Blue"] = 23,
    ["Diamond_Blue_1"] = 24,
    ["Diamond_Blue_2"] = 25,
    ["Diamond_Blue_3"] = 26,
    ["Diamond_Blue_4"] = 27,
    ["Diamond_Green"] = 28,
    ["Diamond_Green_1"] = 29,
    ["Diamond_Green_2"] = 30,
    ["Diamond_Green_3"] = 31,
    ["Diamond_Green_4"] = 32,
    ["Diamond_Orange"] = 33,
    ["Diamond_Orange_1"] = 34,
    ["Diamond_Orange_2"] = 35,
    ["Diamond_Orange_3"] = 36,
    ["Diamond_Orange_4"] = 37,
    ["Diamond_Pink"] = 38,
    ["Diamond_Red"] = 39,
    ["Diamond_Red_1"] = 40,
    ["Diamond_Red_2"] = 41,
    ["Diamond_Red_3"] = 42,
    ["Diamond_Red_4"] = 43,
    ["Diamond_Yellow"] = 44,
    ["A"] = 45,
    ["B"] = 46,
    ["C"] = 47,
    ["D"] = 48,
    ["E"] = 49,
    ["F"] = 50,
    ["G"] = 51,
    ["H"] = 52,
    ["I"] = 53,
    ["J"] = 54,
    ["K"] = 55,
    ["L"] = 56,
    ["M"] = 57,
    ["N"] = 58,
    ["O"] = 59,
    ["P"] = 60,
    ["Q"] = 61,
    ["R"] = 62,
    ["S"] = 63,
    ["T"] = 64,
    ["U"] = 65,
    ["V"] = 66,
    ["W"] = 67,
    ["X"] = 68,
    ["Y"] = 69,
    ["Z"] = 70,
    ["sharkpog"] = 71,
  }

  ElmsMarkers.reverseOptionMap = {
    [1] = "1",
    [2] = "2",
    [3] = "3",
    [4] = "4",
    [5] = "5",
    [6] = "6",
    [7] = "7",
    [8] = "8",
    [9] = "9",
    [10] = "10",
    [11] = "11",
    [12] = "12",
    [13] = "Arrow",
    [14] = "Marker_Lightblue",
    [15] = "Square_Blue",
    [16] = "Square_Green",
    [17] = "Square_Orange",
    [18] = "Square_OT",
    [19] = "Square_Pink",
    [20] = "Square_Red",
    [21] = "Square_MT",
    [22] = "Square_Yellow",
    [23] = "Diamond_Blue",
    [24] = "Diamond_Blue_1",
    [25] = "Diamond_Blue_2",
    [26] = "Diamond_Blue_3",
    [27] = "Diamond_Blue_4",
    [28] = "Diamond_Green",
    [29] = "Diamond_Green_1",
    [30] = "Diamond_Green_2",
    [31] = "Diamond_Green_3",
    [32] = "Diamond_Green_4",
    [33] = "Diamond_Orange",
    [34] = "Diamond_Orange_1",
    [35] = "Diamond_Orange_2",
    [36] = "Diamond_Orange_3",
    [37] = "Diamond_Orange_4",
    [38] = "Diamond_Pink",
    [39] = "Diamond_Red",
    [40] = "Diamond_Red_1",
    [41] = "Diamond_Red_2",
    [42] = "Diamond_Red_3",
    [43] = "Diamond_Red_4",
    [44] = "Diamond_Yellow",
    [45] = "A",
    [46] = "B",
    [47] = "C",
    [48] = "D",
    [49] = "E",
    [50] = "F",
    [51] = "G",
    [52] = "H",
    [53] = "I",
    [54] = "J",
    [55] = "K",
    [56] = "L",
    [57] = "M",
    [58] = "N",
    [59] = "O",
    [60] = "P",
    [61] = "Q",
    [62] = "R",
    [63] = "S",
    [64] = "T",
    [65] = "U",
    [66] = "V",
    [67] = "W",
    [68] = "X",
    [69] = "Y",
    [70] = "Z",
    [71] = "sharkpog"
  }

  ElmsMarkers.options = {
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "Arrow",
    "Marker_Lightblue",
    "Square_Blue",
    "Square_Green",
    "Square_Orange",
    "Square_OT",
    "Square_Pink",
    "Square_Red",
    "Square_MT",
    "Square_Yellow",
    "Diamond_Blue",
    "Diamond_Blue_1",
    "Diamond_Blue_2",
    "Diamond_Blue_3",
    "Diamond_Blue_4",
    "Diamond_Green",
    "Diamond_Green_1",
    "Diamond_Green_2",
    "Diamond_Green_3",
    "Diamond_Green_4",
    "Diamond_Orange",
    "Diamond_Orange_1",
    "Diamond_Orange_2",
    "Diamond_Orange_3",
    "Diamond_Orange_4",
    "Diamond_Pink",
    "Diamond_Red",
    "Diamond_Red_1",
    "Diamond_Red_2",
    "Diamond_Red_3",
    "Diamond_Red_4",
    "Diamond_Yellow",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "sharkpog"
  }  