local _traitTypes = {
	[ITEM_TRAIT_TYPE_ARMOR_AGGRESSIVE] = ITEM_TRAIT_TYPE_CATEGORY_ARMOR,
	[ITEM_TRAIT_TYPE_ARMOR_AUGMENTED] = ITEM_TRAIT_TYPE_CATEGORY_ARMOR,
	[ITEM_TRAIT_TYPE_ARMOR_BOLSTERED] = ITEM_TRAIT_TYPE_CATEGORY_ARMOR,
	[ITEM_TRAIT_TYPE_ARMOR_DIVINES] = ITEM_TRAIT_TYPE_CATEGORY_ARMOR,
	[ITEM_TRAIT_TYPE_ARMOR_FOCUSED] = ITEM_TRAIT_TYPE_CATEGORY_ARMOR,
	[ITEM_TRAIT_TYPE_ARMOR_IMPENETRABLE] = ITEM_TRAIT_TYPE_CATEGORY_ARMOR,
	[ITEM_TRAIT_TYPE_ARMOR_INFUSED] = ITEM_TRAIT_TYPE_CATEGORY_ARMOR,
	[ITEM_TRAIT_TYPE_ARMOR_INTRICATE] = ITEM_TRAIT_TYPE_CATEGORY_ARMOR,
	[ITEM_TRAIT_TYPE_ARMOR_NIRNHONED] = ITEM_TRAIT_TYPE_CATEGORY_ARMOR,
	[ITEM_TRAIT_TYPE_ARMOR_ORNATE] = ITEM_TRAIT_TYPE_CATEGORY_ARMOR,
	[ITEM_TRAIT_TYPE_ARMOR_PROLIFIC] = ITEM_TRAIT_TYPE_CATEGORY_ARMOR,
	[ITEM_TRAIT_TYPE_ARMOR_PROSPEROUS] = ITEM_TRAIT_TYPE_CATEGORY_ARMOR,
	[ITEM_TRAIT_TYPE_ARMOR_QUICKENED] = ITEM_TRAIT_TYPE_CATEGORY_ARMOR,
	[ITEM_TRAIT_TYPE_ARMOR_REINFORCED] = ITEM_TRAIT_TYPE_CATEGORY_ARMOR,
	[ITEM_TRAIT_TYPE_ARMOR_SHATTERING] = ITEM_TRAIT_TYPE_CATEGORY_ARMOR,
	[ITEM_TRAIT_TYPE_ARMOR_SOOTHING] = ITEM_TRAIT_TYPE_CATEGORY_ARMOR,
	[ITEM_TRAIT_TYPE_ARMOR_STURDY] = ITEM_TRAIT_TYPE_CATEGORY_ARMOR,
	[ITEM_TRAIT_TYPE_ARMOR_TRAINING] = ITEM_TRAIT_TYPE_CATEGORY_ARMOR,
	[ITEM_TRAIT_TYPE_ARMOR_VIGOROUS] = ITEM_TRAIT_TYPE_CATEGORY_ARMOR,
	[ITEM_TRAIT_TYPE_ARMOR_WELL_FITTED] = ITEM_TRAIT_TYPE_CATEGORY_ARMOR,

	[ITEM_TRAIT_TYPE_WEAPON_AGGRESSIVE] = ITEM_TRAIT_TYPE_CATEGORY_WEAPON,
	[ITEM_TRAIT_TYPE_WEAPON_AUGMENTED] = ITEM_TRAIT_TYPE_CATEGORY_WEAPON,
	[ITEM_TRAIT_TYPE_WEAPON_BOLSTERED] = ITEM_TRAIT_TYPE_CATEGORY_WEAPON,
	[ITEM_TRAIT_TYPE_WEAPON_CHARGED] = ITEM_TRAIT_TYPE_CATEGORY_WEAPON,
	[ITEM_TRAIT_TYPE_WEAPON_DECISIVE] = ITEM_TRAIT_TYPE_CATEGORY_WEAPON,
	[ITEM_TRAIT_TYPE_WEAPON_DEFENDING] = ITEM_TRAIT_TYPE_CATEGORY_WEAPON,
	[ITEM_TRAIT_TYPE_WEAPON_FOCUSED] = ITEM_TRAIT_TYPE_CATEGORY_WEAPON,
	[ITEM_TRAIT_TYPE_WEAPON_INFUSED] = ITEM_TRAIT_TYPE_CATEGORY_WEAPON,
	[ITEM_TRAIT_TYPE_WEAPON_INTRICATE] = ITEM_TRAIT_TYPE_CATEGORY_WEAPON,
	[ITEM_TRAIT_TYPE_WEAPON_NIRNHONED] = ITEM_TRAIT_TYPE_CATEGORY_WEAPON,
	[ITEM_TRAIT_TYPE_WEAPON_ORNATE] = ITEM_TRAIT_TYPE_CATEGORY_WEAPON,
	[ITEM_TRAIT_TYPE_WEAPON_POWERED] = ITEM_TRAIT_TYPE_CATEGORY_WEAPON,
	[ITEM_TRAIT_TYPE_WEAPON_PRECISE] = ITEM_TRAIT_TYPE_CATEGORY_WEAPON,
	[ITEM_TRAIT_TYPE_WEAPON_PROLIFIC] = ITEM_TRAIT_TYPE_CATEGORY_WEAPON,
	[ITEM_TRAIT_TYPE_WEAPON_QUICKENED] = ITEM_TRAIT_TYPE_CATEGORY_WEAPON,
	[ITEM_TRAIT_TYPE_WEAPON_SHARPENED] = ITEM_TRAIT_TYPE_CATEGORY_WEAPON,
	[ITEM_TRAIT_TYPE_WEAPON_SHATTERING] = ITEM_TRAIT_TYPE_CATEGORY_WEAPON,
	[ITEM_TRAIT_TYPE_WEAPON_SOOTHING] = ITEM_TRAIT_TYPE_CATEGORY_WEAPON,
	[ITEM_TRAIT_TYPE_WEAPON_TRAINING] = ITEM_TRAIT_TYPE_CATEGORY_WEAPON,
	[ITEM_TRAIT_TYPE_WEAPON_VIGOROUS] = ITEM_TRAIT_TYPE_CATEGORY_WEAPON,

	[ITEM_TRAIT_TYPE_JEWELRY_AGGRESSIVE] = ITEM_TRAIT_TYPE_CATEGORY_JEWELRY,
	[ITEM_TRAIT_TYPE_JEWELRY_ARCANE] = ITEM_TRAIT_TYPE_CATEGORY_JEWELRY,
	[ITEM_TRAIT_TYPE_JEWELRY_AUGMENTED] = ITEM_TRAIT_TYPE_CATEGORY_JEWELRY,
	[ITEM_TRAIT_TYPE_JEWELRY_BLOODTHIRSTY] = ITEM_TRAIT_TYPE_CATEGORY_JEWELRY,
	[ITEM_TRAIT_TYPE_JEWELRY_BOLSTERED] = ITEM_TRAIT_TYPE_CATEGORY_JEWELRY,
	[ITEM_TRAIT_TYPE_JEWELRY_FOCUSED] = ITEM_TRAIT_TYPE_CATEGORY_JEWELRY,
	[ITEM_TRAIT_TYPE_JEWELRY_HARMONY] = ITEM_TRAIT_TYPE_CATEGORY_JEWELRY,
	[ITEM_TRAIT_TYPE_JEWELRY_HEALTHY] = ITEM_TRAIT_TYPE_CATEGORY_JEWELRY,
	[ITEM_TRAIT_TYPE_JEWELRY_INFUSED] = ITEM_TRAIT_TYPE_CATEGORY_JEWELRY,
	[ITEM_TRAIT_TYPE_JEWELRY_INTRICATE] = ITEM_TRAIT_TYPE_CATEGORY_JEWELRY,
	[ITEM_TRAIT_TYPE_JEWELRY_ORNATE] = ITEM_TRAIT_TYPE_CATEGORY_JEWELRY,
	[ITEM_TRAIT_TYPE_JEWELRY_PROLIFIC] = ITEM_TRAIT_TYPE_CATEGORY_JEWELRY,
	[ITEM_TRAIT_TYPE_JEWELRY_PROTECTIVE] = ITEM_TRAIT_TYPE_CATEGORY_JEWELRY,
	[ITEM_TRAIT_TYPE_JEWELRY_QUICKENED] = ITEM_TRAIT_TYPE_CATEGORY_JEWELRY,
	[ITEM_TRAIT_TYPE_JEWELRY_ROBUST] = ITEM_TRAIT_TYPE_CATEGORY_JEWELRY,
	[ITEM_TRAIT_TYPE_JEWELRY_SHATTERING] = ITEM_TRAIT_TYPE_CATEGORY_JEWELRY,
	[ITEM_TRAIT_TYPE_JEWELRY_SOOTHING] = ITEM_TRAIT_TYPE_CATEGORY_JEWELRY,
	[ITEM_TRAIT_TYPE_JEWELRY_SWIFT] = ITEM_TRAIT_TYPE_CATEGORY_JEWELRY,
	[ITEM_TRAIT_TYPE_JEWELRY_TRIUNE] = ITEM_TRAIT_TYPE_CATEGORY_JEWELRY,
	[ITEM_TRAIT_TYPE_JEWELRY_VIGOROUS] = ITEM_TRAIT_TYPE_CATEGORY_JEWELRY,
}

local _includedTraitTypes = {
	[ITEM_TRAIT_TYPE_CATEGORY_ARMOR] = {},
	[ITEM_TRAIT_TYPE_CATEGORY_WEAPON] = {},
	[ITEM_TRAIT_TYPE_CATEGORY_JEWELRY] = {},
}

function AutoBind.Traits.Initialize()
	for traitType, category in pairs(_traitTypes) do
		_includedTraitTypes[category][traitType] = {
			DisplayName = GetString("SI_ITEMTRAITTYPE", traitType),
			TraitType = traitType,
		}
	end
end

function AutoBind.Traits.GetIncludedTraitTypesArmor()
	return _includedTraitTypes[ITEM_TRAIT_TYPE_CATEGORY_ARMOR]
end

function AutoBind.Traits.GetIncludedTraitTypesWeapon()
	return _includedTraitTypes[ITEM_TRAIT_TYPE_CATEGORY_WEAPON]
end

function AutoBind.Traits.GetIncludedTraitTypesJewelry()
	return _includedTraitTypes[ITEM_TRAIT_TYPE_CATEGORY_JEWELRY]
end
