local WPamA = WPamA
local GetIcon = WPamA.Textures.GetTexture
-- UpdV_xxx settings - need update window after set value of "xxx":
-- nil - not need, false - need update, true - need update with Redraw
WPamA.ColBCount = 9
WPamA.TabBCount = 11
WPamA.WindSettings = {
  [0] = {
    Mds = {[1]=0,[2]=1,[3]=7,[4]=43},
  },
  [1] = {
    Mds = {[1]=6,[2]=15,[3]=44},
  },
  [2] = {
    Mds = {[1]=2,[2]=8,[3]=9,[4]=11,[5]=14,[6]=17,[7]=26,[8]=33,[9]=41,[10]=45,[11]=47},
  },
  [3] = {
    Mds = {[1]=4,[2]=5,[3]=12,[4]=24,[5]=13,[6]=28,[7]=30},
  },
  [4] = {
    Mds = {[1]=3,[2]=19,[3]=20,[4]=21,[5]=25,[6]=35,[7]=37},
  },
  [5] = {
    Mds = {[1]=16,[2]=18,[3]=22,[4]=23,[5]=50},
  },
  [6] = {
    Mds = {[1]=29,[2]=46,[3]=32,[4]=36,[5]=39,[6]=40},
  },
  [7] = {
    Mds = {[1]=10,[2]=34,[3]=49},
  },
  [8] = {
    Mds = {[1]=27,[2]=31,[3]=38,[4]=42,[5]=48},
  },
}
WPamA.WindCount = #WPamA.WindSettings + 1
--    FavRadMenuIcon = "esoui/art/treeicons/tutorial_idexicon_cwc_up. dds", -- Clockwork
--    FavRadMenuIcon = "esoui/art/treeicons/tutorial_idexicon_murkmire_up. dds", -- Murkmire
--    FavRadMenuIcon = "esoui/art/charactercreate/charactercreate_dragonguardicon_up. dds",
--    FavRadMenuIcon = "esoui/art/treeicons/tutorial_idexicon_dragonguard_up. dds", -- Dragonhold
--    FavRadMenuIcon = "esoui/art/treeicons/store_indexicon_trophy_up. dds", -- trophy sign
--    FavRadMenuIcon = "esoui/art/treeicons/collection_indexicon_service_up. dds",
--    FavRadMenuIcon = "esoui/art/treeicons/collection_indexicon_assistants_up. dds", -- Assistants
--    FavRadMenuIcon = "esoui/art/help/help_tabicon_feedback_up. dds",
--    FavRadMenuIcon = "esoui/art/progression/progression_indexicon_class_up. dds",
--    FavRadMenuIcon = "esoui/art/chatwindow/chat_friendsonline_up. dds",
-- esoui/art/treeicons/reconstruction_tabicon_arenasolo_up. dds -- Arena
-- esoui/art/tutorial/menubar_skills_up. dds
-- esoui/art/treeicons/collection_indexicon_equipment_up. dds -- companion equipment
-- esoui/art/help/help_tabicon_trial_up. dds
-- esoui/art/crafting/blueprints_tabicon_up. dds
-- esoui/art/treeicons/achievements_indexicon_darkanchors_up. dds  -- World Events
-- esoui/art/treeicons/tutorial_idexicon_deadlands_up. dds -- Dead Lands
-- esoui/art/treeicons/collection_indexicon_tribute_up. dds -- Tribute
-- esoui/art/treeicons/tutorial_indexicon_scribing_up. dds -- Scribing
-- esoui/art/lfg/gamepad/lfg_menuicon_promotionalevents.dds
-- esoui/art/treeicons/gamepad/lfg_menuicon_promotionalevents.dds
-- esoui/art/lfg/lfg_indexicon_promotionalevents_up.dds
-- esoui/art/armory/buildicons/buildicon_13.dds -- Dark Bro fugure
WPamA.ModeSettings = {
  [0] = {
    WinX = 820,
    TT = 4,
    UpdV_ShowLoc = false,
    UpdV_ENDung = false,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    UpdV_ShowMonsterSet = false,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = GetIcon(16),
    isVisibleDef = true,
    Col = {[1]=24,[2]=170,[3]=24,[4]=170,[5]=24,[6]=170,[7]=36},
    --Hdr = {[1]=14,[2]=40,[3]=165,[4]=24,[5]=165,},
    BTT = {[7]=29},
    HdT = {[7]=GetIcon(63,28,true)},
    HdA = {[2]=TEXT_ALIGN_LEFT, [4]=TEXT_ALIGN_LEFT, [6]=TEXT_ALIGN_LEFT},
    ClA = {[2]=TEXT_ALIGN_LEFT, [4]=TEXT_ALIGN_LEFT, [6]=TEXT_ALIGN_LEFT},
  },
  [1] = {
    WinX = 820,
    TT = 5,
    UpdV_ShowLoc = false,
    UpdV_ENDung = false,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    --UpdV_CharVisible = nil,
    UpdV_DateTime = false,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    UpdV_ShowMonsterSet = false,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = GetIcon(17),
    isVisibleDef = true,
    Col = {[1]=24,[2]=190,[3]=4,[4]=190,[5]=4,[6]=205},
    --Hdr = {[1]=14,[2]=40,[3]=165,[4]=24,[5]=165,},
    BTT = {},
    HdT = {},
    HdA = {[2]=TEXT_ALIGN_LEFT, [4]=TEXT_ALIGN_LEFT, [6]=TEXT_ALIGN_LEFT},
    ClA = {[2]=TEXT_ALIGN_LEFT, [4]=TEXT_ALIGN_LEFT, [6]=TEXT_ALIGN_LEFT},
  },
  [2] = {
    TT = 6,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = GetIcon(18),
    isVisibleDef = true,
    Col = {[1]=63,[2]=63,[3]=63,[4]=63,[5]=63,[6]=63,[7]=24},
    BTT = {[1]=21,[2]=22,[3]=23,[4]=24,[5]=25,[6]=26,[7]=27},
    HdT = {[7]=GetIcon(19, 24)}, -- Other will be coped near end of file
  },
  [3] = {
    WinX = 680,
    TT = 7,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    --UpdV_DontShowNone = nil,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = "esoui/art/bank/bank_tabIcon_gold_up.dds",
    isVisibleDef = true,
    Col = {[1]=63,[2]=63,[3]=63,[4]=63,},
    BTT = {},
    Map = {[1]=2,[2]=3,[3]=7,[4]=8},
    HdT = {},
  },
  [4] = {
    WinX = 695,
    TT = 17,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    --UpdV_DontShowNone = nil,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    UpdV_AvlSPChg = false,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = "esoui/art/treeicons/tutorial_idexicon_charprogression_up.dds",
    isVisibleDef = true,
    Col = {[1]=67,[2]=67,[3]=67,[4]=67,[5]=67,[6]=67,[7]=80,},
    BTT = {[1]=31,[2]=32,[3]=33,[4]=48,[5]=49,[6]=50,[7]=60,},
    HdT = {
      [1] = GetIcon(24, 28) .. " 1",
      [2] = GetIcon(24, 28) .. " 2",
      [3] = GetIcon(24, 28) .. " 3",
      [4] = "|t28:28:esoui/art/treeicons/tutorial_indexicon_ic_up.dds|t",
      [5] = GetIcon(29, 28) .. " 1",
      [6] = GetIcon(29, 28) .. " 2",
      [7] = "SP",
    },
  },
  [5] = {
    WinX = 890,
    TT = 18,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    --UpdV_DontShowNone = nil,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = "esoui/art/treeicons/tutorial_idexicon_tradeskills_up.dds",
    isVisibleDef = true,
    Col = {[1]=95,[2]=95,[3]=95,[4]=100,[5]=110,[6]=110,[7]=85,},
    BTT = {[1]=41,[2]=42,[3]=43,[4]=44,[5]=45,[6]=46,[7]=47,},
    HdT = {
      [1] = "|t28:28:esoui/art/inventory/inventory_tabicon_craftbag_blacksmithing_up.dds|t",
      [2] = "|t28:28:esoui/art/inventory/inventory_tabicon_craftbag_clothing_up.dds|t",
      [3] = "|t28:28:esoui/art/inventory/inventory_tabicon_craftbag_woodworking_up.dds|t",
      [4] = "|t28:28:esoui/art/inventory/inventory_tabicon_craftbag_alchemy_up.dds|t",
      [5] = "|t28:28:esoui/art/inventory/inventory_tabicon_craftbag_enchanting_up.dds|t",
      [6] = "|t28:28:esoui/art/inventory/inventory_tabicon_craftbag_provisioning_up.dds|t",
      [7] = "|t28:28:esoui/art/inventory/inventory_tabicon_craftbag_jewelrycrafting_up.dds|t",
    },
  },
  [6] = {
    WinX = 800, --
    TT = 19,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    UpdV_TrialAvl = true,
    --UpdV_LFGRndAvl = nil,
    UpdV_FreqRedrawMode = 1,
    FavRadMenuIcon = GetIcon(23),
    isVisibleDef = true,
    Col = {},
    BTT = {},
    HdT = {},
    Map = {},
  },
  [7] = {
    WinX = 820,
    TT = 20,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    --UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    UpdV_LFGRndAvl = true,
    UpdV_FreqRedrawMode = 0,
    FavRadMenuIcon = "esoui/art/treeicons/tutorial_idexicon_groups_up.dds",
    isVisibleDef = true,
    Col = {[1]=150,[2]=150,[3]=180,},
    BTT = {[1]=30,[2]=30,[3]=30,},
    HdT = {},
  },
  [8] = {
    TT = 6,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = GetIcon(25),
    isVisibleDef = true,
    Col = {[1]=63,[2]=63,[3]=63,[4]=63,[5]=63,[6]=63},
    BTT = {[1]=71,[2]=72,[3]=73,[4]=74,[5]=75,[6]=76},
    HdT = {},
  },
  [9] = {
    TT = 6,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = GetIcon(22),
    isVisibleDef = true,
    Col = {[1]=63,[2]=63},
    BTT = {[1]=77,[2]=78},
    HdT = {},
  },
  [10] = {
    WinX = 890,
    TT = 15,
--    UpdV_ShowLoc = false,
--    UpdV_ENDung = false,
--    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = true,
--    UpdV_DateTime = false,
--    UpdV_TrialAvl = nil,
--    UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = "esoui/art/treeicons/achievements_indexicon_events_up.dds",
    isVisibleDef = true,
    Col = {[1]=170,[2]=170,[3]=170,[4]=170},
--    Hdr = {[1]=24,[2]=185,[3]=185,[4]=185,[5]=185,[6]=185,},
    BTT = {},
    HdT = {
      [1] = GetAchievementSubCategoryInfo(14,5), -- Winter
      [2] = GetAchievementSubCategoryInfo(14,3), -- Spring
      [3] = GetAchievementSubCategoryInfo(14,1), -- Summer
      [4] = GetAchievementSubCategoryInfo(14,6), -- Autumn
    },
--    HdA = {[2]=TEXT_ALIGN_LEFT,},
--    ClA = {[2]=TEXT_ALIGN_LEFT,},
  },
  [11] = {
    TT = 6,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = GetIcon(26),
    isVisibleDef = true,
    Col = {[1]=63,[2]=63,[3]=63,[4]=63,[5]=63,[6]=63},
    BTT = {[1]=81,[2]=82,[3]=83,[4]=84,[5]=85,[6]=86},
    HdT = {},
  },
  [12] = {
    TT = 16,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    --UpdV_DontShowNone = nil,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = "esoui/art/treeicons/tutorial_idexicon_guilds_up.dds",
    isVisibleDef = true,
    Col = {[1]=65,[2]=65,[3]=65,[4]=65,[5]=65,[6]=65},
    BTT = {[1]=34,[2]=35,[3]=36,[4]=37,[5]=38,[6]=39},
    HdT = {
      [1] = GetIcon(35, 28),
      [2] = GetIcon(36, 28),
      [3] = "|t28:28:esoui/art/treeicons/tutorial_idexicon_combat_up.dds|t",
      [4] = "|t28:28:esoui/art/treeicons/tutorial_idexicon_thievesguild_up.dds|t",
      [5] = GetIcon(22, 28),
      [6] = "|t28:28:esoui/art/icons/progression_tabicon_magma_up.dds|t",
    },
  },
  [13] = {
    WinX = 800,
    TT = 13,
--    UpdV_ShowLoc = false,
--    UpdV_ENDung = false,
--    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = true,
--    UpdV_DateTime = false,
--    UpdV_TrialAvl = nil,
    UpdV_LFGRndAvl = true,
    UpdV_FreqRedrawMode = 0,
    FavRadMenuIcon = GetIcon(27),
    isVisibleDef = true,
    Col = {[1]=150,[2]=150,[3]=150,[4]=130},
--    Hdr = {[1]=24,[2]=185,[3]=185,[4]=185,[5]=185,[6]=185,},
    BTT = {},
    HdT = {
      [1] = GetString(SI_RIDINGTRAINTYPE1), -- speed
      [2] = GetString(SI_RIDINGTRAINTYPE3), -- stamina
      [3] = GetString(SI_RIDINGTRAINTYPE2), -- capacity
      [4] = GetIcon(6, 28, true), -- time until next training
    },
--    HdA = {[2]=TEXT_ALIGN_LEFT,},
--    ClA = {[2]=TEXT_ALIGN_LEFT,},
  }, -- mode 13
  [14] = {
    TT = 6,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = GetIcon(28),
    isVisibleDef = true,
    Col = {[1]=63,[2]=63,[3]=63,[4]=63,[5]=63,[6]=63},
    BTT = {[1]=91,[2]=92,[3]=93,[4]=94,[5]=95,[6]=96},
    HdT = {},
  },
  [15] = {
    WinX = 800,
    TT = 19,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    UpdV_TrialAvl = true,
    --UpdV_LFGRndAvl = nil,
    UpdV_FreqRedrawMode = 1,
    FavRadMenuIcon = GetIcon(23),
    isVisibleDef = true,
    Col = {},
    BTT = {},
    HdT = {},
    Map = {},
  },
  [16] = {
    WinX = 890,
    TT = 14,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = true,
    UpdV_LFGRndAvl = true,
    UpdV_FreqRedrawMode = 1,
    FavRadMenuIcon = GetIcon(29),
    isVisibleDef = true,
    Col = {[1]=70,[2]=50,[3]=50,[4]=180,[5]=70,[6]=130,[7]=130},
    BTT = {[1]=103,[2]=48,[3]=49,[4]=100,[5]=101,[6]=102,[7]=104},
    HdT = {
      [1] = GetString(SI_GUILD_TOOLTIP_RANK), -- rank
      [2] = "|t28:28:esoui/art/treeicons/tutorial_indexicon_ic_up.dds|t", -- IC emperor
      [3] = GetIcon(29, 28), -- AvA skill
      [4] = GetString(SI_BATTLEGROUNDQUERYCONTEXTTYPE2), -- home campaign
      [5] = GetString(SI_LEVEL_UP_REWARDS_GAMEPAD_REWARD_SECTION_HEADER_SINGULAR), -- reward tier
      [6] = GetString(SI_STAT_GAMEPAD_TIME_REMAINING):gsub(":", ""), -- campaign time remaining
      [7] = GetString(SI_NOTIFICATIONTYPE10), -- leaderboard
    },
    Map = {},
  },
  [17] = {
    TT = 6,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = GetIcon(30),
    isVisibleDef = true,
    Col = {[1]=63, [2]=63, [3]=63, [4]=63, [5]=63, [6]=63},
    BTT = {[1]=121,[2]=122,[3]=123,[4]=124,[5]=125,[6]=126},
    HdT = {},
  },
  [18] = {
    WinX = 890,
    TT = 14,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = true,
    UpdV_LFGRndAvl = true,
    UpdV_FreqRedrawMode = 1,
    FavRadMenuIcon = "esoui/art/treeicons/tutorial_idexicon_battlegrounds_up.dds",
    isVisibleDef = true,
    Col = {[1]=70,[2]=50,[3]=140,[4]=130},
    BTT = {[1]=103,[2]=49,[3]=104,[4]=102},
    HdT = {
      [1] = GetString(SI_GUILD_TOOLTIP_RANK), -- rank
      [2] = GetIcon(29, 28), -- AvA skill
      [3] = GetString(SI_NOTIFICATIONTYPE10), -- Leaderboard
      [4] = GetString(SI_STAT_GAMEPAD_TIME_REMAINING):gsub(":", "") -- campaign time remaining
    },
    --[[ SI_TRIBUTE_FINDER_REWARDS_LEADERBOARD_RANK_HEADER "Leaderboard Rank"
         SI_BATTLEGROUNDLEADERBOARDTYPE1 "Deathmatch"
         SI_BATTLEGROUNDLEADERBOARDTYPE2 "Land Grab"
         SI_BATTLEGROUNDLEADERBOARDTYPE3 "Flag Games"
         SI_BATTLEGROUNDLEADERBOARDTYPE4 "Competitive" --]]
    Map = {},
  },
  [19] = {
    WinX = 720,
    TT = 7,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    --UpdV_DontShowNone = nil,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = GetIcon(31),
    isVisibleDef = true,
    Col = {[1]=63,[2]=63,[3]=63,[4]=63,[5]=63,[6]=63,[7]=63,[8]=63},
    BTT = {},
    Map = {[1]= 5,[2]= 6,[3]=10,[4]= 4,[5]=12,[6]=11,[7]=44,[8]=43},
    HdT = {},
  },
  [20] = {
    WinX = 680,
    TT = 7,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    --UpdV_DontShowNone = nil,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = GetIcon(32),
    isVisibleDef = true,
    Col = {[1]=63,[2]=63,[3]=73,[4]=73,[5]=63,[6]=63,[7]=63},
    BTT = {},
    Map = {[1]=1, [2]=15,[3]=16,[4]=17,[5]=29,[6]=30,[7]=31},
    HdT = {},
  },
  [21] = {
    WinX = 785,
    TT = 7,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    --UpdV_DontShowNone = nil,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = GetIcon(60),
    isVisibleDef = true,
    Col = {[1]=61,[2]=61,[3]=61,[4]=61,[5]=61,[6]=61,[7]=61,[8]=79},
    BTT = {[8]=11},
    Map = {[1]=18,[2]=24,[3]=20,[4]=22,[5]=14,[6]=23,[7]=21,[8]=0},
    HdT = {[8]="|t20:20:esoui/art/currency/icon_seedcrystal.dds|t"},
  },
  [22] = {
    WinX = 820,
    TT = 105,
    UpdV_ShowLoc = false,
    UpdV_ENDung = false,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    --UpdV_CharVisible = nil,
    --UpdV_DateTime = false,
    --UpdV_TrialAvl = nil,
    UpdV_LFGRndAvl = true,
    UpdV_ShowMonsterSet = false,
    UpdV_FreqRedrawMode = 0,
    FavRadMenuIcon = "esoui/art/treeicons/tutorial_idexicon_magicweaponsarmor_up.dds",
    isVisibleDef = true,
    Col = {[1]=240},
    --Hdr = {[1]=14,[2]=40,[3]=165,[4]=24,[5]=165,},
    BTT = {},
    HdT = {[1]=GetString(SI_GAMEPAD_DAILY_LOGIN_REWARDS_NEXT_REWARD_CLAIM_TITLE)},
  },
  [23] = {
    WinX = 820,
    TT = 14,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    --UpdV_DontShowNone = nil,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = "esoui/art/campaign/overview_indexicon_bonus_up.dds",
    isVisibleDef = true,
    Col = {[1]=70,[2]=70,[3]=70,[4]=70,[5]=70,[6]=70},
    BTT = {},
    Map = {[1]=13,[2]=25,[3]=27,[4]=26,[5]=28,[6]=45},
    HdT = {},
  },
  [24] = {
    WinX = 680,
    TT = 12,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    --UpdV_DontShowNone = nil,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = "esoui/art/progression/progression_indexicon_world_up.dds",
    isVisibleDef = true,
    Col = {[1]=65 ,[2]=65 ,[3]=65 ,[4]=65 ,[5]=75 ,[6]=75 ,},
    BTT = {[1]=131,[2]=132,[3]=133,[4]=134,[5]=135,[6]=136,},
    HdT = {
      [1] = "Vamp",
      [2] = "WW",
      [3] = "Leger",
      [4] = "Soul",
      [5] = "Scry",
      [6] = "Excav",
    },
  },
  [25] = {
    WinX = 680,
    TT = 87,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    --UpdV_DontShowNone = nil,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = GetIcon(31),
    isVisibleDef = true,
    Col = {[1]=80,[2]=80,[3]=80,[4]=70,[5]=70,[6]=70},
    BTT = {[1]=88,[2]=89,[3]=90,[4]=97,[5]=98,[6]=99},
    Map = {},
    HdT = {
      [1] = "Total",
      [2] = "Filled",
      [3] = "Free",
      [4] = GetIcon(31, 28) .. GetIcon(33, 28),
      [5] = GetIcon(27, 28) .. GetIcon(33, 28),
      [6] = "|t32:32:esoui/art/tutorial/store_indexicon_vanitypets_up.dds|t" ..
            GetIcon(33, 28),
    },
  },
  [26] = {
    TT = 6,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = GetIcon(34),
    isVisibleDef = true,
    Col = {[1]=63, [2]=63, [3]=63, [4]=63, [5]=63, [6]=63},
    BTT = {[1]=201,[2]=202,[3]=203,[4]=204,[5]=205,[6]=206},
    HdT = {},
  },
  [27] = {
    WinX = 950,
    TT = 106,
    UpdV_ShowLoc = false,
    UpdV_ENDung = false,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    --UpdV_CharVisible = nil,
    --UpdV_DateTime = false,
    --UpdV_TrialAvl = nil,
    UpdV_LFGRndAvl = true,
    UpdV_ShowMonsterSet = false,
    UpdV_FreqRedrawMode = 0,
    FavRadMenuIcon = GetIcon(68),
    isVisibleDef = true,
    Col = {[1]=130,[2]=130,[3]=180},
    BTT = {},
    HdT = {
      [1] = GetString(SI_QUEST_TYPE_COMPLETE),
      [2] = WPamA.i18n.EndeavorRepeat, -- Repeat
      [3] = GetString(SI_LEVEL_UP_REWARDS_GAMEPAD_REWARD_SECTION_HEADER_SINGULAR) -- Reward
    },
  },
  [28] = {
    TT = 107,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    --UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    UpdV_LFGRndAvl = true,
    UpdV_FreqRedrawMode = 0,
    FavRadMenuIcon = GetIcon(22),
    isVisibleDef = true,
    Col = {[1]=150},
    BTT = {[1]=108},
    HdT = {[1]=GetIcon(6, 28, true)},
  },
  [29] = {
    WinX = 965,
    TT = 109,
    UpdV_ShowLoc = false,
    UpdV_ENDung = false,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    --UpdV_CharVisible = nil,
    --UpdV_DateTime = false,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    UpdV_ShowMonsterSet = false,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = GetIcon(45),
    isVisibleDef = true,
    Col = {[1]=120,[2]=120,[3]=120,[4]=120,[5]=120,[6]=120},
    BTT = {},
    HdT = { [1]="???", [2]="???", [3]="???", [4]="???", [5]="???", [6]="???" },
  },
  [30] = {
    WinX = 840,
    TT = 110,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    --UpdV_DontShowNone = nil,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = "esoui/art/mainmenu/menubar_champion_up.dds",
    isVisibleDef = true,
    Col = {[1]=200,[2]=200,[3]=200},
    BTT = {},
    HdT = { [1] = "???", [2] = "???", [3] = "???" },
  },
  [31] = {
    WinX = 800,
    TT = 111,
--    UpdV_ShowLoc = false,
--    UpdV_ENDung = false,
--    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = true,
--    UpdV_DateTime = false,
--    UpdV_TrialAvl = nil,
    UpdV_LFGRndAvl = true,
    UpdV_FreqRedrawMode = 0,
    FavRadMenuIcon = "esoui/art/treeicons/tools_up.dds",
    isVisibleDef = true,
    Col = {[1]=80,[2]=80,[3]=80,[4]=80,[5]=80,[6]=80,[7]=80},
--    Hdr = {[1]=24,[2]=185,[3]=185,[4]=185,[5]=185,[6]=185,},
    BTT = {[1]=207,[2]=208,[3]=209,[4]=210,[5]=211,[6]=212,[7]=213},
    HdT = {
      [1] = "|t28:28:esoui/art/inventory/inventory_tabicon_craftbag_blacksmithing_up.dds|t",
      [2] = "|t28:28:esoui/art/inventory/inventory_tabicon_craftbag_clothing_up.dds|t",
      [3] = "|t28:28:esoui/art/inventory/inventory_tabicon_craftbag_woodworking_up.dds|t",
      [4] = "|t28:28:esoui/art/inventory/inventory_tabicon_craftbag_alchemy_up.dds|t",
      [5] = "|t28:28:esoui/art/inventory/inventory_tabicon_craftbag_enchanting_up.dds|t",
      [6] = "|t28:28:esoui/art/inventory/inventory_tabicon_craftbag_provisioning_up.dds|t",
      [7] = "|t28:28:esoui/art/inventory/inventory_tabicon_craftbag_jewelrycrafting_up.dds|t",
    },
--    HdA = {[2]=TEXT_ALIGN_LEFT,},
--    ClA = {[2]=TEXT_ALIGN_LEFT,},
  }, -- mode 31
  [32] = {
    WinX = 820,
    TT = -1,
    UpdV_ShowLoc = false,
    UpdV_ENDung = false,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    --UpdV_CharVisible = nil,
    --UpdV_DateTime = false,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    UpdV_ShowMonsterSet = false,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = "esoui/art/companion/keyboard/companion_skills_up.dds",
    isVisibleDef = true,
    Col = {[1]=85,[2]=85,[3]=85,[4]=85,[5]=85,[6]=85,[7]=85},
    --Hdr = {[1]=14,[2]=40,},
    BTT = {[1]=214,[2]=215,[3]=216,[4]=217,[5]=218,[6]=219,[7]=220},
    HdT = {
      [1] = GetIcon(24, 28),
      [2] = GetIcon(35, 28),
      [3] = GetIcon(36, 28),
      [4] = "|t28:28:esoui/art/treeicons/tutorial_idexicon_combat_up.dds|t",
      [5] = GetIcon(37, 28),
      [6] = GetIcon(38, 28),
      [7] = GetIcon(39, 28),
    },
  }, -- mode 32
  [33] = {
    TT = 6,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = GetIcon(40),
    isVisibleDef = true,
    Col = {[1]=63, [2]=63, [3]=63, [4]=63, [5]=63, [6]=63},
    BTT = {[1]=241,[2]=242,[3]=243,[4]=244,[5]=245,[6]=246},
    HdT = {},
  },
  [34] = {
    WinX = 890,
    TT = -1,
--    UpdV_ShowLoc = false,
--    UpdV_ENDung = false,
--    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = true,
--    UpdV_DateTime = false,
--    UpdV_TrialAvl = nil,
--    UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = "esoui/art/journal/journal_tabicon_lorelibrary_up.dds",
    isVisibleDef = true,
    Col = {[1]=226,[2]=226,[3]=226},
    BTT = {[1]=247,[2]=248,[3]=249},
    HdT = {[1]="",[2]="",[3]="",}, -- Init by WPamA:InitLoreBookMode()
  },
  [35] = {
    WinX = 680,
    TT = 7,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    --UpdV_DontShowNone = nil,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = "esoui/art/journal/journal_tabicon_cadwell_up.dds",
    isVisibleDef = true,
    Col = {[1]=63,[2]=63},
    BTT = {},
    Map = {[1]=32,[2]=33},
    HdT = {},
  },
  [36] = {
    WinX = 820,
    TT = -1,
    UpdV_ShowLoc = false,
    UpdV_ENDung = false,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    --UpdV_CharVisible = nil,
    --UpdV_DateTime = false,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    UpdV_ShowMonsterSet = false,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = "esoui/art/tutorial/inventory_tabicon_weapons_up.dds",
    isVisibleDef = true,
    Col = {[1]=95,[2]=95,[3]=95,[4]=95,[5]=95,[6]=95},
    BTT = {[1]=221,[2]=222,[3]=223,[4]=224,[5]=225,[6]=226},
    HdT = {
      [1] = GetIcon(48, 28), -- 2handed
      [2] = GetIcon(49, 28), -- 1handed
      [3] = GetIcon(50, 28), -- dualwield
      [4] = GetIcon(51, 28), -- bow
      [5] = GetIcon(52, 28), -- firestaff
      [6] = GetIcon(53, 28), -- healstaff
    },
  }, -- mode 36
  [37] = {
    WinX = 760,
    TT = 7,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    --UpdV_DontShowNone = nil,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = GetIcon(65),
    isVisibleDef = true,
    Col = {[1]=60,[2]=60,[3]=60,[4]=60}, --[5]=60,[6]=60,[7]=60,[8]=60,[9]=60},
    BTT = {},
    Map = {[1]=42,[2]=43,[3]=19,[4]=41}, --[5]=38,[6]=39,[7]=40,[8]=41,[9]=9},
    HdT = {},
  },
  [38] = {
    WinX = 820,
    TT = -1,
    UpdV_ShowLoc = false,
    UpdV_ENDung = false,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    --UpdV_CharVisible = nil,
    --UpdV_DateTime = false,
    --UpdV_TrialAvl = nil,
    UpdV_LFGRndAvl = true,
    UpdV_ShowMonsterSet = false,
    UpdV_FreqRedrawMode = 0,
    FavRadMenuIcon = GetIcon(12),
    isVisibleDef = true,
    Col = {[1]=140,[2]=140,[3]=140},
    BTT = {[1]=112,[2]=113,[3]=114},
    HdT = { [1] = "???", [2] = "???", [3] = "???" },
  }, -- mode 38
  [39] = {
    WinX = 820,
    TT = -1,
    UpdV_ShowLoc = false,
    UpdV_ENDung = false,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    --UpdV_CharVisible = nil,
    --UpdV_DateTime = false,
    FavRadMenuIcon = GetIcon(37),
    isVisibleDef = true,
    Col = {[1]=85,[2]=85,[3]=85,[4]=85,[5]=85,[6]=85,[7]=85},
    BTT = {[1]=227,[2]=228,[3]=229,[4]=230,[5]=231,[6]=232,[7]=233},
    HdT = {
      [1] = "|t28:28:esoui/art/characterwindow/gearslot_head.dds|t",
      [2] = "|t28:28:esoui/art/characterwindow/gearslot_shoulders.dds|t",
      [3] = "|t28:28:esoui/art/characterwindow/gearslot_chest.dds|t",
      [4] = "|t28:28:esoui/art/characterwindow/gearslot_hands.dds|t",
      [5] = "|t28:28:esoui/art/characterwindow/gearslot_belt.dds|t",
      [6] = "|t28:28:esoui/art/characterwindow/gearslot_legs.dds|t",
      [7] = "|t28:28:esoui/art/characterwindow/gearslot_feet.dds|t",
    },
  }, -- mode 39
  [40] = {
    WinX = 820,
    TT = -1,
    UpdV_ShowLoc = false,
    UpdV_ENDung = false,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    --UpdV_CharVisible = nil,
    --UpdV_DateTime = false,
    FavRadMenuIcon = GetIcon(48),
    isVisibleDef = true,
    Col = {[1]=119,[2]=119,[3]=119,[4]=119,[5]=119},
    BTT = {[1]=234,[2]=235,[3]=236,[4]=237,[5]=238},
    HdT = {
      [1] = "|t28:28:esoui/art/characterwindow/gearslot_mainhand.dds|t",
      [2] = "|t28:28:esoui/art/characterwindow/gearslot_offhand.dds|t",
      [3] = "|t28:28:esoui/art/characterwindow/gearslot_neck.dds|t",
      [4] = "|t28:28:esoui/art/characterwindow/gearslot_ring.dds|t 1",
      [5] = "|t28:28:esoui/art/characterwindow/gearslot_ring.dds|t 2",
    },
  }, -- mode 40
  [41] = {
    TT = 6,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = GetIcon(42),
    isVisibleDef = true,
    Col = {[1]=63, [2]=63, [3]=63, [4]=63, [5]=63, [6]=63},
    BTT = {[1]=251,[2]=252,[3]=253,[4]=254,[5]=255,[6]=256},
    HdT = {},
  }, -- mode 41
  [42] = {
    WinX = 800,
    TT = -1,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    --UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    UpdV_TrialAvl = true,
    --UpdV_LFGRndAvl = nil,
    UpdV_AvlSPChg = false,
    UpdV_FreqRedrawMode = 1,
    FavRadMenuIcon = GetIcon(56),
    isVisibleDef = true,
    Col = {[1]=80,[2]=80,[3]=80,[4]=150,[5]=150},
    BTT = {[3]=60},
    HdT = { [1] = "???", [2] = "???", [3] = "???", [4] = "???", [5] = "???" },
  }, -- mode 42
  [43] = {
    WinX = 880,
    TT = -1,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    --UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = true,
    --UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = 1,
    FavRadMenuIcon = "esoui/art/journal/leaderboard_indexicon_endlessdungeon_up.dds",
    isVisibleDef = true,
    Col = {[1]=80,[2]=130,[3]=170,[4]=130,[5]=170},
    BTT = {[1]=158,[2]=159,[3]=104,[4]=159,[5]=104},
    HdT = {
      [1] = GetString(SI_SCREEN_NARRATION_CRAFTING_QUEST_PIN_ICON_NARRATION), -- quest
      [2] = GetString(SI_ENDLESS_DUNGEON_SUMMARY_PROGRESS_HEADER) ..
            "|t24:24:esoui/art/mainmenu/menubar_character_up.dds|t", -- best progress solo
      [3] = GetString(SI_NOTIFICATIONTYPE10) ..
            "|t24:24:esoui/art/mainmenu/menubar_character_up.dds|t", -- leaderboard solo
      [4] = GetString(SI_ENDLESS_DUNGEON_SUMMARY_PROGRESS_HEADER) ..
            "|t24:24:esoui/art/mainmenu/menubar_social_up.dds|t", -- best progress duo
      [5] = GetString(SI_NOTIFICATIONTYPE10) ..
            "|t24:24:esoui/art/mainmenu/menubar_social_up.dds|t", -- leaderboard duo
    },
  }, -- mode 43
  [44] = {
    WinX = 800,
    TT = 19,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    UpdV_TrialAvl = true,
    --UpdV_LFGRndAvl = nil,
    UpdV_FreqRedrawMode = 1,
    FavRadMenuIcon = GetIcon(23),
    isVisibleDef = true,
    Col = {},
    BTT = {},
    HdT = {},
    Map = {},
  }, -- mode 44
  [45] = {
    TT = 6,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = GetIcon(43),
    isVisibleDef = true,
    Col = {[1]=63, [2]=63, [3]=63, [4]=63, [5]=63, [6]=63},
    BTT = {[1]=261,[2]=262,[3]=263,[4]=264,[5]=265,[6]=266},
    HdT = {},
  }, -- mode 45
  [46] = {
    WinX = 965,
    TT = 109,
    UpdV_ShowLoc = false,
    UpdV_ENDung = false,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    --UpdV_CharVisible = nil,
    --UpdV_DateTime = false,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    UpdV_ShowMonsterSet = false,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = GetIcon(45),
    isVisibleDef = true,
    Col = {[1]=120,[2]=120}, -- ,[3]=120,[4]=120,[5]=120,[6]=120},
    BTT = {},
    HdT = { [1]="???", [2]="???" }, -- , [3]="???", [4]="???", [5]="???", [6]="???" },
  }, -- mode 46
  [47] = {
    TT = 6,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = GetIcon(66),
    isVisibleDef = true,
    Col = {[1]=63, [2]=63, [3]=63, [4]=63, [5]=63, [6]=63},
    BTT = {[1]=267,[2]=268,[3]=269,[4]=270,[5]=271,[6]=272},
    HdT = {},
  }, -- mode 47
  [48] = {
    WinX = 820,
    TT = -1,
    UpdV_ShowLoc = false,
    UpdV_ENDung = false,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    --UpdV_CharVisible = nil,
    --UpdV_DateTime = false,
    FavRadMenuIcon = GetIcon(69),
    isVisibleDef = true,
    Col = {[1]=70,[2]=50,[3]=70,[4]=70,[5]=70,[6]=50,[7]=70},
    BTT = {[1]=234,[3]=235,[5]=239,[7]=240},
    HdT = {
      [1] = GetIcon(48, 32, true),
      [2] = "|t20:20:esoui/art/charactercreate/rotate_left_up.dds:inheritcolor|t 1 |t20:20:esoui/art/charactercreate/rotate_right_up.dds:inheritcolor|t",
      [3] = "|t32:32:esoui/art/inventory/inventory_tabicon_shield_up.dds:inheritcolor|t",
      [4] = " ",
      [5] = GetIcon(48, 32, true),
      [6] = "|t20:20:esoui/art/charactercreate/rotate_left_up.dds:inheritcolor|t 2 |t20:20:esoui/art/charactercreate/rotate_right_up.dds:inheritcolor|t",
      [7] = "|t32:32:esoui/art/inventory/inventory_tabicon_shield_up.dds:inheritcolor|t",
    },
  }, -- mode 48
  [49] = {
    WinX = 890,
    TT = -1,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    --UpdV_DontShowNone = nil,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = nil,
    --UpdV_LFGRndAvl = nil,
    --UpdV_FreqRedrawMode = nil,
    FavRadMenuIcon = "esoui/art/crafting/blueprints_tabicon_up.dds",
    isVisibleDef = true,
    Col = {[1]=95,[2]=95,[3]=95,[4]=100,[5]=110,[6]=110,[7]=85},
    BTT = {[1]=-1,[2]=-1,[3]=-1,[4]=-1,[5]=-1,[6]=-1,[7]=-1},
    BTTA = {
      [CRAFTING_TYPE_BLACKSMITHING]   = GetString(SI_TRADESKILLTYPE1),
      [CRAFTING_TYPE_CLOTHIER]        = GetString(SI_TRADESKILLTYPE2),
      [CRAFTING_TYPE_ENCHANTING]      = GetString(SI_TRADESKILLTYPE3),
      [CRAFTING_TYPE_ALCHEMY]         = GetString(SI_TRADESKILLTYPE4),
      [CRAFTING_TYPE_PROVISIONING]    = GetString(SI_TRADESKILLTYPE5),
      [CRAFTING_TYPE_WOODWORKING]     = GetString(SI_TRADESKILLTYPE6),
      [CRAFTING_TYPE_JEWELRYCRAFTING] = GetString(SI_TRADESKILLTYPE7),
   -- [CRAFTING_TYPE_SCRIBING]        = GetString(SI_TRADESKILLTYPE8) -- not yet
    },
    HdT = {
      [1] = "|t28:28:esoui/art/inventory/inventory_tabicon_craftbag_blacksmithing_up.dds|t",
      [2] = "|t28:28:esoui/art/inventory/inventory_tabicon_craftbag_clothing_up.dds|t",
      [3] = "|t28:28:esoui/art/inventory/inventory_tabicon_craftbag_enchanting_up.dds|t",
      [4] = "|t28:28:esoui/art/inventory/inventory_tabicon_craftbag_alchemy_up.dds|t",
      [5] = "|t28:28:esoui/art/inventory/inventory_tabicon_craftbag_provisioning_up.dds|t",
      [6] = "|t28:28:esoui/art/inventory/inventory_tabicon_craftbag_woodworking_up.dds|t",
      [7] = "|t28:28:esoui/art/inventory/inventory_tabicon_craftbag_jewelrycrafting_up.dds|t",
    },
  }, -- mode 49
-----
  [50] = {
    WinX = 890,
    TT = 28,
    --UpdV_ShowLoc = nil,
    --UpdV_ENDung = nil,
    UpdV_DontShowNone = false,
    UpdV_TitleToolTip = true,
    UpdV_CharVisible = false,
    --UpdV_DateTime = nil,
    --UpdV_TrialAvl = true,
    UpdV_LFGRndAvl = true,
    UpdV_FreqRedrawMode = 1,
    FavRadMenuIcon = "esoui/art/treeicons/provisioner_indexicon_baked_up.dds",
    isVisibleDef = true,
    Col = {[1]=100,[2]=130,[3]=63,[4]=63,[5]=63},
    BTT = {[1]=-1},
    BTTA = {[1]=GetString(SI_CHAMPION_TOOLTIP_CURRENT_BONUS)},
    HdT = {},
    Map = {[3]=38,[4]=39,[5]=40},
  }, -- mode 50
-----
} -- ModeSettings end
--================================================================
WPamA.ModeCount = #WPamA.ModeSettings + 1
WPamA.ModeOrder = {}
do
  local nOrd = 0
  local modeSet = WPamA.ModeSettings
  for i = 0, WPamA.WindCount - 1 do
    local v = WPamA.WindSettings[i]
    if v then
      for j = 1, WPamA.TabBCount do
        local q = v.Mds[j]
        if q and modeSet[q] ~= nil then
          modeSet[q].WinInd = i
          modeSet[q].TabInd = j
          modeSet[q].MOrder = nOrd
          WPamA.ModeOrder[nOrd] = q
          nOrd = nOrd + 1
        end
      end
    end
  end
  ---
  local maxX = WPamA.Consts.WinSizeMinX
  for i = 0, #modeSet do
    local ms = modeSet[i]
    if ms and ms.WinX and (maxX < ms.WinX) then maxX = ms.WinX end
  end
  WPamA.Consts.WinSizeMaxX = maxX
  ---
end
--================================================================
WPamA.Inventory.CreateModesHeaders()
WPamA.Equipment.CreateIterators()
WPamA.GroupDungeons.CreateIterators()
WPamA.DailyWrits.CreateIterators()
WPamA.CraftCerts.CreateIterators()
WPamA.Companions.CreateIterators()
WPamA.EndlessDungeons.CreateIterators()
---
WPamA.WorldBosses.CreateModesHeaders()
if WPamA.i18n.Lng == "JP" then -- Copy Bosses.H to the mode headers array
  local bosses = WPamA.WorldBosses.Bosses
  local modeSet = WPamA.ModeSettings
  for j = 1, 6 do
    modeSet[2].HdT[j] = bosses[j].H
  end
end
WPamA.WorldBosses.CreateIterators()
---
WPamA.TrialDungeons.CreateIterators()
WPamA.SkillLines.CreateModesHeaders()
WPamA.TimedEffects.CreateIterators()
--================================================================
