Set7={
	name = "Vault of Umbrage",
	nR = 5,
	rounds = {			
		--first round
		[1] = {
			nWave =4,
			Waves = {
				[1] = {
					nMOB = 3,
					Mobs = {
						[1] = {posx =131695,posy =49904,posz =173665,X=0.58111381530762,Y=0.50605326890945, texture = "MAHelper/Icons/Signal.dds",  c = 1,}, 
						[2] = {posx =129476,posy =49985,posz =177396,X=0.52784502506256,Y=0.59564167261124, texture = "MAHelper/Icons/Signal.dds",  c = 1,},
						[3] = {posx =127950,posy =49952,posz =174088,X=0.49152541160583,Y=0.51573848724365, texture = "MAHelper/Icons/Signal.dds",  c = 1,},
					},
				},
				[2] = {
					nMOB = 3,
					Mobs = {
						[1] = {posx =131846,posy =49934,posz =176444,X=0.58595639467239,Y=0.57384985685349, texture = "MAHelper/Icons/Signal2.dds",   c = 1,},
						[2] = {posx =130160,posy =49930,posz =172870,X=0.54479420185089,Y=0.48668280243874, texture = "MAHelper/Icons/Signal2.dds",   c = 1,},
						[3] = {posx =127799,posy =49962,posz =176277,X=0.48668280243874,Y=0.56900727748871, texture = "MAHelper/Icons/Signal2.dds",   c = 1,},
					},
				},
				[3] = {
					nMOB = 3,
					Mobs = {
						[1] = {posx =131141,posy =49885,posz =173285,X=0.56900727748871,Y=0.49636805057526, texture = "MAHelper/Icons/Signal3.dds",   c = 1,}, 
						[2] = {posx =130156,posy =49957,posz =177460,X=0.54479420185089,Y=0.5980629324913, texture = "MAHelper/Icons/Signal3.dds",  c = 1,},
						[3] = {posx =128901,posy =49921,posz =173636,X=0.51573848724365,Y=0.50605326890945, texture = "MAHelper/Icons/Signal3.dds",  c = 1,},
					},
				},
				[4] = {
					nMOB = 1,
					Mobs = {
						[1] = {posx =129066,posy =49938,posz =176971,X=0.51815980672836,Y=0.58595639467239, texture = "MAHelper/Icons/Signal4.dds",  c = 2,},
					},
				},
			},
		},
		--second round
		[2] = {
			nWave =4,
			Waves = {
				[1] = {
					nMOB = 2,
					Mobs = {
						[1] = {posx =132059,posy =49946,posz =174112,X=0.59079903364182,Y=0.51815980672836, texture = "MAHelper/Icons/Signal.dds",  c = 1,}, 
						[2] = {posx =130111,posy =49923,posz =172940,X=0.54479420185089,Y=0.48910412192345, texture = "MAHelper/Icons/Signal.dds",  c = 1,},
					},
				},
				[2] = {
					nMOB = 3,
					Mobs = {
						[1] = {posx =127394,posy =49959,posz =176124,X=0.47699758410454,Y=0.566585958004, texture = "MAHelper/Icons/Signal2.dds",   c = 1,},
						[2] = {posx =127186,posy =49922,posz =173999,X=0.47215497493744,Y=0.51331716775894, texture = "MAHelper/Icons/Signal2.dds",   c = 1,},
						[3] = {posx =130969,posy =49902,posz =177199,X=0.56416463851929,Y=0.59079903364182, texture = "MAHelper/Icons/Signal2.dds",   c = 1,},
					},
				},
				[3] = {
					nMOB = 2,
					Mobs = {
						[1] = {posx =127600,posy =49953,posz =176796,X=0.48426151275635,Y=0.58111381530762, texture = "MAHelper/Icons/Signal3.dds",  c = 1,}, 
						[2] = {posx =131483,posy =49894,posz =176826,X=0.5762711763382,Y=0.58353513479233, texture = "MAHelper/Icons/Signal3.dds",  c = 1,},
					},
				},
				[4] = {
					nMOB = 3,
					Mobs = {
						[1] = {posx =129089,posy =49936,posz =173374,X=0.51815980672836,Y=0.49878934025764, texture = "MAHelper/Icons/Signal4.dds",   c = 1,},
						[2] = {posx =131794,posy =49888,posz =173499,X=0.58353513479233,Y=0.50121062994003, texture = "MAHelper/Icons/Signal4.dds",   c = 1,},
						[3] = {posx =129378,posy =49971,posz =177309,X=0.52542370557785,Y=0.59564167261124, texture = "MAHelper/Icons/Signal4.dds",   c = 2,},
					},
				},
			},
		},
		--third round
		[3] = {
			nWave =4,
			Waves = {
				[1] = {
					nMOB = 4,
					Mobs = {
						[1] = {posx =131589,posy =49911,posz =173702,X=0.57869249582291,Y=0.50847458839417, texture = "MAHelper/Icons/Signal.dds",  c = 1,}, 
						[2] = {posx =131526,posy =49931,posz =176360,X=0.57869249582291,Y=0.57142859697342, texture = "MAHelper/Icons/Signal.dds",  c = 1,},
						[3] = {posx =128040,posy =49947,posz =176495,X=0.49394673109055,Y=0.57384985685349, texture = "MAHelper/Icons/Signal.dds",  c = 1,},
						[4] = {posx =128351,posy =49943,posz =173759,X=0.50121062994003,Y=0.50847458839417, texture = "MAHelper/Icons/Signal.dds",  c = 1,},
					},
				},
				[2] = {
					nMOB = 3,
					Mobs = {
						[1] = {posx =131553,posy =49881,posz =173191,X=0.57869249582291,Y=0.49394673109055, texture = "MAHelper/Icons/Signal2.dds",   c = 1,},
						[2] = {posx =127690,posy =49969,posz =175979,X=0.48426151275635,Y=0.56174331903458, texture = "MAHelper/Icons/Signal2.dds",   c = 1,},
						[3] = {posx =131974,posy =49970,posz =176069,X=0.5883777141571,Y=0.56416463851929, texture = "MAHelper/Icons/Signal2.dds",   c = 1,},
					},
				},
				[3] = {
					nMOB = 2,
					Mobs = {
						[1] = {posx =129491,posy =49994,posz =177461,X=0.52784502506256,Y=0.5980629324913, texture = "MAHelper/Icons/Signal3.dds",  c = 1,}, 
						[2] = {posx =130018,posy =49916,posz =173067,X=0.54237288236618,Y=0.49152541160583, texture = "MAHelper/Icons/Signal3.dds",  c = 1,},
					},
				},
				[4] = {
					nMOB = 1,
					Mobs = {
						[1] = {posx =128170,posy =49983,posz =174630,X=0.49636805057526,Y=0.53026634454727, texture = "MAHelper/Icons/Signal4.dds",   c = 1,},
					},
				},
			},
		},
		[4] = {
			nWave =4,
			Waves = {
				[1] = {
					nMOB = 3,
					Mobs = {
						[1] = {posx =130056,posy =49913,posz =173215,X=0.54237288236618,Y=0.49636805057526, texture = "MAHelper/Icons/Signal.dds",  c = 1,}, 
						[2] = {posx =131948,posy =49980,posz =174503,X=0.5883777141571,Y=0.52784502506256, texture = "MAHelper/Icons/Signal.dds",  c = 1,},
						[3] = {posx =128123,posy =49962,posz =174435,X=0.49636805057526,Y=0.52542370557785, texture = "MAHelper/Icons/Signal.dds",  c = 1,},
					},
				},
				[2] = {
					nMOB = 3,
					Mobs = {
						[1] = {posx =127935,posy =49962,posz =176153,X=0.49152541160583,Y=0.566585958004, texture = "MAHelper/Icons/Signal2.dds",   c = 1,},
						[2] = {posx =130007,posy =49931,posz =177102,X=0.54237288236618,Y=0.59079903364182, texture = "MAHelper/Icons/Signal2.dds",   c = 1,},
						[3] = {posx =131698,posy =49942,posz =176554,X=0.58111381530762,Y=0.5762711763382, texture = "MAHelper/Icons/Signal2.dds",   c = 1,},
					},
				},
				[3] = {
					nMOB = 3,
					Mobs = {
						[1] = {posx =131049,posy =49915,posz =173796,X=0.566585958004,Y=0.50847458839417, texture = "MAHelper/Icons/Signal3.dds",  c = 1,}, 
						[2] = {posx =128862,posy =49931,posz =174017,X=0.51331716775894,Y=0.51573848724365, texture = "MAHelper/Icons/Signal3.dds",  c = 1,},
						[3] = {posx =130739,posy =49904,posz =176791,X=0.55932205915451,Y=0.58111381530762, texture = "MAHelper/Icons/Signal3.dds",  c = 1,},
					},
				},
				[4] = {
					nMOB = 2,
					Mobs = {
						[1] = {posx =129338,posy =49953,posz =177183,X=0.52542370557785,Y=0.59079903364182, texture = "MAHelper/Icons/Signal4.dds",   c = 1,},
						[2] = {posx =129268,posy =49948,posz =173207,X=0.52300244569778,Y=0.49636805057526, texture = "MAHelper/Icons/Signal4.dds",   c = 1,},
					},
				},
			},
		},
		[5] = {
			nWave = 1,
			Waves = {
				[1] = {
					nMOB = 1,
					Mobs = {
						[1] = {posx =130271,posy =49917,posz =173209,X=0.5472155213356,Y=0.49636805057526, texture = "MAHelper/Icons/BossMaelCroco.dds", c = 3},						
					},
				},
			},
		},
	},	
}

CurrWeave = 1
NumK = 0
CurrStageArena = 1
token = true

function Set7.OnCheckingEffect( eventCode,  changeType,  effectSlot,  effectName,  unitTag,  beginTime,  endTime,  stackCount,  iconName,  buffType,  effectType,  abilityType,  statusEffectType,  unitName,  unitId,  abilityId,  sourceUnitType)
	if effectName == "Portal Spawn" and unitName == "Argonian Venomcaller" then
		MAHelper.SetText("Argonian Venomcaller spawned! Kill it!")
		do return end
	end
	if effectName == "Portal Spawn" and NumK ~= 0 and token then
		token = false
		if NumK > 0 then		
			NumK = NumK - Set7.rounds[CurrStageArena].Waves[CurrWeave].nMOB 
		end
		CurrWeave = CurrWeave + 1
		MAHelper.RemoveIcons()
		MAHelper.ListAddPosition(CurrStageArena , CurrWeave)
		zo_callLater(function() token = true end, 6000)
	end
end

function  Set7.OnTitleAnnounced(eventcode, title)
	NumK = 0
	CurrWeave = 1
	CurrStageArena = MAHelper.OnTitleReturnRound(title)
	if CurrStageArena >= 1 then
		MAHelper.RemoveIcons()
		MAHelper.ListAddPosition(CurrStageArena , 1)
	end
end


function Set7.OnUnitKilled(eventCode,   result,  isError,  abilityName,  abilityGraphic,   abilityActionSlotType,  sourceName,   sourceType,   targetName,   targetType,  hitValue,   powerType,   damageType,  log,  sourceUnitId,  targetUnitId,  abilityId,  overflow)
	if targetName == "Argonian Venomcaller" then
		MAHelper.StopText()
		do return end
	end
	if CurrStageArena == 5 then
		if targetName ~= "Argonian Behemoth" then
			do return end
		else
			MAHelper.RemoveIcons()
			do return end
		end
	end
	NumK = NumK + 1
	if NumK >= Set7.rounds[CurrStageArena].Waves[CurrWeave].nMOB then
		token = false 
		zo_callLater(function() token = true end, 5000)
		MAHelper.RemoveIcons()
		CurrWeave = CurrWeave +1
		if CurrWeave <= Set7.rounds[CurrStageArena].nWave then
			NumK = 0			
			MAHelper.ListAddPosition(CurrStageArena, CurrWeave)		
		else
			CurrWeave = 1
			NumK=0
			CurrStageArena = CurrStageArena +1
			if CurrStageArena <= Set7.nR then 			
				MAHelper.ListAddPosition(CurrStageArena, 1)	
			end
		end
	end
end
