Set9={
	name = "Theater of Despair",
	nR = 6,
	rounds = {			
		--first round
		[1] = {
			nWave =4,
			Waves = {
				[1] = {
					nMOB = 3,
					Mobs = {
						[1] = {posx =35706,posy =50034,posz =169781,X=0.52427184581757,Y=0.55825245380402, texture = "MAHelper/Icons/Signal.dds",  c = 1,}, 
						[2] = {posx =34822,posy =50017,posz =170168,X=0.50970876216888,Y=0.56472492218018, texture = "MAHelper/Icons/Signal.dds",  c = 1,},
						[3] = {posx =35483,posy =50080,posz =167811,X=0.51941746473312,Y=0.52750808000565, texture = "MAHelper/Icons/Signal.dds",  c = 1,},
					},
				},
				[2] = {
					nMOB = 2,
					Mobs = {
						[1] = {posx =34150,posy =50038,posz =169947,X=0.49838188290596,Y=0.5614886879921, texture = "MAHelper/Icons/Signal2.dds",   c = 1,},
						[2] = {posx =36048,posy =50046,posz =168780,X=0.52912622690201,Y=0.54207122325897, texture = "MAHelper/Icons/Signal2.dds",   c = 1,},
					},
				},
				[3] = {
					nMOB = 2,
					Mobs = {
						[1] = {posx =34374,posy =50061,posz =167662,X=0.50161814689636,Y=0.52427184581757, texture = "MAHelper/Icons/Signal3.dds",   c = 1,}, 
						[2] = {posx =33711,posy =50071,posz =168372,X=0.49190938472748,Y=0.53559869527817, texture = "MAHelper/Icons/Signal3.dds",   c = 1,}, 
					},
				},
				[4] = {
					nMOB = 1,
					Mobs = {
						[1] = {posx =33619,posy =50051,posz =169065,X=0.49029126763344,Y=0.54692554473877, texture = "MAHelper/Icons/Signal4.dds",  c = 2,},
					},
				},
			},
		},
		--second round
		[2] = {
			nWave =4,
			Waves = {
				[1] = {
					nMOB = 3,
					Mobs = {
						[1] = {posx =35744,posy =50047,posz =169584,X=0.52427184581757,Y=0.55501616001129, texture = "MAHelper/Icons/Signal.dds",  c = 1,}, 
						[2] = {posx =34863,posy =50072,posz =167716,X=0.50970876216888,Y=0.52588999271393, texture = "MAHelper/Icons/Signal.dds",  c = 1,},
						[3] = {posx =33763,posy =50052,posz =168659,X=0.49190938472748,Y=0.54045307636261, texture = "MAHelper/Icons/Signal.dds",  c = 1,},
					},
				},
				[2] = {
					nMOB = 3,
					Mobs = {
						[1] = {posx =33961,posy =50066,posz =167946,X=0.49514561891556,Y=0.52912622690201, texture = "MAHelper/Icons/Signal2.dds",   c = 1,},
						[2] = {posx =35962,posy =50049,posz =168554,X=0.52750808000565,Y=0.53883492946625, texture = "MAHelper/Icons/Signal2.dds",   c = 1,},
						[3] = {posx =34764,posy =50007,posz =170094,X=0.50809061527252,Y=0.56310677528381, texture = "MAHelper/Icons/Signal2.dds",   c = 1,},
					},
				},
				[3] = {
					nMOB = 2,
					Mobs = {
						[1] = {posx =35806,posy =50037,posz =168954,X=0.52588999271393,Y=0.54530745744705, texture = "MAHelper/Icons/Signal3.dds",  c = 2,}, 
						[2] = {posx =33756,posy =50040,posz =168821,X=0.49190938472748,Y=0.54368931055069, texture = "MAHelper/Icons/Signal3.dds",  c = 1,},
					},
				},
				[4] = {
					nMOB = 3,
					Mobs = {
						[1] = {posx =35635,posy =50069,posz =168105,X=0.5226536989212,Y=0.53236246109009, texture = "MAHelper/Icons/Signal3.dds",  c = 1,}, 
						[2] = {posx =35528,posy =50025,posz =169751,X=0.52103561162949,Y=0.55825245380402, texture = "MAHelper/Icons/Signal3.dds",  c = 1,},
						[3] = {posx =33754,posy =50058,posz =169617,X=0.49190938472748,Y=0.55663430690765, texture = "MAHelper/Icons/Signal3.dds",  c = 2,},
					},
				},
			},
		},
		--third round
		[3] = {
			nWave =5,
			Waves = {
				[1] = {
					nMOB = 2,
					Mobs = {
						[1] = {posx =33964,posy =50038,posz =168378,X=0.49514561891556,Y=0.53559869527817, texture = "MAHelper/Icons/Signal.dds",  c = 1,}, 
						[2] = {posx =34465,posy =50018,posz =169822,X=0.50323623418808,Y=0.55987054109573, texture = "MAHelper/Icons/Signal.dds",  c = 2,}, --daedroth
					},
				},
				[2] = {
					nMOB = 3,
					Mobs = {
						[1] = {posx =33691,posy =50043,posz =169005,X=0.49029126763344,Y=0.54692554473877, texture = "MAHelper/Icons/Signal2.dds",   c = 1,},
						[2] = {posx =35315,posy =50061,posz =167731,X=0.51779937744141,Y=0.52588999271393, texture = "MAHelper/Icons/Signal2.dds",   c = 1,},
						[3] = {posx =36080,posy =50066,posz =169122,X=0.52912622690201,Y=0.54854369163513, texture = "MAHelper/Icons/Signal2.dds",   c = 1,},
					},
				},
				[3] = {
					nMOB = 1,
					Mobs = {
						[1] = {posx =34927,posy =49984,posz =168716,X=0.5113268494606,Y=0.54207122325897, texture = "MAHelper/Icons/Signal3.dds",  c = 1,}, 
					},
				},
				[4] = {
					nMOB = 2,
					Mobs = {
						[1] = {posx =34004,posy =50005,posz =169565,X=0.49676376581192,Y=0.55501616001129, texture = "MAHelper/Icons/Signal.dds",  c = 1,}, 
						[2] = {posx =34639,posy =50003,posz =170104,X=0.50647246837616,Y=0.56472492218018, texture = "MAHelper/Icons/Signal.dds",  c = 1,},
					},
				},
				[5] = {
					nMOB = 3,
					Mobs = {
						[1] = {posx =35714,posy =50035,posz =169776,X=0.52427184581757,Y=0.55825245380402, texture = "MAHelper/Icons/Signal2.dds",   c = 1,},
						[2] = {posx =35768,posy =50083,posz =168086,X=0.52427184581757,Y=0.53074431419373, texture = "MAHelper/Icons/Signal2.dds",   c = 1,},
						[3] = {posx =34491,posy =50105,posz =167452,X=0.50323623418808,Y=0.52103561162949, texture = "MAHelper/Icons/Signal2.dds",   c = 1,}, --daed
					},
				},
			},
		},
		[4] ={
			nWave =5,
			Waves = {
				[1] = {
					nMOB = 3,
					Mobs = {
						[1] = {posx =33952,posy =50063,posz =167981,X=0.49514561891556,Y=0.52912622690201, texture = "MAHelper/Icons/Signal.dds",  c = 1,}, 
						[2] = {posx =35485,posy =50076,posz =167873,X=0.51941746473312,Y=0.52750808000565, texture = "MAHelper/Icons/Signal.dds",  c = 1,},
						[3] = {posx =35109,posy =50246,posz =171211,X=0.51456308364868,Y=0.58252429962158, texture = "MAHelper/Icons/MaelSkeletonMage.dds",  c = 1,},
					},
				},
				[2] = {
					nMOB = 3,
					Mobs = {
						[1] = {posx =34174,posy =50026,posz =169820,X=0.49838188290596,Y=0.55987054109573, texture = "MAHelper/Icons/Signal2.dds",   c = 1,},
						[2] = {posx =34622,posy =50098,posz =167489,X=0.50647246837616,Y=0.52103561162949, texture = "MAHelper/Icons/Signal2.dds",   c = 1,},
						[3] = {posx =37473,posy =50162,posz =168369,X=0.55177992582321,Y=0.53559869527817, texture = "MAHelper/Icons/MaelSkeletonMage.dds",   c = 1,},
					},
				},
				[3] = {
					nMOB = 3,
					Mobs = {
						[1] = {posx =35992,posy =50059,posz =169172,X=0.52750808000565,Y=0.54854369163513, texture = "MAHelper/Icons/Signal3.dds",  c = 1,}, 
						[2] = {posx =34558,posy =50007,posz =170033,X=0.50485438108444,Y=0.56310677528381, texture = "MAHelper/Icons/Signal3.dds",  c = 1,}, 
						[3] = {posx =32643,posy =50237,posz =167874,X=0.47411003708839,Y=0.52750808000565, texture = "MAHelper/Icons/MaelSkeletonMage.dds",  c = 1,}, 
					},
				},
				[4] = {
					nMOB = 2,
					Mobs = {
						[1] = {posx =32481,posy =50267,posz =169549,X=0.47087377309799,Y=0.55501616001129, texture = "MAHelper/Icons/MaelSkeletonMage.dds",  c = 1,}, 
						[2] = {posx =36074,posy =50084,posz =168257,X=0.52912622690201,Y=0.53398060798645, texture = "MAHelper/Icons/Signal.dds",  c = 1,},
					},
				},
				[5] = {
					nMOB = 3,
					Mobs = {
						[1] = {posx =34795,posy =50256,posz =166357,X=0.50809061527252,Y=0.50323623418808, texture = "MAHelper/Icons/MaelSkeletonMage.dds",   c = 1,},
						[2] = {posx =32715,posy =50235,posz =170039,X=0.47572815418243,Y=0.56310677528381, texture = "MAHelper/Icons/Signal5.dds",   c = 1,},
						[3] = {posx =36621,posy =50223,posz =170380,X=0.53883492946625,Y=0.56796115636826, texture = "MAHelper/Icons/MaelSkeletonMage.dds",   c = 1,},
					},
				},
			},
		},
		[5] = {
			nWave =5,
			Waves = {
				[1] = {
					nMOB = 2,
					Mobs = {
						[1] = {posx =34558,posy =50007,posz =170073,X=0.50485438108444,Y=0.56310677528381, texture = "MAHelper/Icons/Signal.dds",  c = 1,}, 
						[2] = {posx =34703,posy =50065,posz =167696,X=0.50809061527252,Y=0.52427184581757, texture = "MAHelper/Icons/Signal.dds",  c = 1,},
					},
				},
				[2] = {
					nMOB = 1,
					Mobs = {
						[1] = {posx =34888,posy =49986,posz =168835,X=0.50970876216888,Y=0.54368931055069, texture = "MAHelper/Icons/BossMaelDraghenshi.dds",   c =  2,},
					},
				},
				[3] = {
					nMOB = 3,
					Mobs = {
						[1] = {posx =35934,posy =50061,posz =169708,X=0.52750808000565,Y=0.55825245380402, texture = "MAHelper/Icons/Signal3.dds",  c = 1,}, 
						[2] = {posx =35749,posy =50090,posz =167961,X=0.52427184581757,Y=0.52912622690201, texture = "MAHelper/Icons/Signal3.dds",  c = 1,}, 
						[3] = {posx =33591,posy =50074,posz =168649,X=0.4886731505394,Y=0.54045307636261, texture = "MAHelper/Icons/Signal3.dds",  c = 1,}, 
					},
				},
				[4] = {
					nMOB = 3,
					Mobs = {
						[1] = {posx =36079,posy =50062,posz =169355,X=0.52912622690201,Y=0.55177992582321, texture = "MAHelper/Icons/Signal4.dds",  c = 1,}, 
						[2] = {posx =35301,posy =50093,posz =167519,X=0.51779937744141,Y=0.5226536989212, texture = "MAHelper/Icons/Signal4.dds",  c = 1,},
						[3] = {posx =33899,posy =50022,posz =169649,X=0.49352750182152,Y=0.55663430690765, texture = "MAHelper/Icons/Signal4.dds",  c = 1,},
					},
				},
				[5] = {
					nMOB = 1,
					Mobs = {
						[1] = {posx =35414,posy =50041,posz =170002,X=0.51941746473312,Y=0.56310677528381, texture = "MAHelper/Icons/Signal5.dds",   c = 1,},
					},
				},
			},
		},
		[6] = {
			nWave =1,
			Waves= {
				[1] = {
					nMOB = 1,
					Mobs = {
						[1] = {posx =34888,posy =49986,posz =168835,X=0.50970876216888,Y=0.54368931055069, texture = "MAHelper/Icons/BossMaelFinal.dds",  c = 3,}, 
					},
				},
			}
		},
		[7] = {
			nWave =1,
			Waves= {
				[1] = {
					nMOB = 1,
					Mobs = {
						[1] = {posx =34888,posy =49986,posz =168835,X=0.50970876216888,Y=0.54368931055069, texture = "MAHelper/Icons/MaelMoyaiSuper.dds",  c = 3,},
					},
				},
			}
		},
	},	
}

CurrWeave = 1
NumK = 0
CurrStageArena = 1
token = true

function Set9.OnCheckingEffect( eventCode,  changeType,  effectSlot,  effectName,  unitTag,  beginTime,  endTime,  stackCount,  iconName,  buffType,  effectType,  abilityType,  statusEffectType,  unitName,  unitId,  abilityId,  sourceUnitType)
	if effectName == "Portal Spawn" and CurrStageArena == 5 and CurrWeave == 2 then
		token = false
		NumK = NumK - Set9.rounds[CurrStageArena].Waves[CurrWeave].nMOB 
		CurrWeave = CurrWeave + 1
		MAHelper.RemoveIcons()
		MAHelper.ListAddPosition(CurrStageArena , CurrWeave)
		zo_callLater(function() token = true end, 5000)
	end 
	if effectName == "Portal Spawn" and NumK ~= 0 and token then
		token = false
		NumK = NumK - Set9.rounds[CurrStageArena].Waves[CurrWeave].nMOB 
		CurrWeave = CurrWeave + 1
		MAHelper.RemoveIcons()
		MAHelper.ListAddPosition(CurrStageArena , CurrWeave)
		zo_callLater(function() token = true end, 5000)
	end
end

function  Set9.OnTitleAnnounced(eventcode, title)
	NumK = 0
	CurrWeave = 1
	CurrStageArena = MAHelper.OnTitleReturnRound(title)
	if CurrStageArena >= 1 then
		MAHelper.RemoveIcons()
		MAHelper.ListAddPosition(CurrStageArena , 1)
	end
end

function Set9.OnUnitKilled(eventCode,   result,  isError,  abilityName,  abilityGraphic,   abilityActionSlotType,  sourceName,   sourceType,   targetName,   targetType,  hitValue,   powerType,   damageType,  log,  sourceUnitId,  targetUnitId,  abilityId,  overflow)
	if CurrStageArena == 6 then
		if targetName == "Voriak Solkyn^M" then
			MAHelper.RemoveIcons()
			MAHelper.ListAddPosition(7,1)
			do return end
		end
		do return end
	end
	NumK = NumK + 1
	if NumK >= Set9.rounds[CurrStageArena].Waves[CurrWeave].nMOB then
		token = false 
		zo_callLater(function() token = true end, 4000)
		MAHelper.RemoveIcons()
		CurrWeave = CurrWeave +1
		if CurrWeave <= Set9.rounds[CurrStageArena].nWave then
			NumK = 0			
			MAHelper.ListAddPosition(CurrStageArena, CurrWeave)		
		else
			CurrStageArena = CurrStageArena +1
			if CurrStageArena <= Set9.nR then 			
				MAHelper.ListAddPosition(CurrStageArena, 1)	
			end
		end
	end
end
