-- Flamechasers Spellcheck & Autocomplete: curated ESO seed phrases
-- Names are kept by category for diagnostics and future UI features.
-- RuntimeESOCollector.lua supplements this from the installed ESO client.

local FSC = FlamechasersSpellcheck
local E = FSC.ESO
E.phrases = {
    ["arenas_and_archives"] = {
        "Dragonstar Arena",
        "Maelstrom Arena",
        "Blackrose Prison",
        "Vateshran Hollows",
        "Infinite Archive",
    },
    ["base_dungeons"] = {
        "Fungal Grotto I",
        "Fungal Grotto II",
        "Spindleclutch I",
        "Spindleclutch II",
        "The Banished Cells I",
        "The Banished Cells II",
        "Darkshade Caverns I",
        "Darkshade Caverns II",
        "Elden Hollow I",
        "Elden Hollow II",
        "Wayrest Sewers I",
        "Wayrest Sewers II",
        "Crypt of Hearts I",
        "Crypt of Hearts II",
        "City of Ash I",
        "City of Ash II",
        "Arx Corinium",
        "Blackheart Haven",
        "Blessed Crucible",
        "Direfrost Keep",
        "Selene's Web",
        "Tempest Island",
        "Vaults of Madness",
        "Volenfell",
    },
    ["cities"] = {
        "Daggerfall",
        "Wayrest",
        "Shornhelm",
        "Evermore",
        "Sentinel",
        "Bergama",
        "Davon's Watch",
        "Ebonheart",
        "Mournhold",
        "Narsis",
        "Windhelm",
        "Riften",
        "Elden Root",
        "Vulkhel Guard",
        "Skywatch",
        "Rawl'kha",
        "Marbruk",
        "Woodhearth",
        "Orsinium",
        "Abah's Landing",
        "Kvatch",
        "Anvil",
        "Vivec City",
        "Alinor",
        "Lilmoth",
        "Rimmen",
        "Senchal",
        "Solitude",
        "Markarth",
        "Leyawiin",
        "Gonfalon Bay",
        "Necrom",
        "Skingrad",
        "Sunport",
        "Vastyr",
        "Fargrave",
        "Aldcroft",
        "Arenthia",
        "Baandari Trading Post",
        "Balmora",
        "Belkarth",
        "Brass Fortress",
        "Camlorn",
        "Dune",
        "Elinhir",
        "Firsthold",
        "Gideon",
        "Hallin's Stand",
        "Haven",
        "Hollow City",
        "Kozanset",
        "Kragenmoor",
        "Lillandril",
        "Mistral",
        "Northpoint",
        "Port Hunding",
        "Silvenar",
        "Stormhold",
        "Tava's Blessing",
        "Velyn Harbor",
    },
    ["classes"] = {
        "Dragonknight",
        "Sorcerer",
        "Nightblade",
        "Templar",
        "Warden",
        "Necromancer",
        "Arcanist",
    },
    ["current_content"] = {
        "Fallen Banners",
        "Feast of Shadows",
        "Seasons of the Worm Cult",
        "Black Gem Foundry",
        "Naj-Caldeesh",
        "Exiled Redoubt",
        "Lep Seclusa",
        "Ossein Cage",
        "Solstice",
        "Tamriel Tomes",
        "Nowhere Vault",
        "Night Market",
    },
    ["buffs_and_debuffs"] = {
        "Minor Slayer",
        "Minor Aegis",
        "Major Brutality",
        "Major Expedition",
        "Minor Protection",
        "Major Protection",
        "Major Resolve",
        "Minor Vulnerability",
        "Major Savagery",
        "Minor Force",
        "Minor Maim",
        "Major Evasion",
        "Major Maim",
        "Major Breach",
        "Major Prophecy",
        "Minor Breach",
        "Minor Endurance",
        "Major Berserk",
        "Minor Berserk",
        "Minor Resolve",
        "Minor Courage",
        "Minor Heroism",
        "Major Cowardice",
        "Major Force",
        "Major Vulnerability",
        "Minor Fortitude",
        "Minor Intellect",
        "Major Heroism",
        "Minor Lifesteal",
        "Minor Vitality",
        "Major Courage",
        "Major Defile",
        "Major Vitality",
        "Major Aegis",
        "Major Sorcery",
        "Minor Defile",
        "Minor Expedition",
        "Major Mending",
        "Major Slayer",
        "Minor Brittle",
        "Minor Cowardice",
        "Minor Enervation",
        "Minor Mending",
        "Minor Mangle",
        "Major Endurance",
        "Major Fortitude",
        "Minor Evasion",
        "Minor Timidity",
        "Major Brittle",
        "Minor Magickasteal",
        "Minor Toughness",
        "Major Intellect",
        "Minor Brutality",
        "Minor Prophecy",
        "Minor Savagery",
        "Minor Sorcery",
        "Minor Uncertainty",
    },
    ["status_effects_and_cc"] = {
        "Burning",
        "Chilled",
        "Concussion",
        "Concussed",
        "Diseased",
        "Hemorrhaging",
        "Overcharged",
        "Poisoned",
        "Sundered",
        "Off Balance",
        "Crowd Control",
        "Stun",
        "Stunned",
        "Disorient",
        "Fear",
        "Silence",
        "Knockback",
        "Immobilize",
        "Immobilized",
        "Root",
        "Snare",
        "Stealth",
        "Invisible",
        "Revealed",
    },
    ["combat_and_build_terms"] = {
        "Area of Effect",
        "AoE",
        "Damage over Time",
        "DoT",
        "Direct Damage",
        "Single Target",
        "Light Attack",
        "Heavy Attack",
        "Light Attack Weaving",
        "Bar Swap",
        "Front Bar",
        "Back Bar",
        "Weapon Damage",
        "Spell Damage",
        "Weapon Critical",
        "Spell Critical",
        "Critical Chance",
        "Critical Damage",
        "Physical Resistance",
        "Spell Resistance",
        "Armor Penetration",
        "Spell Penetration",
        "Physical Penetration",
        "Damage Shield",
        "Block Mitigation",
        "Block Cost",
        "Roll Dodge",
        "Bash",
        "Execute",
        "Burst Damage",
        "Cleave",
        "Sustain",
        "Resource Recovery",
        "Magicka Recovery",
        "Stamina Recovery",
        "Health Recovery",
        "Ultimate Generation",
        "Resurrection",
        "Resurrect",
        "Battle Rez",
        "Prebuff",
        "Prebuffing",
        "Parse Dummy",
        "Trial Dummy",
        "Resistance Cap",
        "Penetration Cap",
        "Global Cooldown",
    },
    ["crafting_and_gear_terms"] = {
        "Blacksmithing",
        "Clothing",
        "Woodworking",
        "Jewelry Crafting",
        "Alchemy",
        "Enchanting",
        "Provisioning",
        "Master Writ",
        "Master Writs",
        "Trait Research",
        "Reconstruction",
        "Item Set Collection",
        "Sticker Book",
        "Transmute Crystals",
        "Nirnhoned",
        "Divines",
        "Infused",
        "Reinforced",
        "Well-fitted",
        "Impenetrable",
        "Sturdy",
        "Training",
        "Precise",
        "Sharpened",
        "Charged",
        "Decisive",
        "Powered",
        "Defending",
        "Bloodthirsty",
        "Harmony",
        "Arcane",
        "Healthy",
        "Robust",
        "Swift",
        "Protective",
        "Triune",
    },
    ["pvp_terms"] = {
        "Alliance Points",
        "Tel Var Stones",
        "Elder Scroll",
        "Battleground",
        "Battlegrounds",
        "Deathmatch",
        "Domination",
        "Capture the Flag",
        "Crazy King",
        "King of the Hill",
        "Chaosball",
        "Murderball",
        "Keep",
        "Outpost",
        "Resource",
        "Siege",
        "Ballista",
        "Trebuchet",
        "Battering Ram",
        "Forward Camp",
        "Emperor",
        "Alliance War",
        "Battle Spirit",
        "Vengeance",
        "Veterancy",
    },
    ["popular_skills_fallback"] = {
        "Banner Bearer",
        "Ulfsild's Contingency",
        "Wield Soul",
        "Elemental Susceptibility",
        "Resolving Vigor",
        "Echoing Vigor",
        "Combat Prayer",
        "Aggressive Horn",
        "War Horn",
        "Barrier",
        "Elemental Blockade",
        "Wall of Elements",
        "Destructive Clench",
        "Force Pulse",
        "Crushing Shock",
        "Inner Fire",
        "Inner Rage",
        "Puncture",
        "Pierce Armor",
        "Silver Leash",
        "Razor Caltrops",
        "Ring of Preservation",
        "Camouflaged Hunter",
        "Barbed Trap",
        "Channeled Acceleration",
        "Race Against Time",
        "Mystic Orb",
        "Energy Orb",
        "Blood Altar",
        "Overflowing Altar",
        "Dragonknight Standard",
        "Death Stroke",
        "Incapacitating Strike",
        "Soul Harvest",
        "Consuming Darkness",
        "Soul Shred",
        "Soul Siphon",
        "Soul Tether",
        "Siphoning Attacks",
        "Drain Power",
        "Power Extraction",
        "Sap Essence",
        "The Unblinking Eye",
        "Vitalizing Glyphic",
        "Abyssal Emergence",
    },
    ["popular_passives_fallback"] = {
        "Undaunted Mettle",
        "Battle Roar",
        "Helping Hands",
        "Combustion",
        "Catalyst",
        "Magicka Flood",
        "Soul Siphoner",
        "Transfer",
        "Tri Focus",
        "Penetrating Magic",
        "Elemental Force",
        "Ancient Knowledge",
        "Destruction Expert",
        "Medicinal Use",
        "Meticulous Disassembly",
        "Battle Mastery",
        "Flawless Ritual",
        "Gifted Rider",
        "War Mount",
    },
    ["popular_sets_and_mythics"] = {
        "Oakensoul Ring",
        "Velothi Ur-Mage's Amulet",
        "Order's Wrath",
        "Tide-Born Wildstalker",
        "Ring of the Pale Order",
        "Sea-Serpent's Coil",
        "Harpooner's Wading Kilt",
        "Mora's Whispers",
        "Powerful Assault",
        "Turning Tide",
        "Pearlescent Ward",
        "Lucent Echoes",
        "Roaring Opportunist",
        "Pillager's Profit",
        "Elemental Catalyst",
        "Martial Knowledge",
        "Deadly Strike",
        "Ansuul's Torment",
        "Coral Riptide",
        "Whorl of the Depths",
        "Relequen",
    },
    ["mundus_stones"] = {
        "The Apprentice",
        "The Atronach",
        "The Lady",
        "The Lord",
        "The Lover",
        "The Mage",
        "The Ritual",
        "The Serpent",
        "The Shadow",
        "The Steed",
        "The Thief",
        "The Tower",
        "The Warrior",
    },
    ["currencies_and_rewards"] = {
        "Alliance Points",
        "Archival Fortunes",
        "Crown Gems",
        "Crowns",
        "Event Tickets",
        "Gold",
        "Seals of Endeavor",
        "Tel Var Stones",
        "Transmute Crystals",
        "Undaunted Keys",
        "Writ Vouchers",
        "Champion Points",
        "Skill Points",
        "Attribute Points",
    },
    ["named_characters"] = {
        "Abnur Tharn",
        "Cadwell",
        "Varen Aquilarios",
        "Lyris Titanborn",
        "Sai Sahan",
        "Mannimarco",
        "Razum-dar",
        "Naryu Virian",
        "Darien Gautier",
        "Gabrielle Benele",
        "Eveli Sharp-Arrow",
        "Jakarn",
        "Lady Arabelle Davaux",
        "Leramil the Wise",
        "Prince Azah",
        "Midconjurer Mirmal",
        "Wormblood",
        "Bastian Hallix",
        "Mirri Elendis",
        "Ember",
        "Isobel Veloise",
        "Sharp-as-Night",
        "Azandar al-Cybiades",
        "Tanlorin",
        "Zerith-var",
    },
    ["systems_and_activities"] = {
        "Antiquities",
        "Scrying",
        "Excavation",
        "Tales of Tribute",
        "Endeavors",
        "Golden Pursuits",
        "Tamriel Tomes",
        "Armory",
        "Outfit Station",
        "Group Finder",
        "Dungeon Finder",
        "Activity Finder",
        "Housing",
        "Home Tours",
        "Skill Styling",
        "Subclassing",
        "Companions",
        "Scribing",
        "Infinite Archive",
        "Undaunted Pledges",
    },
    ["daedric_and_lore"] = {
        "Daedra",
        "Daedric",
        "Aedra",
        "Aedric",
        "Tamriel",
        "Nirn",
        "Oblivion",
        "Mundus",
        "Molag Bal",
        "Mehrunes Dagon",
        "Hermaeus Mora",
        "Sheogorath",
        "Azura",
        "Boethiah",
        "Mephala",
        "Nocturnal",
        "Meridia",
        "Hircine",
        "Sithis",
        "Akatosh",
        "Kynareth",
        "Mara",
        "Stendarr",
        "Julianos",
        "Zenithar",
        "Arkay",
        "Lorkhan",
        "Sotha Sil",
        "Almalexia",
        "Vivec",
    },
    ["dlc_dungeons"] = {
        "Imperial City Prison",
        "White-Gold Tower",
        "Ruins of Mazzatun",
        "Cradle of Shadows",
        "Bloodroot Forge",
        "Falkreath Hold",
        "Scalecaller Peak",
        "Fang Lair",
        "Moon Hunter Keep",
        "March of Sacrifices",
        "Frostvault",
        "Depths of Malatar",
        "Moongrave Fane",
        "Lair of Maarselok",
        "Icereach",
        "Unhallowed Grave",
        "Stone Garden",
        "Castle Thorn",
        "Black Drake Villa",
        "The Cauldron",
        "Red Petal Bastion",
        "The Dread Cellar",
        "Coral Aerie",
        "Shipwright's Regret",
        "Earthen Root Enclave",
        "Graven Deep",
        "Bal Sunnar",
        "Scrivener's Hall",
        "Oathsworn Pit",
        "Bedlam Veil",
        "Exiled Redoubt",
        "Lep Seclusa",
        "Black Gem Foundry",
        "Naj-Caldeesh",
    },
    ["gameplay_terms"] = {
        "wayshrine",
        "wayshrines",
        "skyshard",
        "skyshards",
        "hardmode",
        "hardmodes",
        "trifecta",
        "trifectas",
        "pledge",
        "pledges",
        "Undaunted",
        "DPS",
        "DD",
        "tank",
        "tanking",
        "healer",
        "healing",
        "parse",
        "parsing",
        "proc",
        "procs",
        "buff",
        "buffs",
        "debuff",
        "debuffs",
        "aggro",
        "taunt",
        "taunts",
        "taunting",
        "interrupt",
        "interrupts",
        "synergy",
        "synergies",
        "writ",
        "writs",
        "transmute",
        "transmutes",
        "mythic",
        "mythics",
        "monster set",
        "Scribing",
        "grimoire",
        "grimoires",
        "script",
        "scripts",
        "subclass",
        "subclassing",
        "Werewolf",
        "Vampire",
        "Champion Points",
        "CP",
        "PvE",
        "PvP",
        "Battlegrounds",
        "Cyrodiil",
        "Veteran",
        "Normal",
        "HM",
        "DLC",
        "ESO Plus",
        "Crown Store",
        "Armory",
        "Outfit Station",
        "Transmute Station",
        "Craft Bag",
        "quickslot",
        "quickslots",
        "Companion",
        "companions",
        "Antiquities",
        "Scrying",
        "Excavation",
        "Endeavors",
        "Seals of Endeavor",
        "Tamriel Tomes",
        "Dynamic Encounters",
        "Rumors",
        "Challenge Difficulty",
        "Night Market",
    },
    ["organizations"] = {
        "Daggerfall Covenant",
        "Ebonheart Pact",
        "Aldmeri Dominion",
        "Undaunted",
        "Fighters Guild",
        "Mages Guild",
        "Psijic Order",
        "Thieves Guild",
        "Dark Brotherhood",
        "Companions",
        "Worm Cult",
        "Stirk Fellowship",
        "Morag Tong",
        "House Hlaalu",
        "House Redoran",
        "House Telvanni",
        "House Dres",
        "House Indoril",
        "Corelanya Clan",
    },
    ["races"] = {
        "Breton",
        "Redguard",
        "Orc",
        "Nord",
        "Dark Elf",
        "Argonian",
        "High Elf",
        "Wood Elf",
        "Khajiit",
        "Imperial",
    },
    ["skill_lines_and_systems"] = {
        "Ardent Flame",
        "Draconic Power",
        "Earthen Heart",
        "Dark Magic",
        "Daedric Summoning",
        "Storm Calling",
        "Assassination",
        "Shadow",
        "Siphoning",
        "Aedric Spear",
        "Dawn's Wrath",
        "Restoring Light",
        "Animal Companions",
        "Green Balance",
        "Winter's Embrace",
        "Grave Lord",
        "Bone Tyrant",
        "Living Death",
        "Herald of the Tome",
        "Soldier of Apocrypha",
        "Curative Runeforms",
        "Two Handed",
        "One Hand and Shield",
        "Dual Wield",
        "Bow",
        "Destruction Staff",
        "Restoration Staff",
        "Light Armor",
        "Medium Armor",
        "Heavy Armor",
        "Soul Magic",
        "Vampire",
        "Werewolf",
        "Fighters Guild",
        "Mages Guild",
        "Undaunted",
        "Psijic Order",
        "Thieves Guild",
        "Dark Brotherhood",
        "Legerdemain",
        "Assault",
        "Support",
        "Emperor",
        "Blacksmithing",
        "Clothing",
        "Woodworking",
        "Jewelry Crafting",
        "Alchemy",
        "Enchanting",
        "Provisioning",
        "Scribing",
        "Class Mastery",
        "Vengeance",
        "Veterancy",
    },
    ["trials"] = {
        "Aetherian Archive",
        "Hel Ra Citadel",
        "Sanctum Ophidia",
        "Maw of Lorkhaj",
        "Halls of Fabrication",
        "Asylum Sanctorium",
        "Cloudrest",
        "Sunspire",
        "Kyne's Aegis",
        "Rockgrove",
        "Dreadsail Reef",
        "Sanity's Edge",
        "Lucent Citadel",
        "Ossein Cage",
    },
    ["zones"] = {
        "Stros M'Kai",
        "Betnikh",
        "Glenumbra",
        "Stormhaven",
        "Rivenspire",
        "Alik'r Desert",
        "Bangkorai",
        "Bleakrock Isle",
        "Bal Foyen",
        "Stonefalls",
        "Deshaan",
        "Shadowfen",
        "Eastmarch",
        "The Rift",
        "Khenarthi's Roost",
        "Auridon",
        "Grahtwood",
        "Greenshade",
        "Malabal Tor",
        "Reaper's March",
        "Coldharbour",
        "Craglorn",
        "Cyrodiil",
        "Imperial City",
        "Wrothgar",
        "Hew's Bane",
        "Gold Coast",
        "Vvardenfell",
        "Clockwork City",
        "Summerset",
        "Artaeum",
        "Murkmire",
        "Northern Elsweyr",
        "Southern Elsweyr",
        "Western Skyrim",
        "Blackreach",
        "The Reach",
        "Blackwood",
        "The Deadlands",
        "Fargrave",
        "High Isle",
        "Amenos",
        "Galen",
        "Telvanni Peninsula",
        "Apocrypha",
        "West Weald",
        "Solstice",
        "Eyevea",
        "Arkthzand Cavern",
        "Greymoor Caverns",
        "High Isle and Amenos",
        "Galen and Y'ffelon",
        "Southern Marsh",
        "The Weeping Desert",
    },
}

-- ESO dictionary subcategories. These IDs are intentionally stable because their
-- enabled states are stored in SavedVariables. The registry exposes them generically
-- so future dictionary packs can use the same settings infrastructure.
E.subcategories = {
    { id = "general",    name = "General ESO & classes",       description = "Classes, races, and core ESO-specific vocabulary that does not fit a more specialized category.", order = 10, defaultEnabled = true },
    { id = "skills",     name = "Skills & skill lines",         description = "Skill lines, active abilities, passives, ultimates, and morph names.", order = 20, defaultEnabled = true },
    { id = "sets",       name = "Item sets & Mythics",         description = "Armor/weapon set names, monster sets, arena sets, trial sets, and Mythic items.", order = 30, defaultEnabled = true },
    { id = "locations",  name = "Locations & wayshrines",      description = "Zones, cities, settlements, maps, points of interest, and wayshrines.", order = 40, defaultEnabled = true },
    { id = "activities", name = "Dungeons, trials & arenas",   description = "Dungeons, trials, arenas, Infinite Archive, and other named group activities/current content.", order = 50, defaultEnabled = true },
    { id = "combat",     name = "Combat, buffs & debuffs",     description = "Buff/debuff names, status effects, crowd control, combat roles, parsing, build, and PvP terminology.", order = 60, defaultEnabled = true },
    { id = "systems",    name = "Systems, crafting & CP",      description = "Champion Points, Scribing, crafting/gear terms, currencies, Mundus Stones, Antiquities, Armory, and other gameplay systems.", order = 70, defaultEnabled = true },
    { id = "lore",       name = "Characters, factions & lore", description = "Named characters, alliances, organizations, Daedric names, and other lore terminology.", order = 80, defaultEnabled = true },
}

E.phraseCategoryToSubcategory = {
    arenas_and_archives = "activities",
    base_dungeons = "activities",
    cities = "locations",
    classes = "general",
    current_content = "activities",
    buffs_and_debuffs = "combat",
    status_effects_and_cc = "combat",
    combat_and_build_terms = "combat",
    crafting_and_gear_terms = "systems",
    pvp_terms = "combat",
    popular_skills_fallback = "skills",
    popular_passives_fallback = "skills",
    popular_sets_and_mythics = "sets",
    mundus_stones = "systems",
    currencies_and_rewards = "systems",
    named_characters = "lore",
    systems_and_activities = "systems",
    daedric_and_lore = "lore",
    dlc_dungeons = "activities",
    gameplay_terms = "systems",
    organizations = "lore",
    races = "general",
    skill_lines_and_systems = "skills",
    trials = "activities",
    zones = "locations",
}

function E.GetPhraseSubcategory(category)
    return E.phraseCategoryToSubcategory[category] or "general"
end

function E.IsSubcategoryEnabled(id)
    return FSC:IsDictionarySubcategoryEnabled("eso", id)
end

function E.ForEachEnabledStaticPhrase(callback)
    if type(callback) ~= "function" then return end
    for category, phrases in pairs(E.phrases or {}) do
        local subcategory = E.GetPhraseSubcategory(category)
        if E.IsSubcategoryEnabled(subcategory) then
            for _, phrase in ipairs(phrases) do callback(phrase, subcategory, category) end
        end
    end
end


E.seedTokens = {
    ["abah's"] = true,
    ["aedra"] = true,
    ["aedric"] = true,
    ["aetherian"] = true,
    ["akatosh"] = true,
    ["aldmeri"] = true,
    ["alik'r"] = true,
    ["alinor"] = true,
    ["almalexia"] = true,
    ["amenos"] = true,
    ["arcanist"] = true,
    ["argonian"] = true,
    ["arkay"] = true,
    ["artaeum"] = true,
    ["arx"] = true,
    ["auridon"] = true,
    ["azura"] = true,
    ["bangkorai"] = true,
    ["betnikh"] = true,
    ["blackreach"] = true,
    ["blackrose"] = true,
    ["bleakrock"] = true,
    ["boethiah"] = true,
    ["caldeesh"] = true,
    ["cloudrest"] = true,
    ["coldharbour"] = true,
    ["corinium"] = true,
    ["craglorn"] = true,
    ["cyrodiil"] = true,
    ["daedra"] = true,
    ["daedric"] = true,
    ["daggerfall"] = true,
    ["darkshade"] = true,
    ["davon's"] = true,
    ["deadlands"] = true,
    ["debuff"] = true,
    ["debuffs"] = true,
    ["deshaan"] = true,
    ["direfrost"] = true,
    ["dlc"] = true,
    ["dragonknight"] = true,
    ["dragonstar"] = true,
    ["dreadsail"] = true,
    ["eastmarch"] = true,
    ["ebonheart"] = true,
    ["elden"] = true,
    ["elsweyr"] = true,
    ["eso"] = true,
    ["falkreath"] = true,
    ["fargrave"] = true,
    ["foyen"] = true,
    ["frostvault"] = true,
    ["glenumbra"] = true,
    ["grahtwood"] = true,
    ["greenshade"] = true,
    ["grimoire"] = true,
    ["grimoires"] = true,
    ["hardmode"] = true,
    ["hardmodes"] = true,
    ["hermaeus"] = true,
    ["hew's"] = true,
    ["icereach"] = true,
    ["julianos"] = true,
    ["khajiit"] = true,
    ["khenarthi's"] = true,
    ["kvatch"] = true,
    ["kynareth"] = true,
    ["kyne's"] = true,
    ["lep"] = true,
    ["leyawiin"] = true,
    ["lilmoth"] = true,
    ["lorkhaj"] = true,
    ["lorkhan"] = true,
    ["m'kai"] = true,
    ["maarselok"] = true,
    ["malabal"] = true,
    ["malatar"] = true,
    ["marbruk"] = true,
    ["markarth"] = true,
    ["mazzatun"] = true,
    ["mehrunes"] = true,
    ["mephala"] = true,
    ["meridia"] = true,
    ["molag"] = true,
    ["moongrave"] = true,
    ["mournhold"] = true,
    ["mundus"] = true,
    ["murkmire"] = true,
    ["mythics"] = true,
    ["naj"] = true,
    ["naj-caldeesh"] = true,
    ["narsis"] = true,
    ["necrom"] = true,
    ["nightblade"] = true,
    ["nirn"] = true,
    ["nord"] = true,
    ["oathsworn"] = true,
    ["ophidia"] = true,
    ["orsinium"] = true,
    ["procs"] = true,
    ["psijic"] = true,
    ["pve"] = true,
    ["pvp"] = true,
    ["quickslot"] = true,
    ["quickslots"] = true,
    ["rawl'kha"] = true,
    ["redguard"] = true,
    ["riften"] = true,
    ["rimmen"] = true,
    ["rivenspire"] = true,
    ["rockgrove"] = true,
    ["runeforms"] = true,
    ["sanctorium"] = true,
    ["scalecaller"] = true,
    ["scrying"] = true,
    ["seclusa"] = true,
    ["senchal"] = true,
    ["shadowfen"] = true,
    ["sheogorath"] = true,
    ["shornhelm"] = true,
    ["sil"] = true,
    ["sithis"] = true,
    ["skingrad"] = true,
    ["skyrim"] = true,
    ["skyshard"] = true,
    ["skyshards"] = true,
    ["skywatch"] = true,
    ["sotha"] = true,
    ["spindleclutch"] = true,
    ["stendarr"] = true,
    ["stonefalls"] = true,
    ["stormhaven"] = true,
    ["stros"] = true,
    ["subclassing"] = true,
    ["summerset"] = true,
    ["sunnar"] = true,
    ["sunport"] = true,
    ["sunspire"] = true,
    ["tamriel"] = true,
    ["telvanni"] = true,
    ["vastyr"] = true,
    ["vateshran"] = true,
    ["vivec"] = true,
    ["volenfell"] = true,
    ["vulkhel"] = true,
    ["vvardenfell"] = true,
    ["wayrest"] = true,
    ["wayshrine"] = true,
    ["wayshrines"] = true,
    ["white-gold"] = true,
    ["windhelm"] = true,
    ["woodhearth"] = true,
    ["wrothgar"] = true,
    ["zenithar"] = true,
    ["aldcroft"] = true,
    ["arenthia"] = true,
    ["baandari"] = true,
    ["balmora"] = true,
    ["belkarth"] = true,
    ["camlorn"] = true,
    ["elinhir"] = true,
    ["firsthold"] = true,
    ["gideon"] = true,
    ["hallin's"] = true,
    ["kozanset"] = true,
    ["kragenmoor"] = true,
    ["lillandril"] = true,
    ["mistral"] = true,
    ["northpoint"] = true,
    ["hunding"] = true,
    ["silvenar"] = true,
    ["stormhold"] = true,
    ["tava's"] = true,
    ["velyn"] = true,
    ["arkthzand"] = true,
    ["eyevea"] = true,
    ["greymoor"] = true,
    ["y'ffelon"] = true,
    ["magickasteal"] = true,
    ["lifesteal"] = true,
    ["brittle"] = true,
    ["enervation"] = true,
    ["timidity"] = true,
    ["hemorrhaging"] = true,
    ["overcharged"] = true,
    ["sundered"] = true,
    ["concussed"] = true,
    ["nirnhoned"] = true,
    ["bloodthirsty"] = true,
    ["triune"] = true,
    ["prebuff"] = true,
    ["prebuffing"] = true,
    ["tel"] = true,
    ["ulfsild's"] = true,
    ["oakensoul"] = true,
    ["velothi"] = true,
    ["relequen"] = true,
    ["ansuul's"] = true,
}

-- Keep proper names from curated phrase categories spellcheckable even when the
-- English dictionary is disabled. This is intentionally limited to named/content
-- categories; conversational words from combat descriptions are not imported here.
local AUTO_TOKEN_CATEGORIES = {
    arenas_and_archives = true,
    base_dungeons = true,
    cities = true,
    classes = true,
    current_content = true,
    currencies_and_rewards = true,
    daedric_and_lore = true,
    dlc_dungeons = true,
    mundus_stones = true,
    named_characters = true,
    organizations = true,
    popular_passives_fallback = true,
    popular_sets_and_mythics = true,
    popular_skills_fallback = true,
    races = true,
    skill_lines_and_systems = true,
    systems_and_activities = true,
    trials = true,
    zones = true,
}

local AUTO_TOKEN_STOPWORDS = {
    ["a"] = true, ["an"] = true, ["and"] = true, ["as"] = true, ["at"] = true,
    ["by"] = true, ["for"] = true, ["from"] = true, ["in"] = true, ["into"] = true,
    ["of"] = true, ["on"] = true, ["or"] = true, ["the"] = true, ["to"] = true,
    ["with"] = true, ["without"] = true,
}

for category in pairs(AUTO_TOKEN_CATEGORIES) do
    for _, phrase in ipairs(E.phrases[category] or {}) do
        for token in phrase:gmatch("[A-Za-z][A-Za-z'%-]*") do
            local normalized = string.lower(token:gsub("’", "'"))
            if normalized ~= "" and not AUTO_TOKEN_STOPWORDS[normalized] then
                E.seedTokens[normalized] = true
                -- Hyphenated ESO names are useful both as their exact token and by
                -- component (Razum-dar -> razum-dar, razum, dar).
                if normalized:find("-", 1, true) then
                    for part in normalized:gmatch("[^%-]+") do
                        if part ~= "" and not AUTO_TOKEN_STOPWORDS[part] then
                            E.seedTokens[part] = true
                        end
                    end
                end
            end
        end
    end
end

-- Track which ESO subcategory owns each curated token. A token may belong to more
-- than one category; it remains enabled while any owning category is enabled. Manual
-- seed tokens that do not occur in a categorized phrase fall back to General ESO.
E.seedTokenSubcategories = {}
local function AddSeedTokenCategory(token, subcategory)
    token = string.lower(tostring(token or ""):gsub("’", "'"))
    if token == "" or AUTO_TOKEN_STOPWORDS[token] then return end
    local memberships = E.seedTokenSubcategories[token]
    if not memberships then memberships = {}; E.seedTokenSubcategories[token] = memberships end
    memberships[subcategory] = true
end

for phraseCategory, phrases in pairs(E.phrases or {}) do
    local subcategory = E.GetPhraseSubcategory(phraseCategory)
    for _, phrase in ipairs(phrases) do
        for token in phrase:gmatch("[A-Za-zÀ-ÖØ-öø-ÿ][A-Za-zÀ-ÖØ-öø-ÿ'’%-]*") do
            local normalized = string.lower(token:gsub("’", "'"))
            AddSeedTokenCategory(normalized, subcategory)
            if normalized:find("-", 1, true) then
                for part in normalized:gmatch("[^%-]+") do AddSeedTokenCategory(part, subcategory) end
            end
        end
    end
end

for token in pairs(E.seedTokens or {}) do
    if not E.seedTokenSubcategories[token] then
        E.seedTokenSubcategories[token] = { general = true }
    end
end

function E.IsStaticTokenEnabled(word)
    if not E.seedTokens or not E.seedTokens[word] then return false end
    local memberships = E.seedTokenSubcategories and E.seedTokenSubcategories[word]
    if not memberships then return E.IsSubcategoryEnabled("general") end
    for subcategory in pairs(memberships) do
        if E.IsSubcategoryEnabled(subcategory) then return true end
    end
    return false
end

function E.ForEachEnabledStaticToken(callback)
    if type(callback) ~= "function" then return end
    for word in pairs(E.seedTokens or {}) do
        if E.IsStaticTokenEnabled(word) then callback(word) end
    end
end

return E
