local R = Conductor.Registry

local skills = {
    -- Shared and weapon skills
    {"COMBAT_PRAYER","Combat Prayer","WEAPON_SKILL","RESTORATION_STAFF",{"MINOR_BERSERK","MINOR_RESOLVE"},{coverageType="DIRECTIONAL_CONE",classRestricted=false}},
    {"BLESSING_OF_PROTECTION","Blessing of Protection","WEAPON_SKILL","RESTORATION_STAFF",{"MINOR_RESOLVE"}},
    {"BLESSING_OF_RESTORATION","Blessing of Restoration","WEAPON_SKILL","RESTORATION_STAFF",{"MINOR_RESOLVE"}},
    {"ELEMENTAL_SUSCEPTIBILITY","Elemental Susceptibility","WEAPON_SKILL","DESTRUCTION_STAFF",{"MAJOR_BREACH","CHILLED","CONCUSSION","BURNING"}},
    {"WEAKNESS_TO_ELEMENTS","Weakness to Elements","WEAPON_SKILL","DESTRUCTION_STAFF",{"MAJOR_BREACH"}},
    {"ELEMENTAL_DRAIN","Elemental Drain","WEAPON_SKILL","DESTRUCTION_STAFF",{"MAJOR_BREACH","MINOR_MAGICKASTEAL"}},
    {"PIERCE_ARMOR","Pierce Armor","WEAPON_SKILL","ONE_HAND_AND_SHIELD",{"MAJOR_BREACH","MINOR_BREACH"}},
    {"PUNCTURE","Puncture","WEAPON_SKILL","ONE_HAND_AND_SHIELD",{"MAJOR_BREACH"}},
    {"RANSACK","Ransack","WEAPON_SKILL","ONE_HAND_AND_SHIELD",{"MAJOR_BREACH","MINOR_PROTECTION"}},
    {"HEROIC_SLASH","Heroic Slash","WEAPON_SKILL","ONE_HAND_AND_SHIELD",{"MINOR_MAIM","MINOR_HEROISM"}},
    {"LOW_SLASH","Low Slash","WEAPON_SKILL","ONE_HAND_AND_SHIELD",{"MINOR_MAIM"}},
    {"DEEP_SLASH","Deep Slash","WEAPON_SKILL","ONE_HAND_AND_SHIELD",{"MINOR_MAIM"}},
    {"MOMENTUM","Momentum","WEAPON_SKILL","TWO_HANDED",{"MAJOR_BRUTALITY","MAJOR_SORCERY"}},
    {"RALLY","Rally","WEAPON_SKILL","TWO_HANDED",{"MAJOR_BRUTALITY","MAJOR_SORCERY"}},
    {"FORWARD_MOMENTUM","Forward Momentum","WEAPON_SKILL","TWO_HANDED",{"MAJOR_BRUTALITY","MAJOR_SORCERY"}},
    {"DIZZYING_SWING","Dizzying Swing","WEAPON_SKILL","TWO_HANDED",{"OFF_BALANCE"}},
    {"HIDDEN_BLADE","Hidden Blade","WEAPON_SKILL","DUAL_WIELD",{"MAJOR_BRUTALITY","MAJOR_SORCERY"}},
    {"FLYING_BLADE","Flying Blade","WEAPON_SKILL","DUAL_WIELD",{"MAJOR_BRUTALITY","MAJOR_SORCERY"}},
    {"SHROUDED_DAGGERS","Shrouded Daggers","WEAPON_SKILL","DUAL_WIELD",{"MAJOR_BRUTALITY","MAJOR_SORCERY"}},
    {"BARBED_TRAP","Barbed Trap","GUILD_SKILL","FIGHTERS_GUILD",{"MINOR_FORCE"}},
    {"LIGHTWEIGHT_BEAST_TRAP","Lightweight Beast Trap","GUILD_SKILL","FIGHTERS_GUILD",{"MINOR_FORCE"}},
    {"ACCELERATE","Accelerate","GUILD_SKILL","PSIJIC_ORDER",{"MINOR_FORCE","MAJOR_EXPEDITION"}},
    {"CHANNELED_ACCELERATION","Channeled Acceleration","GUILD_SKILL","PSIJIC_ORDER",{"MINOR_FORCE","MAJOR_EXPEDITION"}},
    {"RACE_AGAINST_TIME","Race Against Time","GUILD_SKILL","PSIJIC_ORDER",{"MINOR_FORCE","MAJOR_EXPEDITION"}},
    {"INNER_LIGHT","Inner Light","GUILD_SKILL","MAGES_GUILD",{"MAJOR_PROPHECY","MAJOR_SAVAGERY"}},
    {"MAGELIGHT","Magelight","GUILD_SKILL","MAGES_GUILD",{"MAJOR_PROPHECY","MAJOR_SAVAGERY"}},
    {"RADIANT_MAGELIGHT","Radiant Magelight","GUILD_SKILL","MAGES_GUILD",{"MAJOR_PROPHECY","MAJOR_SAVAGERY"}},
    {"DEGENERATION","Degeneration","GUILD_SKILL","MAGES_GUILD",{"MAJOR_BRUTALITY","MAJOR_SORCERY"}},
    {"ENTROPY","Entropy","GUILD_SKILL","MAGES_GUILD",{"MAJOR_BRUTALITY","MAJOR_SORCERY"}},
    {"STRUCTURED_ENTROPY","Structured Entropy","GUILD_SKILL","MAGES_GUILD",{"MAJOR_BRUTALITY","MAJOR_SORCERY"}},
    {"CAMOUFLAGED_HUNTER","Camouflaged Hunter","GUILD_SKILL","FIGHTERS_GUILD",{"MAJOR_PROPHECY","MAJOR_SAVAGERY","MINOR_BERSERK"}},
    {"EXPERT_HUNTER","Expert Hunter","GUILD_SKILL","FIGHTERS_GUILD",{"MAJOR_PROPHECY","MAJOR_SAVAGERY"}},
    {"EVIL_HUNTER","Evil Hunter","GUILD_SKILL","FIGHTERS_GUILD",{"MAJOR_PROPHECY","MAJOR_SAVAGERY"}},
    {"ENERGY_ORB","Energy Orb","GUILD_SKILL","UNDAUNTED",{"RESOURCE_RESTORE","SYNERGY_PROVIDER"}},
    {"MYSTIC_ORB","Mystic Orb","GUILD_SKILL","UNDAUNTED",{"RESOURCE_RESTORE","SYNERGY_PROVIDER"}},
    {"NECROTIC_ORB","Necrotic Orb","GUILD_SKILL","UNDAUNTED",{"RESOURCE_RESTORE","SYNERGY_PROVIDER"}},
    {"SILVER_LEASH","Silver Leash","GUILD_SKILL","FIGHTERS_GUILD",{"PULL_STACK"}},
    {"PURGE","Purge","ALLIANCE_WAR_SKILL","SUPPORT",{"CLEANSE"}},
    {"EFFICIENT_PURGE","Efficient Purge","ALLIANCE_WAR_SKILL","SUPPORT",{"CLEANSE"}},
    {"CLEANSE_SKILL","Cleanse","ALLIANCE_WAR_SKILL","SUPPORT",{"CLEANSE"}},
    {"RAPID_MANEUVER","Rapid Maneuver","ALLIANCE_WAR_SKILL","ASSAULT",{"MAJOR_EXPEDITION"}},
    {"CHARGING_MANEUVER","Charging Maneuver","ALLIANCE_WAR_SKILL","ASSAULT",{"MAJOR_EXPEDITION","MINOR_EXPEDITION"}},
    {"RETREATING_MANEUVER","Retreating Maneuver","ALLIANCE_WAR_SKILL","ASSAULT",{"MAJOR_EXPEDITION"}},
    {"RAZOR_CALTROPS","Razor Caltrops","ALLIANCE_WAR_SKILL","ASSAULT",{"MAJOR_BREACH"}},

    -- Class skills
    {"ARCANISTS_DOMAIN","Arcanist's Domain","CLASS_SKILL","ARCANIST",{"MINOR_COURAGE","MINOR_INTELLECT","MINOR_ENDURANCE","MINOR_FORTITUDE"},{skillLine="SOLDIER_OF_APOCRYPHA",subclassCompatible=true}},
    {"ZENAS_EMPOWERING_DISC","Zenas' Empowering Disc","CLASS_SKILL","ARCANIST",{"MINOR_COURAGE","MINOR_INTELLECT","MINOR_ENDURANCE","MINOR_FORTITUDE"},{subclassCompatible=true}},
    {"RECONSTRUCTIVE_DOMAIN","Reconstructive Domain","CLASS_SKILL","ARCANIST",{"MINOR_COURAGE","MINOR_INTELLECT","MINOR_ENDURANCE","MINOR_FORTITUDE"},{subclassCompatible=true}},
    {"RUNE_OF_THE_COLORLESS_POOL","Rune of the Colorless Pool","CLASS_SKILL","ARCANIST",{"MINOR_VULNERABILITY"},{subclassCompatible=true}},
    {"RUNE_GUARD_OF_FREEDOM","Runeguard of Freedom","CLASS_SKILL","ARCANIST",{"MINOR_PROTECTION"},{subclassCompatible=true}},
    {"RUNIC_DEFENSE","Runic Defense","CLASS_SKILL","ARCANIST",{"MINOR_PROTECTION"},{subclassCompatible=true}},
    {"IGNEOUS_WEAPONS","Igneous Weapons","CLASS_SKILL","DRAGONKNIGHT",{"MAJOR_BRUTALITY","MAJOR_SORCERY"},{subclassCompatible=true}},
    {"MOLTEN_WEAPONS","Molten Weapons","CLASS_SKILL","DRAGONKNIGHT",{"MAJOR_BRUTALITY","MAJOR_SORCERY"},{subclassCompatible=true}},
    {"MOLTEN_ARMAMENTS","Molten Armaments","CLASS_SKILL","DRAGONKNIGHT",{"MAJOR_BRUTALITY","MAJOR_SORCERY"},{subclassCompatible=true}},
    {"NOXIOUS_BREATH","Noxious Breath","CLASS_SKILL","DRAGONKNIGHT",{"MAJOR_BREACH"},{subclassCompatible=true}},
    {"CHOKING_TALONS","Choking Talons","CLASS_SKILL","DRAGONKNIGHT",{"MINOR_MAIM","CROWD_CONTROL"},{subclassCompatible=true}},
    {"FIERY_GRIP","Fiery Grip","CLASS_SKILL","DRAGONKNIGHT",{"PULL_STACK"},{subclassCompatible=true}},
    {"UNRELENTING_GRIP","Unrelenting Grip","CLASS_SKILL","DRAGONKNIGHT",{"PULL_STACK"},{subclassCompatible=true}},
    {"FETCHER_INFECTION","Fetcher Infection","CLASS_SKILL","WARDEN",{"MINOR_VULNERABILITY"},{skillLine="ANIMAL_COMPANIONS",subclassCompatible=true}},
    {"GROWING_SWARM","Growing Swarm","CLASS_SKILL","WARDEN",{"MINOR_VULNERABILITY"},{skillLine="ANIMAL_COMPANIONS",subclassCompatible=true}},
    {"DEEP_FISSURE","Deep Fissure","CLASS_SKILL","WARDEN",{"MAJOR_BREACH","MINOR_BREACH"},{subclassCompatible=true}},
    {"SUBTERRANEAN_ASSAULT","Subterranean Assault","CLASS_SKILL","WARDEN",{"MAJOR_BREACH","MINOR_BREACH"},{subclassCompatible=true}},
    {"FROST_CLOAK","Frost Cloak","CLASS_SKILL","WARDEN",{"MAJOR_RESOLVE"},{skillLine="WINTERS_EMBRACE",subclassCompatible=true}},
    {"EXPANSIVE_FROST_CLOAK","Expansive Frost Cloak","CLASS_SKILL","WARDEN",{"MAJOR_RESOLVE"},{skillLine="WINTERS_EMBRACE",subclassCompatible=true,coverageType="GROUP_AREA"}},
    {"ICE_FORTRESS","Ice Fortress","CLASS_SKILL","WARDEN",{"MAJOR_RESOLVE","MINOR_PROTECTION"},{subclassCompatible=true}},
    {"ENCHANTED_GROWTH","Enchanted Growth","CLASS_SKILL","WARDEN",{"MINOR_INTELLECT","MINOR_ENDURANCE"},{subclassCompatible=true}},
    {"CORRUPTING_POLLEN","Corrupting Pollen","CLASS_SKILL","WARDEN",{"MAJOR_DEFILE"},{subclassCompatible=true}},
    {"FROZEN_DEVICE","Frozen Device","CLASS_SKILL","WARDEN",{"MAJOR_MAIM","PULL_STACK"},{subclassCompatible=true}},
    {"BLUE_BETTY","Blue Betty","CLASS_SKILL","WARDEN",{"MAJOR_BRUTALITY","MAJOR_SORCERY","CLEANSE"},{subclassCompatible=true}},
    {"BULL_NETCH","Bull Netch","CLASS_SKILL","WARDEN",{"MAJOR_BRUTALITY","MAJOR_SORCERY","CLEANSE"},{subclassCompatible=true}},
    {"POWER_OF_THE_LIGHT","Power of the Light","CLASS_SKILL","TEMPLAR",{"MINOR_BREACH"},{subclassCompatible=true}},
    {"DARK_FLARE","Dark Flare","CLASS_SKILL","TEMPLAR",{"MAJOR_DEFILE"},{subclassCompatible=true}},
    {"RADIANT_AURA","Radiant Aura","CLASS_SKILL","TEMPLAR",{"MINOR_ENDURANCE","MINOR_INTELLECT","MINOR_FORTITUDE","MINOR_MAGICKASTEAL"},{subclassCompatible=true}},
    {"RESTORING_AURA","Restoring Aura","CLASS_SKILL","TEMPLAR",{"MINOR_ENDURANCE","MINOR_INTELLECT","MINOR_FORTITUDE"},{subclassCompatible=true}},
    {"CLEANSING_RITUAL","Cleansing Ritual","CLASS_SKILL","TEMPLAR",{"CLEANSE"},{subclassCompatible=true}},
    {"EXTENDED_RITUAL","Extended Ritual","CLASS_SKILL","TEMPLAR",{"CLEANSE"},{subclassCompatible=true}},
    {"RITUAL_OF_RETRIBUTION","Ritual of Retribution","CLASS_SKILL","TEMPLAR",{"CLEANSE"},{subclassCompatible=true}},
    {"RUNE_FOCUS","Rune Focus","CLASS_SKILL","TEMPLAR",{"MAJOR_RESOLVE"},{subclassCompatible=true}},
    {"LOTUS_FAN","Lotus Fan","CLASS_SKILL","NIGHTBLADE",{"MINOR_VULNERABILITY"},{subclassCompatible=true}},
    {"TELEPORT_STRIKE","Teleport Strike","CLASS_SKILL","NIGHTBLADE",{"MINOR_VULNERABILITY"},{subclassCompatible=true}},
    {"POWER_EXTRACTION","Power Extraction","CLASS_SKILL","NIGHTBLADE",{"MAJOR_BRUTALITY","MAJOR_SORCERY","MINOR_COWARDICE"},{subclassCompatible=true}},
    {"REAPERS_MARK","Reaper's Mark","CLASS_SKILL","NIGHTBLADE",{"MAJOR_BREACH"},{subclassCompatible=true}},
    {"MARK_TARGET","Mark Target","CLASS_SKILL","NIGHTBLADE",{"MAJOR_BREACH"},{subclassCompatible=true}},
    {"PIERCING_MARK","Piercing Mark","CLASS_SKILL","NIGHTBLADE",{"MAJOR_BREACH"},{subclassCompatible=true}},
    {"DARK_CLOAK","Dark Cloak","CLASS_SKILL","NIGHTBLADE",{"MINOR_PROTECTION"},{subclassCompatible=true}},
    {"MIRAGE","Mirage","CLASS_SKILL","NIGHTBLADE",{"MINOR_RESOLVE"},{subclassCompatible=true}},
    {"BOUNDLESS_STORM","Boundless Storm","CLASS_SKILL","SORCERER",{"MAJOR_RESOLVE","MAJOR_EXPEDITION"},{subclassCompatible=true}},
    {"HURRICANE","Hurricane","CLASS_SKILL","SORCERER",{"MAJOR_RESOLVE","MINOR_EXPEDITION"},{subclassCompatible=true}},
    {"LIGHTNING_FORM","Lightning Form","CLASS_SKILL","SORCERER",{"MAJOR_RESOLVE"},{subclassCompatible=true}},
    {"RESTRAINING_PRISON","Restraining Prison","CLASS_SKILL","SORCERER",{"MAJOR_VITALITY","CROWD_CONTROL"},{subclassCompatible=true}},
    {"UNNERVING_BONEYARD","Unnerving Boneyard","CLASS_SKILL","NECROMANCER",{"MAJOR_BREACH"},{subclassCompatible=true}},
    {"AGONY_TOTEM","Agony Totem","CLASS_SKILL","NECROMANCER",{"MINOR_PROTECTION","SYNERGY_PROVIDER"},{subclassCompatible=true}},
    {"REMOTE_TOTEM","Remote Totem","CLASS_SKILL","NECROMANCER",{"MINOR_PROTECTION"},{subclassCompatible=true}},
    {"NECROTIC_POTENCY","Necrotic Potency","CLASS_SKILL","NECROMANCER",{"ULTIMATE_RESTORE"},{subclassCompatible=true}},
    {"BITTER_HARVEST","Bitter Harvest","CLASS_SKILL","NECROMANCER",{"ULTIMATE_RESTORE"},{subclassCompatible=true}},
    {"BECKONING_ARMOR","Beckoning Armor","CLASS_SKILL","NECROMANCER",{"MAJOR_RESOLVE","PULL_STACK"},{subclassCompatible=true}},
}

for _, entry in ipairs(skills) do
    local data = {name=entry[2],sourceType=entry[3],sourceGroup=entry[4],provides=entry[5],abilityIds={},needsIdValidation=true}
    for key, value in pairs(entry[6] or {}) do data[key] = value end
    R:Register("SKILLS", entry[1], data)
end
