GoblinSayings = {
    "I smash things! Snrk! Big thing coming!",
    "I gonna blow this up! Blargh! Wait for it!",
    "Kekeke, look out! Something's big comin’ your way!",
    "Big boom time! Gronk!",
    "Boom boom, watch out! Squish!",
    "Let’s break it! Squee!",
    "Watch the explosions! Zog zog!",
    "Pbbbt! Time to drop it!",
    "Ready for boom! Blargh!",
    "Boom time! Gahhh!",
    "Let me show you how it’s done! Plop!",
    "Boom! Boom! Boom! Zzzzt!",
    "Plop, ready to smash the big guy!",
    "Time for a surprise! Brap!",
    "Flarp, things gonna get messy!",
    "Bigger explosions? Sure, I got them! Squish!",
    "Zzt! This gonna be big!",
    "Boom! Let’s go! Bwahaha!",
    "Zorp! Time for a surprise!",
    "Time for more booms! Squee!",
    "Time for the big guns! Zorp!",
    "I’m quick and sneaky! Glorp!",
    "I’ll sneak up and then Plop! Surprise!",
    "I’m tiny, but I pack a punch! Gulp!",
    "Gribbit, they never expect a goblin, do they?",
    "Can’t catch me! Bwahaha!",
    "I’m faster than you! Glorp!",
    "I’m too fast! Eep eep!",
    "Wait for it... Boom!",
    "More traps! More explosions! Flop!",
    "I’m sneaky and quick! Brap!",
    "Look out, I’m bringing the pain! Brap!",
    "Sneaky goblin, watch out! Zorp!",
    "I’m on fire today! Bwahaha!",
    "Boom time! Gahhh!",
    "Fizzz, I’m always ready to make things go boom!",
    "Surprise! Yoink! You’re too slow!",
    "Let’s do this! Meep, boom!",
    "Let’s break ‘em! Snrk!",
    "Hehe, I heard the big one’s got a shiny treasure! Glorp!",
    "Eep, do you see it? Do you? It's shiny!",
    "Who’s ready for a goblin surprise? Snrk!",
    "Gribbit, that wasn’t big enough! Let’s do it again!",
    "Plop, let me at ‘em! I’m ready to bash!",
    "Zorp, ooooh, shiny! It’s mine now!",
    "Narf, I can smell treasure! Can you smell it?",
    "Me likes shiny things, yes-yes! Bwahaha!",
    "I’ll take all their shiny things! Squee!",
    "Here comes the big one! Thwack!",
    "Bwahaha, boom goes the goblin!",
    "Big monster? Gribbit, I’ll make it fall!",
    "Gronk, get ready for an explosion of fun!",
    "Squish, we’re making this harder for them!",
    "Flarp, I’m gonna make them regret poking this goblin!",
    "Zorp, let me at ‘em! BOOM!",
    "I hit harder than a giant! Thwack!",
    "Squee, don’t underestimate me!",
    "I’ll show you chaos! Bwahaha!",
    "Surprise! Bwahaha!",
    "Ready for fun? Fizzz!",
    "Let’s cause some trouble! Squee!",
    "Everything’s going down! Flop!",
    "Watch out! Gahhh!",
    "Get ready! Thwack!",
    "Boom, right in your face! Thwack!",
    "Big hit coming! Gribbit!",
    "Zzt! I’m ready for this!",
    "Smash ‘em all! Meep!",
    "More booms, more fun! Flarp!",
    "I’m gonna wreck it! Honk!",
    "I’ll take care of this, just you wait! Yoink!",
    "Squee, you don’t run from me, you fight or you fall!",
    "Stay close, I got a plan... maybe. Burp!",
    "Plop, let me show you my best tricks!",
    "Gahhh, let’s make it bigger, badder!",
    "Zzzzt, that’s gonna leave a mark! Hehe!",
    "Let’s make it happen! Bwahaha!",
    "You won’t see me coming! Flop!",
    "I got the best traps! Skrreee, just wait and see!",
    "I’m just warming up! Zorp!",
    "Zog zog, watch out, I’m bringing the pain!",
    "Brap, that’s the goblin way'smash, run, repeat!",
    "Flop, here we go again! More explosions!",
    "I think they’re mad, but they should be scared! Bork!",
    "Let’s make ‘em scream! Plop!",
    "I can outsmart ‘em! Bwahaha!"
}
