GoblinTrialSayings = {
    [1121] = { -- SS
		"Cat gods scream too loud, blegh!", "Z'Maja not here? Cat boss weaker, snrk.", "Goblin throw snowball at Yolnahkriin! Pbbbt!",
		"Big lizard fly. Goblin no like! Zog zog!", "Flame cat smell like BBQ, urk!", "Goblin want pet Nahviintaas, whee!",
		"Goblin no scared of dragons... okay maybe little, gahhh.", "Khajiit gods? Pfft, goblin god better, grr!",
		"Zog zog! Too much fire breath, splurt!", "Goblin slip on ice, bonk! Oof!", "Yolnahkriin make goblin crispy, hurrr!",
		"Big cat yell too much, ears go blargh!", "Snow dragon cold butt, goblin no like, brr!", "Flap flap, go away, big lizard, vroom!",
		"Pbbbt! Nahviintaas always vanish, squish!", "Snrk! Goblin no cook dragon egg, promise, blegh!", "Fwoosh! Goblin eyebrows gone, bleh!",
		"Raar! Kaalgrontiid cousin? Vroom!", "Blegh, dragon drool nasty, gurgle!", "Meh, goblin stronger than sun cat, skrrt!",
		"Gyaa! Sky on fire, sky on fire, eep!", "Skrrt! Goblin dodge tail swipe, squish!", "Urk! Flame breath smell like burnt cheese, urrg!",
		"Bwahaha, dragon dance funny, gronk!", "Goblin try ride Lokkestiiz, now goblin pancake, whoomp.", "Thwack! Goblin smack cat nose, zap!",
		"Reeek! Ice breath give goblin sneeze, achoo!", "Glorp! Goblin stuck in snow bank, zoink!", "Gloop! Yolnahkriin belly flop, blop!",
		"Squee! Nahviintaas scream too loud, grr!", "Whee! Goblin go flying, boing!", "Gribbit! Khajiit priest yell too much, chirp!",
		"Gahhh, big wings scary, zoop!", "Goblin want roast lizard for dinner, flap!", "Zizzle! Big flame hurt goblin feet!",
		"Goblin tired of cold, needs fire, whap!", "Gurgle! That dragon’s spit is gross!", "Chomp! Goblin bit the wrong thing, oops.",
		"Goblin go squish with snow dragon tail, squishity!", "Flop! Goblin no fly like big lizard, snrk!", "Yarp! Z'Maja no like goblin's jokes!",
		"Bork! This cat’s claws too sharp!", "Glorp, goblin stuck in the ice again!", "Plop! Goblin fall down! Oof!",
		"Honk! Nahviintaas too fast!", "Boing! Goblin hop over ice, squee!", "Fizzz! Fire dragons hurt goblin face, wooo!",
		"Gahh! Too much flame! Meh.", "Blep! Cat god make goblin sleepy!", "Yikesss! Ice breath too cold for goblin!",
		"Rarr! Goblin eat dragon tail for snack!", "Pop-pop! Big lizard smashes goblin, oops!", "Squawk! Snow dragon goes skitter!",
		"Thump! Goblin hit by big tail, blegh!", "Pop! Who needs the cat gods, huh? Gahhh!", "Whizz! Cat gods too busy, too loud!",
		"Squeak! Nahviintaas not listen, zap zap!", "Bloop! Dragon breath freeze goblin paws!", "Zoink! Get off me, big dragon!",
		"Gloop! Goblin trap in snow, help!", "Ssskkrrt! Fire on goblin’s behind, wheee!", "Clomp! Goblin march with dragon feet, meep!",
		"Plunk! Z'Maja too sneaky, grr!", "Eep! Goblin jump outta the way, crash!", "Womph! That dragon's breath burns, yikes!",
		"Fwoosh! Big tail hit goblin like squish!", "Honk! Too much smoke, can't see!", "Zzzzzt! Goblin needs ice cure!",
		"Blech! Cat gods make goblin feel dizzy, snort!", "Bloop! Goblin can't stop sliding on ice!", "Chomp! Goblin bite too much ice, gahhh!",
		"Vroom! Big dragon chase goblin, vwoosh!", "Gurgle! Fire smells bad! Goblin no like!", "Flop! Big claws trap goblin, plop!",
		"Flarp! Ice cold feet, squish!", "Thwack! Dragon’s wings hurt goblin head!", "Clunk! Z'Maja gone, goblin chase!",
		"Bwahaha, fire breath too easy to dodge!", "Hoo-hoo! Goblin love dragon meat, squish!", "Squish! Cold ice no good for goblin skin!",
		"Blegh! Goblin want hot lava bath instead!", "Flop! Goblin hit by dragon tail, squish!", "Borf! Sunspire too hot for goblin!",
		"Kekeke! Big lizard try to catch goblin!", "Boom! Big dragon roar shake goblin, ow!", "Honk! Fire everywhere, meep!"
	},
	[1478] = { -- LC
		"Shiny floor make goblin slip, zoink!", "Big glowy lights hurt goblin eyes, squint!", "Goblin no like these bright walls, gahh!",
		"Ooooh, spooky light everywhere! Blip!", "Why all this light? Goblin need shade, grr!", "Luminous fire hurt goblin’s nose, eep!",
		"Flop! Too much glow, goblin go blind, zzzzt!", "Skreee! Magic hurt goblin feet!", "Goblin punch the light thing, squish!",
		"Yikesss! That glow burn goblin skin, bork!", "Honk! Too bright! Can’t see!", "Pbbbt! Luminous things all over the place!",
		"Gahhh! Goblin not used to all this light, flarp!", "Rarr! Spinning lights make goblin dizzy, squish!", "Blergh! Magic everywhere, eeep!",
		"Glorp! Goblin stomp on magic crystal, plop!", "Squee! Goblin not like glowing cubes!", "Flap! That orb went boom! Zog zog!",
		"Zoop! Goblin smashed by light wall, whoomp!", "Eep! Goblin trapped in shiny barrier!", "Thwack! Too much magic, squish!",
		"Whee! Goblin go flying from big light explosion, blegh!", "Gribble! Bright thing coming at me!", "Goblin eat light orb, snrk!",
		"Squawk! More light? Goblin blind, gahhh!", "Splat! Too much sparkles, goblin go splurt!", "Vroom! Goblin’s feet go zap-zap!",
		"Thump! Goblin hit wall of shiny, gahhh!", "Plop! Shiny floor too slippery, squish!", "Gurgle! Light hurts goblin head, gah!",
		"Bleep! Magic cube go boom, grrr!", "Bork! Goblin not like all this glowing stuff!", "Chomp! Big orb, goblin nibble!",
		"Gahh! Goblin stuck in glow! Help!", "Squish! Too many lights! ZZZZZZT!", "Clunk! Goblin hit shiny wall again, splurt!",
		"Gloop! Magic traps everywhere, bleh!", "Zzzzt! Too many floating crystals!", "Meh, goblin no care for glowing things!",
		"Goblin squish with light blast, pbbbt!", "Grggh! Lights make goblin grumpy!", "Flap! This place too bright for goblin eyes!",
		"Gah! Big orb zap goblin! Whoomp!", "Wobble! Goblin fall into light pit!", "Thwack! Goblin smack into magic wall!",
		"Snrk! Goblin no like sparkly places!", "Bloop! That light zap goblin’s tail!", "Grrr, too much magic in the air!",
		"Squee! Goblin got zapped by shiny orb!", "Fwoosh! Lights too hot for goblin skin, meep!", "Kekeke! Goblin love smashing lights!",
		"Eep! Lights spin too fast for goblin!", "Whap! Goblin caught in magical snare, blegh!", "Meow! That magic orb make goblin hiss!",
		"Zorg! Goblin need nap after all this magic, squish!", "Gurgle! Bright lights everywhere, ow!", "Grunt! Too many sparkles!",
		"Goblin throw rock at shiny orb, squish!", "Yarp! Goblin no like shiny magic walls!", "Gahh! That thing go zap, squish!",
		"Gloop! Goblin just swallowed glowing crystal, whoomp!", "Flap! Goblin dodge another zap!", "Whew! Goblin barely dodge that one, eep!",
		"Bloop! Too many shiny things, goblin tired!", "Chomp! Aha! Goblin eat glowing rock, squish!", "Yikesss! Magic hurts goblin feet!",
		"Squeak! That thing spinning, bleh!", "Gaaah! Goblin trip on glowing floor!", "Zog zog! Goblin hate shiny walls!",
		"Gloop! Too much light make goblin dizzy!", "Pbbbt! Goblin need sunglasses for all this light!", "Plunk! Goblin smack into magic barrier!",
		"Rarr! Goblin punch that crystal, squish!", "Blip! Too much glow, goblin no like!", "Bwahaha! Goblin break crystal for fun!",
		"Yarp! Too much sparkle, ugh!", "Gribble! That orb did not like goblin’s bite!", "Clomp! Goblin foot stuck in magic trap!",
		"Bork! Goblin fall in shiny pit!", "Vroom! Big shiny thing chase goblin, squish!", "Pop! Goblin make explosion with light crystal!",
		"Bleeep! Shiny stuff burn goblin's face!", "Squish! Goblin get hit by magic blast!", "Zoink! Goblin throw rock at the orb!",
		"Vrrr! Too many spinning lights, blegh!", "Bork! Goblin need a break from the lights!", "Grunk! Magic crystal hurt goblin hands!",
		"Zzzzt! Magic trap zap goblin tail!", "Eep! That big orb makes me go squish!", "Honk! Goblin just broke a magic wall!",
		"Squawk! Too much light! I can’t see!", "Bloop! Goblin blinded by glowing thing!", "Pop! Shiny stuff everywhere, eep!",
		"Gahhh! That thing go boom! Hurts goblin!", "Wobble! Goblin tripped on glow-floors!", "Florp! Magic cubes make goblin dizzy!",
		"Snrk! More lights? Goblin no like!", "Zog zog! Goblin get zap! Too bright!", "Vwoosh! Magic makes goblin go skitter!",
		"Wham! Goblin crush magic orb!", "Gurgle! Too much sparkle, goblin head hurt!", "Chomp! Magic tastes weird, blegh!",
		"Squee! Goblin smash shiny orb, whee!", "Flap! Goblin no like glowing crystals!", "Boom! Another orb explosion, ouch!",
		"Honk! Too many glowing things, bork!", "Eep! Goblin caught in shiny trap again!", "Bork! Magic blast hits goblin face, squish!"
	},
	[1196] = { -- KA
		"Big bear smash goblin! Too cold, brrr!", "Rarr! Stormbeast hurt goblin’s face!", "Flop! Frost hurt goblin’s paws, bleh!",
		"Whee! Kyne’s storm blow goblin away, squish!", "Zog zog! That frost beast roar too loud, eep!", "Bork! Giant ice monster, no thanks!",
		"Grgnk! Goblin slip on icy floor, meep!", "Gahhh! That big beast stomp hurt! Hurrr!", "Brrr! Too much cold, goblin shiver!",
		"Plop! Big ice storm everywhere, yikesss!", "Snrk! Stormbeasts all around, no good!", "Honk! Goblin fight big beast? Eep!",
		"Bwahaha! Goblin outrun frost beast, vroom!", "Skrrt! Kyne’s storm freeze goblin’s feet, gah!", "Yarp! Big monster try to squish goblin!",
		"Pop! Goblin caught in Kyne’s icy trap, plunk!", "Chomp! That frost beast bite hurt, bleh!", "Meep! Ice storm hurt goblin face!",
		"Yikesss! Too many beasts, goblin run faster!", "Squee! Storm’s so loud, goblin can’t hear!", "Flap! Ice monster punch goblin’s head!",
		"Squawk! Snowstorm too strong, goblin spin!", "Zorg! Big ice monster smash goblin, squish!", "Rarr! That big bear throw goblin far!",
		"Glorp! Goblin slip on icy floor, gahh!", "Blegh! Too much cold! Goblin freeze!", "Whap! Storm beast hit goblin again, gah!",
		"Fwoosh! Kyne’s wrath freeze goblin solid!", "Squish! Ice beast throw goblin in snow!", "Honk! Storm beast bite goblin’s tail, urk!",
		"Grrr! Big bear want to crush goblin, bleh!", "Blergh! Too much ice everywhere, eeep!", "Yarp! Kyne’s storm blow goblin away, vroom!",
		"Bork! Ice storm so loud, goblin can’t hear!", "Snrk! That frost beast charge goblin!", "Wobble! Goblin slide on ice, squish!",
		"Pop! Too much snow, goblin can’t see!", "Flap! Kyne’s storm make goblin dizzy!", "Eep! Big bear want goblin for lunch!",
		"Gurgle! Big storm freeze goblin’s feet!", "Sniff! Too cold! Goblin no like!", "Squishity! That ice beast bite hurt!",
		"Meep! Goblin trapped in snowstorm, gahhh!", "Vroom! Goblin too fast for ice beast, squish!", "Rarr! That frost beast bite too hard!",
		"Yikesss! Storm beast hurt goblin's tail!", "Thwack! Goblin get hit by ice storm, blegh!", "Grgrg! Too many monsters! Goblin can’t run!",
		"Bwahaha! Goblin dodge the frost, grr!", "Wobble! Snowstorm too much for goblin, yikesss!", "Pop! Frost hurt goblin’s ears, squish!",
		"Flop! Goblin slip, storm beast get me!", "Bork! Goblin no want bear to squish me!", "Snrk! Kyne’s storm makes goblin fall!",
		"Gribble! Ice everywhere, goblin no like!", "Vibbb! Goblin run away from ice monster!", "Gahhh! That bear break goblin’s bone!",
		"Whoomp! Big monster throw goblin, gahh!", "Meow! That big bear hit goblin’s paw, bleh!", "Honk! Snowstorm too loud for goblin!",
		"Pop-pop! Goblin hit by ice storm, squish!", "Pbbbt! Too much snow, goblin fall down!", "Chomp! Frost beast eat goblin’s lunch!",
		"Flap! Ice storm everywhere, grr!", "Zorg! Goblin running from big beast, bork!", "Whee! Goblin slide on ice like slippery!",
		"Guffaw! Goblin too fast for giant bear!", "Screech! Kyne’s wrath freeze goblin’s bones!", "Vwoosh! Ice beast chasing goblin!",
		"Plop! Big ice bear stomp on goblin’s tail!", "Gurgle! Goblin no want to fight stormbeast!", "Fwooosh! That frost beast bite hurt!",
		"Squishity! Goblin trapped in snowstorm!", "Fwoosh! Ice storm hurt goblin’s face, gah!", "Zoink! Goblin dodge frost, yarp!",
		"Rarr! Ice monsters are everywhere, bork!", "Chomp! That ice beast bite too hard, grr!", "Bork! Goblin hide from Kyne’s wrath!",
		"Gahh! That storm beast stomped goblin, blegh!", "Whoomp! Big frost bear chase goblin!", "Whee! Goblin fall, snow too slippery!",
		"Flap! Goblin knocked by stormbeast, grr!", "Grrr! Snowstorm freeze goblin’s ears, squish!", "Plunk! Too many ice bears, eep!",
		"Squawk! Goblin get trapped in Kyne’s snowstorm!", "Vibbb! Ice storm everywhere, gahhh!", "Bwahaha! Goblin outrun big monster!"
	},
    [1263] = { -- RG
		"Argonian make funny noises!", "Too much lava, gobbo boots melt!", "Big toad scary, goblin run!",
		"Xalvakka no fun. Too much zap!", "Tideborn Taleria? Goblin prefer fish stew!", "Why fire everywhere?!",
		"Goblin got burned butt in Oaxiltso fight!", "Lizards angry! Why always angry?!", "snrk! Goblin trip on tail!",
		"blargh, too hot for goblin skin!", "gyaa! Toad try eat goblin!", "Tideborn look like overgrown fish, hurrr!",
		"blegh, swamp water taste bad!", "reeek! Goblin nose burn!", "nyah, lava not soup!", "Xalvakka scream too much!",
		"urk... goblin dizzy from portal!", "glorp, fishy boss too slippery!", "meep! Goblin no like giant lizard eyes!",
		"gronk! Oaxiltso breath stink!", "eep eep! Fire spirit chase goblin!", "squish... that not healing!",
		"honk honk! Goblin warning call!", "zog zog, why water on fire?!", "pbbbt, goblin fart scare tadpole!",
		"gahhh! Volcano angry again!", "eep! Goblin tail got singed!", "brap! Rockgrove make gobbo jump!",
		"yarp! Tideborn too splashy!", "bonk! Goblin head meet tail swipe!", "flarp, too much jumping!",
		"squee! Goblin squished by tail!", "bwahaha! Goblin ride lava wave!", "narf! Boss talk too much!",
		"plop... goblin fell in lava again!", "gribbit, that not goblin noise!", "mlem, not taste like fish!",
		"gloop! Xalvakka full of slime!", "splurt, lava not drinkable!", "burp, goblin eat wrong bug!",
		"yikesss! Fire rock fall near gobbo!", "fizzz... tail smoking again!", "skrreee! Goblin panic dance!",
		"eep-o! Toad jump too far!", "gah, goblin hate Argonian ruins!", "chomp! Goblin bite back!",
		"bork bork, goblin bark of fear!", "rawr! Goblin pretend to be boss!", "flop... goblin faint from heat!",
		"yoink! Goblin steal boss tooth!", "crunch... not candy rock!", "thwack! Goblin hit own foot!",
		"gulp, goblin not ready!", "zorp! Magic water hit goblin!", "grrr, goblin angry now!",
		"kronk! Toad bounce like drum!", "vroom! Goblin speed-run lava!", "boing boing, jump puzzle pain!",
		"zizzle... boss zap goblin hair!", "woohoo! Goblin did mechanic right!", "grrroar! Boss louder than gobbo!",
		"whap! Goblin slapped by tail!", "squawk! Goblin call for help!", "zoink! That was goblin soul!",
		"whizz... portal too fast!", "ka-boom! Goblin no like fireball!", "bloop... lava swallowed gobbo!",
		"blip! Goblin gone poof!", "screech! Too many adds!", "clomp! Goblin boot stuck in mud!",
		"chitter chitter, gobbo scared!", "whee! Lava slide fun till burn!", "vibb... goblin vibrate from zap!",
		"rarr! Toad roar bigger than goblin!", "pop! Goblin nearly explode!", "gurgle... fire potion taste bad!",
		"smack! Goblin whacked tail again!", "slurp... not healing pool?!", "vrrr... goblin spin in panic!",
		"sizzle... tail never grow back!", "plunk! Goblin fell off again!", "wham! Rock to face hurts!",
		"bleep! Wrong button again!", "guffaw! Goblin laugh at own death!", "sniff... lava smell like failure!",
		"wobble! Goblin barely alive!", "skid! Goblin can't stop runnin'!", "fwoosh! Fire too friendly!",
		"shlurp... goblin stuck in goo!", "squishity! Goblin got sat on!", "biff! Goblin try headbutt boss!",
		"tshh! Xalvakka too sparkly!", "caw! Bird thing scary!", "gribble... goblin lost again!",
		"blurp... don't drink from fountain!", "thump! Goblin failed roll dodge!", "roar! Goblin try intimidate boss!",
		"fizz... magic make goblin tingle!", "squiggle! Goblin can't aim!", "boomp! Goblin press wrong rune!",
		"bub... goblin blow bubble under lava!", "meow? What goblin say?", "womp! Big tail hit goblin hard!",
		"twang! Goblin launch self!", "flibber... goblin flail wildly!"
	},
	[1051] = { -- CR
		"Sky is so pretty! But goblin no fly! Meep!",
		"Clouds so fluffy, goblin get lost in them! Urk!",
		"Azurah's light shine bright! Too bright for goblin eyes!",
		"Big sky dragon come! Goblin run away! Gahhh!",
		"Watch out for light! Goblin get zapped, squish!",
		"Too much light! Me not like it! Blargh!",
		"Me think Azurah is too shiny. Blegh!",
		"Zzzap! Lightning hurt goblin head! Zzzt!",
		"Big bird in sky? Goblin make it fall! Thwack!",
		"Light burn goblin! Why no cloud? Grrrr!",
		"What that sound? Sky shake like thunder! Plop!",
		"Gah! No more lightning! Hurrr!",
		"Clouds go boom! Goblin no like thunder! Zorrrp!",
		"Thunder’s loud! Goblin hide in hole! Squish!",
		"Sky, so bright! Goblin can’t see! Hooomph!",
		"I see pretty light! Goblin go zooooop!",
		"Clouds dance in sky, goblin dizzy! Whee!",
		"That thunder sounds like big goblin fight! Bwahaha!",
		"Azurah smile down on goblin, but goblin still small!",
		"Goblin’s favorite cloud is the one not zapping!",
		"More clouds, more goblin fun! Squishity!",
		"Goblin want pet big bird! Meep!",
		"Boom! Boom! Boom! Goblin head shake like thunder! Vroom",
		"Sky dragon come for goblin! No way, no way! Meep!",
		"Big shiny light hurt goblin eyes! Too bright! Blergh!",
		"Gah, light’s too sharp! No more zap! Ouch!",
		"Thunder storm bad for goblin fur. So wet! Glorp!",
		"That cloud look like goblin face! Gribble",
		"Why so much light? Make goblin's head spin! Zzzzzt!",
		"I miss the clouds! They no zap me! Bork",
		"Thunder? More like thunderous GAAH!",
		"Fluffy clouds! But where is goblin’s thunder? Grrrrr!",
		"Zzzzap! Don’t touch sky! It burn!",
		"Is that a big bird? Goblin gonna eat it! Bork bork!",
		"Too much thunder! I go hide under rock. Flop!",
		"Light so loud! Goblin go squish!",
		"Who need cloud when you got a goblin zapper? Squish!",
		"Clouds go BOOM! Thunder bad for goblin ears!",
		"All the light too much! Goblin need shade. Meep!",
		"Goblins, clouds, and thunder... Best combo! Yarp!",
		"Too bright, me need sunglasses! Gahhh!",
		"Cloud? More like squish on goblin head!",
		"Gahhh, this too much cloud! Too much storm! Vroom!",
		"Why so loud? Goblin’s head feels squished! Squawk",
		"Zzzzapp! Lightning hit goblin in the rear! Whap!",
		"Thunder booms! Goblin says no no no no!",
		"Goblins like light, but not when it boom! Pop-pop",
		"That cloud's giving me the fwoosh! Watch out!",
		"Goblins don't trust big birds in sky. Too high!",
		"Azurah shine bright! Goblin shield not bright enough!",
		"Gahh! Too much storm! Goblin go hide in the cave!",
		"Big zap! Big boom! Goblin heart racing! Zzzzt!",
		"Grrrr, goblin no like thunder. But funny noises!",
		"What that light do? Goblin no trust it! Whizz",
		"When does cloud stop zapping goblin?!",
		"Clouds make goblin sneeze! Chomp Chomp!",
		"Gah! Goblin stunned from zap! Vibbb",
		"Cloud dragons go BOOM! Goblin not ready for this!",
		"Too much lightning! Goblin no like zaps!",
		"Ahh, goblin’s fur all soggy! Blegh!",
		"Thunder in sky makes goblin shake like jelly!",
		"That zap hit goblin's toes! Meow!",
		"Big birds are too loud for goblin ears!",
		"Sky explode! Goblin no want to fight thunder! Plunk",
		"Why does the cloud hate goblin? Pbbbt!",
		"Oh no! That’s a big zap! Goblin get fried!",
		"Let me tell you, goblin’s not made for storms! Bloop",
		"More clouds, more noise! Goblin need silence!",
		"Not enough clouds! No thunder! Rarr",
		"Goblins fear no thunder! Except maybe that one!",
		"Zzzzap! Goblin need bigger umbrella!",
		"Is there a thunder goblin? Maybe I can find one!",
		"Who says goblins can’t fly? Meep! I try!",
		"Cloud monster come! Goblin go run!",
		"Thunder's loud, but goblin is louder! Woohoo!",
		"Let the thunder roll! Meep, meep!",
		"Gah! Sky scream louder than goblin's battle cry! Woosh!",
		"Let’s make it rain… goblin-style!",
		"No more zap! My fur’s all frizzy! Snrk",
		"Sky get big, but goblin bigger! Thump",
		"Thunder no stop, goblin no stop! Sniff",
		"Light bright, but goblin no squish!",
		"Big zap! Big squish! But goblin still standing!",
		"Gah, sky mad! Goblin hide from zap!",
		"Big thunder make goblin dance! Whee!",
		"Not scared of thunder, just a bit!",
		"Zzzzzap! Meep! Sky light bright!",
		"Goblin love cloud, but not the lightning! Whoomp",
		"Sky angry today! Hope it cool down soon!",
		"Big bird swoop! Goblin dodge it!",
		"Light in the sky too much! Goblin need sleep!",
		"Look at cloud! No, look at thunder! Zzzzt!"
	},
	[1427] = { -- SE
		"Goblin brain hurt! Too many thoughts! Grrr",
		"This place makes goblin head spin! Whap!",
		"I feel like goblin’s going mad! Zorp!",
		"Why so many voices in my head? Brrr!",
		"Big scary mind! Goblin not like it! Thwack",
		"Too much thinking! Goblin’s brain too small! Glorp",
		"Sanity? What sanity? Squawk!",
		"Brain explode! Too much confusion! Vroom",
		"What’s real? What’s not? Gahhh",
		"I see things that goblin shouldn’t see! Blergh!",
		"Too many whispers! Go away! Chomp",
		"Mind spinning like goblin on a wheel! Wheee!",
		"This place drive goblin crazy! Bwahaha!",
		"Big headache! Too many thoughts! Gahhh!",
		"Goblin no like voices! Make goblin scream! Honk",
		"Sanity’s edge? More like goblin’s cliff! Vibb",
		"Make the voices stop! Glurp",
		"Too much madness! Goblin’s going in circles! Squish",
		"My head full of crazy! Thump",
		"Can’t think straight! Too much chaos! Bork",
		"Goblin brain no work here! Too much skrrrt!",
		"That mind stuff hit me hard! Zzzap!",
		"Goblin can’t deal with this madness! Pop",
		"Is this real? Goblin feel funny! Gurgle",
		"Who’s talking? Goblin hear voices! Urk",
		"I think I lost my mind! Pbbbt!",
		"Sanity? Never heard of it! Bwahaha!",
		"Too many thoughts, too little goblin brain! Squeak",
		"Ahh! My brain feels like it’s melting! Gahhh!",
		"This place makes goblin dizzy! Flop",
		"I’m getting sucked into the madness! Womp",
		"These voices keep telling me to run! Thwack",
		"Goblin lost in thoughts, can’t find way out! Plop",
		"I think I’m going mad! Gahhh! Honk",
		"My mind’s all scrambled! Grrr",
		"Too much madness! Goblin need escape! Gribble",
		"Mind's spinning! Too many voices! Glorp",
		"This trial make goblin nuts! Brrr!",
		"Everything’s fuzzy! Goblin need to clear head! Zzzzzt",
		"Goblin can’t tell what’s real anymore! Meep",
		"My mind’s melting! Someone help! Plop",
		"This trial not good for goblin’s brain! Whap",
		"Goblin can’t think straight! Too much madness! Flop",
		"Oh no, the voices! Make it stop! Squish",
		"Everything’s spinning! Goblin need to run! Squawk",
		"Too many thoughts! Brain too small for this! Blech",
		"I lost my mind! Help! Gurgle",
		"All these voices! They’re too loud! Thump",
		"I don’t know where I am anymore! Pop",
		"Goblin can’t stop thinking! Urk!",
		"Help! Goblin’s brain is on fire! Zap",
		"Too many things happening at once! Gloop",
		"I think I’m losing it! Vroom",
		"Everything’s upside down! Whoomp",
		"Goblin’s brain is broken! Vibb",
		"That’s too much! Goblin need nap! Flop",
		"Help! Too much madness! Honk",
		"My brain hurts from all the voices! Rarr",
		"Make the madness stop! Clomp",
		"Why my mind feel all fuzzy? Eep",
		"Goblin can’t take it anymore! Gahhh!",
		"My brain’s going crazy! Boom!",
		"Stop messing with goblin’s head! Whizz",
		"Too much mind-bending stuff! Zzap!",
		"My head’s full of chaos! Too much! Pbbbt",
		"Goblin can’t see straight! What’s happening?! Plunk",
		"So much madness! Goblin can’t take it! Thwack",
		"Goblin feel like scrambled egg! Wham",
		"Everything feels wrong! Bloop",
		"I see strange things! Goblin don’t like it! Pop",
		"Too many whispers! Goblin run away! Whoosh",
		"What is this madness? Flibber",
		"Goblin’s head is a mess! Vwoosh",
		"Everything’s twisted in goblin brain! Grunk",
		"No more voices! Pbbbt!",
		"My head feels like it’s going to explode! Boink",
		"I can’t handle this! Whizz",
		"This trial is crazy! Goblin going insane! Yarp",
		"Too many voices! Can’t think! Thump",
		"I need out of this trial! Wobble",
		"Goblin's going mad! Need escape now! Skrrrt",
		"I can't think straight anymore! Gurgle",
		"Why is everything so twisted? Pop-pop",
		"Too many distractions! Goblin needs focus! Chomp",
		"I’m losing it! Goblin not like this! Plop",
		"I can’t stand it! Too much madness! Squawk",
		"Goblin’s brain is all scrambled! Fwoosh",
		"Too many voices! Goblin can’t focus! Vroom",
		"I feel the madness creeping in! Thwack",
		"Where’s the exit? Goblin need to run! Skitter",
		"This place make goblin feel dizzy! Flop",
		"Help! Mind’s going wild! Whap",
		"I’m trapped in my own head! Booom"
	},
	[1000] = { -- AS
		"Demon smash goblin! Bwahaha! Goblin smash back!",
		"Big scary demon thing! Goblin no like! Eep, eep!",
		"This place smell like goblin BBQ! Zorp!",
		"Demons everywhere! Goblin dizzy! Skrrrt!",
		"Goblin run, fire comin'! Squish, squish!",
		"Sanctuary full of demons, full of crazy! Urk! Urk!",
		"Fire everywhere! Goblin need new pants! Blegh!",
		"Big demon yell! Goblin hide or die! Vrooom!",
		"Demons everywhere! They watch goblin, waitin’ for snack! Glorp!",
		"Spooky demons! Goblin wanna run but feet won’t move! Gahhh!",
		"Too many demons! Too much fire! Goblin get crispy! Fwoosh!",
		"Too many demons lookin' at goblin! Squawk!",
		"Da fire burn, goblin burn! Honk honk!",
		"Flames everywhere! Goblin can’t see! Yikessss!",
		"Gah! Goblin roastin'! Too much fire! Meep!",
		"Help! Big demon comin'! Goblin not ready! Wham!",
		"Fire everywhere! Goblin cookin’ alive! Vroom!",
		"Why da demons so many? Goblin lost! Plop",
		"Demon army comin'! Goblin no run fast enough! Blergh!",
		"Fire! Fire! Goblin in da oven! Whizz!",
		"This place not safe! Goblin need bigger boots... and a shield! Clomp!",
		"Demons hit like bricks! Goblin no strong enough! Thump!",
		"Gah! More demons! Goblin get overwhelmed! Plunk!",
		"This place! Demons everywhere! Screech!",
		"I feel da heat! Is it from da demon or da fire? Bwahaha!",
		"Too much fire! Too much danger! Zizzle!",
		"Demon chasin' goblin! Goblin gotta run fast! Zorp!",
		"That demon looks real mad! Vibb!",
		"Goblin not run fast enough! Skitter!",
		"Demon’s claws too sharp! Eep-eep!",
		"Everything burnin'! Grumble!",
		"Why da demons keep comin'?! Gribbit!",
		"Fire everywhere! Goblin just wanna cook! Pop!",
		"Demon shout make goblin ears hurt! Whap!",
		"These demons like fire too much! Meow!",
		"This place bad for goblin skin! Bloop!",
		"Demons wanna play? Goblin not play! Honk!",
		"Too many daemons! Too much fire! Whizz!",
		"I think goblin’s gonna cook! Plunk!",
		"Oh no! Da demon boss here! Vroom!",
		"Goblin get roasted! Womp!",
		"Fire! More fire! I can’t handle da heat! Fwoosh!",
		"Flames everywhere! Fire and demons! Baaaah!",
		"Big demon stomp me! Thwack!",
		"Gah! Goblin need a break from fire! Squawk!",
		"Goblin feel da burn! Need ice! Eep!",
		"Fire bad for goblin health! Boing!",
		"Demons everywhere! Squish!",
		"Goblin not like fire demons! Yarp!",
		"Where’s da exit? Goblin trapped in fire! Chomp!",
		"This place is a mess! Goblin need more armor! Honk!",
		"Demon looks hungry! Goblin run! Sniff!",
		"More fire! Goblin can’t take it anymore! Vwoosh!",
		"Demons be everywhere! They never stop! Whap!",
		"Big demon gonna crush me! Flop!",
		"These flames too hot! Gahhh!",
		"Demons make goblin dizzy! Bzzzt!",
		"Goblin need an escape! Fire too strong! Plop!",
		"Is that demon laughing? Goblin no like! Pffft!",
		"This place makes goblin nervous! Too much fire! Yikesss!",
		"Why so much screaming?! Yawn!",
		"Gah! Demons keep following goblin! Skrrrt!",
		"Big scary demon stomp goblin! Honk!",
		"Fire too close! Goblin can’t keep up! Vroom!",
		"What is dat smell? Smells like roast goblin! Eep!",
		"Goblin burn again! Too much fire! Flop!",
		"Oh no! Another demon! Gahhh!",
		"Gah! Goblin getting fried! Meep!",
		"Big fire, big demon, BIG TROUBLE! Womp!",
		"That demon got big teeth! Rarrr!",
		"Goblin can’t stop da fire! Sizzle!",
		"More demons! Goblin’s not ready! Chomp!",
		"Goblin feel da heat! Too much fire! Glorp!",
		"Fire! Fire! Too much fire! Vroom!",
		"Demons like fire too much! Goblin no like! Pbbbt!",
		"Too many flames! Can’t see! Plunk!",
		"Da fire is bad for goblin’s skin! Honk!",
		"Demon keeps following! Zzzz!",
		"This place too hot! Goblin need to cool off! Eep!",
		"Fire’s too close! Goblin’s gonna burn! Bork!",
		"Demons coming! Goblin can’t keep up! Bloop!",
		"Fire everywhere! Goblin need water! Gurgle!",
		"Big demon with wings! Flap flap!",
		"Goblin can’t see in all this smoke! Guffaw!",
		"Demon stomps! Goblin run away! Boing!",
		"This trial’s not fun! Goblin need to get out! Thwack!",
		"Goblin got roasted again! Plop!",
		"Too much fire! Goblin needs a drink! Squish!"
	},
	[1344] = { -- DSR
		"Arrr! Big sea beast! Goblin no like fishy smell!",
		"Storms everywhere! Goblin’s gonna drown!",
		"Big ship, big waves, big trouble!",
		"Pirates? Goblin not afraid of pirates!",
		"Sea monster coming! Goblin swim away!",
		"Sharks in da water! Goblin not go swimming!",
		"Yarrr! Dreadsail ship not be friendly!",
		"Big waves crash! Goblin go splish-splash!",
		"Why so many ropes? Goblin get tangled!",
		"Arrr! Sea make goblin’s belly twist!",
		"Why da water so salty? Goblin’s tongue hurts!",
		"Storm rage on! Goblin no like wet boots!",
		"Big fish make goblin nervous!",
		"Goblin not be eaten by big fish!",
		"Ship shake too much! Goblin feel sea sick!",
		"Arrr! Dreadsail ship full of danger!",
		"Saltwater make goblin's fur all wet!",
		"Storms are a-ragin'! Goblin don’t like da rain!",
		"Ahoy! Pirates everywhere! Goblin no want fight!",
		"Oh no! Water rising! Goblin gonna sink!",
		"Big ship going down! Goblin not swim fast enough!",
		"Why da sky so dark? Goblin no see!",
		"Sea monsters! Goblin not ready!",
		"Waves are crashing! Goblin need a bigger boat!",
		"Big storm! Too much wind!",
		"ARRR! Pirate ship be comin’! Goblin no like pirates!",
		"Goblin run! Big fish after me!",
		"Get away from me, sea monster!",
		"Storm’s bad, goblin’s good!",
		"The waves keep pushin'! Goblin’s gonna fall off!",
		"Too many pirates! Goblin no fight da sea men!",
		"Arrr! Fish smells bad! Goblin hold nose!",
		"Dread sails make goblin dizzy!",
		"Storm make goblin go all wet!",
		"Pirates everywhere! Goblin be sneaky!",
		"Aye, that’s a big fish! Goblin no want to be lunch!",
		"Sea so cold! Goblin freeze!",
		"Too much rain! Goblin can’t see!",
		"Arrr! Waves make goblin puke!",
		"Sea monsters always hungry!",
		"I’m gonna sink! Goblin no like water!",
		"Big fish eat goblin!",
		"Why water so deep? Goblin gonna drown!",
		"No! Goblin’s boat sinking!",
		"Ropes everywhere! Goblin trippin’!",
		"Pirates throwin' bombs! Goblin go boom!",
		"Gah! Goblin’s ship is leakin’!",
		"Water rise! Goblin can't swim!",
		"Big pirate ship coming!",
		"Sea monster’s breath smells like fish!",
		"Arrr! Goblin not like Dreadsail water!",
		"It’s too wet! Goblin’s gonna drown!",
		"The water’s too deep! Goblin’s scared!",
		"That ship’s got a lotta holes! Goblin will fall right in!",
		"Why so much salt in da water?! Goblin no like!",
		"Too much wind! Too much rain! Goblin needs cover!",
		"Big fish swim underneath! Goblin not go near!",
		"I smell fish! Big fish coming to eat goblin!",
		"That’s a big wave! Goblin can’t handle that!",
		"Big monster on da horizon!",
		"Dread sails no fun! Goblin get all wet!",
		"Goblin no like sea air! It too thick!",
		"Waves keep coming! Goblin no stay afloat!",
		"Demon fish from da deep!",
		"Big ship moving! Goblin hold on tight!",
		"Why da water so salty?!",
		"Goblin swim fast, no catch me, fishy!",
		"Argh! Dread sails make goblin dizzy!",
		"Water everywhere! Goblin’s losing ground!",
		"Gah! Too much water! Goblin can’t handle da sea!",
		"Arrr! Big shark! Get away!",
		"Goblin no like salty water!",
		"Waves too big! Goblin falling in da sea!",
		"Too many pirates! Goblin gonna escape!",
		"Demons rise from da sea! Goblin no swim near dat!",
		"Arrr! Dread sail rocks da boat!",
		"That storm got me soaked!",
		"Pirates got me! I gonna be da next fish!",
		"Big ship sailing by! Too big for goblin!",
		"That fish’s teeth are huge!",
		"Sinking ship! Goblin no want swim!",
		"Too much rain! Goblin can’t see!",
		"Waves swallow goblin!",
		"Goblin’s gonna get sea sick!"
	},
	[725] = { -- MoL
		"Moon beasts coming! Goblin not ready!",
		"Big lion! Goblin no want fight lion!",
		"Big moon! Big danger!",
		"Wolves howl! Goblin no like moonlight!",
		"Moon monsters bite! Goblin run fast!",
		"Ahh! Da moon’s glowing too bright!",
		"Lion jump at goblin!",
		"Why da moon be so big? It watching goblin!",
		"Big cat smells bad! Goblin no want it near!",
		"Da wolves are hungry!",
		"Moon beasts hungry, goblin too fast!",
		"Why all da wolves so angry?!",
		"That lion's roar make goblin's fur stand up!",
		"Wolves run wild! Goblin not fast enough!",
		"Moon beast roar! Goblin run for cover!",
		"Lion’s teeth too sharp! Goblin dodge!",
		"Gah! Too many wolves! Goblin lost!",
		"Moon's too bright! Goblin can't see!",
		"What be that? Big claw!",
		"Lion's tail swingin'! Goblin dodge!",
		"Moonlight make goblin dizzy!",
		"Beasts on da hunt! Goblin no like big paws!",
		"Wolves circle round! Goblin too smart to get caught!",
		"Moon beasts bite hard! Goblin need bandages!",
		"Why da lion gotta look so angry?!",
		"Too many wolves! Goblin need escape route!",
		"Moon’s glow makin’ goblin confused!",
		"Big claws, big bites! Goblin not ready for dat!",
		"Ah! Goblin's on da hunt too!",
		"Lion jump high! Goblin gotta jump higher!",
		"Wolves too sneaky! Goblin be faster!",
		"Moon wolves not get goblin!",
		"Gah! Lion smells like danger!",
		"Lions got big teeth! Goblin got big claws!",
		"Full moon make goblin go wild!",
		"Too many teeth! Goblin gotta run!",
		"Big claws swipe at goblin!",
		"Moon beast be fast! Goblin needs speed!",
		"Wolves howlin’ in da night! Goblin gotta be sneaky!",
		"Lion chase goblin! Goblin faster!",
		"The moon’s too bright for goblin!",
		"Wolves circle round! Goblin will bite first!",
		"Da lion ain't gonna catch me!",
		"Why da wolves always hungry?!",
		"Lion bites goblin’s tail! Goblin run faster!",
		"Moonlight no help me!",
		"Lion fight goblin? Goblin fight back!",
		"That’s a big claw! Goblin dodge fast!",
		"Why da moon glow like dat? Goblin’s scared!",
		"Lion coming to eat goblin! Goblin too quick!",
		"Moon wolves make goblin shiver!",
		"Dat lion’s breath smells like meat!",
		"Wolves biting me! Goblin fight back!",
		"Full moon means full fight!",
		"Big claws swipe! Goblin not get caught!",
		"That’s one angry lion! Goblin need backup!",
		"Moon’s too bright for goblin’s eyes!",
		"Wolves run fast, but goblin faster!",
		"Lion's coming! Goblin no like cat fight!",
		"Full moon means big fight!",
		"Ahh! Lion bite my foot!",
		"Goblin dodges da claws!",
		"Wolves no catch goblin today!",
		"Lions too strong! Goblin too fast!",
		"Wolves howling everywhere! Goblin fight or flee?",
		"Big teeth, big paws, big trouble!",
		"Moon's light make goblin dizzy!",
		"Lion’s roar echo in da night!",
		"Wolves chase goblin! Goblin no get caught!",
		"Gah! That lion’s got claws!",
		"Beasts growl too loud! Goblin cover ears!",
		"Moon beasts waiting to eat me! Goblin ready!",
		"Wolves keep circling, but goblin be sneaky!",
		"Moonlight shining too bright! Goblin can’t see!",
		"The wolves be out in full force!",
		"Big claws, big teeth! Goblin just faster!",
		"Da wolves got too many tricks!",
		"Lion’s roar echo in goblin’s head!",
		"Big paws coming! Goblin not scared!",
		"Wolves all around! Goblin's goin’ wild!",
		"That lion won’t stop chasing!",
		"Gah! Dat lion’s got a sharp bite!",
		"Moon wolves be howling! Goblin no run away!"
	},
	[638] = { -- AA
		"Aetherian machines! Too many buttons!",
		"Da sky's glowin'! Goblin don't trust da stars!",
		"What be all dis metal stuff? Goblin not techy!",
		"Big blue light, big shock! Goblin no like dat!",
		"Da machines are hummin’! Goblin ready to smash ‘em!",
		"Too many aetheric doohickeys! Goblin no understand!",
		"Dis place smells funny, like magic!",
		"Da stars lookin’ down on goblin! Goblin not sure dat’s good!",
		"Machines explode! Goblin be running!",
		"Shiny blue lights be goin' everywhere!",
		"Gah! Dis place full of da weirdest stuff!",
		"Too many explosions, too many sparks!",
		"Dis machine got sharp bits! Goblin dodge fast!",
		"Aether-powered metal monsters! Goblin's turn to smash!",
		"Stars twinkle funny! Goblin thinkin’ it's a trap!",
		"Machine parts flyin’! Goblin run from dat!",
		"That big blue thing hurt goblin's ears!",
		"Goblin can't catch dat blue light!",
		"Da aetheric devices makin’ goblin dizzy!",
		"Gah! Machine's gonna zap goblin!",
		"Explosions everywhere! Goblin's gotta stay fast!",
		"Dis place full of shinin’ bits! Goblin wants one for da loot!",
		"Gah! Goblin just got zapped!",
		"Blue light make goblin glow! Goblin's too bright now!",
		"Why all da lights blinkin'?! Goblin can’t keep up!",
		"Explosion big enough to shake da stars!",
		"Machines makin’ goblin jumpy!",
		"Da light’s burnin’ goblin’s eyes!",
		"Lights, machines, everywhere! Goblin can’t stop runnin’!",
		"Da Aetherian boss wantin' goblin! Goblin no like!",
		"Gah! Goblin can’t see with all da light!",
		"That machine go boom! Goblin not want to be near!",
		"Aether-powered thingamajigs! Goblin's confused!",
		"Stars makin’ goblin dizzy!",
		"Zaps everywhere! Goblin's gotta dodge fast!",
		"Blue lights da color of da sky! Goblin want to punch ‘em!",
		"Machine’s got sharp edges!",
		"Why everything here glows? Goblin want to poke it!",
		"Big blue laser! Goblin not want to be zapped!",
		"Machine smell funny, like burnt toast!",
		"Too many lights! Goblin dizzy, need rest!",
		"Gah! Aetheric shock hurt goblin’s bones!",
		"What be that noise? Goblin not trust dat sound!",
		"Ahh! Dis machine keep shocking goblin!",
		"Stars too bright, goblin no can see!",
		"Big explosion! Goblin feel da rumble!",
		"More machines! Goblin wish for axe!",
		"What’s that blue spark doin’? Goblin no like!",
		"Aetheric trap! Goblin can't get caught!",
		"Machines turnin' on goblin!",
		"Da stars watchin' goblin! Goblin no like feelin’ watched!",
		"What’s all da noise? Too much in da air!",
		"Big lights! Big kaboom! Goblin need to run!",
		"Dis place too bright! Goblin need goggles!",
		"Aether-powered stuff going wild! Goblin no like wild!",
		"Can’t keep up with all da zapping!",
		"Da stars be laughin’ at goblin!",
		"Dis machine’s too hot! Goblin no touch!",
		"Blue sparks flyin’ everywhere! Goblin dodge!",
		"Gah! Aether-powered goblin slicer! Goblin no like!",
		"Big blast! Goblin need to hide!",
		"Da blue light makin' me crazy!",
		"Gah! Goblin got zapped again!",
		"That explosion felt like da stars hittin' me!",
		"Dis aetheric place full of traps! Goblin run faster!",
		"Machines going boom! Goblin don’t wanna be near!",
		"Why da stars gotta glow so bright? Goblin can’t see!",
		"Gah! Dat machine just tried to eat goblin!",
		"Big explosion, goblin dodge quick!",
		"Aetheric beam comin’! Goblin gotta jump!",
		"Dis place be full of scary lights!",
		"Gah! Goblin’s ears ringing!",
		"Machine’s hummin'! Goblin ready to smash!",
		"Stars makin’ goblin dizzy!",
		"Blue shock hurt goblin’s fur!",
		"Light everywhere, machines everywhere, goblin lost!",
		"Big blast! Too much noise!",
		"Aether's messin' with goblin’s brain!",
		"What’s dat? Aetheric guardian? Goblin no like!"
	},
	[639] = { -- SO
		"Da snakes here! Goblin no like snakes!",
		"All dis poison! Goblin not touch dat!",
		"Da big snake boss! Goblin get bite!",
		"Snake be everywhere! Goblin's got no time!",
		"Dis place full of slithery things!",
		"Ophidian queen? Goblin no like queen!",
		"Too many snakes! Goblin gotta run!",
		"Dis floor all wet, like snake skin!",
		"Poison everywhere! Goblin’s gonna get sick!",
		"Big snake hiss at goblin!",
		"Dis place smells like a swamp!",
		"Why so many snakes? Goblin no feel safe!",
		"Goblin not ready for all da hissin'!",
		"Gah! Snake bite goblin’s foot!",
		"Ophidian magic be all around!",
		"Too many slithery things, goblin can’t focus!",
		"Snake boss throwin' poison! Goblin dodge!",
		"Dis place give goblin chills!",
		"Ophidian fire, burn goblin's face!",
		"Snake goo everywhere! Goblin don't wanna touch dat!",
		"Da snake queen callin' goblin! No way!",
		"Da ground’s all squishy! Goblin not like!",
		"All dis venom! Goblin’s getting woozy!",
		"Snake make goblin dizzy!",
		"Dis poison cloud gonna choke goblin!",
		"Big snakes fallin' from da ceiling!",
		"Poison snake spit! Goblin no like dat!",
		"Why da snakes keep hissin' at goblin?!",
		"Ophidian magic hurts goblin’s brain!",
		"That big snake look mad!",
		"Goblin ready to smush dem slithery things!",
		"Gah! Dis poison cloud makin' goblin’s skin tingle!",
		"Da snakes all coiled up! Goblin be careful!",
		"Ophidian fight’s too much for goblin!",
		"Gah! Too many bitey things!",
		"Snake’s too fast! Goblin can't catch it!",
		"Da ground shakes! Big snake comin'!",
		"Ophidian magic, goblin feel funny!",
		"More snakes! Why so many?!",
		"Snake venom! Goblin not want poison!",
		"Da big snake boss lookin’ at goblin!",
		"Goblin gettin’ hit by poison darts!",
		"Gah! What be dat big snake doin'?!",
		"Ophidian poison burn goblin’s tongue!",
		"Da queen snake be hissin' louder!",
		"Poison everywhere! Goblin’s breathin’ in venom!",
		"Da snakes seem to be everywhere!",
		"Poisonous spit all around! Goblin’s gotta dodge!",
		"Ophidian ground all wet! Goblin slide!",
		"Da big snake be ready to strike!",
		"Gah, goblin feel da poison creep in!",
		"Snakes tryin’ to get goblin!",
		"Da Ophidian magic feels like it's burnin'!",
		"Too many slithering sounds! Goblin can’t focus!",
		"Dat snake just missed goblin!",
		"Gah! Goblin feel da poison deep in da bones!",
		"Dat snake makin' weird noises! Goblin not trust dat!",
		"Snake spit everywhere! Goblin stay far!",
		"Big snake comin’! Time to fight!",
		"Ophidian magic zap goblin!",
		"Dis poison is strong! Goblin feel da burn!",
		"Poison in da air, goblin breathin’ deep!",
		"Da queen be callin’ goblin to her! Goblin not goin’!",
		"Snakes crawlin’ all over da place! Goblin not sure where to go!",
		"Big snake bite! Goblin scream!",
		"Dis place smell like snake eggs! Goblin feel sick!",
		"Ophidian magic too much! Goblin dizzy!",
		"Goblin’s gotta hide from dat big snake!",
		"What be dat? Da ground tremblin’!",
		"Gah! Poison gonna make goblin faint!",
		"Gah! Da snake’s too quick! Goblin no catch it!",
		"Poison cloud makin’ goblin’s head spin!",
		"Dis place full of slithery critters!",
		"More venomous things around! Goblin gotta hide!",
		"Snake queen’s power too strong!",
		"Ophidian magic’s everywhere! Goblin gotta watch out!",
		"All dis poison’s makin’ goblin sick!"
	},
	[975] = { -- HoF
		"Dis place full of weird machines! Goblin no trust dem!",
		"Dat big machine gonna crush goblin!",
		"Dis place hummin' like a big metal bee!",
		"Machine blow up! Goblin no want dat!",
		"Dis floor all shiny! Goblin slip!",
		"Big metal spider comin'! Goblin not like bugs!",
		"Da metal constructs all over da place!",
		"Why dis place smell like oil? Goblin no like dat!",
		"Gah! Dis place makin' goblin’s head spin!",
		"Big machine boss! Goblin not ready for dat!",
		"Goblin gettin’ squashed by all da robots!",
		"Wha dat? A metal goblin?!",
		"Dis trial too much tech! Goblin prefer fire!",
		"Big metal arms! Goblin duck!",
		"Why da robots keep movin’? Goblin can’t keep up!",
		"Dis place too noisy! Goblin gonna go deaf!",
		"Too much metal in dis room! Goblin can’t breathe!",
		"Dis machine throwin' lasers! Goblin gotta dodge!",
		"Goblin no like big metal balls!",
		"Machine parts everywhere! Goblin gettin’ lost!",
		"Da machine hurt goblin’s foot!",
		"Dis place full of danger! Goblin gotta be quick!",
		"Dis big robot be watchin’ goblin!",
		"Dis trial makin’ goblin’s bones ache!",
		"Gah! Dis metal thing’s got tentacles!",
		"Too many sparks flyin' round here!",
		"Goblin gettin’ zapped!",
		"Dis place full of weird contraptions!",
		"Too much noise! Goblin can’t hear!",
		"Da floor's all clickity-clack! Goblin no like dis!",
		"Why are these machines tryin' to kill goblin?!",
		"Goblin don’t trust da lasers!",
		"Why da robots keep comin’? Too many of dem!",
		"Dis metal trial not goblin friendly!",
		"Gah! Machine’s grabbin' goblin!",
		"Dis place too full of wires! Goblin feel tangled!",
		"Da metal spiders be movin’ too fast!",
		"Dis machine be blowin’ hot air! Goblin not like it!",
		"More machines! Goblin gettin’ overwhelmed!",
		"Dis place smells like rust! Goblin don’t wanna touch nothin’!",
		"Da big robot punchin' goblin!",
		"Wha? Goblin feel da metal in da air!",
		"Da robot arms comin’ to grab goblin!",
		"Too many gadgets! Goblin’s head too full!",
		"Da floor's all sparklin'! Goblin no like dis at all!",
		"Metal on metal! Dis trial makin' goblin crazy!",
		"What dis? A big flying machine!",
		"Goblin gotta watch out for da laser beams!",
		"Too many lights! Goblin can’t see!",
		"Dis big robot crush goblin’s bones!",
		"Gah! Goblin gettin’ zapped by da machines!",
		"Dis place give goblin a headache!",
		"Dis trial is all wires and metal! Goblin no like it!",
		"Da big robot make goblin go boom!",
		"Too many mechanical noises! Goblin ears hurt!",
		"Dis machine got too many parts! Goblin’s confused!",
		"Dis place full of dangerous gadgets! Goblin not go near dem!",
		"Gah! Da floor's cracklin' with electricity!",
		"Machine boss comin' to get goblin!",
		"Dis place makin' goblin’s tail twitch!",
		"Big robot explode! Goblin run!",
		"Dis place got too many gears! Goblin caught in 'em!",
		"Why da machines all movin’? Goblin not ready!",
		"Gah! Da robots not stop comin'!",
		"Dis trial's full of dangerous machines!",
		"Metal everywhere! Goblin gotta stay alert!",
		"Dis trial is makin' goblin dizzy!",
		"Gah, dis machine burn goblin!",
		"More robots? Goblin’s had enough!",
		"Goblin stuck between gears! Help!",
		"Dis place too full of clicks and clatters!",
		"Goblin fallin’ in da wires!",
		"Metal spiders all around! Goblin not like!",
		"Why da robots get so angry?!",
		"Dis big machine watchin' goblin!",
		"Too much electricity in da air!",
		"Dis place be full of mechanical terror!",
		"Goblin caught in da machine!",
		"Da big robot gonna smash goblin!",
		"Goblin feel da zap in da air!",
		"Dis big machine gonna crush goblin!",
		"Da robots comin' for goblin’s tail!",
		"Dis place full of strange gadgets!",
		"More robots! Goblin not ready for this!",
		"Da machines make too much noise!",
		"Goblin's been hit by da laser!",
		"Dis trial feel like a big trap!",
		"Why all dis tech here? Goblin prefer da fire!"
	},
	[636] = { -- HRC
		"Dis place full of dead! Goblin no like ghosts! Bwahaha!",
		"Lava everywhere! Goblin gonna melt! Vrooom!",
		"Da fire not hot enough for goblin! Honk!",
		"Lava not burn goblin! It burn da boots! Gahhh!",
		"Big scary ghost-man comin' for goblin! Screech!",
		"Dis lava, dis heat, dis bad for goblin's skin! Ouch!",
		"Goblin see da big dragon! Roar!",
		"Da fire be angry! Goblin not wanna be roasted! Glorp!",
		"Dem monsters look like they want goblin for lunch! Grrr!",
		"Gah! Da ground’s cracklin’ with lava! Boom!",
		"Why dis place smell like burnt meat?! Blech!",
		"Dat big daedra throwin’ fireballs! Goblin duck! Flop!",
		"Goblins like fire, but not dis much fire! Zizzle!",
		"What dat? Big fiery bird comin’! Flap!",
		"Hel Ra Citadel full of ghosts! Goblin no like spirits! Plop!",
		"Da floor's burnin'! Goblin gotta run! Whoosh!",
		"Big ghost bad! Goblin run from da shade! Skitter!",
		"Why is it so hot?! Goblin meltin’! Sizzle!",
		"Dis trial be full of fire and pain! Vzzzzt!",
		"Fireball flyin’ everywhere! Goblin duck! Skrreee!",
		"Gah! Goblin’s tail on fire! Hissss!",
		"Too much heat! Too many monsters! Goblin not like! Grunk!",
		"Why dem big daedra look so mad?! Bwahaha!",
		"Dis ghost-man throwin’ rocks! Thump!",
		"Lava everywhere! Goblin’s feet gettin’ hot! Gah!",
		"Big bad monsters coming! Goblin got no time! Bop!",
		"Why da daedra keep shoutin’? Goblin can’t hear! Ka-boom!",
		"Dis place full of pain! Goblin feel da burn! Glorp!",
		"Fire no good for goblin’s fur! Whizz!",
		"Dat big dragon comin' down! Wham!",
		"Damn ghost-beast tryin’ to bite! Crunch!",
		"Lava gonna fry goblin good! Sizzle!",
		"Gah! Da big flame beasts coming for goblin! Whap!",
		"Dis place too fiery for goblin! Too many dangers! Squeak!",
		"Da daedra’s got big fire breath! Hissss!",
		"Goblin no scared of fire... but dat burnin’ rock? Glorp!",
		"Why is it so smokey in here? Goblin can’t see! Chomp!",
		"Gah! Da big dragon’s breathing fire! Flare!",
		"Dis ghost beast be mad at goblin! Bleep!",
		"Dem monsters be big and fiery! Thwack!",
		"Da daedra’s burnin’ everything! Goblin gonna dodge! Plop!",
		"Lava burns like the goblin’s rage! Vroom!",
		"Gah! Goblin fallin' in da lava! Skrrt!",
		"Dis place got monsters and fire everywhere! Squish!",
		"More daedra! Goblin no have time for dis! Ka-boom!",
		"Dat big fire beast smell like burnt fish! Sniff!",
		"Lava comin’ to get goblin! Thwack!",
		"Da heat makin’ goblin dizzy! Wobble!",
		"Too much heat, too much fire! Whoosh!",
		"Dis place makin’ goblin sweat! Blegh!",
		"Da ghosts be laughin’ at goblin! Guffaw!",
		"Fire not scaring goblin! Dat fireball was a little close! Ka-boom!",
		"Why dem daedra scream so loud? Goblin's head hurt! Blep!",
		"Dis trial so hot, goblin can’t think! Gah!",
		"Gah! Lava comin' from everywhere! Fwoosh!",
		"Dis place full of fiery beasties! Goblin no want none of dat! Vrrrr!",
		"Dis ghost's makin’ noise! Goblin no like loud sounds! Plop!",
		"Gah, big lava golem smashin' goblin! Crash!",
		"Dem fiery daedra want goblin for dinner! Yikess!",
		"Why da ground all cracklin’? Goblin no wanna fall in! Whizz!",
		"Goblin feel da heat makin’ him melt! Fwoosh!",
		"Lava shootin’ outta da ground! Plop!",
		"Dem daedra lookin’ mean today! Grrr!",
		"More fireballs? Goblin dodgin’ like crazy! Plunk!",
		"Fire beast tryin’ to burn goblin! Bwahaha!",
		"Why dis place smell like roasted daedra? Sniff!",
		"Da fire comin’ for goblin’s tail! Yelp!",
		"Dis trial be like a furnace! Goblin’s burnin’ up! Sizzle!",
		"Gah! Dis lava burnin’ goblin’s feet! Whoosh!",
		"Da ghost-beast smash goblin with its claws! Wham!",
		"Too much lava! Too much smoke! Goblin not like! Pbbbt!",
		"Da fire spirits comin’ to roast goblin! Scree!",
		"Why da fire so hot?! Goblin not used to dis! Grunt!",
		"Big dragon movin' slow, but fire everywhere! Grrr!",
		"Dis place be a deathtrap! Too much burnin’! Fzzzzt!",
		"Lava splashin’ everywhere! Goblin no like wet fire! Splat!",
		"Why dis place so hot? Goblin needs a drink! Gurgle!",
		"Dis trial makes goblin’s fur stand on end! Shudder!",
		"Lava comin' from da ceiling! Boom!",
		"Big ghosts with swords! Goblin no like fightin' dat! Wham!",
		"Gah! Da fire’s meltin’ goblin’s face! Sizzle!",
		"Big monsters shootin’ lava everywhere! Crackle!",
		"Dis place full of danger! Goblin better stay low! Bloop!",
		"Dem daedra be scary! Big fire goin' up high! Zzzzt!",
		"Why da ground be so crackly? Lava comin'! Brrr!",
		"Da fire’s makin’ goblin’s nose burn! Pbbt!",
		"Gah! Lava’s splittin' da floor! Clunk!",
		"Dis place be too hot for goblin! Gahhh!",
		"Da big fire beast comin' again! Kablamm!",
		"Dis place full of flame, fire, and death! Sniff!",
		"Lava comin’ like a wave! Goblin gotta run! Whoosh!",
		"Fireball hittin' goblin’s tail! Sizzle!"
	}
}
