GoblinCombatSayings = {
    "Goblin gonna bash your skull in, snrk!",
    "Boom! Boom! Boom! Who’s next, blargh?",
    "Fight, fight, fight! Goblin like it, kekeke!",
    "Goblin hit hard, watch out, gyaa!",
    "Skrraaa! Big smash incoming, meh!",
    "Goblin no care, goblin still smash you, hurrr!",
    "You gonna regret that, fool, blegh!",
    "Yaargh! Fight until bones crack, reeek!",
    "Goblin power! Goblin stronger than you, nyah!",
    "No escape from goblin! Goblin catch you, skrrt!",
    "Zzzt! Burn them alive, gloop!",
    "You mess with goblin, you get boom, squish!",
    "Goblin smash you with a big rock, honk!",
    "Wanna die slow or fast? Goblin make it fun, zog zog!",
    "Brrrrap! Goblin hit hard like thunder, pbbbt!",
    "Goblin love a good fight! Smack ‘em, gahhh!",
    "Goblins never stop fighting, eep eep!",
    "Goblin don’t run! Goblin fight ‘til death, brap!",
    "Too slow, too weak! Goblin win, yarp!",
    "Boom! Smashy time, flarp!",
    "You can't beat goblin! Goblin too quick, squee!",
    "Hehe, goblin break bones like sticks, bwahaha!",
    "Zzzzap! Taste goblin fire, narf!",
    "Goblin gonna smash you to pieces, plop!",
    "Goblin never back down, gribbit!",
    "Goblin hit you with fire and rocks, mlem!",
    "Too slow for goblin, ha! splurt!",
    "No one escapes goblin wrath, burp!",
    "Smash ‘em, smash ‘em all, yikesss!",
    "Goblin punch! Kaboom, fizzz!",
    "Goblin no die! You die first, skrreee!",
    "You won't escape this one, eep-o!",
    "Goblin squish you like bug, gah!",
    "Goblin got moves, crunch!",
    "Goblin too fast for you, hehe, zorp!",
    "You can’t run from goblin, grrr!",
    "Goblin gonna make you regret this, thwack!",
    "You’re too weak for goblin power, gulp!",
    "Goblin smash ‘til there’s nothing left, yoink!",
    "Goblin hit hard, you fall down, bork!",
    "Goblin gonna break your bones, flop!",
    "Goblins never lose a fight, snrk!",
    "Goblin make you wish you stayed home, gronk!",
    "Feel the power of goblin might, chomp!",
    "Goblin smash your bones to dust, squish!",
    "Goblins never run from a fight, zzzzap!",
    "You’re goblin’s now, fool, reeek!",
    "Time for a goblin beatdown, blegh!",
    "Goblin always win in the end, narf!",
    "Goblin never lose a fight, ever, plop!",
    "Ha! Goblin crush you now, squish!",
    "Goblin love a good fight, yarp!",
    "Smash time, fool, pbbbt!",
    "You can't stop goblin! Hehe, flarp!",
    "Goblin win, you lose, meep!",
    "You’re too slow to stop goblin, squee!",
    "Goblin smash! You go boom, honk!",
    "You’re gonna feel this one, glorp!",
    "Goblin gonna make you wish you never came, bork!",
    "Zzzzap! More fire for you, zorp!",
    "Don’t mess with goblin’s fist, squish!",
    "Boom! Goblin hit harder than that, skrrt!",
    "Goblin love smashing things, pbbbt!"
}
