GoblinOthersDeathSayings = {
    "Goblin see {{name}} fall over, blegh!",
    "{{name}} go sleep! No get up!",
    "{{name}} all bones now. Yikes!",
    "Another meat friend down! {{name}}, nooo!",
    "{{name}} squished like bug!",
    "Oh no, {{name}} no more wiggle!",
    "Uh oh! {{name}} nap forever now!",
    "Goblin smell dead {{name}}...",
    "{{name}} explode real good!",
    "{{name}} forgot dodge dance!",
    "Oops! {{name}} became floor paint!",
    "That scream from {{name}}? Hehe!",
    "{{name}} went poof! Like ghost fart!",
    "Zog zog! {{name}} real ded now!",
    "Big ouchie for {{name}}!",
    "{{name}} meet Sharp Rock! Rock win!",
    "Bye bye, {{name}}! Goblin wave!",
    "{{name}} now part of dirt!",
    "Goblin mark grave: Here lay {{name}}!",
    "No more snack talk from {{name}}!",
    "{{name}} down! Goblin sad! Kinda.",
    "Goblin saw {{name}} trip... on death!",
    "That thud? {{name}} hit ground hard!",
    "Whoops! {{name}} forgot to breathe!",
    "{{name}} went squish! Hehe!",
    "Rest in pieces, {{name}}!",
    "{{name}} did a death flip!",
    "Boom! {{name}} no more!",
    "{{name}} join ghost club now!",
    "That was {{name}}'s last 'ow'!",
    "{{name}} now worm treat!",
    "{{name}} ded. Goblin not surprised!",
    "Another squishy gone! Bye {{name}}!",
    "Zapped! Toasted {{name}} detected!",
    "Boss smacked {{name}} to next week!",
    "{{name}}? More like was-name!",
    "Oopsie daisy, {{name}} real flat!",
    "{{name}} do good impression of corpse!",
    "Blood spill from {{name}} make art!",
    "{{name}} sleepin’ in red now!",
    "Dead? Yup. That was {{name}}!",
    "{{name}} now floor decoration!",
    "{{name}} got bonked hard!",
    "That kaboom? {{name}} vanish!",
    "Goblin say rip {{name}}, hehe!",
    "{{name}} forgot how to live!",
    "One less loot thief! Bye {{name}}!",
    "{{name}} make goblin laugh, then cry, then laugh!",
    "No more yappin’ from {{name}}!",
    "{{name}} real crispy now! Zog zog!",
    "Next time, {{name}}, try harder!",
    "Goblin save spot in dirt for {{name}}!",
    "Hey {{name}}, where life go?",
    "{{name}} now one with floor!",
    "Goblin saw {{name}} get flattened!",
    "Smelled {{name}} death from here!",
    "{{name}} make great rug now!",
    "That’s what {{name}} get for standin’ still!",
    "Goblin clap for {{name}}’s epic demise!",
    "No shield, no chance, right {{name}}?",
    "Dead like sad mudcrab. Poor {{name}}!",
    "Oops! {{name}} nap in lava!",
    "Zap zap, {{name}} go bye!",
    "Not even bones left of {{name}}!",
    "They gone! {{name}} no comin’ back!",
    "That one? {{name}}? Toast!",
    "{{name}} did death dance real good!",
    "{{name}} become decoration now!",
    "Big mess! Was {{name}} a person?",
    "Goblin smell {{name}}'s failure!",
    "{{name}} needed more luck!",
    "Molag Bal say hi to {{name}}!",
    "{{name}} trip over own doom!",
    "{{name}} forgot healing potion!",
    "Oopsie! {{name}} no block in time!",
    "{{name}} fall like sack o’ mud!",
    "Real squish noise from {{name}}!",
    "Goblin laugh at {{name}}’s kaboom!",
    "That death? Oh, {{name}} again.",
    "RIP {{name}}, again!",
    "Stepped in stupid? That was {{name}}!",
    "Yikes! Guts of {{name}} go splat!",
    "Even ghosts laugh at {{name}} now!",
    "Zap! {{name}} like sweetroll toast!",
    "{{name}} make good bone pile now!",
    "Another trip to Shadow Realm for {{name}}!",
    "{{name}} forgot dodgeball rule!",
    "Dead? {{name}} nailed it!",
    "{{name}} flat. Very flat.",
    "{{name}} down so fast! Blink gone!",
    "Oops! {{name}} learn flying... badly.",
    "{{name}}? More like puddle now.",
    "Squish! {{name}} no more.",
    "Time for new {{name}}, this one broken!",
    "{{name}} turn to goo! Hehe!",
    "Boss say ‘no’ to {{name}}!",
    "Goblin saw {{name}} death from here!",
    "That was {{name}}’s final oof!",
    "Goblin add {{name}} to memory pile!",
    "{{name}} need mop and bucket!",
    "Blood? Check. Dead {{name}}? Check!",
    "Welp, {{name}} done for!"
}
