GoblinBossSayings = {
    "We gonna smash {{bossName}} into pieces, blegh!",
    "A big boss like {{bossName}}? Goblin no scared, snrk!",
    "Heh, {{bossName}} think they can beat goblin? Fool!",
    "We fight big boss now, {{bossName}}? Zog zog!",
    "Goblins crush {{bossName}}! No mercy, gronk!",
    "Smash the {{bossName}}! Goblin not scared, snort!",
    "Big fight ahead! Goblin ready for {{bossName}}, heh!",
    "This gonna be a tough one! But goblin crush {{bossName}}!",
    "Goblin hungry for boss meat! Time for {{bossName}} to fall!",
    "Me see big boss {{bossName}}! Goblin smash it good!",
    "Oof, {{bossName}} tough! But goblin tougher, gribbit!",
    "Goblins never lose! Time to smash {{bossName}}!",
    "Big fight, big loot! Let's crush {{bossName}}, whee!",
    "{{bossName}} think they big? Goblin smash big things, gronk!",
    "Goblin ready for big boss, Z'Maja! Gotta show 'em who's boss!",
    "Zog zog! {{bossName}} gonna feel goblin wrath!",
    "We gonna break {{bossName}}! Crunchy time, nyah!",
    "Big, big boss! But goblin smash bigger, hrk!",
    "Watch out, {{bossName}}! Goblin smash from above, ZAP!",
    "Goblin gonna throw rocks at {{bossName}}! Smashy smash!",
    "{{bossName}} will be dust when goblin done!",
    "Boom! Goblin smash, {{bossName}} crash!",
    "Let’s show {{bossName}} who’s the boss, bleh!",
    "Goblin break bones, even big ones like {{bossName}}!",
    "This gonna be a big fight! Goblin gonna win, bwahaha!",
    "{{bossName}} looks tough, but goblin smash tough things, hehe!",
    "Goblin fight until the last breath! {{bossName}} gonna fall!",
    "Big battle, big fun! Goblin crush {{bossName}}!",
    "Goblin’s not scared of {{bossName}}. Bring it on, snrk!",
    "Big boss, big challenge, but goblin crush all, oof!",
    "Goblin fight big, take down {{bossName}}, krr!",
    "Time for a goblin-sized beatdown, {{bossName}}!",
    "We fight to the end! Goblin smash {{bossName}} down!",
    "That’s a big boss, but goblin’s bigger, gribbit!",
    "{{bossName}} gonna get squashed, goblin style!",
    "Smash it up, goblin style! Time for {{bossName}} to fall!",
    "Big boss? Goblin not scared, squish {{bossName}}!",
    "We smash big bosses like {{bossName}} all day!",
    "Let’s wreck {{bossName}} together, goblin style!",
    "Time for {{bossName}} to taste goblin fury!",
    "{{bossName}} never stood a chance against goblin power!",
    "Goblin crush bigger than {{bossName}}, hurrr!",
    "Big boss, big fun! Goblin make it crash!",
    "Goblin beat up big bosses! Now we smash {{bossName}}!",
    "No retreat, no surrender! Smash {{bossName}}!",
    "Goblin smash till there's nothing left of {{bossName}}!",
    "This fight big! But goblin bigger, yarp!",
    "Fight of the century! Goblin crush {{bossName}}!",
    "I smell a big boss! {{bossName}}, you’re next, gronk!",
    "{{bossName}} gonna fall to goblin might, squish!",
    "Time to smash big things! {{bossName}} first!",
    "Goblin’s gonna make sure {{bossName}} never stands again!",
    "{{bossName}} better be ready for a goblin showdown!",
    "Goblins win, even against tough bosses like {{bossName}}!",
    "Tough boss! But goblin’s tougher, bleh!",
    "Let’s make a big mess! Smash {{bossName}} now!",
    "Big boss? Goblin smash big, hard, and fast!",
    "Goblin no care how tough! Smash {{bossName}}!",
    "{{bossName}} might be big, but goblin’s bigger, nyah!",
    "Smash the big boss, {{bossName}}! Goblin’s coming!",
    "Fight to the end! Goblin’s not backing down from {{bossName}}!",
    "Goblin gonna rip {{bossName}} apart, bwahaha!",
    "Time for the boss to fall! Goblin take it down!",
    "Goblin smash like thunder, {{bossName}} can't stop it!",
    "No mercy for {{bossName}}! Goblin crush all!",
    "Goblin’s not afraid! Smash {{bossName}} with style!",
    "Big fight, big goblin, bigger victory! {{bossName}} crushed!",
    "Let's make this boss fall! Smash {{bossName}}!",
    "Goblin’s gonna show {{bossName}} how to lose!",
    "Smash the boss! Big fight, big goblin win!",
    "We got this! {{bossName}} gonna get wrecked!",
    "Goblin’s gonna wreck {{bossName}} into the ground!",
    "Boss? Big? Pfft, goblin smash harder, grrr!",
    "Goblin break bones, even big boss bones like {{bossName}}!",
    "Goblin smash boss after boss! Now it’s {{bossName}} turn!",
    "Big boss coming? Goblin’s ready for it, snrk!",
    "Time to defeat big boss! Goblin show how it’s done!",
    "Goblin got this! {{bossName}} is going down!",
    "Another big boss to smash, {{bossName}} next!",
    "Goblin crushes big bosses with ease, even {{bossName}}!",
    "Bring it on, {{bossName}}! Goblin’s not scared of big!",
    "Big fight ahead! Goblin smash {{bossName}} to dust!",
    "We’ll win this! Goblin crush {{bossName}} first!",
    "Smash! Goblin break {{bossName}} good!",
    "Big boss, big fight, but goblin’s bigger!",
    "Goblin crush bosses like {{bossName}}, no sweat!",
    "Time to show big boss like {{bossName}} who’s boss!",
    "Let’s wreck {{bossName}}, goblin style!",
    "This fight gonna be tough, but goblin win every time!",
    "Smash the boss! Goblin rule the world, hrk!",
    "Big fight coming! Goblin crush {{bossName}}!",
    "Time to break boss! {{bossName}} no match for goblin!",
    "Goblin crush all bosses! {{bossName}} too, snort!",
    "Fight’s not over till goblin wins! Let’s smash {{bossName}}!",
    "Smash the boss! Goblin show no mercy, bwahaha!",
    "We fight! We win! {{bossName}} get smashed!",
    "Goblin crush {{bossName}} to bits!",
    "Bring it on, {{bossName}}! We fight till the end!",
    "Big boss? Pfft! Goblin crush bigger, gronk!",
    "Goblin break things, even big bosses like {{bossName}}!",
    "Goblin gonna make {{bossName}} regret showing up!",
    "This fight big, but goblin smash bigger, gribbit!",
    "Let’s show {{bossName}} what goblins are made of!",
    "Goblin gonna break the boss, one smash at a time!",
    "We fight tough bosses! {{bossName}} next!",
    "Goblin crush all, even big bosses like {{bossName}}!",
    "Goblin never back down from any boss, snrk!",
    "Big fight! But goblin’s bigger than {{bossName}}!",
    "Goblin ready to smash bosses like {{bossName}}!",
    "Time to make {{bossName}} regret coming here!",
    "Goblin’s gonna show how it’s done! Smash {{bossName}}!"
}
