GoblinDeathSayings = {
    "Snrk... goblin nap now... forever nap.",
    "Oopsies! goblin squished! Blegh!",
    "Boss too smashy! Gyaa!",
    "Why goblin bones no work? Glorp...",
    "Goblin went bye-bye... burp.",
    "Respawn... later. Skrrt.",
    "Big ouchie! Bwahaha!",
    "Too much stab, not enough dodge! Narf!",
    "Goblin done got bonked! BONK!",
    "Tell gobbo family... goblin not make it. Meep.",
    "Send help... or snacks... pbbbt.",
    "Goblin no like red circles no more! Flarp!",
    "Dead again? goblin pro at this! Kekeke!",
    "Is this... goblin heaven? Gloop...",
    "Was goblin supposed to block? Eep-o!",
    "Goblin play dead! Wait... no, is real! Hurrr...",
    "Why screen go grey?! Skrreee!",
    "Healer busy nap too? Yikesss!",
    "Oops. Wrong button. Now goblin ghost. Glorp.",
    "That boss cheat! Reeeek!",
    "Goblin just testing floor. Honk.",
    "Don't rez goblin! goblin comfy here. Meh.",
    "Too many adds, not enough goblin. Gahhh!",
    "This fine. goblin like ground. Squish.",
    "Respawn in... eventually. Blegh.",
    "Call priest! Gobbo down! Zog zog!",
    "Goblin spirit floaty now... mlem.",
    "Floor taste funny! Plop.",
    "That was... unexpected. Eep.",
    "Mistakes were made... mostly by goblin. Brap.",
    "So much red! So much pain! Squee!",
    "Shoulda stayed in hut today... Gronk.",
    "Well, that escalated quickly. Gloop!",
    "Goblin down. I repeat: goblin down! Yarp!",
    "Send green pokes! Send lots! Flop!",
    "Goblin not dead, just... slow. Burp.",
    "Can’t feel legs... or arms... or anything. Zzzt.",
    "Tell boss: goblin surrender! Chomp.",
    "Guess goblin nap through next mechanic. Gulp!",
    "Oops. goblin forgot dodge roll... Meep!",
    "That AoE was personal! Reek!",
    "ZAP! And now goblin toast. Kekeke!",
    "Bonk... and gone. BONK bonk.",
    "Goblin squashed flatter than cave pancake! Skreeee!",
    "That crit hit soul, not just armor. Eep eep.",
    "Healer? Hello?? Meh.",
    "Not my fault! Lag goblin did it! Plop!",
    "Can goblin sue boss for damages? Flarp!",
    "Tell guild: gobbo died with honor! Gribbit.",
    "DPS so high, even goblin health gone! Gyaa!",
    "They got goblin! Save yourselves! Snrk!",
    "First to die... again! Squee!",
    "Boss no like goblin face, goblin think... Hurrr.",
    "Goblin just here to decorate floor. Narf.",
    "Hold up... why goblin always target? Zorp.",
    "This boss rude. Bork!",
    "That cone? Didn’t see cone. Yikesss!",
    "Lying down for dramatic effect. Kekeke!",
    "Dead again? Must be Tuesday. Glorp.",
    "Oops. That AoE spicy. Urk!",
    "Goblin bones scattered now! Flop.",
    "Death hug from boss too strong! Gah!",
    "Let goblin cook! Oh wait, goblin dead... Zzzt.",
    "Next time goblin wear helmet. Meh.",
    "Zoned out... then zoned into death. Skrreee.",
    "Boss smacked soul outta goblin! Reek!",
    "You see that? goblin exploded good! Brapp!",
    "Tell boss: goblin not dinner! Flarp!",
    "This mechanic too mechanic-y. Gronk.",
    "Respawn gods no like goblin today. Snrk.",
    "Hey, someone turn off screen! Blargh!",
    "Guess goblin live here now. Bwahaha!",
    "Healer, blink twice if you forgot goblin. Gloop.",
    "All part of plan... bad plan. Eep!",
    "Goblin armor broke... and spine too. Thwack!",
    "Rez plz? goblin promise no die next time. Pbbbt.",
    "Goblin should’ve read mechanics... Mlem.",
    "Goblin tried. Goblin failed. Narf.",
    "Now goblin get break! Yay? Squee!",
    "Goblin nap while you finish, ok? Burp.",
    "Goblin soul floating nearby... Skrreee.",
    "Ghost goblin reporting for duty! Zorp.",
    "Why boss so angry?! Meep!",
    "Add killed goblin... not even boss! Reek!",
    "Floor too comfy to get up. Blegh!",
    "This trial hard. Gobbo squish easy. Flarp.",
    "Goblin not tank! Stop hit goblin! Yarp!",
    "Oopsie daisy. goblin face tanked. Skrrt!",
    "Red circle hug too hard. Bwahaha!",
    "Goblin just practicing for hardmode death. Brapp!",
    "Down but not out... oh wait, out. Kekeke!",
    "Squish! Goes the goblin! SQUISH!",
    "Rez faster! goblin spirit getting bored! Snrk!",
    "Stuck in floor. Emotionally. Eep.",
    "RIP goblin... again. Blegh.",
    "Y’all got this! goblin cheer from death! Zog zog!",
    "F for gobbo... Gahhh!",
    "Death counter say hi again! Narf.",
    "Why does boss always step on goblin?! Gloop!",
    "Goblin down = party wipe? Flop!",
    "Goblin died for group... that sound noble. Meep.",
    "Dead again... where snack bag? Gyaa!",
    "Can’t fight... too dead. Meh.",
    "This wipe brought to you by goblin error. Squee!"
}
