GoblinStealthSayings = {
    "Hehehe, goblin sneaky, sneaky... no one see me, snrk!",
    "Gonna creep up, strike hard, then vanish, blargh!",
    "Sneak, sneak... then BANG! Goblin smashes, kekeke!",
    "You won’t see me coming... until it's too late, gyaa!",
    "Skrraaa! Goblin lurking, waiting to strike, meh!",
    "Goblin in shadows, goblin hit fast, hurrr!",
    "Quiet... then BOOM! You’ll regret that, fool, blegh!",
    "Shhh... goblin’s coming closer, reeek!",
    "Goblin’s power is in the shadows... you’ll never see it, nyah!",
    "No escape, goblin’s already there, skrrt!",
    "Zzzt! Sneak up and burn, gloop!",
    "Mess with goblin in stealth? You get a surprise, squish!",
    "Goblin creepin’, then smash! Honk!",
    "Slow or fast, goblin chooses! Zog zog!",
    "Brrrrap! Goblin strikes from shadows like thunder, pbbbt!",
    "Goblin’s favorite? Sneak up and hit hard! Gahhh!",
    "Stealth mode on! Goblin's got the drop on you, eep eep!",
    "Goblin don’t run, goblin just hides and waits, brap!",
    "Too slow, goblin already behind you, yarp!",
    "Boom! Sneak attack time, flarp!",
    "You can't stop me, goblin too quick in the shadows, squee!",
    "Hehe, goblin strikes when you least expect it, bwahaha!",
    "Zzzzap! From the shadows, fire comes, narf!",
    "Goblin sneaky, smash you in your sleep, plop!",
    "Goblin never backs down, but sometimes, goblin hides, gribbit!",
    "Fire and rocks, goblin strikes from the dark, mlem!",
    "Too slow for goblin in stealth, ha! splurt!",
    "No one escapes goblin's sneak attack, burp!",
    "Sneak up, smash ‘em all, yikesss!",
    "Goblin punch! You won’t see it coming, fizzz!",
    "Goblin no die! You die first, skrreee!",
    "You won’t escape this... not when goblin’s hiding, eep-o!",
    "Goblin squish you in stealth, gah!",
    "Goblin got moves in the shadows, crunch!",
    "Goblin too fast, too sneaky, hehe, zorp!",
    "Can’t run from goblin, not when he’s already behind you, grrr!",
    "Goblin gonna make you regret this, thwack!",
    "You’re too weak for goblin’s stealthy power, gulp!",
    "Goblin smash from the shadows, yoink!",
    "Goblin hit hard, you never saw it coming, bork!",
    "Goblin gonna break your bones in the dark, flop!",
    "Goblins never lose... we just hide, snrk!",
    "Goblin makes you wish you never came close, gronk!",
    "Feel the goblin sneak attack, chomp!",
    "Goblin smash you in the dark, squish!",
    "Goblins never run, we just get sneaky, zzzzap!",
    "You’re goblin’s now, sneaky fool, reeek!",
    "Time for a goblin stealth beatdown, blegh!",
    "Goblin always wins, even in the shadows, narf!",
    "Goblin never lose a fight... we wait in the dark, plop!",
    "Ha! Goblin crush you from behind, squish!",
    "Goblin love sneaky fights, yarp!",
    "Smash time? Not yet, gotta sneak, pbbbt!",
    "You can't stop goblin! Not when he's behind you, flarp!",
    "Goblin win, you never saw me, meep!",
    "You’re too slow for goblin’s sneak, squee!",
    "Goblin smash! You go boom, honk!",
    "You’re gonna feel this one, sneaky glorp!",
    "Goblin makes you regret sneaking up, bork!",
    "Zzzzap! Fire in the shadows, zorp!",
    "Don’t mess with goblin in stealth, squish!",
    "Boom! Goblin strikes harder from the shadows, skrrt!",
    "Goblin love smashing things, pbbbt!",
    "Goblin’s sneaky feet, coming for you, snrk!",
    "I’m here... but you won’t hear me, blargh!",
    "You think you’re safe? Think again, gyaa!",
    "I’m watching... waiting... strike! Brrrap!",
    "Goblin’s coming close... you won’t see me until it’s too late, meh!",
    "Shadows are my friend, strike from the dark, blegh!",
    "Goblin’s behind you, quick as a shadow, squee!",
    "Gonna catch you, gonna smash you, grrr!",
    "Not even the wind can hear me, flarp!",
    "Shhh... goblin sneaks up, then it’s over, squish!",
    "You’ll never hear goblin’s footsteps, plop!",
    "Stealth mode! Strike hard, strike fast, snrk!",
    "Goblin strikes from darkness... you won’t even know it, zzzzap!",
    "I'm already there, waiting for you, honk!",
    "Where’d goblin go? Behind you, gronk!",
    "Sneak, strike, disappear goblin way, yarp!",
    "You won’t even see goblin’s fist, squish!",
    "Too bad you’re not paying attention, blegh!",
    "Goblin’s coming from behind... no escape, plop!",
    "One step and you’re done, zorp!",
    "You’re too slow to stop me, gribbit!",
    "No chance, goblin’s already in position, fizzz!",
    "Goblin’s got you in his sights, hehe!",
    "The darkness is my playground, boom!",
    "Goblin waits, goblin strikes, blegh!",
    "I’m already there... strike time! Thwack!",
    "You’re already too late to stop goblin, squish!",
    "I’ll sneak up... then you’ll feel it, zzzzap!",
    "Sneaky goblin’s got a surprise for you, honk!",
    "You’re never gonna see goblin coming, squee!",
    "Don’t blink, goblin strikes in the shadows, glorp!",
    "Goblin in stealth... strike’s coming soon, gronk!",
    "You think you’re safe? Goblin’s already there, pbbbt!",
    "Stealth attack, no escape, skrrt!",
    "Goblin’s feet silent as night, strike now, squish!",
    "I’m already behind you, better watch out, fizzz!",
    "Goblin waits... then BOOM! You’re done, blegh!"
}
