local ArcanumGuildHall = _G["ArcanumGuildHall"]

ArcanumGuildHallLocalizationData = {

    de = {
        --Changelog
        CHANGELOG_TITLE = "<<1>> Changelog",
        CHANGELOG_FROM = "v<<1>> von <<2>>",
        --Changelog Text
        changelog_message = {
            "|cFFA500Arcanum Artis Version 1.22.0|r",
            "",
            "|cFFFF00Allgemein:|r",
            "[*] API-Anpassung auf Version 50 - Season Zero Pt. 2.",
            "",
            "|cFFFF00Folianten:|r",
            "[+] Fortschrittsbalken pro Aufgabe hinzugefügt (deaktivierbar in den Einstellungen).",
            "[+] Automatische Aufgabenverfolgung hinzugefügt (deaktivierbar in den Einstellungen).",
            "[+] Begonnene Aufgaben werden nun zuerst angezeigt.",
            "[*] Fortschritt wird nun farblich dargestellt: Grün = einsammelbar, Orange = in Arbeit.",
            "[*] Einsammelbare Aufgaben haben nun einen dezenten grünen Hintergrund.",
            "[*] Hover-Hervorhebung überarbeitet – keine Lücken mehr zwischen den Zeilen.",
            "[*] Fehler beim Hovern über die Schaltfläche 'Alle abholen' behoben.",
            "[*] Das Fenster wird nach einem Reroll nun sofort aktualisiert.",
            "",
            "|cFFFF00Einstellungen:|r",
            "[*] Fehler beim Zurücksetzen der Dekonstruktions-Standardeinstellungen behoben.",
            "",
        },
        --General
        NAME = "Arcanum Artis ",
        BUTTON_GROUPTOOL = "Gruppen Tool",
        PORT_GROUPLEADER = "Port zum Gruppenleiter",
        PORT_IN_HOUSE = "In das Haus reisen",
        PORT_FRONT_HOUSE = "Vor das Haus reisen",
        OUR_DISCORD = "Discord",
        MENU_LEFT = "|cBFBC99Gilden-Menü|r",
        MENU_RIGHT = "|cBFBC99Reparatur-Menü|r",
        SHARE_ALLDAILIES = "Teile alle Dailies",
        SHARE_ZONEDAILIES = "Teile Dailies der Zone",
        --Pledges
        PLEDGES_SPINDLE2 = "Spindeltiefen II",
        PLEDGES_BANISHED1 = "Verbannungs-Zellen I",
        PLEDGES_FUNGAL2 = "Pilzgrotte II",
        PLEDGES_SPINDLE1 = "Spindeltiefen I",
        PLEDGES_ELDEN1 = "Eldengrund I",
        PLEDGES_DARK2 = "Dunkelschattenkavernen II",
        PLEDGES_WAYREST2 = "Kanalisation von Wegesruh II",
        PLEDGES_FUNGAL1 = "Pilzgrotte I",
        PLEDGES_BANISHED2 = "Verbannungszellen II",
        PLEDGES_DARK1 = "Dunkelschattenkavernen I",
        PLEDGES_ELDEN2 = "Eldengrund II",
        PLEDGES_WAYREST1 = "Kanalisation von Wegesruh I",
        PLEDGES_DIREFROST = "Burg Grauenfrost",
        PLEDGES_VAULTS = "Kammern des Wahnsinns",
        PLEDGES_CRYPT2 = "Krypta der Herzen II",
        PLEDGES_CITY1 = "Stadt der Asche I",
        PLEDGES_TEMPEST = "Orkaninsel",
        PLEDGES_BLACKHEART = "Schwarzherz-Unterschlupf",
        PLEDGES_ARX = "Arx Corinium",
        PLEDGES_SELENES = "Selenes Netz",
        PLEDGES_CITY2 = "Stadt der Asche II",
        PLEDGES_CRYPT1 = "Krypta der Herzen I",
        PLEDGES_VOLENFELL = "Volenfell",
        PLEDGES_BLESSED = "Gesegnete Feuerprobe",
        PLEDGES_LAIR = "Hort von Maarselok",
        PLEDGES_ICEREACH = "Eiskap",
        PLEDGES_UNHALLOWED = "Unheiliges Grab",
        PLEDGES_STONE = "Steingarten",
        PLEDGES_CASTLE = "Kastell Dorn",
        PLEDGES_BLACKDRAKE = "Schwarzdrachenvilla",
        PLEDGES_CAULDRON = "Der Kessel",
        PLEDGES_IMPERIAL = "Gefängnis der Kaiserstadt",
        PLEDGES_MAZZATUN = "Ruinen von Mazzatun",
        PLEDGES_WHITEGOLD = "Weißgoldturm",
        PLEDGES_CRADLE = "Wiege der Schatten",
        PLEDGES_BLOODROOT = "Blutquell-Schmiede",
        PLEDGES_FALKREATH = "Falkenring",
        PLEDGES_FANGLAIR = "Krallenhort",
        PLEDGES_SCALECALLER = "Gipfel der Schuppenruferin",
        PLEDGES_MOONHUNTER = "Mondjägerfeste",
        PLEDGES_MARCH = "Marsch der Aufopferung",
        PLEDGES_MALATAR = "Tiefen von Malatar",
        PLEDGES_FROSTVAULT = "Frostgewölbe",
        PLEDGES_MOONGRAVE = "Mondgrab-Tempelstadt",
        PLEDGES_REDPETAL = "Rotblütenbastion",
        PLEDGES_DREADCELLAR = "Schreckenskeller",
        PLEDGES_CORALAERIE = "Der Korallenhorst",
        PLEDGES_SHIPWRIGHTSREGRET = "Der Gram des Schiffbauers",
        PLEDGES_EARTHENROOT = "Erdwurz-Enklave",
        PLEDGES_GRAVENDEEP = "Kentertiefen",
        PLEDGES_BALSUNNAR = "Bal Sunnar",
        PLEDGES_SCRIVENERSHALL = "Halle der Schriftmeister",
        PLEDGES_BEDLAMVEIL = "Schleier des Aufruhrs",
        PLEDGES_OATHSWORNPIT = "Grube der Eidgeschworenen",
        PLEDGES_EXILED = "Schanze der Abgeschiedenen",
        PLEDGES_SECLUSA = "Lep Seclusa",
        PLEDGES_BLACKGEM = "Schwarzstein-Gießerei",
        PLEDGES_CALDEESH = "Naj-Caldeesh",
        PLEDGES_NPC_MAJ = "[Maj al-Ragath]",
        PLEDGES_NPC_GLI = "[Glirion]",
        PLEDGES_NPC_URG = "[Urgarlag (DLC)]",
        PLEDGES_CHAT_DATE = "Tägliche Gelöbnisse vom ",
        PLEDGES_BUTTON = "Gelöbnisse",
        PLEDGES_BUTTON_SHOW = "Gelöbnisse im Chat anzeigen",
        PLEDGES_BUTTON_SEND = "Gelöbnisse im Chat einfügen",
        --Weekly Challenges
        CHALLENGES_WINDOW_TITLE = "Gelöbnisse & Prüfungen der Woche",
        CHALLENGES_WINDOW_DATE = "Datum:",
        CHALLENGES_WINDOW_PERIOD = "Zeitraum:",
        CHALLENGES_WINDOW_NEXT_DAILY_CHANGE = "Nächster Tageswechsel: ",
        CHALLENGES_WINDOW_NEXT_WEEKLY_CHANGE = "Nächster Wochenwechsel: ",
        CHALLENGES_WINDOW_SEND_BUTTON = "In den Chat einfügen",
        WEEKLY_CHALLENGES_TITLE = "Prüfungen der Woche",
        WEEKLY_CHALLENGES_TRIAL = "Prüfung: ",
        WEEKLY_CHALLENGES_SOLO = "Solo: ",
        -- Teleport
        TELEPORT_WINDOW_TITLE = "Arcanum Artis Teleport",
        TELEPORT_SEARCH_PLACEHOLDER = "Bitte Ziel eingeben",
        TELEPORT_ADD_FAVORITE = "Zu Favoriten hinzufügen",
        TELEPORT_DEL_FAVORITE = "Von Favoriten entfernen",
        TELEPORT_SHOW_FAVORITES = "Favoriten anzeigen",
        TELEPORT_DETAILS_TITLE = "Details",
        TELEPORT_DETAILS_SUBTITLE = "Informationen zum aktuellen Eintrag",
        TELEPORT_FILTER_LABEL = "Filter:",
        TELEPORT_BUTTON_REFRESH = "Aktualisieren",
        TELEPORT_BUTTON_TELEPORT = "Teleportieren",
        TELEPORT_TAB_NETWORK_TOOLTIP = "Spieler",
        TELEPORT_TAB_WAYSHRINES_TOOLTIP = "Bekannte Orte",
        TELEPORT_TAB_UNKNOWN_TOOLTIP = "Unbekannte Orte",
        TELEPORT_TAB_HOUSES_TOOLTIP = "Häuser",
        TELEPORT_TAB_GUILDHOUSES_TOOLTIP = "Gildenhäuser",
        TELEPORT_FILTER_ALL = "Alle",
        TELEPORT_FILTER_ZONE = "Ort",
        TELEPORT_FILTER_DUNGEON = "Verlies",
        TELEPORT_FILTER_TRIAL = "Raid",
        TELEPORT_FILTER_ARENA = "Arena",
        TELEPORT_FILTER_HOUSE_OWNED = "Besitz",
        TELEPORT_FILTER_HOUSE_UNOWNED = "Fehlend",
        TELEPORT_CATEGORY_ZONE = "Ort",
        TELEPORT_CATEGORY_DUNGEON = "Verlies",
        TELEPORT_CATEGORY_TRIAL = "Raid",
        TELEPORT_CATEGORY_ARENA = "Arena",
        TELEPORT_CATEGORY_HOUSE = "Haus",
        TELEPORT_LABEL_TARGET = "Ziel:",
        TELEPORT_LABEL_LOCATION = "Ort:",
        TELEPORT_LABEL_PLAYER = "Spieler:",
        TELEPORT_LABEL_SOURCE = "Quelle:",
        TELEPORT_LABEL_TYPE = "Typ:",
        TELEPORT_LABEL_STATUS = "Status:",
        TELEPORT_LABEL_COST = "Kosten:",
        TELEPORT_LABEL_HOUSE = "Haus:",
        TELEPORT_LABEL_OWNER = "Besitzer:",
        TELEPORT_VALUE_EMPTY = "-",
        TELEPORT_VALUE_KNOWN = "Bekannt",
        TELEPORT_VALUE_UNDISCOVERED = "Nicht entdeckt",
        TELEPORT_VALUE_HOUSE = "Haus",
        TELEPORT_VALUE_GUILD_HOUSE = "Gildenhaus",
        TELEPORT_VALUE_OWNED = "Im Besitz",
        TELEPORT_VALUE_UNOWNED = "Nicht erworben",
        TELEPORT_SOURCE_GROUP = "Gruppe",
        TELEPORT_SOURCE_FRIENDS = "Freunde",
        TELEPORT_SOURCE_GUILD = "Gilde",
        TELEPORT_SOURCE_ADDON = "Arcanum Artis",
        TELEPORT_TARGET_GUILD_HOUSE = "Gildenhaus",
        TELEPORT_LOADING_PLAYERS = "Lade Spieler ...",
        TELEPORT_LOADING_GUILD_MEMBERS = "Lade Gildenmitglieder (<<1>>/<<2>>) ...",
        TELEPORT_EMPTY_ENTRIES = "Keine Einträge gefunden",
        TELEPORT_DIVIDER_PRIMARY_HOUSE = "Eigenes Haupthaus",
        TELEPORT_DIVIDER_OWNED_HOUSES = "Im Besitz",
        TELEPORT_DIVIDER_UNOWNED_HOUSES = "Nicht erworben",
        TELEPORT_HINT_LIST_ACTION = "Klick: auswählen   |   Doppelklick: teleportieren",
        TELEPORT_CHAT_TRAVEL = "Du teleportierst dich nach: <<1>>.",
        TELEPORT_CHAT_TRAVEL_COST = "Du teleportierst dich nach: <<1>>. Das kostet dich <<2>> Gold.",
        TELEPORT_CHAT_INVALID_TARGET = "Ungültiges Ziel.",
        TELEPORT_CHAT_WAYSHRINE_UNKNOWN = "Leider ist dir dieser Wegschrein nicht bekannt und du kannst dich nicht dort hin teleportieren!",
        TELEPORT_CHAT_CANT_RECALL_AVA = "Du kannst dich aus dieser Zone nicht teleportieren.",
        -- Tome
        TOME_WINDOW_TITLE = "Foliantenübersicht",
        TOME_WINDOW_TAB_WEEKLY = "Wöchentlich",
        TOME_WINDOW_TAB_SEASONAL = "Saisonal",
        TOME_WINDOW_BUTTON_TRACK = "Verfolgen",
        TOME_WINDOW_BUTTON_UNTRACK = "Nicht mehr verfolgen",
        TOME_WINDOW_BUTTON_CLAIM = "Abholen",
        TOME_WINDOW_BUTTON_REROLL = "Erneuern",
        TOME_WINDOW_LABEL_NAME = "Aufgaben",
        TOME_WINDOW_LABEL_PROGRESS = "Fortschritt",
        TOME_WINDOW_LABEL_REWARD = "Belohnung",
        TOME_WINDOW_EMPTY = "Keine passenden Herausforderungen gefunden.",
        TOME_WINDOW_TIME_WEEKLY = "Weekly endet in",
        TOME_WINDOW_TIME_SEASONAL = "Saisonal endet in",
        TOME_WINDOW_BUTTON_REROLL_UNAVAILABLE = "Keine Rerolls mehr übrig",
        TOME_WINDOW_LABEL_TOTAL = "Gesamt:",
        TOME_ICON_UI_OPEN = "Foliantenfenster öffnen",
        TOME_WINDOW_BUTTON_CLAIM_ALL = "Alle abholen",
        TOME_WINDOW_BUTTON_CLAIM_ALL_TOOLTIP = "Alle verfügbaren Foliantenbelohnungen abholen.",
        TOME_WINDOW_BUTTON_CLAIM_ALL_UNAVAILABLE = "Keine Foliantenbelohnungen zum Abholen verfügbar.",
        -- Settings
        SETTINGS = "Einstellungen",
        SETTINGS_CHAT_ICON = "Chat Icon anzeigen",
        SETTINGS_MONOCHROME_ICON = "Einfarbiges Icon",
        SETTINGS_HEADER_NAMES = "Namen einfärben",
        SETTINGS_HEADER_NAMES_DESCRIPTION = "Färbe hier die Namen der Gildenmitglieder in die jeweilige Rangfarbe welche diese besitzen.",
        SETTINGS_COLORIZE_GUILD_NAMES = "Mitgliedernamen einfärben",
        SETTINGS_NOGUILDLEAVE = "\"Gilde verlassen\"-Button deaktivieren",
        SETTINGS_NOGUILDLEAVE_CHOICE0 = "Aus",
        SETTINGS_NOGUILDLEAVE_CHOICE1 = "Nur Arcanum Artis",
        SETTINGS_NOGUILDLEAVE_CHOICE2 = "Alle Gilden",
        SETTINGS_HEADER_NOTIFICATION = "Benachrichtigungen",
        SETTINGS_TOME_HEADER_CHAT = "Chat",
        SETTINGS_TOME_HEADER_WINDOW = "Fenster",
        SETTINGS_TOME_TITLE = "Folianten",
        SETTINGS_TOME_ENABLE = "Fortschritt anzeigen",
        SETTINGS_TOME_LOCATION = "Anzeigeort",
        SETTINGS_TOME_ICON = "Arcanum Icon anzeigen",
        SETTINGS_TOME_ICON_UI = "Folianten Icon anzeigen",
        SETTINGS_TOME_CHOICE0 = "Chatfenster",
        SETTINGS_TOME_CHOICE1 = "Bildschirm",
        SETTINGS_TOME_COLOR_WEEKLY = "Textfarbe (wöchentliche Herausforderungen)",
        SETTINGS_TOME_COLOR_SEASONAL = "Textfarbe (saisonale Herausforderungen)",
        SETTINGS_TOME_REWARD = "Belohnung in [] darstellen",
        SETTINGS_TOME_SEASONAL_PROGRESS = "Saisonalen Fortschritt immer anzeigen",
        SETTINGS_TOME_CLAIM = "Foliantenpunkte automatisch abholen",
        SETTINGS_TOME_AUTO_TRACK = "Aufgabe automatisch verfolgen",
        SETTINGS_TOME_PROGRESS_BAR = "Fortschrittsbalken anzeigen",
        SETTINGS_TOME_WINDOW_INFO = "Fenster der Übersicht über das Icon oder mit /tomes öffnen.",
        SETTINGS_TOME_COMPACT_MODE = "Kompakter Fenstermodus",
        SETTINGS_TOME_BGTRANSPARENCY = "Fenster Transparenz",
        SETTINGS_CLOCK_TITLE = "Uhrzeit",
        SETTINGS_CLOCK_SHOW = "Uhr anzeigen",
        SETTINGS_CLOCK_COMBAT = "Im Kampf Uhr rot färben",
        SETTINGS_CLOCK_DST = "Sommer/Winterzeit",
        SETTINGS_CLOCK_COLOR = "Schriftfarbe",
        SETTINGS_CLOCK_FONT = "Schriftart",
        SETTINGS_CLOCK_FONTSIZE = "Schriftgröße",
        SETTINGS_CLOCK_OUTLINE = "Umrandung",
        SETTINGS_CLOCK_BG = "Hintergrund",
        SETTINGS_CLOCK_BGCOLOR = "Hintergrundfarbe",
        SETTINGS_CLOCK_BGTRANSPARENCY = "Transparenz",
        SETTINGS_CLOCK_HEADER_INGAMETIME = "Tamriel Zeit (InGame Zeit)",
        SETTINGS_CLOCK_SHOW_INGAMETIME = "Tamriel Zeit anzeigen",
        SETTINGS_CLOCK_INGAMETIME_FONTRATIO = "Größenunterschied",
        SETTINGS_CLOCK_SHOW_BG = "Hintergrund anzeigen",
        SETTINGS_CHAT_TITLE = "Chat",
        SETTINGS_CHAT_SHOW_TIMESTAMP = "Zeitstempel anzeigen",
        SETTINGS_CHAT_SHOW_RANKICONS = "Gildenränge anzeigen",
        SETTINGS_CHAT_SHOW_RANKICONSCOLOR = "Icon in die Farbe des Gildenranges einfärben",
        SETTINGS_CHAT_TIMESTAMP_COLOR = "Schriftfarbe",
        SETTINGS_SHOWRANKICON_CHOICE0 = "Aus",
        SETTINGS_SHOWRANKICON_CHOICE1 = "Alle Mitglieder",
        SETTINGS_SHOWRANKICON_CHOICE2 = "Nur Offiziere",
        SETTINGS_ANNOUNCEMENTS_TITLE = "Ankündigungen",
        SETTINGS_ANNOUNCEMENTS_SHOW_SCREEN = "Auf dem Bildschirm anzeigen",
        SETTINGS_ANNOUNCEMENTS_SHOW_CHAT = "Im Chat anzeigen",
        SETTINGS_ANNOUNCEMENTS_SHOW_NOTIF = "In Benachrichtigungen anzeigen",
        SETTINGS_SHOW_CHANGELOG = "Changelog automatisch öffnen [Update]",
        SETTINGS_SHOW_CHANGELOGBUTTON = "Changelog öffnen",
        SETTINGS_CHALLENGES_TITLE = "Gelöbnisse & Prüfungen der Woche",
        SETTINGS_TOOLTIP_CHALLENGES = "Lege fest, ob Gelöbnisse und Prüfungen der Woche über das Chat-Icon direkt im Chat angezeigt oder über ein gemeinsames Fenster geöffnet werden.",
        SETTINGS_CHALLENGES_MODE = "Anzeigemodus",
        SETTINGS_CHALLENGES_MODE_CHAT = "Chat",
        SETTINGS_CHALLENGES_MODE_WINDOW = "Fenster",
        SETTINGS_DECON_TITLE = "Verwerten",
        SETTINGS_TOOLTIP_DECON = "Einstellungen rund um das automatische auswählen beim verwerten findest du hier.",
        SETTINGS_DECON_SELECT_TITLE = "Qualität & Eigenschaft",
        SETTINGS_DECON_LABEL_RESEARCH = "Analysierbar",
        SETTINGS_DECON_LABEL_ORNATE = "Verziert",
        SETTINGS_DECON_LABEL_INTRICATE = "Intrikat",
        --Tooltips
        SETTINGS_TOOLTIP_NOGUILDLEAVE = "Du kannst hier festlegen ob du den Button \"Gilde verlassen\" ausblendest.",
        SETTINGS_TOOLTIP_MEMBER = "Stelle hier ein ob dir die Namen der Gildenmitglieder farblich anhand des jeweiligen Ranges dargestellt werden sollen.",
        SETTINGS_TOOLTIP_NOTIFICATIONS = "Stelle hier ein ob du bezüglich der Gildenlotterie benachrichtigt werden möchtest.",
        SETTINGS_TOOLTIP_TOMES = "Stelle hier ein ob du eine Anzeige bezüglich der Folianten-Herausforderungen haben möchtest.",
        SETTINGS_TOOLTIP_TOME_SEASONAL_PROGRESS = "Wenn deaktiviert, werden saisonale Herausforderungen nur bei Abschluss gemeldet.",
        SETTINGS_TOOLTIP_TOME_AUTO_TRACK = "Verfolgt automatisch die am weitesten fortgeschrittene offene Aufgabe wenn keine aktiv verfolgt wird.",
        SETTINGS_NOTIFICATION_HEADER_TOOLTIP = "Lege hier den Titel deiner Benachrichtigung fest.",
        SETTINGS_NOTIFICATION_MESSAGE_TOOLTIP = "Lege hier fest worüber du benachrichtigt werden möchtest.",
        SETTINGS_TOOLTIP_CLOCK = "Hier findest du alle Einstellungen für die Uhrzeit.",
        SETTINGS_TOOLTIP_BGCOLOR = "Die Hintergrundfarbe ändert sich nur bei der Option Solid.",
        SETTINGS_TOOLTIP_CHAT = "Hier kannst du die Chat-Funktionen aktivieren oder deaktvieren sowie diese bearbeiten.",
        SETTINGS_TOOLTIP_ANNOUNCEMENTS = "Stelle hier ein ob und wo du dir die Ankündigung der Gilde angezeigt werden soll.",
        SETTINGS_TOOLTIP_REPAIR = "Hier findest du alle Einstellungen bezüglich für die Reparatur und Aufladefunktion.",
        SETTINGS_TOOLTIP_REPAIR_THRESHOLD = "Stelle hier ein ab wann eine Reparatur durchgeführt werden kann [% der Beschädigung].",
        SETTINGS_TOOLTIP_RECHARGE_THRESHOLD = "Stelle hier ein ab wann eine Aufladung durchgeführt werden kann [% der Aufladung] |c880000Für automatisches aufladen empfiehlt es sich den Wert so gering wie möglich zu setzen!|r.",
        SETTINGS_TOOLTIP_REPAIR_STORES = "Stelle hier ein ob und was beim öffnen eines Händlers repariert werden soll.",
        -- Notifications
        SETTINGS_NOTIFICATION_DAYS = "Wochentag",
        SETTINGS_NOTIFICATION_CHOICE_0 = "Montag",
        SETTINGS_NOTIFICATION_CHOICE_1 = "Dienstag",
        SETTINGS_NOTIFICATION_CHOICE_2 = "Mittwoch",
        SETTINGS_NOTIFICATION_CHOICE_3 = "Donnerstag",
        SETTINGS_NOTIFICATION_CHOICE_4 = "Freitag",
        SETTINGS_NOTIFICATION_CHOICE_5 = "Samstag",
        SETTINGS_NOTIFICATION_CHOICE_6 = "Sonntag",
        SETTINGS_NOTIFICATION_TITLE = "Arcanum Artis",
        SETTINGS_NOTIFICATION_TEXT = "Vergiss nicht ein Lotterielos zu kaufen um an der wöchentlichen Gildenlotterie teilnehmen zu können.",
        SETTINGS_NOTIFICATION_ACTIVE = "Benachrichtigungen",
        SETTINGS_NOTIFICATION_CHANGE_ACTIVE = "Eigene Benachrichtigung",
        SETTINGS_NOTIFICATION_CHANGE_HEADER = "Kopfzeile",
        SETTINGS_NOTIFICATION_CHANGE_MESSAGE = "Benachrichtigung",
        SETTINGS_NOTIFICATION_WARN_HEADER = "Maximal 25 Zeichen erlaubt!",
        SETTINGS_NOTIFICATION_WARN_MESSAGE = "Maximal 50 Zeichen erlaubt!",
        SETTINGS_NOTIFICATION_RESET = "Zurücksetzen",
        SETTINGS_NOTIFICATION_MESSAGE_FIRST = "Möchtest du die Erinnerung zur Gildenlotterie aktivieren? Du kannst dies auch nachträglich in den Einstellungen anpassen.",
        ANNOUNCEMENTS_TEXT = "WICHTIGE INFORMATION",
        -- Chat Outputs
        CHAT_SHARED = "Es wurden <<1>> Quests geteilt.",
        CHAT_NO_DAILIES_TO_SHARE = "Es gibt keine täglichen Quests zum Teilen.",
        CHAT_SHARING = "Es werden die täglichen Quests aus <<1>> geteilt.",
        CHAT_SHARING_ALL = "Es werden <<1>> tägliche Quests geteilt.",
        CHAT_REPAIRED = "<<1>> wurde von <<2>> auf <<3>> repariert.",
        CHAT_RECHARGED = "<<1>> wurde von <<2>> auf <<3>> aufgeladen.",
        CHAT_SHOP_REPAIRED_DECLINED = "<<1>> konnte nicht repariert werden. Kosten: <<2>>.",
        CHAT_SHOP_REPAIRED = "<<1>> wurde für <<2>> repariert.",
        CHAT_REPAIR_COST = "Gesamte Reparaturkosten: <<1>>.",
        CHAT_SHOP_REPAIRED_COST = "Die gesamte Ausrüstung wurde für <<1>> repariert.",
        CHAT_SHOP_REPAIRED_DECLINED2 = "Die gesamte Ausrüstung konnte nicht repariert werden. Benötigt: <<1>>.",
        CHAT_WELCOME_MESSAGE = "%s %sAddon geladen, %s %s!|r",
        CHAT_WELCOME_MESSAGE_MORNING = "Guten Morgen",
        CHAT_WELCOME_MESSAGE_MIDDAY = "Hallo",
        CHAT_WELCOME_MESSAGE_EVENING = "Guten Abend",
        CHAT_NOTHING_TO_REPAIR = "Aktuell gibt es nichts zu reparieren, der Schwellenwert von <<1>>% wurde noch nicht erreicht.",
        CHAT_NOTHING_TO_RECHARGE = "Aktuell gibt es nichts aufzuladen, der Schwellenwert von <<1>>% wurde noch nicht erreicht.",
        CHAT_NOTHING_TO_REPAIR_RECHARGE = "Aktuell gibt es weder etwas zu reparieren noch aufzuladen, die Schwellenwerte wurden noch nicht erreicht.",
        --PlayerContextMenu
        CHAT_NEW_MESSAGE = "Neue Nachricht",
        CHAT_NEW_RANK = "-Rang:",
        CHAT_NEW_INVITE = "Einladen in",
        --Repair
        SETTINGS_REPAIR_TITLE = "Reparieren & Aufladen",
        SETTINGS_REPAIR_STORES_HEADER = "Händler",
        SETTINGS_REPAIR_STORES = "Autom. reparieren beim Händler",
        SETTINGS_REPAIR_STORES_CHOICE0 = "Alles",
        SETTINGS_REPAIR_STORES_CHOICE1 = "Ausgerüstet",
        SETTINGS_REPAIR_STORES_CHOICE2 = "Nichts",
        SETTINGS_REPAIR_PRINT = "Im Chat anzeigen",
        SETTINGS_REPAIR_HEADER = "Reparieren",
        SETTINGS_REPAIR_KIT = "Jedes Reparaturset verwenden",
        SETTINGS_REPAIR_THRESHOLD = "Schwelle für Reparatur",
        SETTINGS_RECHARGE_HEADER = "Aufladen",
        SETTINGS_RECHARGE_GEM = "Jeden Seelenstein verwenden",
        SETTINGS_RECHARGE_THRESHOLD = "Schwelle für Aufladen",
        SETTINGS_RECHARGE_AUTO = "Automatisch Aufladen",
        SETTINGS_RECHARGE_CHOICE0 = "Immer",
        SETTINGS_RECHARGE_CHOICE1 = "Im Raid",
        SETTINGS_RECHARGE_CHOICE2 = "Niemals",
        --TakeOneFromInventory
        TAKE_LABEL = "Nur eines entnehmen",
        TAKE_FAILURE = "Fehler: Nicht genügen Platz im Inventar [Es müssen mind. 2 Plätze frei sein].",
        TAKE_PROCESS = "Es wird 1 / <<1>> des Items <<2>> entnommen.",
        TAKE_RETURN = "Erfolgreich entnommen und rest wieder in Gildenbank eingelagert.",
        --Deconstruction
        DECON_LABEL = "Alles auswählen",
        --Bindings
        BINDING_OPEN_SETTINGS = "Einstellungen öffnen",
        BINDING_REPAIR_RECHARGE = "Reparieren & Aufladen",
        BINDING_REPAIR_WITH_KITS = "Ausrüstung reparieren",
        BINDING_RECHARGE_WITH_GEMS = "Waffen aufladen",
        BINDING_OPEN_TOMES_WINDOW = "Folianten öffnen",
    },

    en = {
        --Changelog
        CHANGELOG_TITLE = "<<1>> Changelog",
        CHANGELOG_FROM = "v<<1>> from <<2>>",
        --Changelog Text
        changelog_message = {
            "|cFFA500Arcanum Artis Version 1.22.0|r",
            "",
            "|cFFFF00General:|r",
            "[*] API bump to version 50 - Season Zero Pt. 2.",
            "",
            "|cFFFF00Tomes:|r",
            "[+] Added progress bar per task, toggleable in settings.",
            "[+] Added automatic task tracking when nothing is actively tracked, toggleable in settings.",
            "[+] In-progress tasks are now sorted to the top.",
            "[*] Task progress is now colour-coded: green = claimable, orange = in progress.",
            "[*] Claimable tasks now have a subtle green background.",
            "[*] Fixed hover highlight to cover full row height with no gaps between rows.",
            "[*] Fixed error when hovering over the claim all button.",
            "[*] Window now refreshes immediately after a reroll.",
            "",
            "|cFFFF00Settings:|r",
            "[*] Fixed deconstruction quality defaults resetting to the wrong values.",
            "",
        },
        -- English Language Localization
        NAME = "Arcanum Artis",
        BUTTON_GROUPTOOL = "Group Tool",
        PORT_GROUPLEADER = "Port to Group Leader",
        PORT_IN_HOUSE = "Travel into the house",
        PORT_FRONT_HOUSE = "Travel in front of the house",
        OUR_DISCORD = "Discord",
        MENU_LEFT = "|cBFBC99Guild Menu|r",
        MENU_RIGHT = "|cBFBC99Repair Menu|r",
        SHARE_ALLDAILIES = "Share all dailies",
        SHARE_ZONEDAILIES = "Share all dailies from zone",
        --Pledges
        PLEDGES_SPINDLE2 = "Spindleclutch II",
        PLEDGES_BANISHED1 = "Banished Cells I",
        PLEDGES_FUNGAL2 = "Fungal Grotto II",
        PLEDGES_SPINDLE1 = "Spindleclutch I",
        PLEDGES_ELDEN1 = "Elden Hollow I",
        PLEDGES_DARK2 = "Darkshade Caverns II",
        PLEDGES_WAYREST2 = "Wayrest Sewers II",
        PLEDGES_FUNGAL1 = "Fungal Grotto I",
        PLEDGES_BANISHED2 = "Banished Cells II",
        PLEDGES_DARK1 = "Darkshade Caverns I",
        PLEDGES_ELDEN2 = "Elden Hollow II",
        PLEDGES_WAYREST1 = "Wayrest Sewers I",
        PLEDGES_DIREFROST = "Direfrost Keep",
        PLEDGES_VAULTS = "Vaults of Madness",
        PLEDGES_CRYPT2 = "Crypt of Hearts II",
        PLEDGES_CITY1 = "City of Ash I",
        PLEDGES_TEMPEST = "Tempest Island",
        PLEDGES_BLACKHEART = "Blackheart Haven",
        PLEDGES_ARX = "Arx Corinium",
        PLEDGES_SELENES = "Selene’s Web",
        PLEDGES_CITY2 = "City of Ash II",
        PLEDGES_CRYPT1 = "Crypt of Hearts I",
        PLEDGES_VOLENFELL = "Volenfell",
        PLEDGES_BLESSED = "Blessed Crucible",
        PLEDGES_LAIR = "Lair of Maarselok",
        PLEDGES_ICEREACH = "Icereach",
        PLEDGES_UNHALLOWED = "Unhallowed Grave",
        PLEDGES_STONE = "Stone Garden",
        PLEDGES_CASTLE = "Castle Thorn",
        PLEDGES_BLACKDRAKE = "Black Drake Villa",
        PLEDGES_CAULDRON = "The Cauldron",
        PLEDGES_IMPERIAL = "Imperial City Prison",
        PLEDGES_MAZZATUN = "Ruins of Mazzatun",
        PLEDGES_WHITEGOLD = "White Gold Tower",
        PLEDGES_CRADLE = "Cradle of Shadows",
        PLEDGES_BLOODROOT = "Bloodroot Forge",
        PLEDGES_FALKREATH = "Falkreath Hold",
        PLEDGES_FANGLAIR = "Fang Lair",
        PLEDGES_SCALECALLER = "Scalecaller Peak",
        PLEDGES_MOONHUNTER = "Moon Hunter Keep",
        PLEDGES_MARCH = "March of Sacrifices",
        PLEDGES_MALATAR = "Depths of Malatar",
        PLEDGES_FROSTVAULT = "Frostvault",
        PLEDGES_MOONGRAVE = "Moongrave Fane",
        PLEDGES_REDPETAL = "Red Petal Bastion",
        PLEDGES_DREADCELLAR = "The Dread Cellar",
        PLEDGES_CORALAERIE = "Coral Aerie",
        PLEDGES_SHIPWRIGHTSREGRET = "Shipwright's Regret",
        PLEDGES_EARTHENROOT = "Earthen Root Enclave",
        PLEDGES_GRAVENDEEP = "Graven Deep",
        PLEDGES_BALSUNNAR = "Bal Sunnar",
        PLEDGES_SCRIVENERSHALL = "Scrivener’s Hall",
        PLEDGES_BEDLAMVEIL = "Bedlam Veil",
        PLEDGES_OATHSWORNPIT = "Oathsworn Pit",
        PLEDGES_EXILED = "Exiled Redoubt ",
        PLEDGES_SECLUSA = "Lep Seclusa",
        PLEDGES_BLACKGEM = "Black Gem Foundry",
        PLEDGES_CALDEESH = "Naj-Caldeesh",
        PLEDGES_NPC_MAJ = "[Maj al-Ragath]",
        PLEDGES_NPC_GLI = "[Glirion]",
        PLEDGES_NPC_URG = "[Urgarlag (DLC)]",
        PLEDGES_CHAT_DATE = "Daily pledges from ",
        PLEDGES_BUTTON = "Pledges",
        PLEDGES_BUTTON_SHOW = "Show pledges in chat",
        PLEDGES_BUTTON_SEND = "Insert pledges into chat",
        --Weekly Challenges
        CHALLENGES_WINDOW_TITLE = "Pledges & Weekly Challenges",
        CHALLENGES_WINDOW_DATE = "Date:",
        CHALLENGES_WINDOW_PERIOD = "Period:",
        CHALLENGES_WINDOW_NEXT_DAILY_CHANGE = "Next daily reset: ",
        CHALLENGES_WINDOW_NEXT_WEEKLY_CHANGE = "Next weekly reset: ",
        CHALLENGES_WINDOW_SEND_BUTTON = "Insert into Chat",
        WEEKLY_CHALLENGES_TITLE = "Weekly Challenges",
        WEEKLY_CHALLENGES_TRIAL = "Trial: ",
        WEEKLY_CHALLENGES_SOLO = "Solo: ",
        -- Teleport
        TELEPORT_WINDOW_TITLE = "Arcanum Artis Teleport",
        TELEPORT_SEARCH_PLACEHOLDER = "Please enter a destination",
        TELEPORT_ADD_FAVORITE = "Add to Favorites",
        TELEPORT_DEL_FAVORITE = "Remove from Favorites",
        TELEPORT_SHOW_FAVORITES = "Show Favorites",
        TELEPORT_DETAILS_TITLE = "Details",
        TELEPORT_DETAILS_SUBTITLE = "Information about the current entry",
        TELEPORT_FILTER_LABEL = "Filter:",
        TELEPORT_BUTTON_REFRESH = "Refresh",
        TELEPORT_BUTTON_TELEPORT = "Teleport",
        TELEPORT_TAB_NETWORK_TOOLTIP = "Players",
        TELEPORT_TAB_WAYSHRINES_TOOLTIP = "Known locations",
        TELEPORT_TAB_UNKNOWN_TOOLTIP = "Unknown locations",
        TELEPORT_TAB_HOUSES_TOOLTIP = "Houses",
        TELEPORT_TAB_GUILDHOUSES_TOOLTIP = "Guild houses",
        TELEPORT_FILTER_ALL = "All",
        TELEPORT_FILTER_ZONE = "Location",
        TELEPORT_FILTER_DUNGEON = "Dungeon",
        TELEPORT_FILTER_TRIAL = "Trial",
        TELEPORT_FILTER_ARENA = "Arena",
        TELEPORT_FILTER_HOUSE_OWNED = "Owned",
        TELEPORT_FILTER_HOUSE_UNOWNED = "Unowned",
        TELEPORT_CATEGORY_ZONE = "Location",
        TELEPORT_CATEGORY_DUNGEON = "Dungeon",
        TELEPORT_CATEGORY_TRIAL = "Trial",
        TELEPORT_CATEGORY_ARENA = "Arena",
        TELEPORT_CATEGORY_HOUSE = "House",
        TELEPORT_LABEL_TARGET = "Target:",
        TELEPORT_LABEL_LOCATION = "Location:",
        TELEPORT_LABEL_PLAYER = "Player:",
        TELEPORT_LABEL_SOURCE = "Source:",
        TELEPORT_LABEL_TYPE = "Type:",
        TELEPORT_LABEL_STATUS = "Status:",
        TELEPORT_LABEL_COST = "Cost:",
        TELEPORT_LABEL_HOUSE = "House:",
        TELEPORT_LABEL_OWNER = "Owner:",
        TELEPORT_VALUE_EMPTY = "-",
        TELEPORT_VALUE_KNOWN = "Known",
        TELEPORT_VALUE_UNDISCOVERED = "Undiscovered",
        TELEPORT_VALUE_HOUSE = "House",
        TELEPORT_VALUE_GUILD_HOUSE = "Guild house",
        TELEPORT_VALUE_OWNED = "Owned",
        TELEPORT_VALUE_UNOWNED = "Unowned",
        TELEPORT_SOURCE_GROUP = "Group",
        TELEPORT_SOURCE_FRIENDS = "Friends",
        TELEPORT_SOURCE_GUILD = "Guild",
        TELEPORT_SOURCE_ADDON = "Arcanum Artis",
        TELEPORT_TARGET_GUILD_HOUSE = "Guild house",
        TELEPORT_LOADING_PLAYERS = "Loading players ...",
        TELEPORT_LOADING_GUILD_MEMBERS = "Loading guild members (<<1>>/<<2>>) ...",
        TELEPORT_EMPTY_ENTRIES = "No entries found",
        TELEPORT_DIVIDER_PRIMARY_HOUSE = "Primary house",
        TELEPORT_DIVIDER_OWNED_HOUSES = "Owned",
        TELEPORT_DIVIDER_UNOWNED_HOUSES = "Unowned",
        TELEPORT_HINT_LIST_ACTION = "Click: select   |   Double-click: teleport",
        TELEPORT_CHAT_TRAVEL = "You are teleporting to: <<1>>.",
        TELEPORT_CHAT_TRAVEL_COST = "You are teleporting to: <<1>>. This costs you <<2>> gold.",
        TELEPORT_CHAT_INVALID_TARGET = "Invalid target.",
        TELEPORT_CHAT_WAYSHRINE_UNKNOWN = "Unfortunately, you are not familiar with this wayshrine and cannot teleport there!",
        TELEPORT_CHAT_CANT_RECALL_AVA = "You cannot teleport from this zone.",
        -- Tome
        TOME_WINDOW_TITLE = "Tome Overview",
        TOME_WINDOW_TAB_WEEKLY = "Weekly",
        TOME_WINDOW_TAB_SEASONAL = "Seasonal",
        TOME_WINDOW_BUTTON_TRACK = "Track",
        TOME_WINDOW_BUTTON_UNTRACK = "Untrack",
        TOME_WINDOW_BUTTON_CLAIM = "Claim",
        TOME_WINDOW_BUTTON_REROLL = "Reroll",
        TOME_WINDOW_LABEL_NAME = "Challenges",
        TOME_WINDOW_LABEL_PROGRESS = "Progress",
        TOME_WINDOW_LABEL_REWARD = "Reward",
        TOME_WINDOW_EMPTY = "No matching challenges found.",
        TOME_WINDOW_TIME_WEEKLY = "Weekly ends in",
        TOME_WINDOW_TIME_SEASONAL = "Seasonal ends in",
        TOME_WINDOW_BUTTON_REROLL_UNAVAILABLE = "No rerolls left",
        TOME_WINDOW_LABEL_TOTAL = "Total:",
        TOME_ICON_UI_OPEN = "Open Tome window",
        TOME_WINDOW_BUTTON_CLAIM_ALL = "Claim All",
        TOME_WINDOW_BUTTON_CLAIM_ALL_TOOLTIP = "Claim all available Tome rewards.",
        TOME_WINDOW_BUTTON_CLAIM_ALL_UNAVAILABLE = "No Tome rewards available to claim.",
        -- Settings
        SETTINGS = "Settings",
        SETTINGS_CHAT_ICON = "Show chat icon",
        SETTINGS_MONOCHROME_ICON = "Monochrome icon",
        SETTINGS_HEADER_NAMES = "Color names",
        SETTINGS_HEADER_NAMES_DESCRIPTION = "Color the names of the guild members here in the respective rank color they possess.",
        SETTINGS_COLORIZE_GUILD_NAMES = "Color member names",
        SETTINGS_NOGUILDLEAVE = "Deactivate \"Leave guild\"-button",
        SETTINGS_NOGUILDLEAVE_CHOICE0 = "Off",
        SETTINGS_NOGUILDLEAVE_CHOICE1 = "Only Arcanum Artis",
        SETTINGS_NOGUILDLEAVE_CHOICE2 = "All guilds",
        SETTINGS_HEADER_NOTIFICATION = "Notifications",
        SETTINGS_TOME_HEADER_CHAT = "Chat",
        SETTINGS_TOME_HEADER_WINDOW = "Window",
        SETTINGS_TOME_TITLE = "Tomes",
        SETTINGS_TOME_ENABLE = "Show progress",
        SETTINGS_TOME_LOCATION = "Location",
        SETTINGS_TOME_ICON = "Show Arcanum icon",
        SETTINGS_TOME_ICON_UI = "Show Tomes icon",
        SETTINGS_TOME_CHOICE0 = "Chat window",
        SETTINGS_TOME_CHOICE1 = "Screen",
        SETTINGS_TOME_COLOR_WEEKLY = "Text color (weekly challenges)",
        SETTINGS_TOME_COLOR_SEASONAL = "Text color (seasonal challenges)",
        SETTINGS_TOME_REWARD = "Display reward in []",
        SETTINGS_TOME_SEASONAL_PROGRESS = "Always show seasonal progress",
        SETTINGS_TOME_CLAIM = "Auto-claim Tome points",
        SETTINGS_TOME_AUTO_TRACK = "Auto-track task",
        SETTINGS_TOME_PROGRESS_BAR = "Show progress bar",
        SETTINGS_TOME_WINDOW_INFO = "Open the Tome window via the window icon or with /tomes.",
        SETTINGS_TOME_COMPACT_MODE = "Compact window mode",
        SETTINGS_TOME_BGTRANSPARENCY = "Window transparency",
        SETTINGS_CLOCK_TITLE = "Clock",
        SETTINGS_CLOCK_SHOW = "Show clock",
        SETTINGS_CLOCK_COMBAT = "In combat dye clock red",
        SETTINGS_CLOCK_DST = "DST-Support",
        SETTINGS_CLOCK_COLOR = "Change color",
        SETTINGS_CLOCK_FONT = "Font",
        SETTINGS_CLOCK_FONTSIZE = "Font size",
        SETTINGS_CLOCK_OUTLINE = "Outline",
        SETTINGS_CLOCK_BG = "Background",
        SETTINGS_CLOCK_BGCOLOR = "Background color",
        SETTINGS_CLOCK_BGTRANSPARENCY = "Transparency",
        SETTINGS_CLOCK_HEADER_INGAMETIME = "Tamriel Time (InGame Time)",
        SETTINGS_CLOCK_SHOW_INGAMETIME = "Show Tamriel Time",
        SETTINGS_CLOCK_INGAMETIME_FONTRATIO = "Tamriel Time Font ratio",
        SETTINGS_CLOCK_SHOW_BG = "Show Background",
        SETTINGS_CHAT_TITLE = "Chat",
        SETTINGS_CHAT_SHOW_TIMESTAMP = "Show timestamp",
        SETTINGS_CHAT_SHOW_RANKICONS = "Show guildranks",
        SETTINGS_CHAT_SHOW_RANKICONSCOLOR = "Dye the icon in the color of the guild rank",
        SETTINGS_CHAT_TIMESTAMP_COLOR = "Textcolor",
        SETTINGS_SHOWRANKICON_CHOICE0 = "Off",
        SETTINGS_SHOWRANKICON_CHOICE1 = "All Members",
        SETTINGS_SHOWRANKICON_CHOICE2 = "Only Officers",
        SETTINGS_ANNOUNCEMENTS_TITLE = "Announcements",
        SETTINGS_ANNOUNCEMENTS_SHOW_SCREEN = "Show on Screen",
        SETTINGS_ANNOUNCEMENTS_SHOW_CHAT = "Show in Chat",
        SETTINGS_ANNOUNCEMENTS_SHOW_NOTIF = "Show in notifications",
        SETTINGS_SHOW_CHANGELOG = "Open Changelog automatically [Update]",
        SETTINGS_SHOW_CHANGELOGBUTTON = "Open Changelog",
        SETTINGS_CHALLENGES_TITLE = "Pledges & Weekly Challenges",
        SETTINGS_TOOLTIP_CHALLENGES = "Choose whether pledges and weekly challenges should be shown directly in chat from the chat icon or opened in a combined window.",
        SETTINGS_CHALLENGES_MODE = "Display mode",
        SETTINGS_CHALLENGES_MODE_CHAT = "Chat",
        SETTINGS_CHALLENGES_MODE_WINDOW = "Window",
        SETTINGS_DECON_TITLE = "Deconstruction",
        SETTINGS_TOOLTIP_DECON = "Settings related to automatic selection during deconstruction can be found here.",
        SETTINGS_DECON_SELECT_TITLE = "Quality & Trait",
        SETTINGS_DECON_LABEL_RESEARCH = "Analyzable",
        SETTINGS_DECON_LABEL_ORNATE = "Ornate",
        SETTINGS_DECON_LABEL_INTRICATE = "Intricate",
        --Tooltips
        SETTINGS_TOOLTIP_NOGUILDLEAVE = "You can decide here whether you want to hide the \"Leave guild\"-button",
        SETTINGS_TOOLTIP_MEMBER = "Set here whether the names of the guild members should be displayed in color according to their respective rank.",
        SETTINGS_TOOLTIP_NOTIFICATIONS = "Set here if you want to be notified about the guild lottery.",
        SETTINGS_TOOLTIP_TOMES = "Choose here whether you want progress alerts for Tamriel Tome challenges.",
        SETTINGS_TOOLTIP_TOME_SEASONAL_PROGRESS = "If disabled, seasonal challenges are only shown when completed.",
        SETTINGS_TOOLTIP_TOME_AUTO_TRACK = "Automatically tracks the most progressed incomplete task when none is currently tracked.",
        SETTINGS_NOTIFICATION_HEADER_TOOLTIP = "Set the title of your notification here.",
        SETTINGS_NOTIFICATION_MESSAGE_TOOLTIP = "Specify here what you would like to be notified about.",
        SETTINGS_TOOLTIP_CLOCK = "Here you will find all the settings for the time",
        SETTINGS_TOOLTIP_BGCOLOR = "The background color only changes with the option Solid",
        SETTINGS_TOOLTIP_CHAT = "Here you can activate or deactivate the chat functions and edit them",
        SETTINGS_TOOLTIP_ANNOUNCEMENTS = "Set here whether and where you want the guild's announcement to be displayed",
        SETTINGS_TOOLTIP_REPAIR = "Here you will find all the settings for the repair and recharge function",
        SETTINGS_TOOLTIP_REPAIR_THRESHOLD = "Set here from when a repair can be carried out [% of damage].",
        SETTINGS_TOOLTIP_RECHARGE_THRESHOLD = "Set here from when a recharge can be carried out [% of recharge] |c880000For automatic charging it is recommended to set the value as low as possible!|r.",
        SETTINGS_TOOLTIP_REPAIR_STORES = "Set here whether and what is to be repaired when a trader is opened.",
        -- Notifications
        SETTINGS_NOTIFICATION_DAYS = "Day",
        SETTINGS_NOTIFICATION_CHOICE_0 = "Monday",
        SETTINGS_NOTIFICATION_CHOICE_1 = "Tuesday",
        SETTINGS_NOTIFICATION_CHOICE_2 = "Wednesday",
        SETTINGS_NOTIFICATION_CHOICE_3 = "Thursday",
        SETTINGS_NOTIFICATION_CHOICE_4 = "Friday",
        SETTINGS_NOTIFICATION_CHOICE_5 = "Saturday",
        SETTINGS_NOTIFICATION_CHOICE_6 = "Sunday",
        SETTINGS_NOTIFICATION_TITLE = "Arcanum Artis",
        SETTINGS_NOTIFICATION_TEXT = "Don't forget to buy a raffle ticket to participate in the weekly guild lottery.",
        SETTINGS_NOTIFICATION_ACTIVE = "Notifications",
        SETTINGS_NOTIFICATION_CHANGE_ACTIVE = "Change Message",
        SETTINGS_NOTIFICATION_CHANGE_HEADER = "Title",
        SETTINGS_NOTIFICATION_CHANGE_MESSAGE = "Notification",
        SETTINGS_NOTIFICATION_WARN_HEADER = "Limit 25 characters!",
        SETTINGS_NOTIFICATION_WARN_MESSAGE = "Limit 50 characters!",
        SETTINGS_NOTIFICATION_RESET = "Reset",
        SETTINGS_NOTIFICATION_MESSAGE_FIRST = "Would you like to activate the guild lottery reminder? You can also adjust this later in the settings.",
        ANNOUNCEMENTS_TEXT = "IMPORTANT ANNOUNCEMENT",
        --Chat Outputs
        CHAT_SHARED = "<<1>> quests were shared.",
        CHAT_NO_DAILIES_TO_SHARE = "There are no daily quests to share.",
        CHAT_SHARING = "The daily quests from <<1>> are being shared.",
        CHAT_SHARING_ALL = "<<1>> daily quests are being shared.",
        CHAT_REPAIRED = "<<1>> was repaired from <<2>> to <<3>>.",
        CHAT_RECHARGED = "<<1>> was recharged from <<2>> to <<3>>.",
        CHAT_SHOP_REPAIRED_DECLINED = "<<1>> could not be repaired. Cost: <<2>>.",
        CHAT_SHOP_REPAIRED = "<<1>> was repaired for <<2>>.",
        CHAT_REPAIR_COST = "Total repair cost: <<1>>.",
        CHAT_SHOP_REPAIRED_COST = "All equipment was repaired for <<1>>.",
        CHAT_SHOP_REPAIRED_DECLINED2 = "All equipment could not be repaired. Required: <<1>>.",
        CHAT_WELCOME_MESSAGE = "%s %sAddon loaded, %s %s!|r",
        CHAT_WELCOME_MESSAGE_MORNING = "Good morning",
        CHAT_WELCOME_MESSAGE_MIDDAY = "Hello",
        CHAT_WELCOME_MESSAGE_EVENING = "Good evening",
        CHAT_NOTHING_TO_REPAIR = "There is currently nothing to repair, the threshold of <<1>>% has not been reached yet.",
        CHAT_NOTHING_TO_RECHARGE = "There is currently nothing to recharge, the threshold of <<1>>% has not been reached yet.",
        CHAT_NOTHING_TO_REPAIR_RECHARGE = "There is currently nothing to repair or recharge, the thresholds have not been reached yet.",
        --PlayerContextMenu
        CHAT_NEW_MESSAGE = "New Message",
        CHAT_NEW_RANK = "-Rank:",
        CHAT_NEW_INVITE = "Invite to",
        --Repair
        SETTINGS_REPAIR_TITLE = "Repair & Recharge",
        SETTINGS_REPAIR_STORES_HEADER = "Stores",
        SETTINGS_REPAIR_STORES = "Autom. repair at store",
        SETTINGS_REPAIR_STORES_CHOICE0 = "All",
        SETTINGS_REPAIR_STORES_CHOICE1 = "Worn",
        SETTINGS_REPAIR_STORES_CHOICE2 = "Nothing",
        SETTINGS_REPAIR_PRINT = "Show in chat",
        SETTINGS_REPAIR_HEADER = "Repair",
        SETTINGS_REPAIR_KIT = "Use any repair kit",
        SETTINGS_REPAIR_THRESHOLD = "Repair kit threshold",
        SETTINGS_RECHARGE_HEADER = "Recharge",
        SETTINGS_RECHARGE_GEM = "Use any recharge gem",
        SETTINGS_RECHARGE_THRESHOLD = "Recharge gem threshold",
        SETTINGS_RECHARGE_AUTO = "Automatic charging",
        SETTINGS_RECHARGE_CHOICE0 = "Always",
        SETTINGS_RECHARGE_CHOICE1 = "Raiding",
        SETTINGS_RECHARGE_CHOICE2 = "Never",
        --TakeOneFromInventory
        TAKE_LABEL = "Take only one",
        TAKE_FAILURE = "Error: Not enough space in the inventory [There must be at least 2 free spaces].",
        TAKE_PROCESS = "1 / <<1>> of the item <<2>> is taken.",
        TAKE_RETURN = "Successfully removed and rest restored to guild bank.",
        --Deconstruction
        DECON_LABEL = "Select all",
        --Bindings
        BINDING_OPEN_SETTINGS = "Open settings",
        BINDING_REPAIR_RECHARGE = "Repair & Recharge",
        BINDING_REPAIR_WITH_KITS = "Repair equipment",
        BINDING_RECHARGE_WITH_GEMS = "Recharge weapon",
        BINDING_OPEN_TOMES_WINDOW = "Open Tomes",
    },
}

local function GetLocaleString(langId, langStr)
    if (ArcanumGuildHallLocalizationData[langId] ~= nil) and (ArcanumGuildHallLocalizationData[langId][langStr] ~= nil) then
        return ArcanumGuildHallLocalizationData[langId][langStr]
    end

    return ArcanumGuildHallLocalizationData["en"][langStr]
end

function ArcanumGuildHall.GetDefaultLocaleString(langStr)
    return GetLocaleString(GetCVar("language.2"), langStr)
end

ArcanumGuildHall.defaults.defaultNotTitle = ArcanumGuildHall.GetDefaultLocaleString("SETTINGS_NOTIFICATION_TITLE")
ArcanumGuildHall.defaults.defaultNotMessage = ArcanumGuildHall.GetDefaultLocaleString("SETTINGS_NOTIFICATION_TEXT")