local translations = {
    ["DisplayTime"] = "Mostrar hora",
    ["ItemStacking"] = "Ativar empilhamento de itens",
    ["PriceDataSource"] = "Fonte do preço",
    ["PriceCalculationMethod"] = "Método de cálculo do preço",
    ["NotifyOnNirncrux"] = "Notificar sobre Nirncrux",
    ["NotifyOnLegendary"] = "Notificar sobre itens lendários",
    ["TextNotify"] = "Notificações de texto",
    ["NotificationSound"] = "Som de notificação",
    ["AutoLootAfterStart"] = "Coleta automática após o início",
    ["InventorySpaceType"] = "Tipo de espaço de inventário",
    ["SortListParametr"] = "Parâmetro de ordenação da lista",
    ["SortListDirection"] = "Direção de ordenação da lista",
    ["SortListDirectionAsc"] = "Ascendente",
    ["SortListDirectionDesc"] = "Descendente",
    ["SetLootWindowAlpha"] = "Alfa da janela de saque",
    ["PriceTypeAvarage"] = "Média",
    ["PriceTypeMin"] = "Mínimo",
    ["PriceTypeMax"] = "Máximo",
    ["PriceTypeSuggested"] = "Sugerido",
    ["CategoryNames"] = {
        ["All"] = "Todos",
        ["Alchemy"] = "Alquimia",
        ["Blacksmithing"] = "Ferraria",
        ["Clothing"] =  "Vestuário",
        ["Enchanting"] = "Encantamento",
        ["JewelryCrafting"] = "Joalheria",
        ["Provisioning"] = "Fornecimento",
        ["Woodworking"] = "Marcenaria",
        ["Other"] = "Outro"
    },
    ["Name"] = "Nome",
    ["Category"] = "Categoria",
    ["Amount"] = "Quantidade",
    ["Time"] = "Tempo",
    ["Price"] = "Preço",
    ["Price/Item"] = "Preço/Item",
    ["TotalGold"] = "Ouro total",
    ["CategoryGold"] = "Ouro da categoria",
    ["ShowMaterials"] = "Mostrar apenas materiais",
    ["Vendor"] = "Fornecedor",
    ["Looted"] = "Coletado",
    ["AutoLootEnabled"] = "Coleta automática ativada",
    ["AutoLootDisabled"] = "Coleta automática desativada",
    ["Donate"] = "Doar",
    ["Author"] = "Autor",
    ["Session"] = "Sessão",
}

function LocalizationLoadPt()
    LootTrackerSolution.Localization.translation = translations
end
