local translations = {
    ["DisplayTime"] = "Zeit anzeigen",
    ["ItemStacking"] = "Gegenstandstapel aktivieren",
    ["PriceDataSource"] = "Preisquelle",
    ["PriceCalculationMethod"] = "Preistyp",
    ["NotifyOnNirncrux"] = "Benachrichtigen über Nirncrux",
    ["NotifyOnLegendary"] = "Benachrichtigen über legendäre Gegenstände",
    ["TextNotify"] = "Textbenachrichtigungen",
    ["NotificationSound"] = "Benachrichtigungston",
    ["AutoLootAfterStart"] = "Automatische Beute nach dem Start",
    ["InventorySpaceType"] = "Inventarplatztyp",
    ["SortListParametr"] = "Sortierlistenparameter",
    ["SortListDirection"] = "Sortierrichtung der Liste",
    ["SortListDirectionAsc"] = "Aufsteigend",
    ["SortListDirectionDesc"] = "Absteigend",
    ["SetLootWindowAlpha"] = "Loot-Fenster-Alpha",
    ["PriceTypeAvarage"] = "Durchschnitt",
    ["PriceTypeMin"] = "Minimum",
    ["PriceTypeMax"] = "Maximum",
    ["PriceTypeSuggested"] = "Vorgeschlagen",
    ["CategoryNames"] = {
        ["All"] = "Alle",
        ["Alchemy"] = "Alchemie",
        ["Blacksmithing"] = "Schmiedekunst",
        ["Clothing"] =  "Schneiderei",
        ["Enchanting"] = "Verzauberung",
        ["JewelryCrafting"] = "Schmuckherstellung",
        ["Provisioning"] = "Versorgung",
        ["Woodworking"] = "Holzbearbeitung",
        ["Other"] = "Andere"
    },
    ["Name"] = "Name",
    ["Category"] = "Kategorie",
    ["Amount"] = "Menge",
    ["Time"] = "Zeit",
    ["Price"] = "Preis",
    ["Price/Item"] = "Preis/Objekt",
    ["TotalGold"] = "Gesamtes Gold",
    ["CategoryGold"] = "Kategorie Gold",
    ["ShowMaterials"] = "Nur Materialien anzeigen",
    ["Vendor"] = "Verkäufer",
    ["Looted"] = "Geplündert",
    ["AutoLootEnabled"] = "Automatische Beute aktiviert",
    ["AutoLootDisabled"] = "Automatische Beute deaktiviert",
    ["Donate"] = "Spenden",
    ["Author"] = "Autor",
}

function LocalizationLoadDe()
    LootTrackerSolution.Localization.translation = translations
end