local translations = {
    ["DisplayTime"] = "Show Time",
    ["ItemStacking"] = "Enable Item Stacking",
    ["PriceDataSource"] = "Price Source",
    ["PriceCalculationMethod"] = "Price Type",
    ["NotifyOnNirncrux"] = "Notify on Nirncrux",
    ["NotifyOnLegendary"] = "Notify on Legendary Items",
    ["TextNotify"] = "Text Notifications",
    ["NotificationSound"] = "Notification Sound",
    ["AutoLootAfterStart"] = "Auto Loot After Start",
    ["InventorySpaceType"] = "Inventory Space Type",
    ["SortListParametr"] = "Sort List Parameter",
    ["SortListDirection"] = "Sort List Direction",
    ["SortListDirectionAsc"] = "Ascending",
    ["SortListDirectionDesc"] = "Descending",
    ["SetLootWindowAlpha"] = "Loot Window Alpha",
    ["PriceTypeAvarage"] = "Average",
    ["PriceTypeMin"] = "Minimum",
    ["PriceTypeMax"] = "Maximum",
    ["PriceTypeSuggested"] = "Suggested",
    ["CategoryNames"] = {
        ["All"] = "All",
        ["Alchemy"] = "Alchemy",
        ["Blacksmithing"] = "Blacksmithing",
        ["Clothing"] =  "Clothing",
        ["Enchanting"] = "Enchanting",
        ["JewelryCrafting"] = "Jewelry Crafting",
        ["Provisioning"] = "Provisioning",
        ["Woodworking"] = "Woodworking",
        ["Other"] = "Other"
    },
    ["Name"] = "Name",
    ["Category"] = "Category",
    ["Amount"] = "Amount",
    ["Time"] = "Time",
    ["Price"] = "Price",
    ["Price/Item"] = "Price/Item",
    ["TotalGold"] = "Total Gold",
    ["CategoryGold"] = "Category Gold",
    ["ShowMaterials"] = "Show Only Materials",
    ["Vendor"] = "Vendor",
    ["Looted"] = "Looted",
    ["AutoLootEnabled"] = "Auto Loot Enabled",
    ["AutoLootDisabled"] = "Auto Loot Disabled",
    ["Donate"] = "Donate",
    ["Author"] = "Author",
    ["Session"] = "Session",
}

function LocalizationLoadEn()
    LootTrackerSolution.Localization.translation = translations
end