local translations = {
    ["DisplayTime"] = "Mostrar tiempo",
    ["ItemStacking"] = "Activar apilamiento de objetos",
    ["PriceDataSource"] = "Fuente de precio",
    ["PriceCalculationMethod"] = "Método de cálculo del precio",
    ["NotifyOnNirncrux"] = "Notificar sobre Nirncrux",
    ["NotifyOnLegendary"] = "Notificar sobre objetos legendarios",
    ["TextNotify"] = "Notificaciones de texto",
    ["NotificationSound"] = "Sonido de notificación",
    ["AutoLootAfterStart"] = "Recoger automáticamente después del inicio",
    ["InventorySpaceType"] = "Tipo de espacio de inventario",
    ["SortListParametr"] = "Parámetro de ordenación de la lista",
    ["SortListDirection"] = "Dirección de ordenación de la lista",
    ["SortListDirectionAsc"] = "Ascendente",
    ["SortListDirectionDesc"] = "Descendente",
    ["SetLootWindowAlpha"] = "Alfa de la ventana de botín",
    ["PriceTypeAvarage"] = "Promedio",
    ["PriceTypeMin"] = "Mínimo",
    ["PriceTypeMax"] = "Máximo",
    ["PriceTypeSuggested"] = "Sugerido",
    ["CategoryNames"] = {
        ["All"] = "Todos",
        ["Alchemy"] = "Alquimia",
        ["Blacksmithing"] = "Herrería",
        ["Clothing"] =  "Ropa",
        ["Enchanting"] = "Encantamiento",
        ["JewelryCrafting"] = "Joyería",
        ["Provisioning"] = "Avituallamiento",
        ["Woodworking"] = "Carpintería",
        ["Other"] = "Otro"
    },
    ["Name"] = "Nombre",
    ["Category"] = "Categoría",
    ["Amount"] = "Cantidad",
    ["Time"] = "Tiempo",
    ["Price"] = "Precio",
    ["Price/Item"] = "Precio/Artículo",
    ["TotalGold"] = "Oro total",
    ["CategoryGold"] = "Oro de la categoría",
    ["ShowMaterials"] = "Mostrar solo materiales",
    ["Vendor"] = "Vendedor",
    ["Looted"] = "Saqueado",
    ["AutoLootEnabled"] = "Recolección automática habilitada",
    ["AutoLootDisabled"] = "Recolección automática deshabilitada",
    ["Donate"] = "Donar",
    ["Author"] = "Autor",
    ["Session"] = "Sesión",
}

function LocalizationLoadEs()
    LootTrackerSolution.Localization.translation = translations
end