local translations = {
    ["DisplayTime"] = "時間を表示する",
    ["ItemStacking"] = "アイテムスタッキングを有効にする",
    ["PriceDataSource"] = "価格データソース",
    ["PriceCalculationMethod"] = "価格計算方法",
    ["NotifyOnNirncrux"] = "ニルンクルックスについて通知する",
    ["NotifyOnLegendary"] = "伝説のアイテムについて通知する",
    ["TextNotify"] = "テキスト通知",
    ["NotificationSound"] = "通知音",
    ["AutoLootAfterStart"] = "開始後に自動収集する",
    ["InventorySpaceType"] = "インベントリスペースのタイプ",
    ["SortListParametr"] = "リストのソートパラメータ",
    ["SortListDirection"] = "リストのソート方向",
    ["SortListDirectionAsc"] = "昇順",
    ["SortListDirectionDesc"] = "降順",
    ["SetLootWindowAlpha"] = "収集ウィンドウのアルファ値",
    ["PriceTypeAvarage"] = "平均",
    ["PriceTypeMin"] = "最小",
    ["PriceTypeMax"] = "最大",
    ["PriceTypeSuggested"] = "推奨",
    ["CategoryNames"] = {
        ["All"] = "すべて",
        ["Alchemy"] = "錬金術",
        ["Blacksmithing"] = "鍛冶",
        ["Clothing"] =  "服",
        ["Enchanting"] = "付呪",
        ["JewelryCrafting"] = "宝飾",
        ["Provisioning"] = "調理",
        ["Woodworking"] = "木工",
        ["Other"] = "その他"
    },
    ["Name"] = "名前",
    ["Category"] = "カテゴリー",
    ["Amount"] = "量",
    ["Time"] = "時間",
    ["Price"] = "価格",
    ["Price/Item"] = "価格/アイテム",
    ["TotalGold"] = "合計ゴールド",
    ["CategoryGold"] = "カテゴリーゴールド",
    ["ShowMaterials"] = "材料のみ表示",
    ["Vendor"] = "販売者",
    ["Looted"] = "収集済み",
    ["AutoLootEnabled"] = "自動収集有効",
    ["AutoLootDisabled"] = "自動収集無効",
    ["Donate"] = "作者を支援する",
    ["Author"] = "著者",
    ["Session"] = "セッション",
}

function LocalizationLoadJp()
    LootTrackerSolution.Localization.translation = translations
end