local translations = {
    ["DisplayTime"] = "시간 표시",
    ["ItemStacking"] = "아이템 스택 활성화",
    ["PriceDataSource"] = "가격 데이터 소스",
    ["PriceCalculationMethod"] = "가격 계산 방법",
    ["NotifyOnNirncrux"] = "니른크럭스 알림",
    ["NotifyOnLegendary"] = "전설 아이템 알림",
    ["TextNotify"] = "텍스트 알림",
    ["NotificationSound"] = "알림 소리",
    ["AutoLootAfterStart"] = "시작 후 자동 전리품 수집",
    ["InventorySpaceType"] = "인벤토리 공간 유형",
    ["SortListParametr"] = "리스트 정렬 매개변수",
    ["SortListDirection"] = "리스트 정렬 방향",
    ["SortListDirectionAsc"] = "오름차순",
    ["SortListDirectionDesc"] = "내림차순",
    ["SetLootWindowAlpha"] = "전리품 창 알파 설정",
    ["PriceTypeAvarage"] = "평균",
    ["PriceTypeMin"] = "최소",
    ["PriceTypeMax"] = "최대",
    ["PriceTypeSuggested"] = "제안된",
    ["CategoryNames"] = {
        ["All"] = "모두",
        ["Alchemy"] = "연금술",
        ["Blacksmithing"] = "대장기술",
        ["Clothing"] =  "의상 제작",
        ["Enchanting"] = "마법부여",
        ["JewelryCrafting"] = "보석세공",
        ["Provisioning"] = "배급",
        ["Woodworking"] = "목공예",
        ["Other"] = "기타"
    },
    ["Name"] = "이름",
    ["Category"] = "카테고리",
    ["Amount"] = "수량",
    ["Time"] = "시간",
    ["Price"] = "가격",
    ["Price/Item"] = "가격/아이템",
    ["TotalGold"] = "총 금액",
    ["CategoryGold"] = "카테고리 금액",
    ["ShowMaterials"] = "자료만 표시",
    ["Vendor"] = "판매자",
    ["Looted"] = "획득함",
    ["AutoLootEnabled"] = "자동 전리품 수집 활성화됨",
    ["AutoLootDisabled"] = "자동 전리품 수집 비활성화됨",
    ["Donate"] = "기부",
    ["Author"] = "저자",
    ["Session"] = "세션",
}

function LocalizationLoadKr()
    LootTrackerSolution.Localization.translation = translations
end
