local translations = {
    ["DisplayTime"] = "Zamanı Göster",
    ["ItemStacking"] = "Öğe Yığma Etkinleştir",
    ["PriceDataSource"] = "Fiyat Kaynağı",
    ["PriceCalculationMethod"] = "Fiyat Hesaplama Yöntemi",
    ["NotifyOnNirncrux"] = "Nirncrux Bildir",
    ["NotifyOnLegendary"] = "Efsanevi Öğeleri Bildir",
    ["TextNotify"] = "Metin Bildirimleri",
    ["NotificationSound"] = "Bildirim Sesi",
    ["AutoLootAfterStart"] = "Başlangıç Sonrası Otomatik Yağma",
    ["InventorySpaceType"] = "Envanter Alan Türü",
    ["SortListParametr"] = "Liste Sıralama Parametresi",
    ["SortListDirection"] = "Liste Sıralama Yönü",
    ["SortListDirectionAsc"] = "Artan",
    ["SortListDirectionDesc"] = "Azalan",
    ["SetLootWindowAlpha"] = "Yağma Penceresi Alfası Ayarla",
    ["PriceTypeAvarage"] = "Ortalama",
    ["PriceTypeMin"] = "Minimum",
    ["PriceTypeMax"] = "Maksimum",
    ["PriceTypeSuggested"] = "Önerilen",
    ["CategoryNames"] = {
        ["All"] = "Tümü",
        ["Alchemy"] = "Simya",
        ["Blacksmithing"] = "Demircilik",
        ["Clothing"] =  "Giysicilik",
        ["Enchanting"] = "Büyücülük",
        ["JewelryCrafting"] = "Mücevherat",
        ["Provisioning"] = "Tedarik",
        ["Woodworking"] = "Ahşap İşleme",
        ["Other"] = "Diğer"
    },
    ["Name"] = "Ad",
    ["Category"] = "Kategori",
    ["Amount"] = "Miktar",
    ["Time"] = "Zaman",
    ["Price"] = "Fiyat",
    ["Price/Item"] = "Fiyat/Öğe",
    ["TotalGold"] = "Toplam Altın",
    ["CategoryGold"] = "Kategori Altını",
    ["ShowMaterials"] = "Yalnızca Malzemeleri Göster",
    ["Vendor"] = "Satıcı",
    ["Looted"] = "Toplanan",
    ["AutoLootEnabled"] = "Otomatik Yağma Etkin",
    ["AutoLootDisabled"] = "Otomatik Yağma Devre Dışı",
    ["Donate"] = "Bağış",
    ["Author"] = "Yazar",
    ["Session"] = "Oturum",
}

function LocalizationLoadTr()
    LootTrackerSolution.Localization.translation = translations
end