local translations = {
    ["DisplayTime"] = "Показувати час",
    ["ItemStacking"] = "Увімкнути стосування предметів",
    ["PriceDataSource"] = "Джерело ціни",
    ["PriceCalculationMethod"] = "Спосіб розрахунку ціни",
    ["NotifyOnNirncrux"] = "Повідомляти про Нірнкрукси",
    ["NotifyOnLegendary"] = "Повідомляти про легендарні предмети",
    ["TextNotify"] = "Текстові повідомлення",
    ["NotificationSound"] = "Звук повідомлення",
    ["AutoLootAfterStart"] = "Автоматичне збирання після старту",
    ["InventorySpaceType"] = "Тип простору інвентаря",
    ["SortListParametr"] = "Параметр сортування списку",
    ["SortListDirection"] = "Напрям сортування списку",
    ["SortListDirectionAsc"] = "У зростанні",
    ["SortListDirectionDesc"] = "У спаданні",
    ["SetLootWindowAlpha"] = "Прозорість вікна здобичі",
    ["PriceTypeAvarage"] = "Середнє",
    ["PriceTypeMin"] = "Мінімальне",
    ["PriceTypeMax"] = "Максимальне",
    ["PriceTypeSuggested"] = "Рекомендоване",
    ["CategoryNames"] = {
        ["All"] = "Усі",
        ["Alchemy"] = "Алхімія",
        ["Blacksmithing"] = "Ковальство",
        ["Clothing"] =  "Портняжний ремесло",
        ["Enchanting"] = "Зачарування",
        ["JewelryCrafting"] = "Ювелірний ремесло",
        ["Provisioning"] = "Постачання",
        ["Woodworking"] = "Деревообробка",
        ["Other"] = "Інше"
    },
    ["Name"] = "Назва",
    ["Category"] = "Категорія",
    ["Amount"] = "Кількість",
    ["Time"] = "Час",
    ["Price"] = "Ціна",
    ["Price/Item"] = "Ціна/Предмет",
    ["TotalGold"] = "Загальне золото",
    ["CategoryGold"] = "Золото категорії",
    ["ShowMaterials"] = "Показувати лише матеріали",
    ["Vendor"] = "Продавець",
    ["Looted"] = "Здобуто",
    ["AutoLootEnabled"] = "Автоматичне збирання увімкнено",
    ["AutoLootDisabled"] = "Автоматичне збирання вимкнено",
    ["Donate"] = "Підтримати автора",
    ["Author"] = "Автор",
    ["Session"] = "Сесія",
}

function LocalizationLoadUa()
    LootTrackerSolution.Localization.translation = translations
end