-- CommandCodex_Strings.lua : every text the addon shows, in each language.
-- The language is picked in Settings > Addons > Command Codex ("auto"
-- follows the game's language). S.L("KEY", ...) returns the text, formatted.

CommandCodex = CommandCodex or {}
local S = CommandCodex

S.LANGUAGES = { "auto", "en", "de", "fr", "es" }
S.LANGUAGE_NAMES = { en = "English", de = "Deutsch", fr = "Français", es = "Español" }

S.STRINGS = {}

S.STRINGS.en = {
    PREFIX = "[Command Codex]",
    TITLE = "Command Codex",
    LAUNCHER = "Command Codex",

    -- Chat messages
    ALIAS_LOOP = "Stopped: your aliases call each other in a loop.",
    UNKNOWN_COMMAND = "Unknown command: %s",
    ERROR_IN = "Error in %s: %s",
    ALIAS_ONE_WORD = "The alias must be one word, like /rl.",
    ALIAS_NEED_TARGET = "Enter the command the alias should run.",
    ALIAS_EXISTS = "%s is already a command. Pick another name.",
    ALIAS_SELF = "An alias can't run itself.",
    ALIAS_INACTIVE = "Alias %s is not active: another addon uses that command now.",
    ALIAS_RUNS_CHAT = "Alias %s runs: %s",
    ALIAS_USAGE = "Usage: /codex alias /rl /reloadui",
    ALIAS_DELETED = "Deleted alias %s",
    ALIAS_NOT_FOUND = "No alias called %s",
    NO_ALIASES = "You have no aliases yet.",
    FAV_SLOT_EMPTY = "Favorite slot %d is empty. Star a command to fill it.",
    FAVS_SHOWN = "Favorites shown on screen.",
    FAVS_HIDDEN = "Favorites hidden from screen. Right-click the \"Command Codex\" button to show them again.",
    FAVS_RESET = "Favorites moved back to the top center of the screen.",
    FAVS_LOCKED = "Favorites locked in place.",
    FAVS_UNLOCKED = "Favorites unlocked. Drag them anywhere.",
    LAUNCHER_HIDDEN = "Button hidden. Type /codex to show it again.",
    SET_SWITCHED = "Favorite set: %s",
    KEY_ONLY_5 = "Only your first 5 favorites can have a key. Move this one up by unstarring one above it.",
    KEY_DIALOG_FAIL = "Couldn't open the key dialog. Bind it in Controls > Keybindings > Command Codex > Run favorite %d.",
    HELP = {
        "/codex - open or close the window",
        "/codex aui - open the window searching for \"aui\"",
        "/codex bar - show or hide your favorites on screen",
        "/codex lock - lock or unlock your favorites on screen",
        "/codex reset - move your favorites back to the top center of the screen",
        "/codex alias /rl /reloadui - create an alias (chain commands with ;)",
        "/codex unalias /rl - delete an alias",
        "/codex aliases - list your aliases",
        "Language and favorite sets: Settings > Addons > Command Codex",
    },

    -- Keybindings
    BIND_TOGGLE = "Toggle Command Codex",
    BIND_TOGGLE_FAVS = "Show/hide favorites on screen",
    BIND_FAV = "Run favorite %d",

    -- Categories
    CAT_ALL = "All commands",
    CAT_FAVORITES = "Favorites",
    CAT_RECENT = "Recent",
    CAT_ADDONS = "Addons",
    CAT_ALIASES = "Your aliases",
    CAT_GAME = "Game",
    CAT_EMOTES = "Emotes",
    EMOTE = "Emote",
    OTHER = "Other",

    -- Window
    SEARCH = "Search",
    HIDE_LIBS = "Hide libraries",
    HIDE_LIBS_TT = "Hide commands from libraries (LibAddonMenu and similar).\nThey are rarely useful to run yourself.",
    SHOW_FAVS = "Show favorites on screen",
    SHOW_FAVS_TT = "Show each favorite as its own button on your screen.\nRight-click a favorite > Bind a Key to run it with a key.",
    LOCK_TT_LOCKED = "Favorites are locked in place.\nClick to unlock and drag them around.",
    LOCK_TT_UNLOCKED = "Favorites are unlocked: drag them anywhere.\nClick to lock them in place.",
    RESET_POS = "Reset positions",
    RESET_POS_TT = "Move all your favorites back to where they\nstarted: a row at the top center of the screen.",
    MINIMIZE = "Minimize",
    COUNT = "%d commands",
    EMPTY_FAVORITES = "No favorites yet.\nClick the star next to a command.",
    EMPTY_RECENT = "Nothing run yet.\nCommands you run from here show up in this list.",
    EMPTY_ALIASES = "No aliases yet. Create one below.",
    EMPTY_SEARCH = "No commands match your search.",
    BTN_RUN = "Run",
    BTN_CHAT = "Put in Chat",
    BTN_FAVORITE = "Favorite",
    BTN_UNFAVORITE = "Unfavorite",
    BTN_DELETE_ALIAS = "Delete Alias",
    NEW_ALIAS = "New Alias",
    RUNS = "runs",
    ADD = "Add",
    ALIAS_ADDED = "Added %s",
    ALIAS_TIP = "The command your alias runs.",
    ALIAS_TIP_CHAIN = "Tip: an alias can run several commands at once.\nSeparate them with ;   e.g.  /cmd1 ; /cmd2",

    -- Tooltips
    TT_ALIAS = "Your alias. Runs: %s",
    TT_FROM = "From: %s",
    TT_GAME = "Built into the game.",
    TT_METHOD_NAME = "Addon guessed from the command's name.",
    TT_METHOD_LOAD = "Addon found while addons were loading.",
    TT_ROW_HINT = "Arrow: run.\nDouble-click: put in chat.  Right-click: more.",
    TT_LAST_RUN = "Last run: %s",
    QT_RUNS = "Runs: %s",
    QT_CLICK = "Click: run.",
    QT_KEY = "Key: %s  (right-click to change)",
    QT_BIND_HINT = "Right-click > Bind a Key to run it with a key.",
    QT_DRAG = "Drag to move.",
    LAUNCHER_TT = "Click: open / minimize\nRight-click: favorites on screen, favorite sets\nDrag: move",
    LAUNCHER_HIDE_TT = "Hide this button\nType /codex to show it again",

    -- Menus
    MENU_RUN = "Run",
    MENU_CHAT = "Put in Chat",
    MENU_BIND = "Bind a Key...",
    MENU_CHANGE_KEY = "Change Key...",
    MENU_ADD_NOTE = "Add Note...",
    MENU_EDIT_NOTE = "Edit Note...",
    MENU_DELETE_ALIAS = "Delete Alias",
    MENU_RESET_POS = "Reset Position",
    MENU_REMOVE_FAV = "Remove from Favorites",
    MENU_HIDE_FAVS = "Hide Favorites from Screen",
    MENU_SHOW_FAVS = "Show Favorites on Screen",
    MENU_USE_SET = "Favorite set: %s",
    MENU_CURRENT = "(current)",
    MENU_SETTINGS = "Settings...",

    -- Key dialog
    KEY_DIALOG_NAME = "Run favorite %d  (%s)",

    -- Notes
    NOTE_TITLE = "Note for %s",
    NOTE_HINT = "What does this command do?",
    SAVE = "Save",
    CANCEL = "Cancel",

    -- Time
    AGO_NOW = "just now",
    AGO_MIN = "%d min ago",
    AGO_HOUR = "%d h ago",
    AGO_DAY = "%d d ago",

    -- Settings
    SETTINGS_LANGUAGE_HEADER = "Language",
    SETTINGS_LANGUAGE = "Language",
    SETTINGS_LANGUAGE_TT = "Language of this addon. Applies after the UI reloads.",
    LANG_AUTO = "Game language",
    SETS_HEADER = "Favorite sets",
    SETS_DESC = "Each set has its own favorites, button positions and keys 1-5. Use a different set per character, or switch automatically in PvP or at home.",
    SET_DEFAULT = "Default",
    SET_THIS_CHAR = "Set for this character",
    SET_THIS_CHAR_TT = "The favorites this character uses.",
    SET_PVP = "In Cyrodiil and battlegrounds",
    SET_HOUSE = "In houses",
    SET_PVP_TT = "Automatically use this set while you're in Cyrodiil or a battleground.",
    SET_HOUSE_TT = "Automatically use this set while you're in a house.",
    SET_NO_SWITCH = "Don't switch",
    NEW_SET_NAME = "New set name",
    CREATE_SET = "Create set",
    CREATE_SET_TT = "Creates an empty set with the name above.",
    SET_NAME_EMPTY = "Enter a name for the new set first.",
    SET_EXISTS = "A set called %s already exists.",
    SET_CREATED = "Created favorite set %s.",
    DELETE_SET_PICK = "Set to delete",
    DELETE_SET = "Delete set",
    DELETE_SET_WARN = "Deletes the set and its favorites.",
    SET_DELETED = "Deleted favorite set %s.",
    NO_SETS_TO_DELETE = "(no other sets)",
}

S.STRINGS.de = {
    PREFIX = "[Command Codex]",
    TITLE = "Command Codex",
    LAUNCHER = "Command Codex",

    ALIAS_LOOP = "Gestoppt: Deine Aliase rufen sich gegenseitig auf.",
    UNKNOWN_COMMAND = "Unbekannter Befehl: %s",
    ERROR_IN = "Fehler in %s: %s",
    ALIAS_ONE_WORD = "Der Alias muss ein einzelnes Wort sein, z. B. /rl.",
    ALIAS_NEED_TARGET = "Gib den Befehl ein, den der Alias ausführen soll.",
    ALIAS_EXISTS = "%s ist bereits ein Befehl. Wähle einen anderen Namen.",
    ALIAS_SELF = "Ein Alias kann sich nicht selbst ausführen.",
    ALIAS_INACTIVE = "Alias %s ist nicht aktiv: Ein anderes Addon nutzt diesen Befehl jetzt.",
    ALIAS_RUNS_CHAT = "Alias %s führt aus: %s",
    ALIAS_USAGE = "Verwendung: /codex alias /rl /reloadui",
    ALIAS_DELETED = "Alias %s gelöscht",
    ALIAS_NOT_FOUND = "Kein Alias namens %s",
    NO_ALIASES = "Du hast noch keine Aliase.",
    FAV_SLOT_EMPTY = "Favoritenplatz %d ist leer. Markiere einen Befehl mit dem Stern.",
    FAVS_SHOWN = "Favoriten auf dem Bildschirm angezeigt.",
    FAVS_HIDDEN = "Favoriten ausgeblendet. Rechtsklick auf die Schaltfläche \"Command Codex\" zeigt sie wieder an.",
    FAVS_RESET = "Favoriten wieder oben in der Bildschirmmitte.",
    FAVS_LOCKED = "Favoriten fixiert.",
    FAVS_UNLOCKED = "Favoriten entsperrt. Zieh sie, wohin du willst.",
    LAUNCHER_HIDDEN = "Schaltfläche ausgeblendet. Gib /codex ein, um sie wieder anzuzeigen.",
    SET_SWITCHED = "Favoritensatz: %s",
    KEY_ONLY_5 = "Nur deine ersten 5 Favoriten können eine Taste haben. Entferne den Stern bei einem Favoriten davor, um diesen nach oben zu holen.",
    KEY_DIALOG_FAIL = "Das Tastenfenster ließ sich nicht öffnen. Belege sie unter Steuerung > Tastenbelegung > Command Codex > Favorit %d ausführen.",
    HELP = {
        "/codex - Fenster öffnen oder schließen",
        "/codex aui - Fenster öffnen und nach \"aui\" suchen",
        "/codex bar - Favoriten auf dem Bildschirm ein- oder ausblenden",
        "/codex lock - Favoriten auf dem Bildschirm fixieren oder entsperren",
        "/codex reset - Favoriten wieder oben in die Bildschirmmitte setzen",
        "/codex alias /rl /reloadui - Alias erstellen (mehrere Befehle mit ; trennen)",
        "/codex unalias /rl - Alias löschen",
        "/codex aliases - deine Aliase auflisten",
        "Sprache und Favoritensätze: Einstellungen > Addons > Command Codex",
    },

    BIND_TOGGLE = "Command Codex öffnen/schließen",
    BIND_TOGGLE_FAVS = "Favoriten auf dem Bildschirm ein-/ausblenden",
    BIND_FAV = "Favorit %d ausführen",

    CAT_ALL = "Alle Befehle",
    CAT_FAVORITES = "Favoriten",
    CAT_RECENT = "Zuletzt verwendet",
    CAT_ADDONS = "Addons",
    CAT_ALIASES = "Deine Aliase",
    CAT_GAME = "Spiel",
    CAT_EMOTES = "Emotes",
    EMOTE = "Emote",
    OTHER = "Sonstige",

    SEARCH = "Suchen",
    HIDE_LIBS = "Bibliotheken ausblenden",
    HIDE_LIBS_TT = "Befehle von Bibliotheken (LibAddonMenu usw.) ausblenden.\nDiese brauchst du selten selbst.",
    SHOW_FAVS = "Favoriten anzeigen",
    SHOW_FAVS_TT = "Jeden Favoriten als eigene Schaltfläche auf dem Bildschirm zeigen.\nRechtsklick auf einen Favoriten > Taste belegen, um ihn per Taste auszuführen.",
    LOCK_TT_LOCKED = "Favoriten sind fixiert.\nKlicken, um sie zu entsperren und zu verschieben.",
    LOCK_TT_UNLOCKED = "Favoriten sind entsperrt: zieh sie, wohin du willst.\nKlicken, um sie zu fixieren.",
    RESET_POS = "Positionen zurücksetzen",
    RESET_POS_TT = "Alle Favoriten wieder an ihren Startplatz setzen:\neine Reihe oben in der Bildschirmmitte.",
    MINIMIZE = "Minimieren",
    COUNT = "%d Befehle",
    EMPTY_FAVORITES = "Noch keine Favoriten.\nKlicke auf den Stern neben einem Befehl.",
    EMPTY_RECENT = "Noch nichts ausgeführt.\nBefehle, die du hier ausführst, erscheinen in dieser Liste.",
    EMPTY_ALIASES = "Noch keine Aliase. Erstelle unten einen.",
    EMPTY_SEARCH = "Keine Befehle passen zu deiner Suche.",
    BTN_RUN = "Ausführen",
    BTN_CHAT = "In den Chat",
    BTN_FAVORITE = "Favorit",
    BTN_UNFAVORITE = "Kein Favorit",
    BTN_DELETE_ALIAS = "Alias löschen",
    NEW_ALIAS = "Neuer Alias",
    RUNS = "führt aus",
    ADD = "Hinzufügen",
    ALIAS_ADDED = "%s hinzugefügt",
    ALIAS_TIP = "Der Befehl, den dein Alias ausführt.",
    ALIAS_TIP_CHAIN = "Tipp: Ein Alias kann mehrere Befehle auf einmal ausführen.\nTrenne sie mit ;   z. B.  /befehl1 ; /befehl2",

    TT_ALIAS = "Dein Alias. Führt aus: %s",
    TT_FROM = "Von: %s",
    TT_GAME = "Gehört zum Spiel.",
    TT_METHOD_NAME = "Addon anhand des Befehlsnamens erraten.",
    TT_METHOD_LOAD = "Addon beim Laden der Addons erkannt.",
    TT_ROW_HINT = "Pfeil: ausführen.\nDoppelklick: in den Chat.  Rechtsklick: mehr.",
    TT_LAST_RUN = "Zuletzt ausgeführt: %s",
    QT_RUNS = "Führt aus: %s",
    QT_CLICK = "Klick: ausführen.",
    QT_KEY = "Taste: %s  (Rechtsklick zum Ändern)",
    QT_BIND_HINT = "Rechtsklick > Taste belegen, um ihn per Taste auszuführen.",
    QT_DRAG = "Ziehen zum Verschieben.",
    LAUNCHER_TT = "Klick: öffnen / minimieren\nRechtsklick: Favoriten auf dem Bildschirm, Favoritensätze\nZiehen: verschieben",
    LAUNCHER_HIDE_TT = "Diese Schaltfläche ausblenden\nMit /codex wieder anzeigen",

    MENU_RUN = "Ausführen",
    MENU_CHAT = "In den Chat",
    MENU_BIND = "Taste belegen...",
    MENU_CHANGE_KEY = "Taste ändern...",
    MENU_ADD_NOTE = "Notiz hinzufügen...",
    MENU_EDIT_NOTE = "Notiz bearbeiten...",
    MENU_DELETE_ALIAS = "Alias löschen",
    MENU_RESET_POS = "Position zurücksetzen",
    MENU_REMOVE_FAV = "Aus Favoriten entfernen",
    MENU_HIDE_FAVS = "Favoriten ausblenden",
    MENU_SHOW_FAVS = "Favoriten anzeigen",
    MENU_USE_SET = "Favoritensatz: %s",
    MENU_CURRENT = "(aktiv)",
    MENU_SETTINGS = "Einstellungen...",

    KEY_DIALOG_NAME = "Favorit %d ausführen  (%s)",

    NOTE_TITLE = "Notiz zu %s",
    NOTE_HINT = "Was macht dieser Befehl?",
    SAVE = "Speichern",
    CANCEL = "Abbrechen",

    AGO_NOW = "gerade eben",
    AGO_MIN = "vor %d Min.",
    AGO_HOUR = "vor %d Std.",
    AGO_DAY = "vor %d T.",

    SETTINGS_LANGUAGE_HEADER = "Sprache",
    SETTINGS_LANGUAGE = "Sprache",
    SETTINGS_LANGUAGE_TT = "Sprache dieses Addons. Gilt nach dem Neuladen der Oberfläche.",
    LANG_AUTO = "Spielsprache",
    SETS_HEADER = "Favoritensätze",
    SETS_DESC = "Jeder Satz hat eigene Favoriten, Positionen und Tasten 1-5. Nutze pro Charakter einen anderen Satz oder wechsle automatisch im PvP oder zu Hause.",
    SET_DEFAULT = "Standard",
    SET_THIS_CHAR = "Satz für diesen Charakter",
    SET_THIS_CHAR_TT = "Die Favoriten, die dieser Charakter nutzt.",
    SET_PVP = "In Cyrodiil und Schlachtfeldern",
    SET_HOUSE = "In Häusern",
    SET_PVP_TT = "Diesen Satz automatisch nutzen, solange du in Cyrodiil oder auf einem Schlachtfeld bist.",
    SET_HOUSE_TT = "Diesen Satz automatisch nutzen, solange du in einem Haus bist.",
    SET_NO_SWITCH = "Nicht wechseln",
    NEW_SET_NAME = "Name des neuen Satzes",
    CREATE_SET = "Satz erstellen",
    CREATE_SET_TT = "Erstellt einen leeren Satz mit dem Namen oben.",
    SET_NAME_EMPTY = "Gib zuerst einen Namen für den neuen Satz ein.",
    SET_EXISTS = "Es gibt bereits einen Satz namens %s.",
    SET_CREATED = "Favoritensatz %s erstellt.",
    DELETE_SET_PICK = "Zu löschender Satz",
    DELETE_SET = "Satz löschen",
    DELETE_SET_WARN = "Löscht den Satz und seine Favoriten.",
    SET_DELETED = "Favoritensatz %s gelöscht.",
    NO_SETS_TO_DELETE = "(keine weiteren Sätze)",
}

S.STRINGS.fr = {
    PREFIX = "[Command Codex]",
    TITLE = "Command Codex",
    LAUNCHER = "Command Codex",

    ALIAS_LOOP = "Arrêté : vos alias s'appellent en boucle.",
    UNKNOWN_COMMAND = "Commande inconnue : %s",
    ERROR_IN = "Erreur dans %s : %s",
    ALIAS_ONE_WORD = "L'alias doit être un seul mot, comme /rl.",
    ALIAS_NEED_TARGET = "Saisissez la commande que l'alias doit exécuter.",
    ALIAS_EXISTS = "%s est déjà une commande. Choisissez un autre nom.",
    ALIAS_SELF = "Un alias ne peut pas s'exécuter lui-même.",
    ALIAS_INACTIVE = "L'alias %s n'est pas actif : un autre addon utilise maintenant cette commande.",
    ALIAS_RUNS_CHAT = "L'alias %s exécute : %s",
    ALIAS_USAGE = "Utilisation : /codex alias /rl /reloadui",
    ALIAS_DELETED = "Alias %s supprimé",
    ALIAS_NOT_FOUND = "Aucun alias nommé %s",
    NO_ALIASES = "Vous n'avez pas encore d'alias.",
    FAV_SLOT_EMPTY = "L'emplacement favori %d est vide. Mettez une étoile à une commande.",
    FAVS_SHOWN = "Favoris affichés à l'écran.",
    FAVS_HIDDEN = "Favoris masqués. Clic droit sur le bouton \"Command Codex\" pour les réafficher.",
    FAVS_RESET = "Favoris replacés en haut au centre de l'écran.",
    FAVS_LOCKED = "Favoris verrouillés.",
    FAVS_UNLOCKED = "Favoris déverrouillés. Déplacez-les où vous voulez.",
    LAUNCHER_HIDDEN = "Bouton masqué. Tapez /codex pour le réafficher.",
    SET_SWITCHED = "Jeu de favoris : %s",
    KEY_ONLY_5 = "Seuls vos 5 premiers favoris peuvent avoir une touche. Retirez l'étoile d'un favori placé avant pour faire remonter celui-ci.",
    KEY_DIALOG_FAIL = "Impossible d'ouvrir la fenêtre des touches. Assignez-la dans Commandes > Raccourcis > Command Codex > Exécuter le favori %d.",
    HELP = {
        "/codex - ouvrir ou fermer la fenêtre",
        "/codex aui - ouvrir la fenêtre en cherchant \"aui\"",
        "/codex bar - afficher ou masquer vos favoris à l'écran",
        "/codex lock - verrouiller ou déverrouiller vos favoris à l'écran",
        "/codex reset - replacer vos favoris en haut au centre de l'écran",
        "/codex alias /rl /reloadui - créer un alias (séparez plusieurs commandes par ;)",
        "/codex unalias /rl - supprimer un alias",
        "/codex aliases - lister vos alias",
        "Langue et jeux de favoris : Paramètres > Addons > Command Codex",
    },

    BIND_TOGGLE = "Ouvrir/fermer Command Codex",
    BIND_TOGGLE_FAVS = "Afficher/masquer les favoris à l'écran",
    BIND_FAV = "Exécuter le favori %d",

    CAT_ALL = "Toutes les commandes",
    CAT_FAVORITES = "Favoris",
    CAT_RECENT = "Récentes",
    CAT_ADDONS = "Addons",
    CAT_ALIASES = "Vos alias",
    CAT_GAME = "Jeu",
    CAT_EMOTES = "Emotes",
    EMOTE = "Emote",
    OTHER = "Autres",

    SEARCH = "Rechercher",
    HIDE_LIBS = "Masquer les bibliothèques",
    HIDE_LIBS_TT = "Masquer les commandes des bibliothèques (LibAddonMenu, etc.).\nVous en aurez rarement besoin.",
    SHOW_FAVS = "Afficher les favoris",
    SHOW_FAVS_TT = "Afficher chaque favori comme un bouton à l'écran.\nClic droit sur un favori > Assigner une touche pour l'exécuter au clavier.",
    LOCK_TT_LOCKED = "Les favoris sont verrouillés.\nCliquez pour les déverrouiller et les déplacer.",
    LOCK_TT_UNLOCKED = "Les favoris sont déverrouillés : déplacez-les où vous voulez.\nCliquez pour les verrouiller.",
    RESET_POS = "Réinitialiser les positions",
    RESET_POS_TT = "Replacer tous vos favoris à leur position de départ :\nune rangée en haut au centre de l'écran.",
    MINIMIZE = "Réduire",
    COUNT = "%d commandes",
    EMPTY_FAVORITES = "Aucun favori pour l'instant.\nCliquez sur l'étoile à côté d'une commande.",
    EMPTY_RECENT = "Rien d'exécuté pour l'instant.\nLes commandes exécutées d'ici apparaissent dans cette liste.",
    EMPTY_ALIASES = "Aucun alias pour l'instant. Créez-en un ci-dessous.",
    EMPTY_SEARCH = "Aucune commande ne correspond à votre recherche.",
    BTN_RUN = "Exécuter",
    BTN_CHAT = "Dans le chat",
    BTN_FAVORITE = "Favori",
    BTN_UNFAVORITE = "Retirer",
    BTN_DELETE_ALIAS = "Suppr. l'alias",
    NEW_ALIAS = "Nouvel alias",
    RUNS = "exécute",
    ADD = "Ajouter",
    ALIAS_ADDED = "%s ajouté",
    ALIAS_TIP = "La commande exécutée par votre alias.",
    ALIAS_TIP_CHAIN = "Astuce : un alias peut exécuter plusieurs commandes à la fois.\nSéparez-les par ;   ex.  /cmd1 ; /cmd2",

    TT_ALIAS = "Votre alias. Exécute : %s",
    TT_FROM = "De : %s",
    TT_GAME = "Intégrée au jeu.",
    TT_METHOD_NAME = "Addon deviné d'après le nom de la commande.",
    TT_METHOD_LOAD = "Addon détecté pendant le chargement des addons.",
    TT_ROW_HINT = "Flèche : exécuter.\nDouble-clic : dans le chat.  Clic droit : plus.",
    TT_LAST_RUN = "Dernière exécution : %s",
    QT_RUNS = "Exécute : %s",
    QT_CLICK = "Clic : exécuter.",
    QT_KEY = "Touche : %s  (clic droit pour changer)",
    QT_BIND_HINT = "Clic droit > Assigner une touche pour l'exécuter au clavier.",
    QT_DRAG = "Faites glisser pour déplacer.",
    LAUNCHER_TT = "Clic : ouvrir / réduire\nClic droit : favoris à l'écran, jeux de favoris\nGlisser : déplacer",
    LAUNCHER_HIDE_TT = "Masquer ce bouton\nTapez /codex pour le réafficher",

    MENU_RUN = "Exécuter",
    MENU_CHAT = "Dans le chat",
    MENU_BIND = "Assigner une touche...",
    MENU_CHANGE_KEY = "Changer la touche...",
    MENU_ADD_NOTE = "Ajouter une note...",
    MENU_EDIT_NOTE = "Modifier la note...",
    MENU_DELETE_ALIAS = "Supprimer l'alias",
    MENU_RESET_POS = "Réinitialiser la position",
    MENU_REMOVE_FAV = "Retirer des favoris",
    MENU_HIDE_FAVS = "Masquer les favoris",
    MENU_SHOW_FAVS = "Afficher les favoris",
    MENU_USE_SET = "Jeu de favoris : %s",
    MENU_CURRENT = "(actif)",
    MENU_SETTINGS = "Paramètres...",

    KEY_DIALOG_NAME = "Exécuter le favori %d  (%s)",

    NOTE_TITLE = "Note pour %s",
    NOTE_HINT = "Que fait cette commande ?",
    SAVE = "Enregistrer",
    CANCEL = "Annuler",

    AGO_NOW = "à l'instant",
    AGO_MIN = "il y a %d min",
    AGO_HOUR = "il y a %d h",
    AGO_DAY = "il y a %d j",

    SETTINGS_LANGUAGE_HEADER = "Langue",
    SETTINGS_LANGUAGE = "Langue",
    SETTINGS_LANGUAGE_TT = "Langue de cet addon. S'applique après le rechargement de l'interface.",
    LANG_AUTO = "Langue du jeu",
    SETS_HEADER = "Jeux de favoris",
    SETS_DESC = "Chaque jeu a ses propres favoris, positions et touches 1-5. Utilisez un jeu par personnage, ou changez automatiquement en JcJ ou chez vous.",
    SET_DEFAULT = "Par défaut",
    SET_THIS_CHAR = "Jeu pour ce personnage",
    SET_THIS_CHAR_TT = "Les favoris utilisés par ce personnage.",
    SET_PVP = "En Cyrodiil et champs de bataille",
    SET_HOUSE = "Dans les maisons",
    SET_PVP_TT = "Utiliser automatiquement ce jeu quand vous êtes en Cyrodiil ou sur un champ de bataille.",
    SET_HOUSE_TT = "Utiliser automatiquement ce jeu quand vous êtes dans une maison.",
    SET_NO_SWITCH = "Ne pas changer",
    NEW_SET_NAME = "Nom du nouveau jeu",
    CREATE_SET = "Créer le jeu",
    CREATE_SET_TT = "Crée un jeu vide avec le nom ci-dessus.",
    SET_NAME_EMPTY = "Saisissez d'abord un nom pour le nouveau jeu.",
    SET_EXISTS = "Un jeu nommé %s existe déjà.",
    SET_CREATED = "Jeu de favoris %s créé.",
    DELETE_SET_PICK = "Jeu à supprimer",
    DELETE_SET = "Supprimer le jeu",
    DELETE_SET_WARN = "Supprime le jeu et ses favoris.",
    SET_DELETED = "Jeu de favoris %s supprimé.",
    NO_SETS_TO_DELETE = "(aucun autre jeu)",
}

S.STRINGS.es = {
    PREFIX = "[Command Codex]",
    TITLE = "Command Codex",
    LAUNCHER = "Command Codex",

    ALIAS_LOOP = "Detenido: tus alias se llaman entre sí en bucle.",
    UNKNOWN_COMMAND = "Comando desconocido: %s",
    ERROR_IN = "Error en %s: %s",
    ALIAS_ONE_WORD = "El alias debe ser una sola palabra, como /rl.",
    ALIAS_NEED_TARGET = "Escribe el comando que debe ejecutar el alias.",
    ALIAS_EXISTS = "%s ya es un comando. Elige otro nombre.",
    ALIAS_SELF = "Un alias no puede ejecutarse a sí mismo.",
    ALIAS_INACTIVE = "El alias %s no está activo: otro addon usa ahora ese comando.",
    ALIAS_RUNS_CHAT = "El alias %s ejecuta: %s",
    ALIAS_USAGE = "Uso: /codex alias /rl /reloadui",
    ALIAS_DELETED = "Alias %s eliminado",
    ALIAS_NOT_FOUND = "No hay ningún alias llamado %s",
    NO_ALIASES = "Aún no tienes alias.",
    FAV_SLOT_EMPTY = "El favorito %d está vacío. Marca un comando con la estrella.",
    FAVS_SHOWN = "Favoritos visibles en pantalla.",
    FAVS_HIDDEN = "Favoritos ocultos. Haz clic derecho en el botón \"Command Codex\" para volver a mostrarlos.",
    FAVS_RESET = "Favoritos devueltos a la parte superior central de la pantalla.",
    FAVS_LOCKED = "Favoritos bloqueados.",
    FAVS_UNLOCKED = "Favoritos desbloqueados. Arrástralos adonde quieras.",
    LAUNCHER_HIDDEN = "Botón oculto. Escribe /codex para volver a mostrarlo.",
    SET_SWITCHED = "Conjunto de favoritos: %s",
    KEY_ONLY_5 = "Solo tus 5 primeros favoritos pueden tener una tecla. Quita la estrella a uno anterior para subir este.",
    KEY_DIALOG_FAIL = "No se pudo abrir la ventana de teclas. Asígnala en Controles > Asignación de teclas > Command Codex > Ejecutar favorito %d.",
    HELP = {
        "/codex - abrir o cerrar la ventana",
        "/codex aui - abrir la ventana buscando \"aui\"",
        "/codex bar - mostrar u ocultar tus favoritos en pantalla",
        "/codex lock - bloquear o desbloquear tus favoritos en pantalla",
        "/codex reset - devolver tus favoritos a la parte superior central",
        "/codex alias /rl /reloadui - crear un alias (separa varios comandos con ;)",
        "/codex unalias /rl - eliminar un alias",
        "/codex aliases - ver tus alias",
        "Idioma y conjuntos de favoritos: Ajustes > Addons > Command Codex",
    },

    BIND_TOGGLE = "Abrir/cerrar Command Codex",
    BIND_TOGGLE_FAVS = "Mostrar/ocultar favoritos en pantalla",
    BIND_FAV = "Ejecutar favorito %d",

    CAT_ALL = "Todos los comandos",
    CAT_FAVORITES = "Favoritos",
    CAT_RECENT = "Recientes",
    CAT_ADDONS = "Addons",
    CAT_ALIASES = "Tus alias",
    CAT_GAME = "Juego",
    CAT_EMOTES = "Gestos",
    EMOTE = "Gesto",
    OTHER = "Otros",

    SEARCH = "Buscar",
    HIDE_LIBS = "Ocultar bibliotecas",
    HIDE_LIBS_TT = "Ocultar comandos de bibliotecas (LibAddonMenu y similares).\nRara vez te harán falta.",
    SHOW_FAVS = "Mostrar favoritos",
    SHOW_FAVS_TT = "Mostrar cada favorito como un botón en pantalla.\nClic derecho en un favorito > Asignar tecla para ejecutarlo con el teclado.",
    LOCK_TT_LOCKED = "Los favoritos están bloqueados.\nHaz clic para desbloquearlos y moverlos.",
    LOCK_TT_UNLOCKED = "Los favoritos están desbloqueados: arrástralos adonde quieras.\nHaz clic para bloquearlos.",
    RESET_POS = "Restablecer posiciones",
    RESET_POS_TT = "Devolver todos tus favoritos a su posición inicial:\nuna fila en la parte superior central de la pantalla.",
    MINIMIZE = "Minimizar",
    COUNT = "%d comandos",
    EMPTY_FAVORITES = "Aún no hay favoritos.\nHaz clic en la estrella junto a un comando.",
    EMPTY_RECENT = "Aún no has ejecutado nada.\nLos comandos que ejecutes desde aquí aparecen en esta lista.",
    EMPTY_ALIASES = "Aún no hay alias. Crea uno abajo.",
    EMPTY_SEARCH = "Ningún comando coincide con tu búsqueda.",
    BTN_RUN = "Ejecutar",
    BTN_CHAT = "Al chat",
    BTN_FAVORITE = "Favorito",
    BTN_UNFAVORITE = "Quitar",
    BTN_DELETE_ALIAS = "Borrar alias",
    NEW_ALIAS = "Nuevo alias",
    RUNS = "ejecuta",
    ADD = "Añadir",
    ALIAS_ADDED = "%s añadido",
    ALIAS_TIP = "El comando que ejecuta tu alias.",
    ALIAS_TIP_CHAIN = "Consejo: un alias puede ejecutar varios comandos a la vez.\nSepáralos con ;   p. ej.  /cmd1 ; /cmd2",

    TT_ALIAS = "Tu alias. Ejecuta: %s",
    TT_FROM = "De: %s",
    TT_GAME = "Integrado en el juego.",
    TT_METHOD_NAME = "Addon deducido por el nombre del comando.",
    TT_METHOD_LOAD = "Addon detectado al cargar los addons.",
    TT_ROW_HINT = "Flecha: ejecutar.\nDoble clic: al chat.  Clic derecho: más.",
    TT_LAST_RUN = "Última ejecución: %s",
    QT_RUNS = "Ejecuta: %s",
    QT_CLICK = "Clic: ejecutar.",
    QT_KEY = "Tecla: %s  (clic derecho para cambiar)",
    QT_BIND_HINT = "Clic derecho > Asignar tecla para ejecutarlo con el teclado.",
    QT_DRAG = "Arrastra para mover.",
    LAUNCHER_TT = "Clic: abrir / minimizar\nClic derecho: favoritos en pantalla, conjuntos de favoritos\nArrastrar: mover",
    LAUNCHER_HIDE_TT = "Ocultar este botón\nEscribe /codex para volver a mostrarlo",

    MENU_RUN = "Ejecutar",
    MENU_CHAT = "Al chat",
    MENU_BIND = "Asignar tecla...",
    MENU_CHANGE_KEY = "Cambiar tecla...",
    MENU_ADD_NOTE = "Añadir nota...",
    MENU_EDIT_NOTE = "Editar nota...",
    MENU_DELETE_ALIAS = "Eliminar alias",
    MENU_RESET_POS = "Restablecer posición",
    MENU_REMOVE_FAV = "Quitar de favoritos",
    MENU_HIDE_FAVS = "Ocultar favoritos",
    MENU_SHOW_FAVS = "Mostrar favoritos",
    MENU_USE_SET = "Conjunto de favoritos: %s",
    MENU_CURRENT = "(activo)",
    MENU_SETTINGS = "Ajustes...",

    KEY_DIALOG_NAME = "Ejecutar favorito %d  (%s)",

    NOTE_TITLE = "Nota para %s",
    NOTE_HINT = "¿Qué hace este comando?",
    SAVE = "Guardar",
    CANCEL = "Cancelar",

    AGO_NOW = "ahora mismo",
    AGO_MIN = "hace %d min",
    AGO_HOUR = "hace %d h",
    AGO_DAY = "hace %d d",

    SETTINGS_LANGUAGE_HEADER = "Idioma",
    SETTINGS_LANGUAGE = "Idioma",
    SETTINGS_LANGUAGE_TT = "Idioma de este addon. Se aplica al recargar la interfaz.",
    LANG_AUTO = "Idioma del juego",
    SETS_HEADER = "Conjuntos de favoritos",
    SETS_DESC = "Cada conjunto tiene sus propios favoritos, posiciones y teclas 1-5. Usa un conjunto por personaje o cambia automáticamente en JcJ o en casa.",
    SET_DEFAULT = "Predeterminado",
    SET_THIS_CHAR = "Conjunto de este personaje",
    SET_THIS_CHAR_TT = "Los favoritos que usa este personaje.",
    SET_PVP = "En Cyrodiil y campos de batalla",
    SET_HOUSE = "En casas",
    SET_PVP_TT = "Usar este conjunto automáticamente mientras estés en Cyrodiil o en un campo de batalla.",
    SET_HOUSE_TT = "Usar este conjunto automáticamente mientras estés en una casa.",
    SET_NO_SWITCH = "No cambiar",
    NEW_SET_NAME = "Nombre del nuevo conjunto",
    CREATE_SET = "Crear conjunto",
    CREATE_SET_TT = "Crea un conjunto vacío con el nombre de arriba.",
    SET_NAME_EMPTY = "Primero escribe un nombre para el nuevo conjunto.",
    SET_EXISTS = "Ya existe un conjunto llamado %s.",
    SET_CREATED = "Conjunto de favoritos %s creado.",
    DELETE_SET_PICK = "Conjunto a eliminar",
    DELETE_SET = "Eliminar conjunto",
    DELETE_SET_WARN = "Elimina el conjunto y sus favoritos.",
    SET_DELETED = "Conjunto de favoritos %s eliminado.",
    NO_SETS_TO_DELETE = "(no hay otros conjuntos)",
}

-- ---------------------------------------------------------------------------
local active = "en"

-- choice: "auto" (the game's language) or a language code.
function S.SetLanguage(choice)
    local lang = choice
    if lang == nil or lang == "auto" or not S.STRINGS[lang] then
        lang = GetCVar and GetCVar("language.2") or "en"
    end
    if not S.STRINGS[lang] then lang = "en" end
    active = lang
end

function S.GetLanguage()
    return active
end

-- Text for key in the active language (English if missing), formatted with the extra arguments.
function S.L(key, ...)
    local text = S.STRINGS[active][key]
    if text == nil then text = S.STRINGS.en[key] end
    if text == nil then return key end
    if select("#", ...) > 0 then return string.format(text, ...) end
    return text
end

-- Until the saved setting is read, follow the game's language.
S.SetLanguage("auto")
