CraftAutoLootUpgrade = {}

CraftAutoLootUpgrade.name = "CraftAutoLootUpgrade"

function CraftAutoLootUpgrade:Initialize()
  local currentLanguage = GetCVar("Language.2")

  local searchActionTable = {
    en = { 
      ["Search"] = true,
    },
    zh = { 
      ["搜索"] = true,
    },
    ru = { 
      ["Обыскать"] = true,
    },
    de = { 
      ["Durchsuchen"] = true,
    },
    es = { 
      ["Buscar"] = true,
    },
    fr = { 
      ["Fouiller"] = true,
    },
    jp = { 
      ["調査"] = true,
    },
  }

  local actionTable = {
    en = { 
      ["Mine"] = true,
      ["Collect"] = true,
      ["Cut"] = true,
      ["Reel In"] = true,
    },
    zh = { 
      ["开采"] = true,
      ["收集"] = true,
      ["砍伐"] = true,
      ["卷线"] = true,
    },
    ru = { 
      ["Добыть"] = true,
      ["Взять"] = true,
      ["Рубить"] = true,
      ["Выудить"] = true,
    },
    de = { 
      ["Abbauen"] = true,
      ["Nehmen"] = true,
      ["Hacken"] = true,
      ["Einholen"] = true,
    },
    es = { 
      ["Minar"] = true,
      ["Recoger"] = true,
      ["Cortar"] = true,
      ["Recoger sedal"] = true,
    },
    fr = { 
      ["Extraire"] = true,
      ["Ramasser"] = true,
      ["Couper"] = true,
      ["Ramener la ligne"] = true,
    },
    jp = { 
      ["採掘する"] = true,
      ["集める"] = true,
      ["切る"] = true,
      ["引き寄せ"] = true,
    },
  }

  local lootableTable = {
    en = {
      ["Apple Basket"] = true,
      ["Apple Crate"] = true,
      ["Apples"] = true,
      ["Backpack"] = true,
      ["Bookshelf"] = true,
      ["Barrel"] = true,
      ["Barrels"] = true,
      ["Basket"] = true,
      ["Cabinet"] = true,
      ["Cauldron"] = true,
      ["Cupboard"] = true,
      ["Corn Basket"] = true,
      ["Crate"] = true,
      ["Crates"] = true,
      ["Desk"] = true,
      ["Drawers"] = true,
      ["Dresser"] = true,
      ["Flour Sack"] = true,
      ["Greens Basket"] = true,
      ["Heavy Crate"] = true,
      ["Heavy Sack"] = true,
      ["Jewelry Box"] = true,
      ["Keg"] = true,
      ["Melon Basket"] = true,
      ["Millet Basket"] = true,
      ["Nightstand"] = true,
      ["Pumpkin Basket"] = true,
      ["Rack"] = true,
      ["Sack"] = true,
      ["Saltrice Sack"] = true,
      ["Seasoning Sack"] = true,
      ["Tomato Crate"] = true,
      ["Trunk"] = true,
      ["Urn"] = true,
      ["Wardrobe"] = true,
    },
    zh = {
      ["苹果篮子"] = true,
      ["Apple Crate"] = true,
      ["苹果"] = true,
      ["背包"] = true,
      ["书架"] = true,
      ["桶"] = true,
      ["篮子"] = true,
      ["柜子"] = true,
      ["大锅"] = true,
      ["橱柜"] = true,
      ["玉米篮子"] = true,
      ["木箱"] = true,
      ["书桌"] = true,
      ["抽屉"] = true,
      ["梳妆台"] = true,
      ["面粉袋子"] = true,
      ["卷心菜篮子"] = true,
      ["重木箱"] = true,
      ["重麻袋"] = true,
      ["珠宝盒"] = true,
      ["小桶"] = true,
      ["甜瓜篮子"] = true,
      ["Millet Basket"] = true,
      ["床头柜"] = true,
      ["南瓜篮子"] = true,
      ["架子"] = true,
      ["袋子"] = true,
      ["盐米袋子"] = true,
      ["调料袋子"] = true,
      ["番茄箱子"] = true,
      ["瓮"] = true,
      ["衣柜"] = true,
    },
    ru = {
      ["Корзина яблоками"] = true,
      ["Apple Crate"] = true,
      ["Яблоки"] = true,
      ["Заплечный мешок"] = true,
      ["Книжная полка"] = true,
      ["Бочка"] = true,
      ["Корзина"] = true,
      ["Шкаф"] = true,
      ["Котел"] = true,
      ["Буфет"] = true,
      ["Корзина кукурузой"] = true,
      ["Ящики"] = true,
      ["Ящик"] = true,
      ["Стол"] = true,
      ["Комод"] = true,
      ["Мешок мукой"] = true,
      ["Корзина зеленью"] = true,
      ["Тяжелый ящик"] = true,
      ["Тяжелый мешок"] = true,
      ["Шкатулка для драгоценностей"] = true,
      ["Бочонок"] = true,
      ["Корзина дынями"] = true,
      ["Millet Basket"] = true,
      ["Тумбочка"] = true,
      ["Корзина тыквами"] = true,
      ["Стойка"] = true,
      ["Мешок"] = true,
      ["Мешок соленым рисом"] = true,
      ["Мешок приправами"] = true,
      ["помидорами"] = true,
      ["Сундук"] = true,
      ["Урна"] = true,
      ["Платяной шкаф"] = true,
    },
    de = {
      ["Apfelkorb"] = true,
      ["Apple Crate"] = true,
      ["Äpfel"] = true,
      ["Rucksack"] = true,
      ["Bücherregal"] = true,
      ["Fass"] = true,
      ["Fässer"] = true,
      ["Korb"] = true,
      ["Wandschrank"] = true,
      ["Kessel"] = true,
      ["Schrank"] = true,
      ["Korb mit Mais"] = true,
      ["Kisten"] = true,
      ["Kiste"] = true,
      ["Schreibtisch"] = true,
      ["Schubladen"] = true,
      ["Kommode"] = true,
      ["Mehlsack"] = true,
      ["Melonenkorb"] = true,
      ["schwere Kiste"] = true,
      ["schwerer Sack"] = true,
      ["Schmuckkästchen"] = true,
      ["Fässchen"] = true,
      ["Millet Basket"] = true,
      ["Beistelltisch"] = true,
      ["Kürbiskorb"] = true,
      ["Regal"] = true,
      ["Sack"] = true,
      ["Salzreissack"] = true,
      ["Gewürzsack"] = true,
      ["Tomatenkiste"] = true,
      ["Truhe"] = true,
      ["Urne"] = true,
      ["Garderobe"] = true,
    },
    es = {
      ["Cesta de manzanas"] = true,
      ["Apple Crate"] = true,
      ["Manzanas"] = true,
      ["Mochila"] = true,
      ["Estante de libros"] = true,
      ["Barril"] = true,
      ["Barriles"] = true,
      ["Cesta"] = true,
      ["Aparador"] = true,
      ["Caldero"] = true,
      ["Alacena"] = true,
      ["Cesta de maíz"] = true,
      ["Cajas"] = true,
      ["Caja"] = true,
      ["Escritorio"] = true,
      ["cajones"] = true,
      ["tocador"] = true,
      ["Saco de harina"] = true,
      ["Cesta de verduras"] = true,
      ["caja pesada"] = true,
      ["saco pesado"] = true,
      ["Joyero"] = true,
      ["Cesta de melones"] = true,
      ["Millet Basket"] = true,
      ["Mesita de noche"] = true,
      ["Cesta de calabazas"] = true,
      ["Estante"] = true,
      ["Saco"] = true,
      ["Saco de arroz de sal"] = true,
      ["Saco de especias"] = true,
      ["Caja de tomates"] = true,
      ["Baúl"] = true,
      ["Urna"] = true,
      ["Guardarropa"] = true,
    },
    fr = {
      ["Panier de pommes"] = true,
      ["Apple Crate"] = true,
      ["Pommes"] = true,
      ["Sac à dos"] = true,
      ["Étagère de livres"] = true,
      ["Tonneau"] = true,
      ["Tonneaux"] = true,
      ["Panier"] = true,
      ["Meuble"] = true,
      ["Chaudron"] = true,
      ["Placard"] = true,
      ["Panier de maïs"] = true,
      ["Caisses"] = true,
      ["Caisse"] = true,
      ["Bureau"] = true,
      ["tiroirs"] = true,
      ["Commode"] = true,
      ["Sac de farine"] = true,
      ["Panier de légumes"] = true,
      ["caisse pesante"] = true,
      ["sac lourd"] = true,
      ["Coffret à bijoux"] = true,
      ["Tonnelet"] = true,
      ["Panier de melons"] = true,
      ["Millet Basket"] = true,
      ["Table de chevet"] = true,
      ["Panier de citrouilles"] = true,
      ["Casier"] = true,
      ["Sac"] = true,
      ["Sac de riz-de-sel"] = true,
      ["Sac d'épices"] = true,
      ["Caisse de tomates"] = true,
      ["Coffre"] = true,
      ["Urne"] = true,
      ["Garde-robe"] = true,
    },
    jp = {
      ["リンゴのかご"] = true,
      ["Apple Crate"] = true,
      ["リンゴ"] = true,
      ["バックパック"] = true,
      ["本棚"] = true,
      ["樽"] = true,
      ["かご"] = true,
      ["キャビネット"] = true,
      ["大がま"] = true,
      ["戸棚"] = true,
      ["トウモロコシのかご"] = true,
      ["木枠箱"] = true,
      ["机"] = true,
      ["ドロワース"] = true,
      ["ドレッサー"] = true,
      ["小麦粉の袋"] = true,
      ["青菜のかご"] = true,
      ["重い木枠箱"] = true,
      ["重い袋"] = true,
      ["宝石箱"] = true,
      ["小樽"] = true,
      ["メロンのかご"] = true,
      ["Millet Basket"] = true,
      ["ナイトテーブル"] = true,
      ["カボチャのかご"] = true,
      ["棚"] = true,
      ["袋"] = true,
      ["サルトリスの袋"] = true,
      ["調味料の袋"] = true,
      ["トマトの木枠箱"] = true,
      ["トランク"] = true,
      ["壷"] = true,
      ["ワードローブ"] = true,
    },
  }

  local isAction    = actionTable[currentLanguage] or {}
  local isLootable  = lootableTable[currentLanguage] or {}
  local searchAction = searchActionTable[currentLanguage] or {}


  ZO_ReticleContainerInteract:SetHandler("OnShow", function()
    local action, container, _, _, additionalInfo, _ = GetGameCameraInteractableActionInfo()

    if isAction[action] or (isLootable[container] and searchAction[action]) then
      SetSetting(SETTING_TYPE_LOOT, LOOT_SETTING_AUTO_LOOT, 1)
    else
      SetSetting(SETTING_TYPE_LOOT, LOOT_SETTING_AUTO_LOOT, 0)
    end
  end)
end

function CraftAutoLootUpgrade.OnAddOnLoaded(event, addonName)
  if addonName ~= CraftAutoLootUpgrade.name then
    return
  end
  EVENT_MANAGER:UnregisterForEvent(CraftAutoLootUpgrade.name, EVENT_ADD_ON_LOADED)
  CraftAutoLootUpgrade:Initialize()
end

EVENT_MANAGER:RegisterForEvent(CraftAutoLootUpgrade.name, EVENT_ADD_ON_LOADED, CraftAutoLootUpgrade.OnAddOnLoaded)