----------------------------------------------------------------------
-- SmartGear — Meta Set Database
-- AUTO-GENERATED by SmartGear Updater on 2026-03-29 11:55
-- Total sets: 182
-- Do not edit manually — changes will be overwritten!
-- Use overrides.json for manual adjustments.
----------------------------------------------------------------------
SmartGear = SmartGear or {}

----------------------------------------------------------------------
-- Role definitions & optimal traits/weights
----------------------------------------------------------------------
SmartGear.RoleConfig = {
    MagDD = {
        optimalTraits = { [ITEM_TRAIT_TYPE_ARMOR_DIVINES] = true },
        pvpTraits     = { [ITEM_TRAIT_TYPE_ARMOR_IMPENETRABLE] = true },
        optimalWeights = { [ARMORTYPE_LIGHT] = true },
        optimalJewelryTrait = { [ITEM_TRAIT_TYPE_JEWELRY_BLOODTHIRSTY] = true },
        optimalWeaponTraits = {
            [ITEM_TRAIT_TYPE_WEAPON_PRECISE] = true,
            [ITEM_TRAIT_TYPE_WEAPON_INFUSED] = true,
        },
        description = "Magicka Damage Dealer",
    },
    StamDD = {
        optimalTraits = { [ITEM_TRAIT_TYPE_ARMOR_DIVINES] = true },
        pvpTraits     = { [ITEM_TRAIT_TYPE_ARMOR_IMPENETRABLE] = true },
        optimalWeights = { [ARMORTYPE_MEDIUM] = true },
        optimalJewelryTrait = { [ITEM_TRAIT_TYPE_JEWELRY_BLOODTHIRSTY] = true },
        optimalWeaponTraits = {
            [ITEM_TRAIT_TYPE_WEAPON_PRECISE] = true,
            [ITEM_TRAIT_TYPE_WEAPON_INFUSED] = true,
        },
        description = "Stamina Damage Dealer",
    },
    Tank = {
        optimalTraits = { [ITEM_TRAIT_TYPE_ARMOR_STURDY] = true },
        pvpTraits     = { [ITEM_TRAIT_TYPE_ARMOR_IMPENETRABLE] = true },
        optimalWeights = { [ARMORTYPE_HEAVY] = true },
        optimalJewelryTrait = {
            [ITEM_TRAIT_TYPE_JEWELRY_PROTECTIVE] = true,
            [ITEM_TRAIT_TYPE_JEWELRY_TRIUNE] = true,
        },
        optimalWeaponTraits = {
            [ITEM_TRAIT_TYPE_WEAPON_INFUSED] = true,
            [ITEM_TRAIT_TYPE_WEAPON_DECISIVE] = true,
        },
        description = "Tank",
    },
    Healer = {
        optimalTraits = { [ITEM_TRAIT_TYPE_ARMOR_DIVINES] = true },
        pvpTraits     = { [ITEM_TRAIT_TYPE_ARMOR_IMPENETRABLE] = true },
        optimalWeights = { [ARMORTYPE_LIGHT] = true },
        optimalJewelryTrait = { [ITEM_TRAIT_TYPE_JEWELRY_ARCANE] = true },
        optimalWeaponTraits = {
            [ITEM_TRAIT_TYPE_WEAPON_POWERED] = true,
            [ITEM_TRAIT_TYPE_WEAPON_INFUSED] = true,
        },
        description = "Healer",
    },
}

----------------------------------------------------------------------
-- Trait display names
----------------------------------------------------------------------
SmartGear.TraitNames = {
    [ITEM_TRAIT_TYPE_ARMOR_DIVINES] = "Divines",
    [ITEM_TRAIT_TYPE_ARMOR_IMPENETRABLE] = "Impenetrable",
    [ITEM_TRAIT_TYPE_ARMOR_INFUSED] = "Infused",
    [ITEM_TRAIT_TYPE_ARMOR_REINFORCED] = "Reinforced",
    [ITEM_TRAIT_TYPE_ARMOR_STURDY] = "Sturdy",
    [ITEM_TRAIT_TYPE_ARMOR_TRAINING] = "Training",
    [ITEM_TRAIT_TYPE_ARMOR_WELL_FITTED] = "Well-Fitted",
    [ITEM_TRAIT_TYPE_ARMOR_NIRNHONED] = "Nirnhoned",
    [ITEM_TRAIT_TYPE_WEAPON_PRECISE] = "Precise",
    [ITEM_TRAIT_TYPE_WEAPON_INFUSED] = "Infused",
    [ITEM_TRAIT_TYPE_WEAPON_SHARPENED] = "Sharpened",
    [ITEM_TRAIT_TYPE_WEAPON_CHARGED] = "Charged",
    [ITEM_TRAIT_TYPE_WEAPON_POWERED] = "Powered",
    [ITEM_TRAIT_TYPE_WEAPON_DECISIVE] = "Decisive",
    [ITEM_TRAIT_TYPE_WEAPON_NIRNHONED] = "Nirnhoned",
    [ITEM_TRAIT_TYPE_WEAPON_TRAINING] = "Training",
    [ITEM_TRAIT_TYPE_JEWELRY_ARCANE] = "Arcane",
    [ITEM_TRAIT_TYPE_JEWELRY_BLOODTHIRSTY] = "Bloodthirsty",
    [ITEM_TRAIT_TYPE_JEWELRY_HARMONY] = "Harmony",
    [ITEM_TRAIT_TYPE_JEWELRY_INFUSED] = "Infused",
    [ITEM_TRAIT_TYPE_JEWELRY_PROTECTIVE] = "Protective",
    [ITEM_TRAIT_TYPE_JEWELRY_ROBUST] = "Robust",
    [ITEM_TRAIT_TYPE_JEWELRY_SWIFT] = "Swift",
    [ITEM_TRAIT_TYPE_JEWELRY_TRIUNE] = "Triune",
}

----------------------------------------------------------------------
-- Content Contexts
-- Each context adjusts stat targets based on what the player
-- has access to (group buffs, tank debuffs, healer support).
----------------------------------------------------------------------
SmartGear.ContentContexts = {
    solo      = { name = "Solo",         nameRu = "Соло",           desc = "Overland, questing, solo arenas" },
    dungeon   = { name = "Dungeon",      nameRu = "Данж",           desc = "4-man group dungeons" },
    trial     = { name = "Trial",        nameRu = "Триал",          desc = "12-man raids with full support" },
    pvp       = { name = "PvP",          nameRu = "PvP",            desc = "Battlegrounds, Cyrodiil" },
}

----------------------------------------------------------------------
-- Group buff assumptions per context
-- These are subtracted from raw targets to get personal targets.
----------------------------------------------------------------------
SmartGear.GroupBuffs = {
    solo = {
        penFromGroup    = 0,       -- no tank
        wsdFromGroup    = 0,       -- no healer courage
        critFromGroup   = 0,       -- only self-buffs
        hasMajorForce   = false,   -- no warhorn
        hasMajorSlayer  = false,
    },
    dungeon = {
        penFromGroup    = 11030,   -- Major+Minor Breach (8922) + Crusher (2108)
        wsdFromGroup    = 430,     -- Major Courage from healer
        critFromGroup   = 0,
        hasMajorForce   = false,   -- rare in dungeons
        hasMajorSlayer  = false,
    },
    trial = {
        penFromGroup    = 17000,   -- Breach + Crusher + Alkosh
        wsdFromGroup    = 645,     -- Major+Minor Courage
        critFromGroup   = 0,
        hasMajorForce   = true,    -- +20% crit dmg from warhorn
        hasMajorSlayer  = true,    -- +10% damage
    },
    pvp = {
        penFromGroup    = 0,       -- solo or small group
        wsdFromGroup    = 0,
        critFromGroup   = 0,
        hasMajorForce   = false,
        hasMajorSlayer  = false,
    },
}

----------------------------------------------------------------------
-- Stat targets per role PER CONTEXT
-- These are PERSONAL targets (after subtracting group buffs).
--
-- Research sources: Alcast, Skinnycheeks, Hack the Minotaur,
-- ArzyeLBuilds, The Tank Club, ESO-Hub, UESP (2025-2026 meta).
----------------------------------------------------------------------
SmartGear.StatTargets = {}

-- DD targets by context
SmartGear.StatTargets.MagDD = {
    solo = {
        weaponDamage = 4500,   -- no group courage, self-buffed
        critPercent  = 50,
        penetration  = 14000,  -- solo arena: no tank, need high self-pen
        maxResource  = 30000,
        maxHealth    = 22000,  -- survivability matters solo
        resistance   = 0,
        critResist   = 0,
        healingDone  = 0,
        -- Solo priorities: survivability > sustain > pen > crit > damage
        priorities = { "maxHealth", "maxResource", "penetration", "critPercent", "weaponDamage" },
    },
    dungeon = {
        weaponDamage = 5000,   -- group provides ~430 from Major Courage
        critPercent  = 60,
        penetration  = 7200,   -- 18200 - 11030 from tank
        maxResource  = 32000,
        maxHealth    = 18000,  -- healer present
        resistance   = 0,
        critResist   = 0,
        healingDone  = 0,
        priorities = { "penetration", "critPercent", "weaponDamage", "maxResource" },
    },
    trial = {
        weaponDamage = 4000,   -- group provides ~645 WSD
        critPercent  = 60,
        penetration  = 1200,   -- 18200 - 17000 from full group
        maxResource  = 32000,
        maxHealth    = 17000,  -- full healer support
        resistance   = 0,
        critResist   = 0,
        healingDone  = 0,
        priorities = { "critPercent", "weaponDamage", "maxResource" },
    },
    pvp = {
        weaponDamage = 5500,   -- burst damage
        critPercent  = 40,     -- crit less reliable in PvP (crit resist)
        penetration  = 12000,  -- players have 20-33k resist
        maxResource  = 28000,
        maxHealth    = 28000,  -- survivability critical
        resistance   = 25000,  -- need defenses
        critResist   = 2000,
        healingDone  = 0,
        priorities = { "maxHealth", "penetration", "weaponDamage", "resistance", "maxResource" },
    },
}

-- StamDD same structure as MagDD
SmartGear.StatTargets.StamDD = {
    solo = {
        weaponDamage = 4500,   critPercent  = 50,
        penetration  = 14000,  maxResource  = 30000,
        maxHealth    = 22000,  resistance   = 0,
        critResist   = 0,      healingDone  = 0,
        priorities = { "maxHealth", "maxResource", "penetration", "critPercent", "weaponDamage" },
    },
    dungeon = {
        weaponDamage = 5000,   critPercent  = 60,
        penetration  = 7200,   maxResource  = 32000,
        maxHealth    = 18000,  resistance   = 0,
        critResist   = 0,      healingDone  = 0,
        priorities = { "penetration", "critPercent", "weaponDamage", "maxResource" },
    },
    trial = {
        weaponDamage = 4000,   critPercent  = 60,
        penetration  = 1200,   maxResource  = 32000,
        maxHealth    = 17000,  resistance   = 0,
        critResist   = 0,      healingDone  = 0,
        priorities = { "critPercent", "weaponDamage", "maxResource" },
    },
    pvp = {
        weaponDamage = 5500,   critPercent  = 40,
        penetration  = 12000,  maxResource  = 28000,
        maxHealth    = 28000,  resistance   = 25000,
        critResist   = 2000,   healingDone  = 0,
        priorities = { "maxHealth", "penetration", "weaponDamage", "resistance", "maxResource" },
    },
}

-- Tank targets
SmartGear.StatTargets.Tank = {
    solo = {
        weaponDamage = 2500,   critPercent  = 15,
        penetration  = 9100,   maxResource  = 25000,
        maxHealth    = 35000,  resistance   = 30000,
        critResist   = 0,      healingDone  = 0,
        priorities = { "resistance", "maxHealth", "maxResource" },
    },
    dungeon = {
        weaponDamage = 2000,   critPercent  = 10,
        penetration  = 0,      maxResource  = 28000,
        maxHealth    = 35000,  resistance   = 28000,
        critResist   = 0,      healingDone  = 0,
        priorities = { "resistance", "maxHealth", "maxResource" },
    },
    trial = {
        weaponDamage = 2000,   critPercent  = 10,
        penetration  = 0,      maxResource  = 30000,
        maxHealth    = 42000,  resistance   = 33000,
        critResist   = 0,      healingDone  = 0,
        priorities = { "maxHealth", "resistance", "maxResource" },
    },
    pvp = {
        weaponDamage = 3000,   critPercent  = 15,
        penetration  = 8000,   maxResource  = 28000,
        maxHealth    = 35000,  resistance   = 33000,
        critResist   = 3000,   healingDone  = 0,
        priorities = { "resistance", "maxHealth", "critResist", "maxResource" },
    },
}

-- Healer targets
SmartGear.StatTargets.Healer = {
    solo = {
        weaponDamage = 4000,   critPercent  = 45,
        penetration  = 9100,   maxResource  = 32000,
        maxHealth    = 22000,  resistance   = 0,
        critResist   = 0,      healingDone  = 10,
        priorities = { "maxHealth", "maxResource", "weaponDamage", "critPercent" },
    },
    dungeon = {
        weaponDamage = 3000,   critPercent  = 50,
        penetration  = 0,      maxResource  = 35000,
        maxHealth    = 20000,  resistance   = 0,
        critResist   = 0,      healingDone  = 12,
        priorities = { "maxResource", "critPercent", "weaponDamage" },
    },
    trial = {
        weaponDamage = 3500,   critPercent  = 55,
        penetration  = 0,      maxResource  = 38000,
        maxHealth    = 21000,  resistance   = 0,
        critResist   = 0,      healingDone  = 15,
        priorities = { "maxResource", "critPercent", "weaponDamage", "healingDone" },
    },
    pvp = {
        weaponDamage = 3500,   critPercent  = 35,
        penetration  = 6000,   maxResource  = 30000,
        maxHealth    = 28000,  resistance   = 25000,
        critResist   = 2000,   healingDone  = 8,
        priorities = { "maxHealth", "resistance", "maxResource", "weaponDamage" },
    },
}

----------------------------------------------------------------------
-- Trait -> stat mapping (for adaptive trait scoring)
-- "mundus" resolves to the stat of the player's active mundus stone
----------------------------------------------------------------------
SmartGear.TraitStatMap = {
    -- Armor traits
    [ITEM_TRAIT_TYPE_ARMOR_DIVINES]       = { stat = "mundus",      weight = 1.0 },
    [ITEM_TRAIT_TYPE_ARMOR_INFUSED]       = { stat = "enchant",     weight = 0.7 },
    [ITEM_TRAIT_TYPE_ARMOR_REINFORCED]    = { stat = "resistance",  weight = 1.0 },
    [ITEM_TRAIT_TYPE_ARMOR_STURDY]        = { stat = "blockCost",   weight = 1.0 },
    [ITEM_TRAIT_TYPE_ARMOR_IMPENETRABLE]  = { stat = "critResist",  weight = 1.0 },
    [ITEM_TRAIT_TYPE_ARMOR_WELL_FITTED]   = { stat = "dodge",       weight = 0.5 },
    [ITEM_TRAIT_TYPE_ARMOR_NIRNHONED]     = { stat = "resistance",  weight = 0.8 },
    [ITEM_TRAIT_TYPE_ARMOR_TRAINING]      = { stat = "none",        weight = 0.0 },
    -- Weapon traits
    [ITEM_TRAIT_TYPE_WEAPON_PRECISE]      = { stat = "critPercent", weight = 1.0 },
    [ITEM_TRAIT_TYPE_WEAPON_SHARPENED]    = { stat = "penetration", weight = 1.0 },
    [ITEM_TRAIT_TYPE_WEAPON_INFUSED]      = { stat = "enchant",     weight = 0.8 },
    [ITEM_TRAIT_TYPE_WEAPON_CHARGED]      = { stat = "statusEffect", weight = 0.6 },
    [ITEM_TRAIT_TYPE_WEAPON_NIRNHONED]    = { stat = "weaponDamage", weight = 1.0 },
    [ITEM_TRAIT_TYPE_WEAPON_POWERED]      = { stat = "healingDone", weight = 1.0 },
    [ITEM_TRAIT_TYPE_WEAPON_DECISIVE]     = { stat = "ultimateGen", weight = 0.6 },
    [ITEM_TRAIT_TYPE_WEAPON_TRAINING]     = { stat = "none",        weight = 0.0 },
    -- Jewelry traits
    [ITEM_TRAIT_TYPE_JEWELRY_BLOODTHIRSTY] = { stat = "executeDmg",  weight = 0.8 },
    [ITEM_TRAIT_TYPE_JEWELRY_ARCANE]       = { stat = "maxResource", weight = 0.8 },
    [ITEM_TRAIT_TYPE_JEWELRY_ROBUST]       = { stat = "maxResource", weight = 0.8 },
    [ITEM_TRAIT_TYPE_JEWELRY_INFUSED]      = { stat = "enchant",     weight = 0.7 },
    [ITEM_TRAIT_TYPE_JEWELRY_PROTECTIVE]   = { stat = "resistance",  weight = 0.8 },
    [ITEM_TRAIT_TYPE_JEWELRY_HARMONY]      = { stat = "ultimateGen", weight = 0.5 },
    [ITEM_TRAIT_TYPE_JEWELRY_TRIUNE]       = { stat = "maxResource", weight = 0.7 },
    [ITEM_TRAIT_TYPE_JEWELRY_SWIFT]        = { stat = "none",        weight = 0.0 },
}

----------------------------------------------------------------------
-- Meta Sets Database (auto-generated)
----------------------------------------------------------------------
SmartGear.MetaSets = {

    -- DUNGEON SETS
    ["Tide-Born Wildstalker"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 21,
        source = "Dungeon",
        notes = "Dungeon set",
    },

    -- MONSTER SET SETS
    ["Slimecraw"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 71,
        source = "Slimecraw in Wayrest Sewers I, Maj al-Ragath",
        notes = "Minor Berserk, 1pc crit",
        isMonsterSet = true,
    },
    ["Stormfist"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 54,
        source = "Stormreeve Neidir in Tempest Island, Glirion the Redbeard",
        notes = "Monster Set set",
        isMonsterSet = true,
    },
    ["Maw of the Infernal"] = {
        roles = { "MagDD" },
        tier = "S",
        rating = 30,
        source = "High Kinlord Rilis in Banished Cells II, Maj al-Ragath",
        notes = "Monster Set set",
        isMonsterSet = true,
    },
    ["Domihaus"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 26,
        source = "Domihaus the Bloody-Horned in Falkreath Hold, Urgarlag Chief-bane",
        notes = "Monster Set set",
        isMonsterSet = true,
    },
    ["Kra'gh"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 26,
        source = "Kra'gh the Dreugh King in Fungal Grotto I, Maj al-Ragath",
        notes = "Monster Set set",
        isMonsterSet = true,
    },
    ["Maarselok"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 26,
        source = "Maarselok in Lair of Maarselok, Urgarlag Chief-bane",
        notes = "Monster Set set",
        isMonsterSet = true,
    },
    ["Selene"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 26,
        source = "Selene in Selene's Web, Glirion the Redbeard",
        notes = "Monster Set set",
        isMonsterSet = true,
    },
    ["Velidreth"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 26,
        source = "Velidreth in Cradle of Shadows, Urgarlag Chief-bane",
        notes = "Monster Set set",
        isMonsterSet = true,
    },
    ["Earthgore"] = {
        roles = { "Healer", "Tank" },
        tier = "S",
        rating = 23,
        source = "Earthgore Amalgam in Bloodroot Forge, Urgarlag Chief-bane",
        notes = "Monster Set set",
        isMonsterSet = true,
    },
    ["Symphony of Blades"] = {
        roles = { "Healer" },
        tier = "S",
        rating = 23,
        source = "Symphony of Blades in Depths of Malatar, Urgarlag Chief-bane",
        notes = "Resource return for lowest member",
        isMonsterSet = true,
    },
    ["Nazaray"] = {
        roles = { "Tank" },
        tier = "S",
        rating = 17,
        source = "Captain Numirril in Shipwright's Regret, Urgarlag Chief-bane",
        notes = "Monster Set set",
        isMonsterSet = true,
    },
    ["Lord Warden"] = {
        roles = { "Tank" },
        tier = "S",
        rating = 0,
        source = "Lord Warden Dusk in Imperial City Prison, Urgarlag Chief-bane",
        notes = "Group resistances",
        isMonsterSet = true,
    },
    ["Mighty Chudan"] = {
        roles = { "Tank" },
        tier = "A",
        rating = 16,
        source = "Tree-Minder Na-Kesh in Ruins of Mazzatun, Urgarlag Chief-bane",
        notes = "Monster Set set",
        isMonsterSet = true,
    },
    ["Tremorscale"] = {
        roles = { "Tank" },
        tier = "A",
        rating = 14,
        source = "Guardian Council in Volenfell, Glirion the Redbeard",
        notes = "Monster Set set",
        isMonsterSet = true,
    },
    ["Archdruid Devyric"] = {
        roles = { "Tank" },
        tier = "A",
        rating = 11,
        source = "Archdruid Devyric in Earthen Root Enclave, Urgarlag Chief-bane",
        notes = "Monster Set set",
        isMonsterSet = true,
    },
    ["Balorgh"] = {
        roles = { "MagDD" },
        tier = "A",
        rating = 11,
        source = "Balorgh in March of Sacrifices, Urgarlag Chief-bane",
        notes = "Monster Set set",
        isMonsterSet = true,
    },
    ["Bloodspawn"] = {
        roles = { "Tank" },
        tier = "A",
        rating = 11,
        source = "Vorenor Winterbourne in Spindleclutch II, Maj al-Ragath",
        notes = "Monster Set set",
        isMonsterSet = true,
    },
    ["Chokethorn"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "Canonreeve Oraneth in Elden Hollow I, Maj al-Ragath",
        notes = "Monster Set set",
        isMonsterSet = true,
    },
    ["Encratis's Behemoth"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "Pyroturge Encratis in Black Drake Villa, Urgarlag Chief-bane",
        notes = "Monster Set set",
        isMonsterSet = true,
    },
    ["Grothdarr"] = {
        roles = { "MagDD" },
        tier = "A",
        rating = 11,
        source = "Mad Architect in Vaults of Madness, Glirion the Redbeard",
        notes = "Monster Set set",
        isMonsterSet = true,
    },
    ["Iceheart"] = {
        roles = { "MagDD" },
        tier = "A",
        rating = 11,
        source = "Drodda of Icereach in Direfrost Keep, Glirion the Redbeard",
        notes = "Monster Set set",
        isMonsterSet = true,
    },
    ["Ilambris"] = {
        roles = { "MagDD" },
        tier = "A",
        rating = 11,
        source = "Ilambris-Athor or Ilambris-Zaven in Crypt of Hearts I, Glirion the Redbeard",
        notes = "Monster Set set",
        isMonsterSet = true,
    },
    ["Nightflame"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "Bogdan the Nightflame in Elden Hollow II, Maj al-Ragath",
        notes = "Monster Set set",
        isMonsterSet = true,
    },
    ["Sentinel of Rkugamz"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "Sentinel of Rkugamz in Darkshade Caverns I, Maj al-Ragath",
        notes = "Monster Set set",
        isMonsterSet = true,
    },
    ["Swarm Mother"] = {
        roles = { "Tank" },
        tier = "A",
        rating = 11,
        source = "The Whisperer in Spindleclutch I, Maj al-Ragath",
        notes = "Monster Set set",
        isMonsterSet = true,
    },
    ["The Troll King"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "The Lava Queen in Blessed Crucible, Glirion the Redbeard",
        notes = "Monster Set set",
        isMonsterSet = true,
    },
    ["Valkyn Skoria"] = {
        roles = { "MagDD" },
        tier = "A",
        rating = 11,
        source = "Valkyn Skoria in City of Ash II, Glirion the Redbeard",
        notes = "Monster Set set",
        isMonsterSet = true,
    },
    ["Zaan"] = {
        roles = { "MagDD" },
        tier = "A",
        rating = 11,
        source = "Dragon Bones in Scalecaller Peak, Urgarlag Chief-bane",
        notes = "Monster Set set",
        isMonsterSet = true,
    },
    ["Kjalnar's Nightmare"] = {
        roles = { "MagDD" },
        tier = "B",
        rating = 6,
        source = "Kjalnar Tombskald in Unhallowed Grave, Urgarlag Chief-bane",
        notes = "Monster Set set",
        isMonsterSet = true,
    },

    -- MYTHIC SETS
    ["Velothi Ur-Mage's Amulet"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 69,
        source = "Fragment Leads",
        notes = "Mythic set",
        isMythic = true,
    },
    ["Death Dealer's Fete"] = {
        roles = { "MagDD", "StamDD", "Tank" },
        tier = "S",
        rating = 49,
        source = "Fragment Leads",
        notes = "Mythic set",
        isMythic = true,
    },
    ["Harpooner's Wading Kilt"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 37,
        source = "Fragment Leads",
        notes = "Stacking crit damage, BiS for parsing",
        isMythic = true,
    },
    ["Ring of the Pale Order"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 26,
        source = "Fragment Leads",
        notes = "Mythic set",
        isMythic = true,
    },
    ["Bloodlord's Embrace"] = {
        roles = { "Tank" },
        tier = "A",
        rating = 11,
        source = "Fragment Leads",
        notes = "Mythic set",
        isMythic = true,
    },
    ["Pearls of Ehlnofey"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "Fragment Leads",
        notes = "Mythic set",
        isMythic = true,
    },
    ["Spaulder of Ruin"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "Fragment Leads",
        notes = "Mythic set",
        isMythic = true,
    },
    ["Oakensoul Ring"] = {
        roles = { "Healer", "MagDD", "StamDD", "Tank" },
        tier = "A",
        rating = 0,
        source = "Fragment Leads",
        notes = "One-bar build enabler, many buffs",
        isMythic = true,
    },

    -- PVP SETS
    ["The Morag Tong"] = {
        roles = { "MagDD", "StamDD", "Tank" },
        tier = "S",
        rating = 37,
        source = "Cyrodiil, Bruma",
        notes = "PvP set",
        pvpOnly = true,
    },
    ["Deadly Strike"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 26,
        source = "Cyrodiil, Bruma",
        notes = "PvP set",
        pvpOnly = true,
    },
    ["Spell Power Cure"] = {
        roles = { "Healer" },
        tier = "S",
        rating = 24,
        source = "Imperial City, White-Gold Tower",
        notes = "PvP set",
        pvpOnly = true,
    },
    ["Alessian Order"] = {
        roles = { "Tank" },
        tier = "A",
        rating = 11,
        source = "Cyrodiil, Vlastarus",
        notes = "PvP set",
        pvpOnly = true,
    },
    ["Brands of Imperium"] = {
        roles = { "Tank" },
        tier = "A",
        rating = 11,
        source = "Imperial City, White-Gold Tower",
        notes = "PvP set",
        pvpOnly = true,
    },
    ["Leeching Plate"] = {
        roles = { "Tank" },
        tier = "A",
        rating = 11,
        source = "Imperial City, Imperial City Prison",
        notes = "PvP set",
        pvpOnly = true,
    },
    ["Scathing Mage"] = {
        roles = { "MagDD" },
        tier = "A",
        rating = 11,
        source = "Imperial City, Imperial City Prison",
        notes = "PvP set",
        pvpOnly = true,
    },

    -- CRAGLORN, FALKREATH HOLD SETS
    ["Pillar of Nirn"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 100,
        source = "Craglorn, Falkreath Hold",
        notes = "Top proc DPS set, AoE damage",
    },

    -- SUMMERSET, CLOUDREST SETS
    ["Perfected Arms of Relequen"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 90,
        source = "Summerset, Cloudrest",
        notes = "Trial set",
    },
    ["Arms of Relequen"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 26,
        source = "Summerset, Cloudrest",
        notes = "Trial set",
    },
    ["Perfected Mantle of Siroria"] = {
        roles = { "MagDD" },
        tier = "A",
        rating = 11,
        source = "Summerset, Cloudrest",
        notes = "Trial set",
    },

    -- BROKEN ARCH IN REAPER'S MARCH, WETHERS' CLEFT IN BANGKORAI, TROLLSLAYER'S GULLY IN THE RIFT SETS
    ["Hunding's Rage"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 86,
        source = "Broken Arch in Reaper's March, Wethers' Cleft in Bangkorai, Trollslayer's Gully in The Rift",
        notes = "Crafted set",
    },

    -- OLD TOWN CAVERN IN REAPER'S MARCH, SILASELI RUINS IN BANGKORAI, ELDBJORG'S HIDEAWAY IN THE RIFT SETS
    ["Night Mother's Gaze"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 69,
        source = "Old Town Cavern in Reaper's March, Silaseli Ruins in Bangkorai, Eldbjorg's Hideaway in The Rift",
        notes = "Crafted set",
    },

    -- NECROM, SANITY'S EDGE SETS
    ["Ansuul's Torment"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 64,
        source = "Necrom, Sanity's Edge",
        notes = "Top trial DPS set",
    },
    ["Transformative Hope"] = {
        roles = { "Healer" },
        tier = "S",
        rating = 27,
        source = "Necrom, Sanity's Edge",
        notes = "Trial set",
    },
    ["Perfected Transformative Hope"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "Necrom, Sanity's Edge",
        notes = "Trial set",
    },
    ["Perfected Ansuul's Torment"] = {
        roles = { "StamDD" },
        tier = "B",
        rating = 7,
        source = "Necrom, Sanity's Edge",
        notes = "Trial set",
    },

    -- OVERRIDE SETS
    ["Olorime"] = {
        roles = { "Healer" },
        tier = "S",
        rating = 50,
        source = "Override",
        notes = "Major Courage ground AoE",
    },

    -- TEL VAR MERCHANT SETS
    ["Powerful Assault"] = {
        roles = { "Healer", "Tank" },
        tier = "S",
        rating = 49,
        source = "Tel Var Merchant",
        notes = "Dungeon set",
    },

    -- EASTMARCH, FROSTVAULT SETS
    ["Tzogvin's Warband"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 44,
        source = "Eastmarch, Frostvault",
        notes = "Dungeon set",
    },

    -- WROTHGAR SETS
    ["Briarheart"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 43,
        source = "Wrothgar",
        notes = "Overland set",
    },

    -- RIVENSPIRE, CRYPT OF HEARTS SETS
    ["Leviathan"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 43,
        source = "Rivenspire, Crypt of Hearts",
        notes = "Dungeon set",
    },
    ["Ebon Armory"] = {
        roles = { "Healer", "Tank" },
        tier = "S",
        rating = 23,
        source = "Rivenspire, Crypt of Hearts",
        notes = "Dungeon set",
    },

    -- SOUTHERN ELSWEYR, FUR-FORGE COVE SETS
    ["New Moon Acolyte"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 37,
        source = "Southern Elsweyr, Fur-Forge Cove",
        notes = "Crafted set",
    },

    -- WROTHGAR, BOREAL FORGE SETS
    ["Law of Julianos"] = {
        roles = { "MagDD" },
        tier = "S",
        rating = 36,
        source = "Wrothgar, Boreal Forge",
        notes = "Crafted set",
    },

    -- DESHAAN SETS
    ["Mother's Sorrow"] = {
        roles = { "MagDD" },
        tier = "S",
        rating = 36,
        source = "Deshaan",
        notes = "Overland set",
    },
    ["Plague Doctor"] = {
        roles = { "Tank" },
        tier = "A",
        rating = 11,
        source = "Deshaan",
        notes = "Overland set",
    },

    -- FISHERMAN'S ISLE IN GRAHTWOOD, HAMMERDEATH WORKSHOP IN STORMHAVEN, LAKE HLAALU RETREAT IN DESHAAN SETS
    ["Torug's Pact"] = {
        roles = { "Healer", "Tank" },
        tier = "S",
        rating = 31,
        source = "Fisherman's Isle in Grahtwood, Hammerdeath Workshop in Stormhaven, Lake Hlaalu Retreat in Deshaan",
        notes = "Crafted set",
    },

    -- THE EARTH FORGE SETS
    ["Kagrenac's Hope"] = {
        roles = { "Healer" },
        tier = "S",
        rating = 29,
        source = "The Earth Forge",
        notes = "Crafted set",
    },

    -- LUCENT CITADEL SETS
    ["Lucent Echoes"] = {
        roles = { "Tank" },
        tier = "S",
        rating = 27,
        source = "Lucent Citadel",
        notes = "Trial set",
    },
    ["Perfected Lucent Echoes"] = {
        roles = { "Tank" },
        tier = "A",
        rating = 11,
        source = "Lucent Citadel",
        notes = "Trial set",
    },
    ["Perfected Xoryn's Masterpiece"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "Lucent Citadel",
        notes = "Trial set",
    },
    ["Xoryn's Masterpiece"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "Lucent Citadel",
        notes = "Trial set",
    },

    -- MAELSTROM ARENA SETS
    ["Perfected Merciless Charge"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 27,
        source = "Maelstrom Arena",
        notes = "Arena set",
    },
    ["Merciless Charge"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 21,
        source = "Maelstrom Arena",
        notes = "Arena set",
    },
    ["Perfected Crushing Wall"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 21,
        source = "Maelstrom Arena",
        notes = "Back bar Destro staff, must have",
    },
    ["Elemental Succession"] = {
        roles = { "MagDD" },
        tier = "A",
        rating = 11,
        source = "Maelstrom Arena",
        notes = "Arena set",
    },
    ["Crushing Wall"] = {
        roles = { "MagDD" },
        tier = "B",
        rating = 6,
        source = "Maelstrom Arena",
        notes = "Arena set",
    },

    -- BANGKORAI, UNHALLOWED GRAVE SETS
    ["Aegis Caller"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 26,
        source = "Bangkorai, Unhallowed Grave",
        notes = "Dungeon set",
    },

    -- CRAGLORN, HEL RA CITADEL SETS
    ["Berserking Warrior"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 26,
        source = "Craglorn, Hel Ra Citadel",
        notes = "Dungeon set",
    },

    -- GOLD COAST, BLACK DRAKE VILLA SETS
    ["Kinras's Wrath"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 26,
        source = "Gold Coast, Black Drake Villa",
        notes = "Dungeon set",
    },
    ["Drake's Rush"] = {
        roles = { "Tank" },
        tier = "A",
        rating = 16,
        source = "Gold Coast, Black Drake Villa",
        notes = "Dungeon set",
    },

    -- ELSWEYR, SUNSPIRE SETS
    ["Perfected Tooth of Lokkestiiz"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 26,
        source = "Elsweyr, Sunspire",
        notes = "Trial set",
    },
    ["Tooth of Lokkestiiz"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 26,
        source = "Elsweyr, Sunspire",
        notes = "Trial set",
    },
    ["False God's Devotion"] = {
        roles = { "MagDD" },
        tier = "S",
        rating = 23,
        source = "Elsweyr, Sunspire",
        notes = "Trial set",
    },
    ["Claw of Yolnahkriin"] = {
        roles = { "Tank" },
        tier = "S",
        rating = 11,
        source = "Elsweyr, Sunspire",
        notes = "Minor Courage uptime for group",
    },
    ["Perfected Claw of Yolnahkriin"] = {
        roles = { "Tank" },
        tier = "A",
        rating = 11,
        source = "Elsweyr, Sunspire",
        notes = "Trial set",
    },

    -- BANGKORAI SETS
    ["Spriggan's Thorns"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 26,
        source = "Bangkorai",
        notes = "Overland set",
    },

    -- PARSED FROM BUILDS SETS
    ["Strength of Automaton"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 26,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Vestments of Olorime"] = {
        roles = { "Healer" },
        tier = "S",
        rating = 23,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Patron's Gold, Void Pitch"] = {
        roles = { "Healer", "StamDD", "Tank" },
        tier = "A",
        rating = 13,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Perfected Siroria"] = {
        roles = { "MagDD" },
        tier = "A",
        rating = 11,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Torc of Tonal Constanty"] = {
        roles = { "Tank" },
        tier = "A",
        rating = 11,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Barbaric Windblown Hair"] = {
        roles = { "MagDD" },
        tier = "A",
        rating = 9,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Hidden"] = {
        roles = { "MagDD", "StamDD" },
        tier = "A",
        rating = 9,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Void Pitch, Divine Gold"] = {
        roles = { "MagDD", "Tank" },
        tier = "A",
        rating = 9,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Claws of Yolnahkriin"] = {
        roles = { "Tank" },
        tier = "B",
        rating = 7,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Perf. Null Arca"] = {
        roles = { "MagDD" },
        tier = "B",
        rating = 7,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Perfected Null Arca"] = {
        roles = { "StamDD" },
        tier = "B",
        rating = 7,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Ancient Dragon Body Marks"] = {
        roles = { "MagDD" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Ancient Dragon Face Marks"] = {
        roles = { "MagDD" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Blackreach Blue,Marble White"] = {
        roles = { "Healer" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Blood-Forged"] = {
        roles = { "Healer" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Court of Bedlam"] = {
        roles = { "MagDD" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Dark Passions Regalia"] = {
        roles = { "MagDD" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Dragonbone Staff"] = {
        roles = { "MagDD" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Dremora Kynreeve Pauldrons"] = {
        roles = { "StamDD" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Dro-m'Athra"] = {
        roles = { "StamDD" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Frozen Blood,Void Pitch"] = {
        roles = { "Tank" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Jester"] = {
        roles = { "MagDD" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Monster Set of your choice"] = {
        roles = { "MagDD" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Patron's Gold, Marshnettle Titian"] = {
        roles = { "MagDD" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Patron's Gold,Bloodroot Wine,Void Pitch"] = {
        roles = { "Healer" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Patron's Gold,Warrior's Steel"] = {
        roles = { "Tank" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Reanimated Vampiric Thrall"] = {
        roles = { "MagDD" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Scrying Eye Psijic Face Tattoo"] = {
        roles = { "Healer" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Spiderkith"] = {
        roles = { "StamDD" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Viridian Venom,Brightfern Green"] = {
        roles = { "Healer" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Void Pathosis"] = {
        roles = { "Healer" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Void Pitch, Bloodroot Wine"] = {
        roles = { "StamDD" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Void Pitch, Cardsharp Crimson"] = {
        roles = { "StamDD" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Void Pitch, Colossus Brass"] = {
        roles = { "StamDD" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Void Pitch, Contraband Violet"] = {
        roles = { "MagDD" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["White-Gold Eyeshadow"] = {
        roles = { "MagDD" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Worm Wizard"] = {
        roles = { "MagDD" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },
    ["Z'Maja's Shadow"] = {
        roles = { "StamDD" },
        tier = "B",
        rating = 4,
        source = "Parsed from builds",
        notes = "Unknown set",
    },

    -- CRAGLORN, SANCTUM OPHIDIA SETS
    ["Twice-Fanged Serpent"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 26,
        source = "Craglorn, Sanctum Ophidia",
        notes = "Dungeon set",
    },

    -- CRAGLORN TRIALS SETS
    ["Vicious Serpent"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 26,
        source = "Craglorn Trials",
        notes = "Trial set",
    },
    ["Eternal Warrior"] = {
        roles = { "Tank" },
        tier = "A",
        rating = 11,
        source = "Craglorn Trials",
        notes = "Trial set",
    },

    -- VVARDENFELL, HALLS OF FABRICATION SETS
    ["War Machine"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 26,
        source = "Vvardenfell, Halls of Fabrication",
        notes = "Dungeon set",
    },
    ["Master Architect"] = {
        roles = { "MagDD" },
        tier = "A",
        rating = 11,
        source = "Vvardenfell, Halls of Fabrication",
        notes = "Dungeon set",
    },

    -- RIVENSPIRE, SHIPWRIGHT'S REGRET SETS
    ["Turning Tide"] = {
        roles = { "Tank" },
        tier = "S",
        rating = 24,
        source = "Rivenspire, Shipwright's Regret",
        notes = "Group DPS support, off-balance",
    },
    ["Storm-Cursed's Revenge"] = {
        roles = { "MagDD" },
        tier = "B",
        rating = 7,
        source = "Rivenspire, Shipwright's Regret",
        notes = "Dungeon set",
    },

    -- CLOCKWORK CITY, RESTRICTED BRASSWORKS SETS
    ["Fortified Brass"] = {
        roles = { "Tank" },
        tier = "S",
        rating = 23,
        source = "Clockwork City, Restricted Brassworks",
        notes = "Crafted set",
    },

    -- REAPER'S MARCH, SELENE'S WEB SETS
    ["Hircine's Veneer"] = {
        roles = { "Healer", "Tank" },
        tier = "S",
        rating = 23,
        source = "Reaper's March, Selene's Web",
        notes = "Dungeon set",
    },

    -- ARANANGA IN GREENSHADE, VEAWEND EDE IN RIVENSPIRE, XAL HAJ-EI SHRINE IN SHADOWFEN SETS
    ["Magnus' Gift"] = {
        roles = { "MagDD" },
        tier = "S",
        rating = 23,
        source = "Arananga in Greenshade, Veawend Ede in Rivenspire, Xal Haj-Ei Shrine in Shadowfen",
        notes = "Crafted set",
    },

    -- COLDHARBOUR, VAULTS OF MADNESS SETS
    ["The Worm's Raiment"] = {
        roles = { "Healer", "Tank" },
        tier = "S",
        rating = 23,
        source = "Coldharbour, Vaults of Madness",
        notes = "Dungeon set",
    },

    -- GRAHTWOOD, LAIR OF MAARSELOK SETS
    ["Azureblight Reaper"] = {
        roles = { "MagDD" },
        tier = "S",
        rating = 21,
        source = "Grahtwood, Lair of Maarselok",
        notes = "Dungeon set",
    },
    ["Z'en's Redress"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "Grahtwood, Lair of Maarselok",
        notes = "Dungeon set",
    },

    -- HIGH ISLE, DREADSAIL REEF SETS
    ["Perfected Whorl of the Depths"] = {
        roles = { "MagDD" },
        tier = "S",
        rating = 21,
        source = "High Isle, Dreadsail Reef",
        notes = "Trial set",
    },
    ["Pillager's Profit"] = {
        roles = { "Healer" },
        tier = "S",
        rating = 11,
        source = "High Isle, Dreadsail Reef",
        notes = "Group burst heal on revive",
    },
    ["Coral Riptide"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 0,
        source = "High Isle, Dreadsail Reef",
        notes = "Resource-drain DPS, high ceiling",
    },
    ["Whorl of the Depths"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 0,
        source = "High Isle, Dreadsail Reef",
        notes = "Trial DPS set, AoE proc",
    },
    ["Perfected Pillager's Profit"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "High Isle, Dreadsail Reef",
        notes = "Trial set",
    },
    ["Perfected Pearlescent Ward"] = {
        roles = { "Tank" },
        tier = "B",
        rating = 7,
        source = "High Isle, Dreadsail Reef",
        notes = "Trial set",
    },

    -- BLACKWOOD, ROCKGROVE SETS
    ["Saxhleel Champion"] = {
        roles = { "Healer", "Tank" },
        tier = "S",
        rating = 19,
        source = "Blackwood, Rockgrove",
        notes = "Ultimate generation for group",
    },
    ["Bahsei's Mania"] = {
        roles = { "MagDD", "StamDD" },
        tier = "S",
        rating = 0,
        source = "Blackwood, Rockgrove",
        notes = "Low-resource damage amp",
    },
    ["Perfected Saxhleel Champion"] = {
        roles = { "Tank" },
        tier = "A",
        rating = 11,
        source = "Blackwood, Rockgrove",
        notes = "Trial set",
    },
    ["Perfected Stone-Talker's Oath"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "Blackwood, Rockgrove",
        notes = "Trial set",
    },
    ["Stone-Talker's Oath"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "Blackwood, Rockgrove",
        notes = "Trial set",
    },

    -- DRAGONSTAR ARENA SETS
    ["Perfected Grand Rejuvenation"] = {
        roles = { "Healer" },
        tier = "S",
        rating = 17,
        source = "Dragonstar Arena",
        notes = "Arena set",
    },
    ["Perfected Titanic Cleave"] = {
        roles = { "StamDD" },
        tier = "A",
        rating = 13,
        source = "Dragonstar Arena",
        notes = "Arena set",
    },
    ["Grand Rejuvenation"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "Dragonstar Arena",
        notes = "Arena set",
    },

    -- MALABAL TOR SETS
    ["Spinner's Garments"] = {
        roles = { "MagDD" },
        tier = "S",
        rating = 17,
        source = "Malabal Tor",
        notes = "Overland set",
    },

    -- GREYMOOR, KYNE'S AEGIS SETS
    ["Roaring Opportunist"] = {
        roles = { "Healer" },
        tier = "S",
        rating = 11,
        source = "Greymoor, Kyne's Aegis",
        notes = "Minor Slayer for group",
    },
    ["Perfected Roaring Opportunist"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "Greymoor, Kyne's Aegis",
        notes = "Trial set",
    },

    -- REWARDS FOR THE WORTHY SETS
    ["Battalion Defender"] = {
        roles = { "Tank" },
        tier = "A",
        rating = 16,
        source = "Rewards for the Worthy",
        notes = "Dungeon set",
    },
    ["Spell Strategist"] = {
        roles = { "MagDD" },
        tier = "A",
        rating = 11,
        source = "Rewards for the Worthy",
        notes = "Dungeon set",
    },

    -- BLACKWOOD, THE DREAD CELLAR SETS
    ["Crimson Oath's Rive"] = {
        roles = { "Tank" },
        tier = "A",
        rating = 16,
        source = "Blackwood, The Dread Cellar",
        notes = "Dungeon set",
    },
    ["Scorion's Feast"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "Blackwood, The Dread Cellar",
        notes = "Dungeon set",
    },

    -- HIGHTIDE KEEP IN AURIDON, MESANTHANO'S TOWER IN GLENUMBRA, STEAMFONT CAVERN IN STONEFALLS SETS
    ["Night's Silence"] = {
        roles = { "Tank" },
        tier = "A",
        rating = 13,
        source = "Hightide Keep in Auridon, Mesanthano's Tower in Glenumbra, Steamfont Cavern in Stonefalls",
        notes = "Crafted set",
    },

    -- EASTMARCH SETS
    ["Akaviri Dragonguard"] = {
        roles = { "Tank" },
        tier = "A",
        rating = 11,
        source = "Eastmarch",
        notes = "Overland set",
    },

    -- GREENSHADE SETS
    ["Beekeeper's Gear"] = {
        roles = { "Tank" },
        tier = "A",
        rating = 11,
        source = "Greenshade",
        notes = "Overland set",
    },

    -- GREENSHADE, CITY OF ASH SETS
    ["Burning Spellweave"] = {
        roles = { "MagDD" },
        tier = "A",
        rating = 11,
        source = "Greenshade, City of Ash",
        notes = "Dungeon set",
    },

    -- BLACKWOOD, PENTRIC RUN SETS
    ["Diamond's Victory"] = {
        roles = { "MagDD" },
        tier = "A",
        rating = 11,
        source = "Blackwood, Pentric Run",
        notes = "Crafted set",
    },

    -- DESHAAN, THE CAULDRON SETS
    ["Foolkiller's Ward"] = {
        roles = { "Tank" },
        tier = "A",
        rating = 11,
        source = "Deshaan, The Cauldron",
        notes = "Dungeon set",
    },

    -- VATESHRAN HOLLOWS  SETS
    ["Force Overflow"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "Vateshran Hollows ",
        notes = "Arena set",
    },

    -- CRAGLORN, AETHERIAN ARCHIVE SETS
    ["Healing Mage"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "Craglorn, Aetherian Archive",
        notes = "Dungeon set",
    },

    -- WROTHGAR, ICEREACH SETS
    ["Hiti's Hearth"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "Wrothgar, Icereach",
        notes = "Dungeon set",
    },

    -- NORTHERN ELSWEYR, MOONGRAVE FANE SETS
    ["Hollowfang Thirst"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "Northern Elsweyr, Moongrave Fane",
        notes = "Dungeon set",
    },

    -- STORMHAVEN, SCALECALLER PEAK SETS
    ["Jorvuld's Guidance"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "Stormhaven, Scalecaller Peak",
        notes = "Dungeon set",
    },

    -- REAPER'S MARCH, MAW OF LORKHAJ SETS
    ["Lunar Bastion"] = {
        roles = { "Tank" },
        tier = "A",
        rating = 11,
        source = "Reaper's March, Maw of Lorkhaj",
        notes = "Dungeon set",
    },
    ["Roar of Alkosh"] = {
        roles = { "Tank" },
        tier = "A",
        rating = 11,
        source = "Reaper's March, Maw of Lorkhaj",
        notes = "Dungeon set",
    },

    -- CLOCKWORK CITY, PAVILION OF ARTIFICE SETS
    ["Mechanical Acuity"] = {
        roles = { "MagDD" },
        tier = "A",
        rating = 11,
        source = "Clockwork City, Pavilion of Artifice",
        notes = "Crafted set",
    },

    -- SHADOWFEN, ARX CORINIUM SETS
    ["Medusa"] = {
        roles = { "MagDD" },
        tier = "A",
        rating = 11,
        source = "Shadowfen, Arx Corinium",
        notes = "Dungeon set",
    },

    -- CLOCKWORK CITY, ASYLUM SANCTORIUM SETS
    ["Perfected Timeless Blessing"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "Clockwork City, Asylum Sanctorium",
        notes = "Unknown set",
    },
    ["Timeless Blessing"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "Clockwork City, Asylum Sanctorium",
        notes = "Unknown set",
    },
    ["Defensive Position"] = {
        roles = { "Tank" },
        tier = "B",
        rating = 6,
        source = "Clockwork City, Asylum Sanctorium",
        notes = "Dungeon set",
    },

    -- AURIDON, THE BANISHED CELLS SETS
    ["Sanctuary"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "Auridon, The Banished Cells",
        notes = "Dungeon set",
    },

    -- CRAGLORN SETS
    ["Way of Martial Knowledge"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "Craglorn",
        notes = "Overland set",
    },

    -- WESTERN SKYRIM SETS
    ["Winter's Respite"] = {
        roles = { "Healer" },
        tier = "A",
        rating = 11,
        source = "Western Skyrim",
        notes = "Overland set",
    },

    -- RIVENSPIRE SETS
    ["Necropotence"] = {
        roles = { "MagDD" },
        tier = "A",
        rating = 10,
        source = "Rivenspire",
        notes = "Overland set",
    },

    -- HIGH ISLE, HIDDEN FOUNDRY SETS
    ["Druid's Braid"] = {
        roles = { "Tank" },
        tier = "B",
        rating = 7,
        source = "High Isle, Hidden Foundry",
        notes = "Crafted set",
    },

    -- SHADOWFEN, RUINS OF MAZZATUN SETS
    ["Amber Plasm"] = {
        roles = { "MagDD" },
        tier = "B",
        rating = 4,
        source = "Shadowfen, Ruins of Mazzatun",
        notes = "Dungeon set",
    },

}

----------------------------------------------------------------------
-- Stat caps reference
----------------------------------------------------------------------
SmartGear.StatCaps = {
    physicalPenetration = 18200,
    spellPenetration    = 18200,
    criticalChance      = 125,
    criticalDamage      = 125,
    weaponDamage        = 0,
    spellDamage         = 0,
}
