ItemShareSavedVars =
{
    ["Default"] = 
    {
        ["@CraftMaster99"] = 
        {
            ["$AccountWide"] = 
            {
                ["sharedItems"] = 
                {
                    ["|H0:item:189768:359:50:0:0:0:0:0:0:0:0:0:0:0:0:25:0:0:0:250:0|h|h||inventory:alchemist rena"] = 
                    {
                        ["itemLink"] = "|H0:item:189768:359:50:0:0:0:0:0:0:0:0:0:0:0:0:25:0:0:0:250:0|h|h",
                        ["locationKey"] = "inventory:alchemist rena",
                        ["lastDumpedAt"] = 1776422670,
                        ["count"] = 1,
                        ["sharedFrom"] = "Inventory (Alchemist Rena)",
                        ["bagId"] = 1,
                        ["itemTypeName"] = "Weapon",
                        ["quality"] = 2,
                        ["traitType"] = 7,
                        ["accountName"] = "@CraftMaster99",
                        ["furnitureDataId"] = 0,
                        ["firstDumpedAt"] = 1776422670,
                        ["itemKey"] = "|H0:item:189768:359:50:0:0:0:0:0:0:0:0:0:0:0:0:25:0:0:0:250:0|h|h||inventory:alchemist rena",
                        ["trait"] = "Sharpened",
                        ["slotIndex"] = 3,
                        ["itemType"] = 1,
                        ["itemName"] = "Bow of Nocturnal's Ploy",
                        ["qualityName"] = "Fine",
                    },
                    ["|H0:item:88872:363:50:0:0:0:0:0:0:0:0:0:0:0:0:25:0:0:0:10000:0|h|h||inventory:alchemist rena"] = 
                    {
                        ["itemLink"] = "|H0:item:88872:363:50:0:0:0:0:0:0:0:0:0:0:0:0:25:0:0:0:10000:0|h|h",
                        ["locationKey"] = "inventory:alchemist rena",
                        ["lastDumpedAt"] = 1776422693,
                        ["count"] = 1,
                        ["sharedFrom"] = "Inventory (Alchemist Rena)",
                        ["bagId"] = 1,
                        ["itemTypeName"] = "Apparel",
                        ["quality"] = 4,
                        ["traitType"] = 15,
                        ["accountName"] = "@CraftMaster99",
                        ["furnitureDataId"] = 0,
                        ["firstDumpedAt"] = 1776422693,
                        ["itemKey"] = "|H0:item:88872:363:50:0:0:0:0:0:0:0:0:0:0:0:0:25:0:0:0:10000:0|h|h||inventory:alchemist rena",
                        ["trait"] = "Training",
                        ["slotIndex"] = 6,
                        ["itemType"] = 2,
                        ["itemName"] = "Greaves of Beckoning Steel",
                        ["qualityName"] = "Epic",
                    },
                    ["|H0:item:223160:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||inventory:alchemist rena"] = 
                    {
                        ["itemLink"] = "|H0:item:223160:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                        ["locationKey"] = "inventory:alchemist rena",
                        ["lastDumpedAt"] = 1776422749,
                        ["count"] = 1,
                        ["sharedFrom"] = "Inventory (Alchemist Rena)",
                        ["bagId"] = 1,
                        ["itemTypeName"] = "Furnishing",
                        ["quality"] = 3,
                        ["traitType"] = 0,
                        ["accountName"] = "@CraftMaster99",
                        ["furnitureDataId"] = 11183,
                        ["firstDumpedAt"] = 1776422749,
                        ["itemKey"] = "|H0:item:223160:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||inventory:alchemist rena",
                        ["trait"] = "",
                        ["slotIndex"] = 9,
                        ["itemType"] = 61,
                        ["itemName"] = "Worm Cult Carving, Eye",
                        ["qualityName"] = "Superior",
                    },
                    ["|H0:item:219816:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||bank"] = 
                    {
                        ["itemLink"] = "|H0:item:219816:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                        ["locationKey"] = "bank",
                        ["lastDumpedAt"] = 1776422845,
                        ["count"] = 2,
                        ["sharedFrom"] = "Bank",
                        ["bagId"] = 2,
                        ["itemTypeName"] = "Collectible",
                        ["quality"] = 5,
                        ["traitType"] = 0,
                        ["accountName"] = "@CraftMaster99",
                        ["furnitureDataId"] = 0,
                        ["firstDumpedAt"] = 1776422845,
                        ["itemKey"] = "|H0:item:219816:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||bank",
                        ["trait"] = "",
                        ["slotIndex"] = 103,
                        ["itemType"] = 34,
                        ["itemName"] = "Style Page: Dapper Daredevil Breeches",
                        ["qualityName"] = "Legendary",
                    },
                    ["|H0:item:203248:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||bank"] = 
                    {
                        ["itemLink"] = "|H0:item:203248:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                        ["locationKey"] = "bank",
                        ["lastDumpedAt"] = 1776422834,
                        ["count"] = 1,
                        ["sharedFrom"] = "Bank",
                        ["bagId"] = 2,
                        ["itemTypeName"] = "Collectible",
                        ["quality"] = 5,
                        ["traitType"] = 0,
                        ["accountName"] = "@CraftMaster99",
                        ["furnitureDataId"] = 0,
                        ["firstDumpedAt"] = 1776422834,
                        ["itemKey"] = "|H0:item:203248:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||bank",
                        ["trait"] = "",
                        ["slotIndex"] = 104,
                        ["itemType"] = 34,
                        ["itemName"] = "Style Page: Jester's Seeker Suit Breeches",
                        ["qualityName"] = "Legendary",
                    },
                    ["|H0:item:223157:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||inventory:alchemist rena"] = 
                    {
                        ["itemLink"] = "|H0:item:223157:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                        ["locationKey"] = "inventory:alchemist rena",
                        ["lastDumpedAt"] = 1776422797,
                        ["count"] = 2,
                        ["sharedFrom"] = "Inventory (Alchemist Rena)",
                        ["bagId"] = 1,
                        ["itemTypeName"] = "Furnishing",
                        ["quality"] = 3,
                        ["traitType"] = 0,
                        ["accountName"] = "@CraftMaster99",
                        ["furnitureDataId"] = 11180,
                        ["firstDumpedAt"] = 1776422797,
                        ["itemKey"] = "|H0:item:223157:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||inventory:alchemist rena",
                        ["trait"] = "",
                        ["slotIndex"] = 18,
                        ["itemType"] = 61,
                        ["itemName"] = "Worm Cult Bucket, Bismuth Samples",
                        ["qualityName"] = "Superior",
                    },
                    ["|H0:item:210996:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||bank"] = 
                    {
                        ["itemLink"] = "|H0:item:210996:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                        ["locationKey"] = "bank",
                        ["lastDumpedAt"] = 1776422846,
                        ["count"] = 1,
                        ["sharedFrom"] = "Bank",
                        ["bagId"] = 2,
                        ["itemTypeName"] = "Collectible",
                        ["quality"] = 5,
                        ["traitType"] = 0,
                        ["accountName"] = "@CraftMaster99",
                        ["furnitureDataId"] = 0,
                        ["firstDumpedAt"] = 1776422846,
                        ["itemKey"] = "|H0:item:210996:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||bank",
                        ["trait"] = "",
                        ["slotIndex"] = 106,
                        ["itemType"] = 34,
                        ["itemName"] = "Style Page: Worm Cult Hunter Bracers",
                        ["qualityName"] = "Legendary",
                    },
                    ["|H0:item:183862:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||bank"] = 
                    {
                        ["itemLink"] = "|H0:item:183862:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                        ["locationKey"] = "bank",
                        ["lastDumpedAt"] = 1776422871,
                        ["count"] = 1,
                        ["sharedFrom"] = "Bank",
                        ["bagId"] = 2,
                        ["itemTypeName"] = "Collectible",
                        ["quality"] = 5,
                        ["traitType"] = 0,
                        ["accountName"] = "@CraftMaster99",
                        ["furnitureDataId"] = 0,
                        ["firstDumpedAt"] = 1776422871,
                        ["itemKey"] = "|H0:item:183862:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||bank",
                        ["trait"] = "",
                        ["slotIndex"] = 107,
                        ["itemType"] = 34,
                        ["itemName"] = "Style Page: Second Seed Gloves",
                        ["qualityName"] = "Legendary",
                    },
                }
            }
        }
    }
}
