CerconeGrimoireData = {
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Asesinato",
        Orden="1",
        Descripcion="Empalamiento: Acuchillas al enemigo con una hoja cáustica de precisión letal que inflige daño y causa sangrado.",
        Valores="Acción, Ataque 1d6+2, 3mag y causa sangrado por 2 turnos adicionales, infligiendo 2 pts de daño por turno",
    },
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Asesinato",
        Orden="2",
        Descripcion="Ataque sorpresa: Te ubicas en un flanco o en la retaguardia del enemigo, para atacarlo y causarle gran daño físico.",
        Valores="Acción, Ataque 1d8+4, 3mag",
    },
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Asesinato",
        Orden="3",
        Descripcion="Abanico de loto: Irrumpes a través de las sombras y emboscas a un enemigo mientras despliegas un abanico de cuchillos que les inflige daño mágico a él y a los enemigos situados a tu alrededor.",
        Valores="Acción, Ataque en área 1d4+1, 4mag",
    },
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Sombra",
        Orden="1",
        Descripcion="Capa oscura: Te envuelves en una sombra protectora que dificulta la visión de tu oponente aumentando tu defensa o la de la persona que vayas a proteger.",
        Valores="Reacción, +2 Def por 1 turno, 2 mag",
    },
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Sombra",
        Orden="2",
        Descripcion="Oscuridad devoradora: Conjuras un círculo de sombras que reduce el daño recibido, este círculo te rodea hasta ser consumido.",
        Valores="Acción adicional, -4 de daño hasta que se consuma, 3mag",
    },
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Sombra",
        Orden="3",
        Descripcion="Invocar sombra: Invoca una sombra que comparte la vida y la defensa del Hoja de la Noche y obliga a los enemigos a atacarla.",
        Valores="Acción, Taunt por 1 turno a 1d3 enemigos, +1 def por 1 turno, 2 mag",
    },
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Sifón",
        Orden="1",
        Descripcion="Ofrenda de vida: Vierte tu sangre y canaliza lo arcano para curar tu salud o la de un aliado que esté cerca tuyo.",
        Valores="Acción, Sanación 1 objetivo 1d4+2, 3 mag, -1HP",
    },
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Sifón",
        Orden="2",
        Descripcion="Canalización de salud: Vierte tu sangre y la canaliza en tus aliados para curar a un máximo de personas cerca tuyo.",
        Valores="Acción, Sanación 4 objetivos 1d3+1, 6 mag, -1HP",
    },
    {
        Z="1",
        Nombre="Hoja de la Noche",
        NombreRama="Sifón",
        Orden="3",
        Descripcion="Golpes drenadores: Canalizas una porción de tu magicka sobre ti mismo o sobre un objetivo para que absorban la salud de tu enemigo al infligir daño.",
        Valores="Acción Adicional, +2 HP en el siguiente ataque exitoso que realice el objetivo, 2 mag",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Señor sepulcral",
        Orden="1",
        Descripcion="Arquero esquelético: Reanima un arquero esquelético del suelo que lucha a tu lado lanzando flechas venenosas, tras finalizar el combate el arquero se desintegrará. Requiere de un cadaver o totem de hueso.",
        Valores="Acción, Ataque 1d6+2, 3mag y causa envenenamiento por 2 turnos adicionales, infligiendo 2 pts de daño por turno",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Señor sepulcral",
        Orden="2",
        Descripcion="Mago esquelético: Reanima un mago esquelético del suelo que lucha a tu lado lanzando ataques de gran magnitud, tras finalizar el combate el arquero se desintegrará. Requiere de un cadaver o totem de hueso.",
        Valores="Acción, Ataque 1d8+4, 3mag",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Señor sepulcral",
        Orden="3",
        Descripcion="Esqueleto explosivo pestífero: Ordena a tu esqueleto correr hacia el objetivo y explotar cuando se acerque; infligiendo daño a todos los enemigos cercanos. Requiere de un cadaver o totem de hueso.",
        Valores="Acción, Ataque en área 1d4+1, 4mag",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Tirano de los huesos",
        Orden="1",
        Descripcion="Armadura de hueso: Te envuelve en unos duros huesos que te otorgan una armadura que mejora tu defensa. Requiere de un cadáver o tótem de hueso.",
        Valores="Reacción, +2 Def por 1 turno, 2 mag",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Tirano de los huesos",
        Orden="2",
        Descripcion="Agarre Sepulcral: Invoca tres zonas de garras esqueléticas frente a ti en el suelo que atrapan a los enemigos situados al frente tuyo, reduciendo su defensa durante un turno.",
        Valores="Acción, -2 Def a un enemigo por 1 turno, 3 mag",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Tirano de los huesos",
        Orden="3",
        Descripcion="Tótem hueso: Invoca una efigie de hueso a tus pies durante el combate que os otorga a ti y a tus aliados una fuente de cadáveres.",
        Valores="Acción adicional, un uso al dia, 0 Mag",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Muerte encarnada",
        Orden="1",
        Descripcion="Sanación de carne: Sacrificas tu propio poder para reparar la carne dañada y te curas a ti o a un aliado situado delante de tuyo.",
        Valores="Acción, Sanación 1d4+2 HP, Coste 3Mag",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Muerte encarnada",
        Orden="2",
        Descripcion="Vida entre la Muerte: Libera los fragmentos residuales de las almas caídas en la ubicación especificada y hace que tú y tus aliados recuperéis de salud.",
        Valores="Acción, Sanación 1d3+1 HP a 4 Objetivos, 6 Mag",
    },
    {
        Z="2",
        Nombre="Nigromante",
        NombreRama="Muerte encarnada",
        Orden="3",
        Descripcion="Resurrección: Devuelve a tus aliados al borde de la muerte y resucita hasta a 1d3 aliados en la ubicación de objetivo.",
        Valores="Acción, Revive a 1d3 aliados, 2mag",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Emisario del Tomo",
        Orden="1",
        Descripcion="Impacto Abisal: Te imbuye magia abisal en el brazo para formar tentáculos que arremeten contra tus enemigos, lo que inflige daño y sangrado por un tiempo.",
        Valores="Acción, Ataque 1d6+2, 3mag y causa sangrado por 2 turnos adicionales, infligiendo 2 pts de daño por turno",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Emisario del Tomo",
        Orden="2",
        Descripcion="Forjador del Destino: Canaliza tu conocimiento puro a través de tu libro en un haz de energía que deja cicatrices en el mundo que tienes ante ti.",
        Valores="Acción, Ataque 1d8+4, 3mag",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Emisario del Tomo",
        Orden="3",
        Descripcion="Ojo Impasible: Rasga el tejido del Aurbis para invocar un vástago de Hermaeus Mora. Este ser crea un haz que desgarra la realidad y proyecta un haz de luz que daña todo lo que se encuentre a su alcance.",
        Valores="Acción, Ataque en área 1d4+1, 4mag",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Soldado de Apocrypha",
        Orden="1",
        Descripcion="Defensa Runica: Lanza una runa protectora simple que permite ser activada en menos de un segundo conjurando un portal a apocrypha que envia parte del daño dirigido a ti o a otra persona.",
        Valores="Reacción, +2 Def por 1 turno, 2 mag",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Soldado de Apocrypha",
        Orden="2",
        Descripcion="Convulcion Runica: Crea una runa de Apocrypha en la mente de un grupo de enemigos nublando su mente y todo pensamiento, remplazándolos con el único pensamiento de atacar a quien lanzo esta habilidad.",
        Valores="Acción, Taunt por 1 turno a 1d3 enemigos, +1 def por 1 turno, 2 mag",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Soldado de Apocrypha",
        Orden="3",
        Descripcion="Armadura tejida por el destino: Forja una armadura rúnica capaz de enviar gran parte del daño recibido directo a apocrypha lo que hace mas complicado que te lastimen.",
        Valores="Reacción, 3 defensa a si mismo, 3mag",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Formas rúnicas curativas",
        Orden="1",
        Descripcion="Curacion Runica: Crea una serie de runas de Apocrypha precisas y las lleva hasta ti o hasta un aliado que tengas delante. Las runas restauran el daño infligido.",
        Valores="Sanación 1 objetivo 1d4+2, 3 mag, -1HP",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Formas rúnicas curativas",
        Orden="2",
        Descripcion="Dominio del Arcanista: Hace aparecer tu tomo e invoca el vigoratum de Hermaeus Mora para conjurar un vórtice de poder sobrenatural. Estar en este vórtice cura a ti y tres aliados o a cuatro aliados una gran cantidad de vida.",
        Valores="Sanación 4 objetivos 1d3+1, 6 mag, -1HP",
    },
    {
        Z="3",
        Nombre="Arcanista",
        NombreRama="Formas rúnicas curativas",
        Orden="3",
        Descripcion="Escudos de Chakram: Talla las runas del Hombre Ciego para invocar discos místicos giratorios que te rodean a ti o hasta 3 miembros imbuyendo sus ataques con fuerza de apocrypha.",
        Valores="Acción, +1 al daño a 1d3 de aliados por un turno, 2 mag",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Fuego ardiente",
        Orden="1",
        Descripcion="Latigazo fulminante: El Caballero utilizando el fulgor dracónico de su interior conjura un látigo de llamas con el cual arremete contra su adversario.",
        Valores="Acción, Ataque 1d6+2, 3mag y causa quemadura por 2 turnos adicionales, infligiendo 2 pts de daño por turno",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Fuego ardiente",
        Orden="2",
        Descripcion="Aliento abrasador: El fuego en el interior del caballero sale liberado por su boca, lastimando no solo el cuerpo del enemigo sino también su espíritu.",
        Valores="Acción, Ataque 1d8+4, 3mag",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Fuego ardiente",
        Orden="3",
        Descripcion="Infierno: El poder interior del caballero dragón explota en una fulminante llamarada que lastima a todos sus adversarios.",
        Valores="Acción, Ataque en área 1d4+1, 4mag",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Poder draconiano",
        Orden="1",
        Descripcion="Escamas protectoras: La voluntad de defender a sus aliados, despierta poderosas escamas que cubren ya sea al portador o para proteger a un compañero.",
        Valores="Reacción, +2 Def por 1 turno, 2 mag",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Poder draconiano",
        Orden="2",
        Descripcion="Aliento profundo: Un fuerte rugido cubre el lugar, el aura de desafío sale desprendida del caballero dragón, retando a los adversarios quienes no pueden evitar seguir este llamado al combate.",
        Valores="Acción, Taunt por 1 turno a 1d3 enemigos, +1 def por 1 turno, 2 mag",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Poder draconiano",
        Orden="3",
        Descripcion="Gran salto de dragón: Llamando el fulgor dracónico de su interior el caballero salta contra su adversario, provocando un temblor en la ubicación que aturde por un turno al enemigo.",
        Valores="Acción, Stun por 1 turno, 1 objetivo, 3mag",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Corazón de tierra",
        Orden="1",
        Descripcion="Nube de cenizas: El Caballero Dragón genera una nube de cenizas que envuelven y se adhieren a un aliado  sanando sus heridas.",
        Valores="Acción, Sanación 1 objetivo 1d4+2, 3 mag",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Corazón de tierra",
        Orden="2",
        Descripcion="Fragmento de obsidiana: El caballero dragón desprende fragmentos de obsidiana de su cuerpo los cuales poseen runas de curación que se dirigen a sus aliados.",
        Valores="Acción, Sanación 4 objetivos 1d3+1, 6 mag",
    },
    {
        Z="4",
        Nombre="Caballero Dragón",
        NombreRama="Corazón de tierra",
        Orden="3",
        Descripcion="Armamento Fundido: Tras elegir un aliado, este recibe un aura de fuego en sus armas que le agregan daño de quemadura.",
        Valores="Acción Adicional, agrega quemadura al ataque por 2 turnos adicionales, infligiendo 2 pts de daño por turno.",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Llamada de la tormenta",
        Orden="1",
        Descripcion="Furia interminable: Conjuras un rayo concentrado desde lo alto que golpea con mucha fuerza a un objetivo, provocándole quemaduras eléctricas por un tiempo.",
        Valores="Acción, Ataque 1d6+2, 3mag y causa quemadura por 2 turnos adicionales, infligiendo 2 pts de daño por turno",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Llamada de la tormenta",
        Orden="2",
        Descripcion="Escape Relampago: Te conviertes en el relámpago mismo atravesando al enemigo completamente y apareciendo al otro lado causándole una gran cantidad de daño.",
        Valores="Acción, Ataque 1d8+4, 3mag",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Llamada de la tormenta",
        Orden="3",
        Descripcion="Torrente de Relampagos: Creas un nexo de magia tormentosa en donde el brujo decida dañando en un area considerable todo lo que se encuentre dentro.",
        Valores="Acción, Ataque en área 1d4+1, 4mag",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Magia Oscura",
        Orden="1",
        Descripcion="Tratado Oscuro: Usas tu magia para pactar con entidades menores de oblivion, recibiendo una mejora en tu armadura de manera inmediata a cambio de la magia que pactaste.",
        Valores="Reacción, +2def un turno, 2mag",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Magia Oscura",
        Orden="2",
        Descripcion="Prision Runica: Encarcelas a un grupo de enemigos en esferas constrictoras de magia oscura nublando su visión y provocando que ignoren a cualquier otra persona que no seas tu.",
        Valores="Acción, Taunt por 1 turno a 1d3 enemigos, +1 def por 1 turno, 2 mag",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Magia Oscura",
        Orden="3",
        Descripcion="Negacion Magica: Usando tu conocimiento en magia oscura creas una cúpula de silencio capaz de negar cualquier ataque que el enemigo quiera lanzar.",
        Valores="Reacción, Niega 1 ataque a un enemigo, 3mag",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Invocacion Daedrica",
        Orden="1",
        Descripcion="Invocar Crepusculo aliado: Invocas desde Oblivion a un crepúsculo que transformara parte de tu vida y de tu magia para darle una gran ola de sanación a un objetivo en particular.",
        Valores="Acción, Sanación 1 objetivo 1d4+2, 3 mag",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Invocacion Daedrica",
        Orden="2",
        Descripcion="Custodia Conjurada: Conjuras esferas de energía daédrica que curan las heridas de un grupo grande de personas.",
        Valores="Acción, Sanación 4 objetivos 1d3+1, 6 mag",
    },
    {
        Z="5",
        Nombre="Brujo",
        NombreRama="Invocacion Daedrica",
        Orden="3",
        Descripcion="Armadura Vinculada: Te proteges a ti y a tus aliados usando el poder de Oblivion conjurando para todos una cota de malla daédrica.",
        Valores="Acción, +1 defensa a 1d3 de aliados por un turno, 2mag",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Acompañantes animales",
        Orden="1",
        Descripcion="Netch azul: Invocas a tu Netch azul para que te ayude en combate y envenene a tus enemigos.",
        Valores="Acción adicional para Convocar por primera vez y Acción para el Ataque 1d6+2, 3mag y causa envenenamiento por 2 turnos adicionales, infligiendo 2 pts de daño por turno",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Acompañantes animales",
        Orden="2",
        Descripcion="Asolador cortante: Llamas un violento asolador de acantilados para que ataque a tus enemigos.",
        Valores="Acción adicional para Convocar por primera vez y Acción para el Ataque 1d8+4, 3mag",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Acompañantes animales",
        Orden="3",
        Descripcion="Guardián feroz: Convoca a un feroz oso que atacará con sus zarpas a los enemigos en su área.",
        Valores="Acción adicional para Convocar por primera vez y Acción para el Ataque en área 1d4+1, 4mag",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Equilibrio verde",
        Orden="1",
        Descripcion="Semilla sanadora: Florece las semillas del verde dentro tuyo para que sanen las heridas de uno de tus aliados.",
        Valores="Sanación 1 objetivo 1d4+2, 3 mag",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Equilibrio verde",
        Orden="2",
        Descripcion="Proliferación fúngica: Reúne las esporas de los hongos a tu alrededor y las combina con tu magicka para sanar hasta 4 de tus aliados.",
        Valores="Sanación 4 objetivos 1d3+1, 6 mag",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Equilibrio verde",
        Orden="3",
        Descripcion="Bendición de loto: Usa tu magicka para que florezca como un loto para que la naturaleza misma le preste un poco de su magia a un aliado.",
        Valores="Acción, 1d3+1 Magicka a 1 objetivo, 2 mag",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Abrazo invernal",
        Orden="1",
        Descripcion="Escudo cristalizado: Reaccionas al ataque de tus oponentes congelando el aire a tu alrededor tuyo creando un escudo para protegerte.",
        Valores="Reacción, +2 Def por 1 turno, 2mag",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Abrazo invernal",
        Orden="2",
        Descripcion="Portal congelado: Creas un portal bajo los pies de tus oponentes atrayéndolos y sometiendo su voluntad para que pongan su atención en ti.",
        Valores="Acción, Taunt por 1 turno a 1d3 enemigos, +1 def por 1 turno, 2 mag",
    },
    {
        Z="6",
        Nombre="Guardián",
        NombreRama="Abrazo invernal",
        Orden="3",
        Descripcion="Venganza invernal: Te vengas de los que dañan a tus aliados, congelando el suelo bajo ellos impidiéndoles tomar acción.",
        Valores="Acción, Stun por 1 turno, 1 objetivo, 3mag",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Lanza Daédrica",
        Orden="1",
        Descripcion="Carga Concentrada: El Templario Oscuro concentra la devoción en su pecho, generando un halo de llamas profanas inertes para los aliados pero fulminando a los enemigos con quemaduras.",
        Valores="Acción, Ataque 1d6+2, 3mag y causa quemadura por 2 turnos adicionales, infligiendo 2 pts de daño por turno",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Lanza Daédrica",
        Orden="2",
        Descripcion="Golpes Perforantes: La fe manifiesta en las manos del Dark Templar una lanza de energía oscura, con la cual arremete contra sus adversarios provocando grandes daños.",
        Valores="Acción, Ataque 1d8+4, 3mag",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Lanza Daédrica",
        Orden="3",
        Descripcion="Jabalina Perforadora: La fuerte devoción del Templario Oscuro consagra en la zona un punto donde poderosas lanzas de energía oscura azotan violentamente contra todo objetivo.",
        Valores="Acción, Ataque en área 1d4+1, 4mag",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Ira del ocaso",
        Orden="1",
        Descripcion="Eclipse: El Templario Oscuro realiza una oración que envuelve a sí mismo o un aliado con una fuerte barrera profana que protege a su usuario.",
        Valores="Reacción, +2 Def por 1 turno, 2 mag",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Ira del ocaso",
        Orden="2",
        Descripcion="Opresión radiante: La gran devoción del Templario Oscuro hacia su daedra genera una concentración de energía tan grande que provoca que los adversarios solo puedan atacar al Templario Oscuro.",
        Valores="Acción, Taunt por 1 turno a 1d3 enemigos, +1 def por 1 turno, 2 mag",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Ira del ocaso",
        Orden="3",
        Descripcion="Contragolpe: Las oscuras intenciones del Templario Oscuro se canalizan por medio de una maldición que envuelve al enemigo y lo sume en un aura de debilidad.",
        Valores="Acción, +1 a todos los dados de aquellos que han recibido daño en el turno anterior, coste 3 mag",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Oscuridad restauradora",
        Orden="1",
        Descripcion="Ritual Curativo: Un ritual antiguo y profano para generar poder vital a partir de la devoción del Templario Oscuro que restaura a un aliado.",
        Valores="Acción, Sanación 1 objetivo 1d4+2, 3 mag",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Oscuridad restauradora",
        Orden="2",
        Descripcion="Rito de paso: Desde el suelo, una oscura aura comienza a emerger envolviendo a 4 aliados, este poder profano se interna en sus cuerpos y restaura su energía vital.",
        Valores="Acción, Sanación 4 objetivos 1d3+1, 6 mag",
    },
    {
        Z="7",
        Nombre="Templario Oscuro",
        NombreRama="Oscuridad restauradora",
        Orden="3",
        Descripcion="Honor del Caído: Los rezos del Templario Oscuro llaman la oscuridad encarnada dentro de sus aliados, permitiéndole a los heridos restaurar su fuerza y recobrar su Fe.",
        Valores="Acción Adicional, +1 HP a 3 aliados que hayan recibido daño en el turno anterior, coste 2 mag",
    },
    {
        Z="8",
        Nombre="Arte de la Guerra",
        NombreRama="Armas de una mano",
        Orden="1",
        Descripcion="Doble Arma: Entrenamiento en el combate utilizando dos armas de una mano.",
        Valores="Acción, Ataque 2d3+1, Coste 0 Mag.",
    },
    {
        Z="8",
        Nombre="Arte de la Guerra",
        NombreRama="Armas de una mano",
        Orden="2",
        Descripcion="Arma y escudo: Entrenamiento en el combate con un arma de una mano y escudo.",
        Valores="Def +1, Acción, Ataque 1d3+1, Coste 0 Mag.",
    },
    {
        Z="8",
        Nombre="Arte de la Guerra",
        NombreRama="Armas de dos manos",
        Orden="1",
        Descripcion="Manodoble: Entrenamiento en el combate con un arma de dos manos.",
        Valores="Acción, Ataque 1d8+1, Coste 0 Mag.",
    },
    {
        Z="8",
        Nombre="Arte de la Guerra",
        NombreRama="Armas de dos manos",
        Orden="2",
        Descripcion="Arqueria: Entrenamiento en el combate con arcos cortos y arcos largos.",
        Valores="Acción, Ataque 1d6+1, Coste 0 Mag.",
    },
    {
        Z="8",
        Nombre="Arte de la Guerra",
        NombreRama="Bastones",
        Orden="1",
        Descripcion="Bastones de destrucción: Capacidad de lanzar ataques de fuego, hielo y electricidad.",
        Valores="Acción, Ataque 1d6+1, Coste 0 Mag.",
    },
    {
        Z="8",
        Nombre="Arte de la Guerra",
        NombreRama="Bastones",
        Orden="2",
        Descripcion="Bastones de restauración: Capacidad de sanar y lanzar ataques de energía.",
        Valores="Acción, Ataque 1d3, Coste 0 Mag. / Acción, Sanación 1d3 HP a 2 aliados, Coste 0 Mag.",
    },
    {
        Z="8",
        Nombre="Arte de la Guerra",
        NombreRama="Técnicas adicionales",
        Orden="1",
        Descripcion="Armas de Asedio: Capacitación para operar las siguientes armas de asedio contra estructuras:",
        Valores="Balistas Acción, Ataque 1d12+3, Ventaja contra armas de asedio, Desventaja contra oponentes en movimiento Coste 0 Mag,\nCatapultas Acción, Ataque 1d12+6, 1 turno de recarga. (0 turno de recarga si hay 1 persona asistiendo),\nTrabuquetes Acción, Ataque 1d12+12, 1 turno de recarga, requiere 2 personas,\nArietes Acción, Ataque 1d12+9 y +3 adicional por cada persona asistiendo (max +18), requiere 3-6 personas.",
    },
    {
        Z="9",
        Nombre="Linaje Cercone",
        NombreRama="Bloque 1",
        Orden="1",
        Descripcion="Seducción Vampírica: Seduce a tu objetivo dándote ventaja en la tirada de persuadir.",
        Valores="Tirada de ventaja a Persuadir, 1 uso al día, Coste 0 Mag",
    },
    {
        Z="9",
        Nombre="Linaje Cercone",
        NombreRama="Bloque 2",
        Orden="2",
        Descripcion="Absorción Vampírica: Atacas a tu oponente con sed de sangre, mientras te curas.",
        Valores="Acción, Ataque +2, + 1d3 HP, 1 uso al día, Coste 0 Mag",
    },
    {
        Z="9",
        Nombre="Linaje Cercone",
        NombreRama="Bloque 3",
        Orden="3",
        Descripcion="Vástago de Sangre: Te transformas en Vástago de Sangre alterando tu forma drásticamente, sanándote y mejorando por un turno tu fuerza de ataque y tu defensa. Si usas esta habilidad en exteriores durante el día recibes 2 pt de daño.",
        Valores="Acción Élite, Ataque 1d10+5, Defensa +5, +5 HP, 1 turno, 1 uso al día, (-2 HP, si se usa en exteriores durante el día).",
    },
    {
        Z="10",
        Nombre="Linaje Indómito",
        NombreRama="Bloque 1",
        Orden="1",
        Descripcion="Presencia Indómita: Según la marca obtenida en tu ritual, dicha luna te otorgara un bonificación.\nMasser: Tirada de ventaja en Persuadir\nSecunda: Tirada de ventaja en Intimidar\nLuna Obscura: Tirada de ventaja en Intimidar y Persuadir",
        Valores="Acción, Habilidad fuera de combate, 1 uso al día, Coste 0 Mag.",
    },
    {
        Z="10",
        Nombre="Linaje Indómito",
        NombreRama="Bloque 2",
        Orden="2",
        Descripcion="Devorar: Atacas a tu oponente con furia feral, mientras te curas.",
        Valores="Acción, Ataque 1d6+2, regenera 1d3 HP, 1 uso al día, Coste 0 Mag.",
    },
    {
        Z="10",
        Nombre="Linaje Indómito",
        NombreRama="Bloque 3",
        Orden="3",
        Descripcion="Llamado de la Manada: Invocas 2 lobos para causar un ataque o entras en Berserker potenciando tu forma drásticamente, sanándote y mejorando por un turno tu fuerza de ataque y tu defensa. Por cada Lycan Indómito tu ataque se ve potenciado.",
        Valores="Acción Élite, Ataque 1d10+3 (y +1 adicional por cada Lycan Indómito presente), Defensa +5, +5 HP, 1 turno, 1 uso al día.",
    },
    {
        Z="11",
        Nombre="Habilidades de la orden",
        NombreRama="Custodes",
        Orden="1",
        Descripcion="Restablecimiento Arcano: El custode genera un pozo de magicka pura, restaurando 1d3 de magicka a todos los aliados.",
        Valores="Acción adicional Élite, 1d3 magicka a todos los aliados, 1 uso al día.",
    },
    {
        Z="11",
        Nombre="Habilidades de la orden",
        NombreRama="Sanguinaris",
        Orden="2",
        Descripcion="Cuerno de Guerra: Soplas un cuerno que eleva la moral de tus aliados, potenciando sus ataques un 1d3 durante 1 turno.",
        Valores="Acción adicional Élite, Bonificación de 1d3 al daño de aliados cercanos por 1 turno, 1 uso al día.",
    },
    {
        Z="11",
        Nombre="Habilidades de la orden",
        NombreRama="Frumentarii",
        Orden="3",
        Descripcion="Subterfugio: El Frumentarii se acerca al enemigo, distrayéndolo, mientras genera un aura de sombras ocultando a 1d3 aliados.",
        Valores="Acción adicional Élite, oculta 1d3 de aliados, 1 uso al día.",
    },
    {
        Z="11",
        Nombre="Habilidades de la orden",
        NombreRama="Inquisidores",
        Orden="4",
        Descripcion="Devoción Profana: Realizas un rezo a la Dama de los Lamentos suplicando su ayuda, reviviendo 1d6 de aliados en caso de utilizarse como acción. O reviviéndote a ti mismo, en caso de utilizarse como reacción.",
        Valores="Acción Élite o Acción adicional Élite, Resurrección en masa de 1d6 de aliados, o a si mismo, 1 uso al día.",
    },
    {
        Z="12",
        Nombre="Herrería",
        NombreRama="Bloque 1",
        Orden="1",
        Descripcion="Refuerzos de armadura: Unos refuerzos de armadura que mejoran tu capacidad de resistir golpes fisicos y de hechizos.",
        Valores="Bonificador de Defensa +1 permanente.",
    },
    {
        Z="12",
        Nombre="Herrería",
        NombreRama="Bloque 2",
        Orden="2",
        Descripcion="Herrero del Clan: Técnicas avanzadas que requieren de una mayor aptitud física para la fabricación de armas y armaduras.",
        Valores="Bonificador de Fuerza +1 permanente.",
    },
    {
        Z="12",
        Nombre="Herrería",
        NombreRama="Bloque 3",
        Orden="3",
        Descripcion="Piedras de afilar y contrapeso: Incorporación del uso de las piedras de afilar para hacer mas daños con las armas punzo-cortantes y contrapesos para hacer mas daño con armas contundentes.",
        Valores="Bonificador de +1 a los ataques con Arco, Dagas, Espadas, Hachas y Mazas.",
    },
    {
        Z="13",
        Nombre="Ingeniería de Clockwork",
        NombreRama="Bloque 1",
        Orden="1",
        Descripcion="Ganzúas mejoradas: Aprendes a fabricas unas ganzúas mejoradas, que te permiten desempeñarte mejor al forzar cerraduras.",
        Valores="Bonificador de Inutilizar Mecanismo +1 permanente",
    },
    {
        Z="13",
        Nombre="Ingeniería de Clockwork",
        NombreRama="Bloque 2",
        Orden="1",
        Descripcion="Fabricante de Clockwork City: Ordenas a tu fabricante previamente ensamblado a atacar a tu oponente.",
        Valores="Acción, Ataque 1d8+4, 1 uso al día, Coste 0 Mag",
    },
    {
        Z="13",
        Nombre="Ingeniería de Clockwork",
        NombreRama="Bloque 3",
        Orden="1",
        Descripcion="Protocolo de Autodestrucción: Ordenas a tu fabricante previamente fabricado a ejecutar su protocolo de autodestrucción causando una gran explosión.",
        Valores="Acción, Ataque en área 1d4+1, 1 uso al día, Coste 0 Mag.",
    },
    {
        Z="14",
        Nombre="Sastrería",
        NombreRama="Bloque 1",
        Orden="1",
        Descripcion="Refuerzos de armadura: Unos refuerzos de armadura que mejoran tu capacidad de resistir golpes fisicos y de hechizos.",
        Valores="Bonificador de Defensa +1 permanente",
    },
    {
        Z="14",
        Nombre="Sastrería",
        NombreRama="Bloque 2",
        Orden="1",
        Descripcion="Armadura Ornamentada: Utiliza tu habilidades de sastre para darte una apariencia mas Noble, y así persuadir mas fácilmente.",
        Valores="Bonificador de persuasión +1 permanente",
    },
    {
        Z="14",
        Nombre="Sastrería",
        NombreRama="Bloque 3",
        Orden="1",
        Descripcion="Empuñadura potenciada: Aprende a fabricar una empuñadura con hilos mágicos que permiten una mejor conducción del ataque mágico.",
        Valores="Bonificador de +1 a los ataques con bastón.",
    },
    {
        Z="15",
        Nombre="Alquimia",
        NombreRama="Bloque 1",
        Orden="1",
        Descripcion="Poción de Regeneración: Bebes una poción previamente creada que cura tus heridas.",
        Valores="Acción adicional, Sanación +3 HP, Coste 0.",
    },
    {
        Z="15",
        Nombre="Alquimia",
        NombreRama="Bloque 1",
        Orden="2",
        Descripcion="Poción de Magicka: Bebes una poción previamente creada que recupera tu Magicka.",
        Valores="Acción adicional, Recupera +3 Mag, Coste 0.",
    },
    {
        Z="15",
        Nombre="Alquimia",
        NombreRama="Bloque 2",
        Orden="1",
        Descripcion="Toxicología I Venenos: Lanzas un vial de veneno a tu enemigo causando 2pts de daño cada turno, durante 3 turnos",
        Valores="Acción, Ataque 2pts daño por turno, Duración: 3 turnos, Coste 0 Mag",
    },
    {
        Z="15",
        Nombre="Alquimia",
        NombreRama="Bloque 2",
        Orden="2",
        Descripcion="Toxicología II Antídotos: Bebes un antídoto previamente preparado que elimina los efectos de envenenamientos.",
        Valores="Acción Adicional, Elimina 2 efectos dañinos en ti, Coste 0 Mag.",
    },
    {
        Z="15",
        Nombre="Alquimia",
        NombreRama="Bloque 3",
        Orden="1",
        Descripcion="Poción de invisibilidad:  Bebes una poción previamente creada que te hace invisible temporalmente",
        Valores="Acción Adicional, 2 turnos/6 min, Coste 0 Mag.",
    },
}
