TetsuCombatTools = TetsuCombatTools or {}

TetsuCombatTools.L = {
    TITLE = "|cFFD700Tetsu's|r Combat Tools",

    INFO_LABEL = "Info",
    INFO_TT = "Gamepad-Kampf-HUD. Skills, Kampflampe, Essen und Trank, Veteranen-Timer.\nGold / Bugs: Post an @Tetsurion.",

    SKILL_ENABLE = "Skill-Tracking",
    SKILL_ENABLE_TT = "Zeigt die zuletzt gedrückten Leisten-Skills und einen GCD-Balken. Ultimate ist immer dabei.",

    SKILL_SECTION = "Skill-Tracking",
    SKILL_SECTION_TT = "Historie-Leiste, Größe, Position, Sichtbarkeit.",

    SKILL_SLOTS = "Historie-Slots",
    SKILL_SLOTS_TT = "Wie viele letzte Skills behalten. 4–8. Standard 6.",

    SKILL_SCALE = "Symbolgröße %",
    SKILL_SCALE_TT = "Größe der Historie-Symbole.",

    SKILL_X = "Offset X",
    SKILL_X_TT = "0 = Bildschirmmitte. Minus links, plus rechts.",

    SKILL_Y = "Offset Y",
    SKILL_Y_TT = "0 = Fadenkreuz / Bildschirmmitte. Standard 330 über der Aktionsleiste. Minus oben, plus unten.",

    SKILL_SHOW = "Wann anzeigen",
    SKILL_SHOW_TT = "Kampf = im Kampf, danach ausblenden. Immer = bleibt. Nach Druck = N Sekunden nach dem letzten Skill.",

    SHOW_COMBAT = "Nur im Kampf",
    SHOW_ALWAYS = "Immer",
    SHOW_IDLE = "Nach letztem Druck",

    SKILL_HIDE = "Ausblenden nach (Sek)",
    SKILL_HIDE_TT = "Nach Kampfende (Kampfmodus) und nach dem letzten Skill (Nach-Druck-Modus). Standard 8.",

    SKILL_BAR = "Skill-Symbole",
    SKILL_BAR_TT = "Historie. Aus = keine Symbole; GCD bleibt und folgt X/Y.",
    SKILL_GCD = "GCD-Balken",
    SKILL_GCD_TT = "Gelb/roter Balken. Geht auch ohne Symbole. Gleiche X/Y.",

    SKILL_WEAVE = "Weave-Rahmen",
    SKILL_WEAVE_TT = "Grüner Rahmen, wenn vorher ein Leichtangriff gedrückt wurde, sonst rot. Aus = normale Rahmen. Leichtangriff-Symbole bleiben getrennt.",

    SKILL_LA = "Leichte Angriffe",
    SKILL_LA_TT = "Standard aus. Wenn an, erscheinen Waffen-Leichtangriffe als eigene Symbole. Der Weave-Rahmen funktioniert auch aus. Schwere Angriffe, Block, Dodge und Synergien bleiben draußen.",

    STATUS_ENABLE = "Kampfstatus",
    STATUS_ENABLE_TT = "Rot im Kampf, grün außerhalb. Symbol, Text und Startton sind getrennt.",
    STATUS_SECTION = "Kampfstatus",
    STATUS_SECTION_TT = "Symbol, Text und der Ton beim Kampfbeginn.",
    STATUS_ICON = "Symbol",
    STATUS_ICON_TT = "Standard an. Farbiger Kreis am Fadenkreuz. Position und Größe unabhängig vom Text.",
    STATUS_ICON_X = "Symbol Offset X",
    STATUS_ICON_X_TT = "0 = Bildschirmmitte. Bereich ±900 bis zum Rand.",
    STATUS_ICON_Y = "Symbol Offset Y",
    STATUS_ICON_Y_TT = "0 = Fadenkreuz. Minus oben, plus unten.",
    STATUS_ICON_SCALE = "Symbolgröße %",
    STATUS_ICON_SCALE_TT = "Größe der Kampflampe. Minimum 30.",
    STATUS_ICON_ALPHA = "Symbol-Deckkraft %",
    STATUS_ICON_ALPHA_TT = "Wie deckend die Lampe ist. Standard 50.",
    STATUS_TEXT = "Text",
    STATUS_TEXT_TT = "Standard aus. Schreibt IM KAMPF / AUSSER KAMPF in denselben Farben.",
    STATUS_TEXT_X = "Text Offset X",
    STATUS_TEXT_X_TT = "0 = Bildschirmmitte.",
    STATUS_TEXT_Y = "Text Offset Y",
    STATUS_TEXT_Y_TT = "Standard 250 unter dem Fadenkreuz. Minus oben, plus unten.",
    STATUS_TEXT_SCALE = "Textgröße %",
    STATUS_TEXT_SCALE_TT = "Größe des Kampftexts. 40 klein, 250 groß.",
    STATUS_IN = "IM KAMPF",
    STATUS_OUT = "AUSSER KAMPF",
    STATUS_SOUND = "Ton bei Kampfbeginn",
    STATUS_SOUND_TT = "Standard an. Nur beim Eintreten in den Kampf, nie beim Verlassen.",
    STATUS_SOUND_PICK = "Startton",
    STATUS_SOUND_PICK_TT = "Eingebauter Spielton. Keine eigenen Dateien.",
    SOUND_DUEL = "Duellstart",
    SOUND_ALERT = "Warnung",
    SOUND_QUEST = "Quest-Tick",
    SOUND_NOTIFY = "Benachrichtigung",
    SOUND_DISCOVER = "Ziel entdeckt",

    CONS_ENABLE = "Verbrauchsgegenstände",
    CONS_ENABLE_TT = "Zwei Slots: Essen und Trank. Symbol + Restzeit. Grauer Strich wenn leer.",
    CONS_SECTION = "Verbrauchsgegenstände",
    CONS_SECTION_TT = "Essens- und Trank-Timer.",
    CONS_X = "Offset X",
    CONS_X_TT = "0 = Bildschirmmitte.",
    CONS_Y = "Offset Y",
    CONS_Y_TT = "0 = Fadenkreuz. Standard 220 über der Skillleiste.",
    CONS_SCALE = "Größe %",
    CONS_SCALE_TT = "Symbol und Timer-Text zusammen. 40 klein, 250 groß.",
    CONS_SHOW_FOOD = "Essen zeigen",
    CONS_SHOW_FOOD_TT = "Aus = Essens-Slot verstecken. Trank kann bleiben.",
    CONS_SHOW_POT = "Trank zeigen",
    CONS_SHOW_POT_TT = "Aus = Trank-Slot verstecken. Essen kann bleiben.",
    CONS_FOOD_WARN = "Essen-Warnung (Min)",
    CONS_FOOD_WARN_TT = "Timer wird gelb, wenn so viele Minuten Essen übrig sind. Standard 5.",
    CONS_POT_WARN = "Trank-Warnung (Sek)",
    CONS_POT_WARN_TT = "Timer wird gelb, wenn so viele Sekunden Trank-Buff übrig sind. Standard 10.",
    CONS_POT_COMBAT = "Trank nur im Kampf",
    CONS_POT_COMBAT_TT = "Trank-Slot außerhalb des Kampfs ausblenden. Essen bleibt.",
    CONS_FOOD_SOUND = "Ton wenn Essen endet",
    CONS_FOOD_SOUND_TT = "Standard aus. Einmal, wenn der Essens-Buff verschwindet.",
    CONS_POT_SOUND = "Ton wenn Trank endet",
    CONS_POT_SOUND_TT = "Standard aus. Gleicher Ton wie beim Essen — unten wählen.",
    CONS_END_SOUND = "Ende-Ton",
    CONS_END_SOUND_TT = "Ein eingebauter Ton für Essen- und Trank-Ende.",
    CONS_MSG = "Ende-Text in Instanzen",
    CONS_MSG_TT = "Kurze Zeile wenn Essen oder Trank endet. Nur Dungeon / Prüfung / Arena / Archiv / PvP. Nicht in der offenen Welt.",
    CONS_MSG_FOOD_ON = "Essen-Ende-Text",
    CONS_MSG_FOOD_ENTER = "Text beim Betreten",
    CONS_MSG_FOOD_ENTER_TT = "Standard an. 10s „Kein Essen“ beim Betreten von Dungeon / Prüfung / Arena / Archiv ohne Essen.",

    CONS_MSG_FOOD_ON_TT = "An = „Essen beendet“ in Instanzen für 60 Sekunden. Position ist X/Y unten.",
    CONS_MSG_POT_ON = "Trank-Ende-Text",
    CONS_MSG_POT_ON_TT = "An = „Trank beendet“. Gleiches X wie Essen, eine Zeile tiefer.",
    CONS_MSG_X = "Text Offset X",
    CONS_MSG_X_TT = "X der Essens-Zeile. Der Trank nutzt dasselbe X.",
    CONS_MSG_Y = "Text Offset Y",
    CONS_MSG_Y_TT = "Y der Essens-Zeile. Trank eine Zeile tiefer. 0 = Fadenkreuz.",
    CONS_MSG_SCALE = "Textgröße %",
    CONS_MSG_SCALE_TT = "Größe des Ende-Warntexts.",
    CONS_MSG_FOOD = "Essen beendet",
    CONS_MSG_FOOD_MISS = "Kein Essen",
    CONS_MSG_POT = "Trank beendet",
    CONS_MSG_BOTH = "Essen und Trank beendet",
    CONS_PREVIEW = "Vorschau",
    CONS_PREVIEW_TT = "Zeigt Dummy-Timer, spielt den Ende-Ton und den Warntext 8 Sekunden — auch über diesem Menü.",
    CONS_PREVIEW_BTN = "8 Sek. zeigen",

    TIMER_ENABLE = "Lauf-Timer",
    TIMER_ENABLE_TT = "Standard aus. Nur Veteran. Dungeon startet beim ersten Kampf, Prüfung/Arena wenn die Tür aufgeht. Stoppt bei Abschluss.",
    TIMER_SECTION = "Lauf-Timer",
    TIMER_SECTION_TT = "Welchen Veteranen-Inhalt zeitnehmen, Position und 10-Sekunden-Vorschau.",
    TIMER_DUNGEON = "Gruppendungeons",
    TIMER_DUNGEON_TT = "Veteranen-4er-Dungeons. Startet beim ersten Kampf.",
    TIMER_TRIAL = "Prüfungen",
    TIMER_TRIAL_TT = "Veteranen-Prüfungen. Startet wenn die Raid-Tür aufgeht.",
    TIMER_ARENA = "Arenen",
    TIMER_ARENA_TT = "Veteranen-Arenen (DSA, Mahlstrom, Schwarzdorn, Vateshran). Startet wenn die Tür aufgeht.",
    TIMER_GOAL = "Zeitlimit zeigen",
    TIMER_GOAL_TT = "Offizielle Veteranen-Speed-Zeit: 8:12 / 20:00. Wird rot wenn drüber. Aus = nur aktuelle Zeit.",
    TIMER_X = "Offset X",
    TIMER_X_TT = "0 = Bildschirmmitte. Bereich ±900 bis zum Rand.",
    TIMER_Y = "Offset Y",
    TIMER_Y_TT = "0 = Fadenkreuz. Minus oben, plus unten. ±900 bis ganz nach oben und unten.",
    TIMER_SCALE = "Größe %",
    TIMER_SCALE_TT = "Echte Textgröße der Uhr. 100 = Standard. 40 klein, 250 groß.",
    TIMER_PREVIEW = "Vorschau",
    TIMER_PREVIEW_TT = "Zeigt die Uhr 10 Sekunden auch in der Stadt, auch über dem Einstellungsmenü, zum Setzen von X/Y.",
    TIMER_PREVIEW_BTN = "10 Sek. zeigen",

    LINK_ENABLE = "Set-Link",
    LINK_GROUP = "Immer Gruppenchat",
    LINK_GROUP_TT = "An = auf Gruppe/Schlachtzug wechseln. Aus = aktueller Kanal im Chatmenü. Standard an.",
    LINK_ENABLE_TT = "R3 in der vollen Text-Chat-Ansicht halten. Ohne Gruppe = /say.",
    LINK_SECTION = "Set-Link",
    LINK_SECTION_TT = "Keine Extra-Optionen. Schalter auf der ersten Seite.",
    LINK_HELP = "R3 im vollen Text-Chat halten.",
    LINK_HELP_TT = "Sozial → Text-Chat. R3 ~0,6s halten. Ohne Gruppe = /say.",
    LINK_HOLD = "R3 halten: Sets",
    LINK_EMPTY = "Keine Sets zum Verlinken.",
    LINK_TEST = "Jetzt einfügen",
    LINK_TEST_TT = "Dieselben Links ins Chatfeld, ohne Chatmenü.",
    LINK_TEST_BTN = "Sets linken",
}
