TetsuCombatTools = TetsuCombatTools or {}

TetsuCombatTools.L = {
    TITLE = "|cFFD700Tetsu's|r Combat Tools",

    INFO_LABEL = "Info",
    INFO_TT = "Gamepad combat HUD. Skills, combat lamp, food and potion, veteran run timer, set link.\nGold / bugs: mail @Tetsurion.",

    SKILL_ENABLE = "Skill Tracking",
    SKILL_ENABLE_TT = "Show the last pressed bar skills and a GCD bar. Ultimate is always included.",

    SKILL_SECTION = "Skill Tracking",
    SKILL_SECTION_TT = "History strip, size, position, visibility.",

    SKILL_SLOTS = "History slots",
    SKILL_SLOTS_TT = "How many recent skills to keep. 4–8. Default 6.",

    SKILL_SCALE = "Icon scale %",
    SKILL_SCALE_TT = "Size of the history icons.",

    SKILL_X = "Offset X",
    SKILL_X_TT = "0 = screen center. Negative left, positive right.",

    SKILL_Y = "Offset Y",
    SKILL_Y_TT = "0 = reticle / screen center. Default 330 sits above the action bar. Negative = up, positive = down.",

    SKILL_SHOW = "When to show",
    SKILL_SHOW_TT = "Combat = in fight, then hide after the delay. Always = stay up. After press = hide N seconds after the last skill.",

    SHOW_COMBAT = "In combat only",
    SHOW_ALWAYS = "Always",
    SHOW_IDLE = "After last press",

    SKILL_HIDE = "Hide after (sec)",
    SKILL_HIDE_TT = "Used after combat ends (combat mode) and after the last press (after-press mode). Default 8.",

    SKILL_BAR = "Skill icons",
    SKILL_BAR_TT = "History strip. Off = hide icons; GCD can stay and still follows X/Y.",
    SKILL_GCD = "GCD bar",
    SKILL_GCD_TT = "Yellow/red bar. Works with icons off. Same X/Y as the skill strip.",

    SKILL_WEAVE = "Weave frames",
    SKILL_WEAVE_TT = "Green frame if a light attack was pressed before the skill, red if not. Off = plain frames. Light-attack icons stay separate.",

    SKILL_LA = "Show light attacks",
    SKILL_LA_TT = "Off by default. When on, weapon light attacks also appear as their own icons. Weave mark (green/red frame) works even if this is off. Heavy attacks, block, dodge and synergies stay out.",

    STATUS_ENABLE = "Combat Status",
    STATUS_ENABLE_TT = "Red in combat, green out of combat. Icon, text and start sound are separate.",
    STATUS_SECTION = "Combat Status",
    STATUS_SECTION_TT = "Icon, text and the sound played when a fight starts.",
    STATUS_ICON = "Icon",
    STATUS_ICON_TT = "On by default. Colored circle at the reticle. Position and size are independent from the text.",
    STATUS_ICON_X = "Icon offset X",
    STATUS_ICON_X_TT = "0 = screen center. Negative left, positive right.",
    STATUS_ICON_Y = "Icon offset Y",
    STATUS_ICON_Y_TT = "0 = reticle / screen center. Negative up, positive down.",
    STATUS_ICON_SCALE = "Icon scale %",
    STATUS_ICON_SCALE_TT = "Size of the combat lamp. Minimum 30.",
    STATUS_ICON_ALPHA = "Icon opacity %",
    STATUS_ICON_ALPHA_TT = "How solid the lamp is. Default 50.",
    STATUS_TEXT = "Text",
    STATUS_TEXT_TT = "Off by default. Writes IN COMBAT / OUT OF COMBAT in the same red/green colors.",
    STATUS_TEXT_X = "Text offset X",
    STATUS_TEXT_X_TT = "0 = screen center.",
    STATUS_TEXT_Y = "Text offset Y",
    STATUS_TEXT_Y_TT = "Default 250 = below the reticle. Negative up, positive down.",
    STATUS_TEXT_SCALE = "Text scale %",
    STATUS_TEXT_SCALE_TT = "Size of the combat text. 40 tiny, 250 huge.",
    STATUS_IN = "IN COMBAT",
    STATUS_OUT = "OUT OF COMBAT",
    STATUS_SOUND = "Sound on combat start",
    STATUS_SOUND_TT = "On by default. Plays only when you enter combat, never when you leave.",
    STATUS_SOUND_PICK = "Start sound",
    STATUS_SOUND_PICK_TT = "Built-in game sound. No custom files.",
    SOUND_DUEL = "Duel start",
    SOUND_ALERT = "Alert",
    SOUND_QUEST = "Quest tick",
    SOUND_NOTIFY = "Notification",
    SOUND_DISCOVER = "Objective found",

    CONS_ENABLE = "Consumables",
    CONS_ENABLE_TT = "Two slots: food and potion. Icon + time left. Grey dash if missing.",
    CONS_SECTION = "Consumables",
    CONS_SECTION_TT = "Food and potion timers.",
    CONS_X = "Offset X",
    CONS_X_TT = "0 = screen center.",
    CONS_Y = "Offset Y",
    CONS_Y_TT = "0 = reticle. Default 220 sits above the skill strip.",
    CONS_SCALE = "Scale %",
    CONS_SCALE_TT = "Icon and timer text together. 40 tiny, 250 huge.",
    CONS_SHOW_FOOD = "Show food",
    CONS_SHOW_FOOD_TT = "Off = hide the food slot. Potion can stay.",
    CONS_SHOW_POT = "Show potion",
    CONS_SHOW_POT_TT = "Off = hide the potion slot. Food can stay.",
    CONS_FOOD_WARN = "Food warn (min)",
    CONS_FOOD_WARN_TT = "Timer turns yellow when food has this many minutes left. Default 5.",
    CONS_POT_WARN = "Potion warn (sec)",
    CONS_POT_WARN_TT = "Timer turns yellow when the potion buff has this many seconds left. Default 10.",
    CONS_POT_COMBAT = "Potion only in combat",
    CONS_POT_COMBAT_TT = "Hide the potion slot out of combat. Food stays.",
    CONS_FOOD_SOUND = "Sound when food ends",
    CONS_FOOD_SOUND_TT = "Off by default. Plays once when the food buff disappears.",
    CONS_POT_SOUND = "Sound when potion ends",
    CONS_POT_SOUND_TT = "Off by default. Same sound as food — pick it below.",
    CONS_END_SOUND = "End sound",
    CONS_END_SOUND_TT = "One built-in sound for both food and potion end.",
    CONS_MSG = "End text in instances",
    CONS_MSG_TT = "Short line when food or potion ends. Only in dungeon / trial / arena / archive / PvP. Never overland.",
    CONS_MSG_FOOD_ON = "Food end text",
    CONS_MSG_FOOD_ENTER = "Text on enter",
    CONS_MSG_FOOD_ENTER_TT = "On by default. 10s “No food” when you enter a dungeon / trial / arena / archive without food. Independent from the end text.",

    CONS_MSG_FOOD_ON_TT = "On = “Food ended” for 60s when the buff drops, and “No food” for 10s when you enter a dungeon/trial/arena without food.",
    CONS_MSG_POT_ON = "Potion end text",
    CONS_MSG_POT_ON_TT = "On = show “Potion ended”. Same X as food, one line lower.",
    CONS_MSG_X = "Text offset X",
    CONS_MSG_X_TT = "X of the food line. Potion uses the same X.",
    CONS_MSG_Y = "Text offset Y",
    CONS_MSG_Y_TT = "Y of the food line. Potion sits one line below. 0 = reticle.",
    CONS_MSG_SCALE = "Text scale %",
    CONS_MSG_SCALE_TT = "Size of the end warning text.",
    CONS_MSG_FOOD = "Food ended",
    CONS_MSG_FOOD_MISS = "No food",
    CONS_MSG_POT = "Potion ended",
    CONS_MSG_BOTH = "Food and potion ended",
    CONS_PREVIEW = "Preview",
    CONS_PREVIEW_TT = "Shows dummy timers, plays the end sound and the warning text for 8 seconds — even over this menu.",
    CONS_PREVIEW_BTN = "Show 8s",

    TIMER_ENABLE = "Run Timer",
    TIMER_ENABLE_TT = "Off by default. Veteran only. Dungeon starts on first combat, trial/arena when the door opens. Stops on activity complete.",
    TIMER_SECTION = "Run Timer",
    TIMER_SECTION_TT = "Which veteran content to time, position, and a 10-second preview.",
    TIMER_DUNGEON = "Group dungeons",
    TIMER_DUNGEON_TT = "Veteran 4-man dungeons. Starts on first combat.",
    TIMER_TRIAL = "Trials",
    TIMER_TRIAL_TT = "Veteran trials. Starts when the raid door opens.",
    TIMER_ARENA = "Arenas",
    TIMER_ARENA_TT = "Veteran arenas (DSA, Maelstrom, Blackrose, Vateshran). Starts when the raid door opens.",
    TIMER_GOAL = "Show speed limit",
    TIMER_GOAL_TT = "Adds the official veteran speed-achievement time: 8:12 / 20:00. Turns red if you go over. Off = current time only.",
    TIMER_X = "Offset X",
    TIMER_X_TT = "0 = screen center. Range ±900 so you can park it at the edge.",
    TIMER_Y = "Offset Y",
    TIMER_Y_TT = "0 = reticle. Minus = up, plus = down. Range ±900 reaches the top and the very bottom.",
    TIMER_SCALE = "Scale %",
    TIMER_SCALE_TT = "Actual text size of the clock. 100 = default. 40 tiny, 250 huge.",
    TIMER_PREVIEW = "Preview",
    TIMER_PREVIEW_TT = "Shows the clock for 10 seconds even in town, including over the settings menu, so you can set X/Y.",
    TIMER_PREVIEW_BTN = "Show 10s",

    LINK_ENABLE = "Set Link",
    LINK_GROUP = "Always group chat",
    LINK_GROUP_TT = "On = switch to party/raid and put the links there. Off = keep the channel already open in the chat menu. Default on.",
    LINK_ENABLE_TT = "Hold R3 in the full Text Chat menu to put one piece of each worn set into the chat box. 2+ pieces or a mythic. Does not send by itself. Not in a group = /say.",
    LINK_SECTION = "Set Link",
    LINK_SECTION_TT = "No extra options. Toggle is on the first page.",
    LINK_HELP = "Hold R3 in full Text Chat.",
    LINK_HELP_TT = "Social → Text Chat. Hold R3 ~0.6s. Links drop into the input. You still press Send. One piece per set with 2+ equipped, plus mythic. Not in a group = /say.",
    LINK_HOLD = "Hold R3: sets",
    LINK_EMPTY = "No sets to link.",
    LINK_TEST = "Insert now",
    LINK_TEST_TT = "Puts the same links into chat input without opening the chat menu.",
    LINK_TEST_BTN = "Link sets",
}
