TetsuCombatTools = TetsuCombatTools or {}

TetsuCombatTools.L = {
    TITLE = "|cFFD700Tetsu's|r Combat Tools",
    INFO_LABEL = "Info",
    INFO_TT = "HUD de combate para mando. Habilidades, lampara, comida y pocion, cronometro veterano.\nOro / errores: correo @Tetsurion.",
    SKILL_ENABLE = "Seguimiento de habilidades",
    SKILL_ENABLE_TT = "Muestra las ultimas habilidades de la barra y una barra de GCD. La definitiva siempre entra.",
    SKILL_SECTION = "Seguimiento de habilidades",
    SKILL_SECTION_TT = "Historial, tamano, posicion, visibilidad.",
    SKILL_SLOTS = "Huecos de historial",
    SKILL_SLOTS_TT = "Cuantas habilidades recientes guardar. 4-8. Por defecto 6.",
    SKILL_SCALE = "Escala de iconos %",
    SKILL_SCALE_TT = "Tamano de los iconos del historial.",
    SKILL_X = "Desplazamiento X",
    SKILL_X_TT = "0 = centro. Menos izquierda, mas derecha.",
    SKILL_Y = "Desplazamiento Y",
    SKILL_Y_TT = "0 = reticula / centro. Por defecto 330 encima de la barra. Menos = arriba, mas = abajo.",
    SKILL_SHOW = "Cuando mostrar",
    SKILL_SHOW_TT = "Combate = en pelea y luego se oculta. Siempre = se queda. Tras pulsar = N segundos tras la ultima habilidad.",
    SHOW_COMBAT = "Solo en combate",
    SHOW_ALWAYS = "Siempre",
    SHOW_IDLE = "Tras la ultima pulsacion",
    SKILL_HIDE = "Ocultar tras (s)",
    SKILL_HIDE_TT = "Tras acabar el combate y tras la ultima pulsacion. Por defecto 8.",
    SKILL_BAR = "Iconos de skills",
    SKILL_BAR_TT = "Historial. Off = sin iconos; el GCD se queda y sigue X/Y.",
    SKILL_GCD = "Barra GCD",
    SKILL_GCD_TT = "Barra amarilla/roja. Funciona sin iconos. Mismo X/Y.",
    SKILL_WEAVE = "Marcos de weave",
    SKILL_WEAVE_TT = "Marco verde si hubo ataque ligero antes de la habilidad, rojo si no.",
    SKILL_LA = "Ataques ligeros",
    SKILL_LA_TT = "Desactivado por defecto. Si se activa, los ligeros de arma salen como iconos.",
    STATUS_ENABLE = "Estado de combate",
    STATUS_ENABLE_TT = "Rojo en combate, verde fuera. Icono, texto y sonido de inicio van aparte.",
    STATUS_SECTION = "Estado de combate",
    STATUS_SECTION_TT = "Icono, texto y el sonido al empezar el combate.",
    STATUS_ICON = "Icono",
    STATUS_ICON_TT = "Activado por defecto. Circulo de color en la reticula.",
    STATUS_ICON_X = "Icono X",
    STATUS_ICON_X_TT = "0 = centro. Rango ±900 hasta el borde.",
    STATUS_ICON_Y = "Icono Y",
    STATUS_ICON_Y_TT = "0 = reticula. Menos = arriba, mas = abajo.",
    STATUS_ICON_SCALE = "Escala icono %",
    STATUS_ICON_SCALE_TT = "Tamano de la lampara. Minimo 30.",
    STATUS_ICON_ALPHA = "Opacidad icono %",
    STATUS_ICON_ALPHA_TT = "Que tan solido se ve. Por defecto 50.",
    STATUS_TEXT = "Texto",
    STATUS_TEXT_TT = "Desactivado por defecto. Escribe EN COMBATE / FUERA DE COMBATE.",
    STATUS_TEXT_X = "Texto X",
    STATUS_TEXT_X_TT = "0 = centro de la pantalla.",
    STATUS_TEXT_Y = "Texto Y",
    STATUS_TEXT_Y_TT = "Por defecto 250 bajo la reticula.",
    STATUS_TEXT_SCALE = "Escala texto %",
    STATUS_TEXT_SCALE_TT = "Tamano del texto de combate. 40 pequeno, 250 grande.",
    STATUS_IN = "EN COMBATE",
    STATUS_OUT = "FUERA DE COMBATE",
    STATUS_SOUND = "Sonido al empezar combate",
    STATUS_SOUND_TT = "Activado por defecto. Solo al entrar en combate.",
    STATUS_SOUND_PICK = "Sonido de inicio",
    STATUS_SOUND_PICK_TT = "Sonido integrado del juego.",
    SOUND_DUEL = "Inicio de duelo",
    SOUND_ALERT = "Alerta",
    SOUND_QUEST = "Tick de mision",
    SOUND_NOTIFY = "Notificacion",
    SOUND_DISCOVER = "Objetivo hallado",
    CONS_ENABLE = "Consumibles",
    CONS_ENABLE_TT = "Dos huecos: comida y pocion. Icono + tiempo.",
    CONS_SECTION = "Consumibles",
    CONS_SECTION_TT = "Temporizadores de comida y pocion.",
    CONS_X = "Desplazamiento X",
    CONS_X_TT = "0 = centro de la pantalla.",
    CONS_Y = "Desplazamiento Y",
    CONS_Y_TT = "0 = reticula. Por defecto 220 encima de la barra.",
    CONS_SCALE = "Escala %",
    CONS_SCALE_TT = "Icono y texto del temporizador juntos. 40 pequeno, 250 grande.",
    CONS_SHOW_FOOD = "Mostrar comida",
    CONS_SHOW_FOOD_TT = "Off = ocultar el hueco de comida.",
    CONS_SHOW_POT = "Mostrar pocion",
    CONS_SHOW_POT_TT = "Off = ocultar el hueco de pocion.",
    CONS_FOOD_WARN = "Aviso comida (min)",
    CONS_FOOD_WARN_TT = "El temporizador se pone amarillo con tantos minutos restantes. Por defecto 5.",
    CONS_POT_WARN = "Aviso pocion (s)",
    CONS_POT_WARN_TT = "El temporizador se pone amarillo con tantos segundos. Por defecto 10.",
    CONS_POT_COMBAT = "Pocion solo en combate",
    CONS_POT_COMBAT_TT = "Oculta la pocion fuera de combate. La comida se queda.",
    CONS_FOOD_SOUND = "Sonido al acabar la comida",
    CONS_FOOD_SOUND_TT = "Desactivado por defecto. Una vez cuando desaparece el beneficio.",
    CONS_POT_SOUND = "Sonido al acabar la pocion",
    CONS_POT_SOUND_TT = "Desactivado por defecto. El mismo sonido que la comida.",
    CONS_END_SOUND = "Sonido de fin",
    CONS_END_SOUND_TT = "Un sonido integrado para el fin de comida y pocion.",
    CONS_MSG = "Texto de fin en instancias",
    CONS_MSG_TT = "Linea corta cuando acaba comida o pocion. Solo mazmorra / prueba / arena / archivo / JcJ.",
    CONS_MSG_FOOD_ON = "Texto fin de comida",
    CONS_MSG_FOOD_ENTER = "Texto al entrar",
    CONS_MSG_FOOD_ENTER_TT = "Activado por defecto. 10s «Sin comida» al entrar a mazmorra / prueba / arena / archivo sin comida.",

    CONS_MSG_FOOD_ON_TT = "On = Comida terminada en instancia durante 60 segundos.",
    CONS_MSG_POT_ON = "Texto fin de pocion",
    CONS_MSG_POT_ON_TT = "On = Pocion terminada. El mismo X que la comida, una linea mas abajo.",
    CONS_MSG_X = "Texto X",
    CONS_MSG_X_TT = "X de la linea de comida. La pocion usa el mismo X.",
    CONS_MSG_Y = "Texto Y",
    CONS_MSG_Y_TT = "Y de la linea de comida. La pocion una linea mas abajo. 0 = reticula.",
    CONS_MSG_SCALE = "Escala texto %",
    CONS_MSG_SCALE_TT = "Tamano del texto de aviso.",
    CONS_MSG_FOOD = "Comida terminada",
    CONS_MSG_FOOD_MISS = "Sin comida",
    CONS_MSG_POT = "Pocion terminada",
    CONS_MSG_BOTH = "Comida y pocion terminadas",
    CONS_PREVIEW = "Vista previa",
    CONS_PREVIEW_TT = "Muestra temporizadores de prueba, el sonido y el texto 8 segundos.",
    CONS_PREVIEW_BTN = "Mostrar 8 s",
    TIMER_ENABLE = "Cronometro de run",
    TIMER_ENABLE_TT = "Desactivado por defecto. Solo veterano. Mazmorra al primer combate, prueba/arena al abrir la puerta.",
    TIMER_SECTION = "Cronometro de run",
    TIMER_SECTION_TT = "Que contenido veterano cronometrar, posicion y vista previa de 10 segundos.",
    TIMER_DUNGEON = "Mazmorras de grupo",
    TIMER_DUNGEON_TT = "Mazmorras veterano de 4. Empieza en el primer combate.",
    TIMER_TRIAL = "Pruebas",
    TIMER_TRIAL_TT = "Pruebas veterano. Empieza al abrir la puerta.",
    TIMER_ARENA = "Arenas",
    TIMER_ARENA_TT = "Arenas veterano (DSA, Maelstrom, Rosalnegro, Vateshran).",
    TIMER_GOAL = "Mostrar limite",
    TIMER_GOAL_TT = "Anade el tiempo oficial de speedrun veterano: 8:12 / 20:00. Rojo si te pasas.",
    TIMER_X = "Desplazamiento X",
    TIMER_X_TT = "0 = centro. Rango ±900 hasta el borde.",
    TIMER_Y = "Desplazamiento Y",
    TIMER_Y_TT = "0 = reticula. Menos = arriba, mas = abajo. ±900 llega arriba y abajo.",
    TIMER_SCALE = "Escala %",
    TIMER_SCALE_TT = "Tamano real del reloj. 100 = por defecto. 40 pequeno, 250 grande.",
    TIMER_PREVIEW = "Vista previa",
    TIMER_PREVIEW_TT = "Muestra el reloj 10 segundos incluso en ciudad, tambien sobre el menu.",
    TIMER_PREVIEW_BTN = "Mostrar 10 s",

    LINK_ENABLE = "Enlace de sets",
    LINK_GROUP = "Siempre chat de grupo",
    LINK_GROUP_TT = "On = grupo/raid. Off = el canal ya abierto. Activado por defecto.",
    LINK_ENABLE_TT = "Mantén R3 en el menú Text Chat. Sin grupo = /say.",
    LINK_SECTION = "Enlace de sets",
    LINK_SECTION_TT = "Sin más opciones. El interruptor está en la primera página.",
    LINK_HELP = "Mantén R3 en Text Chat.",
    LINK_HELP_TT = "Social → Text Chat. Mantén R3 ~0,6s. Sin grupo = /say.",
    LINK_HOLD = "Mantén R3: sets",
    LINK_EMPTY = "No hay sets para enlazar.",
    LINK_TEST = "Insertar ahora",
    LINK_TEST_TT = "Los mismos enlaces en el campo, sin abrir el menú de chat.",
    LINK_TEST_BTN = "Enlazar sets",
}
