TetsuCombatTools = TetsuCombatTools or {}

TetsuCombatTools.L = {
    TITLE = "|cFFD700Tetsu's|r Combat Tools",
    INFO_LABEL = "Info",
    INFO_TT = "HUD de combat manette. Competences, voyant, nourriture et potion, chrono veteran.\nOr / bugs : courrier @Tetsurion.",
    SKILL_ENABLE = "Suivi des competences",
    SKILL_ENABLE_TT = "Dernieres competences de barre et barre de GCD. L'ultime est toujours inclus.",
    SKILL_SECTION = "Suivi des competences",
    SKILL_SECTION_TT = "Bande d'historique, taille, position, visibilite.",
    SKILL_SLOTS = "Emplacements d'historique",
    SKILL_SLOTS_TT = "Nombre de competences recentes. 4-8. Defaut 6.",
    SKILL_SCALE = "Taille des icones %",
    SKILL_SCALE_TT = "Taille des icones d'historique.",
    SKILL_X = "Decalage X",
    SKILL_X_TT = "0 = centre de l'ecran. Moins a gauche, plus a droite.",
    SKILL_Y = "Decalage Y",
    SKILL_Y_TT = "0 = reticule / centre. Defaut 330 au-dessus de la barre. Moins = haut, plus = bas.",
    SKILL_SHOW = "Quand afficher",
    SKILL_SHOW_TT = "Combat = en combat puis masque. Toujours = reste. Apres appui = N secondes apres la derniere competence.",
    SHOW_COMBAT = "En combat seulement",
    SHOW_ALWAYS = "Toujours",
    SHOW_IDLE = "Apres le dernier appui",
    SKILL_HIDE = "Masquer apres (s)",
    SKILL_HIDE_TT = "Apres la fin du combat et apres le dernier appui. Defaut 8.",
    SKILL_BAR = "Icones de skills",
    SKILL_BAR_TT = "Bande d historique. Off = pas d icones; le GCD reste et suit X/Y.",
    SKILL_GCD = "Barre GCD",
    SKILL_GCD_TT = "Barre jaune/rouge. Marche sans icones. Meme X/Y.",
    SKILL_WEAVE = "Cadres de weave",
    SKILL_WEAVE_TT = "Cadre vert si une attaque legere a precede la competence, rouge sinon. Off = cadres simples.",
    SKILL_LA = "Attaques legeres",
    SKILL_LA_TT = "Desactive par defaut. Si active, les attaques legeres d'arme apparaissent. Lourdes, blocage, esquive et synergies exclus.",
    STATUS_ENABLE = "Statut de combat",
    STATUS_ENABLE_TT = "Rouge en combat, vert hors combat. Icone, texte et son de debut sont separes.",
    STATUS_SECTION = "Statut de combat",
    STATUS_SECTION_TT = "Icone, texte et le son joue au debut du combat.",
    STATUS_ICON = "Icone",
    STATUS_ICON_TT = "Active par defaut. Cercle colore au reticule. Position et taille independantes du texte.",
    STATUS_ICON_X = "Icone decalage X",
    STATUS_ICON_X_TT = "0 = centre. Plage ±900 jusqu'au bord.",
    STATUS_ICON_Y = "Icone decalage Y",
    STATUS_ICON_Y_TT = "0 = reticule. Moins = haut, plus = bas.",
    STATUS_ICON_SCALE = "Taille icone %",
    STATUS_ICON_SCALE_TT = "Taille du voyant. Minimum 30.",
    STATUS_ICON_ALPHA = "Opacite icone %",
    STATUS_ICON_ALPHA_TT = "Opacite du voyant. Defaut 50.",
    STATUS_TEXT = "Texte",
    STATUS_TEXT_TT = "Desactive par defaut. Affiche EN COMBAT / HORS COMBAT.",
    STATUS_TEXT_X = "Texte decalage X",
    STATUS_TEXT_X_TT = "0 = centre de l'ecran.",
    STATUS_TEXT_Y = "Texte decalage Y",
    STATUS_TEXT_Y_TT = "Defaut 250 sous le reticule. Moins = haut, plus = bas.",
    STATUS_TEXT_SCALE = "Taille texte %",
    STATUS_TEXT_SCALE_TT = "Taille du texte de combat. 40 petit, 250 grand.",
    STATUS_IN = "EN COMBAT",
    STATUS_OUT = "HORS COMBAT",
    STATUS_SOUND = "Son au debut du combat",
    STATUS_SOUND_TT = "Active par defaut. Seulement a l'entree en combat.",
    STATUS_SOUND_PICK = "Son de debut",
    STATUS_SOUND_PICK_TT = "Son integre du jeu. Pas de fichiers perso.",
    SOUND_DUEL = "Debut de duel",
    SOUND_ALERT = "Alerte",
    SOUND_QUEST = "Tick de quete",
    SOUND_NOTIFY = "Notification",
    SOUND_DISCOVER = "Objectif trouve",
    CONS_ENABLE = "Consommables",
    CONS_ENABLE_TT = "Deux emplacements : nourriture et potion. Icone + temps restant.",
    CONS_SECTION = "Consommables",
    CONS_SECTION_TT = "Chronos nourriture et potion.",
    CONS_X = "Decalage X",
    CONS_X_TT = "0 = centre de l'ecran.",
    CONS_Y = "Decalage Y",
    CONS_Y_TT = "0 = reticule. Defaut 220 au-dessus de la barre.",
    CONS_SCALE = "Echelle %",
    CONS_SCALE_TT = "Icone et texte du chrono ensemble. 40 petit, 250 grand.",
    CONS_SHOW_FOOD = "Afficher la nourriture",
    CONS_SHOW_FOOD_TT = "Off = cacher l'emplacement nourriture.",
    CONS_SHOW_POT = "Afficher la potion",
    CONS_SHOW_POT_TT = "Off = cacher l'emplacement potion.",
    CONS_FOOD_WARN = "Alerte nourriture (min)",
    CONS_FOOD_WARN_TT = "Le chrono passe au jaune quand il reste autant de minutes. Defaut 5.",
    CONS_POT_WARN = "Alerte potion (s)",
    CONS_POT_WARN_TT = "Le chrono passe au jaune quand il reste autant de secondes. Defaut 10.",
    CONS_POT_COMBAT = "Potion seulement en combat",
    CONS_POT_COMBAT_TT = "Cache la potion hors combat. La nourriture reste.",
    CONS_FOOD_SOUND = "Son fin de nourriture",
    CONS_FOOD_SOUND_TT = "Desactive par defaut. Une fois quand le buff disparait.",
    CONS_POT_SOUND = "Son fin de potion",
    CONS_POT_SOUND_TT = "Desactive par defaut. Meme son que la nourriture.",
    CONS_END_SOUND = "Son de fin",
    CONS_END_SOUND_TT = "Un son integre pour la fin de nourriture et de potion.",
    CONS_MSG = "Texte de fin en instance",
    CONS_MSG_TT = "Ligne courte quand nourriture ou potion se termine. Donjon / epreuve / arene / archive / JcJ seulement.",
    CONS_MSG_FOOD_ON = "Texte fin de nourriture",
    CONS_MSG_FOOD_ENTER = "Texte a l'entree",
    CONS_MSG_FOOD_ENTER_TT = "Active par defaut. 10s « Pas de nourriture » en entrant en donjon / epreuve / arene / archive sans nourriture.",

    CONS_MSG_FOOD_ON_TT = "On = Nourriture terminee en instance pendant 60 secondes.",
    CONS_MSG_POT_ON = "Texte fin de potion",
    CONS_MSG_POT_ON_TT = "On = Potion terminee. Meme X que la nourriture, une ligne plus bas.",
    CONS_MSG_X = "Texte decalage X",
    CONS_MSG_X_TT = "X de la ligne nourriture. La potion utilise le meme X.",
    CONS_MSG_Y = "Texte decalage Y",
    CONS_MSG_Y_TT = "Y de la ligne nourriture. Potion une ligne plus bas. 0 = reticule.",
    CONS_MSG_SCALE = "Taille texte %",
    CONS_MSG_SCALE_TT = "Taille du texte d'alerte de fin.",
    CONS_MSG_FOOD = "Nourriture terminee",
    CONS_MSG_FOOD_MISS = "Pas de nourriture",
    CONS_MSG_POT = "Potion terminee",
    CONS_MSG_BOTH = "Nourriture et potion terminees",
    CONS_PREVIEW = "Apercu",
    CONS_PREVIEW_TT = "Montre des chronos factices, le son et le texte pendant 8 secondes.",
    CONS_PREVIEW_BTN = "Montrer 8 s",
    TIMER_ENABLE = "Chrono de run",
    TIMER_ENABLE_TT = "Desactive par defaut. Veteran seulement. Donjon au premier combat, epreuve/arene a l'ouverture de la porte.",
    TIMER_SECTION = "Chrono de run",
    TIMER_SECTION_TT = "Quel contenu veteran chronometrer, position et apercu 10 secondes.",
    TIMER_DUNGEON = "Donjons de groupe",
    TIMER_DUNGEON_TT = "Donjons veteran 4 joueurs. Demarre au premier combat.",
    TIMER_TRIAL = "Epreuves",
    TIMER_TRIAL_TT = "Epreuves veteran. Demarre a l'ouverture de la porte.",
    TIMER_ARENA = "Arenes",
    TIMER_ARENA_TT = "Arenes veteran (DSA, Maelstrom, Ronce noire, Vateshran).",
    TIMER_GOAL = "Afficher la limite",
    TIMER_GOAL_TT = "Ajoute le temps officiel speedrun veteran : 8:12 / 20:00. Rouge si depasse.",
    TIMER_X = "Decalage X",
    TIMER_X_TT = "0 = centre. Plage ±900 jusqu'au bord.",
    TIMER_Y = "Decalage Y",
    TIMER_Y_TT = "0 = reticule. Moins = haut, plus = bas. ±900 jusqu'en haut et en bas.",
    TIMER_SCALE = "Echelle %",
    TIMER_SCALE_TT = "Taille reelle du chrono. 100 = defaut. 40 petit, 250 grand.",
    TIMER_PREVIEW = "Apercu",
    TIMER_PREVIEW_TT = "Affiche le chrono 10 secondes meme en ville, y compris sur le menu.",
    TIMER_PREVIEW_BTN = "Montrer 10 s",

    LINK_ENABLE = "Lien des sets",
    LINK_GROUP = "Toujours le chat de groupe",
    LINK_GROUP_TT = "On = canal groupe/raid. Off = canal deja ouvert. Active par defaut.",
    LINK_ENABLE_TT = "Maintenir R3 dans le menu Text Chat. Hors groupe = /say.",
    LINK_SECTION = "Lien des sets",
    LINK_SECTION_TT = "Pas d autres options. Interrupteur en premiere page.",
    LINK_HELP = "Maintenir R3 dans Text Chat.",
    LINK_HELP_TT = "Social → Text Chat. Maintenir R3 ~0,6s. Hors groupe = /say.",
    LINK_HOLD = "Maintenir R3 : sets",
    LINK_EMPTY = "Aucun set a lier.",
    LINK_TEST = "Inserer maintenant",
    LINK_TEST_TT = "Meme liens dans le champ, sans ouvrir le menu chat.",
    LINK_TEST_BTN = "Lier les sets",
}
