--[[
-------------------------------------------------------------------------------
-- Advanced Nameplates
-------------------------------------------------------------------------------
-- Original Addon by: Tierney11290 (Stratejacket), released in 2017
-- License: MIT License
--
-- Current Maintainer: Sharlikran
-- First upload: 2020-03-07
--
-- This project was revived and continued by the current maintainer with
-- permission inferred from the original author's ESOUI project page,
-- in accordance with community guidelines.
--
-------------------------------------------------------------------------------
-- License Terms:
--
-- Permission is hereby granted, free of charge, to any person obtaining a copy
-- of this software and associated documentation files (the "Software"), to deal
-- in the Software without restriction, including without limitation the rights
-- to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-- copies of the Software, and to permit persons to whom the Software is
-- furnished to do so, subject to the following conditions:
--
-- The above copyright notice and this permission notice shall be included in
-- all copies or substantial portions of the Software.
--
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-- AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-- LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-- OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
-- THE SOFTWARE.
-------------------------------------------------------------------------------
]]
ZO_CreateStringId("ANP_Options_Header", "Advanced Nameplates Options")
ZO_CreateStringId("ANP_Font_Size_Desc", "Font Size")
ZO_CreateStringId("ANP_Font_Size_Tip", "Move the slider to change the text size")
ZO_CreateStringId("ANP_Font_Style_Desc", "Font Style")
ZO_CreateStringId("ANP_Font_Style_Tip", "Changes the style of the text.")
ZO_CreateStringId("ANP_Font_Keyboard_Desc", "Keyboard Font")
ZO_CreateStringId("ANP_Font_Keyboard_Tip", "Select the Font for Keyboard Mode.")
ZO_CreateStringId("ANP_Font_Gamepad_Desc", "Gamepad Font")
ZO_CreateStringId("ANP_Font_Gamepad_Tip", "Select the Font for Gamepad Mode.")
