FurnishThemAllData_FSets_CraglornMulticulturalParlorPack = {
    name = "Craglorn Multicultural Parlor Pack",
    source = "Furnishing Sets",
    collection = {
        [1] = {
            { name = "Orcish Coffer, Bolted" },
            { name = "Painting of Autumn, Bolted" },
            { name = "Plaque, Bordered Deer Antlers" },
            { name = "Redguard Amphora, Gilded" },
            { name = "Redguard Bench, Padded" },
            { name = "Redguard Bookcase, Arched" },
            { name = "Redguard Bowl, Hanging Star" },
            { name = "Redguard Chair, Starry" },
            { name = "Redguard Chandelier, Polished" },
            { name = "Redguard Couch, Bolted" },
            { name = "Redguard Couch, Slatted" },
            { name = "Redguard Desk, Bolted" },
            { name = "Redguard End Table, Oasis" },
            { name = "Redguard Footlocker, Braced" },
            { name = "Redguard Footstool, Starry" },
            { name = "Redguard Mat, Desert" },
            { name = "Redguard Mat, Desert Sun" },
            { name = "Redguard Nightstand, Sturdy" },
            { name = "Redguard Sconce, Polished" },
            { name = "Redguard Shelf, Bolted" },
            { name = "Redguard Stool, Starry" },
            { name = "Redguard Tapestry, Oasis" },
            { name = "Redguard Vessel, Gilded" },
            { name = "Redguard Wardrobe, Sturdy" },
        },
    },
}
