FurnishThemAllData_FSets_IslandAssortmentHouseholdPack = {
    name = "Island Assortment Household Pack",
    source = "Furnishing Sets",
    collection = {
        [1] = {
            { name = "Argonian Bowl, Serving" },
            { name = "Argonian Bowl, Wooden" },
            { name = "Argonian Cup, Bordered" },
            { name = "Argonian Mortar and Pestle, Bone" },
            { name = "Argonian Mug, Tooth" },
            { name = "Argonian Pot, Ritual" },
            { name = "Argonian Ramekin, Hardened" },
            { name = "Argonian Tray, Woven" },
            { name = "Argonian Urn, Clawfoot" },
            { name = "Book Row, Long" },
            { name = "Book Stack, Decorative" },
            { name = "Book Stack, Tall" },
            { name = "Bottle, Elixir" },
            { name = "Bottle, Liquor" },
            { name = "Bread, Plain" },
            { name = "Common Barrel, Sealed" },
            { name = "Common Pot, Cooking" },
            { name = "Gaming Die" },
            { name = "Ham, Display" },
            { name = "Letter, Personal" },
            { name = "Radish, Wax" },
            { name = "Rough Barrel, Sturdy" },
            { name = "Rough Rod, Fishing" },
            { name = "Sack of Beans" },
            { name = "Sack of Grain" },
            { name = "Vial, Delicate" },
        },
    },
}
