FurnishThemAllData_FSets_TreesOfTamrielGardenPack = {
    name = "Trees of Tamriel Garden Pack",
    source = "Furnishing Sets",
    collection = {
        [1] = {
            { name = "Bush, Dense Forest" },
            { name = "Bush, Flowering Scrub" },
            { name = "Bush, Green Forest" },
            { name = "Bush, Mountain Scrub" },
            { name = "Bush, Red Berry" },
            { name = "Flowers, Golden Prairie" },
            { name = "Flowers, Violet Prairie" },
            { name = "Plant, Forest Sprig" },
            { name = "Plants, Dense Underbrush" },
            { name = "Plants, Dry Underbrush" },
            { name = "Plants, Sparse Underbrush" },
            { name = "Saplings, Autumn Cluster" },
            { name = "Saplings, Fragile Autumn Birch" },
            { name = "Shrub, Autumn Forest" },
            { name = "Shrub, Dense Forest" },
            { name = "Shrub, Sparse Green" },
            { name = "Topiary, Sparse" },
            { name = "Tree, Autumn Maple" },
            { name = "Tree, Strong Maple" },
            { name = "Tree, Young Green Birch" },
            { name = "Tree, Young Healthy Birch" },
            { name = "Trees, Fragile Autumn Birch" },
            { name = "Trees, Young Autumn Birch" },
        },
    },
}
