ZO_CreateStringId("SI_ENCHANT_QUALITY_MENU_ITEM_QUALITY_TEXT","Texto de calidad del artículo")
ZO_CreateStringId("SI_ENCHANT_QUALITY_MENU_ITEM_QUALITY_TOOLTIP","Muestra el texto de la calidad del elemento.")
ZO_CreateStringId("SI_ENCHANT_QUALITY_MENU_ENCHANT_QUALITY_TEXT","Texto de la calidad del encantamiento")
ZO_CreateStringId("SI_ENCHANT_QUALITY_MENU_ENCHANT_QUALITY_TOOLTIP","Muestra el texto de la calidad del encantamiento.")
ZO_CreateStringId("SI_ENCHANT_QUALITY_MENU_ENCHANT_COLOR_TEXT","Color de la calidad del encantamiento")
ZO_CreateStringId("SI_ENCHANT_QUALITY_MENU_ENCHANT_COLOR_TOOLTIP","Usa el color de la calidad del encantamiento.")
ZO_CreateStringId("SI_ENCHANT_QUALITY_TOOLTIP_ITEM_NAME", "<<1{%s/%s/%s/%s}>> <<1>>")
ZO_CreateStringId("SI_ENCHANT_QUALITY_ENCHANTED_NAME", "Encantamiento <<1{%s/%s/%s/%s}>> de <<1>> ")
ZO_CreateStringId("SI_ENCHANT_QUALITY_ENCHANTED_NAME_MULTI_EFFECT", "Encantamiento %s multi-efecto")
