local mkstr = ZO_CreateStringId
local SI = Alchemist.SI

-- output texts
mkstr(SI.NO_DISCOVERIES_AVAILABLE,          "Keine Entdeckungen m\195\182glich.")
mkstr(SI.COMBINATIONS_AVAILABLE,            "%d Kombination(en) verf\195\188gbar!")
mkstr(SI.COMBINE_THE_FOLLOWING,             "Kombiniere folgendes:")
mkstr(SI.TO_GET_THE_FOLLOWING_DISCOVERIES,  ".. um folgende Entdeckung(en) zu erzielen:")

-- reagents
mkstr(SI.BEETLE_SCUTTLE,    "Käferbeine")
mkstr(SI.BLESSED_THISTLE,   "Benediktenkraut")
mkstr(SI.BLUE_ENTOLOMA,     "Blauer Glöckling")
mkstr(SI.BUGLOSS,           "Wolfsauge")
mkstr(SI.BUTTERFLY_WING,    "Schmetterlingsflügel")
mkstr(SI.CLAM_GALL,         "Muschelgalle")
mkstr(SI.COLUMBINE,         "Akelei")
mkstr(SI.CORN_FLOWER,       "Kornblume")
mkstr(SI.DRAGON_BILE,       "Drachengalle")
mkstr(SI.DRAGON_BLOOD,      "Drachenblut")
mkstr(SI.DRAGONTHORN,       "Drachendorn")
mkstr(SI.EMETIC_RUSSULA,    "Brechtäubling")
mkstr(SI.FLESHFLY_LARVA,    "Fleischfliegenlarve")
mkstr(SI.IMP_STOOL,         "Koboldschemel")
mkstr(SI.LADYS_SMOCK,       "Wiesenschaumkraut")
mkstr(SI.LUMINOUS_RUSSULA,  "Leuchttäubling")
mkstr(SI.MOUNTAIN_FLOWER,   "Bergblume")
mkstr(SI.MUDCRAB_CHITIN,    "Schlammkrabbenchitin")
mkstr(SI.NAMIRAS_ROT,       "Namiras Fäulnis")
mkstr(SI.NIGHTSHADE,        "Nachtschatten")
mkstr(SI.NIRNROOT,          "Nirnwurz")
mkstr(SI.POWDERED_MOP,      "Pulverisiertes Perlmutt")
mkstr(SI.SCRIB_JELLY,       "Skribgelee")
mkstr(SI.SPIDER_EGG,        "Spinnenei")
mkstr(SI.STINKHORN,         "Stinkmorchel")
mkstr(SI.TORCHBUG_THORAX,   "Fackelkäferpanzer")
mkstr(SI.VIOLET_COPRINUS,   "Violetter Tintling")
mkstr(SI.WATER_HYACINTH,    "Wasserhyazinthe")
mkstr(SI.WHITE_CAP,         "Weißkappe")
mkstr(SI.WORMWOOD,          "Wermut")
mkstr(SI.CRIMSON_NIRNROOT,  "Purpurne Nirnwurz")
mkstr(SI.VILE_COAGULANT,    "Boshafter Verdicker")
mkstr(SI.CHAURUS_EGG,       "Chaurusei")

-- traits
mkstr(SI.BREACH,                "Bruch")
mkstr(SI.COWARDICE,             "Feigheit")
mkstr(SI.DEFILE,                "Schänden")
mkstr(SI.DETECTION,             "Detektion")
mkstr(SI.ENERVATION,            "Schwäche")
mkstr(SI.ENTRAPMENT,            "Einfangen")
mkstr(SI.FRACTURE,              "Fraktur")
mkstr(SI.GRADUAL_RAVAGE_HEALTH, "Langsame Lebensverwüstung")
mkstr(SI.HEROISM,               "Heldentum")
mkstr(SI.HINDRANCE,             "Einschränken")
mkstr(SI.INCREASE_ARMOR,        "Erhöht Rüstung")
mkstr(SI.INCREASE_SPELL_POWER,  "Erhöht Magiekraft")
mkstr(SI.INCREASE_SPELL_RESIST, "Erhöht Magieresistenz")
mkstr(SI.INCREASE_WEAPON_POWER, "Erhöht Waffenkraft")
mkstr(SI.INVISIBLE,             "Unsichtbarkeit")
mkstr(SI.LINGERING_HEALTH,      "Beständige Heilung")
mkstr(SI.LOWER_SPELL_POWER,     "Verringert Magiekraft")
mkstr(SI.MAIM,                  "Verkrüppeln")
mkstr(SI.PROTECTION,            "Schutz")
mkstr(SI.RAVAGE_HEALTH,         "Lebensverwüstung")
mkstr(SI.RAVAGE_MAGICKA,        "Magickaverwüstung")
mkstr(SI.RAVAGE_STAMINA,        "Ausdauerverwüstung")
mkstr(SI.RESTORE_HEALTH,        "Leben wiederherstellen")
mkstr(SI.RESTORE_MAGICKA,       "Magicka wiederherstellen")
mkstr(SI.RESTORE_STAMINA,       "Ausdauer wiederherstellen")
mkstr(SI.SPEED,                 "Tempo")
mkstr(SI.SPELL_CRIT,            "Kritische Magietreffer")
mkstr(SI.UNCERTAINTY,           "Ungewissheit")
mkstr(SI.UNSTOPPABLE,           "Sicherer Stand")
mkstr(SI.VITALITY,              "Vitalität")
mkstr(SI.VULNERABILITY,         "Verwundbarkeit")
mkstr(SI.WEAPON_CRIT,           "Kritische Waffentreffer")
mkstr(SI.TIMIDITY,              "Scheu")