local t={
name="FavOptions",
savedVars=nil
}
local f={
chatsize=nil,
chatcolors={
[CHAT_CATEGORY_SAY]={},
[CHAT_CATEGORY_YELL]={},
[CHAT_CATEGORY_WHISPER_INCOMING]={},
[CHAT_CATEGORY_WHISPER_OUTGOING]={},
[CHAT_CATEGORY_PARTY]={},
[CHAT_CATEGORY_ZONE]={},
[CHAT_CATEGORY_ZONE_ENGLISH]={},
[CHAT_CATEGORY_ZONE_FRENCH]={},
[CHAT_CATEGORY_ZONE_GERMAN]={},
[CHAT_CATEGORY_ZONE_JAPANESE]={},
[CHAT_CATEGORY_ZONE_RUSSIAN]={},
[CHAT_CATEGORY_ZONE_SPANISH]={},
[CHAT_CATEGORY_ZONE_CHINESE_S]={},
[CHAT_CATEGORY_MONSTER_SAY]={},
[CHAT_CATEGORY_EMOTE]={},
[CHAT_CATEGORY_SYSTEM]={},
[CHAT_CATEGORY_GUILD_1]={},
[CHAT_CATEGORY_OFFICER_1]={},
[CHAT_CATEGORY_GUILD_2]={},
[CHAT_CATEGORY_OFFICER_2]={},
[CHAT_CATEGORY_GUILD_3]={},
[CHAT_CATEGORY_OFFICER_3]={},
[CHAT_CATEGORY_GUILD_4]={},
[CHAT_CATEGORY_OFFICER_4]={},
[CHAT_CATEGORY_GUILD_5]={},
[CHAT_CATEGORY_OFFICER_5]={},
},
choices={
[SETTING_PANEL_AUDIO]={
[SETTING_TYPE_SUBTITLES]={
[SUBTITLE_SETTING_ENABLED_FOR_NPCS]={OPTIONS_CHECKBOX},
},
},
[SETTING_PANEL_GAMEPLAY]={
[SETTING_TYPE_GAMEPAD]={
[GAMEPAD_SETTING_GAMEPAD_TEMPLATE]={OPTIONS_FINITE_LIST},
},
[SETTING_TYPE_IN_WORLD]={
[IN_WORLD_UI_SETTING_HIDE_POLYMORPH_HELM]={OPTIONS_CHECKBOX},
[IN_WORLD_UI_SETTING_HIDE_MOUNT_STAMINA_UPGRADE]={OPTIONS_CHECKBOX},
[IN_WORLD_UI_SETTING_HIDE_MOUNT_SPEED_UPGRADE]={OPTIONS_CHECKBOX},
[IN_WORLD_UI_SETTING_HIDE_MOUNT_INVENTORY_UPGRADE]={OPTIONS_CHECKBOX},
[IN_WORLD_UI_SETTING_COMPANION_REACTION_FREQUENCY]={OPTIONS_FINITE_LIST},
[IN_WORLD_UI_SETTING_COMPANION_PASSENGER_PREFERENCE]={OPTIONS_FINITE_LIST},
[IN_WORLD_UI_SETTING_DEFAULT_SOUL_GEM]={OPTIONS_FINITE_LIST},
},
[SETTING_TYPE_COMBAT]={
[COMBAT_SETTING_PREVENT_ATTACKING_INNOCENTS]={OPTIONS_CHECKBOX},
[COMBAT_SETTING_QUICK_CAST_GROUND_ABILITIES]={OPTIONS_FINITE_LIST},
[COMBAT_SETTING_ALLOW_COMPANION_AUTO_ULTIMATE]={OPTIONS_CHECKBOX},
},
[SETTING_TYPE_LOOT]={
[LOOT_SETTING_AOE_LOOT]={OPTIONS_CHECKBOX},
[LOOT_SETTING_AUTO_LOOT]={OPTIONS_CHECKBOX},
[LOOT_SETTING_AUTO_LOOT_STOLEN]={OPTIONS_CHECKBOX},
[LOOT_SETTING_PREVENT_STEALING_PLACED]={OPTIONS_CHECKBOX},
[LOOT_SETTING_AUTO_ADD_TO_CRAFT_BAG]={OPTIONS_CHECKBOX},
[LOOT_SETTING_LOOT_HISTORY]={OPTIONS_CHECKBOX},
},
[SETTING_TYPE_TUTORIAL]={
[TUTORIAL_ENABLED_SETTING_ID]={OPTIONS_CHECKBOX},
},
},
[SETTING_PANEL_CAMERA]={
[SETTING_TYPE_CAMERA]={
[CAMERA_SETTING_FIRST_PERSON_FIELD_OF_VIEW]={OPTIONS_SLIDER},
[CAMERA_SETTING_FIRST_PERSON_HEAD_BOB]={OPTIONS_SLIDER},
[CAMERA_SETTING_THIRD_PERSON_FIELD_OF_VIEW]={OPTIONS_SLIDER},
[CAMERA_SETTING_THIRD_PERSON_HORIZONTAL_POSITION_MULTIPLIER]={OPTIONS_SLIDER},
[CAMERA_SETTING_THIRD_PERSON_HORIZONTAL_OFFSET]={OPTIONS_SLIDER},
[CAMERA_SETTING_THIRD_PERSON_VERTICAL_OFFSET]={OPTIONS_SLIDER},
},
},
[SETTING_PANEL_INTERFACE]={
[SETTING_TYPE_UI]={
[UI_SETTING_PRIMARY_PLAYER_NAME_GAMEPAD]={OPTIONS_FINITE_LIST},
[UI_SETTING_SHOW_RAID_LIVES]={OPTIONS_FINITE_LIST},
[UI_SETTING_SHOW_HOUSE_TRACKER]={OPTIONS_CHECKBOX},
[UI_SETTING_SHOW_QUEST_TRACKER]={OPTIONS_CHECKBOX},
[UI_SETTING_AUTOMATIC_QUEST_TRACKING]={OPTIONS_CHECKBOX},
[UI_SETTING_SHOW_QUEST_BESTOWER_INDICATORS]={OPTIONS_CHECKBOX},
[UI_SETTING_COMPASS_QUEST_GIVERS]={OPTIONS_CHECKBOX},
[UI_SETTING_COMPASS_ACTIVE_QUESTS]={OPTIONS_FINITE_LIST},
[UI_SETTING_COMPASS_COMPANION]={OPTIONS_CHECKBOX},
[UI_SETTING_COMPASS_TARGET_MARKERS]={OPTIONS_CHECKBOX},
[UI_SETTING_SHOW_WEAPON_INDICATOR]={OPTIONS_CHECKBOX},
[UI_SETTING_SHOW_ARMOR_INDICATOR]={OPTIONS_CHECKBOX},
},
[SETTING_TYPE_CHAT_BUBBLE]={
[CHAT_BUBBLE_SETTING_ENABLED]={OPTIONS_CHECKBOX},
[CHAT_BUBBLE_SETTING_SPEED_MODIFIER]={OPTIONS_SLIDER},
[CHAT_BUBBLE_SETTING_ENABLED_ONLY_FROM_CONTACTS]={OPTIONS_CHECKBOX},
[CHAT_BUBBLE_SETTING_ENABLED_FOR_LOCAL_PLAYER]={OPTIONS_CHECKBOX},
},
},
[SETTING_PANEL_NAMEPLATES]={
[SETTING_TYPE_NAMEPLATES]={
[NAMEPLATE_TYPE_ALL_NAMEPLATES]={OPTIONS_CHECKBOX},
[NAMEPLATE_TYPE_SHOW_PLAYER_TITLES]={OPTIONS_CHECKBOX},
[NAMEPLATE_TYPE_SHOW_PLAYER_GUILDS]={OPTIONS_CHECKBOX},
[NAMEPLATE_TYPE_PLAYER_NAMEPLATE]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_PLAYER_NAMEPLATE_HIGHLIGHT]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_GROUP_MEMBER_NAMEPLATES]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_GROUP_MEMBER_NAMEPLATES_HIGHLIGHT]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_FRIENDLY_NPC_NAMEPLATES]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_FRIENDLY_NPC_NAMEPLATES_HIGHLIGHT]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_FRIENDLY_PLAYER_NAMEPLATES]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_FRIENDLY_PLAYER_NAMEPLATES_HIGHLIGHT]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_NEUTRAL_NPC_NAMEPLATES]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_NEUTRAL_NPC_NAMEPLATES_HIGHLIGHT]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_ENEMY_NPC_NAMEPLATES]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_ENEMY_NPC_NAMEPLATES_HIGHLIGHT]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_ENEMY_PLAYER_NAMEPLATES]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_ENEMY_PLAYER_NAMEPLATES_HIGHLIGHT]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_ALL_HEALTHBARS]={OPTIONS_CHECKBOX},
[NAMEPLATE_TYPE_HEALTHBAR_ALIGNMENT]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_HEALTHBAR_CHASE_BAR]={OPTIONS_CHECKBOX},
[NAMEPLATE_TYPE_HEALTHBAR_FRAME_BORDER]={OPTIONS_CHECKBOX},
[NAMEPLATE_TYPE_PLAYER_HEALTHBAR]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_PLAYER_HEALTHBAR_HIGHLIGHT]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_GROUP_MEMBER_HEALTHBARS]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_GROUP_MEMBER_HEALTHBARS_HIGHLIGHT]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_FRIENDLY_NPC_HEALTHBARS]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_FRIENDLY_NPC_HEALTHBARS_HIGHLIGHT]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_FRIENDLY_PLAYER_HEALTHBARS]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_FRIENDLY_PLAYER_HEALTHBARS_HIGHLIGHT]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_NEUTRAL_NPC_HEALTHBARS]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_NEUTRAL_NPC_HEALTHBARS_HIGHLIGHT]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_ENEMY_NPC_HEALTHBARS]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_ENEMY_NPC_HEALTHBARS_HIGHLIGHT]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_ENEMY_PLAYER_HEALTHBARS]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_ENEMY_PLAYER_HEALTHBARS_HIGHLIGHT]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_ALLIANCE_INDICATORS]={OPTIONS_FINITE_LIST},
[NAMEPLATE_TYPE_GROUP_INDICATORS]={OPTIONS_CHECKBOX},
[NAMEPLATE_TYPE_TARGET_MARKERS]={OPTIONS_CHECKBOX},
[NAMEPLATE_TYPE_RESURRECT_INDICATORS]={OPTIONS_CHECKBOX},
[NAMEPLATE_TYPE_FOLLOWER_INDICATORS]={OPTIONS_CHECKBOX},
},
[SETTING_TYPE_IN_WORLD]={
[IN_WORLD_UI_SETTING_TARGET_MARKER_SIZE]={OPTIONS_SLIDER},
[IN_WORLD_UI_SETTING_GLOW_THICKNESS]={OPTIONS_SLIDER},
[IN_WORLD_UI_SETTING_TARGET_GLOW_ENABLED]={OPTIONS_CHECKBOX},
[IN_WORLD_UI_SETTING_TARGET_GLOW_INTENSITY]={OPTIONS_SLIDER},
[IN_WORLD_UI_SETTING_INTERACTABLE_GLOW_ENABLED]={OPTIONS_CHECKBOX},
[IN_WORLD_UI_SETTING_INTERACTABLE_GLOW_INTENSITY]={OPTIONS_SLIDER},
},
},
[SETTING_PANEL_SOCIAL]={
[SETTING_TYPE_LANGUAGE]={
[LANGUAGE_SETTING_USE_PROFANITY_FILTER]={OPTIONS_CHECKBOX},
},
[SETTING_TYPE_UI]={
[UI_SETTING_GAMEPAD_CHAT_HUD_ENABLED]={OPTIONS_CHECKBOX},
[UI_SETTING_SHOW_LEADERBOARD_NOTIFICATIONS]={OPTIONS_CHECKBOX},
[UI_SETTING_AUTO_DECLINE_DUEL_INVITES]={OPTIONS_CHECKBOX},
[UI_SETTING_AUTO_DECLINE_TRIBUTE_INVITES]={OPTIONS_CHECKBOX},
[UI_SETTING_SHOW_AVA_NOTIFICATIONS]={OPTIONS_FINITE_LIST},
[UI_SETTING_SHOW_GUILD_KEEP_NOTICES]={OPTIONS_FINITE_LIST},
[UI_SETTING_SHOW_PVP_KILL_FEED_NOTIFICATIONS]={OPTIONS_CHECKBOX},
},
},
[SETTING_PANEL_COMBAT]={
[SETTING_TYPE_UI]={
[UI_SETTING_SHOW_ACTION_BAR]={OPTIONS_FINITE_LIST},
[UI_SETTING_SHOW_ACTION_BAR_TIMERS]={OPTIONS_CHECKBOX},
[UI_SETTING_SHOW_ACTION_BAR_BACK_ROW]={OPTIONS_CHECKBOX},
[UI_SETTING_SHOW_RESOURCE_BARS]={OPTIONS_FINITE_LIST},
[UI_SETTING_RESOURCE_NUMBERS]={OPTIONS_FINITE_LIST},
[UI_SETTING_ULTIMATE_NUMBER]={OPTIONS_CHECKBOX},
},
[SETTING_TYPE_ACTIVE_COMBAT_TIP]={
[0]={OPTIONS_FINITE_LIST},
},
[SETTING_TYPE_BUFFS]={
[BUFFS_SETTING_ALL_ENABLED]={OPTIONS_FINITE_LIST},
[BUFFS_SETTING_BUFFS_ENABLED]={OPTIONS_CHECKBOX},
[BUFFS_SETTING_BUFFS_ENABLED_FOR_SELF]={OPTIONS_CHECKBOX},
[BUFFS_SETTING_DEBUFFS_ENABLED_FOR_SELF]={OPTIONS_CHECKBOX},
[BUFFS_SETTING_DEBUFFS_ENABLED_FOR_TARGET]={OPTIONS_CHECKBOX},
[BUFFS_SETTING_DEBUFFS_ENABLED_FOR_TARGET_FROM_OTHERS]={OPTIONS_CHECKBOX},
[BUFFS_SETTING_LONG_EFFECTS]={OPTIONS_CHECKBOX},
[BUFFS_SETTING_PERMANENT_EFFECTS]={OPTIONS_CHECKBOX},
},
},
[SETTING_PANEL_ACCESSIBILITY]={
[SETTING_TYPE_ACCESSIBILITY]={
[ACCESSIBILITY_SETTING_GAMEPAD_AIM_ASSIST_INTENSITY]={OPTIONS_SLIDER},
},
},
},
}
local l=false
local s="|t24:24:/esoui/art/menubar/gamepad/gp_playermenu_icon_character.dds|t "
local h="|cff6666"
local r="|c66ff66"
local function o()
if l then return end
l=true
local u=false
for e=1,GAMEPAD_OPTIONS.optionsList:GetNumEntries()do
local a=GAMEPAD_OPTIONS.optionsList:GetEntryData(e)
local e=a.panel
local c=a.system
local l=a.settingId
local e=t.savedVars.choices[e]
local e=e and e[c]
local t=e and e[l]
if t then
local o=a.text
local i=a.gamepadTextOverride
local n=a.consoleTextOverride
local e=""
if n then e=n
elseif i then e=i
elseif o then e=o
end
local m=e
if type(e)=="number"then e=GetString(e)end
if e:find(s,1,true)then e=e:gsub(s,"")end
if e:find(h,1,true)then e=e:gsub(h,"")end
if e:find(r,1,true)then e=e:gsub(r,"")end
if e:find("|r",1,true)then e=e:gsub("|r","")end
if t[2]~=nil and t[1]~=OPTIONS_SLIDER then
if t[2]==GetSetting(c,l)then
e=r..e.."|r"
else
e=h..e.."|r"
end
end
e=s..e
if e~=m then
if n then a.consoleTextOverride=e
elseif i then a.gamepadTextOverride=e
elseif o then a.text=e
end
u=true
end
end
end
if u then
zo_callLater(function()GAMEPAD_OPTIONS.optionsList:Commit()end,1)
end
l=false
end
local e=false
local i=nil
local a=nil
local function s(n,t)
if t==SCENE_SHOWING then
if not e then
i=ZO_HorizontalScrollList_Gamepad.MoveLeft
ZO_HorizontalScrollList_Gamepad.MoveLeft=function(e)
i(e)
zo_callLater(o,50)
end
a=ZO_HorizontalScrollList_Gamepad.MoveRight
ZO_HorizontalScrollList_Gamepad.MoveRight=function(t)
a(t)
zo_callLater(o,50)
end
e=true
end
elseif t==SCENE_HIDING and e then
ZO_HorizontalScrollList_Gamepad.MoveLeft=i
ZO_HorizontalScrollList_Gamepad.MoveRight=a
e=false
end
end
local function n()
local i=false
for e=1,GAMEPAD_OPTIONS.optionsList:GetNumEntries()do
local e=GAMEPAD_OPTIONS.optionsList:GetEntryData(e)
local n=e.panel
local o=e.system
local a=e.settingId
local e=t.savedVars.choices[n]
local e=e and e[o]
local e=e and e[a]
if e then
local t=GetSetting(o,a)
if e[2]~=t then
e[2]=t
i=true
end
end
end
if i then
zo_callLater(o,10)
end
end
local function i()
local t=GetCVar("language.2")
local e="Store as favorite"
if t~="en"then
e=GetString(SI_COLLECTIBLE_ACTION_ADD_FAVORITE)
end
ZO_Dialogs_RegisterCustomDialog(
"STOREFAV_CONFIRM_DIALOG",{
gamepadInfo={dialogType=GAMEPAD_DIALOGS.BASIC,},
title={text=e,},
mainText={text=SI_DEFAULT_CONFIRM_INTERACTION_MAIN_TEXT},
buttons={{
text=SI_DEFAULT_CONFIRM_INTERACTION_TITLE,
keybind="DIALOG_PRIMARY",
callback=function()
n()
end,
},
{
text=SI_DIALOG_DECLINE,
keybind="DIALOG_NEGATIVE",
callback=function()end,
},
}
}
)
SecurePostHook(ZO_GamepadOptions,"InitializeKeybindStrip",function(t)
table.insert(GAMEPAD_OPTIONS.keybindStripDescriptor,{
alignment=KEYBIND_STRIP_ALIGN_LEFT,
name=e,
keybind="UI_SHORTCUT_QUATERNARY",
callback=function()
ZO_Dialogs_ShowGamepadDialog("STOREFAV_CONFIRM_DIALOG")
end,
visible=function()
local e={
[SETTING_PANEL_AUDIO]=true,
[SETTING_PANEL_GAMEPLAY]=true,
[SETTING_PANEL_INTERFACE]=true,
[SETTING_PANEL_NAMEPLATES]=true,
[SETTING_PANEL_SOCIAL]=true,
[SETTING_PANEL_COMBAT]=true,
}
return e[GAMEPAD_OPTIONS.currentCategory]~=nil
end,
})
end)
end
local function a()
for e,a in pairs(t.savedVars.chatcolors)do
local i,a,o=GetChatCategoryColor(e)
t.savedVars.chatcolors[e]={i,a,o}
end
t.savedVars.chatsize=GetGamepadChatFontSize()
end
local function n()
for e,t in pairs(t.savedVars.chatcolors)do
SetChatCategoryColor(e,unpack(t))
end
if t.savedVars.chatsize then
SetGamepadChatFontSize(t.savedVars.chatsize)
end
end
local function c(h,e)
if e~=t.name then return end
EVENT_MANAGER:UnregisterForEvent(t.name,EVENT_ADD_ON_LOADED)
t.savedVars=ZO_SavedVars:NewAccountWide("FavOptions_SavedVars",1,nil,f)
if UI_SETTING_COMPASS_DISTANCE_TRACKING and not t.savedVars.choices[SETTING_PANEL_INTERFACE][SETTING_TYPE_UI][UI_SETTING_COMPASS_DISTANCE_TRACKING]then t.savedVars.choices[SETTING_PANEL_INTERFACE][SETTING_TYPE_UI][UI_SETTING_COMPASS_DISTANCE_TRACKING]={OPTIONS_CHECKBOX}
end
if not t.savedVars.choices[SETTING_PANEL_CAMERA][SETTING_TYPE_CAMERA][CAMERA_SETTING_THIRD_PERSON_VERTICAL_OFFSET]then t.savedVars.choices[SETTING_PANEL_CAMERA][SETTING_TYPE_CAMERA][CAMERA_SETTING_THIRD_PERSON_VERTICAL_OFFSET]={OPTIONS_SLIDER}
end
if not t.savedVars.chatsize then
a()
else
n()
end
i()
local e=SCENE_MANAGER:GetScene("gamepad_options_panel")
e:RegisterCallback("StateChange",s)
SecurePostHook(ZO_GamepadOptions,"Select",function()
o()
end)
SecurePostHook(ZO_GamepadOptions,"RefreshOptionsList",function()
o()
end)
ZO_PostHook("SetChatCategoryColor",function(o,i,a,e)
t.savedVars.chatcolors[o]={i,a,e}
end)
ZO_PostHook("ResetChatCategoryColorToDefault",function(e)
local a,o,i=GetChatCategoryColor(e)
t.savedVars.chatcolors[e]={a,o,i}
end)
ZO_PostHook("SetGamepadChatFontSize",function(e)
t.savedVars.chatsize=e
end)
ZO_PostHook("ResetChatFontSizeToDefault",function()
local e=GetGamepadChatFontSize()
t.savedVars.chatsize=e
end)
local i=ZO_ChatMenu_Gamepad.AddMessage
function ZO_ChatMenu_Gamepad:AddMessage(t,e,a,o,h,n,s)
local l,u,r=GetChatCategoryColor(e)
if l==0 and u==0 and r==0 then return end
return i(self,t,e,a,o,h,n,s)
end
local i=ZO_GamepadChatSystem.OnFormattedChatMessage
function ZO_GamepadChatSystem:OnFormattedChatMessage(t,e,n,r,s,h,o)
local a,u,l=GetChatCategoryColor(e)
if a==0 and u==0 and l==0 then return end
return i(self,t,e,n,r,s,h,o)
end
end
EVENT_MANAGER:RegisterForEvent(t.name,EVENT_ADD_ON_LOADED,c)
