-- Version 2.92

--[[ Umlauts & special characters list
	ä --> \195\164
	Ä --> \195\132
	ö --> \195\182
	Ö --> \195\150
	ü --> \195\188
	Ü --> \195\156
	ß --> \195\159

   à : \195\160    è : \195\168    ì : \195\172    ò : \195\178    ù : \195\185
   á : \195\161    é : \195\169    í : \195\173    ó : \195\179    ú : \195\186
   â : \195\162    ê : \195\170    î : \195\174    ô : \195\180    û : \195\187
      	 		   ë : \195\171    ï : \195\175
   æ : \195\166    ø : \195\184
   ç : \195\167                                    œ : \197\147
   Ä : \195\132    Ö : \195\150    Ü : \195\156    ß : \195\159
   ä : \195\164    ö : \195\182    ü : \195\188
   ã : \195\163    õ : \195\181  				   \195\177 : \195\177
]]
local mb = MailBuddy
mb.localizationVars.all = {
	--English
    [1] = {
		-- Options menu
        ["options_description"]                  = "Helps you to easily manage your mail recipients and subjects",
        ["options_header1"] 			 		 = "General settings",
        ["options_language"] 					 = "Language",
        ["options_language_tooltip"] 			 = "Choose the language",
        ["options_language_dropdown_selection1"] = "English",
        ["options_language_dropdown_selection2"] = "German",
        ["options_language_dropdown_selection3"] = "French",
        ["options_language_dropdown_selection4"] = "Spanish",
        ["options_language_dropdown_selection5"] = "Italian",
        ["options_language_description1"]		 = "CAUTION: Changing the language/save option will reload the user interface!",
        ["options_savedvariables"]				 = "Save settings",
        ["options_savedvariables_tooltip"]       = "Save the addon settings for all your characters of your account, or single for each character",
        ["options_savedVariables_dropdown_selection1"] = "Each character",
        ["options_savedVariables_dropdown_selection2"] = "Account wide",
        ["options_appearance"]                          = "Appearance",
        ["options_alternative_layout"]                  = "Use alternative layout",
        ["options_alternative_layout_tooltip"]          = "Hide the additional recipient and subject fields left of the mail's 'To' and 'Subject' edit fields. Right click the mail's 'To' or 'Subject' edit field instead to show the recipients/subjects list!",
        ["options_show_alternative_layout_tooltip"]     = "Show alternative layout tooltip",
        ["options_show_alternative_layout_tooltip_tooltip"] = "Show a tooltip with instructions at the standard mail 'To' and 'Subject' edit fields",
        ["options_play_sounds"]                         = "Play sounds",
        ["options_play_sounds_tooltip"]                 = "Play sounds upon showing/hiding MailBuddy, adding/deleting/selecting entries",
        ["options_additional"]                   = "Additional options",
        ["options_toggle_recipients_box_click"]         = "Toggle recipients box vis. on click",
        ["options_toggle_recipients_box_click_tooltip"] = "Only if alternative layout is deactivated:\n\nClick the additional recipient label to toggle the recipients box visibility",
        ["options_toggle_subjects_box_click"]           = "Toggle subjects box vis. on click",
        ["options_toggle_subjects_box_click_tooltip"]   = "Only if alternative layout is deactivated:Click the additional subject label to toggle the subjects box visibility",
        ["options_standard_mail"]                = "Standard mail settings",
        ["options_standard_recipient"]           = "Standard recipient name",
        ["options_standard_recipient_tooltip"]   = "The standard mail recipient name which will be filled in a new mail. Leave it empty if none is wished. Can be @accountname or character name. Attention: Enabling the 'Mail-Brain' for the last recipient will disable this option!",
        ["options_standard_subject"]           = "Standard subject name",
        ["options_standard_subject_tooltip"]   = "The standard mail subject which will be filled in a new mail. Leave it empty if none is wished. Can be 'return', 'Hello' or whatever you want to. Attention: Enabling the 'Mail-Brain' for the last subject will disable this option!",
        ["options_mail_brain"]                   = "Mail-Brain",
        ["options_reuse_recipient"]           = "Re-Use last used recipient name",
        ["options_reuse_recipient_tooltip"]   = "Automatically fill in the last used recipient's name for your next mails",
        ["options_reuse_subject"]           = "Re-Use last used subject text",
        ["options_reuse_subject_tooltip"]   = "Automatically fill in the last used subject for your next mails",
        ["options_reuse_body"]           = "Re-Use last used body text",
        ["options_reuse_body_tooltip"]   = "Automatically fill in the last used body text for your next mails",
        ["options_automatism"]                   = "Automatism",
        ["options_auto_hide_recipients_box"]           = "Autom. hide recipients box",
        ["options_auto_hide_recipients_box_tooltip"]   = "Automatically hide the recipients box if you open the mail send panel/guild roster, and if it was open after your last visit",
        ["options_auto_hide_subjects_box"]           = "Autom. hide subjects box",
        ["options_auto_hide_subjects_box_tooltip"]   = "Automatically hide the subjects box if you open the mail send panel, and if it was open after your last visit",
        ["options_auto_close_recipients_box"]           = "Autom. close recipients box",
        ["options_auto_close_recipients_box_tooltip"]   = "Automatically close the recipients box if you have added/chosen a recipient. This will only apply to the mail send panel, not to the guild roster/friends list!",
        ["options_auto_close_subjects_box"]           = "Autom. close subjects box",
        ["options_auto_close_subjects_box_tooltip"]   = "Automatically close the subjects box if you have added/chosen a subject.",
        ["options_autofocus"]                    = "Automatic focus",
        ["options_auto_focus_recipients_field"]           = "Autom. focus the 'To' field",
        ["options_auto_focus_recipients_field_tooltip"]   = "Automatically focus the mail's 'To' field, if it is empty. This will apply if you click the recipients/subjects lists",
        ["options_auto_focus_subjects_field"]           = "Autom. focus the 'Subject' field",
        ["options_auto_focus_subjects_field_tooltip"]   = "Automatically focus the mail's 'Subject' field, if it is empty. This will apply if you click the recipients/subjects lists",
        ["options_auto_focus_auto_open_recipients_field"]           = "Autom. open recipients list",
        ["options_auto_focus_auto_open_recipients_field_tooltip"]   = "Automatically open the recipients list too.",
        ["options_auto_focus_auto_open_subjects_field"]           = "Autom. open subjects list",
        ["options_auto_focus_auto_open_subjects_field_tooltip"]   = "Automatically open the subjects list too.",
        ["options_auto_focus_body_field"]           = "Autom. focus the 'Body' text box",
        ["options_auto_focus_body_field_tooltip"]   = "Automatically focus the mail's 'Body' field, if it is empty. This will apply if you click the recipients/subjects lists",
        ["options_fonts"]                   = "Fonts",
        ["options_font_recipient_label"]    = "Recipient label font",
        ["options_font_recipients_box"]     = "Recipients box font",
        ["options_font_subject_label"]      = "Subject label font",
        ["options_font_subjects_box"]       = "Subjects box font",
        ["options_font_recipient_label_size"]    = "Font size",
        ["options_font_recipients_box_size"]     = "Font size",
        ["options_font_subject_label_size"]      = "Font size",
        ["options_font_subjects_box_size"]       = "Font size",
        ["options_font_recipient_label_style"]    = "Font style",
        ["options_font_recipients_box_style"]     = "Font style",
        ["options_font_subject_label_style"]      = "Font stylet",
        ["options_font_subjects_box_style"]       = "Font style",
        ["options_font_recipient_label_color"]    = "Font color",
        ["options_font_recipients_box_color"]     = "Font color",
        ["options_font_subject_label_color"]      = "Font color",
        ["options_font_subjects_box_color"]       = "Font color",
		["options_header_sender"]				  = "Sender",
        ["options_show_account_name"]			  = "Show current @account name",
        ["options_show_account_name_tooltip"]	  = "Show the current @account name above the 'to' caption",
        ["options_show_character_name"]			  = "Show current character name",
        ["options_show_character_name_tooltip"]	  = "Show the current character name above the 'to' caption",
        ["options_mail_from"]					  = "From:",
		["options_header_inbox"]				  = "Inbox",
		["options_show_mail_count"]				  = "Show mail count",
        ["options_show_mail_count_tooltip"]		  = "Show the actual number of mails in your inbox, next to the unread mails counter",
        --Chat output
        ["chat_output_recipient_already_in_list"]   	= "[MailBuddy] Recipient name is already in the list!",
        ["chat_output_recipient_list_full"]   			= "[MailBuddy] Your recipients list is full. Please delete at least one entry!",
        ["chat_output_subject_already_in_list"]   		= "[MailBuddy] Subject is already in the list!",
        ["chat_output_subject_list_full"]   			= "[MailBuddy] Your subjects list is full. Please delete at least one entry!",
        ["chat_output_subject_already_in_fixed_list"]   = "[MailBuddy] Subject is already fixed at the top of the list!",
        --Key bindings
        ["SI_BINDING_NAME_MAILBUDDY_COPY"]		         = "Name -> MailBuddy",
        ["SI_BINDING_NAME_MAILBUDDY_FRIEND_COPY"]		 = "Friend -> MailBuddy",
		["SI_BINDING_NAME_MAILBUDDY_GUILD_MEMBER_COPY"]	 = "Member -> MailBuddy",
    },
--==============================================================================
	--German / Deutsch
    [2] = {
		-- Options menu
        ["options_description"] 				 = "Hilft dir deine Mail Empfänger und Betreffe einfach zu verwalten",
		["options_header1"] 			 		 = "Generelle Einstellungen",
    	["options_language"] 					 = "Sprache",
		["options_language_tooltip"] 			 = "Wählen Sie die Sprache aus",
		["options_language_dropdown_selection1"] = "Englisch",
		["options_language_dropdown_selection2"] = "Deutsch",
		["options_language_dropdown_selection3"] = "Französisch",
		["options_language_dropdown_selection4"] = "Spanisch",
        ["options_language_dropdown_selection5"] = "Italienisch",
		["options_language_description1"]		 = "ACHTUNG: Veränderungen der Sprache/der Speicherart laden die Benutzeroberfläche neu!",
        ["options_savedvariables"]				 = "Einstellungen speichern",
        ["options_savedvariables_tooltip"]       = "Die Einstellungen dieses Addons werden für alle Charactere Ihres Accounts, oder für jeden Character einzeln gespeichert",
        ["options_savedVariables_dropdown_selection1"] = "Jeder Charakter",
        ["options_savedVariables_dropdown_selection2"] = "Ganzer Account",

        ["options_appearance"]                   = "Erscheinung",
        ["options_alternative_layout"]                  = "Nutze alternatives Layout",
        ["options_alternative_layout_tooltip"]          = "Verstecke die zusätzlichen Empfänger und Betreff Labels links der original Mail Empfänger und Betreff Felder. Klicke mit der rechten Maustaste auf das Empfänger bzw. Betreff Feld der Mail, um die Empfänger bzw. Betreff-Liste zu öffnen/zu schließen!",
        ["options_show_alternative_layout_tooltip"]     = "Zeige Tooltip für alternatives Layout",
        ["options_show_alternative_layout_tooltip_tooltip"] = "Zeige einen Tooltip, mit Bedienungsanweisungen, über den standard Empfänger und Betreff Email Feldern an",
        ["options_play_sounds"]                         = "Sounds abspielen",
        ["options_play_sounds_tooltip"]                 = "Sounds beim Anzeigen/Verbergen/Hinzufügen/Löschen/Auswählen von MailBuddy (Einträgen) abspielen",
        ["options_additional"]                   = "Zusätzliche Optionen",
        ["options_toggle_recipients_box_click"]         = "Empfänger-Box AN/AUS beim Klicken",
        ["options_toggle_recipients_box_click_tooltip"] = "Nur wenn das alternative Layout deaktiviert ist:\n\nKlicke den zusätzlichen Empfänger Label an, um die Empfänger Box anzuzeigen/zu verstecken.",
        ["options_toggle_subjects_box_click"]           = "Betreff-Box AN/AUS beim Klicken",
        ["options_toggle_subjects_box_click_tooltip"]   = "Nur wenn das alternative Layout deaktiviert ist:\n\nKlicke den zusätzlichen Betreff Label an, um die Betreff Box anzuzeigen/zu verstecken",
        ["options_standard_mail"]                = "Standard Mail Optionen",
        ["options_standard_recipient"]           = "Standard Empfänger Name",
        ["options_standard_recipient_tooltip"]   = "Der Standard Mail Empfänger, welcher automatisch in neuen Mails eingetragen werden soll. Dies kann ein @AccountName sein, oder auch ein Charaktername. Achtung: Das Einschalten des Mail-Brains für den letzten Empfänger deaktiviert diese Option hier!",
        ["options_standard_subject"]           = "Standard Betreff Text",
        ["options_standard_subject_tooltip"]   = "Der Standard Mail Betreff, welcher automatisch in neuen Mails eingetragen werden soll. Achtung: Das Einschalten des Mail-Brains für den letzten Mail Betreff deaktiviert diese Option hier!",
        ["options_mail_brain"]                   = "Mail-Brain",
        ["options_reuse_recipient"]           = "Merke den letzten Empfänger",
        ["options_reuse_recipient_tooltip"]   = "Automatisch den letzten Empfänger für neue Mails verwenden",
        ["options_reuse_subject"]           = "Merke letzten Betreff",
        ["options_reuse_subject_tooltip"]   = "Automatisch den letzten Betreff für neue Mails verwenden",
        ["options_reuse_body"]           = "Merke letzten Mail Text",
        ["options_reuse_body_tooltip"]   = "Automatisch den letzten Mail Text für neue Mails verwenden",
        ["options_automatism"]                   = "Automatismen",
        ["options_auto_hide_recipients_box"]           = "Autom. Empfänger Box verstecken",
        ["options_auto_hide_recipients_box_tooltip"]   = "Automatisch die Empfänger Box verstecken, wenn die Mail Senden Ansicht geöffnet wird und es beim letzten Besuch dieser Ansicht noch geöffnet gewesen war.",
        ["options_auto_hide_subjects_box"]           = "Autom. Betreff Box verstecken",
        ["options_auto_hide_subjects_box_tooltip"]   = "Automatisch die Betreff Box verstecken, wenn die Mail Senden Ansicht geöffnet wird und es beim letzten Besuch dieser Ansicht noch geöffnet gewesen war.",
        ["options_auto_close_recipients_box"]           = "Autom. Empfänger Box schließen",
        ["options_auto_close_recipients_box_tooltip"]   = "Automatisch Empfänger Box schließen, wenn du einen Empfänger hinzugefügt hast. Dies funktioniert nur mit der Mail Senden Ansicht, nicht in der Freundesliste oder der Gilden Mitglieder Übersicht!",
        ["options_auto_close_subjects_box"]           = "Autom. Betreff Box schließen",
        ["options_auto_close_subjects_box_tooltip"]   = "Automatisch Betreff Box schließen, wenn du einen Betreff hinzugefügt hast. Dies funktioniert nur mit der Mail Senden Ansicht, nicht in der Freundesliste oder der Gilden Mitglieder Übersicht!",
        ["options_autofocus"]                    = "Auto-Fokus",
        ["options_auto_focus_recipients_field"]           = "Autom. das 'An' Feld auswählen",
        ["options_auto_focus_recipients_field_tooltip"]   = "Automatisch das Mail 'An' Feld auswählen, wenn dieses nicht gefüllt ist. Dies wird überprüft, wenn Sie in den Empfänger bzw. Betreff Boxen einen Eintrag auswählen.",
        ["options_auto_focus_auto_open_recipients_field"]           = "Autom. Empfängerliste öffnen",
        ["options_auto_focus_auto_open_recipients_field_tooltip"]   = "Die Empfängerliste wird dabei ebenfalls automatisch geöffnet.",
        ["options_auto_focus_subjects_field"]           = "Autom. das 'Betreff' Feld auswählen",
        ["options_auto_focus_subjects_field_tooltip"]   = "Automatisch das Mail 'Betreff' Feld auswählen, wenn dieses nicht gefüllt ist. Dies wird überprüft, wenn Sie in den Empfänger bzw. Betreff Boxen einen Eintrag auswählen.",
        ["options_auto_focus_auto_open_subjects_field"]           = "Autom. Betreffliste öffnen",
        ["options_auto_focus_auto_open_subjects_field_tooltip"]   = "Die Betreffliste wird dabei ebenfalls automatisch geöffnet.",
        ["options_auto_focus_body_field"]           = "Autom. das 'Mail Text' Feld auswählen",
        ["options_auto_focus_body_field_tooltip"]   = "Automatisch das Mail 'Text' Feld auswählen, wenn dieses nicht gefüllt ist. Dies wird überprüft, wenn Sie in den Empfänger bzw. Betreff Boxen einen Eintrag auswählen.",
        ["options_fonts"]                   = "Schrift",
        ["options_font_recipient_label"]    = "Empfänger Schrift",
        ["options_font_recipients_box"]     = "Empfänger Box Schrift",
        ["options_font_subject_label"]      = "Betreff Schrift",
        ["options_font_subjects_box"]       = "Betreff Box Schrift",
        ["options_font_recipient_label_size"]    = "Schrift Größe",
        ["options_font_recipients_box_size"]     = "Schrift Größe",
        ["options_font_subject_label_size"]      = "Schrift Größe",
        ["options_font_subjects_box_size"]       = "Schrift Größe",
        ["options_font_recipient_label_style"]    = "Schrift Stil",
        ["options_font_recipients_box_style"]     = "Schrift Stil",
        ["options_font_subject_label_style"]      = "Schrift Stil",
        ["options_font_subjects_box_style"]       = "Schrift Stil",
        ["options_font_recipient_label_color"]    = "Schrift Farbe",
        ["options_font_recipients_box_color"]     = "Schrift Farbe",
        ["options_font_subject_label_color"]      = "Schrift Farbe",
        ["options_font_subjects_box_color"]       = "Schrift Farbe",
		["options_header_sender"]				  = "Absender",
        ["options_show_account_name"]			  = "Zeige aktuellen @Account Namen",
        ["options_show_account_name_tooltip"]	  = "Zeige den aktuellen @Account Namen über dem 'An' Feld an",
        ["options_show_character_name"]			  = "Zeige aktuellen Charakter Namen",
        ["options_show_character_name_tooltip"]	  = "Zeige den aktuellen Charakter Namen über dem 'An' Feld an",
        ["options_mail_from"]					  = "Absender:",
		["options_header_inbox"]				  = "Posteingang",
		["options_show_mail_count"]				  = "Zeige Mail Anzahl an",
        ["options_show_mail_count_tooltip"]		  = "Zeige die aktuelle Anzahl der Mails in der Inbox neben der Anzahl für ungelesene Mails an",
        --Chat output
        ["chat_output_recipient_already_in_list"]   	= "[MailBuddy] Empfänger Name ist bereits in der Liste!",
        ["chat_output_recipient_list_full"]   			= "[MailBuddy] Die Empfänger Liste ist voll. Bitte mindestens einen Eintrag löschen!",
        ["chat_output_subject_already_in_list"]   		= "[MailBuddy] Betreff ist bereits in der Liste!",
        ["chat_output_subject_list_full"]   			= "[MailBuddy] Die Betreff Liste ist voll. Bitte mindestens einen Eintrag löschen!",
        ["chat_output_subject_already_in_fixed_list"]   = "[MailBuddy] Der Betreff ist bereits in der fixierten Liste!",
		--Key bindings
        ["SI_BINDING_NAME_MAILBUDDY_COPY"]		         = "Name -> MailBuddy",
        ["SI_BINDING_NAME_MAILBUDDY_FRIEND_COPY"]		 = "Freund -> MailBuddy",
        ["SI_BINDING_NAME_MAILBUDDY_GUILD_MEMBER_COPY"]	 = "Mitglied -> MailBuddy",
    },
--==============================================================================
--French / Französisch
	[3] = {
		-- Options menu
        ["options_description"]                          = "Helps you to easily manage your mail recipients and subjects",
		["options_header1"] 							 = "Général",
		["options_language"]							 = "Langue",
		["options_language_tooltip"]					 = "Choisir la langue",
		["options_language_dropdown_selection1"]		 = "Anglais",
		["options_language_dropdown_selection2"]		 = "Allemand",
		["options_language_dropdown_selection3"]		 = "Français",
		["options_language_dropdown_selection4"] 		 = "Espagnol",
        ["options_language_dropdown_selection5"]         = "Italian",
		["options_language_description1"]				 = "ATTENTION : Modifier un de ces réglages provoquera un rechargement",
		["options_savedvariables"]						 = "Sauvegarder",
		["options_savedvariables_tooltip"] 				 = "Sauvegarder les données de l'addon pour tous les personages du compte, ou individuellement pour chaque personage",
		["options_savedVariables_dropdown_selection1"]	 = "Individuellement",
		["options_savedVariables_dropdown_selection2"]	 = "Compte",
        ["options_appearance"]                          = "Appearance",
        ["options_alternative_layout"]                  = "Use alternative layout",
        ["options_alternative_layout_tooltip"]          = "Hide the additional recipient and subject fields left of the mail's 'To' and 'Subject' edit fields. Right click the mail's 'To' or 'Subject' edit field instead to show the recipients/subjects list!",
        ["options_show_alternative_layout_tooltip"]     = "Show alternative layout tooltip",
        ["options_show_alternative_layout_tooltip_tooltip"] = "Show a tooltip with instructions at the standard mail 'To' and 'Subject' edit fields",
        ["options_play_sounds"]                         = "Play sounds",
        ["options_play_sounds_tooltip"]                 = "Play sounds upon showing/hiding MailBuddy, adding/deleting/selecting entries",
        ["options_additional"]                   = "Additional options",
        ["options_toggle_recipients_box_click"]         = "Toggle recipients box vis. on click",
        ["options_toggle_recipients_box_click_tooltip"] = "Only if alternative layout is deactivated:\n\nClick the additional recipient label to toggle the recipients box visibility",
        ["options_toggle_subjects_box_click"]           = "Toggle subjects box vis. on click",
        ["options_toggle_subjects_box_click_tooltip"]   = "Only if alternative layout is deactivated:Click the additional subject label to toggle the subjects box visibility",
        ["options_standard_mail"]                = "Standard mail settings",
        ["options_standard_recipient"]           = "Standard recipient name",
        ["options_standard_recipient_tooltip"]   = "The standard mail recipient name which will be filled in a new mail. Leave it empty if none is wished. Can be @accountname or character name. Attention: Enabling the 'Mail-Brain' for the last recipient will disable this option!",
        ["options_standard_subject"]           = "Standard subject name",
        ["options_standard_subject_tooltip"]   = "The standard mail subject which will be filled in a new mail. Leave it empty if none is wished. Can be 'return', 'Hello' or whatever you want to. Attention: Enabling the 'Mail-Brain' for the last subject will disable this option!",
        ["options_mail_brain"]                   = "Mail-Brain",
        ["options_reuse_recipient"]           = "Re-Use last used recipient name",
        ["options_reuse_recipient_tooltip"]   = "Automatically fill in the last used recipient's name for your next mails",
        ["options_reuse_subject"]           = "Re-Use last used subject text",
        ["options_reuse_subject_tooltip"]   = "Automatically fill in the last used subject for your next mails",
        ["options_reuse_body"]           = "Re-Use last used body text",
        ["options_reuse_body_tooltip"]   = "Automatically fill in the last used body text for your next mails",
        ["options_automatism"]                   = "Automatism",
        ["options_auto_hide_recipients_box"]           = "Autom. hide recipients box",
        ["options_auto_hide_recipients_box_tooltip"]   = "Automatically hide the recipients box if you open the mail send panel/guild roster, and if it was open after your last visit",
        ["options_auto_hide_subjects_box"]           = "Autom. hide subjects box",
        ["options_auto_hide_subjects_box_tooltip"]   = "Automatically hide the subjects box if you open the mail send panel, and if it was open after your last visit",
        ["options_auto_close_recipients_box"]           = "Autom. close recipients box",
        ["options_auto_close_recipients_box_tooltip"]   = "Automatically close the recipients box if you have added/chosen a recipient. This will only apply to the mail send panel, not to the guild roster/friends list!",
        ["options_auto_close_subjects_box"]           = "Autom. close subjects box",
        ["options_auto_close_subjects_box_tooltip"]   = "Automatically close the subjects box if you have added/chosen a subject.",
        ["options_autofocus"]                    = "Automatic focus",
        ["options_auto_focus_recipients_field"]           = "Autom. focus the 'To' field",
        ["options_auto_focus_recipients_field_tooltip"]   = "Automatically focus the mail's 'To' field, if it is empty. This will apply if you click the recipients/subjects lists",
        ["options_auto_focus_subjects_field"]           = "Autom. focus the 'Subject' field",
        ["options_auto_focus_subjects_field_tooltip"]   = "Automatically focus the mail's 'Subject' field, if it is empty. This will apply if you click the recipients/subjects lists",
        ["options_auto_focus_auto_open_recipients_field"]           = "Autom. open recipients list",
        ["options_auto_focus_auto_open_recipients_field_tooltip"]   = "Automatically open the recipients list too.",
        ["options_auto_focus_auto_open_subjects_field"]           = "Autom. open subjects list",
        ["options_auto_focus_auto_open_subjects_field_tooltip"]   = "Automatically open the subjects list too.",
        ["options_auto_focus_body_field"]           = "Autom. focus the 'Body' text box",
        ["options_auto_focus_body_field_tooltip"]   = "Automatically focus the mail's 'Body' field, if it is empty. This will apply if you click the recipients/subjects lists",
        ["options_fonts"]                   = "Fonts",
        ["options_font_recipient_label"]    = "Recipient label font",
        ["options_font_recipients_box"]     = "Recipients box font",
        ["options_font_subject_label"]      = "Subject label font",
        ["options_font_subjects_box"]       = "Subjects box font",
        ["options_font_recipient_label_size"]    = "Font size",
        ["options_font_recipients_box_size"]     = "Font size",
        ["options_font_subject_label_size"]      = "Font size",
        ["options_font_subjects_box_size"]       = "Font size",
        ["options_font_recipient_label_style"]    = "Font style",
        ["options_font_recipients_box_style"]     = "Font style",
        ["options_font_subject_label_style"]      = "Font stylet",
        ["options_font_subjects_box_style"]       = "Font style",
        ["options_font_recipient_label_color"]    = "Font color",
        ["options_font_recipients_box_color"]     = "Font color",
        ["options_font_subject_label_color"]      = "Font color",
        ["options_font_subjects_box_color"]       = "Font color",
		["options_header_sender"]				  = "Sender",
        ["options_show_account_name"]			  = "Show current @account name",
        ["options_show_account_name_tooltip"]	  = "Show the current @account name above the 'to' caption",
        ["options_show_character_name"]			  = "Show current character name",
        ["options_show_character_name_tooltip"]	  = "Show the current character name above the 'to' caption",
        ["options_mail_from"]					  = "From:",
		["options_header_inbox"]				  = "Inbox",
		["options_show_mail_count"]				  = "Show mail count",
        ["options_show_mail_count_tooltip"]		  = "Show the actual number of mails in your inbox, next to the unread mails counter",
        --Chat output
        ["chat_output_recipient_already_in_list"]   	= "[MailBuddy] Recipient name is already in the list!",
        ["chat_output_recipient_list_full"]   			= "[MailBuddy] Your recipients list is full. Please delete at least one entry!",
        ["chat_output_subject_already_in_list"]   		= "[MailBuddy] Subject is already in the list!",
        ["chat_output_subject_list_full"]   			= "[MailBuddy] Your subjects list is full. Please delete at least one entry!",
        ["chat_output_subject_already_in_fixed_list"]   = "[MailBuddy] Subject is already fixed at the top of the list!",
		--Key bindings
        ["SI_BINDING_NAME_MAILBUDDY_COPY"]		         = "Name -> MailBuddy",
        ["SI_BINDING_NAME_MAILBUDDY_FRIEND_COPY"]		 = "Friend -> MailBuddy",
        ["SI_BINDING_NAME_MAILBUDDY_GUILD_MEMBER_COPY"]	 = "Member -> MailBuddy",
	},

--Spanish
	[4] = {
		-- Options menu
        ["options_description"]                          = "Helps you to easily manage your mail recipients and subjects",
		["options_header1"] 							 = "General",
		["options_language"]							 = "Idioma",
		["options_language_tooltip"]					 = "Elegir idioma",
		["options_language_dropdown_selection1"]		 = "Inglés",
		["options_language_dropdown_selection2"]		 = "Alemán",
		["options_language_dropdown_selection3"]		 = "Francés",
		["options_language_dropdown_selection4"]		 = "Espa\195\177ol",
        ["options_language_dropdown_selection5"]         = "Italian",
		["options_language_description1"]				 = "CUIDADO: Modificar uno de esos parámetros recargará la interfaz",
		["options_savedvariables"]						 = "Guardar",
		["options_savedvariables_tooltip"] 				 = "Guardar los parámetros del addon para toda la cuenta o individualmente para cada personaje",
		["options_savedVariables_dropdown_selection1"]	 = "Individualmente",
		["options_savedVariables_dropdown_selection2"]	 = "Cuenta",
        ["options_appearance"]                          = "Appearance",
        ["options_alternative_layout"]                  = "Use alternative layout",
        ["options_alternative_layout_tooltip"]          = "Hide the additional recipient and subject fields left of the mail's 'To' and 'Subject' edit fields. Right click the mail's 'To' or 'Subject' edit field instead to show the recipients/subjects list!",
        ["options_show_alternative_layout_tooltip"]     = "Show alternative layout tooltip",
        ["options_show_alternative_layout_tooltip_tooltip"] = "Show a tooltip with instructions at the standard mail 'To' and 'Subject' edit fields",
        ["options_play_sounds"]                         = "Play sounds",
        ["options_play_sounds_tooltip"]                 = "Play sounds upon showing/hiding MailBuddy, adding/deleting/selecting entries",
        ["options_additional"]                   = "Additional options",
        ["options_toggle_recipients_box_click"]         = "Toggle recipients box vis. on click",
        ["options_toggle_recipients_box_click_tooltip"] = "Only if alternative layout is deactivated:\n\nClick the additional recipient label to toggle the recipients box visibility",
        ["options_toggle_subjects_box_click"]           = "Toggle subjects box vis. on click",
        ["options_toggle_subjects_box_click_tooltip"]   = "Only if alternative layout is deactivated:Click the additional subject label to toggle the subjects box visibility",
        ["options_standard_mail"]                = "Standard mail settings",
        ["options_standard_recipient"]           = "Standard recipient name",
        ["options_standard_recipient_tooltip"]   = "The standard mail recipient name which will be filled in a new mail. Leave it empty if none is wished. Can be @accountname or character name. Attention: Enabling the 'Mail-Brain' for the last recipient will disable this option!",
        ["options_standard_subject"]           = "Standard subject name",
        ["options_standard_subject_tooltip"]   = "The standard mail subject which will be filled in a new mail. Leave it empty if none is wished. Can be 'return', 'Hello' or whatever you want to. Attention: Enabling the 'Mail-Brain' for the last subject will disable this option!",
        ["options_mail_brain"]                   = "Mail-Brain",
        ["options_reuse_recipient"]           = "Re-Use last used recipient name",
        ["options_reuse_recipient_tooltip"]   = "Automatically fill in the last used recipient's name for your next mails",
        ["options_reuse_subject"]           = "Re-Use last used subject text",
        ["options_reuse_subject_tooltip"]   = "Automatically fill in the last used subject for your next mails",
        ["options_reuse_body"]           = "Re-Use last used body text",
        ["options_reuse_body_tooltip"]   = "Automatically fill in the last used body text for your next mails",
        ["options_automatism"]                   = "Automatism",
        ["options_auto_hide_recipients_box"]           = "Autom. hide recipients box",
        ["options_auto_hide_recipients_box_tooltip"]   = "Automatically hide the recipients box if you open the mail send panel/guild roster, and if it was open after your last visit",
        ["options_auto_hide_subjects_box"]           = "Autom. hide subjects box",
        ["options_auto_hide_subjects_box_tooltip"]   = "Automatically hide the subjects box if you open the mail send panel, and if it was open after your last visit",
        ["options_auto_close_recipients_box"]           = "Autom. close recipients box",
        ["options_auto_close_recipients_box_tooltip"]   = "Automatically close the recipients box if you have added/chosen a recipient. This will only apply to the mail send panel, not to the guild roster/friends list!",
        ["options_auto_close_subjects_box"]           = "Autom. close subjects box",
        ["options_auto_close_subjects_box_tooltip"]   = "Automatically close the subjects box if you have added/chosen a subject.",
        ["options_autofocus"]                    = "Automatic focus",
        ["options_auto_focus_recipients_field"]           = "Autom. focus the 'To' field",
        ["options_auto_focus_recipients_field_tooltip"]   = "Automatically focus the mail's 'To' field, if it is empty. This will apply if you click the recipients/subjects lists",
        ["options_auto_focus_subjects_field"]           = "Autom. focus the 'Subject' field",
        ["options_auto_focus_subjects_field_tooltip"]   = "Automatically focus the mail's 'Subject' field, if it is empty. This will apply if you click the recipients/subjects lists",
        ["options_auto_focus_auto_open_recipients_field"]           = "Autom. open recipients list",
        ["options_auto_focus_auto_open_recipients_field_tooltip"]   = "Automatically open the recipients list too.",
        ["options_auto_focus_auto_open_subjects_field"]           = "Autom. open subjects list",
        ["options_auto_focus_auto_open_subjects_field_tooltip"]   = "Automatically open the subjects list too.",
        ["options_auto_focus_body_field"]           = "Autom. focus the 'Body' text box",
        ["options_auto_focus_body_field_tooltip"]   = "Automatically focus the mail's 'Body' field, if it is empty. This will apply if you click the recipients/subjects lists",
        ["options_fonts"]                   = "Fonts",
        ["options_font_recipient_label"]    = "Recipient label font",
        ["options_font_recipients_box"]     = "Recipients box font",
        ["options_font_subject_label"]      = "Subject label font",
        ["options_font_subjects_box"]       = "Subjects box font",
        ["options_font_recipient_label_size"]    = "Font size",
        ["options_font_recipients_box_size"]     = "Font size",
        ["options_font_subject_label_size"]      = "Font size",
        ["options_font_subjects_box_size"]       = "Font size",
        ["options_font_recipient_label_style"]    = "Font style",
        ["options_font_recipients_box_style"]     = "Font style",
        ["options_font_subject_label_style"]      = "Font stylet",
        ["options_font_subjects_box_style"]       = "Font style",
        ["options_font_recipient_label_color"]    = "Font color",
        ["options_font_recipients_box_color"]     = "Font color",
        ["options_font_subject_label_color"]      = "Font color",
        ["options_font_subjects_box_color"]       = "Font color",
		["options_header_sender"]				  = "Sender",
        ["options_show_account_name"]			  = "Show current @account name",
        ["options_show_account_name_tooltip"]	  = "Show the current @account name above the 'to' caption",
        ["options_show_character_name"]			  = "Show current character name",
        ["options_show_character_name_tooltip"]	  = "Show the current character name above the 'to' caption",
        ["options_mail_from"]					  = "From:",
		["options_header_inbox"]				  = "Inbox",
		["options_show_mail_count"]				  = "Show mail count",
        ["options_show_mail_count_tooltip"]		  = "Show the actual number of mails in your inbox, next to the unread mails counter",
        --Chat output
        ["chat_output_recipient_already_in_list"]   	= "[MailBuddy] Recipient name is already in the list!",
        ["chat_output_recipient_list_full"]   			= "[MailBuddy] Your recipients list is full. Please delete at least one entry!",
        ["chat_output_subject_already_in_list"]   		= "[MailBuddy] Subject is already in the list!",
        ["chat_output_subject_list_full"]   			= "[MailBuddy] Your subjects list is full. Please delete at least one entry!",
        ["chat_output_subject_already_in_fixed_list"]   = "[MailBuddy] Subject is already fixed at the top of the list!",
		--Key bindings
        ["SI_BINDING_NAME_MAILBUDDY_COPY"]		         = "Name -> MailBuddy",
        ["SI_BINDING_NAME_MAILBUDDY_FRIEND_COPY"]		 = "Friend -> MailBuddy",
        ["SI_BINDING_NAME_MAILBUDDY_GUILD_MEMBER_COPY"]	 = "Member -> MailBuddy",
	},
    --==============================================================================
    --Italian/Italiano
    [5] = {
        -- Options menu
        ["options_description"]                  = "Helps you to easily manage your mail recipients and subjects",
        ["options_header1"] 			 		 = "General settings",
        ["options_language"] 					 = "Language",
        ["options_language_tooltip"] 			 = "Choose the language",
        ["options_language_dropdown_selection1"] = "English",
        ["options_language_dropdown_selection2"] = "German",
        ["options_language_dropdown_selection3"] = "French",
        ["options_language_dropdown_selection4"] = "Spanish",
        ["options_language_dropdown_selection5"] = "Italian",
        ["options_language_description1"]		 = "CAUTION: Changing the language/save option will reload the user interface!",
        ["options_savedvariables"]				 = "Save settings",
        ["options_savedvariables_tooltip"]       = "Save the addon settings for all your characters of your account, or single for each character",
        ["options_savedVariables_dropdown_selection1"] = "Each character",
        ["options_savedVariables_dropdown_selection2"] = "Account wide",
        ["options_appearance"]                          = "Appearance",
        ["options_alternative_layout"]                  = "Use alternative layout",
        ["options_alternative_layout_tooltip"]          = "Hide the additional recipient and subject fields left of the mail's 'To' and 'Subject' edit fields. Right click the mail's 'To' or 'Subject' edit field instead to show the recipients/subjects list!",
        ["options_show_alternative_layout_tooltip"]     = "Show alternative layout tooltip",
        ["options_show_alternative_layout_tooltip_tooltip"] = "Show a tooltip with instructions at the standard mail 'To' and 'Subject' edit fields",
        ["options_play_sounds"]                         = "Play sounds",
        ["options_play_sounds_tooltip"]                 = "Play sounds upon showing/hiding MailBuddy, adding/deleting/selecting entries",
        ["options_additional"]                   = "Additional options",
        ["options_toggle_recipients_box_click"]         = "Toggle recipients box vis. on click",
        ["options_toggle_recipients_box_click_tooltip"] = "Only if alternative layout is deactivated:\n\nClick the additional recipient label to toggle the recipients box visibility",
        ["options_toggle_subjects_box_click"]           = "Toggle subjects box vis. on click",
        ["options_toggle_subjects_box_click_tooltip"]   = "Only if alternative layout is deactivated:Click the additional subject label to toggle the subjects box visibility",
        ["options_standard_mail"]                = "Standard mail settings",
        ["options_standard_recipient"]           = "Standard recipient name",
        ["options_standard_recipient_tooltip"]   = "The standard mail recipient name which will be filled in a new mail. Leave it empty if none is wished. Can be @accountname or character name. Attention: Enabling the 'Mail-Brain' for the last recipient will disable this option!",
        ["options_standard_subject"]           = "Standard subject name",
        ["options_standard_subject_tooltip"]   = "The standard mail subject which will be filled in a new mail. Leave it empty if none is wished. Can be 'return', 'Hello' or whatever you want to. Attention: Enabling the 'Mail-Brain' for the last subject will disable this option!",
        ["options_mail_brain"]                   = "Mail-Brain",
        ["options_reuse_recipient"]           = "Re-Use last used recipient name",
        ["options_reuse_recipient_tooltip"]   = "Automatically fill in the last used recipient's name for your next mails",
        ["options_reuse_subject"]           = "Re-Use last used subject text",
        ["options_reuse_subject_tooltip"]   = "Automatically fill in the last used subject for your next mails",
        ["options_reuse_body"]           = "Re-Use last used body text",
        ["options_reuse_body_tooltip"]   = "Automatically fill in the last used body text for your next mails",
        ["options_automatism"]                   = "Automatism",
        ["options_auto_hide_recipients_box"]           = "Autom. hide recipients box",
        ["options_auto_hide_recipients_box_tooltip"]   = "Automatically hide the recipients box if you open the mail send panel/guild roster, and if it was open after your last visit",
        ["options_auto_hide_subjects_box"]           = "Autom. hide subjects box",
        ["options_auto_hide_subjects_box_tooltip"]   = "Automatically hide the subjects box if you open the mail send panel, and if it was open after your last visit",
        ["options_auto_close_recipients_box"]           = "Autom. close recipients box",
        ["options_auto_close_recipients_box_tooltip"]   = "Automatically close the recipients box if you have added/chosen a recipient. This will only apply to the mail send panel, not to the guild roster/friends list!",
        ["options_auto_close_subjects_box"]           = "Autom. close subjects box",
        ["options_auto_close_subjects_box_tooltip"]   = "Automatically close the subjects box if you have added/chosen a subject.",
        ["options_autofocus"]                    = "Automatic focus",
        ["options_auto_focus_recipients_field"]           = "Autom. focus the 'To' field",
        ["options_auto_focus_recipients_field_tooltip"]   = "Automatically focus the mail's 'To' field, if it is empty. This will apply if you click the recipients/subjects lists",
        ["options_auto_focus_subjects_field"]           = "Autom. focus the 'Subject' field",
        ["options_auto_focus_subjects_field_tooltip"]   = "Automatically focus the mail's 'Subject' field, if it is empty. This will apply if you click the recipients/subjects lists",
        ["options_auto_focus_auto_open_recipients_field"]           = "Autom. open recipients list",
        ["options_auto_focus_auto_open_recipients_field_tooltip"]   = "Automatically open the recipients list too.",
        ["options_auto_focus_auto_open_subjects_field"]           = "Autom. open subjects list",
        ["options_auto_focus_auto_open_subjects_field_tooltip"]   = "Automatically open the subjects list too.",
        ["options_auto_focus_body_field"]           = "Autom. focus the 'Body' text box",
        ["options_auto_focus_body_field_tooltip"]   = "Automatically focus the mail's 'Body' field, if it is empty. This will apply if you click the recipients/subjects lists",
        ["options_fonts"]                   = "Fonts",
        ["options_font_recipient_label"]    = "Recipient label font",
        ["options_font_recipients_box"]     = "Recipients box font",
        ["options_font_subject_label"]      = "Subject label font",
        ["options_font_subjects_box"]       = "Subjects box font",
        ["options_font_recipient_label_size"]    = "Font size",
        ["options_font_recipients_box_size"]     = "Font size",
        ["options_font_subject_label_size"]      = "Font size",
        ["options_font_subjects_box_size"]       = "Font size",
        ["options_font_recipient_label_style"]    = "Font style",
        ["options_font_recipients_box_style"]     = "Font style",
        ["options_font_subject_label_style"]      = "Font stylet",
        ["options_font_subjects_box_style"]       = "Font style",
        ["options_font_recipient_label_color"]    = "Font color",
        ["options_font_recipients_box_color"]     = "Font color",
        ["options_font_subject_label_color"]      = "Font color",
        ["options_font_subjects_box_color"]       = "Font color",
		["options_header_sender"]				  = "Sender",
        ["options_show_account_name"]			  = "Show current @account name",
        ["options_show_account_name_tooltip"]	  = "Show the current @account name above the 'to' caption",
        ["options_show_character_name"]			  = "Show current character name",
        ["options_show_character_name_tooltip"]	  = "Show the current character name above the 'to' caption",
        ["options_mail_from"]					  = "From:",
		["options_header_inbox"]				  = "Inbox",
		["options_show_mail_count"]				  = "Show mail count",
        ["options_show_mail_count_tooltip"]		  = "Show the actual number of mails in your inbox, next to the unread mails counter",
        --Chat output
        ["chat_output_recipient_already_in_list"]   	= "[MailBuddy] Recipient name is already in the list!",
        ["chat_output_recipient_list_full"]   			= "[MailBuddy] Your recipients list is full. Please delete at least one entry!",
        ["chat_output_subject_already_in_list"]   		= "[MailBuddy] Subject is already in the list!",
        ["chat_output_subject_list_full"]   			= "[MailBuddy] Your subjects list is full. Please delete at least one entry!",
        ["chat_output_subject_already_in_fixed_list"]   = "[MailBuddy] Subject is already fixed at the top of the list!",
        --Key bindings
        ["SI_BINDING_NAME_MAILBUDDY_COPY"]		         = "Name -> MailBuddy",
        ["SI_BINDING_NAME_MAILBUDDY_FRIEND_COPY"]		 = "Friend -> MailBuddy",
        ["SI_BINDING_NAME_MAILBUDDY_GUILD_MEMBER_COPY"]	 = "Member -> MailBuddy",
    },
}
local mbAll = mb.localizationVars.all

--Meta table trick to use english localization for german and french values, which are missing
setmetatable(mbAll[2], {__index = mbAll[1]})
setmetatable(mbAll[3], {__index = mbAll[1]})
setmetatable(mbAll[4], {__index = mbAll[1]})
setmetatable(mbAll[5], {__index = mbAll[1]})
