NGear = NGear or {}

local Lexicon = {}
local DEFAULT_LANGUAGE = "en"
local DEFAULT_LANGUAGE_PREFERENCE = "auto"
local LANGUAGE_SAVED_VARIABLES_NAME = "NGearLanguageSettings"
local LANGUAGE_SAVED_VARIABLES_VERSION = 1
local INSTALLATION_WIDE = "$InstallationWide"
local Unpack = unpack or table.unpack

local SUPPORTED_LANGUAGES = {
    en = true,
    fr = true,
    de = true,
    jp = true,
    es = true,
    ru = true,
    zh = true,
}

local LANGUAGE_ALIASES = {
    ja = "jp",
    ["zh-cn"] = "zh",
    ["zh-hans"] = "zh",
    ["zh-sg"] = "zh",
}
local LANGUAGE_CHOICES = { "auto", "en", "fr", "de", "jp", "es", "ru", "zh" }
local LANGUAGE_CHOICE_KEYS = {
    "settings.language.choice.auto",
    "settings.language.choice.en",
    "settings.language.choice.fr",
    "settings.language.choice.de",
    "settings.language.choice.jp",
    "settings.language.choice.es",
    "settings.language.choice.ru",
    "settings.language.choice.zh",
}

-- Add every player-facing string here in all seven language tables.
local TRANSLATIONS = {
    en = {
        ["features.collections_gear.search_dialog_placeholder"] = "<<1>> name",
        ["features.collections_gear.search_dialog_title"] = "Search <<1>>",
        ["dialogs.language_reload.message"] = "Changing NGear's language requires a UI reload. Reload the UI now?",
        ["dialogs.language_reload.title"] = "Change language?",
        ["settings.language.choice.auto"] = "Auto",
        ["settings.language.choice.de"] = "Deutsch",
        ["settings.language.choice.en"] = "English",
        ["settings.language.choice.es"] = "Español",
        ["settings.language.choice.fr"] = "Français",
        ["settings.language.choice.jp"] = "日本語",
        ["settings.language.choice.ru"] = "Русский",
        ["settings.language.choice.zh"] = "简体中文",
        ["settings.language.label"] = "Language",
        ["settings.language.tooltip"] = "Chooses the language used by NGear. Auto follows the game's language. A new selection is applied after you exit NGear settings.",
        ["ui.headers.global_options"] = "Global options",
        ["common.font.antique"] = "Antique",
        ["common.font.gamepad_bold"] = "Gamepad bold",
        ["common.font.gamepad_light"] = "Gamepad light",
        ["common.font.gamepad_medium"] = "Gamepad medium",
        ["common.font.handwritten"] = "Handwritten",
        ["common.font.keyboard_bold"] = "Keyboard bold",
        ["common.font.keyboard_medium"] = "Keyboard medium",
        ["common.item_set"] = "Item set",
        ["common.other"] = "Other",
        ["common.right_stick"] = "Right stick",
        ["common.search"] = "Search",
        ["common.unknown_value"] = "Unknown",
        ["features.collections_gear.all_sets_6ece2fa"] = "All sets",
        ["features.collections_gear.apply_search_96b8b79"] = "Apply Search",
        ["features.collections_gear.background_opacity_label"] = "Background opacity",
        ["features.collections_gear.background_opacity_tooltip"] = "Adjusts the opacity of the Gear collection display background.",
        ["features.collections_gear.class_sets_d8f88fa"] = "Class sets",
        ["features.collections_gear.clear_search_87e328d"] = "Clear Search",
        ["features.collections_gear.completed_sets_5094bc4"] = "Completed sets",
        ["features.collections_gear.font_label"] = "Font",
        ["features.collections_gear.font_tooltip"] = "Chooses the font used by the Gear collection display.",
        ["features.collections_gear.horizontal_position_label"] = "Horizontal position",
        ["features.collections_gear.horizontal_position_tooltip"] = "Moves the Gear collection display left or right.",
        ["features.collections_gear.incomplete_sets_a81fe8d"] = "Incomplete sets",
        ["features.collections_gear.input_hint"] = "<<1>> <<2>>  Jump group    <<3>>  Search    <<4>>  Filter: <<5>>    <<6>>  Browse sets",
        ["features.collections_gear.input_hint_flat"] = "<<1>>  Search    <<2>>  Filter: <<3>>    <<4>>  Browse sets",
        ["features.collections_gear.loading"] = "Loading gear...",
        ["features.collections_gear.monster_sets_6bed3c4"] = "Monster sets",
        ["features.collections_gear.mythics_965733d"] = "Mythics",
        ["features.collections_gear.no_bonus_details"] = "No set bonus details are available.",
        ["features.collections_gear.no_mythic_lead_data"] = "No Antiquity lead data is available for this Mythic.",
        ["features.collections_gear.no_pieces_are_available_for_this_set_e297c61"] = "No pieces are available for this set.",
        ["features.collections_gear.no_search_results"] = "No sets match the search '<<1>>' and selected filter.",
        ["features.collections_gear.no_set_selected"] = "No set selected",
        ["features.collections_gear.no_sets_match_filter"] = "No sets match the selected filter.",
        ["features.collections_gear.perfected_name"] = "<<1>> (perfected)",
        ["features.collections_gear.scale_label"] = "Scale",
        ["features.collections_gear.scale_tooltip"] = "Changes the size of the entire Gear collection display.",
        ["features.collections_gear.search_title"] = "GEAR (<<1>>)",
        ["features.collections_gear.set_bonus"] = "SET BONUS",
        ["features.collections_gear.set_bonuses"] = "SET BONUSES",
        ["features.collections_gear.set_card_label"] = "Set card",
        ["features.collections_gear.set_card_tooltip"] = "Shows a third pane with the selected set's bonus details.",
        ["features.collections_gear.set_collection"] = "Set Collection",
        ["features.collections_gear.sets_cba9e41"] = "SETS",
        ["features.collections_gear.show_watermark_label"] = "Show watermark",
        ["features.collections_gear.show_watermark_tooltip"] = "Shows or hides the repeated player and server watermark behind the Gear collection content.",
        ["features.collections_gear.summary"] = "<<1>> <<2>>  •  <<3>> / <<4>> pieces",
        ["features.collections_gear.summary_class_sets"] = "Class sets",
        ["features.collections_gear.summary_completed_sets"] = "completed sets",
        ["features.collections_gear.summary_incomplete_sets"] = "incomplete sets",
        ["features.collections_gear.summary_monster_sets"] = "Monster sets",
        ["features.collections_gear.summary_mythics"] = "Mythics",
        ["features.collections_gear.summary_sets"] = "sets",
        ["features.collections_gear.title"] = "GEAR",
        ["features.collections_gear.type_class"] = "CLASS ITEM SET",
        ["features.collections_gear.type_item"] = "ITEM SET",
        ["features.collections_gear.type_monster"] = "MONSTER ITEM SET",
        ["features.collections_gear.type_mythic"] = "MYTHIC ITEM SET",
        ["features.collections_gear.type_perfected"] = "PERFECTED ITEM SET",
        ["features.collections_gear.unknown_lead"] = "Unknown lead",
        ["features.collections_gear.unknown_piece"] = "Unknown piece",
        ["features.collections_gear.unknown_set"] = "Unknown set",
        ["features.collections_gear.vertical_position_label"] = "Vertical position",
        ["features.collections_gear.vertical_position_tooltip"] = "Moves the Gear collection display up or down.",
        ["ui.addons_menu.ngear_name"] = "|cFF0000N|r|c007FFFGear|r",
        ["item_locator.apply_search"] = "Apply Search",
        ["item_locator.bank"] = "Bank",
        ["item_locator.background_opacity_label"] = "Background opacity",
        ["item_locator.background_opacity_tooltip"] = "Adjusts the opacity of the Item Locator background.",
        ["item_locator.font_label"] = "Font",
        ["item_locator.font_tooltip"] = "Chooses the font used by Item Locator.",
        ["item_locator.horizontal_position_label"] = "Horizontal position",
        ["item_locator.horizontal_position_tooltip"] = "Moves Item Locator left or right.",
        ["item_locator.scale_label"] = "Scale",
        ["item_locator.scale_tooltip"] = "Changes the size of the entire Item Locator display.",
        ["item_locator.vertical_position_label"] = "Vertical position",
        ["item_locator.vertical_position_tooltip"] = "Moves Item Locator up or down.",
        ["item_locator.binding"] = "Binding",
        ["item_locator.category"] = "Category",
        ["item_locator.craft_bag"] = "Craft Bag",
        ["item_locator.chat_bank"] = "Bank (<<1>>)",
        ["item_locator.chat_character"] = "<<1>> (<<2>>)",
        ["item_locator.chat_message"] = "<<1>> · <<2>>",
        ["item_locator.chat_storage"] = "<<1>> (<<2>>)",
        ["item_locator.champion_level"] = "Champion <<1>>",
        ["item_locator.clear_search"] = "Clear Search",
        ["item_locator.data_unavailable"] = "Some saved item data could not be read.",
        ["item_locator.date_month_abbreviations"] = "Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec",
        ["item_locator.detail_line"] = "|c72BEEB<<1>>:|r <<2>>",
        ["item_locator.details"] = "ITEM DETAILS",
        ["item_locator.enchantment"] = "Enchantment",
        ["item_locator.furniture_vault"] = "Furnishing Vault",
        ["item_locator.house_storage"] = "House Storage",
        ["item_locator.items"] = "ITEMS",
        ["item_locator.input_hint_actions"] = "<<1>> Search · <<2>> · <<3>> Back",
        ["item_locator.input_hint_categories"] = "<<1>> Browse · <<2>> <<3>> Categories · <<4>> Search · <<5>> · <<6>> Log in chat · <<7>> Back",
        ["item_locator.input_hint_empty"] = "<<1>> Back",
        ["item_locator.input_hint_items"] = "<<1>> Browse · <<2>> Search · <<3>> · <<4>> Log in chat · <<5>> Back",
        ["item_locator.level"] = "Level",
        ["item_locator.location_bank"] = "Bank: <<1>>",
        ["item_locator.location_equipped"] = "<<1>> · Equipped: <<2>>",
        ["item_locator.location_inventory"] = "<<1>>: <<2>>",
        ["item_locator.location_storage"] = "<<1>>: <<2>>",
        ["item_locator.locations"] = "LOCATIONS",
        ["item_locator.market_prices"] = "MARKET PRICES",
        ["item_locator.no_items"] = "No tracked items are available.",
        ["item_locator.no_search_results"] = "No items match the search '<<1>>'.",
        ["item_locator.no_selection"] = "No item selected",
        ["item_locator.log_in_chat"] = "Log in chat",
        ["item_locator.price_average"] = "Average value",
        ["item_locator.price_maximum"] = "Maximum value",
        ["item_locator.price_minimum"] = "Minimum value",
        ["item_locator.roster_not_indexed"] = "Not indexed yet",
        ["item_locator.roster_date"] = "<<1>>-<<2>>-<<3>>",
        ["item_locator.roster_scanned"] = "|cFFFFFF<<1>>:|r\n<<2>>",
        ["item_locator.search_placeholder"] = "Item name",
        ["item_locator.search_title"] = "Search Items",
        ["item_locator.sort"] = "Sort",
        ["item_locator.sort_alphabetical"] = "Alphabetically",
        ["item_locator.sort_hint"] = "<<1>> Sort: <<2>>",
        ["item_locator.sort_quality"] = "By quality",
        ["item_locator.status"] = "Status",
        ["item_locator.stolen"] = "Stolen",
        ["item_locator.style"] = "Style",
        ["item_locator.summary"] = "<<1>> items • <<2>> variants",
        ["item_locator.title"] = "ITEM LOCATOR",
        ["item_locator.title_search"] = "ITEM LOCATOR (<<1>>)",
        ["item_locator.trait"] = "Trait",
        ["item_locator.type"] = "Type",
        ["item_locator.variant_total"] = "<<1>> available",
        ["item_locator.weight"] = "Weight",
        ["ui.navigation.item_categories"] = "Item Categories",
        ["ui.navigation.item_categories_tooltip"] = "Choose which item categories appear in Item Locator.",
        ["ui.navigation.item_category_toggle_tooltip"] = "Show this category in Item Locator.",
        ["ui.navigation.item_locator"] = "Item locator",
        ["ui.navigation.item_locator_tooltip"] = "Locate an item across your account",
        ["ui.navigation.scan_items"] = "Scan items",
        ["ui.navigation.scan_items_tooltip"] = "Scans and tracks items carried or equipped by this character, plus items in the shared bank, Furnishing Vault, and house storage.",
        ["ui.navigation.browse_every_reconstructable_gear_set_and_its_collec_86e2576"] = "Browse every reconstructable gear set and its collected pieces in a dedicated collection display.",
        ["ui.navigation.gear_def2b5f"] = "Gear",
    },
    fr = {
        ["features.collections_gear.search_dialog_placeholder"] = "<<1>> nom",
        ["features.collections_gear.search_dialog_title"] = "Rechercher <<1>>",
        ["dialogs.language_reload.message"] = "Changer la langue de NGear nécessite de recharger l’interface. Recharger l’interface maintenant ?",
        ["dialogs.language_reload.title"] = "Changer de langue ?",
        ["settings.language.choice.auto"] = "Automatique",
        ["settings.language.choice.de"] = "Deutsch",
        ["settings.language.choice.en"] = "English",
        ["settings.language.choice.es"] = "Español",
        ["settings.language.choice.fr"] = "Français",
        ["settings.language.choice.jp"] = "日本語",
        ["settings.language.choice.ru"] = "Русский",
        ["settings.language.choice.zh"] = "简体中文",
        ["settings.language.label"] = "Langue",
        ["settings.language.tooltip"] = "Choisit la langue utilisée par NGear. Automatique suit la langue du jeu. La nouvelle sélection est appliquée lorsque vous quittez les paramètres de NGear.",
        ["ui.headers.global_options"] = "Options globales",
        ["common.font.antique"] = "Antiquité",
        ["common.font.gamepad_bold"] = "Manette de jeu audacieuse",
        ["common.font.gamepad_light"] = "Lumière de la manette de jeu",
        ["common.font.gamepad_medium"] = "Support de manette de jeu",
        ["common.font.handwritten"] = "Manuscrit",
        ["common.font.keyboard_bold"] = "Clavier gras",
        ["common.font.keyboard_medium"] = "Clavier médium",
        ["common.item_set"] = "Ensemble d'articles",
        ["common.other"] = "Autre",
        ["common.right_stick"] = "Stick droit",
        ["common.search"] = "Rechercher",
        ["common.unknown_value"] = "Inconnu",
        ["features.collections_gear.all_sets_6ece2fa"] = "Tous les ensembles",
        ["features.collections_gear.apply_search_96b8b79"] = "Appliquer la recherche",
        ["features.collections_gear.background_opacity_label"] = "Opacité de l'arrière-plan",
        ["features.collections_gear.background_opacity_tooltip"] = "Ajuste l’opacité de l’arrière-plan de l’affichage de la collection Gear.",
        ["features.collections_gear.class_sets_d8f88fa"] = "Ensembles de classe",
        ["features.collections_gear.clear_search_87e328d"] = "Effacer la recherche",
        ["features.collections_gear.completed_sets_5094bc4"] = "Ensembles terminés",
        ["features.collections_gear.font_label"] = "Police",
        ["features.collections_gear.font_tooltip"] = "Choisit la police utilisée par l'affichage de la collection Gear.",
        ["features.collections_gear.horizontal_position_label"] = "Position horizontale",
        ["features.collections_gear.horizontal_position_tooltip"] = "Déplace l’affichage de la collection Gear vers la gauche ou la droite.",
        ["features.collections_gear.incomplete_sets_a81fe8d"] = "Ensembles incomplets",
        ["features.collections_gear.input_hint"] = "<<1>> <<2>> Groupe de sauts <<3>> Recherche <<4>> Filtre : <<5>> <<6>> Parcourir les ensembles",
        ["features.collections_gear.input_hint_flat"] = "<<1>> Recherche <<2>> Filtre : <<3>> <<4>> Parcourir les ensembles",
        ["features.collections_gear.loading"] = "Chargement de l’équipement...",
        ["features.collections_gear.monster_sets_6bed3c4"] = "Ensembles de monstres",
        ["features.collections_gear.mythics_965733d"] = "Mythiques",
        ["features.collections_gear.no_bonus_details"] = "Aucun détail sur le bonus défini n'est disponible.",
        ["features.collections_gear.no_mythic_lead_data"] = "Aucune donnée de piste d'Antiquité n'est disponible pour ce Mythique.",
        ["features.collections_gear.no_pieces_are_available_for_this_set_e297c61"] = "Aucune pièce n'est disponible pour cet ensemble.",
        ["features.collections_gear.no_search_results"] = "Aucun ensemble ne correspond à la recherche « <<1>> » et au filtre sélectionné.",
        ["features.collections_gear.no_set_selected"] = "Aucun ensemble sélectionné",
        ["features.collections_gear.no_sets_match_filter"] = "Aucun ensemble ne correspond au filtre sélectionné.",
        ["features.collections_gear.perfected_name"] = "<<1>> (perfectionné)",
        ["features.collections_gear.scale_label"] = "Échelle",
        ["features.collections_gear.scale_tooltip"] = "Modifie la taille de l'ensemble de l'affichage de la collection Gear.",
        ["features.collections_gear.search_title"] = "ÉQUIPEMENT (<<1>>)",
        ["features.collections_gear.set_bonus"] = "DÉFINIR LE BONUS",
        ["features.collections_gear.set_bonuses"] = "DÉFINIR DES BONUS",
        ["features.collections_gear.set_card_label"] = "Définir la carte",
        ["features.collections_gear.set_card_tooltip"] = "Affiche un troisième volet avec les détails des bonus de l'ensemble sélectionné.",
        ["features.collections_gear.set_collection"] = "Ensemble de collecte",
        ["features.collections_gear.sets_cba9e41"] = "ENSEMBLES",
        ["features.collections_gear.show_watermark_label"] = "Afficher le filigrane",
        ["features.collections_gear.show_watermark_tooltip"] = "Affiche ou masque le filigrane répété du joueur et du serveur derrière le contenu de la collection Gear.",
        ["features.collections_gear.summary"] = "<<1>> <<2>>  •  <<3>> / <<4>> pièces",
        ["features.collections_gear.summary_class_sets"] = "Ensembles de classe",
        ["features.collections_gear.summary_completed_sets"] = "ensembles terminés",
        ["features.collections_gear.summary_incomplete_sets"] = "ensembles incomplets",
        ["features.collections_gear.summary_monster_sets"] = "Ensembles de monstres",
        ["features.collections_gear.summary_mythics"] = "Mythiques",
        ["features.collections_gear.summary_sets"] = "ensembles",
        ["features.collections_gear.title"] = "ÉQUIPEMENT",
        ["features.collections_gear.type_class"] = "ENSEMBLE D'OBJETS DE CLASSE",
        ["features.collections_gear.type_item"] = "ENSEMBLE D'ARTICLE",
        ["features.collections_gear.type_monster"] = "ENSEMBLE D'OBJETS DE MONSTRE",
        ["features.collections_gear.type_mythic"] = "ENSEMBLE D'OBJETS MYTHIQUES",
        ["features.collections_gear.type_perfected"] = "ENSEMBLE D'ARTICLES PARFAITS",
        ["features.collections_gear.unknown_lead"] = "Piste inconnue",
        ["features.collections_gear.unknown_piece"] = "Pièce inconnue",
        ["features.collections_gear.unknown_set"] = "Ensemble inconnu",
        ["features.collections_gear.vertical_position_label"] = "Position verticale",
        ["features.collections_gear.vertical_position_tooltip"] = "Déplace l’affichage de la collection Gear vers le haut ou vers le bas.",
        ["ui.addons_menu.ngear_name"] = "|cFF0000N|r|c007FFFGear|r",
        ["item_locator.apply_search"] = "Appliquer la recherche",
        ["item_locator.bank"] = "Banque",
        ["item_locator.background_opacity_label"] = "Opacité de l’arrière-plan",
        ["item_locator.background_opacity_tooltip"] = "Ajuste l’opacité de l’arrière-plan du localisateur d’objets.",
        ["item_locator.font_label"] = "Police",
        ["item_locator.font_tooltip"] = "Choisit la police utilisée par le localisateur d’objets.",
        ["item_locator.horizontal_position_label"] = "Position horizontale",
        ["item_locator.horizontal_position_tooltip"] = "Déplace le localisateur d’objets vers la gauche ou la droite.",
        ["item_locator.scale_label"] = "Échelle",
        ["item_locator.scale_tooltip"] = "Modifie la taille de l’ensemble du localisateur d’objets.",
        ["item_locator.vertical_position_label"] = "Position verticale",
        ["item_locator.vertical_position_tooltip"] = "Déplace le localisateur d’objets vers le haut ou vers le bas.",
        ["item_locator.binding"] = "Liaison",
        ["item_locator.category"] = "Catégorie",
        ["item_locator.craft_bag"] = "Sac d’artisanat",
        ["item_locator.chat_bank"] = "Banque (<<1>>)",
        ["item_locator.chat_character"] = "<<1>> (<<2>>)",
        ["item_locator.chat_message"] = "<<1>> · <<2>>",
        ["item_locator.chat_storage"] = "<<1>> (<<2>>)",
        ["item_locator.champion_level"] = "Champion <<1>>",
        ["item_locator.clear_search"] = "Effacer la recherche",
        ["item_locator.data_unavailable"] = "Certaines données d’objets enregistrées n’ont pas pu être lues.",
        ["item_locator.date_month_abbreviations"] = "janv.|févr.|mars|avr.|mai|juin|juil.|août|sept.|oct.|nov.|déc.",
        ["item_locator.detail_line"] = "|c72BEEB<<1>> :|r <<2>>",
        ["item_locator.details"] = "DÉTAILS DE L’OBJET",
        ["item_locator.enchantment"] = "Enchantement",
        ["item_locator.furniture_vault"] = "Garde-meubles",
        ["item_locator.house_storage"] = "Rangement de maison",
        ["item_locator.items"] = "OBJETS",
        ["item_locator.input_hint_actions"] = "<<1>> Rechercher · <<2>> · <<3>> Retour",
        ["item_locator.input_hint_categories"] = "<<1>> Parcourir · <<2>> <<3>> Catégories · <<4>> Rechercher · <<5>> · <<6>> Afficher dans le chat · <<7>> Retour",
        ["item_locator.input_hint_empty"] = "<<1>> Retour",
        ["item_locator.input_hint_items"] = "<<1>> Parcourir · <<2>> Rechercher · <<3>> · <<4>> Afficher dans le chat · <<5>> Retour",
        ["item_locator.level"] = "Niveau",
        ["item_locator.location_bank"] = "Banque : <<1>>",
        ["item_locator.location_equipped"] = "<<1>> · Équipé : <<2>>",
        ["item_locator.location_inventory"] = "<<1>> : <<2>>",
        ["item_locator.location_storage"] = "<<1>> : <<2>>",
        ["item_locator.locations"] = "EMPLACEMENTS",
        ["item_locator.market_prices"] = "PRIX DU MARCHÉ",
        ["item_locator.no_items"] = "Aucun objet suivi n’est disponible.",
        ["item_locator.no_search_results"] = "Aucun objet ne correspond à la recherche « <<1>> ».",
        ["item_locator.no_selection"] = "Aucun objet sélectionné",
        ["item_locator.log_in_chat"] = "Afficher dans le chat",
        ["item_locator.price_average"] = "Valeur moyenne",
        ["item_locator.price_maximum"] = "Valeur maximale",
        ["item_locator.price_minimum"] = "Valeur minimale",
        ["item_locator.roster_not_indexed"] = "Pas encore indexé",
        ["item_locator.roster_date"] = "<<1>>-<<2>>-<<3>>",
        ["item_locator.roster_scanned"] = "|cFFFFFF<<1>> :|r\n<<2>>",
        ["item_locator.search_placeholder"] = "Nom de l’objet",
        ["item_locator.search_title"] = "Rechercher des objets",
        ["item_locator.sort"] = "Trier",
        ["item_locator.sort_alphabetical"] = "Alphabétiquement",
        ["item_locator.sort_hint"] = "<<1>> Tri : <<2>>",
        ["item_locator.sort_quality"] = "Par qualité",
        ["item_locator.status"] = "Statut",
        ["item_locator.stolen"] = "Volé",
        ["item_locator.style"] = "Style",
        ["item_locator.summary"] = "<<1>> objets • <<2>> variantes",
        ["item_locator.title"] = "LOCALISATEUR D’OBJETS",
        ["item_locator.title_search"] = "LOCALISATEUR D’OBJETS (<<1>>)",
        ["item_locator.trait"] = "Trait",
        ["item_locator.type"] = "Type",
        ["item_locator.variant_total"] = "<<1>> disponibles",
        ["item_locator.weight"] = "Poids",
        ["ui.navigation.item_categories"] = "Catégories d’objets",
        ["ui.navigation.item_categories_tooltip"] = "Choisissez les catégories d’objets qui apparaissent dans le localisateur d’objets.",
        ["ui.navigation.item_category_toggle_tooltip"] = "Afficher cette catégorie dans le localisateur d’objets.",
        ["ui.navigation.item_locator"] = "Localisateur d’objets",
        ["ui.navigation.item_locator_tooltip"] = "Localisez un objet dans tout votre compte",
        ["ui.navigation.scan_items"] = "Analyser les objets",
        ["ui.navigation.scan_items_tooltip"] = "Analyse et suit les objets portés ou équipés par ce personnage ainsi que ceux de la banque partagée, du garde-meubles et des rangements de maison.",
        ["ui.navigation.browse_every_reconstructable_gear_set_and_its_collec_86e2576"] = "Parcourez chaque ensemble d'équipement reconstructible et ses pièces collectées dans une exposition de collection dédiée.",
        ["ui.navigation.gear_def2b5f"] = "Équipement",
    },
    de = {
        ["features.collections_gear.search_dialog_placeholder"] = "<<1>> Name",
        ["features.collections_gear.search_dialog_title"] = "Suchen Sie nach <<1>>",
        ["dialogs.language_reload.message"] = "Das Ändern der NGear-Sprache erfordert ein Neuladen der Benutzeroberfläche. Benutzeroberfläche jetzt neu laden?",
        ["dialogs.language_reload.title"] = "Sprache ändern?",
        ["settings.language.choice.auto"] = "Automatisch",
        ["settings.language.choice.de"] = "Deutsch",
        ["settings.language.choice.en"] = "English",
        ["settings.language.choice.es"] = "Español",
        ["settings.language.choice.fr"] = "Français",
        ["settings.language.choice.jp"] = "日本語",
        ["settings.language.choice.ru"] = "Русский",
        ["settings.language.choice.zh"] = "简体中文",
        ["settings.language.label"] = "Sprache",
        ["settings.language.tooltip"] = "Wählt die von NGear verwendete Sprache aus. Automatisch übernimmt die Sprache des Spiels. Die neue Auswahl wird angewendet, nachdem du die NGear-Einstellungen verlassen hast.",
        ["ui.headers.global_options"] = "Globale Optionen",
        ["common.font.antique"] = "Antik",
        ["common.font.gamepad_bold"] = "Gamepad fett",
        ["common.font.gamepad_light"] = "Gamepad-Licht",
        ["common.font.gamepad_medium"] = "Gamepad mittel",
        ["common.font.handwritten"] = "Handschriftlich",
        ["common.font.keyboard_bold"] = "Tastatur fett",
        ["common.font.keyboard_medium"] = "Tastatur mittel",
        ["common.item_set"] = "Artikelset",
        ["common.other"] = "Andere",
        ["common.right_stick"] = "Rechter Stock",
        ["common.search"] = "Suchen",
        ["common.unknown_value"] = "Unbekannt",
        ["features.collections_gear.all_sets_6ece2fa"] = "Alle Sets",
        ["features.collections_gear.apply_search_96b8b79"] = "Suche anwenden",
        ["features.collections_gear.background_opacity_label"] = "Hintergrundopazität",
        ["features.collections_gear.background_opacity_tooltip"] = "Passt die Deckkraft des Anzeigehintergrunds der Gear-Sammlung an.",
        ["features.collections_gear.class_sets_d8f88fa"] = "Klassensätze",
        ["features.collections_gear.clear_search_87e328d"] = "Suche löschen",
        ["features.collections_gear.completed_sets_5094bc4"] = "Fertige Sets",
        ["features.collections_gear.font_label"] = "Schriftart",
        ["features.collections_gear.font_tooltip"] = "Wählt die Schriftart aus, die von der Gear-Sammlungsanzeige verwendet wird.",
        ["features.collections_gear.horizontal_position_label"] = "Horizontale Position",
        ["features.collections_gear.horizontal_position_tooltip"] = "Verschiebt die Gear-Sammlungsanzeige nach links oder rechts.",
        ["features.collections_gear.incomplete_sets_a81fe8d"] = "Unvollständige Sätze",
        ["features.collections_gear.input_hint"] = "<<1>> <<2>> Sprunggruppe <<3>> Suche <<4>> Filter: <<5>> <<6>> Sätze durchsuchen",
        ["features.collections_gear.input_hint_flat"] = "<<1>> Suche <<2>> Filter: <<3>> <<4>> Suchsätze",
        ["features.collections_gear.loading"] = "Ausrüstung wird geladen...",
        ["features.collections_gear.monster_sets_6bed3c4"] = "Monster-Sets",
        ["features.collections_gear.mythics_965733d"] = "Mythen",
        ["features.collections_gear.no_bonus_details"] = "Es sind keine Details zum festgelegten Bonus verfügbar.",
        ["features.collections_gear.no_mythic_lead_data"] = "Für dieses mythische Set sind keine Antiquitäten-Spurdaten verfügbar.",
        ["features.collections_gear.no_pieces_are_available_for_this_set_e297c61"] = "Für dieses Set sind keine Teile verfügbar.",
        ["features.collections_gear.no_search_results"] = "Keine Sätze entsprechen der Suche „<<1>>“ und dem ausgewählten Filter.",
        ["features.collections_gear.no_set_selected"] = "Kein Satz ausgewählt",
        ["features.collections_gear.no_sets_match_filter"] = "Keine Sets entsprechen dem gewählten Filter.",
        ["features.collections_gear.perfected_name"] = "<<1>> (perfektioniert)",
        ["features.collections_gear.scale_label"] = "Maßstab",
        ["features.collections_gear.scale_tooltip"] = "Ändert die Größe der gesamten Gear-Sammlungsanzeige.",
        ["features.collections_gear.search_title"] = "AUSRÜSTUNG (<<1>>)",
        ["features.collections_gear.set_bonus"] = "BONUS EINSTELLEN",
        ["features.collections_gear.set_bonuses"] = "Boni festlegen",
        ["features.collections_gear.set_card_label"] = "Karte setzen",
        ["features.collections_gear.set_card_tooltip"] = "Zeigt einen dritten Bereich mit den Bonusdetails des ausgewählten Sets an.",
        ["features.collections_gear.set_collection"] = "Sammlung festlegen",
        ["features.collections_gear.sets_cba9e41"] = "SETZT",
        ["features.collections_gear.show_watermark_label"] = "Wasserzeichen anzeigen",
        ["features.collections_gear.show_watermark_tooltip"] = "Zeigt oder verbirgt das wiederholte Spieler- und Server-Wasserzeichen hinter dem Inhalt der Gear-Sammlung.",
        ["features.collections_gear.summary"] = "<<1>> <<2>>  •  <<3>> / <<4>> Teile",
        ["features.collections_gear.summary_class_sets"] = "Klassensätze",
        ["features.collections_gear.summary_completed_sets"] = "fertige Sets",
        ["features.collections_gear.summary_incomplete_sets"] = "unvollständige Sätze",
        ["features.collections_gear.summary_monster_sets"] = "Monster-Sets",
        ["features.collections_gear.summary_mythics"] = "Mythen",
        ["features.collections_gear.summary_sets"] = "Sätze",
        ["features.collections_gear.title"] = "AUSRÜSTUNG",
        ["features.collections_gear.type_class"] = "KLASSENGEGENSTÄNDE-SET",
        ["features.collections_gear.type_item"] = "ARTIKEL-SET",
        ["features.collections_gear.type_monster"] = "MONSTER-ITEM-SET",
        ["features.collections_gear.type_mythic"] = "MYTHISCHES GEGENSTÄNDE-SET",
        ["features.collections_gear.type_perfected"] = "PERFEKTES ARTIKEL-SET",
        ["features.collections_gear.unknown_lead"] = "Unbekannter Hinweis",
        ["features.collections_gear.unknown_piece"] = "Unbekanntes Teil",
        ["features.collections_gear.unknown_set"] = "Unbekannter Satz",
        ["features.collections_gear.vertical_position_label"] = "Vertikale Position",
        ["features.collections_gear.vertical_position_tooltip"] = "Verschiebt die Anzeige der Gear-Sammlung nach oben oder unten.",
        ["ui.addons_menu.ngear_name"] = "|cFF0000N|r|c007FFFGear|r",
        ["item_locator.apply_search"] = "Suche anwenden",
        ["item_locator.bank"] = "Bank",
        ["item_locator.background_opacity_label"] = "Hintergrundopazität",
        ["item_locator.background_opacity_tooltip"] = "Passt die Deckkraft des Hintergrunds der Gegenstandssuche an.",
        ["item_locator.font_label"] = "Schriftart",
        ["item_locator.font_tooltip"] = "Wählt die Schriftart der Gegenstandssuche aus.",
        ["item_locator.horizontal_position_label"] = "Horizontale Position",
        ["item_locator.horizontal_position_tooltip"] = "Verschiebt die Gegenstandssuche nach links oder rechts.",
        ["item_locator.scale_label"] = "Maßstab",
        ["item_locator.scale_tooltip"] = "Ändert die Größe der gesamten Gegenstandssuche.",
        ["item_locator.vertical_position_label"] = "Vertikale Position",
        ["item_locator.vertical_position_tooltip"] = "Verschiebt die Gegenstandssuche nach oben oder unten.",
        ["item_locator.binding"] = "Bindung",
        ["item_locator.category"] = "Kategorie",
        ["item_locator.craft_bag"] = "Handwerksbeutel",
        ["item_locator.chat_bank"] = "Bank (<<1>>)",
        ["item_locator.chat_character"] = "<<1>> (<<2>>)",
        ["item_locator.chat_message"] = "<<1>> · <<2>>",
        ["item_locator.chat_storage"] = "<<1>> (<<2>>)",
        ["item_locator.champion_level"] = "Champion <<1>>",
        ["item_locator.clear_search"] = "Suche löschen",
        ["item_locator.data_unavailable"] = "Einige gespeicherte Gegenstandsdaten konnten nicht gelesen werden.",
        ["item_locator.date_month_abbreviations"] = "Jan|Feb|Mär|Apr|Mai|Jun|Jul|Aug|Sep|Okt|Nov|Dez",
        ["item_locator.detail_line"] = "|c72BEEB<<1>>:|r <<2>>",
        ["item_locator.details"] = "GEGENSTANDSDETAILS",
        ["item_locator.enchantment"] = "Verzauberung",
        ["item_locator.furniture_vault"] = "Einrichtungsspeicher",
        ["item_locator.house_storage"] = "Hauslager",
        ["item_locator.items"] = "GEGENSTÄNDE",
        ["item_locator.input_hint_actions"] = "<<1>> Suchen · <<2>> · <<3>> Zurück",
        ["item_locator.input_hint_categories"] = "<<1>> Durchsuchen · <<2>> <<3>> Kategorien · <<4>> Suchen · <<5>> · <<6>> Im Chat ausgeben · <<7>> Zurück",
        ["item_locator.input_hint_empty"] = "<<1>> Zurück",
        ["item_locator.input_hint_items"] = "<<1>> Durchsuchen · <<2>> Suchen · <<3>> · <<4>> Im Chat ausgeben · <<5>> Zurück",
        ["item_locator.level"] = "Stufe",
        ["item_locator.location_bank"] = "Bank: <<1>>",
        ["item_locator.location_equipped"] = "<<1>> · Ausgerüstet: <<2>>",
        ["item_locator.location_inventory"] = "<<1>>: <<2>>",
        ["item_locator.location_storage"] = "<<1>>: <<2>>",
        ["item_locator.locations"] = "FUNDORTE",
        ["item_locator.market_prices"] = "MARKTPREISE",
        ["item_locator.no_items"] = "Keine erfassten Gegenstände verfügbar.",
        ["item_locator.no_search_results"] = "Keine Gegenstände entsprechen der Suche „<<1>>“.",
        ["item_locator.no_selection"] = "Kein Gegenstand ausgewählt",
        ["item_locator.log_in_chat"] = "Im Chat ausgeben",
        ["item_locator.price_average"] = "Durchschnittswert",
        ["item_locator.price_maximum"] = "Höchstwert",
        ["item_locator.price_minimum"] = "Mindestwert",
        ["item_locator.roster_not_indexed"] = "Noch nicht indexiert",
        ["item_locator.roster_date"] = "<<1>>-<<2>>-<<3>>",
        ["item_locator.roster_scanned"] = "|cFFFFFF<<1>>:|r\n<<2>>",
        ["item_locator.search_placeholder"] = "Gegenstandsname",
        ["item_locator.search_title"] = "Gegenstände suchen",
        ["item_locator.sort"] = "Sortieren",
        ["item_locator.sort_alphabetical"] = "Alphabetisch",
        ["item_locator.sort_hint"] = "<<1>> Sortierung: <<2>>",
        ["item_locator.sort_quality"] = "Nach Qualität",
        ["item_locator.status"] = "Status",
        ["item_locator.stolen"] = "Gestohlen",
        ["item_locator.style"] = "Stil",
        ["item_locator.summary"] = "<<1>> Gegenstände • <<2>> Varianten",
        ["item_locator.title"] = "GEGENSTANDSSUCHE",
        ["item_locator.title_search"] = "GEGENSTANDSSUCHE (<<1>>)",
        ["item_locator.trait"] = "Eigenschaft",
        ["item_locator.type"] = "Typ",
        ["item_locator.variant_total"] = "<<1>> verfügbar",
        ["item_locator.weight"] = "Gewicht",
        ["ui.navigation.item_categories"] = "Gegenstandskategorien",
        ["ui.navigation.item_categories_tooltip"] = "Lege fest, welche Gegenstandskategorien in der Gegenstandssuche angezeigt werden.",
        ["ui.navigation.item_category_toggle_tooltip"] = "Zeigt diese Kategorie in der Gegenstandssuche an.",
        ["ui.navigation.item_locator"] = "Gegenstandssuche",
        ["ui.navigation.item_locator_tooltip"] = "Finde einen Gegenstand in deinem gesamten Konto",
        ["ui.navigation.scan_items"] = "Gegenstände scannen",
        ["ui.navigation.scan_items_tooltip"] = "Scannt und verfolgt Gegenstände, die dieser Charakter trägt oder ausgerüstet hat, sowie Gegenstände in der gemeinsamen Bank, im Einrichtungsspeicher und im Hauslager.",
        ["ui.navigation.browse_every_reconstructable_gear_set_and_its_collec_86e2576"] = "Durchsuchen Sie jedes rekonstruierbare Ausrüstungsset und seine gesammelten Teile in einer speziellen Sammlungsausstellung.",
        ["ui.navigation.gear_def2b5f"] = "Ausrüstung",
    },
    jp = {
        ["features.collections_gear.search_dialog_placeholder"] = "<<1>> 名前",
        ["features.collections_gear.search_dialog_title"] = "<<1>>を検索",
        ["dialogs.language_reload.message"] = "NGearの言語を変更するにはUIの再読み込みが必要です。今すぐUIを再読み込みしますか？",
        ["dialogs.language_reload.title"] = "言語を変更しますか？",
        ["settings.language.choice.auto"] = "自動",
        ["settings.language.choice.de"] = "Deutsch",
        ["settings.language.choice.en"] = "English",
        ["settings.language.choice.es"] = "Español",
        ["settings.language.choice.fr"] = "Français",
        ["settings.language.choice.jp"] = "日本語",
        ["settings.language.choice.ru"] = "Русский",
        ["settings.language.choice.zh"] = "简体中文",
        ["settings.language.label"] = "言語",
        ["settings.language.tooltip"] = "NGearで使用する言語を選択します。自動ではゲームの言語を使用します。新しい選択はNGear設定を終了した後に適用されます。",
        ["ui.headers.global_options"] = "グローバルオプション",
        ["common.font.antique"] = "アンティーク",
        ["common.font.gamepad_bold"] = "ゲームパッドボールド",
        ["common.font.gamepad_light"] = "ゲームパッドライト",
        ["common.font.gamepad_medium"] = "ゲームパッド媒体",
        ["common.font.handwritten"] = "手書き",
        ["common.font.keyboard_bold"] = "キーボードの太字",
        ["common.font.keyboard_medium"] = "キーボード媒体",
        ["common.item_set"] = "アイテムセット",
        ["common.other"] = "その他",
        ["common.right_stick"] = "右スティック",
        ["common.search"] = "検索",
        ["common.unknown_value"] = "不明",
        ["features.collections_gear.all_sets_6ece2fa"] = "すべてのセット",
        ["features.collections_gear.apply_search_96b8b79"] = "検索の適用",
        ["features.collections_gear.background_opacity_label"] = "背景の不透明度",
        ["features.collections_gear.background_opacity_tooltip"] = "Gear コレクションの表示背景の不透明度を調整します。",
        ["features.collections_gear.class_sets_d8f88fa"] = "クラスセット",
        ["features.collections_gear.clear_search_87e328d"] = "検索をクリア",
        ["features.collections_gear.completed_sets_5094bc4"] = "完成したセット",
        ["features.collections_gear.font_label"] = "フォント",
        ["features.collections_gear.font_tooltip"] = "Gear コレクションの表示で使用されるフォントを選択します。",
        ["features.collections_gear.horizontal_position_label"] = "水平位置",
        ["features.collections_gear.horizontal_position_tooltip"] = "ギアコレクションの表示を左右に移動します。",
        ["features.collections_gear.incomplete_sets_a81fe8d"] = "不完全なセット",
        ["features.collections_gear.input_hint"] = "<<1>> <<2>> ジャンプ グループ <<3>> 検索 <<4>> フィルタ: <<5>> <<6>> セットの参照",
        ["features.collections_gear.input_hint_flat"] = "<<1>> <<2>> フィルタを検索: <<3>> <<4>> セットを参照",
        ["features.collections_gear.loading"] = "装備を読み込み中...",
        ["features.collections_gear.monster_sets_6bed3c4"] = "モンスターセット",
        ["features.collections_gear.mythics_965733d"] = "神話",
        ["features.collections_gear.no_bonus_details"] = "セットボーナスの詳細はありません。",
        ["features.collections_gear.no_mythic_lead_data"] = "この神話アイテムに利用可能な古遺物の手掛かりデータはありません。",
        ["features.collections_gear.no_pieces_are_available_for_this_set_e297c61"] = "このセットで利用できるピースはありません。",
        ["features.collections_gear.no_search_results"] = "検索 '<<1>>' および選択されたフィルターに一致するセットはありません。",
        ["features.collections_gear.no_set_selected"] = "セットが選択されていません",
        ["features.collections_gear.no_sets_match_filter"] = "選択したフィルターに一致するセットはありません。",
        ["features.collections_gear.perfected_name"] = "<<1>> (完成)",
        ["features.collections_gear.scale_label"] = "スケール",
        ["features.collections_gear.scale_tooltip"] = "ギアコレクションの表示全体のサイズを変更します。",
        ["features.collections_gear.search_title"] = "ギア (<<1>>)",
        ["features.collections_gear.set_bonus"] = "セットボーナス",
        ["features.collections_gear.set_bonuses"] = "セットボーナス",
        ["features.collections_gear.set_card_label"] = "セットカード",
        ["features.collections_gear.set_card_tooltip"] = "選択したセットのボーナスの詳細を含む 3 番目のペインを表示します。",
        ["features.collections_gear.set_collection"] = "セットコレクション",
        ["features.collections_gear.sets_cba9e41"] = "セット",
        ["features.collections_gear.show_watermark_label"] = "透かしを表示する",
        ["features.collections_gear.show_watermark_tooltip"] = "Gear コレクション コンテンツの背後に繰り返されるプレーヤーとサーバーの透かしを表示または非表示にします。",
        ["features.collections_gear.summary"] = "<<1>> <<2>>  •  <<3>> / <<4>> 部位",
        ["features.collections_gear.summary_class_sets"] = "クラスセット",
        ["features.collections_gear.summary_completed_sets"] = "完成したセット",
        ["features.collections_gear.summary_incomplete_sets"] = "不完全な集合",
        ["features.collections_gear.summary_monster_sets"] = "モンスターセット",
        ["features.collections_gear.summary_mythics"] = "神話",
        ["features.collections_gear.summary_sets"] = "セット",
        ["features.collections_gear.title"] = "ギア",
        ["features.collections_gear.type_class"] = "クラスアイテムセット",
        ["features.collections_gear.type_item"] = "アイテムセット",
        ["features.collections_gear.type_monster"] = "モンスターアイテムセット",
        ["features.collections_gear.type_mythic"] = "ミシックアイテムセット",
        ["features.collections_gear.type_perfected"] = "完璧なアイテムセット",
        ["features.collections_gear.unknown_lead"] = "不明なリード",
        ["features.collections_gear.unknown_piece"] = "不明な部位",
        ["features.collections_gear.unknown_set"] = "不明なセット",
        ["features.collections_gear.vertical_position_label"] = "縦位置",
        ["features.collections_gear.vertical_position_tooltip"] = "ギアコレクションの表示を上下に移動します。",
        ["ui.addons_menu.ngear_name"] = "|cFF0000N|r|c007FFFGear|r",
        ["item_locator.apply_search"] = "検索を適用",
        ["item_locator.bank"] = "銀行",
        ["item_locator.background_opacity_label"] = "背景の不透明度",
        ["item_locator.background_opacity_tooltip"] = "アイテム検索の背景の不透明度を調整します。",
        ["item_locator.font_label"] = "フォント",
        ["item_locator.font_tooltip"] = "アイテム検索で使用するフォントを選択します。",
        ["item_locator.horizontal_position_label"] = "水平位置",
        ["item_locator.horizontal_position_tooltip"] = "アイテム検索を左右に移動します。",
        ["item_locator.scale_label"] = "スケール",
        ["item_locator.scale_tooltip"] = "アイテム検索全体のサイズを変更します。",
        ["item_locator.vertical_position_label"] = "縦位置",
        ["item_locator.vertical_position_tooltip"] = "アイテム検索を上下に移動します。",
        ["item_locator.binding"] = "譲渡制限",
        ["item_locator.category"] = "カテゴリー",
        ["item_locator.craft_bag"] = "クラフトバッグ",
        ["item_locator.chat_bank"] = "銀行 (<<1>>)",
        ["item_locator.chat_character"] = "<<1>> (<<2>>)",
        ["item_locator.chat_message"] = "<<1>> · <<2>>",
        ["item_locator.chat_storage"] = "<<1>> (<<2>>)",
        ["item_locator.champion_level"] = "チャンピオン <<1>>",
        ["item_locator.clear_search"] = "検索をクリア",
        ["item_locator.data_unavailable"] = "保存済みの一部のアイテムデータを読み取れませんでした。",
        ["item_locator.date_month_abbreviations"] = "1月|2月|3月|4月|5月|6月|7月|8月|9月|10月|11月|12月",
        ["item_locator.detail_line"] = "|c72BEEB<<1>>:|r <<2>>",
        ["item_locator.details"] = "アイテム詳細",
        ["item_locator.enchantment"] = "付呪",
        ["item_locator.furniture_vault"] = "家具の宝物庫",
        ["item_locator.house_storage"] = "ハウジング収納",
        ["item_locator.items"] = "アイテム",
        ["item_locator.input_hint_actions"] = "<<1>> 検索 · <<2>> · <<3>> 戻る",
        ["item_locator.input_hint_categories"] = "<<1>> 閲覧 · <<2>> <<3>> カテゴリー · <<4>> 検索 · <<5>> · <<6>> チャットに表示 · <<7>> 戻る",
        ["item_locator.input_hint_empty"] = "<<1>> 戻る",
        ["item_locator.input_hint_items"] = "<<1>> 閲覧 · <<2>> 検索 · <<3>> · <<4>> チャットに表示 · <<5>> 戻る",
        ["item_locator.level"] = "レベル",
        ["item_locator.location_bank"] = "銀行: <<1>>",
        ["item_locator.location_equipped"] = "<<1>> · 装備中: <<2>>",
        ["item_locator.location_inventory"] = "<<1>>: <<2>>",
        ["item_locator.location_storage"] = "<<1>>: <<2>>",
        ["item_locator.locations"] = "保管場所",
        ["item_locator.market_prices"] = "市場価格",
        ["item_locator.no_items"] = "追跡済みのアイテムはありません。",
        ["item_locator.no_search_results"] = "「<<1>>」に一致するアイテムはありません。",
        ["item_locator.no_selection"] = "アイテムが選択されていません",
        ["item_locator.log_in_chat"] = "チャットに表示",
        ["item_locator.price_average"] = "平均価格",
        ["item_locator.price_maximum"] = "最高価格",
        ["item_locator.price_minimum"] = "最低価格",
        ["item_locator.roster_not_indexed"] = "まだインデックスされていません",
        ["item_locator.roster_date"] = "<<1>>-<<2>>-<<3>>",
        ["item_locator.roster_scanned"] = "|cFFFFFF<<1>>：|r\n<<2>>",
        ["item_locator.search_placeholder"] = "アイテム名",
        ["item_locator.search_title"] = "アイテムを検索",
        ["item_locator.sort"] = "並べ替え",
        ["item_locator.sort_alphabetical"] = "名前順",
        ["item_locator.sort_hint"] = "<<1>> 並べ替え: <<2>>",
        ["item_locator.sort_quality"] = "品質順",
        ["item_locator.status"] = "状態",
        ["item_locator.stolen"] = "盗品",
        ["item_locator.style"] = "スタイル",
        ["item_locator.summary"] = "<<1>>個 • <<2>>種類",
        ["item_locator.title"] = "アイテム検索",
        ["item_locator.title_search"] = "アイテム検索 (<<1>>)",
        ["item_locator.trait"] = "特性",
        ["item_locator.type"] = "タイプ",
        ["item_locator.variant_total"] = "<<1>>個利用可能",
        ["item_locator.weight"] = "重量",
        ["ui.navigation.item_categories"] = "アイテムカテゴリ",
        ["ui.navigation.item_categories_tooltip"] = "アイテム検索に表示するアイテムカテゴリを選択します。",
        ["ui.navigation.item_category_toggle_tooltip"] = "このカテゴリをアイテム検索に表示します。",
        ["ui.navigation.item_locator"] = "アイテム検索",
        ["ui.navigation.item_locator_tooltip"] = "アカウント全体からアイテムを探します",
        ["ui.navigation.scan_items"] = "アイテムをスキャン",
        ["ui.navigation.scan_items_tooltip"] = "このキャラクターの所持品と装備品、および共有銀行、家具の宝物庫、ハウジング収納内のアイテムをスキャンして追跡します。",
        ["ui.navigation.browse_every_reconstructable_gear_set_and_its_collec_86e2576"] = "専用のコレクション ディスプレイで、すべての再構成可能なギア セットとその収集品を閲覧できます。",
        ["ui.navigation.gear_def2b5f"] = "ギア",
    },
    es = {
        ["features.collections_gear.search_dialog_placeholder"] = "<<1>> nombre",
        ["features.collections_gear.search_dialog_title"] = "Buscar <<1>>",
        ["dialogs.language_reload.message"] = "Cambiar el idioma de NGear requiere recargar la interfaz. ¿Quieres recargarla ahora?",
        ["dialogs.language_reload.title"] = "¿Cambiar el idioma?",
        ["settings.language.choice.auto"] = "Automático",
        ["settings.language.choice.de"] = "Deutsch",
        ["settings.language.choice.en"] = "English",
        ["settings.language.choice.es"] = "Español",
        ["settings.language.choice.fr"] = "Français",
        ["settings.language.choice.jp"] = "日本語",
        ["settings.language.choice.ru"] = "Русский",
        ["settings.language.choice.zh"] = "简体中文",
        ["settings.language.label"] = "Idioma",
        ["settings.language.tooltip"] = "Selecciona el idioma que usa NGear. Automático usa el idioma del juego. La nueva selección se aplica después de salir de los ajustes de NGear.",
        ["ui.headers.global_options"] = "Opciones globales",
        ["common.font.antique"] = "antiguo",
        ["common.font.gamepad_bold"] = "Mando en negrita",
        ["common.font.gamepad_light"] = "Luz del mando",
        ["common.font.gamepad_medium"] = "Mando medio",
        ["common.font.handwritten"] = "escrito a mano",
        ["common.font.keyboard_bold"] = "Teclado en negrita",
        ["common.font.keyboard_medium"] = "Medio de teclado",
        ["common.item_set"] = "conjunto de elementos",
        ["common.other"] = "Otro",
        ["common.right_stick"] = "Joystick derecho",
        ["common.search"] = "Buscar",
        ["common.unknown_value"] = "Desconocido",
        ["features.collections_gear.all_sets_6ece2fa"] = "Todos los conjuntos",
        ["features.collections_gear.apply_search_96b8b79"] = "Aplicar búsqueda",
        ["features.collections_gear.background_opacity_label"] = "Opacidad del fondo",
        ["features.collections_gear.background_opacity_tooltip"] = "Ajusta la opacidad del fondo de visualización de la colección Gear.",
        ["features.collections_gear.class_sets_d8f88fa"] = "conjuntos de clases",
        ["features.collections_gear.clear_search_87e328d"] = "Borrar búsqueda",
        ["features.collections_gear.completed_sets_5094bc4"] = "Conjuntos completos",
        ["features.collections_gear.font_label"] = "fuente",
        ["features.collections_gear.font_tooltip"] = "Elige la fuente utilizada por la visualización de la colección Gear.",
        ["features.collections_gear.horizontal_position_label"] = "posición horizontal",
        ["features.collections_gear.horizontal_position_tooltip"] = "Mueve la visualización de la colección Gear hacia la izquierda o hacia la derecha.",
        ["features.collections_gear.incomplete_sets_a81fe8d"] = "Conjuntos incompletos",
        ["features.collections_gear.input_hint"] = "<<1>> <<2>> Saltar grupo <<3>> Buscar <<4>> Filtro: <<5>> <<6>> Buscar conjuntos",
        ["features.collections_gear.input_hint_flat"] = "<<1>> Buscar <<2>> Filtro: <<3>> <<4>> Buscar conjuntos",
        ["features.collections_gear.loading"] = "Cargando equipo...",
        ["features.collections_gear.monster_sets_6bed3c4"] = "conjuntos de monstruos",
        ["features.collections_gear.mythics_965733d"] = "míticos",
        ["features.collections_gear.no_bonus_details"] = "No hay detalles de bonificación establecidos disponibles.",
        ["features.collections_gear.no_mythic_lead_data"] = "No hay datos de pistas de antigüedades disponibles para este mítico.",
        ["features.collections_gear.no_pieces_are_available_for_this_set_e297c61"] = "No hay piezas disponibles para este conjunto.",
        ["features.collections_gear.no_search_results"] = "Ningún conjunto coincide con la búsqueda '<<1>>' y el filtro seleccionado.",
        ["features.collections_gear.no_set_selected"] = "Ningún conjunto seleccionado",
        ["features.collections_gear.no_sets_match_filter"] = "Ningún conjunto coincide con el filtro seleccionado.",
        ["features.collections_gear.perfected_name"] = "<<1>> (perfeccionado)",
        ["features.collections_gear.scale_label"] = "Escala",
        ["features.collections_gear.scale_tooltip"] = "Cambia el tamaño de toda la visualización de la colección Gear.",
        ["features.collections_gear.search_title"] = "EQUIPO (<<1>>)",
        ["features.collections_gear.set_bonus"] = "BONO ESTABLECIDO",
        ["features.collections_gear.set_bonuses"] = "BONOS ESTABLECIDOS",
        ["features.collections_gear.set_card_label"] = "Establecer tarjeta",
        ["features.collections_gear.set_card_tooltip"] = "Muestra un tercer panel con los detalles de bonificación del conjunto seleccionado.",
        ["features.collections_gear.set_collection"] = "Colección de conjuntos",
        ["features.collections_gear.sets_cba9e41"] = "CONJUNTOS",
        ["features.collections_gear.show_watermark_label"] = "Mostrar marca de agua",
        ["features.collections_gear.show_watermark_tooltip"] = "Muestra u oculta la marca de agua repetida del jugador y del servidor detrás del contenido de la colección Gear.",
        ["features.collections_gear.summary"] = "<<1>> <<2>>  •  <<3>> / <<4>> piezas",
        ["features.collections_gear.summary_class_sets"] = "conjuntos de clases",
        ["features.collections_gear.summary_completed_sets"] = "conjuntos completos",
        ["features.collections_gear.summary_incomplete_sets"] = "conjuntos incompletos",
        ["features.collections_gear.summary_monster_sets"] = "conjuntos de monstruos",
        ["features.collections_gear.summary_mythics"] = "míticos",
        ["features.collections_gear.summary_sets"] = "conjuntos",
        ["features.collections_gear.title"] = "EQUIPO",
        ["features.collections_gear.type_class"] = "CONJUNTO DE ARTÍCULOS DE CLASE",
        ["features.collections_gear.type_item"] = "CONJUNTO DE ARTÍCULOS",
        ["features.collections_gear.type_monster"] = "CONJUNTO DE ARTÍCULOS DE MONSTRUO",
        ["features.collections_gear.type_mythic"] = "CONJUNTO DE ARTÍCULOS MÍTICOS",
        ["features.collections_gear.type_perfected"] = "CONJUNTO DE ARTÍCULOS PERFECCIONADOS",
        ["features.collections_gear.unknown_lead"] = "Pista desconocida",
        ["features.collections_gear.unknown_piece"] = "Pieza desconocida",
        ["features.collections_gear.unknown_set"] = "Conjunto desconocido",
        ["features.collections_gear.vertical_position_label"] = "posición vertical",
        ["features.collections_gear.vertical_position_tooltip"] = "Mueve la visualización de la colección Gear hacia arriba o hacia abajo.",
        ["ui.addons_menu.ngear_name"] = "|cFF0000N|r|c007FFFGear|r",
        ["item_locator.apply_search"] = "Aplicar búsqueda",
        ["item_locator.bank"] = "Banco",
        ["item_locator.background_opacity_label"] = "Opacidad del fondo",
        ["item_locator.background_opacity_tooltip"] = "Ajusta la opacidad del fondo del localizador de objetos.",
        ["item_locator.font_label"] = "Fuente",
        ["item_locator.font_tooltip"] = "Elige la fuente utilizada por el localizador de objetos.",
        ["item_locator.horizontal_position_label"] = "Posición horizontal",
        ["item_locator.horizontal_position_tooltip"] = "Mueve el localizador de objetos hacia la izquierda o la derecha.",
        ["item_locator.scale_label"] = "Escala",
        ["item_locator.scale_tooltip"] = "Cambia el tamaño de todo el localizador de objetos.",
        ["item_locator.vertical_position_label"] = "Posición vertical",
        ["item_locator.vertical_position_tooltip"] = "Mueve el localizador de objetos hacia arriba o hacia abajo.",
        ["item_locator.binding"] = "Vinculación",
        ["item_locator.category"] = "Categoría",
        ["item_locator.craft_bag"] = "Bolsa de artesanía",
        ["item_locator.chat_bank"] = "Banco (<<1>>)",
        ["item_locator.chat_character"] = "<<1>> (<<2>>)",
        ["item_locator.chat_message"] = "<<1>> · <<2>>",
        ["item_locator.chat_storage"] = "<<1>> (<<2>>)",
        ["item_locator.champion_level"] = "Campeón <<1>>",
        ["item_locator.clear_search"] = "Borrar búsqueda",
        ["item_locator.data_unavailable"] = "No se pudieron leer algunos datos de objetos guardados.",
        ["item_locator.date_month_abbreviations"] = "ene|feb|mar|abr|may|jun|jul|ago|sept|oct|nov|dic",
        ["item_locator.detail_line"] = "|c72BEEB<<1>>:|r <<2>>",
        ["item_locator.details"] = "DETALLES DEL OBJETO",
        ["item_locator.enchantment"] = "Encantamiento",
        ["item_locator.furniture_vault"] = "Cámara de mobiliario",
        ["item_locator.house_storage"] = "Almacenamiento de casa",
        ["item_locator.items"] = "OBJETOS",
        ["item_locator.input_hint_actions"] = "<<1>> Buscar · <<2>> · <<3>> Atrás",
        ["item_locator.input_hint_categories"] = "<<1>> Explorar · <<2>> <<3>> Categorías · <<4>> Buscar · <<5>> · <<6>> Mostrar en el chat · <<7>> Atrás",
        ["item_locator.input_hint_empty"] = "<<1>> Atrás",
        ["item_locator.input_hint_items"] = "<<1>> Explorar · <<2>> Buscar · <<3>> · <<4>> Mostrar en el chat · <<5>> Atrás",
        ["item_locator.level"] = "Nivel",
        ["item_locator.location_bank"] = "Banco: <<1>>",
        ["item_locator.location_equipped"] = "<<1>> · Equipado: <<2>>",
        ["item_locator.location_inventory"] = "<<1>>: <<2>>",
        ["item_locator.location_storage"] = "<<1>>: <<2>>",
        ["item_locator.locations"] = "UBICACIONES",
        ["item_locator.market_prices"] = "PRECIOS DE MERCADO",
        ["item_locator.no_items"] = "No hay objetos rastreados disponibles.",
        ["item_locator.no_search_results"] = "Ningún objeto coincide con la búsqueda «<<1>>».",
        ["item_locator.no_selection"] = "Ningún objeto seleccionado",
        ["item_locator.log_in_chat"] = "Mostrar en el chat",
        ["item_locator.price_average"] = "Valor medio",
        ["item_locator.price_maximum"] = "Valor máximo",
        ["item_locator.price_minimum"] = "Valor mínimo",
        ["item_locator.roster_not_indexed"] = "Aún no se ha indexado",
        ["item_locator.roster_date"] = "<<1>>-<<2>>-<<3>>",
        ["item_locator.roster_scanned"] = "|cFFFFFF<<1>>:|r\n<<2>>",
        ["item_locator.search_placeholder"] = "Nombre del objeto",
        ["item_locator.search_title"] = "Buscar objetos",
        ["item_locator.sort"] = "Ordenar",
        ["item_locator.sort_alphabetical"] = "Alfabéticamente",
        ["item_locator.sort_hint"] = "<<1>> Orden: <<2>>",
        ["item_locator.sort_quality"] = "Por calidad",
        ["item_locator.status"] = "Estado",
        ["item_locator.stolen"] = "Robado",
        ["item_locator.style"] = "Estilo",
        ["item_locator.summary"] = "<<1>> objetos • <<2>> variantes",
        ["item_locator.title"] = "LOCALIZADOR DE OBJETOS",
        ["item_locator.title_search"] = "LOCALIZADOR DE OBJETOS (<<1>>)",
        ["item_locator.trait"] = "Rasgo",
        ["item_locator.type"] = "Tipo",
        ["item_locator.variant_total"] = "<<1>> disponibles",
        ["item_locator.weight"] = "Peso",
        ["ui.navigation.item_categories"] = "Categorías de objetos",
        ["ui.navigation.item_categories_tooltip"] = "Elige qué categorías de objetos aparecen en el localizador de objetos.",
        ["ui.navigation.item_category_toggle_tooltip"] = "Muestra esta categoría en el localizador de objetos.",
        ["ui.navigation.item_locator"] = "Localizador de objetos",
        ["ui.navigation.item_locator_tooltip"] = "Localiza un objeto en toda tu cuenta",
        ["ui.navigation.scan_items"] = "Escanear objetos",
        ["ui.navigation.scan_items_tooltip"] = "Escanea y rastrea los objetos que lleva o equipa este personaje y los objetos del banco compartido, la cámara de mobiliario y el almacenamiento de casa.",
        ["ui.navigation.browse_every_reconstructable_gear_set_and_its_collec_86e2576"] = "Explore cada conjunto de equipo reconstruible y sus piezas recolectadas en una exhibición de colección dedicada.",
        ["ui.navigation.gear_def2b5f"] = "Equipo",
    },
    ru = {
        ["features.collections_gear.search_dialog_placeholder"] = "<<1>> имя",
        ["features.collections_gear.search_dialog_title"] = "Поиск <<1>>",
        ["dialogs.language_reload.message"] = "Чтобы изменить язык NGear, необходимо перезагрузить интерфейс. Перезагрузить интерфейс сейчас?",
        ["dialogs.language_reload.title"] = "Изменить язык?",
        ["settings.language.choice.auto"] = "Авто",
        ["settings.language.choice.de"] = "Deutsch",
        ["settings.language.choice.en"] = "English",
        ["settings.language.choice.es"] = "Español",
        ["settings.language.choice.fr"] = "Français",
        ["settings.language.choice.jp"] = "日本語",
        ["settings.language.choice.ru"] = "Русский",
        ["settings.language.choice.zh"] = "简体中文",
        ["settings.language.label"] = "Язык",
        ["settings.language.tooltip"] = "Выбирает язык NGear. Авто использует язык игры. Новый выбор применяется после выхода из настроек NGear.",
        ["ui.headers.global_options"] = "Общие настройки",
        ["common.font.antique"] = "Антиквариат",
        ["common.font.gamepad_bold"] = "Геймпад жирный",
        ["common.font.gamepad_light"] = "Подсветка геймпада",
        ["common.font.gamepad_medium"] = "Геймпад средний",
        ["common.font.handwritten"] = "Рукописный",
        ["common.font.keyboard_bold"] = "Клавиатура жирная",
        ["common.font.keyboard_medium"] = "Клавиатура средняя",
        ["common.item_set"] = "Набор предметов",
        ["common.other"] = "Другое",
        ["common.right_stick"] = "Правый джойстик",
        ["common.search"] = "Поиск",
        ["common.unknown_value"] = "Неизвестно",
        ["features.collections_gear.all_sets_6ece2fa"] = "Все наборы",
        ["features.collections_gear.apply_search_96b8b79"] = "Применить поиск",
        ["features.collections_gear.background_opacity_label"] = "Непрозрачность фона",
        ["features.collections_gear.background_opacity_tooltip"] = "Регулирует непрозрачность фона отображения коллекции Gear.",
        ["features.collections_gear.class_sets_d8f88fa"] = "Наборы классов",
        ["features.collections_gear.clear_search_87e328d"] = "Очистить поиск",
        ["features.collections_gear.completed_sets_5094bc4"] = "Готовые наборы",
        ["features.collections_gear.font_label"] = "Шрифт",
        ["features.collections_gear.font_tooltip"] = "Выбор шрифта, используемого при отображении коллекции Gear.",
        ["features.collections_gear.horizontal_position_label"] = "Горизонтальное положение",
        ["features.collections_gear.horizontal_position_tooltip"] = "Перемещает отображение коллекции Gear влево или вправо.",
        ["features.collections_gear.incomplete_sets_a81fe8d"] = "Неполные наборы",
        ["features.collections_gear.input_hint"] = "<<1>> <<2>> Группа переходов <<3>> Поиск <<4>> Фильтр: <<5>> <<6>> Просмотр наборов",
        ["features.collections_gear.input_hint_flat"] = "<<1>> Поиск <<2>> Фильтр: <<3>> <<4>> Просмотр наборов",
        ["features.collections_gear.loading"] = "Загрузка снаряжения...",
        ["features.collections_gear.monster_sets_6bed3c4"] = "Наборы монстров",
        ["features.collections_gear.mythics_965733d"] = "Мифы",
        ["features.collections_gear.no_bonus_details"] = "Детали набора бонусов отсутствуют.",
        ["features.collections_gear.no_mythic_lead_data"] = "Для этого мифического предмета нет данных о зацепках реликвий.",
        ["features.collections_gear.no_pieces_are_available_for_this_set_e297c61"] = "В этом наборе нет деталей.",
        ["features.collections_gear.no_search_results"] = "Нет наборов, соответствующих запросу '<<1>>' и выбранному фильтру.",
        ["features.collections_gear.no_set_selected"] = "Набор не выбран",
        ["features.collections_gear.no_sets_match_filter"] = "Нет комплектов, соответствующих выбранному фильтру.",
        ["features.collections_gear.perfected_name"] = "<<1>> (улучшено)",
        ["features.collections_gear.scale_label"] = "Масштаб",
        ["features.collections_gear.scale_tooltip"] = "Изменяет размер всей коллекции Gear.",
        ["features.collections_gear.search_title"] = "СНАРЯЖЕНИЕ (<<1>>)",
        ["features.collections_gear.set_bonus"] = "НАБОР БОНУСА",
        ["features.collections_gear.set_bonuses"] = "НАБОР БОНУСОВ",
        ["features.collections_gear.set_card_label"] = "Установить карту",
        ["features.collections_gear.set_card_tooltip"] = "Показывает третью панель с подробной информацией о бонусах выбранного набора.",
        ["features.collections_gear.set_collection"] = "Коллекция наборов",
        ["features.collections_gear.sets_cba9e41"] = "НАБОРЫ",
        ["features.collections_gear.show_watermark_label"] = "Показать водяной знак",
        ["features.collections_gear.show_watermark_tooltip"] = "Показывает или скрывает повторяющийся водяной знак игрока и сервера за содержимым коллекции Gear.",
        ["features.collections_gear.summary"] = "<<1>> <<2>>  •  <<3>> / <<4>> частей",
        ["features.collections_gear.summary_class_sets"] = "Наборы классов",
        ["features.collections_gear.summary_completed_sets"] = "готовые наборы",
        ["features.collections_gear.summary_incomplete_sets"] = "неполные наборы",
        ["features.collections_gear.summary_monster_sets"] = "Наборы монстров",
        ["features.collections_gear.summary_mythics"] = "Мифы",
        ["features.collections_gear.summary_sets"] = "наборы",
        ["features.collections_gear.title"] = "СНАРЯЖЕНИЕ",
        ["features.collections_gear.type_class"] = "НАБОР ПУНКТОВ КЛАССА",
        ["features.collections_gear.type_item"] = "НАБОР ПУНКТОВ",
        ["features.collections_gear.type_monster"] = "НАБОР ПРЕДМЕТОВ «МОНСТР»",
        ["features.collections_gear.type_mythic"] = "МИФИЧЕСКИЙ НАБОР ПРЕДМЕТОВ",
        ["features.collections_gear.type_perfected"] = "СОВЕРШЕННЫЙ НАБОР ПРЕДМЕТОВ",
        ["features.collections_gear.unknown_lead"] = "Неизвестный лидер",
        ["features.collections_gear.unknown_piece"] = "Неизвестная часть",
        ["features.collections_gear.unknown_set"] = "Неизвестный набор",
        ["features.collections_gear.vertical_position_label"] = "Вертикальное положение",
        ["features.collections_gear.vertical_position_tooltip"] = "Перемещает отображение коллекции Gear вверх или вниз.",
        ["ui.addons_menu.ngear_name"] = "|cFF0000N|r|c007FFFGear|r",
        ["item_locator.apply_search"] = "Применить поиск",
        ["item_locator.bank"] = "Банк",
        ["item_locator.background_opacity_label"] = "Непрозрачность фона",
        ["item_locator.background_opacity_tooltip"] = "Регулирует непрозрачность фона поиска предметов.",
        ["item_locator.font_label"] = "Шрифт",
        ["item_locator.font_tooltip"] = "Выбирает шрифт для поиска предметов.",
        ["item_locator.horizontal_position_label"] = "Горизонтальное положение",
        ["item_locator.horizontal_position_tooltip"] = "Перемещает поиск предметов влево или вправо.",
        ["item_locator.scale_label"] = "Масштаб",
        ["item_locator.scale_tooltip"] = "Изменяет размер всего окна поиска предметов.",
        ["item_locator.vertical_position_label"] = "Вертикальное положение",
        ["item_locator.vertical_position_tooltip"] = "Перемещает поиск предметов вверх или вниз.",
        ["item_locator.binding"] = "Привязка",
        ["item_locator.category"] = "Категория",
        ["item_locator.craft_bag"] = "Ремесленная сумка",
        ["item_locator.chat_bank"] = "Банк (<<1>>)",
        ["item_locator.chat_character"] = "<<1>> (<<2>>)",
        ["item_locator.chat_message"] = "<<1>> · <<2>>",
        ["item_locator.chat_storage"] = "<<1>> (<<2>>)",
        ["item_locator.champion_level"] = "Чемпион <<1>>",
        ["item_locator.clear_search"] = "Очистить поиск",
        ["item_locator.data_unavailable"] = "Некоторые сохранённые данные предметов не удалось прочитать.",
        ["item_locator.date_month_abbreviations"] = "янв|фев|мар|апр|май|июн|июл|авг|сен|окт|ноя|дек",
        ["item_locator.detail_line"] = "|c72BEEB<<1>>:|r <<2>>",
        ["item_locator.details"] = "СВЕДЕНИЯ О ПРЕДМЕТЕ",
        ["item_locator.enchantment"] = "Зачарование",
        ["item_locator.furniture_vault"] = "Хранилище предметов обстановки",
        ["item_locator.house_storage"] = "Домашнее хранилище",
        ["item_locator.items"] = "ПРЕДМЕТЫ",
        ["item_locator.input_hint_actions"] = "<<1>> Поиск · <<2>> · <<3>> Назад",
        ["item_locator.input_hint_categories"] = "<<1>> Просмотр · <<2>> <<3>> Категории · <<4>> Поиск · <<5>> · <<6>> Вывести в чат · <<7>> Назад",
        ["item_locator.input_hint_empty"] = "<<1>> Назад",
        ["item_locator.input_hint_items"] = "<<1>> Просмотр · <<2>> Поиск · <<3>> · <<4>> Вывести в чат · <<5>> Назад",
        ["item_locator.level"] = "Уровень",
        ["item_locator.location_bank"] = "Банк: <<1>>",
        ["item_locator.location_equipped"] = "<<1>> · Экипировано: <<2>>",
        ["item_locator.location_inventory"] = "<<1>>: <<2>>",
        ["item_locator.location_storage"] = "<<1>>: <<2>>",
        ["item_locator.locations"] = "МЕСТОНАХОЖДЕНИЕ",
        ["item_locator.market_prices"] = "РЫНОЧНЫЕ ЦЕНЫ",
        ["item_locator.no_items"] = "Нет доступных отслеживаемых предметов.",
        ["item_locator.no_search_results"] = "Нет предметов, соответствующих запросу «<<1>>».",
        ["item_locator.no_selection"] = "Предмет не выбран",
        ["item_locator.log_in_chat"] = "Вывести в чат",
        ["item_locator.price_average"] = "Средняя стоимость",
        ["item_locator.price_maximum"] = "Максимальная стоимость",
        ["item_locator.price_minimum"] = "Минимальная стоимость",
        ["item_locator.roster_not_indexed"] = "Ещё не проиндексировано",
        ["item_locator.roster_date"] = "<<1>>-<<2>>-<<3>>",
        ["item_locator.roster_scanned"] = "|cFFFFFF<<1>>:|r\n<<2>>",
        ["item_locator.search_placeholder"] = "Название предмета",
        ["item_locator.search_title"] = "Поиск предметов",
        ["item_locator.sort"] = "Сортировка",
        ["item_locator.sort_alphabetical"] = "По алфавиту",
        ["item_locator.sort_hint"] = "<<1>> Сортировка: <<2>>",
        ["item_locator.sort_quality"] = "По качеству",
        ["item_locator.status"] = "Состояние",
        ["item_locator.stolen"] = "Украдено",
        ["item_locator.style"] = "Стиль",
        ["item_locator.summary"] = "Предметов: <<1>> • вариантов: <<2>>",
        ["item_locator.title"] = "ПОИСК ПРЕДМЕТОВ",
        ["item_locator.title_search"] = "ПОИСК ПРЕДМЕТОВ (<<1>>)",
        ["item_locator.trait"] = "Особенность",
        ["item_locator.type"] = "Тип",
        ["item_locator.variant_total"] = "Доступно: <<1>>",
        ["item_locator.weight"] = "Вес",
        ["ui.navigation.item_categories"] = "Категории предметов",
        ["ui.navigation.item_categories_tooltip"] = "Выберите категории предметов, которые будут отображаться в поиске предметов.",
        ["ui.navigation.item_category_toggle_tooltip"] = "Показывать эту категорию в поиске предметов.",
        ["ui.navigation.item_locator"] = "Поиск предметов",
        ["ui.navigation.item_locator_tooltip"] = "Найдите предмет среди всех персонажей учётной записи",
        ["ui.navigation.scan_items"] = "Сканировать предметы",
        ["ui.navigation.scan_items_tooltip"] = "Сканирует и отслеживает предметы в инвентаре и экипировке этого персонажа, а также в общем банке, хранилище предметов обстановки и домашнем хранилище.",
        ["ui.navigation.browse_every_reconstructable_gear_set_and_its_collec_86e2576"] = "Просмотрите каждый реконструируемый комплект снаряжения и его части на специальной выставке.",
        ["ui.navigation.gear_def2b5f"] = "Снаряжение",
    },
    zh = {
        ["features.collections_gear.search_dialog_placeholder"] = "<<1>>名称",
        ["features.collections_gear.search_dialog_title"] = "搜索<<1>>",
        ["dialogs.language_reload.message"] = "更改 NGear 的语言需要重新加载界面。现在重新加载界面吗？",
        ["dialogs.language_reload.title"] = "更改语言？",
        ["settings.language.choice.auto"] = "自动",
        ["settings.language.choice.de"] = "Deutsch",
        ["settings.language.choice.en"] = "English",
        ["settings.language.choice.es"] = "Español",
        ["settings.language.choice.fr"] = "Français",
        ["settings.language.choice.jp"] = "日本語",
        ["settings.language.choice.ru"] = "Русский",
        ["settings.language.choice.zh"] = "简体中文",
        ["settings.language.label"] = "语言",
        ["settings.language.tooltip"] = "选择 NGear 使用的语言。选择“自动”时会使用游戏语言。退出 NGear 设置后将应用新选择。",
        ["ui.headers.global_options"] = "全局选项",
        ["common.font.antique"] = "古董",
        ["common.font.gamepad_bold"] = "游戏手柄粗体",
        ["common.font.gamepad_light"] = "游戏手柄灯",
        ["common.font.gamepad_medium"] = "游戏手柄中号",
        ["common.font.handwritten"] = "手写",
        ["common.font.keyboard_bold"] = "键盘粗体",
        ["common.font.keyboard_medium"] = "键盘介质",
        ["common.item_set"] = "物品套装",
        ["common.other"] = "其他",
        ["common.right_stick"] = "右摇杆",
        ["common.search"] = "搜索",
        ["common.unknown_value"] = "未知",
        ["features.collections_gear.all_sets_6ece2fa"] = "所有套装",
        ["features.collections_gear.apply_search_96b8b79"] = "应用搜索",
        ["features.collections_gear.background_opacity_label"] = "背景不透明度",
        ["features.collections_gear.background_opacity_tooltip"] = "调整齿轮集合显示背景的不透明度。",
        ["features.collections_gear.class_sets_d8f88fa"] = "班级集",
        ["features.collections_gear.clear_search_87e328d"] = "清除搜索",
        ["features.collections_gear.completed_sets_5094bc4"] = "已完成的套装",
        ["features.collections_gear.font_label"] = "字体",
        ["features.collections_gear.font_tooltip"] = "选择 Gear 集合显示所使用的字体。",
        ["features.collections_gear.horizontal_position_label"] = "水平位置",
        ["features.collections_gear.horizontal_position_tooltip"] = "向左或向右移动齿轮集合显示。",
        ["features.collections_gear.incomplete_sets_a81fe8d"] = "不完整集",
        ["features.collections_gear.input_hint"] = "<<1>> <<2>> 跳转组 <<3>> 搜索 <<4>> 筛选器：<<5>> <<6>> 浏览集",
        ["features.collections_gear.input_hint_flat"] = "<<1>> 搜索 <<2>> 筛选器： <<3>> <<4>> 浏览集",
        ["features.collections_gear.loading"] = "正在加载装备...",
        ["features.collections_gear.monster_sets_6bed3c4"] = "怪物套装",
        ["features.collections_gear.mythics_965733d"] = "神话",
        ["features.collections_gear.no_bonus_details"] = "没有可用的固定奖金详细信息。",
        ["features.collections_gear.no_mythic_lead_data"] = "此神话物品没有可用的古物线索数据。",
        ["features.collections_gear.no_pieces_are_available_for_this_set_e297c61"] = "该套装没有可用的部件。",
        ["features.collections_gear.no_search_results"] = "没有集合与搜索“<<1>>”和选定的过滤器相匹配。",
        ["features.collections_gear.no_set_selected"] = "未选择任何设置",
        ["features.collections_gear.no_sets_match_filter"] = "没有套装符合所选筛选条件。",
        ["features.collections_gear.perfected_name"] = "<<1>>（已完善）",
        ["features.collections_gear.scale_label"] = "规模",
        ["features.collections_gear.scale_tooltip"] = "更改整个 Gear 集合显示的大小。",
        ["features.collections_gear.search_title"] = "装备 (<<1>>)",
        ["features.collections_gear.set_bonus"] = "设定奖金",
        ["features.collections_gear.set_bonuses"] = "设定奖金",
        ["features.collections_gear.set_card_label"] = "设置卡",
        ["features.collections_gear.set_card_tooltip"] = "显示第三个窗格，其中包含所选集合的奖金详细信息。",
        ["features.collections_gear.set_collection"] = "套装系列",
        ["features.collections_gear.sets_cba9e41"] = "SETS",
        ["features.collections_gear.show_watermark_label"] = "显示水印",
        ["features.collections_gear.show_watermark_tooltip"] = "显示或隐藏 Gear 集合内容后面重复的玩家和服务器水印。",
        ["features.collections_gear.summary"] = "<<1>> <<2>>  •  <<3>> / <<4>> 件",
        ["features.collections_gear.summary_class_sets"] = "班级集",
        ["features.collections_gear.summary_completed_sets"] = "完成集",
        ["features.collections_gear.summary_incomplete_sets"] = "不完整集",
        ["features.collections_gear.summary_monster_sets"] = "怪物套装",
        ["features.collections_gear.summary_mythics"] = "神话",
        ["features.collections_gear.summary_sets"] = "套",
        ["features.collections_gear.title"] = "装备",
        ["features.collections_gear.type_class"] = "类别物品套装",
        ["features.collections_gear.type_item"] = "项目套装",
        ["features.collections_gear.type_monster"] = "怪物套装",
        ["features.collections_gear.type_mythic"] = "神话物品套装",
        ["features.collections_gear.type_perfected"] = "完美的物品套装",
        ["features.collections_gear.unknown_lead"] = "未知铅",
        ["features.collections_gear.unknown_piece"] = "未知部件",
        ["features.collections_gear.unknown_set"] = "未知集",
        ["features.collections_gear.vertical_position_label"] = "垂直位置",
        ["features.collections_gear.vertical_position_tooltip"] = "向上或向下移动齿轮集合显示。",
        ["ui.addons_menu.ngear_name"] = "|cFF0000N|r|c007FFFGear|r",
        ["item_locator.apply_search"] = "应用搜索",
        ["item_locator.bank"] = "银行",
        ["item_locator.background_opacity_label"] = "背景不透明度",
        ["item_locator.background_opacity_tooltip"] = "调整物品定位界面背景的不透明度。",
        ["item_locator.font_label"] = "字体",
        ["item_locator.font_tooltip"] = "选择物品定位界面使用的字体。",
        ["item_locator.horizontal_position_label"] = "水平位置",
        ["item_locator.horizontal_position_tooltip"] = "左右移动物品定位界面。",
        ["item_locator.scale_label"] = "缩放",
        ["item_locator.scale_tooltip"] = "更改整个物品定位界面的大小。",
        ["item_locator.vertical_position_label"] = "垂直位置",
        ["item_locator.vertical_position_tooltip"] = "上下移动物品定位界面。",
        ["item_locator.binding"] = "绑定",
        ["item_locator.category"] = "类别",
        ["item_locator.craft_bag"] = "制作背包",
        ["item_locator.chat_bank"] = "银行 (<<1>>)",
        ["item_locator.chat_character"] = "<<1>> (<<2>>)",
        ["item_locator.chat_message"] = "<<1>> · <<2>>",
        ["item_locator.chat_storage"] = "<<1>> (<<2>>)",
        ["item_locator.champion_level"] = "冠军 <<1>>",
        ["item_locator.clear_search"] = "清除搜索",
        ["item_locator.data_unavailable"] = "部分已保存的物品数据无法读取。",
        ["item_locator.date_month_abbreviations"] = "1月|2月|3月|4月|5月|6月|7月|8月|9月|10月|11月|12月",
        ["item_locator.detail_line"] = "|c72BEEB<<1>>：|r <<2>>",
        ["item_locator.details"] = "物品详情",
        ["item_locator.enchantment"] = "附魔",
        ["item_locator.furniture_vault"] = "装饰品宝库",
        ["item_locator.house_storage"] = "住宅储藏箱",
        ["item_locator.items"] = "物品",
        ["item_locator.input_hint_actions"] = "<<1>> 搜索 · <<2>> · <<3>> 返回",
        ["item_locator.input_hint_categories"] = "<<1>> 浏览 · <<2>> <<3>> 类别 · <<4>> 搜索 · <<5>> · <<6>> 输出到聊天栏 · <<7>> 返回",
        ["item_locator.input_hint_empty"] = "<<1>> 返回",
        ["item_locator.input_hint_items"] = "<<1>> 浏览 · <<2>> 搜索 · <<3>> · <<4>> 输出到聊天栏 · <<5>> 返回",
        ["item_locator.level"] = "等级",
        ["item_locator.location_bank"] = "银行：<<1>>",
        ["item_locator.location_equipped"] = "<<1>> · 已装备：<<2>>",
        ["item_locator.location_inventory"] = "<<1>>：<<2>>",
        ["item_locator.location_storage"] = "<<1>>：<<2>>",
        ["item_locator.locations"] = "位置",
        ["item_locator.market_prices"] = "市场价格",
        ["item_locator.no_items"] = "没有可用的已追踪物品。",
        ["item_locator.no_search_results"] = "没有物品符合搜索“<<1>>”。",
        ["item_locator.no_selection"] = "未选择物品",
        ["item_locator.log_in_chat"] = "输出到聊天栏",
        ["item_locator.price_average"] = "平均价值",
        ["item_locator.price_maximum"] = "最高价值",
        ["item_locator.price_minimum"] = "最低价值",
        ["item_locator.roster_not_indexed"] = "尚未建立索引",
        ["item_locator.roster_date"] = "<<1>>-<<2>>-<<3>>",
        ["item_locator.roster_scanned"] = "|cFFFFFF<<1>>：|r\n<<2>>",
        ["item_locator.search_placeholder"] = "物品名称",
        ["item_locator.search_title"] = "搜索物品",
        ["item_locator.sort"] = "排序",
        ["item_locator.sort_alphabetical"] = "按字母顺序",
        ["item_locator.sort_hint"] = "<<1>> 排序：<<2>>",
        ["item_locator.sort_quality"] = "按品质",
        ["item_locator.status"] = "状态",
        ["item_locator.stolen"] = "赃物",
        ["item_locator.style"] = "样式",
        ["item_locator.summary"] = "<<1>> 件物品 • <<2>> 个变体",
        ["item_locator.title"] = "物品定位",
        ["item_locator.title_search"] = "物品定位（<<1>>）",
        ["item_locator.trait"] = "特性",
        ["item_locator.type"] = "类型",
        ["item_locator.variant_total"] = "可用数量：<<1>>",
        ["item_locator.weight"] = "重量",
        ["ui.navigation.item_categories"] = "物品类别",
        ["ui.navigation.item_categories_tooltip"] = "选择要在物品定位中显示的物品类别。",
        ["ui.navigation.item_category_toggle_tooltip"] = "在物品定位中显示此类别。",
        ["ui.navigation.item_locator"] = "物品定位",
        ["ui.navigation.item_locator_tooltip"] = "在整个账号中定位物品",
        ["ui.navigation.scan_items"] = "扫描物品",
        ["ui.navigation.scan_items_tooltip"] = "扫描并追踪此角色携带或装备的物品以及共享银行、装饰品宝库和住宅储藏箱中的物品。",
        ["ui.navigation.browse_every_reconstructable_gear_set_and_its_collec_86e2576"] = "在专门的收藏展示中浏览每套可重建的装备及其收藏的部件。",
        ["ui.navigation.gear_def2b5f"] = "装备",
    },
}

local languageSettings
local refreshCallbacks = {}

local function ResolveLanguage(value)
    local language = string.lower(tostring(value or DEFAULT_LANGUAGE)):gsub("_", "-")
    language = LANGUAGE_ALIASES[language] or language
    if not SUPPORTED_LANGUAGES[language] then
        local prefix = language:match("^([a-z][a-z])")
        language = LANGUAGE_ALIASES[prefix] or prefix
    end

    return SUPPORTED_LANGUAGES[language] and language or nil
end

local function NormalizeLanguage(value)
    return ResolveLanguage(value) or DEFAULT_LANGUAGE
end

local function NormalizeLanguagePreference(value)
    if type(value) ~= "string" or value == "" then
        return DEFAULT_LANGUAGE_PREFERENCE
    end

    if string.lower(value) == DEFAULT_LANGUAGE_PREFERENCE then
        return DEFAULT_LANGUAGE_PREFERENCE
    end

    return ResolveLanguage(value) or DEFAULT_LANGUAGE_PREFERENCE
end

local function InitializeLanguageSettings()
    local defaults = { language = DEFAULT_LANGUAGE_PREFERENCE }
    languageSettings = ZO_SavedVars:NewAccountWide(
        LANGUAGE_SAVED_VARIABLES_NAME,
        LANGUAGE_SAVED_VARIABLES_VERSION,
        nil,
        defaults,
        nil,
        INSTALLATION_WIDE
    )

    return languageSettings
end

local function RequestLanguageSettingsSave()
    local addOnManager = GetAddOnManager and GetAddOnManager()
    if addOnManager and addOnManager.RequestAddOnSavedVariablesPrioritySave then
        addOnManager:RequestAddOnSavedVariablesPrioritySave(NGear.name or "NGear")
    end
end

local gameLanguage = NormalizeLanguage(GetCVar and GetCVar("Language.2") or DEFAULT_LANGUAGE)
local languagePreference = DEFAULT_LANGUAGE_PREFERENCE
local activeLanguage = gameLanguage
local initialized = false

local function PruneTranslations()
    for language in pairs(TRANSLATIONS) do
        if language ~= DEFAULT_LANGUAGE and language ~= activeLanguage then
            TRANSLATIONS[language] = nil
        end
    end
end

local function FormatWithoutEso(text, ...)
    local arguments = { ... }
    return (text:gsub("<<[A-Za-z]?:?(%d+)>>", function(index)
        local value = arguments[tonumber(index)]
        return value == nil and "" or tostring(value)
    end))
end

function Lexicon.NormalizeLanguage(value)
    return NormalizeLanguage(value)
end

function Lexicon.GetLanguage()
    return activeLanguage
end

function Lexicon.GetGameLanguage()
    return gameLanguage
end

function Lexicon.IsSupportedLanguage(value)
    return ResolveLanguage(value) ~= nil
end

function Lexicon.Initialize()
    if initialized then
        return activeLanguage
    end

    local currentSettings = InitializeLanguageSettings()
    languagePreference = NormalizeLanguagePreference(currentSettings.language)
    currentSettings.language = languagePreference
    activeLanguage = languagePreference == DEFAULT_LANGUAGE_PREFERENCE and gameLanguage or languagePreference
    initialized = true

    for index = 1, #refreshCallbacks do
        refreshCallbacks[index]()
    end
    refreshCallbacks = {}
    PruneTranslations()

    return activeLanguage
end

function Lexicon.RegisterRefreshCallback(callback)
    if type(callback) ~= "function" then
        return
    end

    callback()
    if not initialized then
        refreshCallbacks[#refreshCallbacks + 1] = callback
    end

end

function Lexicon.LocalizedList(definitions)
    local values = {}
    Lexicon.RegisterRefreshCallback(function()
        for index, definition in ipairs(definitions) do
            if type(definition) == "table" then
                values[index] = Lexicon.Get(Unpack(definition))
            else
                values[index] = Lexicon.Get(definition)
            end
        end
    end)

    return values
end

function Lexicon.RegisterTableField(values, fieldName, definitions)
    Lexicon.RegisterRefreshCallback(function()
        for index, definition in ipairs(definitions) do
            if type(definition) == "table" then
                values[index][fieldName] = Lexicon.Get(Unpack(definition))
            else
                values[index][fieldName] = Lexicon.Get(definition)
            end
        end
    end)
end

function Lexicon.GetLanguagePreference()
    if initialized then
        languagePreference = NormalizeLanguagePreference(languageSettings.language)
    end

    return languagePreference
end

function Lexicon.GetLanguagePreferenceDefault()
    return DEFAULT_LANGUAGE_PREFERENCE
end

function Lexicon.NormalizeLanguagePreference(value)
    return NormalizeLanguagePreference(value)
end

function Lexicon.IsLanguagePreference(value)
    return type(value) == "string"
        and (string.lower(value) == DEFAULT_LANGUAGE_PREFERENCE or ResolveLanguage(value) ~= nil)
end

function Lexicon.SetLanguagePreference(value)
    if not initialized then
        return false
    end

    local normalizedValue = NormalizeLanguagePreference(value)
    languageSettings.language = normalizedValue
    languagePreference = normalizedValue
    RequestLanguageSettingsSave()

    return languageSettings.language == normalizedValue
end

function Lexicon.GetLanguageChoices()
    local choices = {}
    for index = 1, #LANGUAGE_CHOICES do
        choices[index] = LANGUAGE_CHOICES[index]
    end
    return choices
end

function Lexicon.GetLanguageChoiceNames()
    local names = {}
    for index = 1, #LANGUAGE_CHOICE_KEYS do
        names[index] = Lexicon.Get(LANGUAGE_CHOICE_KEYS[index])
    end
    return names
end

function Lexicon.Get(key, ...)
    local languageTable = TRANSLATIONS[activeLanguage] or TRANSLATIONS[DEFAULT_LANGUAGE]
    local text = languageTable[key] or TRANSLATIONS[DEFAULT_LANGUAGE][key] or tostring(key)
    if select("#", ...) == 0 then
        return text
    end

    if zo_strformat then
        return zo_strformat(text, ...)
    end

    return FormatWithoutEso(text, ...)
end

Lexicon.SupportedLanguages = SUPPORTED_LANGUAGES
Lexicon.Translations = TRANSLATIONS
NGear.Lexicon = Lexicon
NGear.L = Lexicon.Get
