local TT = TamrielicTongues

-- Permanent concept assignments: append new literal IDs; never renumber/reuse.
-- Context-free English lemmas, not a word-sense disambiguator: saw means see;
-- left retains the direction sense. Noun/verb homographs (guard, run, etc.)
-- share a concept. Only explicitly listed inflections are recognized; no stemming.
-- Retired alias slots remain unused. Requirements are authored, not list ranks.
local entries = {
    ["C0001"] = { lemma = "i", requirement = 10 },
    ["C0002"] = { lemma = "you", requirement = 10 },
    ["C0003"] = { lemma = "he", requirement = 10 },
    ["C0004"] = { lemma = "she", requirement = 10 },
    ["C0005"] = { lemma = "we", requirement = 10 },
    ["C0006"] = { lemma = "they", requirement = 10 },
    ["C0007"] = { lemma = "me", requirement = 10 },
    ["C0008"] = { lemma = "him", requirement = 10 },
    ["C0009"] = { lemma = "her", requirement = 10 },
    ["C0010"] = { lemma = "us", requirement = 10 },
    ["C0011"] = { lemma = "them", requirement = 10 },
    ["C0012"] = { lemma = "my", requirement = 10 },
    ["C0013"] = { lemma = "your", requirement = 10 },
    ["C0014"] = { lemma = "his", requirement = 10 },
    ["C0015"] = { lemma = "our", requirement = 10 },
    ["C0016"] = { lemma = "their", requirement = 10 },
    ["C0017"] = { lemma = "this", requirement = 10 },
    ["C0018"] = { lemma = "that", requirement = 10 },
    ["C0019"] = { lemma = "these", requirement = 35 },
    ["C0020"] = { lemma = "those", requirement = 35 },
    ["C0021"] = { lemma = "a", requirement = 10 },
    ["C0022"] = { lemma = "an", requirement = 10 },
    ["C0023"] = { lemma = "the", requirement = 10 },
    ["C0024"] = { lemma = "and", requirement = 10 },
    ["C0025"] = { lemma = "or", requirement = 10 },
    ["C0026"] = { lemma = "but", requirement = 35 },
    ["C0027"] = { lemma = "if", requirement = 35 },
    ["C0028"] = { lemma = "then", requirement = 35 },
    ["C0029"] = { lemma = "because", requirement = 65 },
    ["C0030"] = { lemma = "with", requirement = 35 },
    ["C0031"] = { lemma = "without", requirement = 65 },
    ["C0032"] = { lemma = "in", requirement = 35 },
    ["C0033"] = { lemma = "on", requirement = 35 },
    ["C0034"] = { lemma = "at", requirement = 35 },
    ["C0035"] = { lemma = "to", requirement = 35 },
    ["C0036"] = { lemma = "from", requirement = 35 },
    ["C0037"] = { lemma = "for", requirement = 35 },
    ["C0038"] = { lemma = "of", requirement = 35 },
    ["C0039"] = { lemma = "by", requirement = 35 },
    ["C0040"] = { lemma = "near", requirement = 35 },
    ["C0041"] = { lemma = "under", requirement = 35 },
    ["C0042"] = { lemma = "over", requirement = 35 },
    ["C0043"] = { lemma = "behind", requirement = 35 },
    ["C0044"] = { lemma = "before", requirement = 35 },
    ["C0045"] = { lemma = "after", requirement = 35 },
    ["C0046"] = { lemma = "yes", requirement = 10 },
    ["C0047"] = { lemma = "no", requirement = 10 },
    ["C0048"] = { lemma = "not", requirement = 10 },
    ["C0049"] = { lemma = "maybe", requirement = 35 },
    ["C0050"] = { lemma = "please", requirement = 10 },
    ["C0051"] = { lemma = "thanks", requirement = 10 },
    ["C0052"] = { lemma = "hello", requirement = 10 },
    ["C0053"] = { lemma = "goodbye", requirement = 10 },
    ["C0059"] = { lemma = "be", requirement = 10 },
    ["C0061"] = { lemma = "have", requirement = 10 },
    ["C0064"] = { lemma = "do", requirement = 10 },
    ["C0067"] = { lemma = "will", requirement = 35 },
    ["C0068"] = { lemma = "would", requirement = 65 },
    ["C0069"] = { lemma = "can", requirement = 35 },
    ["C0070"] = { lemma = "could", requirement = 65 },
    ["C0071"] = { lemma = "should", requirement = 65 },
    ["C0072"] = { lemma = "must", requirement = 65 },
    ["C0073"] = { lemma = "who", requirement = 35 },
    ["C0074"] = { lemma = "what", requirement = 35 },
    ["C0075"] = { lemma = "where", requirement = 35 },
    ["C0076"] = { lemma = "when", requirement = 35 },
    ["C0077"] = { lemma = "why", requirement = 35 },
    ["C0078"] = { lemma = "how", requirement = 35 },
    ["C0079"] = { lemma = "come", requirement = 10 },
    ["C0080"] = { lemma = "go", requirement = 10 },
    ["C0081"] = { lemma = "leave", requirement = 35 },
    ["C0082"] = { lemma = "return", requirement = 35 },
    ["C0083"] = { lemma = "wait", requirement = 35 },
    ["C0084"] = { lemma = "follow", requirement = 35 },
    ["C0085"] = { lemma = "meet", requirement = 35 },
    ["C0086"] = { lemma = "find", requirement = 35 },
    ["C0087"] = { lemma = "seek", requirement = 65 },
    ["C0088"] = { lemma = "see", requirement = 10 },
    ["C0089"] = { lemma = "watch", requirement = 35 },
    ["C0090"] = { lemma = "look", requirement = 35 },
    ["C0091"] = { lemma = "hear", requirement = 35 },
    ["C0092"] = { lemma = "listen", requirement = 35 },
    ["C0093"] = { lemma = "speak", requirement = 35 },
    ["C0094"] = { lemma = "say", requirement = 35 },
    ["C0095"] = { lemma = "tell", requirement = 35 },
    ["C0096"] = { lemma = "ask", requirement = 35 },
    ["C0097"] = { lemma = "answer", requirement = 35 },
    ["C0098"] = { lemma = "know", requirement = 35 },
    ["C0099"] = { lemma = "think", requirement = 35 },
    ["C0100"] = { lemma = "believe", requirement = 65 },
    ["C0101"] = { lemma = "trust", requirement = 65 },
    ["C0102"] = { lemma = "want", requirement = 10 },
    ["C0103"] = { lemma = "need", requirement = 10 },
    ["C0104"] = { lemma = "give", requirement = 35 },
    ["C0105"] = { lemma = "take", requirement = 35 },
    ["C0106"] = { lemma = "bring", requirement = 35 },
    ["C0107"] = { lemma = "keep", requirement = 35 },
    ["C0108"] = { lemma = "hide", requirement = 35 },
    ["C0109"] = { lemma = "run", requirement = 35 },
    ["C0110"] = { lemma = "walk", requirement = 35 },
    ["C0111"] = { lemma = "fight", requirement = 35 },
    ["C0112"] = { lemma = "kill", requirement = 35 },
    ["C0113"] = { lemma = "help", requirement = 10 },
    ["C0114"] = { lemma = "save", requirement = 35 },
    ["C0115"] = { lemma = "open", requirement = 35 },
    ["C0116"] = { lemma = "close", requirement = 35 },
    ["C0117"] = { lemma = "eat", requirement = 35 },
    ["C0118"] = { lemma = "drink", requirement = 35 },
    ["C0119"] = { lemma = "sleep", requirement = 35 },
    ["C0120"] = { lemma = "wake", requirement = 35 },
    ["C0121"] = { lemma = "live", requirement = 35 },
    ["C0122"] = { lemma = "die", requirement = 35 },
    ["C0123"] = { lemma = "love", requirement = 35 },
    ["C0124"] = { lemma = "hate", requirement = 35 },
    ["C0125"] = { lemma = "fear", requirement = 35 },
    ["C0126"] = { lemma = "friend", requirement = 10 },
    ["C0127"] = { lemma = "enemy", requirement = 35 },
    ["C0128"] = { lemma = "stranger", requirement = 65 },
    ["C0129"] = { lemma = "family", requirement = 35 },
    ["C0130"] = { lemma = "mother", requirement = 35 },
    ["C0131"] = { lemma = "father", requirement = 35 },
    ["C0132"] = { lemma = "brother", requirement = 35 },
    ["C0133"] = { lemma = "sister", requirement = 35 },
    ["C0134"] = { lemma = "child", requirement = 35 },
    ["C0135"] = { lemma = "man", requirement = 35 },
    ["C0136"] = { lemma = "woman", requirement = 35 },
    ["C0137"] = { lemma = "guard", requirement = 35 },
    ["C0138"] = { lemma = "mage", requirement = 35 },
    ["C0139"] = { lemma = "warrior", requirement = 35 },
    ["C0140"] = { lemma = "hunter", requirement = 35 },
    ["C0141"] = { lemma = "assassin", requirement = 65 },
    ["C0142"] = { lemma = "merchant", requirement = 65 },
    ["C0143"] = { lemma = "home", requirement = 10 },
    ["C0144"] = { lemma = "house", requirement = 35 },
    ["C0145"] = { lemma = "room", requirement = 35 },
    ["C0146"] = { lemma = "tavern", requirement = 35 },
    ["C0147"] = { lemma = "city", requirement = 35 },
    ["C0148"] = { lemma = "village", requirement = 35 },
    ["C0149"] = { lemma = "road", requirement = 35 },
    ["C0150"] = { lemma = "bridge", requirement = 35 },
    ["C0151"] = { lemma = "gate", requirement = 35 },
    ["C0152"] = { lemma = "forest", requirement = 35 },
    ["C0153"] = { lemma = "mountain", requirement = 35 },
    ["C0154"] = { lemma = "river", requirement = 35 },
    ["C0155"] = { lemma = "sea", requirement = 35 },
    ["C0156"] = { lemma = "temple", requirement = 65 },
    ["C0157"] = { lemma = "ruin", requirement = 65 },
    ["C0158"] = { lemma = "camp", requirement = 35 },
    ["C0159"] = { lemma = "sword", requirement = 35 },
    ["C0160"] = { lemma = "bow", requirement = 35 },
    ["C0161"] = { lemma = "dagger", requirement = 35 },
    ["C0162"] = { lemma = "staff", requirement = 35 },
    ["C0163"] = { lemma = "armor", requirement = 65 },
    ["C0164"] = { lemma = "gold", requirement = 35 },
    ["C0165"] = { lemma = "coin", requirement = 35 },
    ["C0166"] = { lemma = "food", requirement = 10 },
    ["C0167"] = { lemma = "wine", requirement = 35 },
    ["C0168"] = { lemma = "water", requirement = 10 },
    ["C0169"] = { lemma = "fire", requirement = 35 },
    ["C0170"] = { lemma = "earth", requirement = 35 },
    ["C0171"] = { lemma = "air", requirement = 35 },
    ["C0172"] = { lemma = "magic", requirement = 65 },
    ["C0173"] = { lemma = "blood", requirement = 35 },
    ["C0174"] = { lemma = "death", requirement = 65 },
    ["C0175"] = { lemma = "life", requirement = 35 },
    ["C0176"] = { lemma = "sun", requirement = 35 },
    ["C0177"] = { lemma = "moon", requirement = 35 },
    ["C0178"] = { lemma = "star", requirement = 35 },
    ["C0179"] = { lemma = "day", requirement = 35 },
    ["C0180"] = { lemma = "night", requirement = 35 },
    ["C0181"] = { lemma = "morning", requirement = 35 },
    ["C0182"] = { lemma = "evening", requirement = 35 },
    ["C0183"] = { lemma = "today", requirement = 35 },
    ["C0184"] = { lemma = "tomorrow", requirement = 35 },
    ["C0185"] = { lemma = "yesterday", requirement = 35 },
    ["C0186"] = { lemma = "now", requirement = 10 },
    ["C0187"] = { lemma = "soon", requirement = 35 },
    ["C0188"] = { lemma = "later", requirement = 35 },
    ["C0189"] = { lemma = "early", requirement = 35 },
    ["C0190"] = { lemma = "late", requirement = 35 },
    ["C0191"] = { lemma = "midnight", requirement = 65 },
    ["C0192"] = { lemma = "good", requirement = 10 },
    ["C0193"] = { lemma = "bad", requirement = 10 },
    ["C0194"] = { lemma = "old", requirement = 35 },
    ["C0195"] = { lemma = "new", requirement = 35 },
    ["C0196"] = { lemma = "young", requirement = 35 },
    ["C0197"] = { lemma = "large", requirement = 35 },
    ["C0198"] = { lemma = "small", requirement = 35 },
    ["C0199"] = { lemma = "long", requirement = 35 },
    ["C0200"] = { lemma = "short", requirement = 35 },
    ["C0201"] = { lemma = "dark", requirement = 35 },
    ["C0202"] = { lemma = "light", requirement = 35 },
    ["C0203"] = { lemma = "red", requirement = 35 },
    ["C0204"] = { lemma = "black", requirement = 35 },
    ["C0205"] = { lemma = "white", requirement = 35 },
    ["C0206"] = { lemma = "strong", requirement = 35 },
    ["C0207"] = { lemma = "weak", requirement = 35 },
    ["C0208"] = { lemma = "fast", requirement = 35 },
    ["C0209"] = { lemma = "slow", requirement = 35 },
    ["C0210"] = { lemma = "safe", requirement = 35 },
    ["C0211"] = { lemma = "dangerous", requirement = 65 },
    ["C0212"] = { lemma = "dead", requirement = 35 },
    ["C0213"] = { lemma = "alive", requirement = 35 },
    ["C0214"] = { lemma = "north", requirement = 35 },
    ["C0215"] = { lemma = "south", requirement = 35 },
    ["C0216"] = { lemma = "east", requirement = 35 },
    ["C0217"] = { lemma = "west", requirement = 35 },
    ["C0218"] = { lemma = "left", requirement = 35 },
    ["C0219"] = { lemma = "right", requirement = 35 },
    ["C0220"] = { lemma = "here", requirement = 10 },
    ["C0221"] = { lemma = "there", requirement = 10 },
    ["C0222"] = { lemma = "inside", requirement = 35 },
    ["C0223"] = { lemma = "outside", requirement = 35 },
    ["C0224"] = { lemma = "one", requirement = 10 },
    ["C0225"] = { lemma = "two", requirement = 10 },
    ["C0226"] = { lemma = "three", requirement = 10 },
    ["C0227"] = { lemma = "many", requirement = 35 },
    ["C0228"] = { lemma = "few", requirement = 35 },
    ["C0229"] = { lemma = "all", requirement = 10 },
    ["C0230"] = { lemma = "none", requirement = 35 },
    ["C0231"] = { lemma = "never", requirement = 35 },
}

local grammar = {
    ["conditional"] = 65,
    ["conjunction"] = 30,
    ["contraction"] = 45,
    ["future"] = 35,
    ["modal"] = 50,
    ["negation"] = 20,
    ["past"] = 35,
    ["perfect"] = 60,
    ["plural"] = 15,
    ["progressive"] = 40,
    ["question"] = 25,
    ["subordination"] = 55,
}

local aliases = {
    ["am"] = { "C0059" },
    ["answered"] = { "C0097", "past" },
    ["answering"] = { "C0097", "progressive" },
    ["answers"] = { "C0097" },
    ["are"] = { "C0059" },
    ["asked"] = { "C0096", "past" },
    ["asking"] = { "C0096", "progressive" },
    ["asks"] = { "C0096" },
    ["assassins"] = { "C0141", "plural" },
    ["ate"] = { "C0117", "past" },
    ["been"] = { "C0059", "perfect" },
    ["being"] = { "C0059", "progressive" },
    ["believed"] = { "C0100", "past" },
    ["believes"] = { "C0100" },
    ["believing"] = { "C0100", "progressive" },
    ["bows"] = { "C0160", "plural" },
    ["bridges"] = { "C0150", "plural" },
    ["bringing"] = { "C0106", "progressive" },
    ["brings"] = { "C0106" },
    ["brothers"] = { "C0132", "plural" },
    ["brought"] = { "C0106", "past" },
    ["came"] = { "C0079", "past" },
    ["camps"] = { "C0158", "plural" },
    ["children"] = { "C0134", "plural" },
    ["cities"] = { "C0147", "plural" },
    ["closed"] = { "C0116", "past" },
    ["closes"] = { "C0116" },
    ["closing"] = { "C0116", "progressive" },
    ["coins"] = { "C0165", "plural" },
    ["comes"] = { "C0079" },
    ["coming"] = { "C0079", "progressive" },
    ["daggers"] = { "C0161", "plural" },
    ["days"] = { "C0179", "plural" },
    ["did"] = { "C0064", "past" },
    ["died"] = { "C0122", "past" },
    ["dies"] = { "C0122" },
    ["does"] = { "C0064" },
    ["doing"] = { "C0064", "progressive" },
    ["done"] = { "C0064", "past" },
    ["drank"] = { "C0118", "past" },
    ["drinking"] = { "C0118", "progressive" },
    ["drinks"] = { "C0118" },
    ["drunk"] = { "C0118", "past" },
    ["dying"] = { "C0122", "progressive" },
    ["eaten"] = { "C0117", "past" },
    ["eating"] = { "C0117", "progressive" },
    ["eats"] = { "C0117" },
    ["enemies"] = { "C0127", "plural" },
    ["evenings"] = { "C0182", "plural" },
    ["families"] = { "C0129", "plural" },
    ["fathers"] = { "C0131", "plural" },
    ["feared"] = { "C0125", "past" },
    ["fearing"] = { "C0125", "progressive" },
    ["fears"] = { "C0125" },
    ["fighting"] = { "C0111", "progressive" },
    ["fights"] = { "C0111" },
    ["finding"] = { "C0086", "progressive" },
    ["finds"] = { "C0086" },
    ["followed"] = { "C0084", "past" },
    ["following"] = { "C0084", "progressive" },
    ["follows"] = { "C0084" },
    ["foods"] = { "C0166", "plural" },
    ["forests"] = { "C0152", "plural" },
    ["fought"] = { "C0111", "past" },
    ["found"] = { "C0086", "past" },
    ["friends"] = { "C0126", "plural" },
    ["gates"] = { "C0151", "plural" },
    ["gave"] = { "C0104", "past" },
    ["given"] = { "C0104", "past" },
    ["gives"] = { "C0104" },
    ["giving"] = { "C0104", "progressive" },
    ["goes"] = { "C0080" },
    ["going"] = { "C0080", "progressive" },
    ["gone"] = { "C0080", "past" },
    ["guarded"] = { "C0137", "past" },
    ["guarding"] = { "C0137", "progressive" },
    ["guards"] = { "C0137", "plural" },
    ["had"] = { "C0061", "past" },
    ["has"] = { "C0061" },
    ["having"] = { "C0061", "progressive" },
    ["hated"] = { "C0124", "past" },
    ["hates"] = { "C0124" },
    ["hating"] = { "C0124", "progressive" },
    ["heard"] = { "C0091", "past" },
    ["hearing"] = { "C0091", "progressive" },
    ["hears"] = { "C0091" },
    ["helped"] = { "C0113", "past" },
    ["helping"] = { "C0113", "progressive" },
    ["helps"] = { "C0113" },
    ["hid"] = { "C0108", "past" },
    ["hidden"] = { "C0108", "past" },
    ["hides"] = { "C0108" },
    ["hiding"] = { "C0108", "progressive" },
    ["homes"] = { "C0143", "plural" },
    ["houses"] = { "C0144", "plural" },
    ["hunters"] = { "C0140", "plural" },
    ["is"] = { "C0059" },
    ["keeping"] = { "C0107", "progressive" },
    ["keeps"] = { "C0107" },
    ["kept"] = { "C0107", "past" },
    ["killed"] = { "C0112", "past" },
    ["killing"] = { "C0112", "progressive" },
    ["kills"] = { "C0112" },
    ["knew"] = { "C0098", "past" },
    ["knowing"] = { "C0098", "progressive" },
    ["known"] = { "C0098", "past" },
    ["knows"] = { "C0098" },
    ["leaves"] = { "C0081" },
    ["leaving"] = { "C0081", "progressive" },
    ["listened"] = { "C0092", "past" },
    ["listening"] = { "C0092", "progressive" },
    ["listens"] = { "C0092" },
    ["lived"] = { "C0121", "past" },
    ["lives"] = { "C0121" },
    ["living"] = { "C0121", "progressive" },
    ["looked"] = { "C0090", "past" },
    ["looking"] = { "C0090", "progressive" },
    ["looks"] = { "C0090" },
    ["loved"] = { "C0123", "past" },
    ["loves"] = { "C0123" },
    ["loving"] = { "C0123", "progressive" },
    ["mages"] = { "C0138", "plural" },
    ["meeting"] = { "C0085", "progressive" },
    ["meets"] = { "C0085" },
    ["men"] = { "C0135", "plural" },
    ["merchants"] = { "C0142", "plural" },
    ["met"] = { "C0085", "past" },
    ["mornings"] = { "C0181", "plural" },
    ["mothers"] = { "C0130", "plural" },
    ["mountains"] = { "C0153", "plural" },
    ["needed"] = { "C0103", "past" },
    ["needing"] = { "C0103", "progressive" },
    ["needs"] = { "C0103" },
    ["nights"] = { "C0180", "plural" },
    ["opened"] = { "C0115", "past" },
    ["opening"] = { "C0115", "progressive" },
    ["opens"] = { "C0115" },
    ["ran"] = { "C0109", "past" },
    ["returned"] = { "C0082", "past" },
    ["returning"] = { "C0082", "progressive" },
    ["returns"] = { "C0082" },
    ["rivers"] = { "C0154", "plural" },
    ["roads"] = { "C0149", "plural" },
    ["rooms"] = { "C0145", "plural" },
    ["ruins"] = { "C0157", "plural" },
    ["running"] = { "C0109", "progressive" },
    ["runs"] = { "C0109" },
    ["said"] = { "C0094", "past" },
    ["saved"] = { "C0114", "past" },
    ["saves"] = { "C0114" },
    ["saving"] = { "C0114", "progressive" },
    ["saw"] = { "C0088", "past" },
    ["saying"] = { "C0094", "progressive" },
    ["says"] = { "C0094" },
    ["seas"] = { "C0155", "plural" },
    ["seeing"] = { "C0088", "progressive" },
    ["seeking"] = { "C0087", "progressive" },
    ["seeks"] = { "C0087" },
    ["seen"] = { "C0088", "past" },
    ["sees"] = { "C0088" },
    ["sisters"] = { "C0133", "plural" },
    ["sleeping"] = { "C0119", "progressive" },
    ["sleeps"] = { "C0119" },
    ["slept"] = { "C0119", "past" },
    ["sought"] = { "C0087", "past" },
    ["speaking"] = { "C0093", "progressive" },
    ["speaks"] = { "C0093" },
    ["spoke"] = { "C0093", "past" },
    ["spoken"] = { "C0093", "past" },
    ["stars"] = { "C0178", "plural" },
    ["staves"] = { "C0162", "plural" },
    ["strangers"] = { "C0128", "plural" },
    ["swords"] = { "C0159", "plural" },
    ["taken"] = { "C0105", "past" },
    ["takes"] = { "C0105" },
    ["taking"] = { "C0105", "progressive" },
    ["taverns"] = { "C0146", "plural" },
    ["telling"] = { "C0095", "progressive" },
    ["tells"] = { "C0095" },
    ["temples"] = { "C0156", "plural" },
    ["thinking"] = { "C0099", "progressive" },
    ["thinks"] = { "C0099" },
    ["thought"] = { "C0099", "past" },
    ["told"] = { "C0095", "past" },
    ["took"] = { "C0105", "past" },
    ["trusted"] = { "C0101", "past" },
    ["trusting"] = { "C0101", "progressive" },
    ["trusts"] = { "C0101" },
    ["villages"] = { "C0148", "plural" },
    ["waited"] = { "C0083", "past" },
    ["waiting"] = { "C0083", "progressive" },
    ["waits"] = { "C0083" },
    ["wakes"] = { "C0120" },
    ["waking"] = { "C0120", "progressive" },
    ["walked"] = { "C0110", "past" },
    ["walking"] = { "C0110", "progressive" },
    ["walks"] = { "C0110" },
    ["wanted"] = { "C0102", "past" },
    ["wanting"] = { "C0102", "progressive" },
    ["wants"] = { "C0102" },
    ["warriors"] = { "C0139", "plural" },
    ["was"] = { "C0059", "past" },
    ["watched"] = { "C0089", "past" },
    ["watches"] = { "C0089" },
    ["watching"] = { "C0089", "progressive" },
    ["went"] = { "C0080", "past" },
    ["were"] = { "C0059", "past" },
    ["wines"] = { "C0167", "plural" },
    ["woke"] = { "C0120", "past" },
    ["woken"] = { "C0120", "past" },
    ["women"] = { "C0136", "plural" },
    ["ain't"] = { "C0059", "negation", "negation", "contraction" },
    ["aren't"] = { "C0059", "negation", "negation", "contraction" },
    ["can't"] = { "C0069", "modal", "negation", "contraction" },
    ["cannot"] = { "C0069", "modal", "negation", "contraction" },
    ["couldn't"] = { "C0070", "conditional", "negation", "contraction" },
    ["didn't"] = { "C0064", "past", "negation", "contraction" },
    ["doesn't"] = { "C0064", "negation", "negation", "contraction" },
    ["don't"] = { "C0064", "negation", "negation", "contraction" },
    ["hadn't"] = { "C0061", "past", "negation", "contraction" },
    ["hasn't"] = { "C0061", "negation", "contraction" },
    ["haven't"] = { "C0061", "negation", "contraction" },
    ["isn't"] = { "C0059", "negation", "negation", "contraction" },
    ["mustn't"] = { "C0072", "modal", "negation", "contraction" },
    ["shouldn't"] = { "C0071", "modal", "negation", "contraction" },
    ["wasn't"] = { "C0059", "past", "negation", "contraction" },
    ["weren't"] = { "C0059", "past", "negation", "contraction" },
    ["won't"] = { "C0067", "future", "negation", "contraction" },
    ["wouldn't"] = { "C0068", "conditional", "negation", "contraction" },
}

local baseFeatures = {
    ["and"] = "conjunction",
    ["because"] = "subordination",
    ["but"] = "conjunction",
    ["can"] = "modal",
    ["could"] = "conditional",
    ["how"] = "question",
    ["if"] = "conditional",
    ["must"] = "modal",
    ["never"] = "negation",
    ["no"] = "negation",
    ["not"] = "negation",
    ["or"] = "conjunction",
    ["should"] = "modal",
    ["tomorrow"] = "future",
    ["what"] = "question",
    ["when"] = "question",
    ["where"] = "question",
    ["who"] = "question",
    ["why"] = "question",
    ["will"] = "future",
    ["without"] = "negation",
    ["would"] = "conditional",
    ["yesterday"] = "past",
}

-- Participles are grammatical surface evidence, not a new vocabulary concept or
-- an unconditional perfect feature. In particular, saw/ran/went are NOT on this
-- list. Shared past/participle forms and supported regular forms are explicit;
-- ambiguous left remains the direction concept and is deliberately excluded.
local participles = {
    been = true, had = true, done = true, come = true, gone = true,
    met = true, found = true, sought = true, seen = true, heard = true,
    spoken = true, said = true, told = true, known = true, thought = true,
    given = true, taken = true, brought = true, kept = true, hidden = true,
    run = true, fought = true, eaten = true, drunk = true, slept = true, woken = true,
    answered = true, asked = true, believed = true, closed = true, died = true,
    feared = true, followed = true, guarded = true, hated = true, helped = true,
    killed = true, listened = true, lived = true, looked = true, loved = true,
    needed = true, opened = true, returned = true, saved = true, trusted = true,
    waited = true, walked = true, wanted = true, watched = true,
}

-- UTF-8 U+2019 RIGHT SINGLE QUOTATION MARK; normalize lookup only, never wire text.
local RIGHT_APOSTROPHE = string.char(226, 128, 153)

local bySurface = {}
for id, entry in pairs(entries) do
    assert(not bySurface[entry.lemma], "duplicate canonical lemma: " .. entry.lemma)
    bySurface[entry.lemma] = { id }
end
for surface, entry in pairs(aliases) do
    assert(entries[entry[1]], "missing canonical alias target: " .. surface)
    assert(not bySurface[surface], "ambiguous canonical alias: " .. surface)
    bySurface[surface] = entry
end

TT.CanonicalCatalog = { GrammarRequirements = grammar }

function TT.CanonicalCatalog:GetEntry(id)
    return entries[id]
end

function TT.CanonicalCatalog:GetVocabularyRequirement(id)
    return entries[id] and entries[id].requirement or 100
end

function TT.CanonicalCatalog:IsSupportedParticiple(surface)
    return participles[string.lower(surface)] == true
end

function TT.CanonicalCatalog:Resolve(surface)
    local lower = string.lower(surface):gsub(RIGHT_APOSTROPHE, "'")
    -- Strip boundary punctuation only; internal apostrophes carry grammar.
    lower = lower:gsub("^[%s%p]+", ""):gsub("[%s%p]+$", "")
    local alias = bySurface[lower]
    if not alias then
        return { id = "oov:en:v1:" .. lower, lemma = lower, requirement = 100,
            features = {}, unknown = true }
    end
    local entry, features = entries[alias[1]], {}
    local feature = baseFeatures[entry.lemma]
    if feature then features[feature] = grammar[feature] end
    for i = 2, #alias do features[alias[i]] = grammar[alias[i]] end
    return { id = alias[1], lemma = entry.lemma, requirement = entry.requirement,
        features = features, unknown = false }
end
