-- IngredientHunter Localization
-- Both languages are always loaded.
-- Active language is chosen in Initialize() from SavedVars or ESO client locale.
---------------------------------------------------------

IngredientHunter_Strings = {

    -- ESO client locale (used as default when no SavedVar override)
    _auto = GetCVar("language.2") or "en",

    ---------------------------------------------------------
    en = {
        WINDOW_TITLE    = "INGREDIENT HUNTER",
        TRACK_BTN       = "TRACK",
        EFFECTS_LABEL   = "Effects: ",
        SOLVENT_LABEL   = "Solvent: ",
        SOLVENT_UNKNOWN = "Solvent: ?",
        COMBO_FORMAT    = "Combo %d / %d",
        PREV_COMBO      = "<< Prev",
        NEXT_COMBO      = "Next >>",
        ALL_COMBOS_HDR  = "--- All Combinations ---",
        BAG_FMT_3       = "Pk%d Bk%d Cb%d",
        BAG_FMT_2       = "Pk%d Bk%d",
        MSG_PREFIX      = "|cC89B3C[Ingredient Hunter]|r",
        MSG_SELECT_RECIPE = "Select a recipe first!",
        MSG_LOADED      = "Loaded. Use |c4ADE80/ih|r to open.",

        reagent = {
            ["Благословенный чертополох"] = "Blessed Thistle",
            ["Синяя энтолома"]            = "Blue Entoloma",
            ["Воловик"]                   = "Bugloss",
            ["Водосбор"]                  = "Columbine",
            ["Василёк"]                   = "Corn Flower",
            ["Драконий шип"]              = "Dragonthorn",
            ["Рвотная сыроежка"]          = "Emetic Russula",
            ["Импья поганка"]             = "Imp Stool",
            ["Дамский смок"]              = "Lady's Smock",
            ["Светящаяся сыроежка"]       = "Luminous Russula",
            ["Горный цветок"]             = "Mountain Flower",
            ["Гниль Намиры"]              = "Namira's Rot",
            ["Нирнкорень"]                = "Nirnroot",
            ["Весёлка"]                   = "Stinkhorn",
            ["Фиолетовый навозник"]       = "Violet Coprinus",
            ["Водяной гиацинт"]           = "Water Hyacinth",
            ["Белая шляпка"]              = "White Cap",
            ["Полынь"]                    = "Wormwood",
            ["Слёзы Лорхана"]             = "Lorkhan's Tears",
            ["Желчь моллюска"]            = "Clam Gall",
            ["Хитин грязевого краба"]     = "Mudcrab Chitin",
            ["Паучье яйцо"]               = "Spider Egg",
            ["Желе скриба"]               = "Scrib Jelly",
        },
        solvent = {
            ["Природная вода"]        = "Natural Water",
            ["Чистая вода"]           = "Clear Water",
            ["Нетронутая вода"]       = "Pristine Water",
            ["Очищенная вода"]        = "Cleansed Water",
            ["Фильтрованная вода"]    = "Filtered Water",
            ["Дистиллированная вода"] = "Distilled Water",
            ["Облачная дымка"]        = "Cloud Mist",
            ["Звёздная роса"]         = "Star Dew",
            ["Слёзы Лорхана"]         = "Lorkhan's Tears",
            ["Жир"]                   = "Grease",
            ["Ихор"]                  = "Ichor",
            ["Слизь"]                 = "Slime",
            ["Желчь"]                 = "Bile",
            ["Терпентин"]             = "Turpentine",
            ["Смоляная желчь"]        = "Pitch Bile",
            ["Дёготь"]                = "Tar",
            ["Ночное масло"]          = "Night Oil",
            ["Алкагест"]              = "Alkahest",
        },
        effect = {
            ["Восстановление здоровья"]     = "Restore Health",
            ["Восстановление магики"]       = "Restore Magicka",
            ["Восстановление выносливости"] = "Restore Stamina",
            ["Урон заклинания"]             = "Spell Damage",
            ["Крит заклинания"]             = "Spell Critical",
            ["Урон оружия"]                 = "Weapon Damage",
            ["Крит оружием"]                = "Weapon Critical",
            ["Невидимость"]                 = "Invisibility",
            ["Скорость"]                    = "Speed",
            ["Неудержимость"]               = "Unstoppable",
            ["Обнаружение"]                 = "Detection",
            ["Истощение здоровья"]          = "Drain Health",
            ["Истощение магики"]            = "Drain Magicka",
            ["Истощение выносливости"]      = "Drain Stamina",
            ["Снижение сопр. магии"]        = "Lower Spell Resistance",
            ["Снижение сопр. оружию"]       = "Lower Weapon Resistance",
            ["Оглушение"]                   = "Stun",
            ["Снижение скорости"]           = "Slow",
        },
        recipe = {
            ["Восстановление здоровья"]                = "Restore Health",
            ["Восстановление магики"]                  = "Restore Magicka",
            ["Восстановление выносливости"]            = "Restore Stamina",
            ["Сущность здоровья (три характеристики)"] = "Tri-Stat Essence",
            ["Зелье силы заклинаний"]                  = "Spell Power Potion",
            ["Зелье силы оружия"]                      = "Weapon Power Potion",
            ["Сущность силы заклинаний"]               = "Spell Power Essence",
            ["Сущность силы оружия"]                   = "Weapon Power Essence",
            ["Зелье невидимости"]                      = "Invisibility Potion",
            ["Зелье неудержимости"]                    = "Unstoppable Potion",
            ["Зелье обнаружения"]                      = "Detection Potion",
            ["Зелье скорости"]                         = "Speed Potion",
            ["Яд истощения здоровья"]                  = "Health Drain Poison",
            ["Яд истощения магики"]                    = "Magicka Drain Poison",
            ["Яд истощения выносливости"]              = "Stamina Drain Poison",
            ["Яд поглощения здоровья"]                 = "Health Absorption Poison",
            ["Яд уязвимости (снижение сопр. магии)"]   = "Vulnerability Poison (Spell Res.)",
            ["Яд уязвимости (снижение сопр. оружию)"]  = "Vulnerability Poison (Weapon Res.)",
            ["Яд оглушения"]                           = "Stun Poison",
        },
    },

    ---------------------------------------------------------
    ru = {
        WINDOW_TITLE    = "ОХОТНИК ЗА ИНГРЕДИЕНТАМИ",
        TRACK_BTN       = "СЛЕЖКА",
        EFFECTS_LABEL   = "Эффекты: ",
        SOLVENT_LABEL   = "Растворитель: ",
        SOLVENT_UNKNOWN = "Растворитель: ?",
        COMBO_FORMAT    = "Комбинация %d / %d",
        PREV_COMBO      = "<< Пред",
        NEXT_COMBO      = "След >>",
        ALL_COMBOS_HDR  = "--- Все комбинации ---",
        BAG_FMT_3       = "С%d Б%d В%d",
        BAG_FMT_2       = "С%d Б%d",
        MSG_PREFIX      = "|cC89B3C[Охотник за ингредиентами]|r",
        MSG_SELECT_RECIPE = "Сначала выберите рецепт!",
        MSG_LOADED      = "Загружен. Используйте |c4ADE80/ih|r для открытия окна.",
        -- Russian data names are already in Recipes.lua — no translation maps needed.
        reagent = {}, solvent = {}, effect = {}, recipe = {},
    },
}
