ExtraRadialMenuData = ExtraRadialMenuData or {}
local ERMData = ExtraRadialMenuData

ERMData.houses = {
    { type = "Rewards", no = 70, name = "Hall of the Lunar Champion" },
    { type = "Rewards", no = 90, name = "Doomchar Plateau" },
    { type = "Rewards", no = 103, name = "Sword-Singer's Redoubt" },
    { type = "Rewards", no = 104, name = "Kelesan'ruhn" },
    { type = "Rewards", no = 112, name = "Haven of the Five Companions" },
    { type = "Rewards", no = 114, name = "Grand Gallery of Tamriel" },
    { type = "Rewards", no = 121, name = "Wildgrown Chapel of Julianos" },
    { type = "Rewards", no = 124, name = "Night's Den" },
    { type = "Rewards", no = 128, name = "Rogue's Refuge" },

	{ type = "Exclusive", no = 40, name = "Grand Topal Hideaway" },
    { type = "Exclusive", no = 45, name = "Tel Galen" },
    { type = "Exclusive", no = 46, name = "Linchal Grand Manor" },
    { type = "Exclusive", no = 54, name = "Pariah's Pinnacle" },
    { type = "Exclusive", no = 56, name = "The Erstwhile Sanctuary" },
    { type = "Exclusive", no = 57, name = "Princely Dawnlight Palace" },
    { type = "Exclusive", no = 60, name = "Colossal Aldmeri Grotto" },
    { type = "Exclusive", no = 61, name = "Hunter's Glade" },
    { type = "Exclusive", no = 62, name = "Grand Psijic Villa" },
    { type = "Exclusive", no = 63, name = "Enchanted Snow Globe Home" },
    { type = "Exclusive", no = 64, name = "Lakemire Xanmeer Manor" },
    { type = "Exclusive", no = 65, name = "Frostvault Chasm" },
    { type = "Exclusive", no = 66, name = "Elinhir Private Arena" },
    { type = "Exclusive", no = 69, name = "Jode's Embrace" },
    { type = "Exclusive", no = 72, name = "Wraithhome" },
    { type = "Exclusive", no = 74, name = "Potentate's Retreat" },
    { type = "Exclusive", no = 75, name = "Forgemaster Falls" },
    { type = "Exclusive", no = 76, name = "Thieves' Oasis" },
    { type = "Exclusive", no = 79, name = "Bastion Sanguinaris" },
    { type = "Exclusive", no = 81, name = "Antiquarian's Alpine Gallery" },
    { type = "Exclusive", no = 82, name = "Shalidor's Shrouded Realm" },
    { type = "Exclusive", no = 83, name = "Stone Eagle Aerie" },
    { type = "Exclusive", no = 85, name = "Kushalit Sanctuary" },
    { type = "Exclusive", no = 86, name = "Varlaisvea Ayleid Ruins" },
    { type = "Exclusive", no = 89, name = "Pantherfang Chapel" },
    { type = "Exclusive", no = 91, name = "Sweetwater Cascades" },
    { type = "Exclusive", no = 92, name = "Ossa Accentium" },
    { type = "Exclusive", no = 93, name = "Agony's Ascent" },
    { type = "Exclusive", no = 94, name = "Seaveil Spire" },
    { type = "Exclusive", no = 96, name = "Highhallow Hold" },
    { type = "Exclusive", no = 98, name = "Fogbreak Lighthouse" },
    { type = "Exclusive", no = 99, name = "The Fair Winds" },
    { type = "Exclusive", no = 102, name = "Shadow Queen's Labyrinth" },
    { type = "Exclusive", no = 105, name = "Gladesong Arboretum" },
    { type = "Exclusive", no = 106, name = "Tower of Unutterable Truths" },
    { type = "Exclusive", no = 107, name = "Willowpond Haven" },
    { type = "Exclusive", no = 108, name = "Zhan Khaj Crest" },
    { type = "Exclusive", no = 111, name = "Seabloom Villa" },
    { type = "Exclusive", no = 113, name = "Kthendral Deep Mines" },
    { type = "Exclusive", no = 115, name = "Shattered Mirror Isle" },
    { type = "Exclusive", no = 116, name = "Castle Skingrad" },
    { type = "Exclusive", no = 119, name = "Theater of the Ancestors" },
    { type = "Exclusive", no = 120, name = "Hiddenspring Cottage" },
    { type = "Exclusive", no = 122, name = "Cradle of the Worm Colossus" },
    { type = "Exclusive", no = 123, name = "Druidspring Conservatory" },
    { type = "Exclusive", no = 125, name = "Buccaneer Bay" },
    { type = "Exclusive", no = 129, name = "Dancing Waters Wellspring" },

	{ type = "Manor", no = 37, name = "Serenity Falls Estate" },
    { type = "Manor", no = 38, name = "Daggerfall Overlook" },
    { type = "Manor", no = 39, name = "Ebonheart Chateau" },
    { type = "Manor", no = 41, name = "Earthtear Cavern" },
    { type = "Manor", no = 47, name = "Coldharbour Surreal Estate" },
    { type = "Manor", no = 48, name = "Hakkvild's High Hall" },
    { type = "Manor", no = 55, name = "The Orbservatory Prior" },
    { type = "Manor", no = 71, name = "Moon-Sugar Meadow" },
    { type = "Manor", no = 80, name = "Stillwaters Retreat" },

	{ type = "Large", no = 9, name = "Mathiisen Manor" },
    { type = "Large", no = 12, name = "Stay-Moist Mansion" },
    { type = "Large", no = 15, name = "The Gorinir Estate" },
    { type = "Large", no = 18, name = "Gardner House" },
    { type = "Large", no = 21, name = "Quondam Indorilia" },
    { type = "Large", no = 24, name = "Dawnshadow" },
    { type = "Large", no = 27, name = "Strident Springs Demesne" },
    { type = "Large", no = 30, name = "Old Mistveil Manor" },
    { type = "Large", no = 33, name = "Forsaken Stronghold" },
    { type = "Large", no = 36, name = "Hunding's Palatial Hall" },
    { type = "Large", no = 43, name = "Amaya Lake Lodge" },
    { type = "Large", no = 59, name = "Alinor Crest Townhouse" },
    { type = "Large", no = 78, name = "Proudspire Manor" },
    { type = "Large", no = 88, name = "Water's Edge" },
    { type = "Large", no = 101, name = "Emissary's Enclave" },
    { type = "Large", no = 110, name = "Merryvine Estate" },
    { type = "Large", no = 117, name = "Bismuth Steam Baths" },

	{ type = "Medium", no = 8, name = "Cliffshade" },
    { type = "Medium", no = 11, name = "The Ample Domicile" },
    { type = "Medium", no = 14, name = "Bouldertree Refuge" },
    { type = "Medium", no = 17, name = "Ravenhurst" },
    { type = "Medium", no = 20, name = "Velothi Reverie" },
    { type = "Medium", no = 23, name = "Sleek Creek House" },
    { type = "Medium", no = 26, name = "Domus Phrasticus" },
    { type = "Medium", no = 29, name = "Grymharth's Woe" },
    { type = "Medium", no = 32, name = "Mournoth Keep" },
    { type = "Medium", no = 35, name = "House of the Silent Magnifico" },
    { type = "Medium", no = 44, name = "Ald Velothi Harbor House" },
    { type = "Medium", no = 49, name = "Exorcised Coven Cottage" },
    { type = "Medium", no = 73, name = "Lucky Cat Landing" },

	{ type = "Small", no = 7, name = "Black Vine Villa" },
    { type = "Small", no = 10, name = "Humblemud" },
    { type = "Small", no = 13, name = "Snugpod" },
    { type = "Small", no = 16, name = "Captain Margaux's Place" },
    { type = "Small", no = 19, name = "Kragenhome" },
    { type = "Small", no = 22, name = "Moonmirth House" },
    { type = "Small", no = 25, name = "Cyrodilic Jungle House" },
    { type = "Small", no = 28, name = "Autumn's-Gate" },
    { type = "Small", no = 31, name = "Hammerdeath Bungalow" },
    { type = "Small", no = 34, name = "Twin Arches" },

    { type = "Apartment", no = 4, name = "Barbed Hook Private Room" },
    { type = "Apartment", no = 5, name = "Sisters of the Sands Apartment" },
    { type = "Apartment", no = 6, name = "Flaming Nix Deluxe Garret" },

	{ type = "Inn Room", no = 1, name = "Mara's Kiss Public House" },
    { type = "Inn Room", no = 2, name = "The Rosy Lion" },
    { type = "Inn Room", no = 3, name = "The Ebony Flask Inn Room" },
    { type = "Inn Room", no = 42, name = "Saint Delyn Penthouse" },
    { type = "Inn Room", no = 58, name = "Golden Gryphon Garret" },
    { type = "Inn Room", no = 68, name = "Sugar Bowl Suite" },
    { type = "Inn Room", no = 77, name = "Snowmelt Suite" },
    { type = "Inn Room", no = 87, name = "Pilgrim's Rest" },
    { type = "Inn Room", no = 95, name = "Ancient Anchor Berth" },
    { type = "Inn Room", no = 100, name = "Journey's End Lodgings" },
    { type = "Inn Room", no = 109, name = "Rosewine Retreat" },
    { type = "Inn Room", no = 118, name = "The Sleepy Sloth" },
}
