ItemShareSavedVars =
{
    ["Default"] = 
    {
        ["@DragonSlayerX"] = 
        {
            ["$AccountWide"] = 
            {
                ["sharedItems"] = 
                {
                    ["|H0:item:199708:359:50:0:0:0:0:0:0:0:0:0:0:0:0:25:0:0:0:250:0|h|h||inventory:kael stormblade"] = 
                    {
                        ["itemLink"] = "|H0:item:199708:359:50:0:0:0:0:0:0:0:0:0:0:0:0:25:0:0:0:250:0|h|h",
                        ["locationKey"] = "inventory:kael stormblade",
                        ["lastDumpedAt"] = 1776422674,
                        ["count"] = 1,
                        ["sharedFrom"] = "Inventory (Kael Stormblade)",
                        ["bagId"] = 1,
                        ["itemTypeName"] = "Weapon",
                        ["quality"] = 2,
                        ["traitType"] = 1,
                        ["accountName"] = "@DragonSlayerX",
                        ["furnitureDataId"] = 0,
                        ["firstDumpedAt"] = 1776422674,
                        ["itemKey"] = "|H0:item:199708:359:50:0:0:0:0:0:0:0:0:0:0:0:0:25:0:0:0:250:0|h|h||inventory:kael stormblade",
                        ["trait"] = "Powered",
                        ["slotIndex"] = 3,
                        ["itemType"] = 1,
                        ["itemName"] = "Greatsword of Vicious Death",
                        ["qualityName"] = "Fine",
                    },
                    ["|H0:item:126473:5:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||inventory:kael stormblade"] = 
                    {
                        ["itemLink"] = "|H0:item:126473:5:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                        ["locationKey"] = "inventory:kael stormblade",
                        ["lastDumpedAt"] = 1776422725,
                        ["count"] = 1,
                        ["sharedFrom"] = "Inventory (Kael Stormblade)",
                        ["bagId"] = 1,
                        ["itemTypeName"] = "Furnishing",
                        ["quality"] = 4,
                        ["traitType"] = 0,
                        ["accountName"] = "@DragonSlayerX",
                        ["furnitureDataId"] = 3548,
                        ["firstDumpedAt"] = 1776422725,
                        ["itemKey"] = "|H0:item:126473:5:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||inventory:kael stormblade",
                        ["trait"] = "",
                        ["slotIndex"] = 6,
                        ["itemType"] = 61,
                        ["itemName"] = "Telvanni Lamp, Organic Azure",
                        ["qualityName"] = "Epic",
                    },
                    ["|H0:item:91650:359:50:0:0:0:0:0:0:0:0:0:0:0:0:25:0:0:0:250:0|h|h||inventory:kael stormblade"] = 
                    {
                        ["itemLink"] = "|H0:item:91650:359:50:0:0:0:0:0:0:0:0:0:0:0:0:25:0:0:0:250:0|h|h",
                        ["locationKey"] = "inventory:kael stormblade",
                        ["lastDumpedAt"] = 1776422715,
                        ["count"] = 1,
                        ["sharedFrom"] = "Inventory (Kael Stormblade)",
                        ["bagId"] = 1,
                        ["itemTypeName"] = "Weapon",
                        ["quality"] = 2,
                        ["traitType"] = 7,
                        ["accountName"] = "@DragonSlayerX",
                        ["furnitureDataId"] = 0,
                        ["firstDumpedAt"] = 1776422715,
                        ["itemKey"] = "|H0:item:91650:359:50:0:0:0:0:0:0:0:0:0:0:0:0:25:0:0:0:250:0|h|h||inventory:kael stormblade",
                        ["trait"] = "Sharpened",
                        ["slotIndex"] = 9,
                        ["itemType"] = 1,
                        ["itemName"] = "Sword of the Arch-Mage",
                        ["qualityName"] = "Fine",
                    },
                    ["|H0:item:171727:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||bank"] = 
                    {
                        ["itemLink"] = "|H0:item:171727:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                        ["locationKey"] = "bank",
                        ["lastDumpedAt"] = 1776422807,
                        ["count"] = 1,
                        ["sharedFrom"] = "Bank",
                        ["bagId"] = 2,
                        ["itemTypeName"] = "Collectible",
                        ["quality"] = 5,
                        ["traitType"] = 0,
                        ["accountName"] = "@DragonSlayerX",
                        ["furnitureDataId"] = 0,
                        ["firstDumpedAt"] = 1776422807,
                        ["itemKey"] = "|H0:item:171727:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||bank",
                        ["trait"] = "",
                        ["slotIndex"] = 103,
                        ["itemType"] = 34,
                        ["itemName"] = "Style Page: Regal Regalia Sash",
                        ["qualityName"] = "Legendary",
                    },
                    ["|H0:item:114363:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||bank"] = 
                    {
                        ["itemLink"] = "|H0:item:114363:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                        ["locationKey"] = "bank",
                        ["lastDumpedAt"] = 1776422971,
                        ["count"] = 1,
                        ["sharedFrom"] = "Bank",
                        ["bagId"] = 2,
                        ["itemTypeName"] = "Furnishing",
                        ["quality"] = 3,
                        ["traitType"] = 0,
                        ["accountName"] = "@DragonSlayerX",
                        ["furnitureDataId"] = 290,
                        ["firstDumpedAt"] = 1776422971,
                        ["itemKey"] = "|H0:item:114363:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||bank",
                        ["trait"] = "",
                        ["slotIndex"] = 104,
                        ["itemType"] = 61,
                        ["itemName"] = "High Elf Tapestry, Water-Themed",
                        ["qualityName"] = "Superior",
                    },
                    ["|H0:item:126364:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||inventory:kael stormblade"] = 
                    {
                        ["itemLink"] = "|H0:item:126364:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                        ["locationKey"] = "inventory:kael stormblade",
                        ["lastDumpedAt"] = 1776422776,
                        ["count"] = 1,
                        ["sharedFrom"] = "Inventory (Kael Stormblade)",
                        ["bagId"] = 1,
                        ["itemTypeName"] = "Furnishing",
                        ["quality"] = 3,
                        ["traitType"] = 0,
                        ["accountName"] = "@DragonSlayerX",
                        ["furnitureDataId"] = 3439,
                        ["firstDumpedAt"] = 1776422776,
                        ["itemKey"] = "|H0:item:126364:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||inventory:kael stormblade",
                        ["trait"] = "",
                        ["slotIndex"] = 18,
                        ["itemType"] = 61,
                        ["itemName"] = "Dres Tapestry, Vines",
                        ["qualityName"] = "Superior",
                    },
                    ["|H0:item:223157:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||bank"] = 
                    {
                        ["itemLink"] = "|H0:item:223157:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                        ["locationKey"] = "bank",
                        ["lastDumpedAt"] = 1776422975,
                        ["count"] = 2,
                        ["sharedFrom"] = "Bank",
                        ["bagId"] = 2,
                        ["itemTypeName"] = "Furnishing",
                        ["quality"] = 3,
                        ["traitType"] = 0,
                        ["accountName"] = "@DragonSlayerX",
                        ["furnitureDataId"] = 11180,
                        ["firstDumpedAt"] = 1776422975,
                        ["itemKey"] = "|H0:item:223157:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||bank",
                        ["trait"] = "",
                        ["slotIndex"] = 106,
                        ["itemType"] = 61,
                        ["itemName"] = "Worm Cult Bucket, Bismuth Samples",
                        ["qualityName"] = "Superior",
                    },
                    ["|H0:item:144283:359:50:0:0:0:0:0:0:0:0:0:0:0:0:25:0:0:0:0:0|h|h||inventory:kael stormblade"] = 
                    {
                        ["itemLink"] = "|H0:item:144283:359:50:0:0:0:0:0:0:0:0:0:0:0:0:25:0:0:0:0:0|h|h",
                        ["locationKey"] = "inventory:kael stormblade",
                        ["lastDumpedAt"] = 1776422785,
                        ["count"] = 1,
                        ["sharedFrom"] = "Inventory (Kael Stormblade)",
                        ["bagId"] = 1,
                        ["itemTypeName"] = "Apparel",
                        ["quality"] = 2,
                        ["traitType"] = 23,
                        ["accountName"] = "@DragonSlayerX",
                        ["furnitureDataId"] = 0,
                        ["firstDumpedAt"] = 1776422785,
                        ["itemKey"] = "|H0:item:144283:359:50:0:0:0:0:0:0:0:0:0:0:0:0:25:0:0:0:0:0|h|h||inventory:kael stormblade",
                        ["trait"] = "Robust",
                        ["slotIndex"] = 24,
                        ["itemType"] = 2,
                        ["itemName"] = "Battlefield Acrobat Ring",
                        ["qualityName"] = "Fine",
                    },
                }
            }
        }
    }
}
