--[[
ZO_CreateStringId("SI_BINDING_NAME_FCOTM_TOGGLE_1", FCOTM.GetKeybindLocText("SI_BINDING_NAME_FCOTM_TOGGLE_1", true))
ZO_CreateStringId("SI_BINDING_NAME_FCOTM_TOGGLE_2", FCOTM.GetKeybindLocText("SI_BINDING_NAME_FCOTM_TOGGLE_2", true))
ZO_CreateStringId("SI_BINDING_NAME_FCOTM_TOGGLE_3", FCOTM.GetKeybindLocText("SI_BINDING_NAME_FCOTM_TOGGLE_3", true))
ZO_CreateStringId("SI_BINDING_NAME_FCOTM_TOGGLE_4", FCOTM.GetKeybindLocText("SI_BINDING_NAME_FCOTM_TOGGLE_4", true))
ZO_CreateStringId("SI_BINDING_NAME_FCOTM_TOGGLE_5", FCOTM.GetKeybindLocText("SI_BINDING_NAME_FCOTM_TOGGLE_5", true))
ZO_CreateStringId("SI_BINDING_NAME_FCOTM_TOGGLE_6", FCOTM.GetKeybindLocText("SI_BINDING_NAME_FCOTM_TOGGLE_6", true))
ZO_CreateStringId("SI_BINDING_NAME_FCOTM_TOGGLE_7", FCOTM.GetKeybindLocText("SI_BINDING_NAME_FCOTM_TOGGLE_7", true))
ZO_CreateStringId("SI_BINDING_NAME_FCOTM_TOGGLE_8", FCOTM.GetKeybindLocText("SI_BINDING_NAME_FCOTM_TOGGLE_8", true))
]]
ZO_CreateStringId("SI_BINDING_NAME_FCOTM_REMOVE_ALL", FCOTM.GetKeybindLocText("SI_BINDING_NAME_FCOTM_REMOVE_ALL", true))
