FurnishThemAllData_TamrielTomes_SeasonOne = {
    name = "Season One: Return of the Thieves Guild",
    source = "Tamriel Tomes",
    collection = {
        [1] = {
            { name = "Bounty Sheet: Argonian Man" },
            { name = "Bounty Sheet: Breton Man" },
            { name = "Bounty Sheet: Breton Woman" },
            { name = "Bounty Sheet: Colovian Man" },
            { name = "Bounty Sheet: High Elf Man" },
            { name = "Bounty Sheet: Imperial Man" },
            { name = "Bounty Sheet: Khajiit Man" },
            { name = "Bounty Sheet: Orc Man" },
            { name = "Bounty Sheet: Orc Woman" },
            { name = "Completed Bounty Sheet, Framed Breton Man" },
            { name = "Redguard Satchel, Heavy" },
            { name = "Redguard Armchair, Starry" },
            { name = "Redguard Desk, Bolted" },
            { name = "Alinor Jewelry Box, Octagonal" },
            { name = "Solitude Patching Kit, Well-Worn" },
            { name = "Redguard Candleholder, Polished" },
            { name = "Key, Brass" },
            { name = "Papers, Stack" },
            { name = "Common Quill, Feather" },
            { name = "Common Inkwell, Practical" },

            { name = "Pie Dish, Display" },
            { name = "Solitude Platter, Ribs" },
            { name = "Redguard Candelabra, Twisted" },
            { name = "Redguard Table, Game" },
            { name = "Redguard Footstool, Starry" },
            { name = "Redguard Mug, Full" },
            { name = "Tangerines, Bunch" },
            { name = "Bread, Braided" },
            { name = "Solitude Bread, Floral Pattern" },
            { name = "Solitude Bread, Rustic Loaf" },
            { name = "Colovian Meal, Poultry" },
            { name = "Colovian Bowl, Grapes" },
            { name = "Colovian Wine Bottle, Wax Sealed" },
            { name = "Smoked Cheese Wheel, Wax" },
            { name = "Apple, Display" },

            { name = "Pile of Dubious Riches" },
            { name = "Khajiit Statue, Guardian" },
            { name = "Elsweyr Sugar Pipe, Gilded" },
            { name = "Redguard Jar, Oasis" },
            { name = "Redguard Jar, Baroque" },
            { name = "Redguard Trunk, Garish" },
            { name = "Redguard Urn, Wrapped Golden" },
            { name = "Redguard Vessel, Gilded" },
            { name = "Redguard Trunk, Heavy" },
        },
    },
}
